var quiz = [
    

    {
        q: `The maximum excursion of a wave above and below the baseline is known as its:`,
        q2: ``,
        q3: [],
        option: [`wavelength.`, 
        `frequency.`, 
        `period.`, 
        `cycle.`, 
        `amplitude.`],
        optionStyleType: `st-lower-alpha`,
        answer: [4],
        ansText:`Rationale: <!--<b>e. Amplitude.</b>--> In ultrasound physics it is crucial to understand the concept of amplitude. The amplitude of an ultrasound wave represents its relative energy state, and it is the amplitude of the returning sound wave that determines the pixel brightness to be displayed on a monitor during real-time gray-scale imaging.`, 
        state: `notAnswered`,
        userAnswered: []
        ,
        type: `MCSS`},
    {
        q: `The artifact that occurs when an ultrasound wave strikes an interface at a critical angle and is refracted with limited reflection is:`,
        q2: ``,
        q3: [],
        option: [`reverberation artifact.`, 
        `increased through-transmission artifact.`, 
        `edging artifact.`, 
        `comet-tail artifact.`, 
        `aliasing artifact.`],
        optionStyleType: `st-lower-alpha`,
        answer: [2],
        ansText:`Rationale: <!--<b>c. Edging artifact.</b>--> Echo reflection is the primary mechanism whereby sound waves are returned to a transducer. It is important to understand how the angle of insonation affects the reflection and refraction of sound waves. There is a critical angle at which waves will travel along an interface rather than being returned to the probe. When this angle is encountered, it provides a dark or hypoechoic “shadow” called an “edging artifact.” A reverberation artifact is one caused by multiple transits of a sound wave between the transducer and the reflecting object. Increased through-transmission artifact is caused by decreased attenuation of sound waves as they travel through a fluid-filled structure. Comet-tail artifact is seen as the result of the interaction between sound waves and fluid and gas filled structures such as the bowel. Aliasing artifact is seen with Doppler ultrasonography.`, 
        state: `notAnswered`,
        userAnswered: []
        ,
        type: `MCSS`},
    {
        q: `Which ultrasound mode allows for detection and characterization of the velocity and direction of motion?`,
        q2: ``,
        q3: [],
        option: [`Harmonic scanning`, 
        `Color Doppler`, 
        `Power Doppler`, 
        `Spatial compounding`, 
        `Gray-scale ultrasonography`],
        optionStyleType: `st-lower-alpha`,
        answer: [1],
        ansText:`Rationale: <!--<b>b. Color Doppler.</b>--> Doppler ultrasonography is important for evaluating motion and flow. The critical difference between color Doppler and power Doppler is that color Doppler is able to evaluate both flow velocity and direction. Power Doppler evaluates integrated amplitude of the returning sound waves. Although gray-scale ultrasonography does permit the evaluation of motion, it does not permit the characterization of velocity or direction. Harmonic scanning and spatial compounding are modes that allow the selective evaluation or combination of reflected frequencies in ways that improve image quality.`, 
        state: `notAnswered`,
        userAnswered: []
        ,
        type: `MCSS`},
    {
        q: `If the kidney is less echogenic than the liver, the kidney is described as:`,
        q2: ``,
        q3: [],
        option: [`hyperechoic.`, 
        `hypoechoic.`, 
        `isoechoic.`, 
        `anechoic.`, 
        `echogenic.`],
        optionStyleType: `st-lower-alpha`,
        answer: [1],
        ansText:`Rationale: <!--<b>b. Hypoechoic.</b>--> In describing ultrasound images, it is important to use correct terminology. Descriptive terms involving echogenicity are relative terms. A hyperechoic or hypoechoic structure is being described in relation to the echogenicity of a reference standard. In most cases the reference standard is the liver. In the adult the normal kidney is hypoechoic relative to the normal liver in approximately 75% of patients.`, 
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `The sonographic hallmark of testicular torsion is:`,
        q2: ``,
        q3: [],
        option: [`the “blue dot” sign.`, 
        `epididymal edema.`, 
        `paratesticular fluid.`, 
        `increased epididymal blood flow.`, 
        `absence of intratesticular blood flow.`],
        optionStyleType: `st-lower-alpha`,
        answer: [4],
        ansText:`Rationale: <!--<b>e. Absence of intratesticular blood flow.</b>--> The absence of intratesticular blood flow is the classic sonographic finding in testicular torsion. However, there are many documented cases of some preserved intratesticular blood flow even in cases with significant torsion. Therefore testicular torsion remains a clinical diagnosis. Epididymal edema, paratesticular fluid, and increased epididymal blood flow may be seen with testicular torsion but may also be seen with other clinical conditions. The blue dot sign is a classic physical finding in torsion of the appendix testis.`, 
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `Ultrasound waves are examples of:`,
        q2: ``,
        q3: [],
        option: [`radio waves.`, 
        `mechanical waves.`, 
        `electromagnetic waves.`, 
        `ionizing radiation.`, 
        `light waves.`],
        optionStyleType: `st-lower-alpha`,
        answer: [1],
        ansText:`Rationale: <!--<b>b. Mechanical waves:</b>--> Mechanical waves are represented graphically as a sine wave alternating between a positive and negative direction from the baseline. Sound waves as they propagate through human tissue produce areas of returning compression and rarefaction.`, 
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `The most important determinant of axial resolution is:`,
        q2: ``,
        q3: [],
        option: [`impedance.`, 
        `speed of propagation.`, 
        `acoustic power.`, 
        `frequency.`, 
        `number of foci.`],
        optionStyleType: `st-lower-alpha`,
        answer: [3],
        ansText:`Rationale: <!--<b>d. Frequency:</b>--> Axial resolution is directly dependent on the frequency of sound waves. The higher the sound wave’s frequency is, the better the axial resolution.`, 
        state: `notAnswered`,
        userAnswered: []
        ,
        type: `MCSS`},
    {
        q: `Increasing frequency results in a loss of:`,
        q2: ``,
        q3: [],
        option: [`absorption.`, 
        `axial resolution.`, 
        `lateral resolution.`, 
        `depth of penetration.`, 
        `mechanical index.`],
        optionStyleType: `st-lower-alpha`,
        answer: [3],
        ansText:`Rationale: <!--<b>d. Depth of penetration:</b>--> The optimal ultrasound image requires tradeoffs between resolution and depth of penetration. High-frequency transducers of 6 to 10 MHz may be used to image structures near the surface of the body (e.g., testis, pediatric kidney) with excellent resolution. However, deeper structures (e.g., right kidney, bladder) require lower frequencies of 3.5 to 5 MHz to penetrate. Such images will have poorer axial resolution.`, 
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `When sound waves encounter the interface between two tissues with large differences in impedance, the waves are:`,
        q2: ``,
        q3: [],
        option: [`increased in frequency.`, 
        `decreased in frequency.`, 
        `reflected.`, 
        `refracted.`, 
        `reverberated.`],
        optionStyleType: `st-lower-alpha`,
        answer: [2],
        ansText:`Rationale: <!--<b>c. Reflected:</b>--> The shape and size of the object and the angle at which the advancing wave strikes the object are critical determinants of the amount of energy reflected. The amount of energy reflected from an interface is also influenced by the <b>impedance</b> of the two tissues at the interface. Impedance is a property that is influenced by tissue stiffness and density. It is the difference in impedance that allows an appreciation of interfaces between different types of tissue.`, 
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `When a tissue appears darker than the surrounding tissue on ultrasound it is said to be relatively:`,
        q2: ``,
        q3: [],
        option: [`hypoechoic.`, 
        `hyperechoic.`, 
        `hypodense.`, 
        `isoechoic`, 
        `anechoic.`],
        optionStyleType: `st-lower-alpha`,
        answer: [0],
        ansText:`Rationale: <!--<b>a. Hypoechoic:</b>--> The liver is usually used as a benchmark for echogenicity. A hypoechoic area is described as “darker” on B-mode ultrasound.`, 
        state: `notAnswered`,
        userAnswered: []
        ,
        type: `MCSS`},
    {
        q: `The focal zone represents the area of best:`,
        q2: ``,
        q3: [],
        option: [`lateral resolution.`, 
        `axial resolution.`, 
        `echogenicity.`, 
        `blood flow.`, 
        `tissue penetration.`],
        optionStyleType: `st-lower-alpha`,
        answer: [0],
        ansText:`Rationale: <!--<b>a. Lateral resolution:</b>--> Lateral resolution refers to the ability to identify separately objects that are equidistant from the transducer. Lateral resolution is a function of the focused width of the ultrasound beam and is a characteristic of the transducer. The location of the narrowest beam width can be adjusted by the user. The more focused the beam is, the better the lateral resolution at that location. Thus image quality can be enhanced by locating the narrowest beam width (focus or focal zone) at the depth of the object or tissue of interest`, 
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `Increasing the gain has the effect of:`,
        q2: ``,
        q3: [],
        option: [`increasing amplitude of the sound waves.`, 
        `increasing acoustic power.`, 
        `increasing thermal index.`, 
        `increasing mechanical index.`, 
        `increasing transducer sensitivity.`],
        optionStyleType: `st-lower-alpha`,
        answer: [4],
        ansText:`Rationale: The gain control on the console of the ultrasound machine permits the user to increase or decrease the sensitivity of the transducer to reflected sound waves.`, 
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `One way to improve the visualization of deep structures is to:`,
        q2: ``,
        q3: [],
        option: [`increase the frequency.`, 
        `decrease the frequency.`, 
        `increase the wave velocity.`, 
        `decrease the gain.`, 
        `employ Doppler flow.`],
        optionStyleType: `st-lower-alpha`,
        answer: [1],
        ansText:`Rationale: <!--<b>b. Decrease the frequency:</b>--> The optimal ultrasound image requires trade-offs between resolution and depth of penetration. High-frequency transducers of 6 to 10 MHz may be used to image structures near the surface of the body (e.g., testis, pediatric kidney), with excellent resolution. However, deeper structures (e.g., right kidney, bladder) require lower frequencies of 3.5 to 5 MHz to penetrate. Such images will have poorer axial resolution.`, 
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `The best frequency for performing external renal ultrasound in most adults is:`,
        q2: ``,
        q3: [],
        option: [`3.5 to 5 MHz.`, 
        `6 to 7 MHz.`, 
        `7.5 to 8.4 MHz.`, 
        `8.5 to 9.9 MHz.`, 
        `None of the above.`],
        optionStyleType: `st-lower-alpha`,
        answer: [0],
        ansText:`Rationale: <!--<b>a. 3.5 to 5 MHz:</b>--> Deeper structures (e.g., right kidney, bladder) require lower frequencies of 3.5 to 5 MHz to penetrate.`, 
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `A simple cyst of the kidney would not display which of the following characteristics?`,
        q2: ``,
        q3: [],
        option: [`Bright back wall`, 
        `Increased through transmission`, 
        `Anechoic interior`, 
        `Edging artifact`, 
        `Hyperechoic internal nodule`],
        optionStyleType: `st-lower-alpha`,
        answer: [4],
        ansText:`Rationale: <!--<b>e. Hyperechoic internal nodule:</b>--> A simple cyst is an example of a structure that is well circumscribed, with an anechoic interior and through transmission.`, 
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `Which of the following is correct?`,
        q2: ``,
        q3: [],
        option: [`Measuring bladder volume requires three-dimensional scanning.`, 
        `A nearly empty bladder is desirable for bladder scanning.`, 
        `A curved array transducer is preferred for bladder ultrasound in most patients.`, 
        `Ureteroceles are usually poorly visualized because the membrane is thin.`, 
        `Bladder ultrasound is a sensitive screening exam for suspected bladder tumors.`],
        optionStyleType: `st-lower-alpha`,
        answer: [2],
        ansText:`Rationale: <!--<b>c. A curved array transducer is preferred for bladder ultrasound in most patients:</b>--> A curved array transducer is of lower frequency (3.5–6 MHz) and provides greater depth of penetration but with less axial resolution. It is most often the transducer of choice for imaging the kidney and urinary bladder.`, 
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `Which of the following are evaluable by transabdominal bladder ultrasound?`,
        q2: ``,
        q3: [],
        option: [`Urine volume`, 
        `Bladder wall characteristics`, 
        `Stones or diverticulum`, 
        `Dilated ureters`, 
        `All of the above`],
        optionStyleType: `st-lower-alpha`,
        answer: [4],
        ansText:`Rationale: <!--<b>e. All of the above:</b>--> Urine volume, bladder wall characteristics, the presence of calculi or diverticulum, and the presence of dilated ureters just outside the bladder are all evaluable by transabdominal bladder ultrasound.`, 
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `Scrotal ultrasound for the evaluation of possible testicular torsion may include all of the following but must include:`,
        q2: ``,
        q3: [],
        option: [`B-mode ultrasound.`, 
        `multiple scrotal views.`, 
        `Doppler flow studies.`, 
        `simultaneous bilateral views.`, 
        `harmonic scanning.`],
        optionStyleType: `st-lower-alpha`,
        answer: [2],
        ansText:`Rationale: <!--<b>c. Doppler flow studies:</b>--> Caution should be used when interpreting Doppler flow studies in the evaluation of suspected testicular torsion. The hallmark of testicular torsion is the absence of <b>intratesticular</b> blood flow. Paratesticular flow in epididymal collaterals may appear within hours of torsion. Comparison with the contralateral testis should be performed to ensure that the technical attributes of the study are adequate to demonstrate intratesticular blood flow.`, 
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `The most important limitation of ultrasound in attempting to characterize complex renal cysts as benign or malignant is:`,
        q2: ``,
        q3: [],
        option: [`refraction.`, 
        `inability to evaluate enhancement.`, 
        `lack of axial resolution.`, 
        `increased through-transmission with artifact.`, 
        `reverberation artifact.`],
        optionStyleType: `st-lower-alpha`,
        answer: [1],
        ansText:`Rationale: <!--<b>b. Inability to evaluate enhancement:</b>--> Unlike computed tomography (CT), currently ultrasound cannot evaluate enhancement. Once it is approved by the US Food and Drug Administration (FDA) for this purpose, contrast-enhanced ultrasound will allow the detection of enhancement of renal masses by ultrasound.`, 
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `A complete transrectal ultrasound of the prostate should include an evaluation of:`,
        q2: ``,
        q3: [],
        option: [`rectal wall.`, 
        `seminal vesicles and ejaculatory ducts.`, 
        `bladder.`, 
        `prostate.`, 
        `all of the above.`],
        optionStyleType: `st-lower-alpha`,
        answer: [4],
        ansText:`Rationale: <!--<b>e. All of the above:</b>--> When evaluating the prostate, surrounding structures need to be assessed. Rectal lesions (including cancer), dilated seminal vesicles, and/or ejaculatory ducts as well as bladder pathology should all be evaluated for a complete examination.`, 
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `Which of the following would not typically be visible in a sagittal midline prostate ultrasound?`,
        q2: ``,
        q3: [],
        option: [`Middle lobe of the prostate`, 
        `Central zone`, 
        `Ejaculatory duct`, 
        `Tip of right seminal vesicle`, 
        `Apex of the prostate`],
        optionStyleType: `st-lower-alpha`,
        answer: [3],
        ansText:`Rationale: <!--<b>d. Tip of right seminal vesicle:</b>--> In a midline sagittal view the tips of the seminal vesicles are not normally visualized on ultrasound. An axial projection needs to be obtained to be able to measure the length of each seminal vesicle.`, 
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `Characteristics of prostate cancer as demonstrated on transrectal ultrasound of the prostate may include:`,
        q2: ``,
        q3: [],
        option: [`hypoechogenicity.`, 
        `hyperechogenicity.`, 
        `prostate asymmetry.`, 
        `increased vascularity.`, 
        `all of the above.`],
        optionStyleType: `st-lower-alpha`,
        answer: [4],
        ansText:`Rationale: <!--<b>e. All of the above:</b>--> Although excellent resolution and tissue characteristics is possible with transrectal ultrasound a diagnosis of prostate cancer is not often able to be made with ultrasound alone.`, 
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `The single most important determinant of patient safety in ultrasound utilization is:`,
        q2: ``,
        q3: [],
        option: [`multifrequency probes.`, 
        `good documentation.`, 
        `an informed operator.`, 
        `periodic equipment inspection.`, 
        `Doppler capability.`],
        optionStyleType: `st-lower-alpha`,
        answer: [2],
        ansText:`Rationale: <!--<b>c. An informed operator:</b>--> The ALARA (as low as reasonably achievable) principle is intended to limit the total energy imparted to the patient during an examination. This can be accomplished by (1) keeping power outputs low, (2) using appropriate scanning modes, (3) limiting examination times, (4) adjusting focus and frequency, and (5) using the cine function during documentation. All of these are dependent upon an informed sonographer.`, 
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `The disinfection level protocol required for transrectal ultrasound probes following needle biopsy is:`,
        q2: ``,
        q3: [],
        option: [`low.`, 
        `moderate.`, 
        `high.`, 
        `critical.`, 
        `none of the above.`],
        optionStyleType: `st-lower-alpha`,
        answer: [3],
        ansText:`Rationale: <!--<b>d. Critical:</b>--> Any time body fluids or tissues come in contact with an ultrasound transducer, critical or high-level disinfection protocols must be strictly adhered to.`, 
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `For patient safety it is preferable to maximize and limit:`,
        q2: ``,
        q3: [],
        option: [`acoustic power, exam duration.`, 
        `acoustic power, gain.`, 
        `gain, acoustic power.`, 
        `gain, use of cine function.`, 
        `images, description.`],
        optionStyleType: `st-lower-alpha`,
        answer: [2],
        ansText:`Rationale: <!--<b>c. Gain, acoustic power:</b>--> Unlike gain, which refers to amplification of the acoustic signal returning to the transducer, acoustic power is the amount of acoustic energy applied to the tissue. The biologic effects of ultrasound in terms of power are in the milliwatt range. High levels generate heat and cavitation, which might result in tissue damage.`, 
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`}



];
