var quiz = [
    

    {
        q: `When assessing disease-specific mortality, researchers need to be aware that this outcome is subject to:`,
        q2: ``,
        q3: [],
        option: [`detection bias.`, 
        `attribution bias.`, 
        `problems with loss to follow-up.`, 
        `all of the above.`, 
        `b and c.`],
        optionStyleType: `st-lower-alpha`,
        answer: [4],
        ansText:`Rationale: <!--<b>e. b and c.</b>--> When assessing disease-specific mortality, researchers need to be aware that this outcome is subject to attribution bias and problems with loss to follow-up.`, 
        state: `notAnswered`,
        userAnswered: []
        ,
        type: `MCSS`},
    {
        q: `Which of the following is NOT one of the four requirements for a valid surrogate endpoint as described by Prentice?`,
        q2: ``,
        q3: [],
        option: [`Treatment is associated with the true endpoint.`, 
        `The surrogate endpoint is associated with the true endpoint.`, 
        `The full effect of treatment on the true endpoint is explained by the surrogate endpoint.`, 
        `The surrogate endpoint can reliably be measured using highly objective methods.`, 
        `Treatment is also associated with the surrogate endpoint.`],
        optionStyleType: `st-lower-alpha`,
        answer: [3],
        ansText:`Rationale: <!--<b>d. The surrogate endpoint can reliably be measured using highly objective methods.</b>--> It is not a requirement for a valid surrogate endpoint that it can reliably be measured using highly objective methods.`, 
        state: `notAnswered`,
        userAnswered: []
        ,
        type: `MCSS`},
    {
        q: `With regard to patient-centered outcomes:`,
        q2: ``,
        q3: [],
        option: [`clinicians can reliably assess these outcomes from the doctor–patient interaction.`, 
        `there are very few validated and reliable questionnaires available for use in urology.`, 
        `health-related quality of life is an important outcome to measure, but only function need be assessed to get a full portrait of this outcome.`, 
        `patient-centered questionnaires are developed using the principles of psychometric test theory.`, 
        `none of the above.`],
        optionStyleType: `st-lower-alpha`,
        answer: [3],
        ansText:`Rationale: <!--<b>d. Patient-centered questionnaires are developed using the principles of psychometric test theory.</b>--> For patient-centered outcomes, patient-centered questionnaires are developed using the principles of psychometric test theory.`, 
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `Which of the following methods has not been suggested as a technique to assess patient experience of pain?`,
        q2: ``,
        q3: [],
        option: [`Collect verbal or written descriptions of the pain`, 
        `Query patient’s caregiver regarding patient’s pain level.`, 
        `Have subject rate pain via its effect on observable behavior.`, 
        `Use analogue techniques in which the patient compares his/her pain with an experimentally induced stimulus of a known intensity in a laboratory setting.`, 
        `All of the above can be used to assess pain levels.`],
        optionStyleType: `st-lower-alpha`,
        answer: [4],
        ansText:`Rationale: <!--<b>e. All of the above can be used to assess pain levels.</b>--> Collecting verbal or written descriptions of the pain; querying the patient’s caregiver regarding the patient’s pain level; having the subject rate pain via its effect on observable behavior; and using analogue techniques in which the patient compares his/her pain with an experimentally induced stimulus of a known intensity in a laboratory setting are all methods to assess patient pain.`, 
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `When a scale has a coefficient α of 0.90, one can be assured that the scale has high degree of:`,
        q2: ``,
        q3: [],
        option: [`alternate form reliability.`, 
        `test-retest reliability.`, 
        `internal consistency reliability.`, 
        `intraobserver reliability.`, 
        `interobserver reliability.`],
        optionStyleType: `st-lower-alpha`,
        answer: [2],
        ansText:`Rationale: <!--<b>c. Internal consistency reliability.</b>--> When a scale has a coefficient alpha of 0.90, the scale has a high degree of internal consistency reliability.`, 
        state: `notAnswered`,
        userAnswered: []
        ,
        type: `MCSS`},
    {
        q: `If a urologist were designing an instrument to measure cancer-specific quality of life following prostatectomy, how would she design an experiment to assess test-retest reliability?`,
        q2: ``,
        q3: [],
        option: [`She could administer the questionnaire before and after the operation.`, 
        `She could administer the questionnaire to her patients and a group of age-matched healthy controls.`, 
        `She could use a differently worded questionnaire to obtain the same information.`, 
        `She could administer the questionnaire to the same patient twice in the same week and compare the results.`, 
        `She could administer the questionnaire to the same patient twice at an interval of one year and compare the results.`],
        optionStyleType: `st-lower-alpha`,
        answer: [3],
        ansText:`Rationale: <!--<b>d. She could administer the questionnaire to the same patient twice in the same week and compare the results.</b>--> A urologist wishing to measure cancer-specific quality of life following prostatectomy could design an experiment to assess test-retest reliability by administering the questionnaire to the same patient twice in the same week and comparing the results.`, 
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `Of the following types of validity, which one often takes many years of instrument use by numerous investigators to adequately assess?`,
        q2: ``,
        q3: [],
        option: [`Face validity`, 
        `Content validity`, 
        `Concurrent validity`, 
        `Predictive validity`, 
        `Construct validity`],
        optionStyleType: `st-lower-alpha`,
        answer: [4],
        ansText:`Rationale: <!--<b>e. Construct validity.</b>--> Construct validity often takes many years of instrument use by numerous investigators to adequately assess.`, 
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `The use of uroflow results in validating a new survey instrument that measures disease-specific HRQOL in benign prostatic hyperplasia (BPH) patients is an example of:`,
        q2: ``,
        q3: [],
        option: [`concurrent validity.`, 
        `content validity.`, 
        `construct validity.`, 
        `predictive validity.`, 
        `face validity.`],
        optionStyleType: `st-lower-alpha`,
        answer: [0],
        ansText:`Rationale: The use of uroflow results in validating a new survey instrument that measures disease-specific HRQOL in BPH patients is an example of concurrent validity.`, 
        state: `notAnswered`,
        userAnswered: []
        ,
        type: `MCSS`},
    {
        q: `A patient undergoes a radical cystectomy. On post-operative day #2, he aspirates and requires emergent intubation and transfer to the ICU. He is started on intravenous antibiotics and is extubated on post-operative day #4. The remainder of his hospital course in unremarkable and he is discharged on post-operative day #8. The complication he experienced is a Clavien-Dindo grade:`,
        q2: ``,
        q3: [],
        option: [`II.`, 
        `IIIa.`, 
        `IIIb.`, 
        `IVa.`, 
        `IVb.`],
        optionStyleType: `st-lower-alpha`,
        answer: [3],
        ansText:`Rationale: <!--<b>d. IVa.</b>--> The patient’s complication is Clavien-Dindo grade IVa.`, 
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `A patient with kidney cancer has a single target lesion, a 5-cm bony metastases. She is treated with a tyrosine kinase inhibitor (TKI). The lesion is reduced in size and is now 4 cm on imaging. According to the RECIST criteria, this is considered a:`,
        q2: ``,
        q3: [],
        option: [`complete response.`, 
        `partial response.`, 
        `stable disease.`, 
        `non-CR/non-PD.`, 
        `progressive disease.`],
        optionStyleType: `st-lower-alpha`,
        answer: [2],
        ansText:`Rationale: <!--<b>c. Stable disease.</b>--> This is considered stable disease per RECIST criteria.`, 
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`}



];
