var quiz = [
    

    {
        q: `Which of the following is not considered an indication for an open abdominal approach (as opposed to minimally invasive)?`,
        q2: ``,
        q3: [],
        option: [`Multiple prior abdominal surgeries`, 
        `Complex renal mass with caval thrombus`, 
        `Previous abdominal hernia repair with mesh`, 
        `Patient with multiple comorbidities`, 
        `Surgeon’s preference and experience`],
        optionStyleType: `st-lower-alpha`,
        answer: [3],
        ansText:`Rationale: <!--<b>d. Patient with multiple comorbidities.</b>--> With an aging and more complex population, having multiple comorbidities on its own is not an indication for open surgery compared to minimally invasive surgery. Answers a, b, c, and e are all considered relative indications for open surgery. Patients with multiple previous abdominal procedures are more likely to have adhesions and difficulties establishing a pneumoperitoneum. Complicated renal tumors with caval thrombi, although possible to do laparoscopically, should be considered for open surgery. A large abdominal wall mesh could significantly complicate a minimally invasive approach, and surgeon skill and preference is another important consideration for an open approach.`, 
        state: `notAnswered`,
        userAnswered: []
        ,
        type: `MCSS`},
    {
        q: `Following a motor vehicle crash (MVC), a 35-year-old male is found to have a significant right-sided renal hilar injury on imaging. He becomes hemodynamically unstable, despite intravenous fluid resuscitation and massive transfusion protocol. The decision is made to take him to the OR. What incision should you use?`,
        q2: ``,
        q3: [],
        option: [`Flank incision`, 
        `Complete midline incision`, 
        `Chevron incision`, 
        `Subcostal incision`, 
        `Thoracoabdominal incision`],
        optionStyleType: `st-lower-alpha`,
        answer: [1],
        ansText:`Rationale: <!--<b>b. Complete midline incision.</b>--> Trauma nephrectomies should always be approached with a laparotomy or complete midline incision. The other approaches would not be appropriate in this clinical setting.`, 
        state: `notAnswered`,
        userAnswered: []
        ,
        type: `MCSS`},
    {
        q: `Which approach of abdominal wall fascial closure has been shown to have a higher rate of abdominal wall hernias?`,
        q2: ``,
        q3: [],
        option: [`Rapidly absorbable suture, running continuous closure`, 
        `Rapidly absorbable suture, interrupted closure`, 
        `Slowly absorbable suture, running continuous closure`, 
        `Slowly absorbable suture, interrupted closure`],
        optionStyleType: `st-lower-alpha`,
        answer: [0],
        ansText:`Rationale: <!--<b>a. Rapidly absorbable suture, running continuous closure.</b>--> In a 2002 meta-analysis of closure techniques for midline abdominal incisions, Riet et al. found that continuous rapidly absorbable sutures had significantly more incisional hernias than slowly absorbable or non-absorbable sutures. No difference in hernia rates between slowly absorbable and non-absorbable sutures. (Reference: van ‘t Riet M, Steyerberg EW, Nellensteyn J, Bonjer HJ, Jeekel J: Meta-analysis of techniques for closure of midline abdominal incisions. <b><i>Br J Surg</i></b> 89:1350–1356, 2002.)`, 
        state: `notAnswered`,
        userAnswered: []
        ,
        type: `MCSS`},
    {
        q: `A 25-year-old patient has been cleared to donate her left kidney to her cousin who recently was started on dialysis for end-stage renal disease. She is seeing you for pre-surgical consultation. You inform her you will be performing the nephrectomy laparoscopically and will be extracting the kidney through ___________ because this has been shown to have _________.`,
        q2: ``,
        q3: [],
        option: [`extension of the inferior port site; lower morbidity and incisional hernia rates`, 
        `extension of the midline port site; decreased pain scores and complications`, 
        `pfannenstiel incision; lower morbidity and incisional hernia rates`, 
        `pfannenstiel incision; decreased pain scores and complications`, 
        `extension of the superior most port site; decreased pain scores and complications`],
        optionStyleType: `st-lower-alpha`,
        answer: [2],
        ansText:`Rationale: <!--<b>c. Pfannenstiel incision; lower morbidity and incisional hernia rates.</b>--> A prospective study comparing Pfannenstiel incision versus port site expansion for nephrectomies showed that morbidity and length of stay were shorter in the pfannensteil group, while a meta-analysis for extractions in laparoscopic bowel surgery showed lower hernia rates with pfannensteil. (References: Binsaleh S, Madbouly K, Matsumoto ED, Kapoor A:<sup>.</sup> a prospective randomized study of pfannenstiel versus expanded port site incision for intact specimen extraction in laparoscopic radical nephrectomy. <b><i>J Endourol</i></b> 29[8]:913–918, 2015; Lee L, Abou-Khalil M, Liberman S, Boutros M, Fried GM, Feldman LS: Incidence of incisional hernia in the specimen extraction site for laparoscopic colorectal surgery: systematic review and meta-analysis. <b><i>Surg Endosc</i></b> 31[12]:5083–5093, 2017)`, 
        state: `notAnswered`,
        userAnswered: []
        ,
        type: `MCSS`},
    {
        q: `A 45-year-old female had deceased donor renal transplant placed 5 years ago. She has been noncompliant with immunosuppressive medications and the allograft has failed. She has developed peri-allograft abscess, and the allograft must be removed. Which incision is best for renal allograft nephrectomy?`,
        q2: ``,
        q3: [],
        option: [`Lower midline`, 
        `Inguinal incision`, 
        `Subcostal incision`, 
        `Gibson incision`, 
        `Flank incision`],
        optionStyleType: `st-lower-alpha`,
        answer: [3],
        ansText:`Rationale: <!--<b>d. Gibson incision.</b>--> Renal transplants and renal allograft nephrectomies are performed through a traditional Gibson incision, which gives extraperitoneal access to the iliac vessels and bladder.`, 
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `Which incision is rarely used due to high risk of nerve injuries and ventral hernias?`,
        q2: ``,
        q3: [],
        option: [`Midline incision`, 
        `Paramedian incision`, 
        `Thoraco-abdominal incision`, 
        `Pfannenstiel incision`, 
        `Gibson incision`],
        optionStyleType: `st-lower-alpha`,
        answer: [1],
        ansText:`Rationale: <!--<b>b. Paramedian incision.</b>--> Paramedian incisions have been described as an extra-peritoneal approach to nephroureterectomies and pediatric bladder augmentations. They are lateral to the rectus and are rarely used due to risks of nerve injury and ventral hernias.`, 
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `Which of the following is NOT an advantage of the thoracoabdominal incision as an approach to large renal tumors?`,
        q2: ``,
        q3: [],
        option: [`Exposure of adjacent thorax`, 
        `Exposure of retroperitoneum`, 
        `Early vascular control`, 
        `Large incision`, 
        `Access to inferior vena cava (IVC) for advanced disease/caval thrombus`],
        optionStyleType: `st-lower-alpha`,
        answer: [3],
        ansText:`Rationale: <!--<b>d. Large incision.</b>--> The thoracoabdominal incision, although considered to be a large invasive incision, provides the added benefit of significantly improved exposure, ability to achieve early vascular control, and access to major vessels (including the IVC) and organs for advanced renal tumors.`, 
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `Which is the second muscle layer incised in a typical flank incision?`,
        q2: ``,
        q3: [],
        option: [`External oblique`, 
        `Internal oblique`, 
        `Serratus anterior`, 
        `Latissimus dorsi`, 
        `Transversalis`],
        optionStyleType: `st-lower-alpha`,
        answer: [1],
        ansText:`Rationale: <!--<b>b. Internal oblique.</b>--> The muscle and fascial layers encountered in a traditional flank incision, from skin to abdomen, are the external oblique, internal oblique, and transversalis muscles.`, 
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `Which of the following is not considered a true flank incision approach?`,
        q2: ``,
        q3: [],
        option: [`12th rib supracostal`, 
        `11th rib transcostal`, 
        `Subcostal`, 
        `9th rib supracostal`],
        optionStyleType: `st-lower-alpha`,
        answer: [3],
        ansText:`Rationale: <!--<b>d. 9th rib supracostal.</b>--> True flank incisions include the 12th rib supracostal, 11th rib transcostal, and subcostal approaches. Going above this level is often in the context of a thoraco-abdominal incision rather than a true flank incision.`, 
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `Which nerve must be carefully handled to avoid injury during surgery in the inguinal canal?`,
        q2: ``,
        q3: [],
        option: [`Femoral nerve`, 
        `Sciatic nerve`, 
        `Genitofemoral nerve`, 
        `Ilioinguinal nerve`, 
        `Lateral femoral cutaneous nerve`],
        optionStyleType: `st-lower-alpha`,
        answer: [3],
        ansText:`Rationale: <!--<b>d. Ilioinguinal nerve.</b>--> The ilioinguinal nerve runs in the inguinal canal alongside the spermatic cord and should be identified upon opening and closure of an inguinal incision above the inguinal ligament. The genital branch of the genitofemoral nerve is present with the cord structures but is not exposed in the inguinal canal. The other nerves listed do not run through the inguinal canal.`, 
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `Which incision was used for the first-ever planned nephrectomy?`,
        q2: ``,
        q3: [],
        option: [`Thoracoabdominal incision`, 
        `Flank incision`, 
        `Posterior lumbodorsal incision`, 
        `Subcostal incision`, 
        `Gibson incision`],
        optionStyleType: `st-lower-alpha`,
        answer: [2],
        ansText:`Rationale: <!--<b>c. Posterior lumbodorsal incision.</b>--> The first-ever planned nephrectomy was performed in 1870 through a posterior lumbodorsal incision by Simon. This incision had multiple benefits over other open approaches. These include lack of muscle or rib distortion, faster convalescence, and decreased intra-peritoneal complications.`, 
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `Which are NOT considered benefits of the dorsal lumbotomy approach compared to flank incisions?`,
        q2: ``,
        q3: [],
        option: [`Rib and muscle sparing`, 
        `Less postoperative pain`, 
        `Decreased hospitalization`, 
        `Better surgical exposure for vascular control`, 
        `Decreased intra-peritoneal complications`],
        optionStyleType: `st-lower-alpha`,
        answer: [3],
        ansText:`Rationale: <!--<b>d. Better surgical exposure for vascular control.</b>--> The dorsal lumbotomy approach, although not as common now, did boast multiple advantages over subcostal or anterior abdominal approaches. These include faster convalescence, less pain, less musculoskeletal complications (flank bulge), decreased hospitalization, and less intra-peritoneal complications. The major disadvantage was limited surgical exposure to the renal hilum and vessels for vascular control.`, 
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `Which of the following is NOT a border of the lumbodorsal region?`,
        q2: ``,
        q3: [],
        option: [`12th rib–superiorly`, 
        `Quadratus lumborum–inferiorly`, 
        `Spinal processes–medially`, 
        `Iliac crest–inferiorly`, 
        `Line between anterior superior iliac spine (ASIS) and costal margin–laterally`],
        optionStyleType: `st-lower-alpha`,
        answer: [1],
        ansText:`Rationale: <!--<b>b. Quadratus lumborum–inferiorly.</b>--> The borders of the lumbodorsal region are the 12th rib superiorly, iliac crest inferiorly, spinous processes of vertebral columns medially, and a line between the ASIS (anterior superior iliac spine) and costal margin laterally. The incision is generally made directly over the quadratus lumborum, but it is not a border of this region.`, 
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `Which superficial muscles are NOT encountered during a dorsal lumbotomy approach?`,
        q2: ``,
        q3: [],
        option: [`Internal oblique`, 
        `External oblique`, 
        `Latissimus dorsi`, 
        `Sacrospinalis`, 
        `Quadratus lumborom`],
        optionStyleType: `st-lower-alpha`,
        answer: [0],
        ansText:`Rationale: <!--<b>a. Internal oblique.</b>--> The superficial muscles encountered are the sacrospinalis (medially), latissimus dorsi (posteriorly), and external oblique (anteriorly). The incision is deepened through the lumbodorsal fascia where the sacrospinalis muscle is encountered and a “Y” should be made around it (<a class="lightboxcallout" img-ref="image_fig_9_1" href="8b7acd46354f41b1b79dbb982fe2b73d">Fig. 9.1</a>). The incision is made directly over the quadratus lumborum muscle over the lateral part of the sacrospinalis muscle slightly obliquely toward the iliac crest or sacroiliac joint. The internal oblique muscle is not encountered during this incision.`, 
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`}



];
