var quiz = [
    

    {
        q: `The measure of the potential adverse health effects of ionizing radiation in sieverts (Sv) is known as:`,
        q2: ``,
        q3: [],
        option: [`radiation exposure.`, 
        `absorbed dose.`, 
        `equivalent dose.`, 
        `effective dose.`, 
        `relative radiation levels.`],
        optionStyleType: `st-lower-alpha`,
        answer: [3],
        ansText:`Rationale: <!--<b>d. Effective dose.</b>--> The distribution of energy absorption in the human body will be different based on the body part being imaged and a variety of other factors. The most important risk of radiation exposure from diagnostic imaging is the development of cancer. <b>The effective dose is a quantity used to denote the radiation risk (expressed in sieverts) to a population of patients from an imaging study.</b>`, 
        state: `notAnswered`,
        userAnswered: []
        ,
        type: `MCSS`},
    {
        q: `The relative radiation level associated with abdominal computed tomography (CT) without and with contrast is:`,
        q2: ``,
        q3: [],
        option: [`none.`, 
        `minimal, less than 0.1 mSv.`, 
        `low, 0.1 to 1.0 mSv.`, 
        `moderate, 1 to 10 mSv.`, 
        `high, 10 to 100 mSv.`],
        optionStyleType: `st-lower-alpha`,
        answer: [4],
        ansText:`Rationale: <!--<b>e. High, 10 to 100 mSv.</b>--> The average person living in the United States is exposed to 6.2 mSv of radiation per year from ambient sources, such as radon, cosmic rays, and medical procedures, which account for 36% of the annual radiation exposure (NCRP, 2012). <b>The recommended occupational exposure limit to medical personnel is 50 mSv per year</b> (NCRP, 2012). The effective dose from a three-phase CT of the abdomen and pelvis without and with contrast may be as high as 25 to 40 mSv.`, 
        state: `notAnswered`,
        userAnswered: []
        ,
        type: `MCSS`},
    {
        q: `Bladder filling may precipitate autonomic dysreflexia in patients with a spinal cord injury above:`,
        q2: ``,
        q3: [],
        option: [`S2.`, 
        `L4.`, 
        `T10.`, 
        `T12.`, 
        `T6.`],
        optionStyleType: `st-lower-alpha`,
        answer: [4],
        ansText:`Rationale: <!--<b>e. T6.</b>--> Autonomic dysreflexia, also known as hyperreflexia, means an overactivity of the autonomic nervous system that can result in an abrupt onset of excessively high blood pressure. Persons at risk for this problem generally have spinal cord injury level above T6. Autonomic dysreflexia can develop suddenly, is potentially life threatening, and is considered a medical emergency. If not treated promptly and correctly, it may lead to seizures, stroke, and even death.`, 
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `Radiation exposure diminishes as the square of the distance from the radiation source. An exposure of 9 mSv at 1 foot from the source would be how much at 3 feet from the source?`,
        q2: ``,
        q3: [],
        option: [`0.09 mSv`, 
        `1 mSv`, 
        `3 mSv`, 
        `9 mSv`, 
        `27 mSv`],
        optionStyleType: `st-lower-alpha`,
        answer: [1],
        ansText:`Rationale: <!--<b>b. 1 mSv.</b>--> Maintaining the maximum practical distance from an active radiation source significantly decreases exposure to medical personnel.`, 
        state: `notAnswered`,
        userAnswered: []
        ,
        type: `MCSS`},
    {
        q: `Type 2 diabetics on oral metformin biguanide hyperglycemic therapy are at risk for biguanide lactic acidosis after exposure to intravascular radiologic contrast media if they:`,
        q2: ``,
        q3: [],
        option: [`discontinue metformin 48 hours before the study.`, 
        `have severe renal insufficiency and take metformin the day of the study.`, 
        `are given a saline injection while taking metformin.`, 
        `have normal kidney function and fail to stop metformin 48 hours before the study.`, 
        `decrease metformin dose and increase other antihyperglycemic agents on the day of the study.`],
        optionStyleType: `st-lower-alpha`,
        answer: [1],
        ansText:`Rationale: <!--<b>b. Have severe renal insufficiency and take metformin the day of the study.</b>--> Patients with type 2 diabetes mellitus on metformin may have an accumulation of the drug after administering intravascular radiologic contrast medium (IRCM), resulting in biguanide lactic acidosis presenting with vomiting, diarrhea, and somnolence. This condition is fatal in approximately 50% of cases (Wiholm, 1993).<sup>a</sup> <b>Biguanide lactic acidosis is rare in patients with normal renal function. Consequently in patients with normal renal function and no known comorbidities, there is no need to discontinue metformin before IRCM use, nor is there a need to check creatinine following the imaging study.</b><br/><br/><b>a</b> Sources referenced can be found in <i>Campbell-Walsh Urology, 12th Edition,</i> on the Expert Consult website.`, 
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `All of the following are true EXCEPT:`,
        q2: ``,
        q3: [],
        option: [`Patients with a history of asthma are at greater risk of having an adverse reaction to contrast media.`, 
        `Severe allergic reactions are not dose dependent.`, 
        `Hyperosmolar contrast media are more likely to cause contrast reactions than are iso-osmolar agents.`, 
        `The mechanism of action associated with severe idiosyncratic anaphylactoid (IA) reactions is an immunoglobulin E (IgE) antibody reaction to the contrast media.`, 
        `Severe cardiac disease is a risk factor for an adverse reaction to contrast media.`],
        optionStyleType: `st-lower-alpha`,
        answer: [3],
        ansText:`Rationale: <!--<b>d. The mechanism of action associated with severe idiosyncratic anaphylactoid (IA) reactions is an immunoglobulin E (IgE) antibody reaction to the contrast media.</b>--> The IA reactions are most concerning because they are potentially fatal and can occur without any predictable or predisposing factors. <b>Approximately 85% of IA reactions occur during or immediately after injection of IRCM and are more common in patients with a prior adverse drug reaction to contrast media; patients with asthma, diabetes, impaired renal function, or diminished cardiac function; and patients on beta-adrenergic blockers</b> (Spring et&#160;al., 1997).`, 
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `After rapidly assessing airway, breathing, and circulation, the medical treatment of choice for a severe, life-threatening adverse drug reaction following exposure to contrast media is:`,
        q2: ``,
        q3: [],
        option: [`subcutaneous injection of epinephrine 0.5 mg of 1:10,000 epinephrine.`, 
        `intravenous injection of 100 mg of methylprednisone.`, 
        `0.01 mg/kg of epinephrine (1:10,000 concentration), given intramuscularly in the lateral thigh.`, 
        `intravenous diphenhydramine, 50 mg.`, 
        `0.01 mg/kg of epinephrine (1:1000 concentration), given intramuscularly in the lateral thigh.`],
        optionStyleType: `st-lower-alpha`,
        answer: [4],
        ansText:`Rationale: <!--<b>e. 0.01 mg/kg of epinephrine (1:1000 concentration), given intramuscularly in the lateral thigh.</b>--> Rapid administration of epinephrine is the treatment of choice for severe contrast reactions. Epinephrine can be administered intravenously (IV) 0.01 mg/kg body weight of 1: 10,000 dilution or 0.1 mL/kg slowly into a running IV infusion of saline and can be repeated every 5 to 15 minutes as needed. If no IV access is available, the recommended intramuscular dose of epinephrine is 0.01 mg/kg of 1:1000 dilution (or 0.01 mL/kg to a maximum of 0.15 mg of 1:1000 if body weight is &lt;30 kg; 0.3 mg if weight is &gt;30 kg) injected intramuscularly in the lateral thigh.`, 
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `Which of the following is NOT a risk factor for developing contrast-induced nephropathy (CIN)?`,
        q2: ``,
        q3: [],
        option: [`Type 2 diabetes mellitus`, 
        `Dehydration`, 
        `Hypertension`, 
        `Ventricular ejection fraction less than 50%`, 
        `Chronic kidney disease (CKD) (glomerular filtration rate [GFR] &lt; 60 mL/min)`],
        optionStyleType: `st-lower-alpha`,
        answer: [3],
        ansText:`Rationale: <!--<b>d. Ventricular ejection fraction less than 50%.</b>--> The most common patient-related risk factors for CIN are CKD (creatinine clearance &lt;60 mL/min), diabetes mellitus, dehydration, diuretic use, advanced age, congestive heart failure, age, hypertension, low hematocrit, and ventricular ejection fraction less than 40%. <b>The patients at highest risk for developing CIN are those with both diabetes and preexisting renal insufficiency.</b>`, 
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `Nephrogenic systemic fibrosis (NSF) is:`,
        q2: ``,
        q3: [],
        option: [`a rare genetic condition exacerbated by the use of gadolinium-based contrast medium (GBCM).`, 
        `immediately evident after exposure to gadolinium in 10% of exposed patients.`, 
        `fibrosis of the skin, subcutaneous tissue, and skeletal muscle seen in patients with chronic hypertension exposed to gadolinium contrast medium.`, 
        `not seen in patients with GFR greater than 60 mL/min/1.73 m<sup>2</sup>.`, 
        `mainly seen in dialysis patients exposed to gadolinium contrast medium.`],
        optionStyleType: `st-lower-alpha`,
        answer: [3],
        ansText:`Rationale: <!--<b>d. Not seen in patients with GFR greater than 60 mL/min/1.73 m<sup>2</sup>.</b>--> Patients with CKD but GRF greater than 30 mL/min/1.73 m<sup>2</sup> are considered to be at extremely low or no risk for developing NSF if a dose of GBCM of 0.1 mmol/kg or less is used. Patients with GFR greater than 60 mL/min/1.73 m<sup>2</sup> do not appear to be at increased risk of developing NSF, and the current consensus is that all GBCM can be administered safely to these patients.`, 
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `During a diuretic renal scintigraphy:`,
        q2: ``,
        q3: [],
        option: [`the diuretic is administered approximately 2 minutes after peak activity is seen in the collecting system.`, 
        `a T<sub>&#189;</sub> of greater than 14 minutes is consistent with obstruction.`, 
        `<sup>99m</sup>Tc-DMSA is the most sensitive for obstruction and determination of GFR.`, 
        `intestinal or gallbladder activity should never be seen with <sup>99m</sup>Tc-MAG3.`, 
        `a T<sub>&#189;</sub> of less than 10 minutes is consistent with a nonobstructed system.`],
        optionStyleType: `st-lower-alpha`,
        answer: [4],
        ansText:`Rationale: <!--<b>e. a T<sub>&#189;</sub> of less than 10 minutes is consistent with a nonobstructed system.</b>--> Transit time throughout the collecting system in less than 10 minutes is consistent with a normal, nonobstructed collecting system. A T<sub>&#189;</sub> of 10 to 20 minutes shows mild to moderate delay and may be a mechanical obstruction. The patient’s perception of pain after diuretic administration can be helpful for the treating urologist to consider when planning surgery in the patient with middle to moderate obstruction. <b>A T</b><sub><b>&#189;</b></sub> <b>of greater than 20 minutes is consistent with a high-grade obstruction.</b>`, 
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `Positron emission tomography (PET):`,
        q2: ``,
        q3: [],
        option: [`has a higher diagnostic accuracy than CT for seminoma and nonseminoma testis cancer following chemotherapy.`, 
        `is sensitive and specific for detection of postchemotherapy teratoma.`, 
        `can be used with high positive predictive value within 2&#160;weeks of completion of chemotherapy for bulky lymph adenopathy.`, 
        `has greater predictive value of primary disease in metastatic urothelial carcinoma than magnetic resonance imaging (MRI).`, 
        `is able to detect local or systemic recurrence of prostate cancer in 74% of patients with prostate-specific antigen recurrence.`],
        optionStyleType: `st-lower-alpha`,
        answer: [0],
        ansText:`Rationale: <!--<b>a. Has a higher diagnostic accuracy than CT for seminoma and nonseminoma testis cancer following chemotherapy.</b>--> There are data on the use of PET/CT in testis cancer, where PET/CT was found to have a higher diagnostic accuracy than CT for staging and restaging in the assessment of a CT-visualized residual mass following chemotherapy for seminoma and nonseminomatous germ cell tumors (Hain et&#160;al., 2000; Albers et&#160;al., 1999).`, 
        state: `notAnswered`,
        userAnswered: []
        ,
        type: `MCSS`},
    {
        q: `What is the minimum estimated GFR for use of gadolinium-based contrast agents?`,
        q2: ``,
        q3: [],
        option: [`Less than 30 mL/min/1.73 m<sup>2</sup>`, 
        `Greater than 50 mL/min/1.73 m<sup>2</sup>`, 
        `Greater than 35 mL/min/1.73 m<sup>2</sup>`, 
        `Greater than 30 mL/min/1.73 m<sup>2</sup>`, 
        `There are no restrictions for patients with renal insufficiency.`],
        optionStyleType: `st-lower-alpha`,
        answer: [3],
        ansText:`Rationale: <!--<b>d. Greater than 30 mL/min/1.73 m<sup>2</sup>.</b>--> NSF occurs in patients with acute or chronic renal insufficiency with a GFR less than 30 mL/min/1.73 m<sup>2</sup>.`, 
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `In magnetic resonance (MR) images using T2-weighted sequences, fluid appears as:`,
        q2: ``,
        q3: [],
        option: [`dark.`, 
        `bright.`, 
        `low signal.`, 
        `signal void.`, 
        `indeterminate.`],
        optionStyleType: `st-lower-alpha`,
        answer: [1],
        ansText:`Rationale: <!--<b>b. Bright.</b>--> High signal on T2-weighted images. Fluid exhibits a low signal on T1-weighted images.`, 
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `What lesions may have a high signal (bright) on T2-weighted MRI of the adrenal gland?`,
        q2: ``,
        q3: [],
        option: [`Pheochromocytoma`, 
        `Metastasis`, 
        `Adrenal cortical carcinoma (ACC)`, 
        `None of the above`, 
        `All of the above`],
        optionStyleType: `st-lower-alpha`,
        answer: [4],
        ansText:`Rationale: <!--<b>e. All of the above.</b>--> Traditional teaching reported the lightbulb sign to be consistent with pheochromocytoma. However, metastasis and ACC also have a high signal on T2-weighted images. Furthermore, Varghese and colleagues reported that <b>35% of pheochromocytomas demonstrated low T2 signal,</b> contrary to conventional teaching. Therefore the conventional teaching of the “lightbulb sign” is incorrect.`, 
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `MR chemical shift imaging (CSI) for adrenal adenoma takes advantage of which of the following phenomena to aid in the diagnosis?`,
        q2: ``,
        q3: [],
        option: [`Water and fat within the same voxel signals are canceled out in opposed-phase imaging.`, 
        `Opposed-phase imaging will exhibit a high signal (bright).`, 
        `Intracellular lipid content within an adenoma is low.`, 
        `Intravenous contrast is required.`, 
        `All of the above.`],
        optionStyleType: `st-lower-alpha`,
        answer: [0],
        ansText:`Rationale: <!--<b>a. Water and fat within the same voxel signals are canceled out in opposed-phase imaging.</b>--> MR CSI is performed on T1-weighted images. Opposed-phase imaging will demonstrate a low signal (dark) if fat and water occupy the same voxel. Adrenal adenomas have high intracytoplasmic fat. CSI is performed without the use of intravenous contrast.`, 
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `Oncocytoma typically has been characterized by a central scar. Which other renal lesion may also exhibit a central scar on T2-weighted images?`,
        q2: ``,
        q3: [],
        option: [`Clear cell carcinoma`, 
        `Angiomyolipoma`, 
        `Chromophobe carcinoma`, 
        `Transitional cell carcinoma`, 
        `No other renal masses exhibit a central scar.`],
        optionStyleType: `st-lower-alpha`,
        answer: [2],
        ansText:`Rationale: <!--<b>c. Chromophobe carcinoma.</b>--> Chromophobe carcinoma exhibits a high signal on T2-weighted images.`, 
        state: `notAnswered`,
        userAnswered: []
        ,
        type: `MCSS`},
    {
        q: `Which renal mass exhibits signal drop on opposed phase imaging?`,
        q2: ``,
        q3: [],
        option: [`Papillary renal cell`, 
        `Chromophobe carcinoma`, 
        `Angiomyolipoma`, 
        `Clear cell carcinoma`, 
        `Transitional cell carcinoma`],
        optionStyleType: `st-lower-alpha`,
        answer: [3],
        ansText:`Rationale: <!--<b>d. Clear cell carcinoma.</b>--> Microscopic intracytoplasmic lipids have been found in 59% of clear cell carcinomas, which allows it to be differentiated from other renal cell carcinoma cell types.`, 
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `What signal characteristics do kidney stones exhibit on MR urography?`,
        q2: ``,
        q3: [],
        option: [`High signal on T2-weighted images`, 
        `Low signal on T2-weighted images`, 
        `Signal void`, 
        `High signal on T1-weighted images`, 
        `Low signal on T1-weighted images`],
        optionStyleType: `st-lower-alpha`,
        answer: [2],
        ansText:`Rationale: <!--<b>c. Signal void.</b>--> Nephrolithiasis/calcification on MR imaging has no signal characteristics; therefore it appears as a void on imaging.`, 
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `Multiparametric imaging of the prostate consists of anatomic and functional sequences. Match the correct pair.`,
        q2: ``,
        q3: [],
        option: [`Anatomic: Diffusion-weighted imaging`, 
        `Functional: T1- and T2-weighted images`, 
        `Anatomic: Dynamic contrast enhanced sequences`, 
        `Functional: Apparent diffusion coefficient maps`, 
        `All of the above`],
        optionStyleType: `st-lower-alpha`,
        answer: [3],
        ansText:`Rationale: <!--<b>d. Functional: Apparent diffusion coefficient maps.</b>--> Multiparametric MRI refers to the use of anatomic sequences (T1-weighted images, T2 triplanar [axial, sagittal, and coronal] images) and functional sequences (diffusion-weighted imaging/apparent diffusion coefficient maps, dynamic contrast-enhanced MRI, spectroscopy). The combined approach has reported negative and positive predictive values to be greater than 90% in detecting prostate&#160;cancer.`, 
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`}


];
