var quiz = [
    

    {
        q: `The Hippocratic Oath does not include the ethical principle of:`,
        q2: ``,
        q3: [],
        option: [`beneficence.`, 
        `non-maleficence.`, 
        `patient privacy.`, 
        `patient autonomy.`, 
        `accountability to the profession.`],
        optionStyleType: `st-upper-alpha`,
        answer: [3],
        ansText:`Rationale: <!--<b>d. Patient autonomy.</b>--> Although the Hippocratic Oath includes the concepts of benefiting and avoiding harm to patients as well as protecting patient privacy, it does not include the concept of patient autonomy, which emerged in the 20th century.`, 
        state: `notAnswered`,
        userAnswered: []
,
        type: `MCSS`},
    {
        q: `Important events leading to the modern framework of medical ethics include:`,
        q2: ``,
        q3: [],
        option: [`The Nuremburg Trials.`, 
        `The Tuskegee Syphilis Studies.`, 
        `The Milgram Experiments.`, 
        `all of the above.`, 
        `none of the above.`],
        optionStyleType: `st-upper-alpha`,
        answer: [3],
        ansText:`Rationale: <!--<b>d. All of the above.</b>--> The Nuremburg trials revealed the involuntary experiments of Dr. Josef Mengele and other Nazi doctors on concentration camp detainees, resulting in pain, debilitation, and death of subjects. The trials led to the development of the Nuremburg code, which reinforced the need for voluntary consent, need to minimize harm, absence of other methods to obtain data, and need to terminate studies early if evidence of potential harm in a clinical research study. The Tuskegee studies were performed from 1932 to 1972 in Tuskegee, Alabama, to study the natural history of syphilis, with investigators withholding antibiotic treatment even after the discovery of the efficacy of penicillin to treat the disease. The study raised issues of adequate knowledge for consent, need to avoid coercion for participation, and need to terminate studies early if the investigator has knowledge of preventable harm. The Milgram experiments, which were conducted in 1963 at Yale by psychologist Stanley Milgram, encouraged subjects to administer fake electrical shocks to unseen participants. Recorded responses to the shocks were played, including screaming and silence suggestive of possible unconsciousness. Subjects were encouraged to continue to escalate shocks despite these responses, with the majority of subjects administering maximal shocks, leading to psychological trauma in many participants. The study raised concerns about use of deception in research and lack of adequate safeguards against harm. All of these events led to heightened scrutiny and development of heightened standards for medical research.`, 
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `The most important of the four basic principles of modern medical ethics is:`,
        q2: ``,
        q3: [],
        option: [`justice.`, 
        `autonomy.`, 
        `beneficence.`, 
        `non-maleficence.`, 
        `none of the above.`],
        optionStyleType: `st-upper-alpha`,
        answer: [4],
        ansText:`Rationale: <!--<b>e. None of the above.</b>--> According to Beauchamp and Childress, the four basic principles of autonomy, beneficence, non-maleficence, and justice should be considered equal in weight.`, 
        state: `notAnswered`,
        userAnswered: []
        ,
        type: `MCSS`},
    {
        q: `The term bioethics was first coined by:`,
        q2: ``,
        q3: [],
        option: [`Veatch.`, 
        `Potter.`, 
        `Beauchamp and Childress.`, 
        `Jonsen, Siegler, and Winslade.`, 
        `none of the above.`],
        optionStyleType: `st-upper-alpha`,
        answer: [1],
        ansText:`Rationale: <!--<b>b. Potter.</b>--> Van Rensselaer Potter first coined the term bioethics in 1970, described as the “study of the moral relationship between humans and their social and physical world.”`, 
        state: `notAnswered`,
        userAnswered: []
        ,
        type: `MCSS`},
    {
        q: `The Four Box Method does not:`,
        q2: ``,
        q3: [],
        option: [`provide a systematic approach to apply ethical principles to specific clinical situations.`, 
        `include consideration of medical indications, patient preferences, quality of life, and other contextual features.`, 
        `create a venue for discussion of relative risks and benefits of potential treatment options.`, 
        `provide definitive answers to ethically challenging situations.`, 
        `none of the above`],
        optionStyleType: `st-upper-alpha`,
        answer: [3],
        ansText:`Rationale: <!--<b>d. Provide definitive answers to ethically challenging situations.</b>--> Although the Four Box Method allows for systematic consideration of ethically complex clinical situations and creates a vehicle for discussions regarding treatment, it may also oversimplify ethical problems and does not always provide clear “right” and “wrong” answers to address ethical concerns.`, 
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `Clinical informed consent originated in:`,
        q2: ``,
        q3: [],
        option: [`The Hippocratic Oath.`, 
        `19th-century negligence laws.`, 
        `The Nuremburg Code.`, 
        `20th-century battery laws.`],
        optionStyleType: `st-upper-alpha`,
        answer: [3],
        ansText:`Rationale: <!--<b>d. 20th-century battery laws</b>-->. Although now considered within the scope of negligence, informed consent was first described by state courts in early 20th-century battery cases and was considered to be grounded in the right to bodily integrity. The Nuremburg code recommended expansion of the right to informed consent to medical research.`, 
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `Under current informed consent requirements, physicians are obligated to provide:`,
        q2: ``,
        q3: [],
        option: [`information about the most common risks of a procedure.`, 
        `information that a “reasonable physician” would provide.`, 
        `information that a “reasonable person” would want to know.`, 
        `a written document detailing risks and benefits of the procedure.`],
        optionStyleType: `st-upper-alpha`,
        answer: [2],
        ansText:`Rationale: <!--<b>c. Information that a “reasonable person” would want to know.</b>--> Although battery law required disclosure of risks and early negligence law required disclosure of what a “reasonable and prudent” physician would do, the current standard is what a reasonable person would want to know (Canterbury vs. Spence, 1972). The informed consent process requires both information from the physician and demonstrated understanding by the patient but does not require written documentation.`, 
        state: `notAnswered`,
        userAnswered: []
,
        type: `MCSS`},
    {
        q: `The element of informed consent that is most often lacking is:`,
        q2: ``,
        q3: [],
        option: [`description of the clinical problem, proposed treatment, and alternatives.`, 
        `discussion of the risks and benefits of the proposed treatment.`, 
        `assessment of the patient’s understanding of the information provided by the medical provider.`, 
        `solicitation of the patient’s preferences for treatment.`],
        optionStyleType: `st-upper-alpha`,
        answer: [2],
        ansText:`Rationale: <!--<b>c. Assessment of the patient’s understanding of the information provided by the medical provider.</b>--> Although all four elements are needed for a comprehensive informed consent, the majority of informed consents are incomplete with the element of assessing patient understanding of the information provided being the most commonly missed.`, 
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `Exceptions to the informed consent requirement do not include:`,
        q2: ``,
        q3: [],
        option: [`an unconscious 25-year-old patient who sustained multiple gunshot wounds.`, 
        `a 75-year-old patient with Alzheimer dementia who is being evaluated for benign prostatic hyperplasia (BPH) and has a previously identified surrogate decision maker.`, 
        `a 3-year-old patient who is accompanied by his parents for circumcision evaluation.`, 
        `a conscious 25-year-old patient who sustained multiple gunshot wounds.`, 
        `none of the above.`],
        optionStyleType: `st-upper-alpha`,
        answer: [3],
        ansText:`Rationale: <!--<b>d. A conscious 25-year-old patient who sustained multiple gunshot wounds.</b>--> In emergency settings where there is a significant threat to patient life or well-being, consent is presumed. However, this waiver of consent does not extend to the conscious patient even if refusal of treatment is life-threatening (In re Quackenbush 1978).`, 
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `Issues thought to be associated with lack of patient understanding of consent include all EXCEPT:`,
        q2: ``,
        q3: [],
        option: [`language of the surgical consent form is above the average patient reading level.`, 
        `patients may misunderstand the risks posed by surgery.`, 
        `patients idealize surgeons and defer to surgeon recommendations.`, 
        `patients may not recall the information contained within a surgical consent form.`, 
        `none of the above.`],
        optionStyleType: `st-upper-alpha`,
        answer: [4],
        ansText:`Rationale: <!--<b>e. None of the above.</b>--> All of the options have been posed as limitations to patient understanding of consent. The information provided in consent forms often is above the 12th-grade level, although the majority of patients have reading levels below the 8th-grade level. Additionally, patients who report reading consent forms may not recall the information contained in the document. Additionally, patients often underestimate their risks compared to other people or may use heuristics to make decisions that lead to a misunderstanding of the risks involved. Finally, patients often accept surgical recommendations without meaningful participation in the decision-making process due to idealization of the surgeon and his or her judgment.`, 
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `Use of decision aids have been associated with all of the following EXCEPT:`,
        q2: ``,
        q3: [],
        option: [`improved knowledge of the procedure.`, 
        `improved assessment of risk.`, 
        `increased patient participation in the decision-making process.`, 
        `increased decisional conflict.`, 
        `none of the above.`],
        optionStyleType: `st-upper-alpha`,
        answer: [3],
        ansText:`Rationale: <!--<b>d. Increased decisional conflict.</b>--> Decision aids have been associated with improved knowledge about procedures, reduced decisional conflict, improved patient participation in the decision, and improved assessment of risk.`, 
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`}



];
