var quiz = [
    

    {
        q: `<sup>99m</sup>Tc-diethylenetriaminepentaacetic acid (<sup>99m</sup>Tc-DTPA) undergoes renal clearance by which mechanism?`,
        q2: ``,
        q3: [],
        option: [`Glomerular filtration`, 
        `Active tubular secretion`, 
        `Anion exchange`, 
        `Both A and B`, 
        `All of the above`],
        optionStyleType: `st-lower-alpha`,
        answer: [0],
        ansText:`Rationale: <!--<b>a. Goluerular filtration.</b>--> <sup>99m</sup>Tc-DPTA is a single-photon radiotracer that is excreted in the urine and can be used to determine renal split function and to assess for functional obstruction. <sup>99m</sup>Tc-DTPA is extracted by the kidneys through glomerular filtration. The drug then quickly moves through the renal tubules and is excreted in the urine without being reabsorbed.`, 
        state: `notAnswered`,
        userAnswered: []
        ,
        type: `MCSS`},
    {
        q: `<sup>99m</sup>Tc-mercaptoacetyltriglycine (<sup>99m</sup>Tc-MAG3) undergoes renal clearance by which mechanism?`,
        q2: ``,
        q3: [],
        option: [`Glomerular filtration`, 
        `Active tubular secretion`, 
        `Anion exchange`, 
        `Both A and B`, 
        `All of the above`],
        optionStyleType: `st-lower-alpha`,
        answer: [1],
        ansText:`Rationale: <!--<b>b. Active tubular secretion.</b>--><sup>99m</sup>Tc-MAG3 is a single-photon radiotracer that is excreted in the urine and can be used to determine renal split function and to assess for functional obstruction. <sup>99m</sup>Tc-MAG3 is protein bound in circulation and undergoes clearance exclusively through tubular secretion. <sup>99m</sup>Tc-MAG3 imaging is therefore not impacted by impaired glomerular filtration.`, 
        state: `notAnswered`,
        userAnswered: []
        ,
        type: `MCSS`},
    {
        q: `<sup>99m</sup>Tc–dimercaptosuccinic acid (<sup>99m</sup>Tc-DMSA) undergoes renal clearance and is endocytosed by cells of which part of the nephron?`,
        q2: ``,
        q3: [],
        option: [`Glomerulus`, 
        `Proximal tubule`, 
        `Distal tubule`, 
        `Ascending loop of Henle`, 
        `Collecting duct`],
        optionStyleType: `st-lower-alpha`,
        answer: [1],
        ansText:`Rationale: <!--<b>b. Proximal tubule.</b>--> <sup><b>99m</b></sup><b>Tc-DMSA is cleared from the plasma primarily by glomerular filtration.</b> Once within the lumina of the renal tubules, <sup>99m</sup>Tc-DMSA undergoes receptor-mediated endocytosis by the proximal tubular cells. The receptors responsible for the endocytosis of <sup>99m</sup>Tc-DMSA are megalin and cubilin.`, 
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `When performing <sup>99m</sup>Tc-MAG3 renography, the relative function of each kidney is determined by measuring the area under the time activity curve between what two time points post injection?`,
        q2: ``,
        q3: [],
        option: [`1 to 3 minutes`, 
        `3 to 5 minutes`, 
        `5 to 10 minutes`, 
        `10 to 15 minutes`, 
        `15 to 20 minutes`],
        optionStyleType: `st-lower-alpha`,
        answer: [0],
        ansText:`Rationale: <!--<b>a. 1 to 3 minutes.</b>--> Dynamic renal imaging is performed in two phases. In the first phase, known as the perfusion phase, renal plasma flow to each individual renal unit is measured and compared with flow within the aorta. Activity should be detected in the regions of interest overlying the kidneys within several seconds of detection in the aorta. The relative function of each kidney is determined by measuring the area under the time activity curves between 1 and 3 minutes post injection of the radiotracer.`, 
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `Which radiotracer is ideally suited for imaging renal scaring?`,
        q2: ``,
        q3: [],
        option: [`<sup>99m</sup>Tc-DTPA`, 
        `<sup>99m</sup>Tc-MAG3`, 
        `<sup>99m</sup>Tc-DMSA`, 
        `<sup>67</sup>Ga-citrate`, 
        `<sup>99m</sup>Tc–sulfur colloid`],
        optionStyleType: `st-lower-alpha`,
        answer: [2],
        ansText:`Rationale: <!--<b>c. <sup>99m</sup>Tc-DMSA.</b>--> Because this radiotracer undergoes endocytosis by the proximal tubular cells, it is ideally suited for imaging cortical processes such as acute pyelonephritis and renal scaring.`, 
        state: `notAnswered`,
        userAnswered: []
        ,
        type: `MCSS`},
    {
        q: `2-Deoxy-2-[<sup>18</sup>F]fluoro-D-glucose (<sup>18</sup>F-FDG) is phosphorylated by which glycolytic enzyme, trapping it inside metabolically active cells?`,
        q2: ``,
        q3: [],
        option: [`Hexokinase`, 
        `Glucokinase`, 
        `Phosphofructokinase`, 
        `Pyruvate kinase`, 
        `Phosphoglucose isomerase`],
        optionStyleType: `st-lower-alpha`,
        answer: [0],
        ansText:`Rationale: <!--<b>a. Hexokinase.</b>--> <sup>18</sup>F-FDG is a glucose analog that is taken up by metabolically active cells via GLUT transporters. Once within the cell, <sup>18</sup>F-FDG is phosphorylated by the glycolytic enzyme hexokinase, preventing diffusion back across the cell membrane. The trapped <sup>18</sup>F-FDG molecules, which are missing a 2-hydroxyl group, cannot undergo further glycolytic metabolism and remain intact allowing for their detection with PET imaging.`, 
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `Which urologic malignancy is poorly imaged with <sup>18</sup>F-FDG positron emission tomography (PET)?`,
        q2: ``,
        q3: [],
        option: [`Bladder cancer`, 
        `Penile cancer`, 
        `Prostate cancer`, 
        `Renal cell carcinoma`, 
        `Seminomatous germ cell tumor`],
        optionStyleType: `st-lower-alpha`,
        answer: [2],
        ansText:`Rationale: <!--<b>c. Prostate cancer.</b>--><sup>18</sup>F- FDG is taken up by malignant cells, which commonly shunt energy production toward anaerobic metabolism, a phenomenon referred to as the Warburg effect. A number of genitourinary malignancies, including urothelial carcinoma, renal cell carcinoma, squamous cell carcinoma of the penis, and testicular germ cell tumors, can be successfully imaged with <sup>18</sup>F-FDG PET. Prostate cancer is unique in that it does not show increased levels of glycolysis and therefore is poorly visualized with <sup>18</sup>F-FDG PET.`, 
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `What is the half-life of the radionuclide <sup>18</sup>F?`,
        q2: ``,
        q3: [],
        option: [`20.3 minutes`, 
        `109.8 minutes`, 
        `68.0 minutes`, 
        `4.17 days`, 
        `78.4 hours`],
        optionStyleType: `st-lower-alpha`,
        answer: [1],
        ansText:`Rationale: <!--<b>b. 109.8 minutes.</b>--> The half-lives of other commonly used radionuclides for PET imaging can be found in Table 5.2.`, 
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `Which of the following PET radiotracers for prostate cancer imaging is an amino acid analog?`,
        q2: ``,
        q3: [],
        option: [`<sup>18</sup>F-DCFPyL`, 
        `<sup>68</sup>Ga-PSMA-11`, 
        `<sup>11</sup>C-choline`, 
        `<sup>68</sup>Ga-RM2`, 
        `<sup>18</sup>F-FACBC`],
        optionStyleType: `st-lower-alpha`,
        answer: [0],
        ansText:`Rationale: <!--<b>a. 18F-FACBC.</b>--> This radiotracer functions as a substrate for the amino acid transporters LAT1 and ASCT2, which are overexpressed by multiple malignancies including prostate cancer.`, 
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `Which protein is highly expressed by clear cell renal cell carcinoma (RCC) but not other renal tumor types and serves as a target for molecular imaging of this malignancy?`,
        q2: ``,
        q3: [],
        option: [`GLUT1`, 
        `PSMA`, 
        `GRPR`, 
        `CAIX`, 
        `ASCT2`],
        optionStyleType: `st-lower-alpha`,
        answer: [3],
        ansText:`Rationale: <!--<b>d. CAIX.</b>--> <b>This cell surface protein is near universally expressed by clear cell RCC but not other renal tumor histologies.</b> CAIX is upregulated following loss of the von Hippel-Lindau <b><i>(VHL)</i></b> gene, which is a defining event in the pathogenesis of clear cell RCC.`, 
        state: `notAnswered`,
        userAnswered: []
        ,
        type: `MCSS`},
    {
        q: `Which radiotracer has the highest specificity for imaging prostate cancer?`,
        q2: ``,
        q3: [],
        option: [`<sup>18</sup>F-DCFPyL`, 
        `<sup>67</sup>Ga-citrate`, 
        `<sup>11</sup>C-choline`, 
        `<sup>18</sup>F-FDG`, 
        `<sup>18</sup>F-FACBC`],
        optionStyleType: `st-lower-alpha`,
        answer: [0],
        ansText:`Rationale: <!--<b>a. 18F-DCFPyL.</b>--> PET radiotracers targeting prostate-specific membrane antigen (PSMA) have the highest specificity for prostate cancer imaging. Of the radiotracers listed, 18F-DCFPyL is the only PSMA-targeted radiotracer. A summary of other radiotracer used for prostate cancer imaging can be found in Table 5.3.`, 
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `<sup>18</sup>F-FDG PET is recommended for which application in men with testicular cancer?`,
        q2: ``,
        q3: [],
        option: [`Initial cancer staging of patients with elevated postorchiectomy tumor markers`, 
        `Initial cancer staging of patients with negative postorchiectomy tumor markers`, 
        `Postchemotherapy imaging of a residual retroperitoneal mass in men with a seminomatous germ cell tumor`, 
        `Postchemotherapy imaging of a residual retroperitoneal mass in men with a nonseminomatous germ cell tumors`, 
        `Post-treatment surveillance in patients with negative markers`],
        optionStyleType: `st-lower-alpha`,
        answer: [2],
        ansText:`Rationale: <!--<b>c. Postchemotherapy imaging of a residual retroperitoneal mass in men with a seminomatous germ cell tumor.</b>--> Guidelines from the European Association of Urology endorse the use of <sup>18</sup>F-FDG PET for men with a residual mass following treatment of a seminoma with chemotherapy. Using <sup>18</sup>F-FDG PET in this manner helps to differentiate fibrosis from residual active tumor. For patients with nonseminomatous germ cell tumors, <sup>18</sup>F-FDG PET imaging is not indicated because there appears to be no clinical benefit for PET in the detection of viable tumor over the combination of computed tomography (CT) and serum markers.`, 
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`}



];
