var quiz = [
    

    {
        q: `Pain associated with a stone in the ureter is the result of:`,
        q2: ``,
        q3: [],
        option: [`obstruction of urine flow with distention of the renal capsule.`, 
        `irritation of the ureteral mucosa by the stone.`, 
        `excessive ureteral peristalsis in response to the obstructing stone.`, 
        `irritation of the intramural ureter.`, 
        `urinary extravasation from a ruptured calyceal fornix.`],
        optionStyleType: `st-lower-alpha`,
        answer: [0],
        ansText:`Rationale: <!--<b>a. Obstruction of urine flow with distention of the renal capsule.</b>--> Pain is usually caused by acute distention of the renal capsule, usually from inflammation or obstruction.`, 
        state: `notAnswered`,
        userAnswered: [],
	type: `MCSS`},
     {
        q: `The most common cause of gross hematuria in a patient older than 50 years is:`,
        q2: ``,
        q3: [],
        option: [`renal calculi.`, 
        `infection.`, 
        `bladder cancer.`, 
        `benign prostatic hyperplasia.`, 
        `trauma.`],
        optionStyleType: `st-lower-alpha`,
        answer: [2],
        ansText:`Rationale: <!--<b>c. Bladder cancer.</b>--> The most common cause of gross hematuria in a patient older than age 50 is bladder cancer.`, 
        state: `notAnswered`,
        userAnswered: [],
	type: `MCSS`},
     {
        q: `The most common cause of pain associated with gross hematuria is:`,
        q2: ``,
        q3: [],
        option: [`simultaneous passage of a kidney stone.`, 
        `ureteral obstruction due to blood clots.`, 
        `urinary tract malignancy.`, 
        `prostatic inflammation.`, 
        `prostatic enlargement.`],
        optionStyleType: `st-lower-alpha`,
        answer: [1],
        ansText:`Rationale: <!--<b>b. Ureteral obstruction due to blood clots.</b>--> Pain in association with hematuria usually results from upper urinary tract hematuria with obstruction of the ureters with clots.`, 
        state: `notAnswered`,
        userAnswered: [],
	type: `MCSS`},
     {
        q: `All of the following are typical lower urinary tract symptoms associated with benign prostatic hyperplasia EXCEPT:`,
        q2: ``,
        q3: [],
        option: [`urgency.`, 
        `frequency.`, 
        `nocturia.`, 
        `dysuria.`, 
        `weak urinary stream.`],
        optionStyleType: `st-lower-alpha`,
        answer: [3],
        ansText:`Rationale: <!--<b>d. Dysuria.</b>--> Dysuria is painful urination that is usually caused by inflammation.`, 
        state: `notAnswered`,
        userAnswered: [],
	type: `MCSS`},
     {
        q: `The most likely cause of continuous incontinence (loss of urine at all times and in all positions) is:`,
        q2: ``,
        q3: [],
        option: [`enterovesical fistula.`, 
        `noncompliant bladder.`, 
        `detrusor hyperreflexia.`, 
        `vesicovaginal fistula.`, 
        `sphincteric incompetence.`],
        optionStyleType: `st-lower-alpha`,
        answer: [3],
        ansText:`Rationale: <!--<b>d. Vesicovaginal fistula.</b>--> Continuous incontinence is most commonly due to a urinary tract fistula that bypasses the urethral sphincter or an ectopic ureter.`, 
        state: `notAnswered`,
        userAnswered: [],
	   type: `MCSS`},
     {
        q: `All of the following are potential causes of anejaculation EXCEPT:`,
        q2: ``,
        q3: [],
        option: [`sympathetic denervation.`, 
        `pharmacologic agents.`, 
        `bladder neck and prostatic surgery.`, 
        `androgen deficiency.`, 
        `cerebrovascular accidents.`],
        optionStyleType: `st-lower-alpha`,
        answer: [4],
        ansText:`Rationale: <!--<b>e. Cerebrovascular accidents.</b>--> Anejaculation may result from several causes: (1) androgen deficiency, (2) sympathetic denervation, (3) pharmacologic agents, and (4) bladder neck and prostatic surgery.`, 
        state: `notAnswered`,
        userAnswered: [],
	type: `MCSS`},
     {
        q: `What percentage of patients with multiple sclerosis will present with urinary symptoms as the first manifestation of the disease?`,
        q2: ``,
        q3: [],
        option: [`1%`, 
        `5%`, 
        `10%`, 
        `15%`, 
        `20%`],
        optionStyleType: `st-lower-alpha`,
        answer: [1],
        ansText:`Rationale: <!--<b>b. 5%.</b>--> In fact, 5% of patients with previously undiagnosed multiple sclerosis present with urinary symptoms as the first manifestation of the disease.`, 
        state: `notAnswered`,
        userAnswered: [],
	   type: `MCSS`},
     {
        q: `What important information is gained from pelvic bimanual examination that cannot be obtained from radiologic evaluation?`,
        q2: ``,
        q3: [],
        option: [`Presence of bladder mass`, 
        `Invasion of bladder cancer into perivesical fat`, 
        `Presence of bladder calculi`, 
        `Presence of associated pathologic lesion in female adnexal structures`, 
        `Mobility/fixation of pelvic organs`],
        optionStyleType: `st-lower-alpha`,
        answer: [4],
        ansText:`Rationale: <!--<b>e. Mobility/fixation of pelvic organs.</b>--> In addition to defining areas of induration, the bimanual examination allows the examiner to assess the mobility of the bladder; such information cannot be obtained by radiologic techniques such as computed tomography (CT) and magnetic resonance imaging (MRI), which convey static images.`, 
        state: `notAnswered`,
        userAnswered: [],
	   type: `MCSS`},
     {
        q: `With which of the following diseases is priapism most commonly associated?`,
        q2: ``,
        q3: [],
        option: [`Peyronie disease`, 
        `Sickle cell anemia`, 
        `Parkinson disease`, 
        `Organic depression`, 
        `Leukemia`],
        optionStyleType: `st-lower-alpha`,
        answer: [1],
        ansText:`Rationale: <!--<b>b. Sickle cell anemia.</b>--> Priapism occurs most commonly in patients with sickle cell disease but can also occur in those with advanced malignancy, coagulation disorders, and pulmonary disease, as well as in many patients without an obvious cause.`, 
        state: `notAnswered`,
        userAnswered: [],
	   type: `MCSS`},
     {
        q: `What is the most common cause of cloudy urine?`,
        q2: ``,
        q3: [],
        option: [`Bacterial cystitis`, 
        `Urine overgrowth with yeast`, 
        `Phosphaturia`, 
        `Alkaline urine`, 
        `Significant proteinuria`],
        optionStyleType: `st-lower-alpha`,
        answer: [2],
        ansText:`Rationale: <!--<b>c. Phosphaturia.</b>--> Cloudy urine is most commonly caused by phosphates in the urine.`, 
        state: `notAnswered`,
        userAnswered: [],
	   type: `MCSS`},
     {
        q: `Conditions that decrease urine specific gravity include all of the following EXCEPT:`,
        q2: ``,
        q3: [],
        option: [`increased fluid intake.`, 
        `use of diuretics.`, 
        `decreased renal concentrating ability.`, 
        `dehydration.`, 
        `diabetes insipidus.`],
        optionStyleType: `st-lower-alpha`,
        answer: [3],
        ansText:`Rationale: <!--<b>d. Dehydration.</b>--> Conditions that decrease specific gravity include (1) increased fluid intake, (2) diuretics, (3) decreased renal concentrating ability, and (4) diabetes insipidus.`, 
        state: `notAnswered`,
        userAnswered: [],
	   type: `MCSS`},
     {
        q: `Urine osmolality usually varies between:`,
        q2: ``,
        q3: [],
        option: [`10 and 200 mOsm/L.`, 
        `50 and 500 mOsm/L.`, 
        `50 and 1200 mOsm/L.`, 
        `100 and 1000 mOsm/L.`, 
        `100 and 1500 mOsm/L.`],
        optionStyleType: `st-lower-alpha`,
        answer: [2],
        ansText:`Rationale: <!--<b>c. 50 and 1200 mOsm/L.</b>--> Osmolality is a measure of the amount of solutes dissolved in the urine and usually varies between 50 and 1200 mOsm/L.`, 
        state: `notAnswered`,
        userAnswered: [],
	   type: `MCSS`},
     {
        q: `Elevated ascorbic acid levels in the urine may lead to false-negative results on a urine dipstick test for:`,
        q2: ``,
        q3: [],
        option: [`glucose.`, 
        `hemoglobin.`, 
        `myoglobin.`, 
        `red blood cells.`, 
        `leukocytes.`],
        optionStyleType: `st-lower-alpha`,
        answer: [0],
        ansText:`Rationale: <!--<b>a. Glucose.</b>--> False-negative results for glucose and bilirubin may be seen in the presence of elevated ascorbic acid concentrations in the urine.`, 
        state: `notAnswered`,
        userAnswered: [],
	   type: `MCSS`},
     {
        q: `Hematuria is distinguished from hemoglobinuria or myoglobinuria by:`,
        q2: ``,
        q3: [],
        option: [`dipstick testing.`, 
        `the simultaneous presence of significant leukocytes.`, 
        `microscopic presence of erythrocytes.`, 
        `examination of serum.`, 
        `evaluation of hematocrit.`],
        optionStyleType: `st-lower-alpha`,
        answer: [2],
        ansText:`Rationale: <!--<b>c. Microscopic presence of erythrocytes.</b>--> Hematuria can be distinguished from hemoglobinuria and myoglobinuria by microscopic examination of the centrifuged urine; the presence of a large number of erythrocytes establishes the diagnosis of hematuria.`, 
        state: `notAnswered`,
        userAnswered: [],
	   type: `MCSS`},
     {
        q: `The presence of one positive dipstick reading for hematuria is associated with significant urologic pathologic findings on subsequent testing in what percentage of patients?`,
        q2: ``,
        q3: [],
        option: [`2%`, 
        `10%`, 
        `25%`, 
        `50%`, 
        `75%`],
        optionStyleType: `st-lower-alpha`,
        answer: [2],
        ansText:`Rationale: <!--<b>c. 25%.</b>--> Investigators at the University of Wisconsin found that 26% of adults who had at least one positive dipstick reading for hematuria were subsequently found to have significant urologic pathologic findings.`, 
        state: `notAnswered`,
        userAnswered: [],
	   type: `MCSS`},
     {
        q: `The most common cause of glomerular hematuria is:`,
        q2: ``,
        q3: [],
        option: [`transitional cell carcinoma.`, 
        `nephritic syndrome.`, 
        `Berger disease (immunoglobulin A nephropathy).`, 
        `poststreptococcal glomerulonephritis.`, 
        `Goodpasture syndrome.`],
        optionStyleType: `st-lower-alpha`,
        answer: [2],
        ansText:`Rationale: <!--<b>c. Berger disease (immunoglobulin A nephropathy).</b>--> IgA nephropathy, or Berger disease, is the most common cause of glomerular hematuria, accounting for about 30% of cases.`, 
        state: `notAnswered`,
        userAnswered: [],
	   type: `MCSS`},
     {
        q: `The most common cause of proteinuria is:`,
        q2: ``,
        q3: [],
        option: [`Fanconi syndrome.`, 
        `excessive glomerular permeability due to primary glomerular disease.`, 
        `failure of adequate tubular reabsorption.`, 
        `overflow proteinuria due to increased plasma concentration of immunoglobulins.`, 
        `diabetes.`],
        optionStyleType: `st-lower-alpha`,
        answer: [1],
        ansText:`Rationale: <!--<b>b. Excessive glomerular permeability due to primary glomerular disease.</b>--> Glomerular proteinuria is the most common type of proteinuria and results from increased glomerular capillary permeability to protein, especially albumin. Glomerular proteinuria occurs in any of the primary glomerular diseases such as IgA nephropathy or in glomerulopathy associated with systemic illness such as diabetes mellitus.`, 
        state: `notAnswered`,
        userAnswered: [],
	   type: `MCSS`},
     {
        q: `Transient proteinuria may be due to all of the following EXCEPT:`,
        q2: ``,
        q3: [],
        option: [`exercise.`, 
        `fever.`, 
        `emotional stress.`, 
        `congestive heart failure (CHF).`, 
        `ureteroscopy.`],
        optionStyleType: `st-lower-alpha`,
        answer: [4],
        ansText:`Rationale: <!--<b>e. Ureteroscopy.</b>--> Transient proteinuria occurs commonly, especially in the pediatric population, and usually resolves spontaneously within a few days. It may result from fever, exercise, or emotional stress. In older patients, transient proteinuria may be due to CHF.`, 
        state: `notAnswered`,
        userAnswered: [],
	   type: `MCSS`},
     {
        q: `Glucose will be detected in the urine when the serum level is above:`,
        q2: ``,
        q3: [],
        option: [`75 mg/dL.`, 
        `100 mg/dL.`, 
        `150 mg/dL.`, 
        `180 mg/dL.`, 
        `225 mg/dL.`],
        optionStyleType: `st-lower-alpha`,
        answer: [3],
        ansText:`Rationale: <!--<b>d. 180 mg/dL.</b>--> This so-called renal threshold corresponds to a serum glucose level of about 180 mg/dL; above this level, glucose will be detected in the urine.`, 
        state: `notAnswered`,
        userAnswered: [],
	   type: `MCSS`},
     {
        q: `The specificity of dipstick nitrite testing for bacteriuria is:`,
        q2: ``,
        q3: [],
        option: [`20%.`, 
        `40%.`, 
        `60%.`, 
        `80%.`, 
        `&gt;90%.`],
        optionStyleType: `st-lower-alpha`,
        answer: [4],
        ansText:`Rationale: <!--<b>e. &gt;90%.</b>--> The specificity of the nitrite dipstick test for detecting bacteriuria is greater than 90%.`, 
        state: `notAnswered`,
        userAnswered: [],
	   type: `MCSS`},
     {
        q: `All of the following are microscopic features of squamous epithelial cells EXCEPT:`,
        q2: ``,
        q3: [],
        option: [`large size.`, 
        `small central nucleus.`, 
        `irregular cytoplasm.`, 
        `presence in clumps.`, 
        `fine granularity in the cytoplasm.`],
        optionStyleType: `st-lower-alpha`,
        answer: [3],
        ansText:`Rationale: <!--<b>d. Presence in clumps.</b>--> Squamous epithelial cells are large, have a central small nucleus about the size of an erythrocyte, and have an irregular cytoplasm with fine granularity.`, 
        state: `notAnswered`,
        userAnswered: [],
	   type: `MCSS`},
     {
        q: `The number of bacteria per high-power microscopic field that corresponds to colony counts of 100,000/mL is:`,
        q2: ``,
        q3: [],
        option: [`1.`, 
        `3.`, 
        `5.`, 
        `10.`, 
        `20.`],
        optionStyleType: `st-lower-alpha`,
        answer: [2],
        ansText:`Rationale: <!--<b>c. 5.</b>--> Therefore five bacteria per high-power field in a spun specimen reflect colony counts of about 100,000/mL.`, 
        state: `notAnswered`,
        userAnswered: [],
	   type: `MCSS`},
     {
        q: `Pain in the flaccid penis is usually due to:`,
        q2: ``,
        q3: [],
        option: [`Peyronie disease.`, 
        `bladder or urethral inflammation.`, 
        `priapism.`, 
        `calculi impacted in the distal ureter.`, 
        `hydrocele.`],
        optionStyleType: `st-lower-alpha`,
        answer: [1],
        ansText:`Rationale: <!--<b>b. Bladder or urethral inflammation.</b>--> Pain in the flaccid penis is usually secondary to inflammation in the bladder or urethra, with referred pain that is experienced maximally at the urethral meatus.`, 
        state: `notAnswered`,
        userAnswered: [],
	   type: `MCSS`},
     {
        q: `Chronic scrotal pain is most often due to:`,
        q2: ``,
        q3: [],
        option: [`testicular torsion.`, 
        `trauma.`, 
        `cryptorchidism.`, 
        `hydrocele.`, 
        `orchitis.`],
        optionStyleType: `st-lower-alpha`,
        answer: [3],
        ansText:`Rationale: <!--<b>d. Hydrocele.</b>--> Chronic scrotal pain is usually related to noninflammatory conditions such as a hydrocele or varicocele, and the pain is usually characterized as a dull, heavy sensation that does not radiate.`, 
        state: `notAnswered`,
        userAnswered: [],
	   type: `MCSS`},
     {
        q: `Terminal hematuria (at the end of the urinary stream) is usually due to:`,
        q2: ``,
        q3: [],
        option: [`bladder neck or prostatic inflammation.`, 
        `bladder cancer.`, 
        `kidney stones.`, 
        `bladder calculi.`, 
        `urethral stricture disease.`],
        optionStyleType: `st-lower-alpha`,
        answer: [0],
        ansText:`Rationale: <!--<b>a. Bladder neck or prostatic inflammation.</b>--> Terminal hematuria occurs at the end of micturition and is usually secondary to inflammation in the area of the bladder neck or prostatic urethra.`, 
        state: `notAnswered`,
        userAnswered: [],
	   type: `MCSS`},
     {
        q: `Enuresis is present in what percentage of children at age 5 years?`,
        q2: ``,
        q3: [],
        option: [`5%`, 
        `15%`, 
        `25%`, 
        `50%`, 
        `75%`],
        optionStyleType: `st-lower-alpha`,
        answer: [1],
        ansText:`Rationale: <!--<b>b. 15%.</b>--> Enuresis refers to urinary incontinence that occurs during sleep. It occurs normally in children as old as 3 years but persists in about 15% of children at age 5 and about 1% of children at age 15.`, 
        state: `notAnswered`,
        userAnswered: [],
	   type: `MCSS`},
     {
        q: `All of the following in the medical history suggest that erectile dysfunction is more likely due to organic rather than psychogenic causes EXCEPT:`,
        q2: ``,
        q3: [],
        option: [`sudden onset.`, 
        `peripheral vascular disease.`, 
        `absence of nocturnal erections.`, 
        `diabetes mellitus.`, 
        `inability to achieve adequate erections in a variety of circumstances.`],
        optionStyleType: `st-lower-alpha`,
        answer: [0],
        ansText:`Rationale: <!--<b>a. Sudden onset.</b>--> A careful history will often determine whether the problem is primarily psychogenic or organic. In men with psychogenic impotence, the condition frequently develops rather quickly, secondary to a precipitating event such as marital stress or change or loss of a sexual partner.`, 
        state: `notAnswered`,
        userAnswered: [],
	   type: `MCSS`},
     {
        q: `All of the following should be routinely performed in men with hematospermia EXCEPT:`,
        q2: ``,
        q3: [],
        option: [`cystoscopy.`, 
        `digital rectal examination.`, 
        `serum prostate-specific antigen (PSA) level.`, 
        `genital examination.`, 
        `urinalysis.`],
        optionStyleType: `st-lower-alpha`,
        answer: [0],
        ansText:`Rationale: <!--<b>a. Cystoscopy.</b>--> A genital and rectal examination should be done to exclude the presence of tuberculosis, a PSA assessment and digital rectal examination should be done to exclude prostatic carcinoma, and a urinary cytologic assessment should be done to exclude the possibility of transitional cell carcinoma of the prostate.`, 
        state: `notAnswered`,
        userAnswered: [],
	   type: `MCSS`},
     {
        q: `Pneumaturia may be due to all of the following EXCEPT:`,
        q2: ``,
        q3: [],
        option: [`diverticulitis.`, 
        `colon cancer.`, 
        `recent urinary tract instrumentation.`, 
        `inflammatory bowel disease.`, 
        `ectopic ureter.`],
        optionStyleType: `st-lower-alpha`,
        answer: [4],
        ansText:`Rationale: <!--<b>e. Ectopic ureter.</b>--> Pneumaturia is the passage of gas in the urine. In patients who have not recently had urinary tract instrumentation or a urethral catheter placed, this is almost always due to a fistula between the intestine and bladder. Common causes include diverticulitis, carcinoma of the sigmoid colon, and regional enteritis (Crohn disease).`, 
        state: `notAnswered`,
        userAnswered: [],
	   type: `MCSS`},
     {
        q: `Which of the following disorders may commonly lead to irritative voiding symptoms?`,
        q2: ``,
        q3: [],
        option: [`Parkinson disease`, 
        `Renal cell carcinoma`, 
        `Bladder diverticula`, 
        `Prostate cancer`, 
        `Testicular torsion`],
        optionStyleType: `st-lower-alpha`,
        answer: [0],
        ansText:`Rationale: <!--<b>a. Parkinson disease.</b>--> The second important example of nonspecific lower urinary tract symptoms that may occur secondary to a variety of neurologic conditions is irritative symptoms resulting from neurologic disease such as cerebrovascular accident, diabetes mellitus, or Parkinson disease.`, 
        state: `notAnswered`,
        userAnswered: [],
	   type: `MCSS`}



];
