var quiz = [
   
    {
        q: `The male urethra is ___ cm long.`,
        q2: ``,
        q3: [],
        option: [`15`, 
        `13`, 
        `24`,  
        `20`],
        optionFeedback: [``,
        ``,
        ``,
        ``,
        ``],
        optionStyleType: `st-upper-alpha`,
        answer: [3],
        ansText:`Rationale: <!--<b>d. 20.</b>--> The male urethra is 18 to 20 cm. The anterior urethra is 16 cm.`, 
        state: `notAnswered`,
        userAnswered: []        ,
        type: `MCSS`},
    {
        q: `The anterior male urethra is surrounded by ____`,
        q2: ``,
        q3: [],
        option: [`the bulbospongiosus muscle.`, 
        `corpus spongiosum.`, 
        `both a and b.`,  
        `none of the above.`],
        optionFeedback: [``,
        ``,
        ``,
        ``,
        ``],
        optionStyleType: `st-upper-alpha`,
        answer: [2],
        ansText:`Rationale: <!--<b>c. Both a and b.</b>--> The anterior male urethra is surrounded by both corpus spongiosum and bulbospongiosus muscle at the bulbar urethra.`, 
        state: `notAnswered`,
        userAnswered: []        ,
        type: `MCSS`},
    {
        q: `The female urethra is approximately ____ cm long`,
        q2: ``,
        q3: [],
        option: [`4`, 
        `6`, 
        `8`, 
        `10`],
        optionFeedback: [``,
        ``,
        ``,
        ``,
        ``],
        optionStyleType: `st-upper-alpha`,
        answer: [0],
        ansText:`Rationale: <!--<b>a. 4.</b>--> The female urethra is approximately 4 cm long`, 
        state: `notAnswered`,
        userAnswered: []        ,
        type: `MCSS`},
    {
        q: `A 16-Fr catheter is approximately ____ cm in outer diameter.`,
        q2: ``,
        q3: [],
        option: [`16`, 
        `10.4`, 
        `8.7`,  
        `5.3`],
        optionFeedback: [``,
        ``,
        ``,
        ``,
        ``],
        optionStyleType: `st-upper-alpha`,
        answer: [3],
        ansText:`Rationale: <!--<b>d. 5.3.</b>--> To calculate French size approximately, divide by 3.`, 
        state: `notAnswered`,
        userAnswered: []
    
            ,
        type: `MCSS`},
    {
        q: `______ is the most rigid catheter material.`,
        q2: ``,
        q3: [],
        option: [`Latex`, 
        `Silicone`, 
        `Polyvinylchloride (PVC)`, 
        `None of the above`],
        optionFeedback: [``,
        ``,
        ``,
        ``,
        ``],
        optionStyleType: `st-upper-alpha`,
        answer: [2],
        ansText:`Rationale: <!--<b>c. Polyvinylchloride (PVC)</b>--> Rigidity from least to greatest: latex, silicone, PVC. This is important to understand, and different catheter materials may be more appropriate for different clinical situations.`, 
        state: `notAnswered`,
        userAnswered: [],
        type: `MCSS`},
    {
        q: `Suprapubic catheter placement with a guide wire is the _______ technique.`,
        q2: ``,
        q3: [],
        option: [`cystotomy`, 
        `Seldinger`, 
        `Lowsley`,  
        `trocar`],
        optionFeedback: [``,
        ``,
        ``,
        ``,
        ``],
        optionStyleType: `st-upper-alpha`,
        answer: [1],
        ansText:`Rationale: <!--<b>b. Seldinger.</b>--> The Seldinger technique involves gaining access into the bladder with a 21-gauge needle. I wire is placed once urine return is identified. Various catheters or kits can be used to place a catheter over the wire. The Lowsley retractor is a modified male urethral sound that can be used to place a suprapubic catheter. There are trocars that can be placed under vision with a cystoscope that can accommodate a catheter once the inner section is removed and the sheath left in place.`, 
        state: `notAnswered`,
        userAnswered: [],
        type: `MCSS`},
    {
        q: `The most common cause of inability to catheterize an Indiana pouch is _____.`,
        q2: ``,
        q3: [],
        option: [`perforation`, 
        `catheter malfunction`, 
        `overdistension`, 
        `none of the above`],
        optionFeedback: [``,
        ``,
        ``,
        ``,
        ``],
        optionStyleType: `st-upper-alpha`,
        answer: [2],
        ansText:`Rationale:<!--<b>c. Overdistension.</b>--> Overdistension is the most common reason for catheterization difficulty. If the catheter is forced, a perforation in the channel will be likely. A 21-gauge needle can be placed into the reservoir. After drainage, a catheter will usually pass without difficulty. `, 
        state: `notAnswered`,
        userAnswered: [],
        type: `MCSS`},
    {
        q: `A urostomy should never be catheterized.`,
        q2: ``,
        q3: [],
        option: [`T`, 
        `F`],
        optionFeedback: [``,
        ``,
        ``,
        ``,
        ``],
        optionStyleType: `st-upper-alpha`,
        answer: [1],
        ansText:`Rationale:<!--<b>b. F.</b>--> Catheterizing a urostomy gently can be performed without risk. Occasionally, catheterizing the stoma may be therapeutic in cases such as stomal stenosis or parastomal hernia. `, 
        state: `notAnswered`,
        userAnswered: [],
        type: `MCSS`},
    {
        q: `Patients after bladder neck reconstruction should never be catheterized per urethra.`,
        q2: ``,
        q3: [],
        option: [`T`, 
        `F`],
        optionFeedback: [``,
        ``,
        ``,
        ``,
        ``],
        optionStyleType: `st-upper-alpha`,
        answer: [0],
        ansText:`Rationale: <!--<b>a. T.</b>--> A history of bladder neck reconstruction is one of the few contraindications to urethral catheterization.`, 
        state: `notAnswered`,
	   userAnswered: [],
	   type: `MCSS`},
    {
        q: `Catheter-associated urinary tract infection is the most common type of health care–associated infection`,
        q2: ``,
        q3: [],
        option: [`T`, 
        `F`],
        optionFeedback: [``,
        ``,
        ``,
        ``,
        ``],
        optionStyleType: `st-upper-alpha`,
        answer: [0],
        ansText:`Rationale:<!--<b>a. T.</b>--> Unfortunately, this is true based on a Centers for Disease Control and Prevention report. Decreasing catheter use should decrease the hospital-acquired infection rates. `, 
        state: `notAnswered`,
        userAnswered: [],
        type: `MCSS`},
    {
        q: `The incidence of bladder cancer in spinal cord patients with chronic catheters is _______.`,
        q2: ``,
        q3: [],
        option: [`1%`, 
        `2%`, 
        `3%`, 
        `4%`, 
        `5%`,
        `6%`],
        optionFeedback: [``,
        ``,
        ``,
        ``,
        ``],
        optionStyleType: `st-upper-alpha`,
        answer: [0],
        ansText:`Rationale: <!--<b>a. 1%.</b>--> There are retrospective studies that do show what appears to be an increased risk of bladder cancer. Some recommend surveillance after 8 years of chronic catheterization.`, 
        state: `notAnswered`,
        userAnswered: [],
    
        type: `MCSS`},
 
]
