var quiz = [
   
    {
        q: `According to AUA guidelines, microhematuria sufficient to trigger a diagnostic evaluation is defined as:`,
        q2: ``,
        q3: [],
        option: [`a positive chemical test (urine dipstick) showing small, moderate, or large blood on one properly collected specimen.`, 
        `a positive chemical test (urine dipstick) showing small, moderate, or large blood on at least two of three properly collected specimens.`, 
        `a positive chemical test (urine dipstick) showing large blood on one properly collected specimen.`, 
        `urine microscopy showing three or more red blood cells per high-powered field on one properly collected urine specimen.`, 
        `urine microscopy showing three or more RBC/HPF on at least two of three properly collected urine specimens.`],
        optionFeedback: [``,
        ``,
        ``,
        ``,
        
        ``],
        optionStyleType: `st-upper-alpha`,
        answer: [3],
        ansText:`Rationale: <!--<b>d. Urine microscopy showing three or more red blood cells per high-powered field on one properly collected urine specimen.</b>--> <b>The presence of three of more RBCs/HPF on a single urine microscopy is associated with malignancy in 2.3-5.5% of patients.</b> Chemical tests for hematuria detect the peroxidase activity of erythrocytes using benzidine, and can render false results in the presence of dehydration, myoglobinuria, high doses of vitamin C, improper technique, and other factors. While higher levels of microhematuria (&gt;25 RBCs/HPF) are known to be associated with higher rates of malignancy on evaluation, setting the threshold higher than three RBCs/HPF or requiring more than one positive urinalysis would lead to an unknown number of missed opportunities for diagnosis.`, 
        state: `notAnswered`,
        userAnswered: []        ,
        type: `MCSS`},
    {
        q: `The likelihood of finding a malignancy in a patient with microhematuria is influenced by all of the following EXCEPT:`,
        q2: ``,
        q3: [],
        option: [`age.`, 
        `gender.`, 
        `use of anticoagulants.`, 
        `tobacco use.`, 
        `degree of hematuria.`],
        optionFeedback: [``,
        ``,
        ``,
        ``,
        
        ``],
        optionStyleType: `st-upper-alpha`,
        answer: [2],
        ansText:`Rationale:<!--<b>c. Use of anticoagulants.</b>--> <b>Increasing age, male gender, and tobacco use are risk factors for urologic cancers and specifically for urothelial carcinoma.</b> In addition, while there is little data to distinguish among thresholds of two, three, four, or five RBCs/HPF, it is clear that a high level of microhematuria (&gt;25 RBCs/HPF) is associated with a greater likelihood of malignancy. By contrast, patients using anticoagulant medications or anti-platelet medications have a similar risk of malignancy compared to those who do not use these medications. Therefore such patients should be evaluated comparably to those who do not use anticoagulants or anti-platelet agents. `, 
        state: `notAnswered`,
        userAnswered: []        ,
        type: `MCSS`},
    {
        q: `According to AUA guidelines, the proper initial assessment of a 50-year-old patient with asymptomatic microhematuria includes:`,
        q2: ``,
        q3: [],
        option: [`blood pressure measurement, serum creatinine level, cystoscopy, and computed tomography (CT) urogram.`, 
        `urine cytology, cystoscopy, and CT urogram.`, 
        `urine cytology, blue-light cystoscopy, and any upper tract imaging.`, 
        `urine cytology and renal/bladder ultrasound.`, 
        `no evaluation is necessary unless microhematuria is persistent/recurrent or hematuria is visible.`],
        optionFeedback: [``,
        ``,
        ``,
        ``,
        
        ``],
        optionStyleType: `st-upper-alpha`,
        answer: [0],
        ansText:`Rationale: <!--<b>a. Blood pressure measurement, serum creatinine level, cystoscopy, and computed tomography (CT) urogram.</b>--> <b>The AUA suggests that adult patients presenting with asymptomatic microhematuria should undergo evaluation to determine the cause.</b> Blood pressure measurement and serum creatinine level may help identify patients who require concurrent nephrologic workup, and creatinine level also helps determine patient eligibility for contrast imaging. The evaluation of asymptomatic hematuria includes imaging (preferably with CT urogram), and cystoscopy in patients 35 and older and those under 35 with risk factors for malignancy.`, 
        state: `notAnswered`,
        userAnswered: []        ,
        type: `MCSS`},
    {
        q: `In the evaluation of patients with microhematuria, cystoscopy may be safely avoided if: <a class="lightboxcallout" img-ref="image_fig_16_2" href="f437c21f50534a2b920e5ef936025654">Fig. 16.2</a>`,
        q2: ``,
        q3: [],
        option: [`there are no associated symptoms in a patient of any age.`, 
        `the patient is under 35 years of age and without symptoms or risk factors for malignancy.`, 
        `the patient is taking aspirin or warfarin.`, 
        `the cytology is negative.`, 
        `the patient has a history of urinary tract infection and hematuria is still present after treatment.`],
        optionFeedback: [``,
        ``,
        ``,
        ``,
        
        ``],
        optionStyleType: `st-upper-alpha`,
        answer: [1],
        ansText:`Rationale: <!--b. -->the patient is under 35 years of age and without symptoms or risk factors for malignancy.
        <!--<b>b. The patient is under 35 years of age and without symptoms or risk factors for malignancy.</b>--> <b>The AUA guidelines (<a class="lightboxcallout" img-ref="image_fig_16_1" href="e24562ad22ec4cb9b4961afb7f9594d8">Fig. 16.1</a>) call for use of cystoscopy for evaluation of hematuria in all patients 35 years of age and older (Recommendation).</b> The risk of malignancy is very low in persons under 35 years of age, such that the potential benefits of cystoscopy may be outweighed by the very small risks associated with the procedure. Therefore it is an option to omit cystoscopy in patients under the age of 35, provided that the patient does not have risk factors for a urologic malignancy.`, 
        state: `notAnswered`,
        userAnswered: []        ,
        type: `MCSS`},
    {
        q: `Patients presenting with gross hematuria in the absence of recent trauma or concurrent infection who are on anticoagulation medications should be evaluated with:`,
        q2: ``,
        q3: [],
        option: [`urinalysis, urine cytology, and cystoscopy only.`, 
        `CT urogram, with cystoscopy only if symptomatic.`, 
        `no evaluation necessary.`, 
        `assessment of anticoagulation status, and evaluation only if supra-therapeutic.`, 
        `urine cytology, cystoscopy, CT urogram.`],
        optionFeedback: [``,
        ``,
        ``,
        ``,
        
        ``],
        optionStyleType: `st-upper-alpha`,
        answer: [4],
        ansText:`Rationale:<!--<b>e. Urine cytology, cystoscopy, CT urogram.</b>--> <b>Given the increased frequency with which clinically significant findings are associated with gross hematuria, the recommended evaluation in this setting is relatively uniform.</b> That is, patients presenting with gross hematuria in the absence of antecedent trauma or culture-documented urinary tract infection should be evaluated with a urine cytology, cystoscopy, and upper tract imaging, preferably CT urogram. Importantly, patients who develop hematuria who are on anticoagulation medications should undergo a complete evaluation in the <b>same manner as patients not taking such medications, as the prevalence</b> of hematuria, as well as the likelihood of finding genitourinary cancers, among patients with hematuria on anticoagulation has been reported to be no different from patients not taking such medications. `, 
        state: `notAnswered`,
        userAnswered: []        ,
        type: `MCSS`},
    {
        q: `The metabolite of oxazaphosphorine chemotherapeutic agents which is responsible for hemorrhagic cystitis is:`,
        q2: ``,
        q3: [],
        option: [`Mesna.`, 
        `Acrolein.`, 
        `Formalin.`, 
        `Gemcitabine.`, 
        `Methotrexate.`],
        optionFeedback: [``,
        ``,
        ``,
        ``,
        
        ``],
        optionStyleType: `st-upper-alpha`,
        answer: [1],
        ansText:`Rationale: <!--<b>b. Acrolein.</b>--> <b>Bladder toxicity from oxazaphosphorine chemotherapeutic agents results from renal excretion of the metabolite acrolein, which is produced by the liver and which stimulates bladder mucosal sloughing and subsequent tissue edema/fibrosis.</b> Mesna (2-mercaptoethane sulfonate), which binds to acrolein and renders it inert, has been suggested for prophylaxis against cyclophosphamide-induced hemorrhagic cystitis.`, 
        state: `notAnswered`,
        userAnswered: [],
        type: `MCSS`},
    {
        q: `Use of intravesical alum for hemorrhagic cystitis should be avoided in patients with:`,
        q2: ``,
        q3: [],
        option: [`a history of malignancy.`, 
        `a history of detrusor instability.`, 
        `active gross hematuria.`, 
        `renal insufficiency.`, 
        `vesicoureteral reflux.`],
        optionFeedback: [``,
        ``,
        ``,
        ``,
        
        ``],
        optionStyleType: `st-upper-alpha`,
        answer: [3],
        ansText:`Rationale:<!--<b>d. Renal insufficiency.</b>--> <b>Alum may be considered for first-line intravesical therapy among patients with hemorrhagic cystitis (</b><a class="lightboxcallout" img-ref="image_fig_16_2" href="f437c21f50534a2b920e5ef936025654">Fig. 16.2</a><b>) failing initial supportive measures.</b> However, while cell penetration and therefore overall toxicity of this agent are low, systemic absorption may nevertheless occur and may result in aluminum toxicity, with consequent mental status changes, particularly among patients with renal insufficiency. Meanwhile, prior to intravesical administration of silver nitrate or of formalin, a cystogram should be obtained to evaluate for the presence of vesicoureteral reflux. `, 
        state: `notAnswered`,
        userAnswered: [],
    
        type: `MCSS`},
    {
        q: `The molecular pathophysiology linking BPH and hematuria is exemplified by the identification of which of the following in the prostate tissue from men with BPH:`,
        q2: ``,
        q3: [],
        option: [`decreased microvessel density`, 
        `androgen-independent angiogenesis`, 
        `elevated VEGF expression`, 
        `reduced cell proliferation`, 
        `diminished blood flow`],
        optionFeedback: [``,
        ``,
        ``,
        ``,
        
        ``],
        optionStyleType: `st-upper-alpha`,
        answer: [3],
        ansText:`Rationale:<!--<b>c. Elevated VEGF expression.</b>--> <b>The etiology for BPH-related hematuria has been thought to be increased prostatic vascularity due to higher microvessel density in hyperplastic prostate tissue.</b> This noted increase in microvessel density has in turn been linked to higher levels of VEGF. Moreover, as the pathophysiology of BPH-related bleeding has been postulated as increased cell proliferation stimulating increased vascularity, efforts to suppress prostate growth via androgen ablation have been explored. Indeed, both estrogens and antiandrogens have, in small case reports, been associated with decreased prostate bleeding, presumably through the repression of androgen-stimulated angiogenesis and the induction of programmed cell death within the prostate. `, 
        state: `notAnswered`,
        userAnswered: [],
        type: `MCSS`},
    {
        q: `A 65-year-old man with a history of BPH has recurrent gross hematuria. The patient is clinically stable, with no transfusion requirement, no clots in urine, and no difficulty with bladder emptying. A hematuria evaluation with CT urogram, cystoscopy, and urine cytology is otherwise unremarkable. The best next step in management is:`,
        q2: ``,
        q3: [],
        option: [`five-alpha reductase inhibitor.`, 
        `alpha-blocker therapy.`, 
        `prostatic artery embolization (PAE).`, 
        `channel TURP.`, 
        `trial of antibiotic therapy.`],
        optionFeedback: [``,
        ``,
        ``,
        ``,
        
        ``],
        optionStyleType: `st-upper-alpha`,
        answer: [0],
        ansText:`Rationale:<!--<b>a. Five-alpha reductase inhibitor.</b>--> <b>Treatment with five-alpha reductase inhibitors has been associated with decreased VEGF expression, prostate microvessel density, and prostatic blood flow.</b> Clinically, multiple series have demonstrated efficacy of finasteride for BPH-related hematuria, with symptom improvement or resolution consistently noted in approximately 90% of patients. As such, in otherwise stable patients, finasteride represents a reasonable first-line therapy for BPH-related gross hematuria after the completion of an initial diagnostic evaluation. Channel TURP has typically been utilized in the setting of prostate cancer, while a “standard” TURP or an alternative form of such endoscopic prostate tissue removal/destruction may be used for patients with persistent bleeding from BPH despite conservative therapies and/or endoscopic fulguration, particularly when additional indications for BPH surgery coexist. In cases with persistent bleeding despite TURP or in the significantly comorbid patient, prostatic artery embolization can be considered. `, 
        state: `notAnswered`,
        userAnswered: [],
        type: `MCSS`},
    {
        q: `A 35-year-old man presents with complaint of penile pain and immediate detumescence during intercourse. Physical examination notes blood at the urethral meatus. The next step should be:`,
        q2: ``,
        q3: [],
        option: [`immediate operative exploration.`, 
        `CT scan of pelvis.`, 
        `retrograde urethrography.`, 
        `obtain serum coagulation parameters.`, 
        `conservative management with serial examinations.`],
        optionFeedback: [``,
        ``,
        ``,
        ``,
        
        ``],
        optionStyleType: `st-upper-alpha`,
        answer: [2],
        ansText:`Rationale: <!--<b>c. Retrograde urethrography.</b>--> <b>The clinical scenario is consistent with an acute penile fracture.</b> Blood at the meatus raises suspicion for concomitant urethral injury that requires investigation by retrograde urethrography prior to planned operative repair. Conservative management poses the risk of untreated urethral and corporal injury that can result in urethral stricture disease and erectile dysfunction.`, 
        state: `notAnswered`,
        userAnswered: [],
        type: `MCSS`},
    {
        q: `A 55-year-old woman presents with intermittent gross hematuria 2 weeks after undergoing a right partial nephrectomy for a 4-cm solid enhancing renal mass. She is afebrile with stable vital signs. She is able to void to completion and her urine is red without clots. Her creatinine is 1.1 mg/dL. The next step should be:`,
        q2: ``,
        q3: [],
        option: [`surgical exploration.`, 
        `renal angiography.`, 
        `continuous bladder irrigation.`, 
        `observation.`, 
        `noncontrast CT scan of the abdomen/pelvis.`],
        optionFeedback: [``,
        ``,
        ``,
        ``,
        
        ``],
        optionStyleType: `st-upper-alpha`,
        answer: [1],
        ansText:`Rationale:<!--<b>b. Renal angiography.</b>--> <b>The clinical scenario is consistent with a renal arteriovenous malformation (AVM).</b> Renal angiography may be both diagnostic and therapeutic in this scenario with ability to coil or embolize this abnormal vascular communication. Observation and bladder irrigation do not address the underlying causative factor while non-contrast CT imaging fails to delineate the vascular anatomy. Surgical exploration has a high likelihood of renal loss and is reserved for cases refractory to angiographic modalities. `, 
        state: `notAnswered`,
        userAnswered: [],
        type: `MCSS`},
]