var quiz = [
   
    {
        q: `During posterior dissection in a robotic salvage radical prostatectomy, an inadvertent rectal injury is encountered. Gross fecal spillage is seen in the surgical field. What does a good management strategy include?`,
        q2: ``,
        q3: [],
        option: [`Closure of rectal mucosa and serosa with non-absorbable sutures`, 
        `Open conversion, colostomy, and delayed repair`, 
        `Broad-spectrum antibiotics are advised for up to 1 month postoperatively`, 
        `Primary closure and omental flap`, 
        `Open approach to radical prostatectomy is preferable in this case given the lower incidence of injuries`],
        optionFeedback: [``,
        ``,
        ``,
        ``,
        
        ``],
        optionStyleType: `st-upper-alpha`,
        answer: [1],
        ansText:`Rationale: <!--<b>b. Open conversion, colostomy, and delayed repair.</b>--> A good management strategy in this case includes open conversion, colostomy, and delayed repair.`, 
        state: `notAnswered`,
        userAnswered: []        ,
        type: `MCSS`},
    {
        q: `Which of the following has the greatest effect on pseudoaneurysm development following partial nephrectomy?`,
        q2: ``,
        q3: [],
        option: [`The open approach versus minimally invasive (1% vs. 5%)`, 
        `Patients with higher nephrometry score are at increased risk`, 
        `Early unclamping even in the presence of arterial bleed`, 
        `Tumor depth has no impact on incidence of pseudoaneurysm`, 
        `Deep suture repair through the renal parenchyma is the best preventative measure`],
        optionFeedback: [``,
        ``,
        ``,
        ``,
        
        ``],
        optionStyleType: `st-upper-alpha`,
        answer: [1],
        ansText:`Rationale:<!--<b>b. Patients with higher nephrometry score are at increased risk.</b>--> Patients with higher nephrometry score are at increased risk for pseudoaneurysm development following partial nephrectomy.`, 
        state: `notAnswered`,
        userAnswered: [],
        type: `MCSS`},
    {
        q: `When obtaining pneumoperitoneum with the VERESS needle:`,
        q2: ``,
        q3: [],
        option: [`the angle of entry for the needle should be near 90 degrees for people with normal body mass index (BMI).`, 
        `the angle of entry for the needle should be near 45 degrees for people with high BMI.`, 
        `the most commonly injured vessel is the right iliac vein.`, 
        `the most commonly injured vessel is the left common iliac vein.`, 
        `this access modality has been increasingly abandoned and replaced by optical trocars.`],
        optionFeedback: [``,
        ``,
        ``,
        ``,
        
        ``],
        optionStyleType: `st-upper-alpha`,
        answer: [3],
        ansText:`Rationale: <!--<b>d. The most commonly injured vessel is the left common iliac vein.</b>--> When obtaining pneumoperitoneum with the Veress needle, the most commonly injured vessel is the left common iliac vein.`, 
        state: `notAnswered`,
        userAnswered: []        ,
        type: `MCSS`},
    {
        q: `What is true about urine leaks after partial nephrectomy?`,
        q2: ``,
        q3: [],
        option: [`They are more likely to cause ileus during open surgery`, 
        `90% of patients will require readmission.`, 
        `The mean postoperative day for presentation is 18 days.`, 
        `Longer warm ischemia times are directly related to the development of urine leaks.`, 
        `This complication is more common in minimally invasive surgery.`],
        optionFeedback: [``,
        ``,
        ``,
        ``,
        
        ``],
        optionStyleType: `st-upper-alpha`,
        answer: [3],
        ansText:`Rationale:<!--<b>d. Longer warm ischemia times are directly related to the development of urine leaks.</b>--> Longer warm ischemia times are directly related to the development of urine leaks after partial nephrectomy. `, 
        state: `notAnswered`,
        userAnswered: [],
        type: `MCSS`},
    {
        q: `Once all attempts for conservative management have failed for ureteral complications, it is agreed that:`,
        q2: ``,
        q3: [],
        option: [`waiting 6 weeks for surgical repair allowing inflammation to subside is reasonable.`, 
        `early surgical repair can be achieved when discovered early within 3 weeks.`, 
        `urinomas do not have to be drained to prevent re-accumulation.`, 
        `there is no increased risk for stricture.`, 
        `robotic approach for Boari flap and psoas hitch should be avoided.`],
        optionFeedback: [``,
        ``,
        ``,
        ``,
        
        ``],
        optionStyleType: `st-upper-alpha`,
        answer: [0],
        ansText:`Rationale: <!--<b>a. Waiting 6 weeks for surgical repair allowing inflammation to subside is reasonable.</b>--> Once all attempts for conservative management have failed for ureteral complications, it is agreed that waiting 6 weeks for surgical repair allowing inflammation to subside is reasonable.`, 
        state: `notAnswered`,
        userAnswered: []        ,
        type: `MCSS`},
    {
        q: `During Psoas hitch procedure, the most commonly injured structure is:`,
        q2: ``,
        q3: [],
        option: [`obturator nerve.`, 
        `ilio-inguinal nerve.`, 
        `pudendal nerve.`, 
        `sympathetic nerves.`, 
        `genito-femoral nerve.`],
        optionFeedback: [``,
        ``,
        ``,
        ``,
        
        ``],
        optionStyleType: `st-upper-alpha`,
        answer: [4],
        ansText:`Rationale:<!--<b>e. Genito-femoral nerve.</b>--> The most commonly injured structure during Psoas hitch procedure is the genito-femoral nerve. `, 
        state: `notAnswered`,
        userAnswered: []        ,
        type: `MCSS`},
    {
        q: `Brachial plexus injuries can be prevented by:`,
        q2: ``,
        q3: [],
        option: [`adequate padding of the arms.`, 
        `arm positioning in external rotation and posterior shoulder displacement.`, 
        `avoiding excess arm abduction of greater than 90 degrees.`, 
        `preferring modified lateral to lateral positions.`, 
        `limiting axillary rolls.`],
        optionFeedback: [``,
        ``,
        ``,
        ``,
        
        ``],
        optionStyleType: `st-upper-alpha`,
        answer: [2],
        ansText:`Rationale:<!--<b>c. Avoiding excess arm abduction of greater than 90 degrees.</b>--> Avoiding excess arm abduction of greater than 90 degrees can prevent brachial plexus injuries. `, 
        state: `notAnswered`,
        userAnswered: []        ,
        type: `MCSS`},
]
