var quiz = [
   
    {
        q: `Percutaneous nephrostomy is not indicated for:`,
        q2: ``,
        q3: [],
        option: [`instillation of intracavitary topical therapy for urothelial carcinoma.`, 
        `Whitaker test.`, 
        `management of fungal bezoars.`, 
        `urinary retention.`,  
        `ureteral injury.`],
        optionFeedback: [``,
        ``,
        ``,
        ``,
        
        ``],
        optionStyleType: `st-upper-alpha`,
        answer: [3],
        ansText:`Rationale: <!--<b>d. Urinary retention.</b>--> Obstruction of the lower urinary tract is best treated by drainage of the bladder rather than the kidney, unless secondary obstruction of the upper tract has developed that is refractory to vesical drainage. The other indications are appropriate ones for percutaneous nephrostomy.`, 
        state: `notAnswered`,
        userAnswered: []        ,
        type: `MCSS`},
    {
        q: `Relative to retrograde ureteral stent placement, percutaneous nephrostomy:`,
        q2: ``,
        q3: [],
        option: [`has a lower success rate.`, 
        `requires less anesthesia.`, 
        `is preferred in cases of ureteral obstruction owing to malignancy.`, 
        `is less commonly complicated by bacteriuria after indwelling for 1 week.`,  
        `is associated with worse health-related quality-of-life scores.`],
        optionFeedback: [``,
        ``,
        ``,
        ``,
        
        ``],
        optionStyleType: `st-upper-alpha`,
        answer: [1],
        ansText:`Rationale:<!--<b>b. Requires less anesthesia.</b>--> Percutaneous nephrostomy can be done under local anesthesia, as opposed to retrograde ureteral stent placement, which usually requires at least intravenous sedation, and commonly general or regional anesthesia. Percutaneous nephrostomy has a greater initial success rate than retrograde ureteral stent placement, at least when the collecting system is dilated. Percutaneous nephrostomy is commonly associated with bacteriuria and has health-related quality-of-life scores that are equivalent to those associated with retrograde ureteral stent placement. Ureteral stents provide satisfactory drainage in most cases of ureteral obstruction owing to malignancy. `, 
        state: `notAnswered`,
        userAnswered: []        ,
        type: `MCSS`},
    {
        q: `Which of the following is correct regarding the orientation of the kidney?`,
        q2: ``,
        q3: [],
        option: [`The right kidney is slightly cephalad to the left kidney.`, 
        `The longitudinal axis is 45 degrees from vertical, with the lower pole lateral to the upper pole.`, 
        `The longitudinal axis is 45 degrees from vertical, with the lower pole anterior to the upper pole.`, 
        `The apposition of the colon to the kidney is greatest on the left side at the upper pole.`, 
        `Immediately posterior to the kidneys are the quadratus lumborum muscle, the psoas muscle, and the diaphragm.`],
        optionFeedback: [``,
        ``,
        ``,
        ``,
        
        ``],
        optionStyleType: `st-upper-alpha`,
        answer: [4],
        ansText:`Rationale: <!--<b>e. Immediately posterior to the kidneys are the quadratus lumborum muscle, the psoas muscle, and the diaphragm.</b>--> The upper poles are anterior to attachments of the diaphragm. It is the left kidney that is slightly cephalad to the right one. The second two statements are correct, except that the angulation is 30 degrees rather than 45 degrees. The apposition of the colon to the kidney varies with location; it is greatest on the left side but at the lower rather than upper pole.`, 
        state: `notAnswered`,
        userAnswered: []        ,
        type: `MCSS`},
    {
        q: `Which of the following is correct regarding the intrarenal collecting system?`,
        q2: ``,
        q3: [],
        option: [`Paired anterior and posterior calyces enter the infundibula approximately 90 degrees from each other.`, 
        `Compound calyces are most common in the lower pole`, 
        `Most kidneys have three distinct infundibula: the upper, middle, and lower.`, 
        `There are 8 to 16 minor calyces.`, 
        `There is a consistent relationship between anterior and posterior calyces and their medial-lateral position on anterior-posterior radiography.`],
        optionFeedback: [``,
        ``,
        ``,
        ``,
        
        ``],
        optionStyleType: `st-upper-alpha`,
        answer: [0],
        ansText:`Rationale: <!--<b>a. Paired anterior and posterior calyces enter the infundibula approximately 90 degrees from each other.</b>--> The paired anterior and posterior calyces enter approximately 90 degrees from each other. <b>Although compound calyces are common in the lower pole, they are almost always present in the upper pole.</b> In approximately two-thirds of kidneys, there are only two major calyceal systems (upper and lower). There are 5 to 14 minor calyces in each kidney. Because variation is considerable, the lateral-medial orientation of the calyces on anteroposterior radiography cannot be used to reliably determine which calyces are posterior.`, 
        state: `notAnswered`,
        userAnswered: []        ,
        type: `MCSS`},
    {
        q: `The correct order of the division of the intrarenal branches of the renal artery is:`,
        q2: ``,
        q3: [],
        option: [`segmental, arcuate, interlobar (infundibular), interlobular.`, 
        `segmental, arcuate, interlobular, interlobar (infundibular).`, 
        `segmental, interlobar (infundibular), arcuate, interlobular.`, 
        `interlobular, segmental, interlobar (infundibular), arcuate.`,  
        `segmental, interlobular, interlobar (infundibular), arcuate.`],
        optionFeedback: [``,
        ``,
        ``,
        ``,
        
        ``],
        optionStyleType: `st-upper-alpha`,
        answer: [2],
        ansText:`Rationale: <!--<b>c. Segmental, interlobar (infundibular), arcuate, interlobular.</b>-->`, 
        state: `notAnswered`,
        userAnswered: []        ,
        type: `MCSS`},
    {
        q: `To reduce the risk of infectious complications from percutaneous renal surgery:`,
        q2: ``,
        q3: [],
        option: [`all patients should receive prophylactic antimicrobials.`, 
        `urine cultures should be obtained on all patients.`, 
        `urine must be sterile before the procedure.`, 
        `gentamicin is an acceptable single agent for antimicrobial prophylaxis.`, 
        `ampicillin/sulbactam is not an acceptable single agent for antimicrobial prophylaxis.`],
        optionFeedback: [``,
        ``,
        ``,
        ``,
        
        ``],
        optionStyleType: `st-upper-alpha`,
        answer: [0],
        ansText:`Rationale:<!--<b>a. All patients should receive prophylactic antimicrobials.</b>--> The American Urological Association recommends periprocedural antimicrobial prophylaxis for all cases of percutaneous renal surgery. Urine cultures are considered standard only in patients where bacteriuria is likely; in other cases a screening urinalysis likely is adequate, with urine culture when the urinalysis is suspicious. The urine cannot be sterilized in some patients, especially in the presence of an externalized urinary catheter or an infected calculus, and the goal in these situations is only to suppress the bacterial count before intervention. Aminoglycosides (e.g., gentamicin) are acceptable for antimicrobial prophylaxis when combined with another agent. Ampicillin/sulbactam, first- and second-generation cephalosporins, and fluoroquinolones are acceptable single agents for antimicrobial prophylaxis. `, 
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `To reduce the risk of hemorrhagic complications associated with percutaneous renal access, the minimum recommended preoperative cessation period for:`,
        q2: ``,
        q3: [],
        option: [`herbal medications is 2 weeks.`, 
        `clopidogrel is 10 days.`, 
        `aspirin is 5 days.`, 
        `warfarin is 5 days.`, 
        `nonsteroidal inflammatory agents is 1 day.`],
        optionFeedback: [``,
        ``,
        ``,
        ``,
        
        ``],
        optionStyleType: `st-upper-alpha`,
        answer: [3],
        ansText:`Rationale: <!--<b>d. Warfarin is 5 days.</b>--> The recommended preoperative cessation periods are as follows: herbal medicines, 1 week; clopidogrel, 5 days; aspirin, 1 week; warfarin, 5 days; nonsteroidal inflammatory agents, 3 to 7 days.`, 
        state: `notAnswered`,
        userAnswered: [],
        type: `MCSS`},
    {
        q: `Which of the following have NOT been demonstrated in randomized controlled clinical trials to reduce pain associated with percutaneous renal access?`,
        q2: ``,
        q3: [],
        option: [`Tract infiltration with local anesthetic`, 
        `Intercostal nerve block`, 
        `Thoracic paravertebral block`, 
        `Balloon dilation compared with semirigid plastic dilation of the access tract`,  
        `Smaller, compared with larger, caliber postprocedure nephrostomy tubes`],
        optionFeedback: [``,
        ``,
        ``,
        ``,
        
        ``],
        optionStyleType: `st-upper-alpha`,
        answer: [3],
        ansText:`Rationale: <!--<b>d. Balloon dilation compared with semirigid plastic dilation of the access tract.</b>--> There is no evidence that balloon dilation is associated with less pain compared with semirigid plastic dilation of the access tract. All of the other maneuvers have been demonstrated in randomized controlled clinical trials to reduce pain associated with percutaneous renal access.`, 
        state: `notAnswered`,
        userAnswered: [],
    
        type: `MCSS`},
    {
        q: `An advantage of the supine versus prone position for percutaneous renal surgery is:`,
        q2: ``,
        q3: [],
        option: [`improved pulmonary mechanics.`, 
        `a large horizontal working surface.`, 
        `easier entry into upper pole calyces.`, 
        `easier entry into posterior calyces.`, 
        `reduced pressure in the collecting system.`],
        optionFeedback: [``,
        ``,
        ``,
        ``,
        
        ``],
        optionStyleType: `st-upper-alpha`,
        answer: [4],
        ansText:`Rationale:<!--<b>e. Reduced pressure in the collecting system.</b>--> The angle of the sheath is more horizontal in the supine compared with the prone position for percutaneous renal surgery, which reduces pressure in the collecting system (the volume also is reduced, which is a disadvantage). When padding is appropriate, pulmonary mechanics are better in the prone position. The prone position also provides a large horizontal working surface and easier entry into posterior and upper pole calyces compared to the supine position. `, 
        state: `notAnswered`,
        userAnswered: [],
    
        type: `MCSS`},
    {
        q: `<!--10. -->Access into which site provides the optimal versatility and safety for percutaneous renal surgery in the prone position?`,
        q2: ``,
        q3: [],
        option: [`Upper pole posterior calyx`, 
        `Upper pole infundibulum`, 
        `Renal pelvis`, 
        `Middle calyx`,  
        `Lower pole anterior calyx`],
        optionFeedback: [``,
        ``,
        ``,
        ``,
        
        ``],
        optionStyleType: `st-upper-alpha`,
        answer: [0],
        ansText:`Rationale: <!--<b>a. Upper pole posterior calyx.</b>--> This offers the most versatile access to the intrarenal collecting system, and as long as the entry is below the 11th rib, the advantages generally outweigh the risks. Percutaneous access into an infundibulum or the renal pelvis poses a greater risk of vascular injury than calyceal entry. Middle calyceal access provides good access to the ureter but usually does not provide good access to the upper and lower calyces. In the prone position an anterior calyx offers little access to the rest of the kidney.`, 
        state: `notAnswered`,
        userAnswered: [],
    
        type: `MCSS`},
    {
        q: `Techniques for retrograde assistance for percutaneous renal access include all but which of the following?`,
        q2: ``,
        q3: [],
        option: [`Straight ureteral catheter to inject air`, 
        `Ureteral access sheath to facilitate drainage`, 
        `Ureteroscopy to retrieve guidewire`, 
        `Retrograde approach to percutaneous access`,  
        `Retrograde placement of externalized (single pigtail) ureteral stent for drainage`],
        optionFeedback: [``,
        ``,
        ``,
        ``,
        
        ``],
        optionStyleType: `st-upper-alpha`,
        answer: [4],
        ansText:`Rationale:<!--<b>e. Retrograde placement of externalized (single pigtail) ureteral stent for drainage.</b>--> This can be performed at the conclusion of the procedure for drainage as an alternative to a nephrostomy tube, but it is not useful before access because the pigtail might interfere with the procedure and it would not have any advantage over a straight ureteral catheter or an occlusion balloon catheter. The other choices are all well-described techniques of retrograde assistance for percutaneous renal access. `, 
        state: `notAnswered`,
        userAnswered: [],
    
        type: `MCSS`},
    {
        q: `Compared with an 18-gauge needle, the 21-gauge needle for percutaneous renal access:`,
        q2: ``,
        q3: [],
        option: [`should not be used by inexperienced operators.`, 
        `requires a 0.025-inch guidewire.`, 
        `cannot be directed as easily.`, 
        `entails less risk of loss of access.`, 
        `is more traumatic.`],
        optionFeedback: [``,
        ``,
        ``,
        ``,
        
        ``],
        optionStyleType: `st-upper-alpha`,
        answer: [2],
        ansText:`Rationale: <!--<b>c. cannot be directed as easily.</b>--> A 21-gauge needle is not as easy to direct as an 18-gauge needle because it is more flexible. A 21-gauge needle requires a 0.018-inch guidewire, and because of this extra step (exchanging the 0.018-inch guidewire for a 0.035-inch guidewire) there is a greater risk of loss of access. Compared with an 18-gauge needle, the 21-gauge needle is less traumatic; this is its primary advantage, and it is for this reason that the 21-gauge needle should be used when the operator is less experienced or if minimizing trauma is paramount.`, 
        state: `notAnswered`,
        userAnswered: [],
    
        type: `MCSS`},
    {
        q: `Compared with ultrasonography, fluoroscopy for percutaneous renal access:`,
        q2: ``,
        q3: [],
        option: [`is less suited in the morbidly obese.`, 
        `provides more rapid evaluation of the entire kidney.`, 
        `cannot be used to monitor tract dilation.`, 
        `visualizes the access needle better.`, 
        `is preferred in transplant kidneys.`],
        optionFeedback: [``,
        ``,
        ``,
        ``,
        
        ``],
        optionStyleType: `st-upper-alpha`,
        answer: [3],
        ansText:`Rationale:<!--<b>d. Visualizes the access needle better.</b>--> It is easier to see a needle and monitor tract dilation with fluoroscopy than with ultrasonography. Percutaneous access is always more difficult in the morbidly obese, and ultrasonography is no better than fluoroscopy in this situation. Ultrasonography is more portable, can more rapidly evaluate different views of the kidney, and is preferred in settings in which retrograde access cannot be attained or is difficult to attain (kidneys above urinary diversions, transplanted kidneys, kidneys above a completely obstructed ureter, etc.). `, 
        state: `notAnswered`,
        userAnswered: [],
    
        type: `MCSS`},
    {
        q: `The “triangulation” technique for fluoroscopic percutaneous renal access:`,
        q2: ``,
        q3: [],
        option: [`increases radiation exposure to the operator’s hands compared with the “eye-of-the-needle” technique.`, 
        `cannot be performed in malrotated kidneys.`, 
        `is not as dependent on retrograde assistance as the “eye-of-the-needle” technique.`, 
        `is less suitable than the “eye-of-the-needle” technique in morbidly obese patients.`,  
        `continuously monitors depth of needle penetration.`],
        optionFeedback: [``,
        ``,
        ``,
        ``,
        
        ``],
        optionStyleType: `st-upper-alpha`,
        answer: [4],
        ansText:`Rationale: <!--<b>e. Continuously monitors depth of needle penetration.</b>--> The “triangulation” technique monitors depth of needle placement in all fluoroscopic views, whereas the “eye-of-the-needle” technique assesses depth only at the final step. If the fluoroscopy field is collimated down and the needle is held with a hemostat, sponge forceps, or purpose-built needle holder, then radiation exposure to the operator’s hands can be avoided with both techniques. Retrograde assistance is useful with any fluoroscopic percutaneous renal access, and both techniques are more difficult in morbidly obese patients.`, 
        state: `notAnswered`,
        userAnswered: [],
    
        type: `MCSS`},
    {
        q: `Dilation of the tract for percutaneous renal surgery is:`,
        q2: ``,
        q3: [],
        option: [`not effective with a balloon dilator in hypermobile kidneys.`, 
        `most effective with semirigid dilator.`, 
        `least expensive with metal dilators.`, 
        `most rapid with metal dilators.`, 
        `easiest with a one-shot semirigid dilator.`],
        optionFeedback: [``,
        ``,
        ``,
        ``,
        
        ``],
        optionStyleType: `st-upper-alpha`,
        answer: [2],
        ansText:`Rationale:<!--<b>c. Least expensive with metal dilators.</b>--> Metal dilators are least expensive on a per-case basis because they are reusable. The metal dilators are also the most effective dilators. It is uncertain which are the safest dilators, at least in terms of association with hemorrhage. The balloon dilators are more effective in hypermobile kidneys than other techniques and also more rapid than sequential passage of metal or semirigid dilators. The one-shot semirigid dilator technique requires considerable manual force to create the tract. `, 
        state: `notAnswered`,
        userAnswered: [],
    
        type: `MCSS`},
    {
        q: `When considering percutaneous renal surgery in horseshoe kidneys:`,
        q2: ``,
        q3: [],
        option: [`upper pole access is dangerous.`, 
        `lower pole access is preferred in most cases.`, 
        `computed tomography can be misleading.`, 
        `the puncture site is more lateral than in normal kidneys.`, 
        `lower hemorrhage rates than in normal kidneys can be expected.`],
        optionFeedback: [``,
        ``,
        ``,
        ``,
        
        ``],
        optionStyleType: `st-upper-alpha`,
        answer: [4],
        ansText:`Rationale:<!--<b>e. Lower hemorrhage rates than in normal kidneys can be expected.</b>--> The rate of major hemorrhagic complications during percutaneous renal surgery in horseshoe kidneys (4.3%) is less than in normal kidneys (6% to 20%). Upper pole access is useful, and direct lower pole access is usually not possible. Cross-sectional imaging is useful in assessing the anatomy of horseshoe kidneys. <b>The initial entry into a horseshoe kidney usually is more medial than in normal kidneys.</b> `, 
        state: `notAnswered`,
        userAnswered: [],
    
        type: `MCSS`},
    {
        q: `When considering percutaneous renal surgery in transplant kidneys:`,
        q2: ``,
        q3: [],
        option: [`retrograde assistance is difficult.`, 
        `fluoroscopy is more useful than ultrasonography for initial access.`, 
        `the typical hypermobility renders tract dilation difficult.`, 
        `semirigid plastic dilators should not be used.`, 
        `secondary procedures are usually required.`],
        optionFeedback: [``,
        ``,
        ``,
        ``,
        
        ``],
        optionStyleType: `st-upper-alpha`,
        answer: [0],
        ansText:`Rationale: <!--<b>a. Retrograde assistance is difficult.</b>--> Because of the site of ureteral implantation in the bladder, retrograde assistance for percutaneous renal surgery in transplant kidneys is difficult. Given this, ultrasonography is more useful than fluoroscopy for guiding initial access. Semirigid plastic and metal dilators are often more useful than balloon dilators because of the perinephric scarring, which makes the transplant kidney quite fixed in place rather than hypermobile. Despite the challenges, percutaneous renal surgery in transplant kidneys has a high success rate, and secondary procedures are usually not required.`, 
        state: `notAnswered`,
        userAnswered: [],
    
        type: `MCSS`},
    {
        q: `Foley catheters for postprocedure nephrostomy drainage:`,
        q2: ``,
        q3: [],
        option: [`do not need to be secured at the skin.`, 
        `can have a ureteral catheter passed through the end.`, 
        `should have the balloon filled with dilute contrast material.`, 
        `stay more securely in the kidney than Malecot catheters.`,  
        `are less likely to become infected than Malecot catheters.`],
        optionFeedback: [``,
        ``,
        ``,
        ``,
        
        ``],
        optionStyleType: `st-upper-alpha`,
        answer: [3],
        ansText:`Rationale:<!--<b>d. Stay more securely in the kidney than Malecot catheters.</b>--> Malecot tubes are the easiest to pull out, and circle nephrostomy tubes are the hardest. All tubes should be secured at the skin to reduce the risk of at least one mechanism of tube removal. A ureteral catheter can be passed through the end hole of a Councill catheter; a Foley catheter does not have this end hole. Saline or water should be used to inflate the balloon, because the more viscous contrast material might hinder emptying of the balloon when removal is attempted. All nephrostomy tubes, even ones with robust internal retention devices, should be fixed to the skin externally with a suture or other mechanism. There is no evidence that Foley and Malecot catheters differ in propensity for infection. `, 
        state: `notAnswered`,
        userAnswered: [],
    
        type: `MCSS`},
    {
        q: `The Cope retention mechanism:`,
        q2: ``,
        q3: [],
        option: [`is used in nephroureteral stents.`, 
        `is used in internal ureteral stents.`, 
        `is more secure than a balloon catheter.`, 
        `requires cutting the tube to disengage.`, 
        `should not be used in more than one access site.`],
        optionFeedback: [``,
        ``,
        ``,
        ``,
        
        ``],
        optionStyleType: `st-upper-alpha`,
        answer: [0],
        ansText:`Rationale:<!--<b>a. Is used in nephroureteral stents.</b>--> The Cope retention mechanism is used in the renal pelvic portion of nephroureteral stents. According to one study, the Cope retention mechanism is more secure than Malecot wings but does not retain as well as a balloon. It is more secure than a passive pigtail retention mechanism owing to the string that holds the coil in place. There is no evidence that more than one Cope-type nephrostomy tube should not be used. `, 
        state: `notAnswered`,
        userAnswered: [],
    
        type: `MCSS`},
    {
        q: `Alternatives to a nephrostomy tube after percutaneous renal surgery include all EXCEPT:`,
        q2: ``,
        q3: [],
        option: [`maintenance of the working sheath.`, 
        `an internal ureteral stent that is removed cystoscopically.`, 
        `an internal ureteral stent with an attached string that exits out the flank.`, 
        `a ureteral stent externalized out the urethra.`, 
        `no drainage tube at all.`],
        optionFeedback: [``,
        ``,
        ``,
        ``,
        
        ``],
        optionStyleType: `st-upper-alpha`,
        answer: [0],
        ansText:`Rationale:<!--<b>a. Maintenance of the working sheath.</b>--> The stiff working access sheath would be a poor choice for postprocedure collecting system drainage. All of the other options have been described. `, 
        state: `notAnswered`,
        userAnswered: [],
    
        type: `MCSS`},
    {
        q: `A postoperative nephrostomy tube:`,
        q2: ``,
        q3: [],
        option: [`offers greater assurance of upper urinary tract drainage than an internal ureteral stent.`, 
        `should be placed in the dilated access site.`, 
        `does not maintain the percutaneous access tract unless &gt;18 Fr.`, 
        `reduces postoperative bleeding.`, 
        `is associated with pain unrelated to tube diameter.`],
        optionFeedback: [``,
        ``,
        ``,
        ``,
        
        ``],
        optionStyleType: `st-upper-alpha`,
        answer: [0],
        ansText:`Rationale:<!--<b>a. Offers greater assurance of upper urinary tract drainage than an internal ureteral stent.</b>--> Drainage of upper urinary tract after percutaneous renal surgery is adequate with an internal ureteral stent in most cases (or with no tube at all in selected cases), but when hemorrhage occurs, the larger caliber of a nephrostomy tube provides better drainage of the upper urinary tract collecting system than an internal ureteral stent. The nephrostomy tube does not have to be placed in the dilated access site (i.e., it can be placed at a new site), although that is common practice. Although redilation may be required, any external nephrostomy tube maintains the percutaneous access tract. There is actually less hemorrhage when a postoperative nephrostomy tube is omitted. Most studies suggest that the pain associated with nephrostomy tubes is related to tube diameter, with smaller-caliber tubes causing less pain. `, 
        state: `notAnswered`,
        userAnswered: [],
        type: `MCSS`},
    {
        q: `A small-caliber (8 to 18 Fr) compared with a large-caliber (20 to 24 Fr) nephrostomy tube after percutaneous renal surgery is associated with:`,
        q2: ``,
        q3: [],
        option: [`equivalent pain.`, 
        `more urinary leakage.`, 
        `less postprocedure blood loss.`, 
        `less need for removal in the radiology suite.`, 
        `earlier hospital discharge.`],
        optionFeedback: [``,
        ``,
        ``,
        ``,
        
        ``],
        optionStyleType: `st-upper-alpha`,
        answer: [3],
        ansText:`Rationale: <!--<b>d. Less need for removal in the radiology suite.</b>--> The removal of larger tubes occasionally can be followed by immediate hemorrhage; this is rare with smaller tubes. Therefore large-caliber nephrostomy tubes should be removed in a radiology suite where there is the opportunity for immediate replacement of the tube. Small-caliber tubes can be removed safely at the bedside after a period of clamping to assess clinically for distal ureteral obstruction. A number of studies have compared the impact of nephrostomy tube diameter after percutaneous renal surgery. Only one study found no benefit to the smaller tube. Otherwise, consistent advantages of the small-caliber tubes were less pain, less urinary leakage, and no change in postprocedure blood loss. There is no consistent evidence that small-caliber tubes are associated with shorter duration of hospitalization compared with large-caliber tubes.`, 
        state: `notAnswered`,
        userAnswered: [],
    
        type: `MCSS`},
    {
        q: `Adjuncts intended to enhance hemostasis of the percutaneous tract include all EXCEPT:`,
        q2: ``,
        q3: [],
        option: [`direct cauterization of the tract.`, 
        `microwave treatment of the tract.`, 
        `cryotreatment of the tract.`, 
        `insertion of oxidized cellulose.`, 
        `instillation of fibrin glue.`],
        optionFeedback: [``,
        ``,
        ``,
        ``,
        
        ``],
        optionStyleType: `st-upper-alpha`,
        answer: [1],
        ansText:`Rationale:<!--<b>b. Microwave treatment of the tract.</b>--> Microwave treatment of the tract would be difficult with current instruments. The other options have all been described. Other hemostatic agents that have been inserted/instilled into the tract include gelatin sponge and gelatin granules plus thrombin. `, 
        state: `notAnswered`,
        userAnswered: [],
    
        type: `MCSS`},
    {
        q: `Compared with internal ureteral stents after percutaneous renal surgery, nephrostomy tubes are associated with:`,
        q2: ``,
        q3: [],
        option: [`reduced need for a second procedure for removal.`, 
        `greater technical success rate.`, 
        `greater narcotic use.`, 
        `fewer complications.`, 
        `less urinary leakage from skin entry site.`],
        optionFeedback: [``,
        ``,
        ``,
        ``,
        
        ``],
        optionStyleType: `st-upper-alpha`,
        answer: [2],
        ansText:`Rationale:<!--<b>c. Greater narcotic use.</b>--> Most randomized controlled trials comparing internal ureteral stents to large-caliber nephrostomy tubes after percutaneous renal surgery have shown reduced narcotic use in the stented patients. The difference is less significant when a small-caliber nephrostomy tube is used. Depending on physician preference, both internal ureteral stents (if attached to a string that exits via the flank) and small-caliber nephrostomy tubes can be removed at the bedside. Randomized controlled trials comparing internal ureteral stents to nephrostomy tubes have not revealed any difference in technical success rates, complication rates, or incidence of urinary leakage from the skin entry site. `, 
        state: `notAnswered`,
        userAnswered: [],
    
        type: `MCSS`},
    {
        q: `Following an unremarkable percutaneous nephrolithotomy, there is nonpulsatile bleeding from the tract when the sheath is removed around a 12-Fr nephrostomy tube. The next step is:`,
        q2: ``,
        q3: [],
        option: [`replace the nephrostomy tube with an 18-Fr Malecot catheter.`, 
        `replace the nephrostomy tube with a ureteral stent and suture the skin.`, 
        `irrigate the nephrostomy tube./`, 
        `occlude the nephrostomy tube and apply pressure to the incision.`, 
        `replace the nephrostomy tube with a Kaye nephrostomy tamponade balloon.`],
        optionFeedback: [``,
        ``,
        ``,
        ``, 
        ``],
        optionStyleType: `st-upper-alpha`,
        answer: [3],
        ansText:`Rationale:<!--<b>d. Occlude the nephrostomy tube and apply pressure to the incision.</b>--> The first step in this situation is to occlude the nephrostomy tube and apply pressure to the incision. Let the collecting system clot off, and do not irrigate until the following morning. This management is successful in the majority of cases. If bleeding persists, then insert a Kaye nephrostomy tamponade balloon. An 18-Fr Malecot catheter will be no more effective than the 12-Fr Cope nephrostomy tube. Irrigation is not useful, and removing the nephrostomy tube altogether is ill advised.`, 
        state: `notAnswered`,
        userAnswered: [],
    
        type: `MCSS`},
    {
        q: `During a percutaneous resection of a 2-cm upper pole urothelial neoplasm, there is sudden hemorrhage from the resection site. The next step is:`,
        q2: ``,
        q3: [],
        option: [`continue with the procedure if vision is adequate.`, 
        `insert a percutaneous nephroureteral stent.`, 
        `instill gelatin granules plus thrombin into the collecting system.`, 
        `place an 18-Fr Councill catheter with the balloon inflated at the injury site.`, 
        `prepare the patient for selective angioembolization.`],
        optionFeedback: [``,
        ``,
        ``,
        ``,
        
        ``],
        optionStyleType: `st-upper-alpha`,
        answer: [0],
        ansText:`Rationale: <!--<b>a. Continue with the procedure if vision is adequate.</b>--> If the procedure can be continued with acceptable vision, then the blood loss cannot be great. However, if vision is lost, then the procedure must be aborted. If so, then inserting and occluding a nephrostomy tube, as well as applying pressure to the incision so that the collecting system clots off, will suffice in most cases. If this is not successful, then place a Councill catheter and attempt to inflate the balloon at the injury site. Instillation of gelatin granules plus thrombin into the collecting system can create a clot that is difficult to manage. Selective angioembolization is required only when an arterial injury does not respond to less intensive management, or if the injury is obviously a significant one that will not respond to these maneuvers.`, 
        state: `notAnswered`,
        userAnswered: [],
    
        type: `MCSS`},
    {
        q: `A 65-year-old man calls the office 1 week after percutaneous nephrolithotomy complaining of bright red blood in the urine on his last two urinations. He is otherwise feeling well. He should next:`,
        q2: ``,
        q3: [],
        option: [`check the percutaneous access site and come to the hospital if there is external bleeding.`, 
        `force fluids and call back if bleeding persists.`, 
        `take aminocaproic acid (Amicar).`, 
        `apply pressure to the percutaneous access site.`,  
        `come to the hospital.`],
        optionFeedback: [``,
        ``,
        ``,
        ``,
        
        ``],
        optionStyleType: `st-upper-alpha`,
        answer: [4],
        ansText:`Rationale: <!--<b>e. Come to the hospital.</b>--> Any report of bright red blood in the urine after percutaneous renal surgery should prompt hospital admission. This man likely has an arteriovenous fistula or arterial pseudoaneurysm. The conservative measures are not likely to be helpful, and aminocaproic acid (Amicar) is contraindicated in the setting of upper tract hemorrhage.`, 
        state: `notAnswered`,
        userAnswered: [],
    
        type: `MCSS`},
    {
        q: `Which of the following has NOT been reported to cause renal pelvic perforation in association with percutaneous renal surgery?`,
        q2: ``,
        q3: [],
        option: [`Wire passage`, 
        `Tract dilation`, 
        `Massive hemorrhage`, 
        `Use of resectoscope`, 
        `Ultrasonic lithotripsy`],
        optionFeedback: [``,
        ``,
        ``,
        ``,
        
        ``],
        optionStyleType: `st-upper-alpha`,
        answer: [2],
        ansText:`Rationale: <!--<b>c. Massive hemorrhage.</b>--> The renal pelvis will clot off before the pressure from hemorrhage would rupture it. Any manipulation during percutaneous renal surgery can cause renal pelvic perforation.`, 
        state: `notAnswered`,
        userAnswered: [],
    
        type: `MCSS`},
    {
        q: `Two days after percutaneous endopyelotomy in a 65-year-old woman, nephrostography reveals contrast entering the colon. The next step is to:`,
        q2: ``,
        q3: [],
        option: [`perform exploratory laparotomy.`, 
        `maintain the nephrostomy tube in place and insert a ureteral stent.`, 
        `maintain the nephrostomy tube in place and insert a colostomy tube.`, 
        `back out the nephrostomy tube into the colon and insert a new nephrostomy tube.`, 
        `start parenteral feeding, after appropriate tube insertions.`],
        optionFeedback: [``,
        ``,
        ``,
        ``,
        
        ``],
        optionStyleType: `st-upper-alpha`,
        answer: [3],
        ansText:`Rationale:<!--<b>d. Back out the nephrostomy tube into the colon and insert a new nephrostomy tube.</b>--> <b>The main principle of care of a colon injury associated with percutaneous renal surgery is prompt and separate drainage of the colon and urinary collecting system.</b> If detected postoperatively, the simplest management is to back the nephrostomy tube out of the kidney and into the colon to serve as a colostomy, and then obtain separate access to the upper urinary tract, with either a new percutaneous access that does not traverse the colon or a retrograde-placed ureteral stent. Parenteral feeding is usually not required, and for the typical extraperitoneal injury, open surgical repair usually is needed only if the patient develops peritonitis or sepsis. `, 
        state: `notAnswered`,
        userAnswered: [],
    
        type: `MCSS`},
    {
        q: `Injury to which organ during percutaneous renal surgery can often be managed with little additional interventions?`,
        q2: ``,
        q3: [],
        option: [`Liver`, 
        `Spleen`, 
        `Duodenum`, 
        `Jejunum`, 
        `Gallbladder`],
        optionFeedback: [``,
        ``,
        ``,
        ``,
        
        ``],
        optionStyleType: `st-upper-alpha`,
        answer: [0],
        ansText:`Rationale:<!--<b>a. Liver.</b>--> Although splenic injuries have been managed conservatively, the need for surgical intervention is more likely than with liver injuries. Injuries to small bowel or the biliary system require prompt treatment. `, 
        state: `notAnswered`,
        userAnswered: [],
    
        type: `MCSS`},
    {
        q: `Regarding pleural injuries in association with percutaneous renal surgery:`,
        q2: ``,
        q3: [],
        option: [`access below the 12th rib results in hydropneumothorax in 1% to 2% of cases.`, 
        `supra-12th rib punctures (the 11th intercostal space) result in hydropneumothorax in 20% to 40% of cases.`, 
        `supra-11th rib punctures (the 10th intercostal space) result in hydropneumothorax in 50% to 75% of cases.`, 
        `combined with distal ureteral obstruction, a nephropleural fistula can occur.`, 
        `thoracostomy to water seal drainage and suction is recommended.`],
        optionFeedback: [``,
        ``,
        ``,
        ``,
        
        ``],
        optionStyleType: `st-upper-alpha`,
        answer: [3],
        ansText:`Rationale: combined with distal ureteral obstruction, a nephropleural fistula can occur.
        <!--<b>d. Combined with distal ureteral obstruction, a nephropleural fistula can occur.</b>--> Nephropleural fistula (urinothorax) is a direct and persistent communication between the intrarenal collecting system and the intrathoracic cavity, which can follow percutaneous renal access of the upper urinary tract in the setting of pleural transgression. Some degree of distal ureteral obstruction usually contributes to the problem. The rates of pleural injures for infra-12th rib, supra-12th rib, and supra-11th rib punctures are approximately less than 0.5%, 5%, and 25%, respectively. Thoracostomy is not necessary for all patients with hydrothorax. If one is needed, then a small-caliber tube with a Heimlich valve is all that is required in the absence of lung injury. `, 
        state: `notAnswered`,
        userAnswered: [],
        type: `MCSS`},
    {
        q: `Irrigation fluid during percutaneous renal surgery:`,
        q2: ``,
        q3: [],
        option: [`is not absorbed systemically unless there is significant venous injury.`, 
        `should be normal saline except during percutaneous nephrolithotomy.`, 
        `can have fatal consequences.`, 
        `should not be glycine.`,     
        `will not create a defined extrarenal collection.`],
        optionFeedback: [``,
        ``,
        ``,
        ``,
        
        ``],
        optionStyleType: `st-upper-alpha`,
        answer: [2],
        ansText:`Rationale: <!--<b>c. Can have fatal consequences.</b>--> <b>Intravascular hemolysis from the extravasated water irrigant can be fatal. The irrigant for percutaneous renal surgery should be saline, with the exception of glycine or similar nonelectrolytic isotonic fluids when monopolar electrocautery is used.</b> Intravascular or extravascular extravasation of fluid from continued irrigation in the setting of a large venous injury or collecting system perforation can lead to clinically significant sequelae including volume overload and extrarenal fluid collections that require drainage.`, 
        state: `notAnswered`,
        userAnswered: [],
        type: `MCSS`},
    {
        q: `A 55-year-old woman has an oral temperature of 38.5°C on the first night after an uncomplicated percutaneous nephrolithotomy for a partial staghorn renal calculus. A nephrostomy tube is in place. She is hemodynamically stable. The preoperative urine culture had grown a pansensitive <i>Proteus</i> sp., and she had received oral trimethoprim sulfamethoxazole for 2 weeks preoperatively. One gram of cefazolin had been administered on call to the operating room. The next step is:`,
        q2: ``,
        q3: [],
        option: [`observation.`, 
        `culture aspirate from nephrostomy tube and irrigate nephrostomy tube.`, 
        `Doppler ultrasonography of lower extremities and/or pulmonary embolus-protocol computed tomography scan.`, 
        `administer broad-spectrum antibiotics.`, 
        `culture urine and blood, obtain chest radiograph, and administer broad-spectrum antibiotics.`],
        optionFeedback: [``,
        ``,
        ``,
        ``,
        
        ``],
        optionStyleType: `st-upper-alpha`,
        answer: [0],
        ansText:`Rationale: <!--<b>a. Observation.</b>--> Preoperative and perioperative management of this patient has been appropriate. In this setting, most patients with fever after percutaneous nephrolithotomy do not have infection. If the fever is an isolated postoperative one, then standard postoperative care (early ambulation, use of incentive spirometry, etc.) is all that is needed. If the fever does not resolve promptly, then appropriate diagnostic evaluation and initiation of antimicrobial therapy and other supportive care are indicated.`, 
        state: `notAnswered`,
        userAnswered: [],
        type: `MCSS`},
    {
        q: `Following percutaneous renal surgery, loss of renal function is:`,
        q2: ``,
        q3: [],
        option: [`approximately 5% of ipsilateral function per access site.`, 
        `minimal in the absence of vascular injury.`, 
        `greater than after shock wave lithotripsy.`, 
        `less in pelvic compared with orthotopic kidneys.`,  
        `greater in solitary compared with nonsolitary kidneys.`],
        optionFeedback: [``,
        ``,
        ``,
        ``,
        
        ``],
        optionStyleType: `st-upper-alpha`,
        answer: [1],
        ansText:`Rationale:<!--<b>b. Minimal in the absence of vascular injury.</b>--> The kidney suffers little permanent damage after uncomplicated percutaneous renal surgery. If there is significant loss of function, it is usually owing to disastrous vascular injury or the angioembolization used to treat hemorrhage. Loss of renal function associated with percutaneous renal surgery is less than or equal to the loss associated with shock wave lithotripsy. There is no evidence that damage to the kidney is any more or less in pelvic, orthotopic, solitary, or nonsolitary kidneys. `, 
        state: `notAnswered`,
        userAnswered: [],
    
        type: `MCSS`},
    {
        q: `With regard to ureteral stents, which factors have been associated with improved patient tolerance?`,
        q2: ``,
        q3: [],
        option: [`Ureteral stent length`, 
        `Ureteral stent diameter`, 
        `Stent material`, 
        `Distal stent tip architecture (pigtail vs. Polaris)`,  
        `None of the above`],
        optionFeedback: [``,
        ``,
        ``,
        ``,
        
        ``],
        optionStyleType: `st-upper-alpha`,
        answer: [4],
        ansText:`Rationale:<!--<b>e. None of the above.</b>--> Randomized controlled trials have failed to show association between stent length, diameter, material, or architecture and impact on patient tolerability. `, 
        state: `notAnswered`,
        userAnswered: [],
        type: `MCSS`},
]