var quiz = [
   
    {
        q: `Patients undergoing diagnostic cystoscopy should receive prophylactic antibiotics if they have any of the following risk factors except:`,
        q2: ``,
        q3: [],
        option: [`poor nutritional status.`, 
        `anatomic anomalies.`, 
        `hypertension.`, 
        `corticosteroid use.`, 
        `smoking history.`],
        optionFeedback: [``,
        ``,
        ``,
        ``,
        
        ``],
        optionStyleType: `st-upper-alpha`,
        answer: [2],
        ansText:`Rationale: <!--<b>c. Hypertension.</b>--> The American Urological Association’s Best Practice Policy Statement on Antimicrobial Prophylaxis did <b>not recommend routine antibiotic administration for diagnostic cystourethroscopy.</b> This recommendation was based on the recognition that some randomized studies have shown antibiotic prophylaxis reduces bacteriuria and symptomatic infection rates, whereas others have not. However, <b>antibiotic administration was advocated</b> by the panel for patients with host factors increasing their risk of infection. These include <b>advanced age, anatomic anomalies, poor nutritional status, smoking, chronic corticosteroid use, immunodeficiency, chronic indwelling hardware infected with endogenous or exogenous material, distant coinfection, and prolonged hospitalization.</b>`, 
        state: `notAnswered`,
        userAnswered: []        ,
        type: `MCSS`},
    {
        q: `Compared with reusable flexible ureteroscopes, single-use flexible ureteroscopes have been shown to have:`,
        q2: ``,
        q3: [],
        option: [`decreased active deflection.`, 
        `comparable visibility.`, 
        `well-established cost savings.`, 
        `decreased durability.`, 
        `longer procedure time.`],
        optionFeedback: [``,
        ``,
        ``,
        ``,
        
        ``],
        optionStyleType: `st-upper-alpha`,
        answer: [1],
        ansText:`Rationale:<!--<b>b. Comparable visibility.</b>--> One of the early studies evaluating disposable ureteroscopes was a cadaveric study comparing the LithoVue to nondisposable fiberoptic and digital ureteroscopes. The researchers found the LithoVue to be comparable in visibility and scope maneuverability. `, 
        state: `notAnswered`,
        userAnswered: []        ,
        type: `MCSS`},
    {
        q: `Techniques that have been shown to improve flexible cystourethroscopy tolerance in men include all of the following except:`,
        q2: ``,
        q3: [],
        option: [`allowing the patient to observe the procedure.`, 
        `having the patient empty his bladder before the procedure.`, 
        `playing classical music during the procedure.`, 
        `using lidocaine lubricating gel.`, 
        `increasing the hydrostatic pressure of the irrigant during scope passage.`],
        optionFeedback: [``,
        ``,
        ``,
        ``,
        
        ``],
        optionStyleType: `st-upper-alpha`,
        answer: [1],
        ansText:`Rationale: <!--<b>b. Having the patient empty his bladder before the procedure.</b>--> A variety of prospective studies have been performed with the aim of improving patient tolerance during office-based diagnostic flexible cystourethroscopy. A meta-analysis of four randomized trials involving 411 patients found that patients receiving lidocaine gel were 1.7 times less likely to experience moderate to severe pain during the procedure. Results of a randomized trial involving 151 men indicated that increasing the hydrostatic pressure of the irrigation solution during passage of the scope through the membranous urethra was associated with significantly less discomfort on an analog pain scale. In another study, men who were allowed to watch the procedure had significantly less pain on a 100-mm visual analog scale. Last, 70 men were randomly assigned to hear either no music or classical music during cystourethroscopy. Patients listening to classical music had significantly less pain, greater satisfaction, lower postprocedure pulse rates, and lower systolic blood pressures.`, 
        state: `notAnswered`,
        userAnswered: []
    
            ,
        type: `MCSS`},
    {
        q: `Indications for ureteroscopy include all of the following except:`,
        q2: ``,
        q3: [],
        option: [`obstructing ureteral calculus.`, 
        `filling defect of the renal pelvis.`, 
        `1.2-cm renal calculus in the lower pole.`, 
        `ureteropelvic junction obstruction with a large crossing vessel present.`, 
        `1.5-cm midureteral stricture.`],
        optionFeedback: [``,
        ``,
        ``,
        ``,
        
        ``],
        optionStyleType: `st-upper-alpha`,
        answer: [3],
        ansText:`Rationale:<!--<b>d. Ureteropelvic junction obstruction with a large crossing vessel present.</b>--> All of the options are common indications for ureteroscopy except ureteropelvic junction obstruction due to a large crossing vessel. Although ureteropelvic junction obstruction can be managed with ureteroscopic endopyelotomy, <b>patients with a large crossing vessel are better treated by laparoscopic pyeloplasty.</b> `, 
        state: `notAnswered`,
        userAnswered: []        ,
        type: `MCSS`},
    {
        q: `Which of the following statements about ureteroscopy are true?`,
        q2: ``,
        q3: [],
        option: [`Ureteral access sheaths decrease intrarenal pressure during ureteroscopy.`, 
        `Flexible ureteroscopes accept working instruments 3.6 Fr in diameter.`, 
        `Normal saline should be used for irrigation during ureteroscopy.`, 
        `A preoperative antibiotic is needed only in high-risk patients.`, 
        `a and c.`],
        optionFeedback: [``,
        ``,
        ``,
        ``,
        
        ``],
        optionStyleType: `st-upper-alpha`,
        answer: [4],
        ansText:`Rationale: <!--<b>e. a and c.</b>--> Auge and colleagues measured the pressure within the renal pelvis and proximal, mid, and distal ureter before and after ureteral access sheath placement in five patients who had previously undergone nephrostomy tube placement. The pressure within the collecting system was found to be significantly lower at each location following access sheath placement.`, 
        state: `notAnswered`,
        userAnswered: []        ,
        type: `MCSS`},
    {
        q: `Compared with white-light endoscopy, narrow-band imaging has been shown to:`,
        q2: ``,
        q3: [],
        option: [`predict favorable response to bacillus Calmette-Guérin (BCG) intravesical therapy.`, 
        `accurately differentiate between low- and high-grade lesions.`, 
        `obviate the need for re-resection in patients with high-grade tumors involving the lamina propria.`, 
        `significantly improve detection accuracy of muscle-invasive lesions.`, 
        `improve detection of noninvasive lesions, including carcinoma in situ.`],
        optionFeedback: [``,
        ``,
        ``,
        ``,
        
        ``],
        optionStyleType: `st-upper-alpha`,
        answer: [4],
        ansText:`Rationale:<!--<b>e. Improve detection of noninvasive lesions, including carcinoma in situ.</b>--> Narrow-band imaging uses only blue (415 nm) and green (540 nm) wavelengths to image the urothelium compared with white-light endoscopy, which uses the entire visible light spectrum. Blue and green wavelengths are strongly absorbed by hemoglobin, improving visibility of urothelial capillaries, small papillary lesions, and carcinoma in situ. A meta-analysis of eight studies including 1022 patients found that <b>narrow-band imaging improves detection accuracy of noninvasive lesions, including carcinoma in situ.</b> `, 
        state: `notAnswered`,
        userAnswered: [],
    
        type: `MCSS`},
    {
        q: `Which of the following statements are true?`,
        q2: ``,
        q3: [],
        option: [`The holmium laser is absorbed in 3 cm of water.`, 
        `Water is the preferred irrigant for ureteroscopy because of improved visibility.`, 
        `Baskets made of nitinol are more “kink resistant” compared with stainless steel.`, 
        `Balloon dilation of the intramural ureter is usually necessary before flexible ureteroscopy.`, 
        `Compared with fiberoptic flexible ureteroscopes, digital flexible ureteroscopes less frequently require the use ureteral access sheaths.`],
        optionFeedback: [``,
        ``,
        ``,
        ``,
        
        ``],
        optionStyleType: `st-upper-alpha`,
        answer: [2],
        ansText:`Rationale:<!--<b>c. Baskets made of nitinol are more “kink resistant” compared with stainless steel.</b>--> Nitinol has a variety of advantageous properties compared with stainless steel. Nitinol is more biocompatible, has greater torquability and improved “memory,” and is more resistant to kinking. These properties make it ideal for stone basket construction. Holmium laser energy is absorbed by 3 mm of water. Saline is the preferred irrigation solution because of the decreased risk of “transurethral resection syndrome” compared with hypotonic solutions. The need for ureteral dilation has decreased over time with the advent of smaller-diameter ureteroscopes. However, digital models have larger tip and shaft diameters, making them more likely to need ureteral dilation or access sheath placement compared with their fiberoptic counterparts. `, 
        state: `notAnswered`,
        userAnswered: [],
    
        type: `MCSS`},
    {
        q: `Techniques to minimize staff radiation exposure include all of the following except:`,
        q2: ``,
        q3: [],
        option: [`using “last image hold” setting.`, 
        `using fixed fluoroscopy units.`, 
        `surgeon control of the foot pedal.`, 
        `using image collimation.`, 
        `using pulse fluoroscopy mode.`],
        optionFeedback: [``,
        ``,
        ``,
        ``,
        
        ``],
        optionStyleType: `st-upper-alpha`,
        answer: [1],
        ansText:`Rationale: <!--<b>b. Using fixed fluoroscopy units.</b>--> All endourologic procedures using fluoroscopy should operate on the ALARA principle (as low as reasonably achievable). Techniques that have been shown to minimize radiation exposure include surgeon control of the foot pedal, using “last image hold,” image collimation, and pulsed fluoroscopy mode. Compared with fixed units, mobile C-arm fluoroscopy machines are able to position the image intensifier closer to the patient, thereby reducing exposure while improving image quality.`, 
        state: `notAnswered`,
        userAnswered: [],
    
        type: `MCSS`},

]