var quiz = [
   
    {
        q: `Decreased cardiac output in pregnant patients undergoing urologic surgery may be ameliorated by the following maneuver:`,
        q2: ``,
        q3: [],
        option: [`Aggressive intraoperative fluid resuscitation`, 
        `Administration of alpha receptor agonists`, 
        `Use of only regional anesthesia`, 
        `Right-side elevation allowing displacement of the uterus off the vena cava`, 
        `High lithotomy position to increase venous return from lower extremities`],
        optionFeedback: [``,
        ``,
        ``,
        ``,
        
        ``],
        optionStyleType: `st-upper-alpha`,
        answer: [3],
        ansText:`Rationale:<!--<b>d. Right-side elevation allowing displacement of the uterus off the vena cava.</b>--> CO in pregnancy is dependent on maternal position and standard techniques for urology may pose unintended consequences. In the supine position, CO in the pregnant woman decreases by up to 30% at term as compared to a lateral recumbent position. <b>Prevention of potential acute drops in venous return and CO may require avoidance of supine and lithotomy positions when feasible with right-side elevation to displace the uterus to the left.</b> Placement of a wedge may be logistically challenging but achieving a 15- to 20-degree left tilt should reduce uterine compression of the inferior vena cava. `, 
        state: `notAnswered`,
        userAnswered: []        ,
        type: `MCSS`},
    {
        q: `Changes in renal tubular function during pregnancy result in alterations of urine chemistries EXCEPT for:`,
        q2: ``,
        q3: [],
        option: [`glycosuria.`, 
        `proteinuria.`, 
        `pyuria.`, 
        `albuminuria.`, 
        `calcinuria.`],
        optionFeedback: [``,
        ``,
        ``,
        ``,
        
        ``],
        optionStyleType: `st-upper-alpha`,
        answer: [2],
        ansText:`Rationale: <!--<b>c. Pyuria.</b>--> Marked change in renal tubular function during pregnancy results in a variety of alterations of urine chemistries that may be encountered by the urologist although elevation of ketones is not typical. Indeed, glycosuria during pregnancy is exceedingly common, with 10- to 100-fold increase in urinary glucose excretion described. Proteinuria and albuminuria additionally manifest during pregnancy and may increase as the gestation advances. Calcinuria doubles during pregnancy. Although women may display pyuria due to contamination or superimposed infection, it is not a consistent finding during gestation.`, 
        state: `notAnswered`,
        userAnswered: []        ,
        type: `MCSS`},
    {
        q: `Symptomatic physiologic hydronephrosis of pregnancy should be primarily managed by:`,
        q2: ``,
        q3: [],
        option: [`percutaneous nephrostomy.`, 
        `conservative measures.`, 
        `antibiotic prophylaxis.`, 
        `ureteral stent.`, 
        `Alpha-blocker therapy.`],
        optionFeedback: [``,
        ``,
        ``,
        ``,
        
        ``],
        optionStyleType: `st-upper-alpha`,
        answer: [1],
        ansText:`Rationale: <!--<b>b. Conservative measures.</b>--> <b>In general, ureteral stent insertion in symptomatic gestational hydronephrosis does not generally add benefit over conservative treatment and should be reserved for complicated cases or additional pathologic obstructions.</b> Conservative measures include analgesia, position, and intravenous fluids and failure included signs of evolving infection or deteriorating renal function. Parameters that may increase the likelihood of surgical treatment with ureteral stenting for symptomatic hydronephrosis include maximal anterior-posterior renal pelvis diameter, parity, C-reactive protein level, white blood cell count, and pain on a visual analog scale. Rarely is percutaneous nephrostomy required, and there is not a role for antibiotics outside of acute infection. Alpha blockers are likewise not indicated for relief of colic from physiologic hydronephrosis.`, 
        state: `notAnswered`,
        userAnswered: []        ,
        type: `MCSS`},
    {
        q: `Which of the following statements is FALSE regarding imaging in pregnant patients?`,
        q2: ``,
        q3: [],
        option: [`Ultrasound and magnetic resonance imaging are the techniques of choice.`, 
        `Routine imaging with magnetic resonance imaging (MRI) should employ use of gadolinium contrast.`, 
        `Radiation from computed tomography (CT) scan is usually at a dose lower than that associated with fetal harm.`, 
        `Safety of nuclear medicine studies is dependent on the isotope utilized.`, 
        `None of the above.`],
        optionFeedback: [``,
        ``,
        ``,
        ``,
        
        ``],
        optionStyleType: `st-upper-alpha`,
        answer: [1],
        ansText:`Rationale:<!--<b>b. Routine imaging with magnetic resonance imaging (MRI) should employ use of gadolinium contrast.</b>--> This statement is false. The American College of Obstetricians and Gynecologists (ACOG) have outlined clinical guidelines to drive management decisions and determine the diagnostic imaging modality which provides the optimal risk/benefit ratio in many situations. The use of gadolinium contrast with MRI should be limited; it may be used as a contrast agent in the pregnant woman only if it significantly improves diagnostic performance and is expected to improve fetal or maternal outcomes. `, 
        state: `notAnswered`,
        userAnswered: [],
        type: `MCSS`},
    {
        q: `Current practice recommendations for pregnant women undergoing nonobstetric surgery include:`,
        q2: ``,
        q3: [],
        option: [`Anesthetic agents should be avoided due to teratogenic effects.`, 
        `Elective surgery is best accomplished in the first trimester.`, 
        `Use of fetal heart rate monitoring during the first trimester to influence delivery decisions.`, 
        `Surgery should be performed at an institution with neonatal and pediatric services.`, 
        `None of the above.`],
        optionFeedback: [``,
        ``,
        ``,
        ``,
        
        ``],
        optionStyleType: `st-upper-alpha`,
        answer: [3],
        ansText:`Rationale:<!--<b>d. Surgery should be performed at an institution with neonatal and pediatric services.</b>--> Recommendations from the ACOG provide the urologist guidance regarding considerations for nonobstetric surgery during pregnancy. Overall, consultation with an obstetrician should be obtained to ensure pertinent aspects of maternal physiology are considered along with potential need for fetal monitoring. <b>If possible, nonurgent surgery should be performed in the second trimester when preterm contractions and spontaneous abortion are least likely.</b> `, 
        state: `notAnswered`,
        userAnswered: [],
        type: `MCSS`},
    {
        q: `Which of the following statements regarding stone disease in pregnancy is TRUE?`,
        q2: ``,
        q3: [],
        option: [`Approximately 30% of pregnant women with symptomatic calculi pass the stone spontaneously.`, 
        `Stone events in pregnancy carry an increased risk of maternal and fetal morbidity.`, 
        `Complication rates of ureteroscopy in pregnant women is 27%.`, 
        `Ureteroscopy and stent placement should always be performed without fluoroscopic guidance.`, 
        `None of the above.`],
        optionFeedback: [``,
        ``,
        ``,
        ``,
        
        ``],
        optionStyleType: `st-upper-alpha`,
        answer: [1],
        ansText:`Rationale: <!--<b>b. Stone events in pregnancy carry an increased risk of maternal and fetal morbidity.</b>--> Of pregnant patients with symptomatic calculi, 50% to 80% will pass their stones spontaneously when treated conservatively with hydration and analgesia. However, a stone event in pregnancy does carry with it an increased risk of maternal and fetal morbidity, so patients should be followed closely for recurrent or persistent symptoms. Ureteroscopy in pregnancy carries an overall complication rate of 8.3%, with no significant difference in rates of urinary tract complications compared to the non-pregnant population. Although methods to reduce fetal radiation exposure should be employed, rarely would endoscopic procedures need to be performed without the aid of fluoroscopy.`, 
        state: `notAnswered`,
        userAnswered: [],
        type: `MCSS`},
    {
        q: `Counseling of female patients with myelomeningocele (MMC) desiring pregnancy includes:`,
        q2: ``,
        q3: [],
        option: [`Women with MMC in general are considered to have normal fertility.`, 
        `There is no risk of genetic transmission of neural tube defects to the offspring.`, 
        `Patients with preexisting renal insufficiency do not have increased risk during pregnancy of worsening renal function.`, 
        `Women with MMC do not require folic acid supplementation during conception.`, 
        `None of the above.`],
        optionFeedback: [``,
        ``,
        ``,
        ``,
        
        ``],
        optionStyleType: `st-upper-alpha`,
        answer: [0],
        ansText:`Rationale:<!--<b>a. Women with MMC in general are considered to have normal fertility.</b>--> Females with MMC are considered to have normal fertility with up to 70% of those who conceive having successful pregnancies. With regard to transmission, the threat is identical if the affected parent is male or female; however, the incidence in female offspring is 1 in 13 and diminishes to 1 in 50 for male children. However, if both parents are affected, the neural tube defect transmission rate increases dramatically to 15%. Foremost is recognition that <b>the greatest risk factor for worsening renal function in pregnant women with or without urinary reconstruction is preexisting renal insufficiency.</b> Notably, compared to routine supplementation of women without MMC of 0.4 mg folic acid per day, <b>doses of 4 to 5 mg/day have been advocated for the MMC patient desirous of fertility.</b> `, 
        state: `notAnswered`,
        userAnswered: []        ,
        type: `MCSS`},
    {
        q: `All of the following regarding placenta percreta are correct EXCEPT:`,
        q2: ``,
        q3: [],
        option: [`Prior cesarean section is the predominant risk factor for abnormal placentation.`, 
        `Biopsy prior to surgical intervention is indicated for placenta percreta.`, 
        `A multidisciplinary team is mandated to deliver specialized care.`, 
        `Preoperative counseling should include discussion of ureteral catheters, stents, urinary tract injury, or possible extirpative surgery with urinary diversion.`, 
        `None of the above.`],
        optionFeedback: [``,
        ``,
        ``,
        ``,
        
        ``],
        optionStyleType: `st-upper-alpha`,
        answer: [1],
        ansText:`Rationale:<!--<b>b. Biopsy prior to surgical intervention is indicated for placenta percreta.</b>--> With knowledge of the potential risk factors for abnormal placentation, the clinician may choose to proceed with cystoscopic evaluation of such patients to evaluate the posterior bladder wall and significant invasion. Biopsy of the hypervascular tissue visualized in the bladder is discouraged. Assembly of a multidisciplinary team is currently recommended standard of care to reduce maternal and fetal morbidity and mortality. Suggested involvement includes an appropriate anesthesiologist, obstetrician, experienced pelvic surgeon such as a gynecologic oncologist, intensivist, maternal-fetal medicine specialist, interventional radiologist, and as required additional surgical subspecialties such as urology and general surgery. <b>Preoperative planning by the urologist should include appropriate counseling of the patient with regard to placement of ureteral catheters or stents as well as potential manifestations of substantial injury or need for extirpative surgery for urologic organs and urinary diversion.</b> Prior cesarean delivery appears to be the predominant risk factor due to abnormal implantation in the myometrial scar with compromised vascularity. Advanced maternal age is additionally contributory with women over 35 years of age accounting for 57% of placental adhesive disorders. `, 
        state: `notAnswered`,
        userAnswered: [],
        type: `MCSS`},
]
