var quiz = [

    {
        q: `Which of the following is <i>true</i> regarding cosmetic benefits of minimally invasive surgery in children?`,
        q2: ``,
        q3: [],
        option: [`Incisional scars will contract over time as the children grow longitudinally.`, 
        `Parents have no preference toward clinical outcomes (success and complications) over cosmetic appears of incisions when weighing open versus minimally invasive approach.`, 
        `Size of the incisions are not as important as location of the incision as it relates to cosmetic outcomes.`, 
        `Cosmetic benefits of single-port laparoendoscopic surgery are durable over several years. `, 
        ` No validated questionnaires exist to assess bother as related to incisional scarring following surgical interventions.`,
        ],
        optionFeedback: [``,
          ``,
          ``,
          ``,
          ``],
        optionStyleType: `st-lower-alpha`,
        answer: [2],
        ansText: `Rationale: Validated instruments to assess scar both do exist and have been used to show that families show preference over location of scar (i.e., prefer more inconspicuous positions), as well as that the benefits cosmetically from a single-site incisional approach are not significantly better than standard laparoscopic approaches after 18 months of follow-up. Families would prefer optimal clinical outcomes to cosmetic appearance, although if equal, families would choose a minimally invasive approach for their child.`,
        state: `notAnswered`,
        userAnswered: []
      ,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`        ,
        type: `MCSS`},
      {
        q: `Which of the following procedures has not been shown to have a length of stay benefit for minimally invasive approaches as compared with the open surgical counterpart?`,
        q2: ``,
        q3: [],
        option: [`Pyeloplasty`, 
        `Ureteral reimplant`, 
        `Hernia/hydrocele`, 
        `Appendicovesicostomy `, 
        ` Augmentation enterocystoplasty`,
        ],
        optionFeedback: [``,
          ``,
          ``,
          ``,
          ``],
        optionStyleType: `st-lower-alpha`,
        answer: [2],
        ansText: `Rationale: Although a combination of prospective observational trials, randomized controlled trials, and retrospective cohort analyses have shown length of stay benefits for minimally invasive pyeloplasty, ureteral reimplantation, appendicovesicostomy, and augmentation enterocystoplasty, no such data exist showing benefit for hernia/hydrocele repairs. In fact, pain scores may be higher following laparoscopic hernia/hydrocele repairs as compared with open inguinal incisions, potentially due to the stress of pneumoperitoneum. Thus the benefit of convalescence and postoperative pain from a minimally invasive approach is likely proportional to the burden of the alternative open approach. `,
        state: `notAnswered`,
        userAnswered: []
              ,
        type: `MCSS`},
      {
        q: `Which of the following is false regarding cardiovascular implications of pneumoperitoneum?`,
        q2: ``,
        q3: [],
        option: [`Bradycardia may be seen upon insufflation.`, 
        `Tachyarrhythmia may be seen secondary to a sympathetic response of pneumoperitoneum.`, 
        `Cardiac index is decreased at insufflation pressures as low as 10 mm Hg.`, 
        `Left ventricular ejection fraction does not appear to be impacted by pneumoperitoneal changes, although myocardial workload may increase. `, 
        `Mortality is no different in laparoscopic approaches for children with congenital cardiac defects as compared with healthy children, despite the cardiovascular implications of pneumoperitoneum. `,
        ],
        optionFeedback: [``,
          ``,
          ``,
          ``,
          ``],
        optionStyleType: `st-lower-alpha`,
        answer: [4],
        ansText: `Rationale: Vagal nerve stimulation can result in initial bradycardia, which may be managed with atropine or glycopyrrolate but is typically self-limited. Cardiac index decreases with pneumoperitoneum greater than 10 mm Hg, likely due in part to increased intraabdominal and intrathoracic pressure on the venous return. This may result in an increased work of the myocardium as a compensatory response, which is why the left ventricular ejection fraction remains stable in spite of the cardiovascular changes. However, mortality is increased for children with congenital cardiac defects undergoing laparoscopic procedures as compared with healthy children, indicating a need for close hemodynamic monitoring and consideration of a specialized cardiac anesthesia team for these procedures. `,
        state: `notAnswered`,
        userAnswered: []
      ,
	type: `MCSS`,
	type: `MCSS`        ,
        type: `MCSS`},
      {
        q: `With pneumoperitoneum, which of the following physiological changes is incorrectly described?`,
        q2: ``,
        q3: [],
        option: [`Increase in end-tidal CO<sub>2</sub>`, 
        `Increase in dynamic pulmonary compliance`, 
        `Increase in systemic vascular resistance`, 
        `Increase in intracranial pressure `, 
        `Decrease in urine output `,
        ],
        optionFeedback: [``,
          ``,
          ``,
          ``,
          ``],
        optionStyleType: `st-lower-alpha`,
        answer: [1],
        ansText: `Rationale: End-tidal CO<sub>2</sub> will increase from both an increased absorption of insufflated CO<sub>2</sub> gas and a decrease in minute ventilation from upward pressure on the diaphragm. Systemic vascular resistance increases, which drives a sympathetic response. Both of these changes likely contribute to a decrease in glomerular filtration rate and thus a decrease in urine output. Intracranial pressure also increases, although in most cases not to a clinically relevant degree. Dynamic pulmonary compliance will decrease, likely secondary to upward mobilization of the diaphragm and a decrease in the overall tidal volumes; often these changes necessitate ventilator manipulations to maintain appropriate ventilation.`,
        state: `notAnswered`,
        userAnswered: []
      ,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`        ,
        type: `MCSS`},
      {
        q: `Which of the following statements appropriately reflects the impact of the pneumoperitoneum on the immune response?`,
        q2: ``,
        q3: [],
        option: [`Polymorphonuclear cells and macrophages, as well as levels of interleukin-6 (IL-6), are increased locally due to the effect of pneumoperitoneum across the entire abdominal wall, as compared with open surgery.`, 
        `Pediatric patients have a greater degree of benefit toward a blunted immune response following laparoscopy as compared with adult patients.`, 
        `Peritoneal signs following laparoscopy are heightened as compared with open surgery, likely owing to the local acidotic environment following CO<sub>2</sub> insufflation.`, 
        ` Systemic C-reactive protein (CRP) and IL-6 levels are decreased following laparoscopy as compared with open surgery.`, 
        ` Insufflation with room air results in a lessened inflammatory response as compared with CO<sub>2</sub> gas.`,
        ],
        optionFeedback: [``,
          ``,
          ``,
          ``,
          ``],
        optionStyleType: `st-lower-alpha`,
        answer: [3],
        ansText: `Rationale: Systemic and local inflammatory responses are blunted with insufflation, a result that appears to be in part due to the use of CO<sub>2</sub> gas, which elicits a lessened immune response as compared with insufflation with room air or open surgery. This blunted immune response results in lower pain and fatigue levels postoperatively but also may blunt peritoneal signs in the event of a visceral injury. Thus the surgeon must have a high index of suspicion for visceral injury in the absence of an acute abdomen, if the child otherwise appears ill.`,
        state: `notAnswered`,
        userAnswered: []
      ,
	type: `MCSS`        ,
        type: `MCSS`},
      {
        q: `Which of the following is/are an absolute contraindication to minimally invasive surgery?`,
        q2: ``,
        q3: [],
        option: [`Size less than 4 kg`, 
        `Inability to tolerate pneumoperitoneum`, 
        `Age less than 3 months`, 
        `Prior abdominal surgery `, 
        `a and c `,
        ],
        optionFeedback: [``,
          ``,
          ``,
          ``,
          ``],
        optionStyleType: `st-lower-alpha`,
        answer: [1],
        ansText: `Rationale: Inability to tolerate pneumoperitoneum and inability of the surgeon to perform the procedure in a minimally invasive fashion are the only two absolute contraindications to a minimally invasive approach in children. Children less than a week of age have safely undergone robotic and laparoscopic-assisted procedures in experienced hands. Although prior abdominal operations may increase the risk for conversion to open surgery, these patients may also experience a differential benefit to a minimally invasive approach if performed successfully.`,
        state: `notAnswered`,
        userAnswered: []
              ,
        type: `MCSS`},
      {
        q: `Which of the following is true regarding peritoneal access via the umbilicus?`,
        q2: ``,
        q3: [],
        option: [`A fascial hernia is rarely identified.`, 
        `Due to the fascial support at the umbilicus, a port site in this location does not usually require closure.`, 
        `The umbilicus is a reliable indicator of the location of the aortic bifurcation, which will lie superior to the umbilicus.`, 
        ` Trendelenburg positioning does not alter the relation between the umbilicus and the aortic bifurcation.`, 
        `None of the above. `,
        ],
        optionFeedback: [``,
          ``,
          ``,
          ``,
          ``],
        optionStyleType: `st-lower-alpha`,
        answer: [4],
        ansText: `Rationale: Fascial openings are commonly observed in children and even found in up to 25% of adults at the umbilicus. However, the variance of the fascial support necessitates closure of the umbilical port sites in children. The umbilicus is a poor indicator of the location of the aortic bifurcation, which may fall inferior to the umbilicus in up to 40% of patients, a proportion that may even increase should the patient be placed in Trendelenburg position. The implication of this fact is that the surgeon should take care in blind trocar placement at the umbilicus as major vascular structures including the aorta and vena cava are at risk of injury in that approach.`,
        state: `notAnswered`,
        userAnswered: []
              ,
        type: `MCSS`},
      {
        q: `A comparison of open and Veress access techniques has revealed:`,
        q2: ``,
        q3: [],
        option: [`an increased risk of visceral injury with open access.`, 
        `an increased risk of vascular injury with Veress access.`, 
        `an increased risk of failed access with Veress access.`, 
        `an increased risk of failed access with open access. `, 
        ` an increased risk of port site hernia with open access.`,
        ],
        optionFeedback: [``,
          ``,
          ``,
          ``,
          ``],
        optionStyleType: `st-lower-alpha`,
        answer: [2],
        ansText: `Rationale: Major complications with access are rare regardless of technique chosen. Thus no difference is observed in major vascular or visceral injury with either open or Veress access technique. However, Veress access does appear to be associated with a higher risk for access failure as compared with the open technique. Port site hernia risk has not been formally assessed in most studies.`,
        state: `notAnswered`,
        userAnswered: []
              ,
        type: `MCSS`},
      {
        q: `Port site hernias in children:`,
        q2: ``,
        q3: [],
        option: [`have not been reported in trocar sites smaller than 5 mm`, 
        `may present with lethargy and a bulge in the absence of peritoneal signs.`, 
        `are at an increased risk at the umbilical site.`, 
        `are a lower risk complication after robotic-assisted procedures. `, 
        `b and c. `,
        ],
        optionFeedback: [``,
          ``,
          ``,
          ``,
          ``],
        optionStyleType: `st-lower-alpha`,
        answer: [1],
        ansText: `Rationale: Port site herniation of omentum has been reported in a 3-mm port site, indicating the importance of closure of all laparoscopic and robotic ports in children. Unlike adults, there does not appear to be a protective location for port site hernia comparing midline, umbilical, and lateral port site location. The blunted inflammatory response post-pneumoperitoneum can mute peritoneal signs even when a port site herniation poses risk of compromise to incarcerated intestine.`,
        state: `notAnswered`,
        userAnswered: []
              ,
        type: `MCSS`},
      {
        q: `The blood vessel most likely injured by Veress needle access at the umbilicus, as shown in <a class="lightboxcallout" img-ref="image_fig_27_1">Fig. 27.1</a> `,
        q2: ``,
        q3: [],
        option: [`left common iliac vein.`, 
        `right common iliac vein.`, 
        `right common iliac artery.`, 
        ` vena cava.`, 
        ` aorta`,
        ],
        optionFeedback: [``,
          ``,
          ``,
          ``,
          ``],
        optionStyleType: `st-lower-alpha`,
        answer: [0],
        ansText: `Rationale: This photo represents a retroperitoneal hematoma from venous injury, the dotted line representing the extent of the hematoma bulge. Although the umbilicus is a poor marker of the aortic bifurcation, most commonly the left common iliac vein is found as the most superior blood vessel in this location, crossing over the iliac artery. Recognition of a vascular injury at the time of Veress access is imperative as dilation with a trocar in this situation could result in life-threatening hemorrhage.`,
        state: `notAnswered`,
        userAnswered: []
      ,
	type: `MCSS`,
	type: `MCSS`        ,
        type: `MCSS`},
      {
        q: `Pulmonary air embolus:`,
        q2: ``,
        q3: [],
        option: [`may be prevented by using CO<sub>2</sub> insufflation.`, 
        `is a common complication with rare catastrophic outcome.`, 
        `may present with increased or decreased end-tidal CO<sub>2</sub>`, 
        `likely results from direct absorption of insufflation gas via the peritoneum. `, 
        ` can be managed best by repositioning the patient prone.`,
        ],
        optionFeedback: [``,
          ``,
          ``,
          ``,
          ``],
        optionStyleType: `st-lower-alpha`,
        answer: [2],
        ansText: `Rationale: Although traditionally described as presenting with an increase in end-tidal CO<sub>2</sub>, vascular collapse with either increased or decreased end-tidal CO<sub>2</sub> at the onset of insufflation should prompt concern for a pulmonary air embolus. This rare but life-threatening event may be managed by placing the patient in the left lateral decubitus position, thereby encouraging migration of the air embolus out of the right pulmonary vein back into the right atrium. Up to 10% of insufflated gas initially may be nitrogen or oxygen, even when using CO<sub>2</sub> insufflation, emanating from the insufflation tubing. Thus flushing the tubing is recommended, especially in infants where the volume of ventilator dead space might be quite low.`,
        state: `notAnswered`,
        userAnswered: []
              ,
        type: `MCSS`},
      {
        q: `All of the following factors are aid in training of minimally invasive surgeons EXCEPT:`,
        q2: ``,
        q3: [],
        option: [`training standardization across centers.`, 
        `standardized assessments of robotic and laparoscopic surgical skills.`, 
        `certified curriculum for surgical training.`, 
        ` well-validated low- and high-fidelity simulation.`, 
        `use of surgical “warm-up.” `,
        ],
        optionFeedback: [``,
          ``,
          ``,
          ``,
          ``],
        optionStyleType: `st-lower-alpha`,
        answer: [0],
        ansText: `Rationale: Although a certified training curriculum (Fundamentals in Laparoscopic Surgery) exists and is commonly applied across general surgery training sites, there is not a standardized laparoscopic or robotic curriculum for urologic surgeons. However, standardized assessments, a combination of low- and high-fidelity surgical simulators, and surgical warm-ups are all tools that can aid in training the newest generation of minimally invasive urologic surgeons, as well as maintaining expertise and skill in those already practicing.`,
        state: `notAnswered`,
        userAnswered: []
              ,
        type: `MCSS`}
    
]