var quiz = [
  {
    q: `Under what conditions is a uroflow reading valid and interpretable?`,
    q2: ``,
    q3: [],
    option: [
      `Postvoid residual (PVR) &lt; 100 mL`,
      `Voided volume &gt; 150 mL`,
      `Voided volume &gt; 50 mL`,
      `Electromyography (EMG) lag time &lt; 6 seconds `,
      ` Any voided volume if there is no PVR`,
    ],
    optionFeedback: [``, ``, ``, ``, ``],
    optionStyleType: `st-lower-alpha`,
    answer: [2],
    ansText: `Rationale: Uroflowmetry is affected by multiple parameters. However, the validity of a test is generally affected by voided volumes. For many studies of pediatric uroflowmetry, <b>50 mL is the cutoff for validity</b>. In adults, a higher value is used (&gt;150 mL). Ideally, a voided volume greater than 50 mL and less than 115% of expected bladder capacity generates the best results. Volumes greater than 115% of expected capacity may also produce uroflow results that are spurious or misleading. `,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
    type: `MCSS`,
    type: `MCSS`,
  },

  {
    q: `What are the five reference uroflow curve types?`,
    q2: ``,
    q3: [],
    option: [
      `Stuttering, bell shaped, peaked, plateau, intermittent`,
      `Staccato, intermittent, bell shaped, plateau, tower`,
      `Tower, peaked, stuttering, normal, flat`,
      `Plateau, intermittent, high, normal, staccato `,
      ` Continuous staccato, bell shaped, normal, inverted`,
    ],
    optionFeedback: [``, ``, ``, ``, ``],
    optionStyleType: `st-lower-alpha`,
    answer: [1],
    ansText: `Rationale: The Standardization Committee of the International Children’s Continence Society published a list of terminology standardization in the Journal of Urology in 2014. <b>This important document lists common terms used to describe voiding dysfunction</b> and the requisite testing performed on these patients.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },

  {
    q: `EMG lag time less than 2 seconds corresponds to what potential patient presentation?`,
    q2: ``,
    q3: [],
    option: [
      `Normal voiding and bell-shaped uroflow curve`,
      `Overactive bladder and tower uroflow curve`,
      `Primary bladder neck dysfunction and plateau uroflow curve`,
      `Underactive bladder and staccato uroflow curve `,
      `Incontinence without PVR `,
    ],
    optionFeedback: [``, ``, ``, ``, ``],
    optionStyleType: `st-lower-alpha`,
    answer: [1],
    ansText: `Rationale: EMG lag times of 2 to 6 seconds are considered normal. <b>Times less than 2 seconds are prevalent in patients with overactive bladder</b>. Times greater than 6 seconds indicate primary bladder neck dysfunction.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },

  {
    q: `What is a normal EMG lag time?`,
    q2: ``,
    q3: [],
    option: [
      `2 seconds`,
      `2 to 6 seconds`,
      `6 seconds`,
      ` 10 seconds`,
      `12 second `,
    ],
    optionFeedback: [``, ``, ``, ``, ``],
    optionStyleType: `st-lower-alpha`,
    answer: [1],
    ansText: `Rationale: EMG lag times of 2 to 6 seconds are considered normal and associated with a bell-shaped voiding curve. Times less than 2 seconds are prevalent in patients with overactive bladder. Times greater than 6 seconds indicate primary bladder neck dysfunction. `,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },

  {
    q: `EMG lag time greater than 6 seconds typically corresponds to what potential patient presentation?`,
    q2: ``,
    q3: [],
    option: [
      `Normal voider and bell-shaped uroflow curve`,
      `Overactive bladder and tower uroflow curve`,
      `Primary bladder neck dysfunction and plateau uroflow curve`,
      `Underactive bladder and staccato uroflow curve `,
      `Controlled (external sphincter) incontinence`,
    ],
    optionFeedback: [``, ``, ``, ``, ``],
    optionStyleType: `st-lower-alpha`,
    answer: [2],
    ansText: `Rationale: EMG lag times of 2 to 6 seconds are considered normal. Times less than 2 seconds are seen with bladder hyperactivity. <b>Times greater than 6 seconds indicate primary bladder neck dysfunction</b> associated with a uroflow curve that plateaus or flattens after an initial rise. `,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },

  {
    q: `Which are valid methods to define functional bladder capacity?`,
    q2: ``,
    q3: [],
    option: [
      `Voided volume on uroflow + PVR`,
      `(Age + 2) × 30 mL`,
      `Smallest voided volume on voiding diary`,
      ` Largest voided volume on voiding diary`,
      ` a + d`,
    ],
    optionFeedback: [``, ``, ``, ``, ``],
    optionStyleType: `st-lower-alpha`,
    answer: [4],
    ansText: `Rationale: Functional bladder capacity is a measure of day-to-day capacity of a patient’s bladder. This number should reflect how much a particular patient’s bladder holds when full. This is reflected by both (a) voided volume on uroflow + PVR and (d) smallest voided volume on voiding diary. (b) corresponds to the patient’s estimated bladder capacity (if older than 1 year). (d) does not reflect any clinically useful measure of the bladder.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },

  {
    q: `What is the significance of debris visualized within the bladder or collecting system on ultrasound?`,
    q2: ``,
    q3: [],
    option: [
      `This is a normal finding`,
      `Concern for ureterocele`,
      `Increased risk of symptomatic urinary tract infection`,
      `Increased risk of positive urine culture regardless of symptoms `,
      ` Urothelial tumor`,
    ],
    optionFeedback: [``, ``, ``, ``, ``],
    optionStyleType: `st-lower-alpha`,
    answer: [3],
    ansText: `Rationale: Studies looking at the association of debris on ultrasound have shown increased association with positive culture. These findings should be interpreted with caution in asymptomatic patients. `,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },

  {
    q: `What test is recommended for all patients who present with lower urinary tract symptoms and no prior urologic diagnosis?`,
    q2: ``,
    q3: [],
    option: [
      `Urinalysis`,
      `Urodynamics`,
      `Serum creatinine`,
      `Uroflow `,
      `Renal bladder ultrasound `,
    ],
    optionFeedback: [``, ``, ``, ``, ``],
    optionStyleType: `st-lower-alpha`,
    answer: [0],
    ansText: `Rationale: American Urological Association (AUA) guidelines for work-up of lower urinary tract symptoms recommend a urinalysis to rule out the presence of a urinary tract infection. None of the other options are recommended for initial testing in new patients seen for lower urinary tract symptoms.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },

  {
    q: `Which cutaneous finding over the sacral spine on exam is at highest risk for diagnosis of occult spinal dysraphism (tethered cord)?`,
    q2: ``,
    q3: [],
    option: [
      `Cutaneous dimple less than 2.5 cm from anus`,
      `Hemangioma`,
      `Dermal sinus tract`,
      ` Symmetric bifid gluteal cleft`,
      `hypertrichosis `,
    ],
    optionFeedback: [``, ``, ``, ``, ``],
    optionStyleType: `st-lower-alpha`,
    answer: [1],
    ansText: `Rationale: The risk of occult spinal dysraphism is different for each of the listed lesions. From lowest risk to highest, they are: simple cutaneous dimple, symmetric bifid gluteal, hypertrichosis (hair tuft), dermal sinus tract, and hemangioma.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },

  {
    q: `What imaging modality is the gold standard for diagnosing spinal dysraphism?`,
    q2: ``,
    q3: [],
    option: [
      `Computed tomography (CT) scan`,
      `Ultrasound`,
      `Positron emission tomography (PET) scan`,
      ` Magnetic resonance imaging (MRI)`,
      `Videourodynamics `,
    ],
    optionFeedback: [``, ``, ``, ``, ``],
    optionStyleType: `st-lower-alpha`,
    answer: [3],
    ansText: `Rationale: MRI is the most sensitive and specific test to rule out any form of spinal dysraphism. Spinal ultrasound can be used for neonates up to age 6 months in whom there is suspicion for dysraphic conditions, but this imaging modality has lower sensitivity. There is no role for CT or PET scans or videourodynamics for the diagnosis of possible dysraphism.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },

  {
    q: `Under which conditions would it be appropriate to consider ultrasound of the spine to rule out spinal dysraphism?`,
    q2: ``,
    q3: [],
    option: [
      `Newborn with open myelomeningocele`,
      `6-month-old with deviated gluteal cleft`,
      `3-year-old with gait problems and secondary enuresis`,
      `Healthy 12-month-old with normal exam and cutaneous dimple 2 cm from the anal verge `,
      ` Family history of a tethered cord`,
    ],
    optionFeedback: [``, ``, ``, ``, ``],
    optionStyleType: `st-lower-alpha`,
    answer: [1],
    ansText: `Rationale: There is debate between use of ultrasound and MRI to rule out spinal dysraphism. MRI is more sensitive but more expensive than ultrasound. <b>For skin findings associated with spina bifida, lesions with low likelihood of diagnosis of spina bifida (like deviated gluteal cleft) may be more appropriate to use ultrasound if testing is being considered</b>. Inconclusive or positive ultrasounds can then be followed up with an MRI to confirm the diagnosis.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },

  {
    q: `What test/treatment is recommended in patients with lower urinary tract dysfunction who fail first-line, conservative therapies (e.g., behavioral modification, timed voiding, avoidance of bladder irritants)?`,
    q2: ``,
    q3: [],
    option: [
      `7-day bowel and bladder diary or 48-hour frequency-volume chart`,
      `Formal videourodynamics`,
      `Treatment with antimuscarinics`,
      ` Treatment with α-blocker`,
      `Intradetrusor injection of botulinum toxin `,
    ],
    optionFeedback: [``, ``, ``, ``, ``],
    optionStyleType: `st-lower-alpha`,
    answer: [0],
    ansText: `Rationale: Elimination diaries can pinpoint a number of issues that may not be elicited during a clinical encounter, including low functional capacity, infrequent voiding, nocturia, and polydipsia. This should be used prior to more invasive evaluation or treatment. `,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },

  {
    q: `Lower urinary tract dysfunction is associated with which of the following?`,
    q2: ``,
    q3: [],
    option: [
      `Constipation`,
      `Neuropsychiatric issues`,
      `Urinary tract infections`,
      ` Vesicoureteral reflux`,
      `All of the above `,
    ],
    optionFeedback: [``, ``, ``, ``, ``],
    optionStyleType: `st-lower-alpha`,
    answer: [4],
    ansText: `Rationale: Constipation, neuropsychiatric issues, urinary tract infections, and vesicoureteral reflux are commonly associated with lower urinary tract dysfunction.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },

  {
    q: `What is an appropriate fill rate on cystometrogram for a pediatric patient?`,
    q2: ``,
    q3: [],
    option: [
      `5 mL/min`,
      `10 mL/min`,
      ` 15 mL/min`,
      ` 20% of expected bladder capacity per minute`,
      `5% to 10% of expected bladder capacity per minute`,
    ],
    optionFeedback: [``, ``, ``, ``, ``],
    optionStyleType: `st-lower-alpha`,
    answer: [3],
    ansText: `Rationale: Pediatric patients have varied bladder capacities, so fill rates relative to expected bladder capacity should be considered. As such, absolute fill rates (e.g., 20 mL/min) might be too fast for a neonate with a bladder capacity of 80 mL. The recommended fill rate is 5% to 10% of expected capacity per minute.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },

  {
    q: `What finding(s) may be reduced on urodynamics when performed under sedation?`,
    q2: ``,
    q3: [],
    option: [
      `Detrusor overactivity`,
      `Compliance`,
      `Detrusor leak point pressure`,
      `Bladder capacity `,
      `Internal sphincter control `,
    ],
    optionFeedback: [``, ``, ``, ``, ``],
    optionStyleType: `st-lower-alpha`,
    answer: [0],
    ansText: `Rationale: Studies have demonstrated that the only parameter reliably affected by sedation or anesthesia is detrusor overactivity. That is, if it were present normally, it would not be present on a sedated urodynamics study. Compliance, detrusor leak point pressure (dLPP), and bladder capacity are not generally affected.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
];
