var quiz = [
    {
        q: `All of the following statements regarding prenatal sonography are true EXCEPT:`,
        q2: ``,
        q3: [],
        option: [`amniotic fluid contains fetal urine before 10 weeks of age.`, 
        
        
        `amniotic fluid contains fetal urine by 10 to 12 weeks of age.`, 
        ` urine fills the fetal bladder by 20 weeks of age.`, 
        `  the fetal bladder never completely empties despite normal bladder cycling.`, 
         `in the fetal kidney, prominent corticomedullary differentiation can be confused for hydronephrosis.`,
        ],
        optionFeedback: [``,
          ``,
          ``,
          ``,
          ``],
        optionStyleType: `st-lower-alpha`,
        answer: [0],
        ansText: `Rationale: Amniotic fluid does not contain fetal urine before 10 weeks of age. `,
        state: `notAnswered`,
        userAnswered: []
      ,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`        ,
        type: `MCSS`},
      {
        q: `All of the following statements about postnatal ultrasound findings of hydronephrosis are true EXCEPT:`,
        q2: ``,
        q3: [],
        option: [`hydronephrosis may be obstructive or nonobstructive`, 
        
        `Hydronephrosis is not always an indication of obstruction.`, 
        `hydronephrosis can be more fully evaluated by functional imaging to identify obstruction. `, 
        `hydronephrotic pelvicalyceal system can be differentiated from renal cysts based on whether the fluid spaces do not or do communicate.`,
        ` autosomal recessive polycystic kidneys are characterized by homogeneously bright kidneys that are enlarged.`,
        ],
        optionFeedback: [``,
          ``,
          ``,
          ``,
          ``],
        optionStyleType: `st-lower-alpha`,
        answer: [1],
        ansText: `Rationale: hydronephrosis is always an indication of obstruction. `,
        state: `notAnswered`,
        userAnswered: []
      ,
	type: `MCSS`        ,
        type: `MCSS`},
      {
        q: `Identify the false statement about imaging for urinary tract infection.`,
        q2: ``,
        q3: [],
        option: [`Sonography is very sensitive for the detection of vesicoureteral reflux.`, 
        `Sonography is not very sensitive for the detection of acute pyelonephritis.`, 
        `Sonography should be considered during acute infection when the patient fails to respond to antibiotic treatment.`, 
        `Contrast-enhanced sonography may soon supplant voiding cystourethrogram (VCUG) as a means to diagnose vesicoureteral reflux. `, 
        `Dimercaptosuccinic acid (DMSA) renal scan is highly accurate for the detection of acute pyelonephritis and renal scarring. `,
        ],
        optionFeedback: [
                        `Sonography is not very sensitive for the detection of acute pyelonephritis.`,
                    
          ``],
        optionStyleType: `st-lower-alpha`,
        answer: [0],
        ansText: `Rationale: Sonography is not sensitive for the detection of vesicoureteral reflux.`,
        state: `notAnswered`,
        userAnswered: []
              ,
        type: `MCSS`},
      {
        q: `Identify the false statement about imaging the acute scrotum.`,
        q2: ``,
        q3: [],
        option: [`Surgical exploration for torsion should not be delayed to obtain scrotal imaging if the history and physical examination suggests that diagnosis.`, 
        `Salvageability of the testicle based on sonographic appearance is difficult to predict.`, 
        `Epididymo-orchitis and spontaneous detorsion can <i>both</i> demonstrate hyperemia on sonography.`, 
        ` Torsion of the appendix testis can be seen as an enlarged and avascular lower pole testicular nodule with surrounding hyperemia.`, 
        `Most prepubertal testicular masses are benign. `,
        ],
        optionFeedback: [``,
          ``,
          ``,
          ``,
          ``],
        optionStyleType: `st-lower-alpha`,
        answer: [3],
        ansText: `Rationale: Torsion of the appendix testis is not seen as an enlarged and avascular lower pole testicular nodule with surrounding hyperemia.`,
        state: `notAnswered`,
        userAnswered: []
      ,
	type: `MCSS`        ,
        type: `MCSS`},
      {
        q: `The four “key elements” to a successful diuresis renogram for the evaluation of hydronephrosis are:`,
        q2: ``,
        q3: [],
        option: [`hydration, selection of the appropriate region of interest, bladder drainage as appropriate, timing of diuretic administration.`, 
        `sedation, selection of the appropriate region of interest, bladder drainage as appropriate, timing of diuretic administration.`, 
        `hydration, selection of the appropriate region of interest, bladder drainage as appropriate, timing of diuretic administration to occur exactly when furosemide is administered.`, 
        ` hydration, selection of the appropriate region of interest, catheterization of the bladder on completion of the test, timing of diuretic administration.`, 
        `hydration, selection of the region of interest tightly around the renal cortex, bladder drainage as appropriate, timing of diuretic administration. `,
        ],
        optionFeedback: [``,
          ``,
          ``,
          ``,
          ``],
        optionStyleType: `st-lower-alpha`,
        answer: [0],
        ansText: `Rationale: The four key elements to a successful diuresis renogram are hydration, selection of the appropriate region of interest, bladder drainage as appropriate, and timing of diuretic administration.`,
        state: `notAnswered`,
        userAnswered: []
              ,
        type: `MCSS`},
    
    


]