var quiz = [

    {
        q: `The primary symptom in a 3-month-old that leads to the diagnosis of a pediatric urinary tract infection (UTI) is:`,
        q2: ``,
        q3: [],
        option: [`diarrhea`, 
        `frequency`, 
        `fever`, 
        ` jaundice`, 
        ` foul-smelling urine.`,
        ],
        optionFeedback: [``,
          ``,
          ``,
          ``,
          ``],
        optionStyleType: `st-lower-alpha`,
        answer: [2],
        ansText: `Rationale: Although all of the choices may be symptoms of a UTI in infants and young patients and UTI should be considered as a possible diagnosis, after the neonatal period fever is usually the primary symptom that leads to the diagnosis of a pediatric UTI.`,
        state: `notAnswered`,
        userAnswered: [],
	type: `MCSS`        ,
        type: `MCSS`},
      
      {
        q: `Which of the following factors would not increase the probability of a UTI in a febrile girl?`,
        q2: ``,
        q3: [],
        option: [`Age less than 12 months`, 
        `Temperature 39°C or higher`, 
        `African American race`, 
        ` Absence of other source of infection`, 
        `Recent previous UTI `,
        ],
        optionFeedback: [``,
          ``,
          ``,
          ``,
          ``],
        optionStyleType: `st-lower-alpha`,
        answer: [2],
        ansText: `Rationale: The probability of a UTI in girls has been shown to be at least 1%, and 2% if they had two or more, or three or more, of the following risk factors, respectively: white race, age younger than 12 months, temperature at or above 39°<b>C, fever lasting 2 days or more, or absence of another source of infection</b> (Gorelick and Shaw, 2000).<sup>a</sup> In addition, children with a previous UTI are at increased risk for UTI. Children younger than 6 years with a documented UTI have been noted to have a 12% risk of recurrence per year in a community-based study (Conway et al., 2007).
        <br /><br /><b>a</b> Sources referenced can be found in <i>Campbell-Walsh-Wein Urology, 12th Edition</i>, on the Expert Consult website`,
        state: `notAnswered`,
        userAnswered: [],
	   type: `MCSS`
              ,
        type: `MCSS`},
      

      {
        q: `A false-negative urinary nitrite test for UTI may be caused by all of the following EXCEPT:`,
        q2: ``,
        q3: [],
        option: [`gram-positive bacterial UTI.`, 
        `urinary retention.`, 
        `dilute urine.`, 
        ` yeast infection.`, 
        `frequent urination. `,
        ],
        optionFeedback: [``,
          ``,
          ``,
          ``,
          ``],
        optionStyleType: `st-lower-alpha`,
        answer: [1],
        ansText: `Rationale: Urinary nitrite is reduced from dietary nitrates in the urine by gram-negative enteric bacteria. This conversion requires several hours to occur; thus a first morning urine sample gives the best sensitivity with this test. Frequent urination, as is often the case in infants and small children, may not permit enough time for the urine in the bladder to undergo significant conversion of nitrates to nitrites and therefore result in a false-negative nitrite test more frequently than in older children (Mori et al., 2010). A dilute urine may also generate a false-negative test. Other reasons for a false-negative test include infection with gram-positive organisms that do not reduce nitrates.`,
        state: `notAnswered`,
        userAnswered: [],
	type: `MCSS`        ,
        type: `MCSS`},

      {
        q: `Which of the following tests has the highest sensitivity for UTI?`,
        q2: ``,
        q3: [],
        option: [`Leukocyte esterase`, 
        `Urinary nitrite`, 
        `Urinary nitrate`, 
        `Serum procalcitonin `, 
        ` Urine protein`,
        ],
        optionFeedback: [``,
          ``,
          ``,
          ``,
          ``],
        optionStyleType: `st-lower-alpha`,
        answer: [0],
        ansText: `Rationale: Leukocyte esterase has a relatively high sensitivity but low specificity. <b>Urinary nitrite has a very high specificity.</b> Urinary nitrite is formed by bacterial enzymatic reduction of urinary nitrate. Procalcitonin may be useful in identifying children with acute pyelonephritis.`,
        state: `notAnswered`,
        userAnswered: [],
        type: `MCSS`},
      

      {
        q: `Which of the following statements is FALSE regarding dimercaptosuccinic acid (DMSA) renal scan?`,
        q2: ``,
        q3: [],
        option: [`The maximum sensitivity for detection of acute pyelonephritis is within 1 week from the onset of symptoms.`, 
        `Demonstration of irreversible renal damage and scar may require a renal scan at least 1 year after pyelonephritis.`, 
        `The risk of an abnormal scan increases with increased grades of vesicoureteral reflux (VUR).`, 
        ` The estimated radiation dose is approximately 1 mSv.`, 
        ` DMSA is bound to the glomerular basement membrane, providing excellent cortical imaging but slow excretion.`,
        ],
        optionFeedback: [``,
          ``,
          ``,
          ``,
          ``],
        optionStyleType: `st-lower-alpha`,
        answer: [4],
        ansText: `Rationale: All other statements are true. DMSA is injected intravenously and taken up by the kidney, bound to the proximal renal tubular cells, and excreted very slowly in the urine, providing good and stable imaging of the renal cortex.`,
        state: `notAnswered`,
        userAnswered: []
      ,
        type: `MCSS`},
      

      {
        q: `Which of the following statements regarding imaging is most likely to be broadly accepted?`,
        q2: ``,
        q3: [],
        option: [`All children with febrile UTI require a voiding cystourethrogram (VCUG).`, 
        `All children with a febrile UTI require a renal ultrasound.`, 
        `All children with fever persisting longer than 48 hours after appropriate antibiotics require a renal and bladder ultrasound.`, 
        `All children with a febrile UTI require a DMSA. `, 
        `All children with fever persisting longer than 48 hours after appropriate antibiotics require a computed tomography (CT) scan. `,
        ],
        optionFeedback: [``,
          ``,
          ``,
          ``,
          ``],
        optionStyleType: `st-lower-alpha`,
        answer: [2],
        ansText: `Rationale: There is a lack of consensus among various guidelines around the world on what routine imaging, if any, is required with a febrile UTI. However, significant clinical improvement including defervescence routinely takes at least 24 hours after beginning antibiotics (Hoberman et al., 1999). Ninety percent of children will have a normal body temperature within 48 hours of the start of therapy, but if the child is not improving after 48 hours, a renal and bladder ultrasound should be strongly considered.`,
        state: `notAnswered`,
        userAnswered: []
	   ,
        type: `MCSS`},
      

      {
        q: `The most common pediatric uropathogen is:`,
        q2: ``,
        q3: [],
        option: [`<i>Escherichia coli.</i>`, 
        `Klebsiella`, 
        `Proteus`, 
        ` Enterobacter`, 
        `Citrobacter `,
        ],
        optionFeedback: [``,
          ``,
          ``,
          ``,
          ``],
        optionStyleType: `st-lower-alpha`,
        answer: [0],
        ansText: `Rationale:<!--a.--> <i>E. coli</i> remains the most common pediatric uropathogen (&gt;80% of UTIs). `,
        state: `notAnswered`,
        userAnswered: [],
	   type: `MCSS`
              ,
        type: `MCSS`},
      

      {
        q: `Ampicillin should be strongly considered for use with neonates because of the increased incidence of which uropathogen?`,
        q2: ``,
        q3: [],
        option: [`<i>E. coli</i>`, 
        `<i>Klebsiella</i>`, 
        `<i>Pseudomonas</i>`, 
        `<i>Enterococcus</i> `, 
        ` <i>Staphylococcus aureus</i>`,
        ],
        optionFeedback: [``,
          ``,
          ``,
          ``,
          ``],
        optionStyleType: `st-lower-alpha`,
        answer: [3],
        ansText: `Rationale: Neonates and young infants should be covered for <b><i>Enterococcus</i> species when choosing empiric antibiotics, because the incidence of infections with this uropathogen is higher in early infancy than at a later age</b> (Beetz and Westenfelder, 2011). <b><i>Enterococcus</i></b> is frequently sensitive to ampicillin and first-generation cephalosporins. `,
        state: `notAnswered`,
        userAnswered: [],
	type: `MCSS`        ,
        type: `MCSS`},
      

      {
        q: `Which of the following antibiotics would NOT be a good choice for a child with suspected pyelonephritis?`,
        q2: ``,
        q3: [],
        option: [`Fluoroquinolones`, 
        `Trimethoprim`, 
        `Cephalosporin`, 
        ` Nitrofurantoin`, 
        ` Gentamicin`,
        ],
        optionFeedback: [``,
          ``,
          ``,
          ``,
          ``],
        optionStyleType: `st-lower-alpha`,
        answer: [3],
        ansText: `Rationale: Nitrofurantoin has poor tissue penetration and should not be used for febrile UTI/pyelonephritis.`,
        state: `notAnswered`,
        userAnswered: [],
	   type: `MCSS`
              ,
        type: `MCSS`},
      

      {
        q: `Which of the following antibiotics is contraindicated in children younger than 6 weeks?`,
        q2: ``,
        q3: [],
        option: [`Trimethoprim-sulfamethoxazole`, 
        `Amoxicillin-clavulanate`, 
        `Cephalexin`, 
        ` Piperacillin`, 
        ` Tobramycin`,
        ],
        optionFeedback: [``,
          ``,
          ``,
          ``,
          ``],
        optionStyleType: `st-lower-alpha`,
        answer: [0],
        ansText: `Rationale: Trimethoprim-sulfamethoxazole (TMP-SMX) is contraindicated in premature infants and newborns younger than 6 weeks. Sulfonamides may compete for bilirubin binding sites on albumin and cause neonatal hyperbilirubinemia and kernicterus, so TMP-SMX is avoided in the first 6 weeks of life.`,
        state: `notAnswered`,
        userAnswered: [],
	   type: `MCSS`
              ,
        type: `MCSS`},
      

      {
        q: `Which of the following have been identified as risk factors for UTI?`,
        q2: ``,
        q3: [],
        option: [`Constipation`, 
        `Bladder dysfunction`, 
        `High-grade VUR`, 
        ` Female gender, older than 1 year`, 
        `All of the above `,
        ],
        optionFeedback: [``,
          ``,
          ``,
          ``,
          ``],
        optionStyleType: `st-lower-alpha`,
        answer: [4],
        ansText: `Rationale: All of the listed options have been identified as risk factors. Boys in the first year of life have a higher incidence of UTIs than girls.`,
        state: `notAnswered`,
        userAnswered: [],
	   type: `MCSS`
              ,
        type: `MCSS`},
      

      {
        q: `Which of the following is NOT true regarding renal scars?`,
        q2: ``,
        q3: [],
        option: [`Increased incidence occurs with delayed treatment of a UTI`, 
        `May be indistinguishable on renal scan from renal dysplasia`, 
        `Most frequently seen in midportion of the kidney parenchyma`, 
        `Involve a loss of renal parenchymal tissue `, 
        `Have been associated with an increased risk of hypertension `,
        ],
        optionFeedback: [``,
          ``,
          ``,
          ``,
          ``],
        optionStyleType: `st-lower-alpha`,
        answer: [2],
        ansText: `Rationale: Pyelonephritic scarring occurs most commonly in the poles of the kidney and is associated with compound papillae (Hannerz et al., 1987).`,
        state: `notAnswered`,
        userAnswered: [],
	   type: `MCSS`
              ,
        type: `MCSS`},
      

      {
        q: `Children with significant bilateral renal scars require:`,
        q2: ``,
        q3: [],
        option: [`prophylactic antibiotics.`, 
        `renin-angiotensin antagonists.`, 
        `dietary modification.`, 
        ` long-term assessment of proteinuria.`, 
        ` none of the above.`,
        ],
        optionFeedback: [``,
          ``,
          ``,
          ``,
          ``],
        optionStyleType: `st-lower-alpha`,
        answer: [3],
        ansText: `Rationale: Although certain children with significant bilateral renal scars may benefit from a, b, or c, on a routine basis, children with significant bilateral renal scars or reduction of renal function warrant long-term follow-up for assessment of hypertension, renal function, and proteinuria. Recent studies suggest that proteinuria not only may be a clinical feature of chronic kidney disease but may hasten its progression. The use of renin-angiotensin antagonists may slow the progression of chronic kidney disease in some of these patients (Wong et al., 2009).`,
        state: `notAnswered`,
        userAnswered: [],
	   type: `MCSS`
              ,
        type: `MCSS`},
      

      {
        q: `Which of the following statements regarding recurrent UTIs is FALSE?`,
        q2: ``,
        q3: [],
        option: [`The risk of a recurrent UTI is higher in a boy with an initial UTI who is younger than 1 year than in one who is older than 1 year.`, 
        `Ten percent to 30% of children will develop at least one recurrent UTI.`, 
        `The recurrence rate is highest within the first 3 to 6 months following a UTI.`, 
        ` The more frequent and more recurrent a child’s UTIs, the more likely the child is to have subsequent UTIs.`, 
        ` The risk of renal scars increases with recurrent UTIs.`,
        ],
        optionFeedback: [``,
          ``,
          ``,
          ``,
          ``],
        optionStyleType: `st-lower-alpha`,
        answer: [0],
        ansText: `Rationale: For boys younger than 1 year, 18% will develop a recurrent infection, usually within the next year. If the initial infection is in a boy older than 1 year, his risk of a reinfection increases to 32%. A similar trend is noted in girls younger than and older than 1 year of age, who have a recurrence risk of 26% and 40%, respectively (Winberg et al., 1974). `,
        state: `notAnswered`,
        userAnswered: [],
	   type: `MCSS`
              ,
        type: `MCSS`},
      

      {
        q: `In children aged 0 to 24 months who present with a fever, which of the following signs/symptoms are not useful in suspecting that they may have a UTI as the cause of their fever?`,
        q2: ``,
        q3: [],
        option: [`Fever greater than 40°C`, 
        `Vomiting`, 
        `History of a previous UTI`, 
        ` Suprapubic tenderness`, 
        `Uncircumcised penis `,
        ],
        optionFeedback: [``,
          ``,
          ``,
          ``,
          ``],
        optionStyleType: `st-lower-alpha`,
        answer: [1],
        ansText: `Rationale: Vomiting has been shown to be nonspecific in predicting the presence of a UTI in patients aged 0 to 24 months of age. The remainder of the symptoms/signs are more specific for predicting the presence of a UTI. `,
        state: `notAnswered`,
        userAnswered: [],
	   type: `MCSS`
              ,
        type: `MCSS`},
      

      {
        q: `Which of the following statements is FALSE?`,
        q2: ``,
        q3: [],
        option: [`Virulent bacteria that cause UTIs are otherwise known as uropathogenic bacteria.`, 
        `Virulent bacteria possess different adaptations and fitness factors that allow them to subvert or hijack host defenses and reside in an environment in which they would not normally preside.`, 
        `Virulent bacteria have mechanisms that allow the bacteria to initially attach to urogenital mucosal surfaces and then interact with these tissues by setting off cascades of signaling and other immunologic response events and subsequently invade the bladder.`, 
        `Commensal bacteria cannot cause UTIs. `, 
        ` Commensal bacteria are defined as lacking the virulent traits that would allow bacteria to subvert a host’s immune defenses.`,
        ],
        optionFeedback: [``,
          ``,
          ``,
          ``,
          ``],
        optionStyleType: `st-lower-alpha`,
        answer: [3],
        ansText: `Rationale: Although virulent bacteria do account for the majority of UTIs, commensal bacteria may also cause a small percentage of UTIs.`,
        state: `notAnswered`,
        userAnswered: [],
	   type: `MCSS`
              ,
        type: `MCSS`},
      

      {
        q: `Which of the following is NOT considered a bacterial virulence trait?`,
        q2: ``,
        q3: [],
        option: [`Properties that improve bacterial adherence`, 
        `Properties that allow bacterial nourishment in otherwise adverse environments`, 
        `Flagellar attachments that allow bacteria to move more quickly`, 
        ` Properties that protect bacteria from the host’s immune response`, 
        `Toxins that allow bacteria to invade host cells `,
        ],
        optionFeedback: [``,
          ``,
          ``,
          ``,
          ``],
        optionStyleType: `st-lower-alpha`,
        answer: [2],
        ansText: `Rationale: Flagellae are considered a normal component of some bacteria and not necessarily a virulence trait. The remainder of the statements are true regarding virulence factors. `,
        state: `notAnswered`,
        userAnswered: [],
	   type: `MCSS`
              ,
        type: `MCSS`},
      

      {
        q: `Which of the following statements is FALSE?`,
        q2: ``,
        q3: [],
        option: [`In children younger than 1 year, UTIs are more common in boys than girls.`, 
        `After 1 year, UTIs are more prevalent in females than males, except in elderly individuals`, 
        `It has been estimated that 7% of girls and 2% of boys suffer a UTI by the age of 6 years.`, 
        `Three percent to 5% of febrile children have a UTI. `, 
        `In sexually active teenagers, there is a female predominance of UTIs. `,
        ],
        optionFeedback: [``,
          ``,
          ``,
          ``,
          ``],
        optionStyleType: `st-lower-alpha`,
        answer: [1],
        ansText: `Rationale: UTIs are more common in boys compared with girls younger than 1 year of age. After 1 year, UTIs are more common in females and remain so, even in elderly individuals.`,
        state: `notAnswered`,
        userAnswered: [],
	   type: `MCSS`
              ,
        type: `MCSS`},
      

      {
        q: `Which of the following is a TRUE statement?`,
        q2: ``,
        q3: [],
        option: [`Circumcision reduces the rate of UTI development in the first 12 months of life by almost 20-fold.`, 
        `Circumcision reduces the rate of UTI development in the first 6 months of life by almost 5-fold.`, 
        `Circumcision reduces the rate of UTI development in the first 6 months of life by almost 10-fold.`, 
        `Circumcision reduces the rate of UTI development in the first 18 months of life by almost 5-fold. `, 
        ` Circumcision does not reduce the rate of UTI.`,
        ],
        optionFeedback: [``,
          ``,
          ``,
          ``,
          ``],
        optionStyleType: `st-lower-alpha`,
        answer: [2],
        ansText: `Rationale: Although controversial, several studies have demonstrated that the risk of UTI appears to correlate with a period during the first 6 months of life when there is an increased amount of uropathogenic bacteria colonizing the prepuce, which appears to decrease and resolve by 5 years.`,
        state: `notAnswered`,
        userAnswered: [],
	   type: `MCSS`
              ,
        type: `MCSS`},
      

      {
        q: `Which of the following statements is FALSE regarding the role that VUR plays in pediatric UTI development?`,
        q2: ``,
        q3: [],
        option: [`VUR has been identified in 1% to 2% of all newborns.`, 
        `VUR is found in 25% to 40% of children after their first episode of UTI.`, 
        `In children who are found to have a DMSA-proven episode of pyelonephritis, 66% will be found to have VUR`, 
        ` Kidneys associated with higher-grade VUR (grades III and IV) are twice as likely to have pyelonephritic changes on DMSA scan.`, 
        ` Obtaining a VCUG in only those children with an abnormal DMSA scan may miss 15%–30% of children with dilating VUR.`,
        ],
        optionFeedback: [``,
          ``,
          ``,
          ``,
          ``],
        optionStyleType: `st-lower-alpha`,
        answer: [2],
        ansText: `Rationale: Although we continually question whether VUR may be present in a child who has suffered a pyelonephritic infection, it is important to remember that the majority of children who have suffered from pyelonephritis do not have VUR. Rushton et al. (1992) found that in children suffering DMSA-proven pyelonephritis, only 37% are found to have VUR.`,
        state: `notAnswered`,
        userAnswered: [],
	   type: `MCSS`
              ,
        type: `MCSS`},
      

      {
        q: `A 9-year-old female referred for treatment of multiple afebrile UTIs suffers from urinary urgency and is known to prolong using the toilet. She suffers from day and nighttime urinary incontinence. She also has a bowel movement only every few days that is typically hard and painful. She underwent a renal ultrasound that showed normal upper tracts and a thick-walled bladder. A VCUG was performed that showed grade II left VUR and a spinning top urethra. Which of the following statements regarding treatment of this child is TRUE?`,
        q2: ``,
        q3: [],
        option: [`The use of anticholinergics in this child would not help to resolve her VUR.`, 
        `Biofeedback would be of no use in this patient because it has not been shown to improve VUR resolution and further UTI development.`, 
        `Treatment of her constipation may improve her day and nighttime urinary incontinence and help to reduce the incidence of recurrent UTIs.`, 
        ` The implementation of a timed voiding schedule would not be appropriate because this child requires urgent surgical therapy for treatment of her VUR to prevent further UTI development.`, 
        ` Treatment of her dysfunctional elimination should not be considered because she has VUR.`,
        ],
        optionFeedback: [``,
          ``,
          ``,
          ``,
          ``],
        optionStyleType: `st-lower-alpha`,
        answer: [2],
        ansText: `Rationale: This child suffers from dysfunctional bowel and bladder issues that are known to contribute to UTI development and VUR. Treatment of her bladder issues with antimuscarinics, biofeedback, and timed voiding would be appropriate, along with therapies to treat her constipation, before considering surgical therapy. In fact, these conservative therapies often will eliminate the need for any surgery for VUR treatment.`,
        state: `notAnswered`,
        userAnswered: [],
	   type: `MCSS`
              ,
        type: `MCSS`},
      
      {
        q: `Multiple studies demonstrate that _____ of individuals who intermittently catheterize develop chronic bacteria and/or pyuria and most are asymptomatic.`,
        q2: ``,
        q3: [],
        option: [`40% to 80%`, 
        `50% to 90%`, 
        `30% to 60%`, 
        `10% to 25% `, 
        ` 45% to 85%`,
        ],
        optionFeedback: [``,
          ``,
          ``,
          ``,
          ``],
        optionStyleType: `st-lower-alpha`,
        answer: [0],
        ansText: `Rationale: Of individuals who intermittently catheterize, 40% to 80% develop chronic bacteruria and/or pyuria. Most of these individuals are asymptomatic and do not require antibiotic prophylaxis or treatment. `,
        state: `notAnswered`,
        userAnswered: [],
	   type: `MCSS`
              ,
        type: `MCSS`},
      
      {
        q: `Which of the following statements is FALSE?`,
        q2: ``,
        q3: [],
        option: [`Catheter-associated UTI is the second most common nosocomial infection, accounting for more than 1 million cases each year in U.S. hospitals and nursing homes.`, 
        `The risk of UTI increases with the length of time that the catheter is in place.`, 
        `Nosocomial UTIs typically necessitate one extra hospital day per patient and nearly 1 million extra hospital days annually.`, 
        ` The best way to avoid a catheter-related UTI and its related cost is the judicious use of urinary catheters and to remove urethral catheters in hospitalized patients as soon as they are no longer medically necessary.`, 
        ` In children, nosocomial UTIs account for 6% to 18% of nosocomial infections on pediatric hospital services.`,
        ],
        optionFeedback: [``,
          ``,
          ``,
          ``,
          ``],
        optionStyleType: `st-lower-alpha`,
        answer: [0],
        ansText: `Rationale: Catheter-associated UTIs are the most common nosocomial infections affecting children. The risk increases with the duration that the catheter is in place. The best way to avoid these infections is to use urinary catheters judiciously and to remove them from hospitalized patients as soon as they are no longer medically necessary. `,
        state: `notAnswered`,
        userAnswered: [],
	   type: `MCSS`
              ,
        type: `MCSS`},
      

      {
        q: `A 9-year-old female presents with fevers, nausea, vomiting, and flank pain and is shown to have a culture-proven UTI. If she underwent a DMSA scan, how likely is it that the scan would show changes associated with pyelonephritis?`,
        q2: ``,
        q3: [],
        option: [`95% to 100%`, 
        `50% to 66%`, 
        `60% to 75%`, 
        `70% to 85% `, 
        ` 10% to 25%`,
        ],
        optionFeedback: [``,
          ``,
          ``,
          ``,
          ``],
        optionStyleType: `st-lower-alpha`,
        answer: [2],
        ansText: `Rationale: We use signs and symptoms such as fever, flank pain, nausea, and vomiting to clinically define a pyelonephritic UTI. <b>However, it is important to remember that acute changes on a DMSA renal scan at the time of a UTI is currently the “gold standard” for indicating that a child truly has pyelonephritis.</b> When a patient presents with these pyelonephritic symptoms, a DMSA scan is positive only 50% to 66% of the time.`,
        state: `notAnswered`,
        userAnswered: [],
	   type: `MCSS`
              ,
        type: `MCSS`},
      

      {
        q: `Which of the following statements is FALSE regarding why bacteria within a biofilm may be difficult to eradicate with antibiotics?`,
        q2: ``,
        q3: [],
        option: [`Antibiotics often fail to penetrate the full depth of a biofilm.`, 
        `Organisms within a biofilm often grow quickly, resulting in resistance to the antibiotics`, 
        `Antimicrobial binding proteins are poorly expressed in these biofilm bacteria.`, 
        `Bacteria within a biofilm activate many genes that alter the cell envelope, the molecular targets, and the susceptibility to antimicrobial agents. `, 
        ` Bacteria in a biofilm can survive in the presence of antimicrobial agents at a concentration 1000 to 1500 times higher than the concentration normally necessary to kill non–biofilm-associated bacteria in the same species.`,
        ],
        optionFeedback: [``,
          ``,
          ``,
          ``,
          ``],
        optionStyleType: `st-lower-alpha`,
        answer: [1],
        ansText: `Rationale: Bacteria within a biofilm have been found to grow at a slower than normal rate, making them more resistant to antibiotic therapy.`,
        state: `notAnswered`,
        userAnswered: [],
	   type: `MCSS`
              ,
        type: `MCSS`},
      

      {
        q: `A girl who presents for a preschool physical is found to have more than 10<sup>5</sup> colony-forming units (CFU)/mL <i>E. coli</i> on a urine culture. She has never previously suffered a UTI and is asymptomatic. How should she be treated?`,
        q2: ``,
        q3: [],
        option: [`Three-day course of antibiotics`, 
        `Urodynamics and kidney-ureter-bladder (KUB) radiography for evaluation of occult voiding dysfunction and constipation`, 
        `Renal ultrasound and VCUG`, 
        `No treatment or further evaluation is necessary. `, 
        `A catheterized urine specimen should be obtained to verify that this is truly a UTI. `,
        ],
        optionFeedback: [``,
          ``,
          ``,
          ``,
          ``],
        optionStyleType: `st-lower-alpha`,
        answer: [3],
        ansText: `Rationale: ASB occurs in 0.8% of preschool girls and even fewer preschool boys. Children in this age group who are without VUR and/or other genitourinary abnormalities do not require antibiotics to clear their bacteria because they do not appear to be at any risk for recurrent symptomatic infections, renal damage, or impaired renal growth.`,
        state: `notAnswered`,
        userAnswered: [],
	   type: `MCSS`
              ,
        type: `MCSS`},
      

      {
        q: `>Which of the following statements is FALSE?`,
        q2: ``,
        q3: [],
        option: [`Recurrent UTIs can be subdivided into unresolved bacteriuria, bacterial persistence, and reinfection.`, 
        `Unresolved bacteriuria is most commonly caused by inadequate bacterial therapy.`, 
        `Bacterial persistence and reinfection occur after sterile urine has been documented after previous UTI therapy.`, 
        `In cases of bacterial reinfection, typically a nidus causing the infection has not been eradicated. `, 
        `Asymptomatic bacteriuria (ASB) is defined as the presence of two consecutive urine specimens yielding positive cultures (more than 105 CFU/mL) of the same uropathogen in a patient who is free of any infectious symptoms. `,
        ],
        optionFeedback: [``,
          ``,
          ``,
          ``,
          ``],
        optionStyleType: `st-lower-alpha`,
        answer: [3],
        ansText: `Rationale: Typically, a nidus causing a UTI has not been eradicated in cases of bacterial persistence, not bacterial reinfection.`,
        state: `notAnswered`,
        userAnswered: [],
	   type: `MCSS`
              ,
        type: `MCSS`},
      

      {
        q: `Which of the following is TRUE regarding a renal abscess?`,
        q2: ``,
        q3: [],
        option: [`Individuals presenting with a renal abscess commonly are more ill than patients with just pyelonephritis.`, 
        `In as many as 30% of renal abscess cases, the urine culture may be negative.`, 
        `CT appears to be the most sensitive and specific imaging modality in making the diagnosis of a renal abscess.`, 
        ` Associated early CT findings include a poorly defined area of low attenuation or decreased enhancement or a striated, wedge-shaped zone of increased or decreased enhancement.`, 
        ` Ultrasound can detect an abscess as small as 2 cm and usually appears as a sonolucent area containing low-amplitude echoes.`,
        ],
        optionFeedback: [``,
          ``,
          ``,
          ``,
          ``],
        optionStyleType: `st-lower-alpha`,
        answer: [2],
        ansText: `Rationale: Individuals presenting with a renal abscess often have symptoms similar to those of patients with pyelonephritis. In as many as 20% of renal abscess cases, the urine culture may be negative. Ultrasound can detect an abscess as small as 1 cm, which usually appears as a sonolucent area containing low-amplitude echoes. CT appears to be the most sensitive and specific imaging modality in making the diagnosis of a renal abscess.`,
        state: `notAnswered`,
        userAnswered: [],
	   type: `MCSS`
              ,
        type: `MCSS`},
      

      //{
      //q: `Which of the following defines a UTI?`,
       //q2: ``,
        //q3: [],
        //option: [`If a suprapubic aspiration was performed, then recovery of any organisms defines a UTI.`, 
        //`For catheterized specimens, recovery of at least 10,000 CFU/mL is required to define a UTI.`, 
        //`If the specimen was collected via a clean catch method, 50,000 CFU/mL are required.`, 
        //` If a suprapubic aspiration was performed, then recovery of at least 10,000 CFU/mL organisms defines a UTI.`, 
        //`No matter how the culture is collected, the presence of 10,000 CFU/mL defines a UTI. `,
        //],
        //optionFeedback: [``,
          //``,
          //``,
          //``,
          //``],
        //optionStyleType: `st-lower-alpha`,
        //answer: [0],
        //ansText: `Rationale: For catheterized specimens, recovery of at least 50,000 CFU/mL is required to define a UTI, and 100,000 CFU/mL are required if the specimen was collected via a clean catch method. `,
        //state: `notAnswered`,
        //userAnswered: []
      //},

]