var quiz = [
    {
        q: `The mature nephron segments arise from which embryonic precursors?`,
        q2: ``,
        q3: [],
        option: [`Pronephros`, 
        `Mesonephros`, 
        `Mesonephric duct`, 
        `Metanephros `, 
        ` A combination of the mesonephros and metanephros`,
        ],
        optionFeedback: [``,
          ``,
          ``,
          ``,
          ``],
        optionStyleType: `st-lower-alpha`,
        answer: [3],
        ansText: `Rationale: The metanephros forms the mature nephron segments. The pronephros undergoes complete involution, while residual segments of the mesonephros, the mesonephric duct, forms portions of the urinary tract.`,
        state: `notAnswered`,
        userAnswered: []
        ,
        type: `MCSS`},
    {
      q: `In term infants, which of the following are fully mature?`,
      q2: ``,
      q3: [],
      option: [`Glomerular filtration rate (GFR)`, 
      `Tubular maturation`, 
      `Nephrogenesis`, 
      ` Renal growth`, 
      `Renal sodium regulation `,
      ],
      optionFeedback: [``,
        ``,
        ``,
        ``,
        ``],
      optionStyleType: `st-lower-alpha`,
      answer: [2],
      ansText: `Rationale: Nephrogenesis is complete by 34 to 36 weeks post conception, whether in utero or ex utero. Tubular maturation, including urinary sodium regulation, continues for weeks to months post partum. GFR reaches adult levels by 2 years of age, whereas renal growth continues until the postpubertal period. `,
      state: `notAnswered`,
      userAnswered: []
        ,
        type: `MCSS`},
  
  {
    q: `A 10-year-old healthy boy is found on routine physical examination to have asymptomatic microscopic hematuria. Urinalysis reveals yellow urine with a specific gravity of 1.020, pH 6, no protein, and moderate amount of blood. The microscopic examination shows 5 to 6 red blood cells (RBCs) per high-powered field and no white blood cells, bacteria, or crystals. The most appropriate next step would be:`,
    q2: ``,
    q3: [],
    option: [`renal ultrasonography.`, 
    `spot urine calcium and creatinine determinations.`, 
    `urine culture.`, 
    `measurement of serum creatinine. `, 
    `repeat urinalysis in 2 weeks. `,
    ],
    optionFeedback: [``,
      ``,
      ``,
      ``,
      ``],
    optionStyleType: `st-lower-alpha`,
    answer: [4],
    ansText: `Rationale: In a healthy asymptomatic child, isolated microscopic hematuria can occur in up to 1% of school-age children. With repeat measure, less than 25% will have persistent hematuria. Should the microscopic hematuria be persistent, then screening studies of renal function, renal structure, urinary calcium excretion, and possible infection are indicated. `,
    state: `notAnswered`,
    userAnswered: []
        ,
        type: `MCSS`},

{
  q: `Urine protein excretion can be assessed qualitatively and quantitatively; which of the following represents abnormal urine protein excretion?`,
  q2: ``,
  q3: [],
  option: [`A term infant with a urine protein to creatinine ratio (UPC) of 0.6 mg/mg`, 
  `A 13-year-old girl with a UPC of 1.0 mg/mg`, 
  `A first morning urine sample with a UPC of 0.1 mg/mg`, 
  `A 24-hour urine collection in a 15-year-old male with 150 mg of total protein `, 
  `A 12-hour urine collection with 3.1 mg/m<sup>2</sup>/h of protein `,
  ],
  optionFeedback: [``,
    ``,
    ``,
    ``,
    ``],
  optionStyleType: `st-lower-alpha`,
  answer: [1],
  ansText: `Rationale: A UPC of greater than 1.0 mg/mg is abnormal. Normal urine protein excretion as measured by UPC is less than 0.7 mg/m in a newborn and less than 0.2 mg/mg in older children. A 24-hour protein collections in adolescents and adults should be less than 200 mg/24 h or in younger children less than 4 mg/m<sup>2</sup>/h. A UPC of greater than 2.0 mg/mg defines nephrotic range proteinuria.`,
  state: `notAnswered`,
  userAnswered: []
        ,
        type: `MCSS`},

{
  q: `A 6-year-old boy presents with generalized swelling and weight gain. His blood pressure is normal and his urinalysis notes clear yellow urine, a specific gravity of 1.030, pH 5.5, 3+ protein, and trace blood. Laboratory testing shows a creatinine of 0.2 mg/dL, an albumin of 1.8 gm/dL, a cholesterol of 350 mg/dL, and a spot UPC of 10 mg/mg. The most likely cause of his nephrotic syndrome is:`,
  q2: ``,
  q3: [],
  option: [`congenital nephrotic syndrome.`, 
  `focal segmental glomerulosclerosis.`, 
  `membranous nephropathy.`, 
  `mesangial proliferation. `, 
  `minimal change disease. `,
  ],
  optionFeedback: [``,
    ``,
    ``,
    ``,
    ``],
  optionStyleType: `st-lower-alpha`,
  answer: [4],
  ansText: `Rationale: The most common cause of nephrotic syndrome in childhood is minimal change disease. Congenital nephrotic syndrome by definition is seen in children younger than 3 months of age. Membranous nephropathy and mesangial proliferation are seen less frequently in childhood, whereas focal segmental glomerulosclerosis (FSGS) become increasing common during adolescence and late childhood. `,
  state: `notAnswered`,
  userAnswered: []
        ,
        type: `MCSS`},

{
  q: `An 8-year-old boy is seen in the emergency room with new-onset headaches and gross hematuria. He has no history of fever, dysuria, joint pains, rash, or abdominal pain. He had a sore throat 2 weeks before, which resolved with antibiotics. His blood pressure is 125/90 mm Hg, and his physical examination is remarkable for 1+ lower extremity edema. The urinalysis notes tea-colored urine with a specific gravity = 1.025, pH = 6.5, large blood, and 2+ protein. His diagnostic evaluation should include all of the following EXCEPT:`,
  q2: ``,
  q3: [],
  option: [`computed tomography (CT) of the abdomen and pelvis.`, 
  `comprehensive metabolic panel.`, 
  `C3 determination.`, 
  `antistreptolysin O (ASO)/DNase B titer. `, 
  `microscopic examination of the urine. `,
  ],
  optionFeedback: [``,
    ``,
    ``,
    ``,
    ``],
  optionStyleType: `st-lower-alpha`,
  answer: [0],
  ansText: `Rationale: A child presenting with symptomatic hypertension and gross hematuria is strongly suggestive of acute glomerulonephritis. The prior history of pharyngitis is consistent with poststreptococcal-associated disease. Examination of the urine sediment for signs of glomerulonephritis (cellular casts) and documentation of renal function and electrolytes, as well as elevated antistreptolysin O titer and decreased C3, are recommend to confirm the diagnosis. Abdominal CT scans play no role in the initial evaluation of suspected acute glomerulonephritis. `,
  state: `notAnswered`,
  userAnswered: []
        ,
        type: `MCSS`},

{
  q: `The causes of hypocomplementemic nephritis in children include all of the following EXCEPT:`,
  q2: ``,
  q3: [],
  option: [`poststreptococcal glomerulonephritis.`, 
  `membranoproliferative glomerulonephritis.`, 
  `lupus nephritis.`, 
  `antineutrophil cytoplasmic antibody (ANCA)–associated glomerulonephritis. `, 
  ` C3 glomerulopathy.`,
  ],
  optionFeedback: [``,
    ``,
    ``,
    ``,
    ``],
  optionStyleType: `st-lower-alpha`,
  answer: [3],
  ansText: `Rationale: Serum complement levels are very useful in narrowing the differential diagnosis in acute glomerulonephritis. Low C3 and C4 levels are seen in lupus nephritis and membranoproliferative glomerulonephritis (MPGN), whereas low C3 and normal C4 levels are seen in postinfectious glomerulonephritis (PIGN) and C3 glomerulonephritis (C3GN). Complement levels are normal in patients with ANCA-associated glomerulonephritis. `,
  state: `notAnswered`,
  userAnswered: []
        ,
        type: `MCSS`},

{
  q: `A 6-year-old girl is seen in the emergency room with complaints of abdominal and joint pains with gross hematuria. Her blood pressure is normal. Her physical examination is remarkable for a raised red rash on her lower legs and buttocks, mild abdominal pain on palpation, and bilateral ankle pain with minimal swelling. Her urinalysis noted tea-colored urine with a specific gravity of 1.020, pH 6.5, 3+ blood, and 2+ protein; urine microscopy showed numerous RBC cast. Her most likely diagnosis is:`,
  q2: ``,
  q3: [],
  option: [`Henoch-Schönlein purpura (HSP).`, 
  `Postinfectious glomerulonephritis.`, 
  `Hemolytic uremic syndrome (HUS).`, 
  `Alport syndrome. `, 
  `ANCA-associated glomerulonephritis. `,
  ],
  optionFeedback: [``,
    ``,
    ``,
    ``,
    ``],
  optionStyleType: `st-lower-alpha`,
  answer: [0],
  ansText: `Rationale: HSP is a systemic vasculitis that is characterized by purpuric rash, commonly on legs and buttocks, abdominal pain, arthritis, and nephritis. HUS is commonly seen in association with bloody diarrhea. Alport syndrome is not commonly seen with systemic complaints, whereas PIGN is usually preceded by either pharyngitis or impetigo. ANCA-associated glomerulonephritis, although rare is childhood, can be seen in older children or adolescents, and systemic complaints including fever are common.`,
  state: `notAnswered`,
  userAnswered: []
        ,
        type: `MCSS`},

{
  q: `A 3-year-old boy presents to clinic with failure to thrive. His blood pressure is normal. His initial evaluation is remarkable for a serum sodium of 144 meq/L, potassium of 2.5 meq/L, a chloride of 105 meq/L, a HCO<sub>3</sub> of 9 meq/L, and a phosphorus of 4.5 mg/dL. A urinalysis notes a specific gravity = 1.005, pH = 7.0, and no blood or protein. A renal ultrasound shows normal renal size and shape with findings consistent with nephrocalcinosis. His most likely diagnosis is:`,
  q2: ``,
  q3: [],
  option: [`Fanconi syndrome.`, 
  `proximal renal tubular acidosis (RTA).`, 
  `Bartter syndrome.`, 
  `Dent disease. `, 
  `distal RTA. `,
  ],
  optionFeedback: [``,
    ``,
    ``,
    ``,
    ``],
  optionStyleType: `st-lower-alpha`,
  answer: [4],
  ansText: `Rationale: Failure to thrive in an infant in association with hyperchloremic acidosis (nonanion gap) is strongly suggestive of RTA. Nephrocalcinosis is a common finding in distal RTA, as is the very low HCO<sub>3</sub> level. With proximal RTA or Fanconi, HCO<sub>3</sub> levels are typically in the 12 to 14 meq/L range, and hypophosphatemia, low-grade proteinuria, and glycosuria are commonly seen. Dent disease does not present with RTA, and Bartter syndrome is defined by metabolic alkalosis. `,
  state: `notAnswered`,
  userAnswered: []
        ,
        type: `MCSS`},

{
  q: `A 4-year-old girl is referred to clinic because her mother was recently diagnosed with cystic renal disease and a polycystin-1 mutation. Likely findings on ultrasound in this child could include all of the following EXCEPT:`,
  q2: ``,
  q3: [],
  option: [`normal renal ultrasound.`, 
  `a unilateral renal cyst.`, 
  `hepatic fibrosis.`, 
  `multiple unilateral cysts. `, 
  `multiple bilateral renal cysts. `,
  ],
  optionFeedback: [``,
    ``,
    ``,
    ``,
    ``],
  optionStyleType: `st-lower-alpha`,
  answer: [2],
  ansText: `Rationale: Hepatic fibrosis is a feature commonly seen in autosomal recessive polycystic kidney disease (ARPKD). Mutations in polycystin-1 are associated with autosomal dominant polycystic kidney disease (ADPKD). Renal ultrasound findings in childhood can be highly variable and range from “normal” to severe bilateral cystic disease.`,
  state: `notAnswered`,
  userAnswered: []
        ,
        type: `MCSS`},

{
  q: `A 10-year-old boy is seen in the emergency department with the new onset of left-sided flank pain, gross hematuria, and vomiting. His blood pressure is 100/65 mm Hg, and the physical examination reveals right costovertebral angle tenderness. The urinalysis shows brown urine with a specific gravity = 1.030, pH = 7, large amount of blood, and 2+ protein. The next step in diagnostic evaluation of choice should be:`,
  q2: ``,
  q3: [],
  option: [`high-resolution CT of abdomen/pelvis without contrast.`, 
  `microscopic examination of the urine.`, 
  `cystoscopy`, 
  `abdominal ultrasound. `, 
  ` serum electrolyte determination.`,
  ],
  optionFeedback: [``,
    ``,
    ``,
    ``,
    ``],
  optionStyleType: `st-lower-alpha`,
  answer: [3],
  ansText: `Rationale: This clinical scenario is most consistent with acute presentation of a renal or ureteral stone. Ultrasound imaging to rule out hydronephrosis and to identify presence of a stone is the best first step. Intervention for drainage is not indicated until appropriate analgesics have been initiated. CT imaging is unlikely to add further information and exposes the child to radiation.`,
  state: `notAnswered`,
  userAnswered: []
        ,
        type: `MCSS`},

{
  q: ``,
  q2: ``,
  q3: [],
  option: [`vitamin C excess.`, 
  `short gut syndrome.`, 
  `oxylate-rich diets.`, 
  `alanine:glyoxylate aminotransferase deficiency. `, 
  ` adenine phosphoribosyltransferase (APRT) deficiency.`,
  ],
  optionFeedback: [``,
    ``,
    ``,
    ``,
    ``],
  optionStyleType: `st-lower-alpha`,
  answer: [4],
  ansText: `Rationale: Hyperoxaluria can be primary, in the case of alanine:glyoxylate aminotransferase deficiency, or secondary due to excessive oxalate intake, vitamin C (a precursor of oxalate), or hyperabsorption in the case of short gut syndrome. APRT deficiency is an autosomal recessive disorder of adenine metabolism linked with recurrent dihydroxyadenine stones. `,
  state: `notAnswered`,
  userAnswered: []
        ,
        type: `MCSS`},

{
  q: `A 15-year-old boy has a blood pressure of 120/80 mm Hg during routine examination. The child is calm, and a properly sized blood pressure cuff was used for blood pressure measurement. The family history is strongly positive for essential hypertension and diabetes mellitus. His physical examination is unremarkable except for a body mass index (BMI) of 29 kg/m<sup>2</sup>. The best next step in management is to:`,
  q2: ``,
  q3: [],
  option: [`repeat blood pressure measurement in 1 to 2 weeks.`, 
  `obtain a fasting lipid profile.`, 
  `perform Doppler renal ultrasonography.`, 
  `obtain peripheral vein renin levels. `, 
  ` obtain 24-hour ambulatory blood pressure monitoring (ABPM).`,
  ],
  optionFeedback: [``,
    ``,
    ``,
    ``,
    ``],
  optionStyleType: `st-lower-alpha`,
  answer: [0],
  ansText: `Rationale: Repeat the measurement next week in the office. This child’s blood pressure is elevated, and measurement should be repeated and possible hypertension confirmed. ABPM could be considered and is recommended; however, availability is a challenge and is more practically performed after repeated office measurements. Therefore the blood pressure should be remeasured in the office. If hypertension is confirmed, the workup will include a complete metabolic panel, lipid profile, echocardiogram, and renal ultrasonography. Angiography and selective renin levels can be considered in case of severe or recalcitrant hypertension.`,
  state: `notAnswered`,
  userAnswered: []
        ,
        type: `MCSS`},

{
  q: `A 12-year-old boy is sent to the emergency department for evaluation of vomiting and decreased urination. He has a blood urea nitrogen (BUN) level = 40 mg/dL and a creatinine = 1.8 mg/dL. His urinary sodium level = 20 meq/L, fractional excretion of sodium (FE<sub>Na</sub>) = 0.8%, and urinary osmolality = 600 mOsm/kg. The most likely cause of his elevated creatinine is:`,
  q2: ``,
  q3: [],
  option: [`posterior urethral valves.`, 
  `dehydration`, 
  `interstitial nephritis.`, 
  `Hemolytic uremic syndrome. `, 
  `acute urinary tract infection (UTI). `,
  ],
  optionFeedback: [``,
    ``,
    ``,
    ``,
    ``],
  optionStyleType: `st-lower-alpha`,
  answer: [1],
  ansText: `Rationale: The initial evaluation of patients with suspected acute kidney injury (AKI) should include urinary indices including urine sodium, osmolality, and creatinine. A low urine sodium (&lt;25 meq/L) or a FeNa of less than 1% is consistent with “prerenal” AKI, or renal hypoperfusion as seen with dehydration of vomiting and/or diarrhea. An elevated BUN and creatinine due to posterior urethral valves, interstitial nephritis, or UTIs are due to “intrinsic” renal disease, and urinary sodium and FeNa (&gt;1%) are typically elevated. `,
  state: `notAnswered`,
  userAnswered: []
        ,
        type: `MCSS`},

{
  q: `Common complications of advanced chronic kidney disease in children include all of the following EXCEPT:`,
  q2: ``,
  q3: [],
  option: [`growth hormone deficiency.`, 
  `protein malnutrition.`, 
  `erythropoietin deficiency.`, 
  ` metabolic acidosis.`, 
  `1,25 vitamin D insufficiency. `,
  ],
  optionFeedback: [``,
    ``,
    ``,
    ``,
    ``],
  optionStyleType: `st-lower-alpha`,
  answer: [0],
  ansText: `Rationale: Patients with chronic kidney disease (CKD) have growth failure due to abnormalities in growth hormone activity rather than true growth hormone deficiency. Protein malnutrition, anemia from erythropoietin deficiency, chronic metabolic acidosis, and an inability to convert 25 vitamin D to active 1,25 vitamin D are all common feature of advanced CKD in children.`,
  state: `notAnswered`,
  userAnswered: []
        ,
        type: `MCSS`},

{
  q: `A 5-year-old-boy with posterior urethral valves since birth has renal function that has slowly declined, with a current creatinine = 1.7 mg/dL. His growth is impaired, with height and weight less than the third percentile. The most appropriate management strategy is:`,
  q2: ``,
  q3: [],
  option: [`referral for initiation of transplant evaluation.`, 
  `urologic evaluation for urethral obstruction.`, 
  `repeat urodynamics in expectation of preemptive transplantation.`, 
  `optimization of nutritional intake and recombinant growth hormone therapy. `, 
  `G-tube placement. `,
  ],
  optionFeedback: [``,
    ``,
    ``,
    ``,
    ``],
  optionStyleType: `st-lower-alpha`,
  answer: [4],
  ansText: `Rationale: Impairment of growth is a common feature of CKD even at an early stage, regardless of etiology. Aggressive management of nutritional needs is often insufficient, and therapy with recombinant growth hormone is indicated in the majority of patients.`,
  state: `notAnswered`,
  userAnswered: []
        ,
        type: `MCSS`},

{
  q: `The most common cause of pediatric renal allograft loss is:`,
  q2: ``,
  q3: [],
  option: [`primary anastomotic failure.`, 
  `recurrent obstructive uropathy.`, 
  `antibody mediated rejection.`, 
  ` acute cellular rejection.`, 
  `chronic allograft nephropathy. `,
  ],
  optionFeedback: [``,
    ``,
    ``,
    ``,
    ``],
  optionStyleType: `st-lower-alpha`,
  answer: [4],

  ansText: `Rationale: The most common cause of renal transplantation loss in children is chronic allograft nephropathy. Primary anastomotic failure is very rare, and recurrent obstructive uropathy in most patients can be managed with medical or surgical interventions. Acute cellular rejection, although common, is typically responsive to immunomodulation. Antibody-mediated rejection is increasing being recognized as a cause of graft failure. `,
  state: `notAnswered`,
  userAnswered: []
        ,
        type: `MCSS`},


    
   
   

      
   
    




]