var quiz = [
    
    {
        q: `All are true regarding the embryologic development of the urinary system <b>EXCEPT</b> which?`,
        q2: ``,
        q3: [],
        option: [`Between the fourth and sixth weeks of gestation, the urorectal septum divides the endodermal cloaca into a ventral urogenital sinus and a dorsal rectum.`, 
        `Around the fourth to fifth month of gestation, the allantoic duct and ventral cloaca involute as the bladder descends into the pelvis.`, 
        `The obliterated urachus becomes the median umbilical ligament and connects the apex of the bladder with the umbilicus.`, 
        `Definitive nephrons within the embryologic kidneys will begin urine production around the 12th week of gestation, and the first signs of lower urinary tract anomalies may become evident. `, 
        `Unlike the case in males, the entire female urethra is derived from the pelvic part of the urogenital sinus. `,
        ],
        optionFeedback: [``,
          ``,
          ``,
          ``,
          ``],
        optionStyleType: `st-lower-alpha`,
        answer: [3],
        ansText: `Rationale: Definitive nephrons within the embryologic kidneys will actually begin to produce urine prior to the 12th week of gestation. It is around the 10th week of gestation that the first signs of lower urinary tract anomalies may become evident.`,
        state: `notAnswered`,
        userAnswered: []
      ,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`        ,
        type: `MCSS`},
  
      {
        q: `Which of the following statements best describes visualization of the fetal bladder?`,
        q2: ``,
        q3: [],
        option: [`Transabdominal imaging is more sensitive than transvaginal imaging for early detection of the fetal bladder.`, 
        `The fetal bladder typically empties every 15 to 20 minutes, and nonvisualization of the bladder necessitates prolonged inspection to make sure that a full bladder was not missed.`, 
        `At 10 weeks of gestation the bladder will be visualized in 25% of fetuses.`, 
        `At 13 weeks of gestation the bladder will be visualized in 50% of fetuses. `, 
        ` During the first trimester the normal bladder diameter is 12 mm or less.`,
        ],
        optionFeedback: [``,
          ``,
          ``,
          ``,
          ``],
        optionStyleType: `st-lower-alpha`,
        answer: [1],
        ansText: `Rationale: The timing of ultrasound findings is important and due to the frequent cycling of the normal fetal bladder. Careful observation is needed prior to determining that a bladder is not visualized.`,
        state: `notAnswered`,
        userAnswered: []
      ,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`        ,
        type: `MCSS`},
  
      {
        q: `In prenatally detected bladder anomalies,`,
        q2: ``,
        q3: [],
        option: [`the incidence of bladder agenesis is approximately 1 per 600,000 gestations.`, 
        `bladder agenesis is most common in males.`, 
        `bladder exstrophy is most often associated with nonvisualization of the bladder and oligohydramnios.`, 
        ` most cases of bladder exstrophy are diagnosed prenatally.`, 
        ` visualization of the bladder is expected to be normal in cases of bilateral renal dysplasia.`,
        ],
        optionFeedback: [``,
          ``,
          ``,
          ``,
          ``],
        optionStyleType: `st-lower-alpha`,
        answer: [0],
        ansText: `Rationale: Bladder agenesis incidence is approximately 1 per 600,000 and is more common in females. Bladder exstrophy is typically associated with normal amniotic fluid levels, and most cases are diagnosed postnatally.`,
        state: `notAnswered`,
        userAnswered: []
      ,
	type: `MCSS`,
	type: `MCSS`        ,
        type: `MCSS`},
  
      {
        q: `Regarding megacystis,`,
        q2: ``,
        q3: [],
        option: [`the bladder is dilated secondary to high-grade reflux.`, 
        `this finding indicates that lower urinary tract obstruction (LUTO) is present.`, 
        `during the first trimester a normal bladder should be 6 mm or less.`, 
        ` beyond the first trimester a bladder that fails to empty after 15 minutes is abnormal.`, 
        ` this finding is always associated with a dilated posterior urethra.`,
        ],
        optionFeedback: [``,
          ``,
          ``,
          ``,
          ``],
        optionStyleType: `st-lower-alpha`,
        answer: [2],
        ansText: `Rationale: Megacystis commonly refers to a finding on imaging and has a varied differential beyond dilation secondary to reflux. It may or may not be associated with bladder outlet obstruction. During the first trimester, the definition of megacystis is based on size, with the normal bladder being 6 mm or less in size. Beyond the first trimester, megacystis is defined as a bladder that does not empty during 45 minutes of observation. `,
        state: `notAnswered`,
        userAnswered: []
      ,
	type: `MCSS`,
	type: `MCSS`        ,
        type: `MCSS`},
  
      {
        q: `Genetic evaluation of a fetus with megacystis is likely to demonstrate:`,
        q2: ``,
        q3: [],
        option: [`a definitive genetic diagnosis in most cases.`, 
        `a decreased rate of expected genetic anomalies based on maternal age.`, 
        `a decreased rate of expected genetic anomalies based on nuchal translucency.`, 
        `trisomy 13 or 18. `, 
        ` none of the above.`,
        ],
        optionFeedback: [``,
          ``,
          ``,
          ``,
          ``],
        optionStyleType: `st-lower-alpha`,
        answer: [3],
        ansText: `Rationale: Genetic testing in patients with the finding of megacystis is not universal, and most cases will not have a genetic diagnosis. When genetic testing is performed, the most common anomalies are trisomy 13 and 18. Genetic anomalies in patients with megacystis exceed the expected rates when maternal age and nuchal translucency are controlled for.`,
        state: `notAnswered`,
        userAnswered: []
              ,
        type: `MCSS`},
  
      {
        q: `Improved outcomes for megacystis have been noted when all are present <b>EXCEPT</b> which?`,
        q2: ``,
        q3: [],
        option: [`Aneuploidy`, 
        `Initial bladder dilation of 12 mm or less`, 
        `Resolution of megacystis by 23 weeks of gestational age`, 
        `Normal amniotic fluid levels `, 
        ` Isolated bladder findings without associated congenital anomalies`,
        ],
        optionFeedback: [``,
          ``,
          ``,
          ``,
          ``],
        optionStyleType: `st-lower-alpha`,
        answer: [0],
        ansText: `Rationale: When genetic testing is performed, positive findings are associated with poor outcomes. All other factors listed are predictors of improved outcomes.`,
        state: `notAnswered`,
        userAnswered: []
              ,
        type: `MCSS`},
  
      {
        q: `Megacystis microcolon intestinal hypoperistalsis (MMIH) syndrome:`,
        q2: ``,
        q3: [],
        option: [`is best described as the most common cause of megacystis on routine surveillance.`, 
        `is most often detected prenatally by the gastrointestinal findings.`, 
        `has more morbidity for urologic than enteric sequelae.`, 
        ` has no known survivors beyond the neonatal period.`, 
        ` is suspected of being secondary to dysfunction of actin smooth muscle.`,
        ],
        optionFeedback: [``,
          ``,
          ``,
          ``,
          ``],
        optionStyleType: `st-lower-alpha`,
        answer: [4],
        ansText: `Rationale: MMIH is a rare cause of megacystis and is most often detected by the bladder findings. The urologic sequelae are significant, although morbidity is most often due to enteric complications. Although MMIH was once thought to be incompatible with life, survival beyond the neonatal period is now well documented.`,
        state: `notAnswered`,
        userAnswered: []
      ,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`        ,
        type: `MCSS`},
  
      {
        q: `Bladder duplication will usually be associated with:`,
        q2: ``,
        q3: [],
        option: [`duplex ureters and collecting systems.`, 
        `duplication of the urethra.`, 
        `less than 25% incidence of gastrointestinal (GI) anomalies.`, 
        ` diurnal continence.`, 
        ` genital anomalies.`,
        ],
        optionFeedback: [``,
          ``,
          ``,
          ``,
          ``],
        optionStyleType: `st-lower-alpha`,
        answer: [4],
        ansText: `Rationale: Most cases of bladder duplication will be associated with genital anomalies and the urethra may or may not be duplicated. Over 25% will have GI anomalies, and continence is difficult to predict based on the anatomy alone. `,
        state: `notAnswered`,
        userAnswered: []
              ,
        type: `MCSS`},
  
      {
        q: `Which statement is most accurate regarding congenital bladder diverticula?`,
        q2: ``,
        q3: [],
        option: [`A majority are diagnosed prenatally.`, 
        `Most occur through a hiatus in the bladder wall and consist of mucosal lining only.`, 
        `The reported incidence is 20% of the population.`, 
        `A cystogram offers little information over ultrasound imaging. `, 
        `Most diverticula will require surgical resection. `,
        ],
        optionFeedback: [``,
          ``,
          ``,
          ``,
          ``],
        optionStyleType: `st-lower-alpha`,
        answer: [1],
        ansText: `Rationale: A cystogram is the definitive test for diagnosing bladder diverticula; most instances are diagnosed only following symptomatic presentation. The reported incidence is 1.7%, and most cases will not require surgical resection. `,
        state: `notAnswered`,
        userAnswered: []
              ,
        type: `MCSS`},
  
      {
        q: `Diverticula secondary to connective tissue disorders:`,
        q2: ``,
        q3: [],
        option: [`usually present as a single diverticulum.`, 
        `have walls composed of smooth muscle as well as mucosa.`, 
        `are best managed surgically before symptoms.`, 
        `have an unlikely chance of recurrence after resection. `, 
        `are often associated with increased incidence of urothelial tumors. `,
        ],
        optionFeedback: [``,
          ``,
          ``,
          ``,
          ``],
        optionStyleType: `st-lower-alpha`,
        answer: [1],
        ansText: `Rationale: Diverticula associated with connective tissue disorders will often present with multiple diverticula, and the typical histology will show smooth muscle and mucosa in the wall of the diverticulum. Surgical management can be chosen when symptomatic, and recurrence is to be expected.`,
        state: `notAnswered`,
        userAnswered: []
              ,
        type: `MCSS`},
  
      {
        q: `Regarding urachal anomalies,`,
        q2: ``,
        q3: [],
        option: [`urachal squamous cell carcinoma has been reported in some children.`, 
        `most cases of a patent urachus are associated with bladder outlet obstruction.`, 
        `resection of a urachal cyst is not recommended after treatment of a prior infection.`, 
        `a patent omphalomesenteric duct can mimic a patent urachus. `, 
        `surgical management is best performed with minimally invasive surgery. `,
        ],
        optionFeedback: [``,
          ``,
          ``,
          ``,
          ``],
        optionStyleType: `st-lower-alpha`,
        answer: [3],
        ansText: `Rationale: Adenocarcinoma of urachal anomalies has been reported in adults and is rare in children, but this is not true of squamous cell carcinoma. Most cases of a patent urachus are not associated with bladder outlet obstruction. Resection of a urachal cyst is recommended after treatment of a prior infection. Surgical management of urachal anomalies can be effectively performed with either open or minimally invasive surgery.`,
        state: `notAnswered`,
        userAnswered: []
              ,
        type: `MCSS`},
  
      {
        q: `Which statement best describes noninflammatory bladder conditions?`,
        q2: ``,
        q3: [],
        option: [`Bladder hemangiomas are often multiple.`, 
        `Bladder hemangiomas often require radical resection.`, 
        `Bladder hemangiomas are associated with Klippel-Trenaunay or Sturge-Weber syndrome.`, 
        `Fibroepithelial polyps are the most common cause of bladder masses in children. `, 
        ` Fibroepithelial polyps are difficult to treat endocscopically.`,
        ],
        optionFeedback: [``,
          ``,
          ``,
          ``,
          ``],
        optionStyleType: `st-lower-alpha`,
        answer: [2],
        ansText: `Rationale: Hemangiomas are often singular and can be associated with known syndromes. Fortunately, simple resection can be curative. Fibroepithelial polyps are rare causes of bladder masses and can usually be managed simply with endoscopic resection.`,
        state: `notAnswered`,
        userAnswered: []
              ,
        type: `MCSS`},
  
      {
        q: `Nephrogenic adenoma:`,
        q2: ``,
        q3: [],
        option: [`is more common in children than in adults.`, 
        `often demonstrates malignant transformation.`, 
        `rarely recurs after local treatment.`, 
        ` is best treated by a partial cystectomy.`, 
        ` can be seen as a reaction to infection or urolithiasis.`,
        ],
        optionFeedback: [``,
          ``,
          ``,
          ``,
          ``],
        optionStyleType: `st-lower-alpha`,
        answer: [4],
        ansText: `Rationale: This mostly benign lesion is usually described as a reaction to infection, lithiasis, or injury. Nephrogenic adenomas are more common in adults than in children. Recurrence after resection (usually cystoscopic rather than open) reaches 80%, with a latency of 4 years. `,
        state: `notAnswered`,
        userAnswered: []
              ,
        type: `MCSS`},
  
      {
        q: `When the diagnoses of cystitis cystica and eosinophilic cystitis is being considered, it is important to note that:`,
        q2: ``,
        q3: [],
        option: [`cystitis cystica more commonly occurs in males.`, 
        `eosinophilic cystitis can be treated with steroids, antihistamines, and antibiotics.`, 
        `eosinophilic cystitis more commonly occurs in females.`, 
        ` eosinophilic cystitis in young children will almost always progress.`, 
        ` cystitis cystica treatment typically includes steroids.`,
        ],
        optionFeedback: [``,
          ``,
          ``,
          ``,
          ``],
        optionStyleType: `st-lower-alpha`,
        answer: [1],
        ansText: `Rationale: eosinophilic cystitis can be treated with steroids, antihistamines, and antibiotics.`,
        state: `notAnswered`,
        userAnswered: []
              ,
        type: `MCSS`},
  
     
      
        
]