var quiz = [
  {
    q: ` Which of the following is a correct match regarding renal anomaly and associated finding?`,
    q2: ``,
    q3: [],
    option: [
      ` von Hippel-Lindau disease and adenoma sebaceum`,
      `Tuberous sclerosis and angiomyolipoma `,
      ` Autosomal dominant polycystic kidney disease (ADPKD) and salt-losing nephropathy`,
      ` Congenital nephrosis (Finnish type) and medullary cysts`,
      ` Autosomal recessive polycystic kidney disease (ARPKD) and colonic diverticulosis`,
    ],
    optionStyleType: `st-upper-alpha`,
    answer: [1],
    ansText: `Rationale: Angiomyolipomas occur in 40% to 80% of patients with tuberous sclerosis. `,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: ` The primary feature(s) associated with Ask-Upmark kidney (segmental hypoplasia) is/are:`,
    q2: ``,
    q3: [],
    option: [
      `hypertension. `,
      `renal artery intimal disease. `,
      ` found in young men and boys.`,
      `b and c. `,
      `a and c. `,
    ],
    optionStyleType: `st-upper-alpha`,
    answer: [0],
    ansText: `Rationale: Hypertension and its sequelae (headache, hypertensive encephalopathy, retinopathy, etc.) are the hallmarks of Ask-Upmark kidney. Segmental vascular anomalies have been cited as a possible cause of the hypertension, but there is no evidence that renal artery intimal disease is associated. This disease is primarily found in young women and girls.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `The development of acquired renal cystic disease (ARCD) is most related to which factor? `,
    q2: ``,
    q3: [],
    option: [
      `Age of the patient `,
      ` Duration of renal failure`,
      ` Recent initiation of hemodialysis`,
      ` <i>Escherichia coli</i> infection`,
      ` Genetic defect on chromosome 16`,
    ],
    optionStyleType: `st-upper-alpha`,
    answer: [1],
    ansText: `Rationale: At first, ARCD was thought to be confined to patients receiving hemodialysis. However, it shortly became apparent that the disorder is almost as common in patients receiving peritoneal dialysis and that it may develop in patients with chronic renal failure who are being managed medically without any type of dialysis. Thus ARCD appears to be a feature of end-stage kidney disease, rather than a response to dialysis. `,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `Which statement(s) about ARPKD is/are TRUE? `,
    q2: ``,
    q3: [],
    option: [
      `The most severe forms develop in late childhood or adolescence. `,
      ` No matter the severity of the renal disease, all patients will have liver involvement in the form of congenital hepatic fibrosis.`,
      ` In newborns, ultrasound findings include very enlarged kidneys with increased parenchymal echogenicity.`,
      ` a and b.`,
      ` b and c.`,
    ],
    optionStyleType: `st-upper-alpha`,
    answer: [4],
    ansText: `Rationale: The most severe form of ARPKD appears earliest in life, in the newborn period. <b>All patients with ARPKD have liver involvement in the form of hepatic fibrosis and vary in the degree of biliary ectasia and periportal fibrosis.</b> In both fetus and newborn, ultrasonography identifies bilateral, very enlarged, diffusely echogenic kidneys, especially when compared with the echogenicity of the liver. The increased echogenicity is due to the presence of numerous microcysts (created by tightly compacted, dilated collecting ducts) that result in innumerable interfaces. Compared with normal newborn kidneys, in ARPKD the pyramids are hyperechogenic because they blend in with the rest of the kidney, and the kidneys typically have a homogeneous appearance. `,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `Which of the following statements accurately describes a fundamental process essential for the development of renal cysts? `,
    q2: ``,
    q3: [],
    option: [
      `Proliferation of epithelial cells in segments of the renal collecting system `,
      ` Accumulation of fluid within an expanding segment of the glomerulus`,
      ` An imbalance of the secretory and absorptive properties in proliferating tubular epithelial cells`,
      ` Hypertrophy of the basement membrane within the ascending loop of Henle`,
      `Glomerular outpouching resulting from elevated glomerular hydrostatic pressure `,
    ],
    optionStyleType: `st-upper-alpha`,
    answer: [2],
    ansText: `Rationale: The fundamental processes that are essential for the development and progressive enlargement of renal cysts include (1) proliferation of epithelial cells in segments of renal tubule, (2) accumulation of fluid within the expanding tubule segment, and (3) disturbed organization and metabolism of the extracellular matrix. An imbalance of the secretory and absorptive properties in proliferating epithelial cells leads to a net accumulation of fluid in otherwise normal renal tubules. Recent evidence indicates that, beyond the loop of Henle, tubule cells have the capacity to secrete solutes and fluid on stimulation with 3′,5′-cyclic adenosine monophosphate (cAMP). This secretory flux operates in competition with the more powerful mechanism by which sodium (Na<sup>+</sup>) is reabsorbed through apical epithelial Na<sup>+</sup> channels (ENaC). Under conditions in which Na<sup>+</sup> reabsorption is diminished, the net secretion of sodium chloride (NaCl) and fluid occurs.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `Which of the following statement(s) is/are correct about ADPKD? `,
    q2: ``,
    q3: [],
    option: [
      `The genetic defect is located on the short arm of chromosome 16. `,
      ` Most affected infants have congenital hepatic fibrosis.`,
      ` Renal cysts are infrequently seen on ultrasound in affected patients before 30 years of age.`,
      ` Glomerular cysts are never found in the kidneys of newborns diagnosed with ADPKD.`,
      ` The incidence of renal cell carcinoma in ADPKD is twice that in the normal population.`,
    ],
    optionStyleType: `st-upper-alpha`,
    answer: [0],
    ansText: `Rationale: Infants with ARPKD have hepatic fibrosis, and infants with ADPKD rarely have hepatic fibrosis but commonly have cysts in the liver. Renal cysts are frequently seen in individuals on ultrasonography by the age of 20 years. Glomerular cysts are sometimes found in the kidneys of newborns diagnosed with ADPKD. The risk of renal cell carcinoma in patients with ADPKD is no higher than that in the general population.  `,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: ` All of the following are extrarenal manifestations of ADPKD EXCEPT:`,
    q2: ``,
    q3: [],
    option: [
      ` hepatic cysts.`,
      `intracranial (berry) aneurysms. `,
      `cerebellar hemangioblastomas. `,
      ` colonic diverticulosis.`,
      ` mitral valve prolapse.`,
    ],
    optionStyleType: `st-upper-alpha`,
    answer: [2],
    ansText: `Rationale: All are extrarenal manifestations of ADPKD except cerebellar hemangioblastomas, which are seen in patients with von Hippel-Lindau disease. `,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `Which of the following statements is FALSE regarding unilateral multicystic dysplastic kidneys? `,
    q2: ``,
    q3: [],
    option: [
      `The majority of multicystic dysplastic kidneys become smaller or ultrasonographically undetectable with time. `,
      ` There is an absence of communication between cysts on ultrasonographic scans.`,
      ` Cysts are usually found in communication with each other when injected intracystically with contrast material.`,
      `The sine qua non for histologic diagnosis of a multicystic dysplastic kidney is the presence of primitive ducts. `,
      ` Multicystic dysplastic kidneys appear more often in females and more often on the right side.`,
    ],
    optionStyleType: `st-upper-alpha`,
    answer: [4],
    ansText: `Rationale: At any age, the condition is more likely to be found on the left side. Males are more likely to have unilateral multicystic dysplastic kidneys (2.4:1). `,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `Flank pain is one of the most common presenting symptoms of ADPKD in adult patients. This is often caused by: `,
    q2: ``,
    q3: [],
    option: [
      ` bleeding into a cyst.`,
      `renal cell carcinoma. `,
      ` cyst rupture.`,
      ` b and c.`,
      ` a and c.`,
    ],
    optionStyleType: `st-upper-alpha`,
    answer: [0],
    ansText: `Rationale: Pain (flank and/or abdominal) is the most common presenting symptom in adults. This results from a number of possible factors: mass effect (cysts impinging on abdominal wall or neighboring organs), bleeding into the cysts, urinary tract infection (including infected cysts), and nephrolithiasis. `,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `Which gene is associated with clear cell renal cell carcinoma and a multiple malformation syndrome? `,
    q2: ``,
    q3: [],
    option: [`PDK1 `, `PDK2 `, ` TG737`, ` Wnt-2`, ` VHL`],
    optionStyleType: `st-upper-alpha`,
    answer: [4],
    ansText: `Rationale: The gene associated with the transmission of von Hippel-Lindau disease is located on chromosome 3. In non–von Hippel-Lindau patients with sporadic clear cell renal cell carcinoma, 50% of cell lines are associated with a mutational form of the VHL gene. `,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: ` A benign multilocular cyst is seen most often:`,
    q2: ``,
    q3: [],
    option: [
      ` in males younger than 4 years and in females older than 30 years.`,
      ` in females younger than 4 years and in males older than 30 years.`,
      `in males between 4 and 30 years. `,
      ` equally in both sexes before 4 years and in females after 30 years.`,
      ` equally in both sexes before 4 years and in males after 30 years.`,
    ],
    optionStyleType: `st-upper-alpha`,
    answer: [0],
    ansText: `Rationale: The great majority of patients present before the age of 4 years or after the age of 30 years. Five percent present between 4 and 30 years. The patient is 2 times as likely to be male if younger than 4 years and 8 times as likely to be female if older than 30 years.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: ` What is the primary distinguishing factor between juvenile nephronophthisis (NPH) and medullary cystic kidney disease (MCKD)?`,
    q2: ``,
    q3: [],
    option: [
      `NPH presents with polyuria and polydipsia, whereas MCKD does not. `,
      `NPH is an autosomal recessive disorder, whereas MCKD is an autosomal dominant disease. `,
      `NPH is diagnosed histologically with severe interstitial fibrosis, whereas MCKD is diagnosed by the presence of glomerulosclerosis. `,
      ` Most patients with MCKD have extrarenal manifestations of the disease, whereas patients with NPH are usually affected only in the kidneys.`,
      ` In patients with NPH, renal failure occurs in the third to fourth decade, whereas in patients with MCKD, renal failure typically occurs in adolescence.`,
    ],
    optionStyleType: `st-upper-alpha`,
    answer: [1],
    ansText: `Rationale: <b>Although either condition can occur sporadically, juvenile nephronophthisis usually is inherited as an autosomal recessive trait, whereas medullary cystic disease usually is inherited in an autosomal dominant fashion. Juvenile nephronophthisis and medullary cystic disease both cause polydipsia and polyuria in more than 80% of cases, but not to the extent observed in patients with diabetes insipidus. Pathologically, NPH and MCKD are similar.</b> Histologically, there is a characteristic triad present that includes (1) irregular thickening and disintegration of the tubular basement membrane, (2) marked tubular atrophy with cyst development, and (3) interstitial cell infiltration with fibrosis. Twenty percent of juvenile nephronophthisis families have extrarenal manifestations, whereas MCKD usually affects only the kidneys. Another important difference between the two entities is that renal failure develops in patients with NPH at a mean age of 13 years and almost always before 25 years. MCKD is a milder disease when it presents in early adulthood, but it will manifest in all patients by 50 years (Bernstein and Gardner, 1979).<sup>a</sup> End-stage renal disease (ESRD) in patients with MCKD most often develops in the third or fourth decade of life.
    
        <br /><br /><b>a</b> Sources referenced can be found in <i>Campbell-Walsh-Wein Urology, 12th Edition</i>, on the <a href="http://Expert%20Consult%20website">Expert Consult website</a>. `,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `A patient with which of the following entities has the highest likelihood of having a renal cell carcinoma develop? `,
    q2: ``,
    q3: [],
    option: [
      ` ADPKD`,
      ` Tuberous sclerosis`,
      `von Hippel-Lindau disease `,
      ` Acquired renal cystic disease`,
      `Medullary sponge kidney `,
    ],
    optionStyleType: `st-upper-alpha`,
    answer: [2],
    ansText: `Rationale: <b>Tuberous sclerosis and von Hippel-Lindau disease are associated with epithelial hyperplasia (and adenomas as well) and have an increased incidence of renal cell carcinoma (tuberous sclerosis, 2%, and von Hippel-Lindau disease, 35% to 38%).</b> `,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `Which of the following is FALSE pertaining to MCDK? `,
    q2: ``,
    q3: [],
    option: [
      ` MCDK is one of the most common causes of an abdominal mass in the newborn.`,
      ` In patients with MCDK, the contralateral renal moiety is frequently affected by urologic disease.`,
      ` MCDK is often difficult to differentiate from severe ureteropelvic junction obstruction.`,
      ` Data from large series show that MCDK is associated with an increased risk for hypertension.`,
      ` Roughly 40% of MCDKs will spontaneously involute over time.`,
    ],
    optionStyleType: `st-upper-alpha`,
    answer: [3],
    ansText: `Rationale: <b>All statements are true of MCDK, except that large series indicate MCDK is NOT associated with an increased risk of hypertension.</b> `,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: ` Which of the following would confirm the diagnosis of tuberous sclerosis?`,
    q2: ``,
    q3: [],
    option: [
      `Renal angiomyolipoma and multiple renal cysts `,
      ` Hamartomatous rectal polyps and facial adenoma sebaceum`,
      ` Renal angiomyolipoma and cardiac rhabdomyoma`,
      ` Multiple renal cysts, hepatic fibrosis, and pheochromocytoma`,
      ` Mitral valve prolapse, renal angiolipoma, and gingival fibromas`,
    ],
    optionStyleType: `st-upper-alpha`,
    answer: [2],
    ansText: `Rationale: <b>Definitive diagnosis of tuberous sclerosis (TSC) is dependent on the presence of certain major and minor clinical features.</b> The diagnosis of TSC requires two major features (renal angiomyolipoma, facial angiofibromas or forehead plaques, nontraumatic ungual or periungual fibroma, three or more hypomelanotic macules, shagreen patch, multiple retinal nodular hamartomas, cortical tuber, subependymal nodule, subependymal giant cell astrocytoma, cardiac rhabdomyoma, lymphangioleiomyomatosis) or one major plus two minor features (multiple renal cysts, nonrenal hamartoma, hamartomatous rectal polyps, retinal achromic patch, cerebral white matter radial migration tracts, bone cysts, gingival fibromas, “confetti” skin lesions, multiple enamel pits). `,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `The following are true of von Hippel-Lindau (VHL) disease EXCEPT: `,
    q2: ``,
    q3: [],
    option: [
      `VHL disease is an autosomal dominant syndrome. `,
      `VHL disease is caused by a mutation in the tumor suppressor gene, VHL, located on chromosome 3. `,
      ` epididymal cysts are not infrequent in patients with VHL disease.`,
      ` pheochromocytomas, cerebellar hemangioblastomas, and retinal angiomas are common extrarenal manifestations of VHL disease.`,
      ` renal cell carcinomas, the most common manifestation, are seen in the vast majority of patients.`,
    ],
    optionStyleType: `st-upper-alpha`,
    answer: [4],
    ansText: `Rationale: All statements are true of VHL disease except that renal cysts, NOT <b><i>renal cell carcinoma</i></b>, are the most common and often earliest manifestation as seen in 76% of patients. `,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: ` Renal sinus cysts are most likely derived from:`,
    q2: ``,
    q3: [],
    option: [
      `vascular elements. `,
      ` renal parenchyma.`,
      ` renal pelvis.`,
      ` lymphatic system.`,
      ` nephrogenic rests.`,
    ],
    optionStyleType: `st-upper-alpha`,
    answer: [3],
    ansText: `Rationale: The predominant type of renal sinus cyst appears to be one derived from the lymphatics.  `,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: ` Most simple renal cysts that are identified in utero:`,
    q2: ``,
    q3: [],
    option: [
      ` represent the first sign of a multicystic kidney.`,
      ` represent the first sign of ARPKD.`,
      ` represent the first sign of ADPKD.`,
      ` represent a calyceal diverticulum.`,
      ` resolve before birth.`,
    ],
    optionStyleType: `st-upper-alpha`,
    answer: [4],
    ansText: `Rationale: In 28 of 11,000 fetuses with renal cysts, 25 fetuses had the cysts resolve before birth. Of two cysts that remained postnatally, in one it was the first sign of a multicystic kidney. `,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `Approximately what percentage of individuals older than 60 years will have an identifiable renal cyst on computed tomography (CT)? `,
    q2: ``,
    q3: [],
    option: [`1% to 5%`, ` 10%`, ` 33%`, ` 75%`, ` 90%`],
    optionStyleType: `st-upper-alpha`,
    answer: [2],
    ansText: `Rationale: In adults, the frequency of renal cyst occurrence increases with age. Using CT, one group demonstrated a 20% incidence of cysts by 40 years and approximately 33% incidence of cysts after 60 years.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `Which of the following groups of antibiotics include the best choice for treating an infected renal cyst in a patient with ADPKD? `,
    q2: ``,
    q3: [],
    option: [
      `Trimethoprim-sulfamethoxazole, chloramphenicol, fluoroquinolones `,
      ` Cephalosporins, trimethoprim-sulfamethoxazole, doxycycline`,
      ` Gentamicin, cephalosporins, vancomycin`,
      ` Fluoroquinolones, metronidazole, vancomycin`,
      ` Doxycycline, amoxicillin, gentamicin`,
    ],
    optionStyleType: `st-upper-alpha`,
    answer: [0],
    ansText: `Rationale: <b>In the experience of one group of researchers, the only dependable antibiotics were those that were lipid soluble, namely, trimethoprim-sulfamethoxazole and chloramphenicol. Chloramphenicol produced better results. The fluoroquinolones, which are also lipid soluble, are proving useful.</b> If a patient with suspected pyelonephritis does not respond to an antibiotic, and if the antibiotic used is not lipid soluble, one must consider whether the infection may be present in a noncommunicating cyst. `,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: ` All of the following are reasonable treatment strategies for patients with ADPKD EXCEPT:`,
    q2: ``,
    q3: [],
    option: [
      `management of hypertension. `,
      ` avoidance of surgical treatment for large or multiple cysts in patients with chronic flank pain.`,
      `surgical treatment of symptomatic urinary stone disease. `,
      `use of lipophilic antibiotics for treatment of a suspected renal cyst infection`,
      ` screening with magnetic resonance imaging (MRI) or CT for berry aneurysms in patients with a family history of subarachnoid hemorrhage.`,
    ],
    optionStyleType: `st-upper-alpha`,
    answer: [1],
    ansText: `Rationale: All are reasonable treatment strategies for a patient with ADPKD, except that when conservative measures of chronic pain treatment fail, surgical management must be considered. Ultrasonography- or CT-guided cyst aspiration is a straightforward procedure and may be both diagnostic and therapeutic. Surgical unroofing of multiple or very large cysts can potentially alleviate symptoms of pain and can be performed either laparoscopically or through open flank or dorsal lumbotomy incisions. Surgical intervention appears to only improve symptomatology and does not appear to either accelerate the decline of renal function or preserve declining renal function. `,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `In neonates with a unilateral multicystic kidney, what is the incidence of contralateral vesicoureteral reflux? `,
    q2: ``,
    q3: [],
    option: [`0% to 7% `, ` 18% to 43%`, `50% to 67% `, ` 75%`, ` 7% to 15%`],
    optionStyleType: `st-upper-alpha`,
    answer: [1],
    ansText: `Rationale: Contralateral vesicoureteral reflux is seen even more often than contralateral ureteropelvic junction obstruction, being identified in 18% to 43% of infants.  `,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: ` What is the most likely cause of flank pain and hematuria in a 50-year-old patient with end-stage renal disease who has been undergoing dialysis for 5 years?`,
    q2: ``,
    q3: [],
    option: [
      ` Acute renal vein thrombosis`,
      ` Acute renal artery thrombosis`,
      ` Renal cell carcinoma`,
      `ARCD `,
      ` Uric acid stones`,
    ],
    optionStyleType: `st-upper-alpha`,
    answer: [3],
    ansText: `Rationale: The most common presentation of ARCD is loin pain, hematuria, or both. Bleeding occurs in as many as 50% of patients. `,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `Which group of three findings best describes the typical ultrasonographic image of a multicystic dysplastic kidney? `,
    q2: ``,
    q3: [],
    option: [
      `The cysts are organized around a central large cyst; there is no identifiable renal sinus; and there are communications between the cysts. `,
      ` The cysts have a haphazard distribution; there is absence of a central or medial large cyst; and there are no obvious communications between the cysts.`,
      ` The cysts have a haphazard distribution; there is no obvious renal sinus; and there is a large central cyst.`,
      ` Connections exist between the cysts; a medial cyst is present; and a renal sinus is usually present.`,
      ` The cysts are organized at the periphery; the largest is the central one; and there is an identifiable renal sinus.`,
    ],
    optionStyleType: `st-upper-alpha`,
    answer: [1],
    ansText: `Rationale: Renal masses in infants most often represent either multicystic kidney disease or hydronephrosis, and it is important to distinguish the two, especially if the surgeon wishes to remove a nonfunctioning hydronephrotic kidney or repair a ureteropelvic junction obstruction while leaving a multicystic organ in situ. In newborns, ultrasonography is generally the first study performed. <b>In a few cases, it is difficult to distinguish multicystic kidney disease from severe hydronephrosis. In general, however, the multicystic kidney has a haphazard distribution of cysts of various sizes without a larger central or medial cyst and without visible communications between the cysts.</b> Frequently, very small cysts appear in between the large cysts. <b>By comparison, in ureteropelvic junction obstruction, the cysts or calyces are organized around the periphery of the kidney, connections can usually be demonstrated between the peripheral cysts and a central or medial cyst that represents the renal pelvis, and there is an absence of small cysts between the larger cysts.</b> When there is an identifiable renal sinus, the diagnosis is more likely to be hydronephrosis than multicystic kidney.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: ` Which one of the following conditions is most representative of a neoplastic growth?`,
    q2: ``,
    q3: [],
    option: [
      `Benign multilocular cyst `,
      ` Oligomeganephronia`,
      `Multicystic dysplastic kidney `,
      ` Calyceal diverticulum`,
      ` Ask-Upmark kidney`,
    ],
    optionStyleType: `st-upper-alpha`,
    answer: [0],
    ansText: `Rationale: For the benign multilocular cystic lesion, certain authors prefer the term <b><i>cystic nephroma</i></b>, because this term implies a benign but neoplastic lesion. `,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: ` Which of the following is the best match?`,
    q2: ``,
    q3: [],
    option: [
      ` ARPKD and congenital hepatic fibrosis`,
      `Medullary sponge kidney and predominance of glomerular cysts `,
      ` Juvenile nephronophthisis and cortical cysts`,
      `Ask-Upmark kidney and hypotension `,
      ` von Hippel-Lindau disease and adenoma sebaceum`,
    ],
    optionStyleType: `st-upper-alpha`,
    answer: [0],
    ansText: `Rationale: All patients with ARPKD have varying degrees of congenital hepatic fibrosis. `,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `Which of the following is the best match? `,
    q2: ``,
    q3: [],
    option: [
      `ARPKD and congenital hepatic fibrosis `,
      ` Medullary sponge kidney and predominance of glomerular cysts`,
      ` Juvenile nephronophthisis and cortical cysts`,
      ` Ask-Upmark kidney and hypotension`,
      ` von Hippel-Lindau disease and adenoma sebaceum`,
    ],
    optionStyleType: `st-upper-alpha`,
    answer: [0],
    ansText: `Rationale: All patients with ARPKD have varying degrees of congenital hepatic fibrosis.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },

  {
    q: `A renal cyst with increased number of septa and prominent calcification in a nonenhancing cyst wall does not require exploration, but requires timely follow-up. According to the Bosniak grading system, this cyst would be categorized as: `,
    q2: ``,
    q3: [],
    option: [`I. `, `II. `, ` II F.`, ` III.`, ` IV.`],
    optionStyleType: `st-upper-alpha`,
    answer: [2],
    ansText: `Rationale: The Bosniak classification has recently been updated to include category II F. Bosniak I―simple cyst with imperceptible wall, rounded. Workup: none. Percentage malignant: ∼0%. Bosniak II―minimally complex with a few thin &lt;1 mm septa or thin calcifications (thickness not measurable); non-enhancing high-attenuation (due to proteinaceous or hemorrhagic contents) renal lesions &lt;3 cm. These lesions are generally well marginated. Workup: none. Percentage malignant: ∼0%. Bosniak IIF―minimally complex with increased number of septa, minimally thickened with nodular or thick calcifications. There may be perceived (but not measurable) enhancement of hairline-thin smooth septa, minimal thickening of the wall with perceivable enhancement, hyperdense cyst &gt;3 cm diameter, mostly intrarenal (less than 25% of wall visible); no enhancement. Requires follow-up (the “F” in 2F is for “follow”): needs ultrasound/CT/MRI follow-up—no strict rules on the time frame but reasonable at 6 months. Percentage malignant: ∼5%. Bosniak III―indeterminate with thick, nodular multiple septa or wall with measurable enhancement. Treatment/workup: partial nephrectomy. Percentage malignant: ∼55%. Bosniak IV―clearly malignant with solid mass with a large cystic or a necrotic component. Treatment: partial or total nephrectomy. Percentage malignant: ∼100%`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `Ultrasonography in neonates with ARPKD reveals kidneys that are hyperechogenic or “bright” in appearance. This finding is due to: `,
    q2: ``,
    q3: [],
    option: [
      `the presence of many small punctate calcifications within the renal papillae. `,
      `dysplastic, diseased renal parenchyma. `,
      ` a vast increase in small fat deposits within the renal sinuses.`,
      ` the presence of numerous microcysts created by tightly compacted, dilated collecting ducts that result in innumerable ultrasonographic interfaces.`,
      ` the presence of renal hamartomas with increased cortical vascularity.`,
    ],
    optionStyleType: `st-upper-alpha`,
    answer: [3],
    ansText: `Rationale: In both fetuses and newborns with ARPKD, ultrasonography identifies bilateral, very enlarged, diffusely echogenic kidneys, especially when compared with the echogenicity of the liver. The increased echogenicity is due to the presence of numerous microcysts (created by tightly compacted, dilated collecting ducts) that result in innumerable interfaces. Compared with normal newborn kidneys, in ARPKD the pyramids are hyperechogenic because they blend in with the rest of the kidney, and the kidneys typically have a homogeneous appearance. `,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: ` Ultrasound and/or CT criteria for the diagnosis of a simple renal cyst include all the following EXCEPT:`,
    q2: ``,
    q3: [],
    option: [
      `sharp, thin, distinct smooth walls and margins. `,
      ` thickness of cyst wall less than or equal to 3 mm.`,
      ` acoustic enhancement behind cyst (ultrasound).`,
      ` spherical or ovoid shape.`,
      ` homogeneous with absence of internal echoes.`,
    ],
    optionStyleType: `st-upper-alpha`,
    answer: [1],
    ansText: `Rationale: One can safely make the diagnosis of a classic benign simple cyst by ultrasonography when the following criteria are met: (1) absence of internal echoes; (2) sharply defined, thin, distinct wall with a smooth and distinct margin; (3) good transmission of sound waves through the cyst with consequent acoustic enhancement behind the cyst; and (4) spherical or slightly ovoid shape. The CT criteria for a simple cyst are similar to those used in ultrasonography: (1) sharp, thin, distinct, smooth walls and margins; (2) spherical or ovoid shape; and (3) homogeneous content.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `A 50-year-old man with known von Hippel-Lindau disease presents with a single episode of gross hematuria. CT scan reveals a 3-cm enhancing mass in the upper pole of each kidney. Metastatic evaluation is negative. He is otherwise healthy. Appropriate treatment at this point would be: `,
    q2: ``,
    q3: [],
    option: [
      `bilateral radical nephrectomy with the placement of a peritoneal dialysis catheter. `,
      ` bilateral upper pole partial nephrectomy.`,
      ` right radical nephrectomy with left upper pole partial nephrectomy.`,
      `observation with serial CT every 4 months. `,
      `CT-guided needle biopsy of each lesion with surgical removal if diagnosis confirms renal cell carcinoma. `,
    ],
    optionStyleType: `st-upper-alpha`,
    answer: [1],
    ansText: `Rationale: Because the tumors that characterize VHL disease are frequently multiple, bilateral, and recurrent, close surveillance and minimization of surgical procedures constitute the mainstay of treatment. For patients who have VHL disease and all patients who have hereditary cancer syndromes, the goal of treatment is cancer control, not cancer cure, and preservation of functional parenchyma to avoid the morbidity associated with renal loss. In patients who have VHL disease, surgical resection is performed with the understanding that microscopic disease probably is left behind. Currently, nephron-sparing surgery should be considered the standard of care for treating low-grade renal cell carcinoma in the setting of VHL disease. Patients with high-grade disease are still probably best served with bilateral nephrectomy. Despite having the objective of sparing as much renal parenchyma as possible and preventing metastasis of the lesions already present, it is not curative surgery (Reed, 2009). Although this approach does not reduce the risk of recurrence, reported to be 75% to 85%, the 10-year disease-specific survival rates are quite high (81% to 94%) (Malek, 1987; Steinbach, 1995; Roupret, 2003; Ploussard, 2007). Classically, the survival rate after nephrectomy has been only 50%. Because most of these tumors are low grade, a nephron-sparing approach provides very good survival rates while avoiding the diminished quality of life that comes with bilateral nephrectomy and subsequent dialysis/transplantation. Laparoscopic and percutaneous image-guided ablative techniques, such as radiofrequency ablation and cryoablation, have also been used and are currently under investigation. `,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: ` <b>Pathology</b><br/><br/>A 2-year-old boy has a right nephrectomy following an automobile accident for a shattered kidney with uncontrollable bleeding. The histology depicted in <a class="lightboxcallout" img-ref="image_fig_39_1" href="6fae7b08543f4597b21eb50bda0c903b">Fig. 39.1</a> is reported as showing interstitial nephritis with cysts consistent with juvenile nephronophthisis. The next step in management is to:`,
    q2: ``,
    q3: [],
    option: [
      `have the pathologist reexamine the specimen for evidence of nephrogenic rests. `,
      `have the pathologist reexamine the specimen for an associated teratoma. `,
      ` image the contralateral kidney for a renal mass.`,
      ` image the liver for evidence of hepatic fibrosis.`,
      `inform the family that the child must be followed carefully for hypertension and decreased renal function. `,
    ],
    optionStyleType: `st-upper-alpha`,
    answer: [4],
    ansText: `Rationale: The histology is classic for juvenile nephronophthisis showing chronic interstitial nephritis-fibrosis, atrophic tubules, and glomerular microcysts. It is usually inherited as an autosomal recessive. These patients have a high likelihood of developing hypertension and eventually chronic renal failure. They may also develop retinitis pigmentosa. `,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
];
