var quiz = [
    {
        q: ` A 9-year-old girl presents to the office with a chief complaint of daytime urinary incontinence. She denies dysuria, hematuria, or enuresis. She has never had a urinary tract infection (UTI) and there is no history of hydronephrosis. Her mother states that toilet training occurred at 2 years of age and was “easy.” A clean-catch urinalysis has been obtained by her pediatrician and is completely normal. When characterizing the incontinence, she states that she completely soaks her clothes, necessitating a change in wardrobe. She denies urgency or frequency and otherwise voids every 2 to 3 hours during the day. She states that the episodes are often associated with laughing at a funny joke or movie. She denies any issues with constipation. Assuming physical examination and voiding diary are normal, which of the following would be a reasonable first-line treatment strategy?`,
        q2: ``,
        q3: [],
        option: [`Acupuncture `, 
        ` Biofeedback`, 
        ` Hypnosis`, 
        ` Imipramine`, 
        ` Oxybutynin`],
        optionStyleType: `st-lower-alpha`,
        answer: [1],
        ansText: `Rationale: <b>Giggle incontinence (enuresis risoria) is an uncommon form of daytime incontinence and is classically seen in school-aged females. Typically, there is moderate to large amounts of urinary leakage triggered by laughing alone.</b> The incontinence episodes are invariably significant, and often the entire bladder volume is drained. Daytime urinary incontinence in conjunction with laughter is also seen in children with OAB and is more common than true giggle incontinence. It is a diagnosis of exclusion and is usually established on history and is supplemented by the absence of other voiding symptoms and normal investigations. Currently, available treatment strategies include biofeedback or methylphenidate.`,
        state: `notAnswered`,
        userAnswered: []
    ,
	type: `MCSS`        ,
        type: `MCSS`},
    {
        q: `A 4-year-old girl presents to the office with a chief complaint of labial adhesions, dysuria, daytime urinary incontinence, and recurrent UTIs. Her mother states that toilet training was completed at 20 months and that there were no issues with this. Based on history and completed voiding diary, her elimination pattern is normal. Her mother states that during the past 3 months, however, she has noted that her underpants are damp and that this is often noted within a few minutes of the child having voided. They deny any urgency or frequency. She recently has been complaining of severe dysuria with two urinalyses (UAs) in the past 4 weeks demonstrating 5 to 10 white blood cells per high-power field (WBCs/hpf). Urine cultures have all been negative, and antibiotics have not helped with symptomatology. Physical examination reveals superficial labial adhesions with moderately erythematous external genitalia. Noninvasive urodynamics with pelvic ultrasound and uroflowmetry reveal a bell-shaped curve and an empty bladder with normal wall thickness. There is a small amount of fluid noted in the vagina. While the child climbs down off of the examining room table, there is involuntary leakage of urine. Repeat pelvic ultrasound reveals that the vaginal vault is empty. What is the most likely diagnosis? `,
        q2: ``,
        q3: [],
        option: [` Bladder-bowel dysfunction`, 
        ` Dysfunctional voiding`, 
        ` Urge urinary incontinence`, 
        ` Vaginal reflux`, 
        `Vesicoureteral reflux (VUR) `],
        optionStyleType: `st-lower-alpha`,
        answer: [3],
        ansText: `Rationale: <b>Vaginal reflux (vaginal entrapment, vaginal voiding) is characterized by incontinence following normal voiding in the absence of other LUT symptoms. It is commonly seen in prepubertal girls, and the typical history is that of wetting of undergarments approximately 10 to 15 minutes following a normal void. It can often be associated with labial adhesions because of chronic irritation and inflammation from skin exposure to relatively caustic urine.</b> Reassurance and postural modification to ensure complete vaginal emptying is the only treatment that is required. `,
        state: `notAnswered`,
        userAnswered: []
    ,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`        ,
        type: `MCSS`},
    {
        q: ` An 8-year-old boy is brought in by his grandmother, who recently obtained guardianship due to parental divorce and the biological mother’s recent untimely death. She states that his teachers have been complaining that for the last 4 months he spends most of his time in the restroom, asking to use the bathroom approximately every 15 minutes. He has had some occasional dysuria, but no hematuria or fevers. They deny any UTIs or daytime urinary incontinence. He has occasional constipation, but this is readily corrected with fruit juice and he generally has one soft, smooth bowel movement daily. He is generally able to sleep through the night without having to wake to void, and they deny enuresis. The element in the history that will most often be able to distinguish pollakiuria from overactive bladder (OAB) is:`,
        q2: ``,
        q3: [],
        option: [`a recent life event. `, 
        `male versus female gender. `, 
        ` no history of UTIs.`, 
        `no urinary incontinence. `, 
        `the child does not wake to void. `],
        optionStyleType: `st-lower-alpha`,
        answer: [4],
        ansText: `Rationale: <b>Pollakiuria is a disorder characterized by a very high daytime frequency of micturition (sometimes as high as 50 times per day). A key aspect of this syndrome, which differentiates it from OAB and can often clinch the diagnosis, is that the symptoms are limited to the daytime.</b> It is seen in early childhood (4 to 6 years of age) in both genders and associated with a history of recent death or life-threatening event in the family. <b>Usually, it runs a benign, self-limited course during a period of approximately 6 months.</b> `,
        state: `notAnswered`,
        userAnswered: []
    ,
	type: `MCSS`,
	type: `MCSS`        ,
        type: `MCSS`},
    {
        q: ` Lower urinary tract (LUT) dysfunction is associated with which of the following?`,
        q2: ``,
        q3: [],
        option: [`Constipation `, 
        ` Neuropsychiatric issues`, 
        `UTIs `, 
        ` VUR`, 
        `All of the above `],
        optionStyleType: `st-lower-alpha`,
        answer: [4],
        ansText: `Rationale: <b>There are long-standing, clear associations between LUT dysfunction and bowel dysfunction, UTIs, VUR, and various psychiatric diagnoses.</b> The incomplete bladder emptying that occurs in children with LUT dysfunction can lead to urinary stasis, with subsequent UTIs causing inflammatory changes in the bladder wall that stimulate hypertrophy and overactivity. It has been theorized that detrusor hypertrophy can alter the closure mechanism at the ureterovesical junction (UVJ), leading to reflux. It has also been shown that ongoing issues with bowel-bladder dysfunction can have a negative effect on VUR resolution rates, and that addressing bowel dysfunction alone can positively influence LUT function. Finally, clinicians should be cognizant of the association between neuropsychiatric diagnoses and daytime wetting, as the former is likely to interfere with treatment success of the latter.`,
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `The purported mechanism of action for botulinum toxin in the treatment of children and adolescents with dysfunctional voiding is: `,
        q2: ``,
        q3: [],
        option: [` reducing the frequency and intensity of uninhibited detrusor contractions during the filling phase of the bladder.`, 
        ` smooth muscle relaxation at the bladder neck.`, 
        `paralysis of striated muscle of the external sphincter. `, 
        `stabilization of the motor end plate, inhibiting spinal cord feedback loops. `, 
        ` none of the above.`],
        optionStyleType: `st-lower-alpha`,
        answer: [2],
        ansText: `Rationale: Botulinum-A toxin acts by inhibiting acetylcholine (ACh) release at the presynaptic neuromuscular junction. Inhibited ACh release results in regionally decreased muscle contractility and atrophy at the injection site, which in the case of dysfunctional voiding would be the striated muscle of the external urinary sphincter. The chemical denervation that ensues is a reversible process, and eventually the toxin is inactivated and removed. Clinical effects begin within 5 to 7 days of injection, with maximal effects reached within 4 to 6 weeks. The duration of induced paralysis varies depending on the type of muscle treated, with duration of treatment effect lasting between 3 and 12 months. `,
        state: `notAnswered`,
        userAnswered: []
    ,
	type: `MCSS`        ,
        type: `MCSS`},
    {
        q: `A 7-year-old girl presents to your office with a 6-month history of recurrent UTIs, daytime urinary incontinence, urgency, dysuria, and enuresis. Mother states that her daughter will have wet underwear and clothes 3 to 4 times per week. She is also wet 5 out of 7 nights per week. Mother states that she will often “wait until the last minute” to void. There are no febrile UTIs, and urine cultures from her pediatrician’s office reveal multiple organisms on 2 separate occasions in the last 3 months. A renal/bladder ultrasound demonstrates normal upper urinary tracts. Urinalysis in the office is negative and uroflow shows staccato waveform. You initiate behavioral modification and she returns 6 weeks later with improvement but remains wet during the day 1 time per week with urinary urgency and wets the bed 2 nights per week. The best next step is: `,
        q2: ``,
        q3: [],
        option: [` anticholinergics.`, 
        `moisture alarm. `, 
        `alpha blockers. `, 
        ` biofeedback.`, 
        ` botulinum toxin.`],
        optionStyleType: `st-lower-alpha`,
        answer: [3],
        ansText: `Rationale: All patients with lower urinary tract dysfunction (LUTD) should receive behavioral modification as treatment. A uroflow showing a staccato waveform along with incomplete emptying is consistent with dysfunctional voiding. Biofeedback is particularly valuable in the treatment of dysfunctional voiding and improves LUTD by coordinating the pelvic floor muscle activity and abdominal muscle activity to promote efficient bladder emptying. `,
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: ` Which of the following organ systems is implicated in the pathogenesis of enuresis?`,
        q2: ``,
        q3: [],
        option: [`Bladder `, 
        ` Brain`, 
        ` Kidney`, 
        ` All of the above`, 
        ` None of the above`],
        optionStyleType: `st-lower-alpha`,
        answer: [3],
        ansText: `Rationale: The three organ systems implicated in the pathogenesis of enuresis include the bladder (reduced nocturnal bladder capacity), the kidney (nocturnal polyuria), and the brain (e.g., a disorder affecting arousal from sleep). <b>Enuresis is logically thought to result from a disruption or maturational lag in one or more of these critical domains.</b> `,
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: ` An 8-year-old boy presents to your office with his parents for consultation regarding treatment for primary nocturnal enuresis. Behavioral modification, desmopressin, and the enuresis alarm have failed. Which of the following parameters is the best predictor of response to treatment with desmopressin?`,
        q2: ``,
        q3: [],
        option: [`Age of child `, 
        ` Bladder capacity`, 
        `Motivation of family `, 
        `Nocturnal polyuria `, 
        ` Poor arousal`],
        optionStyleType: `st-lower-alpha`,
        answer: [3],
        ansText: `Rationale: The nocturnal enuresis alarm and desmopressin are both valid treatment options. There exist patient, caregiver, and disease-related parameters that may aid in offering prognostic information in terms of which therapeutic modality should be first entertained. The enuresis alarm seems best fit for motivated patients and families and for children without polyuria but with low voided volume. Desmopressin seems best suited for children with nocturnal polyuria and normal bladder reservoir function, for those with infrequent wet episodes, and for families in whom alarm treatment has failed or who have refused alarm treatment. `,
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    

];
