var quiz = [
  {
    q: ` Which of the following is an acquired form of neuromuscular dysfunction of the lower urinary tract?`,
    q2: ``,
    q3: [],
    option: [
      `Myelomeningocele `,
      ` Cerebral palsy`,
      ` Lipomeningocele`,
      ` Sacral agenesis`,
      ` Anorectal malformation`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [1],
    ansText: `Rationale: Cerebral palsy is the only acquired disease process on the list. The remainder are congenital. `,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: ` What is the primary goal in management of neuromuscular dysfunction of the lower urinary tract?`,
    q2: ``,
    q3: [],
    option: [
      ` Achievement of urinary continence`,
      ` Achievement of fecal continence`,
      `Preservation of renal function `,
      `Facilitation of sexual function `,
      ` Avoidance of urinary tract infection`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [2],
    ansText: `Rationale: Although the other listed goals have important clinical and social implications, preservation of renal function is the primary goal of treatment. Achievement of urinary/fecal continence, sexual function, and avoidance of urinary tract infection are secondary goals of treatment. `,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },

  {
    q: `The International Children’s Continence Society (ICCS) recommends more frequent evaluation of children during periods of high rates of somatic growth when spinal cord tethering is more likely. These two development periods are: `,
    q2: ``,
    q3: [],
    option: [
      `newborn to toddler AND toddler to adolescent. `,
      ` newborn to toddler AND adolescent to adult.`,
      ` newborn to toddler AND adulthood.`,
      ` toddler to adolescent AND adolescent to adult.`,
      ` toddler to adolescent AND adulthood.`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [1],
    ansText: `Rationale: The correct combination of growth periods in which the rate of somatic growth is highest is in the newborn to toddler and adolescent to adult age group. This recommendation is due to the fact that the highest rate of spinal cord tethering, and thus a change in bladder/bowel function, is during periods of highest somatic growth.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },

  {
    q: `The ICCS’s indications for repeat investigations prior the routinely scheduled follow-up for neuromuscular dysfunction of the lower urinary tract do NOT include: `,
    q2: ``,
    q3: [],
    option: [
      `urinary tract infections. `,
      ` development or worsening of hydronephrosis.`,
      ` worsening continence.`,
      ` change in lower extremity function.`,
      ` improved continence.`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [4],
    ansText: `Rationale: Urinary tract infections, hydronephrosis, worsening continence, and a change in lower extremity function are more likely to indicate a significant change in bladder function than improved continence.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },

  {
    q: `Which of the following may compromise bladder emptying in neuromuscular dysfunction of the lower urinary tract? `,
    q2: ``,
    q3: [],
    option: [
      `Low capacity `,
      ` Low compliance`,
      ` Detrusor overactivity`,
      ` Detrusor sphincter dyssynergia`,
      ` Low outlet resistance`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [3],
    ansText: `Rationale: Detrusor sphincter dyssynergia is the only entity listed that may compromise bladder emptying. All other listed options would facilitate or encourage early bladder emptying. `,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },

  {
    q: `Initial minimally invasive treatment options to address inadequate bladder storage in neuromuscular dysfunction in children usually involves: `,
    q2: ``,
    q3: [],
    option: [
      `overnight indwelling catheter drainage. `,
      `antimuscarinics and clean intermittent catheterization (CIC). `,
      ` percutaneous cystostomy tube.`,
      ` endoscopic injection of botulinum toxin.`,
      ` robotic-assisted augmentation cystoplasty.`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [1],
    ansText: `Rationale: The beneficial effects of early initiation of antimuscarinics and CIC are well established. The other listed options would be considered to be more invasive or less established methods of intervention. `,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: ` The use of antimuscarinics for the treatment of detrusor overactivity in children does NOT result in the following:`,
    q2: ``,
    q3: [],
    option: [
      `Increased bladder capacity `,
      ` Decreased number of bladder contractions`,
      `Decreased number of incontinence episodes `,
      ` Decreased number of catheterizations`,
      `Decreased volume to first bladder contraction `,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [4],
    ansText: `Rationale: Antimuscarinics in children result in increased bladder capacity, fewer bladder contractions, less incontinence, and catheterizations. The question is worded negatively; (e) is correct as antimuscarinics would be expected to increase the volume to first bladder contraction, rather than to decrease it. `,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `A possible predictor of poor clinical response to intravesical injection of botulinum toxin injection is preexisting: `,
    q2: ``,
    q3: [],
    option: [
      `low maximum cystometric capacity. `,
      ` detrusor overactivity.`,
      ` more than five episodes of incontinence per day.`,
      ` poor detrusor compliance.`,
      ` previous botulinum toxin injections.`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [3],
    ansText: `Rationale: Kask et al. (2013) demonstrated that preexisting poor detrusor compliance predicts a poor clinical response to intravesical injection of botulinum toxin. One could postulate that the histologic changes that are present after the development of poor detrusor compliance are not amenable to the effects of botulinum toxin.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: ` Which of the following increases the risk of developing lower urinary tract stones in children with bladder augmentation?`,
    q2: ``,
    q3: [],
    option: [
      `Use of the ileal segment `,
      ` Routine bladder irrigation with water or saline`,
      ` Use of an antimuscarinic`,
      ` Catheterization of the urethra, rather than an abdominal stoma`,
      `A mobile patient `,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [0],
    ansText: `Rationale: The use of an ileal segment has been shown to increase the risk of lower urinary tract stones. Catheterization through the urethra, rather than via an abdominal stoma, is associated with fewer lower urinary tract stones, presumably because of better drainage. A mobile patient and routine bladder irrigation decrease the risk of stones. The use of an antimuscarinic should not affect stone formation.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: ` The presentation of bladder malignancy in those with a history of bladder augmentation does NOT include:`,
    q2: ``,
    q3: [],
    option: [
      `presenting with advanced disease. `,
      ` presenting at an older age than is typical for bladder malignancies.`,
      ` presenting with atypical symptoms such as vague abdominal pain, urosepsis or increased frequency of urinary tract infection (UTI), difficult catheterization, and renal failure.`,
      ` presenting with a time lag of a minimum of 10 years after a bladder augmentation.`,
      ` presenting with atypical signs such as new hydronephrosis and bladder wall thickening.`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [1],
    ansText: `Rationale: Those with bladder augmentation present at a younger age, with atypical symptoms and advanced disease, usually with a minimum 10-year lag time between augmentation and presentation of bladder malignancy.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `Which of the following is the preferred approach to increase bladder capacity in children with neuromuscular dysfunction of the lower urinary tract? `,
    q2: ``,
    q3: [],
    option: [
      `Autoaugmentation `,
      `Enteric augmentation with a gastric segment `,
      ` Tissue engineered bladder substitute`,
      ` Enteric augmentation with an ileal segment`,
      ` Enteric augmentation with an ileal-cecal segment`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [3],
    ansText: `Rationale: Lack of improvement in urodynamic and clinical symptoms, along with a high failure rate, makes autoaugmentation an undesirable option. Gastric segments are associated with more symptomatic side effects (such as hematuria dysuria syndrome) and metabolic complications than ileal segments. It is recommended to avoid the ileal-cecal segment in children with neural tube defects because it may aggravate bowel dysfunction. Phase II studies of tissue-engineered bladder revealed no improvement in urodynamic parameters and serious adverse events. Thus, the ileal segment is the most desirable for enteric augmentation. `,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: ` Worsening of bladder function after isolated bladder neck procedures including implantation of an artificial urinary sphincter or bladder neck fascial sling is more common in those with:`,
    q2: ``,
    q3: [],
    option: [
      `preexisting detrusor overactivity and poor compliance. `,
      ` preexisting low maximum cystometric capacity.`,
      ` surgery in the post-pubertal period.`,
      `detrusor sphincter dyssynergia. `,
      ` history of prior bladder neck outlet procedures.`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [0],
    ansText: `Rationale: Isolated bladder neck procedures such as artificial urinary sphincter and bladder neck repairs have been noted to lead to worsening of bladder function in up to 30% of patients, especially those with preexisting detrusor overactivity and poor compliance. The remaining answers have not been associated with worsening of bladder function after isolated bladder neck procedures.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `Which of the following is NOT an acceptable method of managing high-grade vesicoureteral reflux in children with neuromuscular dysfunction of the lower urinary tract? `,
    q2: ``,
    q3: [],
    option: [
      ` CIC`,
      `Antimuscarinics `,
      ` Antibiotic prophylaxis`,
      ` Ureteral re-implantation`,
      ` Bladder emptying by the Credé maneuver`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [4],
    ansText: `Rationale: Children with a reactive external urinary sphincter will have a reflex response of increased external urethral tone in response to the Credé maneuver that can aggravate reflux and thus is contraindicated in this group. The other listed options are all reasonable methods of managing vesicoureteral reflux in those with neuromuscular dysfunction of the lower urinary tract. `,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: ` Prenatal surgery for children with myelomeningocele compared to standard post-natal closure has been noted to result in:`,
    q2: ``,
    q3: [],
    option: [
      ` an increased risk of fetal death and need for cerebrospinal fluid shunting.`,
      ` worsening of mental development and motor function at 30 months.`,
      ` fewer pregnancy complications.`,
      `a lower risk of preterm labor. `,
      ` no improvement in bladder function.`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [4],
    ansText: `Rationale: Prenatal surgery for children with myelomeningocele compared to standard post-natal closure has been noted to decrease the need for cerebrospinal fluid shunting, improve neuromotor function, and increase pregnancy complications and the risk for preterm labor. The correct answer is there is no improvement in lower urinary tract function with prenatal versus postnatal closure. `,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: ` Indications for the initiation of CIC in the newborn with myelomeningocele do NOT include:`,
    q2: ``,
    q3: [],
    option: [
      `post-void residual urine measurement of 3 mL after the Credé maneuver. `,
      `post-void residual urine measurement of 10 mL after spontaneous voiding. `,
      `the presence of detrusor sphincter dyssynergia on urodynamic studies. `,
      ` the presence of hydronephrosis and high-grade vesicoureteral reflux with poor bladder emptying.`,
      `poor bladder compliance with bladder filling pressures greater than 40 cm of water. `,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [0],
    ansText: `Rationale: A post-void residual urine measurement on 3 mL after the Credé maneuver is within normal limits and does not require the initiation of CIC. All other possible answers are indications for the initiation of CIC. `,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `The highest risk for the development of urinary tract deterioration in children with myelodysplasia is in those with initial urodynamic findings of: `,
    q2: ``,
    q3: [],
    option: [
      ` detrusor sphincter synergy.`,
      ` detrusor sphincter dyssynergy.`,
      `complete denervation. `,
      `low maximum cystometric capacity. `,
      `detrusor overactivity. `,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [1],
    ansText: `Rationale: Within the first 3 years of life, over 70% of children with detrusor sphincter dyssynergy will have urinary tract deterioration, whereas less than one-quarter of those with synergy or complete denervation will have deterioration. Low maximum cystometric capacity and detrusor overactivity have not been associated with upper tract deterioration. `,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: ` The gold standard for measuring renal function in children with spina bifida is:`,
    q2: ``,
    q3: [],
    option: [
      `serum creatinine. `,
      `glomerular filtration rate as estimated by the Schwarz formula. `,
      `glomerular filtration rate as estimated by the Schwartz formula. `,
      ` serum cystatin C.`,
      `nuclear renography. `,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [4],
    ansText: `Rationale: Although all possible answers are means of measuring renal function in children with myelodysplasia, nuclear renography is considered to be the gold standard.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: ` Sexual function and satisfaction in men with myelomeningocele is better with the following condition:`,
    q2: ``,
    q3: [],
    option: [
      `Living with their parents `,
      ` Severe incontinence`,
      ` A sacral level lesion of the neural tube defect`,
      ` A thoracic level lesion of the neural tube defect`,
      ` The presence of hydrocephalus`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [2],
    ansText: `Rationale: Lesions above the sacral spinal cord, hydrocephalus, incontinence, and living with your parents are associated with less sexual function and satisfaction compared to men with a sacral level lesion.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `The most common finding associated with an occult neural tube defect is: `,
    q2: ``,
    q3: [],
    option: [
      `a cutaneous abnormality overlying the lower spine. `,
      ` high-arched feet.`,
      ` claw or hammer toes.`,
      ` abnormal gait.`,
      `absent perineal sensation. `,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [1],
    ansText: `Rationale: A cutaneous abnormality overlying the spine such as a skin dimple, tuft of hair, skin tag, lipoma, vascular malformation, or asymmetric gluteal cleft is noted in 90% of those with occult neural tube defect. The other listed answers are also noted as part of this entity but their occurrence is much less frequent. `,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `In a 1-year-old child, definitive diagnosis of an occult neural tube defect can be made by: `,
    q2: ``,
    q3: [],
    option: [
      `spinal ultrasound. `,
      ` urodynamic studies demonstrating findings consistent with neurogenic bladder dysfunction.`,
      ` magnetic resonance imaging of the spine.`,
      ` documentation of resolution of abnormal urodynamic findings after a detethering procedure.`,
      ` abnormal electromyography of the external urinary sphincter.`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [2],
    ansText: `Rationale: Spinal ultrasound may be utilized prior to ossification of vertebral bones (3 months of age). After this time point, magnetic resonance imaging of the spine is required for definitive diagnosis of an occult neural tube defect.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: ` Which of the following is UNLIKELY to be noted in a child with neuromuscular dysfunction of the lower urinary tract secondary to sacral agenesis?`,
    q2: ``,
    q3: [],
    option: [
      ` Urinary incontinence`,
      ` A maternal history of diabetes mellitus or gestational diabetes`,
      `Flattened buttocks and a short, low gluteal cleft `,
      `Absent perineal sensation `,
      ` Vesicoureteral reflux and recurrent urinary tract infections`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [3],
    ansText: `Rationale: Most children with sacral agenesis have preserved perineal sensation, thus they are UNLIKELY to have absent perineal sensation. The other listed answers are all potential presenting features of a child with sacral agenesis. `,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: ` Urodynamic studies of children with an anorectal malformation should be performed in all of the following circumstances EXCEPT:`,
    q2: ``,
    q3: [],
    option: [
      `a bony malformation of the spine or a spinal cord defect. `,
      `hydronephrosis. `,
      ` vesicoureteral reflux.`,
      ` urinary or fecal incontinence.`,
      `a low insertion of the fistulous site. `,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [4],
    ansText: `Rationale: Urodynamic evaluation in those with anorectal malformation is indicated if there is suggestion of possible spinal cord tethering (bony malformation of the spine or spinal cord defect) or signs and/or symptoms that might indicate a neurogenic defect such as hydronephrosis, vesicoureteral reflux, or urinary/fecal incontinence. Although spinal cord defects may be present in up to a third of those with a low insertion of the fistula site, a low insertion site itself is not an indication for urodynamic study. `,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `The following statement concerning bladder function in children with cerebral palsy is TRUE: `,
    q2: ``,
    q3: [],
    option: [
      `They achieve nighttime urinary continence first. `,
      `They achieve urinary continence at the same age as their age-adjusted peers. `,
      `Lower urinary tract symptoms are more common in younger children. `,
      ` The most common urinary tract symptom is monosymptomatic nocturnal enuresis.`,
      ` Clinical symptoms of recurrent UTI and detrusor sphincter dyssynergia (retention, interrupted stream, and hesitancy) are associated with upper urinary tract deterioration.`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [4],
    ansText: `Rationale: Children with cerebral palsy usually achieve daytime dryness first, at an age later than their age-adjusted peers. Lower urinary tract symptoms become more prevalent in children with cerebral palsy as they age. The most common symptom in these children is incontinence. Clinical symptoms of recurrent UTI and detrusor sphincter dyssynergia are associated with upper urinary tract deterioration and may warrant investigation with renal/bladder ultrasound and urodynamic studies. `,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `The most common presenting urinary symptom in children with transverse myelitis is: `,
    q2: ``,
    q3: [],
    option: [
      ` urinary incontinence.`,
      `urinary tract infection. `,
      `urinary retention. `,
      ` urinary frequency.`,
      ` urinary urgency.`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [2],
    ansText: `Rationale: The most common presenting urinary symptom of transverse myelitis is urinary retention. Ninety-five percent of children in the acute phase of the disease will have urinary retention. `,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
];
