var quiz = [
    {
        q: ` What is the live birth incidence of classic bladder exstrophy?`,
        q2: ``,
        q3: [],
        option: [`1 in 1000 `, 
        `1 in 10,000 `, 
        ` 1 in 50,000`, 
        `1 in 70,000 `, 
        ` 1 in 100,000`],
        optionStyleType: `st-lower-alpha`,
        answer: [2],
        ansText: `Rationale: The incidence of bladder exstrophy has been estimated as between 1 in 10,000 and 1 in 50,000 live births. `,
        state: `notAnswered`,
        userAnswered: []
    ,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`        ,
        type: `MCSS`},
    {
        q: `What is the live birth risk of bladder exstrophy in the offspring of individuals with bladder exstrophy and epispadias? `,
        q2: ``,
        q3: [],
        option: [`1 in 70 `, 
        ` 1 in 300`, 
        ` 1 in 500`, 
        ` 1 in 700`, 
        ` 1 in 1000`],
        optionStyleType: `st-lower-alpha`,
        answer: [0],
        ansText: `Rationale: Shapiro determined that the risk of bladder exstrophy in the offspring of individuals with bladder exstrophy and epispadias is 1 in 70 live births, a 500-fold greater incidence than in the general population. `,
        state: `notAnswered`,
        userAnswered: []
    ,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`        ,
        type: `MCSS`},
    {
        q: `The main theory of embryologic maldevelopment in exstrophy is that of: `,
        q2: ``,
        q3: [],
        option: [`underdevelopment of the cloacal membrane, preventing medial migration of the mesoderm tissue and proper lower abdominal wall development.`, 
        ` overdevelopment of the cloacal membrane, preventing medial migration of the mesodermal tissue and proper lower abdominal wall development.`, 
        `infiltration of ectoderm into the cloacal membrane. `, 
        `infiltration of mesoderm into the cloacal membrane. `, 
        ` invasion of endoderm into the cloacal membrane.`],
        optionStyleType: `st-lower-alpha`,
        answer: [1],
        ansText: `Rationale: The theory of embryonic maldevelopment in exstrophy held by Marshall and Muecke is that the basic defect is an abnormal overdevelopment of the cloacal membrane. This theory of embryonic maldevelopment was held by Marshall and Muecke to explain the basic defect in exstrophy patients.`,
        state: `notAnswered`,
        userAnswered: []
    ,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`        ,
        type: `MCSS`},
    {
        q: ` In evaluating the skeletal defects of bladder exstrophy, Sponseller and colleagues (1995)<sup>a</sup> found that with classic bladder exstrophy, there are changes in the orientation of the pelvic bones. These include:`,
        q2: ``,
        q3: [],
        option: [`external rotation of the posterior aspect of the pelvis of 12 degrees on each side. `, 
        ` retroversion of the acetabulum.`, 
        `an 18-degree rotation of the anterior pelvis. `, 
        ` a 30% shortening of the pubic rami in addition to a significant pubic symphyseal diastasis.`, 
        ` all of the above.`],
        optionStyleType: `st-lower-alpha`,
        answer: [4],
        ansText: `Rationale: Sponseller and colleagues found that patients with classic bladder exstrophy have a mean external rotation of the posterior aspect of the pelvis of 12 degrees on each side, retroversion of the acetabulum, and a mean 18-degree external rotation of the anterior pelvis along with 30% shortening of the pubic rami. `,
        state: `notAnswered`,
        userAnswered: []
    ,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`        ,
        type: `MCSS`},
    {
        q: ` Which of the following statements is TRUE regarding hernias in children with exstrophy?`,
        q2: ``,
        q3: [],
        option: [`Identification at the time of initial closure is not possible. `, 
        `They are usually unilateral. `, 
        ` They are noted in 80% of boys and 10% of girls.`, 
        ` The orientation of the pelvic bones makes them infrequent.`, 
        `A patent processus vaginalis is rarely noted. `],
        optionStyleType: `st-lower-alpha`,
        answer: [2],
        ansText: `Rationale: Connelly and colleagues, in a review of 181 children with bladder exstrophy, reported inguinal hernias in 81.8% of boys and 10.5% of girls. `,
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: ` Which of the following statements is TRUE regarding the male genital defect in exstrophy?`,
        q2: ``,
        q3: [],
        option: [`The posterior length of the corporeal bodies was 30% shorter than that in healthy controls. `, 
        ` The diameter of the posterior corporeal segments was less than that in healthy controls.`, 
        ` The shortening of the penis was due entirely to the pubic diastasis.`, 
        `The anterior corporeal segments are 50% shorter than those of healthy control participants. `, 
        ` The angle between the corpora cavernosa is markedly reduced in boys with exstrophy.`],
        optionStyleType: `st-lower-alpha`,
        answer: [3],
        ansText: `Rationale: <b>With the use of magnetic resonance imaging (MRI) to examine adult men with bladder exstrophy and comparison of these results with those from age- and race-matched control participants, it was found that the anterior corporeal length in male patients with bladder exstrophy is almost 50% shorter than that in healthy control participants.</b>`,
        state: `notAnswered`,
        userAnswered: []
    ,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`        ,
        type: `MCSS`},
    {
        q: `Which of the following statements best describes findings regarding the prostate in exstrophy? `,
        q2: ``,
        q3: [],
        option: [` Volume weight and the cross-sectional area appeared healthy compared with published results from control subjects.`, 
        ` The prostate extended circumferentially around the urethra in all patients with exstrophy.`, 
        ` Free prostate-specific antigen (PSA) values were greater than in healthy controls, indicating recurrent injury from infection.`, 
        ` The vas deferens and seminal vesicles were abnormal due to the effect of the exstrophic bladder.`, 
        ` Total PSA values were not measurable in men with exstrophy.`],
        optionStyleType: `st-lower-alpha`,
        answer: [0],
        ansText: `Rationale: The volume, weight, and maximal cross-sectional area of the prostate appeared normal compared with published results from control subjects.`,
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: ` Which of the following accurately describes the vagina in the female patient with bladder exstrophy?`,
        q2: ``,
        q3: [],
        option: [`It is shorter than normal and of smaller caliber. `, 
        ` The vaginal orifice is displaced posteriorly because of the anterior exstrophic bladder.`, 
        `It is shorter than normal but of normal caliber. `, 
        `It is longer than normal and of wider caliber. `, 
        ` The cervix enters the posterior vaginal wall.`],
        optionStyleType: `st-lower-alpha`,
        answer: [0],
        ansText: `Rationale: The vagina is shorter than normal, hardly greater than 6 cm in depth, but of normal caliber. `,
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: ` Findings regarding the structure and innervation of the exstrophic bladder included the following:`,
        q2: ``,
        q3: [],
        option: [`The density and binding affinity of the muscarinic receptors were similar to norms. `, 
        `There was a decreased ratio of collagen to muscle in the exstrophic bladder. `, 
        ` There were more myelinated nerve profiles, indicating a later developmental stage.`, 
        `A threefold increase in the amount of type I collagen was noted. `, 
        ` Study of vasoactive intestinal polypeptide, protein gene product 9.5, and calcitonin gene–related peptide indicated the presence of dysinnervation.`],
        optionStyleType: `st-lower-alpha`,
        answer: [0],
        ansText: `Rationale: Muscarinic cholinergic receptor density and binding affinity were measured in control participants and in patients with classic bladder exstrophy. The density of the muscarinic cholinergic receptors in both the control and exstrophy groups was similar, as was the binding affinity of the muscarinic receptor. Therefore it was thought by the authors that the neurophysiologic composition of the exstrophied bladder is not grossly altered during its anomalous development. `,
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `Which of the following statements best describes bladder function in patients with bladder exstrophy? `,
        q2: ``,
        q3: [],
        option: [`After reconstruction, normal cystometrograms are noted in 10% to 25% of patients who are continent. `, 
        ` Before bladder neck reconstruction, 80% of patients had compliant and stable bladders.`, 
        `Involuntary contractions were rarely noted after bladder neck reconstruction. `, 
        `After bladder neck reconstruction, 90% of patients maintained normal bladder compliance. `, 
        ` After successful closure, ultrastructure remains abnormal in the majority.`],
        optionStyleType: `st-lower-alpha`,
        answer: [1],
        ansText: `Rationale: Diamond and colleagues (1999), looking at 30 patients with bladder exstrophy at various stages of reconstruction, found that 80% of patients had compliant and stable bladders before bladder neck reconstruction. `,
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},

    {
        q: ` The characteristic prenatal appearance of bladder exstrophy includes which of the following?`,
        q2: ``,
        q3: [],
        option: [`Absence of bladder filling `, 
        `Low-set umbilicus `, 
        `Widening of the pubic ramus `, 
        `Diminutive genitalia `, 
        `All of the above `],
        optionStyleType: `st-lower-alpha`,
        answer: [4],
        ansText: `Rationale: In a review of 25 prenatal ultrasonographic examinations with the resulting birth of a newborn with classic bladder exstrophy, several observations were made: (1) absence of bladder filling; (2) a low-set umbilicus; (3) a widened pubis ramus; (4) diminutive genitalia; and (5) a lower abdominal mass that increases in size while the pregnancy progresses and as the intra-abdominal viscera increase in size.`,
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `Newborn patient selection for immediate reconstruction is based on: `,
        q2: ``,
        q3: [],
        option: [`examination of the bladder in the nursery without anesthesia. `, 
        `complete lack of any surface defects on examination. `, 
        ` indentation of the bladder under anesthesia or outward bulging when the child cries.`, 
        ` size of the phallus at birth.`, 
        ` extent of the pubic diastasis.`],
        optionStyleType: `st-lower-alpha`,
        answer: [2],
        ansText: `Rationale: In minor grades of exstrophy that approach the condition of complete epispadias with incontinence, the bladder may be small yet may demonstrate acceptable capacity, either by bulging when the baby cries or by indenting easily when touched by a sterile gloved finger in the operating room with the child under anesthesia. `,
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `Fundamental steps in the modern staged reconstruction of bladder exstrophy include all of the following EXCEPT `,
        q2: ``,
        q3: [],
        option: [`Early closure of the bladder, posterior urethra, and abdominal wall `, 
        ` Early epispadias repair at around age 1 year`, 
        ` Conversion of the bladder exstrophy to complete epispadias`, 
        `Bladder neck reconstruction before the epispadias repair to provide early continence `, 
        ` Ureteral reimplantation at the time of bladder neck reconstruction`],
        optionStyleType: `st-lower-alpha`,
        answer: [3],
        ansText: `Rationale: The most significant changes in the management of bladder exstrophy have been (1) early bladder, posterior urethral, and abdominal wall closure, usually with osteotomy; (2) early epispadias repair; (3) reconstruction of a continent bladder neck and reimplantation of the ureters; and (4) definition of strict criteria for the selection of patients suitable for this approach. Bladder neck repair usually occurs when the child is 4 to 5 years of age, has an adequate bladder capacity, and, most important, is ready to participate in a postoperative voiding program.  `,
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: ` What is the best treatment option at the time of birth in a child whose bladder template is judged to be too small to undergo closure?`,
        q2: ``,
        q3: [],
        option: [`Excision of the bladder with a nonrefluxing colon conduit `, 
        ` Immediate closure with epispadias repair to provide resistance and allow the bladder to grow`, 
        ` Delaying closure by 4 to 6 months with reassessment to see if the bladder will grow`, 
        ` Bladder closure, augmentation, ureteral reimplantation, and a continence procedure`, 
        ` An osteotomy to improve the potential for successful closure`],
        optionStyleType: `st-lower-alpha`,
        answer: [2],
        ansText: `Rationale: Ideally, waiting for the bladder template to grow for 4 to 6 months in the child with a small bladder is not as risky as submitting a small bladder template to closure in an inappropriate setting, resulting in dehiscence and allowing the fate of the bladder to be sealed at that point. `,
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: ` Combined osteotomy was developed for all of the following reasons EXCEPT`,
        q2: ``,
        q3: [],
        option: [`This approach allows placement of an external fixator device. `, 
        `Superior cosmesis is provided by this approach. `, 
        `There is no need to turn the patient to perform an osteotomy. `, 
        ` Pubic approximation is easier.`, 
        ` There is less risk of malunion of the iliac wing and also less blood loss.`],
        optionStyleType: `st-lower-alpha`,
        answer: [2],
        ansText: `Rationale: Combined osteotomy was developed for three reasons: (1) osteotomy is performed with the patient in the supine position, as is the urologic repair, thereby avoiding the need to turn the patient; (2) the anterior approach to this osteotomy allows placement of an external fixator device and intrafragmentary pins under direct vision; and (3) the cosmetic appearance of this osteotomy is superior to that of the posterior iliac approach. `,
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `Complications associated with osteotomy and immobilization techniques include all of the following EXCEPT `,
        q2: ``,
        q3: [],
        option: [` Skin ulceration is associated with use of mummy wrapping.`, 
        ` Failure of the bladder and abdominal wall closure is associated with the use of spica casting.`, 
        ` High rates of failure of reconstruction are associated with the use of osteotomy and external fixation.`, 
        `Transient femoral nerve palsy is associated with the use of osteotomy. `, 
        `Delayed union of the iliac wings may occur after the use of posterior osteotomy. `],
        optionStyleType: `st-lower-alpha`,
        answer: [2],
        ansText: `Rationale: Successful closure was noted in 97% of those immobilized with an external fixator and modified Buck traction. `,
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `Which of the following statements is TRUE regarding the various described approaches to bladder exstrophy reconstruction? `,
        q2: ``,
        q3: [],
        option: [`The Warsaw approach includes bladder neck reconstruction at the time of initial bladder closure. `, 
        ` The Erlangen approach includes all of the features of reconstruction of the exstrophy in a single procedure.`, 
        `The Seattle approach (Complete Primary Repair of Exstrophy [CPRE]) includes bladder neck reconstruction as part of the complete reconstruction of exstrophy. `, 
        ` Combined bladder closure and epispadias repair is performed in cases of primary exstrophy repair at birth.`, 
        ` The Warsaw approach uses the Young repair as the preferred method for epispadias reconstruction.`],
        optionStyleType: `st-lower-alpha`,
        answer: [1],
        ansText: `Rationale: This method is truly a “complete repair” because it accomplishes all of the facets of exstrophy reconstruction in a single procedure. Surgical repair is, however, performed at 8 to 10 weeks of age, when the infant is larger and has had the opportunity to be medically stabilized. `,
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: ` After initial primary bladder closure in the newborn, what should be done if there are recurrent urinary tract infections?`,
        q2: ``,
        q3: [],
        option: [`Voiding cystourethrogram `, 
        ` Computed tomography (CT) scan of the bladder`, 
        `Ureteral reimplantation `, 
        `Prophylaxis modified `, 
        `Cystoscopy `],
        optionStyleType: `st-lower-alpha`,
        answer: [4],
        ansText: `Rationale: An important caveat is that if there are recurrent urinary tract infections or if the bladder is distended on an ultrasonographic study, cystoscopy should be performed and the posterior urethra should be carefully examined anteriorly for erosion of the intrapubic stitch, which may be the cause of the recurrent infections. `,
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: ` After successful bladder closure, management should include all the following EXCEPT`,
        q2: ``,
        q3: [],
        option: [`Calibration of the urethral outlet 4 weeks after closure to ensure free drainage `, 
        `Ultrasound evaluation of the kidneys and bladder `, 
        ` Intermittent antibiotics for urinary tract infections`, 
        ` Complete bladder drainage by suprapubic tube clamping`, 
        ` Yearly cystoscopic evaluation`],
        optionStyleType: `st-lower-alpha`,
        answer: [2],
        ansText: `Rationale: Before removal of the suprapubic tube 4 weeks after surgery, the bladder outlet is calibrated by a urethral catheter or a urethral sound to ensure free drainage. A complete ultrasound examination is obtained to ascertain the status of the renal pelves and ureters, and appropriate urinary antibiotics are administered because all patients will have reflux postclosure. Residual urine is estimated by clamping the suprapubic tube, and specimens for culture are obtained before the patient leaves the hospital and at subsequent intervals to detect infection and ensure that the bladder is empty. `,
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `In a patient with bladder exstrophy who undergoes more than one closure of the bladder and urethral defect, what is the chance of having adequate bladder capacity for later bladder neck reconstruction? `,
        q2: ``,
        q3: [],
        option: [`10% `, 
        `20% `, 
        ` 30%`, 
        ` 60%`, 
        ` 75%`],
        optionStyleType: `st-lower-alpha`,
        answer: [3],
        ansText: `Rationale: In one study, if a patient underwent two closures, the chance of having an adequate bladder capacity for bladder neck reconstruction was 60%. `,
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `The key concepts in the reconstruction of epispadias include all of the following EXCEPT `,
        q2: ``,
        q3: [],
        option: [`Correction of ventral chordee `, 
        ` Urethral reconstruction`, 
        ` Glans reconstruction`, 
        ` Penile skin coverage`, 
        ` Penile lengthening`],
        optionStyleType: `st-lower-alpha`,
        answer: [0],
        ansText: `Rationale: Regardless of the surgical technique chosen for reconstruction of the penis in bladder exstrophy, four key concerns must be addressed to ensure a functional and cosmetically pleasing penis: (1) correction of dorsal chordee, (2) urethral reconstruction, (3) glanular reconstruction, and (4) penile skin closure. `,
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `Information gleaned from most major series of bladder neck reconstruction indicates that the most important factor to predict success and eventual continence after bladder neck reconstruction is: `,
        q2: ``,
        q3: [],
        option: [`the age of the child. `, 
        ` the number of prior bladder infections.`, 
        ` the number of attempts at bladder closure.`, 
        ` bladder capacity.`, 
        ` vesicoureteral reflux.`],
        optionStyleType: `st-lower-alpha`,
        answer: [3],
        ansText: `Rationale: <b>The most important long-term factor gleaned from a review of all these series is the fact that bladder capacity at the time of bladder neck reconstruction is an important determinant of eventual success.</b>`,
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `After bladder neck reconstruction, within what time period do the majority of patients achieve daytime continence? `,
        q2: ``,
        q3: [],
        option: [` 2 months`, 
        `6 months `, 
        ` 1 year`, 
        ` 2 years`, 
        ` 4 years`],
        optionStyleType: `st-lower-alpha`,
        answer: [2],
        ansText: `Rationale: The vast majority of patients achieve daytime continence in the first year after bladder neck reconstruction. `,
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: ` After a failed attempted bladder closure in the newborn period, what time period should elapse before a secondary repair is attempted?`,
        q2: ``,
        q3: [],
        option: [` 2 months`, 
        ` 6 months`, 
        `12 months `, 
        ` 18 months`, 
        `2 years `],
        optionStyleType: `st-lower-alpha`,
        answer: [1],
        ansText: `Rationale: Dehiscence—which may be precipitated by incomplete mobilization of the pelvic diaphragm and inadequate pelvic immobilization postoperatively, wound infection, abdominal distention, or urinary tube malfunction—necessitates a 6-month recovery period before a second attempt at closure.`,
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `All of the following statements are TRUE regarding the results of modern staged reconstruction of exstrophy EXCEPT `,
        q2: ``,
        q3: [],
        option: [`The onset of eventual continence and continence rates were unchanged in those who had initial successful closure. `, 
        `The modified Cantwell-Ransley repair has replaced the Young technique because there is less urethral tortuosity and fistula rates are lower. `, 
        `The incidence of fistula formation was 12% at 3 months after epispadias repair. `, 
        `Continence is more likely in those patients undergoing initial closure before 72 hours of age or those who have closure after 72 hours of age with osteotomy. `, 
        ` Continence rates are higher in those who have a capacity of 85 mL or more at the time of bladder neck reconstruction.`],
        optionStyleType: `st-lower-alpha`,
        answer: [0],
        ansText: `Rationale: <b>The importance of a successful initial closure is emphasized by Oesterling and Jeffs (1987) and by Husmann and colleagues (1989), who found that the onset of eventual continence was quicker and the continence rate higher in those who underwent a successful initial closure with or without osteotomy.</b> `,
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `Which of the following statements is TRUE regarding exstrophy failures? `,
        q2: ``,
        q3: [],
        option: [` After successful secondary closure, 90% of patients develop dryness and voided continence.`, 
        ` Dehiscence after complete primary repair may be associated with corporal, urethral, and other major soft tissue loss.`, 
        ` Bladder prolapse can be managed with minimal outlet procedures because this is considered a mild failure.`, 
        ` Because the results of reclosure are poor, immediate resection of the bladder plate followed by neobladder construction is the preferred management.`, 
        ` Posterior urethral stricture is usually a late complication occurring 4 to 6 years after initial closure.`],
        optionStyleType: `st-lower-alpha`,
        answer: [1],
        ansText: `Rationale: Dehiscence and prolapse have also been reported after the “complete repair” and may be associated with glandular, corporeal, urethral plate, and other major soft tissue loss. `,
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `Bladder neck reconstruction is designated as a failure if a 3-hour dry interval is not achieved within 2 years after surgery. Management of such failure is with the use of: `,
        q2: ``,
        q3: [],
        option: [`collagen injection, which can lead to dryness. `, 
        ` artificial urinary sphincter with small bladder capacity.`, 
        `bladder neck transection, augmentation cystoplasty, and continent diversion. `, 
        ` repeat bladder neck reconstruction in relatively tight bladder necks.`, 
        ` repeat bladder neck reconstruction in bladder instability.`],
        optionStyleType: `st-lower-alpha`,
        answer: [2],
        ansText: `Rationale: The artificial urinary sphincter has been used with some success in patients who have a good bladder capacity. However, in most of these failures the bladder capacity is small and augmentation will be required. At the time of reoperative surgery, the bladder neck is transected proximal to the prostate with a Mitrofanoff substitution, a continence procedure such as an artificial sphincter or collagen injection is performed, or both are performed. In our extensive experience with failed bladder neck reconstruction, most of the patients have had several surgeries and must be dry. In such cases the most suitable alternative is bladder neck transection, augmentation, and a continent urinary stoma (Gearhart et al., 1995b; Hensle et al., 1995). `,
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: ` The risks of ureterosigmoidostomy in the exstrophy population include:`,
        q2: ``,
        q3: [],
        option: [`pyelonephritis and hyperchloremic acidosis. `, 
        ` pyelonephritis, hyponatremia, and rectal incontinence.`, 
        ` low incidence for eventual development of cancer.`, 
        `poor outcomes with upper tract deterioration. `, 
        ` prolapse of the abdominal stoma.`],
        optionStyleType: `st-lower-alpha`,
        answer: [0],
        ansText: `Rationale: However, this form of diversion should not be offered until one is certain that anal continence is normal and after the family has been made aware of the potentially serious complications including pyelonephritis, hyperchloremic acidosis, rectal incontinence, ureteral obstruction, and delayed development of malignancy. `,
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `What is the live birth incidence of cloacal exstrophy? `,
        q2: ``,
        q3: [],
        option: [`1 in 20,000 `, 
        `1 in 100,000 `, 
        ` 1 in 400,000`, 
        `1 in 600,000 `, 
        `1 in 1,000,000 `],
        optionStyleType: `st-lower-alpha`,
        answer: [2],
        ansText: `Rationale: Fortunately cloacal exstrophy is exceedingly rare, occurring in 1 in 200,000 to 400,000 live births. `,
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `All of the following statements regarding neurospinal abnormalities in cloacal exstrophy are true EXCEPT `,
        q2: ``,
        q3: [],
        option: [`Thoracic defects may be noted in 10% of patients. `, 
        `The embryologic basis for the neurospinal defect has been identified as failure of neural tube closure. `, 
        ` Autonomic bladder innervation is derived from a more medial location.`, 
        ` Innervation of the duplicated corporal bodies arises from the sacral plexus and courses medial to the hemibladders.`, 
        `Functional defects can include minimal lower extremity function. `],
        optionStyleType: `st-lower-alpha`,
        answer: [1],
        ansText: `Rationale: The embryologic basis for the neurospinal defects associated with cloacal exstrophy has been postulated to be secondary to problems with the disruption of the tissue of the dorsal mesenchyme rather than failure of neural tube closure (McLaughlin et al., 1995). Alternatively, it has been suggested that the defects that lead to the formation of cloacal exstrophy may lead to the developing spinal cord and vertebrae being pulled apart (Cohen, 1991). `,
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: ` Which of the following is TRUE regarding cloacal exstrophy?`,
        q2: ``,
        q3: [],
        option: [`The bones in a child with cloacal exstrophy are markedly different microscopically from those of healthy controls. `, 
        `In the presence of a normal bowel length, there is low probability for the development of short-gut syndrome. `, 
        `The most common Müllerian anomaly noted is partial uterine duplication. `, 
        ` Cardiovascular and pulmonary anomalies are frequently noted.`, 
        `The most common upper urinary tract anomaly noted is multicystic dysplastic kidney. `],
        optionStyleType: `st-lower-alpha`,
        answer: [2],
        ansText: `Rationale: This anomaly is reported to be as high as 95% (Diamond, 1990). The vast majority of these patients had partial uterine duplication, predominantly a bicornate uterus. `,
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `What is the incidence of omphalocele associated with cloacal exstrophy? `,
        q2: ``,
        q3: [],
        option: [`20% `, 
        ` 40%`, 
        `60% `, 
        ` 75%`, 
        `95% `],
        optionStyleType: `st-lower-alpha`,
        answer: [4],
        ansText: `Rationale: In Diamond’s series, the incidence of omphalocele was 88%, with a majority of all series reporting 95% or greater.`,
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `In the patient with cloacal exstrophy, hindgut remnants should be preserved in order to: `,
        q2: ``,
        q3: [],
        option: [`enlarge the bladder.`, 
        ` permit vaginal reconstruction.`, 
        `allow either bladder augmentation or vaginal reconstruction. `, 
        `provide additional length of bowel for fluid absorption. `, 
        ` allow later anal pull-through surgery.`],
        optionStyleType: `st-lower-alpha`,
        answer: [3],
        ansText: `Rationale: With the recognition of the metabolic changes in patients with ileostomy, an attempt is always made to use the hindgut remnant to provide additional length of bowel for fluid absorption. `,
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: ` Current research regarding gender in cloacal exstrophy indicates that:`,
        q2: ``,
        q3: [],
        option: [`psychosexual evaluation indicates that patients have a marked female shift in development. `, 
        ` patients have feminine childhood behavior but develop masculine gender identity.`, 
        ` histology of the testis at birth is abnormal; therefore removal has been recommended.`, 
        ` gender is based on quality of functional reconstruction rather than on karyotype.`, 
        `a functional and cosmetically acceptable phallus can now be constructed. `],
        optionStyleType: `st-lower-alpha`,
        answer: [4],
        ansText: `Rationale: <b>Most authors recommend assigning gender consistent with the karyotypic makeup of the individual if at all possible.</b> This policy can be supported by a report indicating that the histology of the testis at birth is normal (Mathews et al., 1999a). Furthermore, with the evolution of techniques for phallic reconstruction, a functional and cosmetically acceptable phallus can now be constructed (Husmann et al., 1989). `,
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `What is the live birth incidence of male epispadias? `,
        q2: ``,
        q3: [],
        option: [`1 in 72,000 `, 
        ` 1 in 117,000`, 
        ` 1 in 150,000`, 
        ` 1 in 250,000`, 
        ` 1 in 400,000`],
        optionStyleType: `st-lower-alpha`,
        answer: [1],
        ansText: `Rationale: Male epispadias is a rare anomaly, with a reported incidence of 1 in 117,000 males.`,
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `What is the incidence of reflux in patients with complete epispadias? `,
        q2: ``,
        q3: [],
        option: [`10% to 20% `, 
        ` 30% to 40%`, 
        ` 50%`, 
        `70% `, 
        ` 90%`],
        optionStyleType: `st-lower-alpha`,
        answer: [1],
        ansText: `Rationale: The ureterovesical junction is inherently deficient in complete epispadias, and reflux has been reported between 30% and 40% in a number of series. `,
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: ` In the complete epispadias group, what is the predominant indicator of eventual continence?`,
        q2: ``,
        q3: [],
        option: [`Length of the urethral groove `, 
        ` Lack of spinal abnormalities`, 
        `Bladder capacity at the time of bladder neck reconstruction `, 
        `Age at bladder neck reconstruction `, 
        ` Age at epispadias repair and degree of resistance provided`],
        optionStyleType: `st-lower-alpha`,
        answer: [2],
        ansText: `Rationale: In the epispadias group, much as in the exstrophy group, bladder capacity is the predominant indicator of eventual continence. `,
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: ` All of the following are true regarding exstrophy-epispadias variants EXCEPT`,
        q2: ``,
        q3: [],
        option: [`The presence of musculoskeletal defects characteristic of the complex, with a normal urinary tract, is termed <i>pseudoexstrophy</i>. `, 
        ` The bladder is completely exstrophied in the superior vesical fissure variant.`, 
        `With “covered” exstrophy, an isolated ectopic bowel segment has frequently been noted. `, 
        ` An isolated segment of bladder is left on the abdominal wall, with a complete urinary tract within the bladder in duplicate exstrophy.`, 
        ` A common embryologic origin has been postulated for developments of all of the variants.`],
        optionStyleType: `st-lower-alpha`,
        answer: [0],
        ansText: `Rationale: In the superior vesical fissure variant of the exstrophy complex, the musculature and skeletal defects are exactly the same as those in classic exstrophy; however, the persistent cloacal membrane ruptures only at the uppermost portion, and a superior vesical fistula that actually resembles a vesicostomy results. Bladder extrusion is minimal and is present only over the normal umbilicus.  `,
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: ` Sexual function and libido in male and female exstrophy patients are:`,
        q2: ``,
        q3: [],
        option: [` normal in males, abnormal in females.`, 
        `normal only in males. `, 
        `normal in both males and females. `, 
        ` normal only in females.`, 
        ` abnormal in both males and females.`],
        optionStyleType: `st-lower-alpha`,
        answer: [2],
        ansText: `Rationale: Sexual function and libido in exstrophy patients are normal. `,
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: ` What is the most common complication after pregnancy in female exstrophy patients?`,
        q2: ``,
        q3: [],
        option: [` Premature labor`, 
        `Rectal prolapse `, 
        ` Preeclampsia`, 
        ` Cervical and uterine prolapse`, 
        ` Oligohydramnios`],
        optionStyleType: `st-lower-alpha`,
        answer: [3],
        ansText: `Rationale: The main complication after pregnancy was cervical and uterine prolapse, which occurred frequently.`,
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `Psychologic studies of male and female children with bladder exstrophy find that: `,
        q2: ``,
        q3: [],
        option: [` all have clinical psychopathology.`, 
        ` they do not have clinical psychopathology.`, 
        ` most have significant depression because of the condition.`, 
        ` many children have gender dysphoria.`, 
        ` half of males and half of females have clinical psychopathology.`],
        optionStyleType: `st-lower-alpha`,
        answer: [1],
        ansText: `Rationale: The conclusion of this long-term study was that children with exstrophy do not have clinical psychopathology. `,
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},

    {
        q: `Single-stage reconstruction by using the complete primary exstrophy repair technique offers several advantages versus staged reconstruction EXCEPT `,
        q2: ``,
        q3: [],
        option: [` The possibility of correcting the penile, bladder, and bladder neck abnormalities of bladder exstrophy with one operation.`, 
        ` The ability to achieve urinary continence without bladder neck reconstruction.`, 
        `Correction of vesicoureteral reflux at the time of surgery. `, 
        `Lower complication rates than previous attempts at single-stage reconstruction. `, 
        ` Initiation of bladder cycling early in life.`],
        optionStyleType: `st-lower-alpha`,
        answer: [2],
        ansText: `Rationale: In most applications of the primary exstrophy repair technique, correction of vesicoureteral reflux is not performed, although some have reported performing ureteral reimplantation. All of the other elements are considered advantages of the primary repair. `,
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},

    {
        q: ` Single-stage reconstruction by using the complete primary exstrophy repair technique relies on which of the following to achieve continence?`,
        q2: ``,
        q3: [],
        option: [`Reestablishment of normal anatomic relationships `, 
        ` Bladder neck reconstruction at the time of primary surgery`, 
        ` Osteotomy at the time of single-stage reconstruction`, 
        ` Simultaneous epispadias repair`, 
        ` None of the above`],
        optionStyleType: `st-lower-alpha`,
        answer: [0],
        ansText: `Rationale: The fundamental basis of the primary repair technique is to reposition the bladder neck and urethral complex into the normal pelvic position more posteriorly than at birth. This permits more normal function of the pelvic floor in maintenance of continence. The other factors do not contribute as significantly to continence. `,
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `The following postoperative factors have been shown to increase the success of reconstruction for bladder exstrophy EXCEPT `,
        q2: ``,
        q3: [],
        option: [`Immobilization with external fixators, Buck traction, a spica cast, or a mummy wrap `, 
        `Antibiotic therapy `, 
        `Prolonged status of nothing by mouth (NPO) to avoid abdominal distention `, 
        ` Urinary diversion through ureteral stenting and suprapubic urinary drainage`, 
        ` Adequate nutritional support`],
        optionStyleType: `st-lower-alpha`,
        answer: [2],
        ansText: `Rationale: It is not necessary to maintain an NPO status after primary repair because this will compromise nutrition. If an ileus develops, appropriate decompression and management are necessary because abdominal distention strains the repair. All other factors contribute to a successful outcome. `,
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: ` Single-stage reconstruction by using the complete primary exstrophy repair technique can be safely performed because:`,
        q2: ``,
        q3: [],
        option: [` the neurovascular bundles of the corpus cavernosal bodies lie laterally rather than dorsally on the bodies.`, 
        ` the cavernosal bodies and urethral wedge are not actually separated from each other in this technique.`, 
        ` the blood supply to the cavernosal bodies and that to the urethral wedge are independent of each other.`, 
        ` the blood supply is quickly reestablished once the components are “reassembled.”`, 
        `the distal vascular communications between the corpora and urethral wedge are preserved. `],
        optionStyleType: `st-lower-alpha`,
        answer: [2],
        ansText: `Rationale: Because the three elements of the penis, the two corpora, and the urethral wedge are fully separated in the penile disassembly, their vasculature must be proximal, which it is; that accounts for the success of this method. Nevertheless, preservation of these proximal vascular supplies is essential. `,
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: ` The proximal limit(s) of dissection by using the complete primary exstrophy repair technique is/are:`,
        q2: ``,
        q3: [],
        option: [` the intersymphyseal band.`, 
        ` the muscles of the pelvic floor.`, 
        ` the rectum.`, 
        ` the corpora spongiosa.`, 
        ` the endopelvic fascia.`],
        optionStyleType: `st-lower-alpha`,
        answer: [1],
        ansText: `Rationale: The limit of dissection along the penile structures is the pelvic floor, which is then split to permit repositioning of the bladder neck complex posteriorly. `,
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: ` Factors that mitigate against use of a single-stage reconstruction technique for cloacal exstrophy include the presence of:`,
        q2: ``,
        q3: [],
        option: [` a large omphalocele.`, 
        ` a wide pubic diastasis.`, 
        `a concomitant myelomeningocele. `, 
        ` a small bladder plate.`, 
        ` all of the above.`],
        optionStyleType: `st-lower-alpha`,
        answer: [4],
        ansText: `Rationale: All of these factors would indicate that an attempt to perform a primary repair would be at high risk for failure, predominantly by dehiscence. Several of these factors may be present at one time. `,
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: ` Complications of the complete primary exstrophy repair technique include:`,
        q2: ``,
        q3: [],
        option: [` myogenic bladder failure.`, 
        ` testicular atrophy.`, 
        ` urethrocutaneous fistula.`, 
        `hip dislocation. `, 
        ` epispadias.`],
        optionStyleType: `st-lower-alpha`,
        answer: [2],
        ansText: `Rationale: The most common complication after primary repair is development of a urethrocutaneous fistula on the ventrum of the penis. Other complications can include corporeal devascularization, hydronephrosis, and hypospadias. `,
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},









];
