var quiz = [
    

    {
        q: `<!--1. -->Which of the following is NOT correct concerning laparoscopic pyeloplasty?`,
        q2: ``,
        q3: [],
        option: [`<!--a. -->Discounted early as unacceptable due to degree of difficulty`, 
        `<!--b. -->Can be performed after a failed previous pyeloplasty`, 
        `<!--c. -->Has an overall higher success rate than endopyelotomy`, 
        `<!--d. -->Should be performed in patients of all ages`, 
        `<!--e. -->Many different techniques for laparoscopic approach have been described`],
        optionStyleType: `st-lower-alpha`,
        answer: [3],
        ansText:`Rationale: <!--<b>d. Should be performed in patients of all ages.</b>--> In newborns the access to the ureteropelvic junction only requires a very small incision. Laparoscopy is feasible in infants, but there is a lack of evidence of advantages for this age group.`, 
        state: `notAnswered`,
        userAnswered: []
    ,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`        ,
        type: `MCSS`},
    {
        q: `<!--2. -->In regard to closure of trocar sites:`,
        q2: ``,
        q3: [],
        option: [`<!--a. -->closing fascial wounds more than 3 mm is recommended.`, 
        `<!--b. -->fascial closure devices facilitate closure in the obese patient.`, 
        `<!--c. -->omentum is the most common herniated intra-abdominal structure.`, 
        `<!--d. -->trocars should not be removed before the intra-abdominal pressure is close to normal`, 
        `<!--e. -->all of the above are true.`],
        optionStyleType: `st-lower-alpha`,
        answer: [3],
        ansText:`Rationale: <!--<b>d. Trocars should not be removed before the intra-abdominal pressure is close to normal.</b>--> Lowering the pressure before removing the trocars will reveal that the hemostasis is under control and prevents intra-abdominal (bowel, omentum) content from entering the port holes.`, 
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `<!--3. -->Which is NOT true for transperitoneal procedures?`,
        q2: ``,
        q3: [],
        option: [`<!--a. -->Sutures may be passed through the anterior abdominal wall.`, 
        `<!--b. -->For lower abdominal procedures, infants are best positioned across the foot of the bed.`, 
        `<!--c. -->Laxity of the infant abdominal wall can limit exposure due to compression.`, 
        `<!--d. -->Cannula fixation is a common problem in pediatric laparoscopy.`, 
        `<!--e. -->Visibility is usually a problem.`],
        optionStyleType: `st-lower-alpha`,
        answer: [4],
        ansText:`Rationale: <!--<b>e. Visibility is usually a problem.</b>--> The peritoneal lining mirrors the light from the telescope giving a better visibility than in the retroperitoneal route.`, 
        state: `notAnswered`,
        userAnswered: []
    ,
	type: `MCSS`,
	type: `MCSS`        ,
        type: `MCSS`},
    {
        q: `<!--4. -->A recognized risk of laparoscopy in all infants is:`,
        q2: ``,
        q3: [],
        option: [`<!--a. -->use of monopolar cautery.`, 
        `<!--b. -->ventilatory compromise.`, 
        `<!--c. -->abdominal adhesions.`, 
        `<!--d. -->decreased renal perfusion.`, 
        `<!--e. -->compartmental syndrome.`],
        optionStyleType: `st-lower-alpha`,
        answer: [0],
        ansText:`Rationale: <!--<b>a. Use of monopolar cautery.</b>--> Monopolar cautery increases the risk of unrecognized lesions to intra-abdominal organs, particularly the bowel.`, 
        state: `notAnswered`,
        userAnswered: []
    ,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`        ,
        type: `MCSS`},
    {
        q: `<!--5. -->Which of the following is a relative contraindication to retroperitoneoscopic surgery in the pediatric population?`,
        q2: ``,
        q3: [],
        option: [`<!--a. -->Horseshoe kidneys`, 
        `<!--b. -->Spinal deformity`, 
        `<!--c. -->Previous abdominal surgery`, 
        `Weight`, 
        `<!--e. -->Intestinal malrotation`],
        optionStyleType: `st-lower-alpha`,
        answer: [0],
        ansText:`Rationale: <!--<b>a. Horseshoe kidneys.</b>--> The access to the UPJ from the posterior aspect is extremely difficult in horseshoe kidneys.`, 
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `<!--6. -->Hypothermia during laparoscopy in all infants is caused by:`,
        q2: ``,
        q3: [],
        option: [`<!--a. -->Insufflation of large amount of CO<sub>2</sub> due to port leakage.`, 
        `<!--b. -->High-frequency ventilation.`, 
        `<!--c. -->Room-temperature insufflation.`, 
        `<!--d. -->Evaporation.`, 
        `<!--e. -->Cold room temperature.`],
        optionStyleType: `st-lower-alpha`,
        answer: [0],
        ansText:`Rationale: <!--<b>a. Insufflation of large amount of CO<sub>2</sub> due to port leakage.</b>--> The large amount of gas exchange lowers the intra-abdominal temperature significantly.`, 
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `<!--7. -->Regarding pediatric minimally invasive surgery in obese patients:`,
        q2: ``,
        q3: [],
        option: [`<!--a. -->Suture can be placed from the skin at the entry site to the cannula to keep the cannula from sliding off if rapid desufflation is encountered.`, 
        `<!--b. -->Hitch stitches are helpful.`, 
        `<!--c. -->An insufflation needle works well in most children, because the abdominal wall is thin.`, 
        `<!--d. -->Bladeless optical trocars or open access for the camera port might be helpful.`, 
        `<!--e. -->Higher insufflation pressures are needed.`],
        optionStyleType: `st-lower-alpha`,
        answer: [3],
        ansText:`Rationale: <!--<b>d. Bladeless optical trocars or open access for the camera port might be helpful.</b>--> Blind access to the peritoneal cavity imposes an inherent risk of organ damage.`, 
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `<!--8. -->Which of the following is not found to be associated with higher success rate of endoscopic correction of vesicoureteral reflux?`,
        q2: ``,
        q3: [],
        option: [`<!--a. -->Volume of Dx/HA used`, 
        `<!--b. -->Surgeon experience`, 
        `<!--c. -->Volcano-shaped mound with no hydrodistention`, 
        `<!--d. -->Negative intraoperative cystogram`, 
        `<!--e. -->Utilization of the double hydrodistention-implantation technique`],
        optionStyleType: `st-lower-alpha`,
        answer: [3],
        ansText:`Rationale: <!--<b>d. Negative intraoperative cystogram.</b>--> A negative intraoperative cystogram does not reveal the success rate of the treatment since the child is under anesthesia and unable to spontaneously void.`, 
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `<!--9. -->Regarding surgical correction of vesicoureteral reflux, which of the following is currently accepted?`,
        q2: ``,
        q3: [],
        option: [`<!--a. -->Extravesical ureteral reimplantation`, 
        `<!--b. -->Intravesical ureteral reimplantation`, 
        `<!--c. -->Endoscopic injection of bulking agent`, 
        `<!--d. -->All of the above`, 
        `<!--e. -->None of the above`],
        optionStyleType: `st-lower-alpha`,
        answer: [3],
        ansText:`Rationale: <!--<b>d. All of the above.</b>--> Extravesical and intravesical ureteral reimplantation are all options for treatment of vesicoureteral reflux. In the past decade there has been widespread enthusiasm for endoscopic treatment, and different bulking agents have been used to correct vesicoureteral reflux by using minimally invasive techniques.`, 
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `<!--10. -->Common to each type of open/laparoscopic/robotic repair for reflux is the creation of:`,
        q2: ``,
        q3: [],
        option: [`<!--a. -->a valvular mechanism that enables ureteral compression with bladder filling and contraction.`, 
        `<!--b. -->a mucosal tunnel for reimplantation having adequate muscular backing.`, 
        `<!--c. -->a tunnel length of three times the ureteral diameter.`, 
        `<!--d. -->all of the above.`, 
        `<!--d. -->none of the above.`],
        optionStyleType: `st-lower-alpha`,
        answer: [0],
        ansText:`Rationale: <!--<b>a. A valvular mechanism that enables ureteral compression with bladder filling and contraction.</b>--> Common to each technique is the creation of a valvular mechanism that enables ureteral compression with bladder filling and contraction, thus reenacting normal anatomy and function. A successful ureteroneocystostomy provides a submucosal tunnel for reimplantation having sufficient length and adequate muscular backing. A tunnel length of five times the ureteral diameter is cited as necessary for eliminating reflux.`, 
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `<!--11. -->Early postoperative obstruction can occur after a ureteral reimplant due to:`,
        q2: ``,
        q3: [],
        option: [`edema.`, 
        `<!--b. -->subtrigonal bleeding.`, 
        `<!--c. -->twist or angulation of the ureter.`, 
        `<!--d. -->blood clots.`, 
        `<!--e. -->all of the above.`],
        optionStyleType: `st-lower-alpha`,
        answer: [4],
        ansText:`Rationale: <!--<b>e. All of the above.</b>--> Early after surgery, various degrees of obstruction can be expected of the reimplanted ureter. Edema, subtrigonal bleeding, and bladder spasms all possibly contribute. Mucus plugs and blood clots are other causes. Most postoperative obstructions are mild and asymptomatic and resolve spontaneously. More significant obstructions are usually symptomatic. Affected children typically present 1 to 2 weeks after surgery with acute abdominal pain, nausea, and vomiting.`, 
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `<!--12. -->If early postoperative obstruction occurs after a ureteral reimplant, the next step is:`,
        q2: ``,
        q3: [],
        option: [`<!--a. -->immediate nephrostomy tube placement.`, 
        `<!--b. -->immediate placement of a ureteral stent.`, 
        `<!--c. -->initial observation and diversion for unabating symptoms.`, 
        `<!--d. -->placement of both a nephrostomy tube and a ureteral stent.`, 
        `reoperation.`],
        optionStyleType: `st-lower-alpha`,
        answer: [2],
        ansText:`Rationale: <!--<b>c. Initial observation and diversion for unabating symptoms.</b>--> The large majority of perioperative obstructions subside spontaneously, but placement of a nephrostomy tube or ureteral stent sometimes becomes necessary for unabating symptoms.`, 
        state: `notAnswered`,
        userAnswered: []
    ,
	type: `MCSS`,
	type: `MCSS`        ,
        type: `MCSS`},
    {
        q: `<!--13. -->Which of the following is TRUE regarding persistent reflux after ureteral reimplantation?`,
        q2: ``,
        q3: [],
        option: [`<!--a. -->It may be due to unrecognized secondary causes of reflux such as neuropathic bladder and severe voiding dysfunction.`, 
        `<!--b. -->It seldom results from a failure to provide adequate muscular backing for the ureter within its tunnel.`, 
        `<!--c. -->It may be repaired surgically by using minor submucosal advancements.`, 
        `<!--d. -->All of the above.`, 
        `<!--d. -->none of the above.`],
        optionStyleType: `st-lower-alpha`,
        answer: [0],
        ansText:`Rationale: Other than technical errors, failure to identify and treat secondary causes of reflux is a common cause of the reappearance of reflux. Foremost among these secondary causes are unrecognized neuropathic bladder and severe voiding dysfunction.`, 
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `<!--14. -->Which of the following is TRUE regarding the treatment of vesicoureteral reflux?`,
        q2: ``,
        q3: [],
        option: [`<!--a. -->Since the widespread acceptance of endoscopic treatment, the indications for surgical correction differ between the open endoscopic and laparoscopic approaches.`, 
        `<!--b. -->Long-term follow-up data support the durability of endoscopic injection therapy.`, 
        `<!--c. -->All injection materials provide a similar success rate and are just as easily injected under similar circumstances.`, 
        `<!--d. -->The accuracy of the needle entry point during endoscopic injection, as well as the needle placement, are important components for the success of the surgical procedure.`, 
        `<!--e. -->The learning curve for endoscopic injection is similar to the learning curve for open surgical reimplantation.`],
        optionStyleType: `st-lower-alpha`,
        answer: [3],
        ansText:`Rationale: The learning curve for endoscopic injection is believed to be different from that of open surgical reimplantation.`, 
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `<!--15. -->Which of the following is TRUE regarding the laparoscopic/robotic approach for ureteral reimplantation?`,
        q2: ``,
        q3: [],
        option: [`<!--a. -->The advantages of this approach versus open surgery include smaller incisions, less discomfort, and quicker convalescence.`, 
        `<!--b. -->As with other laparoscopic/robotic procedures, experience is essential to the success of this approach.`, 
        `<!--c. -->Costs may be increased because of lengthier surgery and the expense of the equipment.`, 
        `<!--d. -->All of the above`, 
        `<!--d. -->none of the above`],
        optionStyleType: `st-lower-alpha`,
        answer: [3],
        ansText:`Rationale: <!--<b>d. All of the above.</b>--> The advantages of this approach versus open surgery include smaller incisions, less discomfort, brief hospitalizations (although many centers now perform open reimplants on an outpatient basis), and quicker convalescence.`, 
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `<!--16. -->Which of the following is TRUE regarding primary obstructive megaureters?`,
        q2: ``,
        q3: [],
        option: [`<!--a. -->It is caused by a dysfunctional juxtavesical segment that is unable to propagate urine at acceptable rates of flow.`, 
        `<!--b. -->It most commonly occurs with neurogenic and non-neurogenic voiding dysfunction or infravesical obstructions such as posterior urethral valves.`, 
        `<!--c. -->It may be due to acute infections, nephropathies, and other medical conditions that cause significant increases in urinary output that overwhelm maximal peristalsis.`, 
        `<!--d. -->It is diagnosed when reflux, obstruction, and secondary causes of dilatation are ruled out.`, 
        `<!--e. -->None of the above.`],
        optionStyleType: `st-lower-alpha`,
        answer: [0],
        ansText:`Rationale: Obstruction results from the presence of an abnormal adynamic segment at the terminal end of the ureter near or at the ureterovesical junction (UVJ).`, 
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `<!--17. -->Which of the following is TRUE regarding secondary obstructive megaureters?`,
        q2: ``,
        q3: [],
        option: [`<!--a. -->It is caused by an aperistaltic juxtavesical segment that is unable to propagate urine at acceptable rates of flow.`, 
        `<!--b. -->It most commonly occurs with neurogenic and non-neurogenic voiding dysfunction or infravesical obstruction such as posterior urethral valves.`, 
        `<!--c. -->It may be due to acute infections, nephropathies, and other medical conditions that cause significant increases in urinary output that overwhelm maximal peristalsis.`, 
        `<!--d. -->It is diagnosed once reflux, obstruction, and secondary causes of dilatation are ruled out.`, 
        `None of the above.`],
        optionStyleType: `st-lower-alpha`,
        answer: [1],
        ansText:`Rationale: High bladder pressure might result in secondary reflux.`, 
        state: `notAnswered`,
        userAnswered: []
    ,
	type: `MCSS`        ,
        type: `MCSS`},
    {
        q: `<!--18. -->Which of the following is the most serious complication to ureteral tailoring?`,
        q2: ``,
        q3: [],
        option: [`<!--a. -->Gradual tapering can cause an abrupt change of the ureteral caliber and subsequently kinking.`, 
        `<!--b. -->A too short intravesical tunnel can cause vesicoureteral reflux.`, 
        `<!--c. -->Compromising of the distal vasculature of the ureter with subsequent fibrosis.`, 
        `<!--d. -->Secondary stenosis of the ureteral orifice.`, 
        `<!--e. -->Bladder dysfunction after intravesical dissection.`],
        optionStyleType: `st-lower-alpha`,
        answer: [2],
        ansText:`Rationale: Fibrosis can lead to recurrent obstruction and require redo surgery. However, when performed with care, the risk of vascular compromise should be minimal.`, 
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`}



];
