var quiz = [
    

    {
        q: `<!--1. -->A 5-year-old boy is seen in the office with complaints of intermittent right flank pain. There have been no episodes of nausea, vomiting, or fevers. He has 3+ blood on a urine dip. His physical exam reveals some mild right costovertebral angle (CVA) tenderness. Which imaging modality should be used first?`,
        q2: ``,
        q3: [],
        option: [`<!--a. -->Magnetic resonance imaging (MRI)`, 
        `<!--b. -->Plain radiograph, kidney-ureter-bladder (KUB)`, 
        `Ultrasound`, 
        `<!--d. -->Computed tomography (CT) scan`, 
        `<!--e. -->Retrograde pyelogram`],
        optionStyleType: `st-lower-alpha`,
        answer: [2],
        ansText:`Rationale: Ultrasound is the recommended initial diagnostic imaging study that should be obtained for suspected ureteral or renal stones.`, 
        state: `notAnswered`,
        userAnswered: []
    ,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`        ,
        type: `MCSS`},
    {
        q: `<!--2. -->A 12-year-old girl presented to the emergency department with an acute episode of left flank pain and was diagnosed with 5-mm left distal ureteral stone. She responded well to conservative therapy (intravenous hydration and pain medication) and her pain subsides. The next step in management is:`,
        q2: ``,
        q3: [],
        option: [`<!--a. -->analgesics, trial of passage, and interval ultrasound imaging.`, 
        `<!--b. -->analgesics, tamsulosin, trial of passage, and interval ultrasound imaging.`, 
        `ureteroscopy.`, 
        `<!--d. -->shock wave lithotripsy (SWL).`, 
        `<!--e. -->no further urologic management.`],
        optionStyleType: `st-lower-alpha`,
        answer: [1],
        ansText:`Rationale: <b>Given the size and location of the stone and the favorable clinical status of the patient, a trial of passage is indicated. Current evidence, although of low grade, supports use of medical expulsion therapy, namely tamsulosin 0.4 mg po daily. Interval ultrasound is indicated to ascertain stone passage. If the stone has not passed by 4 to 6 weeks, ureteroscopy is indicated.</b>`, 
        state: `notAnswered`,
        userAnswered: []
    ,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`        ,
        type: `MCSS`},
    {
        q: `<!--3. -->A 10-year-old male with spina bifida had an augmentation cystoplasty, bladder neck reconstruction, and bilateral Glenn-Anderson ureteral reimplantation for high-grade reflux at age 7 years. He now has a 1-cm lower pole stone. The therapy LEAST likely to yield an efficacious (stone-free) result is:`,
        q2: ``,
        q3: [],
        option: [`SWL.`, 
        `<!--b. -->ureteroscopy with laser lithotripsy.`, 
        `<!--c. -->ureteral stenting and ureteroscopy with laser lithotripsy 6 weeks later.`, 
        `<!--d. -->percutaneous nephrolithotomy (PCNL).`, 
        `<!--e. -->open pyelolithotomy.`],
        optionStyleType: `st-lower-alpha`,
        answer: [0],
        ansText:`Rationale: Recent data suggest that stone-free rates in children with a history of urologic condition or urinary tract reconstruction are quite low (12.5%) and may be better served with ureterorenoscopy or PCNL.`, 
        state: `notAnswered`,
        userAnswered: []
    ,
	type: `MCSS`,
	type: `MCSS`        ,
        type: `MCSS`},
    {
        q: `<!--4. -->With regard to SWL in the treatment of pediatric nephrolithiasis, treatment failures are associated with:`,
        q2: ``,
        q3: [],
        option: [`<!--a. -->large stone burden (i.e., ≥2 cm).`, 
        `<!--b. -->long infundibula.`, 
        `<!--c. -->infundibulopelvic angle greater than 45 degrees.`, 
        `<!--d. -->upper pole stone`, 
        `<!--e. -->a, b, and c.`],
        optionStyleType: `st-lower-alpha`,
        answer: [4],
        ansText:`Rationale: <b>SWL failure and retreatment rates were associated with increased mean stone burden, increased infundibular length, and infundibulopelvic angle greater than 45 degrees.</b>`, 
        state: `notAnswered`,
        userAnswered: []
    ,
	type: `MCSS`,
	type: `MCSS`        ,
        type: `MCSS`},
    {
        q: `<!--5. -->Complications that may occur during ureteroscopy while treating a ureteral stone include all EXCEPT:`,
        q2: ``,
        q3: [],
        option: [`hyponatremia.`, 
        `hypertension.`, 
        `<!--c. -->ureteral avulsion.`, 
        `hypothermia.`, 
        `<!--e. -->ureteral false passage.`],
        optionStyleType: `st-lower-alpha`,
        answer: [1],
        ansText:`Rationale: <b>Complications of ureteroscopy include unrecognized ureteral injury including mucosal flaps and tears, perforation, false passage, and partial to complete avulsion. Irrigating fluid, which may be used under pressure, should be isotonic and body temperature to avoid hypothermia and hyponatremia.</b> Hypertension is not a recognized complication of ureteroscopy.`, 
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `<!--6. -->A 9-year-old female with cystinuria is found to have a right 2-cm renal pelvic stone. The treatment option that would provide the highest probability of stone clearance is:`,
        q2: ``,
        q3: [],
        option: [`SWL.`, 
        `<!--b. -->ureteroscopy with laser lithotripsy and stone basketing.`, 
        `<!--c. -->PCNL.`, 
        `<!--d. -->medical therapy with potassium citrate and tiopronin.`, 
        `<!--e. -->anatrophic nephrolithotomy.`],
        optionStyleType: `st-lower-alpha`,
        answer: [2],
        ansText:`Rationale: Stone clearance for this 2-cm stone would be highest with a PCNL. Although ureteroscopy is an option, multiple sessions would most likely be required. Clearance of <b>cystine stones is poor for SWL.</b> Medical therapy helps to prevent cystine stones, not treat them. Anatrophic nephrolithotomy is not an appropriate surgical treatment for this stone.`, 
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `<!--7. -->Which of the following urinary findings are the least commonly observed in children with renal calculi?`,
        q2: ``,
        q3: [],
        option: [`<!--a. -->High urine sodium content`, 
        `Hypocitraturia`, 
        `Hyperuricosuria`, 
        `Hypercalciuria`, 
        `<!--e. -->Low urine volume`],
        optionStyleType: `st-lower-alpha`,
        answer: [2],
        ansText:`Rationale: Although uric acid nephrolithiasis and hyperuricosuria are relatively common in adults, they are relatively rare in childhood, accounting for &lt; 5% of all renal calculi. Low urine volume, high urine sodium content, hypercalciuria, and hypocitraturia are commonly observed in pediatric stone formers.`, 
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `<!--8. -->Which of the following interventions is NOT recommended for the treatment of cystinuria?`,
        q2: ``,
        q3: [],
        option: [`<!--a. -->D-penicillamine`, 
        `<!--b. -->Potassium citrate`, 
        `<!--c. -->Alpha-mercaptopropionylglycine`, 
        `<!--d. -->High fluid intake`, 
        `<!--e. -->Hydrochlorothiazide`],
        optionStyleType: `st-lower-alpha`,
        answer: [4],
        ansText:`Rationale: D-penicillamine and alpha-mercaptopropionylglycine are thiol-containing medications that are used to treat cystinuria by increasing the urine solubility of cysteine. Potassium citrate is used to treat cystinuria by alkalizing the urine thereby increasing cysteine solubility if a pH of greater than 7.0 is maintained. High fluid intake is generally recommended to prevent urinary crystallization of all lithogenic substrates. Thiazide diuretics are generally used to treat hypercalciuria, which is not an expected feature in cystinuria.`, 
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `<!--9. -->Which of the following is generally NOT associated with normocalcemic hypercalciuria?`,
        q2: ``,
        q3: [],
        option: [`<!--a. -->Bartter syndrome`, 
        `<!--b. -->Primary hyperparathyroidism`, 
        `<!--c. -->Dent disease`, 
        `<!--d. -->Distal renal tubular acidosis (DRTA)`, 
        `<!--e. -->Idiopathic hypercalciuria`],
        optionStyleType: `st-lower-alpha`,
        answer: [1],
        ansText:`Rationale: Primary hyperparathyroidism is generally, although not universally, associated with hypercalcemia and hypophosphatemia. Bartter syndrome, Dent disease, and dRTA are genetic conditions in which the serum calcium is normal. By definition, idiopathic hypercalciuria is always associated with normal serum calcium levels.`, 
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `<!--10. -->Which of the following medications are NOT typically associated with renal calculi or nephrocalcinosis?`,
        q2: ``,
        q3: [],
        option: [`<!--a. -->Levetiracetam`, 
        `Topiramate`, 
        `Indinavir`, 
        `Furosemide`, 
        `Acetazolamide`],
        optionStyleType: `st-lower-alpha`,
        answer: [0],
        ansText:`Rationale: Topiramate and acetazolamide are both carbonic anhydrase inhibitors and are commonly associated with hypocitraturia and calcium phosphate stone formation. Loop diuretics such as furosemide promote hypercalciuria and chronic usage is frequently associated with nephrocalcinosis. Indinavir is a protease inhibitor with poor urinary solubility and has the ability to crystallize and form calculi. Levetiracetam is an antiepileptic medication which is not associated with renal calculi.`, 
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`}



];
