var quiz = [
    

    {
        q: `<!--1. -->Which of the following statements is TRUE about <i>SRY</i> (sex-determining region of the Y-chromosome gene)?`,
        q2: ``,
        q3: [],
        option: [`<!--a. -->It is synonymous with the H-Y antigen.`, 
        `<!--b. -->SRY protein has a characteristic high-mobility group (HMG), DNA-binding domain.`, 
        `<!--c. -->It is regulated by SOX9 expression.`, 
        `<!--d. -->It was genetically mapped by the study of patients with Klinefelter and Turner syndromes.`, 
        `<!--e. -->It is synonymous with Zfy in humans.`],
        optionStyleType: `st-lower-alpha`,
        answer: [1],
        ansText:`Rationale: This domain can induce significant DNA bending when bound to the regulatory regions of target genes. <b><i>SRY</i></b> is not synonymous with H-Y antigen. The <i><b>SRY</b></i> gene is located on the short arm of the Y chromosome adjacent to the pseudoautosomal boundary. SRY regulates SOX9 expression during gonadal differentiation.`, 
        state: `notAnswered`,
        userAnswered: []
    ,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`        ,
        type: `MCSS`},
    {
        q: `<!--2. -->Which statement about steroidogenic factor 1 (SF1) is correct?`,
        q2: ``,
        q3: [],
        option: [`<!--a. -->The gene encodes a nuclear hormone transcription factor.`, 
        `<!--b. -->It regulates the expression of anti-Müllerian hormone.`, 
        `<!--c. -->It regulates the expression of enzymes involved in steroid production.`, 
        `<!--d. -->Mutations in the gene are associated with undervirilization.`, 
        `<!--e. -->All of the above are true.`],
        optionStyleType: `st-lower-alpha`,
        answer: [4],
        ansText:`Rationale: The expressed SF1 protein is a nuclear hormone transcription factor that binds to DNA. Several studies have demonstrated that SF1 regulates the transcription of AMH and multiple steroidogenic enzyme genes. Recent studies suggest that mutations in <b><i>SF1</i></b>, also known as <b><i>NR5A1</i></b>, have an additional role in DSD and are associated with varying levels of undervirilization, adrenal insufficiency, and gonadal dysgenesis.`, 
        state: `notAnswered`,
        userAnswered: []
    ,
	type: `MCSS`        ,
        type: `MCSS`},
    {
        q: `<!--3. -->Which of the following statements is TRUE regarding anti-Müllerian-hormone (AMH)?`,
        q2: ``,
        q3: [],
        option: [`<!--a. -->It acts systemically to produce Müllerian regression.`, 
        `<!--b. -->It is secreted by the fetal Leydig cells.`, 
        `<!--c. -->It functions normally in patients with hernia uteri inguinale.`, 
        `<!--d. -->It is secreted at 7 to 8 weeks of gestation, representing the initial endocrine function of the fetal testis.`, 
        `<!--e. -->It is secreted by the fetal testis at 10 weeks of gestation, after testosterone production has begun.`],
        optionStyleType: `st-lower-alpha`,
        answer: [3],
        ansText:`Rationale: AMH is produced by the Sertoli cells and acts in a paracrine fashion to induce regression of Müllerian structures. Hernia uteri inguinale, also known as persistent Müllerian duct syndrome (PMDS), occurs in patients with a 46, XY karyotype and normal male external genitalia. These patients have persistent internal Müllerian duct structures that may herniate or be associated with an undescended testicle.`, 
        state: `notAnswered`,
        userAnswered: []
    ,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`        ,
        type: `MCSS`},
    {
        q: `<!--4. -->Which description of <i>WT1</i> is correct?`,
        q2: ``,
        q3: [],
        option: [`<!--a. -->Mutations in WT1 can result in either Denys-Drash or Frasier syndrome.`, 
        `<!--b. -->Mutations in WT1 are associated with adrenocortical carcinoma.`, 
        `<!--c. -->Loss of WT1 function has not been associated with genitourinary anomalies.`, 
        `<!--d. -->Duplication of WT1 has been associated with dosage-sensitive sex reversal.`, 
        `<!--e. -->The gene was originally isolated in cloning experiments and localized to the X chromosome.`],
        optionStyleType: `st-lower-alpha`,
        answer: [0],
        ansText:`Rationale:  Denys-Drash syndrome is characterized by a triad of Wilms tumor, congenital nephropathy, and genital atypia or Difference of Sex Development (DSD). Frasier syndrome is associated with gonadoblastoma, congenital nephropathy, and gonadal dysgenesis. Patients with Frasier syndrome do not have a known predisposition to Wilms tumor. The <b><i>WT1</i></b> gene is located on chromosome 11 and is not associated with dosage-sensitive sex reversal.`, 
        state: `notAnswered`,
        userAnswered: []
    ,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`        ,
        type: `MCSS`},
    {
        q: `<!--5. -->Which of the following statements is TRUE regarding fetal testosterone?`,
        q2: ``,
        q3: [],
        option: [`<!--a. -->It causes regression of the Müllerian ducts.`, 
        `<!--b. -->It is produced primarily by the adrenal gland.`, 
        `<!--c. -->It acts locally to virilize the urogenital sinus and genital tubercle.`, 
        `<!--d. -->It acts locally to virilize the internal Wolffian duct structures.`, 
        `<!--e. -->It enters target tissue by active diffusion.`],
        optionStyleType: `st-lower-alpha`,
        answer: [3],
        ansText:`Rationale: Androgens are essential for virilization of Wolffian duct structures, the urogenital sinus, and genital tubercle. Testosterone, the major androgen secreted by the testes, enters target tissues by passive diffusion. The local production and paracrine effect of androgen is important for Wolffian duct development, which does not occur if testosterone is supplied only via the peripheral circulation. Masculinization of the external genitalia results from systemic delivery of testosterone and local conversion to DHT.`, 
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `<!--6. -->Which of the following statements is TRUE regarding dihydrotestosterone (DHT)?`,
        q2: ``,
        q3: [],
        option: [`<!--a. -->It produces virilization of Wolffian duct structures.`, 
        `<!--b. -->It is converted by 5α-reductase to testosterone in the liver.`, 
        `<!--c. -->It induces virilization of the urogenital sinus.`, 
        `<!--d. -->It acts locally to produce regression of Müllerian structures.`, 
        `<!--e. -->It is secreted in large quantities by the fetal testis.`],
        optionStyleType: `st-lower-alpha`,
        answer: [3],
        ansText:`Rationale: In some cells, such as those in the urogenital sinus, testosterone is converted to DHT by intracellular 5α-reductase. Testosterone or DHT then binds to a high-affinity intracellular receptor protein, and this complex enters the nucleus, where it binds to acceptor sites on DNA, resulting in target gene activation and protein synthesis. <b>Therefore, in tissues equipped with 5α-reductase at the time of sexual differentiation, such as prostate, urogenital sinus, and external genitalia, DHT is the active androgen.</b>`, 
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `<!--7. -->Which of the following statements is TRUE regarding patients with Klinefelter syndrome?`,
        q2: ``,
        q3: [],
        option: [`<!--a. -->They have at least one X and two Y chromosomes.`, 
        `<!--b. -->They are at increased risk for development of adenocarcinoma of the breast.`, 
        `<!--c. -->They undergo replacement of Leydig cells with hyaline.`, 
        `<!--d. -->They are normally fertile.`, 
        `<!--e. -->They bear little resemblance to XX males.`],
        optionStyleType: `st-lower-alpha`,
        answer: [1],
        ansText:`Rationale:  Gynecomastia, which can be quite marked, is a common pubertal development in patients with Klinefelter syndrome. As a result, these patients are at <b>eight times the risk for developing breast carcinoma</b> relative to normal males. Males with Klinefelter syndrome have one Y chromosome and at least two X chromosomes. The most common karyotype is 47, XXY. The cells lining the seminiferous tubules undergo replacement with hyaline during pubertal development.`, 
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `<!--8. -->The streak gonad of Turner syndrome:`,
        q2: ``,
        q3: [],
        option: [`<!--a. -->can descend to the scrotum.`, 
        `<!--b. -->has a reduced number of oocytes.`, 
        `<!--c. -->results in increased risk for development of seminoma since only one X chromosome is present.`, 
        `<!--d. -->results in increased risk for development of gonadoblastoma when Y chromosome elements are present.`, 
        `<!--e. -->is located in the round ligament.`],
        optionStyleType: `st-lower-alpha`,
        answer: [3],
        ansText:`Rationale: In patients with occult Y chromosome material, the risk of gonadoblastoma, an <b><i>in situ</i></b> germ cell cancer, is approximately 30%. The streak gonad is usually abdominal in location, hypoplastic, and predominantly composed of fibrous tissue.`, 
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `<!--9. -->Which of the following statements is TRUE regarding patients with 46, XY complete gonadal dysgenesis?`,
        q2: ``,
        q3: [],
        option: [`<!--a. -->They frequently have chromosomal anomalies.`, 
        `<!--b. -->They are at significant risk for gonadal tumors.`, 
        `<!--c. -->They have somatic defects similar to Turner syndrome.`, 
        `<!--d. -->They have gonadal histology different from that of patients with Turner syndrome.`, 
        `<!--e. -->They derive similar benefit from synthetic growth hormone as do patients with Turner syndrome.`],
        optionStyleType: `st-lower-alpha`,
        answer: [1],
        ansText:`Rationale: Up to 35% develop tumors by 30 years of age. Patients with 46,XX complete gonadal dysgenesis are closely related to those with Turner syndrome. But, they do not have somatic defects associated with Turner syndrome (e.g., broad chest, neck webbing, cardiac and renal anomalies, and short stature).`, 
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `<!--10. -->What is the most common finding in ALL cases of Denys-Drash syndrome?`,
        q2: ``,
        q3: [],
        option: [`Gonadoblastoma`, 
        `<!--b. -->Nephropathy with early-onset proteinuria`, 
        `<!--c. -->Wilms tumor`, 
        `<!--d. -->Calyceal blunting`, 
        `<!--e. -->Progressive renal failure`],
        optionStyleType: `st-lower-alpha`,
        answer: [1],
        ansText:`Rationale: The full triad of the syndrome includes nephropathy, characterized by the early onset of proteinuria, hypertension, and progressive renal failure in the majority, Wilms tumor, and DSD. Denys-Drash is caused by mutations in the Wilms tumor suppressor (<b><i>WT1</i></b>) gene. Because incomplete forms of the syndrome may occur, the nephropathy aspect is regarded as the common denominator of the syndrome.`, 
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `<!--11. -->Which of the following statements is TRUE regarding patients with embryonic testicular regression or bilateral vanishing testes syndromes?`,
        q2: ``,
        q3: [],
        option: [`<!--a. -->They have normal testosterone and elevated estradiol levels.`, 
        `<!--b. -->They have normal testosterone but decreased DHT levels.`, 
        `<!--c. -->They have castrate testosterone and elevated gonadotropin levels.`, 
        `<!--d. -->They have castrate testosterone and decreased gonadotropin levels.`, 
        `<!--e. -->They have normal follicle-stimulating hormone but decreased luteinizing hormone levels.`],
        optionStyleType: `st-lower-alpha`,
        answer: [2],
        ansText:`Rationale: The diagnosis can be made on the basis of a 46,XY karyotype and castrate levels of testosterone, despite persistently elevated serum luteinizing hormone and follicle-stimulating hormone levels. This can be detected during “mini-puberty” from 2 to 6 months of age. Serum AMH is a useful marker to detect the presence of testicular tissue and is undetectable in these males.`, 
        state: `notAnswered`,
        userAnswered: []
    ,
	type: `MCSS`,
	type: `MCSS`        ,
        type: `MCSS`},
    {
        q: `<!--12. -->Which of the following statements is TRUE regarding the ovotestis in ovotesticular DSD?`,
        q2: ``,
        q3: [],
        option: [`<!--a. -->It cannot descend from the retroperitoneum.`, 
        `<!--b. -->It is found in the minority of patients.`, 
        `<!--c. -->It can be unilateral or bilateral.`, 
        `<!--d. -->It has testicular and ovarian elements randomly distributed.`, 
        `<!--e. -->It is impossible to cleave surgically.`],
        optionStyleType: `st-lower-alpha`,
        answer: [2],
        ansText:`Rationale: Ovotesticular DSD patients are individuals having both testicular tissue with well-developed seminiferous tubules and ovarian tissue with primordial follicles. The gonads may take the form of one ovary and one testis or, more commonly, one or two ovotestes. Histopathology of the ovotestis will typically demonstrate well-developed ovarian tissue and a dysgenetic testicular component. The ovotestis may be located at any point along the path of testicular descent. Ovotestes with bipolar distribution of tissue may often be surgically separated.`, 
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `<!--13. -->An important consideration for gender assignment in the ovotesticular DSD patient is:`,
        q2: ``,
        q3: [],
        option: [`<!--a. -->the potential for fertility.`, 
        `<!--b. -->the impossibility of precisely dividing an ovotestis surgically.`, 
        `<!--c. -->the high incidence of gonadal tumors in 46, XX ovotesticular DSD.`, 
        `<!--d. -->the familial pattern of inheritance of the disorder.`, 
        `<!--e. -->androgen insensitivity.`],
        optionStyleType: `st-lower-alpha`,
        answer: [0],
        ansText:`Rationale: The most important aspect of management in ovotesticular DSD is gender assignment. An important factor to consider is the potential for fertility since individuals with ovotesticular DSD have the potential for fertility if raised as female with the appropriate ductal structures. Pregnancies have been reported in these women. Testicular tissue in an ovotestes is commonly dysgenetic. Approximately 3% of patients with 46, XY ovotesticular DSD develop gonadal tumors. Tumors are rare in patients with 46, XX ovotesticular DSD.`, 
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `<!--14. -->Which of the following statements is TRUE regarding the 21-hydroxylase deficiency in congenital adrenal hyperplasia (CAH)?`,
        q2: ``,
        q3: [],
        option: [`<!--a. -->It accounts for 50% of CAH cases.`, 
        `<!--b. -->It occurs as a result of <i>CYP21A</i> inactivation in the majority of cases.`, 
        `<!--c. -->It occurs with simple virilization in 75% of cases and salt wasting in 25% of cases.`, 
        `<!--d. -->It occurs with a predictable phenotype.`, 
        `<!--e. -->It is transmitted in an autosomal dominant pattern.`],
        optionStyleType: `st-lower-alpha`,
        answer: [1],
        ansText:`Rationale: 21-Hydroxylase deficiency accounts for 95% of CAH cases, with 75% of patients presenting with salt wasting and 25% with simple virilization. Mutations leading to gene conversion of the active <b><i>CYP21A2</i></b> gene into the inactive gene occur in 65% to 90% of cases of the classic disorder (salt wasting and simple virilizing) and all cases of nonclassic 21-hydroxylase deficiency. 21-hydroxylase deficiency is transmitted in an autosomal recessive pattern.`, 
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `<!--15. -->Prenatal treatment of fetuses with CAH using dexamethasone:`,
        q2: ``,
        q3: [],
        option: [`<!--a. -->is appropriate therapy in the majority of at-risk fetuses.`, 
        `<!--b. -->can be initiated after a diagnosis of CAH is confirmed by amniocentesis.`, 
        `<!--c. -->is of no risk to the fetus.`, 
        `<!--d. -->has been demonstrated to be effective.`, 
        `<!--e. -->acts by suppressing maternal ACTH.`],
        optionStyleType: `st-lower-alpha`,
        answer: [3],
        ansText:`Rationale: Treatment should be initiated before 9 weeks after the last menstrual period, once pregnancy is confirmed. A number of series have established the effectiveness of prenatal treatment of CAH with dexamethasone, which suppresses fetal secretion of adrenocorticotropic hormone. <b>However, a diagnosis of CAH cannot be confirmed before therapy is initiated because the diagnosis is usually made by chorionic villus sampling (9 to 11 weeks gestation) or amniocentesis (16 to 17 weeks gestation). Therefore, if treatment is initiated for all at-risk fetuses, the majority (seven out of eight) may be treated unnecessarily before confirmatory diagnosis.</b> Noninvasive prenatal diagnosis of CAH using cell-free fetal DNA obtained from maternal plasma is a promising new development that may allow identification of male fetuses, who would not benefit from treatment, well before 9 weeks gestation.`, 
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `<!--16. -->Which of the following statements is TRUE regarding enzymatic disorders of testosterone biosynthesis?`,
        q2: ``,
        q3: [],
        option: [`<!--a. -->They are transmitted in an autosomal dominant pattern.`, 
        `<!--b. -->They are associated with persistent Müllerian structures.`, 
        `<!--c. -->They appear clinically with a predictable phenotype.`, 
        `<!--d. -->They may involve impaired glucocorticoid and mineralocorticoid synthesis.`, 
        `<!--e. -->They may be associated with fertility.`],
        optionStyleType: `st-lower-alpha`,
        answer: [3],
        ansText:`Rationale: A defect in any of the five enzymes required for the conversion of cholesterol to testosterone can cause incomplete (or absent) virilization of the male fetus during embryogenesis. The first three enzymes (cholesterol side chain cleavage enzyme, 3β-hydroxysteroid dehydrogenase, and 17α-hydroxylase) are present in both the adrenals and the testes. Therefore, their deficiency results in impaired synthesis of glucocorticoids and mineralocorticoids in addition to testosterone. These enzymatic disorders are transmitted in an autosomal recessive pattern and appear clinically with a variable phenotype. Since testosterone biosynthesis is impacted, high concentration of testosterone within the testes is absent thus impacting spermatogenesis and fertility.`, 
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `<!--17. -->Which of the following statements is TRUE regarding patients with complete androgen insensitivity?`,
        q2: ``,
        q3: [],
        option: [`<!--a. -->They are typically raised as female.`, 
        `<!--b. -->They have normal Wolffian duct structures.`, 
        `<!--c. -->They have persistent Müllerian duct structures.`, 
        `<!--d. -->They should undergo orchiectomy as early as possible.`, 
        `<!--e. -->They have a 2% incidence of inguinal hernia.`],
        optionStyleType: `st-lower-alpha`,
        answer: [0],
        ansText:`Rationale: It is of great interest that, currently, all studies of patients with complete androgen insensitivity support an unequivocal female gender identity, consistent with androgen resistance of brain tissue as well. To date there has been only one report of a patient raised as a female who needed gender reassignment to male.<a href="[remark:bc8d47facbc4488284746c0068c33c8f]"><sup>a</sup></a>`, 
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `<!--18. -->Partial androgen insensitivity syndrome is characterized as:`,
        q2: ``,
        q3: [],
        option: [`<!--a. -->a group of defects in testosterone biosynthesis.`, 
        `<!--b. -->a form of 5α-reductase deficiency.`, 
        `<!--c. -->Y-chromosome mutations.`, 
        `<!--d. -->a disorder of androgen receptor quantity or function.`, 
        `<!--e. -->a disorder transmitted in an autosomal recessive manner`],
        optionStyleType: `st-lower-alpha`,
        answer: [3],
        ansText:`Rationale: Androgen receptor studies in cultured fibroblasts have demonstrated two forms of receptor defect in the partial androgen insensitivity syndrome. These include a reduced number of normally functioning androgen receptors and normal receptor number but decreased binding affinity. The androgen receptor gene is located on the long arm of the X chromosome, Xq12. Partial androgen resistance is, therefore, an X-linked disorder of incomplete masculinization.`, 
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `<!--19. -->Which of the following statements is TRUE regarding patients with 5α-reductase deficiency?`,
        q2: ``,
        q3: [],
        option: [`<!--a. -->Patients with a 46,XY karyotype are always infertile.`, 
        `<!--b. -->Isoenzymes 1 and 2 are abnormal.`, 
        `<!--c. -->Serum testosterone levels are normal, but there is a decreased testosterone/DHT ratio.`, 
        `<!--d. -->Masculinization occurs at puberty.`, 
        `<!--e. -->Prostatic enlargement occurs at puberty.`],
        optionStyleType: `st-lower-alpha`,
        answer: [3],
        ansText:`Rationale:  At puberty, partial masculinization occurs with an increase in muscle mass, development of male body habitus, increase in phallic size, and onset of erections. However, prostatic enlargement does not occur as this is dependent on DHT production. <b>The type 2 isoenzyme is affected in patients with 5α-reductase deficiency, resulting in an increased testosterone/DHT ratio owing to a reduced testosterone-to-DHT conversion rate.</b> There are reports of sperm production and fertility in some affected individuals.`, 
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `<!--20. -->Which of the following statements is TRUE regarding patients with persistent Müllerian duct syndrome?`,
        q2: ``,
        q3: [],
        option: [`<!--a. -->They have absent Wolffian duct structures.`, 
        `<!--b. -->They represent a homogeneous disorder of involving the AMH receptor.`, 
        `<!--c. -->They should undergo routine removal of Müllerian structures.`, 
        `<!--d. -->They experience a high incidence of transverse testicular ectopia.`, 
        `<!--e. -->They are uniformly infertile.`],
        optionStyleType: `st-lower-alpha`,
        answer: [3],
        ansText:`Rationale: Persistent Müllerian duct syndrome is thought to be etiologically important in transverse testicular ectopia, occurring in 30% to 50% of cases. Aberrant AMH function may be secondary to defects in the gene for AMH or for the AMH receptor. Individuals with a 46, XY karyotype develop Wolffian duct structures normally and may have impaired spermatogenesis associated with undescended testes.`, 
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `<!--21. -->Which of the following statements is TRUE regarding Mayer-Rokitansky-Küster-Hauser (MRKH) syndrome?`,
        q2: ``,
        q3: [],
        option: [`<!--a. -->It presents most commonly as infertility.`, 
        `<!--b. -->It is a homogeneous disorder entailing congenital absence of the uterus and vagina.`, 
        `<!--c. -->It is associated with a spectrum of ovarian abnormalities.`, 
        `<!--d. -->It has associated upper urinary tract anomalies, more frequently with the atypical disorder.`, 
        `<!--e. -->It is associated with persistent Wolffian duct structures.`],
        optionStyleType: `st-lower-alpha`,
        answer: [3],
        ansText:`Rationale: MRKH syndrome is a rare congenital disorder associated with absence of the uterus and vagina (typical variant). Patients commonly present with primary amenorrhea. The atypical form of MRKH syndrome (10% of cases) includes patients with uterine remnants and/or aplasia of one or both fallopian tubes. Urinary tract anomalies occur more commonly in patients with the atypical form of the disorder.`, 
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `<!--22. -->In a neonate with hypospadias and a unilateral cryptorchid testis:`,
        q2: ``,
        q3: [],
        option: [`<!--a. -->midshaft location of the urethral meatus is an important risk factor for DSD.`, 
        `<!--b. -->impalpability of the cryptorchid testis carries a 50% risk of a DSD.`, 
        `<!--c. -->palpability of the cryptorchid testis effectively rules out DSD.`, 
        `<!--d. -->perineal hypospadias is not a risk factor for a DSD.`, 
        `<!--e. -->difference in tissue texture of the poles of the cryptorchid gonad is suggestive of tumor.`],
        optionStyleType: `st-lower-alpha`,
        answer: [1],
        ansText:`Rationale: With hypospadias and either unilateral or bilateral cryptorchidism, the incidence of a DSD is 30% overall, 15% if the undescended testis is palpable, and 50% if it is impalpable.`, 
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `<!--23. -->Gender identity:`,
        q2: ``,
        q3: [],
        option: [`<!--a. -->is synonymous with gender role.`, 
        `<!--b. -->is primarily determined by prenatal exposure to androgens.`, 
        `<!--c. -->is primarily determined by postnatal environmental influences.`, 
        `<!--d. -->is defined as the identification of self as either male or female.`, 
        `<!--e. -->does not play a role in gender dysphoria.`],
        optionStyleType: `st-lower-alpha`,
        answer: [3],
        ansText:`Rationale: Gender role refers to aspects of behavior that distinguish males and females. The development of gender identity is poorly understood, but is influenced by prenatal and postnatal factors. Individual conflicts with gender identity are central to the concept of gender dysphoria.`, 
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`}




];
