var quiz = [
    

    {
        q: `<!--1. -->Hypospadias is typically made up of which of the following components?`,
        q2: ``,
        q3: [],
        option: [`<!--a. -->A high risk of associated anomalies outside of the genitourinary tract`, 
        `<!--b. -->Ventral penile curvature with an orthotopic urethral meatus`, 
        `<!--c. -->An intact prepuce`, 
        `<!--d. -->An ectopic location to the urethral meatus below the center of the glans`, 
        `<!--e. -->A bifid scrotum`],
        optionStyleType: `st-lower-alpha`,
        answer: [3],
        ansText:`Rationale: The vast majority of boys with hypospadias do not have anomalies outside of the genitourinary tract or a bifid scrotum, the latter of which is typically seen in proximal hypospadias, which occurs 10% of the time. Some boys will have ventral curvature with an orthotopic urethral meatus, but they have chordee without hypospadias and can typically be corrected without repair of the urethra.`, 
        state: `notAnswered`,
        userAnswered: []
    ,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`},
    {
        q: `<!--2. -->The level of hypospadias is typically defined by what parameter?`,
        q2: ``,
        q3: [],
        option: [`<!--a. -->At the initial office visit by identifying the location of the urethral meatus`, 
        `<!--b. -->By calculating the level of penile curvature in the office with a goniometer`, 
        `<!--c. -->Based on the location of the meatus when inserting a feeding tube in the operating room`, 
        `<!--d. -->After penile degloving, taking into account both the location of the urethral meatus and the degree of penile curvature`, 
        `<!--e. -->In the operating room by determining the degree of separation of the glans wings`],
        optionStyleType: `st-lower-alpha`,
        answer: [3],
        ansText:`Rationale: The traditional method of diagnosis and risk stratification was based on the location of the urethral meatus at the time of diagnosis. Based on a number of different variants, the most accurate assessment of the degree of hypospadias is based upon the location of the urethral meatus after penile degloving combined with an assessment of the degree of penile curvature. Taking note of glans separation, although part of the assessment, is present in the majority of boys with hypospadias, and is not thought to correlate with the degree of hypospadias.`, 
        state: `notAnswered`,
        userAnswered: []
    },
    {
        q: `<!--3. -->Which of the following is true about urethral development?`,
        q2: ``,
        q3: [],
        option: [`<!--a. -->The urethral groove forms between the urethral folds at an early stage in urethral development`, 
        `<!--b. -->The urethral folds fuse between gestation weeks 8 to 16 to form the urethra`, 
        `<!--c. -->Preputial skin folds fuse to complete the foreskin prior to fusion of the urethra`, 
        `<!--d. -->a and b`, 
        `b and c`],
        optionStyleType: `st-lower-alpha`,
        answer: [3],
        ansText:`Rationale: The urethral groove forms between the urethral folds and ultimately becomes the urethra. Preputial folds fuse as the urethra closes, in a dorsal to ventral fashion, hence the typical physical characteristics seen in hypospadias.`, 
        state: `notAnswered`,
        userAnswered: []
    },
    {
        q: `<!--4. -->Which of the following support the disruption of androgen signaling as at least a partial cause of hypospadias?`,
        q2: ``,
        q3: [],
        option: [`<!--a. -->A shorter anogenital distance (AGD) and severity of hypospadias`, 
        `<!--b. -->Increased rate of hypospadias development in boys conceived via in-vitro fertilization`, 
        `<!--c. -->An increased risk of hypospadias development in monozygotic male twins compared to singleton live male births`, 
        `<!--d. -->The concordance of rising rates of hypospadias, poor sperm quality, and cryptorchidism`, 
        `<!--e. -->All of the above`],
        optionStyleType: `st-lower-alpha`,
        answer: [4],
        ansText:`Rationale: A shorter AGD is thought to be secondary to exposure to environmental disrupting chemicals, currently theorized to inhibit the androgen cascade and penile development, resulting in hypospadias. The increased rate of hypospadias in twins and those boys conceived via in-vitro fertilization is thought, in part, to be secondary to hormone disruption. The testicular dysgenesis syndrome (TDS) includes several male reproductive developmental disorders, including poor sperm quality and rising rates of cryptorchidism and hypospadias, thought to be secondary to fetal exposure and resultant disruption of the normal androgen cascade during development, resulting in a life-long effect on these boys.`, 
        state: `notAnswered`,
        userAnswered: []
    ,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`},
    {
        q: `<!--5. -->An 8-month-old male presents for evaluation of subcoronal hypospadias. During physical examination, the left testicle is palpated in the groin but cannot be manipulated into the scrotum. The next step is to:`,
        q2: ``,
        q3: [],
        option: [`<!--a. -->reexamine in 6 months to allow for testicular descent.`, 
        `<!--b. -->perform ultrasonography to rule out testicular retraction.`, 
        `<!--c. -->obtain a karyotype.`, 
        `<!--d. -->schedule hypospadias repair now, and orchiopexy in 6 months.`, 
        `<!--e. -->schedule orchiopexy now, with hypospadias repair in 6 months.`],
        optionStyleType: `st-lower-alpha`,
        answer: [2],
        ansText:`Rationale: The combination of a penile anomaly with undescended testis may indicate a disorder of sex development. Although this is more commonly found with proximal hypospadias and a nonpalpable gonad, it is still advised to obtain a karyotype in any child with hypospadias and cryptorchidism.`, 
        state: `notAnswered`,
        userAnswered: []
    ,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`},
    {
        q: `<!--6. -->At the beginning of a penoscrotal hypospadias repair, after degloving but prior to urethral tubularization, you pass a urethral catheter but are unable to enter the bladder. The most likely cause is:`,
        q2: ``,
        q3: [],
        option: [`<!--a. -->a false passage in the posterior urethra.`, 
        `<!--b. -->an enlarged utricle.`, 
        `<!--c. -->partial urethral duplication ending in a blind pouch.`, 
        `<!--d. -->an elevated bladder neck.`, 
        `<!--e. -->proximal urethral stricture.`],
        optionStyleType: `st-lower-alpha`,
        answer: [1],
        ansText:`Rationale: The most common reason for difficulty with catheter placement during hypospadias repair is an enlarged utricle, which occurs more frequently in boys with more severe hypospadias. Urethral duplication is rare in boys with hypospadias and a high bladder neck is encountered often in boys with posterior urethral valves, not hypospadias.`, 
        state: `notAnswered`,
        userAnswered: []
    ,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`},
    {
        q: `<!--7. -->A 6-month-old infant without other known medical problems is referred for proximal penile hypospadias. He is also found to have ventral penile curvature, a deep scrotal cleft, and penoscrotal transposition, but both testes are normally situated in the dependent scrotum. The next step is:`,
        q2: ``,
        q3: [],
        option: [`<!--a. -->proceed with surgery.`, 
        `<!--b. -->obtain a karyotype.`, 
        `<!--c. -->order a voiding cystourethrogram (VCUG) to rule out the presence of a utricle.`, 
        `<!--d. -->obtain renal sonography to rule out a renal anomaly.`, 
        `<!--e. -->delay surgery until 12 months of age to allow for interval penile growth.`],
        optionStyleType: `st-lower-alpha`,
        answer: [0],
        ansText:`Rationale: Neither karyotyping nor urinary tract imaging is indicated for isolated hypospadias, even in patients with proximal defects. Associated renal anomalies are rare in nonsyndromic hypospadias. Karyotyping can be considered and offered to families with proximal hypospadias but is only strongly recommended in the setting of at least one undescended testicle. Delaying surgery will not significantly increase penile growth. If a utricle is encountered at the time of surgery maneuvers are taken to successfully place a catheter and removal at the time of primary hypospadias repair is not recommended.`, 
        state: `notAnswered`,
        userAnswered: []
    ,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`},
    {
        q: `<!--8. -->Which of the following is true regarding penile innervation?`,
        q2: ``,
        q3: [],
        option: [`<!--a. -->The pattern of penile innervation does not have a significant impact on the choice of technique for correction of penile curvature.`, 
        `<!--b. -->The nerve bundles remain as two well-defined structures on the dorsal aspect of the penis.`, 
        `<!--c. -->In hypospadias surgery, a perineal nerve block may provide a better option than a caudal block in an 8-year-old boy.`, 
        `<!--d. -->The pattern of innervation permits the safe use of dorsal plication techniques for orthoplasty, when the sutures are placed in the midline.`, 
        `<!--e. -->b and d.`,
        `<!--f. -->b, c, and d.`],
        optionStyleType: `st-lower-alpha`,
        answer: [5],
        ansText:`Rationale: The pattern of penile nerve innervation plays a critical role in management of penile curvature and must be completely understood prior to correction. The nerve bundles are present at the 11 and 1 o’clock positions on the dorsal penile shaft and can be avoided with midline suture placement. Perineal nerve block can be attempted in older, ambulatory patients who would not otherwise tolerate the temporary lower extremity paralysis after caudal blockade.`, 
        state: `notAnswered`,
        userAnswered: []
    ,
	type: `MCSS`},
    {
        q: `<!--9. -->Two years after a midshaft hypospadias repair a potty-trained 4-year-old boy presents with two febrile urinary tract infections (UTIs). Which of the following is the next step?`,
        q2: ``,
        q3: [],
        option: [`<!--a. -->Recommend that the boy sits to void`, 
        `<!--b. -->A VCUG`, 
        `<!--c. -->A daily cone enema`, 
        `<!--d. -->Cystoscopy under general anesthesia`, 
        `<!--e. -->Reassurance`],
        optionStyleType: `st-lower-alpha`,
        answer: [1],
        ansText:`Rationale: Recurrent UTIs after a hypospadias repair are a relatively rare event. Anatomic concerns including distal stricture, new onset vesicoureteral reflux, or incomplete voiding must be explored. Constipation may be contributing to the UTIs, but a cone enema is not recommended at this point. If an anomaly is seen on VCUG a cystoscopy should be considered. Sitting to void will not help this issue.`, 
        state: `notAnswered`,
        userAnswered: []
    },
    {
        q: `<!--10. -->A patient with penoscrotal hypospadias has 90 degrees of ventral curvature prior to making the initial incision. After the penis is fully degloved, artificial erection reveals residual curvature of 15 degrees. The best next step in correcting the curvature is:`,
        q2: ``,
        q3: [],
        option: [`<!--a. -->transection of the urethral plate.`, 
        `<!--b. -->perform dermal grafting of the corpora cavernosa at the point of maximal curvature and complete with a 2-stage repair.`, 
        `<!--c. -->proceed with urethroplasty.`, 
        `<!--d. -->perform a midline dorsal plication.`, 
        `<!--e. -->perform midline dorsal plication and ventral tunica vaginalis graft corporoplasty, then complete a single-stage urethroplasty repair.`],
        optionStyleType: `st-lower-alpha`,
        answer: [3],
        ansText:`Rationale: <b>Persistent penile curvature of less than 30 degrees after penile degloving can be straightened by a single dorsal plication without clinically apparent shortening of the penis.</b> Transection of the urethral plate and/or ventral corporal lengthening procedures are reserved for cases with curvature greater than 30 degrees after degloving and dartos dissection. In a boy with 15 degrees of ventral curvature, correction is recommended and proceeding with urethroplasty significantly increases the chance that an additional operation to correct curvature will be necessary in the future.`, 
        state: `notAnswered`,
        userAnswered: []
    },
    {
        q: `<!--11. -->A 6-month-old male is referred for hypospadias. On examination he is found to have a dorsally hooded prepuce, ventral penile curvature, a glanular meatus, and a normal scrotum. The parents should be informed that straightening the penile curvature most likely will require:`,
        q2: ``,
        q3: [],
        option: [`<!--a. -->skin degloving and ventral dartos dissection.`, 
        `<!--b. -->multiple dorsal midline plications.`, 
        `<!--c. -->ventral corporal grafting.`, 
        `<!--d. -->transection of the urethra.`, 
        `<!--e. -->single dorsal plication and ventral corporal graft.`],
        optionStyleType: `st-lower-alpha`,
        answer: [0],
        ansText:`Rationale: Most often penile curvature noted in so-called chordee without hypospadias is due to shortened ventral skin and dartos and so corrects as the penis is degloved and ventral dartos dissected. Multiple plications should be avoided, ventral corporal grafting is reserved for curvature greater than 30 degrees after degloving and ventral dartos dissection, and urethral transection for a shortened urethra is only rarely indicated in this condition.`, 
        state: `notAnswered`,
        userAnswered: []
    },
    {
        q: `<!--12. -->A 6-month-old male is referred for hypospadias. On examination he is found to have a dorsally hooded prepuce, 90 degrees of ventral penile curvature, a coronal meatus, and significant penoscrotal webbing. The parents should be counseled as follows:`,
        q2: ``,
        q3: [],
        option: [`<!--a. -->Penile curvature will likely be corrected with skin degloving and ventral dartos dissection.`, 
        `<!--b. -->The risk for hypospadias complication repair is 5%.`, 
        `<!--c. -->Only one procedure should be required.`, 
        `<!--d. -->A karyotype should be performed.`, 
        `<!--e. -->A two-stage repair may be required.`],
        optionStyleType: `st-lower-alpha`,
        answer: [4],
        ansText:`Rationale: Although difficult to fully assess in the office setting, a patient with significant curvature and penoscrotal webbing may be suggestive of a severely hypoplastic urethra with significant penile curvature that may require a 2-stage repair. Parent counseling at the time of the initial visit is a key component of setting expectations for surgical reconstruction. A patient with severe ventral curvature is unlikely to have a complication rate of 5% and most series suggest a total complication rate closer to 10% even for distal hypospadias. A karyotype is not necessary in isolated hypospadias.`, 
        state: `notAnswered`,
        userAnswered: []
    },
    {
        q: `<!--13. -->A 6-week-old infant is evaluated after newborn circumcision. The primary care physician expresses concern for a “bad circumcision.” On examination the meatus is coronal and the glans wings are separated. The meatus itself appears elongated with a deep groove. The parents report no excessive bleeding after the circumcision. There is no redundant shaft skin following the circumcision except in the ventral midline near the meatus. The family should be informed that:`,
        q2: ``,
        q3: [],
        option: [`<!--a. -->these findings indicate urethral injury during circumcision.`, 
        `<!--b. -->urethroplasty will best be performed using a ventral preputial skin flap.`, 
        `<!--c. -->circumcision most likely has affected vascularity to the redundant ventral skin, and so urethroplasty will best be done using the skin as a graft.`, 
        `<!--d. -->following circumcision, urethroplasty will require buccal graft from the lower lip.`, 
        `<!--e. -->their infant has a hypospadias variant.`],
        optionStyleType: `st-lower-alpha`,
        answer: [4],
        ansText:`Rationale: <b>The patient has megameatus intact prepuce (MIP) hypospadias variant, and urethroplasty is typically successful via tubularization of local skin flaps.</b> Preputial skin flaps or buccal grafts are typically not necessary. This is not secondary to a circumcision injury.`, 
        state: `notAnswered`,
        userAnswered: []
    },
    {
        q: `<!--14. -->The parents of a 6-month-old male with subcoronal hypospadias request foreskin reconstruction rather than circumcision. The parents should be informed that:`,
        q2: ``,
        q3: [],
     
        option: [`<!--a. -->preoperative testosterone therapy to enlarge the foreskin is recommended.`, 
        `<!--b. -->complication rates are significantly greater with prepucioplasty.`, 
        `<!--c. -->they should not retract the foreskin in the first 6 weeks after surgery.`, 
        `<!--d. -->a gentle compression dressing should be used to minimize preputial edema after surgery.`, 
        `<!--e. -->the foreskin most likely will be needed for urethroplasty and so circumcision will likely be necessary.`],
        optionStyleType: `st-lower-alpha`,
        answer: [2],
        ansText:`Rationale: Disruption of the reconstructed prepuce may result from attempts to retract the foreskin early after surgery, before edema subsides and the wound heals. Otherwise complication rates are similar between patients with distal hypospadias undergoing foreskin reconstruction versus circumcision. Dressings do not significantly affect postoperative edema. When a sufficient amount of redundant shaft skin is present prepucioplasty can be performed, but the repair should not be compromised in order to achieve this. Tunica vaginalis can be considered for secondary layer closure in these patients.`, 
        state: `notAnswered`,
        userAnswered: []
    },
    {
        q: `<!--15. -->Each of the following is thought to reduce the likelihood for fistula development after hypospadias surgery EXCEPT:`,
        q2: ``,
        q3: [],
        option: [`<!--a. -->subepithelial suturing of the neourethra.`, 
        `<!--b. -->2-layer closure of the neourethra.`, 
        `<!--c. -->use of monofilament sutures for urethroplasty.`, 
        `<!--d. -->approximation of the corpus spongiosum over the neourethra.`, 
        `<!--e. -->placement of a dartos flap over the neourethra.`],
        optionStyleType: `st-lower-alpha`,
        answer: [2],
        ansText:`Rationale: No study demonstrates outcomes are influenced by suture type, but technical modifications such as subepithelial suturing of the neourethra and additional layers of vascularized tissue are beneficial.`, 
        state: `notAnswered`,
        userAnswered: []
    },
    {
        q: `<!--16. -->A mother reports her 7-year-old child who had previously undergone a two-stage Byars flap hypospadias repair now has a prolonged urinary stream and significant dribbling from his meatus after voiding. All of the following are true EXCEPT:`,
        q2: ``,
        q3: [],
        option: [`<!--a. -->at the time of the repair local tissue can often be used to correct the problem.`, 
        `<!--b. -->he will have erectile dysfunction as an adult.`, 
        `<!--c. -->at the time of the repair the meatus should be calibrated to rule out a distal obstruction.`, 
        `<!--d. -->the patient may note a bulging or ballooning of the ventral penile shaft when voiding.`, 
        `<!--e. -->this complication can also occur in the setting of an island onlay flap repair.`],
        optionStyleType: `st-lower-alpha`,
        answer: [0],
        ansText:`Rationale: The history of a 2-stage Byars flap and a prolonged voiding time with significant dribbling suggests a urethral diverticulum. It can be repaired using the redundant tissue present within the diverticulum itself, as some of the tissue can be de-epithelialized and used for additional layers of vascularized closure. They are thought to occur in preputial onlay flaps as well as 2-stage Byars flap repairs due to the dispensability of the preputial skin.`, 
        state: `notAnswered`,
        userAnswered: []
    },
    {
        q: `<!--17. -->An 8-year-old had distal hypospadias repair as an infant. Initially after surgery he was thought to have a normal urinary stream, although the parents only rarely observed urination because he used diapers. During the past year the parents think his stream has slowed and notice he seems to have to “push” to empty his bladder. Examination reveals a faint white discoloration around the meatus that seems to extend deeper into the urethra. The most effective course of action includes:`,
        q2: ``,
        q3: [],
        option: [`<!--a. -->intraoperative biopsy with frozen section.`, 
        `<!--b. -->meatotomy for meatal stenosis.`, 
        `<!--c. -->flip-flap reoperative urethroplasty.`, 
        `<!--d. -->application of topical steroids for 6 weeks.`, 
        `<!--e. -->excision of the distal urethra with two-stage buccal graft urethroplasty.`],
        optionStyleType: `st-lower-alpha`,
        answer: [4],
        ansText:`Rationale: The history and physical findings suggest BXO. A biopsy in the operating room (OR) can be performed at the time of the procedure, but this is not a definitive process. Office biopsy is not recommended. <b>Meatotomy or skin flap repair of meatal stenosis most often fails in the presence of BXO, as residual BXO will progress into the reconstructed tissue. Given the extension of the suspected BXO into the urethra, a cystoscopy to determine proximal extent with subsequent excision of all tissues affected by BXO with staged buccal mucosa reconstruction is standard of care.</b> Topical steroids may be initially effective, but stenosis recurs when therapy ends, and BXO may extend proximally along the urethra to a level not reached by topical applications. In spite of replacement with buccal mucosa, these patients will still be at risk for recurrence and must be monitored closely.`, 
        state: `notAnswered`,
        userAnswered: []
    },
    {
        q: `<!--18. -->A 1-year-old boy had a subcoronal hypospadias repair 6 months ago but has a 2-mm fistula at the site of the original meatus. Distance from the fistula to the neomeatus is approximately 4 mm, and the glans wings still appear approximated. The meatus appears patent and the meatus is calibrated to 8Fr in the operating room. The best treatment of the fistula is:`,
        q2: ``,
        q3: [],
        option: [`<!--a. -->midline incision through the neomeatus to the fistula with reoperative distal urethroplasty.`, 
        `<!--b. -->rotational skin flap fistula closure.`, 
        `<!--c. -->primary fistula closure covered with a ventral dartos barrier flap.`, 
        `<!--d. -->inlay buccal graft urethroplasty.`, 
        `<!--e. -->insertion of urethral catheter to facilitate secondary closure.`],
        optionStyleType: `st-lower-alpha`,
        answer: [2],
        ansText:`Rationale: A fistula with good glans approximation usually can be primarily corrected with fistula closure followed by coverage with additional vascularized layers, in this case a Dartos barrier flap. In contrast, when the skin quality is thin and poor with separation of the glans wings in addition to a short distance between the neomeatus and the fistula, this is not recommended. Instead a reoperative distal urethroplasty/glansplasty should be performed, otherwise a high failure rate will follow. A rotational skin flap is not a good option in this case because it is necessary to dissect under the corona to completely free the fistula tract and advance a barrier flap. Although meatal stenosis has to be considered in any case with a fistula, appropriate therapy when it is present is reoperation, not dilations. Prolonged catheter insertion will not lead to fistula closure.`, 
        state: `notAnswered`,
        userAnswered: []
    },
    {
        q: `<!--19. -->A 10-year-old boy presents with midshaft hypospadias after seven prior operations on his penis. He appears to have ventral curvature greater than 30 degrees and has been circumcised. There is visible scarring between the meatus and the glans, and there appears to be significant penoscrotal webbing. The best surgical approach for him is:`,
        q2: ``,
        q3: [],
        option: [`<!--a. -->a redo tubularized incised plate (TIP) operation.`, 
        `<!--b. -->flip-flap reoperative urethroplasty.`, 
        `<!--c. -->island onlay flap reoperative urethroplasty.`, 
        `<!--d. -->inlay buccal graft urethroplasty.`, 
        `<!--e. -->two-stage buccal graft urethroplasty.`],
        optionStyleType: `st-lower-alpha`,
        answer: [4],
        ansText:`Rationale: <b>Visible scarring is a relative contraindication to TIP or flip-flap reoperations, as there is likely significant compromise of the blood supply to these tissues, which will result in a high failure rate. The penoscrotal webbing and curvature suggests that there is a lack of shaft skin, particularly on the ventral portion of the penis, which will limit the ability to perform an onlay procedure The best plan is to excise scarred tissues and perform a staged buccal graft urethroplasty.</b> The penile curvature must be assessed at the time of the repair to ensure that there is no residual curvature after the scar tissue is excised.`, 
        state: `notAnswered`,
        userAnswered: []
    },
    {
        q: `<!--20. -->A 6-year-old boy who had a tubularized preputial flap hypospadias repair as an infant presents with a slow urinary stream and stranguria worsening over the past year. Physical examination is unremarkable, but the peak flow is 3 mL/s with a postvoid residual of 75 mL (estimated bladder capacity of 240 mL). At surgery cystoscopy shows a 5-mm stricture near the original meatus. This stricture is best corrected by:`,
        q2: ``,
        q3: [],
        option: [`<!--a. -->urethral dilation.`, 
        `<!--b. -->direct vision internal urethrotomy (DVIU).`, 
        `<!--c. -->DVIU with CIC for 3 months.`, 
        `<!--d. -->inlay buccal urethroplasty.`, 
        `<!--e. -->staged buccal graft reoperation.`],
        optionStyleType: `st-lower-alpha`,
        answer: [3],
        ansText:`Rationale: <b>Distal urethral narrowing, particularly within the glans in which there is lack of normal expansion of the urethra, can lead to an elevated postvoid residual and slowed urinary stream. Direct vision internal urethrotomy (DVIU) has a long-term success less than 10% after TIP repairs, even when used in conjunction with clean intermittent catheterization (CIC).</b> The best treatment in this case is inlay grafting into the stricture and either a buccal mucosa graft or a piece of redundant dorsal shaft skin or inner preputial skin can be used for a dorsal inlay graft repair. If an inlay graft repair fails, a staged buccal graft repair would be required.`, 
        state: `notAnswered`,
        userAnswered: []
    },
    {
        q: `<!--21. -->A 9-year-old prepubertal boy has failed multiple prior operations for penoscrotal hypospadias. Examination shows a distal shaft meatus, persistent ventral curvature, and a flattened ventral glans. During planned two-stage buccal graft reoperation, it becomes apparent that the entire neourethra will have to be excised back to the penoscrotal junction. The best plan for first-stage grafting is to:`,
        q2: ``,
        q3: [],
        option: [`<!--a. -->use cheek buccal tissue on the penile shaft and maintain the current remnant prepuce within the glans.`, 
        `<!--b. -->use cheek buccal tissue to graft the entire defect.`, 
        `<!--c. -->use lower lip buccal tissue for the glans and cheek tissue on the penile shaft.`, 
        `<!--d. -->use lip buccal tissue on the penile shaft and cheek tissue within the glans.`, 
        `use ventral penile shaft skin to graft the entire defect.`],
        optionStyleType: `st-lower-alpha`,
        answer: [2],
        ansText:`Rationale: It is best to use lip tissue within the glans, because it is thinner than cheek tissue and results in less complications after glansplasty. Given the narrow and flat appearance of the glans and a history of multiple failed repairs, the skin with the glans is best excised to restore a deep groove that ultimately will result in a vertical meatus at the second stage. After multiple failed operations, redundant shaft skin sufficient for grafting and subsequent urethroplasty is not available.`, 
        state: `notAnswered`,
        userAnswered: []
    },
    {
        q: `<!--22. -->Preoperative androgen stimulation in patients with severe hypospadias has resulted in all of the following except:`,
        q2: ``,
        q3: [],
        option: [`<!--a. -->decreased penile size (compared to men without hypospadias) in adulthood.`, 
        `<!--b. -->increase in penile size including length and glans width.`, 
        `<!--c. -->hormonal levels that return to normal shortly after treatment is discontinued.`, 
        `<!--d. -->nonappreciable long-lasting side effects of treatment.`, 
        `<!--e. -->transient thin pubic hair.`],
        optionStyleType: `st-lower-alpha`,
        answer: [0],
        ansText:`Rationale: Preoperative androgen stimulation in prepubertal boys can transiently increase both the penile length and glans width. It is thought that a small glans width increases urethroplasty and glansplasty complications, therefore increasing the width of the glans at the time of closure is of some theoretical benefit. Several conflicting studies argue both sides of its use. Its side effects including increased frequency of erections, thin pubic hair, and increased aggression, all of which are transient after it is discontinued.`, 
        state: `notAnswered`,
        userAnswered: []
    },
    {
        q: `<!--23. -->Parents report that their 1-year-old boy seems to be having difficulty urinating 3 months after TIP repair for coronal hypospadias. They have observed the stream once or twice and thought it looked thin. On examination the glans looks normal, except that the meatus appears small. In the operating room you attempt to calibrate the meatus, and an 8-Fr sound will not pass. The most likely cause for this complication is:`,
        q2: ``,
        q3: [],
        option: [`<!--a. -->balanitis xerotica obliterans (BXO).`, 
        `<!--b. -->ischemia of the neomeatus.`, 
        `<!--c. -->postoperative edema of the meatus.`, 
        `<!--d. -->suturing the urethral plate too far into the distal glans.`, 
        `<!--e. -->prolonged urethral stent placement.`],
        optionStyleType: `st-lower-alpha`,
        answer: [3],
        ansText:`Rationale: <b>The most common cause of meatal stenosis after TIP is suturing the urethral plate too far distally.</b> The contour of the glans is such that this will narrow the distal portion of the meatus, causing stenosis and/or obstruction. BXO is unlikely early after surgery and often presents with white discoloration at the meatus. Ischemia is possible but unlikely, given the reliable vascularity of the urethral plate and glans tissues. Edema after surgery may slow the urinary stream, but at 3 months it should be resolved enough to not cause passage of a sound. Prolonged urethral stent placement does not cause obstruction.`, 
        state: `notAnswered`,
        userAnswered: []
    },
    {
        q: `<!--24. -->Parents report that their 1-year-old boy seems to be voiding without any problems 6 months after Thiersch-Duplay repair for coronal hypospadias, although they have not seen the actual urinary stream because he is still in diapers. On examination you observe that the meatus appears small. The next step is:`,
        q2: ``,
        q3: [],
        option: [`<!--a. -->calibrate the meatus.`, 
        `<!--b. -->obtain VCUG.`, 
        `<!--c. -->schedule examination under anesthesia and meatotomy.`, 
        `<!--d. -->recommend reoperative urethroplasty, using either a ventral flip-flap if possible, or inlay buccal grafting from the lip.`, 
        `<!--e. -->begin daily urethral dilations for 6 weeks.`],
        optionStyleType: `st-lower-alpha`,
        answer: [0],
        ansText:`Rationale: The meatus may appear small after Thiersch-Duplay urethroplasty without indicating meatal stenosis. Passage of an 8- or 10-Fr sound would suffice to determine if the meatus is stenotic or not, although this is extremely difficult in the office setting. Passage of a sound without anesthesia is only possible in a small number of patients, and even insertion of an 8-Fr feeding tube may be difficult in this population. A small-appearing meatus in an asymptomatic (UTI, stranguria, prolonged urinary stream) patient should not prompt immediate concern that examination under anesthesia or reoperation is needed. If symptoms are present an examination under anesthesia is recommended. If repair is indicated, the intervention of choice would depend upon the length of narrowing, the quality of the glans closure, and the assessment of the remainder of the urethroplasty.`, 
        state: `notAnswered`,
        userAnswered: []
    },
    {
        q: `<!--25. -->If not repaired, an isolated glanular hypospadias with no penile curvature and a normal caliber to the meatus will result in which of the following long-term issues?`,
        q2: ``,
        q3: [],
        option: [`<!--a. -->Difficulty with micturition`, 
        `<!--b. -->Inability to inseminate during sexual intercourse`, 
        `<!--c. -->Clinically significant meatal stenosis`, 
        `<!--d. -->Painful erections`, 
        `<!--e. -->None of the above`],
        optionStyleType: `st-lower-alpha`,
        answer: [4],
        ansText:`Rationale: In isolated hypospadias without any evidence of narrowing of the meatus, a glanular location, and no penile curvature, it is unlikely that significant morbidity would result for the patient. If penile curvature is noted, however, even with a mildly displaced meatus, surgical intervention would be warranted due to the potential for long-term sequelae.`, 
        state: `notAnswered`,
        userAnswered: []
    },
    {
        q: `<!--26. -->A 19-month-old male presents for evaluation of scrotal hypospadias. The mother has noted that his pupils seem enlarged, and she is concerned he might have developmental delay. He is crying during examination, hindering inspection of his eyes. He has scrotal hypospadias with a deep scrotal cleft, but both testes are in the scrotum. His evaluation before surgery should include:`,
        q2: ``,
        q3: [],
        option: [`<!--a. -->renal sonogram.`, 
        `<!--b. -->testicular sonogram.`, 
        `<!--c. -->VCUG.`, 
        `<!--d. -->assessment of testosterone/dihydrotestosterone (T/DHT) ratio.`, 
        `<!--e. -->measurement of anti-Müllerian hormone (AMH).`],
        optionStyleType: `st-lower-alpha`,
        answer: [0],
        ansText:`Rationale: The history suggests WAGR (Wilms tumor, Aniridia, Genital abnormalities, mental Retardation) syndrome, and so renal sonography is recommended because of the association with Wilms tumor.`, 
        state: `notAnswered`,
        userAnswered: []
    },
    {
        q: `<!--27. -->A 12-year-old boy had hypospadias reoperation 1 year ago that included a tunica vaginalis barrier flap over the neourethra harvested from the right testicle. He reports no problems voiding, but with erection the penis is pulled to the right side. The next step is to:`,
        q2: ``,
        q3: [],
        option: [`<!--a. -->reassure him the tension on his penis will resolve at puberty.`, 
        `<!--b. -->make a small scrotal incision and transect the tunica vaginalis flap.`, 
        `<!--c. -->make a midline penile incision and excise the tunica vaginalis flap.`, 
        `<!--d. -->create a tunica vaginalis flap from the left testis to evenly distribute the tension on the penis during erection.`, 
        `<!--e. -->instruct the patient to pull the penis toward the left during erection to relax contracted tissues.`],
        optionStyleType: `st-lower-alpha`,
        answer: [1],
        ansText:`Rationale: <b>Failure to dissect the tunica vaginalis flap to the external ring can result in traction on the penis during erection, deviating it toward the base of the flap.</b> The best therapy is to make a small scrotal incision over the flap and transect it. As this has occurred several years after his initial repair, this should not compromise the blood supply to the urethroplasty.`, 
        state: `notAnswered`,
        userAnswered: []
    },
    {
        q: `<!--28. -->A 14-year-old undergoes a first-stage buccal graft reoperation that involves grafting along the entire penile shaft. The next morning he is found to have visible hematoma under the shaft skin. The next step is:`,
        q2: ``,
        q3: [],
        option: [`<!--a. -->return immediately to the operating room to evacuate the hematoma.`, 
        `<!--b. -->apply a compression dressing over the penis and scrotum.`, 
        `<!--c. -->check coagulation profiles for bleeding diathesis.`, 
        `<!--d. -->observe with continued bed rest.`, 
        `<!--e. -->evacuate the hematoma and regraft the penile shaft.`],
        optionStyleType: `st-lower-alpha`,
        answer: [3],
        ansText:`Rationale: <b>Hematoma formation under buccal mucosa graft can compromise the take rate of the graft. Technical modifications including graft quilting and the tie-over compression dressing prevent blood from accumulating under the graft. Hematoma under adjacent penile skin and within the scrotum as described here will resolve with minimal effect upon the graft itself.</b> It is unlikely that a boy requiring a staged buccal graft repair has an undiagnosed coagulopathy following prior penile operations.`, 
        state: `notAnswered`,
        userAnswered: []
    },
    {
        q: `<!--29. -->A 6-month-old boy has proximal hypospadias. In the operating room, there is 50 degrees of ventral penile curvature after penile degloving and division of the urethral plate. All of the following are viable repair options EXCEPT:`,
        q2: ``,
        q3: [],
        option: [`<!--a. -->corporal grafting with a dermal graft and 2-stage Byars flap repair.`, 
        `<!--b. -->2-stage STAG (staged tubularized autograft) repair with ventral corporotomies.`, 
        `single-stage repair with tunica vaginalis graft corporotomy followed by Duckett tube.`, 
        `single-stage repair with dorsal plication and island onlay urethroplasty.`, 
        `none of the above.`],
        optionStyleType: `st-lower-alpha`,
        answer: [3],
        ansText:`Rationale: In a boy with severe ventral curvature after penile degloving and division of the urethral plate (50 degrees in this case), a two-stage repair should be performed. A corporal lengthening procedure should be performed, and dermal graft, corporotomies, and tunica vaginalis flap are all viable options. Dorsal plication would put the boy at risk for recurrent penile curvature long term.`, 
        state: `notAnswered`,
        userAnswered: []
    },
    {
        q: `<!--30. -->For hypospadias complication repairs, all of the following are true EXCEPT:`,
        q2: ``,
        q3: [],
        option: [`<!--a. -->a coronal fistula with a thin glans should be repaired with a redo urethroplasty and glansplasty.`, 
        `a small penoscrotal fistula identified 12 months after repair can be closed by placement of a urethral catheter and secondary closure.`, 
        `<!--c. -->a urethral diverticulum can be closed using local tissue as a barrier layer.`, 
        `<!--d. -->recurrent penile curvature should be assessed in the operating room to determine if penile skin scarring, corporal disproportion, or both are the cause.`, 
        `<!--e. -->glans dehiscence may require buccal mucosa graft inlay in order to achieve a successful repair.`],
        optionStyleType: `st-lower-alpha`,
        answer: [1],
        ansText:`Rationale: Fistulas rarely, if ever, close with catheter insertion. A coronal fistula with thin glans tissue will likely need a more aggressive repair. A urethral diverticulum can be de-epithelialized to add additional layers of closure. Recurrent curvature should be aggressively diagnosed and managed as there is a high rate of failure with plication alone.`, 
        state: `notAnswered`,
        userAnswered: []
    },
    {
        q: `<!--31. -->Regarding familial hypospadias:`,
        q2: ``,
        q3: [],
        option: [`<!--a. -->only hypospadias associated with malformation syndromes has familial recurrence.`, 
        `<!--b. -->hypospadias will occur only if the mother was taking birth control pills containing progesterone shortly before she conceived.`, 
        `<!--c. -->hypospadias will occur only if the father also has hypospadias.`, 
        `<!--d. -->it will occur, because hypospadias is a Y-linked disorder.`, 
        `<!--e. -->the odds are greatest that another son would not have hypospadias.`],
        optionStyleType: `st-lower-alpha`,
        answer: [3],
        ansText:`Rationale: Sporadic and syndromic hypospadias can have familial recurrence, and the risk of a boy with a brother with hypospadias having hypospadias himself is as high as 15%. This rate would be higher in a twin pairing. Although the likelihood a sibling will have hypospadias is increased, the overall risk remains small.`, 
        state: `notAnswered`,
        userAnswered: []
    }






];
