var quiz = [
    
        {
            q: ` Congenital obstruction differs from acquired obstruction in that it:`,
            q2: ``,
            q3: [],
            option: [` causes renal atrophy.`, 
            `induces interstitial fibrosis. `, 
            `alters renal homeostasis. `, 
            ` affects tubular function.`, 
            `affects glomerular development. `],
            optionStyleType: `st-upper-alpha`,
            answer: [4],
            ansText: `Rationale: Only congenital obstruction will change glomerular development, whereas acquired obstruction can produce all of the other changes indicated. Because it occurs during development, congenital obstruction can produce an altered developmental pattern, whereas acquired obstruction cannot change an already established pattern, only damage or distort it.`,
            state: `notAnswered`,
            userAnswered: []
        ,
	type: `MCSS`,
	type: `MCSS`        ,
        type: `MCSS`},
        {
            q: `Renal dysplasia associated with obstruction is characterized by:`,
            q2: ``,
            q3: [],
            option: [`renal atrophy. `, 
            ` glomerular cysts.`, 
            ` fibromuscular collars.`, 
            ` heterotopic bone formation.`, 
            ` excess production of afferent arteriole renin.`],
            optionStyleType: `st-upper-alpha`,
            answer: [2],
            ansText: `Rationale: One of the histologic hallmarks of dysplasia is fibromuscular collars, so-called <b><i>primitive ducts</i></b> reflecting abnormal differentiation of the peritubular mesenchyme. Renal growth impairment is common with dysplasia; however, this is not atrophy but growth failure. Glomerular cysts are not characteristic of dysplasia. Heterotopic cartilage may be seen, but not bone. Excess renin expression may be seen in obstruction without dysplasia.`,
            state: `notAnswered`,
            userAnswered: []
        ,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`        ,
        type: `MCSS`},
        {
            q: ` After relief of a unilateral obstructing lesion, decreasing relative uptake on radionuclide renal imaging is most likely due to:`,
            q2: ``,
            q3: [],
            option: [` glomerular hyperfiltration.`, 
            `asymmetrical renal growth. `, 
            ` established renal tubular fibrosis.`, 
            ` neural imbalance.`, 
            ` compensatory hypertrophy.`],
            optionStyleType: `st-upper-alpha`,
            answer: [1],
            ansText: `Rationale: When renal function appears to decline after relief of obstruction, it is often due to different growth and functional development rates of the two kidneys, when the affected kidney cannot increase its absolute function as rapidly as the other intact kidney. This produces a progressive differential functional uptake on nuclear imaging that gives the impression of functional loss that is relative and not absolute.`,
            state: `notAnswered`,
            userAnswered: []
        ,
	type: `MCSS`        ,
        type: `MCSS`},
        {
            q: ` In the obstructed kidney, epidermal growth factor (EGF) has been shown to:`,
            q2: ``,
            q3: [],
            option: [` reduce renal apoptosis.`, 
            ` reduce glomerular sclerosis.`, 
            ` accelerate interstitial fibrosis.`, 
            ` improve collecting duct function.`, 
            ` reduce renin recruitment in the afferent arteriole.`],
            optionStyleType: `st-upper-alpha`,
            answer: [0],
            ansText: `Rationale: Administration of EGF to the congenitally obstructed kidney can reduce renal apoptosis and reduce the effects of growth impairment. The other effects have not been reported.`,
            state: `notAnswered`,
            userAnswered: []
        ,
	type: `MCSS`        ,
        type: `MCSS`},
        {
            q: ` Epithelial to mesenchymal transformation in the developing kidney is:`,
            q2: ``,
            q3: [],
            option: [` a one-way process.`, 
            `the basis for glomerular sclerosis. `, 
            ` integral to glomerular development.`, 
            `seen only in the setting of obstruction. `, 
            ` reflected in the presence of α-smooth muscle actin.`],
            optionStyleType: `st-upper-alpha`,
            answer: [4],
            ansText: `Rationale: Epithelial to mesenchymal transformations are an important part of renal development but have not been shown to be part of normal glomerular development. It is the presumed basis for the presence of α-smooth muscle actin in the obstructed kidney. It is bidirectional. `,
            state: `notAnswered`,
            userAnswered: []
                ,
        type: `MCSS`},
        {
            q: ` Regulation of the extracellular matrix in the kidney:`,
            q2: ``,
            q3: [],
            option: [`depends on normal expression of EGF. `, 
            `depends entirely on collagen synthesis. `, 
            `is not related to angiotensin expression. `, 
            `depends on balanced synthesis and degradation. `, 
            ` is independent of transforming growth factor-β (TGF-β) activity.`],
            optionStyleType: `st-upper-alpha`,
            answer: [3],
            ansText: `Rationale: Extracellular membrane (ECM) regulation is due to collagen synthesis rates as well as to the rate of ECM breakdown. The latter is determined by the balanced activities of the tissue inhibitors of metalloproteinases (TIMPs) and matrix metalloproteinases (MMPs); these are regulated in part by TGF-β and the renin-angiotensin system.`,
            state: `notAnswered`,
            userAnswered: []
        ,
	type: `MCSS`,
	type: `MCSS`        ,
        type: `MCSS`},
        {
            q: ` The principal effects of congenital renal obstruction are:`,
            q2: ``,
            q3: [],
            option: [` glomerulosclerosis, interstitial fibrosis, and atrophy.`, 
            `hypoplasia and increased epithelial-mesenchymal transformation. `, 
            ` altered growth regulation, renal differentiation, and functional integration.`, 
            ` glomerulosclerosis, renin downregulation, and tubular hypertrophy.`, 
            ` increased growth, fibrosis, and tubular atrophy.`],
            optionStyleType: `st-upper-alpha`,
            answer: [2],
            ansText: `Rationale: The key patterns defining congenital renal obstruction are altered growth regulation, renal differentiation, and functional integration, although interstitial fibrosis, tubular hypotrophy, and increased epithelial-mesenchymal transformation are components of these changes. `,
            state: `notAnswered`,
            userAnswered: []
                ,
        type: `MCSS`},
        {
            q: ` In the fetal kidney, angiotensin activity:`,
            q2: ``,
            q3: [],
            option: [` is tightly regulated by EGF.`, 
            ` acts predominantly through the AT-1 receptor.`, 
            ` affects epithelial-mesenchymal transformation.`, 
            ` is an important regulator of renal growth.`, 
            ` is unaffected by renal obstruction.`],
            optionStyleType: `st-upper-alpha`,
            answer: [3],
            ansText: `Rationale: In the developing kidney, angiotensin is an important growth regulator, as well as mediator of fibrosis, and is altered significantly by obstruction. Fetal angiotensin acts predominantly through the AT2 receptor until late in gestation, when the AT1 receptor begins to exert a greater role. `,
            state: `notAnswered`,
            userAnswered: []
                ,
        type: `MCSS`},
        {
            q: ` Inflammatory change in the congenitally obstructed kidney:`,
            q2: ``,
            q3: [],
            option: [`is similar to those seen in postnatally obstructed kidneys. `, 
            `is mediated by the renin-angiotensin system. `, 
            ` is minimal in the absence of overt infection.`, 
            ` is the key element in glomerular damage.`, 
            ` affects renal interstitial fibrosis.`],
            optionStyleType: `st-upper-alpha`,
            answer: [2],
            ansText: `Rationale: In contrast to acquired obstruction, congenital obstruction is not characterized by a significant inflammatory infiltrate, except when complicated by infection. `,
            state: `notAnswered`,
            userAnswered: []
                ,
        type: `MCSS`},


];
