var quiz = [
  {
    q: `<!--1. -->Which of the following statements is FALSE regarding the construction of a neovagina utilizing bowel?`,
    q2: ``,
    q3: [],
    option: [
      `<!--a. -->Failure to develop an adequate space between the rectum and bladder can result in compromised blood flow to the segment used for vaginal construction.`,
      `<!--b. -->In general, colon is preferred versus ileum because of its lower incidence of associated postoperative stenosis.`,
      `<!--c. -->When compared with the McIndoe procedure, the bowel vagina suffers from a higher incidence of postoperative stenosis.`,
      `<!--d. -->An advantage of a bowel vagina versus the McIndoe procedure includes the lubricating properties of mucus (which may help facilitate intercourse).`,
      `<!--e. -->One specific indication for the use of ileum is a previous history of pelvic radiation.`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [2],
    ansText: `Rationale: A high incidence of postoperative vaginal stenosis necessitates postoperative vaginal dilatation in the McIndoe procedure.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `<!--2. -->Urogenital sinus anomalies in differences of sexual development states are most commonly seen in association with:`,
    q2: ``,
    q3: [],
    option: [
      `<!--a. -->congenital adrenal hyperplasia.`,
      `<!--b. -->mixed gonadal dysgenesis.`,
      `<!--c. -->ovotesticular disorder.`,
      `<!--d. -->cloacal anomalies.`,
      `<!--e. -->gonadal dysgenesis.`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [0],
    ansText: `Rationale: Urogenital sinus abnormalities are most often seen in disorders of sexual differentiation states, most commonly in association with congenital adrenal hyperplasia, which has been noted to have an incidence as frequent as 1 in 500 in the nonclassic mild forms.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `<!--3. -->The most common finding in cloacal anomalies that have been diagnosed by antenatal ultrasonography is:`,
    q2: ``,
    q3: [],
    option: [
      `ascites.`,
      `<!--b. -->distended rectum.`,
      `<!--c. -->distended bladder.`,
      `<!--d. -->distended vagina.`,
      `<!--e. -->distended bladder and rectum.`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [3],
    ansText: `Rationale: The common finding in all reports has been a cystic pelvic mass between the bladder and rectum, representing a distended vagina.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `<!--4. -->What is the most common vaginal anatomy in cloacal malformation?`,
    q2: ``,
    q3: [],
    option: [
      `<!--a. -->Single vagina, single uterus`,
      `<!--b. -->Single vagina, double uterus`,
      `<!--c. -->Two vaginas, two uteri`,
      `<!--d. -->Two vaginas, one uterus`,
      `<!--e. -->Single vagina, no uterus`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [2],
    ansText: `Rationale: In Hendren’s report on 154 patients with cloacal anomalies, 66 patients had one vagina, 68 had two vaginas, and the vagina was absent in 20. The incidence of vaginal duplication is even higher in the author’s own patient population. The uterus anomaly generally is similar to the vaginal anomaly, that is, two vaginas with two uteri.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `<!--5. -->Neonatal vaginoplasty combined with clitoroplasty and labiaplasty has all of the following advantages EXCEPT:`,
    q2: ``,
    q3: [],
    option: [
      `<!--a. -->it allows phallic skin for vaginal reconstruction.`,
      `<!--b. -->maternal estrogens increase vaginal thickness and vascularity.`,
      `<!--c. -->tissues are less scarred.`,
      `<!--d. -->vaginal stenosis is clearly less.`,
      `<!--e. -->clitoroplasty must retain normal clitoral innervation while providing excellent cosmesis.`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [3],
    ansText: `Rationale: Other investigators, including the author’s group, have thought that vaginoplasty, regardless of the vaginal location, is best combined with clitoroplasty in a single stage. This allows the redundant phallic skin to be used in the reconstruction, adding flexibility for the surgeon, which is compromised when the skin has been previously mobilized. Furthermore, the authors and others have noted that maternal estrogen stimulation of the child’s genitalia results in thicker vaginal tissue, which is better vascularized, making vaginal mobilization more easily performed.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `<!--6. -->The cut-back vaginoplasty is appropriate for:`,
    q2: ``,
    q3: [],
    option: [
      `<!--a. -->labial fusion.`,
      `<!--b. -->low vaginal confluence.`,
      `<!--c. -->high vaginal confluence.`,
      `<!--d. -->vaginal atresia.`,
      `<!--e. -->vaginal agenesis.`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [0],
    ansText: `Rationale: The cut-back vaginoplasty is rarely used and is appropriate only for simple labial fusion.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `<!--7. -->Surgical management of cloacal malformations involves all of the following steps EXCEPT:`,
    q2: ``,
    q3: [],
    option: [
      `<!--a. -->decompression of the gastrointestinal tract.`,
      `<!--b. -->decompression of the genitourinary tract.`,
      `<!--c. -->vaginostomy.`,
      `<!--d. -->definitive repair of the cloaca.`,
      `<!--e. -->correction of nephron destructive anomalies.`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [2],
    ansText: `Rationale: Surgical management now involves four basic steps: decompression of the gastrointestinal tract, decompression of the genitourinary tract, correction of nephron-destructive or potentially lethal urinary anomalies, and definitive repair of the cloaca.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `<!--8. -->Fecal continence after cloacal reconstruction is most closely related to:`,
    q2: ``,
    q3: [],
    option: [
      `<!--a. -->the level of rectal confluence.`,
      `<!--b. -->associated urinary anomalies.`,
      `<!--c. -->neurologic status.`,
      `<!--d. -->the type of repair.`,
      `<!--e. -->the timing of the repair.`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [2],
    ansText: `Rationale: Fecal continence is directly related to neurologic status.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
];
