var quiz = [
    

    {
        q: `<!--1. -->Which of the following statements is TRUE regarding Mayer-Rokitansky-Küster-Hauser (MRKH) syndrome?`,
        q2: ``,
        q3: [],
        option: [`<!--a. -->Patients present most commonly with infertility.`, 
        `<!--b. -->It is a homogeneous disorder entailing congenital absence of the uterus and vagina.`, 
        `<!--c. -->It is associated with a spectrum of ovarian abnormalities.`, 
        `<!--d. -->It has associated upper urinary tract anomalies, primarily with the atypical disorder.`, 
        `<!--e. -->It is associated with persistent Wolffian duct structures.`],
        optionStyleType: `st-lower-alpha`,
        answer: [3],
        ansText:`Rationale: Urinary tract anomalies occur more commonly in patients with the atypical form of the disorder than in patients with the typical syndrome.`, 
        state: `notAnswered`,
        userAnswered: []
    ,
	type: `MCSS`        ,
        type: `MCSS`},
    {
        q: `<!--2. -->What is the crucial period in embryogenesis for the formation of the terminal bowel, kidney, paramesonephric ductal system, and lumbosacral spine?`,
        q2: ``,
        q3: [],
        option: [`<!--a. -->4 to 6 weeks`, 
        `<!--a. -->8 to 10 weeks`, 
        `<!--a. -->10 to 14 weeks`, 
        `<!--a. --> 14 to 18 weeks`, 
        `<!--e. -->After 18 weeks`],
        optionStyleType: `st-lower-alpha`,
        answer: [0],
        ansText:`Rationale: Laboratory data with teratogens support the concept of a key event occurring between the fourth and fifth weeks of gestation that results in an error in the simultaneous development of the terminal bowel, kidney, bladder, paramesonephric ductal system, and lumbosacral spine.`, 
        state: `notAnswered`,
        userAnswered: []
    ,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`        ,
        type: `MCSS`},
    {
        q: `<!--3. -->Which of the following is FALSE regarding vaginal agenesis (Müllerian aplasia)?`,
        q2: ``,
        q3: [],
        option: [`<!--a. -->It occurs in approximately 1 in 5000 live female births.`, 
        `<!--b. -->Serum follicle-stimulating hormone and luteinizing hormone levels can be expected to be abnormally high.`, 
        `Embryologically, it results from a failure of the sinovaginal bulbs to develop and form the vaginal plate.`, 
        `<!--d. -->It is associated with renal abnormalities.`, 
        `<!--e. -->It is associated with skeletal abnormalities.`],
        optionStyleType: `st-lower-alpha`,
        answer: [1],
        ansText:`Rationale: <b>Vaginal agenesis, which occurs in approximately 1 in 5000 live female births, is the congenital absence of the proximal portion of the vagina in an otherwise phenotypically (i.e., normal secondary sexual characteristics), chromosomally (i.e., 46,XX), and hormonally (i.e., normal luteinizing hormone and follicle-stimulating hormone levels) intact female.</b> It results from a failure of the sinovaginal bulbs to develop and form the vaginal plate. <b>Hauser brought further attention to the frequent association of renal and skeletal anomalies in these patients and stressed the differences between patients with these findings and those with complete androgen insensitivity syndrome (testicular feminization).</b>`, 
        state: `notAnswered`,
        userAnswered: []
    ,
	type: `MCSS`,
	type: `MCSS`        ,
        type: `MCSS`},
    {
        q: `<!--4. -->Skeletal anomalies are found in what percentage of patients with Meyer-Rokitansky-Küster-Hauser syndrome?`,
        q2: ``,
        q3: [],
        option: [`10% to 20%`, 
        `25% to 35%`, 
        `40% to 60%`, 
        `70% to 90%`, 
        `0% (they are not seen in MRKH)`],
        optionStyleType: `st-lower-alpha`,
        answer: [0],
        ansText:`Rationale: Associated congenital abnormalities of the skeletal system have been described in 10% to 20% of cases.`, 
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `<!--5. -->What is the most common cause of primary amenorrhea?`,
        q2: ``,
        q3: [],
        option: [`<!--a. -->Complete androgen insensitivity syndrome`, 
        `<!--b. -->Vaginal agenesis`, 
        `<!--c. -->Mixed gonadal dysgenesis`, 
        `<!--d. -->Imperforate hymen`, 
        `<!--e. -->Transverse vaginal septum`],
        optionStyleType: `st-lower-alpha`,
        answer: [2],
        ansText:`Rationale: Meyer-Rokitansky-Küster-Hauser syndrome is in fact secondary only to gonadal dysgenesis as a cause of primary amenorrhea.`, 
        state: `notAnswered`,
        userAnswered: []
    ,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`        ,
        type: `MCSS`},
    {
        q: `<!--6. -->Which of the following statement is FALSE regarding the genitalia of women with Meyer-Rokitansky-Küster-Hauser syndrome?`,
        q2: ``,
        q3: [],
        option: [`<!--a. -->In approximately 10% of patients, a normal but obstructed uterus or rudimentary uterus with functional endometrium is present.`, 
        `<!--b. -->Normal fallopian tubes are seen in approximately 35% of patients.`, 
        `<!--c. -->The ovaries are not functional in the majority of patients.`, 
        `<!--d. -->The hymenal ridge is usually present, along with a small vaginal pouch`, 
        `<!--e. -->The labia majora are typically normal in appearance.`],
        optionStyleType: `st-lower-alpha`,
        answer: [2],
        ansText:`Rationale: Although occasionally cystic, the ovaries are almost always present and functional.`, 
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `<!--7. -->Uterus didelphys with unilateral imperforate vagina is most commonly present with which condition?`,
        q2: ``,
        q3: [],
        option: [`<!--a. -->Primary amenorrhea`, 
        `<!--b. -->Cyclic abdominal pain associated with normal cyclic menstruation.`, 
        `<!--c. -->Renal anomalies contralateral to the side of the obstruction`, 
        `<!--d. -->Anomalies of the axial skeleton`, 
        `<!--e. -->Constipation`],
        optionStyleType: `st-lower-alpha`,
        answer: [1],
        ansText:`Rationale: As with other obstructive disorders, the patient may present with cyclical or chronic abdominal pain. However, unlike other obstructive processes, duplication anomalies with unilateral obstruction are not associated with primary amenorrhea.`, 
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `<!--8. -->Urethral prolapse is most commonly seen in young females of which ethnic background?`,
        q2: ``,
        q3: [],
        option: [`<!--a. -->African American`, 
        `White`, 
        `Asian`, 
        `Hispanic`, 
        `<!--e. -->Native American`],
        optionStyleType: `st-lower-alpha`,
        answer: [0],
        ansText:`Rationale: This entity, which was first described by Solinger in 1732, occurs most often in prepubertal black girls and postmenopausal white women.`, 
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `<!--9. -->In most cases of labial adhesions, which of the following is true?`,
        q2: ``,
        q3: [],
        option: [`<!--a. -->They are believed to occur because of a relative state of hyperestrogenism.`, 
        `<!--b. -->They should be treated with surgical lysis.`, 
        `<!--c. -->They require no treatment.`, 
        `<!--d. -->They occur secondary to sexual abuse.`, 
        `<!--e. -->They have associated renal anomalies.`],
        optionStyleType: `st-lower-alpha`,
        answer: [2],
        ansText:`Rationale: Most children do not require treatment unless one of the aforementioned symptoms (urine pooling within the vagina, which may lead to postvoid dribbling; urinary tract infection; perineal irritation; physical findings of sexual abuse) occurs.`, 
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `<!--10. -->What is the mean age of a child with vaginal rhabdomyosarcoma?`,
        q2: ``,
        q3: [],
        option: [`<!--a. -->Younger than 2 years`, 
        `<!--b. -->2 to 4 years`, 
        `<!--c. -->4 to 8 years`, 
        `<!--d. -->8 to 12 years`, 
        `<!--e. -->Older than 12 years`],
        optionStyleType: `st-lower-alpha`,
        answer: [0],
        ansText:`Rationale: The mean age of patients with primary vaginal tumors is younger than 2 years.`, 
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `<!--11. -->All of the following statements are true of anogenital condyloma acuminatum EXCEPT:`,
        q2: ``,
        q3: [],
        option: [`<!--a. -->human papillomavirus is the etiologic agent.`, 
        `<!--b. -->sexual abuse is the only means by which an infant can contract the disease.`, 
        `<!--c. -->many cases in children resolve spontaneously.`, 
        `<!--d. -->pediatric immunization should dramatically reduce the incidence of this disorder.`, 
        `<!--e. -->carbon dioxide laser ablation is successful for anogenital lesions.`],
        optionStyleType: `st-lower-alpha`,
        answer: [1],
        ansText:`Rationale: Although a very high suspicion for sexual abuse is warranted, it should be kept in mind that perinatal transmission is also a possible mechanism. The ideal treatment depends on patient age and location and severity of the lesions.`, 
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`}
    
];
