var quiz = [
    

    {
        q: `<!--1. -->What is the master gene responsible for male sexual differentiation?`,
        q2: ``,
        q3: [],
        option: [`RSPO1`, 
        `SOX9`, 
        `WT1`, 
        `SRY`, 
        `WNT4`],
        optionStyleType: `st-lower-alpha`,
        answer: [3],
        ansText:`Rationale: The SRY gene appears to be primarily responsible for male sexual differentiation through complex interactions involving both activation and repression of other male-specific genes.`, 
        state: `notAnswered`,
        userAnswered: []
    ,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`        ,
        type: `MCSS`},
    {
        q: `<!--2. -->During male reproductive tract development, androgens mediate the differentiation of all of the following structures EXCEPT:`,
        q2: ``,
        q3: [],
        option: [`<!--a. -->seminal vesicles.`, 
        `ureter.`, 
        `epididymis.`, 
        `<!--d. -->vas deferens.`, 
        `<!--e. -->ejaculatory ducts.`],
        optionStyleType: `st-lower-alpha`,
        answer: [1],
        ansText:`Rationale: Androgens (testosterone, dihydrotestosterone) mediate the differentiation of the paired Wolffian ducts into the seminal vesicles, epididymis, vas deferens, and ejaculatory ducts.`, 
        state: `notAnswered`,
        userAnswered: []
    ,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`        ,
        type: `MCSS`},
    {
        q: `<!--3. -->Which of the following does not play a direct role in testicular descent?`,
        q2: ``,
        q3: [],
        option: [`Testis`, 
        `Epididymis`, 
        `<!--c. -->Genitofemoral nerve`, 
        `<!--d. -->Gubernaculum`, 
        `<!--e. -->Processus vaginalis`],
        optionStyleType: `st-lower-alpha`,
        answer: [1],
        ansText:`Rationale: Changes in the gubernaculum and processus vaginalis and their innervation by the genitofemoral nerve, and hormone secretion by the testis are all important in the process of testicular descent.`, 
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `<!--4. -->Peak levels of testosterone and insulin-like 3 occur in the male fetus at approximately what gestational week?`,
        q2: ``,
        q3: [],
        option: [`5`, 
        `8`, 
        `10`, 
        `15`, 
        `20`],
        optionStyleType: `st-lower-alpha`,
        answer: [3],
        ansText:`Rationale: Testosterone production peaks at 14 to 16 weeks and INSL3 peaks at 15 to 17 weeks.`, 
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `<!--5. -->Cryptorchidism increases the risk of all of the following EXCEPT:`,
        q2: ``,
        q3: [],
        option: [`<!--a. -->spermatic cord torsion.`, 
        `<!--b. -->clinical hernia.`, 
        `<!--c. -->reactive hydrocele.`, 
        `infertility.`, 
        `<!--e. -->testicular malignancy.`],
        optionStyleType: `st-lower-alpha`,
        answer: [2],
        ansText:`Rationale: All of the others are possible complications of cryptorchidism.`, 
        state: `notAnswered`,
        userAnswered: []
    ,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`        ,
        type: `MCSS`},
    {
        q: `<!--6. -->The risk of cryptorchidism is higher in all of the following syndromes EXCEPT:`,
        q2: ``,
        q3: [],
        option: [`<!--a. -->cerebral palsy.`, 
        `<!--b. -->cystic fibrosis.`, 
        `arthrogryposis.`, 
        `<!--d. -->prune belly syndrome.`, 
        `<!--e. -->posterior urethral valves.`],
        optionStyleType: `st-lower-alpha`,
        answer: [1],
        ansText:`Rationale: All the other syndromes are associated with a higher risk of cryptorchidism; mutations of the cystic fibrosis gene are associated with congenital absence of the vas deferens.`, 
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `<!--7. -->All of the following are associated with patency of the processus vaginalis EXCEPT:`,
        q2: ``,
        q3: [],
        option: [`<!--a. -->transverse testicular ectopia.`, 
        `<!--b. -->epididymal anomalies.`, 
        `<!--c. -->cryptorchidism.`, 
        `<!--d. -->spermatic cord torsion.`, 
        `<!--e. -->polyorchidism.`],
        optionStyleType: `st-lower-alpha`,
        answer: [3],
        ansText:`Rationale: Risk of torsion is associated with abnormal development of the tunica vaginalis but not patency of the processus vaginalis.`, 
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `<!--8. -->Histologic findings in cryptorchid testes may include all of the following EXCEPT:`,
        q2: ``,
        q3: [],
        option: [`<!--a. -->carcinoma in situ.`, 
        `<!--b. -->absence of Ad spermatogonia.`, 
        `<!--c. -->early disappearance of gonocytes.`, 
        `<!--d. -->failure of Sertoli cell maturation.`, 
        `<!--e. -->reduced germ cell counts.`],
        optionStyleType: `st-lower-alpha`,
        answer: [2],
        ansText:`Rationale: Histological abnormalities that may be present in cryptorchid testes include delayed disappearance of gonocytes, reduced numbers of adult dark (Ad) spermatogonia, reduced number of germ cells per testicular tubule, and carcinoma in situ (CIS).`, 
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `<!--9. -->What percentage of undescended testes are nonpalpable at presentation?`,
        q2: ``,
        q3: [],
        option: [`1%`, 
        `3%`, 
        `10%`, 
        `20%`, 
        `30%`],
        optionStyleType: `st-lower-alpha`,
        answer: [3],
        ansText:`Rationale: Approximately 20% of undescended testes are nonpalpable at presentation.`, 
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `<!--10. -->During laparoscopy, spermatic cord structures exiting an open internal ring ipsilateral to a nonpalpable testis imply:`,
        q2: ``,
        q3: [],
        option: [`<!--a. -->vanishing testis, inguinal exploration unnecessary.`, 
        `<!--b. -->vanishing testis, inguinal exploration necessary.`, 
        `<!--c. -->intracanalicular atrophic testis, inguinal exploration unnecessary.`, 
        `<!--d. -->intracanalicular testis, inguinal exploration necessary.`, 
        `<!--e. -->further exploration unnecessary if contralateral testicular hypertrophy is present.`],
        optionStyleType: `st-lower-alpha`,
        answer: [3],
        ansText:`Rationale: While atretic spermatic vessels seen exiting the internal ring may be associated with a distal vanishing testis, the appearance of the spermatic vessels during laparoscopy is subjective and therefore exploration (inguinal or laparoscopic) is needed to rule out an intracanalicular viable or atrophic testis. Further exploration is unnecessary if blind-ending intraabdominal spermatic vessels are found. Hypertrophy of a normally descended contralateral testis is suggestive of monorchism.`, 
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `<!--11. -->Advantages of laparoscopic management of an intraabdominal testis include all of the following EXCEPT:`,
        q2: ``,
        q3: [],
        option: [`<!--a. -->more accurately assesses the presence or absence, viability, and anatomy of the testis compared with radiographic imaging.`, 
        `<!--b. -->reduces the risk of damage to the testis.`, 
        `<!--c. -->enhances surgical exposure, lighting, and magnification.`, 
        `<!--d. -->allows a greater degree of proximal dissection of the spermatic vessels.`, 
        `<!--e. -->allows diagnosis of associated Müllerian ductal abnormalities if present.`],
        optionStyleType: `st-lower-alpha`,
        answer: [1],
        ansText:`Rationale: Laparoscopic orchidopexy still carries the risks of bleeding, infection, and damage to the testis and cord in addition to damage to intraabdominal structures such as bowel and the great vessels.`, 
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `<!--12. -->Which statement is FALSE regarding Fowler-Stephens orchidopexy?`,
        q2: ``,
        q3: [],
        option: [`<!--a. -->It is less commonly associated with testicular atrophy than laparoscopic primary orchidopexy.`, 
        `<!--b. -->It has a lower success rate in patients who have undergone previous inguinal surgery.`, 
        `<!--c. -->Blood supply is based on the deferential artery and collateral peritoneal vessels.`, 
        `<!--d. -->It should be performed at a similar age as a standard inguinal orchidopexy.`, 
        `<!--e. -->It should be considered if the testis is not near the internal ring.`],
        optionStyleType: `st-lower-alpha`,
        answer: [0],
        ansText:`Rationale: Fowler-Stephens orchidopexy, either one-or two-stage, has a higher reported testicular atrophy rate compared with laparoscopic orchidopexy. The other statements are true.`, 
        state: `notAnswered`,
        userAnswered: []
    ,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`        ,
        type: `MCSS`},
    {
        q: `<!--13. -->Which of the following is least consistent with a diagnosis of vanishing testis?`,
        q2: ``,
        q3: [],
        option: [`<!--a. -->Patent processus vaginalis`, 
        `<!--b. -->Contralateral testicular hypertrophy`, 
        `<!--c. -->Palpable nubbin in scrotum`, 
        `<!--d. -->Increased serum follicle-stimulating hormone`, 
        `Micropenis`],
        optionStyleType: `st-lower-alpha`,
        answer: [0],
        ansText:`Rationale: Contralateral testicular hypertrophy and a palpable scrotal nubbin may present in boys with unilateral vanishing testis and increased serum FSH and micropenis may be seen in boys with bilateral vanishing testes. The processus vaginalis is closed in most cases of vanishing testis.`, 
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `<!--14. -->Lower than expected testicular volume has been associated with all of the following EXCEPT:`,
        q2: ``,
        q3: [],
        option: [`<!--a. -->cryptorchid testes that have descended spontaneously.`, 
        `<!--b. -->solitary testes in boys with a vanishing testis.`, 
        `<!--c. -->Fowler-Stephens orchidopexy.`, 
        `<!--d. -->increased serum FSH.`, 
        `<!--e. -->surgery for congenital cryptorchidism at 3 years as compared to 9 months of age.`],
        optionStyleType: `st-lower-alpha`,
        answer: [1],
        ansText:`Rationale: In vanishing testis syndrome, the contralateral testis may be larger than expected for age.`, 
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `<!--15. -->Regarding epididymal anatomy, which of the following is the most common finding in boys undergoing orchidopexy for acquired cryptorchidism?`,
        q2: ``,
        q3: [],
        option: [`<!--a. -->Detachment of the cauda epididymis`, 
        `<!--b. -->Detachment of the caput epididymis`, 
        `<!--c. -->Looped epididymis`, 
        `<!--d. -->Long looping epididymis/vas`, 
        `<!--e. -->Normal anatomy`],
        optionStyleType: `st-lower-alpha`,
        answer: [4],
        ansText:`Rationale:  An abnormal epididymis was reported ipsilateral to 11% to 31% of acquired undescended testes at surgery.`, 
        state: `notAnswered`,
        userAnswered: []
    ,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`        ,
        type: `MCSS`},
    {
        q: `<!--16. -->All of the following factors may influence the reliability of studies of the efficacy of hormone therapy for cryptorchidism EXCEPT:`,
        q2: ``,
        q3: [],
        option: [`<!--a. -->treatment of boys with retractile testes.`, 
        `<!--b. -->initial position of the testis.`, 
        `<!--c. -->vanishing testis syndrome.`, 
        `<!--d. -->randomization protocol.`, 
        `<!--e. -->all of the above.`],
        optionStyleType: `st-lower-alpha`,
        answer: [4],
        ansText:`Rationale: All of the above are confounding factors that may affect the reliability of studies of the efficacy of hormone therapy for cryptorchidism.`, 
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `<!--17. -->A healthy full-term newborn boy presents with a bilateral nonpalpable testes. The next step in management should include:`,
        q2: ``,
        q3: [],
        option: [`<!--a. -->karyotype analysis.`, 
        `<!--b. -->GnRH stimulation test.`, 
        `<!--c. -->abdominal ultrasound.`, 
        `circumcision.`, 
        `<!--e. -->discharge home with MRI with gadolinium in four weeks.`],
        optionStyleType: `st-lower-alpha`,
        answer: [0],
        ansText:`Rationale: AUA Guidelines for cryptorchidism state that providers must immediately consult an appropriate specialist for all phenotypic male newborns with bilateral, nonpalpable testes for evaluation of a possible difference of sex development (DSD). A newborn with a male phallus and bilateral nonpalpable gonads is potentially a genetic female (46,XX) with congenital adrenal hyperplasia until proven otherwise. Circumcision should be avoided in the initial management. More than 70% of cryptorchid testes are palpable by physical examination and need no imaging. In the remaining 30% of cases with a nonpalpable testis, the challenge is to confirm absence or presence of the testis. At this time, there is no radiologic test that can conclude with 100% accuracy that a testis is absent.`, 
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `<!--18. -->Of the following, which is the LEAST reliable test in confirming the diagnosis of bilateral anorchia?`,
        q2: ``,
        q3: [],
        option: [`<!--a. -->No change in serum testosterone following hCG stimulation`, 
        `<!--b. -->FSH level &gt;2 IU/L at 1 year of age`, 
        `<!--c. -->Laparoscopy`, 
        `<!--d. -->Undetectable serum inhibin B`, 
        `<!--e. -->Undetectable serum anti-Müllerian hormone (AMH)`],
        optionStyleType: `st-lower-alpha`,
        answer: [0],
        ansText:`Rationale:  Serum testosterone may not increase significantly in response to hCG stimulation in individuals with abnormal testes.`, 
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `<!--19. -->Which of the following is LEAST useful to the provider in determining the diagnosis of retractile vs. undescended testes?`,
        q2: ``,
        q3: [],
        option: [`<!--a. -->Observation of testicular position with abduction of the patient’s legs`, 
        `<!--b. -->History of prior testicular position provided by the primary care physician (PCP)`, 
        `<!--c. -->Failure of the testis to remain stable in the scrotum with sustained traction on the cord`, 
        `<!--d. -->Warm room and hands`, 
        `<!--e. -->Small ipsilateral testis`],
        optionStyleType: `st-lower-alpha`,
        answer: [1],
        ansText:`Rationale: Testicular position can change over time and/or be difficult to ascertain in boys with retractile testes; therefore, a careful examination is necessary to differentiate between retractile and undescended testes.`, 
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `<!--20. -->Which of the following is true regarding spontaneous descent of cryptorchid testes?`,
        q2: ``,
        q3: [],
        option: [`<!--a. -->Spontaneous descent is independent of testicular position.`, 
        `<!--b. -->Reascent occurs in 40% of patients.`, 
        `<!--c. -->Early descent is more likely in premature boys.`, 
        `<!--d. -->Spontaneous descent is unlikely if the ipsilateral hemiscrotum is small.`, 
        `<!--e. -->The majority of testes that descend spontaneously do so in the first few months of life.`],
        optionStyleType: `st-lower-alpha`,
        answer: [4],
        ansText:`Rationale: For full-term boys of normal weight, spontaneous testicular descent typically occurs in the first months after birth and is rare after 6 months of age.`, 
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `<!--21. -->The risk of developing a testicular tumor in males with a history of cryptorchidism is:`,
        q2: ``,
        q3: [],
        option: [`<!--a. -->2 to 5 times the risk in normal boys.`, 
        `<!--b. -->minimal in boys who undergo orchidopexy in infancy.`, 
        `<!--c. -->determined by placental alkaline phosphatase (PLAP) staining in prepubertal testes.`, 
        `<!--d. -->similar in the contralateral descended testis.`, 
        `<!--e. -->increasing over time.`],
        optionStyleType: `st-lower-alpha`,
        answer: [0],
        ansText:`Rationale: Surgery may reduce but does not eliminate the risk of TGCT in boys with cryptorchidism and the risk exists in the contralateral testis as well, albeit lower. PLAP+ germ cells can be found in normal testes after birth.`, 
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `<!--22. -->Each of the following is more common in association with cryptorchid testes, EXCEPT:`,
        q2: ``,
        q3: [],
        option: [`<!--a. -->atrophy.`, 
        `microlithiasis`, 
        `<!--c. -->mature teratoma.`, 
        `<!--d. -->ectasia of the rete testis.`, 
        `<!--e. -->intratesticular varicocele.`],
        optionStyleType: `st-lower-alpha`,
        answer: [2],
        ansText:`Rationale: The risk of benign testicular tumors is not increased in cryptorchidism.`, 
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `<!--23. -->The following are possible locations of an ectopic testis, EXCEPT:`,
        q2: ``,
        q3: [],
        option: [`peripenile.`, 
        `perirenal.`, 
        `perivesical.`, 
        `perianal.`, 
        `femoral.`],
        optionStyleType: `st-lower-alpha`,
        answer: [3],
        ansText:`Rationale: All the other answers reflect possible positions for ectopic testes that are possible although rare.`, 
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `<!--24. -->Levels of all the following hormones peak after birth and remain low during childhood EXCEPT:`,
        q2: ``,
        q3: [],
        option: [`LH.`, 
        `FSH.`, 
        `AMH.`, 
        `<!--d. -->Inhibin B.`, 
        `testosterone.`],
        optionStyleType: `st-lower-alpha`,
        answer: [2],
        ansText:`Rationale: AMH levels remain high during childhood and are downregulated at puberty.`, 
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `<!--25. -->When in fetal development does the testicle pass into the inguinal canal?`,
        q2: ``,
        q3: [],
        option: [`<!--a. -->5 to 7 weeks gestation`, 
        `<!--b. -->10 to 14 weeks gestation`, 
        `<!--c. -->20 to 28 weeks gestation`, 
        `<!--d. -->30 to 34 weeks gestation`, 
        `<!--e. -->None of the above`],
        optionStyleType: `st-lower-alpha`,
        answer: [2],
        ansText:`Rationale: The testis passes into the inguinal canal at 20 to 28 weeks gestation during the fifth phase of testicular descent.`, 
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `<!--26. -->How commonly does cryptorchidism occur in full-term males?`,
        q2: ``,
        q3: [],
        option: [`<!--a. -->&lt;1%`, 
        `<!--b. -->1% to 4%`, 
        `<!--c. -->5% to 10%`, 
        `15%`, 
        `<!--e. -->None of the above`],
        optionStyleType: `st-lower-alpha`,
        answer: [1],
        ansText:`Rationale: Cryptorchidism is one of the most common congenital anomalies occurring in 1% to 4% of full-term male infants.`, 
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `<!--27. -->A 1-month-old full-term male presents with a unilateral nonpalpable testicle. The next step after a confirmatory exam is:`,
        q2: ``,
        q3: [],
        option: [`<!--a. -->ultrasound to identify the position of the testicle.`, 
        `<!--b. -->MRI with gadolinium.`, 
        `<!--c. -->hormonal therapy to induce descent.`, 
        `<!--d. -->surgical intervention.`, 
        `<!--e. -->observation for spontaneous descent until 6 months of age.`],
        optionStyleType: `st-lower-alpha`,
        answer: [4],
        ansText:`Rationale: Descent may occur up until 6 months of age. If it hasn’t occurred by this time, surgical treatment should be performed. Diagnostic imaging has not been shown to change the need for surgery. Hormonal therapy to induce descent is no longer supported given the lack of evidence that exists.`, 
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`}

];
