var quiz = [
    

    {
        q: `A chromosomal abnormality associated with an adverse prognosis in neuroblastoma is:`,
        q2: ``,
        q3: [],
        option: [`mutation of chromosome 11p15.`, 
        `absence of the MDR gene.`, 
        `mutation of the TP53 gene.`, 
        `deletion of the short arm of chromosome 1.`, 
        `loss of heterozygosity (LOH) for chromosome 11p13.`],
        optionStyleType: `st-lower-alpha`,
        answer: [3],
        ansText:`Rationale: <!--<b>d. Deletion of the short arm of chromosome 1.</b>--> Deletion of the short arm of chromosome 1 is found in 25% to 35% of neuroblastomas and is an adverse prognostic marker. The deletions are of different size, but in a series of eight cases a consensus deletion included the segment 1p36.1-2, suggesting that genetic information related to neuroblastoma tumorigenesis is located in this segment.`, 
        state: `notAnswered`,
        userAnswered: []
    ,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`        ,
        type: `MCSS`},
    {
        q: `In situ neuroblastoma:`,
        q2: ``,
        q3: [],
        option: [`invariably progresses to clinical neuroblastoma.`, 
        `usually regresses spontaneously.`, 
        `is associated with deletion of chromosome 11.`, 
        `is usually detected on newborn screening.`, 
        `is frequently associated with amplification of the MYCN oncogene.`],
        optionStyleType: `st-lower-alpha`,
        answer: [1],
        ansText:`Rationale: <!--<b>b. Usually regresses spontaneously.</b>--> In 1963, Beckwith and Perrin coined the term <b><i>in-situ</i></b> neuroblastoma for small nodules of neuroblastoma cells found incidentally within the adrenal gland, which are histologically indistinguishable from neuroblastoma. In infants younger than 3 months of age undergoing postmortem examination, neuroblastoma <b><i>in-situ</i></b> was found in 1 of 224 infants. This represents an incidence of <b><i>in-situ</i></b> neuroblastoma 40 to 45 times greater than the incidence of clinical tumors, suggesting that these small tumors regress spontaneously in most cases. However, more recent studies have shown that these neuroblastic nodules are found in all fetuses studied and generally regress.`, 
        state: `notAnswered`,
        userAnswered: []
    ,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`        ,
        type: `MCSS`},
    {
        q: `Ganglioneuroma is:`,
        q2: ``,
        q3: [],
        option: [`a stroma-rich tumor by the Shimada classification.`, 
        `most commonly located in the adrenal gland.`, 
        `often found secondary to symptoms from metastatic disease.`, 
        `associated with acute myoclonic encephalopathy.`, 
        `associated with an unfavorable prognosis.`],
        optionStyleType: `st-lower-alpha`,
        answer: [0],
        ansText:`Rationale: <!--<b>a. A stroma-rich tumor by the Shimada classification.</b>--> The Shimada classification is an age-linked histopathologic classification. One of the important aspects of the Shimada classification is determining whether the tumor is stroma poor or stroma rich. Patients with stroma-poor tumors with unfavorable histopathologic features have a very poor prognosis (&lt;10% survival). Stroma-rich tumors can be separated into three subgroups: nodular, intermixed, and well differentiated. Tumors in the last two categories more closely resemble ganglioneuroblastoma or immature ganglioneuroma and have a higher rate of survival.`, 
        state: `notAnswered`,
        userAnswered: []
    ,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`        ,
        type: `MCSS`},
    {
        q: `Screening for neuroblastoma:`,
        q2: ``,
        q3: [],
        option: [`has improved survival in patients with neuroblastoma.`, 
        `has decreased the number of children older than 1 year of age with advanced stage disease.`, 
        `has identified more tumors with amplified <i>MYCN</i> oncogene expression.`, 
        `discovers tumors with a favorable prognosis.`, 
        `is widely performed in the United States.`],
        optionStyleType: `st-lower-alpha`,
        answer: [3],
        ansText:`Rationale: <!--<b>d. Discovers tumors with a favorable prognosis.</b>--> The goal of screening programs is to detect disease at an earlier stage and decrease the number of older children with advanced stage disease and thus improve survival. An increased number of infants younger than 1 year of age have been diagnosed with the mass screening program, and most of these patients have lower-stage tumors. Regrettably, the number of children older than 1 year of age with advanced-stage disease has not decreased.`, 
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `A clinical feature associated with a favorable prognosis in neuroblastoma is:`,
        q2: ``,
        q3: [],
        option: [`age &gt;2 years.`, 
        `thoracic location of the primary tumor.`, 
        `<i>MYCN</i> amplification.`, 
        `chromosome 1p deletion.`, 
        `stroma-poor histology.`],
        optionStyleType: `st-lower-alpha`,
        answer: [1],
        ansText:`Rationale: <!--<b>b. Thoracic location of the primary tumor.</b>--> The site of origin is of significance, with a better survival rate noted for nonadrenal primary tumors. Most children with thoracic neuroblastoma present at a younger age with localized disease and have improved survival even when corrected for age and stage.`, 
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `A 1-month-old girl has a right 4-cm suprarenal mass on abdominal ultrasound. Imaging evaluation detects liver metastases. A skeletal survey is normal. Physical examination reveals multiple subcutaneous skin nodules. The mass is removed, confirmed to be neuroblastoma, and analysis reveals no MYCN amplification. The next step is:`,
        q2: ``,
        q3: [],
        option: [`observation.`, 
        `irradiation to the tumor bed.`, 
        `vincristine, cyclophosphamide, and doxorubicin.`, 
        `vincristine, cyclophosphamide, and irradiation to the tumor bed.`, 
        `autologous bone marrow transplantation after chemotherapy and total-body irradiation.`],
        optionStyleType: `st-lower-alpha`,
        answer: [0],
        ansText:`Rationale: <!--<b>a. Observation.</b>--> The generally favorable behavior of stage IV-S disease has been explained with the identification of biologic markers. The vast majority of these infants have tumors with entirely favorable markers explaining their nonmalignant behavior. A small percentage, however, have adverse markers, and it is these children who have progressive disease to which they often succumb. Resection of the primary tumor is not mandatory. Although excellent survival has been reported after surgery, information regarding histologic prognostic factors was not available for all of these patients. A more recent review was performed of a large cohort of 110 infants with stage IV-S disease. The entire cohort of infants had an estimated 3-year survival rate of 85% ± 4%. This survival rate was significantly decreased, however, to 68% ± 12% for infants who were diploid, 44% ± 33% for those who were <b><i>MYCN</i></b> amplified, and 33% ± 19% for those with unfavorable histology tumors. Of note, there was no statistical difference in survival rate for infants who underwent complete resection of their primary tumor compared with those with partial resection or only biopsy. Patients with extensive metastatic disease who are <b><i>MYCN</i></b>–positive represent a high-risk group. These patients should be considered for a more aggressive treatment with multimodal therapy as per the risk group classification.`, 
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `The WAGR (<i>W</i>ilms tumor, <i>A</i>nirida, <i>G</i>enitourinary anomalies, mental <i>R</i>etardation) syndrome is most frequently associated with:`,
        q2: ``,
        q3: [],
        option: [`deletion of chromosome 15.`, 
        `advanced stage Wilms tumor.`, 
        `neonatal presentation of Wilms tumor.`, 
        `renal insufficiency.`, 
        `familial predisposition to Wilms tumor.`],
        optionStyleType: `st-lower-alpha`,
        answer: [3],
        ansText:`Rationale: <!--<b>d. Renal insufficiency.</b>--> Patients with the WAGR syndrome have a germline deletion at 11p13. WT1 mutations and deletions predispose patients to renal insufficiency. Both the Denys-Drash and WAGR syndrome are associated with an increased risk of renal failure. This occurs later in the WAGR syndrome, often in the second decade of life after treatment of the Wilms tumor.`, 
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `A 3-year-old boy had a hypospadias repair and orchiopexy as an infant and now develops renal insufficiency. Renal biopsy is consistent with a membranoproliferative glomerulonephritis. Appropriate management before renal transplantation is:`,
        q2: ``,
        q3: [],
        option: [`voiding cystourethrogram.`, 
        `gonadal biopsy.`, 
        `observation.`, 
        `bilateral nephrectomy.`, 
        `serial renal ultrasounds.`],
        optionStyleType: `st-lower-alpha`,
        answer: [3],
        ansText:`Rationale: <!--<b>d. Bilateral nephrectomy.</b>--> One specific association of male pseudohermaphroditism, renal mesangial sclerosis, and nephroblastoma is the Denys-Drash syndrome. The majority of these patients progress to end-stage renal disease. A specific mutation of the 11p13 Wilms tumor gene has been identified in these children. Although XY individuals have been reported most often, the syndrome has been reported in genotypic/phenotypic females. One should have a high index of suspicion for the development of renal failure and Wilms tumor in patients with male pseudohermaphroditism.`, 
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `A 2-year-old boy has a palpable right-sided abdominal mass, which on CT scan is a solid lesion. On physical examination the patient’s right arm and leg are noted to be slightly longer in length. His diagnosis is most probably:`,
        q2: ``,
        q3: [],
        option: [`Wilms tumor.`, 
        `neuroblastoma.`, 
        `angiomyolipoma.`, 
        `nephroblastomatosis.`, 
        `renal cell carcinoma.`],
        optionStyleType: `st-lower-alpha`,
        answer: [0],
        ansText:`Rationale: <!--<b>a. Wilms tumor.</b>--> BWS is characterized by excess growth at the cellular, organ (macroglossia, nephromegaly, hepatomegaly), or body segment (hemihypertrophy) levels. Most cases of BWS are sporadic, but up to 15% exhibit heritable characteristics with apparent autosomal dominant inheritance. The risk of nephroblastoma in children with BWS and hemihypertrophy is 4% to 10%.`, 
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `A newborn is identified with Beckwith-Wiedemann syndrome (BWS). A renal ultrasound is obtained. The clinical finding that best predicts the risk of subsequent Wilms tumor development is:`,
        q2: ``,
        q3: [],
        option: [`hepatomegaly.`, 
        `hemihypertrophy.`, 
        `nephromegaly.`, 
        `mutation at chromosome 1p.`, 
        `family history of Wilms tumor.`],
        optionStyleType: `st-lower-alpha`,
        answer: [2],
        ansText:`Rationale: <!--<b>c. Nephromegaly.</b>--> Children with BWS found to have nephromegaly (kidneys at or above the 95th percentile of age-adjusted renal length) are at the greatest risk for the development of Wilms tumor.`, 
        state: `notAnswered`,
        userAnswered: []
    ,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`        ,
        type: `MCSS`},
    {
        q: `A 6-month-old girl is diagnosed with aniridia. Ultrasounds are done every 3 months. This will result in:`,
        q2: ``,
        q3: [],
        option: [`increased survival.`, 
        `detection of lower-stage renal tumor.`, 
        `decreased incidence of bilateral tumors.`, 
        `decreased surgical morbidity.`, 
        `detection of tumors smaller than 3 cm in diameter.`],
        optionStyleType: `st-lower-alpha`,
        answer: [1],
        ansText:`Rationale: <!--<b>b. Detection of lower stage renal tumor.</b>--> Screening with serial renal ultrasonographic scans has been recommended in children with aniridia, hemihypertrophy, and BWS. Review of most studies suggests that 3 to 4 months is the appropriate screening interval. Tumors detected by screening will generally be at a lower stage.`, 
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `A deletion of chromosome 11 has been found most frequently in Wilms tumor patients with:`,
        q2: ``,
        q3: [],
        option: [`aniridia.`, 
        `bilateral tumors.`, 
        `hemihypertrophy.`, 
        `Denys-Drash syndrome (DDS).`, 
        `BWS.`],
        optionStyleType: `st-lower-alpha`,
        answer: [0],
        ansText:`Rationale: <!--<b>a. Aniridia.</b>--> Approximately 50% of patients with WAGR syndrome and a constitutional deletion on chromosome 11 will develop Wilms’ tumor.`, 
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `A 5-year-old boy undergoes nephrectomy for a solid renal mass. Pathology reveals stage 1 favorable histology Wilms tumor. An increased risk for tumor relapse is associated with:`,
        q2: ``,
        q3: [],
        option: [`tumor aneuploidy on flow cytometry.`, 
        `deletion of chromosome 11p13.`, 
        `duplication of chromosome 1.`, 
        `LOH for chromosome 16q.`, 
        `elevated serum ferritin level.`],
        optionStyleType: `st-lower-alpha`,
        answer: [3],
        ansText:`Rationale: <!--<b>d. LOH for chromosome 16q.</b>--> LOH for a portion of chromosome 16q has been noted in 20% of Wilms tumors. A study of 232 patients registered on the National Wilms Tumor Study Group (NWTSG) found LOH for 16q in 17% of the tumors. Patients with tumor-specific LOH for chromosome 16q had a statistically significantly poorer 2-year relapse-free and overall survival rate than did those patients without LOH for chromosome 16q.`, 
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `A 2-year-old girl undergoes left nephrectomy for Wilms tumor. A solitary left pulmonary lesion is noted on chest CT. The pathology shows negative nodes and favorable histology but with capsular penetration. The most important prognostic feature is:`,
        q2: ``,
        q3: [],
        option: [`capsular presentation.`, 
        `histologic subtype.`, 
        `absence of lymph node involvement.`, 
        `age at presentation.`, 
        `presence of pulmonary metastasis.`],
        optionStyleType: `st-lower-alpha`,
        answer: [1],
        ansText:`Rationale: <!--<b>b. Histologic subtype.</b>--> Markers associated with unfavorable outcome include nuclear atypia (anaplasia), focal or diffuse, and sarcomatous tumors (rhabdoid and clear cell type). The latter two tumor types, however, are tumor categories distinct from Wilms tumor. These unfavorable features occurred in approximately 10% of patients but accounted for almost half of the tumor deaths in early NWTSG studies.`, 
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `The feature associated with the worst survival in children with Wilms tumor is:`,
        q2: ``,
        q3: [],
        option: [`diffuse anaplasia.`, 
        `diffuse tumor spill.`, 
        `incomplete tumor resection.`, 
        `tumor spread to periaortic lymph nodes.`, 
        `lung metastasis.`],
        optionStyleType: `st-lower-alpha`,
        answer: [0],
        ansText:`Rationale: <!--<b>a. Diffuse anaplasia.</b>--> Anaplasia is associated with resistance to chemotherapy. This is evidenced by the similar incidence of anaplasia (5%) in the NWTSG and International Society of Paediatric Oncology studies. Although the presence of anaplasia has clearly been demonstrated to carry a poor prognosis, patients with stage I anaplastic Wilms tumor as well as those with higher stages and focal rather than diffuse anaplasia seem to have a more favorable outcome. This confirms the observation that anaplasia is more a marker of chemoresistance than inherent aggressiveness of the tumor.`, 
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `An increased risk for metachronous Wilms tumor is associated with:`,
        q2: ``,
        q3: [],
        option: [`anaplastic histology.`, 
        `clear cell sarcoma.`, 
        `blastemal predominant pattern.`, 
        `renal sinus invasion.`, 
        `nephrogenic rests.`],
        optionStyleType: `st-lower-alpha`,
        answer: [4],
        ansText:`Rationale: <!--<b>e. Nephrogenic rests.</b>--> NWTSG investigators demonstrated the clinical importance of nephrogenic rests. Multiple rests in one kidney usually imply that nephrogenic rests are present in the other kidney. Children younger than 12 months of age diagnosed with Wilms tumor who also have nephrogenic rests, in particular perilobar nephrogenic rests, have a markedly increased risk of developing contralateral disease, and require frequent and regular surveillance for several years.`, 
        state: `notAnswered`,
        userAnswered: []
    ,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`        ,
        type: `MCSS`},
    {
        q: `A 1-year-old boy undergoes nephrectomy for Wilms tumor. The finding that has the most adverse impact on survival is:`,
        q2: ``,
        q3: [],
        option: [`hilar lymph node involvement.`, 
        `renal sinus invasion.`, 
        `capsular penetration.`, 
        `ureteral extension of tumor.`, 
        `renal vein thrombus.`],
        optionStyleType: `st-lower-alpha`,
        answer: [0],
        ansText:`Rationale: <!--<b>a. Hilar lymph node involvement.</b>--> The most important determinants of outcome in children with Wilms tumor are histopathology and tumor stage. Accurate staging of Wilms tumor allows treatment results to be evaluated and enables universal comparisons of outcomes. The staging system used by the NWTSG is based primarily on the surgical and histopathologic findings. Examination for extension through the capsule, residual disease, vascular involvement, and lymph node involvement is essential to properly assess the extent of the tumor.`, 
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `The factor associated with the lowest risk of local tumor relapse in children with Wilms tumor is:`,
        q2: ``,
        q3: [],
        option: [`local tumor spill.`, 
        `unfavorable histology.`, 
        `incomplete tumor removal.`, 
        `absence of lymph node sampling.`, 
        `capsular penetration.`],
        optionStyleType: `st-lower-alpha`,
        answer: [4],
        ansText:`Rationale: <!--<b>e. Capsular penetration.</b>--> One study identified risk factors for local tumor recurrence as tumor spillage, unfavorable histology, incomplete tumor removal, and absence of any lymph node sampling. The 2-year survival rate after abdominal recurrence was 43%, emphasizing the importance of the surgeon in performing careful and complete tumor resection.`, 
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `A 4-year-old girl undergoes nephrectomy for a favorable histology Wilms tumor. Imaging reveals multiple pulmonary metastases. Treatment should include vincristine, dactinomycin, and:`,
        q2: ``,
        q3: [],
        option: [`observation.`, 
        `resection of the pulmonary lesions.`, 
        `doxorubicin and chest irradiation.`, 
        `doxorubicin, cyclophosphamide, and irradiation.`, 
        `doxorubicin and etoposide.`],
        optionStyleType: `st-lower-alpha`,
        answer: [2],
        ansText:`Rationale: <!--<b>c. Doxorubicin and chest irradiation.</b>--> Patients with stage III favorable histologic type tumors and stage II to III focal anaplasia are treated with dactinomycin, vincristine, and doxorubicin and 10.8-Gy abdominal irradiation. Patients with stage IV favorable histologic type tumors receive abdominal irradiation based on the local tumor stage and 12 Gy to both lungs.`, 
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `A 3-month-old boy undergoes removal of a 300 g Wilms tumor of the right kidney. The pathology shows diffuse anaplasia and tumor confined to the kidney. Lymph nodes were negative. The next step is:`,
        q2: ``,
        q3: [],
        option: [`observation.`, 
        `vincristine and dactinomycin.`, 
        `vincristine, dactinomycin, and irradiation of the tumor bed.`, 
        `doxorubicin, vincristine, dactinomycin, and irradiation of the tumor bed.`, 
        `ifosfamide, etoposide, and doxorubicin.`],
        optionStyleType: `st-lower-alpha`,
        answer: [3],
        ansText:`Rationale: <!--<b>d. Doxorubicin, vincristine, dactinomycin, and irradiation of the tumor bed.</b>--> Anaplasia tumors are resistant to chemotherapy. However, if the tumor is confined to the kidney and completely resected the prognosis is good. They do require more intense treatment than children with stage I, favorable histology tumors.`, 
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `A 5-year-old girl presents with hematuria. CT reveals a right abdominal mass with extension of tumor thrombus into the suprahepatic vena cava. The best next step is:`,
        q2: ``,
        q3: [],
        option: [`chemotherapy.`, 
        `irradiation.`, 
        `open biopsy followed by chemotherapy.`, 
        `preoperative chemotherapy and radiation therapy.`, 
        `primary surgical removal of the kidney and tumor thrombus.`],
        optionStyleType: `st-lower-alpha`,
        answer: [2],
        ansText:`Rationale: <!--<b>c. Open biopsy followed by chemotherapy.</b>--> The current recommendations from the NWTSG are that preoperative chemotherapy is of benefit in patients with bilateral involvement, inoperable at surgical exploration, and IVC extension above the hepatic veins. All other patients should undergo primary nephrectomy.`, 
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `A 2-year-old boy is found to have bilateral Wilms tumor. There is a tumor occupying more than 50% of the left kidney and a 4.0-cm tumor in the upper pole of the right kidney. The best next step is:`,
        q2: ``,
        q3: [],
        option: [`left nephrectomy and right renal biopsy.`, 
        `bilateral partial nephrectomy.`, 
        `right partial nephrectomy and left renal biopsy.`, 
        `bilateral nephrectomies.`, 
        `chemotherapy.`],
        optionStyleType: `st-lower-alpha`,
        answer: [4],
        ansText:`Rationale: <!--<b>e. Chemotherapy.</b>--> Patients with bilateral Wilms tumor have an increased risk for renal failure. These patients should receive preoperative chemotherapy without attempts at initial surgery. Repeat imaging after 6 weeks of chemotherapy can assess response to treatment.`, 
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `A 1-year-old girl has a stage III Wilms tumor. During the course of chemotherapy she develops an enlarged heart and evidence of congestive heart failure. The drug responsible for these findings is most likely:`,
        q2: ``,
        q3: [],
        option: [`dactinomycin.etoposide.`, 
        `etoposide.`, 
        `vincristine.`, 
        `cyclophosphamide.`, 
        `doxorubicin.`],
        optionStyleType: `st-lower-alpha`,
        answer: [4],
        ansText:`Rationale: <!--<b>e. Doxorubicin.</b>--> In recent years, there has been increasing concern regarding the risk of congestive heart failure in children who receive treatment with anthracyclines such as doxorubicin. In addition to the acute cardiotoxicity, cardiac failure can develop many years after treatment.`, 
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `A 1-year-old boy undergoes left radical nephrectomy for a large renal mass. The pathologic features associated with the worst prognosis are:`,
        q2: ``,
        q3: [],
        option: [`diffuse anaplasia stage I.`, 
        `focal anaplasia stage III.`, 
        `rhabdoid tumor of the kidney stage III.`, 
        `clear cell sarcoma of the kidney stage III.`, 
        `favorable histology stage IV.`],
        optionStyleType: `st-lower-alpha`,
        answer: [2],
        ansText:`Rationale: <!--<b>c. Rhabdoid tumor of the kidney stage III.</b>--> Typical clinical features include early age at diagnosis (median age of &lt;16 months), resistance to chemotherapy, and high mortality rate. Unlike Wilms tumor, which typically metastasizes to the lungs, abdomen/flank, and liver, rhabdoid tumor of the kidney, which also metastasizes to these sites, is distinguished by its propensity to metastasize to the brain.`, 
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `A newborn boy was noted to have a left renal mass on prenatal ultrasound. Postnatal evaluation confirms a 5-cm solid mass in the lower pole of the left kidney. The right kidney is normal. Chest radiography and CT of the chest are negative for metastatic disease. The mass was completely removed by a radical nephrectomy. The tumor was confined to the kidney and weighed 300 g. The next step in treatment is:`,
        q2: ``,
        q3: [],
        option: [`1200-cGy abdominal irradiation to the left flank.`, 
        `observation only.`, 
        `dactinomycin and vincristine for 10 weeks.`, 
        `dactinomycin and vincristine for 18 weeks.`, 
        `2000-cGy abdominal irradiation plus dactinomycin and vincristine for 18 weeks.`],
        optionStyleType: `st-lower-alpha`,
        answer: [1],
        ansText:`Rationale: <!--<b>b. Observation only.</b>--> The most common renal tumor in a newborn is congenital mesoblastic nephroma. The important aspect of the recognition of these tumors as a separate entity is the usually excellent outcome with radical surgery only. Wilms tumors do occur rarely in neonates, but these patients are eligible for observation only on current protocols.`, 
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `The tuberous sclerosis complex is associated with the development of angiomyolipoma and cystic renal disease. These patients have been found to have an abnormality of chromosome:`,
        q2: ``,
        q3: [],
        option: [`1.`, 
        `7.`, 
        `9.`, 
        `12.`, 
        `14.`],
        optionStyleType: `st-lower-alpha`,
        answer: [2],
        ansText:`Rationale: <!--<b>c. 9.</b>--> Two genes have been identified in the tuberous sclerosis complex on chromosome 9 (TSC1) and chromosome 16 (TSC2). It has been postulated that these genes act as tumor suppressor genes and that the LOH of TSC1 or TSC2 may explain the progressive growth pattern of renal lesions seen in these patients.`, 
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`}




];
