var quiz = [
    

    {
        q: `An indication for urodynamic evaluation of a child being prepared for renal transplant is:`,
        q2: ``,
        q3: [],
        option: [`poststreptococcal glomerulonephritis-induced renal failure.`, 
        `ongoing grade III vesicoureteral reflux.`, 
        `end-stage renal disease (ESRD) in a child with nocturnal enuresis.`, 
        `prolonged anuria after focal segmental glomerulosclerosis (FSGS) renal failure.`, 
        `ESRD in a child with wetting but no urinary tract infection (UTIs).`],
        optionStyleType: `st-lower-alpha`,
        answer: [4],
        ansText:`Rationale: <!--<b>e. ESRD in a child with wetting but no urinary tract infections (UTIs).</b>--> <b>The child with ongoing wetting is the most likely to have treatable voiding dysfunction that may put the renal graft at risk.</b> Simple bladder defunctionalization with no history of underlying bladder dysfunction is unlikely to need urodynamic evaluation and often may not need bladder cycling. Reflux alone without recurrent UTI, wetting, or a neurogenic cause is not likely to benefit from urodynamics. Nocturnal enuresis is not an indication for invasive evaluation of bladder function.`, 
        state: `notAnswered`,
        userAnswered: []
    ,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`        ,
        type: `MCSS`},
    {
        q: `Renal transplantation into a child with an augmented bladder is associated with:`,
        q2: ``,
        q3: [],
        option: [`cyclosporine toxicity.`, 
        `hyperchloremic metabolic alkalosis.`, 
        `refractory rejection.`, 
        `recurrent infection and risk of sepsis.`, 
        `no significant change in graft survival.`],
        optionStyleType: `st-lower-alpha`,
        answer: [4],
        ansText:`Rationale: <!--<b>e. No significant change in graft survival.</b>--> <b>Although early reports implied a high risk due to bladder augmentation in children undergoing renal transplant, modern series have demonstrated the safety, and indeed the benefits, of providing a low-pressure urinary reservoir on graft function.</b> The incidence of positive urine cultures can be increased, but clinically significant infections are not markedly increased.`, 
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `In a 10-year-old boy with a 50-mL capacity bladder, a history of posterior urethral valves, ESRD, and anuria, optimal initial bladder management in preparation for renal transplantation is:`,
        q2: ``,
        q3: [],
        option: [`ileocystoplasty at time of renal transplantation.`, 
        `gastrocystoplasty and continent catheterizable stoma.`, 
        `bladder cycling by intermittent catheterization.`, 
        `antimuscarinic medications and proceeding with transplantation.`, 
        `transplant into transverse colon loop and delayed augmentation.`],
        optionStyleType: `st-lower-alpha`,
        answer: [2],
        ansText:`Rationale: <!--<b>c. Bladder cycling by intermittent catheterization.</b>--> <b>In the child with anuria, bladder function cannot be easily assessed until the bladder has been cycled.</b> While this child may require augmentation, that cannot be determined until after a trial of cycling is attempted. Transplanting into a diversion is not an acceptable alternative in a child who has the potential for adequate bladder function with medical management and intermittent catheterization.`, 
        state: `notAnswered`,
        userAnswered: []
    ,
	type: `MCSS`        ,
        type: `MCSS`},
    {
        q: `Indications for pre-transplant native nephrectomy include all of the following EXCEPT:`,
        q2: ``,
        q3: [],
        option: [`refractory two-drug hypertension.`, 
        `multicystic dysplastic kidney (MCDK).`, 
        `persisting grade III VUR in a 4-year-old.`, 
        `age under 12 months.`, 
        `ESRD associated with Denys-Drash syndrome.`],
        optionStyleType: `st-lower-alpha`,
        answer: [1],
        ansText:`Rationale: <!--<b>b. Multicystic dysplastic kidney (MCDK).</b>--> <b>All of these clinical situations can justify native nephrectomy except for the presence of a MCDK.</b> There is minimal to no risk of leaving the dysplastic kidney in place. Persisting reflux may be a relative indication, and some practitioners may choose to reimplant the native ureter or simply leave it alone if there is no significant history of infection. Denys-Drash kidneys are at increased risk for Wilms tumor formation. Children under 12 months in some centers do not routinely have native nephrectomy, although there is a slightly higher risk of graft loss without this.`, 
        state: `notAnswered`,
        userAnswered: []
    ,
	type: `MCSS`,
	type: `MCSS`        ,
        type: `MCSS`},
    {
        q: `A nonrefluxing transplant ureteroneocystostomy should be performed:`,
        q2: ``,
        q3: [],
        option: [`in infants only.`, 
        `in any child undergoing renal transplantation.`, 
        `only in children on intermittent catheterization.`, 
        `in children at risk for UTI or bladder dysfunction.`, 
        `only in children with neurogenic bladder dysfunction.`],
        optionStyleType: `st-lower-alpha`,
        answer: [3],
        ansText:`Rationale: <!--<b>d. In children at risk for UTI or bladder dysfunction.</b>--> <b>Any child with a risk for UTI or who has bladder dysfunction and may therefore develop a UTI, particularly if immunosuppressed, should have a nonrefluxing ureteroneocystostomy.</b> Some centers perform a nonrefluxing ureteral implantation in all children, although this is probably not essential. Older children, those with no history of bladder dysfunction, recurrent infections, or a structural abnormality, can be effectively transplanted with a refluxing ureteroneocystostomy.`, 
        state: `notAnswered`,
        userAnswered: []
    ,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`        ,
        type: `MCSS`},
    {
        q: `Following a cadaveric renal transplant for FSGS, a 10-year-old boy is found to have distal ureteral obstruction from a 4-cm stricture that fails balloon dilation and stenting. The best option for management is:`,
        q2: ``,
        q3: [],
        option: [`ileal interposition.`, 
        `Boari flap to graft pelvis.`, 
        `transplant nephrectomy.`, 
        `psoas hitch transplant ureteroneocystostomy.`, 
        `transplant ureter to native ureteroureterostomy.`],
        optionStyleType: `st-lower-alpha`,
        answer: [3],
        ansText:`Rationale: <!--<b>d. Psoas hitch transplant ureteroneocystostomy.</b>--> <b>Several options are available for salvage of the graft in this situation, but the most effective is a psoas hitch when there is still some graft ureter available.</b> A transplant to native ureteroureterostomy is effective but may require nephrectomy in some cases. Boari flaps may be useful for cases in which the entire ureter is lost or if there is no native ureter remaining. Even with loss of the entire ureter, a renal pelvis to native ureter anastomosis is effective. Ileal interposition and graft nephrectomy are not viable options.`, 
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `Six months following an uncomplicated living related donor renal transplant for FSGS and prior native nephrectomies, a 7-year-old girl develops acute pyelonephritis of the graft with a rise in creatinine. There is no hydronephrosis on ultrasound. A voiding cystourethrogram (VCUG) demonstrates grade III reflux into the graft, but none in the native ureters. She has normal voiding patterns. The best option for management is:`,
        q2: ``,
        q3: [],
        option: [`urodynamic evaluation and MR of the spine.`, 
        `transplant ureter to native ureteroureterostomy.`, 
        `endoscopic injection of subureteral bulking agent.`, 
        `6 months of antibiotic prophylaxis and observation.`, 
        `continuous antibiotic prophylaxis and repeat studies in 18 months anticipating spontaneous resolution.`],
        optionStyleType: `st-lower-alpha`,
        answer: [1],
        ansText:`Rationale: <!--<b>b. Transplant ureter to native ureteroureterostomy.</b>--> <b>The best option in this situation is redo open reimplantation to create an effective antireflux tunnel or transplant to native ureteroureterostomy if there is sufficient native ureter.</b> In the absence of a prior urologic history, urodynamic evaluation and investigation for an occult spinal dysraphism is unlikely to be of value. Spontaneous resolution is highly unlikely, and simply waiting for another episode of pyelonephritis risks graft injury. Endoscopic injection has a limited success rate in published series and the durability is undefined. In the setting where another episode of pyelonephritis is associated with significant risk to the graft, such an approach does not seem prudent.`, 
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `Eighteen months following an uncomplicated living related renal transplant, a 5-year-old boy with a history of posterior urethral valves develops a rising serum creatinine level, graft hydronephrosis, and two febrile UTIs. VCUG shows grade III reflux into the graft and moderate bladder trabeculation similar to his pre-transplant pattern. The next step in his care is:`,
        q2: ``,
        q3: [],
        option: [`psoas hitch ureteral reimplantation.`, 
        `nontunneled ureteroneocystostomy.`, 
        `ileo-cystoplasty and appendicovesicostomy.`, 
        `transplant ureter to native ureteroureterostomy (U-U).`, 
        `urodynamic evaluation and likely antimuscarinics and intermittent catheterization.`],
        optionStyleType: `st-lower-alpha`,
        answer: [4],
        ansText:`Rationale: <!--<b>e. Urodynamic evaluation and likely antimuscarinics and intermittent catheterization.</b>--> <b>This boy is best served by a formal assessment of his bladder function with likely use of antimuscarinics to improve capacity and compliance and intermittent catheterization to provide for emptying.</b> One can start this therapy empirically, but having a baseline permits assessment of the treatment effect. Moving directly to augmentation without knowing if medical management can be effective is not appropriate. Simply reimplanting the ureter or performing a U-U without treating the likely bladder dysfunction is also not appropriate.`, 
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `Twenty-four hours after removal of a ureteral stent, an 8-year-old boy has minimal urine output and develops right lower quadrant tenderness. Two months prior, he had a living related renal transplant following bilateral nephrectomies, radiation, chemotherapy, and surveillance for stage 5 Wilms tumors. A Foley catheter was placed, draining 5 mL of clear urine in 2 hours. He underwent urgent ultrasound evaluation (<a class="lightboxcallout" img-ref="image_fig_51_1" href="76581d20e58e485dbb53da8d7bc066b9">Fig. 51.1</a>). What is the next step in management?`,
        q2: ``,
        q3: [],
        option: [`Replacement of ureteral stent`, 
        `Renal (allograft) biopsy`, 
        `Percutaneous nephrostomy placement`, 
        `Percutaneous drainage of fluid collection`, 
        `Treat for rejection with high-dose steroids`],
        optionStyleType: `st-lower-alpha`,
        answer: [3],
        ansText:`Rationale: <!--<b>d. Percutaneous drainage of fluid collection.</b>--> <b>This boy has a large fluid collection and associated hydronephrosis. The most likely cause of his oligo-anuria is extrinsic ureteral compression due to a lymphocele.</b> Other causes need to be considered, including urinoma formation (and active perinephric urine leak). The next step is to drain the fluid collection and send the fluid for analysis and culture. This will determine the best course of action. Stent replacement and percutaneous nephrostomy placement will help with urine drainage yet fail to secure a diagnosis. A renal biopsy is unlikely to add to the diagnosis, except in the unlikely case that this represents rejection. Similarly, high-dose steroids will not address the most likely etiology, and can be harmful in less likely but important complications in the differential, most notably a perinephric abscess.`, 
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`}



];
