var quiz = [
    

    {
        q: `A man with chronic pelvic pain has a negative urine culture and no evidence of inflammation on expressed prostatic secretions (EPS) or VB3 or in his seminal plasma. What is his category of prostatitis in the NIH classification?`,
        q2: ``,
        q3: [],
        option: [`Category I`, 
        `Category II`, 
        `Category IIIA`, 
        `Category IIIB`, 
        `Category IV`],
        optionStyleType: `st-lower-alpha`,
        answer: [4],
        ansText:`Rationale: <!--<b>d. Category IIIB.</b>--> The NIH classification is IIIB, chronic prostatitis chronic pelvic pain syndrome. He has no infection to suggest acute or chronic bacterial prostatitis, and he is symptomatic and therefore not category IV. The absence of inflammatory cells separates the subclasses of IIA and IIIB. He has no inflammation on EPS, VB3, or seminal plasma and therefore is category IIIB.`, 
        state: `notAnswered`,
        userAnswered: []
    ,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`        ,
        type: `MCSS`},
    {
        q: `A 65-year-old male undergoes a transrectal ultrasound-guided biopsy for an elevated PSA. He has no pelvic pain. Biopsy shows no cancer, but he does have many areas of prostate inflammation. What is his NIH prostatitis category?`,
        q2: ``,
        q3: [],
        option: [`Category I`, 
        `Category II`, 
        `Category IIIA`, 
        `Category IIIB`, 
        `Category IV`],
        optionStyleType: `st-lower-alpha`,
        answer: [4],
        ansText:`Rationale: <!--<b>e. Category IV.</b>--> Category IV is asymptomatic inflammatory prostatitis. Asymptomatic means no symptoms of pelvic pain. This usually diagnosed on specimens taken for treatment of other problems such as BPH, prostate cancer, or infertility.`, 
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `A 58-year-old male with a history of autoimmune pancreatitis presents urinary retention. He is refractory to medical therapy for benign prostatic hyperplasia (BPH), and a transurethral resection of the prostate (TURP) is planned. What type of histology may be expected from the prostate resection?`,
        q2: ``,
        q3: [],
        option: [`No inflammation`, 
        `Granulomatous prostatitis`, 
        `Scant periglandular mononuclear infiltrate`, 
        `Heavy intraductal lymphocytic infiltrate`, 
        `Immunoglobulin G4 (IgG4)-positive plasma cells and fibrosis`],
        optionStyleType: `st-lower-alpha`,
        answer: [4],
        ansText:`Rationale: <!--<b>e. Immunoglobulin G4 (IgG4)-positive plasma cells and fibrosis.</b>--> IgG4-positive plasma cells and a characteristic pattern of fibrosis are seen in IgG4 disease. First described in autoimmune pancreatitis, multiple previously described disorders including Ormond disease (retroperitoneal fibrosis) are currently considered to fall within this category. One of the characteristics of IgG4 disease is a dramatic response to corticosteroids.`, 
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `What is the most common causative organism in patients with category I acute bacterial prostatitis that develops after lower urinary tract manipulation?`,
        q2: ``,
        q3: [],
        option: [`<i>Escherichia coli</i>`, 
        `<i>Pseudomonas</i>`, 
        `<i>Proteus</i>`, 
        `<i>Klebsiella</i>`, 
        `<i>Enterococcus</i>`],
        optionStyleType: `st-lower-alpha`,
        answer: [0],
        ansText:`Rationale: <!--<b>a. <i>Escherichia coli.</i></b>--> Although <b><i>E. coli</i></b> is still the most commonly found organism in patients with acute bacterial prostatitis (ABP) after lower urinary tract manipulation, <b><i>Pseudomonas</i></b> is far more common in cases from manipulation compared with spontaneous or after transrectal prostate biopsy.`, 
        state: `notAnswered`,
        userAnswered: []
    ,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`        ,
        type: `MCSS`},
    {
        q: `A man presents after transrectal prostate biopsy with a fever of 102°F, rigors, and many white blood cells and bacteria in the urine. Which antibiotic is the best choice for initial therapy until urine and blood culture results are available?`,
        q2: ``,
        q3: [],
        option: [`Ciprofloxacin`, 
        `Levofloxacin`, 
        `Trimethoprim-sulfamethoxazole`, 
        `Cefpodoxime`, 
        `Meropenem`],
        optionStyleType: `st-lower-alpha`,
        answer: [4],
        ansText:`Rationale: <!--<b>e. Meropenem.</b>--> The Update of the American Urological Association White Paper on the prevention and treatment of complications after prostate biopsy recommends that patients who present with a fever after prostate biopsy should not be offered fluoroquinolones or trimethoprim-sulfamethoxazole. Management should consist of aggressive resuscitation and broad-spectrum antibiotic coverage—carbapenems, amikacin, or second- and third-generation cephalosporin (after urine and blood cultures).`, 
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `A 35-year-old human immunodeficiency virus (HIV)-positive man presents with fever, dysuria, and leukocytosis. Imaging reveals a 0.9-cm hypoechoic area in the prostate consistent with a prostate abscess. Initial management for this patient is:`,
        q2: ``,
        q3: [],
        option: [`intravenous (IV) antibiotics`, 
        `prostate massage to help drain the abscess`, 
        `percutaneous aspiration`, 
        `transurethral resection`, 
        `open perineal drainage`],
        optionStyleType: `st-lower-alpha`,
        answer: [0],
        ansText:`Rationale: <!--<b>a. Intravenous (IV) antibiotics.</b>--> In men with prostate abscess, smaller lesions less than 1 to 2 cm can be treated conservatively with antibiotics. Larger lesions or lesions that do not respond to antibiotics can be treated with percutaneous aspiration or transurethral unroofing.`, 
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `A 41-year-old male presents with his second urinary tract infection in the past 4 months. He is growing the same <i>E. coli</i> as his previous culture. Evaluation should include:`,
        q2: ``,
        q3: [],
        option: [`computed tomography (CT) urogram`, 
        `uroflow and postvoid residual urine to rule out retention`, 
        `cystoscopy`, 
        `four-glass urine test`, 
        `nuclear amplification test for gonorrhea and chlamydia`],
        optionStyleType: `st-lower-alpha`,
        answer: [1],
        ansText:`Rationale: <!--<b>b. Uroflow and postvoid residual urine to rule out retention.</b>--> In a man younger than 45 years, imaging is not usually helpful. A cystoscopy could be done if he has an elevated residual to rule out stricture if he has a decreased uroflow and elevated postvoid residual urine. The four-glass test is no longer routinely used for cases of suspected chronic bacterial prostatitis. The nuclear amplification test would be indicated if he had a urethral discharge.`, 
        state: `notAnswered`,
        userAnswered: []
    ,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`        ,
        type: `MCSS`},
    {
        q: `What is the relationship between inflammation (white blood cells [WBCs]) found in expressed prostatic fluid and symptoms in men with chronic pelvic pain syndrome?`,
        q2: ``,
        q3: [],
        option: [`Greater WBCs in men with predominantly voiding symptoms plus pelvic pain`, 
        `Inverse correlation between WBCs and symptoms`, 
        `Direct correlation between WBCs and symptoms`, 
        `No correlation between WBCs and symptoms`, 
        `Greater WBCs only in men with prior history of acute prostatitis`],
        optionStyleType: `st-lower-alpha`,
        answer: [3],
        ansText:`Rationale: <!--<b>d. No correlation between WBCs and symptoms.</b>--> No correlation between WBCs and symptoms. In the Chronic Prostatitis Collaborative Research Network (CPCRN) study, men with no symptoms had equal amounts of inflammation in EPS as those with pelvic pain.`, 
        state: `notAnswered`,
        userAnswered: []
    ,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`        ,
        type: `MCSS`},
    {
        q: `What psychological factor is correlated with overall pain along with urinary symptoms and depression in men with chronic prostatitis/chronic pelvic pain syndrome (CP/CPPS)?`,
        q2: ``,
        q3: [],
        option: [`Neuroticism <b>START</b>`, 
        `Obsessive compulsive disorder`, 
        `Anger`, 
        `Catastrophizing`, 
        `Insecurity`],
        optionStyleType: `st-lower-alpha`,
        answer: [4],
        ansText:`Rationale: <!--<b>d. Catastrophizing.</b>--> Helplessness and catastrophizing predict overall pain along with urinary symptoms and depression in men with CP/CPPS.`, 
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `What is the most common overlapping pain condition (COPC) in men with CP/CPPS?`,
        q2: ``,
        q3: [2],
        option: [`Fibromyalgia`, 
        `Chronic fatigue syndrome`, 
        `Irritable bowel syndrome (IBS)`, 
        `Temporomandibular joint disorder`, 
        `Tinnitus`],
        optionStyleType: `st-lower-alpha`,
        answer: [2],
        ansText:`Rationale: <!--<b>c. Irritable bowel syndrome (IBS).</b>--> The most COPC is IBS. Men should be queried about signs and symptoms of bowel dysfunction such as constipation, diarrhea, and the relationship to pelvic pain to bowel movements. Referral to a gastroenterologist should be made if indicated.`, 
        state: `notAnswered`,
        userAnswered: []
    ,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`        ,
        type: `MCSS`},
    {
        q: `In a case-crossover study in the NIH Multidisciplinary Approach to Pelvic Pain (MAPP) study, what correlated with development of symptom flares?`,
        q2: ``,
        q3: [],
        option: [`Psychological stress`, 
        `Caffeine`, 
        `Alcohol`, 
        `Recent sexual activity`, 
        `Physical activity`],
        optionStyleType: `st-lower-alpha`,
        answer: [3],
        ansText:`Rationale: <!--<b>d. Recent sexual activity.</b>--> Only recent sexual activity and urinary tract infection (UTI)-like symptoms were predictive of flare. Items that did not predict a flare included diet, physical activity or sedentary behavior, stress, and constipation.`, 
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `Compared with age-matched controls, men with CP/CPPS have a greater prevalence of which of the following?`,
        q2: ``,
        q3: [],
        option: [`BPH`, 
        `Urinary incontinence`, 
        `Premature ejaculation`, 
        `Condyloma`, 
        `Phimosis`],
        optionStyleType: `st-lower-alpha`,
        answer: [2],
        ansText:`Rationale: <!--<b>c. Premature ejaculation.</b>--> Men with CP/CPPS are more likely to have ejaculatory pain and premature ejaculation.`, 
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `The NIH–Chronic Prostatitis Symptom Index (NIH-CPSI) score has been used in many trials as an outcome measure for treatment of CP/CPPS. It is also used for diagnosis and epidemiologic studies. The Genitourinary Problem Index (GUPI) is a modified version that better reflects what symptoms found in men with CP/CPPS but not part of the NIH-CPSI?`,
        q2: ``,
        q3: [],
        option: [`Penile pain`, 
        `Epididymal pain`, 
        `Scrotal skin pain`, 
        `Back pain`, 
        `Pain with bladder filling`],
        optionStyleType: `st-lower-alpha`,
        answer: [4],
        ansText:`Rationale: <!--<b>e. Pain with bladder filling.</b>--> The GUPI is a modified version that contains questions about bladder pain. These symptoms were found in approximately 40% of men in the NIH-sponsored MAPP study.`, 
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `Which of the following is an optional study in the evaluation of men with CP/CPPS?`,
        q2: ``,
        q3: [],
        option: [`Symptom assessment`, 
        `Midstream urine for urinalysis and culture`, 
        `Abdominal exam`, 
        `Examination of pelvic floor tender points`, 
        `Cystoscopy`],
        optionStyleType: `st-lower-alpha`,
        answer: [4],
        ansText:`Rationale: <!--<b>e. Cystoscopy.</b>--> Cystoscopy is an optional study. Cystoscopy can be used in men with decreased uroflow and/or elevated postvoid residual urine to evaluate for urethral stricture. Cystoscopy should also be used in men who give a history of pain with bladder emptying and/or relieved by bladder emptying, suggestive of interstitial cystitis/bladder pain syndrome (IC/BPS) because in a small set of these patients, a Hunner ulcer is present which responds to fulguration or intralesional injections.`, 
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `On electromyography (EMG) study during urodynamics, a man with pelvic pain, poor stream, and pain with sitting has retained electrical activity of the external sphincter during voiding. He is grossly neurologically intact. What is his diagnosis?`,
        q2: ``,
        q3: [],
        option: [`Detrusor underactivity`, 
        `Upper motor neuron lesion`, 
        `Pseudodyssynergy`, 
        `Urethralis fugax`, 
        `Detrusor overactivity`],
        optionStyleType: `st-lower-alpha`,
        answer: [2],
        ansText:`Rationale: <!--<b>c. Pseudodyssynergy.</b>--> Pseudodyssynergy is retained electrical activity of the external sphincter during voiding in the absence of abdominal straining, and/or brief and intermittent closing of the membranous urethra during voiding detected by electromyography, or fluoroscopy in videourodynamics. These men are considered to have pelvic floor dysfunction.`, 
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `In meta-analyses of treatments for CP/CPPS, which combinations of therapy show the best results?`,
        q2: ``,
        q3: [],
        option: [`Antiinflammatory medications and α-blockers`, 
        `Antibiotics and α-blockers`, 
        `5α-reductase inhibitors and α-blockers`, 
        `Skeletal muscle relaxants and antiinflammatory medications`, 
        `Antibiotics and 5α-reductase inhibitors`],
        optionStyleType: `st-lower-alpha`,
        answer: [1],
        ansText:`Rationale: <!--<b>b. Antibiotics and α-blockers.</b>--> Meta-analyses have shown the best response for a combination of antibiotics and α-blockers.`, 
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `A 38-year-old male presents with a 4-month history of pelvic pain. Urine cultures are negative. He has some generalized increase in anxiety. On exam, he has significant increase in tone of the pelvic floor muscles around the prostate, especially the obturator internus. Management should consist of stress reduction and which of the following?`,
        q2: ``,
        q3: [],
        option: [`Referral to a psychiatrist`, 
        `Oral valium`, 
        `Microwave thermotherapy`, 
        `Pelvic floor physical therapy`, 
        `Injection of onabotulinumtoxinA into the perineal body`],
        optionStyleType: `st-lower-alpha`,
        answer: [3],
        ansText:`Rationale: <!--<b>d. Pelvic floor physical therapy.</b>--> Although he has anxiety, the best treatment is addressing the increased pelvic floor tension by referral a physical therapist for pelvic floor physical therapy (PT).`, 
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `A 65-year-old male undergoes prostate biopsy for an elevated PSA of 5.4. Pathology reveals extensive glandular and periglandular inflammation with both acute and chronic inflammation. The best next step is:`,
        q2: ``,
        q3: [],
        option: [`4-week course of antiinflammatory medications.`, 
        `start finasteride.`, 
        `4-week course of antibiotics and then reassess.`, 
        `observation.`, 
        `repeat biopsy.`],
        optionStyleType: `st-lower-alpha`,
        answer: [3],
        ansText:`Rationale: <!--<b>d. Observation.</b>--> No treatment for asymptomatic prostate inflammation (category IV) is necessary. Treatment with antibiotics is not indicated and should not be used to “treat” his elevated PSA to try to get it back to normal levels. He should be followed for his PSA elevation and have periodic repeat PSA and digital rectal examinations.`, 
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `UPOINT is a phenotyping tool that captures multiple aspects of symptoms and finding in men with CPPS. What does the “N” stand for in UPOINT?`,
        q2: ``,
        q3: [],
        option: [`Nonbacterial`, 
        `Noninflammatory`, 
        `Neurologic`, 
        `Normal prostate exam`, 
        `Normotensive`],
        optionStyleType: `st-lower-alpha`,
        answer: [2],
        ansText:`Rationale: <!--<b>c. Neurologic.</b>--> The N stands for Neurologic. This is for men with widespread pain conditions, with pain outside the pelvis, and overlapping conditions such as IBS, fibromyalgia, or chronic fatigue syndrome. They are thought to possibly have upregulation of the sensitivity of their central nervous system (centralization or central sensitization) and may respond to medications that treat neuropathic pain.`, 
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `Autoimmune orchitis is characterized by the presence of:`,
        q2: ``,
        q3: [],
        option: [`antisperm antibodies (ASAs)`, 
        `antisperm granulomas`, 
        `testicular microinfarcts`, 
        `microlithiasis`, 
        `antilipid antibodies`],
        optionStyleType: `st-lower-alpha`,
        answer: [0],
        ansText:`Rationale: <!--<b>a. Antisperm antibodies (ASAs).</b>--> Autoimmune orchitis is defined as an autoimmune aggression of the testes characterized by the presence of ASAs. Primary autoimmune orchitis is primarily a problem in the evaluation of male infertility. The main causes of secondary autoimmune orchitis are usually associated with a primary vasculitis, particularly Behçet disease, polyarteritis nodosa, and Henoch-Schönlein purpura.`, 
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `A 25-year-old male presents with the acute onset of left epididymal pain. The left epididymis is tender to palpation and swollen. There are 1 to 3 WBCs per high-power field on urinalysis. He is afebrile. He denies being sexually active. The most likely cause for his acute epididymitis is:`,
        q2: ``,
        q3: [],
        option: [`<i>E. coli</i>`, 
        `Pseudomonas`, 
        `Proteus`, 
        `Brucellosis`, 
        `Chlamydia`],
        optionStyleType: `st-lower-alpha`,
        answer: [4],
        ansText:`Rationale: <!--<b>e. Chlamydia.</b>--> Sexually transmitted diseases and particularly chlamydia are the most common cause of acute epididymitis. Patient should be suspected of chlamydia even if they deny recent intercourse, because the infection does not always correlate with the reported sexual history.`, 
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `A 39-year-old male has had chronic orchialgia for 1 year. He has failed a course of antibiotics and antiinflammatory medications. He has no other medical conditions and no back pain. On examination his right testis is mildly tender. On digital rectal exam he has minimal prostate tenderness but has tenderness to the right obturator internus muscle. The next best step in treatment is:`,
        q2: ``,
        q3: [],
        option: [`gabapentin`, 
        `pregabalin`, 
        `pelvic floor physical therapy`, 
        `microsurgical denervation of the right spermatic cord`, 
        `referral to pain management`],
        optionStyleType: `st-lower-alpha`,
        answer: [2],
        ansText:`Rationale: <!--<b>c. Pelvic floor physical therapy.</b>--> He has signs or history to suggest a centralized pain condition. Pelvic floor therapy is emerging as a treatment for chronic orchialgia. All conservative measures should be tried prior to undergoing surgery.`, 
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `Which area is part of the so-called trifecta nerve complex that should be addressed in microsurgical denervation of the spermatic cord for chronic scrotal pain?`,
        q2: ``,
        q3: [],
        option: [`Epididymal tail`, 
        `Cremasteric muscle fibers`, 
        `Rete testis`, 
        `Epididymal tail`, 
        `Testicular artery`],
        optionStyleType: `st-lower-alpha`,
        answer: [1],
        ansText:`Rationale: <!--<b>b. Cremasteric muscle fibers.</b>--> Three areas identified by Parekatil et al. that had the highest areas of wallerian degeneration (WD) were the cremasteric muscle fibers, the perivasal sheath, and the posterior lipomatous tissue; these areas were called the trifecta nerve complex and is thought to form the anatomic basis for relief from the denervation procedure.`, 
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `What technique has been noted to increase the success rate of epididymectomy performed for post vasectomy pain syndrome?`,
        q2: ``,
        q3: [],
        option: [`Ligation of surrounding lymphatics`, 
        `Ligation of the spermatic veins`, 
        `Preservation of surrounding lymphatics`, 
        `Incorporation of the distal portion of the vasectomy site`, 
        `Inguinal approach`],
        optionStyleType: `st-lower-alpha`,
        answer: [3],
        ansText:`Rationale: <!--<b>d. Incorporation of the distal portion of the vasectomy site.</b>--> Better rates are reported in cases with incorporation of the distal portion of the vasectomy site with the epididymectomy specimen.`, 
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `What technique has been reported to increase the success rate of orchiectomy for chronic scrotal pain?`,
        q2: ``,
        q3: [],
        option: [`Ligation of surrounding lymphatics`, 
        `Ligation of the spermatic veins`, 
        `Preservation of surrounding lymphatics`, 
        `Scrotal approach`, 
        `Inguinal approach`],
        optionStyleType: `st-lower-alpha`,
        answer: [4],
        ansText:`Rationale: <!--<b>e. Inguinal approach.</b>--> Better results have been reported with the inguinal approach to orchiectomy performed for chronic scrotal pain.`, 
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`}




];
