var quiz = [
  {
    q: `<!--1. -->Patients with complex congenital urologic conditions:`,
    q2: ``,
    q3: [],
    option: [
      `<!--a. -->are unlikely to require surgery in adulthood.`,
      `<!--b. -->prefer to be looked after in a general urology clinic.`,
      `<!--c. -->generally do not work as adults.`,
      `<!--d. -->desire to be normal.`,
      `<!--e. -->can usually be discharged from care after 18 years of age.`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [3],
    ansText: `Rationale: This a fundamental element of looking after patients with major congenital urologic anomalies. As they move into adulthood, they commonly express a desire to be normal and may exert their independence to try and appear more so—i.e., by not coming to a hospital or not catheterizing. Many will need lifelong care, many work, many prefer to be looked after in a clinic with an expertise in their (rare) condition, and a significant number will need surgery as adults.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `<!--2. -->Effective transition requires:`,
    q2: ``,
    q3: [],
    option: [
      `<!--a. -->a clear plan by the age of 14 years.`,
      `<!--b. -->a purposeful process to get a young adult to take responsibility for their health.`,
      `<!--c. -->preparation of the family.`,
      `<!--d. -->trust between pediatric and adolescent/adult teams.`,
      `<!--e. -->all of the above.`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [4],
    ansText: `Rationale: Planning and preparation definitely make life easier for patients, parents, and those looking after the patients as they move into adulthood. It appears to significantly reduce anxiety and improve engagement, and trust between the team who have looked after the patient in childhood and the adult team is important.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `<!--3. -->Adolescent urology training requires:`,
    q2: ``,
    q3: [],
    option: [
      `<!--a. -->a fellowship in plastic surgery.`,
      `<!--b. -->board certification (or equivalent) in urology.`,
      `<!--c. -->a fellowship in adolescent medicine.`,
      `<!--d. -->1 year of training in psychology.`,
      `<!--e. -->all of the above.`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [1],
    ansText: `Rationale: This is the only requirement at present. A urology training program will offer most of the skills required. Important elements are training in complex pediatric urology and reconstructive urology. Psychology can be very important, hence it is important to have a trained member on the multidisciplinary team.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `<!--4. -->Regarding young adults with congenital anomalies of the urogenital system:`,
    q2: ``,
    q3: [],
    option: [
      `<!--a. -->boys with posterior urethral valves commonly have a dorsal chordee.`,
      `<!--b. -->all young men with corrected hypospadias need lifelong follow-up.`,
      `<!--c. -->an augmentation cystoplasty can lead to a false-positive urinary pregnancy test.`,
      `<!--d. -->patients with spina bifida often die as a result of renal failure.`,
      `<!--e. -->in a boy with exstrophy, the testes are usually badly damaged.`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [2],
    ansText: `Rationale: Data suggest this happens in 57% of augmentation cystoplasty cases. The testes are normal in exstrophy, valve boys would be expected to have a normal penis, mild forms of hypospadias do not usually need long-term follow-up—just information on who to contact if they do have problems. With aggressive early bladder management (clean intermittent catheterization [CIC] and antimuscarinics) deaths from renal failure have dramatically decreased in patients affected by spina bifida.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `<!--5. -->In which of the following situations should elective cesarean section be performed for urologic indications?`,
    q2: ``,
    q3: [],
    option: [
      `<!--a. -->With an artificial urinary sphincter`,
      `<!--b. -->Women with exstrophy and an augmentation cystoplasty`,
      `<!--c. -->Women with a glomerular filtration rate (GFR) below 40 mL/min/m<sup>2</sup>`,
      `<!--d. -->Women with a neuropathic bladder`,
      `<!--e. -->Women with simple (nonsalt-wasting) congenital adrenal hyperplasia`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [1],
    ansText: `Rationale: A cystoplasty on its own is not an absolute indication for a caesarean section—if the pelvis is otherwise normal, a vaginal delivery may be possible (this is an obstetric decision). Fundamentally, it is important to avoid a caesarean section without appropriate urologic support—elective sections should be planned with such a urologist present, and unless such expertise is available 24 hours a day seven days a week, then an emergency caesarean section should be avoided.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `<!--6. -->In boys with posterior urethral valves:`,
    q2: ``,
    q3: [],
    option: [
      `<!--a. -->intervention in utero will prevent the need for renal transplant in adulthood.`,
      `<!--b. -->fertility will likely be normal.`,
      `<!--c. -->60% will have urinary incontinence.`,
      `<!--d. -->there is no increased risk of proteinuria.`,
      `<!--e. -->bladder function will be normal if valves are incised in the first month of life.`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [1],
    ansText: `Rationale: For many years this was not thought to be the case. More recent data suggest that fertility is likely to be normal.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
];
