var quiz = [
  {
    q: `Acute pyelonephritis is the most likely diagnosis in a patient with:`,
    q2: ``,
    q3: [],
    option: [
      `chills, fever, and flank pain.`,
      `bacteria and pyuria.`,
      `focal scar in renal cortex.`,
      `delayed renal function.`,
      `vesicoureteral reflux.`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [0],
    ansText: `Rationale: <!--<b>a. Chills, fever, and flank pain.</b>--> Acute pyelonephritis is a clinical syndrome of chills, fever, and flank pain that is accompanied by bacteriuria and pyuria, a combination that is reasonably specific for an acute bacterial infection of the kidney.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `Bacteriuria without pyuria is indicative of:`,
    q2: ``,
    q3: [],
    option: [
      `infection.`,
      `colonization.`,
      `tuberculosis.`,
      `contamination.`,
      `stones.`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [1],
    ansText: `Rationale: <!--<b>b. Colonization.</b>--> Bacteriuria without pyuria is generally indicative of bacterial colonization without infection of the urinary tract.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `Nosocomial urinary tract infections (UTIs):`,
    q2: ``,
    q3: [],
    option: [
      `occur in patients who are hospitalized or institutionalized.`,
      `are caused by common bowel bacteria.`,
      `can be suppressed by low-dose antimicrobial therapy.`,
      `are due to reinfection.`,
      `are due to bacterial persistence.`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [0],
    ansText: `Rationale: <!--<b>a. Occur in patients who are hospitalized or institutionalized.</b>--> Nosocomial or health care–associated UTIs occur in patients who are hospitalized or institutionalized and may be caused by <b><i>Pseudomonas</i></b> and other more antimicrobial-resistant strains.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `Most recurrent infections in female patients are:`,
    q2: ``,
    q3: [],
    option: [
      `complicated.`,
      `reinfections.`,
      `due to bacterial resistance.`,
      `due to hereditary susceptibility factors.`,
      `composed of multiple organisms.`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [1],
    ansText: `Rationale: <!--<b>b. Reinfections.</b>--> Recurrent infections are hypothesized to be secondary to either bacterial persistence within the urinary tract or, more commonly, novel reinfection. Persistence, caused by the same bacterial strain, usually leads to recurrent infections in a short time frame, whereas reinfections generally occur over a more remote period. Reinfection is likely secondary to ascent of uropathogens from fecal flora into the urinary tract or from reemergence of bacteria from uroepithelial intracellular colonies.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `Rates of reinfection (i.e., time to recurrence) are influenced by:`,
    q2: ``,
    q3: [],
    option: [
      `bladder dysfunction.`,
      `renal scarring.`,
      `vesicoureteral reflux.`,
      `antimicrobial treatment.`,
      `age.`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [3],
    ansText: `Rationale: <!--<b>d. Antimicrobial treatment.</b>--> Whether a patient receives no treatment or short-term, long-term, or prophylactic antimicrobial treatment, the risk of recurrent bacteriuria remains the same.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `The long-term effect of uncomplicated recurrent UTIs is:`,
    q2: ``,
    q3: [],
    option: [
      `renal scarring.`,
      `hypertension.`,
      `azotemia.`,
      `ureteral vesical reflux.`,
      `minimal.`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [4],
    ansText: `Rationale: <!--<b>e. Minimal.</b>--> The long-term effects of uncomplicated recurrent UTIs are not completely known, but so far, <b>no association between recurrent infections and renal scarring, hypertension, or progressive renal azotemia</b> has been established.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `The ascending route of infection is least enhanced by:`,
    q2: ``,
    q3: [],
    option: [
      `catheterization.`,
      `spermicidal agents.`,
      `indwelling catheter.`,
      `fecal soilage of perineum.`,
      `frequent voiding.`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [4],
    ansText: `Rationale: <!--<b>e. Frequent voiding.</b>--> This route is further enhanced in individuals with significant soilage of the perineum with feces, women using spermicidal agents, and patients with intermittent or indwelling catheters.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `Approximately 10% of symptomatic lower UTIs in young, sexually active female patients are caused by:`,
    q2: ``,
    q3: [],
    option: [
      `<i>Escherichia coli (E. coli).</i>`,
      `<i>Staphylococcus saprophyticus.</i>`,
      `<i>Pseudomonas.</i>`,
      `<i>Proteus mirabilis.</i>`,
      `<i>Staphylococcus epidermidis.</i>`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [1],
    ansText: `Rationale: <!--<b>b. <i>Staphylococcus saprophyticus.</i></b>--> <b><i>S. saprophyticus</i></b> is recognized as causing frequent symptomatic UTIs in young, sexually active females, whereas it rarely causes infection in males and elderly individuals.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `The virulence factor that is most important for adherence is:`,
    q2: ``,
    q3: [],
    option: [
      `hemolysin.`,
      `K antigen.`,
      `pili.`,
      `colicin production.`,
      `O serogroup.`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [2],
    ansText: `Rationale: <!--<b>c. Pili.</b>--> Studies have demonstrated that interactions between FimH and receptors expressed on the luminal surface of the bladder epithelium are critical to the ability of many uropathogenic <b><i>E. coli</i></b> strains to colonize the bladder and cause disease.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `Phase variation of bacterial pili:`,
    q2: ``,
    q3: [],
    option: [
      `occurs only in vitro.`,
      `affects bacterial virulence.`,
      `is characteristic of pyelonephritic <i>E. coli.</i>`,
      `is irreversible.`,
      `refers to change in pilus length.`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [1],
    ansText: `Rationale: <!--<b>b. Affects bacterial virulence.</b>--> This process is called <b><i>phase variation</i></b> and has obvious biologic and clinical implications. For example, the presence of type 1 pili may be advantageous to the bacteria for adhering to and colonizing the bladder mucosa but disadvantageous because the pili enhance phagocytosis and killing by neutrophils.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `The finding that first suggested a biologic difference in women susceptible to UTIs is:`,
    q2: ``,
    q3: [],
    option: [
      `increased adherence of bacteria to vaginal cells.`,
      `decreased estrogen concentration in vaginal cells.`,
      `elevated vaginal pH.`,
      `nonsecretor status.`,
      `postmenopausal status.`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [0],
    ansText: `Rationale: <!--<b>a. Increased adherence of bacteria to vaginal cells.</b>--> These studies established increased adherence of pathogenic bacteria to vaginal epithelial cells as the first demonstrable biologic difference that could be shown in women susceptible to UTI.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `The primary bladder defense is:`,
    q2: ``,
    q3: [],
    option: [
      `low urine pH.`,
      `low urine osmolarity.`,
      `voiding.`,
      `Tamm-Horsfall protein (uromucoid).`,
      `vaginal mucus.`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [2],
    ansText: `Rationale: <!--<b>c. Voiding.</b>--> Bacteria presumably make their way into the bladder fairly often. Whether small inocula of bacteria persist, multiply, and infect the host depends in part on the ability of the bladder to empty.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `The most significant sequela of renal papillary necrosis is renal:`,
    q2: ``,
    q3: [],
    option: [`failure.`, `abscess.`, `obstruction.`, `stone.`, `cancer.`],
    optionStyleType: `st-lower-alpha`,
    answer: [2],
    ansText: `Rationale: <!--<b>c. Obstruction.</b>--> A patient who suffers from an acute ureteral obstruction caused by a sloughed papilla and who has a concomitant UTI should have the condition treated as a urologic emergency.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `Severity and morbidity of bacteriuria is most morbid in patients with:`,
    q2: ``,
    q3: [],
    option: [
      `spinal cord injuries.`,
      `pregnancy.`,
      `reflux.`,
      `diabetes mellitus.`,
      `human immunodeficiency virus (HIV) infection.`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [0],
    ansText: `Rationale: <!--<b>a. Spinal cord injuries.</b>--> Of all patients with bacteriuria, no group compares in severity and morbidity with those who have spinal cord injury.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `The validity of a midstream urine specimen should be questioned if microscopy reveals:`,
    q2: ``,
    q3: [],
    option: [
      `squamous epithelial cells.`,
      `red blood cells.`,
      `bacteria.`,
      `white blood cells.`,
      `casts.`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [0],
    ansText: `Rationale: <!--<b>a. Squamous epithelial cells.</b>--> The validation of the midstream urine specimen can be questioned if numerous squamous epithelial cells (indicative of preputial, vaginal, or urethral contaminants) are present.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `Urinary tract imaging is NOT usually indicated for recurrent UTIs in:`,
    q2: ``,
    q3: [],
    option: [
      `women.`,
      `girls.`,
      `men.`,
      `boys.`,
      `spinal cord–injured patients.`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [0],
    ansText: `Rationale: <!--<b>a. Women.</b>--> <b>Imaging and cystoscopic evaluation are not warranted in all women with recurrent UTIs.</b> Indeed, the yield of imaging in women without suspected complicated UTI is low and is not recommended by the American College of Radiology, the Canadian Urological Association Guidelines, or the European Association of Urology Guidelines. However, <b>in women with risk factors for a complicated UTI the evaluation should include imaging and cystoscopy.</b>`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `The most sensitive imaging modality for diagnosing renal abscess is:`,
    q2: ``,
    q3: [],
    option: [
      `ultrasonography.`,
      `indium scanning.`,
      `gallium scanning.`,
      `excretory urography.`,
      `CT.`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [4],
    ansText: `Rationale: <!--<b>e. CT.</b>--> CT and magnetic resonance imaging are more sensitive than excretory urography or ultrasonography in the diagnosis of acute focal bacterial nephritis, renal and perirenal abscesses, and radiolucent calculi.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `Treatment of UTIs depends most on an antimicrobial agent’s:`,
    q2: ``,
    q3: [],
    option: [
      `serum half-life.`,
      `serum level.`,
      `urine level.`,
      `duration of therapy.`,
      `frequency of therapy.`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [2],
    ansText: `Rationale: <!--<b>c. Urine level.</b>--> Efficacy of the antimicrobial therapy is critically dependent on the antimicrobial levels in the urine and the length of time that this level remains above the minimum inhibitory concentration of the infecting organism. Thus resolution of infection is closely associated with the susceptibility of the bacteria to the concentration of the antimicrobial agent achieved in the urine.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `An ideal class of drugs for the treatment of uncomplicated symptomatic UTIs in women is:`,
    q2: ``,
    q3: [],
    option: [
      `aminopenicillins.`,
      `aminoglycosides.`,
      `fluoroquinolones.`,
      `cephalosporins.`,
      `nitrofurantoins.`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [4],
    ansText: `Rationale: <!--<b>e. Nitrofurantoin.</b>--> According to the Infectious Diseases Society of America 2010 update, nitrofurantoin 100 mg twice daily for 5 days, fosfomycin 3 grams orally as a single dose, or Bactrim DS twice daily for 3 days should be preferential regimens for the treatment of uncomplicated UTIs in women. Sensitivity to these agents should be confirmed on urine culture, especially if the patient does not report a resolution of symptoms at the end of their course.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `The host factor least likely to be associated with an increased risk of infection is:`,
    q2: ``,
    q3: [],
    option: [
      `advanced age.`,
      `a history of previous infection in the site/organ of interest.`,
      `residence in a chronic care facility.`,
      `indwelling orthopedic pins.`,
      `coexistent infection.`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [3],
    ansText: `Rationale: <!--<b>d. Indwelling orthopedic pins.</b>--> Bacterial seeding of implanted orthopedic hardware is a rare but morbid event. A joint commission of the American Urological Association, the American Academy of Orthopaedic Surgeons, and infectious disease specialists convened in 2003 and released an advisory statement on antibiotic prophylaxis for urologic patients with total joint replacement. In general, <b>antimicrobial prophylaxis for urologic patients with total joint replacements, pins, plates, or screws is not indicated. Prophylaxis is advised for individuals at higher risk of seeding a prosthetic joint and include those with recently inserted implants (within 2 years).</b>`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `The optimal duration of antimicrobial therapy with Bactrim for symptomatic acute uncomplicated cystitis in women is:`,
    q2: ``,
    q3: [],
    option: [`1 day.`, `3 days.`, `7 days.`, `14 days.`, `21 days.`],
    optionStyleType: `st-lower-alpha`,
    answer: [1],
    ansText: `Rationale: <!--<b>b. 3 days.</b>--> According to IDSA guidelines, a 3-day therapy is the preferred regimen for uncomplicated cystitis in women.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `Treatment of asymptomatic bacteriuria is most indicated in patients who are:`,
    q2: ``,
    q3: [],
    option: [
      `elderly.`,
      `catheterized.`,
      `pregnant.`,
      `confused.`,
      `incontinent.`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [2],
    ansText: `Rationale: <!--<b>c. Pregnant.</b>--> In populations other than those for whom treatment has been documented to be beneficial (e.g., pregnant women and patients undergoing urologic interventions), screening for or treatment of asymptomatic bacteriuria is not appropriate and should be strongly discouraged.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `Screening for bacteriuria is beneficial in:`,
    q2: ``,
    q3: [],
    option: [
      `pregnant women.`,
      `elderly patients.`,
      `men.`,
      `children.`,
      `spinal cord–injured patients.`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [0],
    ansText: `Rationale: <!--<b>a. Pregnant women.</b>--> In populations other than those for whom treatment has been documented to be beneficial (e.g., pregnant women and patients undergoing urologic interventions), screening for or treatment of asymptomatic bacteriuria is not appropriate and should be discouraged.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `The most common cause of unresolved bacteriuria during antimicrobial therapy is:`,
    q2: ``,
    q3: [],
    option: [
      `development of bacterial resistance.`,
      `rapid reinfections.`,
      `azotemia.`,
      `staghorn calculi.`,
      `initial bacterial resistance.`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [4],
    ansText: `Rationale: <!--<b>e. Initial bacterial resistance.</b>--> Most commonly, the bacteria are resistant to the antimicrobial agent selected to treat the infection.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `Nitrofurantoin is effective because of the concentration of the drug in the:`,
    q2: ``,
    q3: [],
    option: [`urine.`, `vaginal mucus.`, `bowel.`, `serum.`, `bladder.`],
    optionStyleType: `st-lower-alpha`,
    answer: [0],
    ansText: `Rationale: <!--<b>a. Urine.</b>--> <b>Nitrofurantoin, which does not alter the bowel flora, is present for brief periods at high concentrations in the urine</b> and leads to repeated elimination of bacteria from the urine, presumably by interfering with bacterial initiation of infection.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `The most common cause of acute pyelonephritis in young women is:`,
    q2: ``,
    q3: [],
    option: [
      `vesicoureteral reflux.`,
      `P-piliated bacteria.`,
      `type 1 piliated bacteria.`,
      `recurrent UTIs.`,
      `bacterial endotoxin.`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [1],
    ansText: `Rationale: <!--<b>b. P-piliated bacteria.</b>--> If vesicourethral reflux is absent, a patient bearing the P blood group phenotype may have special susceptibility to recurrent pyelonephritis caused by <b><i>E. coli</i></b> that have P pili and bind to the P blood group antigen receptors.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `An optimal oral antibiotic agent for the treatment of acute uncomplicated pyelonephritis in a pregnant women is:`,
    q2: ``,
    q3: [],
    option: [
      `TMP-SMX`,
      `Cephalexin`,
      `Amoxicillin`,
      `Levofloxacin`,
      `Macrobid`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [1],
    ansText: `Rationale: <!--<b>b. Cephalexin.</b>--> Macrobid is concentrated in the urine and cannot treat blood-borne infections. Amoxicillin has been used to treat cystitis in pregnancy but does not have broad enough gram-negative coverage for the treatment of pyelonephritis. Levofloxacin is contraindicated in pregnancy due to possible damage to fetal cartilage, and trimethoprim should be avoided in pregnancy because it may cause fetal megaloblastic anemia, and, in the first trimester, neural tube and cardiovascular defects by inhibiting folic acid metabolism.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `A patient with acute pyelonephritis, persistent fever, and flank pain for 24 hours warrants:`,
    q2: ``,
    q3: [],
    option: [
      `observation.`,
      `CT.`,
      `change in antimicrobial therapy.`,
      `ultrasonography.`,
      `blood cultures.`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [0],
    ansText: `Rationale: <!--<b>a. Observation.</b>--> Even though the urine usually becomes sterile within a few hours of starting antimicrobial therapy, patients with acute uncomplicated pyelonephritis may continue to have fever, chills, and flank pain for several more days after initiation of successful antimicrobial therapy. They should be observed.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `Emphysematous pyelonephritis usually occurs in:`,
    q2: ``,
    q3: [],
    option: [
      `children`,
      `adults with a history of renal transplant`,
      `women with a history of recurrent uncomplicated UTIs`,
      `diabetic adults`,
      `adults on clean intermittent catheterization`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [3],
    ansText: `Rationale: <!--<b>d. Diabetic adults.</b>--> Emphysematous pyelonephritis predominantly affects female diabetics and can occur in insulin-dependent and non-insulin-dependent patients in the absence of ureteral obstruction. Nondiabetic patients can also develop this form of pyelonephritis but often have ureteric obstruction and do not seem to develop extensive disease`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `The primary treatment for a small perirenal abscess in a functioning kidney is:`,
    q2: ``,
    q3: [],
    option: [
      `nephrectomy.`,
      `partial nephrectomy.`,
      `open surgical drainage.`,
      `percutaneous drainage.`,
      `retrograde ureteral drainage.`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [3],
    ansText: `Rationale: <!--<b>d. Percutaneous drainage.</b>--> Although surgical drainage, or nephrectomy if the kidney is nonfunctioning or severely infected, is the classic treatment for perinephric abscesses, renal ultrasonography and CT make percutaneous aspiration and drainage of small perirenal collections possible.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `Most patients with chronic pyelonephritis present with:`,
    q2: ``,
    q3: [],
    option: [
      `hypertension.`,
      `renal failure.`,
      `chronic infection.`,
      `flank pain.`,
      `no symptoms.`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [4],
    ansText: `Rationale: <!--<b>e. No symptoms.</b>--> There are no symptoms of chronic pyelonephritis until it produces renal insufficiency, and then the symptoms are similar to those of any other form of chronic renal failure.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `The most common bacterial cause of xanthogranulomatous pyelonephritis is:`,
    q2: ``,
    q3: [],
    option: [
      `<i>E. coli.</i>`,
      `<i>Pseudomonas.</i>`,
      `<i>Klebsiella.</i>`,
      `<i>Proteus mirabilis.</i>`,
      `<i>Staphylococcus.</i>`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [3],
    ansText: `Rationale: <!--<b>d. <i>Proteus mirabilis.</i></b>--> Although review of the literature shows <b><i>Proteus</i></b> to be the most common organism involved with xanthogranulomatous pyelonephritis, <b><i>E. coli</i></b> is also common.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `Michaelis-Gutmann bodies are associated with the following disease process:`,
    q2: ``,
    q3: [],
    option: [
      `Xanthogranulomatous pyelonephritis`,
      `Malacoplakia`,
      `Renal echinococcosis`,
      `Chronic pyelonephritis`,
      `Acute focal bacterial nephritis`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [1],
    ansText: `Rationale: <!--<b>b. Malacoplakia.</b>--> Malacoplakia, from the Greek word meaning “soft plaque,” is an unusual inflammatory disease that was originally described to affect the bladder. It is an inflammatory lesion described originally by Michaelis and Gutmann 1902. It was characterized by von Hansemann 1903 as soft, yellow-brown plaques with granulomatous lesions in which the histiocytes contain distinct basophilic lysosomal inclusion bodies or Michaelis-Gutmann bodies. Although its exact pathogenesis is unknown, malacoplakia probably results from abnormal macrophage function in response to a bacterial infection, which is most often E. coli.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `Treatment of renal echinococcosis involves which of the following:`,
    q2: ``,
    q3: [],
    option: [
      `treatment with antibiotics and follow-up imaging to confirm regression of the hydatid cyst`,
      `observation`,
      `aspiration of cyst contents`,
      `surgical removal of the hydatid cyst`,
      `injection of the hydatid cyst with targeted antibiotics`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [3],
    ansText: `Rationale: <!--<b>d. Surgical removal of the hydatid cyst.</b>--> Surgery remains the mainstay of treatment of renal echinococcosis. The cyst should be removed without rupture to reduce the chance of seeding, antigen reaction, and recurrence. If the cyst ruptures or cannot be removed and marsupialization is required, the contents of the cyst initially should be aspirated and filled with a scolicidal agent.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `The most reliable early clinical indicator of septicemia is:`,
    q2: ``,
    q3: [],
    option: [
      `chills.`,
      `fever.`,
      `hyperventilation.`,
      `lethargy.`,
      `change in mental status.`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [2],
    ansText: `Rationale: <!--<b>c. Hyperventilation.</b>--> Even before temperature extremes and the onset of chills, bacteremic patients often begin to hyperventilate. Thus the earliest metabolic change in septicemia is a resultant respiratory alkalosis.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `Compared with non-pregnant women, pregnant women have a higher prevalence of:`,
    q2: ``,
    q3: [],
    option: [
      `asymptomatic bacteriuria.`,
      `acute cystitis.`,
      `acute pyelonephritis.`,
      `recurrent cystitis.`,
      `bacterial persistence.`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [2],
    ansText: `Rationale: <!--<b>c. Acute pyelonephritis.</b>--> Pyelonephritis develops in 1% to 4% of all pregnant women and in 20% to 40% of pregnant women with untreated bacteriuria.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `Clinical pyelonephritis during pregnancy is most commonly linked to:`,
    q2: ``,
    q3: [],
    option: [
      `maternal sepsis.`,
      `maternal anemia.`,
      `maternal hypertension.`,
      `eclampsia.`,
      `congenital malformations.`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [0],
    ansText: `Rationale: <!--<b>a. Maternal sepsis.</b>--> Pregnant women with asymptomatic bacteriuria are at higher risk for developing a symptomatic UTI that results in adverse fetal sequelae, complications associated with bacteriuria during pregnancy, and pyelonephritis and its possible sequelae, such as sepsis in the mother. Therefore all women with asymptomatic bacteriuria should be treated.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `The drug thought to be safe in any phase of pregnancy is:`,
    q2: ``,
    q3: [],
    option: [
      `a fluoroquinolone.`,
      `nitrofurantoin.`,
      `a sulfonamide.`,
      `penicillin.`,
      `tetracycline.`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [3],
    ansText: `Rationale: <!--<b>d. Penicillin.</b>--> The aminopenicillins and cephalosporins are considered safe and generally effective throughout pregnancy. In patients with penicillin allergy, nitrofurantoin is a reasonable alternative.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `The majority of elderly patients with bacteriuria are:`,
    q2: ``,
    q3: [],
    option: [
      `asymptomatic.`,
      `febrile.`,
      `incontinent.`,
      `confused.`,
      `dysuric.`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [0],
    ansText: `Rationale: <!--<b>a. Asymptomatic.</b>--> Most elderly patients with bacteriuria are asymptomatic.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `In the absence of obstruction, treatment of asymptomatic bacteriuria in the elderly:`,
    q2: ``,
    q3: [],
    option: [
      `is cost effective.`,
      `prevents renal failure.`,
      `reduces mortality.`,
      `reduces morbidity.`,
      `is unnecessary.`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [4],
    ansText: `Rationale: <!--<b>e. Is unnecessary.</b>--> <b>Prospective randomized comparative trials of antimicrobial or no therapy in elderly male and female nursing home residents with asymptomatic bacteriuria consistently document no benefit of antimicrobial therapy.</b> There was no decrease in symptomatic episodes and no improvement in survival. In fact, treatment with antimicrobial therapy increases the occurrence of adverse drug effects and reinfection with resistant organisms and increases the cost of treatment. Therefore asymptomatic bacteriuria in elderly residents of long-term care facilities should not be treated with antimicrobial agents.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `Prophylaxis for endocarditis should be administered in patients with:`,
    q2: ``,
    q3: [],
    option: [
      `a history of childhood heart murmurs.`,
      `heart valves inserted more than 5 years ago.`,
      `calcified heart valves associated with a murmur.`,
      `all synthetic heart valves.`,
      `cadaveric heart valves.`,
      `none of the above.`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [5],
    ansText: `Rationale: <!--<b>f. None of the above.</b>--> The American Heart Association’s recommendations on the prevention of bacterial endocarditis are based on the patient’s risk of developing endocarditis and the likelihood that a procedure will cause bacteremia with an organism that can cause endocarditis. Antibiotic <b>prophylaxis solely for the prevention of infectious endocarditis is not recommended for GU procedures, even in the setting of high-risk patients including individuals with prosthetic heart valves, previous bacterial endocarditis, cyanotic congenital heart disease, and systemic-pulmonary shunts or conduits.</b>`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
    type: `MCSS`,
    type: `MCSS`,
  },
  {
    q: `The most common predisposing factor for hospital-acquired UTIs is:`,
    q2: ``,
    q3: [],
    option: [
      `surgery.`,
      `antimicrobial therapy.`,
      `age.`,
      `catheterization.`,
      `diabetes mellitus.`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [3],
    ansText: `Rationale: <!--<b>d. Catheterization.</b>--> Catheter-associated bacteriuria is the most common hospital-acquired infection.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `The most effective measure for reducing catheter-associated UTI is:`,
    q2: ``,
    q3: [],
    option: [
      `closed drainage.`,
      `antimicrobial prophylaxis.`,
      `catheter irrigation.`,
      `intermittent catheterization.`,
      `daily meatal care.`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [0],
    ansText: `Rationale: <!--<b>a. Closed drainage.</b>--> Careful aseptic insertion of the catheter and maintenance of a closed dependent drainage system are essential to minimize development of bacteriuria.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `In spinal cord–injured patients the bladder drainage technique with the lowest complication rate is:`,
    q2: ``,
    q3: [],
    option: [
      `clean intermittent catheterization (CIC).`,
      `suprapubic drainage.`,
      `indwelling catheter.`,
      `condom catheter.`,
      `suprapubic pressure.`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [0],
    ansText: `Rationale: <!--<b>a. Clean intermittent catheterization (CIC).</b>--> Although never rigorously compared with indwelling urethral catheterization, CIC has been shown to decrease lower urinary tract complications by maintaining low intravesical pressure and reducing the incidence of stones.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `All of the following conditions are predisposing factors to the development of Fournier gangrene EXCEPT:`,
    q2: ``,
    q3: [],
    option: [
      `obesity`,
      `paraphimosis`,
      `diabetes mellitus`,
      `perirectal infections`,
      `urethral strictures`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [0],
    ansText: `Rationale: <!--<b>a. Obesity.</b>--> An association between Fournier gangrene and urethral obstruction associated with strictures and extravasation and instrumentation has been well documented. Predisposing factors include diabetes mellitus, local trauma, paraphimosis, periurethral extravasation of urine, perirectal or perianal infections, and surgery such as circumcision or herniorrhaphy.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `Which of the following is true of vaginal estrogen preparations and recurrent urinary tract infections in postmenopausal women?`,
    q2: ``,
    q3: [],
    option: [
      `The use of vaginal estrogen has been associated with an increased risk of breast cancer.`,
      `Vaginal estrogen use can confer an increased risk of thrombotic events in women.`,
      `Vaginal estrogen preparations can help with vaginal pain symptoms that can be conflated for UTI but do not modulate UTI risk independently.`,
      `Vaginal estrogen can prevent recurrent UTIs and these effects are immediate.`,
      `The effects of vaginal estrogen on recurrent UTI risk are related to modulation of local pH and vaginal microflora.`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [4],
    ansText: `Rationale: <!--<b>e. The effects of vaginal estrogen on recurrent UTI risk are related to modulation of local pH and vaginal microflora.</b>--> Randomized controlled trials of vaginal estrogen use have not been designed to analyze outcomes such as cancer or cardiovascular disease. However, observational studies have found no increased risk of fracture or breast cancer in women who used vaginal estrogen. Vaginal estrogen is effective in preventing recurrent UTIs in postmenopausal women through lowering the vaginal pH and restoring the normal microenvironment such as lactobacilli. The beneficial effect from vaginal estrogen use can take at least 12 weeks to manifest.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `Which of the following is not a risk factor for UTI in a renal transplant recipient?`,
    q2: ``,
    q3: [],
    option: [
      `Cadaveric graft`,
      `Diabetes`,
      `Prolonged hemodialysis prior to transplant`,
      `Female gender`,
      `Polycystic native kidneys`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [4],
    ansText: `Rationale: <!--<b>e. Polycystic native kidneys.</b>--> Transplant recipients are at higher risk for vesicoureteral reflux. Risk factors for infection include cadaveric graft, diabetes, prolonged hemodialysis prior to transplantation, two episodes of asymptomatic bacteriuria, and female gender.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `Prophylaxis for endocarditis should be administered in patients with:`,
    q2: ``,
    q3: [],
    option: [
      `a history of childhood heart murmurs.`,
      `heart valves inserted more than 5 years ago.`,
      `calcified heart valves associated with a murmur.`,
      `all synthetic heart valves.`,
      `cadaveric heart valves.`,
      `none of the above.`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [5],
    ansText: `Rationale: <!--<b>f. None of the above.</b>--> The American Heart Association’s recommendations on the prevention of bacterial endocarditis are based on the patient’s risk of developing endocarditis and the likelihood that a procedure will cause bacteremia with an organism that can cause endocarditis. Antibiotic prophylaxis solely for the prevention of infectious endocarditis is not recommended for GU procedures, even in the setting of high-risk patients including individuals with prosthetic heart valves, previous bacterial endocarditis, cyanotic congenital heart disease, and systemic-pulmonary shunts or conduits.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `Antimicrobial prophylaxis is characterized as:`,
    q2: ``,
    q3: [],
    option: [
      `administration of an antimicrobial agent within 4 to 6 hours of the procedure.`,
      `administration of an antimicrobial agent for a period of time covering the first 48 hours after the procedure.`,
      `administration of an antimicrobial agent within 30 minutes of the initiation of a procedure and for a period of time covering the first 48 hours after the procedure.`,
      `administration of an antimicrobial agent within 60 to 120 minutes of the initiation of a procedure and for a period of time that covers the duration of the procedure.`,
      `administration of an antimicrobial agent the night before the initiation of a procedure and for a period of time that covers the duration of the procedure.`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [3],
    ansText: `Rationale: <!--<b>d. Administration of an antimicrobial agent within 60 to 120 minutes of the initiation of a procedure and for a period of time that covers the duration of the procedure.</b>--> Surgical antimicrobial prophylaxis entails treatment with an antimicrobial agent before and for a limited time after a procedure to prevent local or systemic postprocedural infections.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `Which of the following organisms is NOT associated with positive nitrites on urine analysis?`,
    q2: ``,
    q3: [],
    option: [
      `<i>Enterococcus</i>`,
      `<i>E. coli</i>`,
      `<i>Proteus mirabilis</i>`,
      `<i>Klebsiella pneumoniae</i>`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [0],
    ansText: `Rationale: <!--<b>a. <i>Enterococcus</i></b>.--> Most gram-negative bacteria are capable of producing positive results on a nitrite test. Pseudomonas aeruginosa and most gram-positive organisms do not produce nitrites.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `All of the following are important factors to consider in a patient’s ability to give a noncontaminated midstream urine sample except:`,
    q2: ``,
    q3: [],
    option: [
      `Vaginal atrophy`,
      `Poor manual dexterity`,
      `History of human papilloma virus (HPV)`,
      `Inability to weight beat`,
      `Presence of a vaginal pessary`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [2],
    ansText: `Rationale: <!--<b>c. History of human papilloma virus (HPV).</b>--> HPV history does not impact ability to provide an adequate sample; the other variables are important influencing factors and a catheterized urine sample should be considered in these situations.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `Which of the following is least relevant to history-taking when interviewing a patient with recurrent UTIs?`,
    q2: ``,
    q3: [],
    option: [
      `Family history of postmenopausal UTIs`,
      `Spermicide use`,
      `Childhood voiding dysfunction`,
      `History of urologic surgery`,
      `Past urinary pathogens and antibiotics`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [0],
    ansText: `Rationale: <!--<b>a. Family history of postmenopausal UTIs.</b>--> Family history of postmenopausal UTIs is least relevant to the patient’s immediate evaluation; the other variables list individual behaviors, infection history, and anatomic factors that can have a direct impact on the patient’s ongoing UTI diathesis. Family history of UTIs in childhood or young adulthood bears more relevance regarding structural issues (such as vesicoureteral reflux) or genetic risk factors for recurrent infections.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `<b>Pathology</b><br/><br/>See <a class="lightboxcallout" img-ref="image_fig_55_1" href="66157d28bbbe464394c96bd02ba3e731">Fig. 55.1</a>. A 65-year-old woman has the acute onset of right flank pain, fever, and an enlarged kidney on imaging. Blood cultures and urine cultures are obtained and broad-spectrum antibiotics administered. The patient improves, but the kidney on imaging remains enlarged. A needle biopsy of the kidney is obtained. The pathology report is acute pyelonephritis with numerous neutrophils within the interstitium and the renal tubules. The biopsy:`,
    q2: ``,
    q3: [],
    option: [
      `provides information as to the length of time antibiotics should be administered.`,
      `suggests that the antibiotics should be changed.`,
      `is unnecessary.`,
      `suggests the need for a percutaneous drain.`,
      `suggests that an abscess is likely to develop.`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [2],
    ansText: `Rationale: <!--<b>c. Is unnecessary.</b>--> The figure shows numerous neutrophils within the interstitium and the renal tubules. The neutrophils in the tubules become white blood cell casts. The pathologic findings including an enlarged kidney may persist for several weeks despite appropriate treatment. There is no indication for a biopsy in this patient.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `A 65-year-old man has fever and malaise. A CT scan reveals an 8-cm solid mass in his left kidney with marked thickening of the retroperitoneum around the kidney and pancreas. The kidney is poorly functioning and there is a 1-cm stone in the renal pelvis. A biopsy is done and reveals xanthogranulomatous pyelonephritis, which is depicted in <a class="lightboxcallout" img-ref="image_fig_55_2" href="d77b4060dd944bc5adf978cb44dd48ab">Fig. 55.2</a>. The next step in management is:`,
    q2: ``,
    q3: [],
    option: [
      `extracorporeal shockwave lithotripsy.`,
      `biopsy of the retroperitoneum.`,
      `left nephrectomy.`,
      `urine culture and treatment according to sensitivities.`,
      `partial left nephrectomy`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [2],
    ansText: `Rationale: <!--<b>c. Left nephrectomy.</b>--> The figure shows the foamy macrophages with neutrophils and cellular debris characteristic of xanthogranulomatous pyelonephritis. It may be associated with renal calculi and <b><i>Proteus</i></b> infection. <b><i>E. coli</i></b> is also a common organism found in this disease. Although partial nephrectomy has been performed for a small localized mass in a functioning kidney, a left nephrectomy in this situation is likely required and is necessary to rid the patient of the infection. An associated retroperitoneal inflammatory process with thickening is not uncommon.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `A 45-year-old woman is found to have a raised bladder lesion on cystoscopy. The biopsy shown in <a class="lightboxcallout" img-ref="image_fig_55_3" href="92a1bc9146f845e7889360fd18c0ea11">Fig. 55.3</a> reveals malakoplakia. The next step in management is:`,
    q2: ``,
    q3: [],
    option: [
      `intravesical bacille Calmette-Guérin.`,
      `fulguration of the lesions.`,
      `intravesical mitomycin C.`,
      `treat with a sulfonamide for several months.`,
      `a 3-day course of ciprofloxacin.`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [3],
    ansText: `Rationale: <!--<b>d. Treat with a sulfonamide for several months.</b>--> <a class="lightboxcallout" img-ref="image_fig_55_3" href="92a1bc9146f845e7889360fd18c0ea11">Fig. 55.3A</a> shows von Hansemann histiocytes, and <a class="lightboxcallout" img-ref="image_fig_55_3" href="92a1bc9146f845e7889360fd18c0ea11">Fig. 55.3B</a> demonstrates the Michaelis-Gutmann bodies, both of which are characteristic of malakoplakia. It is thought to be infectious in origin, and therefore the treatment is an extended course of an antibiotic that achieves a high intracellular concentration.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `<b>Imaging</b><br/><br/>A 72-year-old man presents with right flank pain and fever. A contrast-enhanced CT scan is shown in <a class="lightboxcallout" img-ref="image_fig_55_4" href="903c12e088ca4b46863beddcc39ba627">Fig. 55.4</a>. The most likely diagnosis is:`,
    q2: ``,
    q3: [],
    option: [
      `acute right renal obstruction.`,
      `delayed excretion in left kidney.`,
      `cellulitis in right flank.`,
      `right perinephric abscess.`,
      `xanthogranulomatous pyelonephritis.`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [3],
    ansText: `Rationale: <!--<b>d. Right perinephric abscess.</b>--> The CT scan is obtained in the late arterial to nephrographic phase of the examination (the aorta is still opacified with contrast agent), before the excretion of the contrast agent. Thus option b is incorrect. There are multiple calculi in the right kidney, which is small and atrophic, indicating a chronic process (thus option a is incorrect). There is thickening of the perinephric fascia, and gas bubbles are seen in the posterior paranephric space, extending to the right flank. In addition, there are fluid collections in the posterior paranephric space and in the soft tissues of the right flank, making option d the most likely diagnosis. Xanthogranulomatous pyelonephritis is a chronic inflammatory condition associated with staghorn calculi. The affected kidney is usually enlarged rather than shrunken, as is the case here (making option e unlikely).`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `A 40-year-old woman presents with pelvic pain and fever. A contrast-enhanced CT scan is shown in <a class="lightboxcallout" img-ref="image_fig_55_5" href="0b56c69280954ee7afbd4a55828564bd">Fig. 55.5</a>. The most likely diagnosis is:`,
    q2: ``,
    q3: [],
    option: [
      `renal infarct.`,
      `renal artery occlusion.`,
      `chronic pyelonephritis.`,
      `acute urinary obstruction.`,
      `acute pyelonephritis.`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [4],
    ansText: `Rationale: <!--<b>e. Acute pyelonephritis.</b>--> The image demonstrates a pelvic kidney with wedge-shaped area of decreased enhancement, characteristic of acute pyelonephritis. Renal infarcts cause areas of poor perfusion that are more sharply defined and more poorly enhancing than in the present case (making option a unlikely). The clinical history of fever also supports an infection. With renal artery occlusion (option b) the kidney would demonstrate no enhancement. Chronic pyelonephritis causes scarring in the kidney, and the nephrogram is usually normal. The renal contour in the present case is smooth, making option c unlikely. Acute urinary obstruction (option d) is ruled out because the visualized collecting system does not appear dilated.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `A 22-year-old woman presents with shaking chills and fever. An enhanced CT image is shown in <a class="lightboxcallout" img-ref="image_fig_55_6" href="c4994b5430b14db2b93167b5d54d645b">Fig. 55.6</a>. The next step in management is:`,
    q2: ``,
    q3: [],
    option: [
      `percutaneous drainage.`,
      `nephrectomy.`,
      `partial nephrectomy.`,
      `open surgical drainage.`,
      `cystoscopy and retrograde urography.`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [0],
    ansText: `Rationale: <!--<b>a. Percutaneous drainage.</b>--> The image demonstrates a low-attenuation area in the posterior interpolar region of the left kidney, with perinephric fascial thickening, consistent with a renal abscess. Intravenous antimicrobial therapy with percutaneous drainage of renal abscesses is highly effective and is the treatment of choice. Antimicrobial therapy alone is unlikely to be effective, given the size of the abscess. Nephrectomy, partial nephrectomy, and surgical drainage are rarely indicated in young patients with normally functioning kidneys. Cystoscopy is not warranted.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `A 68-year-old diabetic woman presents to the emergency room with the chief complaint of abdominal pain. CT scan findings of her pelvis are shown in <a class="lightboxcallout" img-ref="image_fig_55_7" href="ecfc3bffdd0947a3a55cef87cc7b0806">Fig. 55.7</a>. The next step in her management is:`,
    q2: ``,
    q3: [],
    option: [
      `inpatient antibiotics, Foley catheter placement, and glucose management`,
      `collection of a urine sample and discharge home with empiric antibiotic coverage`,
      `emergent exploration and surgical debridement with placement of a suprapubic tube`,
      `obtain an ultrasound to assess the upper urinary tract`,
      `reassurance`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [0],
    ansText: `Rationale: <!--<b>a. Inpatient antibiotics, Foley catheter placement, and glucose management.</b>--> The figure is an example of emphysematous pyelonephritis. The majority (90%) of these patients are treated with medical therapy alone, which consists of antibiotics (often parenteral), bladder drainage, and treatment of comorbid conditions such as poorly controlled diabetes. The need for surgical intervention is rare and is reserved for those cases that respond poorly to initial medical management or severe necrotizing infections.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
];
