var quiz = [
  {
    q: `The most commonly diagnosed bacterial sexually transmitted infection (STI) in the United States is:`,
    q2: ``,
    q3: [],
    option: [
      `gonorrhea.`,
      `ureaplasma.`,
      `syphilis.`,
      `chlamydia.`,
      `chancroid.`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [3],
    ansText: `Rationale: <!--<b>d. Chlamydia.</b>--> <b>Chlamydia is the most common bacterial STI in the United States.</b> The 1,422,976 cases of <b><i>Chlamydia trachomatis</i></b> infection reported to the Centers for Disease Control and Prevention (CDC) in 2012 was the largest number ever reported to the CDC for any condition. The second most common bacterial STI is gonorrhea. `,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `The major health risk to untreated <i>Chlamydia</i> infection in men is:`,
    q2: ``,
    q3: [],
    option: [
      `epididymitis.`,
      `Reiter syndrome.`,
      `orchitis.`,
      `chronic prostatitis/chronic pelvic pain syndrome.`,
      `transmission to a female partner resulting in pelvic inflammatory disease.`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [4],
    ansText: `Rationale: <!--<b>e. Transmission to a female partner resulting in pelvic inflammatory disease.</b>--> Up to 75% of women with chlamydial infection can be asymptomatic. Ascending chlamydial infection can result in scarring of the fallopian tubes, pelvic inflammatory disease, risk for ectopic pregnancy, pelvic pain, and infertility. The <b>risk of untreated chlamydial infection producing pelvic inflammatory disease is estimated to be between 9.5% and 27% of cases.</b>`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `In addition to treatment for chlamydia, what other medication is recommended as a first-line treatment for gonorrhea?`,
    q2: ``,
    q3: [],
    option: [
      `Ciprofloxacin`,
      `Levofloxacin`,
      `Ceftriaxone`,
      `Cefixime`,
      `Penicillin VK`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [2],
    ansText: `Rationale: <!--<b>c. Ceftriaxone.</b>--> As of 2007, quinolones are no longer recommended in the United States for treatment of gonorrhea and associated conditions such as pelvic inflammatory disease. As of August 2012, because of high resistance, cefixime is no longer recommended as first-line therapy to treat gonorrhea. <b>Current treatment of uncomplicated gonococcal infections of the cervix, urethra, and rectum is ceftriaxone, 250 mg IM, single-dose PLUS azithromycin, 1 g orally in single dose.</b>`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `Which subtypes of human papillomavirus (HPV) are responsible for development of malignancies including cervical, penile, and anal?`,
    q2: ``,
    q3: [],
    option: [`16 and 18`, `13 and 14`, `6 and 11`, `31 and 33`, `26 and 28`],
    optionStyleType: `st-lower-alpha`,
    answer: [0],
    ansText: `Rationale: <!--<b>a. 16 and 18.</b>--> Types 6 and 11 are nononcogenic and are responsible for about 90% of anogenital warts. Other subtypes, including 16 and 18, account for cervical cancer and other types of anogenital cancer including vulvar, vaginal, anal, and penile.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `HPV vaccines are indicated for which groups?`,
    q2: ``,
    q3: [],
    option: [
      `All sexually active women`,
      `All sexually active men who have sex with men (MSMs)`,
      `Men and women up to age 26 years`,
      `Only women up to age 26 years`,
      `Only women with a family history of cervical cancer`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [2],
    ansText: `Rationale: <!--<b>c. Men and women up to age 26 years.</b>--> In June 2006, a quadrivalent HPV vaccine (Gardasil; Merck, Sharpe, and Dohme Corporation) was licensed for use in the United States in females aged 9 to 26 years. In October 2009, this vaccine also was licensed for use in males aged 9 to 26 years. This vaccine provides protection against HPV types 6, 11, 16, and 18. In October 2009, a bivalent HPV vaccine (Cervarix; Glaxo SmithKline Biologicals, Research Triangle Park, NC) that provides protection against types 16 and 18 was licensed for use in females aged 10 to 25 years.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `Which STI often has no visible genital lesion because it has usually resolved by the time of presentation and is associated with tender, often suppurative adenopathy?`,
    q2: ``,
    q3: [],
    option: [
      `Chancroid`,
      `Herpes simplex virus type 2 (HSV-2)`,
      `Herpes simplex virus type 1 (HSV-1)`,
      `Donovanosis`,
      `Lymphogranuloma venereum (LGV)`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [4],
    ansText: `Rationale: <!--<b>e. Lymphogranuloma venereum (LGV).</b>--> A self-limited genital ulcer or papule sometimes is present at the site of infection but usually has disappeared by the time of presentation. The secondary stage is the most common presentation in heterosexuals and is <b>marked by tender inguinal and/or femoral lymphadenopathy, typically unilateral.</b>`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `Which of the following is not a reportable STI in every state?`,
    q2: ``,
    q3: [],
    option: [
      `HSV`,
      `Syphilis`,
      `Chancroid`,
      `Chlamydia`,
      `Human immunodeficiency virus (HIV)`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [0],
    ansText: `Rationale: <!--<b>a. HSV.</b>--> Diseases that must be reported to local health authorities: Syphilis, gonorrhea, chlamydia, chancroid, HIV infection, and acquired immunodeficiency syndrome (AIDS) are reportable diseases in every state.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `Which of the following tests should be used to monitor the clinical response to treatment in patients with syphilis?`,
    q2: ``,
    q3: [],
    option: [
      `<i>Treponema pallidum</i> particle agglutination (TP-PA)`,
      `Rapid plasma reagin (RPR)`,
      `Fluorescent treponemal antibody absorption (FTA-ABS)`,
      `Darkfield microscopy`,
      `Tzanck test`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [1],
    ansText: `Rationale: <!--<b>b. Rapid plasma reagin (RPR).</b>--> <b>Nontreponemal tests (RPR or VDRL) are used to monitor disease activity.</b> A fourfold change in titer equivalent to a change of two dilutions (e.g., from 1:16 to 1:4) is considered necessary to demonstrate a clinically significant difference.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `What is the treatment of choice for primary, secondary, and early latent syphilis?`,
    q2: ``,
    q3: [],
    option: [
      `Azithromycin`,
      `Benzathine penicillin`,
      `Probenecid penicillin`,
      `Ceftriaxone`,
      `Procaine penicillin`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [1],
    ansText: `Rationale: <!--<b>b. Benzathine penicillin.</b>--> Benzathine penicillin is the treatment of choice for all of the stages of syphilis. Treatment varies by dose and duration of therapy. Not considered appropriate treatments are combinations of benzathine and procaine penicillin (Bicillin C-R), or oral penicillin.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `Which statement is true regarding the likelihood of recurrent genital lesions in patients with HSV-1 and HSV-2?`,
    q2: ``,
    q3: [],
    option: [
      `No difference except in HIV patients in whom HSV-1 recurs more often`,
      `No difference except in HIV patients in whom HSV-2 recurs more often`,
      `HSV-1 recurs more often`,
      `HSV-2 recurs more often`,
      `No difference`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [3],
    ansText: `Rationale: <!--<b>d. HSV-2 recurs more often.</b>--> Genital HSV-1 recurs much less frequently (0.02 per month) than genital HSV-2 infections (0.23 per month), on the order of 10-fold less.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `What is the causative organism for LGV?`,
    q2: ``,
    q3: [],
    option: [
      `<i>Calymmatobacterium</i>`,
      `<i>Klebsiella</i>`,
      `<i>Chlamydia</i>`,
      `<i>Haemophilus ducreyi</i>`,
      `<i>Trichomonas</i>`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [2],
    ansText: `Rationale: <!--<b>c. <i>Chlamydia.</i></b>--> LGV is an infection by <b><i>Chlamydia</i></b>, specifically serovars L1, L2, or L3.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `Gardasil in males is recommended:`,
    q2: ``,
    q3: [],
    option: [
      `to prevent transmission of HPV to their partners.`,
      `only for persons with documented HPV.`,
      `to prevent anal cancer and genital warts.`,
      `to prevent genital warts only.`,
      `only in men older than 26 years.`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [2],
    ansText: `Rationale: <!--<b>c. To prevent anal cancer and genital warts.</b>--> The quadrivalent vaccine is used in males to prevent genital warts and in both genders to prevent anal cancer. MSMs are particularly at risk for developing anal intraepithelial neoplasia and anal cancer. As in women, it is best started in males before the onset of sexual activity.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `Donovan bodies are seen on:`,
    q2: ``,
    q3: [],
    option: [
      `Thayer-Martin medium in gonorrhea.`,
      `ulcer scraping in primary syphilis.`,
      `biopsy of condyloma acuminata.`,
      `lymph node aspiration in LGV.`,
      `biopsy of ulcer in granuloma inguinale.`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [4],
    ansText: `Rationale: <!--<b>e. Biopsy of ulcer in granuloma inguinale.</b>--> Granuloma inguinale (GI) is an infection by the intracellular gram-negative bacterium <b><i>Klebsiella granulomatis</i></b> (formerly called <b><i>Calymmatobacterium granulomatis</i></b>) that produces genital ulcers. The bacterium is a strict human pathogen, which makes culture difficult. <b>Diagnosis requires visualization of dark-staining Donovan bodies on crush preparation or biopsy, described by Donovan in 1905. These are intracellular inclusions of the bacteria within the cytoplasm of macrophages and appear deep purple when stained with a Wright, Giemsa, or Leishman stain.</b>`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `Clue cells are diagnostic of:`,
    q2: ``,
    q3: [],
    option: [
      `bacterial vaginosis (BV).`,
      `<i>Trichomonas.</i>`,
      `scabies.`,
      `<i>Candida</i> vulvovaginitis.`,
      `<i>Torulopsis glabrata</i> vulvovaginitis.`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [0],
    ansText: `Rationale: <!--<b>a. Bacterial vaginosis (BV).</b>--> <b>Characteristic findings for BV on microscopic exam are clue cells, which are vaginal epithelial cells covered with bacteria.</b>`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `HIV is what type of virus?`,
    q2: ``,
    q3: [],
    option: [
      `Single-stranded RNA`,
      `Double-stranded RNA`,
      `Single-stranded messenger RNA (mRNA)`,
      `Single-stranded DNA`,
      `Double-stranded DNA`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [0],
    ansText: `Rationale: <!--<b>a. Single-stranded RNA.</b>--> The genetic material in HIV is single-stranded RNA. After entry into the targeted cell, the RNA is reverse transcribed by a reverse transcriptase into a double-stranded DNA. This new DNA is assembled into complexes, which then associate with the target cell chromatin and integrate via the action of viral integrase. The cell then translates and transcribes the viral genes to produce proteins that will assemble new copies of the virus. Copies of the virus are called virions.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `The HIV envelope precursor protein gp160 is cleaved into what two envelope proteins?`,
    q2: ``,
    q3: [],
    option: [
      `gp123 and gp33`,
      `gp124 and gp40`,
      `gp141 and gp20`,
      `gp120 and gp41`,
      `gp120 and gp6`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [3],
    ansText: `Rationale: <!--<b>d. gp120 and gp41.</b>--> The virus is shaped like a sphere. It is covered by an outer envelope that is a lipid bilayer derived from the host cell when it buds out of the cell. Embedded in the envelope is a complex of proteins known as Env. There is initially a precursor gp160 that is cleaved by a protease in the trans-Golgi network. It is cleaved into an outer subunit glycoprotein 120 (gp120) and a transmembrane subunit glycoprotein 41 (gp41). After proteolysis, the gp120 and gp41 remain coupled as noncovalent heterodimers.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `HIV infects which immune cells?`,
    q2: ``,
    q3: [],
    option: [
      `Macrophages`,
      `B cells`,
      `CD4 T cells`,
      `CD8 T cells`,
      `Natural killer (NK) cells`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [2],
    ansText: `Rationale: <!--<b>c. CD4 T cells.</b>--> Glycoprotein gp120 has a high-affinity binding site for the T lymphocyte receptor CD4.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `The initial screening test for HIV is:`,
    q2: ``,
    q3: [],
    option: [
      `Western blot.`,
      `indirect immunofluorescence assay.`,
      `nucleoside amplification assay.`,
      `rapid enzyme immunoassay (EIA).`,
      `viral culture.`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [3],
    ansText: `Rationale: <!--<b>d. Rapid enzyme immunoassay (EIA).</b>--> Diagnosis of HIV includes the use of serologic tests that detect antibodies against HIV-1 (and HIV-2) and by virologic tests that detect HIV antigens RNA. <b>The initial test is a screening test for antibodies, the conventional or rapid EIA. The initial result can be obtained in 30 minutes. Positive or reactive screening tests must be confirmed by a supplemental antibody test, Western blot, and indirect immunofluorescence assay (IFA) or by a virologic test, the HIV-1 RNA assay.</b>`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `Antiretroviral therapy is recommended for:`,
    q2: ``,
    q3: [],
    option: [
      `patients with CD4 count of &lt;200 only.`,
      `patients with CD4 count of &lt;350 only.`,
      `patients with CD4 count of &lt;500 only.`,
      `patients with CD4 count of &lt;500 and symptoms.`,
      `all patients with HIV.`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [4],
    ansText: `Rationale: <!--<b>e. All patients with HIV.</b>--> The benefit of treatment may depend on the starting CD4 count, but treatment guidelines recommend treatment for all patients regardless of CD4 count.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `What factor is not associated with increased risk of seroconversion with HIV after a needle stick?`,
    q2: ``,
    q3: [],
    option: [
      `Recent infection by patient`,
      `Deep exposure of needle`,
      `Visible blood on injuring device`,
      `Prior placement of injuring device in artery or vein`,
      `Patient dying within 2 months of exposure`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [0],
    ansText: `Rationale: <!--<b>a. Recent infection by patient.</b>--> A review of <b>factors for increased risk of infection done by the CDC identified four that increased risk: deep as opposed to superficial exposure (odds ratio [OR] 15, 95% confidence index [CI] 6 to 41), visible blood on the injuring device (OR 6.2, 95% CI 2.2 to 21), prior placement of the injuring device in an artery or vein (OR 4.3, 95% CI 1.7 to 12), and patient dying within 2 months of the exposure (preterminal disease) (OR 5.6, 95% CI 2 to 16).</b>`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `Polymorphisms of which gene are associated with development of HIV-associated nephropathy (HIVAN) in African American patients?`,
    q2: ``,
    q3: [],
    option: [
      `Tyrosine kinase`,
      `Antichymotrypsin-1`,
      `Apolipoprotein-1`,
      `Tumor necrosis alpha`,
      `Interleukin-10`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [2],
    ansText: `Rationale: <!--<b>c. Apolipoprotein-1.</b>--> African Americans carrying two variants of the APOL-1 gene are at very high risk for HIVAN. These genes encode a secreted lipid binding protein called apolipoprotein-1 (apoL1). The variants G1 and G2 are common in African chromosomes but absent in European chromosomes; these variants lyse trypanosomes, including <b><i>Trypanosoma brucei rhodesiense</i></b>, which causes African sleeping sickness. Thus, these loci are thought to be selected out in this population. The presence of these two genes together increases the risk 29-fold, resulting in a 50% risk of developing HIVAN in untreated individuals as compared with a 12% baseline risk. Focal segmental glomerulosclerosis (FSGS) found in individuals with the two risk genes also occurs at an earlier age and progresses much more rapidly.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `Which type of antiretroviral medications are associated with formation of urinary tract stones?`,
    q2: ``,
    q3: [],
    option: [
      `Integrase inhibitors`,
      `Fusion inhibitors`,
      `Protease inhibitors`,
      `Non-nucleoside reverse-transcriptase inhibitors (NNRTIs)`,
      `CCR5 blockers`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [2],
    ansText: `Rationale: <!--<b>c. Protease inhibitors.</b>--> The protease inhibitors specifically have the possibility of stone formation. <b>Indinavir can form crystals in the urine. Indinavir stones are typically radiolucent on both plain film and computed tomography scan but can also be mixed with calcium and appear radio-opaque. Newer inhibitors including lopinavir, atazanavir, amprenavir, and nelfinavir have also been associated with the development of stones, but with less frequency than reported for indinavir.</b>`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `What is the best diagnostic test to detect HIV in the acute phase of infection?`,
    q2: ``,
    q3: [],
    option: [
      `Indirect immunofluorescence assay`,
      `Viral load assay`,
      `Western blot`,
      `HIV-1/HIV-2 serology assay`,
      `Rapid EIA`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [1],
    ansText: `Rationale: <!--<b>b. Viral load assay.</b>--> During this initial 3-month period, the “window” period, antibody screening tests may be negative but the person is still infected. Virologic tests for HIV-1 RNA can be used to detect an acute infection in persons negative for HIV antibodies.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `What class of medication can have a prolonged half-life when used in association with protease inhibitors and NNRTI’s for treatment of HIV?`,
    q2: ``,
    q3: [],
    option: [
      `Alpha-blockers`,
      `5-Alpha reductase inhibitors`,
      `Beta-3 agonists`,
      `PDE5 inhibitors`,
      `Fluoroquinolones`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [3],
    ansText: `Rationale: <!--<b>d. PDE5 inhibitors.</b>--> PDE5 inhibitors depend on CYP3A for clearance, and all protease inhibitors and NNRTIs are inhibitors of CYP3A to some extent. <b>This can lead to a significant increase in the serum dose of PDE5 inhibitors, and therefore they should be started at the lowest dose possible in patients on these antiretroviral medications.</b>`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `What type of genitourinary (GU) cancer is not increased in frequency in patients with HIV?`,
    q2: ``,
    q3: [],
    option: [
      `Prostate cancer`,
      `Kidney cancer`,
      `Penile cancer`,
      `Testis cancer`,
      `Kaposi sarcoma`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [0],
    ansText: `Rationale: <!--<b>a. Prostate cancer.</b>--> The relative risk of prostate cancer in men with HIV compared to uninfected individuals has been reported as either no different or even less at 0.70.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `<b>Pathology</b><br/><br/>A 32-year-old sexually active woman has the lesion in <a class="lightboxcallout" img-ref="image_fig_58_1" href="39259589595b4d4994b718abfc168557">Fig. 58.1A</a> and B excised from her vulva. The diagnosis is condyloma acuminata. The most appropriate next step is:`,
    q2: ``,
    q3: [],
    option: [
      `acetic acid test.`,
      `podophyllin to the base of the lesion.`,
      `HPV vaccine.`,
      `vaginoscopy.`,
      `cystoscopy.`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [3],
    ansText: `Rationale: <!--<b>d. Vaginoscopy.</b>--> The figure shows marked papillomatosis with koilocytic atypia. The patient should have a thorough genital examination, including vaginoscopy for other lesions.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `A 22-year-old sexually active man has a 2-mm raised red lesion in the suprapubic area. A biopsy is performed (depicted in <a class="lightboxcallout" img-ref="image_fig_58_2" href="76e9e1fdf68c43ff98eab6888ce1ed8f">Fig. 58.2</a>) and read as molluscum contagiosum. The patient is concerned and desires treatment. The most appropriate treatment is:`,
    q2: ``,
    q3: [],
    option: [
      `wide local excision.`,
      `5-fluorouracil cream.`,
      `ciprofloxacin for 2 weeks.`,
      `bactrim for 4 weeks.`,
      `liquid nitrogen application.`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [4],
    ansText: `Rationale: <!--<b>e. Liquid nitrogen application.</b>--> The biopsy shows an epidermal crater filled with molluscum bodies. This is usually a self-limited disease and requires no treatment. If treatment is desired, a local therapy is appropriate, such as curettage or liquid nitrogen application.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
];
