var quiz = [
  {
    q: `<!--1. -->While present throughout the world, the region showing the largest gap in life expectancy between genders is:`,
    q2: ``,
    q3: [],
    option: [
      `<!--a. -->North America`,
      `<!--b. -->Southeast Asia`,
      `<!--c. -->Western Europe`,
      `<!--d. -->Eastern Europe`,
      `<!--e. -->sub-Saharan Africa`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [3],
    ansText: `Rationale: Globally, average life expectancy is longer in women compared to men. While this difference in longevity is observed in all regions of the world (regardless of the level of industrial development), it is most pronounced in Eastern Europe. Women in this region tend to live approximately 7 years longer than men.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `<!--2. -->All of the following are proposed as factors contributing to the gender gap in life expectancy, EXCEPT:`,
    q2: ``,
    q3: [],
    option: [
      `<!--a. -->Increased exposure of males to physical and environmental harm in the workplace`,
      `<!--b. -->Higher propensity for risk-taking behaviors in males`,
      `<!--c. -->Masculinity-defined norms of health behavior`,
      `<!--d. -->Improved postpartum care`,
      `<!--e. -->Lower compliance with treatment in male patients`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [3],
    ansText: `Rationale:  A series of factors have been identified that place men at higher risk of death and disease. These include increased exposure to physical and environmental harm in the workplace, propensity for risk-taking behaviors, and masculinity defined norms of health behavior that may negatively impact both acute and chronic illness-related outcomes.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `<!--3. -->All of the following factors are classical components of metabolic syndrome, EXCEPT:`,
    q2: ``,
    q3: [],
    option: [
      `Hypertension`,
      `<!--b. -->Abdominal obesity`,
      `<!--c. -->Insulin resistance/hyperglycemia`,
      `Dyslipidemia`,
      `<!--e. -->Lower urinary tract symptoms`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [4],
    ansText: `Rationale: The WHO, American Association of Clinical Endocrinologists (AACE), European Group for the Study of Insulin Resistance (EGIR), Adult Treatment Panel III (ATP III), and International Diabetes Federation definitions of metabolic syndrome comprise different criteria for defining metabolic syndrome. Classic definition includes hypertension, abdominal obesity, dyslipidemia, and insulin resistance (or hyperglycemia). Lower urinary tract symptoms (LUTS) have been linked with metabolic syndrome by epidemiologic data but are not included in its definition.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `<!--4. -->Which of the following statements regarding the physiology of metabolic syndrome is TRUE?`,
    q2: ``,
    q3: [],
    option: [
      `<!--a. -->Obesity, adipocyte hypertrophy, and adipocyte hyperplasia lead to systemic suppression of inflammatory processes`,
      `<!--b. -->Insulin resistance results in the suppression of pancreatic beta cells, leading to diminished insulin secretion and reduced circulating insulin levels`,
      `<!--c. -->Insulin resistance results in decreased very-low-density lipoprotein (VLDL) production and increased VLDL clearance`,
      `<!--d. -->Insulin resistance and hyperinsulinemia lead to sympathetic nervous system hyperactivity`,
      `<!--e. -->Genetics play a major role in the etiology of metabolic syndrome.`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [3],
    ansText: `Rationale:  Metabolic syndrome includes a number of physiological alterations, including abdominal obesity, insulin resistance, dyslipidemia, and hypertension. Insulin resistance and hyperglycemia are associated with increased stimulation of pancreatic beta cells to secrete more insulin, resulting in hyperinsulinemia. Insulin resistance and hyperinsulinemia lead to hyperactivation of the sympathetic nervous system and hypertension.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `<!--5. -->The following urological conditions are linked with metabolic syndrome, EXCEPT:`,
    q2: ``,
    q3: [],
    option: [
      `<!--a. -->Kidney stones`,
      `<!--b. -->Bladder cancer`,
      `<!--c. -->Overactive bladder`,
      `Priapism`,
      `<!--e. -->Prostate cancer`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [3],
    ansText: `Rationale:  Metabolic syndrome was classically associated with elevated risk of cardiovascular disease, diabetes, and stroke. Urological conditions are increasingly recognized to be highly prevalent among men with metastatic syndrome. Among these are renal conditions (such as renal insufficiency, urolithiasis, and renal tumors), bladder cancers, overactive bladder, lower urinary tract symptoms, prostate cancer, low testosterone levels, and erectile dysfunction.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `<!--6. -->Which of the following statements regarding metabolic syndrome is TRUE?`,
    q2: ``,
    q3: [],
    option: [
      `<!--a. -->Obesity is defined as BMI &gt;20 kg/m<sup>2</sup> in adults.`,
      `<!--b. -->Dietary or lifestyle modifications such as physical fitness may impact both incidence and outcomes of urological diseases.`,
      `<!--c. -->Exercise decreases insulin-mediated glucose uptake and stimulates inflammation.`,
      `<!--d. -->Dietary change, weight loss, and exercise exacerbate erectile dysfunction in majority of patients.`,
      `<!--e. -->There is no clinical evidence showing that exercise programs improve quality-of-life factors`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [1],
    ansText: `Rationale: Frequent physical exercise reduces the risk of many chronic diseases. Exercise increases insulin-mediated glucose uptake and decreases inflammation by reducing circulating levels of insulin-like growth factor (IGF-1). In addition to the meta-analyses showing benefit of exercise for reducing prostate cancer, a growing body of data links inactivity with worse disease outcomes.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `<!--7. -->Which of the following statements is FALSE?`,
    q2: ``,
    q3: [],
    option: [
      `<!--a. -->Reduction of circulating testosterone levels occurs as part of normal aging.`,
      `<!--b. -->Testosterone supplementation is available in formulations for oral, intramuscular, transdermal, sublingual, or transnasal routes.`,
      `<!--c. -->Clinical data suggest a modest impact of testosterone supplementation on physical functioning.`,
      `<!--d. -->Globally, testosterone prescribing has been decreasing over the past decades.`,
      `<!--e. -->Large-scale placebo-controlled prospective trials following patients over decades are needed to establish the safety and benefits of testosterone supplementation.`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [3],
    ansText: `Rationale: Testosterone has been approved and made available for treatment of hypogonadal males, including men with testicular trauma and those with rare bilateral tumors. While testosterone levels decrease as part of aging, the benefits and safety profile of exogenous testosterone supplementation have not been established. Despite the lack of conclusive data (requiring large-scale, placebo-controlled trials), use of testosterone supplements has increased significantly over the past years, with prescriptions for testosterone replacement therapy dramatically increasing in the UK and USA.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `<!--8. -->In making decisions regarding testosterone replacement therapy, the clinician should do all of the following, EXCEPT:`,
    q2: ``,
    q3: [],
    option: [
      `Limit diagnosis of testosterone deficiency to symptomatic males with unequivocally low testosterone levels.`,
      `Evaluate the patient’s history and risk of cardiovascular events.`,
      `Discuss potential risks of testosterone replacement therapy.`,
      `Evaluate patient’s history or risk of prostate cancer.`,
      `Recommend testosterone supplementation in men who are planning fertility in the near term.`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [4],
    ansText: `Rationale: The lack of conclusive clinical trial data makes it essential that the practicing clinician understands the controversies and is able to communicate them to her/his patients. Endocrine Society guidelines published in 2018 (a) advised the clinicians to limit the diagnosis of testosterone deficiency to symptomatic males with unequivocally low testosterone levels; (b) recommend against testosterone replacement therapy in men planning fertility in the near term and those with conditions that could be exacerbated by testosterone; and (c) recommend discussing the potential risks (including cardiovascular) associated with testosterone-replacement therapy.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `<!--9. -->Testosterone replacement should not be recommended in:`,
    q2: ``,
    q3: [],
    option: [
      `<!--a. -->men planning fertility in the near term.`,
      `<!--b. -->men with breast or prostate cancer, or at significant risk of prostate cancer.`,
      `<!--c. -->men with elevated hematocrit.`,
      `<!--d. -->men with uncontrolled heart failure, myocardial infarction, or stroke within the last 6 months.`,
      `all of the above.`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [4],
    ansText: `Rationale: According to the guidelines of the Endocrine Society, testosterone should not be prescribed to men with breast or prostate cancer, those planning fertility in the near term, or in those with significant prostate cancer risk, elevated hematocrit, untreated severe obstructive sleep apnea, severe lower urinary tract symptoms, uncontrolled heart failure, myocardial infarction, or stroke within the last 6 months, or thrombophilia.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `<!--10. -->The following predisposing risk factors and pathological processes apply to both cardiovascular disease and erectile dysfunction, EXCEPT:`,
    q2: ``,
    q3: [],
    option: [
      `Dyslipidemia`,
      `Inflammation`,
      `Atherosclerosis`,
      `Hypotension`,
      `Type 2 diabetes mellitus`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [3],
    ansText: `Rationale: There are a host of predisposing risk factors and underlying pathophysiologic processes for both cardiovascular disease (CVD) and erectile dysfunction (ED). These include, but are not limited to dyslipidemia, smoking, hypertension, and T2DM. The underlying mechanisms of both CVD and ED include inflammation, atherosclerosis, and endothelial dysfunction.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `<!--11. -->Which of the following is FALSE of the relationship between erectile dysfunction and cardiovascular disease?`,
    q2: ``,
    q3: [],
    option: [
      `<!--a. -->Erectile dysfunction could be an early warning of elevated risk of sudden cardiovascular events.`,
      `<!--b. -->Severity and duration of erectile dysfunction has been correlated with the magnitude of coronary disease.`,
      `<!--c. -->There is a clear and defined temporal relationship between erectile dysfunction and cardiovascular disease.`,
      `<!--d. -->Coronary artery calcium score can serve as a marker of atherosclerosis in arteries, including penile arteries.`,
      `<!--e. -->Erectile dysfunction and cardiovascular disorders are increasingly considered to be independent predictors of each other.`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [2],
    ansText: `Rationale: There is emerging consensus that erectile dysfunction and cardiovascular disease are independent risk factors for each other. However, the temporal relationship between the two disorders is less clear. A landmark study, The Multi-Ethnic Study of Atherosclerosis (MESA), demonstrated that subclinical cardiovascular disease is a predictor of erectile dysfunction and potentially of subsequent major adverse cardiac events. Earlier studies suggest that there is a 2- to 3-year interval between the onset of erectile dysfunction and cardiovascular symptoms. Since about 50% of men with sudden cardiovascular events may have had no previous symptoms, ED may be the single warning of the elevated risk of sudden cardiovascular events.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `<!--12. -->Which of the following statements about mental health is FALSE?`,
    q2: ``,
    q3: [],
    option: [
      `<!--a. -->Suicide rate in women is four times higher than in men.`,
      `<!--b. -->An equal number of men and women develop bipolar disorder.`,
      `<!--c. -->Ninety percent of people diagnosed with schizophrenia before the age of 30 are men.`,
      `<!--d. -->Men predisposed to suicide are those that are middle-aged and of lower socioeconomic class.`,
      `<!--e. -->Over 6 million men in the United States suffer from depression.`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [0],
    ansText: `Rationale: Mental illnesses, including anxiety, depression, and suicide, are becoming increasingly prevalent, while concomitantly being underdiagnosed, in men. Specifically, over 6 million men suffer from depression including symptoms such as fatigue, irritability, and loss of interest in work or hobbies. High rates of mental illness have led to a significant increase in incidences of both suicide and substance abuse. Highest prevalence of suicide in the United States occurred in people between ages 45 and 54, with men exhibiting a suicide rate four times higher than women.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `<!--13. -->Which of the following is TRUE of opioid abuse?`,
    q2: ``,
    q3: [],
    option: [
      `<!--a. -->Prevalence of opioid abuse has been decreasing in recent years.`,
      `<!--b. -->Physicians prescribing opioids are encouraged to initially prescribe the lowest effective dose.`,
      `<!--c. -->Chronic opioid use stimulates hypothalamic-pituitary-gonadal axis.`,
      `<!--d. -->Opioid-related endocrine dysfunction could drive some chronic opioid users to seek formal treatment.`,
      `b and d.`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [1],
    ansText: `Rationale: In recent years the emotional and economic consequences of opioid misuse on public health has increased dramatically and is now understood as a major source of morbidity and mortality in the United States. Despite a decrease in the number of total opioids prescribed in the U.S. from a peak in 2012, some 33,000 people died of opioid overdoses in 2015 (including 15,000 from prescription sources), and currently more than 115 Americans die daily after overdosing on opioids. There appears to be a high degree of variability in the dispensing of pain medications after surgery and there are some who routinely dispense above recommended safety thresholds. Urologists need to foster greater awareness of the potential harms associated with even a short course of opioids. Those prescribing should adopt responsible prescribing practices, such as initially prescribing the lowest effective dose and offering repeat assessments as needed.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `<!--14. -->General categories of a comprehensive approach to integrative men’s health should include all of the following, EXCEPT:`,
    q2: ``,
    q3: [],
    option: [
      `<!--a. -->Conditions that are unique to men.`,
      `<!--b. -->Diseases or illnesses that are more prevalent in men compared to women.`,
      `<!--c. -->Health issues that are not covered by other specialties (e.g., cardiology, endocrinology).`,
      `<!--d. -->Health issues for which risk factors and adverse outcomes are different in men.`,
      `<!--e. -->Health issues for which different interventions to achieve improvements are required for men.`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [2],
    ansText: `Rationale: A men’s health center should be focused on conditions, diseases, and health issues that exhibit higher impact on men, or that require unique strategies in men. A men’s health curriculum must include contributions from a host of medical specialties. Optimally, such a center should include partnerships with various subspecialists in cardiology, endocrinology, psychiatry, orthopedics, and dermatology.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
];
