var quiz = [
  {
    q: `<!--1. -->The route that sperm travel through from the seminiferous tubules to the epididymis, in order, is:`,
    q2: ``,
    q3: [],
    option: [
      `<!--a. -->straight tubules, efferent ductules, rete testis.`,
      `<!--b. -->rete testis, straight tubules, efferent ductules.`,
      `<!--c. -->efferent ductules, rete testis, straight tubules.`,
      `<!--d. -->straight tubules, rete testis, efferent ductules.`,
      `<!--e. -->rete testis, efferent ductules, straight tubules.`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [3],
    ansText: `Rationale: Septa form 200 to 300 cone-shaped lobules, each containing one or more convoluted seminiferous tubules. Each tubule is U-shaped and has a stretched length of nearly 1 m. Interstitial (Leydig) cells lie in the loose tissue surrounding the tubules and are responsible for testosterone production. Toward the apices of the lobules, the seminiferous tubules become straight (tubuli recti) and enter the mediastinum testis to form an anastomosing network of tubules lined by flattened epithelium. <b>This network, known as the <i>rete testis</i>, forms 12 to 20 efferent ductules and passes into the largest portion of epididymis, the caput.</b>`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `Septa form 200 to 300 cone-shaped lobules, each containing one or more convoluted seminiferous tubules. Each tubule is U-shaped and has a stretched length of nearly 1 m. Interstitial (Leydig) cells lie in the loose tissue surrounding the tubules and are responsible for testosterone production. Toward the apices of the lobules, the seminiferous tubules become straight (tubuli recti) and enter the mediastinum testis to form an anastomosing network of tubules lined by flattened epithelium. <b>This network, known as the <i>rete testis</i>, forms 12 to 20 efferent ductules and passes into the largest portion of epididymis, the caput.</b>`,
    q2: ``,
    q3: [],
    option: [
      `<!--a. -->visceral tunica vaginalis, tunica albuginea, tunica vasculosa.`,
      `<!--b. -->tunica vasculosa, tunica albuginea, visceral tunica vaginalis.`,
      `<!--c. -->tunica albuginea, tunica vasculosa, visceral tunica vaginalis.`,
      `<!--d. -->visceral tunica vaginalis, tunica vasculosa, tunica albuginea.`,
      `<!--e. -->tunica albuginea, visceral tunica vaginalis, tunica vasculosa.`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [0],
    ansText: `Rationale: The testis is enveloped by a tough capsule composed, from external to internal, of the visceral tunica vaginalis, the tunica albuginea, and the tunica vasculosa, before reaching the parenchyma of the testis. The tunica albuginea is composed of smooth muscle cells that pass through collagenous tissue.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `<!--3. -->What percentage of testicular volume is made up by interstitium?`,
    q2: ``,
    q3: [],
    option: [
      `<!--a. -->10% to 20%`,
      `<!--b. -->20% to 30%`,
      `<!--c. -->30% to 40%`,
      `<!--d. -->40% to 50%`,
      `<!--e. -->50% to 60%`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [1],
    ansText: `Rationale: <b>The testicular interstitial tissue includes Leydig cells, mast cells, macrophages, nerves, blood vessels, and lymphatic vessels.</b> This interstitial tissue makes up 20% to 30% of the testicular volume.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `<!--4. -->Which of the following is the main arterial supply to the testis?`,
    q2: ``,
    q3: [],
    option: [
      `<!--a. -->Testicular artery`,
      `<!--b. -->Superficial dorsal artery`,
      `<!--c. -->The artery of the vas deferens`,
      `<!--d. -->Cremasteric artery`,
      `<!--e. -->Deep dorsal artery`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [0],
    ansText: `Rationale: <b>There are three arterial supplies to the testis: the testicular (internal spermatic) artery, the artery of the vas deferens (deferential artery), and the cremasteric (external spermatic) artery. The testicular artery is the main blood supply to the testis, and its diameter is greater than the deferential and cremasteric arteries combined.</b>`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `<!--5. -->The lymphatic drainage from the testis drains to:`,
    q2: ``,
    q3: [],
    option: [
      `<!--a. -->superficial and deep inguinal nodes.`,
      `<!--b. -->external and internal iliac nodes.`,
      `<!--c. -->para-aortic and interaortocaval nodes.`,
      `<!--d. -->internal iliac and obturator nodes.`,
      `<!--e. -->external iliac and obturator nodes.`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [2],
    ansText: `Rationale: Lymphatic channels from the testis drain into the para-aortic and interaortocaval lymph nodes. These lymphatic channels ascend within the spermatic cord after leaving the testis.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `<!--6. -->The cremaster muscle is innervated by the:`,
    q2: ``,
    q3: [],
    option: [
      `<!--a. -->ilioinguinal nerve.`,
      `<!--b. -->genital branch of the genitofemoral nerve.`,
      `<!--c. -->femoral branch of the genitofemoral nerve.`,
      `<!--d. -->terminal branches of the subcostal nerve (T12).`,
      `<!--e. -->iliohypogastric nerve.`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [1],
    ansText: `Rationale: The genital branch of the genitofemoral nerve follows the spermatic cord through the inguinal canal, supplies the cremaster muscle, and supplies sensation to the anterior scrotum.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `<!--7. -->The nerves thought to be the main contributors to pain in men with chronic orchialgia include:`,
    q2: ``,
    q3: [],
    option: [
      `<!--a. -->perivasal complex.`,
      `<!--b. -->posterior periarterial/lipomatous complex.`,
      `<!--c. -->intracremasteric complex.`,
      `<!--d. -->femoral branch of the genitofemoral nerve.`,
      `<!--e. -->a, b, and c.`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [4],
    ansText: `Rationale: Three distinct anatomic distributions of nerves have been isolated within the spermatic cord and are thought to be the primary contributors in men with chronic orchialgia. These include a perivasal complex, posterior periarterial/lipomatous complex, and intracremasteric complex.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `<!--8. -->The anatomic component of the blood-testis barrier is the:`,
    q2: ``,
    q3: [],
    option: [
      `<!--a. -->tight junctions between Sertoli cells.`,
      `<!--b. -->myoendothelial junctions.`,
      `<!--c. -->tunica albuginea.`,
      `<!--d. -->basement membrane of seminiferous tubules.`,
      `<!--e. -->centrifugal arteries.`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [0],
    ansText: `Rationale: <b>There are extremely strong tight junctions between Sertoli cells, which provide an intracellular barrier that allows for spermatogenesis in an immune-privileged site.</b> This is the barrier known as the <b><i>blood-testis barrier.</i></b>`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `<!--9. -->The ducts of which of the following prostatic zones drain into the preprostatic urethra?`,
    q2: ``,
    q3: [],
    option: [
      `<!--a. -->Periurethral glands`,
      `<!--b. -->Central zone`,
      `<!--c. -->Transition zone`,
      `<!--d. -->Peripheral zone`,
      `<!--e. -->a and c`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [0],
    ansText: `Rationale: At its midpoint, the urethra turns approximately 35 degrees anteriorly, but this angulation can vary from 0 to 90 degrees. This angle divides the prostatic urethra into proximal (preprostatic) and distal (prostatic) segments, which are functionally and anatomically discrete. Small periurethral glands, lacking periglandular smooth muscle, extend between the fibers of the longitudinal smooth muscle to be enclosed by the preprostatic sphincter.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `<!--10. -->Benign prostatic hyperplasia (BPH) arises from the:`,
    q2: ``,
    q3: [],
    option: [
      `<!--a. -->periurethral glands.`,
      `<!--b. -->central zone.`,
      `<!--c. -->transition zone.`,
      `<!--d. -->peripheral zone.`,
      `<!--e. -->a and c.`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [4],
    ansText: `Rationale: The periurethral glands can contribute significantly to prostatic volume in older men as one of the sites of origin of BPH. The transition zone commonly gives rise to BPH.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `<!--11. -->Lymphatic drainage from the prostate drains to the:`,
    q2: ``,
    q3: [],
    option: [
      `<!--a. -->external iliac and common iliac nodes.`,
      `<!--b. -->internal iliac and obturator nodes.`,
      `<!--c. -->para-aortic nodes.`,
      `<!--d. -->internal iliac and inguinal nodes.`,
      `<!--e. -->perirectal and common iliac nodes.`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [1],
    ansText: `Rationale: Lymphatic drainage is primarily to the obturator and internal iliac nodes.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `<!--12. -->The apex of the prostate is continuous with the:`,
    q2: ``,
    q3: [],
    option: [
      `<!--a. -->bladder neck.`,
      `<!--b. -->pubococcygeal portion of the of the levator ani.`,
      `<!--c. -->arcus tendineus fascia pelvis.`,
      `<!--d. -->bulbar urethra.`,
      `<!--e. -->striated urethral sphincter.`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [4],
    ansText: `Rationale: The prostate is enveloped by a collagen, elastin, and smooth muscle capsule. The capsule measures 0.5 mm in thickness posteriorly and laterally on average. <b>There is no true prostatic capsule at the apex of the prostate, where normal prostate glands are seen blending into the striated muscle of the urethral sphincter.</b>`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `<!--13. -->Lymphatic drainage from the bulbar urethra travels:`,
    q2: ``,
    q3: [],
    option: [
      `<!--a. -->through the perianal nodes to reach the pelvis.`,
      `<!--b. -->directly to the deep pelvic lymph nodes.`,
      `<!--c. -->through the superficial and deep inguinal lymph nodes.`,
      `<!--d. -->to the prepubic nodes.`,
      `<!--e. -->to para-aortic lymph nodes along with testicular drainage.`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [2],
    ansText: `Rationale: The penis, scrotum, and perineum drain into the inguinal lymph nodes. These nodes can be divided into superficial groups and deep groups.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `<!--14. -->The only segment of the urethra that does not have transitional epithelium is the:`,
    q2: ``,
    q3: [],
    option: [
      `<!--a. -->prostatic urethra.`,
      `<!--b. -->membranous urethra.`,
      `<!--c. -->bulbar urethra.`,
      `<!--d. -->bulbomembranous urethra.`,
      `<!--e. -->fossa navicularis.`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [4],
    ansText: `Rationale: <b>Unlike the transitional epithelium of the remainder of the urethra, the urethral mucosa that traverses the glans penis is squamous epithelium.</b> These cells become keratinized near the meatus.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `<!--15. -->The glans penis is the most distal expansion of the:`,
    q2: ``,
    q3: [],
    option: [
      `<!--a. -->corpus cavernosum.`,
      `<!--b. -->corpus spongiosum.`,
      `<!--c. -->prepuce.`,
      `urethra.`,
      `<!--e. -->Buck’s fascia.`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [1],
    ansText: `Rationale: The glans penis is an expansion of the corpus spongiosum.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `<!--16. -->The dartos layer of smooth muscle and fascia in the scrotum is continuous with:`,
    q2: ``,
    q3: [],
    option: [
      `<!--a. -->the dartos layer of the penis.`,
      `<!--b. -->Colles fascia.`,
      `<!--c. -->Scarpa fascia.`,
      `<!--d. -->Buck’s fascia.`,
      `<!--e. -->a, b, and c.`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [4],
    ansText: `Rationale: The dartos layer of smooth muscle is anatomically continuous with Colles fascia, Scarpa fascia, and the dartos fascia of the penis.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
];
