var quiz = [
  {
    q: `<!--1. -->For couples practicing optimal timing methods to conceive, the proportion who conceive after six cycles should be approximately:`,
    q2: ``,
    q3: [],
    option: [`1/2.`, `1/3.`, `1/5.`, `2/5.`, `4/5.`],
    optionStyleType: `st-lower-alpha`,
    answer: [4],
    ansText: `Rationale:  Cumulative pregnancy rates in a well-conducted study were 38% at one cycle, 68% at three cycles, 81% at six cycles, and 92% at 12 cycles (Gnoth et al., 2003).<a href="[remark:384d074881c64ac885f46aa9886080ef]"><sup>a</sup></a>`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `<!--2. -->For couples desiring to conceive, around the time of ovulation, they should have intercourse:`,
    q2: ``,
    q3: [],
    option: [
      `daily.`,
      `twice daily.`,
      `every other day.`,
      `in the morning.`,
      `near noon.`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [0],
    ansText: `Rationale: Although prior recommendations specified intercourse every other day to optimize the probability of conception, a recent study demonstrated that intercourse every day around the time of ovulation is likely the best strategy (Scarpa et al., 2007).`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `<!--3. -->In the industrialized world, female fecundity typically declines most rapidly after:`,
    q2: ``,
    q3: [],
    option: [
      `puberty.`,
      `age 30 years.`,
      `age 35 years.`,
      `age 40 years.`,
      `menopause.`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [2],
    ansText: `Rationale: Whereas women in developing nations may experience a rapid decline in fecundity at a younger age, in the industrialized world, female fecundity declines precipitously after age 35 years (Balasch and Gratac&#243;s, 2012).`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `<!--4. -->All of the following medications are associated with male reproductive dysfunction EXCEPT:`,
    q2: ``,
    q3: [],
    option: [
      `cimetidine.`,
      `spironolactone.`,
      `indinavir.`,
      `prednisone.`,
      `lisinopril.`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [4],
    ansText: `Rationale: All agents listed are spermatotoxins except lisinopril, which may improve bulk seminal parameters (Mbah et al., 2012).`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `<!--5. -->A man with oligoasthenospermia has inflammatory bowel disease and is prescribed sulfasalazine. He should be counseled to:`,
    q2: ``,
    q3: [],
    option: [
      `<!--a. -->repeat a semen analysis.`,
      `<!--b. -->continue sulfasalazine.`,
      `<!--c. -->substitute sulfasalazine with colchicine.`,
      `<!--d. -->substitute sulfasalazine with mesalazine.`,
      `<!--e. -->discontinue all medications.`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [3],
    ansText: `Rationale: Sulfasalazine is associated with oligoasthenospermia (Stein and Hanauer, 2000). If sulfasalazine is substituted with mesalazine, adverse effects on sperm are generally reversible (Riley et al., 1987).`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `<!--6. -->A 30-year-old man is attempting to conceive with his 28-year-old wife. She is diagnosed with premature ovarian failure, and hematoxylin and eosin microscopic staining of his sperm is consistent with the presence of <i>Escherichia coli.</i> His bulk seminal parameters are otherwise unremarkable. You recommend:`,
    q2: ``,
    q3: [],
    option: [
      `<!--a. -->swim up and intrauterine insemination (IUI).`,
      `<!--b. -->a 3-week course of ciprofloxacin, 500 mg twice daily.`,
      `<!--c. -->prostatic culture.`,
      `<!--d. -->seminal vesicle aspiration for culture.`,
      `<!--e. -->observation.`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [4],
    ansText: `Rationale: Limited seminal concentrations of the majority of bacteria including <b><i>E. coli</i></b> have minimal or no effects on sperm motility in vivo (Diemer et al., 2003; Lackner et al., 2006).`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `<!--7. -->The effect of human immunodeficiency virus (HIV) infection on bulk seminal parameters is:`,
    q2: ``,
    q3: [],
    option: [
      `<!--a. -->none.`,
      `<!--b. -->decreased motility.`,
      `<!--c. -->increased number of morphologically abnormal forms.`,
      `<!--d. -->decreased concentration.`,
      `<!--e. -->decreased volume.`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [0],
    ansText: `Rationale: <!--<b>a. None.</b>--> HIV does not appear to be correlated with a direct negative effect on sperm function (Garrido et al., 2005).`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `<!--8. -->Direct exposure of the testis to ionizing radiation causes irreparable damage to spermatogenesis at doses at and above:`,
    q2: ``,
    q3: [],
    option: [`2.5 Gy.`, `5 Gy.`, `7.5 Gy.`, `10 Gy.`, `20 Gy.`],
    optionStyleType: `st-lower-alpha`,
    answer: [2],
    ansText: `Rationale: The probability of future fatherhood is significantly decreased with radiation doses to the testes of 7.5 Gy and above (Green et al., 2010). The testis does not need to be directly exposed for adverse spermatogenic effects to occur.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `<!--9. -->The typical differential between core body and scrotal temperature is:`,
    q2: ``,
    q3: [],
    option: [
      `<!--a. -->0.5&#176;C.`,
      `<!--b. -->0.5&#176;F.`,
      `<!--c. -->1&#176;C to 2&#176;C.`,
      `<!--d. -->2&#176;C to 4&#176;C.`,
      `<!--e. -->6&#176;C.`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [3],
    ansText: `Rationale: Unlike female gonads, the testes are extracorporeal and subject to thermal regulation by a vascular heat exchange mechanism and muscular activity controlling proximity to the body, resulting in a scrotal temperature maintained between 2&#176;C and 4&#176;C below body core temperature (Setchell, 1998; Thonneau et al., 1998).`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `<!--10. -->An 18-year-old man has bilateral testes palpable at the external inguinal rings. He desires to father children in the future. Two centrifuged semen analyses reveal azoospermia. Serum testosterone is 410 ng/dL, and follicle-stimulating hormone is 22 IU/L. The best next step is:`,
    q2: ``,
    q3: [],
    option: [
      `<!--a. -->counsel that when he is ready, he and his partner should use donor sperm or adopt.`,
      `<!--b. -->clomiphene citrate, 50 mg every other day.`,
      `<!--c. -->testis biopsy.`,
      `<!--d. -->microsurgical testis sperm extraction with cryopreservation if sperm are found.`,
      `<!--e. -->bilateral orchidopexy.`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [4],
    ansText: `Rationale: The most significant feature affecting this man’s reproductive potential is bilateral cryptorchidism. Although the likelihood of improving fertility is hampered by his advanced age, no value will be derived from waiting. Testis biopsy is unnecessary, and his total testosterone is adequate. In this patient with distal cryptorchidism who does not desire offspring presently, removing the spermatotoxic insult of cryptorchidism is the most prudent course.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `<!--11. -->The lubricant that does NOT affect sperm function or DNA integrity is:`,
    q2: ``,
    q3: [],
    option: [`Astroglide.`, `K-Y Jelly.`, `Pre-Seed.`, `Replens.`, `saliva.`],
    optionStyleType: `st-lower-alpha`,
    answer: [2],
    ansText: `Rationale: Nearly all lubricants are spermatotoxic, including saliva. In a study of a variety of lubricants, Pre-Seed did not result in a significant decrease in sperm motility or chromatin integrity (Agarwal et al., 2008).`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `<!--12. -->The serum hormonal pattern commonly observed in male obesity is: <br/> 
        <div xmlns:tnq="http://www.tnq.co.in/epub3/" class="pageavoid">
<p class="tnum"/>
<div class="big_device">
<table id="t0010" class="tbody">
<thead>
<tr>
<th scope="col" class="tcolhd1"/>
<th scope="col" class="tcolhd1">Testosterone</th>
<th scope="col" class="tcolhd1">Sex Hormone–Binding Globulin (SHBG)</th>
<th scope="col" class="tcolhd1">Estradiol</th>
</tr>
</thead>
<tbody>
<tr>
<th scope="row" class="tb">a.</th>
<td class="tb">↓</td>
<td class="tb">↓</td>
<td class="tb">↓</td>
</tr>
<tr>
<th scope="row" class="tb">b.</th>
<td class="tb">↓</td>
<td class="tb">↓</td>
<td class="tb">↑</td>
</tr>
<tr>
<th scope="row" class="tb">c.</th>
<td class="tb">↓</td>
<td class="tb">↑</td>
<td class="tb">↓</td>
</tr>
<tr>
<th scope="row" class="tb">d.</th>
<td class="tb">↓</td>
<td class="tb">↑</td>
<td class="tb">↑</td>
</tr>
<tr>
<th scope="row" class="tb">e.</th>
<td class="tb">↑</td>
<td class="tb">↑</td>
<td class="tb">↑</td>
</tr>
</tbody>
</table>
</div>
<div class="small_device">
<p class="table_fig">
<img src="B9780323639699000665_t0010_0.png" alt="image"/>
</p>
</div>
</div>`,
    q2: ``,
    q3: [],
    option: [`a`, `b`, `c`, `d`, `e`],
    optionStyleType: `st-lower-alpha`,
    answer: [1],
    ansText: `Rationale: In obese males, serum testosterone is decreased (Hammoud et al., 2006). SHBG is typically reduced, likely because of increased circulating insulin (Hammoud et al., 2006; 2008; Pauli et al., 2008; Teerds et al., 2011). Estradiol is increased because of peripheral conversion from testosterone by an overabundance of adipose cells containing the enzyme aromatase (Aggerholm et al., 2008; Chavarro et al., 2010; Hammoud et al., 2006, 2010; Hofny et al., 2010).`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `<!--13. -->The finding most consistent with spermatogenic impairment is:`,
    q2: ``,
    q3: [],
    option: [
      `<!--a. -->a testis volume as measured by Prader orchidometer less than 30 mL.`,
      `<!--b. -->a testis volume as measured by scrotal ultrasonography less than 30 mL.`,
      `<!--c. -->a testis longitudinal axis as measured by caliper orchidometer less than 4.6 cm.`,
      `<!--d. -->an engorged epididymis.`,
      `<!--e. -->an absent vas deferens.`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [2],
    ansText: `Rationale: A measurement of the long axis of the testis of 4.6 cm or less is associated with spermatogenic impairment (Schoor et al., 2001).`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `<!--14. -->A man evaluated for azoospermia has absent vasa bilaterally. The next step is cystic fibrosis transmembrane conductance regulator (CFTR) gene sequence assay for him and his partner and:`,
    q2: ``,
    q3: [],
    option: [
      `<!--a. -->transrectal ultrasound.`,
      `<!--b. -->renal ultrasound.`,
      `<!--c. -->postejaculatory urinalysis.`,
      `<!--d. -->seminal vesicle aspiration.`,
      `<!--e. -->testis biopsy.`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [1],
    ansText: `Rationale: Renal agenesis is noted in 11% of men with congenital bilateral absence of the vas deferens (Schlegel et al., 1996).`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `<!--15. -->The following condition increases sex hormone–binding globulin (SHBG):`,
    q2: ``,
    q3: [],
    option: [
      `aging`,
      `<!--b. -->diabetes mellitus`,
      `hypothyroidism`,
      `obesity`,
      `testosterone therapy`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [0],
    ansText: `Rationale: <!--<b>a. Aging.</b>--> Concentration of SHBG increases with age, resulting in decreased bioavailable testosterone (Bhasin et al., 2010).`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `<!--16. -->A man is found to be azoospermic. The following most strongly suggests spermatogenic dysfunction as a cause rather than obstruction:`,
    q2: ``,
    q3: [],
    option: [
      `<!--a. -->testis long axis on physical examination 4.2 cm, FSH assay 4 IU/L`,
      `<!--b. -->testis long axis on physical examination 4.3 cm, FSH assay 10 IU/L`,
      `<!--c. -->bioavailable testosterone, 166 ng/dL, FSH assay 6 IU/L`,
      `<!--d. -->luteinizing hormone (LH), 2 IU/L, FSH 2 IU/L`,
      `<!--e. -->testosterone, 160 ng/dL, LH 9 IU/L`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [1],
    ansText: `Rationale: If the FSH assay result is 7.6 IU/L or less and the testis long axis is greater than 4.6 cm, the probability of obstruction is 96%; conversely, if the FSH values is greater than 7.6 IU/L and the testis long axis 4.6 cm or less, the probability that azoospermia is due to spermatogenic dysfunction is 89% (Schoor et al., 2001).`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `<!--17. -->A reasonable threshold for sperm concentration above which a man can be considered fertile is:`,
    q2: ``,
    q3: [],
    option: [
      `<!--a. -->15 million/mL.`,
      `<!--a. -->20 million/mL.`,
      `<!--a. -->48 million/mL.`,
      `<!--a. -->80 million/mL.`,
      `<!--a. -->200 million/mL.`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [2],
    ansText: `Rationale: By classification and regression tree analysis, or CART, one large study demonstrated that for sperm concentration, 13.5 million/mL was found to be the lower parameter below which IUI success would be unlikely, and 48.0 million/mL was identified as the upper parameter above which IUI outcomes were favorable (Guzick et al., 2001).`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `<!--18. -->Brown-hued semen is often associated with:`,
    q2: ``,
    q3: [],
    option: [
      `<!--a. -->ingested asparagus.`,
      `<!--b. -->ejaculatory ductal obstruction.`,
      `<!--c. -->sexual activity.`,
      `<!--d. -->spinal cord injury.`,
      `<!--e. -->urinary tract infection.`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [3],
    ansText: `Rationale: The ejaculate is normally white or light gray. A brown hue is often observed in spinal cord–injured men (Centola, 2011; World Health Organization, 2010).`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `<!--19. -->The optimal time in days of abstinence to wait after an ejaculate for a semen analysis is:`,
    q2: ``,
    q3: [],
    option: [`1.`, `2.`, `3.`, `5.`, `7.`],
    optionStyleType: `st-lower-alpha`,
    answer: [0],
    ansText: `Rationale: A single day of abstinence is optimal for assessing bulk seminal parameters (Elzanaty, 2008; Levitas et al., 2005).`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `<!--20. -->A man who has been unsuccessful in impregnating his wife during the past year is identified to have azoospermia and semen volumes of 0.8 and 0.5 mL. The next step is:`,
    q2: ``,
    q3: [],
    option: [
      `<!--a. -->testis biopsy.`,
      `<!--b. -->scrotal ultrasound.`,
      `<!--c. -->postejaculatory urinalysis.`,
      `<!--d. -->clomiphene citrate, 50 mg every other day.`,
      `<!--e. -->transurethral resection of ejaculatory ducts.`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [2],
    ansText: `Rationale: The differential diagnosis of seminal hypovolemia includes retrograde ejaculation, ejaculatory ductal obstruction, and accessory sex gland hypoplasia. The simplest and least invasive test to exclude a diagnosis of retrograde ejaculation is postejaculatory urinalysis, and this should be performed first.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `<!--21. -->A 32-year-old man presents for fertility evaluation. Physical exam and endocrine assessment are normal. Semen analysis demonstrates volume 2.5 mL, density 84 million/mL, motility 71%, and strict morphology 0% with a variety of abnormal forms. The next step is:`,
    q2: ``,
    q3: [],
    option: [
      `<!--a. -->vitamin E.`,
      `reassurance.`,
      `<!--c. -->testis biopsy.`,
      `<!--d. -->scrotal ultrasound.`,
      `<!--e. -->antisperm antibody assay.`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [1],
    ansText: `Rationale: This man’s bulk seminal parameters are adequate with the exception of morphology. The variety of abnormal forms excludes rare genetic conditions such as failure of formation of the acrosomal cap. The assessing technician likely overread abnormal forms, and the patient should be reassured.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `<!--22. -->Two semen analyses from a man undergoing a reproductive evaluation include volumes of 2.5 and 1.8 mL, densities of 24 and 28 million/mL, and motility 0%. The next step is:`,
    q2: ``,
    q3: [],
    option: [
      `<!--a. -->vital stain.`,
      `<!--b. -->immunobead assay.`,
      `<!--c. -->repeat semen analysis.`,
      `<!--d. -->sperm chromatin structure assay (SCSA).`,
      `<!--e. -->computer-assisted semen analysis (CASA).`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [0],
    ansText: `Rationale: In cases of complete asthenospermia, assessment of antisperm antibodies with the immunobead assay is not possible, as it requires some motile sperm. The first diagnosis to exclude is necrospermia, which may be investigated with a vital stain.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `<!--23. -->Semen observed under phase contrast light microscopy reveals abundant round cells similar in size and shape to leukocytes. The next step is:`,
    q2: ``,
    q3: [],
    option: [
      `<!--a. -->semen culture.`,
      `<!--b. -->Papanicolaou staining.`,
      `<!--c. -->transrectal ultrasound.`,
      `<!--d. -->ciprofloxacin, 1 g daily for 4 weeks.`,
      `<!--e. -->ibuprofen, 400 mg daily for 2 weeks.`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [1],
    ansText: `Rationale: Leukocytes and immature germ cells are not differentiable with light microscopy. A simple stain such as Papanicolaou allows the two to be distinguished (World Health Organization, 2010).`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `<!--24. -->A direct assay of sperm-head DNA fragmentation is the:`,
    q2: ``,
    q3: [],
    option: [
      `<!--a. -->terminal deoxynucleotidyl transferase dUTP nick end labeling (TUNEL) assay.`,
      `<!--b. -->acid comet assay.`,
      `<!--c. -->alkaline comet assay.`,
      `<!--d. -->sperm chromatin dispersion (SCD) assay.`,
      `<!--e. -->SCSA.`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [0],
    ansText: `Rationale:  Direct measures of sperm DNA fragmentation include the TUNEL assay and the comet assay at neutral pH. The other assays listed include denatured DNA (Sakkas and Alvarez, 2010).`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `<!--25. -->The assay that most closely models incubational in vitro fertilization is:`,
    q2: ``,
    q3: [],
    option: [
      `<!--a. -->reactive oxygen species-total antioxidant capacity (ROS-TAC).`,
      `<!--b. -->Penetrak assay.`,
      `<!--c. -->Tru-trax assay.`,
      `<!--d. -->sperm penetration assay.`,
      `<!--e. -->acrosomal assay.`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [3],
    ansText: `Rationale: To simulate incubational in vitro fertilization, human sperm are incubated with denuded hamster ova in the sperm penetration assay, or SPA (Margalioth et al., 1986; Yanagimachi et al., 1976).`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `<!--26. -->A 26-year-old man presenting for fertility evaluation has two semen analyses, one with volume 2.1 mL and density 32 million/mL, and another with volume 2.3 mL and density 28 million/mL. No motile sperm are observed in either, and vital stain demonstrated greater than 80% metabolically active sperm in both. The next step is:`,
    q2: ``,
    q3: [],
    option: [
      `<!--a. -->immunobead assay.`,
      `<!--b. -->pyospermia stain.`,
      `<!--c. -->electron microscopy.`,
      `SCSA.`,
      `repeat semen analysis.`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [2],
    ansText: `Rationale: Vital stain excluded necrospermia in this patient with complete asthenospermia. Electron microscopy will identify ultrastructural tail defects if present in the immotile cilia syndrome (Zini and Sigman, 2009).`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `<!--27. -->A 30-year-old man has azoospermia. Physical examination reveals absent vasa bilaterally. CFTR analysis reveals a ΔF508 mutation. The next step is:`,
    q2: ``,
    q3: [],
    option: [
      `<!--a. -->repeat CFTR analysis of the man with a 1600-mutation screen.`,
      `<!--b. -->repeat semen analysis.`,
      `<!--c. -->CFTR analysis of his wife.`,
      `<!--d. -->testicular sperm extraction.`,
      `<!--e. -->testis biopsy.`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [2],
    ansText: `Rationale: <!--<b>c. CFTR analysis of his wife.</b>--> Should the wife of this azoospermic man with a severe CFTR mutation harbor a severe mutation as well, a child born from surgically extracted sperm and intracytoplasmic sperm injection may be homozygous for a severe mutation and have clinical cystic fibrosis. In order to counsel the couple regarding the probability of that result, CFTR analysis of the wife is indicated.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `<!--28. -->A 28-year-old man desires a biological child. Physical examination is normal. Two semen analyses reveal azoospermia with volumes of 0.8 and 0.7 mL, and no sperm is identified in a postejaculatory urinalysis. FSH is 3.2 IU/L. Transrectal ultrasound reveals seminal vesicles of 0.9 and 1.1 cm in largest diameter, and no midline cyst is visualized. The next step is:`,
    q2: ``,
    q3: [],
    option: [
      `reassurance.`,
      `<!--b. -->testis biopsy.`,
      `<!--c. -->repeat semen analysis.`,
      `<!--d. -->transurethral resection of ejaculatory ducts.`,
      `<!--e. -->testis sperm extraction and cryopreservation.`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [4],
    ansText: `Rationale: This man’s normal physical examination and relatively low FSH indicates a high likelihood of adequate spermatogenesis and obstructive azoospermia. The lack of seminal vesicle dilation suggests that the probability of ejaculatory ductal obstruction is low. The next step is surgical sperm retrieval.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `<!--29. -->A 33-year-old man desires a biological child and is found to have azoospermia with semen volumes 2.2 and 2.4 mL on two analyses. Longitudinal axis of the left testis is 3.3 cm, and the right is 3.5 cm. Serum FSH is 9.3 IU/L, and testosterone is 440 ng/dL. The next step is:`,
    q2: ``,
    q3: [],
    option: [
      `<!--a. -->testis biopsy.`,
      `<!--b. -->epididymovasostomy.`,
      `<!--c. -->repeat semen analysis.`,
      `<!--d. -->microsurgical testis sperm extraction.`,
      `<!--e. -->clomiphene citrate, 50 mg every other day.`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [3],
    ansText: `Rationale: With the FSH assay result greater than 7.6 IU/L and the testes long axis measurements of 4.6 cm or less, the probability that azoospermia is due to spermatogenic dysfunction is 89% (Schoor et al., 2001). The next step is microsurgical testis sperm extraction.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `<!--30. -->A 30-year-old man desires a biological child with his 28-year-old wife. Her evaluation is normal. Semen analysis reveals density 84 million/mL and globozoospermia. The next step is:`,
    q2: ``,
    q3: [],
    option: [
      `<!--a. -->repeat semen analysis.`,
      `<!--b. -->clomiphene citrate, 50 mg every other day.`,
      `<!--c. -->in vitro fertilization after incubation of sperm with pentoxifylline.`,
      `<!--d. -->intracytoplasmic sperm injection with ejaculated sperm.`,
      `<!--e. -->microsurgical testis sperm extraction.`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [3],
    ansText: `Rationale: In globozoospermia, the sperm lack acrosomal caps, and sperm heads are rendered spheric rather than ovoid. Without the acrosome, fertilization with sperm in the natural setting or with incubational in vitro fertilization will not be successful. Intracytoplasmic sperm injection is required. Ejaculated sperm is available in this patient, and surgical sperm extraction is consequently unnecessary.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `<!--31. -->The most common genetic cause of male infertility is:`,
    q2: ``,
    q3: [],
    option: [
      `<!--a. -->r(Y).`,
      `<!--b. -->45,X0.`,
      `<!--c. -->47,XXY.`,
      `<!--d. -->47,XYY.`,
      `<!--e. -->46,XY/47,XXY.`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [2],
    ansText: `Rationale: The presence of a supernumerary X chromosome in 47,XXY, or Klinefelter syndrome, is the most common genetic cause of male infertility (Groth et al., 2013; Oates and Lamb, 2009; Sigman, 2012).`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `<!--32. -->The biological system responsible for protecting haploid male germ cells from the immune system is:`,
    q2: ``,
    q3: [],
    option: [
      `IgG.`,
      `Prostate specific antigen (PSA).`,
      `natural killer cells.`,
      `reactive oxygen species.`,
      `Sertoli cell tight junctions.`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [4],
    ansText: `Rationale: The haploid male gamete expresses different surface antigens than other diploid cells and is protected from the immune system by tight junctions between Sertoli cells (Walsh and Turek, 2009).`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `<!--33. -->A man presents with azoospermia. Testis longitudinal axis is 3.0 cm bilaterally, and the testes are soft. Laboratory evaluation reveals testosterone 140 ng/dL, LH less than 1.0 IU/L, and FSH less than 1.0 IU/L. The next step is:`,
    q2: ``,
    q3: [],
    option: [
      `<!--a. -->repeat semen analysis.`,
      `<!--b. -->transrectal ultrasound.`,
      `<!--c. -->microsurgical testis sperm extraction.`,
      `<!--d. -->smell test.`,
      `<!--e. -->Y-chromosomal microdeletion assay.`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [3],
    ansText: `Rationale: Anosmia associated with hypogonadotropic hypogonadism is known as Kallmann syndrome (Kallmann and Schoenfeld, 1944). In a patient with significantly low gonadotropin assay results, the presence of the syndrome is confirmed by a smell test.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `<!--34. -->A man presents with erectile dysfunction and azoospermia. Testis longitudinal axis is 5 cm bilaterally, and the testes are firm. Laboratory evaluation reveals bioavailable testosterone 150 ng/dL and prolactin 42 μg/L. The next step is:`,
    q2: ``,
    q3: [],
    option: [
      `<!--a. -->repeat prolactin.`,
      `<!--b. -->bromocriptine, 2.5 mg orally per day.`,
      `<!--c. -->cabergoline, 0.25 mg orally twice a week.`,
      `<!--d. -->clomiphene citrate, 50 mg orally every other day.`,
      `<!--e. -->cranial magnetic resonance imaging.`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [0],
    ansText: `Rationale: Prolactin is a labile assay. Before continuing with further diagnostic assessment or therapy, moderately elevated assay results should first be confirmed with a second test.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `<!--35. -->Laboratory values associated with androgen receptor insensitivity include:`,
    q2: ``,
    q3: [],
    option: [
      `<!--a. -->significantly elevated testosterone, LH, and FSH.`,
      `<!--b. -->mildly elevated testosterone, LH, and FSH.`,
      `<!--c. -->significantly elevated testosterone, mildly elevated LH, and normal FSH.`,
      `<!--d. -->decreased testosterone, and elevated LH and FSH.`,
      `<!--e. -->decreased testosterone, LH, and FSH.`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [2],
    ansText: `Rationale: Male infertility associated with androgen receptor insensitivity is characterized by increased testosterone, increased estradiol, increased LH to variable degrees, and typical FSH levels (Sokol, 2009).`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `<!--36. -->The most common mutation in the cystic fibrosis transmembrane conductance region, or CFTR, is:`,
    q2: ``,
    q3: [],
    option: [`R117H.`, `R334W.`, `R347P.`, `ΔF508.`, `G542X.`],
    optionStyleType: `st-lower-alpha`,
    answer: [3],
    ansText: `Rationale: The most common CFTR mutation is ΔF508, which is severe (Hampton and Stanton, 2010).`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `<!--37. -->A man presents with a palpable right-sided varicocele of 3 months onset and no varicocele palpable on the left side. Testis longitudinal axis is 5 cm bilaterally, and a semen analysis reveals volume 2.0 mL, density 33 million/mL, and motility 38%. The next step is:`,
    q2: ``,
    q3: [],
    option: [
      `<!--a. -->semen analysis with strict morphology.`,
      `<!--b. -->renal ultrasound.`,
      `<!--c. -->CFTR testing.`,
      `<!--d. -->right varicocelectomy.`,
      `<!--e. -->bilateral varicocelectomy.`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [1],
    ansText: `Rationale: Solitary right varicoceles are rare. Should one be of abrupt onset, renal pathology such as tumor should be considered (Masson and Brannigan, 2014).`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `<!--38. -->Electroejaculation is planned for a man with anejaculation due to spinal cord injury at T5. Treatment should include monitoring and therapy before the procedure with oral:`,
    q2: ``,
    q3: [],
    option: [
      `lisinopril.`,
      `nifedipine.`,
      `pseudoephedrine.`,
      `captopril.`,
      `ciprofloxacin.`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [1],
    ansText: `Rationale: Ejaculatory stimulation for men with spinal cord injuries at a level of T6 or above may result in autonomic dysreflexia, which can be addressed before stimulation by treatment with nifedipine and during the procedure with monitoring of cardiac activity and blood pressure (Brackett et al., 2009; Phillips et al., 2014).`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `<!--39. -->A couple desires children. Semen analysis reveals volume 2.2 mL, density 58 million/mL, and motility 18%, and all sperm have enlarged heads with multiple tails. The next step is:`,
    q2: ``,
    q3: [],
    option: [
      `<!--a. -->testis biopsy.`,
      `<!--b. -->scrotal ultrasound.`,
      `<!--c. -->repeat semen analysis.`,
      `<!--d. -->IUI with donor sperm.`,
      `<!--e. -->in vitro fertilization with intracytoplasmic sperm injection.`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [3],
    ansText: `Rationale: Because of the high rate of aneuploidy in sperm associated with macrocephaly and multiple tails, intracytoplasmic sperm injection with biological gametes is not recommended (Machev et al., 2005; Perrin et al., 2012; Sun et al., 2006).`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
];
