var quiz = [
    

    {
        q: `<!--1. -->Embryologically, the vas deferens and body of the epididymis are derived from what developmental structure?`,
        q2: ``,
        q3: [],
        option: [`<!--a. -->Müllerian ducts`, 
        `<!--b. -->Wolffian ducts`, 
        `<!--c. -->Urogenital ridge`, 
        `<!--d. -->Gubernaculum testis`, 
        `<!--e. -->Metanephros`],
        optionStyleType: `st-lower-alpha`,
        answer: [1],
        ansText:`Rationale:  The müllerian ducts regress in the male. The indifferent gonad migrates to the urogenital ridge to become the testicle. The gubernaculum testis is responsible for pulling the testis into the scrotum during development.`, 
        state: `notAnswered`,
        userAnswered: []
    ,
	type: `MCSS`        ,
        type: `MCSS`},
    {
        q: `<!--2. -->The proportion of testicular volume comprised of seminiferous tubules in the human testis is:`,
        q2: ``,
        q3: [],
        option: [`5%`, 
        `10% to 20%`, 
        `50% to 60%`, 
        `70% to 80%`, 
        `90% to 95%`],
        optionStyleType: `st-lower-alpha`,
        answer: [3],
        ansText:`Rationale: In humans, interstitial tissue takes up 20% to 30% of the total testicular volume.`, 
        state: `notAnswered`,
        userAnswered: []
    ,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`        ,
        type: `MCSS`},
    {
        q: `<!--3. -->Which hormones play a central role in regulation of Sertoli cell function?`,
        q2: ``,
        q3: [],
        option: [`<!--a. -->LH, follicle-stimulating hormone (FSH)`, 
        `<!--b. -->FSH, estradiol`, 
        `<!--c. -->Prolactin, LH`, 
        `<!--d. -->FSH, testosterone`, 
        `<!--e. -->Androgen-binding protein (ABP), testosterone`],
        optionStyleType: `st-lower-alpha`,
        answer: [3],
        ansText:`Rationale: FSH and testosterone play the most important role in the regulation of Sertoli cell function. The effect of prolactin and estradiol on Sertoli cells is not well defined. ABP is made by Sertoli cells.`, 
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `<!--4. -->The vast majority of the fluid in the male ejaculate is derived from the:`,
        q2: ``,
        q3: [],
        option: [`epididymides`, 
        `<!--b. -->ejaculatory ducts`, 
        `<!--c. -->seminal vesicles`, 
        `testicles`, 
        `<!--e. -->vas deferens`],
        optionStyleType: `st-lower-alpha`,
        answer: [2],
        ansText:`Rationale: At least 65% to 70% of ejaculate volume is derived from the seminal vesicles, with the remainder from the vas deferens (with sperm) and prostatic secretions. Periurethral glands may also contribute a small amount of fluid to the normal ejaculate.`, 
        state: `notAnswered`,
        userAnswered: []
    ,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`        ,
        type: `MCSS`},
    {
        q: `<!--5. -->Testicular blood supply is derived from all of the following sources EXCEPT:`,
        q2: ``,
        q3: [],
        option: [`<!--a. -->Internal spermatic artery`, 
        `<!--b. -->Deferential artery`, 
        `<!--c. -->External spermatic artery`, 
        `<!--d. -->Cremasteric artery`, 
        `<!--e. -->Pudendal artery`],
        optionStyleType: `st-lower-alpha`,
        answer: [4],
        ansText:`Rationale: The arterial supply to the human testis and epididymis is derived from three sources: the internal spermatic artery, the deferential artery, and the external spermatic or cremasteric artery.`, 
        state: `notAnswered`,
        userAnswered: []
    ,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`        ,
        type: `MCSS`},
    {
        q: `<!--6. -->A 25-year old bodybuilder eschews the merits of “natural” bodybuilding and uses injectable anabolic steroids regularly to achieve muscle bulk. While on anabolic steroids, his fertility potential would be expected to be:`,
        q2: ``,
        q3: [],
        option: [`<!--a. -->normal, because exogenous testosterone does not impair production of endogenous testosterone.`, 
        `<!--b. -->low, because exogenous testosterone stimulates pituitary production of FSH and LH`, 
        `<!--c. -->low, because exogenous testosterone inhibits pituitary production of FSH and LH`, 
        `<!--d. -->low, because exogenous testosterone is not as potent as endogenous testosterone at nurturing spermatogenesis.`, 
        `<!--e. -->normal, because intratesticular testosterone concentrations are 50 times higher than serum levels, whether or not the blood contains exogenous testosterone.`],
        optionStyleType: `st-lower-alpha`,
        answer: [2],
        ansText:`Rationale: Because of negative feedback inhibition that maintains homeostatic balance in the pituitary-gonadal axis, exogenous testosterone of any type will cause anterior pituitary production of LH and FSH to fall. This results in azoospermia in most of men on anabolic steroids, but the effect will vary based on the dose, frequency, and duration of the steroid regimen`, 
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `<!--7. -->Structural elements of the blood-testis barrier are observed in:`,
        q2: ``,
        q3: [],
        option: [`<!--a. -->Sertoli-Sertoli cell junctions`, 
        `<!--b. -->Leydig cells`, 
        `<!--c. -->basement membranes`, 
        `<!--d. -->desmosomes between spermatocytes`, 
        `<!--e. -->spermatids`],
        optionStyleType: `st-lower-alpha`,
        answer: [0],
        ansText:`Rationale: Sertoli-Sertoli tight junctions prevent the deep penetration of electron-opaque tracers into the seminiferous epithelium from the testicular interstitium. These junctions between Sertoli cells also segregate premeiotic germ cells (spermatogonia) from meiotic and postmeiotic germ cells and are the structural basis for the “blood-testis” barrier.`, 
        state: `notAnswered`,
        userAnswered: []
    ,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`        ,
        type: `MCSS`},
    {
        q: `<!--8. -->How do elevated levels of prolactin influence testosterone production?`,
        q2: ``,
        q3: [],
        option: [`<!--a. -->Inhibit gonadotropin-releasing hormone (GnRH) and LH`, 
        `<!--b. -->Indirectly inhibit Sertoli cells`, 
        `<!--c. -->Directly inhibit Leydig cells`, 
        `<!--d. -->Upregulate inhibin`, 
        `<!--e. -->Downregulate activin`],
        optionStyleType: `st-lower-alpha`,
        answer: [0],
        ansText:`Rationale: States of hyperprolactinemia act to inhibits GnRH pulses and also LH pulses, which is turn results in lower testosterone production.`, 
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `<!--9. -->What is the normal developmental pattern of spermatogenic cells within the seminiferous tubule?`,
        q2: ``,
        q3: [],
        option: [`<!--a. -->Sertoli, spermatogonia, spermatocyte`, 
        `<!--b. -->Spermatocyte, spermatogonia, spermatid`, 
        `<!--c. -->Spermatid, Sertoli, spermatocyte`, 
        `<!--d. -->Spermatogonia, spermatid, spermatocyte`, 
        `<!--e. -->Spermatogonia, spermatocyte, spermatid`],
        optionStyleType: `st-lower-alpha`,
        answer: [4],
        ansText:`Rationale: Proceeding from the least to the most differentiated, they are named dark type A spermatogonia (Ad); pale type A spermatogonia (Ap); type B spermatogonia (B); preleptotene primary spermatocytes (R); leptotene primary spermatocytes (L); zygotene primary spermatocytes (z); pachytene primary spermatocytes (p); secondary spermatocytes (II); and Sa, Sb1, Sb2, Sc, Sd1, and Sd2 spermatids.`, 
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `<!--10. -->What testicular hormone is the major feedback inhibitor of LH secretion?`,
        q2: ``,
        q3: [],
        option: [`Testosterone`, 
        `Inhibin`, 
        `Activin`, 
        `Prolactin`, 
        `Sertolin`],
        optionStyleType: `st-lower-alpha`,
        answer: [0],
        ansText:`Rationale: Inhibin and activin feedback on FSH secretion. Prolactin in excess can downregulate LH secretion.`, 
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `<!--11. -->What is the normal size for adult human testes?`,
        q2: ``,
        q3: [],
        option: [`5 mL`, 
        `10 mL`, 
        `20 mL`, 
        `30 mL`, 
        `40 mL`],
        optionStyleType: `st-lower-alpha`,
        answer: [2],
        ansText:`Rationale: Although ethnic and racial variations exist, 18 to 22 mL is considered normal testis volume for adult human males.`, 
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `<!--12. -->Major components of the epididymis include:`,
        q2: ``,
        q3: [],
        option: [`<!--a. -->caput, corpus, cauda`, 
        `<!--b. -->globus minor, ductus deferens, cauda`, 
        `<!--c. -->rete testis, efferent ductules, caput`, 
        `<!--d. -->efferent ductules, caput, cauda`, 
        `<!--e. -->septa, efferent ductules, corpus`],
        optionStyleType: `st-lower-alpha`,
        answer: [0],
        ansText:`Rationale: Anatomically, the epididymis is divided into three regions: the caput or head, the corpus or body, and the cauda or tail of the epididymis. On the basis of histologic criteria, each region can be subdivided into distinct zones separated by transition segments.`, 
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `<!--13. -->Which of the following is characteristic of meiosis?`,
        q2: ``,
        q3: [],
        option: [`<!--a. -->Cellular DNA content doubles during the first (meiotic) cell division.`, 
        `<!--b. -->Chromosome number is maintained`, 
        `<!--c. -->Homologous chromosomes (non-sister) pair during the second cell division`, 
        `<!--d. -->Crossing over is present`, 
        `<!--e. -->Centromeres do not divide`],
        optionStyleType: `st-lower-alpha`,
        answer: [3],
        ansText:`Rationale: Crossing over of sister chromatids and exchange of genetic material is the hallmark of chromosomal recombination during meiosis. This does not occur in mitosis. Two other unique characteristics of meiosis are that homologous chromosomes pair during meiosis I, the first cell division, and chromosome numbers in daughter cells are half (haploid) that of mitotic cells.`, 
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `<!--14. -->When does a testosterone peak occur during a human male’s life?`,
        q2: ``,
        q3: [],
        option: [`<!--a. -->2 months`, 
        `<!--b. -->6 to 9 months`, 
        `<!--c. -->30 to 40 years`, 
        `<!--d. -->50 to 60 years`, 
        `<!--e. -->&gt;70 years`],
        optionStyleType: `st-lower-alpha`,
        answer: [0],
        ansText:`Rationale: A testosterone peak occurs at approximately 2 months of age. Another peak occurs earlier, during the first trimester of gestation and a third peak occurs later at puberty.`, 
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `<!--15. -->With chronic vasal obstruction, the highest sperm motility is found in what region of the epididymis?`,
        q2: ``,
        q3: [],
        option: [`<!--a. -->Rete testis`, 
        `<!--b. -->Efferent ducts`, 
        `<!--c. -->Proximal epididymis`, 
        `<!--d. -->Mid epididymis`, 
        `<!--e. -->Distal epididymis`],
        optionStyleType: `st-lower-alpha`,
        answer: [2],
        ansText:`Rationale: Studies in men with congenital absence of the vas deferens or epididymal obstruction from vasectomy frequently report poor motility in sperm aspirated from the distal epididymis, with optimal sperm quality and motility in the proximal epididymis.`, 
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `<!--16. -->Which of the following occurs during spermiogenesis?`,
        q2: ``,
        q3: [],
        option: [`<!--a. -->Type B spermatogonia divide to form primary spermatocytes`, 
        `<!--b. -->Cellular remodeling within the basal compartment of the seminiferous tubule`, 
        `<!--c. -->DNA replication`, 
        `<!--d. -->Nuclear compaction`, 
        `<!--e. -->Cytokinesis`],
        optionStyleType: `st-lower-alpha`,
        answer: [3],
        ansText:`Rationale: In spermiogenesis, cell division or cytokinesis does not occur. In addition, spermiogenesis occurs in the adluminal compartment and not the basal compartment. Spermatids and not spermatogonia are the cell types undergoing the metamorphosis characteristic of spermiogenesis.`, 
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `<!--17. -->Changes to sperm during epididymal transit include:`,
        q2: ``,
        q3: [],
        option: [`<!--a. -->increased positive charge.`, 
        `<!--b. -->sulfhydryl reduction.`, 
        `<!--c. -->decreased phospholipid content.`, 
        `<!--d. -->reduced membrane rigidity.`, 
        `<!--e. -->increased capacity for glycolysis.`],
        optionStyleType: `st-lower-alpha`,
        answer: [4],
        ansText:`Rationale: Sperm undergo numerous metabolic changes during epididymal transit. Animal studies describe the acquisition of an increased capacity for glycolysis, changes in intracellular pH and calcium content, modification of adenylate cyclase activity, and alterations in cellular phospholipid and phospholipid-like fatty acid content.`, 
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `<!--18. -->Which of the following germ cell types is considered a true stem cell?`,
        q2: ``,
        q3: [],
        option: [`<!--a. -->Elongating spermatids`, 
        `<!--b. -->Primary spermatocytes`, 
        `<!--c. -->Round spermatids`, 
        `<!--d. -->Secondary spermatocytes`, 
        `<!--e. -->Type A spermatogonia`],
        optionStyleType: `st-lower-alpha`,
        answer: [4],
        ansText:`Rationale: Type A spermatogonia are the only true stem cell in the testis as they can either self renew or differentiate down the spermatogenic pathway.`, 
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `<!--19. -->During their development within the male reproductive tract prior to ejaculation, sperm spend the majority of time in which organ:`,
        q2: ``,
        q3: [],
        option: [`<!--a. -->epididymis`, 
        `<!--b. -->ejaculatory ducts`, 
        `<!--c. -->seminal vesicle`, 
        `<!--d. -->testicle`, 
        `<!--e. -->vas deferens`],
        optionStyleType: `st-lower-alpha`,
        answer: [3],
        ansText:`Rationale: Sperm spend 45 to 60 days developing in the testis and 2 to 12 days in the epididymis. Depending on ejaculation frequency, they can also be stored in the cauda epididymis from for days to several weeks.`, 
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `<!--20. -->The sperm region containing mitochondria is the:`,
        q2: ``,
        q3: [],
        option: [`tail.`, 
        `head.`, 
        `acrosome.`, 
        `midpiece.`, 
        `axoneme.`],
        optionStyleType: `st-lower-alpha`,
        answer: [3],
        ansText:`Rationale: The middle piece of the sperm is a highly organized segment consisting of helically arranged mitochondria surrounding a set of outer dense fibers and the characteristic 9 + 2 microtubular structure of the axoneme.`, 
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `<!--21. -->Which of the following statements about testosterone is most accurate?`,
        q2: ``,
        q3: [],
        option: [`<!--a. -->It is produced by the exocrine testis`, 
        `<!--b. -->It exists mainly in the unbound or “free” form in the circulation`, 
        `<!--c. -->It is regulated by FSH`, 
        `<!--d. -->Its production is increased by excess prolactin`, 
        `<!--e. -->Its metabolite is dihydrotestosterone (DHT)`],
        optionStyleType: `st-lower-alpha`,
        answer: [4],
        ansText:`Rationale: Testosterone is converted to DHT in target tissue by 5α-reductase. Testosterone is produced by the endocrine testis, exists mainly in bound forms in plasma, and is mainly regulated by LH, not FSH. Excess prolactin decreases testosterone production.`, 
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `<!--22. -->Spermiogenesis includes all of the following processes EXCEPT:`,
        q2: ``,
        q3: [],
        option: [`<!--a. -->loss of cytoplasm`, 
        `<!--b. -->formation of the acrosome`, 
        `<!--c. -->flagellar formation`, 
        `<!--d. -->migration of cytoplasmic organelles`, 
        `<!--e. -->cell division`],
        optionStyleType: `st-lower-alpha`,
        answer: [4],
        ansText:`Rationale: During spermiogenesis, the products of meiosis, the round Sa spermatids, metamorphose into mature spermatids. During this process, extensive changes occur in both the spermatid cytoplasm and the nucleus, but cell division is not required. These changes include loss of cytoplasm, formation of the acrosome, formation of the flagellum, and migration of cytoplasmic organelles to positions characteristic of the mature sperm.`, 
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `<!--23. -->After ejaculation the contents of the vas deferens are:`,
        q2: ``,
        q3: [],
        option: [`<!--a. -->returned to the seminal vesicles`, 
        `<!--b. -->maintained in the ampulla`, 
        `<!--c. -->released into the ejaculatory ducts`, 
        `<!--d. -->propelled back into the epididymis`, 
        `<!--e. -->released into the bladder`],
        optionStyleType: `st-lower-alpha`,
        answer: [3],
        ansText:`Rationale: Studies have shown that after sexual stimulation or ejaculation, the contents of the vas deferens are propelled back toward the cauda epididymis, because the distal portion of the vas deferens contracts with greater amplitude, frequency, and duration than does the proximal portion.`, 
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`}
];
