var quiz = [
  {
    q: `<!--1. -->Which of the following venous structures are intentionally preserved during varicocelectomy?`,
    q2: ``,
    q3: [],
    option: [
      `<!--a. -->External spermatic veins`,
      `<!--b. -->Internal spermatic veins`,
      `<!--c. -->Gubernacular veins`,
      `<!--d. -->Deferential (vasal) veins`,
      `<!--e. -->Cremasteric veins`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [3],
    ansText: `Rationale: <b>All veins within the cord, with the exception of the vasal veins, are doubly ligated.</b> Scrotal or gubernacular collateral veins have been demonstrated radiographically to be the cause of 10% of recurrent varicoceles. All external spermatic veins are identified and doubly ligated with hemoclips and divided. The gubernaculum is inspected for the presence of veins exiting from the tunica vaginalis. These are either cauterized or doubly ligated.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `<!--2. -->In the evaluation for vasectomy reversal, which clinical finding is suggestive of epididymal obstruction?`,
    q2: ``,
    q3: [],
    option: [
      `<!--a. -->Varicocele`,
      `Hydrocele`,
      `<!--c. -->Sperm granuloma`,
      `<!--d. -->Normal serum follicle-stimulating hormone (FSH) level`,
      `<!--e. -->Vasal gap larger than 2 cm`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [1],
    ansText: `Rationale: <b>The presence of a hydrocele in the presence of excurrent ductal system obstruction is often associated with secondary epididymal obstruction.</b> Surgeons attempting reconstruction should be aware of the possibility of the need for a vasoepididymostomy.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `<!--3. -->Which of the following is NOT an indication for crossed vasovasostomy?`,
    q2: ``,
    q3: [],
    option: [
      `<!--a. -->Right: inguinal vas obstruction and normal testis; left: patent vas and atrophic testis`,
      `<!--b. -->Right: epididymal obstruction, patent vas, and normal testis; left: ejaculatory duct obstruction and normal testis`,
      `<!--c. -->Right: inguinal vas obstruction and normal testis; left: epididymal obstruction, patent vas, and normal testis`,
      `<!--d. -->Right: epididymal obstruction and patent right vas above vasectomy site; left: sperm in testicular end of vas and vasectomy site in convoluted vas`,
      `<!--e. -->Right: congenital absence of epididymis and normal patent vas; left: normal testis and partial absence of vas ending retroperitoneally`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [3],
    ansText: `Rationale:  Crossover is indicated in the following circumstances: (1) unilateral inguinal obstruction of the vas deferens associated with an atrophic testis on the contralateral side. A crossover vasovasostomy should be performed to connect a healthy testicle to the contralateral unobstructed vas. (2) Obstruction or aplasia of the inguinal vas or ejaculatory duct on one side and epididymal obstruction on the contralateral side. It is preferable to perform one anastomosis with a high probability of success (vasovasostomy) than two operations with a much lower chance of success such as unilateral vasoepididymostomy and contralateral transurethral resection of the ejaculatory ducts.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `<!--4. -->Compared with the other surgical options for varicocelectomy, the advantages of performing a subinguinal microsurgical varicocelectomy include all of the following EXCEPT:`,
    q2: ``,
    q3: [],
    option: [
      `<!--a. -->lower rate of arterial injury.`,
      `<!--b. -->lower rate of postoperative hydrocele.`,
      `<!--c. -->lower rate of varicocele recurrence.`,
      `<!--d. -->fewer veins ligated.`,
      `<!--e. -->lower overall complication rate.`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [3],
    ansText: `Rationale: At the subinguinal level, significantly more veins are encountered, the artery is more often surrounded by a network of tiny veins that must be ligated, and the testicular artery has often divided into two or three branches, making arterial identification and preservation more difficult without using a microscope for the procedure.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `<!--5. -->Which maneuvers should be avoided when bridging a large vasal gap during vasovasostomy?`,
    q2: ``,
    q3: [],
    option: [
      `<!--a. -->Mobilization of the vas deferens toward the external inguinal ring`,
      `<!--b. -->Dissection of the sheath of the convoluted vas deferens off the epididymis and allowing the testis to drop upside-down`,
      `<!--c. -->Separation of the cauda and corpus epididymis from the testis`,
      `<!--d. -->Mobilization of the vas deferens toward the internal inguinal ring`,
      `<!--e. -->Unraveling of the convoluted vas deferens`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [4],
    ansText: `Rationale: When large vasal gaps are present, a gauze-wrapped index finger is used to bluntly separate the cord structures from the vas. Blunt finger dissection through the external ring will free the vas to the internal ring if additional abdominal side length is necessary. These maneuvers will leave all the vasal vessels intact. When the vasal gap is extremely large, additional length can be achieved by dissecting the entire convoluted vas free of its attachments to the epididymal tunica, allowing the testis to drop upside-down. If the amount of the vas removed is so large that even these measures fail to allow a tension-free anastomosis, the incision can be extended to the internal inguinal ring, the floor of the inguinal canal cut, and the vas rerouted under the floor, as in a difficult orchiopexy. An additional 4 to 6 cm of length can be obtained by dissecting the epididymis off of the testis from the vasoepididymal junction to the caput epididymis. The superior epididymal vessels are left intact and provide adequate blood supply to the testicular end of the vas. With this combination of maneuvers, gaps up to 10 cm wide can be bridged. The convoluted vas should not be unraveled. This disturbs the blood supply at the anastomotic line.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `<!--6. -->In which of the following scenarios is a testis biopsy least helpful?`,
    q2: ``,
    q3: [],
    option: [
      `<!--a. -->Failure to retrieve motile sperm from the epididymis`,
      `<!--b. -->Sperm retrieval for nonobstructive azoospermia`,
      `<!--c. -->Diagnostic evaluation of men with congenital absence of vas and normal FSH levels`,
      `<!--d. -->Diagnostic evaluation in azoospermic men with normal findings on scrotal examination and normal serum testosterone and FSH levels`,
      `<!--e. -->Sperm retrieval for men diagnosed with Sertoli cell–only pattern in the testes`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [2],
    ansText: `Rationale: <b>Testis biopsy is indicated in azoospermic men with testes of normal size and consistency, palpable vasa deferentia, normal serum FSH levels, and a negative serum antisperm antibody assay.</b> Under these circumstances, biopsy will distinguish obstructive azoospermia from primary seminiferous tubular failure. In the testes of men with congenital absence of vasa, biopsy always reveals normal or at least some spermatogenesis, and biopsy is not necessary before definitive sperm aspiration and in vitro fertilization (IVF) with ICSI.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `<!--7. -->Which of the following scenarios has the lowest rate for sperm return to ejaculate after vasectomy reversal?`,
    q2: ``,
    q3: [],
    option: [
      `<!--a. -->Motile sperm in the vas and vasovasostomy`,
      `<!--b. -->Non-motile sperm in the vas and vasovasostomy`,
      `<!--c. -->Motile sperm in the vas and unilateral crossed vasovasostomy`,
      `<!--d. -->Thick, white vasal fluid devoid of sperm and vasovasostomy`,
      `<!--e. -->Copious clear vasal fluid but no sperm and vasovasostomy`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [2],
    ansText: `Rationale: If the fluid expressed from the vas is found to be thick, white, water insoluble, and like toothpaste in quality, microscopic examination rarely reveals sperm. Under these circumstances, the tunica vaginalis is opened and the epididymis inspected. If clear evidence of obstruction is found (e.g., an epididymal sperm granuloma with dilated tubules above and collapsed tubules below), vasoepididymostomy is performed. When the surgeon is in doubt or is not experienced with vasoepididymostomy, vasovasostomy should be performed. <b>However, only 15% of men with bilateral absence of sperm in the vasal fluid after barbotage and intensive search will have sperm return to the ejaculate after vasovasostomy.</b>`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `<!--8. -->In the evaluation for azoospermia, all of the following tests should be considered to confirm a diagnosis of obstructive azoospermia EXCEPT:`,
    q2: ``,
    q3: [],
    option: [
      `<!--a. -->transrectal ultrasonography.`,
      `<!--b. -->testicular biopsy.`,
      `<!--c. -->serum antisperm antibody assay.`,
      `<!--d. -->epididymal biopsy.`,
      `<!--e. -->serum testosterone and FSH assay.`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [2],
    ansText: `Rationale: Before surgical reconstruction of the reproductive tract is attempted, spermatogenesis in the patient should be evident. A testicular biopsy may be indicated to confirm the presence of spermatogenesis. Men with a low semen volume should have a transrectal ultrasonographic scan to alert one to the possibility of an additional ejaculatory duct obstruction. For serum and antisperm antibody studies, the presence of serum antisperm antibodies corroborates the diagnosis of obstruction and the presence of active spermatogenesis. At present, this test is of unknown prognostic value and is optional. For serum FSH assay, men with small, soft testes should have serum FSH measured. An elevated FSH level suggests impaired spermatogenesis and potentially a poorer prognosis.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `<!--9. -->Which of the following is TRUE regarding varicocele?`,
    q2: ``,
    q3: [],
    option: [
      `<!--a. -->Treatment in infertile men rarely results in improved semen parameters.`,
      `<!--b. -->Severity of testicular insult is related to the size of the varicoceles.`,
      `<!--c. -->Severity of testicular insult from varicocele is duration independent.`,
      `<!--d. -->Because of the severity of testicular insult, repair of large varicoceles is not warranted.`,
      `<!--e. -->Surgical treatment of subclinical varicoceles results in greater improvement in semen quality than treatment of large varicoceles.`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [1],
    ansText: `Rationale: <b>Larger varicoceles appear to cause more damage than small varicoceles; large varicoceles are associated with greater preoperative impairment in semen quality than are small varicoceles.</b>`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `<!--10. -->After a bilateral vasoepididymostomy, a patient remained azoospermic in two semen analyses until 6 months postoperative, when the analysis revealed 8 million sperm/mL with 60% motility. What is the next management step?`,
    q2: ``,
    q3: [],
    option: [
      `<!--a. -->A plan for intrauterine insemination with ejaculated sperm`,
      `<!--b. -->A plan for assisted reproduction with intracytoplasmic sperm injection (ICSI) and ejaculated sperm`,
      `<!--c. -->Cryopreservation of semen`,
      `<!--d. -->No follow-up necessary`,
      `<!--e. -->Scrotal ultrasound`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [2],
    ansText: `Rationale: With the older end-to-end or end-to-side vasoepididymostomy method, at 14 months after surgery 25% of initially patent anastomoses have shut down. For this reason, we recommend banking sperm both intraoperatively and as soon as sperm appear in the ejaculate postoperatively.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `<!--11. -->Which of the following is a disadvantage of the intussusception vasoepididymostomy?`,
    q2: ``,
    q3: [],
    option: [
      `<!--a. -->Inability to assess epididymal fluid for sperm before setting up for anastomosis`,
      `<!--b. -->Lower patency rate than end-to-side techniques`,
      `<!--c. -->Difficult hemostasis`,
      `<!--d. -->Placement of sutures into a collapsed epididymal tubule`,
      `<!--e. -->Transection of the epididymis required before anastomosis`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [0],
    ansText: `Rationale: This method, also known as the <b><i>triangulation technique,</i></b> was introduced by Berger. There are several advantages of this method versus previous techniques. Two or three sutures placed in the epididymal tubule provide four and six points of fixation, and the anastomosis is virtually bloodless. However, one cannot assess tubular fluid for sperm before the anastomosis setup.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `<!--12. -->All of the following situations are appropriate for assisted reproduction with ICSI as a first line of treatment EXCEPT:`,
    q2: ``,
    q3: [],
    option: [
      `<!--a. -->obstruction with multiple failures of reconstruction.`,
      `<!--b. -->mild oligoasthenospermia with varicoceles and a female partner of 29 years of age.`,
      `<!--c. -->Klinefelter syndrome.`,
      `<!--d. -->only a few viable sperm found in the ejaculate.`,
      `<!--e. -->post-chemotherapy azoospermia.`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [1],
    ansText: `Rationale: Assisted reproduction can be offered to men with surgically unreconstructable obstruction such as congenital absence of the vas deferens; men with few viable sperm in the ejaculate; azoospermic men with varicoceles (half of these men will respond to varicocelectomy with return of enough sperm to ejaculate to achieve pregnancy using IVF with ICSI); and men with nonobstructive azoospermia.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `<!--13. -->In which of the following settings are vasovasostomy and vasoepididymostomy contraindicated?`,
    q2: ``,
    q3: [],
    option: [
      `<!--a. -->Previous vasectomy more than 20 years ago`,
      `<!--b. -->Concomitant scrotal pain`,
      `<!--c. -->Concomitant hydrocele`,
      `<!--d. -->Concomitant varicoceles`,
      `<!--e. -->Nonobstructive azoospermia`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [4],
    ansText: `Rationale: Before surgical reconstruction of the reproductive tract is attempted, spermatogenesis in the patient should be evident. A prior history of natural fertility pre-vasectomy is usually adequate. In other cases, a testicular biopsy may be indicated to confirm the presence of spermatogenesis.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `<!--14. -->In the presence of epididymal obstruction, which of the following statements is FALSE?`,
    q2: ``,
    q3: [],
    option: [
      `<!--a. -->The quality of sperm is better in caput than caudal tubules.`,
      `<!--b. -->Vasoepididymostomy to the caudal tubules has a better patency rate than to the caput tubules.`,
      `<!--c. -->Vasovasostomy can yield a satisfactory patency rate.`,
      `<!--d. -->A scrotal sonogram may demonstrate epididymal fullness and hydrocele.`,
      `<!--e. -->Intraoperative sperm cryopreservation is possible.`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [2],
    ansText: `Rationale: If clear evidence of obstruction is found, vasoepididymostomy is performed. When there is doubt or the physician is not experienced with vasoepididymostomy, vasovasostomy should be performed. However, only 15% of men with bilateral absence of sperm in the vasal fluid after barbotage and an intensive search will have sperm return to the ejaculate after vasovasostomy.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `<!--15. -->Which of the following statements is FALSE regarding microsurgical testicular sperm extraction (TESE)?`,
    q2: ``,
    q3: [],
    option: [
      `<!--a. -->Sertoli cell–only pattern is a contraindication for the procedure.`,
      `<!--b. -->Large seminiferous tubules typically give a higher sperm yield.`,
      `<!--c. -->It is best performed percutaneously.`,
      `<!--d. -->It can better preserve the blood supply to testis parenchyma than a non-microsurgical approach`,
      `<!--e. -->It should be used in men with nonobstructive azoospermia.`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [2],
    ansText: `Rationale: The use of an operating microscope for standard open diagnostic testes biopsy allows identification of an area in the tunica albuginea free of blood vessels, minimizing the risk of injury to the testicular blood supply and allowing a relatively blood-free biopsy specimen.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `<!--16. -->All of the following are expected outcomes of varicocele repair EXCEPT:`,
    q2: ``,
    q3: [],
    option: [
      `<!--a. -->improved sperm motility.`,
      `<!--b. -->increased risk of multiple gestation.`,
      `<!--c. -->improved sperm counts.`,
      `<!--d. -->improved serum testosterone levels.`,
      `<!--e. -->return of sperm to the ejaculate in 40% to 50% of azoospermic men.`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [1],
    ansText: `Rationale: <b>Varicocelectomy results in significant improvement in the findings of semen analysis in 60% to 80% of men. Reported pregnancy rates after varicocelectomy vary from 20% to 60%.</b> A randomized controlled trial of surgery versus no surgery in infertile men with varicoceles revealed a pregnancy rate of 44% at 1 year in the surgery group versus 10% in the control group. In our series of 1500 microsurgical operations, 43% of couples were pregnant at 1 year and 69% at 2 years when couples with female factors were excluded. Microsurgical varicocelectomy results in return of sperm to the ejaculate in 50% of azoospermic men with palpable varicoceles. Repair of large varicoceles results in a significantly greater improvement in semen quality than repair of small varicoceles. In addition, large varicoceles are associated with greater preoperative impairment in semen quality than are small varicoceles, and consequently overall pregnancy rates are similar regardless of varicocele size. Some evidence suggests that the younger the patient is at the time of varicocele repair, the greater the improvement after repair and the more likely the testis is to recover from varicocele-induced injury. <b>Varicocele recurrence, testicular artery ligation, and postvaricocelectomy hydrocele formation are often associated with poor postoperative results.</b> In infertile men with low serum testosterone levels, microsurgical varicocelectomy alone results in substantial improvement in serum testosterone levels.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `<!--17. -->A 30-year-old man presenting with primary infertility was found to be azoospermic on two semen analyses. For which of the following findings is a diagnostic biopsy indicated?`,
    q2: ``,
    q3: [],
    option: [
      `<!--a. -->Ejaculate volume below 2 mL with negative fructose`,
      `<!--b. -->Semen pH less than 7.2`,
      `<!--c. -->Palpable vasa, normal serum FSH, normal testis volume, and negative antisperm antibodies`,
      `<!--d. -->Serum FSH of 25 IU/L and 12-mL soft testis`,
      `<!--e. -->Absence of vasa deferentia and normal serum FSH level`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [2],
    ansText: `Rationale: <b>Men with a positive antisperm antibody assay are always obstructed, and a biopsy is not necessary.</b> Men with elevated FSH levels and small, soft testes always have nonobstructive azoospermia.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `<!--18. -->In which of the following scenarios is a vasogram indicated at the time of scrotal exploration/possible reconstruction?`,
    q2: ``,
    q3: [],
    option: [
      `<!--a. -->Azoospermia, Sertoli cell only on testis biopsy`,
      `<!--b. -->Azoospermia, testicular volume of 10 mL, FSH value 25 IU/L`,
      `<!--c. -->Azoospermia, normal testicular volume, biopsy revealing active spermatogenesis`,
      `<!--d. -->Azoospermia, no palpable vasa deferential`,
      `<!--e. -->Sperm count 5 million/mL, 5% motility, grade 2 varicoceles bilaterally`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [2],
    ansText: `Rationale:  The absolute indications for vasography are azoospermia, plus complete spermatogenesis with many mature spermatids on testis biopsy and at least one palpable vas. Relative indications for vasography are severe oligospermia with normal testis biopsy, a high level of sperm-bound antibodies that may be due to obstruction, low semen volume, and poor sperm motility (partial ejaculatory duct obstruction).`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `<!--19. -->All of the following diagnoses can be made from a radiocontrast vasogram EXCEPT:`,
    q2: ``,
    q3: [],
    option: [
      `<!--a. -->inguinal vasal obstruction.`,
      `<!--b. -->ejaculatory duct obstruction.`,
      `<!--c. -->seminal vesicle agenesis.`,
      `<!--d. -->spermatogenic failure.`,
      `<!--e. -->partial agenesis of vasa deferentia.`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [3],
    ansText: `Rationale: Vasography should answer the questions: Are there sperm in the vasal fluid? Is the vas obstructed? If the testis biopsy reveals many sperm, then the absence of sperm in vasal fluid indicates obstruction proximal to the vasal site examined, most likely an epididymal obstruction. Vasography is done in this case with saline or indigo carmine to confirm the patency of the seminal vesicle end of the vas before vasoepididymostomy. Copious vasal fluid containing many sperm indicates vasal or ejaculatory duct obstruction, and formal contrast vasography is performed to document the exact location of the obstruction. Copious thick, white fluid without sperm in a dilated vas indicates secondary epididymal obstruction in addition to potential vasal or ejaculatory duct obstruction.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `<!--20. -->All of the following are potential complications of transurethral resection of the ejaculatory ducts EXCEPT:`,
    q2: ``,
    q3: [],
    option: [
      `<!--a. -->urinary incontinence.`,
      `<!--b. -->retrograde ejaculation.`,
      `<!--c. -->recurrent epididymitis.`,
      `<!--d. -->testicular atrophy.`,
      `<!--e. -->contamination of semen with urine.`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [3],
    ansText: `Rationale: Reflux of urine into the ejaculatory ducts, vas, and seminal vesicles occurs after a majority of resections. This can be documented by voiding cystourethrography or by measuring semen creatinine levels. Reflux can lead to acute and chronic epididymitis. Recurrent epididymitis often results in epididymal obstruction. The incidence of epididymitis after transurethral resection is probably underestimated. Symptomatic chemical epididymitis may occur from refluxing urine. If epididymitis is chronic and recurrent, vasectomy or even epididymectomy may be necessary. Even when care has been taken to spare the bladder neck, retrograde ejaculation is common after transurethral resection. Transurethral instrumentation can increase the risk of urethral stricture.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `<!--21. -->What is the pathogenesis of post-varicocelectomy hydrocele?`,
    q2: ``,
    q3: [],
    option: [
      `<!--a. -->Increased testicular venous pressure`,
      `<!--b. -->Lymphatic obstruction`,
      `<!--c. -->Soft tissue fibrosis`,
      `<!--d. -->Arterial injury`,
      `<!--e. -->Catch-up growth of testes`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [1],
    ansText: `Rationale: Analysis of the protein concentration of hydrocele fluid indicates that hydrocele formation after varicocelectomy is due to lymphatic obstruction.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `<!--22. -->Which of the following is TRUE regarding the ejaculatory duct?`,
    q2: ``,
    q3: [],
    option: [
      `<!--a. -->It is a single midline duct formed by the confluence of the seminal vesicle ducts.`,
      `<!--b. -->It enters into the middle of the verumontanum.`,
      `<!--c. -->It joins with the prostatic ducts.`,
      `<!--d. -->It is a paired duct formed by the confluence of each seminal vesicle duct and vasa deferentia.`,
      `<!--e. -->It enters directly into the vesicle trigone.`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [3],
    ansText: `Rationale: The ejaculatory ducts course between the bladder neck and the verumontanum and exit at the level of and along the lateral aspect of the verumontanum.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `<!--23. -->All of the following are potential complications of vasography EXCEPT:`,
    q2: ``,
    q3: [],
    option: [
      `<!--a. -->vasal obstruction at the site of vasography.`,
      `<!--b. -->perivasal hematoma.`,
      `<!--c. -->sperm granuloma at the site of vasography.`,
      `<!--d. -->injury to the vasal artery.`,
      `<!--e. -->retrograde ejaculation.`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [4],
    ansText: `Rationale: <b>Complications of vasography include stricture, injury to the vasal blood supply, hematoma, and sperm granuloma.</b> Multiple attempts at percutaneous vasography using sharp needles can result in stricture or obstruction at the vasography site. Careless or crude closure of a vasostomy can also result in stricture and obstruction. Non–water-soluble contrast agents may also result in stricture and should not be employed for vasography. If the vasal blood supply is injured at the site of vasography, vasovasostomy proximal to the vasography site may result in ischemia, necrosis, and obstruction of the intervening segment of vas. A bipolar cautery should be used for meticulous hemostasis at the time of vasostomy to prevent hematoma in the perivasal sheath. Leaky closure of a vasography site may lead to the development of a sperm granuloma, which can result in stricture or obstruction of the vas.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `<!--24. -->What is the estimated percentage of men who develop antisperm antibodies after vasectomy?`,
    q2: ``,
    q3: [],
    option: [
      `<!--a. -->0% to 20%`,
      `<!--b. -->20% to 40%`,
      `<!--c. -->40% to 60%`,
      `<!--c. -->60% to 80%`,
      `<!--c. -->80% to 100%`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [3],
    ansText: `Rationale: Systemic effects of vasectomy have been postulated. Vasectomy disrupts the blood-testis barrier, resulting in detectable levels of serum antisperm antibodies in 60% to 80% of men. Some studies suggest that the antibody titers diminish 2 or more years after vasectomy. Others suggest that these antibody titers persist. However, neither circulating immune complexes nor deposits are increased after vasectomy.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `<!--25. -->Intraoperatively during a vasectomy reversal, a sperm granuloma is found on the left side. What does this indicate?`,
    q2: ``,
    q3: [],
    option: [
      `<!--a. -->Concomitant epididymal obstruction that requires a vasoepididymostomy`,
      `<!--b. -->Infection requiring postoperative antibiotics`,
      `<!--c. -->The need for genetic counseling`,
      `<!--d. -->That sperm will be found at the testicular end of the vas`,
      `<!--e. -->That the procedure should be abandoned and the patient should undergo re-exploration in 3 months`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [3],
    ansText: `Rationale: <b>A sperm granuloma at the testicular end of the vas suggests that sperm have been leaking at the vasectomy site. This vents the high pressures away from the epididymis and is associated with a better prognosis for restored fertility regardless of the time interval since vasectomy.</b>`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `<!--26. -->When is the best time to perform vasography?`,
    q2: ``,
    q3: [],
    option: [
      `<!--a. -->At the time of diagnostic testis biopsy`,
      `<!--b. -->At the time of reconstruction, if a prior testis biopsy result was normal`,
      `<!--c. -->At the time of scrotal ultrasonography with color flow Doppler`,
      `<!--d. -->At the time of transrectal ultrasonography revealing normal seminal vesicles`,
      `<!--e. -->At the time of electroejaculation`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [1],
    ansText: `Rationale: There is no need to perform vasography at the time of testis biopsy for azoospermia unless immediate reconstruction is planned and the touch or wet-preparation biopsy reveals mature sperm with tails. If performed carelessly, vasography can cause stricture or even obstruction at the vasography site, which can complicate subsequent reconstruction.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `<!--27. -->Twelve years after vasectomy, a man was found on routine examination to have asymptomatic sperm granulomas bilaterally. All of the following scenarios are true EXCEPT:`,
    q2: ``,
    q3: [],
    option: [
      `<!--a. -->Microrecanalization is possible with the appearance of rare sperm in the ejaculate.`,
      `<!--b. -->If vasectomy reversal is performed, only bilateral vasovasostomy is likely to be necessary.`,
      `<!--c. -->The epididymides are unlikely to be indurated.`,
      `<!--d. -->The epididymides are likely to be obstructed.`,
      `<!--e. -->No treatment is necessary for asymptomatic sperm granuloma.`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [3],
    ansText: `Rationale: Sperm granulomas form when sperm leak from the testicular end of the vas. Sperm are highly antigenic, and an intense inflammatory reaction occurs when sperm escape outside the reproductive epithelium. Sperm granulomas are rarely symptomatic. The presence or absence of a sperm granuloma at the vasectomy site seems to be of importance in modulating the local effects of chronic obstruction on the male reproductive tract. The sperm granuloma’s complex network of epithelialized channels provides an additional absorptive surface that helps vent the high intraluminal pressure in the obstructed excurrent ducts. Numerous animal studies have correlated the presence or absence of sperm granuloma at the vasectomy site with the degree of epididymal and testicular damage. Species that always develop granulomas after vasectomy have minimal damage to the seminiferous tubules. Some studies of men undergoing vasectomy reversal have revealed somewhat higher success rates in men who have a sperm granuloma at the vasectomy site, whereas another large study has not. Although sperm granulomas at the vasectomy site are present microscopically in 10% to 30% of men undergoing reversal, it is likely that, given enough time, virtually all men develop sperm granulomas at the vasectomy site, the epididymis, or the rete testis. When chronic postvasectomy pain is localized to the granuloma, excision and occlusion of the vasa with intraluminal cautery usually relieve the pain and prevent recurrence. Men with postvasectomy congestive epididymitis may be relieved of pain by open-ended vasectomy designed to purposefully produce pressure, relieving sperm granuloma.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `<!--28. -->A midline cyst compressing the ejaculatory duct is found on a transrectal ultrasonographic scan. What does the presence of sperm in the cyst aspirate suggest?`,
    q2: ``,
    q3: [],
    option: [
      `<!--a. -->Congenital absence of vas on at least one side`,
      `<!--b. -->Nonobstructive azoospermia`,
      `<!--c. -->Bilateral epididymal obstruction`,
      `<!--d. -->The possibility of XXY karyotype`,
      `<!--e. -->Patency of a vas deferens and epididymis on at least one side`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [4],
    ansText: `Rationale: The fine-needle aspirate is examined for sperm. If sperm are present, it means at least one vas and epididymis are patent.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `<!--29. -->After transurethral resection of the ejaculatory ducts, the patient develops retrograde ejaculation. What is the next step of management?`,
    q2: ``,
    q3: [],
    option: [
      `<!--a. -->Watchful waiting`,
      `<!--b. -->Intrauterine insemination`,
      `ICSI`,
      `A trial of pseudoephedrine`,
      `Electroejaculation`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [3],
    ansText: `Rationale: Pseudoephedrine (Sudafed), 120 mg orally, 90 minutes before ejaculation, may prevent retrograde ejaculation. If this is not successful, sperm can be retrieved from alkalinized urine and used for either intrauterine insemination or IVF with ICSI.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `<!--30. -->One year after vasovasostomy, a progressive decline in sperm motility and sperm counts is noted. What does this indicate?`,
    q2: ``,
    q3: [],
    option: [
      `<!--a. -->Progressive spermatogenic failure`,
      `Infection`,
      `Arterial injury to the testis and epididymis`,
      `Ejaculatory duct obstruction`,
      `Stricture of the vasovasostomy`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [4],
    ansText: `Rationale:  Late stricture and obstruction are disappointingly common. <b>Progressive loss of sperm motility followed by decreasing counts indicates stricture.</b> A trial of oral prednisone can sometimes prevent progression to azoospermia.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `<!--31. -->In which of the following scenarios would a diagnostic testicular biopsy provide valuable clinical information?`,
    q2: ``,
    q3: [],
    option: [
      `<!--a. -->Men with azoospermia, atrophic testes, and an FSH level of 25 IU/L`,
      `<!--b. -->Men with a 47,XXY karyotype`,
      `<!--c. -->Men with a fecundity history who seek vasectomy reversal`,
      `<!--d. -->Men with primary infertility, azoospermia, normal physical examination findings, a normal serum FSH level, and a negative serum antisperm antibody assay`,
      `<!--e. -->Men with anejaculation caused by high spinal cord injury`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [3],
    ansText: `Rationale: Testis biopsy is indicated in azoospermic men with testis of normal size and consistency, palpable vasa deferentia, and normal serum FSH levels.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `<!--32. -->Which of the following is TRUE regarding retractile testes in adults?`,
    q2: ``,
    q3: [],
    option: [
      `<!--a. -->As in the pediatric population, surgical repair is never indicated.`,
      `<!--b. -->A dartos pouch operation is the treatment of choice.`,
      `<!--c. -->Simple three-stitch orchiopexy of the tunica albuginea to the dartos, as for torsion prophylaxis, is effective in preventing retraction.`,
      `<!--d. -->Bilateral orchiopexy is necessary for unilateral retractile testis.`,
      `<!--e. -->Torsion of the testis is a common complication.`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [1],
    ansText: `Rationale: When scrotal orchiopexy is performed for retractile testis, a dartos pouch operation should be performed. Simple suture orchiopexy of the tunica albuginea of the testis to the dartos, such as is performed sometimes to prevent torsion, will not prevent retraction of these testes into the groin. Creation of a dartos pouch will keep the testis well down into the scrotum and permanently prevent retraction. This is also the most reliable and safest technique for the prevention of testicular torsion. `,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `<!--33. -->Which of the following is TRUE regarding vasoepididymostomy?`,
    q2: ``,
    q3: [],
    option: [
      `<!--a. -->End-to-side anastomosis currently has the highest patency rate.`,
      `<!--b. -->Microsurgical technique does not significantly improve the surgical outcome.`,
      `<!--c. -->Assisted reproduction with ICSI is a more cost-effective option.`,
      `<!--d. -->It should be reserved for azoospermia patients with spermatogenic arrest.`,
      `<!--e. -->It should be performed only on an epididymal tubule containing sperm.`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [4],
    ansText: `Rationale: Specific treatments for male factor infertility such as microsurgical reconstruction for obstructive azoospermia and varicocelectomy for impaired testes remain the safest and most cost-effective ways of managing infertile men. Microsurgical approaches allow accurate approximation of the vasal mucosa to that of a single epididymal tubule, resulting in marked improvement in the patency and pregnancy rates. If the level of obstruction is not clearly delineated, after the buttonhole opening is made in the tunica, a 70-μm diameter tapered needle from the 10 to 0 nylon microsuture is used to puncture the epididymal tubule, beginning as distal as possible, and fluid is sampled from the puncture site. When sperm are found, the puncture sites are sealed with microbipolar forceps, a new buttonhole is made in the epididymal tunica just proximally, and the tubule is prepared as described previously. Patency rates with the intussusception technique can exceed 80%. With the classic end-to-side or older end-to-end method, the patency rate is about 70%, and 43% of men with sperm will impregnate their wives after a minimum follow-up of 2 years.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `<!--34. -->When a vasoepididymostomy is performed for fertility reasons, which of the following should be routinely done in the same setting?`,
    q2: ``,
    q3: [],
    option: [
      `<!--a. -->Intraoperative epididymal sperm aspiration for sperm cryopreservation`,
      `<!--b. -->Testicular biopsy for sperm cryopreservation`,
      `<!--c. -->A touch preparation of testicular tissue`,
      `<!--d. -->A squash preparation of testicular tissue`,
      `<!--e. -->A radiocontrast vasogram`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [0],
    ansText: `Rationale: Once sperm are identified, they are aspirated into glass capillary tubes and flushed into media for cryopreservation.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `<!--35. -->Which of the following is the most important factor in ensuring a high patency rate after a vasovasostomy?`,
    q2: ``,
    q3: [],
    option: [
      `<!--a. -->Age of the patient`,
      `<!--b. -->Time since vasectomy`,
      `<!--c. -->Surgeon’s technique and experience`,
      `<!--d. -->Presence of motile sperm in the vasal fluid`,
      `<!--e. -->Presence of a sperm granuloma at the vasectomy site`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [2],
    ansText: `Rationale: The responsibilities assumed by the surgeon demand the utmost in judgment and skill. Many of the procedures described in this chapter are among the most technically demanding in all of urology. Acquisition of the skills required to perform them demands intensive laboratory training in microsurgery and a thorough knowledge of the anatomy and physiology of the male reproductive system.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `<!--36. -->Which of the following surgical sperm retrieval techniques is inappropriate for the clinical situation indicated?`,
    q2: ``,
    q3: [],
    option: [
      `<!--a. -->Percutaneous epididymal sperm aspiration (PESA) for congenital absence of vas`,
      `<!--b. -->Percutaneous testicular sperm aspiration (PTSA) after failed vasoepididymostomy`,
      `<!--c. -->Electroejaculation in a man with postretroperitoneal lymph node dissection for left testicular embryonal carcinoma`,
      `<!--d. -->Microsurgical epididymal sperm aspiration (MESA) for spermatogenic maturation arrest`,
      `<!--e. -->TESE in a man with azoospermia from chemotherapy`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [3],
    ansText: `Rationale: MESA is indicated for men with normal spermatogenesis and unreconstructable obstruction such as congenital bilateral absence of the vas deferens.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
];
