var quiz = [
    

    {
        q: `<b>Tuberculosis</b><br/><br/>All of the following mycobacteria cause tuberculosis (TB) EXCEPT:`,
        q2: ``,
        q3: [],
        option: [`<i>Mycobacterium bovis.</i>`, 
        `<i>Mycobacterium avium-intracellulare.</i>`, 
        `<i>Mycobacterium africanum.</i>`, 
        `<i>Mycobacterium microti.</i>`, 
        `Bacille Calmette-Guérin (BCG).`],
        optionStyleType: `st-lower-alpha`,
        answer: [1],
        ansText:`Rationale: <!--<b>b. <i>Mycobacterium avium-intracellulare.</i></b>--> <b><i>M. bovis, M. africanum,</i></b> and <b><i>M. microti</i></b> are members of the <b><i>M. tuberculosis</i></b> complex (MTBC) and can cause TB disease. BCG is derived from <b><i>M. bovis</i></b> and can cause TB in certain individuals. Of the mycobacteria listed, <b><i>M. avium-intracellulare</i></b> is one of the many nontuberculous mycobacteria.`, 
        state: `notAnswered`,
        userAnswered: []
    ,
	type: `MCSS`,
	type: `MCSS`        ,
        type: `MCSS`},
    {
        q: `Which of the following statements about the epidemiology of tuberculosis is FALSE?`,
        q2: ``,
        q3: [],
        option: [`TB incidence and mortality have been decreasing worldwide since the year 2000.`, 
        `Tuberculosis incidence is higher in those who are born outside the United States than in those born in the United States.`, 
        `Prevalence of multidrug-resistant (MDR) tuberculosis cases is now approaching 12% in the United States.`, 
        `The lifetime risk of reactivation of TB is 5% to 10% in most people.`, 
        `Worldwide, tuberculosis is the cause of death in 25% of persons who test positive for human immunodeficiency virus (HIV).`],
        optionStyleType: `st-lower-alpha`,
        answer: [2],
        ansText:`Rationale: <!--<b>c. Prevalence of multidrug-resistant (MDR) tuberculosis cases is now approaching 12% in the United States.</b>--> Although MDR TB is concerning because of the difficulty of treatment, in 2012, the proportion of TB cases caused by MDR TB was only 1.2% in the United States.`, 
        state: `notAnswered`,
        userAnswered: []
    ,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`        ,
        type: `MCSS`},
    {
        q: `Which of the following routes of infection is the most common in genitourinary tuberculosis?`,
        q2: ``,
        q3: [],
        option: [`Hematogenous seeding`, 
        `Lymphatic spread`, 
        `Direct inoculation`, 
        `Sexual transmission`, 
        `Ascending or retrograde infection`],
        optionStyleType: `st-lower-alpha`,
        answer: [0],
        ansText:`Rationale: <!--<b>a. Hematogenous seeding.</b>--> Each of the answers is a known route of infection for the development of GU TB. However, hematogenous seeding is by far the most common one.`, 
        state: `notAnswered`,
        userAnswered: []
    ,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`        ,
        type: `MCSS`},
    {
        q: `Which of the following is a not a late complication of genitourinary tuberculosis?`,
        q2: ``,
        q3: [],
        option: [`Infertility`, 
        `Scrotal fistula`, 
        `Autonephrectomy`, 
        `Thimble bladder`, 
        `Papulonecrotic tuberculid`],
        optionStyleType: `st-lower-alpha`,
        answer: [4],
        ansText:`Rationale: <!--<b>e. Papulonecrotic tuberculid.</b>--> Papulonecrotic tuberculid is the only manifestation listed that can present early in the course of TB disease. The tuberculids are hypersensitivity reactions to MTBC antigens that were disseminated to the skin from other infectious foci, and as such, they are culture negative and typically PCR negative.`, 
        state: `notAnswered`,
        userAnswered: []
    ,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`        ,
        type: `MCSS`},
    {
        q: `Which of the following persons is LEAST likely to have tuberculosis infection?`,
        q2: ``,
        q3: [],
        option: [`A patient with fibrosis on chest radiograph and a tuberculin skin test (TST) of 5 mm`, 
        `A patient with HIV infection and a TST of 3 mm`, 
        `A recent immigrant from Vietnam with a TST of 11 mm`, 
        `A BCG-vaccinated patient with a TST of 14 mm`, 
        `A healthy U.S.-born teacher with a TST of 11 mm`],
        optionStyleType: `st-lower-alpha`,
        answer: [4],
        ansText:`Rationale: <!--<b>e. A healthy U.S.-born teacher with a TST of 11 mm.</b>--> Refer to <a href="655f2571edc841a5acf65a3acda66f12">Table 60.1</a> for the Centers for Disease Control and Prevention guidelines on TST interpretation. Patients (a), (b), and (c) are likely TB infected. A BCG-vaccinated person is likely from a country with high enough incidence of TB to warrant vaccination; hence a cutoff of 10 mm is likely to apply for this person. Patient (e) has no clear risk factors for TB; hence a cutoff of 15 mm would apply for this person. However, TST cutoffs may be set differently in local public health jurisdictions according to local epidemiology.`, 
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `Which of the following results most specifically diagnoses genitourinary tuberculosis?`,
        q2: ``,
        q3: [],
        option: [`A positive interferon γ release assay`, 
        `A positive urine polymerase chain reaction (PCR) for <i>Mycobacterium tuberculosis</i> complex`, 
        `A TST reaction of 25 mm`, 
        `A positive urine acid-fast bacilli (AFB) culture`, 
        `A renal biopsy showing AFB`],
        optionStyleType: `st-lower-alpha`,
        answer: [3],
        ansText:` `, 
        state: `notAnswered`,
        userAnswered: []
    ,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`        ,
        type: `MCSS`},
    {
        q: `Which of the following first-line antituberculosis agents does not cause hepatic toxicity?`,
        q2: ``,
        q3: [],
        option: [`Isoniazid`, 
        `Rifampin`, 
        `Pyrazinamide`, 
        `Ethambutol`, 
        `Streptomycin`],
        optionStyleType: `st-lower-alpha`,
        answer: [3],
        ansText:`Rationale: <!--<b>d. Ethambutol.</b>--> Ethambutol is rarely hepatotoxic. Its main toxicity is ocular, such as decreased visual acuity or red-green color blindness. Streptomycin is not considered hepatotoxic either, but it is also not considered a first-line agent in the United States.`, 
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `Which of the following drugs might have efficacy against extensively drug-resistant (XDR) tuberculosis?`,
        q2: ``,
        q3: [],
        option: [`Isoniazid (INH)`, 
        `Rifampin`, 
        `Pyrazinamide`, 
        `Moxifloxacin`, 
        `Amikacin`],
        optionStyleType: `st-lower-alpha`,
        answer: [2],
        ansText:`Rationale: <!--<b>c. Pyrazinamide.</b>--> By definition, MDR TB is resistant to INH, rifampin, any quinolone, and at least an additional injectable aminoglycoside. Hence, of the choices, pyrazinamide is the most likely to have efficacy against XDR TB.`, 
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `Which of the urological interventions is emergently indicated?`,
        q2: ``,
        q3: [],
        option: [`Nephrectomy of nonfunctional kidney in medically resistant hypertension`, 
        `Bladder augmentation of a contracted bladder in a patient with severe dysuria`, 
        `Percutaneous nephrostomy of obstructive hydronephrosis in acute renal failure`, 
        `Balloon dilatation and ureteral stenting of a proximal ureteral stricture`, 
        `Boari flap for a lower ureteral stricture that requires excision`],
        optionStyleType: `st-lower-alpha`,
        answer: [2],
        ansText:`Rationale: <!--<b>c. Percutaneous nephrostomy of obstructive hydronephrosis in acute renal failure.</b>--> All of the choices are appropriate indications for urological intervention. However, only (c) is emergently indicated. For the other interventions, waiting at least 4 to 6 weeks after initiation of medical therapy is preferred.`, 
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `Which of the following statements is FALSE about genitourinary (GU) TB patients?`,
        q2: ``,
        q3: [],
        option: [`Magnetic resonance imaging (MRI) is often used to help diagnose patients with GU TB.`, 
        `Computed tomography (CT) is most useful in extensive TB disease when other organ systems might be involved.`, 
        `The most common finding of GU TB on plain film is calcification.`, 
        `Intravenous urography (IVU) is the best test to detect early renal changes due to TB.`, 
        `The most common finding on IVU is obstructive uropathy from scarring.`],
        optionStyleType: `st-lower-alpha`,
        answer: [0],
        ansText:`Rationale: <!--<b>a. Magnetic resonance imaging (MRI) is often used to help diagnose patients with GU TB.</b>--> Although MRI has potential uses in the diagnosis of GU TB, it is not sufficiently superior to CT or IVU to warrant its frequent use.`, 
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `<b>Schistosomiasis</b><br/><br/>Of the following drugs, the most effective to treat schistosomiasis is:`,
        q2: ``,
        q3: [],
        option: [`albendazole.`, 
        `praziquantel.`, 
        `mebendazole.`, 
        `diethylcarbamazine.`, 
        `ivermectin.`],
        optionStyleType: `st-lower-alpha`,
        answer: [1],
        ansText:`Rationale: <!--<b>b. Praziquantel.</b>--> Although all of the drugs listed are antiparasitic agents, only praziquantel is used to treat schistosomiasis. In fact, praziquantel is the only drug approved for schistosomiasis by the World Health Organization (WHO).`, 
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `The life cycle stage of <i>Schistosoma haematobium</i> that infects humans transdermally is:`,
        q2: ``,
        q3: [],
        option: [`the worm.`, 
        `the schistosomule.`, 
        `the cercariae.`, 
        `the egg.`, 
        `the sporocyst.`],
        optionStyleType: `st-lower-alpha`,
        answer: [2],
        ansText:`Rationale: <!--<b>c. The cercariae.</b>--> The worm and egg stages (<a class="lightboxcallout" img-ref="image_fig_60_1" href="7e6c3446967d4cafaf2c2ab77f637363">Fig. 60.1</a>) are found in chronically infected humans but are intravascular or deposited in tissues such as the bladder, respectively. Cercariae infect humans by burrowing through the skin, whereupon they transform into schistosomules.`, 
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `<i>S. haematobium</i> infections are estimated to affect the following number of people:`,
        q2: ``,
        q3: [],
        option: [`1.1 billion`, 
        `1.1 million`, 
        `900,000`, 
        `112 million`, 
        `11 million`],
        optionStyleType: `st-lower-alpha`,
        answer: [3],
        ansText:`Rationale: <!--<b>d. 112 million.</b>--> Although an estimated 1 billion people are at risk of contracting schistosomiasis because they live in endemic areas, only 112 million are actively infected with <b><i>S. haematobium.</i></b>`, 
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `The life cycle stage of <i>S. haematobium</i> that induces the majority of human tissue pathology is:`,
        q2: ``,
        q3: [],
        option: [`the worm.`, 
        `the schistosomule.`, 
        `the cercaria.`, 
        `the egg.`, 
        `the sporocyst.`],
        optionStyleType: `st-lower-alpha`,
        answer: [3],
        ansText:`Rationale: <!--<b>d. The egg.</b>--> The majority of human tissue pathology caused by urogenital schistosomiasis is induced by the host immune response against <b><i>S. haematobium</i></b> eggs (see <a class="lightboxcallout" img-ref="image_fig_60_1" href="7e6c3446967d4cafaf2c2ab77f637363">Fig. 60.1</a>). In comparison to eggs, worms, schistosomules, and cercariae are much less immunogenic and are thought to correspondingly cause much less chronic tissue pathology.`, 
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `The eponym for acute schistosomiasis is:`,
        q2: ``,
        q3: [],
        option: [`Katayama fever.`, 
        `Bilharz syndrome.`, 
        `Barlow fever.`, 
        `Toshiro syndrome.`, 
        `Tan’s triad.`],
        optionStyleType: `st-lower-alpha`,
        answer: [0],
        ansText:`Rationale: <!--<b>a. Katayama fever.</b>--> The syndrome associated with acute schistosomiasis is named after the Katayama valley in Japan, a formerly endemic region for <b><i>Schistosoma japonicum.</i></b>`, 
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `The diagnostic, first-line gold standard for urogenital schistosomiasis is:`,
        q2: ``,
        q3: [],
        option: [`polymerase chain reaction.`, 
        `serology.`, 
        `cystourethroscopy with bladder biopsy.`, 
        `rectal biopsy.`, 
        `urine egg counts.`],
        optionStyleType: `st-lower-alpha`,
        answer: [4],
        ansText:`Rationale: <!--<b>e. Urine egg counts.</b>--> Although PCR and serology are highly sensitive for detecting infection, they are not considered first-line diagnostic modalities. Cystourethroscopy (<a class="lightboxcallout" img-ref="image_fig_60_2" href="0ffd060a876d4ae6906f04bdfb8967a1">Fig. 60.2</a>) with bladder biopsy and rectal biopsy are highly invasive and reserved for difficult-to-diagnose cases or suspected cancer. Microscopic enumeration of <b><i>S. haematobium</i></b> eggs shed in urine are the diagnostic, first-line gold standard (albeit slow and impractical in many field settings).`, 
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `Without treatment, <i>Schistosoma</i> worms can live in human hosts for an average of:`,
        q2: ``,
        q3: [],
        option: [`3 months.`, 
        `9 months.`, 
        `3 to 5 years.`, 
        `5 decades.`, 
        `5 weeks.`],
        optionStyleType: `st-lower-alpha`,
        answer: [2],
        ansText:`Rationale: <!--<b>c. 3 to 5 years.</b>--> Although there have been reports that some schistosome worms can live for several decades, on average they are believed to only live for 3 to 5 years.`, 
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `Surgical options for reconstruction of irreversible ureteral lesions caused by urogenital schistosomiasis include all of the following EXCEPT:`,
        q2: ``,
        q3: [],
        option: [`renal autotransplantation.`, 
        `Boari flaps.`, 
        `ureteroureterostomies.`, 
        `ileal ureter.`, 
        `suprapubic intravesical ureterostomy.`],
        optionStyleType: `st-lower-alpha`,
        answer: [0],
        ansText:`Rationale: <!--<b>a. Renal autotransplantation.</b>--> Renal autotransplantation is reserved for reconstruction of the urinary tract in the setting of multiple and/or large renal tumors. There are much less morbid surgical options for reconstruction of schistosomiasis-associated ureteral lesions.`, 
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `Intermediate snail hosts for <i>S. haematobium</i> are members of the following genus:`,
        q2: ``,
        q3: [],
        option: [`<i>Biomphalaria.</i>`, 
        `<i>Oncomelania.</i>`, 
        `<i>Bulinus.</i>`, 
        `<i>Helix.</i>`, 
        `<i>Achatina.</i>`],
        optionStyleType: `st-lower-alpha`,
        answer: [2],
        ansText:`Rationale: <!--<b>c. <i>Bulinus.</i></b>--> <b><i>Biomphalaria</i></b> and <b><i>Oncomelania</i></b> are host snails for <b><i>Schistosoma mansoni</i></b> and <b><i>S. japonicum,</i></b> respectively, but not <b><i>S. haematobium. Helix</i></b> and <b><i>Achatina</i></b> snails are terrestrial and not considered hosts for human-specific schistosomes. `, 
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `<b>Other Parasitic Infections</b><br/><br/>The rickettsia-like organism that is an endosymbiont of the parasites that cause lymphatic filariasis (LF) and onchocerciasis is:`,
        q2: ``,
        q3: [],
        option: [`<i>Rickettsia rickettsii.</i>`, 
        `<i>Wuchereria bancrofti.</i>`, 
        `<i>Wolbachia</i> spp.`, 
        `<i>Brugia malayi.</i>`, 
        `<i>Brugia timori.</i>`],
        optionStyleType: `st-lower-alpha`,
        answer: [2],
        ansText:`Rationale: <!--<b>c. <i>Wolbachia</i> spp.</b>--> <b><i>Wolbachia</i></b> endosymbionts infect <b><i>W. bancrofti</i></b>, <b><i>Brugia</i></b> spp., and <b><i>O. volvulus.</i></b> They appear to be involved in embryogenesis and, when killed with antimicrobial therapy (e.g., doxycycline), result in decreased microfilaria release and suppressed larval molting.`, 
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `The chronic manifestations of LF are mostly seen in:`,
        q2: ``,
        q3: [],
        option: [`short-term missionaries to endemic areas.`, 
        `short-term aid workers to endemic areas.`, 
        `long-term (current) residents of endemic areas.`, 
        `short-term tourists to endemic areas.`, 
        `short-term visiting friends and relatives travelers (VFRs) to endemic areas.`],
        optionStyleType: `st-lower-alpha`,
        answer: [2],
        ansText:`Rationale: <!--<b>c. Long-term (current) residents of endemic areas.</b>--> Because transmission is inefficient, long-term exposure to multiple infective bites appears to be necessary for transmission of LF and the development of chronic disease due to LF. Therefore, short-term visitors to endemic areas rarely develop LF, which is mostly seen in long-term residents of endemic areas.`, 
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `Most patients infected with <i>Onchocerca volvulus</i> live in:`,
        q2: ``,
        q3: [],
        option: [`Latin America.`, 
        `Oceania.`, 
        `Asia.`, 
        `Sub-Saharan Africa.`, 
        `the Middle East.`],
        optionStyleType: `st-lower-alpha`,
        answer: [3],
        ansText:`Rationale: <!--<b>d. Sub-Saharan Africa.</b>--> Although endemic to Latin America and the Middle East as well, 99% of persons who have onchocerciasis live in sub-Saharan Africa.`, 
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `The majority of patients infected with <i>Wuchereria bancrofti</i> have:`,
        q2: ``,
        q3: [],
        option: [`lymphedema.`, 
        `hydrocele.`, 
        `no clinical manifestations.`, 
        `acute adenolymphangitis (ADL).`, 
        `elephantiasis.`],
        optionStyleType: `st-lower-alpha`,
        answer: [2],
        ansText:`Rationale: <!--<b>c. No clinical manifestations.</b>--> Although <b><i>W. bancrofti</i></b> infection can lead to all of these clinical manifestations, most infected persons remain asymptomatic.`, 
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `Which drug should not be given to patients infected with <i>O. volvulus</i> or to those infected with high-grade <i>Loa loa</i> microfilaremia?`,
        q2: ``,
        q3: [],
        option: [`Diethylcarbamazine (DEC)`, 
        `Albendazole`, 
        `Doxycycline`, 
        `Azithromycin`, 
        `Amoxicillin`],
        optionStyleType: `st-lower-alpha`,
        answer: [0],
        ansText:`Rationale: <!--<b>a. Diethylcarbamazine (DEC).</b>--> DEC can cause blindness in patients with onchocerciasis (due to the inflammatory response to parasites in the anterior chamber of the eye) and encephalopathy in patients with high-grade <b><i>L. loa</i></b> microfilaremia.`, 
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    



];
