var quiz = [
    {
        q: `A 27-year-old patient presented to the emergency room with 36 hours of a prolonged painful erection. Blood gas analysis shows this to be veno-occlusive priapism, and bilateral T-shunts with corporal dilation were performed. This was unsuccessful in reducing the erection, and 1 week later the erection detumesced. After counseling, the patient elects to have a penile implant placed at this time. The type of cylinder that should NOT be used in this circumstance would be: `,
        q2: ``,
        q3: [],
        option: [`AMS 700 CX. `, 
        ` AMS 700 LGX.`, 
        `Genesis. `, 
        ` Titan`, 
        ` Tactra`],
        optionStyleType: `st-lower-alpha`,
        answer: [1],
        ansText: `Rationale: The LGX is the only cylinder with distal expansion when inflated. Following a T-shunt, this cylinder may protrude through the defect at the end of the corporal body or create pressure on this weakened area when it is inflated. `,
        state: `notAnswered`,
        userAnswered: []
    ,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`        ,
        type: `MCSS`},
    {
        q: `During dilation to place a cylinder into a scarred corporal body, a dilator enters the urethra in the fossa navicularis. All of the following would be acceptable approaches EXCEPT: `,
        q2: ``,
        q3: [],
        option: [`abandon the case `, 
        ` proceed placing both cylinders.`, 
        `place a cylinder on the side without the perforation and return at a later date to place the other cylinder. `, 
        `create hypospadias, repair the perforation defect securely, and place both cylinders `],
        optionStyleType: `st-lower-alpha`,
        answer: [1],
        ansText: `Rationale: Placing both cylinders would allow organisms to possibly enter the defect and contaminate the cylinder. In the other answers the cylinder is not exposed to possible infection.`,
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
     {
        q: `Select the TRUE statement: `,
        q2: ``,
        q3: [],
        option: [`Repair of penile implants is currently in the range of 50% within 5 years. `, 
        `Satisfaction with penile implants among both patients and partners is in the 80% to 90% range.`, 
        ` Infection rates with penile implant placement are comparable to those of other surgical procedures in the range of 5% to 7%.`, 
        ` Semirigid rod prostheses are preferable to hydraulic implants in impotent spinal cord injury patients.`, 
        `The lock-out valves of the two vendors’ three-piece inflatable penile implants designed to minimize autoinflation are in the same location. `],
        optionStyleType: `st-lower-alpha`,
        answer: [1],
        ansText: `Rationale: Repair of penile implants is currently in the range of 15% at 5 years. Infection rates with penile implant placement are comparable to those of other surgical procedures in the range of 1% to 3%. Spinal cord injury patients have a high incidence of rod erosions (20% to 50%). Coloplast has the lock-out valve on the reservoir; BSci has the lock-out valve on the pump. `,
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `A “salvage” or “rescue” procedure for an infected penile implant would likely be less successful in a patient with all of the following features EXCEPT: `,
        q2: ``,
        q3: [],
        option: [`cellulitis around the incision and over prosthetic parts. `, 
        `purulent drainage from the incision. `, 
        ` occurrence within 2 months of the implant placement.`, 
        ` associated with an aggressive organism such as methicillin-resistant <i>Staphylococcus aureus</i> (MRSA) or <i>Pseudomonas aeruginosa.</i>`, 
        ` diabetes mellitus as a comorbidity.`],
        optionStyleType: `st-lower-alpha`,
        answer: [4],
        ansText: `Rationale: Answers a through d are risk factors for failed salvage as noted in the chapter narrative. Diabetes mellitus, although a risk factor for implant infection, is not associated with a higher incidence of failed salvage.  `,
        state: `notAnswered`,
        userAnswered: []
    ,
	type: `MCSS`,
	type: `MCSS`        ,
        type: `MCSS`},
     {
        q: ` Which of the following is FALSE regarding informed consent for penile prosthesis surgery?`,
        q2: ``,
        q3: [],
        option: [`The greatest disappointment after surgery is the size of the erection. `, 
        `Tissue problems such as pump migration, erosion, and extrusion of parts occur and require re-operation. `, 
        ` Penile sensation and climax are not affected postoperatively.`, 
        `Alternative erectile dysfunction (ED) treatment options should be explained and offered prior to surgery. `, 
        `Unrealistic expectations for the results of penile implant surgery should be identified and discussed prior to surgery. `],
        optionStyleType: `st-lower-alpha`,
        answer: [2],
        ansText: `Rationale: Penile sensation and ejaculation may both be diminished postoperatively. `,
        state: `notAnswered`,
        userAnswered: []
    ,
	type: `MCSS`,
	type: `MCSS`        ,
        type: `MCSS`},
    {
        q: ` Advantages to the penoscrotal approach for penile implant placement include all of the following EXCEPT:`,
        q2: ``,
        q3: [],
        option: [` secure placement of the pump in a subdartos pouch.`, 
        ` cosmetic skin incision.`, 
        `avoidance of damaging the dorsal neurovascular bundle. `, 
        `easier placement of semirigid rod implants. `, 
        `allows placement of the two-piece inflatable implant. `],
        optionStyleType: `st-lower-alpha`,
        answer: [3],
        ansText: `Rationale: Semirigid rod cylinders are most easily placed through a subcoronal corporotomy. `,
        state: `notAnswered`,
        userAnswered: []
    ,
	type: `MCSS`        ,
        type: `MCSS`},
    {
        q: `Select the FALSE statement: `,
        q2: ``,
        q3: [],
        option: [`A high electrocautery setting may damage the Bioflex cylinders but not silicone-covered cylinders. `, 
        ` Both the Bioflex and triple-layer AMS 700 cylinders are very durable, but may form aneurysms when subjected to repeated high external pressure.`, 
        ` Semirigid rod implant malfunction is very rare and is limited to central wire breakage.`, 
        ` The Ambicor cylinders give less rigidity and flaccidity than three-piece inflatable cylinders.`, 
        `The AMS 700 LGX cylinders are superior to the AMS 700 CX and Titan cylinders for straightening a curved erection due to their ability to increase in length. `],
        optionStyleType: `st-lower-alpha`,
        answer: [4],
        ansText: `Rationale: The LGX cylinders tend to exaggerate a curved erection.  `,
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `The following are features of crural crossover of penile implant cylinders EXCEPT: `,
        q2: ``,
        q3: [],
        option: [` difficult cylinder insertion.`, 
        ` cylinders not appearing to be symmetric on either side of a Foley catheter in the urethra.`, 
        `curved erection. `, 
        `lopsided appearing erection. `, 
        `total corporal length measurements significantly different on right and left sides. `],
        optionStyleType: `st-lower-alpha`,
        answer: [2],
        ansText: `Rationale: Despite crossover, the erection is commonly straight. `,
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},

 {
        q: `The following are suitable locations for a penile implant reservoir EXCEPT: `,
        q2: ``,
        q3: [],
        option: [`a scrotal cavity where the testis had been previously removed. `, 
        `below the rectus muscle above the transversalis fascia. `, 
        `the epigastrium through a subcostal incision. `, 
        ` deep in the fat above the abdominal wall fascia in an obese patient.`, 
        ` in the peritoneal cavity.`],
        optionStyleType: `st-lower-alpha`,
        answer: [0],
        ansText: `Rationale: The Cloverleaf reservoirs contain lockout valves that could be manipulated through the scrotum, resulting in cylinder autoinflation. The Conceal reservoir is too large for scrotal placement, and the AMS spherical reservoir might fit with underfilling but would be subject to manipulation and wear in a scrotal location. `,
        state: `notAnswered`,
        userAnswered: []
    ,
	type: `MCSS`        ,
        type: `MCSS`},
     




];
