var quiz = [
  {
    q: ` Peyronie’s disease (PD):`,
    q2: ``,
    q3: [],
    option: [
      `is a wound healing disorder. `,
      ` is an autoimmune disease.`,
      ` is a transient disorder (30% to 50% of the time).`,
      ` may degenerate into cancer.`,
      `is associated with Dupuytren contracture in 40% of men. `,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [0],
    ansText: `Rationale: <b>PD is currently recognized as a wound healing disorder of the tunica albuginea (Devine and Horton, 1988)</b><sup>a</sup> that results in the formation of an exuberant scar, occurring presumably after an injury to the penis, which activates an abnormal wound healing response (Ralph et al., 2010; Levine and Burnett 2013; Greenfield and Levine, 2005; Van De Water, 1997). PD is not a premalignant condition, spontaneous resolution is a rare event, and improvement likely does not take place in more than 13% of men over the first 12 to 18 months. Though an association with Dupuytren contracture has been described, studies vary widely on this association.
    
    <br /><br /><b>a</b> Sources referenced can be found in <i>Campbell-Walsh-Wein Urology, ed 12 ,</i> on the <a href="http://Expert%20Consult%20website">Expert Consult website</a>.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `The fibrous plaques in PD originate in: `,
    q2: ``,
    q3: [],
    option: [
      ` Buck’s fascia.`,
      `corpora cavernosa. `,
      ` corpus spongiosum.`,
      `the tunica albuginea surrounding the corpora cavernosa. `,
      `the tunica albuginea surrounding the corpus spongiosum. `,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [3],
    ansText: `Rationale: PD plaques originate in the tunica albuginea. <b>Sixty percent to seventy percent of plaques are located on the dorsal aspect of the tunica albuginea and are usually associated with the septum (Pryor and Ralph, 2002).</b> It is possible that pressures on the penis during intercourse result in a delamination between the two layers, activating the abnormal wound-healing process, which is trapped within the tunic, fostering the progressive scarring. `,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: ` Based on recent natural history studies on PD, a 54-year-old man with a 60-degree dorsal curve 18 months after onset has:`,
    q2: ``,
    q3: [],
    option: [
      `40% chance of spontaneous improvement of deformity. `,
      ` 70% chance of getting worse.`,
      ` 10% chance of getting worse.`,
      ` 10% or less chance of spontaneous improvement of deformity.`,
      `80% chance of staying the same. `,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [3],
    ansText: `Rationale:<b>Spontaneous regression has been looked at in several contemporary natural history studies, which have suggested that no more than 13% will experience improvement of deformity.</b> Full spontaneous resolution is extremely rare. If no treatment is offered, up to 50% will experience worsening of their deformity (Mulhall et al., 2006).  `,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: ` What is the prevalence of PD following radical prostatectomy?`,
    q2: ``,
    q3: [],
    option: [`4% `, ` 1% to 3%`, ` 11% to 16%`, ` &gt;20%`, ` 0%`],
    optionStyleType: `st-lower-alpha`,
    answer: [2],
    ansText: `Rationale: Tal and associates (2010) demonstrated an incidence of PD of 15.9% with a mean time to development of disease of 13.9 months. Ciancio and Kim (2000) also examined the effects of prostatectomy on penile fibrosis and sexual dysfunction. <b>Eleven percent of all patients undergoing prostatectomy developed fibrotic changes in the penis.</b> This fibrosis led to penile curvature in 93%, “waistband” deformity in 24%, and palpable plaques in 69%.  `,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `Plaque calcification: `,
    q2: ``,
    q3: [],
    option: [
      `can be reliably identified on physical examination. `,
      ` can be found in 50% to 60% of men with PD.`,
      `is not an indication of stable, mature disease. `,
      ` is associated with successful intralesional injection therapy.`,
      ` is a predictive factor for the need for surgical treatment.`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [2],
    ansText: `Rationale: <b>Only recently has it been recognized that calcification may occur early after the onset of the scarring process, and therefore the previously held notion that calcification is an indication of chronic, severe, and/or mature disease appears untrue (Levine et al., 2013).</b> Several investigators have indicated that intralesional injection therapy of verapamil and interferon is less likely to be successful in men with significant calcification (Levine et al., 2002b; Hellstrom et al., 2006). A “rock-hard” plaque may be an indicator of calcification but will need to be confirmed with some form of imaging, preferably ultrasound. A calcified plaque is readily identified by ultrasound because of the hyperdensity of the plaque with shadowing behind it. Calcification itself does not predict the need for surgery. Approximately 34% of PD patients will have some degree of plaque calcification. `,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `Psychological distress in men with PD: `,
    q2: ``,
    q3: [],
    option: [
      `is infrequent. `,
      `is typically resolved by successful surgery. `,
      ` is frequently associated with penile shortening.`,
      ` correlates with degree of erect curvature.`,
      ` has no association with relationship issues with the patient’s partner.`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [2],
    ansText: `Rationale: <b>Penile shortening and inability to have intercourse are the two most common and consistent risk factors for emotional distress and relationship problems associated with PD (Smith et al., 2008; Rosen et al., 2008).</b> Psychosocial stress is common and is reported by 77% to 94% of men with PD (Gelbard et al., 1990; Tal et al., 2012; Nelson and Mulhall, 2013). PD also commonly affects the patient’s sexual partner, causing feelings of helplessness, as well as feeling personally responsible for the PD due to trauma during intercourse and sadness over loss of intimacy (Rosen et al., 2008). For some patients even a lesser degree of curvature may be highly bothersome or provoke distress (Hellstrom et al., 2013). Despite “successful treatment” that may allow the patient to be sexually functional again, there is often persistent psychological distress, presumably due to the residual changes compared with that man’s pre-PD penis (Jones, 1997; Gelbard et al., 1990).  `,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `All of the following statements regarding the physical examination of a man presenting with PD are true EXCEPT that the examination: `,
    q2: ``,
    q3: [],
    option: [
      `should include measurement of plaque size with calipers. `,
      `should include direct assessment of curvature following injection of vasoactive agent. `,
      ` should include measurement of stretched penile length.`,
      ` can be supported with a picture of the erect penis by a smartphone.`,
      `should include assessment of the patient’s palms. `,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [0],
    ansText: `Rationale: Measurement of the size of the plaque with any modality has been found to be inaccurate, as the plaque is rarely a discrete lesion (Bacal et al., 2009; Levine and Burnett, 2013; Ralph et al., 2010; Hatzimouratidis et al., 2012). Deformity assessment via ultrasound after injection of vasoactive agent has been shown to be the best method of assessing curvature as well as erectile response. Pictures taken from multiple vantage points may give a better idea of deformity during initial consultation. Because of the association with other collagen vascular disorders, the patient’s palms should be examined. `,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: ` Penile duplex ultrasound provides information on all of the parameters below EXCEPT:`,
    q2: ``,
    q3: [],
    option: [
      `penile deformity. `,
      `erectile response to vasoactive penile injection. `,
      `penile vascular flow parameters. `,
      ` penile sensory integrity.`,
      `plaque calcification. `,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [3],
    ansText: `Rationale: The benefits of a complete duplex ultrasound assessment include identification of calcification during initial surveillance in the flaccid state, assessment of penile vascular flow parameters following intracavernosal injection of vasoactive agent, observing the erectile response to the vasoactive injection compared to the patient’s sexually induced erection at home, and finally providing the best opportunity to objectively assess deformity. These parameters are absolutely critical to the decision process for the patient who is considering surgery. Penile sensation is best evaluated with biothesiometry. `,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `Pentoxifylline and the phosphodiesterase-5 (PDE5) inhibitors have been shown in an animal model of PD to reduce scarring by what proposed mechanism? `,
    q2: ``,
    q3: [],
    option: [
      `Improved penile blood flow `,
      `Antiinflammatory `,
      `Elevated local levels of nitric oxide (NO) `,
      `Anti–transforming growth factor-β (TGF-β) `,
      ` Mechanotransduction`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [2],
    ansText: `Rationale: <b>Pentoxifylline is a nonspecific phosphodiesterase inhibitor with combined antiinflammatory and antifibrogenic properties.</b> NO synthesized by inducible nitric oxide synthase (iNOS) reacts with reactive oxygen species (ROS), thus reducing ROS levels and presumably inhibiting fibrosis. The antifibrotic effects of NO may be mediated at least in part by the reduction of myofibroblast abundance and lead to a reduction in collagen I synthesis (Vernet et al., 2002). `,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: ` Penile injection therapy (i.e., prostaglandin E1, TriMix-gel, etc.) for ED is not directly responsible for:`,
    q2: ``,
    q3: [],
    option: [
      `cavernosal fibrosis. `,
      ` Peyronie’s disease.`,
      ` penile pain.`,
      ` priapism`,
      ` high success rate.`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [1],
    ansText: `Rationale: Injection therapy has no association with leading to PD. It may, however, lead to some degree of cavernosal fibrosis, pain, and priapism. When used in the appropriate population, intracavernosal injection therapy for ED does have a high success rate.  `,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: ` A 35-year-old man with PD is able to achieve an erection adequate for intercourse with minimal discomfort and reported dorsal erect penile curvature of 20 degrees. The initial treatment should be:`,
    q2: ``,
    q3: [],
    option: [
      ` reassurance`,
      `oral vitamin E. `,
      ` intralesional steroids.`,
      ` oral tamoxifen.`,
      ` intralesional collagenase.`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [0],
    ansText: `Rationale: In this case, a young man presents with PD with a minimal curvature and minimal discomfort. Pursuing aggressive therapy is not indicated because the disease process may not worsen. Therefore, reassurance is the proper answer. This patient should also be counseled to follow up should he see any exacerbation of his symptoms. At this time, intralesional collagenase is not indicated for curvature less than 30 degrees, the two noted oral therapies are not noted to be beneficial, and intralesional steroids are not recommended because of lack of objective evidence of benefit. `,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: ` A 66-year-old man presents with a 2-year history of PD and a 55-degree dorsal curvature. He also notes that his average-grade erection with sexual stimulation at home is a grade {5/10}, which would not be adequate for intromission even if the penis were straight. Duplex ultrasound analysis demonstrates arterial insufficiency and an inadequate erectile response to 90 mg of intracorporal papaverine. The most appropriate treatment option for this patient who wants to resume sexual activity would be:`,
    q2: ``,
    q3: [],
    option: [
      `16-dot plication. `,
      ` vacuum constriction device.`,
      ` penile prosthesis with penile straightening.`,
      ` intralesional verapamil injections.`,
      ` Plaque incision and grafting`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [2],
    ansText: `Rationale: This man presents with stable PD, a borderline moderate to severe curvature, but a poor-quality erection at home and an inadequate erectile response during duplex ultrasound with a high dose of vasoactive intracorporal drug injection. For the motivated patient who has both ED and PD, placement of a penile prosthesis with straightening maneuvers is the most likely treatment to address both problems. Plication or plaque incision with grafting would not fix this man’s ED. Use of oral therapy had not been proven to be beneficial in this circumstance. Intralesional injection of any sort may potentially benefit his deformity, but given that he has inadequate erectile response, intralesional injections would not result in ability to resume sexual activity. `,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: ` Tunica plication is preferred for mild to moderate lateral curvature correction in a patient who is able to accomplish adequate erections with the assistance of PDE-5I because of:`,
    q2: ``,
    q3: [],
    option: [
      `less shortening compared with grafting. `,
      ` better sensory protection.`,
      ` diminished risk of postoperative ED.`,
      `greater potential for loss of erect length. `,
      `less chance of recurrence `,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [2],
    ansText: `Rationale: A tunica plication procedure is the preferred approach because it has the least likelihood of causing injury to the underlying cavernosal tissue, which presumably is responsible for postsurgical ED seen most commonly with a grafting procedure. There is indeed a greater potential for loss of erect length with a plication and less likelihood of damaging the penile sensory nerves, but the diminished risk of postoperative ED is the strongest reason to pursue a plication rather than grafting procedure, particularly in patients with less than severe curvature. `,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: ` Postoperative rehabilitation is designed to aid in postoperative healing and outcomes in the following ways, EXCEPT:`,
    q2: ``,
    q3: [],
    option: [
      `to prevent shortening and possibly recover some lost length. `,
      ` to encourage straight healing.`,
      `to enhance cicatrix contracture. `,
      ` to preserve vascular integrity.`,
      `to encourage partner participation. `,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [2],
    ansText: `Rationale: Postoperative rehabilitation with massage and stretch, nightly use of a PDE5 inhibitor, and traction therapy are designed to enhance postoperative healing in all listed ways except for c, which is the correct answer because enhancing cicatrix contracture would not enhance healing or postoperative outcomes.  `,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: ` All of the following are true regarding penile traction therapy after surgical penile straightening, EXCEPT:`,
    q2: ``,
    q3: [],
    option: [
      `increases or preserves postoperative length. `,
      ` encourages tissue remodeling.`,
      ` should be used for 3 or more hours/day for optimum results.`,
      `increases the risk of sensory change. `,
      ` results appear dose-related.`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [3],
    ansText: `Rationale: <b>Penile traction therapy has emerged as an effective adjunct treatment option.</b> Traction therapy has been shown to increase or preserve postoperative length and encourage tissue modeling, and it does appear to be dose-related. In addition, one study suggested that the minimum average time for daily use following surgery would be 3 hours or more per day. There is no evidence that traction therapy causes injury to the sensory nerves, nor is there evidence to suggest that it increases the risk of sensory change. `,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `What is the most dreaded complication occurring after manual modeling during placement of a penile prosthesis in a man with PD? `,
    q2: ``,
    q3: [],
    option: [
      `Tunica tear proximal `,
      `Urethral injury `,
      `Sensory deficit `,
      ` Recurrent curvature`,
      `Distal urethral perforation `,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [1],
    ansText: `Rationale: Manual modeling was introduced in the mid-1990s as a straightening maneuver to correct residual curvature after placement of a penile prosthesis. In performing this procedure, the primary reported risk is injury to the urethra at the meatus, where the prosthetic cylinder tips may extrude through the meatus as a result of pressure placed on the distal shaft during the modeling process. Although sensory deficit, recurring curvature, and tunica tear are possible complications, they have not been reported, nor has a proximal urethral perforation.  `,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `Indications to perform a plaque incision or partial excision and grafting include all of the following, EXCEPT: `,
    q2: ``,
    q3: [],
    option: [
      `severe curvature in excess of 70 degrees. `,
      `indentation resulting in an unstable penis or hinge effect. `,
      ` a short penis (&lt;9 cm) with severe curve and poor rigidity.`,
      `a short penis with severe curvature and excellent rigidity. `,
      ` extensive plaque calcification associated with severe deformity.`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [2],
    ansText: `Rationale: This is the only option noted that would not be appropriately treated by a grafting procedure for PD, primarily because of the poor rigidity. <b>One of the primary indications to perform a grafting procedure would be the patient having a strong erection preoperatively with severe curvature in excess of 70 degrees, having indentation causing an unstable penis or hinge effect, hourglass deformity, or a short penis. The key here is the poor rigidity, which would be an absolute contraindication to performing a grafting procedure; it is more likely to cause further ED in this circumstance.</b>  `,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `The primary concern with a grafting procedure for PD is: `,
    q2: ``,
    q3: [],
    option: [
      ` postoperative erectile dysfunction (ED).`,
      ` incomplete correction of hinge effect.`,
      ` penile shortening.`,
      ` decreased penile sensation`,
      `graft infection. `,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [0],
    ansText: `Rationale: Although the other listed side effects have been reported, the primary concern with patients undergoing this procedure is postoperative ED. Therefore, proper patient selection preoperatively would include only those men who have excellent-quality rigidity with or without PDE5 inhibitor therapy and have a normal vascular response during duplex ultrasound assessment. `,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: ` Which of the following is a candidate for plaque incision and grafting?`,
    q2: ``,
    q3: [],
    option: [
      `60-degree severe ventral curve `,
      ` 30-degree curvature with suboptimal rigidity even with PDE5 inhibitors`,
      ` 70 degrees with hinge effect`,
      ` 90-degree lateral curve presenting 5 months after onset`,
      `30-degree dorsal curvature in a patient who desires to gain length as a result of surgery `,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [2],
    ansText: `Rationale: <b>Severe curve greater than 70 degrees and hinge effect are two indications to perform an incision and grafting procedure. Ventral curvatures when repaired with grafting have a much higher rate of complete ED.</b> Those with suboptimal rigidity tend to also develop more erectile problems post-grafting. A 90-degree curve may be an indication, but all surgical procedures should be delayed at least 1 year from the time of onset with 6 months of stable disease. Finally, it should be recognized that although a patient is more likely to recover some length after performing a grafting procedure, neither grafting nor plication operations should be expected to result in substantial gain of length; the primary goal is straightening. `,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `The ideal graft includes all of the following EXCEPT: `,
    q2: ``,
    q3: [],
    option: [
      `thin, strong, and easy to suture. `,
      ` no rejection.`,
      `resistant to infection. `,
      `preserves erectile function. `,
      `contracts during healing. `,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [4],
    ansText: `Rationale: Contraction during the healing process would not be included in the criteria for an ideal graft.  `,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: ` The IMPRESS trials for Clostridium Collagenase Histolyticum (CCH) with modeling found that which of the following patient group would benefit from CCH?`,
    q2: ``,
    q3: [],
    option: [
      `Calcified plaques that have been present for less than 12 months `,
      ` Ventral plaques greater than 60 degrees`,
      ` Stable plaques between 30 and 90 degrees.`,
      `Stable ventral plaques less than 60 degrees `,
      `Hourglass deformities less than 45 degrees. `,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [2],
    ansText: `Rationale: IMPRESS Phase 3 Randomized clinical trials (RCTs) showed that CCH resulted in an improvement of 17 degrees versus 9 degrees (control) in patients with stable dorsal plaques between 30 and 90 degrees. Those who had unstable hinges, calcified plaques, hourglass effect, severe ED, or ventral plaques were excluded from the study. Various quality of life parameters were also improved with CCH injection.  `,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: ` Which of the following is a significant concern with CCH?`,
    q2: ``,
    q3: [],
    option: [
      `Cost and length of treatment `,
      ` Risk of ED`,
      `Autoimmune reaction `,
      `Penile bruising `,
      ` High risk of penile fracture`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [0],
    ansText: `Rationale: In the IMPRESS trial, patients were given four treatment courses consisting of two injections each. Each injection costs $3300. This leads to significant cost and numerous office visits, which may pose a significant burden to the patient. De novo ED has not been reported with CCH. Penile bruising is a common side effect but is almost always benign. Penile fracture is a dreaded complication but occurs in less than 1% in a pooled analysis. There are no reports of severe autoimmune reactions associated with CCH. `,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
];
