var quiz = [
     {
        q: ` Which of the following penile lesions is not typically associated with viral infection?   `,
        q2: ``,
        q3: [],
        option: [` Balanitis xerotica obliterans   `, 
        `   Condylomata acuminatum  `, 
        `  Kaposi sarcoma   `, 
        `  Bowenoid papulosis `, 
        `   Erythroplasia of Queyrat  `],
        optionStyleType: `st-lower-alpha`,
        answer: [0],
        ansText: `Rationale: Also known as lichen sclerosus, manifests as a whitish patch on the prepuce or glans, often involving the meatus and sometimes extending into the fossa navicularis. The cause is unknown but has not been associated with known viruses. Condyloma, Bowenoid papulosis, and erythroplasia of Queyrat are associated with HPV infection while Kaposi sarcoma is associated with HPV 8 infection.  `,
        state: `notAnswered`,
        userAnswered: []
    ,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`        ,
        type: `MCSS`},
     {
        q: `  Which of the following infections is associated with cervical dysplasia?  `,
        q2: ``,
        q3: [],
        option: [`  Human immunodeficiency virus (HIV) infection  `, 
        `    Herpesvirus infection `, 
        `  Gonorrhea   `, 
        `  Human papillomavirus (HPV) infection `, 
        `   Lymphogranuloma venereum  `],
        optionStyleType: `st-lower-alpha`,
        answer: [3],
        ansText: `Rationale: HPV is recognized as the principal etiologic agent in cervical dysplasia and cervical cancer.  `,
        state: `notAnswered`,
        userAnswered: []
    ,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`        ,
        type: `MCSS`},
     {
        q: `   What is the major difference between Bowen disease and erythroplasia of Queyrat? `,
        q2: ``,
        q3: [],
        option: [`  Loss of rete pegs  `, 
        ` Keratin staining    `, 
        `  Viral etiologic agents   `, 
        ` Location  `, 
        `Treatment options`],
        optionStyleType: `st-lower-alpha`,
        answer: [3],
        ansText: `Rationale: Carcinoma in situ of the penis is referred to by urologists and dermatologists as erythroplasia of Queyrat if it involves the glans penis or prepuce and as Bowen disease if it involves the remainder of the penile shaft skin, genitalia, or perineal region.  `,
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
     {
        q: `  Kaposi sarcoma of the acquired immunodeficiency syndrome (AIDS)–related (epidemic) type is associated with which of the following etiologic agents?  `,
        q2: ``,
        q3: [],
        option: [` HPV type 16   `, 
        `   Human herpesvirus (HHV) type 8  `, 
        `  HPV type 32   `, 
        ` <i>Haemophilus ducreyi</i> (chancroid [soft chancre])  `, 
        ` Coxsackievirus type 23    `],
        optionStyleType: `st-lower-alpha`,
        answer: [1],
        ansText: `Rationale: HHV type 8—also known as Kaposi sarcoma-associated herpesvirus—is strongly suspected to be the etiologic agent of epidemic (AIDS-related) Kaposi sarcoma.  `,
        state: `notAnswered`,
        userAnswered: []
    ,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`        ,
        type: `MCSS`},
     {
        q: `  Where do penile cancers most commonly arise?  `,
        q2: ``,
        q3: [],
        option: [`  Glans  `, 
        `   Shaft  `, 
        `  Frenulum   `, 
        ` Coronal sulcus  `, 
        `  Scrotum   `],
        optionStyleType: `st-lower-alpha`,
        answer: [0],
        ansText: `Rationale: Penile tumors may present anywhere on the penis but occur most commonly on the glans (48%) and prepuce (21%). `,
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
     {
        q: `   Which of the following is not considered a risk factor for the development of squamous cell carcinoma of the penis? `,
        q2: ``,
        q3: [],
        option: [` Cigarette smoke   `, 
        `   HPV infection  `, 
        `  Phimosis   `, 
        ` Gonorrhea  `, 
        `   Chewing tobacco  `],
        optionStyleType: `st-lower-alpha`,
        answer: [3],
        ansText: `Rationale: No convincing evidence has been found linking penile cancer to other factors such as occupation, other venereal diseases (gonorrhea, syphilis, herpes), marijuana use, or alcohol intake.  `,
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
     {
        q: `  All of the following are preventive strategies to decrease the incidence of penile cancer EXCEPT:  `,
        q2: ``,
        q3: [],
        option: [`circumcision after 21 years of age    `, 
        `  HPV vaccination   `, 
        `   daily genital hygiene  `, 
        ` avoiding tobacco products  `, 
        `   circumcision before puberty  `],
        optionStyleType: `st-lower-alpha`,
        answer: [0],
        ansText: `Rationale: Adult circumcision appears to offer little or no protection from subsequent development of the disease. These data suggest that the crucial period of exposure to certain etiologic agents may have already occurred at puberty and certainly by adult age, rendering later circumcision relatively ineffective as a prophylactic tool for penile cancer.   `,
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
     {
        q: ` Which of the following statements regarding penile cancer is FALSE?   `,
        q2: ``,
        q3: [],
        option: [`  Cancer may develop anywhere on the penis.  `, 
        `  Because of the associated discomfort, patients usually present to physicians within the first month of noting the lesion.   `, 
        `   Phimosis may obscure the nature of the lesion.  `, 
        ` Penetration of the Buck fascia and the tunica albuginea by the tumor permits invasion of the vascular corpora.  `, 
        `  Cancer cells reach the contralateral inguinal region because of lymphatic cross-communications at the base of the penis.   `],
        optionStyleType: `st-lower-alpha`,
        answer: [1],
        ansText: `Rationale: <b>Patients with cancer of the penis, more than patients with other types of cancer, seem to delay seeking medical attention.</b> In large series, from 15% to 50% of patients have been noted to delay medical care for more than a year.  `,
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
     {
        q: `  Before a treatment plan for penile cancer is initiated, which of the following is TRUE?  `,
        q2: ``,
        q3: [],
        option: [`  Adequate biopsies to determine stage are unimportant because all patients should be treated with amputation.  `, 
        `  Radiologic studies play no role in decision making.   `, 
        `  Tumor HPV status is critical for determining primary tumor therapy.   `, 
        `  Tumor stage, grade, and vascular invasion status all provide prognostically important information. `, 
        `  No disfiguring therapy is indicated, because spontaneous remissions have been noted in approximately 10% of cases.   `],
        optionStyleType: `st-lower-alpha`,
        answer: [3],
        ansText: `Rationale: Confirmation of the diagnosis of carcinoma of the penis, an assessment of the structure(s) invaded, and tumor grade by the combination of an adequate biopsy, and complete clinical assessment are beneficial before the initiation of definitive therapy. Biopsy can be performed as a frozen section immediately before definitive therapy in some cases.  `,
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
     {
        q: `  Which of the following statements is TRUE regarding the natural history of penile cancer?  `,
        q2: ``,
        q3: [],
        option: [` Metastases from the primary tumor often involve lung, liver, or bone as initial sites.   `, 
        `  Lymphatic drainage from the primary tumor is ipsilateral alone in most cases.   `, 
        `  Metastasis often initially involves spread from the corpora cavernosa to the pelvic lymph nodes.   `, 
        `  Metastasis initially involves inguinal lymph nodes beneath the fascia lata. `, 
        `   Metastasis initially involves inguinal lymph nodes above the fascia lata.  `],
        optionStyleType: `st-lower-alpha`,
        answer: [4],
        ansText: `Rationale: `,
        state: `notAnswered`,
        userAnswered: []
    ,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`        ,
        type: `MCSS`},
     {
        q: `  Which of the following statements concerning hypercalcemia in patients with penile cancer is TRUE?  `,
        q2: ``,
        q3: [],
        option: [` It is more commonly due to massive bone metastases than bulky soft tissue metastases.   `, 
        `   It is often related to uremia due to ureteral obstruction.  `, 
        `  It may be due to the action of parathyroid hormone-like substances released from the tumor.   `, 
        ` It is related to the action of osteoblasts on bone formation.  `, 
        `  It is managed with aggressive diuretic administration as first-line therapy.   `],
        optionStyleType: `st-lower-alpha`,
        answer: [2],
        ansText: `Rationale: Parathyroid hormone and related substances may be produced by both tumor and metastases that activate osteoclastic bone resorption. `,
        state: `notAnswered`,
        userAnswered: []
    ,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`        ,
        type: `MCSS`},
     {
        q: `  The following statements are true regarding imaging tests in patients with penile cancer EXCEPT:  `,
        q2: ``,
        q3: [],
        option: [` Both ultrasonography and MRI lack sensitivity for the detection of corpus cavernosum involvement.   `, 
        `  computed tomography (CT) is not an appropriate test for determining primary tumor stage.   `, 
        `  CT may be beneficial in detecting enlarged inguinal nodes in obese patients or those who have had prior inguinal therapy.   `, 
        `  lymphangiography can detect abnormal architecture in normal-sized lymph nodes. `, 
        `    inguinal palpation is preferred to CT and lymphangiography for determining inguinal nodal status. `],
        optionStyleType: `st-lower-alpha`,
        answer: [0],
        ansText: `Rationale: The sensitivity of ultrasonography for detecting cavernosum invasion was 100% in one study. This study confirmed the value of ultrasonography in assessing the primary tumor also reported by other investigators. For lesions suspected of invading the corpus cavernosum, both ultrasonography and contrast-enhanced MRI may provide unique information, especially when organ-sparing surgery is considered.   `,
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
     {
        q: ` According to the eighth edition of the American Joint Committee on Cancer Staging System (i.e., tumor, node, metastases [TNM]) for penile cancer, which of the following statements is TRUE?   `,
        q2: ``,
        q3: [],
        option: [`  Primary tumor stage is based on the size of the primary lesion.  `, 
        `  Lymph node stage is based in part on the size of an involved node.   `, 
        `  Stage T2 tumors invade the corpus spongiosum but not the cavernosum.   `, 
        ` Proven pelvic nodal metastases as well as bilateral inguinal metastases are both designated as stage pN3.  `, 
        `  Stage T1a tumors involve the dartos fascia and exhibit perineural invasion in less than 10% of the specimen.   `],
        optionStyleType: `st-lower-alpha`,
        answer: [2],
        ansText: `Rationale: According to the 8th edition, staging system invasion of the corpus cavernosum is now designated T3, indicating a worse prognosis than tumors involving the spongiosum alone.  `,
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
     {
        q: `   What is the strongest prognostic factor for survival in penile cancer? `,
        q2: ``,
        q3: [],
        option: [` The presence of lymph node metastasis   `, 
        `   The grade of the primary tumor  `, 
        `  The stage of the primary tumor   `, 
        ` Vascular invasion presence in the primary tumor  `, 
        `  The extent of lymph node metastasis   `],
        optionStyleType: `st-lower-alpha`,
        answer: [4],
        ansText: `Rationale: The presence and extent of metastasis to the inguinal region are the most important prognostic factors for survival in patients with squamous penile cancer.  `,
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
     {
        q: `   Criteria for curative surgical resection (&gt;70% 5-year survival) in patients treated for lymph node metastasis include all of the following EXCEPT: `,
        q2: ``,
        q3: [],
        option: [` no more than two positive inguinal lymph nodes.   `, 
        `  no positive pelvic lymph nodes.   `, 
        `  absence of extranodal extension of cancer.   `, 
        ` unilateral metastasis.  `, 
        `   a single metastasis of only 6 cm.  `],
        optionStyleType: `st-lower-alpha`,
        answer: [4],
        ansText: `Rationale: Pathologic criteria associated with long-term survival after attempted curative surgical resection of inguinal metastases (i.e., &gt;70% 5-year survival) include (1) minimal nodal disease (up to two involved nodes in most series), (2) unilateral involvement, (3) no evidence of extranodal extension of cancer, and (4) the absence of pelvic nodal metastases. A lymph node larger than 4 cm is often associated with extranodal extension of cancer.   `,
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
     {
        q: `  Surgical staging of the inguinal region is strongly considered under all of the following conditions EXCEPT:  `,
        q2: ``,
        q3: [],
        option: [`  palpable adenopathy.  `, 
        `  stage T1b or greater primary tumor.   `, 
        `  presence of vascular invasion in primary tumor.   `, 
        ` presence of predominantly high-grade cancer in primary tumor.  `, 
        `   stage Ta tumors.  `],
        optionStyleType: `st-lower-alpha`,
        answer: [4],
        ansText: `Rationale: Tumor histologic type associated with little or no risk for metastasis includes those patients with primary tumors exhibiting (1) carcinoma in situ or (2) verrucous carcinoma.  `,
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: ` Strategies attempting to minimize the morbidity of inguinal staging in patients with no palpable adenopathy include all the following EXCEPT:   `,
        q2: ``,
        q3: [],
        option: [` superficial inguinal lymph node dissection.   `, 
        `  modified complete inguinal dissection.   `, 
        `  standard ilioinguinal dissection.   `, 
        ` laparoscopic and robotic inguinal node dissection.  `, 
        `  dynamic sentinel node biopsy.   `],
        optionStyleType: `st-lower-alpha`,
        answer: [2],
        ansText: `Rationale: In patients with no evidence of palpable adenopathy who are selected to undergo inguinal procedures by virtue of adverse prognostic factors within the primary tumor, the goal is to define whether metastases exist with minimal morbidity for the patient. A variety of treatment options for this purpose have been reported and include (1) dynamic sentinel node biopsy, (2) superficial dissection, (3) modified complete dissections, and (4) laparoscopic and robotic approaches.  `,
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `  Which of the following inguinal staging procedure(s) is/are considered standard for detecting microscopic metastases while limiting both morbidity and false-negative findings?  `,
        q2: ``,
        q3: [],
        option: [` Sentinel lymph node biopsy   `, 
        `  Superficial inguinal dissection   `, 
        `  Dynamic sentinel lymph node biopsy   `, 
        ` All of the above  `, 
        `   b and c only  `],
        optionStyleType: `st-lower-alpha`,
        answer: [4],
        ansText: `Rationale: Both superficial inguinal lymph node dissection and dynamic sentinel lymph node biopsy (latter at experienced centers) are considered standard procedures for determining the presence of inguinal microscopic metastases. Biopsies directed to a specific anatomic area (i.e., sentinel lymph node biopsy) can be unreliable in identifying microscopic metastasis and are no longer recommended.   `,
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
      
      {
        q: ` For patients with proven unilateral metastasis involving two or more lymph nodes at presentation, all of the following surgical considerations are true EXCEPT:   `,
        q2: ``,
        q3: [],
        option: [` ipsilateral ilioinguinal lymphadenectomy should be performed   `, 
        `  a contralateral staging procedure is not indicated   `, 
        `  a contralateral staging procedure is indicated   `, 
        `  both a superficial dissection and a deep ipsilateral dissection are performed `, 
        `  ipsilateral pelvic dissection provides useful prognostic information   `],
        optionStyleType: `st-lower-alpha`,
        answer: [1],
        ansText: `Rationale: Support for a bilateral procedure is based on the finding of bilateral lymphatic drainage from the primary site in the majority of cases and contralateral metastases in more than 50% of patients so treated in some series, even if the contralateral nodal region was negative to palpation. `,
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
      
      {
        q: `  Adjuvant or neoadjuvant chemotherapy should be considered in addition to surgery for all of the following EXCEPT:  `,
        q2: ``,
        q3: [],
        option: [`  single pelvic nodal metastasis  `, 
        `  extranodal extension of cancer   `, 
        `  fixed inguinal masses   `, 
        `  two unilateral inguinal nodes with focal metastases `, 
        `  single 6-cm inguinal lymph node   `],
        optionStyleType: `st-lower-alpha`,
        answer: [3],
        ansText: `Rationale: For patients requiring ilioinguinal lymphadenectomy because of the presence of metastases, adjuvant chemotherapy should be considered for those exhibiting more than two positive lymph nodes, extranodal extension of cancer, or pelvic nodal metastasis. Reports from one center further confirmed the value of adjuvant chemotherapy. Of 25 node-positive patients treated with adjuvant combination vincristine-bleomycin-methotrexate chemotherapy, 82% survived 5 years, compared with 37% of 31 patients treated with surgery alone.  `,
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
      
      {
        q: `  The majority of penile cancers are histologically:  `,
        q2: ``,
        q3: [],
        option: [` melanoma   `, 
        `  bowenoid papulosis.   `, 
        `  squamous cell carcinoma   `, 
        `   epidemic Kaposi sarcoma.`, 
        `   verrucous carcinoma.  `],
        optionStyleType: `st-lower-alpha`,
        answer: [2],
        ansText: `Rationale: The majority of tumors of the penis are squamous cell carcinomas demonstrating keratinization, epithelial pearl formation, and various degrees of mitotic activity.  `,
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `  Which of the following chemotherapeutic agents used in combination therapy for penile cancer has been associated with significant pulmonary toxicity?  `,
        q2: ``,
        q3: [],
        option: [` Bleomycin   `, 
        `   Methotrexate  `, 
        ` Cisplatin    `, 
        `  5-Fluorouracil (5-FU) `, 
        `   Paclitaxel  `],
        optionStyleType: `st-lower-alpha`,
        answer: [0],
        ansText: `Rationale: Response rates of bleomycin, whether as a single agent or in combination with other agents, has not been shown to be superior to cisplatin alone, but has been associated with significant pulmonary toxicity and death in several series of patients treated for metastatic penile cancer.  `,
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: ` Indications for radiation therapy as primary treatment for penile cancer include which of the following?   `,
        q2: ``,
        q3: [],
        option: [` Young, sexually active patient with a small lesion   `, 
        `  Patient refuses surgery   `, 
        `   Patient with distant or inoperable metastases who requires local control to the primary tumor  `, 
        `  None of the above `, 
        `    a, b, and c `],
        optionStyleType: `st-lower-alpha`,
        answer: [4],
        ansText: `Rationale: Radiation therapy may be considered in a select group of patients: (1) young individuals presenting with small (2 to 4 cm), superficial, exophytic, noninvasive lesions on the glans or coronal sulcus; (2) patients who refuse surgery as an initial form of treatment; and (3) patients with distant or inoperable metastases who require local therapy and express a desire to retain the penis.   `,
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: ` Primary penile melanoma is thought to be rare for what reason?   `,
        q2: ``,
        q3: [],
        option: [`  Penile skin is protected from exposure to the sun.  `, 
        `  Keratin content in penile skin is decreased.   `, 
        `   Penile blood supply precludes such tumor development.  `, 
        ` Effective topical chemotherapy exists.  `, 
        `   None of the above.  `],
        optionStyleType: `st-lower-alpha`,
        answer: [0],
        ansText: `Rationale: <b>Melanoma and basal cell carcinoma rarely occur on the penis, presumably because the organ’s skin is protected from exposure to the sun.</b>  `,
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `  Lymphomatous infiltration of the penis is most likely secondary to which condition?  `,
        q2: ``,
        q3: [],
        option: [` Autoimmune disorder   `, 
        `    Diffuse disease `, 
        `  Metastasis from a distant primary tumor    `, 
        `  Chronic infection`, 
        `   Previous venereal infection  `],
        optionStyleType: `st-lower-alpha`,
        answer: [1],
        ansText: `Rationale: When lymphomatous infiltration of the penis is diagnosed, a thorough search for systemic disease is necessary.  `,
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
     {
        q: `  What is the most frequently encountered sign of metastatic involvement of the penis?  `,
        q2: ``,
        q3: [],
        option: [` Pain   `, 
        `  Urethral discharge   `, 
        `   Ecchymoses  `, 
        `  Priapism `, 
        `   Preputial swelling  `],
        optionStyleType: `st-lower-alpha`,
        answer: [3],
        ansText: `Rationale: The most frequent sign of penile metastasis is priapism; penile swelling, nodularity, and ulceration have also been reported.  `,
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
     {
        q: `  Which of the following features of Buschke-Löwenstein tumor characterizes it as different from condyloma acuminatum?  `,
        q2: ``,
        q3: [],
        option: [` Propensity for early distant metastasis   `, 
        `  Disruption of the rete pegs   `, 
        `   Loss of pigmentation  `, 
        `  Autoamputation `, 
        `   Invasion and destruction of adjacent tissues by compression  `],
        optionStyleType: `st-lower-alpha`,
        answer: [4],
        ansText: `Rationale: The Buschke-Löwenstein tumor differs from condyloma acuminatum in that condylomata, regardless of size, always remain superficial and never invade adjacent tissue. Buschke-Löwenstein tumor displaces, invades, and destroys adjacent structures by compression. Aside from this unrestrained local growth, it demonstrates no signs of malignant change on histologic examination and does not metastasize.  `,
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
     {
        q: `  All of the following statements are true regarding the management of bulky inguinal metastases in patients with squamous penile carcinoma EXCEPT:  `,
        q2: ``,
        q3: [],
        option: [`cross-sectional imaging plays an important role in establishing the extent of disease.    `, 
        `  neoadjuvant chemotherapy with a cisplatin-containing regimen is recommended.   `, 
        `  post-chemotherapy surgical consolidation to achieve disease-free status is recommended following an objective response to chemotherapy.   `, 
        ` among patients who progress through chemotherapy, salvage surgery can often result in prolonged survival.  `, 
        `   chemo-radiation for tumor cytoreduction prior to surgical resection or as definitive treatment may play a role.  `],
        optionStyleType: `st-lower-alpha`,
        answer: [3],
        ansText: `Rationale: Surgery among patients who do not respond to chemotherapy is commonly associated with death due to either rapidly occurring locoregional recurrence or distant metastases  `,
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
     {
        q: `  Small lesions of erythroplasia of Queyrat may be successfully treated with which of the following?  `,
        q2: ``,
        q3: [],
        option: [`  Topical 5% 5-FU  `, 
        `  Neodymium:yttrium-aluminum-garnet (Nd:YAG) laser   `, 
        `  Local excision   `, 
        ` Imiquimod  `, 
        `   All of the above  `],
        optionStyleType: `st-lower-alpha`,
        answer: [4],
        ansText: `Rationale: When lesions are small and noninvasive, local excision, which spares penile anatomy and function, is satisfactory. Circumcision will adequately treat preputial lesions. Fulguration may be successful but often results in recurrences. Both Topical 5-FU as the 5% base and Imiquimod causes denudation of malignant and premalignant areas while preserving normal skin. There are also reports of successful treatment with Nd:YAG laser.  `,
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},


      

      
];
