var quiz = [
  {
    q: `  A 23-year old man presents after undergoing transscrotal orchiectomy for presumed hydrocele. Pathologic examination reveals embryonal carcinoma with vascular invasion. Serum levels of tumor markers and results of physical examination and computed tomography (CT) of the chest, abdomen, and pelvis were normal. Which of the following approaches is most appropriate?  `,
    q2: ``,
    q3: [],
    option: [
      `   Observation`,
      `  Retroperitoneal lymph node dissection (RPLND)  `,
      ` RPLND plus excision of scrotal scar and remnant cord   `,
      `  RPLND plus scrotectomy and inguinal lymph node dissection `,
      `  RPLND plus scrotal and inguinal radiation  `,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [2],
    ansText: `Rationale: In the setting of scrotal contamination and clinical stage I disease, the patient is best managed with RPLND and wide excision of the scrotal scar. The remainder of the cord should also be removed. Observation is not optimal because of the presence of vascular invasion and scrotal contamination.  `,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `  Late relapse is a feature most commonly associated with  `,
    q2: ``,
    q3: [],
    option: [
      `  seminoma `,
      `  yolk sac tumor.  `,
      `  embryonal carcinoma.  `,
      ` choriocarcinoma  `,
      `  teratoma  `,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [4],
    ansText: `Rationale: Late relapse of germ cell tumor (GCT) after definitive therapy is defined as recurrence more than 2 years after completion of therapy and occurring without evidence of disease. Teratoma is the most common histologic subtype involved in cases of late relapse. This is likely due to its combination of prolonged doubling time and chemotherapy resistance.   `,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: ` A 25-year-old man with a stage IIC nonseminomatous germ cell tumor (NSGCT) has completed primary platinum-based chemotherapy. Tumor marker levels have normalized according to appropriate half-life, and he has undergone bilateral postchemotherapy RPLND. Final pathologic analysis reveals a focus of yolk sac tumor. Appropriate therapy at this point is   `,
    q2: ``,
    q3: [],
    option: [
      `  careful observation. `,
      ` radiation therapy.   `,
      `  two additional cycles of platinum-based chemotherapy.  `,
      `  four additional cycles of platinum-based chemotherapy. `,
      `  reexploration in 6 weeks.  `,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [2],
    ansText: `Rationale: The patient’s prognosis is related to serum tumor marker level at the time of RPLND, prior treatment burden, and the pathologic findings for the resected specimen. If viable GCT is present at any site but all disease is completely resected, two additional cycles provide survival benefit in this subset of patients. Einhorn reported only 2 long-term survivors of 22 patients (9%) with completely resected viable GCT after cisplatin, bleomycin, and vinblastine chemotherapy if additional postoperative chemotherapy was not given. Fox and colleagues reported that 70% of patients with completely resected viable GCT after primary chemotherapy followed by two cycles of postoperative chemotherapy remained disease free compared with none of 7 patients without additional chemotherapy.  `,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `  A 20-year-old man with clinical stage I NSGCT undergoes laparoscopic RPLND. During surgery, a 2-cm lymph node is encountered. Which of the following is the most appropriate next step?  `,
    q2: ``,
    q3: [],
    option: [
      ` Abort the procedure and administer chemotherapy.  `,
      `Convert to an open procedure.    `,
      `  Perform a unilateral template dissection and administer chemotherapy.  `,
      `  Continue the procedure and perform a full bilateral dissection. `,
      `  None of the above.  `,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [3],
    ansText: `Rationale: Whenever a suspicious lymph node is identified, a full bilateral dissection should be performed. Chemotherapy will not compensate for an inadequate retroperitoneal dissection.   `,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `   The most common cause of open conversion during laparoscopic RPLND is `,
    q2: ``,
    q3: [],
    option: [
      ` intraoperative discovery of bulky lymphadenopathy.  `,
      `  failure to progress.  `,
      ` bowel injury.   `,
      ` hypercapnia  `,
      `  bleeding  `,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [4],
    ansText: `Rationale: The most common reason for conversion to an open procedure is uncontrollable bleeding, and vascular injury is cited as the most common intraoperative complication. In experienced hands, this occurs less than 5% of the time.  `,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `   Two weeks after laparoscopic RPLND, a patient complains of abdominal distention and emesis. CT reveals ascites. Diagnostic paracentesis confirms the diagnosis of chylous ascites. The next best step is `,
    q2: ``,
    q3: [],
    option: [
      ` reassurance and discharge.  `,
      `  reoperation to identify and treat the source of lymphatic leak.  `,
      `  placement of a peritoneal drain and initiation of a low-fat diet.  `,
      ` initiation of somatostatin.  `,
      ` hydration and initiation of a low-fat diet.   `,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [4],
    ansText: `Rationale: Chylous ascites is a devastating complication that occurs less than 2% of the time after primary laparoscopic (and open) RPLND. Initiation of a low-fat diet, hydration, and drainage of the fluid is usually the first step in management. Reoperation is considered only when all other options have been exhausted.   `,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `  A 20-year-old man undergoes laparoscopic RPLND after right radical orchiectomy for an NSGCT. All of the following regions should be dissected clear of all lymphatic tissue EXCEPT which?  `,
    q2: ``,
    q3: [],
    option: [
      ` Right spermatic cord  `,
      ` Paracaval region   `,
      `  Interaortocaval region  `,
      `  Retrocrural region `,
      `  Precaval region  `,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [3],
    ansText: `Rationale: The superior boundary of a dissection template does not include lymph nodes superior to the renal hilum. `,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },

  {
    q: `  Potential advantages to laparoscopic compared with open RPLND include all of the following EXCEPT which?  `,
    q2: ``,
    q3: [],
    option: [
      ` Improved cosmesis  `,
      `  Shorter convalescence  `,
      `  Improved disease-free survival  `,
      `   Shorter interval to chemotherapy when necessary`,
      `   Faster return to normal activities `,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [2],
    ansText: `Rationale: No study has demonstrated any difference in disease-free survival comparing open or laparoscopic approaches with node dissection.  `,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
];
