var quiz = [
  {
    q: `<!--1. -->Ischemic priapism is a persistent erection marked by each of the following clinical and pathophysiologic characteristics EXCEPT:`,
    q2: ``,
    q3: [],
    option: [
      `<!--a. -->rigidity of the corpora cavernosa.`,
      `<!--b. -->bright red corporal blood.`,
      `<!--c. -->hypoxic and acidotic corporal environment.`,
      `<!--d. -->painful rigidity.`,
      `<!--e. -->thrombus within the sinusoidal spaces.`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [1],
    ansText: `Rationale: Ischemic priapism is a persistent erection marked by rigidity of the corpora cavernosa and little or no cavernous arterial inflow. <b>In ischemic priapism there are time-dependent changes in the corporal metabolic environment with progressive hypoxia, hypercarbia, and acidosis. The patient typically complains of penile pain after 6 to 8 hours, and examination reveals a rigid erection.</b> After 48 hours, thrombus can be found in the sinusoidal spaces and smooth muscle necrosis with fibroblast-like cell transformation is evident.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `<!--2. -->Each of the following are etiologies typically associated with ischemic priapism EXCEPT:`,
    q2: ``,
    q3: [],
    option: [
      `<!--a. -->sickle cell disease (SCD).`,
      `<!--b. -->straddle injury.`,
      `<!--c. -->cocaine use.`,
      `<!--d. -->spider bite.`,
      `<!--e. -->pharmacologic erection therapy.`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [1],
    ansText: `Rationale: <b>Nonischemic priapism is much rarer than ischemic priapism, and the etiology is largely attributed to trauma.</b> Forces may be blunt or penetrating, resulting in laceration of the cavernous artery or one of its branches within the corpora. The etiology most commonly reported is a straddle injury to the crura.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `<!--3. -->SCD is a risk factor for ischemic priapism; the pathophysiologic mechanisms include each of the following EXCEPT:`,
    q2: ``,
    q3: [],
    option: [
      `<!--a. -->decreased content of hemoglobin S (HgbS) in the plasma.`,
      `<!--b. -->the polymerization of HgbS when deoxygenated.`,
      `<!--c. -->scavenging of nitric oxide (NO).`,
      `<!--d. -->arginine catabolism removing substrate for NO synthesis.`,
      `<!--e. -->adhesive interactions among sickle cells, endothelial cells, and leukocytes.`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [0],
    ansText: `Rationale: The clinical features are seen in homozygous SCD patients: chronic hemolysis, vascular occlusion, tissue ischemia, and end-organ damage. HgbS polymerizes when deoxygenated, injuring the sickle erythrocyte, activating a cascade of hemolysis and vaso-occlusion. Membrane damage results in dense sickling of red cells, causing adhesive interactions among sickle cells, endothelial cells, and leukocytes. Hemolysis releases hemoglobin into the plasma. Free Hgb reacts with NO to produce methemoglobin and nitrate. <b>This is a scavenging reaction; the vasodilator NO is oxidized to inert nitrate.</b> Sickled erythrocytes release arginase-I into blood plasma, which converts <small>l</small>-arginine into ornithine, effectively removing substrate for NO synthesis. Oxidant radicals further reduce NO bioavailability. <b>The combined effects of NO scavenging and arginine catabolism result in a state of NO resistance and insufficiency termed <i>hemolysis-associated endothelial dysfunction.</i></b> Therapeutic interventions include transfusion to decrease the relative concentrations of HgbS in the plasma.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `<!--4. -->Prolonged erection in males 40 years of age and older is usually attributed to:`,
    q2: ``,
    q3: [],
    option: [
      `SCD.`,
      `<!--b. -->hematologic malignancy.`,
      `<!--c. -->erectile dysfunction (ED) pharmacotherapy.`,
      `<!--d. -->prostate cancer.`,
      `<!--e. -->testosterone supplementation.`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [2],
    ansText: `Rationale: The introduction of intracavernous pharmacotherapy approximately two decades ago led to a pronounced increase in the incidence of prolonged erection and true priapism. Prolonged erection is more commonly reported than is priapism, following therapeutic or diagnostic injection of intracavernous vasoactive medications. In many communities patients receiving intracavernous medications for ED will outnumber patients with SCD. The majority of men requiring treatment for ED are middle-aged to older men. In worldwide clinical trials of the Alprostadil Study Group, prolonged erection (defined as 4 to 6 hours) was 5%, and priapism (&gt; 6 hours) was described in 1% of subjects. In papaverine/phentolamine/alprostadil intracavernous injection programs, prolonged erections have been reported in 5% to 35% of patients.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `<!--5. -->Case reports have documented prolonged erections and, rarely, priapism in men by using phosphodiesterase type 5 (PDE5) inhibitor therapies. Associated risks for prolonged erection/priapism include each of the following EXCEPT:`,
    q2: ``,
    q3: [],
    option: [
      `<!--a. -->daily dosing.`,
      `<!--b. -->combination with intracavernous injection.`,
      `<!--c. -->history of penile trauma.`,
      `<!--d. -->psychotropic medications.`,
      `<!--e. -->narcotic use.`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [0],
    ansText: `Rationale: <!--<b>a. Daily dosing.</b>--> Few cases reports have documented priapism following PDE5 inhibitor therapy. <b>These reports suggest that men with the following conditions were at increased risk for priapism: SCD, spinal cord injury, men who used a PDE5 inhibitor recreationally, men who used a PDE5 inhibitor in combination with intracavernous injection, men with a history of penile trauma, men on psychotropic medications, and men abusing narcotics.</b> Tadalafil, 5 mg daily dosing caused no priapism in a phase II clinical study of 281 men with history of lower urinary tract symptoms secondary to benign prostatic hyperplasia (BPH) for 6 weeks, followed by dosage escalation to 20 mg once daily for 6 weeks.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `<!--6. -->The associations and pathophysiology of high-flow priapism include each of the following EXCEPT:`,
    q2: ``,
    q3: [],
    option: [
      `<!--a. -->straddle injury.`,
      `<!--b. -->coital trauma.`,
      `<!--c. -->birth canal injury to the newborn male.`,
      `<!--d. -->cold-knife urethrotomy.`,
      `<!--e. -->hemodialysis.`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [4],
    ansText: `Rationale: <b>Nonischemic priapism is much rarer than ischemic priapism, and the etiology is largely attributed to trauma. Forces may be blunt or penetrating, resulting in laceration of the cavernous artery or one of its branches within the corpora.</b> The etiology most commonly reported is a straddle injury to the crura. Other mechanisms include coital trauma, kicks to the penis or perineum, pelvic fractures, birth canal trauma to the newborn male, needle lacerations, complications of penile diagnostics, and vascular erosions complicating metastatic infiltration of the corpora. Although accidental blunt trauma is the most common etiology, high-flow priapism has been described following iatrogenic injury: cold-knife urethrotomy, Nesbitt corporoplasty, and deep dorsal vein arterialization. Any mechanism that lacerates a cavernous artery or arteriole can produce unregulated pooling of blood in sinusoidal space with consequent erection.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `<!--7. -->The critical pathologic change occurring in the cavernosal tissue at 4 hours after the onset of ischemic priapism is:`,
    q2: ``,
    q3: [],
    option: [
      `<!--a. -->irreversible cavernous damage and ED.`,
      `<!--b. -->the beginning of glucopenia.`,
      `<!--c. -->the beginning of hypercoagulable thrombotic conditions.`,
      `<!--d. -->the deterioration of cavernous smooth muscle contractile responses.`,
      `<!--e. -->cavernous fibrosis.`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [3],
    ansText: `Rationale: In ischemic priapism there are time-dependent changes in the corporal metabolic environment with progressive hypoxia, hypercarbia, and acidosis. In vitro studies have demonstrated that when corporal smooth muscle strips are exposed to a hypoxic condition, α-adrenergic stimulation fails to induce corporal smooth muscle contraction. Histologically, by 12 hours corporal specimens show interstitial edema, progressing to destruction of the sinusoidal endothelium, exposure of the basement membrane, and thrombocyte adherence at 24 hours.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `<!--8. -->The NO/cyclic guanosine monophosphate (cGMP) signaling pathway is implicated in the pathogenesis of priapism on the basis of scientific work showing:`,
    q2: ``,
    q3: [],
    option: [
      `<!--a. -->guanylate cyclase activity upregulation.`,
      `<!--b. -->guanylate cyclase activity downregulation.`,
      `<!--c. -->NO synthase activity upregulation.`,
      `<!--d. -->PDE5 activity upregulation.`,
      `<!--e. -->PDE5 activity downregulation.`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [4],
    ansText: `Rationale: <b>Recent scientific advances have shown that priapism is associated with decreased PDE5 functional regulation in the penis.</b> The relative lack of this molecular factor needed for controlling chemical signaling of penile erection accounts for stuttering and ischemic priapism in sickle cell patients. Experimental models of corpus cavernosum smooth muscle cells suggest that the cyclic nucleotide cGMP is produced in low steady-state amounts under the influence of priapism-related destruction of the vascular endothelium and thus reduced endothelial NO activity. This situation downregulates the set point of PDE5 function, secondary to altered cGMP-dependent feedback control mechanisms. When NO is neuronally produced in response to erectogenic stimulus or during sleep-related erectile activity, cGMP production surges in a manner that leads to excessive erectile tissue relaxation because of basally insufficient functional PDE5 to degrade the cyclic nucleotide.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `<!--9. -->An adolescent with SCD presents with a 6-hour erection. Initial cavernous blood gas results show P<small>o</small><sub>2</sub> 30 mm Hg, P<small>co</small><sub>2</sub> 60 mm Hg, and pH 7.25. The first therapeutic step should be:`,
    q2: ``,
    q3: [],
    option: [
      `<!--a. -->oral terbutaline.`,
      `<!--b. -->oral pseudoephedrine.`,
      `<!--c. -->intracavernous aspiration.`,
      `<!--d. -->exchange transfusion.`,
      `<!--e. -->distal surgical shunt.`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [3],
    ansText: `Rationale: The history and blood gases define an ischemic priapism event, which warrants immediate attempts at decompression/aspiration of the corpora cavernosa. <b>In SCD, concurrent systemic treatments may be offered, but relief of the penile ischemia should be pursued aggressively. Aspiration should be repeated until no more dark blood can be seen coming out of the corpora and bright red blood is obtained.</b> This process decreases the intracavernous pressure, relieves pain, and resuscitates the corporal environment, removing anoxic, acidotic, and hypercarbic blood.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `<!--10. -->The characteristic blood flow defect of ischemic priapism found on color duplex ultrasonography is:`,
    q2: ``,
    q3: [],
    option: [
      `<!--a. -->normal cavernosal artery inflow.`,
      `<!--b. -->increased cavernosal artery inflow.`,
      `<!--c. -->decreased or absent cavernosal artery inflow.`,
      `<!--d. -->arteriovenous blush.`,
      `<!--e. -->sinusoidal fistula.`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [2],
    ansText: `Rationale: In presentations of ischemic priapism, minimal or absent blood flow in the cavernosal arteries is found using color Doppler ultrasonography. CDU is an adjunct to the corporal aspirate in differentiating ischemic from nonischemic priapism. Patients with ischemic priapism will have no blood flow in the cavernous arteries; the return of the cavernous artery waveform will accompany successful detumescence. Patients with nonischemic priapism have normal to high blood-flow velocities in the cavernous arteries; an effort should be made to localize the characteristic blush of color emanating from flow signal of the disrupted cavernous artery or arteriolar-sinusoidal fistula.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `<!--11. -->After initial intracavernous treatment for ischemic priapism, blood gas sampling produces an equivocal mixed-venous blood result. Priapism resolution is best confirmed by:`,
    q2: ``,
    q3: [],
    option: [
      `<!--a. -->color duplex ultrasonography.`,
      `<!--b. -->penile scintigraphy.`,
      `<!--c. -->corpus cavernosography.`,
      `<!--d. -->penile arteriography.`,
      `<!--e. -->pelvic computed tomography scan.`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [0],
    ansText: `Rationale: This tool is the most reliable and least invasive imaging technique to differentiate ischemic from nonischemic priapism. <b>CDU should always be considered in the evaluation of a full or partial erection after treatments for ischemic priapism. The differential diagnosis includes resolved ischemia with persistent tenderness and penile edema, persistent ischemia, or conversion to a high-flow state.</b>`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `<!--12. -->After a second session of intracavernous treatment consisting of aspiration/irrigation with phenylephrine administration, the priapic penis remains turgid. Cavernosal blood gas results are P<small>o</small><sub>2</sub> 40 mm Hg, P<small>co</small><sub>2</sub> 50 mm Hg, and pH 7.35. The next step should be:`,
    q2: ``,
    q3: [],
    option: [
      `observation.`,
      `<!--b. -->oral sympathomimetic.`,
      `<!--c. -->repeat intracavernous treatment.`,
      `<!--d. -->distal surgical shunt.`,
      `<!--e. -->proximal surgical shunt.`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [0],
    ansText: `Rationale: These blood gas results are consistent with normal mixed venous blood. The turgid penis may be due to tissue edema. Observation is appropriate at this time.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `<!--13. -->Phenylephrine is the preferred sympathomimetic used in the treatment of ischemic priapism because of its:`,
    q2: ``,
    q3: [],
    option: [
      `<!--a. -->α<sub>1</sub>-selective activity.`,
      `<!--b. -->α<sub>1</sub> and α<sub>2</sub> activity.`,
      `<!--c. -->β<sub>1</sub>-selective activity.`,
      `<!--d. -->β<sub>2</sub>-selective activity.`,
      `<!--e. -->combined α and β activities.`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [0],
    ansText: `Rationale: According to American Urological Association Guidelines, aspiration followed by intracavernous injection of sympathomimetic drugs is the standard of care in the medical treatment of ischemic priapism. Sympathomimetic pharmacotherapies (phenylephrine, etilefrine, ephedrine, epinephrine, norepinephrine, metaraminol) cause smooth muscle contraction in the corpora. Phenylephrine is a selective α<sub>1</sub>-adrenergic receptor agonist, with minimal β-mediated inotropic and chronotropic cardiac effects. There are no comparative trials of sympathomimetic injectables in the management of priapism.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `<!--14. -->The best indication for arterial embolization in the management of high-flow priapism is:`,
    q2: ``,
    q3: [],
    option: [
      `<!--a. -->unlikely spontaneous resolution.`,
      `<!--b. -->failure of sympathomimetic therapy.`,
      `<!--c. -->reduction of recurrent priapism risk.`,
      `<!--d. -->reduction of subsequent ED risk.`,
      `<!--e. -->patient preference to intervene.`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [4],
    ansText: `Rationale: <b>Nonischemic priapism should generally be managed by observation.</b> Arterial priapism is not an emergency. <b>Spontaneous resolution or response to conservative therapy has been reported in up to 62% of published series.</b> Persistent partial erection from high-flow priapism may continue from months to years. There are no comparative outcome studies of intervention versus conservative management, but there are sufficient case descriptions in children to recommend initial watchful waiting. Adult patients demanding immediate relief can be offered selective arterial embolization.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `<!--15. -->Persistent penile rigidity after a technically successful proximal surgical shunt procedure in a patient with a 72-hour episode of ischemic priapism is an indication for:`,
    q2: ``,
    q3: [],
    option: [
      `<!--a. -->observation.`,
      `<!--b. -->gonadotropin-releasing hormone agonist therapy.`,
      `<!--c. -->pudendal artery ligation.`,
      `<!--d. -->distal surgical shunt.`,
      `<!--d. -->distal surgical shunt.`,
      `<!--e. -->penile prosthesis surgery.`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [4],
    ansText: `Rationale: <b>Unfortunately, the natural history of untreated ischemic priapism or priapism refractory to interventions is severe fibrosis, penile length loss, and complete ED.</b> The exact time point when penile prosthesis becomes a reasonable option is unclear, but most series describe complete ED in men who have had ischemic priapism for 36 to 72 hours. The advantages of early penile implantation in the acute management of ischemic priapism are preservation of penile length and a technically easier implantation; delayed implantation is technically challenging due to corporal fibrosis.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `<!--16. -->The mother of a child with SCD complains that her son has recently been awakening with erections lasting 3 to 4 hours. She is concerned that similar occurrences have been a warning sign for a major priapism. All of the following are appropriate management options EXCEPT:`,
    q2: ``,
    q3: [],
    option: [
      `<!--a. -->trial of nightly oral sympathomimetic drug.`,
      `<!--b. -->trial of low-dosage, daily PDE5 inhibitor.`,
      `<!--c. -->a gonadotropin-releasing hormone agonist or antiandrogen.`,
      `<!--d. -->intracavernous injection of phenylephrine in the morning.`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [2],
    ansText: `Rationale: The goals of managing stuttering ischemic priapism are prevention of future episodes, preservation of erectile function, and reducing the trauma to the patient from priapism management. A trial of daily oral sympathomimetic therapy, a trial of oral PDE5 inhibitor therapy, or intracavernous injection of phenylephrine should be considered in the management of children and adults with stuttering ischemic priapism associated with hemoglobinopathies. <b>GnRH agonists or antiandrogens may be used in adults but should not be used in patients who have not achieved full sexual maturation and adult stature.</b>`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `<!--17. -->Evidence-based studies of priapism therapies and outcomes are rare. A recent investigation of adult SCD patients presenting with ischemic priapism subjected all men to a standard protocol of aspiration and phenylephrine injections. Long-term sexual health function outcomes revealed complete ED in men with duration of priapism:`,
    q2: ``,
    q3: [],
    option: [
      `<!--a. -->less than 12 hours.`,
      `<!--b. -->12 to 24 hours.`,
      `<!--c. -->longer than 36 hours.`,
      `<!--d. -->longer than 48 hours.`,
      `<!--e. -->longer than 72 hours.`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [2],
    ansText: `Rationale: In those patients in whom priapism was reversed, spontaneous erection (with or without sildenafil) was reported in 100% of men when priapism was reversed in less than 12 hours; 78% when reversed by 12 to 24 hours; and 44% when reversed by 24 to 36 hours. <b>No patient reported spontaneous erection after priapism duration of more than 36 hours.</b>`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `<!--18. -->An adult male presents with ischemic priapism of 8 hours duration. He fails to respond to serial aspiration and intracavernous injection after 4 hours in the emergency department. The recommended intervention at this time should be:`,
    q2: ``,
    q3: [],
    option: [
      `<!--a. -->hydration, nasal oxygen, and keeping the patient NPO for 8 hours to avoid risks of emergent intubation.`,
      `<!--b. -->a percutaneous distal penile shunt.`,
      `<!--c. -->an open distal shunt.`,
      `<!--d. -->an open proximal shunt.`,
      `<!--e. -->a saphenous vein shunt.`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [1],
    ansText: `Rationale: The objective of shunt surgery is reoxygenation of the corpus cavernosum. <b>The shared principle of all shunting procedures is to reestablish corporal inflow by relieving venous outflow obstruction. A distal cavernoglanular shunt should be the first choice of shunting procedures because it is technically easier to perform than proximal shunting.</b> Percutaneous distal shunting is less invasive than open distal shunting and can be attempted in the emergency department with local anesthetic. Anesthesiologists must be educated that ischemic priapism is an emergency and sexual function outcomes are time dependent; appropriate airway precautions should be taken for emergent intubation as needed in the surgical management of priapism.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `<!--19. -->Radiographic imaging may be helpful in the diagnosis and management of priapism. Each of the following is correct EXCEPT:`,
    q2: ``,
    q3: [],
    option: [
      `<!--a. -->color Doppler ultrasound (CDU) in the evaluation of a persistent erection following treatments for ischemic priapism.`,
      `<!--b. -->penile arteriography to differentiate high-flow from ischemic priapism.`,
      `<!--c. -->magnetic resonance imaging (MRI) to diagnose corporal thrombus in men with refractory priapism or when there has been a significant delay in presentation.`,
      `<!--d. -->MRI in the differential diagnosis of corporal metastasis.`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [1],
    ansText: `Rationale: CDU is an adjunct to the corporal aspirate in differentiating ischemic from nonischemic priapism. CDU imaging should include corporal shaft and transperineal assessment of the crural bodies when there is a history of penile trauma or straddle injury. CDU should always be considered in the evaluation of a persistent or partial erection after treatments for ischemic priapism. Penile arteriography is too invasive as a diagnostic procedure to differentiate ischemic from nonischemic priapism. Penile arteriography should be reserved for the management of high-flow priapism, when embolization is planned. There are three possible roles for MRI: (1) imaging of a well-established arteriolar-sinusoidal fistula, (2) identifying corporal thrombus, and (3) identifying corporal metastasis.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `<!--20. -->A 36-year-old tech entrepreneur is referred for a diagnosis of priapism after he slipped while climbing aboard his yacht. He initially had a saddle bruise on his perineum and pain; the next morning he awoke with persistent erection. The patient has a board of directors meeting at the end of the week and wants immediate treatment. The correct management strategy is:`,
    q2: ``,
    q3: [],
    option: [
      `<!--a. -->penile aspiration and α-adrenergic injection in the office or emergency department.`,
      `<!--b. -->penile arteriography.`,
      `<!--c. -->angio-embolization after a thorough discussion of chances for spontaneous resolution and risks of treatment-related ED.`,
      `<!--d. -->CDU-guided corporal exploration to ligate fistula.`,
      `<!--e. -->distal penile shunt.`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [2],
    ansText: `Rationale: Arterial priapism is not an emergency and may be managed expectantly. Diagnosis of high-flow priapism is best made by penile/perineal CDU. Penile aspiration and injection of α-adrenergic agents is not recommended for HFP. Angio-embolization should be preceded by a thorough discussion of chances for spontaneous resolution, risks of treatment-related ED, and lack of significant consequences expected from delaying interventions. Overall success rates with embolization are high, although a single treatment carries a recurrence rate of 30% to 40%. <b>Where angio-embolization fails or is contraindicated, surgical ligation is reasonable. Formation of a pseudocapsule at the site of a sinusoidal fistula may take weeks to months following trauma. CDU guidance is recommended during exploration to locate the fistula.</b>`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `<!--21. -->Priapism associated with SCD is ischemic. The current pathophysiology is believed to be:`,
    q2: ``,
    q3: [],
    option: [
      `<!--a. -->obstruction of venous outflow by sickled erythrocytes.`,
      `<!--b. -->hemolysis and reduced NO.`,
      `<b>Contemporary science implicates hemolysis and reduced NO in the pathogenesis of pulmonary hypertension, leg ulcers, priapism, and stroke in SCD patients, whereas increased blood viscosity is believed to be responsible for painful crises, osteonecrosis, and acute chest syndrome</b>. SCD patients with priapism have a fivefold greater risk of developing pulmonary hypertension. SCD priapism is also associated with reduced hemoglobin levels and increased hemolytic markers: reticulocyte count, bilirubin, lactate dehydrogenase, and aspartate aminotransferase.`,
      `<!--c. -->increased blood viscosity.`,
      `<!--d. -->a blood dyscrasia associated with reduced reticulocyte counts.`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [1],
    ansText: `Rationale: <b>Contemporary science implicates hemolysis and reduced NO in the pathogenesis of pulmonary hypertension, leg ulcers, priapism, and stroke in SCD patients, whereas increased blood viscosity is believed to be responsible for painful crises, osteonecrosis, and acute chest syndrome</b>. SCD patients with priapism have a fivefold greater risk of developing pulmonary hypertension. SCD priapism is also associated with reduced hemoglobin levels and increased hemolytic markers: reticulocyte count, bilirubin, lactate dehydrogenase, and aspartate aminotransferase.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `<!--22. -->Ischemic priapism in boys and men with SCD should focus on correcting the hemoglobinopathy:`,
    q2: ``,
    q3: [],
    option: [
      `<!--a. -->with exchange transfusions.`,
      `<!--b. -->with hydration, alkalinization, and oxygen.`,
      `<!--c. -->with aspiration and pharmacologic detumescence.`,
      `<!--d. -->with hydroxyurea.`,
      `<!--e. -->with analgesia and expectant management.`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [2],
    ansText: `Rationale: Classically, management of SCD-induced ischemic priapism involved analgesics, hydration, oxygen, bicarbonate, and exchange transfusion. It is very tempting, especially in boys, to defer management to pediatricians and hematologists. Hematologists have begun to question the emphasis on intravenous hydration, sodium bicarbonate for alkalinization, and exchange transfusion as first-line therapy for SCD-associated priapism. Unfortunately, acute neurologic complications may follow exchange transfusions. Hydroxycarbamide (hydroxyurea) is a hematologic agent used in the management of vaso-occlusive crises in SCD patients. The proposed mechanisms of action are increase in production of hemoglobin F, lowering of leukocytes–platelets–reticulocytes, and promoting release of NO. In the best interest of the patient, the urologist should seek hematologic consultation in the management of boys and men with SCD priapism, but remain assertive that hematologic therapy alone is not effective management of SCD priapism. One report suggested that blood transfusion may have no effective role in the treatment of sickle cell–induced priapism. Reports from hematology centers suggest high success rates using penile aspiration/injection/irrigation of intracavernous sympathomimetics for SCD priapism.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `<!--23. -->A 27-year-old previously healthy white male is brought into the emergency department in the early morning hours by his girlfriend. She describes a night of partying with alcohol, energy drinks, and a small amount of cocaine. Her boyfriend has had a persistent erection for 6 to 8 hours. She says, “I’ve done all I can to help him—it won’t go down!” The emergency department doctor calls the urologist to go over the case and initiate management. The best course of therapy would be:`,
    q2: ``,
    q3: [],
    option: [
      `<!--a. -->baclofen, 20 mg PO followed every 6 hours until erection subsides.`,
      `<!--b. -->pseudoephedrine, 60 mg PO.`,
      `<!--c. -->inhaled terbutaline, 4 mg.`,
      `<!--d. -->oral terbutaline, 4 mg.`,
      `<!--e. -->corporal aspiration and injection of phenylephrine, 200 μg.`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [4],
    ansText: `Rationale: Oral agents are not recommended in the management of acute ischemic priapism (&gt; 4 hours). Oral α-adrenergic agents may have a role in the management of stuttering priapism associated with prolonged nocturnal erections. The recommended initial treatment of ischemic priapism is the decompression of the corpora cavernosa by aspiration. Aspiration will immediately soften the erection and relieve pain. Aspiration alone may relieve priapism in 36% of cases. The AUA Guidelines Panel advised that there were not sufficient data to conclude that aspiration followed by saline intracorporal irrigation was any more effective than aspiration alone. Aspiration should be repeated until no more dark blood can be seen coming out from the corpora and fresh bright red blood is obtained. This process leads to a marked decrease in the intracavernous pressure, relieves pain, and resuscitates the corporal environment removing anoxic, acidotic, and hypercarbic blood. <b>Corporal aspiration, if unsuccessful, should be followed by</b> α<b>-adrenergic injection.</b>`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `<!--24. -->PDE5 inhibitors are first-line therapy for ED, but like intracavernous therapy, PDE5 inhibitors have been associated with prolonged erection and priapism. Which agent is most likely to cause priapism?`,
    q2: ``,
    q3: [],
    option: [
      `<!--a. -->Sildenafil, 100 mg PRN sex`,
      `<!--b. -->Avanafil, 200 mg PRN sex`,
      `<!--c. -->Levitra, 20 mg PRN sex`,
      `<!--d. -->Cialis, 5 mg daily`,
      `<!--e. -->None of these agents is more likely to result in priapism`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [4],
    ansText: `Rationale: The 2013 label for the most recently approved PDE5 inhibitor Stendra (avanafil 50 mg, 100 mg, 200 mg) contains precautionary wording virtually identical to that on prior labels for PRN oral dosing of sildenafil, vardenafil, and tadalafil: “There have been rare reports of prolonged erection greater than 4 hours and priapism (painful erections greater than 6 hours).” Once-daily tadalafil (2.5 mg and 5 mg) was approved for oral treatment of ED in 2008, and subsequently in 2011 tadalafil (2.5 mg and 5 mg) was approved for the signs and symptoms of BPH and treatment of ED and the signs and symptoms of BPH. Tadalafil 5 mg daily dosing caused no priapism in a phase II clinical study of 281 men with history of lower urinary tract symptoms secondary to BPH for 6 weeks.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `<!--25. -->Early reviews concluded that the natural history of ischemic priapism is ED. Recent interventions have tracked sexual health function outcomes with evidence-based questionnaires such as the International Index of Erectile Function (IIEF-5). Improvements in medical and surgical management of ischemic priapism may preserve erectile function. Unfortunately, ED is likely to occur if reversal by medical or surgical means is not successful after how many hours?`,
    q2: ``,
    q3: [],
    option: [
      `<!--a. -->8 hours`,
      `<!--b. -->12 to 24 hours`,
      `<!--c. -->36 hours`,
      `<!--d. -->48 hours`,
      `<!--e. -->72 hours`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [3],
    ansText: `Rationale: Bennett and Mulhall in 2008 carefully documented 39 cases of SCD priapism presenting to their emergency department over 8 years; men were routinely interviewed for erectile function status within 4 weeks of priapism/interventions. Of the 39 African-American men followed, 73% acknowledged prior episodes of stuttering; 85% had previously been diagnosed with SCD; but only 5% had been counseled in SCD clinics or were aware that priapism was a complication of SCD. A standard protocol of aspiration and phenylephrine injection was performed; shunting for failure of medical management was performed in 28%. In those patients in whom priapism was reversed, spontaneous erections (with or without use of sildenafil) were reported in 100% of men when priapism was reversed by 12 hours; 78% when reversed by 12 to 24 hours; and 44% when reversed by 24 to 36 hours. In this contemporary series of SCD patients, no men reported the return of spontaneous erections after priapism lasting 36 hours or more. Ralph describes the efficacy and outcomes of combining the T-shunt with the corporal “snake” maneuver in 45 patients. All were refractory to medical reversal of ischemic priapism. The combined distal surgical technique was successful in resolving the acute priapism if duration was less than 24 hours but had limited efficacy in cases of priapism greater than 48 hours. Corporal needle biopsies were performed in each case and documented smooth muscle necrosis, worsening as a function of time and uniform in all men with more than 48 hours of ischemia. At 6 months erectile function outcomes were assessed by the erectile function domain score from the IIEF-5. T-shunt with corporal snake tunneling successfully reversed ischemic priapism in all patients with less than 24 hours’ duration, but at 6 months ED was complained of by 50% of men. <b>The authors conclude that the cutoff for irreversible restoration of erectile tissue is 48 hours; aggressive combined distal shunting may resolve priapism in a small cohort (30%), but all will have severe ED. They advise that management of refractory ischemic priapism greater than 48 hours should include discussion of immediate insertion of penile implant.</b>`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
];
