var quiz = [
  {
    q: ` The following adult male germ cell tumor (GCT) subtypes arise from germ cell neoplasia in situ (GCNIS) EXCEPT: `,
    q2: ``,
    q3: [],
    option: [
      `embryonal tumor.  `,
      ` choriocarcinoma `,
      ` classic seminoma. `,
      `  spermatocytic tumor.`,
      `teratoma  `,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [3],
    ansText: `Rationale: <b>GCNIS is the common precursor lesion for all types of adult male GCT with the exception of spermatocytic tumor.</b> Pediatric GCTs do not typically arise from GCNIS. `,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: ` Which of the following statements is TRUE regarding spermatocytic tumor? `,
    q2: ``,
    q3: [],
    option: [
      `Cryptorchidism is a risk factor.  `,
      ` It may occur as a mixed GCT with other histologic GCT subtypes. `,
      ` It may contain i(12p) mutations. `,
      ` Bilateral testicular involvement may occur in 2% to 3% of cases. `,
      `  Metastatic spermatocytic tumor is rare.`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [4],
    ansText: `Rationale: Spermatocytic tumor differs from other GCT subtypes in that it does not arise from GCNIS, cryptorchidism is not a risk factor, bilaterality has not been reported, it does not express i(12p) or placental alkaline phosphatase, and it does not occur as a mixed GCT with other GCT subtypes. Only one documented case of metastasis has been reported, and these lesions are almost always cured by orchiectomy.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: ` Which of the following GCT subtypes is most likely to spread hematogenously? `,
    q2: ``,
    q3: [],
    option: [
      ` Choriocarcinoma `,
      `Embryonal carcinoma  `,
      ` Immature teratoma `,
      ` Teratoma with malignant transformation `,
      `  Seminoma`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [0],
    ansText: `Rationale: With the exception of choriocarcinoma, the most common route of disease dissemination is via lymphatic channels from the primary tumor to the retroperitoneal lymph nodes and subsequently to distant sites. Choriocarcinoma has a propensity for hematogenous dissemination. Yolk sac tumors in children are thought to spread hematogenously as well. `,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `A 24-year-old man presents with a solid, painless, right intratesticular mass confirmed by scrotal ultrasonography. His left testis is normal. Serum tumor markers show a human chorionic gonadotropin (hCG) value of 96 mU/mL (upper limit: &lt;5 mU/mL) and an α-fetoprotein (AFP) value of 58 ng/mL (upper limit: &lt;11 ng/mL). The most likely histologic finding in the right testis is:  `,
    q2: ``,
    q3: [],
    option: [
      ` pure teratoma. `,
      ` pure seminoma `,
      ` pure embryonal carcinoma. `,
      ` pure yolk sac tumor. `,
      `choriocarcinoma  `,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [2],
    ansText: `Rationale: Pure embryonal carcinoma may produce both AFP and hCG. Pure seminoma is associated with elevated serum hCG levels in 15% of cases but does not produce AFP. Pure teratoma typically is not associated with elevated serum tumor markers, although slightly elevated AFP levels may be observed. Choriocarcinoma is uniformly associated with elevated hCG levels but does not produce AFP. Most yolk sac tumors produce AFP, but they do not produce hCG.  `,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `  Which of the following is an acceptable indication for testis-sparing surgery?`,
    q2: ``,
    q3: [],
    option: [
      ` 1.3-cm solid intratesticular mass with a normal contralateral testis `,
      `Suspected benign testicular lesion  `,
      ` 2.4-cm solid mass in a solitary testis `,
      `  Hypogonadal male with 1.2-cm solid intratesticular mass in a solitary testis`,
      ` Small (&lt;1 cm) hyperechoic lesion suggestive of a “burned out” primary tumor in a patient with disseminated nonseminomatous GCT (NSGCT) with serum-elevated AFP and hCG `,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [1],
    ansText: `Rationale: Testis-sparing surgery should be considered only in patients with suspected GCT who have normal testicular androgen production and who have a small (&lt;2 cm) tumor either in a solitary testis or in the setting of bilateral synchronous testicular GCT. Testis-sparing surgery should not be performed in patients with suspected GCT who have a normal contralateral testis. Testis-sparing surgery may also be considered in patients with suspected benign testicular lesions such as an epidermoid cyst or adenomatoid tumor arising from the tunica albuginea. `,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: ` A 37-year-old man presents with a 5-cm left testicular mass. Computed tomography (CT) reveals a 6-cm para-aortic mass but no evidence of distant metastases. Serum tumor markers show an AFP level of 1100 ng/mL (upper limit: &lt;11 ng/mL) and an hCG level of 80 mU/mL (upper limit: &lt;5 mU/mL). Left inguinal orchiectomy reveals a mixed GCT with 60% embryonal carcinoma, 30% yolk sac tumor, 5% seminoma, and 5% teratoma. The next best management step is: `,
    q2: ``,
    q3: [],
    option: [
      ` retroperitoneal lymph node dissection (RPLND). `,
      ` induction chemotherapy with three cycles of bleomycin-etoposide-cisplatin. `,
      ` induction chemotherapy with four cycles of bleomycin-etoposide-cisplatin. `,
      ` to obtain repeat serum tumor marker levels in 7 days. `,
      ` CT-guided biopsy of the para-aortic mass. `,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [3],
    ansText: `Rationale: Patients with elevated serum tumor markers before orchiectomy should have these levels measured after orchiectomy to assess whether the levels are declining, stable, or rising. Management decisions should not be made based on serum tumor marker levels before orchiectomy. Patients with rising postorchiectomy serum tumor marker levels should receive chemotherapy. The IGCCCG classification of metastatic NSGCT is based on the postorchiectomy serum tumor marker levels. `,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: ` All of the following patients would be classified as “poor-risk” by International Germ Cell Cancer Collaborative Group (IGCCCG) classification criteria EXCEPT those with: `,
    q2: ``,
    q3: [],
    option: [
      `testicular seminoma with brain metastases  `,
      ` primary mediastinal NSGCT. `,
      ` testicular NSGCT with rising postorchiectomy AFP of 15,000 ng/mL (upper limit: &lt;11 ng/mL). `,
      ` primary retroperitoneal NSGCT with liver metastases. `,
      `testicular NSGCT with rising postorchiectomy hCG of 93,000 mU/mL (upper limit: &lt;5 mU/mL).  `,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [0],
    ansText: `Rationale: According to IGCCCG classification criteria, there is no “poor risk” category for metastatic seminoma. Patients with metastatic seminoma who have nonpulmonary visceral metastases (e.g., liver, bone, brain) are classified as at intermediate risk. Metastatic NSGCT patients with mediastinal primary tumor <b><i>or</i></b> nonpulmonary visceral metastases <b><i>or</i></b> postorchiectomy AFP &gt;10,000 ng/mL, <b><i>or</i></b> postorchiectomy hCG of 50,000 mU/mL are classified as at poor risk. `,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: ` A 34-year-old African American man with a left testicular mass undergoes inguinal orchiectomy that reveals a 1.2-cm pure seminoma that is confined to the testis with no evidence of lymphovascular invasion or rete testis invasion. His postorchiectomy serum tumor markers are within the normal range. CT of the chest-abdomen-pelvis reveals no evidence of retroperitoneal lymphadenopathy and no evidence of pulmonary metastases. However, on the chest images, there is evidence of bulky hilar adenopathy bilaterally. The next best management step is: `,
    q2: ``,
    q3: [],
    option: [
      ` induction chemotherapy with four cycles of bleomycin-etoposide-cisplatin. `,
      `induction chemotherapy with four cycles of etoposide-cisplatin.  `,
      ` mediastinoscopy and biopsy. `,
      ` close observation. `,
      ` bilateral thoracotomy and resection. `,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [2],
    ansText: `Rationale: The presence of distant metastasis in the absence of retroperitoneal disease or elevated serum levels of tumor markers is uncommon, particularly for patients with testicular seminoma. Therefore, these patients should undergo biopsy and histologic confirmation of the suspected lesion before management decisions are made.  `,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: ` A 43-year-old man with clinical stage IIA left seminoma receives dog-leg radiation therapy to the retroperitoneum and ipsilateral pelvis with a boost to his solitary 2-cm para-aortic mass. Six months after completing treatment, surveillance CT reveals a persistent para-aortic mass that has now grown to 2.8 cm. The remainder of his metastatic evaluation is negative, and his serum tumor marker levels are all within normal limits. The next best management step is: `,
    q2: ``,
    q3: [],
    option: [
      ` RPLND `,
      ` CT-guided biopsy of the retroperitoneal mass. `,
      `close observation until the mass regresses or the patient develops distant metastases.  `,
      ` induction chemotherapy with three cycles of bleomycin-etoposide-cisplatin. `,
      `salvage chemotherapy with four cycles of paclitaxel-ifosfamide-cisplatin.  `,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [1],
    ansText: `Rationale: The risk of teratoma at metastatic sites is less of a consideration for metastatic seminoma than for NSGCT. Although rare, seminoma may transform into NSGCT elements, and this should be considered in patients with metastatic seminoma who fail to respond to conventional therapy. These patients should undergo biopsy and histologic confirmation of the suspected lesion before management decisions are made. Either an open or a laparoscopic biopsy of the para-aortic mass is an acceptable approach if CT-guided biopsy is not feasible or the result is nondiagnostic. However, an RPLND should not be performed without histologic confirmation of NSGCT pathology. `,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: ` A 41-year-old man has GCNIS discovered on biopsy of an atrophic right testis during investigations for infertility due to azoospermia. He has a history of left inguinal hernia repair. His left testis is normal in size and consistency, and there is evidence of normal spermatogenesis on testicular biopsy. His serum luteinizing hormone (LH), follicle-stimulating hormone (FSH), and testosterone levels are within the normal range. The most appropriate treatment for the GCNIS in the right testis now is: `,
    q2: ``,
    q3: [],
    option: [
      `inguinal orchiectomy.  `,
      ` low-dose radiation therapy. `,
      ` carboplatin `,
      `observation  `,
      `  transscrotal orchiectomy`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [0],
    ansText: `Rationale: Inguinal orchiectomy and low-dose radiation therapy are associated with the highest rates of local control of GCNIS. In a patient with a normal contralateral testis (particularly if future paternity is desired), inguinal orchiectomy is the preferred choice owing to the deleterious effects of radiation therapy on spermatogenesis within the contralateral testis. `,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: ` Which of the following factors is NOT associated with the presence of occult metastases in clinical stage I NSGCT? `,
    q2: ``,
    q3: [],
    option: [
      `Lymphovascular invasion  `,
      `Absence of yolk sac tumor in the primary tumor  `,
      ` Percentage of embryonal carcinoma in the primary tumor `,
      ` Elevated preorchiectomy AFP level `,
      ` Advanced primary tumor stage `,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [2],
    ansText: `Rationale: Preorchiectomy serum tumor marker levels are not associated with the presence of occult metastases in clinical stage I NSGCT. The presence of postorchiectomy serum tumor marker levels in clinical stage I NSGCT indicates the presence of occult systemic disease.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: ` A 27-year-old convict at a correctional facility presents for management of clinical stage I left NSGCT. He has a history of enlarging left testicular mass for 12 months that was discovered incidentally during a routine physical examination by the prison physician. Pathologic examination of the orchiectomy specimen revealed a 1.2-cm mixed GCT (40% seminoma, 40% embryonal carcinoma, 20% yolk sac tumor) confined to the testis without evidence of lymphovascular invasion. His postorchiectomy serum tumor markers are within normal limits. He has a history of multiple incarcerations in the past, and his viral serology is positive for hepatitis C. The most appropriate treatment is: `,
    q2: ``,
    q3: [],
    option: [
      ` adjuvant radiation therapy to the retroperitoneum and ipsilateral pelvis. `,
      ` surveillance `,
      ` chemotherapy with one cycle of bleomycin-etoposide-cisplatin. `,
      `  chemotherapy with two cycles of carboplatin.`,
      `  RPLND`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [2],
    ansText: `Rationale: Chemotherapy is associated with the lowest risk of recurrence and is thus preferred versus surveillance for patients who are anticipated to be noncompliant with surveillance imaging and testing (even for patients at low risk for occult metastases). Chemotherapy and RPLND are associated with similar rates of long-term cure, but the former may be preferable in patients with transmissible diseases. Adjuvant radiation therapy and carboplatin are standard treatment approaches for clinical stage I seminoma. `,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `Which of the following factors is NOT associated with the presence of necrosis/fibrosis in residual masses after first-line chemotherapy?  `,
    q2: ``,
    q3: [],
    option: [
      ` Absence of teratoma in the primary tumor. `,
      ` Residual mass size `,
      ` Percentage shrinkage of mass after chemotherapy `,
      ` Prechemotherapy mass size. `,
      `Lymphovascular invasion  `,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [4],
    ansText: `Rationale:<b>Absence of teratoma in the primary tumor, prechemotherapy and postchemotherapy mass size, and percentage shrinkage of mass with chemotherapy are all associated with the presence of necrosis/fibrosis in residual masses after first-line chemotherapy. However, none of these factors (alone or together) is sufficiently accurate to exclude the presence of residual teratoma or viable malignancy in patients with residual masses greater than 1 cm.</b> Lymphovascular invasion is associated with the presence of occult metastases in patients with clinical stage I NSGCT and has no impact on the histology of residual masses after chemotherapy.  `,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `  A 37-year-old man presents for treatment of a 1.2-cm left testicular mixed GCT (40% teratoma, 40% seminoma, 15% embryonal carcinoma, 5% yolk sac tumor) confined to the testis without evidence of lymphovascular invasion. His postorchiectomy serum tumor marker levels are within normal limits. Chest CT shows no evidence of metastatic disease. Abdominopelvic CT shows a 7-mm nodule in the paracaval location just inferior to the right renal hilum. The remainder of the CT study is unremarkable. His medical history is also unremarkable. The most appropriate management is:`,
    q2: ``,
    q3: [],
    option: [
      ` CT-guided biopsy of the paracaval lesion `,
      ` RPLND `,
      ` two cycles of chemotherapy with bleomycin-etoposide-cisplatin `,
      ` observation `,
      `three cycles of chemotherapy with bleomycin-etoposide-cisplatin.  `,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [3],
    ansText: `Rationale: <b>Patients at low risk for metastatic disease with indeterminate CT findings should be closely observed because small (&lt;1 cm) retroperitoneal lesions may represent false-positive findings, particularly if they are located outside the primary landing zone.</b> A CT-guided biopsy would be technically difficult to perform, given the lesion size and its proximity to the renal vessels. `,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: ` The following factors are associated with the presence of occult distant metastases in patients with clinical stage IIA-B NSGCT EXCEPT: `,
    q2: ``,
    q3: [],
    option: [
      `elevated postorchiectomy hCG  `,
      ` lymphovascular invasion. `,
      ` retroperitoneal mass size. `,
      `  large primary tumor with involvement of the scrotal skin.`,
      `  retroperitoneal lymphadenopathy outside the primary landing zone.`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [1],
    ansText: `Rationale: <b>Lymphovascular invasion is associated with the presence of occult metastases in patients with clinical stage I NSGCT, but it has not been associated with an increased risk of distant metastases in patients with clinical or pathologic stage II disease.</b> Elevated postorchiectomy serum tumor markers, bulky (&gt;3 cm) retroperitoneal masses, or retroperitoneal lymphadenopathy outside the primary landing zone are associated with an increased risk of systemic relapse after RPLND. Thus, clinical stage IIA-B patients with these features are recommended to receive induction chemotherapy. Scrotal invasion by the primary tumor is associated with an increased risk of metastasis to the inguinal lymph nodes, which are considered nonregional lymph nodes.  `,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: ` The following are independent risk factors for relapse postchemotherapy RPLND EXCEPT: `,
    q2: ``,
    q3: [],
    option: [
      `evidence of viable malignancy in resected specimens.  `,
      ` incomplete resection. `,
      ` rising pre-RPLND serum tumor markers. `,
      ` poor-risk disease at diagnosis by IGCCCG criteria. `,
      ` prior RPLND. `,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [3],
    ansText: `Rationale: Although patients with poor-risk GCT have diminished survival and are more likely to have viable malignancy or incomplete resection at postchemotherapy RPLND, IGCCCG risk category is not a predictor of relapse independent of the histology of resected masses or completeness of resection. “Desperation” postchemotherapy RPLND in the setting of rising serum tumor markers after second- or third-line chemotherapy and reoperative RPLND are other conditions associated with an increased risk of relapse. `,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: ` A 34-year-old man with right clinical stage III NSGCT (100% embryonal carcinoma) with good-risk features by IGCCCG criteria receives induction chemotherapy with three cycles of bleomycin-etoposide-cisplatin. At completion of chemotherapy, his serum tumor markers are within normal limits. On postchemotherapy CT studies he has a 1.7-cm mass (4.8 cm at diagnosis) in the interaortocaval region and a 0.8-cm mass in the para-aortic region (2.3 cm at diagnosis). He also has bilateral pulmonary nodules in the right lower lobe (0.6 cm; 1.4 cm at diagnosis) and left upper lobe (0.8 cm; 1.6 cm at diagnosis). The most appropriate management is: `,
    q2: ``,
    q3: [],
    option: [
      `four cycles of vinblastine-ifosfamide-cisplatin second-line chemotherapy.  `,
      ` resection of the interaortocaval mass. `,
      ` bilateral postchemotherapy RPLND. `,
      ` bilateral thoracotomy and resection of residual pulmonary masses. `,
      ` CT-guided biopsy of the pulmonary mass(es). `,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [2],
    ansText: `Rationale: <b>Approximately one third of patients will have residual masses at multiple anatomic sites, and these patients should undergo resection of all sites of measurable residual disease because discordant histology between anatomic sites is reported in 22% to 46% of cases. However, the presence of necrosis in postchemotherapy RPLND specimens is highly predictive of necrosis at other sites.</b> Thus, postchemotherapy RPLND should be performed before resection of residual masses at other sites. Observation of small residual masses at other sites is a reasonable option if the histology of the RPLND specimen is necrosis. Patients with viable malignancy discovered at postchemotherapy resection should have all residual masses resected and are usually treated with an additional two cycles of chemotherapy. A full course of second-line chemotherapy is reserved for patients with either serologic or radiographic progression during or after first-line chemotherapy. `,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `Which of the following statements is FALSE concerning late relapse of NSGCT?  `,
    q2: ``,
    q3: [],
    option: [
      ` Surgical resection is the primary treatment modality. `,
      ` Yolk sac tumor is the most common malignant histology. `,
      ` The incidence is increasing. `,
      ` The retroperitoneum is the most common site. `,
      `  The outcome is poor relative to those with early NSGCT relapse.`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [4],
    ansText: `Rationale: Until recently, late relapse has been associated with a worse prognosis than early relapse, although more recent data suggest these patient groups have a similar probability of cure. Disease-free rates of 50% to 60% are reported after treatment of early and late relapse.  `,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: ` A 35-year-old man with clinical stage IIC left mixed GCT (50% embryonal, 40% teratoma, 10% yolk sac) with good-risk features by IGCCCG criteria receives three cycles of bleomycin-etoposide-cisplatin chemotherapy. At the start of chemotherapy, his AFP was 380 ng/mL (upper limit: &lt;11 ng/mL), and this has normalized at the end of chemotherapy. Restaging CT shows the solid para-aortic mass has increased from 5.3 cm to 8.9 cm with displacement of the aorta and left kidney as well as new lymphadenopathy in the left common iliac and left obturator region. The patient complains of recent onset of left-sided back pain. The most appropriate management is: `,
    q2: ``,
    q3: [],
    option: [
      ` RPLND and pelvic lymph node dissection. `,
      `CT-guided biopsy of the para-aortic mass.  `,
      ` four cycles of paclitaxel-ifosfamide-cisplatin as second-line chemotherapy. `,
      ` two cycles of bleomycin-etoposide-cisplatin followed by carboplatin-etoposide high-dose chemotherapy and autologous stem cell rescue. `,
      ` bleomycin-etoposide-cisplatin plus radiation therapy. `,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [1],
    ansText: `Rationale:<b>Patients with good-risk metastatic NSGCT who have dramatic progression of their disease with first-line chemotherapy despite normalization of serum tumor marker levels should be considered to have either growing teratoma syndrome or teratoma with malignant transformation.</b> The presence of an enlarging solid mass and new sites of disease suggest a malignant process. An enlarging mass only with cystic appearance is more suggestive of growing teratoma syndrome. A CT-guided biopsy to identify the presence of malignant transformation is indicated because this finding may influence the choice of chemotherapy.  `,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: ` The rationale for single-agent carboplatin as treatment for clinical stage I seminoma is based on all of the following factors EXCEPT: `,
    q2: ``,
    q3: [],
    option: [
      `absence of teratoma.  `,
      `  less neurotoxicity compared with cisplatin.`,
      ` less nephrotoxicity compared with cisplatin. `,
      ` less ototoxicity compared with cisplatin. `,
      ` similar efficacy to cisplatin. `,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [4],
    ansText: `Rationale: All of the randomized trials in advanced GCT in which a cisplatin-based regimen has been compared with a carboplatin-based regimen have reported superior outcomes with cisplatin. The rationale for single-agent carboplatin is based on reduced toxicity compared with cisplatin and 65% to 90% response rates reported in studies of carboplatin in advanced seminoma. `,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `Late complications of infradiaphragmatic dog-leg radiotherapy include all the following EXCEPT:  `,
    q2: ``,
    q3: [],
    option: [
      ` peptic ulcer disease. `,
      ` coronary artery disease. `,
      ` secondary malignancy. `,
      ` ejaculatory dysfunction. `,
      `impaired spermatogenesis.  `,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [2],
    ansText: `Rationale: Dog-leg radiotherapy for clinical stage I seminoma is associated with infertility due to the direct effects of radiation on the germinal epithelium with resultant impaired spermatogenesis. Infertility related to ejaculatory dysfunction is not associated with radiation therapy and is most commonly associated with RPLND. `,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: ` The rationale for surveillance in clinical stage I seminoma is based on all of the following factors EXCEPT: `,
    q2: ``,
    q3: [],
    option: [
      ` Utility of serum tumor markers to identify relapse at an early and curable stage. `,
      ` Relapses are cured in virtually all cases by deferred dog-leg radiotherapy. `,
      ` Lack of validated histopathologic prognostic factors to identify a high-risk subset. `,
      ` Improved short- and long-term toxicity compared with primary radiotherapy and carboplatin. `,
      `15% to 20% of patients are cured by orchiectomy.  `,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [0],
    ansText: `Rationale: Only 15% of seminomas produce elevations in serum hCG, and serum tumor marker levels are uncommonly elevated in most patients with clinical stage I seminoma at diagnosis or at the time of relapse. This contrasts to clinical stage I NGSCT, in which serum tumor markers are commonly the first (and only) manifestation of disease relapse. `,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: ` The rationale for surveillance in clinical stage I seminoma is based on all of the following factors EXCEPT: `,
    q2: ``,
    q3: [],
    option: [
      ` Utility of serum tumor markers to identify relapse at an early and curable stage. `,
      `  Relapses are cured in virtually all cases by deferred dog-leg radiotherapy.`,
      ` Lack of validated histopathologic prognostic factors to identify a high-risk subset. `,
      `  Improved short- and long-term toxicity compared with primary radiotherapy and carboplatin.`,
      ` 15% to 20% of patients are cured by orchiectomy. `,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [0],
    ansText: `Rationale: Only 15% of seminomas produce elevations in serum hCG, and serum tumor marker levels are uncommonly elevated in most patients with clinical stage I seminoma at diagnosis or at the time of relapse. This contrasts to clinical stage I NGSCT, in which serum tumor markers are commonly the first (and only) manifestation of disease relapse. `,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: ` A 44-year-old man with clinical stage III left testicular seminoma with IGCCCG good-risk features has a discrete 2.4-cm residual para-aortic mass (3.8 cm at diagnosis) after receiving three cycles of bleomycin-etoposide-cisplatin chemotherapy. His pulmonary nodules have regressed completely. His serum tumor markers are within the normal range. The most appropriate management is: `,
    q2: ``,
    q3: [],
    option: [
      ` postchemotherapy radiation therapy to the residual mass. `,
      `fluorodeoxyglucose-labeled positron emission tomography (FDG-PET) at least 4 weeks after completing chemotherapy.  `,
      ` observation `,
      `postchemotherapy surgical resection of the residual mass.  `,
      ` Four cycles of paclitaxel-ifosfamide-cisplatin as second-line chemotherapy. `,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [2],
    ansText: `Rationale: <b>In contrast to advanced NSGCT, only 10% of residual masses in advanced seminoma after first-line chemotherapy contain viable malignancy (90% contain fibrosis/necrosis only), and residual teratoma is less of a consideration.</b> Spontaneous resolution of these masses will occur in most cases. <b>Approximately 30% of discrete residual masses greater than 3 cm will contain viable malignancy. FDG-PET is a useful adjunct to postchemotherapy staging CT to determine the need for postchemotherapy surgical resection. Residual masses larger than 3 cm that are PET negative and those less than 3 cm can be safely observed because of the high probability of necrosis/fibrosis. FDG-PET has no role in the characterization of residual masses less than 3 cm.</b> `,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: ` A 42-year-old asymptomatic man presents for management of right NSGCT (80% embryonal carcinoma, 10% teratoma, 10% choriocarcinoma). His preorchiectomy hCG value was 15,000 mU/mL (upper limit: &lt;5 mU/mL), and this has risen to 50,800 mU/mL after orchiectomy. Chest CT shows numerous pulmonary nodules. There is evidence of multiple masses in the interaortocaval region (largest, 4.8 cm) and masses in the para-aortic region (largest, 2.6 cm). The most appropriate management is: `,
    q2: ``,
    q3: [],
    option: [
      ` three cycles of bleomycin-etoposide-cisplatin chemotherapy. `,
      ` RPLND `,
      ` four cycles of bleomycin-etoposide-cisplatin chemotherapy. `,
      ` CT of the head. `,
      ` two cycles of bleomycin-etoposide-cisplatin followed by carboplatin-etoposide high-dose chemotherapy and autologous stem cell rescue. `,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [3],
    ansText: `Rationale: <b>Choriocarcinoma spreads hematogenously and widely. Brain metastases should be suspected in any patient with a very high hCG level.</b> Thus, patients with high hCG levels at diagnosis should have staging CT or magnetic resonance imaging (MRI) studies of the brain. <b>Choriocarcinomas are highly vascular and tend to hemorrhage during chemotherapy, which may have catastrophic consequences in those patients with brain metastases.</b> Brain metastases are also associated with a poor prognosis, and these patients should receive four cycles of bleomycin-etoposide-cisplatin as first-line chemotherapy, as should any patient with an hCG level over 5000 mU/mL at the time chemotherapy is initiated. `,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },

  {
    q: ` Which of the following statements is FALSE regarding treatment-related toxicity? `,
    q2: ``,
    q3: [],
    option: [
      ` Two cycles of platin-based chemotherapy do not increase one’s risk of developing cardiovascular disease or secondary malignant neoplasm (SMN). `,
      ` Frequent CT body imaging may increase the risk of SMN. `,
      ` The risk of cardiovascular disease is highest among patients receiving mediastinal radiotherapy. `,
      ` Exposure to cisplatin-based chemotherapy and history of cigarette smoking are associated with similar risks of cardiovascular disease and SMN. `,
      ` Suprahilar dissection, vascular reconstruction, and hepatic resection are risk factors for chylous ascites after RPLND. `,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [0],
    ansText: `Rationale: Although the risk of late complications of chemotherapy is dose dependent, there appears to be no safe lower limit. Thus, even patients receiving one to two cycles of platin-based chemotherapy may have an increased risk of late toxicity.  `,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: ` Which of the following are NOT similarities between Leydig cell tumors and GCT?<br/><br/>i. Both are associated with a history of cryptorchidism.<br/>ii. Radical inguinal orchiectomy is the initial treatment of choice.<br/>iii. Bilateral tumors occur in 2% to 3% of cases.<br/>iv. Both may be associated with gynecomastia.<br/>v. The retroperitoneum is the most common site of metastatic disease. `,
    q2: ``,
    q3: [],
    option: [
      ` i, ii, and iii. `,
      `  i and iii.`,
      `i, ii, iii, and iv.  `,
      ` v only. `,
      ` All the above. `,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [1],
    ansText: `Rationale: Unlike GCT, Leydig cell tumors are not associated with a history of cryptorchidism, and bilateral tumors have not been reported. `,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: ` A 54-year-old man presents with an enlarging right inguinal mass. On examination, a palpable mass is noted in the right inguinal region that extends into the right hemiscrotum. The testis cannot be distinguished from this mass. Staging CT reveals a heterogeneous, infiltrative area of low-intensity mass (−20 Hounsfield units), 6 × 9 cm, involving the right spermatic cord and extending from the inguinal canal into the scrotum with displacement of the right testis. There is no evidence of retroperitoneal lymphadenopathy or distant metastases. The most appropriate management is: `,
    q2: ``,
    q3: [],
    option: [
      `inguinal orchiectomy followed by adjuvant radiotherapy.  `,
      ` inguinal orchiectomy alone. `,
      ` transscrotal orchiectomy. `,
      ` inguinal orchiectomy followed by ifosfamide-based adjuvant chemotherapy. `,
      ` inguinal orchiectomy followed by RPLND. `,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [0],
    ansText: `Rationale: A large infiltrative mass involving the spermatic cord in an adult man is a sarcoma until proved otherwise. The low-intensity signal on CT and patient age make liposarcoma the most common histology. Paratesticular liposarcomas rarely metastasize but tend to recur locally. Thus, adjuvant radiotherapy may be used to decrease the risk of local recurrence. `,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: ` <b>Pathology</b><br/><br/>A 26-year-old man has a right radical orchiectomy for an embryonal carcinoma of the testis. At the time of surgery, a contralateral biopsy is performed and reveals intratubular germ cell neoplasia (<a class="lightboxcallout" img-ref="image_fig_76_1" href="19a446336ba24db0b63b6d419b214597">Fig. 76.1</a>). The patient should be advised that he: `,
    q2: ``,
    q3: [],
    option: [
      ` should have a radical orchiectomy. `,
      ` has a significant chance of developing a germ cell tumor in the left testis. `,
      ` has a significant chance of developing a germ cell tumor in the left testis. `,
      ` should not try to have a child. `,
      ` should receive salvage chemotherapy. `,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [1],
    ansText: `Rationale: The figure illustrates germ cell neoplasia in situ as evidenced by enlarged hyperchromatic nuclei and a lack of a spermatogenesis. This carries a 50% risk of developing a germ cell tumor. `,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: ` A 35-year-old man has an asymptomatic right scrotal mass. Testicular ultrasonography reveals a 3-cm heterogeneous intratesticular mass. A right radical orchiectomy is performed. The histology is depicted in <a class="lightboxcallout" img-ref="image_fig_76_2" href="be21dc5f2c06489eb423baa43f10f603">Fig. 76.2</a> and is reported as seminoma. Abdominal CT scan is normal. The patient should be advised to: `,
    q2: ``,
    q3: [],
    option: [
      ` receive radiation to the contralateral testis. `,
      ` receive at least four cycles of chemotherapy. `,
      ` be advised that observation is not an option. `,
      ` be advised to have radiation therapy to the retroperitoneum. `,
      ` receive radiation to the abdomen and chest. `,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [3],
    ansText: `Rationale: Notice in the figure the sheathlike pattern of small cells interspersed with fibrous septa that contain lymphocytes, the hallmarks of seminoma. Although observation is an option, most would recommend radiation to the retroperitoneum, because seminoma is very sensitive to radiation and the morbidity is low—although there is a risk for the development of secondary malignancies over the long term.  `,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: ` A 32-year-old man has a right radical orchiectomy for a testicular mass. Preoperatively, his AFP value was normal and his hCG level was elevated at 5000 units. The histology is depicted in <a class="lightboxcallout" img-ref="image_fig_76_3" href="370572d1a25c475db34f79cd527cfedd">Fig. 76.3</a> and is reported as seminoma with giant cells. The next step in management is: `,
    q2: ``,
    q3: [],
    option: [
      ` follow markers and check half-life. `,
      ` chemotherapy according to choriocarcinoma protocol. `,
      ` RPLND `,
      ` radiation therapy to retroperitoneum. `,
      `  three cycles of chemotherapy.`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [0],
    ansText: `Rationale: The figure demonstrates seminoma with syncytiotrophoblasts. Approximately 15% of patients with seminoma have elevated hCG and will demonstrate syncytiotrophoblasts. Following orchiectomy, the hCG should decline according to its 24-hour half-life. This should be determined first before any treatment decisions are made.  `,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: ` A 50-year-old man has a right radical orchiectomy for a testicular mass. The histology is depicted in <a class="lightboxcallout" img-ref="image_fig_76_4" href="d2634fca4d454d05a81374f6fbd4a45a">Fig. 76.4</a> and is a spermatocytic tumor. Abdominal and chest CT are negative. Serum markers are normal. The patient should be advised to: `,
    q2: ``,
    q3: [],
    option: [
      ` receive radiation to the retroperitoneum. `,
      `receive one cycle of chemotherapy.  `,
      `have a biopsy of the contralateral testis.  `,
      ` not have any treatment. `,
      `  have a PET-CT scan.`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [3],
    ansText: `Rationale: The figure shows a spermatocytic tumor that has a very low malignant potential. Notice the small basophilic cells and the multinucleated tumor giant cell, which are characteristic for spermatocytic tumor. `,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: ` A 20-year-old man has a right radical orchiectomy. The pathology is depicted in <a class="lightboxcallout" img-ref="image_fig_76_5" href="30160893c55849628f67af57f3151895">Fig. 76.5</a> and is read as embryonal carcinoma. His hCG and AFP values are elevated and a CT of abdomen and chest reveals no evidence of metastatic disease. Three weeks later, repeat AFP and hCG testing show no change in either marker. The patient should be advised to: `,
    q2: ``,
    q3: [],
    option: [
      `have induction chemotherapy. `,
      ` have an RPLND. `,
      ` have a PET-CT. `,
      ` receive radiotherapy below the diaphragm. `,
      ` repeat the hCG and AFP tests in another month. `,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [0],
    ansText: `Rationale: This patient has an embryonal carcinoma: notice the primitive, anaplastic epithelial cells. With persistently elevated serum markers, the patient should undergo induction chemotherapy. Surgery is not indicated, radiation therapy is inappropriate, and there is no reason to delay.  `,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: ` A 25-year-old man has a right radical orchiectomy. The histology is depicted in <a class="lightboxcallout" img-ref="image_fig_76_6" href="9cfe3a4bfadc427b8786aad50503ffdb">Fig. 76.6</a> and is reported as a mature teratoma. The patient’s AFP is slightly elevated and bHCG is negative; however, there is a 3-cm mass in the retroperitoneum on CT. He is given chemotherapy and the mass shrinks to 1.8 cm. The patient should be advised to: `,
    q2: ``,
    q3: [],
    option: [
      `have a retroperitoneal lymphadenectomy dissection (RPLND).  `,
      `have salvage chemotherapy.  `,
      `get an FDG-PET scan.  `,
      ` receive radiation therapy. `,
      `  be observed.`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [0],
    ansText: `Rationale: The tumor depicted is a teratoma: notice the mature enteric epithelium. Because the specimen is in the primary tumor, there is a high likelihood that there is residual teratoma in the retroperitoneal mass. This tumor is chemoinsensitive and should be resected. `,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: ` <b>Imaging</b><br/><br/>A 36-year-old man noted a firm left scrotal mass. He was hit in the groin 1 month earlier with a tennis ball. Currently he has no pain, fever, or chills. The testicular ultrasound image is depicted in <a class="lightboxcallout" img-ref="image_fig_76_7" href="85183aa62b524354a03434d7ac911142">Fig. 76.7</a>. The most likely diagnosis is: `,
    q2: ``,
    q3: [],
    option: [
      ` ruptured testis with peritesticular hematoma. `,
      ` testicular neoplasm. `,
      ` epidermoid cyst. `,
      `  dilated rete testis.`,
      `  testicular abscess.`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [1],
    ansText: `Rationale: The ultrasound image shows an irregular vascular mass in the left testis that also has microlithiasis. This is most consistent with a testicular neoplasm. It is not unusual for patients to have a history of groin trauma before presentation.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: ` A 32-year-old man had a left radical orchiectomy. Pathologic evaluation reveals a mixed GCT containing seminoma and embryonal cell carcinoma. Tumor markers are negative. The CT image depicted in <a class="lightboxcallout" img-ref="image_fig_76_8" href="852ec57d68a94868a4091788b71dc5a2">Fig. 76.8</a> was obtained 1-day postoperation. Chest CT is negative. The next step in management is: `,
    q2: ``,
    q3: [],
    option: [
      `biopsy  `,
      ` radiation therapy. `,
      ` chemotherapy `,
      `RPLND  `,
      ` repeat CT in 1 week to confirm a postsurgical inflammatory response. `,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [2],
    ansText: `Rationale: The CT image shows a large (&gt;5 cm) para-aortic mass that represents metastatic adenopathy. Because this represents bulky retroperitoneal disease (stage IIC), chemotherapy is the best option. `,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
];
