var quiz = [
     {
        q: ` Sexual health encompasses which of the following concepts?`,
        q2: ``,
        q3: [],
        option: [`Absence of sexual dysfunction/problem `, 
        ` Mental well-being`, 
        `Human development and maturation `, 
        ` All of the above`, 
        ` a and c`],
        optionStyleType: `st-lower-alpha`,
        answer: [3],
        ansText: `Rationale: Sexual wellness incorporates many aspects of human experience.  `,
        state: `notAnswered`,
        userAnswered: []
    ,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`        ,
        type: `MCSS`},
      {
        q: ` Which of these molecules is thought to play only a minor role in female genital sexual response?`,
        q2: ``,
        q3: [],
        option: [`Vasoactive intestinal polypeptide `, 
        `Nitric oxide `, 
        `Acetylcholine `, 
        ` Norepinephrine`, 
        ` Aquaporins`],
        optionStyleType: `st-lower-alpha`,
        answer: [2],
        ansText: `Rationale: Acetylcholine is thought to play a relatively minor role in sexual response in women. `,
        state: `notAnswered`,
        userAnswered: []
    ,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`        ,
        type: `MCSS`},
    {
        q: `The Female Sexual Function Index (FSFI) assesses all but which of the following aspects of sexuality? `,
        q2: ``,
        q3: [],
        option: [`Sexual distress `, 
        `Sexual desire `, 
        `Sexual arousal `, 
        ` Sexual pain`, 
        `Orgasm `],
        optionStyleType: `st-lower-alpha`,
        answer: [0],
        ansText: `Rationale: The FSFI does not include a metric to quantify or measure sexuality-related distress. `,
        state: `notAnswered`,
        userAnswered: []
    ,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`        ,
        type: `MCSS`},
    {
        q: ` Which of the following is NOT an essential part of the physical examination in a woman with sexual concerns?`,
        q2: ``,
        q3: [],
        option: [` Vital signs`, 
        `Assessment of vaginal pH `, 
        ` Palpation of the levator ani musculature`, 
        ` Careful inspection of the vulva`, 
        ` Biothesiometry`],
        optionStyleType: `st-lower-alpha`,
        answer: [4],
        ansText: `Rationale: Biothesiometry may be indicated in some cases of genital neuropathy, but much of the same information can be gleaned from careful history and physical examination (with or without basic sensory testing). `,
        state: `notAnswered`,
        userAnswered: []
    ,
	type: `MCSS`        ,
        type: `MCSS`},
    {
        q: ` Which of the following statements is TRUE?`,
        q2: ``,
        q3: [],
        option: [`Assessment of the patient’s intimate relationship(s) is a key aspect of treating sexual problems. `, 
        `Women with spinal cord injury cannot experience orgasm `, 
        `A linear pattern for sexual response is typical for all women. `, 
        ` Survey instruments may take the place of history in evaluation of sexual concerns.`, 
        ` All women who have sex with women identify as lesbian or bisexual.`],
        optionStyleType: `st-lower-alpha`,
        answer: [0],
        ansText: `Rationale: Women with spinal cord injury may experience orgasm, and women may endorse a circular or linear sexual response. A history is critical to evaluation of sexual wellness, and up to half of women who have had sex with another woman do not identify as lesbian or bisexual. `,
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
     {
        q: ` Which of the following statements is FALSE?`,
        q2: ``,
        q3: [],
        option: [`Hysterectomy may improve or worsen sexual function in women depending on the indication. `, 
        `Low serum testosterone levels have been clearly linked to worse sexual function in all women. `, 
        ` Phosphodiesterase type 5 inhibitors are not currently approved for the management of problems with sexual arousal response in women.`, 
        `Sexual activity during routine pregnancy is safe. `, 
        ` Women may have genital arousal responses to erotic materials that they find mentally or emotionally unappealing.`],
        optionStyleType: `st-lower-alpha`,
        answer: [1],
        ansText: `Rationale: There are data to support a role for testosterone in sexual function in some women, but this is the least well supported of the statements in this question.  `,
        state: `notAnswered`,
        userAnswered: []
    ,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`        ,
        type: `MCSS`},
    {
        q: `Which of the following are potential adverse events associated with supplemental testosterone in women? `,
        q2: ``,
        q3: [],
        option: [`Hirsutism `, 
        `Acne `, 
        `Decreased high-density lipoprotein `, 
        `Vaginal bleeding `, 
        ` All of the above`],
        optionStyleType: `st-lower-alpha`,
        answer: [4],
        ansText: `Rationale: <b>These are well-established potential effects of testosterone. There are substantial concerns about the potential for cardiovascular disease or neoplasia, but robust data on risk are scant.</b> `,
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
     {
        q: `Decreased sexual interest/desire has been associated with which of the following conditions in women? `,
        q2: ``,
        q3: [],
        option: [`Use of antidepressants `, 
        ` Life stressors`, 
        ` Hypoestrogenism`, 
        `Relationship problems `, 
        `All of the above `,
        `a and c above`],
        optionStyleType: `st-lower-alpha`,
        answer: [4,5],
        ansText: `Rationale: The DSM V combined hypoactive sexual desire disorder and female sexual arousal disorder into female sexual interest/arousal disorder. Similarly, dyspareunia and vaginismus were combined into genitopelvic pain/penetration disorder. FOD was carried over from DSM IV TR. `,
        state: `notAnswered`,
        userAnswered: []
    },
     {
        q: `Which of the following conditions has been associated with lower bioavailable androgen levels in women? `,
        q2: ``,
        q3: [],
        option: [` Hormonal contraceptives`, 
        `Surgical menopause `, 
        `Elevated prolactin levels `, 
        ` All of the above`, 
        ` None of the above`],
        optionStyleType: `st-lower-alpha`,
        answer: [3],
        ansText: `Rationale: <b>Hormonal contraception, prolactin, and surgical menopause all tend to decrease bioavailable testosterone.</b> `,
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
     
    {
        q: `Which of the following has NOT been shown to be useful in the management of problems with sexual arousal in women? `,
        q2: ``,
        q3: [],
        option: [` Topical prostaglandins`, 
        `Muscle relaxants `, 
        `aginal lubricants `, 
        ` Hormonal supplementation with androgens and/or estrogens`, 
        `Psychosocial counseling `],
        optionStyleType: `st-lower-alpha`,
        answer: [1],
        ansText: `Rationale: Muscle relaxants have been used with good efficacy for issues of sexual pain but have not been shown to directly aid sexual arousal response in women. `,
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: ` Which of the following has been definitively linked to sexual dysfunction in women?`,
        q2: ``,
        q3: [],
        option: [`Postmenopausal estrogen replacement `, 
        ` Obesity`, 
        ` High educational achievement`, 
        ` Depression`, 
        ` Metabolic syndrome`],
        optionStyleType: `st-lower-alpha`,
        answer: [3],
        ansText: `Rationale: Depression is unambiguously linked to sexual dysfunction in women; the other entities have been linked to sexual dysfunction in some but not all studies. `,
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
     {
        q: `Which of the following has the least evidence for efficacy in management of antidepressant-associated sexual dysfunction in women? `,
        q2: ``,
        q3: [],
        option: [`Use of an adjunctive antidepressant `, 
        ` Reassurance`, 
        `Drug cessation `, 
        ` Drug holiday`, 
        ` Sildenafil`],
        optionStyleType: `st-lower-alpha`,
        answer: [1],
        ansText: `Rationale: There are peer-reviewed, published data to support all but answer b. Reassurance may be indicated for some women but may be viewed by others as a dismissal of their concerns related to antidepressant treatment. `,
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: ` What is the most commonly purported etiology for the sexual problems that occur in some women using hormonal contraception?`,
        q2: ``,
        q3: [],
        option: [`Reduction of bioavailable testosterone `, 
        `Reduction of bioavailable estrogen `,  
        ` Psychological distress`, 
        `Partner dissatisfaction `,
        `Alteration of vascular response`],
        optionStyleType: `st-lower-alpha`,
        answer: [0],
        ansText: `Rationale: Hormonal contraception has been clearly linked to lower bioavailable serum testosterone. Other etiologies may contribute. `,
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
     {
        q: ` Which of the following is the possible anatomic location of the Grafenberg spot (G-spot), which is particularly sensitive to tactile stimulation in some women?`,
        q2: ``,
        q3: [],
        option: [` Anterior wall of the vagina at the level of midurethra`, 
        `Cervical canal `, 
        `Clitoral surface `, 
        `Posterior vaginal wall `, 
        `Perianal ring `],
        optionStyleType: `st-lower-alpha`,
        answer: [0],
        ansText: `Rationale: A region of the anterior wall of the vagina overlying the midurethra has been identified as the Grafenberg spot (or G-spot), an area that, in some women, is particularly sensitive to tactile stimulation. Grafenberg’s original article identified the erogenous area as arising from the urethra. Controversy still exists over the possible anatomic structure and site of the G-spot. `,
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
     {
        q: ` Choose the correct statement regarding the laboratory evaluation for female sexual dysfunction.`,
        q2: ``,
        q3: [],
        option: [`It is mandatory in all cases `, 
        `Normal range of testosterone levels have been established in women `, 
        ` It is rarely indicated unless there is suspicion for an underlying contributory medical condition`, 
        `Thyroid dysfunction is the most commonly encountered hormonal abnormality in female patients with sexual dysfunction `, 
        ` Abnormalities in hormone levels provide extensive diagnostic and prognostic utility in female sexual dysfunction`],
        optionStyleType: `st-lower-alpha`,
        answer: [2],
        ansText: `Rationale: Laboratory evaluation for female sexual dysfunction (FSD) is rarely indicated unless there is a suspicion for a specific medical condition that might explain patient’s sexual problems. Therefore, random testosterone measurement is worthless in the evaluation of FSD. Furthermore, there are no data to justify serum testosterone measurement for FSD unless there is a concern about hyper/hypoandrogenic state. Normal range of testosterone levels have not been established in women, and testosterone levels do not correlate with libido in females. Likewise, progesterone, measured either alone or in combination with estrogen, has very limited diagnostic/prognostic utility in FSD. If a hormonal abnormality is suspected based on the systemic evaluation of the patient, then a screening blood workup can be done to rule out prolactinoma, thyroid dysfunction, and adrenal disorders. If adrenal insufficiency is suspected, measurement of dehydroepiandrosterone sulfate (DHEA-S) is useful because of isolated adrenal production.  `,
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `Choose the correct statement regarding FSFI. `,
        q2: ``,
        q3: [],
        option: [`Contains 29 items `, 
        `Has an abbreviated version that can be used for screening pre- and postmenopausal women `, 
        `It is not validated for use in patients with cancer `, 
        ` Maximum total score is 30`, 
        `It is not validated for use in research `],
        optionStyleType: `st-lower-alpha`,
        answer: [1],
        ansText: `Rationale: FSFI is a brief, 19-item, multidimensional self-report instrument that assesses six domains of sexual function: desire, arousal, lubrication, orgasm, satisfaction, and pain. Target population consists of hetero- and homosexual women. It is available for pre- and postmenopausal women and women with medical and sexual disorders. It refers to the past 4 weeks and administration time varies between 10 and 15 minutes. Each domain of FSFI is scored on a scale of 0 to 6 points with the exception of the desire domain (scored from 1.2 to 6) and the satisfaction domain (scored from 0.8 to 6). The instrument thus has a range of 2 to 36, with 36 representing a “perfect” score. The maximum total score is 36 and higher scores indicate better sexual functioning. A total FSFI score of less than 26.55 is considered at risk for sexual dysfunction. Although it is validated for use in research, it is not yet used in clinical practice. An abbreviated version (six items) also has been validated in pre- and postmenopausal women and has been proposed as a tool for screening women likely to have FSD. The FSFI also has been validated for use in patients with cancer, in whom strong psychometric properties have been reported in addition to women with chronic pelvic pain.  `,
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
     {
        q: `Which of the following is the most widely studied, most validated physiological test used in the assessment of female sexual function? `,
        q2: ``,
        q3: [],
        option: [` Laser Doppler imaging`, 
        ` Magnetic resonance imaging`, 
        ` Thermistor clip`, 
        `Vaginal photoplethysmography `, 
        ` Doppler ultrasonography`],
        optionStyleType: `st-lower-alpha`,
        answer: [3],
        ansText: `Rationale: There are many physiological monitoring parameters of sexual arousal, which could potentially assist in the diagnosis of organic diseases contributing to sexual dysfunctions. Genital blood flow can be measured with vaginal photoplethysmography, which is the most widely studied and most validated physiological test used in assessment of female sexual function. This method uses a vaginal light source on an acrylic tampon to illuminate the vaginal microcirculation and determine the level of vaginal engorgement. Most studies comparing genital responses of women with and without sexual dysfunction have used vaginal photoplethysmography that measures vaginal pulse amplitude (VPA). `,
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `Choose the correct statement regarding the DSM-5 definitions of sexual dysfunctions in women: `,
        q2: ``,
        q3: [],
        option: [` All disorders, including genitopelvic pain/penetration disorder, require that the symptoms meet the DSM-5 definitions of that condition.`, 
        `Symptoms should be present for 3 months `, 
        `Symptoms should occur on at least half of the sexual occasions `, 
        `Symptoms should cause clinically significant distress `, 
        `Symptoms can be a consequence of a severe relationship distress `],
        optionStyleType: `st-lower-alpha`,
        answer: [3],
        ansText: `Rationale: Regarding the DSM-5 definitions and criteria for sexual dysfunctions in women, all disorders except genitopelvic pain-penetration disorder require that the symptoms meet the DSM-5 definition of that condition, have been present for 6 months on at least 75% of sexual occasions, cause clinically significant distress, are not a consequence of a nonsexual mental disorder or of a severe relationship distress or other significant stressors, and are not attributable to the effect of a medication or illness.  `,
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `Which of the following is the most prevalent type of female sexual dysfunction? `,
        q2: ``,
        q3: [],
        option: [` Hypoactive sexual desire disorder`, 
        `Arousal disorder `, 
        ` Orgasmic disorder`, 
        `Genitopelvic pain/penetration disorder `, 
        ` Vaginismus`],
        optionStyleType: `st-lower-alpha`,
        answer: [1],
        ansText: `Rationale: Shifren et al. (Prevalence of Female Sexual Problems Associated with Distress and Determinants of Treatment Seeking [PRESIDE] study) reported the overall prevalence of FSD associated with low desire to be 37.7% in a study involving 50,001 US women and 31,531 respondents aged 18 to 102 years who were evaluated by validated questionnaires. In this study, 8.9% of women aged 18 to 44 years, 12.3% of women aged 45 to 64 years, and 7.4% of women older than 65 years exhibited low desire accompanied by clinically significant distress (HSDD). `,
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: ` Choose the correct statement about the mechanism of action of Flibanserin, which is currently the only FDA-approved treatment for acquired, generalized hypoactive sexual desire disorder.`,
        q2: ``,
        q3: [],
        option: [` Phosphodiesterase type 5 inhibitor`, 
        `α-adrenergic antagonist `, 
        `5-HT1A receptor agonist and 5-HT 2A receptor antagonist `, 
        `5-HT1A receptor partial agonist `, 
        `Estrogen receptor modulator `],
        optionStyleType: `st-lower-alpha`,
        answer: [2],
        ansText: `Rationale: Flibanserin is currently the only US Food and Drug Administration (FDA)-approved medication that can be used for the management of premenopausal women with low sexual desire. All of the other medical treatment options that can be applied in patients diagnosed with HSDD are used off-label. Flibanserin (Valeant Pharmaceuticals North America LLC, Bridgewater, NJ), dosed at 100 mg PO once daily at bedtime, is a nonhormonal, centrally acting, postsynaptic 5-HT1A receptor agonist and 5-HT2A receptor antagonist that results in a decrease in serotonin activity and an increase in dopamine and norepinephrine activity. `,
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
     {
        q: `Choose the correct statement regarding FOD: `,
        q2: ``,
        q3: [],
        option: [`Orgasmic disorder almost always occurs as an isolated form of female sexual dysfunction `, 
        ` Selective serotonin reuptake inhibitors (SSRIs) are used to treat FOD`, 
        ` The information gathered by the questionnaires about female sexual function is sufficient to arrive at the diagnosis of FOD`, 
        ` DSM-5 definition of FOD does not contain the criterion that requires orgasmic difficulty to occur despite a normal excitement phase`, 
        ` Systemic testosterone treatment (either alone or in combination with systemic/local estrogen treatment) has been approved by the FDA for the treatment for FOD`],
        optionStyleType: `st-lower-alpha`,
        answer: [3],
        ansText: `Rationale: FOD can be diagnosed concurrently with at least one other sexual dysfunction. It has been estimated that among women with FOD, 31% also report difficulties with sexual arousal, 18% with lubrication, 14% with desire, 12% with pain, and 0.9% with vaginismus. The DSM-5 definition of FOD does not contain the DSM-IV-TR criterion requiring that difficulty with orgasm occur despite “a normal excitement phase.” This revision was based on the fact that FOD can occur despite intact arousal. A comprehensive sexual history is essential to diagnose and characterize FOD. Nature and onset of the problem should be carefully assessed as well as the other aspects of female sexual function, since FOD often accompanies problems with interest and arousal. Questionnaires alone are not sufficient to diagnose FOD. However, they can be used to track progress of the orgasmic function and monitor treatment response. Systemic testosterone treatment (either alone or in combination with systemic/intravaginal estrogens) and tibolone (a synthetic steroid available in Europe, which provides a mixture of estrogenic, progestonic, and androgenic actions) have a positive influence on all aspects of female sexual response (desire, arousal, and orgasm) in postmenopausal women with low testosterone/low estrogen levels. However, more research is warranted about the safety and efficacy of hormonal treatment in women with FOD as the primary complaint. SSRIs, which represent the cornerstone of pharmacotherapy of depression, have the potential to adversely affect various aspects of female sexual response cycle, including desire, arousal, and/or orgasm with estimates of 30% to 70% of patients on SSRIs reporting some degree of sexual dysfunction. `,
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `Which of the following is one of the criteria that have been suggested by Leiblum and Nathan and used in the diagnosis of persistent genital arousal disorder in women? `,
        q2: ``,
        q3: [],
        option: [`Physiologic sexual arousal can be brief and remit on its own `, 
        `Symptoms of sexual arousal can be triggered by no stimulus at all `, 
        ` Symptoms of sexual arousal are not distressing`, 
        ` The signs of physiologic sexual arousal remit with ordinary orgasmic experience`, 
        `The signs of physiologic sexual arousal are experienced in the presence of subjective feelings of sexual desire and arousal `],
        optionStyleType: `st-lower-alpha`,
        answer: [1],
        ansText: `Rationale: The International Consultation on Sexual Medicine (ICSM) definition for persistent genital arousal disorder in women is a spontaneous, intrusive, and unwanted genital arousal (i.e., tingling, throbbing, pulsating) in the absence of sexual interest and desire. Any awareness of subjective arousal is typically, but not invariably, unpleasant. The arousal is unrelieved by at least one orgasm, and the feeling of arousal persists for hours or days. In 2001, Leiblum and Nathan defined this syndrome according to the following criteria.<br/><br/>• Physiologic sexual arousal (genital and breast vasocongestion and sensitivity) persists for an extended period (from hours to days) and does not remit on its own.<br/>• The signs of physiologic sexual arousal do not remit with ordinary orgasmic experience.<br/>• The signs of physiologic sexual arousal are experienced in the absence of subjective feelings of sexual desire and arousal.<br/>• The symptoms of sexual arousal can be triggered by sexual-related stimulus but also by nonsexual cues or no stimulus at all.<br/>• These symptoms are perceived as intrusive and unwanted, leading at least to some degree of distress.  `,
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: ` Choose the correct statement regarding provoked vestibulodynia (PVD):`,
        q2: ``,
        q3: [],
        option: [` Patients with primary PVD appear to have greater nerve fiber density and thicker vulvar vestibule compared to the secondary group`, 
        `Pelvic floor muscles are usually hypotonic in both primary and secondary PVD `, 
        ` Positive family history and an association with enuresis is more commonly encountered in secondary PVD`, 
        ` Primary PVD is more common than its secondary counterpart`, 
        ` Local signs of inflammation are a common part of the clinical picture in primary vestibulodynia`],
        optionStyleType: `st-lower-alpha`,
        answer: [0],
        ansText: `Rationale: An important difference between primary and secondary PVD is in the nerve fiber density and the presence of inflammation. Respectively, primary PVD patients appear to have greater nerve fiber density and thicker vulvar vestibule compared to the secondary group. Moreover, hypertonicity of pelvic floor muscles appears to be highly prevalent in patients with PVD. Pelvic muscles dysfunction in patients with PVD can present with decreased muscular strength, reduced speed of contraction, coordination, and reduced endurance.<br/>• Primary PVD: Pain experienced since the first attempt of any type of vaginal penetration (i.e., tampons or sexual activities.) This condition has an early onset, the duration of the pain is longer, and the women are less likely to have had children. They also have a positive family history of the same condition. Frequently there is also an association with enuresis and dysmenorrhea. The presence of local signs of inflammation is less common.<br/>• Secondary PVD: Pain experienced after a certain period of time pertaining to vaginal penetrative activities that previously were pain free. This condition is typically acquired and has a late onset. Larger areas of vestibule are involved in the pain process. The clitoral hood is the area with the most severe pain. Secondary PVD appears to be more frequent than the primary one (65% vs. 35%) and the primary PVD appears to be more frequent in Hispanic women. `,
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
      










];
