var quiz = [
  {
    q: `  Which of the following is not a possible origin of female urethral adenocarcinoma?   `,
    q2: ``,
    q3: [],
    option: [
      ` Müllerian tissue   `,
      ` Cowper glands     `,
      ` Glandular metaplasia   `,
      `   Skene glands `,
      ` Urothelium     `,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [1],
    ansText: `Rationale: There are several proposed origins of female urethral adenocarcinoma, and more than one tissue may be involved. All of the listed tissue types are possible origins with the exception of Cowper glands, which are only present in men.   `,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `  The most common histologic subtype of male anterior urethral cancer is:   `,
    q2: ``,
    q3: [],
    option: [
      `  adenocarcinoma  `,
      `  squamous cell carcinoma.    `,
      ` urothelial carcinoma.   `,
      `  melanoma  `,
      `  sarcoma    `,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [1],
    ansText: `Rationale: The male anterior urethra is lined by stratified and pseudostratified columnar epithelium, which transitions to squamous epithelium distally. The majority of male anterior urethral carcinomas are squamous cell carcinoma.  `,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: ` The histologic subtype of urethral cancer that is more common in women than in men is:    `,
    q2: ``,
    q3: [],
    option: [
      `   adenocarcinoma `,
      `   squamous cell carcinoma.   `,
      `  urothelial carcinoma.  `,
      `  melanoma  `,
      `   sarcoma   `,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [0],
    ansText: `Rationale: Gender is not independently associated with survival for urethral carcinoma; however, there are differences in the characteristics of male and female urethral carcinoma, including the distribution of histologic subtypes. Although squamous cell carcinoma is the predominant form in men, women are more likely to have adenocarcinoma compared to men.  `,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `   In male pendulous urethral carcinoma:  `,
    q2: ``,
    q3: [],
    option: [
      `   prognosis depends on histologic cell type. `,
      ` surgical excision alone is often curative.     `,
      `  prognosis is worse than for bulbomembranous urethral cancer.  `,
      `   a 2-cm margin is always required for penile preserving surgery. `,
      `  biopsy most commonly demonstrates transitional cell carcinoma.    `,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [1],
    ansText: `Rationale: The prognosis of male pendulous anterior urethral cancer is strongly associated with stage, is more favorable than bulbomembranous urethral cancer, and is unrelated to histologic cell type. Most pendulous urethral tumors are squamous cell carcinomas. Low-stage pendulous anterior urethral cancers can often be cured with surgical excision alone, and penile preservation can often be achieved with margins as little as 5 mm.   `,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: ` A treatment that is NOT indicated in cT3N0M0 squamous cell carcinoma of the bulbar urethra is:    `,
    q2: ``,
    q3: [],
    option: [
      ` radical cystectomy with urethrectomy.   `,
      `  chemoradiotherapy.    `,
      `  inguinal lymphadenectomy.  `,
      `  pelvic MRI.  `,
      `    neoadjuvant chemotherapy.  `,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [2],
    ansText: `Rationale: Locally advanced bulbomembranous urethral carcinoma requires aggressive treatment. MRI is required to fully stage the disease, including the extent of local invasion and presence of pelvic nodal metastasis. Of the treatments listed, neoadjuvant chemotherapy, chemoradiation, and radical cystectomy with urethrectomy are all reasonable options. The role of inguinal lymphadenectomy for cN0 urethral cancer is controversial, but there is no role for this in bulbomembranous disease as these tumors are unlikely to drain into the inguinal lymph nodes.   `,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `  The strongest risk factor for male urethral recurrence after radical cystectomy is:   `,
    q2: ``,
    q3: [],
    option: [
      ` carcinoma in situ.   `,
      ` bladder tumor multifocality.     `,
      `  prostatic urethral involvement  `,
      `  squamous cell histology.  `,
      `  prior nonmuscle invasive bladder cancer.    `,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [2],
    ansText: `Rationale: Urethral recurrence after radical cystectomy occurs in 5% to 10% of patients. Of the multiple risk factors that have been studied, prostatic urethral involvement, a positive urethral margin, and cutaneous urinary diversions have the highest risk of urethral recurrence.  `,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `  Which of the following is FALSE about urethral recurrence after radical cystectomy and orthotopic neobladder?   `,
    q2: ``,
    q3: [],
    option: [
      `Urethral recurrences are more common after radical cystectomy and ileal conduit.`,
      ` Radical urethrectomy is always required.  `,
      `   Transurethral resection and intraurethral bacille Calmette-Guérin (BCG) can be effective for noninvasive tumors.   `,
      `  Bowel from the neobladder can be reconfigured for a cutaneous diversion.  `,
      `  Patients with noninvasive recurrences have a good prognosis.  `,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [0],
    ansText: `Rationale: Patients with large or invasive urethral recurrences after radical cystectomy require aggressive treatment, usually with radical urethrectomy. If a urethral recurrence occurs after an orthotopic neobladder, the bowel from the neobladder can be used for a cutaneous diversion in many cases. Patients with noninvasive urethral recurrences have a favorable prognosis and can often be managed with transurethral resection and topical BCG, thus avoiding radical urethrectomy in some cases. Prostatic urethral involvement, a positive urethral margin, and cutaneous diversions all increase the risk of urethral recurrences.   `,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `   A 71-year-old man is diagnosed with a primary prostatic urothelial carcinoma. Transurethral biopsy demonstrates invasion into the prostatic stroma, and imaging is negative for metastasis. The best treatment option is:  `,
    q2: ``,
    q3: [],
    option: [
      ` systemic immunotherapy.   `,
      `   aggressive transurethral resection of the prostate followed by BCG.   `,
      `  radical cystectomy and urethrectomy with neoadjuvant chemotherapy.  `,
      `  whole pelvic radiation.  `,
      `   radical prostatectomy.   `,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [2],
    ansText: `Rationale: The prognosis of primary prostatic urethral carcinoma is strongly associated with depth of invasion into the prostate. Those with superficial or lamina propria invasion can often be managed with transurethral resection and BCG; however, those with tumors invasive into the stroma require aggressive treatment. Radical cystoprostatectomy with urethrectomy and preoperative chemotherapy is the best choice.  `,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `   When a delayed urethrectomy is performed after radical cystectomy in a male, the most important technical consideration to minimize the risk of a local recurrence is:  `,
    q2: ``,
    q3: [],
    option: [
      ` removal of the entire distal urethra including the meatus.   `,
      `  bilateral groin dissections.    `,
      `total penectomy.    `,
      `  intraoperative ultrasound.  `,
      `   neoadjuvant radiation.   `,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [0],
    ansText: `Rationale: A delayed urethrectomy after radical cystectomy can be a challenging procedure. Critically, the entire urethra including the fossa navicularis and urethral meatus should be removed en bloc to eliminate the risk of a distal recurrence, even for proximal tumors. There is no role for routine inguinal lymphadenectomy, and penectomy is not required unless the urethral tumor is invasive into the deep structures of the penis.   `,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `   A condition that does not increase the risk of female urethral carcinoma is:  `,
    q2: ``,
    q3: [],
    option: [
      ` leukoplakia   `,
      `   bacterial vaginosis.   `,
      ` urethral diverticulum.   `,
      `   urethral stricture disease. `,
      `   human papillomavirus infection.   `,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [1],
    ansText: `Rationale: Urethral carcinoma is most likely caused by conditions that cause inflammation of the urethra, such as leukoplakia, urethral strictures, and HPV infection. Female urethral diverticula can increase the risk of urethral cancers, most commonly adenocarcinomas. Bacterial vaginosis has no known association with urethral cancer.   `,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `   The strongest prognostic factor for survival in female urethral cancer is:  `,
    q2: ``,
    q3: [],
    option: [
      ` tumor stage.   `,
      ` age at presentation.     `,
      `  histologic subtype.  `,
      `  multimodal treatment.  `,
      `    urinary retention.  `,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [0],
    ansText: `Rationale: The prognosis of female urethral cancer is strongly associated with stage at diagnosis. Tumors that arise from the proximal urethra tend to present at a more advanced stage. There is no known association between prognosis and histologic subtype, age at presentation, or presenting symptoms.  `,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `  A 68-year-old man presents with an anterior urethral tumor invasive into the corpora cavernosum. His tumor stage is:   `,
    q2: ``,
    q3: [],
    option: [` T1   `, `  T2a    `, `  T2b  `, `  T3  `, `   T4   `],
    optionStyleType: `st-lower-alpha`,
    answer: [3],
    ansText: `Rationale: Male anterior urethral cancer with invasion into the corpora cavernosum or anterior vagina are classified as T3 by the AJCC 8th Edition Staging System. Tumors invasive into the corpus spongiosum or periurethral tissue are classified as T2. The AJCC staging system does not have a T2a or T2b for urethral cancer.  `,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `   The best treatment for a small, exophytic cT2N0 female urethral carcinoma located near the urethral meatus is:  `,
    q2: ``,
    q3: [],
    option: [
      ` excision of the distal 2/3 of the urethra.   `,
      `   transvaginal biopsy followed by systemic chemotherapy.   `,
      `radical urethrectomy with bladder neck closure and ileovesicostomy.    `,
      ` chemoradiation   `,
      `  inguinal lymphadenectomy.    `,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [3],
    ansText: `Rationale: Small exophytic distal female urethral cancers can be effectively treated with surgical excision or radiation with or without chemotherapy. Radical urethrectomy can usually be avoided for distal tumors. The distal 1/3 of the female urethra can be safely excised without compromising urinary continence, but excision of the distal 2/3 will likely cause incontinence and is not a good option. There is currently no role for prophylactic inguinal lymphadenectomy for cN0 female distal urethral cancer. Most distal urethral tumors can be biopsied transurethrally.  `,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `   A 76-year-old female presents with a locally invasive proximal urethral tumor abutting the pubic symphysis. The treatment that would be inappropriate is:  `,
    q2: ``,
    q3: [],
    option: [
      ` radical cystectomy with pubectomy.   `,
      `  external beam radiation with systemic chemotherapy.    `,
      `  radical cystectomy with intraoperative radiation.  `,
      `  radiation monotherapy.  `,
      `  chemoradiation followed by surgical consolidation.    `,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [3],
    ansText: `Rationale: Proximal female urethral cancer often presents at an advanced stage, tends to be aggressive, and can have a poor prognosis. Therefore, aggressive local therapy is required, often in a multidisciplinary setting. Of the listed options, radiation monotherapy is inadequate treatment  `,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `  Two years after a radical cystectomy and ileal conduit in a male patient, a urethral wash cytology is positive for high-grade urothelial carcinoma. The next step is:   `,
    q2: ``,
    q3: [],
    option: [
      `repeat urethral wash cytology.    `,
      `  urethroscopy with biopsy.    `,
      `  radical urethrectomy.  `,
      `   pelvic MRI.   `,
      `urine cytology.`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [1],
    ansText: `Rationale: Urethral wash cytology may be beneficial for detecting early urethral recurrences after radical cystectomy. However, a positive cytology can be falsely positive and always requires confirmation with a biopsy prior to aggressive treatment or further imaging.  `,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `  All of the following are true about the male urethra EXCEPT:   `,
    q2: ``,
    q3: [],
    option: [
      `  the anterior urethra drains into the inguinal lymph nodes.  `,
      `   the glands of Littre line the anterior urethra.   `,
      `  the posterior urethra consists of the prostatic and membranous urethra.  `,
      `  the pseudostratified epithelium of the pendulous urethra transitions to glandular epithelium in the fossa navicularis.  `,
      `   anterior urethral cancers are more common in the bulbar urethra.   `,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [3],
    ansText: `Rationale: All of the listed options are true except “d,” as the urethral epithelium transitions to squamous, not glandular, in the fossa navicularis  `,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `   A 56-year-old-man presents with an invasive pendulous urethral squamous cell carcinoma with palpable inguinal lymph nodes bilaterally. Imaging is negative for distant metastasis. The best treatment is:  `,
    q2: ``,
    q3: [],
    option: [
      ` radiation monotherapy to the tumor and lymph nodes.   `,
      `  chemoradiation to the penis and groins followed by surgical consolidation.    `,
      `   radical penectomy. `,
      ` dynamic sentinel lymph node biopsy.   `,
      `    distal urethrectomy with 6 weeks of oral antibiotics.  `,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [1],
    ansText: `Rationale: Advanced staged urethral carcinoma requires aggressive multimodal treatment. Clinically positive inguinal lymph nodes with an invasive primary urethral cancer should be considered metastatic disease, therefore there is no role for antibiotics or sentinel lymph node biopsy. Radiation monotherapy and surgical monotherapy to the penis alone are both suboptimal treatment for invasive, cN+ penile cancers. Chemoradiation to the penis and groins with surgical consolidation is the best choice.  `,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
];
