var quiz = [
   
    {
        q: `During development, the ureteral lumen is obliterated and then recanalizes. Which of the following substances appears to be involved in this recanalization process?`,
        q2: ``,
        q3: [],
        option: [`Prostaglandin`, 
        `c-KIT`, 
        `Angiotensin`, 
        `Calcitonin gene-related peptide (CGRP) `, 
        `Acetylcholine `,
        ],
        optionFeedback: [``,
          ``,
          ``,
          ``,
          ``],
        optionStyleType: `st-lower-alpha`,
        answer: [2],
        ansText: `Rationale: At a point during development, the ureteral lumen is obliterated and then recanalizes. It appears that angiotensin, acting through the AT2 receptor, is involved in the recanalization process. Knockout mice for the ATR2 gene have congenital anomalies of the kidney and urinary tract, which include multicystic dysplastic kidneys, megaureters, and ureteropelvic junction (UPJ) obstructions.`,
        state: `notAnswered`,
        userAnswered: []
      ,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`        ,
        type: `MCSS`},
      
      {
        q: `The resting membrane potential (RMP) is primarily determined by the distribution of which of the following ions across the cell membrane and the preferential permeability of the cell membrane to that ion?`,
        q2: ``,
        q3: [],
        option: [`Potassium`, 
        `Sodium`, 
        `Calcium`, 
        `Chloride `, 
        ` Barium`,
        ],
        optionFeedback: [``,
          ``,
          ``,
          ``,
          ``],
        optionStyleType: `st-lower-alpha`,
        answer: [0],
        ansText: `Rationale: When a ureteral muscle cell is in a nonexcited or resting state, the electrical potential difference across the cell membrane, the transmembrane potential, is referred to as the <b><i>resting membrane potential.</i></b> The RMP is determined primarily by the distribution of potassium ions (K<sup>+</sup>) across the cell membrane and by the permeability of the membrane to potassium ions.`,
        state: `notAnswered`,
        userAnswered: []
      ,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`        ,
        type: `MCSS`},
      

      {
        q: `With excitation of the ureteral muscle cell, an action potential is formed. Which of the following pairs of ions are primarily responsible for the upstroke of the action potential?`,
        q2: ``,
        q3: [],
        option: [`Potassium and calcium`, 
        `Sodium and chloride`, 
        `Calcium and sodium`, 
        ` Potassium and sodium`, 
        `Calcium and chloride `,
        ],
        optionFeedback: [``,
          ``,
          ``,
          ``,
          ``],
        optionStyleType: `st-lower-alpha`,
        answer: [2],
        ansText: `Rationale: When the ureteral cell is excited, its membrane loses its preferential permeability to K<sup>+</sup> and becomes more permeable to calcium ions (Ca<sup>2+</sup>) that move inward across the cell membrane, primarily through L-type Ca<sup>2+</sup> channels, and give rise to the upstroke of the action potential.`,
        state: `notAnswered`,
        userAnswered: []
              ,
        type: `MCSS`},
      

      {
        q: `Which of the following must be phosphorylated for smooth muscle contraction to occur?`,
        q2: ``,
        q3: [],
        option: [`Actin`, 
        `Myosin`, 
        `Calmodulin`, 
        `Calcium `, 
        `Calcium `,
        ],
        optionFeedback: [``,
          ``,
          ``,
          ``,
          ``],
        optionStyleType: `st-lower-alpha`,
        answer: [1],
        ansText: `Rationale: The most widely accepted theory suggests that phosphorylation of myosin is involved in the contractile process.`,
        state: `notAnswered`,
        userAnswered: []
      ,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`        ,
        type: `MCSS`},
      

      {
        q: `The primary site for intracellular storage of calcium is:`,
        q2: ``,
        q3: [],
        option: [`mitochondria`, 
        `caveolae`, 
        `the nucleolus.`, 
        `actin `, 
        ` the endoplasmic reticulum.`,
        ],
        optionFeedback: [``,
          ``,
          ``,
          ``,
          ``],
        optionStyleType: `st-lower-alpha`,
        answer: [4],
        ansText: `Rationale: Calcium release from tightly bound storage sites (i.e., the endoplasmic or sarcoplasmic reticulum) increases the Ca<sup><b>2+</b></sup> concentration in the sarcoplasm.`,
        state: `notAnswered`,
        userAnswered: []
      ,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`        ,
        type: `MCSS`},
      

      {
        q: `The second messenger involved in β-adrenergic agonist-induced ureteral relaxation is:`,
        q2: ``,
        q3: [],
        option: [`cyclic adenosine monophosphate (cAMP).`, 
        `cyclic guanosine monophosphate (cGMP).`, 
        `nitric oxide.`, 
        ` inositol 1,4,5-triphosphate (IP<sub>3</sub>).`, 
        `diacylglycerol (DG). `,
        ],
        optionFeedback: [``,
          ``,
          ``,
          ``,
          ``],
        optionStyleType: `st-lower-alpha`,
        answer: [0],
        ansText: `Rationale: Cyclic AMP is believed to mediate the relaxing effects of β-adrenergic agonists in a variety of smooth muscles. `,
        state: `notAnswered`,
        userAnswered: []
              ,
        type: `MCSS`},
      

      {
        q: `The enzyme that degrades cyclic GMP is:`,
        q2: ``,
        q3: [],
        option: [`guanylyl cyclase.`, 
        `myosin light-chain kinase.`, 
        `phosphodiesterase`, 
        `phospholipase C. `, 
        ` nitric oxide synthase (NOS).`,
        ],
        optionFeedback: [``,
          ``,
          ``,
          ``,
          ``],
        optionStyleType: `st-lower-alpha`,
        answer: [2],
        ansText: `Rationale: Both cyclic AMP and cyclic GMP can cause smooth muscle relaxation. Cyclic GMP is synthesized from GTP by the enzyme guanylyl cyclase and is degraded to 5′-GMP by a phosphodiesterase.`,
        state: `notAnswered`,
        userAnswered: []
              ,
        type: `MCSS`},
      

      {
        q: `The enzyme that degrades cyclic AMP is:`,
        q2: ``,
        q3: [],
        option: [`adenylyl cyclase.`, 
        `myosin light-chain kinase.`, 
        `phosphodiesterase`, 
        ` phospholipase C.`, 
        ` NOS`,
        ],
        optionFeedback: [``,
          ``,
          ``,
          ``,
          ``],
        optionStyleType: `st-lower-alpha`,
        answer: [2],
        ansText: `Rationale: Phosphodiesterases degrade both cyclic AMP and cyclic GMP. It has been demonstrated in the canine ureter that a variety of inhibitors can preferentially inhibit the breakdown of one or the other cyclic nucleotide.`,
        state: `notAnswered`,
        userAnswered: []
              ,
        type: `MCSS`},
      

      {
        q: `Nitric oxide causes smooth muscle relaxation. In doing so, it activates which of the following enzymes?`,
        q2: ``,
        q3: [],
        option: [`Guanylyl cyclase`, 
        `Myosin light-chain kinase`, 
        `Phosphodiesterase`, 
        `Phospholipase C `, 
        ` NOS`,
        ],
        optionFeedback: [``,
          ``,
          ``,
          ``,
          ``],
        optionStyleType: `st-lower-alpha`,
        answer: [0],
        ansText: `Rationale: Nitric oxide released from the nerve activates the enzyme guanylyl cyclase in the smooth muscle cell, with the resultant conversion of guanosine triphosphate to cyclic GMP, with resultant smooth muscle relaxation.`,
        state: `notAnswered`,
        userAnswered: []
              ,
        type: `MCSS`},
      

      {
        q: `The substrate for NOS is:`,
        q2: ``,
        q3: [],
        option: [`cyclic AMP.`, 
        `cyclic GMP.`, 
        `GTP.`, 
        `Arginine `, 
        `<small>l</small>-Citrulline. `,
        ],
        optionFeedback: [``,
          ``,
          ``,
          ``,
          ``],
        optionStyleType: `st-lower-alpha`,
        answer: [3],
        ansText: `Rationale: NOS converts <small>l</small>-arginine to nitric oxide and <small>l</small>-citrulline in a reaction that requires NADPH.`,
        state: `notAnswered`,
        userAnswered: []
      ,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`        ,
        type: `MCSS`},
      

      {
        q: `Inducible NOS (iNOS) is:`,
        q2: ``,
        q3: [],
        option: [`nicotinamide adenine dinucleotide phosphate (NADPH) independent and calcium independent.`, 
        `NADPH independent and calcium dependent.`, 
        `NADPH dependent and calcium independent.`, 
        ` NADPH dependent and calcium dependent.`, 
        `nitric oxide dependent and calcium dependent. `,
        ],
        optionFeedback: [``,
          ``,
          ``,
          ``,
          ``],
        optionStyleType: `st-lower-alpha`,
        answer: [2],
        ansText: `Rationale: An inducible NOS isoform, iNOS, is NADPH dependent but Ca<sup>2+</sup> independent and has been identified in ureteral smooth muscle.`,
        state: `notAnswered`,
        userAnswered: []
              ,
        type: `MCSS`},
      

      {
        q: `The enzyme involved in the formation of DG (diacylglycerol) is:`,
        q2: ``,
        q3: [],
        option: [`adenylyl cyclase.`, 
        `guanylyl cyclase`, 
        `phosphodiesterase`, 
        `protein kinase C. `, 
        `phospholipase C. `,
        ],
        optionFeedback: [``,
          ``,
          ``,
          ``,
          ``],
        optionStyleType: `st-lower-alpha`,
        answer: [4],
        ansText: `Rationale: Some actions of α<sub>1</sub>-adrenergic and muscarinic cholinergic agonists and a number of other hormones, neurotransmitters, and biologic substances are associated with an increase in intracellular Ca<sup>2+</sup> and are related to changes in inositol lipid metabolism. These agonists combine with a receptor on the cell membrane, and the agonist-receptor complex, in turn, activates an enzyme, phospholipase C, that leads to the hydrolysis of polyphosphatidylinositol 4,5-bisphosphate, with the formation of two second messengers: IP<sub>3</sub> and DG.`,
        state: `notAnswered`,
        userAnswered: []
              ,
        type: `MCSS`},
      

      {
        q: `DG increases the activity of which enzyme?`,
        q2: ``,
        q3: [],
        option: [`Adenylyl cyclase`, 
        `Guanylyl cyclase`, 
        `Phosphodiesterase`, 
        ` Protein kinase C`, 
        `Phospholipase C `,
        ],
        optionFeedback: [``,
          ``,
          ``,
          ``,
          ``],
        optionStyleType: `st-lower-alpha`,
        answer: [4],
        ansText: `Rationale: DG binds to an enzyme, protein kinase C, causes its translocation to the cell membrane, and, by reducing the concentration of Ca<sup>2+</sup> required for protein kinase C activation, results in an increase in this enzyme’s activity.`,
        state: `notAnswered`,
        userAnswered: []
              ,
        type: `MCSS`},
      

      {
        q: `>An agent that prevents reuptake of norepinephrine in nerve terminals and thus potentiates and prolongs the activity of norepinephrine is:`,
        q2: ``,
        q3: [],
        option: [`tyrosine`, 
        `monoamine oxidase.`, 
        `imipramine`, 
        ` tetramethylammonium.`, 
        ` tetraethylammonium.`,
        ],
        optionFeedback: [``,
          ``,
          ``,
          ``,
          ``],
        optionStyleType: `st-lower-alpha`,
        answer: [2],
        ansText: `Rationale: The greatest percentage of the norepinephrine is actively taken up (reuptake or neuronal uptake) into the neuron. Neuronal reuptake regulates the duration for which norepinephrine is in contact with the innervated tissue and thus regulates the magnitude and duration of the catecholamine-induced response. Agents such as cocaine and imipramine (Tofranil, Mallinckrodt, Inc., Hazelwood, MO), which inhibit neuronal uptake, potentiate the physiologic response to norepinephrine.`,
        state: `notAnswered`,
        userAnswered: []
              ,
        type: `MCSS`},
      

      {
        q: `Norepinephrine is synthesized from:`,
        q2: ``,
        q3: [],
        option: [`tyrosine`, 
        `arginine`, 
        `choline`, 
        `cocaine `, 
        ` imipramine`,
        ],
        optionFeedback: [``,
          ``,
          ``,
          ``,
          ``],
        optionStyleType: `st-lower-alpha`,
        answer: [0],
        ansText: `Rationale: Norepinephrine, the chemical mediator responsible for adrenergic transmission, is synthesized in the neuron from tyrosine. `,
        state: `notAnswered`,
        userAnswered: []
              ,
        type: `MCSS`},
      

      {
        q: `Which of the following inhibits ureteral and renal pelvic contractile activity?`,
        q2: ``,
        q3: [],
        option: [`ubstance P`, 
        `Neurokinin A`, 
        `Neuropeptide K`, 
        ` Neuropeptide Y`, 
        ` CGRP`,
        ],
        optionFeedback: [``,
          ``,
          ``,
          ``,
          ``],
        optionStyleType: `st-lower-alpha`,
        answer: [4],
        ansText: `Rationale: Tachykinins and CGRP are neurotransmitters released from peripheral endings of sensory nerves. Tachykinins stimulate contractile activity, and CGRP inhibits contractile activity. `,
        state: `notAnswered`,
        userAnswered: []
              ,
        type: `MCSS`},
      

      {
        q: `The enzyme involved in prostaglandin synthesis is:`,
        q2: ``,
        q3: [],
        option: [`phospholipase C.`, 
        `cyclooxygenase`, 
        `protein kinase C.`, 
        `phosphodiesterase `, 
        ` adenosine triphosphate.`,
        ],
        optionFeedback: [``,
          ``,
          ``,
          ``,
          ``],
        optionStyleType: `st-lower-alpha`,
        answer: [1],
        ansText: `Rationale: The “primary” prostaglandins, PGE<sub>1</sub>, PGE<sub>2</sub>, and PGF<sub>2α</sub>, are synthesized from the fatty acid arachidonic acid by enzymatic reactions involving two cyclooxygenase (COX) isoforms, COX-1 and COX-2. `,
        state: `notAnswered`,
        userAnswered: []
              ,
        type: `MCSS`},
      

      {
        q: `Which of the following is a β-adrenergic agonist?`,
        q2: ``,
        q3: [],
        option: [`Cromakalim`, 
        `Physostigmine`, 
        `Propranolol`, 
        `Phenoxybenzamine `, 
        `Isoproterenol `,
        ],
        optionFeedback: [``,
          ``,
          ``,
          ``,
          ``],
        optionStyleType: `st-lower-alpha`,
        answer: [4],
        ansText: `Rationale: Isoproterenol, a β-adrenergic agonist, depresses smooth muscle contractility.`,
        state: `notAnswered`,
        userAnswered: []
              ,
        type: `MCSS`},
      

      {
        q: `Which of the following conditions must be present for urine to pass efficiently from the ureter into the bladder?`,
        q2: ``,
        q3: [],
        option: [`Intraluminal ureteral contractile pressure must be above 40 cm H<sub>2</sub>O.`, 
        `The ureterovesical junction (UVJ) must relax.`, 
        `Intraluminal ureteral contractile pressures must be greater than intravesical baseline pressures`, 
        ` Intravesical contractile pressures must be less than 40 cm H<sub>2</sub>O.`, 
        `The bladder must relax just before contraction of the ureter. `,
        ],
        optionFeedback: [``,
          ``,
          ``,
          ``,
          ``],
        optionStyleType: `st-lower-alpha`,
        answer: [2],
        ansText: `Rationale: The theoretical aspects of the mechanics of urine transport within the ureter were described in detail by Griffiths and Notschaele in 1983.<sup>a</sup> At normal flow rates, while the renal pelvis fills, a rise in renal pelvic pressure occurs, and urine is extruded into the upper ureter, which is initially in a collapsed state. The contraction wave originates in the most proximal portion of the ureter and moves the urine in front of it in a distal direction. The urine that had previously entered the ureter is formed into a bolus. <b>To propel the bolus of urine efficiently, the contraction wave must completely coapt the ureteral walls, and the pressure generated by this contraction wave provides the primary component of what is recorded by intraluminal pressure measurements.</b> The bolus that is pushed in front of the contraction wave lies almost entirely in a passive, noncontracting part of the ureter.
        <br /><br /><b>a</b> Sources referenced can be found in <i>Campbell-Walsh urology, ed 11</i>, on the <a href="http://Expert%20Consult%20website">Expert Consult website</a>.  `,
        state: `notAnswered`,
        userAnswered: []
              ,
        type: `MCSS`},
      

      {
        q: `What is normal baseline or resting ureteral pressure?`,
        q2: ``,
        q3: [],
        option: [`0 to 5 cm H<sub>2</sub>O`, 
        `5 to 10 cm H<sub>2</sub>O`, 
        `10 to 15 cm H<sub>2</sub>O`, 
        ` 15 to 20 cm H<sub>2</sub>O`, 
        `20 to 25 cm H<sub>2</sub>O `,
        ],
        optionFeedback: [``,
          ``,
          ``,
          ``,
          ``],
        optionStyleType: `st-lower-alpha`,
        answer: [0],
        ansText: `Rationale: Baseline or resting ureteral pressure is approximately 0 to 5 cm H<sub>2</sub>O.`,
        state: `notAnswered`,
        userAnswered: []
              ,
        type: `MCSS`},
      

      {
        q: `The Laplace equation expresses the relationship between the variables that affect intraluminal pressure. Which of the following conforms to the Laplace relationship?`,
        q2: ``,
        q3: [],
        option: [`Tension = (radius × wall thickness)/pressure`, 
        `Tension = (radius × pressure)/wall thickness`, 
        `Tension = (wall thickness × pressure)/radius`, 
        ` Pressure = (radius × wall thickness)/tension`, 
        `Pressure = (radius × tension)/wall thickness `,
        ],
        optionFeedback: [``,
          ``,
          ``,
          ``,
          ``],
        optionStyleType: `st-lower-alpha`,
        answer: [1],
        ansText: `Rationale: The Laplace equation expresses the relationship between the variables that affect intraluminal pressure: pressure = (tension × wall thickness)/radius. `,
        state: `notAnswered`,
        userAnswered: []
              ,
        type: `MCSS`},
      

      {
        q: `Factors that facilitate ureteral stone passage include:`,
        q2: ``,
        q3: [],
        option: [`increased hydrostatic pressures proximal to the calculus and relaxation of the ureter in the region of the stone.`, 
        `increased hydrostatic pressures proximal to the calculus and contraction of the ureter in the region of the stone.`, 
        `decreased hydrostatic pressures proximal to the calculus and relaxation of the ureter in the region of the stone.`, 
        ` decreased hydrostatic pressures proximal to the calculus and contraction of the ureter in the region of the stone.`, 
        `decreased contractile pressures proximal to the calculus and contraction of the ureter in the region of the stone. `,
        ],
        optionFeedback: [``,
          ``,
          ``,
          ``,
          ``],
        optionStyleType: `st-lower-alpha`,
        answer: [0],
        ansText: `Rationale: Two factors that appear to be most useful in facilitating stone passage are an increase in hydrostatic pressure proximal to a calculus and relaxation of the ureter in the region of the stone.`,
        state: `notAnswered`,
        userAnswered: []
              ,
        type: `MCSS`},
      

      {
        q: `Which of the following hormones inhibits ureteral contractility?`,
        q2: ``,
        q3: [],
        option: [`Bombesin`, 
        `Thyroxine`, 
        `Estrogen`, 
        ` Aldosterone`, 
        `Progesterone `,
        ],
        optionFeedback: [``,
          ``,
          ``,
          ``,
          ``],
        optionStyleType: `st-lower-alpha`,
        answer: [4],
        ansText: `Rationale: Several studies have shown an inhibitory effect of progesterone on ureteral function. Progesterone has been noted to increase the degree of ureteral dilatation during pregnancy and to retard the rate of disappearance of hydroureter in postpartum women. `,
        state: `notAnswered`,
        userAnswered: []
              ,
        type: `MCSS`},
      

      {
        q: `A drug that has efficacy in managing ureteral colic is:`,
        q2: ``,
        q3: [],
        option: [`bethanechol`, 
        `prostaglandin F<sub>2α</sub>`, 
        `physostigmine`, 
        ` indomethacin`, 
        ` ephedrine`,
        ],
        optionFeedback: [``,
          ``,
          ``,
          ``,
          ``],
        optionStyleType: `st-lower-alpha`,
        answer: [3],
        ansText: `Rationale: Indomethacin, by reducing pelviureteral pressure and thus pelviureteral wall tension, might eliminate some of the pain of renal colic that is dependent on distention of the upper urinary tract. `,
        state: `notAnswered`,
        userAnswered: []
              ,
        type: `MCSS`},
      

      {
        q: `Which of the following is a calcium-binding protein that plays a role in smooth muscle contraction?`,
        q2: ``,
        q3: [],
        option: [`Connexin 43`, 
        `Calmodulin`, 
        `Cromakalim`, 
        ` Survivin`, 
        `Myosin `,
        ],
        optionFeedback: [``,
          ``,
          ``,
          ``,
          ``],
        optionStyleType: `st-lower-alpha`,
        answer: [3],
        ansText: `Rationale: With excitation, there is a transient increase in the sarcoplasmic Ca<sup>2+</sup> concentration from its steady-state concentration of 10<sup>−8</sup> to 10<sup>−7</sup> M to a concentration of 10<sup>−6</sup> M or higher. At this higher concentration, Ca<sup>2+</sup> forms an active complex with the calcium-binding protein calmodulin. Calmodulin without Ca<sup>2+</sup> is inactive. The calcium-calmodulin complex activates a calmodulin-dependent enzyme, myosin light-chain kinase. The activated myosin light-chain kinase, in turn, catalyzes the phosphorylation of the 20,000-dalton light chain of myosin. Phosphorylation of the myosin light chain allows activation by actin of myosin Mg<sup>2+</sup>-ATPase activity, leading to hydrolysis of ATP and the development of smooth muscle tension or shortening.`,
        state: `notAnswered`,
        userAnswered: []
              ,
        type: `MCSS`},
      

      {
        q: `In the ureter, the resting or the contractile force developed at any given length depends on the direction in which the change in length is occurring. This is referred to as:`,
        q2: ``,
        q3: [],
        option: [`viscoelasticity`, 
        `creep`, 
        `hysteresis`, 
        ` stress relaxation.`, 
        ` compensatory relaxation.`,
        ],
        optionFeedback: [``,
          ``,
          ``,
          ``,
          ``],
        optionStyleType: `st-lower-alpha`,
        answer: [2],
        ansText: `Rationale: Because the ureter is a viscoelastic structure, the resting or contractile force developed at any given length depends on the direction in which change in length is occurring and on the rate of length change. This is referred to as <b><i>hysteresis</i></b>; for the ureter, at any given length, the resting force is less and contractile force is greater when the ureter is allowed to shorten than when the ureter is being stretched. `,
        state: `notAnswered`,
        userAnswered: []
              ,
        type: `MCSS`},
      

      {
        q: `>Which of the following is noted to be expressed before initiation of ureteral peristaltic activity?`,
        q2: ``,
        q3: [],
        option: [`Prostanoids`, 
        `Nitric oxide`, 
        `c-KIT`, 
        `Myosin light chain `, 
        `Phosphodiesterase `,
        ],
        optionFeedback: [``,
          ``,
          ``,
          ``,
          ``],
        optionStyleType: `st-lower-alpha`,
        answer: [2],
        ansText: `Rationale: This tyrosine kinase receptor is important in the development of pacemaker activity and peristalsis of the gut (Der-Silaphet et al., 1998). Pezzone and colleagues (2003) identified c-KIT-positive cells in the mouse ureter. The expression of c-KIT was noted to be upregulated in the embryonic murine ureter before its development of unidirectional peristaltic contractions (David et al., 2005). Incubation of isolated cultured embryonic murine ureters with antibodies that neutralize c-KIT activity alters ureteral morphology and inhibits unidirectional peristalsis. c-KIT-positive cells have been identified in the human ureter (Metzger et al., 2004).`,
        state: `notAnswered`,
        userAnswered: []
              ,
        type: `MCSS`},
      

      {
        q: `Ureteral pacemaker activity is amplified by:`,
        q2: ``,
        q3: [],
        option: [`prostanoids`, 
        `norepinephrine`, 
        `CGRP`, 
        `cyclic GMP. `, 
        ` potassium channel openers.`,
        ],
        optionFeedback: [``,
          ``,
          ``,
          ``,
          ``],
        optionStyleType: `st-lower-alpha`,
        answer: [3],
        ansText: `Rationale: The ionic conduction underlying pacemaker activity in the upper urinary tract is due to the opening and slow closure of voltage-activated L-type Ca<sup>2+</sup> channels, which are amplified by prostanoids (Santicioli et al., 1995a). This is opposed by the opening and closure of voltage and Ca<sup>2+</sup>-dependent K<sup>+</sup> channels. It has been suggested that prostaglandins and excitatory tachykinins, released from sensory nerves, help maintain autorhythmicity in the upper urinary tract through maintenance of Ca<sup>2+</sup> mobilization. Tetrodotoxin and blockers of the autonomic nervous system, both parasympathetic and sympathetic, have little effect on peristalsis, suggesting that autonomic neurotransmitters play little role in maintaining pyeloureteral motility. `,
        state: `notAnswered`,
        userAnswered: []
              ,
        type: `MCSS`},
      
    
     
]