var quiz = [
   
   
    {
        q: `Ureteropelvic junction (UPJ) obstruction in the neonate is most frequently found as a result of:`,
        q2: ``,
        q3: [],
        option: [`maternal-fetal ultrasonography.`, 
        `voiding cystourethrography.`, 
        `diuretic renography.`, 
        ` abdominal radiography.`, 
        `physical examination. `,
        ],
        optionFeedback: [``,
          ``,
          ``,
          ``,
          ``],
        optionStyleType: `st-lower-alpha`,
        answer: [0],
        ansText: `Rationale: The current widespread use of maternal ultrasonography has led to a dramatic increase in the number of asymptomatic newborns who are diagnosed with hydronephrosis, many of whom are subsequently found to have UPJ obstruction.`,
        state: `notAnswered`,
        userAnswered: []
      ,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`        ,
        type: `MCSS`},
      

      {
        q: `Which study is diagnostic for functional obstruction at the UPJ?`,
        q2: ``,
        q3: [],
        option: [`Retrograde pyelography`, 
        `Three-dimensional helical computed tomography (CT)`, 
        `Diuretic renography`, 
        ` Renal ultrasound`, 
        `Renal angiography `,
        ],
        optionFeedback: [``,
          ``,
          ``,
          ``,
          ``],
        optionStyleType: `st-lower-alpha`,
        answer: [2],
        ansText: `Rationale: Provocative testing with a diuretic urogram may allow accurate diagnosis of UPJ obstruction. Renal ultrasound, CT scan, and retrograde pyelogram give anatomic assessments of the UPJ without quantitatively assessing urinary drainage and function`,
        state: `notAnswered`,
        userAnswered: []
      ,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`        ,
        type: `MCSS`},
      

      {
        q: `A 62-year-old man presents with left flank pain. CT urography reveals delayed excretion and hydronephrosis to the level of a 2.5-cm calculus at the UPJ. Percutaneous stone extraction is accomplished without difficulty, but a postextraction nephrostogram reveals hydronephrosis to the level of the UPJ without residual stone. A follow-up nephrostogram 1 week later is unchanged. The best next step is:`,
        q2: ``,
        q3: [],
        option: [`removal of the nephrostomy tube.`, 
        `diuretic renography.`, 
        `CT angiography.`, 
        ` antegrade endopyelotomy`, 
        `Whitaker pressure-perfusion test. `,
        ],
        optionFeedback: [``,
          ``,
          ``,
          ``,
          ``],
        optionStyleType: `st-lower-alpha`,
        answer: [4],
        ansText: `Rationale: When doubt remains as to the clinical significance of a dilated collecting system, placement of percutaneous nephrostomy allows access for pressure perfusion studies. In the pressure perfusion test, first described by Whitaker in 1973 and then modified in 1978, the renal pelvis is perfused with normal saline or dilute radiographic contrast solution, and the pressure gradient across the presumed area of obstruction is determined. Renal pelvic pressures in excess of 15 to 22 cm H<sub>2</sub>O are highly suggestive of a functional obstruction. Although diuretic renography is useful for diagnosis as well, the Whitaker test is ideal for this situation because a nephrostomy tube is already in situ.`,
        state: `notAnswered`,
        userAnswered: []
      ,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`        ,
        type: `MCSS`},
      

      {
        q: `A 27-year-old woman has right flank pain, and her diuretic renography reveals UPJ obstruction and a differential renal function of 75:25 (L:R). The next best step is:`,
        q2: ``,
        q3: [],
        option: [`CT angiography.`, 
        `stent placement.`, 
        `endopyelotomy`, 
        ` laparoscopic pyeloplasty.`, 
        ` laparoscopic nephrectomy.`,
        ],
        optionFeedback: [``,
          ``,
          ``,
          ``,
          ``],
        optionStyleType: `st-lower-alpha`,
        answer: [1],
        ansText: `Rationale: Evidence from several investigators indicates that crossing vessels lower the success rate of endopyelotomy. When such patients were culled from the pool of candidates available for treatment of UPJ obstruction, endopyelotomy success rates improved in most studies. A CT angiography would be necessary to assess this. However, laparoscopic pyeloplasty would be a straightforward minimally invasive option for this young patient. The kidney has too much function to remove at this stage`,
        state: `notAnswered`,
        userAnswered: []
      ,
	type: `MCSS`,
	type: `MCSS`        ,
        type: `MCSS`},
      

      {
        q: `The highest failure rate in treating UPJ obstruction is associated with:`,
        q2: ``,
        q3: [],
        option: [`antegrade endopyelotomy.`, 
        `retrograde ureteroscopic endopyelotomy.`, 
        `balloon dilation.`, 
        `pyeloplasty `, 
        ` cautery balloon incision.`,
        ],
        optionFeedback: [``,
          ``,
          ``,
          ``,
          ``],
        optionStyleType: `st-lower-alpha`,
        answer: [2],
        ansText: `Rationale: McClinton reported long-term follow-up data on balloon dilation of the UPJ, finding a success rate of only 42%, which was significantly lower than the initial publications would indicate. `,
        state: `notAnswered`,
        userAnswered: []
              ,
        type: `MCSS`},
      

      {
        q: `The most appropriate location for endoscopic incision of a proximal ureteral stricture is:`,
        q2: ``,
        q3: [],
        option: [`lateral`, 
        `anterior`, 
        `medial`, 
        `posterior `, 
        ` anterolateral`,
        ],
        optionFeedback: [``,
          ``,
          ``,
          ``,
          ``],
        optionStyleType: `st-lower-alpha`,
        answer: [0],
        ansText: `Rationale: Proximal ureteral strictures are incised laterally, similar to UPJ strictures. Posterior incision is offered to UPJ obstruction patients who have failed open pyeloplasty. Distal strictures are incised anteriorly, as are strictures of the middle ureter.`,
        state: `notAnswered`,
        userAnswered: []
              ,
        type: `MCSS`},
      

      {
        q: `The best treatment option for a patient with a functional left ureteroenteric anastomotic stricture is:`,
        q2: ``,
        q3: [],
        option: [`metallic stent.`, 
        `balloon dilation`, 
        `laser endoureterotomy.`, 
        ` cautery wire balloon incision.`, 
        `open repair. `,
        ],
        optionFeedback: [``,
          ``,
          ``,
          ``,
          ``],
        optionStyleType: `st-lower-alpha`,
        answer: [4],
        ansText: `Rationale: Several studies have linked poor outcomes with endoscopic management of left ureteroenteric strictures. This may be a result of diminished blood flow to the ureter because the left ureter requires more mobilization than the right side at the time of diversion. Although metallic stents show promise in limited studies, using open repair, reports demonstrate an 80% success.`,
        state: `notAnswered`,
        userAnswered: []
              ,
        type: `MCSS`},
      

      {
        q: `The most common cause of retroperitoneal fibrosis is:`,
        q2: ``,
        q3: [],
        option: [`methysergide`, 
        `infection`, 
        `lymphoma`, 
        ` breast cancer.`, 
        `immune-mediated aortitis. `,
        ],
        optionFeedback: [``,
          ``,
          ``,
          ``,
          ``],
        optionStyleType: `st-lower-alpha`,
        answer: [4],
        ansText: `Rationale: Growing evidence indicates that the majority of cases of retroperitoneal fibrosis are, in fact, immune-mediated aortitis. Regardless, the other conditions are relatively rare causes of retroperitoneal fibrosis. `,
        state: `notAnswered`,
        userAnswered: []
              ,
        type: `MCSS`},
      

      {
        q: `Retrocaval ureter results from:`,
        q2: ``,
        q3: [],
        option: [`persistence of posterior cardinal veins.`, 
        `persistence of anterior cardinal veins.`, 
        `duplication of inferior vena cava.`, 
        ` aberrance of lumbar veins.`, 
        `retroaortic renal veins. `,
        ],
        optionFeedback: [``,
          ``,
          ``,
          ``,
          ``],
        optionStyleType: `st-lower-alpha`,
        answer: [0],
        ansText: `Rationale: Retrocaval ureter results from the persistence of the posterior cardinal veins.`,
        state: `notAnswered`,
        userAnswered: []
              ,
        type: `MCSS`},
      

      {
        q: `Transperitoneal laparoscopic pyeloplasty:`,
        q2: ``,
        q3: [],
        option: [`is used rarely compared with the retroperitoneal approach.`, 
        `does not require water-tight, tension-free anastomosis.`, 
        `provides more working space than in the retroperitoneal approach.`, 
        `provides unfamiliar anatomy. `, 
        `does not require an external surgical drain. `,
        ],
        optionFeedback: [``,
          ``,
          ``,
          ``,
          ``],
        optionStyleType: `st-lower-alpha`,
        answer: [2],
        ansText: `Rationale: Transperitoneal laparoscopic pyeloplasty provides a larger working space relative to a retroperitoneoscopic approach. Together with more familiar anatomy, the transperitoneal approach is used most commonly in the laparoscopic urologic community to date.`,
        state: `notAnswered`,
        userAnswered: []
              ,
        type: `MCSS`},
      

      {
        q: `Surgical repair of UPJ obstruction requires:`,
        q2: ``,
        q3: [],
        option: [`a funnel-shaped transition between the renal pelvis and ureter.`, 
        `dependent drainage.`, 
        `water-tight anastomosis.`, 
        ` tension-free anastomosis.`, 
        `all of the above. `,
        ],
        optionFeedback: [``,
          ``,
          ``,
          ``,
          ``],
        optionStyleType: `st-lower-alpha`,
        answer: [4],
        ansText: `Rationale: For any surgical repair of UPJ obstruction, the resultant anastomosis should be widely patent and completed in a watertight fashion without tension. In addition, the reconstructed UPJ should allow a funnel-shaped transition between the pelvis and the ureter that is in a position of dependent drainage. `,
        state: `notAnswered`,
        userAnswered: []
              ,
        type: `MCSS`},
      

      {
        q: `Contraindications for transureteroureterostomy include a history of:`,
        q2: ``,
        q3: [],
        option: [`retroperitoneal fibrosis.`, 
        `urothelial malignancy.`, 
        `nephrolithiasis`, 
        ` a, b, and c.`, 
        ` b and c.`,
        ],
        optionFeedback: [``,
          ``,
          ``,
          ``,
          ``],
        optionStyleType: `st-lower-alpha`,
        answer: [3],
        ansText: `Rationale: Relative contraindications include history of nephrolithiasis, retroperitoneal fibrosis, urothelial malignancy, chronic pyelonephritis, and abdominopelvic radiation.`,
        state: `notAnswered`,
        userAnswered: []
      ,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`        ,
        type: `MCSS`},
      

      {
        q: `A 25-year-old man presents with right flank pain. He underwent a laparoscopic pyeloplasty, which failed within 1 year. Consequently, he underwent failed endopyelotomy. A CT scan shows a small, intrarenal pelvis and moderate cortical loss in the right kidney with a normal-appearing left kidney. A renogram reveals 35% differential function on the affected side, and a diuretic study demonstrates functional obstruction (&gt;30 minutes). The next step is:`,
        q2: ``,
        q3: [],
        option: [`chronic internal ureteral stent.`, 
        `ileal ureter.`, 
        `Davis intubated ureterotomy.`, 
        ` ureterocalicostomy`, 
        `renal autotransplantation. `,
        ],
        optionFeedback: [``,
          ``,
          ``,
          ``,
          ``],
        optionStyleType: `st-lower-alpha`,
        answer: [3],
        ansText: `Rationale: Direct anastomosis of the proximal ureter to the lower calyceal system is a well-accepted salvage technique for the failed pyeloplasty and small renal pelvis.`,
        state: `notAnswered`,
        userAnswered: []
              ,
        type: `MCSS`},
      

      {
        q: `Spiral flap procedures for UPJ obstruction are used:`,
        q2: ``,
        q3: [],
        option: [`to bridge a shorter-length stenosis.`, 
        `to treat crossing vessels.`, 
        `to bridge a longer-length stenosis.`, 
        `for a small, intrarenal pelvis. `, 
        `only in the presence of greater than 30% ipsilateral renal function. `,
        ],
        optionFeedback: [``,
          ``,
          ``,
          ``,
          ``],
        optionStyleType: `st-lower-alpha`,
        answer: [2],
        ansText: `Rationale: Flap procedures can be useful in situations involving a relatively long segment of ureteral narrowing or stricture. Of the various flap procedures, a spiral flap can bridge a strictured or narrow area of longer length. The flap procedures are not appropriate in the setting of crossing vessels.`,
        state: `notAnswered`,
        userAnswered: []
              ,
        type: `MCSS`},
      

      {
        q: `Foley Y-V-plasty is a suitable approach when encountering:`,
        q2: ``,
        q3: [],
        option: [`high ureteral insertion.`, 
        `small intrarenal pelvis.`, 
        `anterior crossing vessel.`, 
        `duplication of collecting system. `, 
        `redundant renal pelvis. `,
        ],
        optionFeedback: [``,
          ``,
          ``,
          ``,
          ``],
        optionStyleType: `st-lower-alpha`,
        answer: [0],
        ansText: `Rationale: The Foley Y-V-plasty is designed for repair of a UPJ obstruction secondary to a high ureteral insertion. It is specifically contraindicated when transposition of lower pole vessels is necessary. In situations requiring concomitant reduction of redundant renal pelvis, this technique is also of little value.`,
        state: `notAnswered`,
        userAnswered: []
              ,
        type: `MCSS`},
      

      {
        q: `>Which type of pyeloplasty is suitable when there is an aberrant crossing vessel?`,
        q2: ``,
        q3: [],
        option: [`Foley Y-V-plasty`, 
        `Culp-DeWeerd spiral flap`, 
        `Dismembered pyeloplasty`, 
        ` Scardino-Prince vertical flap`, 
        `Ligation and transection of the crossing vessel `,
        ],
        optionFeedback: [``,
          ``,
          ``,
          ``,
          ``],
        optionStyleType: `st-lower-alpha`,
        answer: [2],
        ansText: `Rationale: In the presence of crossing aberrant or accessory lower pole renal vessels associated with UPJ obstruction, a dismembered pyeloplasty is the only method to allow transposition of the UPJ in relation to these vessels.`,
        state: `notAnswered`,
        userAnswered: []
              ,
        type: `MCSS`},
      

      {
        q: `Ileal ureter can be performed when the patient has:`,
        q2: ``,
        q3: [],
        option: [`renal insufficiency (serum creatinine &gt; 2 mg/dL).`, 
        `inflammatory bowel disease.`, 
        `bladder dysfunction.`, 
        `radiation enteritis. `, 
        ` small intrarenal pelvis`,
        ],
        optionFeedback: [``,
          ``,
          ``,
          ``,
          ``],
        optionStyleType: `st-lower-alpha`,
        answer: [4],
        ansText: `Rationale: In ileal segment usage, a small intrarenal pelvis is not contraindicated and an ileocalycostomy can be performed successfully.`,
        state: `notAnswered`,
        userAnswered: []
              ,
        type: `MCSS`},
      

      {
        q: `A 55-year-old woman underwent left transperitoneal laparoscopic dismembered pyeloplasty over an internal ureteral stent. An abdominal drain was placed at surgery, and there was minimal drain output during the first 24 hours after surgery. Within 3 hours after Foley catheter removal, the patient’s nurse noted a significant amount of fluid coming out of the drain site. The next step is to:`,
        q2: ``,
        q3: [],
        option: [`change dressings frequently and continue observation.`, 
        `replace the urethral catheter.`, 
        `restrict fluid intake.`, 
        `remove the surgical drain. `, 
        `change the ureteral stent. `,
        ],
        optionFeedback: [``,
          ``,
          ``,
          ``,
          ``],
        optionStyleType: `st-lower-alpha`,
        answer: [1],
        ansText: `Rationale: If the drain output increases following the removal of the Foley catheter, the catheter should be replaced for several days to avoid vesicoureteral reflux up the stent in the operated ureter and decrease urinary extravasation.`,
        state: `notAnswered`,
        userAnswered: []
              ,
        type: `MCSS`},
      

      {
        q: `In performing a psoas hitch, additional bladder mobility can be achieved by transection of the:`,
        q2: ``,
        q3: [],
        option: [`contralateral superior vesical artery.`, 
        `ipsilateral inferior vesical artery.`, 
        `contralateral inferior vesical artery.`, 
        ` ipsilateral superior vesical artery.`, 
        ` ipsilateral gonadal artery.`,
        ],
        optionFeedback: [``,
          ``,
          ``,
          ``,
          ``],
        optionStyleType: `st-lower-alpha`,
        answer: [0],
        ansText: `Rationale: In psoas hitch, transection of the contralateral superior vesical artery can be helpful to bridge the gap to the ipsilateral ureteral end, thereby achieving tension-free anastomosis.`,
        state: `notAnswered`,
        userAnswered: []
              ,
        type: `MCSS`},
      

      {
        q: `A 40-year-old woman with a history of hypertension and recurrent nephrolithiasis presents with a 5-cm proximal right ureteral stricture following an iatrogenic injury in a recent abdominal surgery. She has had an indwelling right nephrostomy tube for more than 6 months. Her baseline serum creatinine is 2.5 mg/dL. Renal scan shows split function of 65% in the right kidney. Her bladder capacity is found to be less than 300 mL. The next step is:`,
        q2: ``,
        q3: [],
        option: [`ureteroureterostomy`, 
        `Boari flap`, 
        `transureteroureterostomy`, 
        `ileal ureteral substitution. `, 
        `autotransplantation `,
        ],
        optionFeedback: [``,
          ``,
          ``,
          ``,
          ``],
        optionStyleType: `st-lower-alpha`,
        answer: [4],
        ansText: `Rationale: Ureteroureterostomy is inappropriate for a 5-cm upper ureteral defect. Boari flap is inappropriate for a small bladder capacity. Transureteroureterostomy is contraindicated in the patient with a history of recurrent nephrolithiasis. Ileal ureter is contraindicated in the presence of elevated serum creatinine above 2 mg/dL. Autotransplant is appropriate for this particular patient.`,
        state: `notAnswered`,
        userAnswered: []
              ,
        type: `MCSS`},
      

      {
        q: `During a psoas hitch, the structure particularly susceptible to injury is the:`,
        q2: ``,
        q3: [],
        option: [`obturator nerve.`, 
        `iliohypogastric nerve.`, 
        `ilioinguinal nerve.`, 
        ` sacral nerve.`, 
        `genitofemoral nerve. `,
        ],
        optionFeedback: [``,
          ``,
          ``,
          ``,
          ``],
        optionStyleType: `st-lower-alpha`,
        answer: [4],
        ansText: `Rationale: The genitofemoral nerve courses over the psoas muscle. `,
        state: `notAnswered`,
        userAnswered: []
              ,
        type: `MCSS`},
      

      {
        q: `The technique that does not require normal bladder capacity, drainage, and function is the:`,
        q2: ``,
        q3: [],
        option: [`ileal ureteral substitution.`, 
        `psoas hitch.`, 
        `ureteroneocystostomy`, 
        `endoscopic incision of transmural ureter. `, 
        `Boari flap. `,
        ],
        optionFeedback: [``,
          ``,
          ``,
          ``,
          ``],
        optionStyleType: `st-lower-alpha`,
        answer: [3],
        ansText: `Rationale: Normal bladder function without significant outlet obstruction is crucial to the success of ileal ureteral substitution, psoas hitch, Boari flap, and ureteroneocystostomy.`,
        state: `notAnswered`,
        userAnswered: []
              ,
        type: `MCSS`},
      

      {
        q: ` see <a class="lightboxcallout" img-ref="image_fig_89_1">Fig. 89.1</a> A 72-year-old man with malaise has this CT scan. The serum creatinine is mildly elevated. What is the best diagnosis?`,
        q2: ``,
        q3: [],
        option: [`Retroperitoneal fibrosis`, 
        `Retroperitoneal hematoma`, 
        `Tuberculosis`, 
        ` Retroperitoneal sarcoma`, 
        `Perianeurysmal fibrosis `,
        ],
        optionFeedback: [``,
          ``,
          ``,
          ``,
          ``],
        optionStyleType: `st-lower-alpha`,
        answer: [0],
        ansText: `Rationale: There is increased soft tissue in the retroperitoneum, which obscures and effaces the planes between the inferior vena cava and the aorta. Tuberculosis causes calcification and stricturing in the kidneys and collecting systems, and tuberculous iliopsoas abscess extends along the iliopsoas muscles. Retroperitoneal hematoma and sarcoma are not centered solely around the aorta and the inferior vena cava. In perianeurysmal fibrosis, a retroperitoneal fibrosis-like picture occurs in association with an abdominal aortic aneurysm; the aorta is of normal caliber in this case`,
        state: `notAnswered`,
        userAnswered: []
              ,
        type: `MCSS`},
      
    
     
]