var quiz = [
   
    {
        q: `Which of the following vessels has the least direct contribution to the arterial supply of the vas deferens?`,
        q2: ``,
        q3: [],
        option: [`Deferential artery`, 
        `Internal spermatic artery`, 
        `Superior vesicle artery`, 
        `Inferior epigastric artery `, 
        `Inferior epididymal artery `,
        ],
        optionFeedback: [``,
          ``,
          ``,
          ``,
          ``],
        optionStyleType: `st-lower-alpha`,
        answer: [2],
        ansText: `Rationale: The superior vesicle artery does not supply the vas deferens, whereas all of the other arteries listed may have a branch to the vas deferens.`,
        state: `notAnswered`,
        userAnswered: []
      ,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`        ,
        type: `MCSS`},
      {
        q: `The best reason for using the no-scalpel vasectomy technique is:`,
        q2: ``,
        q3: [],
        option: [`it has a higher sterilization rate than standard vasectomy with incision.`, 
        `patients are rendered sterile in less time.`, 
        `it is easier to learn than the standard technique.`, 
        `it results in a lower rate of complications, including hematoma and infection. `, 
        ` it results in a higher rate of reversibility.`,
        ],
        optionFeedback: [``,
          ``,
          ``,
          ``,
          ``],
        optionStyleType: `st-lower-alpha`,
        answer: [4],
        ansText: `Rationale: This method eliminates the scalpel incision, results in fewer hematomas and infections, and leaves a much smaller wound than conventional methods of accessing the vas deferens for vasectomy.`,
        state: `notAnswered`,
        userAnswered: []
      ,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`        ,
        type: `MCSS`},
  
      {
        q: `The no-scalpel technique for vasectomy reduces the rate of:`,
        q2: ``,
        q3: [],
        option: [`hematoma`, 
        `vasectomy failures.`, 
        `recanalization`, 
        ` injury to testicular artery.`, 
        `chronic orchialgia. `,
        ],
        optionFeedback: [``,
          ``,
          ``,
          ``,
          ``],
        optionStyleType: `st-lower-alpha`,
        answer: [0],
        ansText: `Rationale: The no-scalpel technique significantly decreases the rate of hematomas, infections, and pain during the procedure.`,
        state: `notAnswered`,
        userAnswered: []
      ,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`        ,
        type: `MCSS`},
  
      {
        q: `Vasectomy failure rate when both the abdominal and testicular ends of the divided vas deferens are occluded with hemoclips is:`,
        q2: ``,
        q3: [],
        option: [`less than 1%.`, 
        `5% to 10%.`, 
        `10% to 20%.`, 
        ` 20% to 30%.`, 
        ` 50% to 60%.`,
        ],
        optionFeedback: [``,
          ``,
          ``,
          ``,
          ``],
        optionStyleType: `st-lower-alpha`,
        answer: [0],
        ansText: `Rationale: 
        <!--<b>a. Less than 1%.</b>--> Vasectomy failure rate when both the abdominal and testicular ends of the divided vas deferens are occluded with hemoclips is less than 1%.`,
        state: `notAnswered`,
        userAnswered: []
              ,
        type: `MCSS`},
  
      {
        q: `The technical aspect shown to decrease vasectomy failure rates the most is:`,
        q2: ``,
        q3: [],
        option: [`no-scalpel technique.`, 
        `conventional technique.`, 
        `fascial interposition of dartos fascia between the divided ends of the vas deferens.`, 
        ` occluding both ends of the divided vas deferens with hemoclips.`, 
        ` occluding both ends of the divided vas deferens thermally with the use of intraluminal cautery.`,
        ],
        optionFeedback: [``,
          ``,
          ``,
          ``,
          ``],
        optionStyleType: `st-lower-alpha`,
        answer: [2],
        ansText: `Rationale: Interposition of dartos fascia between the divided ends of the vas deferens is a technique for occlusion that has been reported to reduce the recanalization rate to nearly zero. `,
        state: `notAnswered`,
        userAnswered: []
              ,
        type: `MCSS`},
  
      {
        q: `The technical aspect when performing vasectomy to make vasectomy reversal easier in the future is:`,
        q2: ``,
        q3: [],
        option: [`no-scalpel technique`, 
        `not excising a long segment of vas deferens.`, 
        `dividing the vas deferens as close to the epididymis as possible.`, 
        `occluding both ends of the divided vas deferens with hemoclips. `, 
        ` occluding both ends of the divided vas deferens thermally with the use of intraluminal cautery.`,
        ],
        optionFeedback: [``,
          ``,
          ``,
          ``,
          ``],
        optionStyleType: `st-lower-alpha`,
        answer: [1],
        ansText: `Rationale: The technical aspects when performing vasectomy to make vasectomy reversal easier in the future include not excising a long segment of vas deferens, dividing the vas deferens approximately 3 cm cephalad to the cauda of the epididymis in the straight portion of the vas deferens, and transecting the vas deferens, followed by low-voltage cautery occlusion and then by fascial interposition.`,
        state: `notAnswered`,
        userAnswered: []
      ,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`        ,
        type: `MCSS`},
  
      {
        q: `Vasectomy has been established as associated with:`,
        q2: ``,
        q3: [],
        option: [`prostate cancer.`, 
        `dementia`, 
        `cardiovascular disease.`, 
        ` atherosclerosis`, 
        `a 10% incidence of chronic scrotal pain. `,
        ],
        optionFeedback: [``,
          ``,
          ``,
          ``,
          ``],
        optionStyleType: `st-lower-alpha`,
        answer: [4],
        ansText: `Rationale: Vasectomy does not have an established association with prostate cancer, dementia, cardiovascular disease, or atherosclerosis, although it has been associated with a 10% incidence of chronic scrotal pain. `,
        state: `notAnswered`,
        userAnswered: []
              ,
        type: `MCSS`},
  
      {
        q: `What is the estimated percentage of men who develop antisperm antibodies after vasectomy?`,
        q2: ``,
        q3: [],
        option: [`0% to 20%`, 
        `20% to 40%`, 
        `40% to 60%`, 
        ` 60% to 80%`, 
        `Greater than 80% `,
        ],
        optionFeedback: [``,
          ``,
          ``,
          ``,
          ``],
        optionStyleType: `st-lower-alpha`,
        answer: [3],
        ansText: `Rationale: Vasectomy disrupts the blood–testis barrier, resulting in detectable levels of serum antisperm antibodies in 60% to 80% of men.`,
        state: `notAnswered`,
        userAnswered: []
      ,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`        ,
        type: `MCSS`},
  
      {
        q: `Which of the following is an indication for repeat vasectomy?`,
        q2: ``,
        q3: [],
        option: [`Painless sperm granuloma`, 
        `Motile sperm found in semen analysis 3 months after vasectomy`, 
        `Nonmotile sperm found in semen analysis 3 months after vasectomy `, 
        ` Persistent testicular pain 3 months after vasectomy`,
        `All of the above`,
        ],
        optionFeedback: [``,
          ``,
          ``,
          ``,
          ``],
        optionStyleType: `st-lower-alpha`,
        answer: [1],
        ansText: `Rationale: If any motile sperm are found in the ejaculate 3 months after vasectomy, consideration should be given to repeating the procedure.`,
        state: `notAnswered`,
        userAnswered: []
              ,
        type: `MCSS`},
  
      {
        q: `Pressure-induced injury following vasectomy occurs in:`,
        q2: ``,
        q3: [],
        option: [`the testis.`, 
        `the ejaculatory duct.`, 
        `the epididymis.`, 
        `the vas deferens. `, 
        `the seminal vesicles. `,
        ],
        optionFeedback: [``,
          ``,
          ``,
          ``,
          ``],
        optionStyleType: `st-lower-alpha`,
        answer: [2],
        ansText: `Rationale: The brunt of pressure-induced damage after vasectomy falls on the epididymis and efferent ductules. `,
        state: `notAnswered`,
        userAnswered: []
              ,
        type: `MCSS`},
  
      {
        q: `In the management of chronic orchialgia, which of the following statements is TRUE?`,
        q2: ``,
        q3: [],
        option: [`Imaging studies are not indicated.`, 
        `Varicocele is not a significant contributor of chronic scrotal pain.`, 
        `Orchiectomy usually relieves the pain.`, 
        ` Denervation of the cord may offer relief in selected cases.`, 
        `Diagnostic epididymal puncture should be performed to rule out chronic bacterial epididymitis. `,
        ],
        optionFeedback: [``,
          ``,
          ``,
          ``,
          ``],
        optionStyleType: `st-lower-alpha`,
        answer: [3],
        ansText: `Rationale: Microsurgical total denervation of the spermatic cord is a procedure used with reported success in several small series.`,
        state: `notAnswered`,
        userAnswered: []
              ,
        type: `MCSS`},
  
      {
        q: `Which of the following statements is TRUE regarding hydrocelectomy?`,
        q2: ``,
        q3: [],
        option: [`Hematoma is the least frequent complication.`, 
        `The Jaboulay bottleneck operation is associated with a high recurrence rate.`, 
        `The Lord plication is an ideal operation for long-standing postinfectious hydroceles.`, 
        `Sclerotherapy is often the treatment of choice for young men of reproductive age. `, 
        ` The Jaboulay bottleneck operation is associated with a low recurrence rate.`,
        ],
        optionFeedback: [``,
          ``,
          ``,
          ``,
          ``],
        optionStyleType: `st-lower-alpha`,
        answer: [4],
        ansText: `Rationale: The Jaboulay bottleneck operation, in which the sac edges are sewn together behind the cord, reduces the chance of recurrence caused by reapposition of the edges of the hydrocele sac.`,
        state: `notAnswered`,
        userAnswered: []
              ,
        type: `MCSS`},
  
      {
        q: `A non-transilluminating, nontender mass is noted in the epididymis on physical examination and confirmed to be solid by sonography. What is the most likely diagnosis?`,
        q2: ``,
        q3: [],
        option: [`Epididymal cyst`, 
        `Adenomatoid tumor`, 
        `Spermatocele`, 
        `Testicular tumor `, 
        `Hydrocele `,
        ],
        optionFeedback: [``,
          ``,
          ``,
          ``,
          ``],
        optionStyleType: `st-lower-alpha`,
        answer: [1],
        ansText: `Rationale: Most nontransilluminable solid epididymal masses are benign adenomatoid tumors.`,
        state: `notAnswered`,
        userAnswered: []
              ,
        type: `MCSS`},
  
      {
        q: `Men who were treated with epididymectomy for chronic epididymitis responded the most favorably if:`,
        q2: ``,
        q3: [],
        option: [`there was a palpable epididymal abnormality.`, 
        `there was no palpable abnormality, but there were sonographic changes of the epididymis.`, 
        `there were no palpable abnormalities and no sonographic changes of the epididymis.`, 
        `they had improvement of pain with spermatic cord block. `, 
        `none of the above apply. `,
        ],
        optionFeedback: [``,
          ``,
          ``,
          ``,
          ``],
        optionStyleType: `st-lower-alpha`,
        answer: [0],
        ansText: `Rationale: A retrospective review of men who underwent epididymectomy for chronic epididymitis showed that outcomes were best when the patient had a palpable epididymal abnormality on physical examination. Men in this study without a palpable abnormality, but with sonographic changes, had slightly worse outcomes, and those with neither a palpable abnormality nor a demonstrable ultrasonographic abnormality did not improve with epididymectomy.`,
        state: `notAnswered`,
        userAnswered: []
              ,
        type: `MCSS`},
  
      {
        q: `Which of the following statements is TRUE regarding retractile testes in adults?`,
        q2: ``,
        q3: [],
        option: [`As in children, surgical repair is never indicated.`, 
        `A dartos pouch orchidopexy is the treatment of choice.`, 
        `Simple three-stitch orchiopexy of the tunica albuginea to the dartos, as for torsion prophylaxis, is effective in preventing retraction.`, 
        ` Bilateral orchiopexy is necessary for a unilateral retractile testis.`, 
        `Coexisting varicocele is common. `,
        ],
        optionFeedback: [``,
          ``,
          ``,
          ``,
          ``],
        optionStyleType: `st-lower-alpha`,
        answer: [1],
        ansText: `Rationale: Creation of a dartos pouch will keep the testis well down into the scrotum and permanently prevent retraction. `,
        state: `notAnswered`,
        userAnswered: []
              ,
        type: `MCSS`},
  
      {
        q: `The most appropriate approach to a long-standing, thick-walled, loculated hydrocele is:`,
        q2: ``,
        q3: [],
        option: [`excision of the hydrocele sac.`, 
        `the Jaboulay bottleneck technique.`, 
        `the Lord plication technique.`, 
        ` the inguinal approach.`, 
        ` sclerotherapy`,
        ],
        optionFeedback: [``,
          ``,
          ``,
          ``,
          ``],
        optionStyleType: `st-lower-alpha`,
        answer: [0],
        ansText: `Rationale: Excising the hydrocele is recommended for long-standing, thick-walled, loculated hydroceles.`,
        state: `notAnswered`,
        userAnswered: []
              ,
        type: `MCSS`},
  
      {
        q: `In men with chronic orchitis without an identifiable bacterial pathogen, antibiotics:`,
        q2: ``,
        q3: [],
        option: [`decrease the length of symptoms.`, 
        `improve the severity of symptoms.`, 
        `decrease the length of time to full activity.`, 
        `are steadily being prescribed more frequently empirically. `, 
        `none of the above apply. `,
        ],
        optionFeedback: [``,
          ``,
          ``,
          ``,
          ``],
        optionStyleType: `st-lower-alpha`,
        answer: [3],
        ansText: `Rationale: Despite evidence that up to 75% of patients with epididymitis/orchitis do not have an identifiable bacterial urinary tract infection concomitantly with their clinical epididymitis, antibiotics are routinely given. Empirical antibiotic administration in the absence of positive urine cultures has been steadily increasing, from 75% to 95% between the years of 1965 and 2005 and is not indicated.`,
        state: `notAnswered`,
        userAnswered: []
              ,
        type: `MCSS`},
  
      {
        q: `When a clinically palpable varicocele is encountered in a patient with orchialgia, varicocelectomy will resolve the pain:`,
        q2: ``,
        q3: [],
        option: [`10% of the time`, 
        `25% of the time.`, 
        `50% of the time.`, 
        `75% of the time. `, 
        ` 90% of the time.`,
        ],
        optionFeedback: [``,
          ``,
          ``,
          ``,
          ``],
        optionStyleType: `st-lower-alpha`,
        answer: [2],
        ansText: `Rationale: When a clinically palpable varicocele is encountered in a patient with orchialgia, varicocelectomy will resolve the pain 50% of the time.`,
        state: `notAnswered`,
        userAnswered: []
              ,
        type: `MCSS`},
  
      {
        q: `What is the embryologic origin of the seminal vesicles?`,
        q2: ``,
        q3: [],
        option: [`Müllerian duct`, 
        `Ectodermal ridge`, 
        `Distal mesonephric duct`, 
        ` Swelling of the distal paramesonephric duct`, 
        `Neural crest cells `,
        ],
        optionFeedback: [``,
          ``,
          ``,
          ``,
          ``],
        optionStyleType: `st-lower-alpha`,
        answer: [2],
        ansText: `Rationale: The seminal vesicle develops as a dorsolateral bulbous swelling of the distal mesonephric duct at approximately 12 fetal weeks.`,
        state: `notAnswered`,
        userAnswered: []
              ,
        type: `MCSS`},
  
      {
        q: `>What percentage of the ejaculate volume is made up of seminal vesicle secretions?`,
        q2: ``,
        q3: [],
        option: [`5% to 10%`, 
        `20% to 30%`, 
        `60% to 80%`, 
        `90% `, 
        `The seminal vesicle does not contribute to the seminal plasma volume `,
        ],
        optionFeedback: [``,
          ``,
          ``,
          ``,
          ``],
        optionStyleType: `st-lower-alpha`,
        answer: [2],
        ansText: `Rationale: The secretions from the seminal vesicle contribute 60% to 80% of the ejaculate volume`,
        state: `notAnswered`,
        userAnswered: []
              ,
        type: `MCSS`},
  
      {
        q: `What artery is the major blood supply to the seminal vesicle?`,
        q2: ``,
        q3: [],
        option: [`Hypogastric`, 
        `Vesiculodeferential artery`, 
        `Inferior vesicl`, 
        `Internal iliac `, 
        `Deep dorsal penile `,
        ],
        optionFeedback: [``,
          ``,
          ``,
          ``,
          ``],
        optionStyleType: `st-lower-alpha`,
        answer: [1],
        ansText: `Rationale: The blood supply to the seminal vesicle is from the vesiculodeferential artery, a branch of the superior vesical artery.`,
        state: `notAnswered`,
        userAnswered: []
              ,
        type: `MCSS`},
  
      {
        q: `Decreased T1 signal intensity on MRI, along with increased T2 intensity of seminal vesicles, is indicative of which process?`,
        q2: ``,
        q3: [],
        option: [`Inflammation of the seminal vesicles`, 
        `Hemorrhage within the seminal vesicles`, 
        `Seminal vesicle tumors`, 
        `Seminal vesicle cysts `, 
        `Normal seminal vesicles `,
        ],
        optionFeedback: [``,
          ``,
          ``,
          ``,
          ``],
        optionStyleType: `st-lower-alpha`,
        answer: [0],
        ansText: `Rationale: Seminal vesiculitis shows decreased signal intensity on the T1-weighted image, whereas the T2-weighted image intensity is higher than that of both fat and the normal seminal vesicle`,
        state: `notAnswered`,
        userAnswered: []
              ,
        type: `MCSS`},
  
      {
        q: `Agenesis of the seminal vesicle is associated with significant ipsilateral renal anomalies. What is the embryologic reason for this?`,
        q2: ``,
        q3: [],
        option: [`A genetic defect links seminal vesicle agenesis to renal agenesis.`, 
        `A mutation occurs in the cystic fibrosis transmembrane regulator gene.`, 
        `There was an insult to the mesonephric duct at approximately 12 weeks’ gestation.`, 
        `There was an embryologic insult to the mesonephric duct earlier than 7 weeks’ gestation. `, 
        `There is no association between agenesis of the seminal vesicle and ipsilateral renal anomalies. `,
        ],
        optionFeedback: [``,
          ``,
          ``,
          ``,
          ``],
        optionStyleType: `st-lower-alpha`,
        answer: [3],
        ansText: `Rationale: Unilateral agenesis of the seminal vesicles has an incidence of 0.6% to 1% and may be associated with unilateral absence of the vas deferens, as well as ipsilateral renal anomalies.`,
        state: `notAnswered`,
        userAnswered: []
              ,
        type: `MCSS`},
  
      {
        q: `What disorder is frequently associated with bilateral agenesis of the seminal vesicles?`,
        q2: ``,
        q3: [],
        option: [`Cystic fibrosis`, 
        `Kartagener syndrome`, 
        `Young syndrome`, 
        `Kallmann syndrome `, 
        ` Klinefelter syndrome`,
        ],
        optionFeedback: [``,
          ``,
          ``,
          ``,
          ``],
        optionStyleType: `st-lower-alpha`,
        answer: [0],
        ansText: `Rationale: Of men with bilateral absence of the vas deferens or seminal vesicles, 70% to 80% carry the genetic mutation associated with cystic fibrosis. Conversely, 80% to 95% of men with cystic fibrosis have bilateral absence of the vas deferens or seminal vesicles.`,
        state: `notAnswered`,
        userAnswered: []
              ,
        type: `MCSS`},
  
      {
        q: `What causes the majority of seminal vesicle cysts?`,
        q2: ``,
        q3: [],
        option: [`Ejaculatory duct stone`, 
        `Obstruction of the ejaculatory duct`, 
        `Inflammation`, 
        `Renal agenesis `, 
        `Trisomy 21 `,
        ],
        optionFeedback: [``,
          ``,
          ``,
          ``,
          ``],
        optionStyleType: `st-lower-alpha`,
        answer: [1],
        ansText: `Rationale: Cysts of the seminal vesicles may be either congenital or acquired and are thought to be due to obstruction of the ejaculatory duct.`,
        state: `notAnswered`,
        userAnswered: []
              ,
        type: `MCSS`},
  
      {
        q: `>What is the most common type of malignant neoplasm found in seminal vesicles?`,
        q2: ``,
        q3: [],
        option: [`Primary adenocarcinoma`, 
        `Sarcoma`, 
        `Cystosarcoma phyllodes`, 
        `Metastatic tumors `, 
        ` Amyloidosis`,
        ],
        optionFeedback: [``,
          ``,
          ``,
          ``,
          ``],
        optionStyleType: `st-lower-alpha`,
        answer: [3],
        ansText: `Rationale: Very few primary tumors of the seminal vesicles have been reported. It is more common for carcinoma of the bladder, prostate, or rectum, or lymphoma to secondarily involve the seminal vesicles.`,
        state: `notAnswered`,
        userAnswered: []
              ,
        type: `MCSS`},
  
      {
        q: `What is the best initial test for a suspected seminal vesicle abnormality?`,
        q2: ``,
        q3: [],
        option: [`Computed tomography (CT)`, 
        `Transrectal ultrasonography`, 
        `Magnetic resonance imaging (MRI)`, 
        `Fine-needle biopsy `, 
        `Vasography `,
        ],
        optionFeedback: [``,
          ``,
          ``,
          ``,
          ``],
        optionStyleType: `st-lower-alpha`,
        answer: [1],
        ansText: `Rationale: Transrectal ultrasonography is the preferred initial test for seminal vesicle abnormality because of its low invasiveness, ease of performance, and ability to perform concomitant transrectal biopsies. `,
        state: `notAnswered`,
        userAnswered: []
              ,
        type: `MCSS`},
  
      {
        q: `What is the best method to differentiate a benign from malignant seminal vesicle mass?`,
        q2: ``,
        q3: [],
        option: [`Biopsy of the lesion`, 
        `Contrast medium-enhanced CT`, 
        `Gadolinium-enhanced MRI`, 
        `Transrectal ultrasonography `, 
        ` Rectal examination`,
        ],
        optionFeedback: [``,
          ``,
          ``,
          ``,
          ``],
        optionStyleType: `st-lower-alpha`,
        answer: [0],
        ansText: `Rationale: Transrectal ultrasonography and biopsy of the seminal vesicle mass is accurate and easily accomplished.`,
        state: `notAnswered`,
        userAnswered: []
              ,
        type: `MCSS`},
  
      {
        q: `What is the best surgical approach to a congenital lesion of the seminal vesicle?`,
        q2: ``,
        q3: [],
        option: [`The perineal route because this has the quickest recovery.`, 
        `The transcoccygeal route because these are usually large lesions.`, 
        `The laparoscopic route so that the ipsilateral kidney can be dealt with concomitantly and recovery may be shorter.`, 
        `The paravesical route because this has a lower incidence of postoperative erectile dysfunction. `, 
        ` The transvesical route because rectal injury is much less likely.`,
        ],
        optionFeedback: [``,
          ``,
          ``,
          ``,
          ``],
        optionStyleType: `st-lower-alpha`,
        answer: [2],
        ansText: `Rationale: Although data are limited for laparoscopic excision of benign seminal vesicle disease alone, this approach appears to afford superb visualization with minimal postoperative morbidity and shorter hospitalization, compared with the open surgical alternatives. `,
        state: `notAnswered`,
        userAnswered: []
              ,
        type: `MCSS`},
  
      {
        q: `What is the best indication for the transcoccygeal approach to the seminal vesicle?`,
        q2: ``,
        q3: [],
        option: [`Need for exploration of the ipsilateral kidney`, 
        `Patient with previous suprapubic and/or perineal surgery`, 
        `Patient wishing to maintain potency`, 
        ` Patient with bilateral large seminal vesicle lesions`, 
        `Patient with metastatic tumor to the seminal vesicle `,
        ],
        optionFeedback: [``,
          ``,
          ``,
          ``,
          ``],
        optionStyleType: `st-lower-alpha`,
        answer: [1],
        ansText: `Rationale: In individuals for whom the perineal or supine position may be difficult to maintain, or for those who have had multiple suprapubic or perineal surgeries, the transcoccygeal approach may be useful.`,
        state: `notAnswered`,
        userAnswered: []
              ,
        type: `MCSS`},
  
      {
        q: `In a patient with a seminal vesicle abscess, the treatment of choice is:`,
        q2: ``,
        q3: [],
        option: [`laparoscopic unroofing.`, 
        `transvesical excision of the seminal vesicle.`, 
        `aspiration and antibiotic instillation.`, 
        ` endoscopic unroofing by deep transurethral resection.`, 
        ` retropubic approach to unroof the abscess.`,
        ],
        optionFeedback: [``,
          ``,
          ``,
          ``,
          ``],
        optionStyleType: `st-lower-alpha`,
        answer: [3],
        ansText: `Rationale: If the abscess is in the portion of the seminal vesicle adjacent to the prostate, a deep transurethral resection into the prostatic substance, just distal to the bladder neck at the 5-o’clock or 7-o’clock position, may be effective in relieving the problem. However, a CT-guided aspiration and drain placement is becoming the preferred least-traumatic option.`,
        state: `notAnswered`,
        userAnswered: []
              ,
        type: `MCSS`},
      
     
]