var quiz = [
   
    {
        q: `A 70-kg man will have the greatest change in glomerular filtration rate (GFR) when the creatinine changes from:`,
        q2: ``,
        q3: [],
        option: [`0.9 to 1.2 mg/dL.`, 
        `1.8 to 1.9 mg/dL`, 
        `3.2 to 3.9 mg/dL.`, 
        `4.1 to 4.7 mg/dL. `, 
        ` 7.9 to 11 mg/dL.`,
        ],
        optionFeedback: [``,
          ``,
          ``,
          ``,
          ``],
        optionStyleType: `st-lower-alpha`,
        answer: [0],
        ansText: `Rationale: The relationship between serum creatinine is not linear. <b>Above a GFR of 60 mL/min, changes in serum creatinine are minimal.</b> The change in serum creatinine from 0.9 to 1.2 may be associated with a large drop in GFR (120 to 60 mL/min). Below a GFR of 60, proportional increments in creatinine are associated with smaller changes in GFR. This is most notable at very high creatinine levels.`,
        state: `notAnswered`,
        userAnswered: []
      ,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`        ,
        type: `MCSS`},
      

      {
        q: `In patients with occult renal artery stenosis, angiotensin-converting enzyme (ACE) inhibitors cause acute renal failure (ARF) due to:`,
        q2: ``,
        q3: [],
        option: [`sodium retention.`, 
        `increased antidiuretic hormone.`, 
        `afferent arteriolar vasoconstriction.`, 
        ` efferent arteriolar vasodilation.`, 
        `decreased sympathetic nervous system activity. `,
        ],
        optionFeedback: [``,
          ``,
          ``,
          ``,
          ``],
        optionStyleType: `st-lower-alpha`,
        answer: [3],
        ansText: `Rationale: Angiotensin II has selectively greater vasoconstrictor effects on the efferent than on the afferent arteriole, whereas vasodilatory prostaglandins cause afferent arteriolar vasodilatation. Drugs that block angiotensin II synthesis (ACE inhibitors), block angiotensin II receptor binding (angiotensin II receptor antagonists), or inhibit vasodilatory prostaglandin synthesis (nonsteroidal anti-inflammatory drugs) may cause ARF in selected clinical settings. `,
        state: `notAnswered`,
        userAnswered: []
      ,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`        ,
        type: `MCSS`},
      

      {
        q: `Six days after partial nephrectomy in a solitary kidney, the patient is oliguric. Large amounts of fluid are coming from the flank drain. The serum creatinine increases from 1.7 to 3.2 mg/dL. The next step in management is:`,
        q2: ``,
        q3: [],
        option: [`renal angiography.`, 
        `computed tomography (CT) scan with intravenous contrast.`, 
        `renal scan.`, 
        `immediate surgical exploration. `, 
        `magnetic resonance imaging (MRI). `,
        ],
        optionFeedback: [``,
          ``,
          ``,
          ``,
          ``],
        optionStyleType: `st-lower-alpha`,
        answer: [2],
        ansText: `Rationale: There are several ways to confirm urinary extravasation. These include assessment of drain fluid for creatinine, intravenous administration of a vital dye excreted by the kidneys (such as indigo carmine or methylene blue), and radiographic demonstration of a fistula (isotope renography, retrograde pyelography, cystography, computed tomography). Renal scan can assess perfusion and also demonstrate extravasation.`,
        state: `notAnswered`,
        userAnswered: []
      ,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`        ,
        type: `MCSS`},
      

      {
        q: `After a 7-hour-long, complex urethral reconstruction performed in the extended lithotomy position, a patient has severe thigh and buttock pain. The creatinine phosphokinase (CPK) is dramatically elevated. The next step is:`,
        q2: ``,
        q3: [],
        option: [`dopamine infusion.`, 
        `plasmapheresis`, 
        `dobutamine infusion.`, 
        `forced alkaline diuresis. `, 
        `dialysis `,
        ],
        optionFeedback: [``,
          ``,
          ``,
          ``,
          ``],
        optionStyleType: `st-lower-alpha`,
        answer: [3],
        ansText: `Rationale: The combination of renal hypoperfusion and the nephrotoxic insult of myoglobin or hemoglobin within the proximal tubule may result in ATN. Early recognition of this disorder is crucial, because a forced alkaline diuresis is indicated to minimize nephrotoxicity. `,
        state: `notAnswered`,
        userAnswered: []
              ,
        type: `MCSS`},
      

      {
        q: `The sentinel cellular change in renal ischemic injury is:`,
        q2: ``,
        q3: [],
        option: [`loss of cell polarity.`, 
        `depletion of adenosine triphosphate (ATP).`, 
        `alteration of Na<sup>+</sup> metabolism.`, 
        ` increased intracellular Ca<sup>2+</sup>.`, 
        `increased oxidant stress. `,
        ],
        optionFeedback: [``,
          ``,
          ``,
          ``,
          ``],
        optionStyleType: `st-lower-alpha`,
        answer: [1],
        ansText: `Rationale: The sentinel biochemical event in renal ischemia is the depletion of ATP, which is the major energy currency for cellular work.`,
        state: `notAnswered`,
        userAnswered: []
      ,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`        ,
        type: `MCSS`},
      

      {
        q: `The renal structure at greatest risk for ischemic injury is the:`,
        q2: ``,
        q3: [],
        option: [`afferent arteriole.`, 
            `cortical collecting duct.`, 
        
        `juxtaglomerular apparatus.`, 
        `straight segment (S3) proximal tubule. `, 
        `distal convoluted tubule. `,
        ],
        optionFeedback: [``,
          ``,
          ``,
          ``,
          ``],
        optionStyleType: `st-lower-alpha`,
        answer: [3],
        ansText: `Rationale: The S3 segment of the proximal tubule is associated with the greatest ischemic damage. Other structures that sustain injury in this region include the medullary thick ascending limb, which is metabolically active and rich in the energy-requiring Na<sup>+</sup>, K<sup>+</sup>-ATPase.`,
        state: `notAnswered`,
        userAnswered: []
              ,
        type: `MCSS`},
      

      {
        q: `A patient with acute kidney injury (AKI) has a urinary sodium of 10 mEq/L, urinary osmolality of 650, and a renal failure index of &lt; 1. Urinalysis shows 10 to 20 red blood cells (RBCs) per high-power field (HPF), 3 to 5 white blood cells per HPF, 2 + proteinuria, and RBC casts. The most likely diagnosis is:`,
        q2: ``,
        q3: [],
        option: [`acute tubular necrosis (ATN).`, 
        `prerenal azotemia.`, 
        `acute glomerulonephritis.`, 
        ` acute interstitial nephritis.`, 
        `obstruction `,
        ],
        optionFeedback: [``,
          ``,
          ``,
          ``,
          ``],
        optionStyleType: `st-lower-alpha`,
        answer: [2],
        ansText: `Rationale: <b>A low fractional excretion of sodium (or renal failure index) may be associated with either prerenal azotemia or acute glomerulonephritis.</b> These entities could be separated clinically by examination of the urinalysis results. Conditions associated with prerenal azotemia would have a bland urinalysis, whereas proteinuria, RBCs, and RBC casts would be seen with acute glomerulonephritis.`,
        state: `notAnswered`,
        userAnswered: []
              ,
        type: `MCSS`},
      

      {
        q: `When AKI is first recognized in a patient, the initial therapeutic intervention should be to:`,
        q2: ``,
        q3: [],
        option: [`begin low-dose dopamine.`, 
        `administer a cardiac inotropic agent.`, 
        `restore adequate circulating blood volume.`, 
        `administer a loop diuretic. `, 
        `begin a mannitol infusion. `,
        ],
        optionFeedback: [``,
          ``,
          ``,
          ``,
          ``],
        optionStyleType: `st-lower-alpha`,
        answer: [2],
        ansText: `Rationale: During the initial stages, a trial of parenteral hydration with isotonic fluids may correct ARF secondary to prerenal causes.`,
        state: `notAnswered`,
        userAnswered: []
              ,
        type: `MCSS`},
      

      {
        q: `Loop diuretics are of benefit in the management of AKI due to:`,
        q2: ``,
        q3: [],
        option: [`improved patient survival.`, 
        `decreased metabolic demand.`, 
        `decreased hypoxic cell swelling.`, 
        `free radical scavenging. `, 
        `increased renal vascular resistance. `,
        ],
        optionFeedback: [``,
          ``,
          ``,
          ``,
          ``],
        optionStyleType: `st-lower-alpha`,
        answer: [1],
        ansText: `Rationale: Loop diuretics decrease active NaCl transport in the thick ascending limb of Henle and thereby limit energy requirements in the metabolically active segment, which often bears the greatest ischemic insult.`,
        state: `notAnswered`,
        userAnswered: []
              ,
        type: `MCSS`},
      

      {
        q: `The major risk of MRI with gadolinium in patients with advanced chronic kidney disease (CKD) is:`,
        q2: ``,
        q3: [],
        option: [`nephrotoxicity`, 
        `anaphylaxis`, 
        `nephrogenic systemic fibrosis.`, 
        ` seizures`, 
        `hepatotoxicity `,
        ],
        optionFeedback: [``,
          ``,
          ``,
          ``,
          ``],
        optionStyleType: `st-lower-alpha`,
        answer: [2],
        ansText: `Rationale: Recently, gadolinium-based contrast agents have been associated with the development of nephrogenic systemic fibrosis. At-risk patients include those with advanced CKD. It is important that these compounds be given to these patients only after careful consideration of the indication for the study.`,
        state: `notAnswered`,
        userAnswered: []
              ,
        type: `MCSS`},
      

      {
        q: `Dopamine therapy in AKI:`,
        q2: ``,
        q3: [],
        option: [`causes efferent arteriolar vasodilation.`, 
        `is recommended for routine use after renal transplantation.`, 
        `is effective due to improved cardiac function.`, 
        `is an unproven treatment. `, 
        ` improves patient survival.`,
        ],
        optionFeedback: [``,
          ``,
          ``,
          ``,
          ``],
        optionStyleType: `st-lower-alpha`,
        answer: [3],
        ansText: `Rationale: Results of clinical studies have not conclusively proved that dopamine infusion improves ARF.`,
        state: `notAnswered`,
        userAnswered: []
              ,
        type: `MCSS`},
      

      {
        q: `A patient with AKI after partial nephrectomy has a serum potassium of 6.9 mEq/L and widening of the QRS complex on electrocardiogram (ECG). The initial step in management should be:`,
        q2: ``,
        q3: [],
        option: [`intravenous (IV) calcium.`, 
        `IV insulin and glucose.`, 
        `sodium polystyrene sulfonate resin (Kayexalate).`, 
        ` IV furosemide.`, 
        ` dialysis`,
        ],
        optionFeedback: [``,
          ``,
          ``,
          ``,
          ``],
        optionStyleType: `st-lower-alpha`,
        answer: [0],
        ansText: `Rationale: Priorities for treatment of acute hyperkalemia with electrocardiographic changes include stabilizing the electrical membrane of the cardiac conduction system, which may be accomplished with the use of intravenous calcium salts. These have an immediate effect and a rather short duration of action.`,
        state: `notAnswered`,
        userAnswered: []
              ,
        type: `MCSS`},
      

      {
        q: `A patient with a serum creatinine level of 2.7 mg/dL requires renal angiography. The best way to protect renal function is:`,
        q2: ``,
        q3: [],
        option: [`saline diuresis`, 
        `pre-study mannitol.`, 
        `furosemide before study`, 
        `dopamine throughout the study. `, 
        `atrial natriuretic factor before study. `,
        ],
        optionFeedback: [``,
          ``,
          ``,
          ``,
          ``],
        optionStyleType: `st-lower-alpha`,
        answer: [0],
        ansText: `Rationale: A study by Solomon and coworkers confirmed that prestudy intravenous hydration with saline was crucial in limiting the nephrotoxic effect of radiocontrast agents in patients with preexisting azotemia. The addition of either a loop diuretic or mannitol did not improve outcome.`,
        state: `notAnswered`,
        userAnswered: []
              ,
        type: `MCSS`},
      

      {
        q: `In response to a reduction in renal mass, a number of events occur within the kidney that include all of the following except:`,
        q2: ``,
        q3: [],
        option: [`activation of the sympathetic nervous system.`, 
        `hyperfiltration`, 
        `glomerular hypertrophy.`, 
        `intrarenal vascular occlusion. `, 
        ` interstitial fibrosis.`,
        ],
        optionFeedback: [``,
          ``,
          ``,
          ``,
          ``],
        optionStyleType: `st-lower-alpha`,
        answer: [3],
        ansText: `Rationale: In response to reduced nephron mass, a mosaic of events occurs linking sympathetic nervous system activation, renal structural remodeling, altered gene expression and regulation, and several regulatory mechanisms for progression. `,
        state: `notAnswered`,
        userAnswered: []
              ,
        type: `MCSS`},
      

      {
        q: `A 65-year-old man has a radical nephrectomy. The estimated GFR by the Modification of Diet in Renal Disease (MDRD) equation is 52 mL/min. Follow-up should include:`,
        q2: ``,
        q3: [],
        option: [`low-protein diet.`, 
        `renal transplant evaluation.`, 
        `nephrology consult for stage 3 CKD.`, 
        `reassessment of kidney function every few months. `, 
        `loop diuretics. `,
        ],
        optionFeedback: [``,
          ``,
          ``,
          ``,
          ``],
        optionStyleType: `st-lower-alpha`,
        answer: [2],
        ansText: `Rationale: According to the National Kidney Foundation (K/DOQI) guidelines, this patient indeed has stage 3 CKD. A nephrologist should be following this patient and appropriate preventive strategies instituted for preservation of kidney function and minimizing the impact of comorbidities. `,
        state: `notAnswered`,
        userAnswered: []
              ,
        type: `MCSS`},
      

      {
        q: `A hypertensive patient with CKD should take an ACE inhibitor drug to:`,
        q2: ``,
        q3: [],
        option: [`improve renal function.`, 
        `prevent progressive kidney disease.`, 
        `improve cardiac ejection fraction.`, 
        `enhance glycemic control. `, 
        `control blood lipids. `,
        ],
        optionFeedback: [``,
          ``,
          ``,
          ``,
          ``],
        optionStyleType: `st-lower-alpha`,
        answer: [1],
        ansText: `Rationale: ACE inhibitors work by hemodynamic and nonhemodynamic mechanisms to slow the progression of renal disease.`,
        state: `notAnswered`,
        userAnswered: []
              ,
        type: `MCSS`},
      

      {
        q: `The most common cause for end-stage renal disease (ESRD) in the United States is:`,
        q2: ``,
        q3: [],
        option: [`focal segmental glomerulosclerosis (FSGS).`, 
        `membranoproliferative glomerulonephritis (type 2).`, 
        `membranous glomerulonephritis.`, 
        ` autosomal dominant polycystic kidney disease.`, 
        ` diabetes mellitus`,
        ],
        optionFeedback: [``,
          ``,
          ``,
          ``,
          ``],
        optionStyleType: `st-lower-alpha`,
        answer: [4],
        ansText: `Rationale: Diabetes mellitus and hypertension account for the greatest percentage of cases, followed by glomerular diseases (e.g., FSGS, membranous glomerulonephritis), and then secondary glomerulonephritis associated with systemic diseases (e.g., systemic lupus erythematosus, Wegener granulomatosis).`,
        state: `notAnswered`,
        userAnswered: []
      ,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`        ,
        type: `MCSS`},
      

      {
        q: `The patient at lowest risk for progressive CKD is:`,
        q2: ``,
        q3: [],
        option: [`diabetic, GFR = 86, albuminuria &gt;300.`, 
        `postnephrectomy, GFR = 62 mL/min, albuminuria ≤30 mg/g.`, 
        `hypertensive, GFR = 75 mL/min, albuminuria = 80 mg/g.`, 
        ` IgA nephropathy, GFR 42 mL/min, albuminuria = 70 mg/g.`, 
        ` autosomal dominant polycystic kidney disease (ADPKD), GFR 28 mL/min, albuminuria ≤ 30 mg/g.`,
        ],
        optionFeedback: [``,
          ``,
          ``,
          ``,
          ``],
        optionStyleType: `st-lower-alpha`,
        answer: [1],
        ansText: `Rationale: The risk of progressive renal disease is based on the cause for renal function reduction, the GFR, and the albuminuria score. In a and c the GFR is higher, and there is cause for ongoing injury. One-time reduction in GFR with nephrectomy in the absence of ongoing injury (no albuminuria) should yield a more favorable prognosis. `,
        state: `notAnswered`,
        userAnswered: []
              ,
        type: `MCSS`},
      

      {
        q: `A hypertensive 38-year-old man has a serum creatinine of 2.4 mg/dL. The urinalysis has 10 to 20 RBCs/HPF, 3 + protein, and RBC casts. Ultrasound shows echogenic kidneys without hydronephrosis. The best way to achieve a diagnosis is:`,
        q2: ``,
        q3: [],
        option: [`renal angiography.`, 
        `renal biopsy`, 
        `retrograde pyelography.`, 
        `MRI `, 
        ` spiral CT scan.`,
        ],
        optionFeedback: [``,
          ``,
          ``,
          ``,
          ``],
        optionStyleType: `st-lower-alpha`,
        answer: [1],
        ansText: `Rationale: For definitive diagnosis, a renal biopsy is required to aid prognosis and therapy decisions, especially in the setting of abnormal renal function.`,
        state: `notAnswered`,
        userAnswered: []
              ,
        type: `MCSS`},
      

      {
        q: `All of the following promote fibrosis in the kidney except:`,
        q2: ``,
        q3: [],
        option: [`angiotensin II.`, 
        `aldosterone`, 
        `atrial natriuretic peptide.`, 
        ` transforming growth factor–β.`, 
        `high-salt diet. `,
        ],
        optionFeedback: [``,
          ``,
          ``,
          ``,
          ``],
        optionStyleType: `st-lower-alpha`,
        answer: [2],
        ansText: `Rationale: All choices promote renal fibrosis except atrial natriuretic peptide, which may have the opposite effect. `,
        state: `notAnswered`,
        userAnswered: []
              ,
        type: `MCSS`},
      

      {
        q: `CKD patients treated with an ACE inhibitor may experience a decrease in residual renal function in the setting of:`,
        q2: ``,
        q3: [],
        option: [`unilateral renal artery stenosis.`, 
        `concomitant treatment with an alpha-blocker.`, 
        `acquired renal cystic disease.`, 
        `left ventricular hypertrophy. `, 
        ` ADPKD with cysts &gt;10 cm.`,
        ],
        optionFeedback: [``,
          ``,
          ``,
          ``,
          ``],
        optionStyleType: `st-lower-alpha`,
        answer: [4],
        ansText: `Rationale: Individuals with bilateral renal artery stenosis and autosomal dominant PKD patients with cyst size greater than 10 cm may also experience a decrease in residual renal function while being given ACE inhibitor therapy. `,
        state: `notAnswered`,
        userAnswered: []
              ,
        type: `MCSS`},
      

      {
        q: `The best renal replacement therapy for an otherwise healthy 37-year-old woman with chronic interstitial nephritis is:`,
        q2: ``,
        q3: [],
        option: [`preemptive transplantation.`, 
        `stabilize with hemodialysis 1 year, then transplant.`, 
        `stabilize with peritoneal dialysis 1 year, then transplant.`, 
        ` home hemodialysis.`, 
        ` peritoneal dialysis with an automated cycler.`,
        ],
        optionFeedback: [``,
          ``,
          ``,
          ``,
          ``],
        optionStyleType: `st-lower-alpha`,
        answer: [0],
        ansText: `Rationale: A comparison of outcomes suggests that renal transplantation is the best overall treatment for ESRD patients.`,
        state: `notAnswered`,
        userAnswered: []
              ,
        type: `MCSS`},
      

      {
        q: `Hospitalization in ESRD patients on hemodialysis is most commonly due to:`,
        q2: ``,
        q3: [],
        option: [`hypertension`, 
        `ileus`, 
        `diabetes`, 
        `hyperkalemia `, 
        `access catheter infection. `,
        ],
        optionFeedback: [``,
          ``,
          ``,
          ``,
          ``],
        optionStyleType: `st-lower-alpha`,
        answer: [4],
        ansText: `Rationale: The most recent USRDS data identify the most common reason for hospital admission in ESRD patients on hemodialysis is catheter infection.`,
        state: `notAnswered`,
        userAnswered: []
              ,
        type: `MCSS`},
      

      {
        q: `All the following have a direct toxic effect on the kidney except:`,
        q2: ``,
        q3: [],
        option: [`iodinated contrast agent.`, 
        `myoglobin`, 
        `gadolinium-based contrast agents.`, 
        ` carboplatin`, 
        ` aminoglycoside antibiotics.`,
        ],
        optionFeedback: [``,
          ``,
          ``,
          ``,
          ``],
        optionStyleType: `st-lower-alpha`,
        answer: [2],
        ansText: `Rationale: Gadolinium is not toxic to the kidney. Its risk relates to the development of nephrogenic systemic fibrosis, which can carry a high mortality in patients with severely reduced GFR. All the others demonstrate direct toxicity to the kidney.`,
        state: `notAnswered`,
        userAnswered: []
              ,
        type: `MCSS`},
      

      {
        q: `The strongest predictor of hospitalization in chronic dialysis patients is:`,
        q2: ``,
        q3: [],
        option: [`African American race.`, 
        `hematocrit &lt;30%`, 
        `glomerulonephritis`, 
        `poor nutritional status `, 
        ` age &lt;30 years.`,
        ],
        optionFeedback: [``,
          ``,
          ``,
          ``,
          ``],
        optionStyleType: `st-lower-alpha`,
        answer: [3],
        ansText: `Rationale: The strongest predictors of the number of hospitalizations per year of patients at risk include low serum albumin, decreased activity level, diabetes mellitus as a primary cause of ESRD, peripheral vascular disease, white race, increasing age, and congestive heart failure. Both nutritional status (levels of serum albumin, creatinine, transferrin, and prealbumin, and lean body mass) and inflammatory response (e.g., C-reactive protein) are independent predictors of hospitalization in chronic hemodialysis patients. `,
        state: `notAnswered`,
        userAnswered: []
              ,
        type: `MCSS`},
      
      {
        q: ` A 55-year-old woman had this abdominal radiograph 1 day after a contrast-enhanced CT scan was done for abdominal pain. Her creatinine before the CT scan was 1.9 mg/dL. The most likely diagnosis is:`,
        q2: ``,
        q3: [],
        option: [`normal film.`, 
        `ATN`, 
        `renal artery occlusion.`, 
        `hypertensive kidneys. `, 
        `nephrocalcinosis `,
        ],
        optionFeedback: [``,
          ``,
          ``,
          ``,
          ``],
        optionStyleType: `st-lower-alpha`,
        answer: [3],
        ansText: `Rationale: Both kidneys are diffusely dense 24 hours after contrast administration (persistent nephrogram), with no excretion into the collecting system, making ATN the best diagnosis. The process is likely related to contrast-induced nephropathy. Renal artery occlusion is usually a unilateral process, and the nephrogram is absent in the affected kidney because of the lack of perfusion. The kidneys are small in patients with severe hypertension, and the nephrogram would have washed out at 24 hours rather than be persistent. No calcifications are seen in the kidneys, making nephrocalcinosis an unlikely diagnosis. `,
        state: `notAnswered`,
        userAnswered: []
              ,
        type: `MCSS`},
      
    
      
    
     
]