var quiz = [
   
    {
        q: `The exact position of the kidney within the retroperitoneum varies during:`,
        q2: ``,
        q3: [],
        option: [`different phases of respiration.`, 
        `presence of anatomic anomalies.`, 
        `body position.`, 
        ` a, b, and c`, 
        `a and c `,
        ],
        optionFeedback: [``,
          ``,
          ``,
          ``,
          ``],
        optionStyleType: `st-lower-alpha`,
        answer: [3],
        ansText: `Rationale: The exact position of the kidney within the retroperitoneum varies <b>during different phases of respiration, body position, and presence of anatomic anomalies</b>. For example, the kidneys move inferiorly about 3 cm (one vertebral body) during inspiration and during the changing of body position from supine to the erect position. `,
        state: `notAnswered`,
        userAnswered: []
      ,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`        ,
        type: `MCSS`},
      {
        q: `Gerota fascia envelops the kidney and the adrenal gland on all aspects but remains open:`,
        q2: ``,
        q3: [],
        option: [`inferiorly`, 
        `laterally`, 
        `medially`, 
        `inferiorly and laterally. `, 
        `inferiorly and medially `,
        ],
        optionFeedback: [``,
          ``,
          ``,
          ``,
          ``],
        optionStyleType: `st-lower-alpha`,
        answer: [0],
        ansText: `Rationale: Gerota fascia encasing the kidneys, adrenal glands, and abdominal ureters is closed superiorly and laterally and serves as an anatomic barrier to the spread of malignancy and a means of containing perinephric fluid collections. Superiorly, the Gerota fascia is continuous with the diaphragmatic fascia on the inferior surface of the diaphragm, whereas inferiorly, the anterior and posterior layers of Gerota fascia are loosely attached where perinephric fluid collections can track inferiorly into the pelvis without violating Gerota fascia.`,
        state: `notAnswered`,
        userAnswered: []
      ,
	type: `MCSS`,
	type: `MCSS`        ,
        type: `MCSS`},
  
      {
        q: `The white line of Toldt is the lateral reflection of posterior parietal peritoneum that covers:`,
        q2: ``,
        q3: [],
        option: [`the ascending colon.`, 
        `the descending colon.`, 
        `the transverse colon.`, 
        `the ascending and descending colons. `, 
        `the ascending and transverse colon. `,
        ],
        optionFeedback: [``,
          ``,
          ``,
          ``,
          ``],
        optionStyleType: `st-lower-alpha`,
        answer: [3],
        ansText: `Rationale: To access the kidneys transperitoneally, the colon needs to be mobilized from the white line of Toldt, which is the lateral reflection of posterior parietal peritoneum over the ascending and descending colon. `,
        state: `notAnswered`,
        userAnswered: []
              ,
        type: `MCSS`},
  
      {
        q: `What are the columns of Bertin?`,
        q2: ``,
        q3: [],
        option: [`Extensions of renal medulla between the pyramids`, 
        `Extensions of renal cortex between the pyramids`, 
        `Cortical extensions between renal lobules`, 
        ` The collecting ducts`, 
        ` None of the above`,
        ],
        optionFeedback: [``,
          ``,
          ``,
          ``,
          ``],
        optionStyleType: `st-lower-alpha`,
        answer: [1],
        ansText: `Rationale: The renal cortex is about 1 cm in thickness and covers the base of each renal pyramid peripherally and extends downward between the individual pyramids to form the columns of Bertin`,
        state: `notAnswered`,
        userAnswered: []
      ,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`        ,
        type: `MCSS`},
  
      {
        q: `Compared with the liver, the normal adult kidneys in gray-scale ultrasound appear:`,
        q2: ``,
        q3: [],
        option: [`hyperechoic`, 
        `isoechoic`, 
        `hypoechoic`, 
        ` b and c.`, 
        ` variable, depending on the renal function.`,
        ],
        optionFeedback: [``,
          ``,
          ``,
          ``,
          ``],
        optionStyleType: `st-lower-alpha`,
        answer: [1],
        ansText: `Rationale: In adults, the normal kidneys have smooth margins and are <b>isoechoic to the liver</b>. However, both renal cortices and pyramids are usually hypoechoic to the liver, spleen, and renal sinus. Compared with renal parenchyma, renal sinus appears hyperechoic because of the presence of hilar adipose tissue, blood vessels, and lymphatics.`,
        state: `notAnswered`,
        userAnswered: []
              ,
        type: `MCSS`},
  
      {
        q: `Occlusion or injury to a segmental renal artery will cause:`,
        q2: ``,
        q3: [],
        option: [`no pathologic conditions.`, 
        `opening of the collateral circulation.`, 
        `segmental renal infarction.`, 
        `an effect that depends on the availability of collaterals. `, 
        `renal atrophy. `,
        ],
        optionFeedback: [``,
          ``,
          ``,
          ``,
          ``],
        optionStyleType: `st-lower-alpha`,
        answer: [2],
        ansText: `Rationale: After entering the hilum, each artery divides into five segmental end arteries that do not anastomose significantly with other segmental arteries. Therefore, occlusion or injury to a segmental branch will cause segmental renal infarction. Nevertheless, the area supplied by each segmental artery could be independently surgically resected.`,
        state: `notAnswered`,
        userAnswered: []
      ,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`        ,
        type: `MCSS`},
  
      {
        q: `Ureteropelvic junction obstruction may be commonly caused by:`,
        q2: ``,
        q3: [],
        option: [`the lower anterior segmental artery when it passes anterior to the ureter.`, 
        `crossing of the ureter by any of the renal segmental arteries.`, 
        `the posterior segmental artery when it passes posterior to the renal pelvis.`, 
        `the posterior segmental artery when it passes anterior to the ureter. `, 
        ` the lower anterior segmental artery when it passes posterior to the ureter.`,
        ],
        optionFeedback: [``,
          ``,
          ``,
          ``,
          ``],
        optionStyleType: `st-lower-alpha`,
        answer: [3],
        ansText: `Rationale: The posterior segmental artery from the posterior division <b>passes posterior to the renal pelvis</b> while the others pass anterior to the renal pelvis. If the posterior segmental branch passes anterior to the ureter, ureteropelvic junction obstruction may occur.`,
        state: `notAnswered`,
        userAnswered: []
              ,
        type: `MCSS`},
      {
        q: `Occlusion of a segmental renal vein results in:`,
        q2: ``,
        q3: [],
        option: [`segmental renal congestion.`, 
        `segmental renal atrophy.`, 
        `no pathologic conditions.`, 
        `an effect that depends on the availability of collaterals. `, 
        ` gross hematuria.`,
        ],
        optionFeedback: [``,
          ``,
          ``,
          ``,
          ``],
        optionStyleType: `st-lower-alpha`,
        answer: [2],
        ansText: `Rationale: The renal venous drainage correlates closely with the arterial supply with the exception that unlike the arterial supply, venous drainage has extensive collateral communication through the venous collars around minor calyceal infundibula. Furthermore, the interlobular veins that drain the <b>post-glomerular capillaries also communicate freely with perinephric veins</b> through the subcapsular venous plexus of stellate veins. Therefore, occlusion of a segmental venous branch has little effect on venous outflow. `,
        state: `notAnswered`,
        userAnswered: []
              ,
        type: `MCSS`},
  
      {
        q: `The main renal vasculature can be accurately identified with 100% sensitivity by:`,
        q2: ``,
        q3: [],
        option: [`Doppler ultrasonography.`, 
        `computed tomography angiography (CTA).`, 
        `intravenous urography.`, 
        `noncontrast computed tomography. `, 
        `all of the above. `,
        ],
        optionFeedback: [``,
          ``,
          ``,
          ``,
          ``],
        optionStyleType: `st-lower-alpha`,
        answer: [2],
        ansText: `Rationale: Doppler ultrasonography clearly identifies renal arteries at their origin from the abdominal aorta. However, the main renal artery is often difficult to identify at baseline ultrasonography. Therefore, <b>CTA is currently considered the gold standard to assess renal arteries</b> with 100% sensitivity for identification of renal arteries and veins. `,
        state: `notAnswered`,
        userAnswered: []
              ,
        type: `MCSS`},
  
      {
        q: `Medial displacement of both pelvic ureteral segments might result from:`,
        q2: ``,
        q3: [],
        option: [`pelvic lipomatosis.`, 
        `postabdominoperineal surgery.`, 
        `retroperitoneal fibrosis.`, 
        ` all of the above.`, 
        ` a and c.`,
        ],
        optionFeedback: [``,
          ``,
          ``,
          ``,
          ``],
        optionStyleType: `st-lower-alpha`,
        answer: [3],
        ansText: `Rationale: Medial displacement of <b>both pelvic ureteral segments might result from retroperitoneal fibrosis, pelvic lipomatosis, or postabdominoperineal surgery.</b> However, medial displacement and concavity of <b>a single pelvic ureter</b> may result from enlarged hypogastric nodes, a bladder diverticulum, or aneurismal dilatation of the hypogastric artery. Nevertheless, this may be a <b>normal finding in adult females</b> if only the right ureter is affected because of the uterine tilt to the left.`,
        state: `notAnswered`,
        userAnswered: []
              ,
        type: `MCSS`},
  
      {
        q: `If the small ureteral arteries that anastomose in the ureteral adventitia are disrupted, this may result in:`,
        q2: ``,
        q3: [],
        option: [`ureteral ischemia.`, 
        `ureteral stricture.`, 
        `a and b.`, 
        ` no impact on ureteral blood supply.`, 
        `gross hematuria `,
        ],
        optionFeedback: [``,
          ``,
          ``,
          ``,
          ``],
        optionStyleType: `st-lower-alpha`,
        answer: [2],
        ansText: `Rationale: The abdominal portion of the ureter is supplied mainly by arterial branches medially from the main renal artery or the aorta, which form a longitudinal anastomosis on the ureteral wall. Despite this anastomotic plexus, <b>ureteral ischemia is not uncommon</b> if these small and delicate ureteral branches are disrupted. Unnecessary lateral retraction and removal of the periureteral adventitial tissues containing the blood supply can result in ureteral ischemia and subsequent stricture.`,
        state: `notAnswered`,
        userAnswered: []
              ,
        type: `MCSS`},
  
      {
        q: `The blood supply of the mid-ureter is mostly:`,
        q2: ``,
        q3: [],
        option: [`anterior`, 
        `posterior`, 
        `medial`, 
        ` lateral`, 
        `any of the above. `,
        ],
        optionFeedback: [``,
          ``,
          ``,
          ``,
          ``],
        optionStyleType: `st-lower-alpha`,
        answer: [1],
        ansText: `Rationale: Although main renal arteries or the aorta supply the abdominal ureter medially, the blood supply to the distal ureter comes laterally from the superior vesical artery, a branch of the internal iliac artery, and the mid-ureter is supplied by branches <b>arising posteriorly</b> from the common iliac arteries. Therefore, the blood supply of the ureter is medial in the proximal part, posterior in the mid portion, and lateral in the distal portion.`,
        state: `notAnswered`,
        userAnswered: []
              ,
        type: `MCSS`},
  
      {
        q: `What is the Mercier bar?`,
        q2: ``,
        q3: [],
        option: [`The intramural ureter`, 
        `The bladder trigone`, 
        `The interureteral ridge`, 
        ` Intraureteral valves`, 
        ` None of the above`,
        ],
        optionFeedback: [``,
          ``,
          ``,
          ``,
          ``],
        optionStyleType: `st-lower-alpha`,
        answer: [2],
        ansText: `Rationale: Once the cystoscope is inside the bladder neck, the trigone can be seen as a raised, smooth triangle. The apex of that triangle is situated at the bladder neck; its base is formed by <b>the interureteral ridge or Mercier bar</b>, extending between the two ureteral orifices.`,
        state: `notAnswered`,
        userAnswered: []
              ,
        type: `MCSS`},
  
      {
        q: `The higher the grade of the ureteral orifice:`,
        q2: ``,
        q3: [],
        option: [`the greater its tendency to be laterally located.`, 
        `the lesser its tendency to reflux.`, 
        `the greater its tendency to be associated with ureterocele.`, 
        `the greater its tendency to reflux. `, 
        ` none of the above.`,
        ],
        optionFeedback: [``,
          ``,
          ``,
          ``,
          ``],
        optionStyleType: `st-lower-alpha`,
        answer: [0],
        ansText: `Rationale: The ureteral orifices are classified according to their position or configuration. They are normally located at the medial aspect of the trigone (position A). However, they may be located at the lateral wall of the bladder or at its junction with the trigone (position C) or in between positions A and C (position B). In terms of configuration, grade 0 indicates a normal ureteral orifice that looks like a cone or a volcano. Grades 1, 2, and 3 describe stadium, horseshoe, and golf-hole orifice, respectively. The higher the grade of the orifice, the greater its tendency to be laterally located and to reflux.`,
        state: `notAnswered`,
        userAnswered: []
              ,
        type: `MCSS`},
      
     
]