var quiz = [
   
    {
        q: `In renal transplant recipients, all of the following are true EXCEPT:`,
        q2: ``,
        q3: [],
        option: [`Recipients usually have classical symptoms of ureteral obstruction.`, 
        `Ureteral stricture is the most common cause of late ureteral obstruction.`, 
        `Ureteral obstruction should be suspected in any deterioration of renal function.`, 
        `Ureter ischemia is the main etiology for ureteral stricture formation. `, 
       
        ],
        optionFeedback: [``,
          ``,
          ``,
          ``,
          ``],
        optionStyleType: `st-lower-alpha`,
        answer: [0],
        ansText: `Rationale: Due to renal allograft during the procurement process, kidney transplant recipients rarely manifest the classical symptoms of ureteral obstruction. As a result, usually recipients present with a progressive decline in renal function, a decrease in urine output, and recurrent UTIs. In a rare instance, patients may present with poorly characterized ache over the allograft due to irritation of peritoneum. `,
        state: `notAnswered`,
        userAnswered: []
      ,
	type: `MCSS`,
	type: `MCSS`        ,
        type: `MCSS`},
      {
        q: `The predominant type of stones in renal transplant patients is:`,
        q2: ``,
        q3: [],
        option: [`calcium oxalate.`, 
        `calcium phosphate.`, 
        `struvite`, 
        ` uric acid.`, 
        ` a and b.`,
        ],
        optionFeedback: [``,
          ``,
          ``,
          ``,
          ``],
        optionStyleType: `st-lower-alpha`,
        answer: [4],
        ansText: `Rationale: The most common stone composition in recipients is calcium-based stones (67%), followed by struvite stones (20%) and uric acid stones (13%).`,
        state: `notAnswered`,
        userAnswered: []
      ,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`        ,
        type: `MCSS`},
      {
        q: `Early stent removal is associated with:`,
        q2: ``,
        q3: [],
        option: [`decrease in incidence of urinary tract infection (UTI).`, 
        `decrease in risk of stent colonization.`, 
        `increase in risk of UTI.`, 
        ` increase in risk of developing urine leak.`, 
        `increase in risk of graft rejection. `,
        ],
        optionFeedback: [``,
          ``,
          ``,
          ``,
          ``],
        optionStyleType: `st-lower-alpha`,
        answer: [0],
        ansText: `Rationale: In a recent meta-analysis, early stent removal, defined by removal of the stent before the third postoperative week (&lt; day 15), has been shown to reduce the incidence of UTI without increasing the incidence of urine leak and stenosis. On the other hand, 27% of the ureteral stents are colonized regardless of the indwelling time.`,
        state: `notAnswered`,
        userAnswered: []
              ,
        type: `MCSS`},
      {
        q: `All of the following have been related to the development of clinically significant vesicoureteral reflux (VUR) in renal transplant recipients EXCEPT:`,
        q2: ``,
        q3: [],
        option: [`bladder outlet obstruction.`, 
        `neurogenic detrusor overactivity.`, 
        `reduced bladder capacity and compliance.`, 
        `ureterovesical anastomosis technique. `, 
        ` use of ureteral stent.`,
        ],
        optionFeedback: [``,
          ``,
          ``,
          ``,
          ``],
        optionStyleType: `st-lower-alpha`,
        answer: [3],
        ansText: `Rationale: VUR can be related to a technical error during the ureteroneocystostomy anastomosis, bladder outlet obstruction, or high-pressure urine storage secondary to either detrusor overactivity or reduced bladder compliance. However, VUR can develop regardless the ureterovesical anastomosis technique used. `,
        state: `notAnswered`,
        userAnswered: []
      ,
	type: `MCSS`,
	type: `MCSS`        ,
        type: `MCSS`},
      {
        q: `The success rate of laparoscopic marsupialization of lymphocele in renal transplant recipients is:`,
        q2: ``,
        q3: [],
        option: [`30%`, 
        `41%`, 
        `69%.`, 
        ` 92%`, 
        ` 84%.`,
        ],
        optionFeedback: [``,
          ``,
          ``,
          ``,
          ``],
        optionStyleType: `st-lower-alpha`,
        answer: [3],
        ansText: `Rationale: The success rate for aspiration alone, sclerotherapy using different composite, drain placement, laparoscopic, and open surgery is 41%, 69%, 50%, 92%, and 84%, respectively.`,
        state: `notAnswered`,
        userAnswered: []
              ,
        type: `MCSS`},
      {
        q: `The following statements regarding renal cell carcinoma in renal transplant recipients are true EXCEPT:`,
        q2: ``,
        q3: [],
        option: [`Most of the kidney tumors develop in the native kidneys.`, 
        `Renal cell carcinoma incidence is higher in the transplant population compared to the general population.`, 
        `Renal cell carcinoma in renal transplant patients is aggressive and associated with worse oncological outcome.`, 
        ` Partial nephrectomy is a feasible option to treat small renal masses in the allograft.`, 
        `Mass screening for renal cell carcinoma in renal transplant recipients is not recommended. `,
        ],
        optionFeedback: [``,
          ``,
          ``,
          ``,
          ``],
        optionStyleType: `st-lower-alpha`,
        answer: [2],
        ansText: `Rationale: Majority of kidney graft tumors has indolent behavior. In a recent analysis of allograft tumors, it was found that papillary carcinomas are reported in 56% of kidney graft tumors and low-grade tumors (Fuhrman grades 1 and 2) accounted for 65% of nonpapillary kidney graft tumors. `,
        state: `notAnswered`,
        userAnswered: []
      ,
	type: `MCSS`,
	type: `MCSS`        ,
        type: `MCSS`},
      {
        q: `The following statements regarding the management of benign prostatic hypertrophy (BPH) in renal transplant recipients are FALSE EXCEPT:`,
        q2: ``,
        q3: [],
        option: [`Transurethral resection of prostate (TURP) can be done in the first 3 weeks after transplant.`, 
        `TURP can be done in the presence of ureteral stent.`, 
        `TURP should be avoided in the first 3 weeks after transplant.`, 
        ` Medical treatment of BPH should be avoided in renal transplant recipients.`, 
        `Renal transplant recipients are at increased risk of developing urethral stricture after TURP. `,
        ],
        optionFeedback: [``,
          ``,
          ``,
          ``,
          ``],
        optionStyleType: `st-lower-alpha`,
        answer: [2],
        ansText: `Rationale: There is no contraindication for medical therapy in renal transplant recipients. TURP or Holmium enucleation of the prostate has been reported to be safe and effective in this subset of patients if performed at least 3 weeks post-transplant. It is crucial to avoid TURP in the first 2 weeks and in the presence of a ureteral stent after the transplant as it has been associated with devastating complications such as sepsis and death. `,
        state: `notAnswered`,
        userAnswered: []
              ,
        type: `MCSS`},
      {
        q: `The following statements regarding the management of bladder cancer in renal transplant recipients are true EXCEPT:`,
        q2: ``,
        q3: [],
        option: [`Intravesical bacillus Calmette-Guerin can be used in renal transplant patients.`, 
        `Muscle-invasive bladder cancer can be treated by chemoradiotherapy.`, 
        `Muscle-invasive bladder cancer can be treated by radical cystectomy and urinary diversion.`, 
        `Early cystectomy should be offered to patients with high-grade non–muscle-invasive bladder cancer. `, 
        ` Bladder cancer in renal transplant recipients has indolent behavior.`,
        ],
        optionFeedback: [``,
          ``,
          ``,
          ``,
          ``],
        optionStyleType: `st-lower-alpha`,
        answer: [4],
        ansText: `Rationale: Bladder cancer in kidney transplant patients is aggressive and tends to be associated with higher recurrence rates, progression, and metastasis. For that reason, early cystectomy should be offered to patients with high-grade non–muscle-invasive bladder cancer. However, intravesical bacillus Calmette-Guerin can be used in selected patients with high-risk non–muscle-invasive bladder cancer. Muscle-invasive bladder cancer can be treated with chemoradiotherapy or radical cystoprostatectomy and urinary diversion.`,
        state: `notAnswered`,
        userAnswered: []
              ,
        type: `MCSS`},
      {
        q: `All of the following are predisposing factors to the development of lymphocele EXCEPT:`,
        q2: ``,
        q3: [],
        option: [`Extensive dissection of the lymphatic around the iliac vessels.`, 
        `Use of mammlian target of rapamycin (mTOR) inhibitors.`, 
        `Prolonged warm ischemia time.`, 
        `Delayed graft function. `, 
        `Atherosclerosis `,
        ],
        optionFeedback: [``,
          ``,
          ``,
          ``,
          ``],
        optionStyleType: `st-lower-alpha`,
        answer: [4],
        ansText: `Rationale: Lymphoceles occur mainly due to extensive dissection of the lymphatics around the iliac vessels of the recipient or renal vessels of the donor occurring during the time of organ procurement surgery or back table preparation. Other factors found to be associated with lymphocele formation include obesity, recipient age, duration of dialysis treatment, warm ischemia time, use of prophylaxis low-molecular-weight heparin, delayed graft function, acute rejection, redo transplant, and the use of mTOR inhibitors.`,
        state: `notAnswered`,
        userAnswered: []
              ,
        type: `MCSS`},
      {
        q: `Initial management of a low-volume urine leak may include all of following EXCEPT:`,
        q2: ``,
        q3: [],
        option: [`bladder catheter.`, 
        `JJ stent placement.`, 
        `percutaneous nephrostomy tube placement.`, 
        ` percutaneous drainage of urinoma.`, 
        `fluid restriction. `,
        ],
        optionFeedback: [``,
          ``,
          ``,
          ``,
          ``],
        optionStyleType: `st-lower-alpha`,
        answer: [4],
        ansText: `Rationale: The initial treatment of urine leak is by diverting the urine from the leak site, and this can be achieved by a Foley catheter and a percutaneous nephrostomy tube. Retrograde stent placement has also been proposed when a double-J stent was not placed at the time of surgery. Percutaneous drainage is recommended if a substantial urinoma forms or causes ureteral obstruction or there is evidence of infection. `,
        state: `notAnswered`,
        userAnswered: []
              ,
        type: `MCSS`},
      {
    q: `Which of the following is a contraindication for surgical reconstruction of ureteral stricture?`,
    q2: ``,
    q3: [],
    option: [`Strictures less than 3 cm in length.`, 
    `Late stricture recurrence after endourological treatment.`, 
    `Surgeon preference.`, 
    `All of above. `, 
    ` None of above.`,
    ],
    optionFeedback: [``,
      ``,
      ``,
      ``,
      ``],
    optionStyleType: `st-lower-alpha`,
    answer: [4],
    ansText: `Rationale: Open surgical repair for ureteral stricture remains the most effective treatment modality with superior long-term results when compared to endoscopic management. The only relative contraindication is very highly co-morbid patients with short life expectancy.`,
    state: `notAnswered`,
    userAnswered: []
  ,
	type: `MCSS`        ,
        type: `MCSS`},
      
    
      
    
     
]