var quiz = [
   
    {
        q: `What is the most accurate imaging study for characterizing a renal mass?`,
        q2: ``,
        q3: [],
        option: [`Intravenous pyelography`, 
        `Ultrasonography`, 
        `Computed tomography (CT) with and without contrast enhancement`, 
        `CT-positron emission tomography (PET) scan`, 
        `Renal arteriography`],
        optionFeedback: [``,
        ``,
        ``,
        ``,
        
        ``],
        optionStyleType: `st-lower-alpha`,
        answer: [2],
        ansText:`Rationale:<!--<b>c. Computed tomography (CT) with and without contrast enhancement.</b>--> A dedicated triple-phase renal CT scan remains the single most important radiographic image to delineate the nature of a renal mass. In general, any renal mass that enhances with administration of intravenous contrast material on CT scanning should be considered a RCC until proved otherwise. `, 
        state: `notAnswered`,
        userAnswered: [],
	type: `MCSS`        ,
        type: `MCSS`},
    {
        q: `A hyperdense renal cyst may also be termed a:`,
        q2: ``,
        q3: [],
        option: [`probable malignancy.`, 
        `Bosniak II cyst.`, 
        `Bosniak III cyst.`, 
        `Bosniak IV cyst.`, 
        `probable angiomyolipoma.`],
        optionFeedback: [``,
        ``,
        ``,
        ``,
        
        ``],
        optionStyleType: `st-lower-alpha`,
        answer: [1],
        ansText:`Rationale:<!--<b>b. Bosniak II cyst.</b>--> Category II lesions are minimally complicated cysts that are benign but have some radiologic findings that cause concern. Classic hyperdense renal cysts are small (&lt;3 cm), round, sharply marginated, and do not enhance after administration of contrast material. Hyperdense cysts that are 3 cm or larger are classified as <b><i>Bosniak IIF</i></b> lesions. `, 
        state: `notAnswered`,
        userAnswered: [],
	type: `MCSS`        ,
        type: `MCSS`},
    {
        q: `The most generally accepted indication for core needle biopsy of a renal mass is a suspected clinical diagnosis of:`,
        q2: ``,
        q3: [],
        option: [`renal cell carcinoma (RCC).`, 
        `renal oncocytoma.`, 
        `renal cyst.`, 
        `renal metastasis.`, 
        `renal angiomyolipoma.`],
        optionFeedback: [``,
        ``,
        ``,
        ``,
        
        ``],
        optionStyleType: `st-lower-alpha`,
        answer: [3],
        ansText:`Rationale:<!--<b>d. Renal metastasis.</b>--> The traditionally accepted indications for biopsy of a renal mass are when a renal abscess or infected cyst is suspected, or when differentiating RCC from metastatic malignancy or renal lymphoma. Core needle biopsy is now performed with increased frequency for the evaluation of renal masses in other circumstances, particularly for patients in whom a wide variety of treatment options are under consideration. `, 
        state: `notAnswered`,
        userAnswered: [],
	type: `MCSS`        ,
        type: `MCSS`},
    {
        q: `According to the American Urological Association (AUA) guidelines (<a href="6f325cc2c2a84c03bbac08a2cf0fd221">Fig. 97.1</a>), recommended postoperative radiographic surveillance of the chest after radical nephrectomy for T1N0M0 RCC is:`,
        q2: ``,
        q3: [],
        option: [`no imaging studies.`, 
        `chest radiograph at 1 year.`, 
        `chest radiograph annually for 3 years.`, 
        `chest CT at 1 year and then chest radiograph annually for 2 years.`, 
        `chest radiograph annually for 5 years.`],
        optionFeedback: [``,
        ``,
        ``,
        ``,
        
        ``],
        optionStyleType: `st-lower-alpha`,
        answer: [2],
        ansText:`Rationale: <!--<b>c. Chest radiograph annually for 3 years.</b>--> Surveillance for recurrent malignancy after radical nephrectomy for RCC can be tailored according to the initial pathologic tumor stage. This patient is low risk (pT1N0M0), and the AUA guidelines recommend an annual chest radiograph for 3 years and only as clinically indicated beyond that time period.`, 
        state: `notAnswered`,
        userAnswered: [],
    
        type: `MCSS`},
    {
        q: `The European Organization for Research and Treatment of Cancer 30904 study randomly assigned patients to radical versus partial nephrectomy. Which of the following was an inclusion criterion?`,
        q2: ``,
        q3: [],
        option: [`Clinical T1a tumor (&lt;4.0 cm)`, 
        `Tumor size &lt;5.0 cm`, 
        `Estimated glomerular filtration rate (GFR) &gt;60 mL/min/1.73 m<sup>2</sup>`, 
        `No hypertension`, 
        `Age &lt;70 years`],
        optionFeedback: [``,
        ``,
        ``,
        ``,
        
        ``],
        optionStyleType: `st-lower-alpha`,
        answer: [1],
        ansText:`Rationale:<!--<b>b. Tumor size &lt;5.0 cm.</b>--> A solitary tumor and a normal contralateral kidney were also required, but criteria for the latter were not well defined, at least based on current perspectives about functional assessment that depend on eGFR rather than serum creatinine level. `, 
        state: `notAnswered`,
        userAnswered: [],
    
        type: `MCSS`},
    {
        q: `According to the AUA guidelines, following partial nephrectomy for pathologic stage T3aN0M0 RCC, it is recommended to perform surveillance abdominal CT scanning with what frequency?`,
        q2: ``,
        q3: [],
        option: [`Never`, 
        `Every 6 months for at least 3 years and then annually to year 5`, 
        `Every year to year 5`, 
        `Every 2 years`, 
        `Every year for 2 years and then at year 5`],
        optionFeedback: [``,
        ``,
        ``,
        ``,
        
        ``],
        optionStyleType: `st-lower-alpha`,
        answer: [1],
        ansText:`Rationale: <!--<b>b. Every 6 months for at least 3 years and then annually to year 5.</b>--> Surveillance for recurrent malignancy after nephron-sparing surgery for RCC can be tailored according to the initial pathologic tumor stage. This patient is intermediate to high risk, and the AUA Guidelines recommend a baseline abdominal scan (CT or MRI) within 3 to 6 months following surgery with continued imaging (ultrasonography, CT, or MRI) every 6 months for at least 3 years and annually thereafter to year 5. Imaging beyond 5 years may be performed at the discretion of the clinician.`, 
        state: `notAnswered`,
        userAnswered: [],
    
        type: `MCSS`},
    {
        q: `Following partial nephrectomy of a solitary kidney, what is the most effective method of screening for hyperfiltration nephropathy?`,
        q2: ``,
        q3: [],
        option: [`Urinary dipstick test for protein`, 
        `Albumin-to-creatinine ratio`, 
        `Iothalamate glomerular filtration rate (GFR) measurement`, 
        `Serum creatinine measurement`, 
        `Renal biopsy`],
        optionFeedback: [``,
        ``,
        ``,
        ``,
        
        ``],
        optionStyleType: `st-lower-alpha`,
        answer: [1],
        ansText:`Rationale:<!--<b>b. Albumin-to-creatinine ratio.</b>--> Patients who undergo nephron-sparing surgery for RCC may be left with a relatively small amount of renal tissue. These patients are at risk for long-term renal functional impairment from hyperfiltration renal injury. Because proteinuria is the initial manifestation of the phenomenon, an albumin-to-creatinine ratio should be obtained yearly in patients with a solitary remnant kidney to screen for hyperfiltration nephropathy. Traditionally a 24-hour urine protein was obtained on an annual basis, but this is more burdensome, and for screening purposes the albumin-to-creatinine ratio is more suitable. If positive, more rigorous testing, such as the 24-hour urine protein, can be considered to more accurately quantify the degree of proteinuria. `, 
        state: `notAnswered`,
        userAnswered: [],
    
        type: `MCSS`},
    {
        q: `The most accurate and practical assessment of renal function for routine use after nephrectomy is:`,
        q2: ``,
        q3: [],
        option: [`serum creatinine measurement.`, 
        `urinary dipstick test for protein.`, 
        `24-hours urinary protein measurement.`, 
        `iothalamate GFR measurement.`, 
        `serum creatinine–based estimation of GFR and analysis for proteinuria.`],
        optionFeedback: [``,
        ``,
        ``,
        ``,
        
        ``],
        optionStyleType: `st-lower-alpha`,
        answer: [4],
        ansText:`Rationale:<!--<b>e. Serum creatinine–based estimation of GFR and analysis for proteinuria.</b>--> <b>Identification and classification of CKD is best performed by assessing cause, estimated GFR (eGFR), and extent of albuminuria.</b> At present, there are several formulas in clinical use, including the MDRD and CKD-EPI formulas, each of which is an improvement over using serum creatinine alone for identification of patients with or at risk for CKD. Serum levels of creatinine are dependent on gender, muscle mass, and other factors and can therefore lead to an underestimation of kidney disease in certain populations, such as thin, elderly women. Urinary creatinine measurement is impractical and provides only marginally more valuable information than serum creatinine. Urinary protein measurement can identify patients with early signs of kidney disease (proteinuria), and there are multiple methods to assess this, including 24-hour urinary protein and spot urine studies (albumin-to-creatinine ratio, protein-to-creatinine ratio); none has been shown to be better than GFR estimation as a screening test. Direct measurement of GFR using iothalamate (or other agents) is costly and not routinely available; it is therefore impractical in most settings. `, 
        state: `notAnswered`,
        userAnswered: [],
	type: `MCSS`        ,
        type: `MCSS`},
    {
        q: `What is an important prerequisite for successful cryoablation of a renal tumor?`,
        q2: ``,
        q3: [],
        option: [`Slow freezing`, 
        `Rapid thawing`, 
        `A single prolonged freeze-thaw cycle`, 
        `A double freeze-thaw cycle`, 
        `Freezing of tumor to a temperature of −10°C`],
        optionFeedback: [``,
        ``,
        ``,
        ``,
        
        ``],
        optionStyleType: `st-lower-alpha`,
        answer: [3],
        ansText:`Rationale: <!--<b>d. A double freeze-thaw cycle.</b>--> Renal cryosurgery is an ablative nephron-sparing treatment option for RCC that can be performed percutaneously under radiographic guidance or laparoscopically under direct vision and ultrasound guidance. The aim of cryosurgery is to ablate the same predetermined volume of tissue that would have been removed had a conventional surgical excision been performed. Established critical prerequisites for successful cryosurgery include rapid freezing, gradual thawing, and a repetition of the freeze-thaw cycle.`, 
        state: `notAnswered`,
        userAnswered: [],
    
        type: `MCSS`},
    {
        q: `Which two imaging modalities are the preferred and most accurate for demonstrating the presence and extent of an inferior vena caval tumor thrombus?`,
        q2: ``,
        q3: [],
        option: [`Abdominal ultrasonography and CT`, 
        `MRI and renal artery angiography`, 
        `CT and MRI`, 
        `MRI and contrast venacavography`, 
        `Contrast venacavography and transesophageal ultrasonography`],
        optionFeedback: [``,
        ``,
        ``,
        ``,
        
        ``],
        optionStyleType: `st-lower-alpha`,
        answer: [2],
        ansText:`Rationale:<!--<b>c. CT and MRI.</b>--> Both CT and MRI are noninvasive and accurate modalities for demonstrating both the presence and the distal extent of vena caval involvement. Although MRI has been recommended as the test of choice at most centers, many studies have demonstrated that a properly performed multiplanar CT also provides sufficient information for surgical planning, and it has become the preferred diagnostic study at many centers. `, 
        state: `notAnswered`,
        userAnswered: [],
    
        type: `MCSS`},
    {
        q: `In patients undergoing complete surgical excision of RCC, the lowest 5-year survival rate is associated with which factor?`,
        q2: ``,
        q3: [],
        option: [`Perinephric fat involvement`, 
        `Clear cell histology`, 
        `Subdiaphragmatic inferior vena caval involvement`, 
        `Intra-atrial tumor thrombus`, 
        `Lymph node involvement`],
        optionFeedback: [``,
        ``,
        ``,
        ``,
        
        ``],
        optionStyleType: `st-lower-alpha`,
        answer: [4],
        ansText:`Rationale:<!--<b>e. Lymph node involvement.</b>--> In most studies, the presence of lymph node or distant metastases has carried a dismal prognosis that is much more pronounced than the other distractors. `, 
        state: `notAnswered`,
        userAnswered: [],
    
        type: `MCSS`},
    {
        q: `A 45-year-old man has a 5-cm, exophytic RCC in the upper pole of a solitary left kidney and a single 2-cm left lower lung metastasis. What is the best treatment?`,
        q2: ``,
        q3: [],
        option: [`Initial targeted therapy, then partial nephrectomy`, 
        `Partial nephrectomy, then targeted therapy`, 
        `Staged partial nephrectomy and pulmonary lobectomy`, 
        `Simultaneous partial nephrectomy and pulmonary lobectomy`, 
        `Simultaneous radical nephrectomy and pulmonary lobectomy`],
        optionFeedback: [``,
        ``,
        ``,
        ``,
        
        ``],
        optionStyleType: `st-lower-alpha`,
        answer: [3],
        ansText:`Rationale:<!--<b>d. Simultaneous partial nephrectomy and pulmonary lobectomy.</b>--> The subset of patients with metastatic RCC and a solitary metastasis, estimated at between 1.6% and 3.2% of patients, may benefit from nephrectomy with resection of the metastatic lesion. This patient also needs partial nephrectomy to preclude the need for dialysis. Of note, both procedures could be performed with a minimally invasive approach under the same anesthesia. `, 
        state: `notAnswered`,
        userAnswered: [],
    
        type: `MCSS`},
    {
        q: `A healthy 75-year-old man is referred after renal biopsy of a 3.0-cm centrally located renal mass. The biopsy is definitive for renal oncocytoma. The other kidney is normal, the serum creatinine level is 1.0 mg/dL, and there is no evidence of metastatic disease. What is the best next step?`,
        q2: ``,
        q3: [],
        option: [`Open radical nephrectomy`, 
        `Laparoscopic nephroureterectomy`, 
        `Percutaneous thermal ablation (TA)`, 
        `Partial nephrectomy`, 
        `Observation with follow-up renal imaging`],
        optionFeedback: [``,
        ``,
        ``,
        ``,
        
        ``],
        optionStyleType: `st-lower-alpha`,
        answer: [4],
        ansText:`Rationale:<!--<b>e. Observation with follow-up renal imaging.</b>--> Renal mass biopsy is now performed with increased frequency and should be considered in an elderly patient such as this. For those in whom nonextirpative options are being considered, biopsy can provide important information, such as a definitive nonmalignant diagnosis (as in this example). Given the benign nature of renal oncocytomas, the best answer is observation with follow-up imaging at an interval between 6 and 12 months, if clinically warranted based on the patient’s overall health and life expectancy. `, 
        state: `notAnswered`,
        userAnswered: [],
    
        type: `MCSS`},
    {
        q: `Which of the following agents demonstrated an oncologic benefit in the postoperative adjuvant setting for patients at high risk of recurrence following nephrectomy?`,
        q2: ``,
        q3: [],
        option: [`High-dose interleukin-2 (IL-2)`, 
        `Sunitinib`, 
        `Autologous tumor vaccine`, 
        `Pazopanib`, 
        `Interferon-α (IFN-α)`],
        optionFeedback: [``,
        ``,
        ``,
        ``,
        
        ``],
        optionStyleType: `st-lower-alpha`,
        answer: [1],
        ansText:`Rationale: <!--<b>b. Sunitinib.</b>--> <b>Sunitinib</b> demonstrated a significantly longer disease-free survival compared to placebo (6.8 vs. 5.6 years) in the phase 3 S-TRAC trial that randomized 615 men with pT2 (high-grade), pT3-4, or N1 clear cell RCC to sunitinib or placebo. Importantly, patients receiving therapy experienced significantly higher rates of toxic events and there was no difference in overall survival. All other therapies listed failed to demonstrate an oncologic benefit in the adjuvant setting.`, 
        state: `notAnswered`,
        userAnswered: [],
    
        type: `MCSS`},
    {
        q: `Based on the 2017 AUA Guidelines, which of the following patients would not need to be considered for genetic counseling?`,
        q2: ``,
        q3: [],
        option: [`A 45-year-old woman with a pT1a clear cell RCC.`, 
        `A 68-year-old man with a pT1a RCC with histology suggestive of succinate dehydrogenase (SDH) deficiency`, 
        `A 69-year-old man with 2 ipsilateral pT1a tumors, a 3.5-cm clear cell, and a 1.1-cm type 1 papillary`, 
        `A 62-year-old woman with a pT1b chromophobe RCC and moderate-sized lung cysts`, 
        `The 7-year-old son of a patient with von Hippel-Lindau (VHL) disease`],
        optionFeedback: [``,
        ``,
        ``,
        ``,
        
        ``],
        optionStyleType: `st-lower-alpha`,
        answer: [2],
        ansText:`Rationale:<!--<b>c. A 69-year-old man with 2 ipsilateral pT1a tumors, a 3.5-cm clear cell, and a 1.1-cm type 1 papillary.</b>--> <b>A 69-year-old man with 2 ipsilateral pT1a tumors, a 3.5-cm clear cell and a 1.1-cm type 1 papillary probably does not need to consider genetic counseling, unless the family or personal history is otherwise suggestive of a familial syndrome.</b> Genetic counseling is recommended for all patients with kidney cancer who are 46 years of age or younger. When histology suggests possible SDH deficiency, further testing should be pursued, and a history of chromophobe RCC and lung cysts or a prior spontaneous pneumothorax is suggestive for BHD syndrome. Relatives of patients with known familial RCC should be strongly considered for genetic counseling, and surveillance ideally will be initiated at an early age. An elderly patient with multifocal RCC may not need to be considered for genetic counseling, particularly if there is discordance in the histologies. `, 
        state: `notAnswered`,
        userAnswered: [],
    
        type: `MCSS`},
    {
        q: `Which two agents have the most similar mechanisms of action?`,
        q2: ``,
        q3: [],
        option: [`Sunitinib and temsirolimus`, 
        `Pazopanib and axitinib`, 
        `Pembrolizumab and ipilimumab`, 
        `Nivolumab and cabozantinib`, 
        `Atezolizumab and ipilimumab`],
        optionFeedback: [``,
        ``,
        ``,
        ``,
        
        ``],
        optionStyleType: `st-lower-alpha`,
        answer: [1],
        ansText:`Rationale:<!--<b>b. Pazopanib and axitinib.</b>--> <b>Pazopanib and axitinib both target the VEGF pathway, and specifically the VEGF receptor, and are TKI.</b> Sunitinib and cabozantinib are also TKIs, and temsirolimus is an mTOR inhibitor. Pembrolizumab, atezolizumab, ipilimumab, and nivolumab are all checkpoint inhibitors (<a href="f50a58af242a496b83378f772d9ea8d7">Fig. 97.6</a>). Pembrolizumab and nivolumab block PD-1, while atezolizumab blocks PD-L1 and ipilimumab blocks CTLA-4. `, 
        state: `notAnswered`,
        userAnswered: [],
    
        type: `MCSS`},
    {
        q: `A 48-year-old woman with a history of seizure disorder presents with recurrent gross hematuria and left flank pain. Abdominal CT shows a large left perinephric hematoma associated with a 3.0-cm left renal angiomyolipoma. There are also multiple right renal angiomyolipomas ranging in size from 1.5 to 6.5 cm. What is the best management of the left renal lesion?`,
        q2: ``,
        q3: [],
        option: [`Selective embolization`, 
        `Radical nephrectomy`, 
        `Observation`, 
        `Partial nephrectomy`, 
        `Laparoscopic exposure and renal cryoablative therapy`],
        optionFeedback: [``,
        ``,
        ``,
        ``,
        
        ``],
        optionStyleType: `st-lower-alpha`,
        answer: [0],
        ansText:`Rationale:<!--<b>a. Selective embolization.</b>--> Most patients with acute or potentially life-threatening hemorrhage will require total nephrectomy if exploration is performed, and if the patient has TSC, bilateral disease, preexisting renal insufficiency, or other medical or urologic disease that could affect renal function in the future, selective embolization should be considered. In such circumstances, selective embolization can temporize by controlling hemorrhage and in many cases will prove to be definitive treatment. This patient almost certainly has TSC given bilateral AMLs and history of seizures. `, 
        state: `notAnswered`,
        userAnswered: [],
	type: `MCSS`        ,
        type: `MCSS`},
    {
        q: `Which of the following statements is TRUE regarding cystic nephromas occurring in adults?`,
        q2: ``,
        q3: [],
        option: [`They are complex cystic lesions that are typically classified as Bosniak II to III.`, 
        `They are malignant 2% to 5% of the time.`, 
        `They are more common in men than in women.`, 
        `When suspected, they should be treated by radical nephrectomy.`, 
        `They are readily differentiated from cystic RCC on the basis of appropriate imaging studies.`],
        optionFeedback: [``,
        ``,
        ``,
        ``,
        
        ``],
        optionStyleType: `st-lower-alpha`,
        answer: [0],
        ansText:`Rationale:<!--<b>a. They are complex cystic lesions that are typically classified as Bosniak II to III.</b>--> <b>Cystic nephromas are benign renal neoplasms that occur most commonly in middle-aged women.</b> They appear to be genetically related to MEST but generally have a somewhat different radiographic appearance. Unlike MEST, which contain a solid stromal component and often appear as solid or Bosniak IV lesions on cross-sectional imaging, cystic nephromas are typically characterized as complex cystic lesions without a solid component. `, 
        state: `notAnswered`,
        userAnswered: [],
    
        type: `MCSS`},
    {
        q: `Which environmental factor is most commonly accepted as a risk factor for RCC?`,
        q2: ``,
        q3: [],
        option: [`Radiation therapy`, 
        `Antihypertensive medications`, 
        `Tobacco use`, 
        `Diuretics`, 
        `High-fat diet`],
        optionFeedback: [``,
        ``,
        ``,
        ``,
        
        ``],
        optionStyleType: `st-lower-alpha`,
        answer: [2],
        ansText:`Rationale:<!--<b>c. Tobacco use.</b>--> The most generally accepted environmental risk factor for RCC is tobacco use, although the relative associated risks have been modest, ranging from 1.4 to 2.3 when compared with controls. All forms of tobacco use have been implicated, with risk increasing with cumulative dose or pack-years. <b>Other well-established risk factors include obesity and hypertension.</b> `, 
        state: `notAnswered`,
        userAnswered: [],
    
        type: `MCSS`},
    {
        q: `Which of the following manifestations is common only in certain VHL families; specifically, which is common in those with type 2 and only rarely seen in type 1 VHL?`,
        q2: ``,
        q3: [],
        option: [`RCC`, 
        `Pancreatic cysts or tumors`, 
        `Epididymal tumors`, 
        `Pheochromocytoma`, 
        `Inner ear tumors`],
        optionFeedback: [``,
        ``,
        ``,
        ``,
        
        ``],
        optionStyleType: `st-lower-alpha`,
        answer: [3],
        ansText:`Rationale:<!--<b>d. Pheochromocytoma.</b>--> The familial form of clear cell RCC is the VHL syndrome. Major manifestations include the development of RCC, pheochromocytoma, retinal angiomas, and hemangioblastomas of the brainstem, cerebellum, or spinal cord. <b>Penetrance for all of these traits is far from complete, and some, such as pheochromocytomas, tend to be clustered in certain families but not in others.</b> `, 
        state: `notAnswered`,
        userAnswered: [],
    
        type: `MCSS`},
    {
        q: `Common manifestations of VHL disease include:`,
        q2: ``,
        q3: [],
        option: [`RCC, pheochromocytoma, fibrofolliculoma`, 
        `angiomyolipoma, pheochromocytoma, fibrofolliculoma`, 
        `RCC, pheochromocytoma, hemangioblastoma`, 
        `angiomyolipoma, pheochromocytoma, hemangioblastoma`, 
        `RCC, thyroid carcinoma, leiomyoma`],
        optionFeedback: [``,
        ``,
        ``,
        ``,
        
        ``],
        optionStyleType: `st-lower-alpha`,
        answer: [2],
        ansText:`Rationale: <!--<b>c. RCC, pheochromocytoma, hemangioblastoma.</b>--> These are the three most common tumor types occurring in VHL disease. Facial fibrofolliculomas occur in BHD syndrome, and uterine leiomyomas are commonly seen in hereditary leiomyomatosis and RCC syndrome.`, 
        state: `notAnswered`,
        userAnswered: [],
    
        type: `MCSS`},
    {
        q: `What is the most common cause of death in patients with the VHL syndrome?`,
        q2: ``,
        q3: [],
        option: [`Renal failure`, 
        `Cerebellar hemangioblastoma`, 
        `Unrelated medical disease`, 
        `Pheochromocytoma`, 
        `RCC`],
        optionFeedback: [``,
        ``,
        ``,
        ``,
        
        ``],
        optionStyleType: `st-lower-alpha`,
        answer: [4],
        ansText:`Rationale: <!--<b>e. RCC.</b>--> With improved management of the central nervous system manifestations of the disease, RCC is the most common cause of mortality in patients with VHL syndrome.`, 
        state: `notAnswered`,
        userAnswered: [],
    
        type: `MCSS`},
    {
        q: `The VHL syndrome tumor suppressor protein regulates the expression of which of the following mediators of biologic aggressiveness for RCC?`,
        q2: ``,
        q3: [],
        option: [`Basic fibroblast growth factor`, 
        `Vascular endothelial cell growth factor`, 
        `Epidermal growth factor receptor (EGFR)`, 
        `Hepatocyte growth factor (scatter factor)`, 
        `P-glycoprotein (multiple drug resistance efflux protein)`],
        optionFeedback: [``,
        ``,
        ``,
        ``,
        
        ``],
        optionStyleType: `st-lower-alpha`,
        answer: [1],
        ansText:`Rationale:<!--<b>b. Vascular endothelial cell growth factor.</b>--> Inactivation or mutation of the VHL gene leads to dysregulated expression of hypoxia inducible factor-1, an intracellular protein that plays an important role in regulating cellular responses to hypoxia, starvation, and other stresses. This in turn leads to a several-fold upregulation of the expression of VEGF, the primary proangiogenic growth factor in RCC, contributing to the pronounced neovascularity associated with this carcinoma. `, 
        state: `notAnswered`,
        userAnswered: [],
    
        type: `MCSS`},
    {
        q: `What do the hereditary papillary RCC syndrome and VHL syndrome have in common?`,
        q2: ``,
        q3: [],
        option: [`Mode of genetic transmission`, 
        `Chromosome 3 abnormalities`, 
        `Propensity toward tumor formation in multiple organ systems`, 
        `Inactivation of a tumor suppressor gene`, 
        `Nearly complete penetrance`],
        optionFeedback: [``,
        ``,
        ``,
        ``,
        
        ``],
        optionStyleType: `st-lower-alpha`,
        answer: [0],
        ansText:`Rationale:<!--<b>a. Mode of genetic transmission.</b>--> Studies of families with hereditary papillary renal carcinoma (HPRC) have demonstrated an autosomal dominant mode of transmission, similar to VHL disease. VHL is caused by inactivation or mutation of a tumor suppressor gene, whereas HPRC is caused by activation of an oncogene. `, 
        state: `notAnswered`,
        userAnswered: [],
    
        type: `MCSS`},
    {
        q: `Mutation of the met proto-oncogene in hereditary papillary RCC leads to:`,
        q2: ``,
        q3: [],
        option: [`increased expression of hepatocyte growth factor.`, 
        `increased sensitivity to vascular endothelial growth factor (VEGF).`, 
        `inactivation of a tumor suppressor gene that regulates cellular proliferation.`, 
        `constitutive activation of the receptor for hepatocyte growth factor.`, 
        `increased expression of VEGF.`],
        optionFeedback: [``,
        ``,
        ``,
        ``,
        
        ``],
        optionStyleType: `st-lower-alpha`,
        answer: [3],
        ansText:`Rationale:<!--<b>d. Constitutive activation of the receptor for hepatocyte growth factor.</b>--> Missense mutations of the <b><i>met</i></b> proto-oncogene at 7q31 were found to segregate with the disease, implicating it as the relevant genetic locus. The protein product of this gene is the receptor tyrosine kinase for the hepatocyte growth factor, which plays an important role in regulating the proliferation and differentiation of epithelial and endothelial cells in a wide variety of organs, including the kidney. Most of the mutations in hereditary papillary RCC have been found in the tyrosine kinase domain of <b><i>met</i></b> and lead to constitutive activation. `, 
        state: `notAnswered`,
        userAnswered: [],
    
        type: `MCSS`},
    {
        q: `P-glycoprotein is a transmembrane protein that is involved in:`,
        q2: ``,
        q3: [],
        option: [`immunotolerance.`, 
        `resistance to high-dose IL-2 therapy.`, 
        `resistance to cisplatin therapy.`, 
        `resistance to radiation therapy.`, 
        `efflux of large hydrophobic compounds, including many cytotoxic drugs.`],
        optionFeedback: [``,
        ``,
        ``,
        ``,
        
        ``],
        optionStyleType: `st-lower-alpha`,
        answer: [4],
        ansText:`Rationale:<!--<b>e. Efflux of large hydrophobic compounds, including many cytotoxic drugs.</b>--> P-glycoprotein is a 170-kDa transmembrane protein expressed by 80% to 90% of RCCs that acts as an energy-dependent efflux pump for a wide variety of large hydrophobic compounds, including several cytotoxic drugs. `, 
        state: `notAnswered`,
        userAnswered: [],
    
        type: `MCSS`},
    {
        q: `<!--27. -->Pathology demonstrates venous involvement limited to the main renal vein along with contralateral adrenal involvement with RCC. There is also a 6-cm bulky retroperitoneal lymph node replaced with cancer. What is the stage?`,
        q2: ``,
        q3: [],
        option: [`pT3aN1M0`, 
        `pT3aN2M0`, 
        `pT3aN1M1`, 
        `pT3bN1M1`, 
        `pT4N2M0`],
        optionFeedback: [``,
        ``,
        ``,
        ``,
        
        ``],
        optionStyleType: `st-lower-alpha`,
        answer: [2],
        ansText:`Rationale:<!--<b>c. pT3aN1M1.</b>--> <b>Isolated renal vein involvement is now classified as T3a, and nodal classification has been simplified such that all nodal involvement is now classified as N1.</b> Contiguous invasion of the ipsilateral adrenal is now classified as T4, but metastatic involvement of the contralateral (or ipsilateral) adrenal gland is classified as M1, reflecting a likely hematogenous pattern of dissemination. `, 
        state: `notAnswered`,
        userAnswered: [],
    
        type: `MCSS`},
    {
        q: `Which of the following is most likely to demonstrate an infiltrative growth pattern?`,
        q2: ``,
        q3: [],
        option: [`Clear cell RCC`, 
        `Sarcomatoid variants of RCC`, 
        `Papillary RCC`, 
        `Chromophobe RCC`, 
        `Oncocytoma`],
        optionFeedback: [``,
        ``,
        ``,
        ``,
        
        ``],
        optionStyleType: `st-lower-alpha`,
        answer: [1],
        ansText:`Rationale:<!--<b>b. Sarcomatoid variants of RCC.</b>--> Most RCCs are round to ovoid and circumscribed by a pseudocapsule of compressed parenchyma and fibrous tissue rather than a true histologic capsule. Unlike upper tract transitional cell carcinomas (TCCs), most RCCs are not grossly infiltrative, with the notable exception of some sarcomatoid variants. `, 
        state: `notAnswered`,
        userAnswered: [],
    
        type: `MCSS`},
    {
        q: `What is the most common mutation identified in sporadic clear cell RCC?`,
        q2: ``,
        q3: [],
        option: [`Activation of the met proto-oncogene`, 
        `Activation of the VHL gene`, 
        `Inactivation of the VHL gene`, 
        `Inactivation of p53`, 
        `Inactivation of genes on chromosome 9`],
        optionFeedback: [``,
        ``,
        ``,
        ``,
        
        ``],
        optionStyleType: `st-lower-alpha`,
        answer: [2],
        ansText:`Rationale:<!--<b>c. Inactivation of the VHL gene.</b>--> Chromosome 3 alterations and VHL mutations are common in conventional RCC, and mutation or inactivation of this gene has been found in over 75% of sporadic cases. `, 
        state: `notAnswered`,
        userAnswered: [],
    
        type: `MCSS`},
    {
        q: `Which of the following cytogenetic abnormalities is commonly associated with type 1 papillary RCC?`,
        q2: ``,
        q3: [],
        option: [`Trisomy of chromosome 7`, 
        `Trisomy of the Y chromosome`, 
        `Loss of chromosome 17`, 
        `Loss of all or parts of chromosome 3`, 
        `Loss of chromosome 7`],
        optionFeedback: [``,
        ``,
        ``,
        ``,
        
        ``],
        optionStyleType: `st-lower-alpha`,
        answer: [0],
        ansText:`Rationale:<!--<b>a. Trisomy of chromosome 7.</b>--> The cytogenetic abnormalities associated with type 1 papillary RCC are characteristic and include trisomy of chromosomes 7 and 17. `, 
        state: `notAnswered`,
        userAnswered: [],
    
        type: `MCSS`},
    {
        q: `What percentage of RCCs are chromophobe cell carcinomas?`,
        q2: ``,
        q3: [],
        option: [`0% to 2%`, 
        `3% to 5%`, 
        `8% to 10%`, 
        `12% to 15%`, 
        `18% to 25%`],
        optionFeedback: [``,
        ``,
        ``,
        ``,
        
        ``],
        optionStyleType: `st-lower-alpha`,
        answer: [1],
        ansText:`Rationale:<!--<b>b. 3% to 5%.</b>--> <b>Chromophobe cell carcinoma is a distinctive histologic subtype of RCC that appears to be derived from the cortical portion of the collecting duct.</b> It represents 3% to 5% of all RCCs. `, 
        state: `notAnswered`,
        userAnswered: [],
    
        type: `MCSS`},
    {
        q: `Most renal medullary carcinomas are:`,
        q2: ``,
        q3: [],
        option: [`found in patients with sickle cell disease.`, 
        `diagnosed in the fifth decade of life.`, 
        `responsive to high-dose chemotherapy.`, 
        `genetically and histologically similar to papillary RCC.`, 
        `metastatic at the time of diagnosis.`],
        optionFeedback: [``,
        ``,
        ``,
        ``,
        
        ``],
        optionStyleType: `st-lower-alpha`,
        answer: [4],
        ansText:`Rationale:<!--<b>e. Metastatic at the time of diagnosis.</b>--> <b>Renal medullary carcinoma is a rare histologic subtype of RCC that occurs almost exclusively in association with sickle cell trait.</b> It is typically diagnosed in young African Americans, often in the third decade of life. Many cases are both locally advanced and metastatic at the time of diagnosis. Most patients have not responded to therapy and have succumbed to their disease in a few to several months. `, 
        state: `notAnswered`,
        userAnswered: [],
    
        type: `MCSS`},
    {
        q: `Which paraneoplastic syndrome associated with RCC can often be managed or palliated medically?`,
        q2: ``,
        q3: [],
        option: [`Polycythemia`, 
        `Stauffer syndrome`, 
        `Neuropathy`, 
        `Hypercalcemia`, 
        `Cachexia`],
        optionFeedback: [``,
        ``,
        ``,
        ``,
        
        ``],
        optionStyleType: `st-lower-alpha`,
        answer: [3],
        ansText:`Rationale:<!--<b>d. Hypercalcemia.</b>--> <b>Hypercalcemia has been reported in up to 13% of patients with RCC and can be due to either paraneoplastic phenomena or osteolytic metastatic involvement of the bone. The production of parathyroid hormonelike peptides is the most common paraneoplastic etiology, although tumor-derived 1,25-dihydroxyvitamin D</b><sub>3</sub> <b>and prostaglandins may contribute in a minority of cases.</b> Medical management includes vigorous hydration followed by diuresis with furosemide and the selective use of bisphosphonates, corticosteroids, and/or calcitonin. `, 
        state: `notAnswered`,
        userAnswered: [],
    
        type: `MCSS`},
    {
        q: `A healthy 64-year-old man is found to have a 6.0-cm solid, heterogeneous mass in the hilum of the right kidney. CT of the abdomen and pelvis shows interaortocaval lymph nodes enlarged to 2.5 cm. A chest radiograph and a bone scan are negative, and the contralateral kidney is normal. The serum creatinine level is 1.0 mg/dL. What is the best next step?`,
        q2: ``,
        q3: [],
        option: [`Right radical nephrectomy and regional or extended lymph node dissection`, 
        `Abdominal exploration, sampling of the enlarged lymph nodes, and possible radical nephrectomy pending frozen section analysis`, 
        `CT-guided percutaneous biopsy of the lymph nodes`, 
        `CT-guided percutaneous biopsy of the tumor mass`, 
        `Systemic therapy followed by radical nephrectomy`],
        optionFeedback: [``,
        ``,
        ``,
        ``,
        
        ``],
        optionStyleType: `st-lower-alpha`,
        answer: [0],
        ansText:`Rationale:<!--<b>a. Right radical nephrectomy and regional or extended lymph node dissection.</b>--> An aggressive surgical approach is still preferred because it will likely prolong survival and represents the only realistic chance for a cure. Lymph nodes in this size range are most likely malignant, and this patient will likely need to consider adjuvant clinical trials. An extended lymph node dissection includes the interaortocaval nodes and nodes alongside and behind the ipsilateral great vessel from the crus of the diaphragm to the ipsilateral common iliac artery. `, 
        state: `notAnswered`,
        userAnswered: [],
    
        type: `MCSS`},
    {
        q: `Which of the following patients would be the best candidate for percutaneous biopsy or fine-needle aspiration of a renal mass?`,
        q2: ``,
        q3: [],
        option: [`A 42-year-old man with a 2.5-cm Bosniak III complex renal cyst`, 
        `An 88-year-old man with a 1.7-cm solid, enhancing renal mass`, 
        `A 32-year-old woman with bilateral solid, enhancing renal masses ranging in size from 1.5 to 4.0 cm`, 
        `A 48-year-old woman with a 3.5-cm solid, enhancing renal mass with fat density present`, 
        `A 38-year-old woman with a fever, a urinary tract infection, and a 3.5-cm solid/cystic, enhancing renal mass`],
        optionFeedback: [``,
        ``,
        ``,
        ``,
        
        ``],
        optionStyleType: `st-lower-alpha`,
        answer: [4],
        ansText:`Rationale: <!--<b>e. A 38-year-old woman with a fever, urinary tract infection, and a 3.5-cm solid/cystic, enhancing renal mass.</b>--> Patients with flank pain, a febrile urinary tract infection, and a renal mass should be offered percutaneous biopsy and/or aspiration to establish a diagnosis of renal abscess rather than malignancy, and to provide drainage if abscess is confirmed.`, 
        state: `notAnswered`,
        userAnswered: [],
    
        type: `MCSS`},
    {
        q: `A 67-year-old man undergoes radical nephrectomy and inferior vena caval thrombectomy (level 2 tumor thrombus). The primary tumor is otherwise confined to the kidney, and the lymph nodes are not involved. What is the approximate 5-year cancer-free survival rate?`,
        q2: ``,
        q3: [],
        option: [`0% to 15%`, 
        `16% to 30%`, 
        `31% to 50%`, 
        `51% to 70%`, 
        `71% to 90%`],
        optionFeedback: [``,
        ``,
        ``,
        ``,
        
        ``],
        optionStyleType: `st-lower-alpha`,
        answer: [2],
        ansText:`Rationale:<!--<b>c. 31% to 50%.</b>--> Venous involvement with tumor thrombi was once thought to be a dismal sign for patients with RCC, but more recent studies suggest that many patients with tumor thrombi can be salvaged with an aggressive surgical approach. These studies document 31% to 50% 5-year survival rates for patients with IVC thrombus thrombi, as long as the tumor is otherwise confined to the kidney. `, 
        state: `notAnswered`,
        userAnswered: [],
    
        type: `MCSS`},
    {
        q: `Which of the following is NOT a predictor of cancer-specific survival after nephrectomy for RCC?`,
        q2: ``,
        q3: [],
        option: [`Pathologic stage`, 
        `Tumor size`, 
        `Nuclear grade`, 
        `Patient age`, 
        `Histologic necrosis`],
        optionFeedback: [``,
        ``,
        ``,
        ``,
        
        ``],
        optionStyleType: `st-lower-alpha`,
        answer: [3],
        ansText:`Rationale:<!--<b>d. Patient age.</b>--> Although patient age and comorbidity are important predictors of overall survival in patients with RCC and strongly affect the choice of treatment in these patients, they have no effect on the likelihood of dying of cancer-specific causes. Each of the other factors is a predictor of cancer-specific mortality from RCC and has been incorporated into one or more RCC prognostic algorithms for cancer-specific outcomes. `, 
        state: `notAnswered`,
        userAnswered: [],
    
        type: `MCSS`},
    {
        q: `Which of the following statements about renal lymphoma is TRUE?`,
        q2: ``,
        q3: [],
        option: [`5% to 10% of all lymphomas involving the kidney are primary tumors.`, 
        `The radiographic patterns manifested by renal lymphoma are diverse and can be difficult to differentiate from RCC.`, 
        `Percutaneous biopsy is rarely indicated if renal lymphoma is suspected.`, 
        `Renal failure associated with renal lymphoma is most often due to extensive parenchymal replacement by the malignancy.`, 
        `The most common pattern of renal involvement is by direct extension from adjacent retroperitoneal lymph nodes.`],
        optionFeedback: [``,
        ``,
        ``,
        ``,
        
        ``],
        optionStyleType: `st-lower-alpha`,
        answer: [1],
        ansText:`Rationale:<!--<b>b. The radiographic patterns manifested by renal lymphoma are diverse and can be difficult to differentiate from RCC.</b>--> Five different radiographic patterns have been described for lymphoma involving the kidney, including a solitary mass, occasionally making it difficult to differentiate from RCC. `, 
        state: `notAnswered`,
        userAnswered: [],
    
        type: `MCSS`},
    {
        q: `Which of the following would be considered diagnostic for renal angiomyolipoma (AML)?`,
        q2: ``,
        q3: [],
        option: [`Hyperechoic pattern on ultrasonography`, 
        `Enhancement of &gt;30 Hounsfield units on CT scan`, 
        `Small area measuring less than −20 Hounsfield units on non-enhanced CT`, 
        `Aneurysmal changes on renal arteriogram`, 
        `Positive signal on T2 images of MRI`],
        optionFeedback: [``,
        ``,
        ``,
        ``,
        
        ``],
        optionStyleType: `st-lower-alpha`,
        answer: [2],
        ansText:`Rationale: <!--<b>c. Small area measuring less than −20 Hounsfield units on non-enhanced CT.</b>--> <b>The presence of even a small focus of fat, as evidenced by a density less than − 20 HU on a non-enhanced CT scan, is diagnostic for AML.</b> The findings described in a, b, and d are all suggestive of, but not diagnostic for, renal AML.`, 
        state: `notAnswered`,
        userAnswered: [],
    
        type: `MCSS`},
    {
        q: `The main limitation of renal mass biopsy is:`,
        q2: ``,
        q3: [],
        option: [`risk of needle tract seeding.`, 
        `difficulty differentiating the eosinophilic variants of RCC from renal oncocytoma.`, 
        `risk of pneumothorax.`, 
        `risk of hemorrhage.`, 
        `inability to determine subtype of RCC.`],
        optionFeedback: [``,
        ``,
        ``,
        ``,
        
        ``],
        optionStyleType: `st-lower-alpha`,
        answer: [1],
        ansText:`Rationale:<!--<b>b. Difficulty differentiating the eosinophilic variants of RCC from renal oncocytoma.</b>--> The main limitation of renal mass biopsy is difficulty differentiating renal oncocytoma, the most common benign renal mass, from eosinophilic variants of conventional, papillary, and chromophobe RCC on biopsy material. While the non-diagnostic rate is between 10% and 15%, the risk of complications is low in the modern era with the use of smaller-gauge needles, and needle tract seeding with RCC appears to be a rare event. `, 
        state: `notAnswered`,
        userAnswered: [],
    
        type: `MCSS`},
    {
        q: `Which of the following tumors is most likely to be a malignant RCC?`,
        q2: ``,
        q3: [],
        option: [`2.5-cm hyperechoic complex cyst, with no enhancement with IV contrast`, 
        `6.0-cm complex cyst with four thin septae`, 
        `5.0-cm cyst with thin, curvilinear calcification`, 
        `11-cm cyst with water density and homogeneous nature`, 
        `3.0-cm solid lesion with fat associated with calcification`],
        optionFeedback: [``,
        ``,
        ``,
        ``,
        
        ``],
        optionStyleType: `st-lower-alpha`,
        answer: [4],
        ansText:`Rationale: <!--<b>e. 3.0-cm solid lesion with fat associated with calcification.</b>--> Tumors with calcification associated with fat are uncommon but are almost always malignant RCC. In this setting the fat is thought to be a reactive process related to tumor necrosis. Calcification is virtually never seen in association with AML. The lesions described in a–c are Bosniak II renal cysts, with risk of malignancy of &lt;10%. The lesion described in d is a simple cyst and highly likely to be benign despite its large size.`, 
        state: `notAnswered`,
        userAnswered: [],
    
        type: `MCSS`},
    {
        q: `A common and pathogenic cytogenetic finding in children with RCC is:`,
        q2: ``,
        q3: [],
        option: [`<i>VHL</i> mutation.`, 
        `<i>cMET</i> oncogene mutation.`, 
        `<i>p53</i> mutation.`, 
        `<i>TFE3</i> gene fusions.`, 
        `<i>PTEN</i> mutations.`],
        optionFeedback: [``,
        ``,
        ``,
        ``,
        
        ``],
        optionStyleType: `st-lower-alpha`,
        answer: [3],
        ansText:`Rationale:<!--<b>d. <i>TFE3</i> gene fusions.</b>--> Mutations or translocations resulting in <b><i>TFE3</i></b> gene fusions are common in RCC occurring in the pediatric population. Although these cancers often present with advanced stage, the t(X;17) variant frequently follows an indolent course, while t(X;1) cancers can recur with late lymph node metastases. `, 
        state: `notAnswered`,
        userAnswered: [],
    
        type: `MCSS`},
    {
        q: `According to the 2017 AUA Guidelines, which of the following statements about TA is TRUE?`,
        q2: ``,
        q3: [],
        option: [`TA should be prioritized in elderly patients with comorbidities.`, 
        `In general, a tumor size threshold of 2.5 cm should be applied for decision making about TA.`, 
        `Renal mass biopsy should be performed at the time of TA whenever it might change management`, 
        `Local recurrence is more common after TA than partial nephrectomy, but when repeat ablation is taken into account, similar local control rates are observed.`, 
        `Repeat ablation is feasible in some patients, but surgical resection is often required after failed TA.`],
        optionFeedback: [``,
        ``,
        ``,
        ``,
        
        ``],
        optionStyleType: `st-lower-alpha`,
        answer: [3],
        ansText:`Rationale:<!--<b>d. Local recurrence is more common after TA than partial nephrectomy, but when repeat ablation is taken into account, similar local control rates are observed.</b>--> Renal mass biopsy should always be performed prior to or concomitant with TA, as it will help guide surveillance. Most local failures of TA can be salvaged with repeat TA, and only a small minority of such patients end up requiring salvage surgery. Success rates TA, for tumors &lt;3.0 cm have been encouraging, and this threshold is advocated in the Guidelines as a general reference point. TA can be a good choice in some elderly patients with comorbidities, but active surveillance is also a reasonable option and in reality is often a better choice for many such patients. `, 
        state: `notAnswered`,
        userAnswered: [],
    
        type: `MCSS`},
    {
        q: `What is the mechanism of action for nivolumab?`,
        q2: ``,
        q3: [],
        option: [`Activates CTLA-4`, 
        `Blocks CTLA-4`, 
        `Activates PD-1`, 
        `Blocks PD-1`, 
        `Blocks PD-L1`],
        optionFeedback: [``,
        ``,
        ``,
        ``,
        
        ``],
        optionStyleType: `st-lower-alpha`,
        answer: [3],
        ansText:`Rationale:<!--<b>c. Activates PD-1.</b>--> <b>The mechanism of action of nivolumab is to block PD-1 and thus activate the immune system.</b> Pembrolizumab also blocks PD-1, while atezolizumab blocks PD-L1 and ipilimumab blocks CTLA-4. `, 
        state: `notAnswered`,
        userAnswered: [],
    
        type: `MCSS`},
    {
        q: `According to the 8th edition of the AJCC TNM classification (2016), which of the following tumors would NOT be considered stage pT3a?`,
        q2: ``,
        q3: [],
        option: [`4.3 cm RCC with renal sinus fat invasion`, 
        `12 cm RCC with involvement of the renal vein`, 
        `5.6 cm RCC with invasion into the perinephric fat`, 
        `4.8 cm RCC with invasion into the adrenal gland`, 
        `6.4 cm RCC with collecting system involvement`],
        optionFeedback: [``,
        ``,
        ``,
        ``,
        
        ``],
        optionStyleType: `st-lower-alpha`,
        answer: [3],
        ansText:`Rationale:<!--<b>d. 4.8 cm RCC with invasion into the adrenal gland.</b>--> Direct invasion of the adrenal gland is pT4 and metastatic involvement of the adrenal gland is pM1. All of the other characteristics are indicative of pT3a tumors, including collecting system involvement (a modification made in the 8th edition). `, 
        state: `notAnswered`,
        userAnswered: [],
    
        type: `MCSS`},
    {
        q: `Most tumors at various sites in the VHL syndrome share the following characteristic:`,
        q2: ``,
        q3: [],
        option: [`Malignant behavior`, 
        `Hypervascularity`, 
        `Rapid growth rate`, 
        `High nuclear grade`, 
        `Symptomatic presentation`],
        optionFeedback: [``,
        ``,
        ``,
        ``,
        
        ``],
        optionStyleType: `st-lower-alpha`,
        answer: [1],
        ansText:`Rationale:<!--<b>b. Hypervascularity.</b>--> Tumors in the VHL syndrome include adrenal pheochromocytoma, retinal angiomas, cerebellar and brainstem hemangioblastoma, RCC, and others. Most are relatively slow growing and asymptomatic if patients are evaluated and screened in a proactive manner. The common feature is that almost all are hypervascular. `, 
        state: `notAnswered`,
        userAnswered: [],
    
        type: `MCSS`},
    {
        q: `One major difference between hereditary papillary RCC syndrome and VHL syndrome is:`,
        q2: ``,
        q3: [],
        option: [`pattern of genetic inheritance.`, 
        `age of onset.`, 
        `gender distribution.`, 
        `incidence of metastasis.`, 
        `incidence of associated tumors in nonrenal organ systems.`],
        optionFeedback: [``,
        ``,
        ``,
        ``,
        
        ``],
        optionStyleType: `st-lower-alpha`,
        answer: [4],
        ansText:`Rationale:<!--<b>e. Incidence of associated tumors in nonrenal organ systems.</b>--> The incidence of nonrenal tumors is low in the hereditary papillary RCC syndrome in contrast to VHL syndrome, in which patients commonly develop tumors in the eyes, spinal cord, cerebellum, adrenal glands, inner ear, epididymis, and pancreas. `, 
        state: `notAnswered`,
        userAnswered: [],
    
        type: `MCSS`},
    {
        q: `Which syndrome is most likely to exhibit aggressive behavior of RCC?`,
        q2: ``,
        q3: [],
        option: [`VHL syndrome`, 
        `Hereditary papillary RCC syndrome`, 
        `Hereditary leiomyomatosis and RCC syndrome`, 
        `Birt-Hogg-Dubé (BHD) syndrome`, 
        `Familial oncocytosis`],
        optionFeedback: [``,
        ``,
        ``,
        ``,
        
        ``],
        optionStyleType: `st-lower-alpha`,
        answer: [2],
        ansText:`Rationale:<!--<b>c. Hereditary leiomyomatosis and RCC syndrome.</b>--> Malignant behavior is particularly common in the hereditary leiomyomatosis and RCC syndrome, and proactive and aggressive surgical management is recommended. `, 
        state: `notAnswered`,
        userAnswered: [],
    
        type: `MCSS`},
    {
        q: `Spontaneous pneumothorax is occasionally observed in which of the following?`,
        q2: ``,
        q3: [],
        option: [`VHL syndrome`, 
        `Hereditary papillary RCC syndrome`, 
        `Hereditary leiomyomatosis and RCC syndrome`, 
        `BHD syndrome`, 
        `Familial oncocytosis`],
        optionFeedback: [``,
        ``,
        ``,
        ``,
        
        ``],
        optionStyleType: `st-lower-alpha`,
        answer: [3],
        ansText:`Rationale:<!--<b>d. BHD syndrome.</b>--> Lung cysts and spontaneous pneumothoraces are well described and relatively common findings in the BHD syndrome. `, 
        state: `notAnswered`,
        userAnswered: [],
    
        type: `MCSS`},
    {
        q: `Chromophobe RCC shares many characteristics with:`,
        q2: ``,
        q3: [],
        option: [`oncocytoma.`, 
        `type 2 papillary RCC.`, 
        `clear cell RCC.`, 
        `mesoblastic nephroma.`, 
        `mixed epithelial and stromal tumor (MEST) of the kidney.`],
        optionFeedback: [``,
        ``,
        ``,
        ``,
        
        ``],
        optionStyleType: `st-lower-alpha`,
        answer: [0],
        ansText:`Rationale:<!--<b>a. Oncocytoma.</b>--> Both chromophobe RCC and renal oncocytoma are derived from the distal tubules, and both are commonly observed in the BHD syndrome. There are also some overlapping cytogenetic changes, all suggesting a potential relationship between these renal tumors. `, 
        state: `notAnswered`,
        userAnswered: [],
    
        type: `MCSS`},
    {
        q: `A finding that is diagnostic for collecting duct carcinoma is:`,
        q2: ``,
        q3: [],
        option: [`central location and infiltrative growth pattern.`, 
        `aggressive clinical course.`, 
        `<i>p53</i> mutation.`, 
        `positive staining for <i>Ulex europaeus</i> lectin.`, 
        `sensitivity to chemotherapy.`],
        optionFeedback: [``,
        ``,
        ``,
        ``,
        
        ``],
        optionStyleType: `st-lower-alpha`,
        answer: [3],
        ansText:`Rationale:<!--<b>d. Positive staining for <i>Ulex europaeus</i> lectin.</b>--> <b><i>Ulex europaeus</i></b> lectin is expressed by the normal collecting duct, and tumor staining suggests origin from this structure. Most collecting duct carcinomas are centrally located and exhibit an infiltrative growth pattern and aggressive clinical course, but this is also true for poorly differentiated TCCs of the renal pelvis or centrally located sarcomatoid RCC. Collecting duct RCC is not typically responsive to chemotherapy. `, 
        state: `notAnswered`,
        userAnswered: [],
    
        type: `MCSS`},
    {
        q: `Sarcomatoid differentiation is most commonly observed with which histologic subtypes of RCC?`,
        q2: ``,
        q3: [],
        option: [`Clear cell and papillary`, 
        `Papillary and chromophobe`, 
        `Clear cell and collecting duct`, 
        `Clear cell and chromophobe`, 
        `Chromophobe and collecting duct`],
        optionFeedback: [``,
        ``,
        ``,
        ``,
        
        ``],
        optionStyleType: `st-lower-alpha`,
        answer: [3],
        ansText:`Rationale:<!--<b>d. Clear cell and chromophobe.</b>--> Sarcomatoid differentiation is most commonly found in association with clear cell and chromophobe RCC. `, 
        state: `notAnswered`,
        userAnswered: [],
    
        type: `MCSS`},
    {
        q: `Which of the following factors has greatest utility for predicting bone metastasis from RCC?`,
        q2: ``,
        q3: [],
        option: [`Tumor size`, 
        `Tumor grade`, 
        `Performance status (PS)`, 
        `Elevated alkaline phosphatase`, 
        `Invasion of the perinephric fat`],
        optionFeedback: [``,
        ``,
        ``,
        ``,
        
        ``],
        optionStyleType: `st-lower-alpha`,
        answer: [2],
        ansText:`Rationale:<!--<b>c. Performance status (PS).</b>--> Poor PS can be used to segregate patients when deciding whether to obtain a bone scan for metastatic RCC. Shvarts and colleagues (2004)<a href="[remark:8896d7ebfd27402dab600887f0158b02]"><sup>a</sup></a> have shown that patients with good PS (ECOG PS = 0), no evidence of extraosseous metastases, and no bone pain were extremely low risk for bone metastasis and did not benefit from bone scanning. They recommended a bone scan for all other patients, and the incidence of bone metastasis in this group was &gt;15%. `, 
        state: `notAnswered`,
        userAnswered: [],
    
        type: `MCSS`},
    {
        q: `The prognosis for a 3-cm tumor infiltrating the renal sinus fat is:`,
        q2: ``,
        q3: [],
        option: [`similar to a pT1bN0 tumor.`, 
        `similar to a pT2aN0 tumor.`, 
        `similar to a pT3a tumor with invasion of the perinephric fat laterally.`, 
        `worse than a pT3a tumor with invasion of the perinephric fat laterally.`, 
        `similar to a tumor with ipsilateral adrenal involvement.`],
        optionFeedback: [``,
        ``,
        ``,
        ``,
        
        ``],
        optionStyleType: `st-lower-alpha`,
        answer: [3],
        ansText:`Rationale:<!--<b>d. Worse than a pT3a tumor with invasion of the perineph-ric fat laterally.</b>--> Invasion of the perisinus fat medially has been shown to be a poor prognostic sign. Medial invasion places the tumor in proximity to the venous system and likely increases the risk of metastatic dissemination. Ipsilateral adrenal involvement is even worse, and these are now classified as pT4 if due to direct local extension, or pM1 otherwise, consistent with a hematogenous route of dissemination. `, 
        state: `notAnswered`,
        userAnswered: [],
    
        type: `MCSS`},
    {
        q: `The single most important prognostic factor for RCC is:`,
        q2: ``,
        q3: [],
        option: [`tumor size.`, 
        `tumor grade.`, 
        `tumor stage.`, 
        `histologic subtype.`, 
        `PS.`],
        optionFeedback: [``,
        ``,
        ``,
        ``,
        
        ``],
        optionStyleType: `st-lower-alpha`,
        answer: [2],
        ansText:`Rationale:<!--<b>c. Tumor stage.</b>--> Although not truly a single factor because it combines tumor size with other information obtained from final pathologic analysis, tumor stage is the most powerful individual predictor of oncologic outcomes. When incorporated into a multi-predictor analysis, such as a nomogram or other multivariable analysis, the predictive ability increases further. `, 
        state: `notAnswered`,
        userAnswered: [],
    
        type: `MCSS`},
    {
        q: `The most accurate assessment of prognosis for patients with RCC is usually provided by:`,
        q2: ``,
        q3: [],
        option: [`tumor size.`, 
        `clinician judgment.`, 
        `tumor stage.`, 
        `integrated analysis of prognostic factors.`, 
        `PS.`],
        optionFeedback: [``,
        ``,
        ``,
        ``,
        
        ``],
        optionStyleType: `st-lower-alpha`,
        answer: [3],
        ansText:`Rationale: <!--<b>d. Integrated analysis of prognostic factors.</b>--> Integrated analysis of a variety of factors such as tumor size, stage, and grade, PS, and histologic subtype has yielded the most accurate prognostication for RCC. Several studies have documented that nomograms and other algorithms outperform traditional staging systems, clinical opinion, individual risk factors, and chance.`, 
        state: `notAnswered`,
        userAnswered: [],
    
        type: `MCSS`},
    {
        q: `Which of the following indicates a tumor that is NOT correctly staged according to the 2016 TNM staging system for RCC?`,
        q2: ``,
        q3: [],
        option: [`Localized RCC, 8.5 cm: <i>pT2a</i>`, 
        `RCC with direct ipsilateral adrenal involvement: <i>pT3a</i>`, 
        `RCC with metastatic involvement of the adrenal gland: <i>pM1</i>`, 
        `RCC with three lymph node metastases: <i>pN1</i>`, 
        `2.5-cm centrally located tumor after radiofrequency ablation`],
        optionFeedback: [``,
        ``,
        ``,
        ``,
        
        ``],
        optionStyleType: `st-lower-alpha`,
        answer: [1],
        ansText:`Rationale:<!--b. RCC with direct ipsilateral adrenal involvement: <b><i>pT3a.</i></b>--> Several studies have demonstrated that RCC directly invading the adrenal gland is associated with poorer prognosis than RCC with perinephric or renal sinus fat invasion. Direct ipsilateral adrenal involvement is now grouped with other RCCs that extend beyond Gerota fascia as pathologic stage T4 <b><i>(pT4).</i></b> These patients have a high risk for disease recurrence or progression. `, 
        state: `notAnswered`,
        userAnswered: [],
    
        type: `MCSS`},
    {
        q: `What is the most common form of renal sarcoma?`,
        q2: ``,
        q3: [],
        option: [`Liposarcoma`, 
        `Rhabdomyosarcoma`, 
        `Fibrosarcoma`, 
        `Leiomyosarcoma`, 
        `Angiosarcoma`],
        optionFeedback: [``,
        ``,
        ``,
        ``,
        
        ``],
        optionStyleType: `st-lower-alpha`,
        answer: [3],
        ansText:`Rationale:<!--<b>d. Leiomyosarcoma.</b>--> Leiomyosarcoma is the most common histologic subtype of renal sarcoma, accounting for 50% to 60% of such tumors. The most common type of sarcoma in the retroperitoneum is liposarcoma. `, 
        state: `notAnswered`,
        userAnswered: [],
    
        type: `MCSS`},
    {
        q: `The most useful prognostic factors for renal sarcoma are:`,
        q2: ``,
        q3: [],
        option: [`tumor size and grade.`, 
        `tumor stage and grade.`, 
        `histologic subtype and stage.`, 
        `tumor stage and ploidy status.`, 
        `margin status and grade.`],
        optionFeedback: [``,
        ``,
        ``,
        ``,
        
        ``],
        optionStyleType: `st-lower-alpha`,
        answer: [4],
        ansText:`Rationale: <!--<b>e. Margin status and grade.</b>--> Margin status and tumor grade are the primary prognostic factors for sarcoma. Patients with high-grade disease are at risk for systemic metastasis, and those with low-grade disease are at risk for local recurrence. Wide local excision with negative margins is essential for minimizing the risk of recurrence for sarcomas because these tumors are derived from the mesenchymal tissues and are typically infiltrative, and thus do not respect natural barriers.`, 
        state: `notAnswered`,
        userAnswered: [],
    
        type: `MCSS`},
    {
        q: `Which of the following renal tumors has the best prognosis?`,
        q2: ``,
        q3: [],
        option: [`Sarcoma`, 
        `Carcinoid`, 
        `Adult Wilms`, 
        `Primitive neuroectodermal tumor`, 
        `Small cell`],
        optionFeedback: [``,
        ``,
        ``,
        ``,
        
        ``],
        optionStyleType: `st-lower-alpha`,
        answer: [1],
        ansText:`Rationale:<!--<b>b. Carcinoid.</b>--> All of these tumor types have a relatively poor prognosis except for renal carcinoid, which tends to be associated with good outcomes in most patients. `, 
        state: `notAnswered`,
        userAnswered: [],
    
        type: `MCSS`},
    {
        q: `Patients with which RCC subtype are most likely to benefit from targeted therapy, such as tyrosine kinase inhibitors (TKIs)?`,
        q2: ``,
        q3: [],
        option: [`Papillary RCC`, 
        `Clear cell RCC`, 
        `Renal medullary carcinoma`, 
        `Collecting duct carcinoma`, 
        `Chromophobe RCC`],
        optionFeedback: [``,
        ``,
        ``,
        ``,
        
        ``],
        optionStyleType: `st-lower-alpha`,
        answer: [1],
        ansText:`Rationale:<!--<b>b. Clear cell RCC.</b>--> Targeted molecular therapies, such as TKI, mostly target VEGF and thus the pathways that are typically upregulated in clear cell RCC. Most objective responses have been observed in individuals with clear cell RCC. Standard of care for the treatment of metastatic non–clear cell RCC is not well defined at present. `, 
        state: `notAnswered`,
        userAnswered: [],
    
        type: `MCSS`},
    {
        q: `Agents targeting which of the following signaling pathways in clear cell RCC have significant antitumor effects in patients with metastatic disease?`,
        q2: ``,
        q3: [],
        option: [`VEGF and EGFR`, 
        `<i>p53</i> and EGFR`, 
        `VEGF and mammalian target of rapamycin (mTOR)`, 
        `mTOR and transforming growth factor-α (TGF-α)`, 
        `All of the above`],
        optionFeedback: [``,
        ``,
        ``,
        ``,
        
        ``],
        optionStyleType: `st-lower-alpha`,
        answer: [2],
        ansText:`Rationale:<!--<b>c. VEGF and mammalian target of rapamycin (mTOR).</b>--> Several clinical trials indicate that agents targeting VEGF signaling, including sunitinib, sorafenib, axitinib, pazopanib, levantanib, caboxantinib, and mTOR pathway signaling, including temsirolimus and everolimus, demonstrate substantial tumor responses or significant improvement in progression-free or overall survival. `, 
        state: `notAnswered`,
        userAnswered: [],
    
        type: `MCSS`},
    {
        q: `Of the following, which is the greatest determinant of renal function after partial nephrectomy?`,
        q2: ``,
        q3: [],
        option: [`Surgical approach (open vs. minimally invasive)`, 
        `Tumor size`, 
        `Absence of a functioning contralateral kidney`, 
        `Renal function before partial nephrectomy`, 
        `Gender`],
        optionFeedback: [``,
        ``,
        ``,
        ``,
        
        ``],
        optionStyleType: `st-lower-alpha`,
        answer: [3],
        ansText:`Rationale:<!--<b>d. Renal function before partial nephrectomy.</b>--> When compared with radical nephrectomy, partial nephrectomy has been associated with better renal functional outcomes. The main determinants of renal function after partial nephrectomy are the quality of the kidney prior to surgery and the quantity of vascularized parenchymal mass that is preserved after excision of the tumor and reconstruction of the kidney. Warm ischemia time, if prolonged, can also contribute to a decline in renal function after partial nephrectomy. `, 
        state: `notAnswered`,
        userAnswered: [],
    
        type: `MCSS`},
    {
        q: `Which of the following statements is TRUE regarding chronic kidney disease (CKD)?`,
        q2: ``,
        q3: [],
        option: [`CKD due to surgery has the same impact as CKD due to medical causes.`, 
        `Serum creatinine below 1.4 mg/dL excludes the possibility of CKD.`, 
        `CKD can be diagnosed based on a single estimated GFR value less than 60 mL/min/1.73 2.`, 
        `Increasing CKD stage has been associated with an increase in morbid cardiovascular events for subjects in the general population.`, 
        `Choice of intervention for localized renal malignancy has little impact on development or progression of CKD.`],
        optionFeedback: [``,
        ``,
        ``,
        ``,
        
        ``],
        optionStyleType: `st-lower-alpha`,
        answer: [3],
        ansText:`Rationale: <!--<b>d. Increasing CKD stage has been associated with an increase in morbid cardiovascular events, hospitalization, and death on a longitudinal basis for subjects in the general population.</b>--> In this setting, CKD is predominantly due to medical causes. CKD due to surgical causes appears to be more stable and less deleterious than that due to medical causes. `, 
        state: `notAnswered`,
        userAnswered: [],
    
        type: `MCSS`},
    {
        q: `Which of the following is an indication for adrenalectomy at the time of partial nephrectomy?`,
        q2: ``,
        q3: [],
        option: [`6-cm upper pole renal tumor`, 
        `4-cm adrenal lesion measuring −20 Hounsfield units on noncontrast CT scan`, 
        `Bilateral adrenal hyperplasia`, 
        `3-cm renal tumor adjacent to the adrenal gland on CT scan, but readily separable from the adrenal gland at surgery`, 
        `1.5-cm adrenal lesion that is bright on T2-weighted MRI`],
        optionFeedback: [``,
        ``,
        ``,
        ``,
        
        ``],
        optionStyleType: `st-lower-alpha`,
        answer: [4],
        ansText:`Rationale:<!--<b>e. 1.5-cm adrenal lesion that is bright on T2-weighted MR imaging.</b>--> Several pathologic adrenal lesions can be diagnosed based on their radiographic characteristics without histologic confirmation. Lesions that are bright on T2-weighted MR imaging are suspicious for pheochromocytomas and should be surgically removed. Careful preoperative and intraoperative management are essential for safe management in this circumstance. `, 
        state: `notAnswered`,
        userAnswered: [],
    
        type: `MCSS`},
    {
        q: `Which of the following statements is FALSE regarding molecular imaging for renal tumors?`,
        q2: ``,
        q3: [],
        option: [`<sup>99m</sup>Tc-sestamibi SPECT/CT is based on uptake by mitochondria, which are in abundance in oncocytomas and hybrid oncocytic/chromophobe tumors.`, 
        `<sup>124</sup>I-girentuximab targets carbonic anhydrase IX present on clear cell RCC.`, 
        `Fluorodeoxyglucose positron emission tomography (FDG-PET)-CT is useful for staging RCC.`, 
        `Prostate-specific membrane antigen (PSMA) imaging can identify clear cell RCC.`, 
        `While early studies are promising, validation studies are needed before widespread acceptance of current molecular imaging techniques.`],
        optionFeedback: [``,
        ``,
        ``,
        ``,
        
        ``],
        optionStyleType: `st-lower-alpha`,
        answer: [2],
        ansText:`Rationale:<!--c. Fluorodeoxyglucose positron emission tomography (FDG-PET)-CT is useful for staging RCC.--> <b>FDG-PET-CT is not useful for the staging of RCC</b> due to high levels of visual conspicuity in the kidney and at the most common sites of metastatic disease. Sestamibi is taken up by mitochondria, which are in abundance in oncocytolmas and hybrid oncocytic/chromophobe tumors, and a strong signal is suggestive of these histologies. <sup>124</sup>I-girentuximab, which targets carbonic anhydrase IX primarily present on clear cell RCC, and PSMA (epithelial membrane target) remain in development for clear cell RCC. `, 
        state: `notAnswered`,
        userAnswered: [],
    
        type: `MCSS`},
    {
        q: `Which of the following statements most accurately characterizes the role of lymphadenectomy for RCC?`,
        q2: ``,
        q3: [],
        option: [`Offers a staging and therapeutic benefit for patients with clinically localized RCC`, 
        `Offers staging information but not a therapeutic benefit for all patients with RCC`, 
        `Offers a therapeutic benefit mostly for patients with locally advanced RCC`, 
        `Compliance with well-described templates is important for achieving a therapeutic benefit`, 
        `Demonstrated a small but statistically significant survival advantage in a randomized trial`],
        optionFeedback: [``,
        ``,
        ``,
        ``,
        
        ``],
        optionStyleType: `st-lower-alpha`,
        answer: [1],
        ansText:`Rationale:<!--<b>b. Offers staging information but not a therapeutic benefit for all patients with RCC.</b>--> Lymphadenectomy may be performed in patients with clinically suspicious (radiographic or intraoperative) lymphadenopathy for staging purposes and, due to lack of data indicating a reliable therapeutic benefit, need not be performed routinely in patients with localized kidney cancer and clinically negative nodes. The EORTC 30881 randomized trial of lymphadenectomy at RN failed to show a survival advantage for patients undergoing lymphadenectomy. `, 
        state: `notAnswered`,
        userAnswered: [],
    
        type: `MCSS`},
    {
        q: `According to the 2017 AUA Guidelines, which of the following patients with kidney cancer will not need to be considered for nephrology consultation?`,
        q2: ``,
        q3: [],
        option: [`A patient with 50/50 split renal function and a preoperative GFR of 70 mL/min/1.73 m<sup>2</sup> who will be undergoing radical nephrectomy`, 
        `A patient with preoperative GFR of 42 mL/min/1.73 m<sup>2</sup>`, 
        `A patient with confirmed proteinuria`, 
        `A diabetic with preoperative GFR &lt;60 mL/min/1.73 m<sup>2</sup>`, 
        `A patient with a solitary kidney, a preoperative GFR of 36 mL/min/1.73 m<sup>2</sup>, and a R.E.N.A.L. 10 lesion`],
        optionFeedback: [``,
        ``,
        ``,
        ``,
        
        ``],
        optionStyleType: `st-lower-alpha`,
        answer: [1],
        ansText:`Rationale:<!--<b>a. A patient with 50/50 split renal function and a preoperative GFR of 70 mL/min/1.73 m<sup>2</sup> who will be undergoing radical nephrectomy.</b>--> <b>A patient with 50/50 split renal function and a preoperative GFR of 70 mL/min/1.73m</b><sup>2</sup> <b>who will be undergoing radical nephrectomy will likely end up with a new baseline GFR of about 40-42 mL/min/1.73m</b><sup>2</sup> <b>and thus will likely not need referral to nephrology based on the 2017 AUA Guidelines for Renal Mass and Localized RCC.</b> Per the guidelines, referral to nephrology should be considered in patients at high risk for GFR progression, including those with preoperative GFR&lt;45 mL/min/1.73m<sup>2</sup>, confirmed proteinuria, diabetics with preexisting CKD (GFR&lt;60 mL/min/1.73m<sup>2</sup>), or whenever the GFR is expected to be &lt;30 mL/min/1.73m<sup>2</sup> after intervention. `, 
        state: `notAnswered`,
        userAnswered: [],
    
        type: `MCSS`},
    {
        q: `<b>Pathology</b><br/><br/>A 49-year-old man has a biopsy of a peripheral lower pole exophytic 4-cm mass of the right kidney. The histology is depicted in <a href="a0d566c96f014e61a0e930d348baccbc">Fig. 97.2</a> and is read as clear cell carcinoma. Metastatic workup is negative. He should be advised to:`,
        q2: ``,
        q3: [],
        option: [`receive targeted chemotherapy.`, 
        `undergo radical nephrectomy.`, 
        `have the tumor ablated with cryotherapy.`,
        `undergo partial nephrectomy.`, 
        `receive radiation therapy.`],
        optionFeedback: [``,
        ``,
        ``,
        ``,
        
        ``],
        optionStyleType: `st-lower-alpha`,
        answer: [3],
        ansText:`Rationale:<!--<b>d. Undergo partial nephrectomy.</b>--> Notice the clear cytoplasm due to glycogen characteristic of clear cell carcinoma of the kidney. Because of the patient’s young age, a nephron-sparing approach is preferred. Because the tumor is located in the lower pole, is peripheral, and is exophytic, it is ideal for this approach. These tumors are not particularly sensitive to radiation therapy, cryotherapy is not as reliable for local control, and targeted systemic therapy is not appropriate for a surgically curable lesion. `, 
        state: `notAnswered`,
        userAnswered: [],
    
        type: `MCSS`},
    {
        q: `<!--2. -->A 48-year-old woman has a right radical nephrectomy for a 6-cm mass. Preoperative metastatic workup was negative. The pathology is illustrated in <a href="2457a5812d8a4b098f2775608d0b8822">Fig. 97.3</a> and is read as collecting duct carcinoma. She should be advised to:`,
        q2: ``,
        q3: [],
        option: [`receive targeted chemotherapy.`, 
        `receive radiation therapy to the nephrectomy bed.`, 
        `receive platinum-based chemotherapy.`, 
        `follow up with her primary care physician.`, 
        `be followed closely because the development of metastatic disease is likely.`],
        optionFeedback: [``,
        ``,
        ``,
        ``,
        
        ``],
        optionStyleType: `st-lower-alpha`,
        answer: [4],
        ansText:`Rationale:<!--<b>e. Be followed closely because the development of metastatic disease is likely.</b>--> Collecting duct cancers have a high likelihood of being metastatic at diagnosis. None of the other therapies listed are helpful in this disease setting. Cis-platinum chemotherapy is a possibility, but in the absence of known metastasis, its role is not well defined. `, 
        state: `notAnswered`,
        userAnswered: [],
    
        type: `MCSS`},
    {
        q: `<b>Imaging</b><br/><br/>See <a href="e58d8c427a0044eca60b7bd473ef481c">Fig. 97.4</a>. A 55-year-old man with hematuria has this contrast-enhanced CT scan for evaluation. The most appropriate therapy is:`,
        q2: ``,
        q3: [],
        option: [`laparoscopic nephron-sparing surgery.`, 
        `radical nephrectomy.`, 
        `open nephron-sparing surgery.`, 
        `radiofrequency ablation.`, 
        `cryoablation.`],
        optionFeedback: [``,
        ``,
        ``,
        ``,
        
        ``],
        optionStyleType: `st-lower-alpha`,
        answer: [1],
        ansText:`Rationale:<!--<b>b. Radical nephrectomy.</b>--> The images demonstrate a large mass in the lower pole of the right kidney, with tumor extension into the right renal vein, extending to the junction of the right renal vein with the inferior vena cava. The renal vein is enlarged, and tumor vessels are seen within the thrombus in the renal vein. These findings make radical nephrectomy the best option. `, 
        state: `notAnswered`,
        userAnswered: [],
    
        type: `MCSS`},
    {
        q: `See <a href="e072857a89304e01b0d846bfa900b927">Fig. 97.5</a>. A 45-year-old man with no urinary symptoms has this axial contrast-enhanced CT scan. What is the most likely diagnosis?`,
        q2: ``,
        q3: [],
        option: [`Bosniak II-F lesion`, 
        `Bosniak IV—cystic RCC`, 
        `Bosniak II cyst`, 
        `Bosniak III cyst`, 
        `Bosniak I cyst`],
        optionFeedback: [``,
        ``,
        ``,
        ``,
        
        ``],
        optionStyleType: `st-lower-alpha`,
        answer: [1],
        ansText:`Rationale:<!--<b>b. Bosniak IV—cystic RCC.</b>--> Notice the enhancing nodules within the cyst wall with foci of dystrophic calcification making cystic RCC the most likely diagnosis. `, 
        state: `notAnswered`,
        userAnswered: [],
    
        type: `MCSS`},
]