var quiz = [
   
   
    {
        q: `Which of the following are mechanisms of injury or physical exam findings concerning for a potential blunt renal injury?`,
        q2: ``,
        q3: [],
        option: [`Significant blow to the flank`, 
        `Lower rib fractures`, 
        `Significant flank ecchymoses`, 
        ` A fall from a third-story window`, 
        ` All of the above`,
        ],
        optionFeedback: [``,
          ``,
          ``,
          ``,
          ``],
        optionStyleType: `st-lower-alpha`,
        answer: [4],
        ansText: ``,
        state: `notAnswered`,
        userAnswered: []
      ,
	type: `MCSS`,
	type: `MCSS`        ,
        type: `MCSS`},
      {
        q: `What is the best option for repair of midureteral transection after a stab wound, in a stable patient?`,
        q2: ``,
        q3: [],
        option: [`Ureteroureterostomy`, 
        `Transureteroureterostomy`, 
        `Boari flap`, 
        `Nephrectomy `, 
        ` Cutaneous ureterostomy`,
        ],
        optionFeedback: [``,
          ``,
          ``,
          ``,
          ``],
        optionStyleType: `st-lower-alpha`,
        answer: [0],
        ansText: `Rationale: Ureteroureterostomy, so-called end-to-end repair in injuries to the upper two-thirds of the ureter, is common (up to 32% of one large series) and has a reported success rate as high as 90%.`,
        state: `notAnswered`,
        userAnswered: []
      ,
	type: `MCSS`,
	type: `MCSS`        ,
        type: `MCSS`},
      {
        q: `When ureteroureterostomy is performed, which of the following is required?`,
        q2: ``,
        q3: [],
        option: [`Postoperative interposition of omentum`, 
        `Postoperative nephrostomy tube`, 
        `Spatulated, watertight repair over a ureteral stent`, 
        `Nonabsorbable sutures `, 
        `Intraperitonealization of the ureteral anastomosis `,
        ],
        optionFeedback: [``,
          ``,
          ``,
          ``,
          ``],
        optionStyleType: `st-lower-alpha`,
        answer: [2],
        ansText: `Rationale: A proper ureteral repair entails a spatulated, tension-free, stented, watertight anastomosis and a retroperitoneal closed suction drain.`,
        state: `notAnswered`,
        userAnswered: []
      ,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`        ,
        type: `MCSS`},
      {
        q: `Which maneuver is a common cause of ureteral injury during stone basketing?`,
        q2: ``,
        q3: [],
        option: [`Ureteroscopy without dilating the ureteral orifice first`, 
        `Ureteroscopy in nondilated systems`, 
        `Use of the holmium laser`, 
        ` Pulsatile saline irrigation to assist visualization`, 
        `Persistence in stone basketing attempts in the face of a ureteral tear `,
        ],
        optionFeedback: [``,
          ``,
          ``,
          ``,
          ``],
        optionStyleType: `st-lower-alpha`,
        answer: [4],
        ansText: `Rationale: One factor cited as a cause of injury was the persistence in stone basketing attempts after recognition of a ureteral tear. Current recommendations are to stop and place a ureteral stent.`,
        state: `notAnswered`,
        userAnswered: []
              ,
        type: `MCSS`},
      {
        q: `Which of the following is a contraindication to transureteroureterostomy for repair of significant lower ureter injury?`,
        q2: ``,
        q3: [],
        option: [`History of urolithiasis`, 
        `History of ureteral trauma`, 
        `Morbid obesity`, 
        `Neurogenic bladder `, 
        ` Thoracic spine fracture`,
        ],
        optionFeedback: [``,
          ``,
          ``,
          ``,
          ``],
        optionStyleType: `st-lower-alpha`,
        answer: [0],
        ansText: `Rationale: TUU is contraindicated in patients with a history of kidney stones because a distal ureteral obstructing stone can put then put both kidneys at risk.`,
        state: `notAnswered`,
        userAnswered: []
              ,
        type: `MCSS`},
      {
        q: `What is the best treatment for a short, mid ureter ureteral contusion caused by a high-velocity bullet?`,
        q2: ``,
        q3: [],
        option: [`Observation`, 
        `Ureteral stent placement`, 
        `Transureteroureterostomy`, 
        ` Excision and ureteroureterostomy`, 
        `Oversew the contusion with healthy ureteral tissue `,
        ],
        optionFeedback: [``,
          ``,
          ``,
          ``,
          ``],
        optionStyleType: `st-lower-alpha`,
        answer: [3],
        ansText: `Rationale: High-velocity gunshot wounds to the ureter result in blast injury and thus often heal with stricture or break down from ureteral necrosis. Such contusions should be treated with excision and ureteroureterostomy. Low-velocity bullet ureter contusions can be safely managed by ureteral stent placement.`,
        state: `notAnswered`,
        userAnswered: []
      ,
	type: `MCSS`        ,
        type: `MCSS`},
      {
        q: `Which imaging technique is most useful for detecting ureteral injuries in the stable trauma patient?`,
        q2: ``,
        q3: [],
        option: [`Computed tomography (CT) of the abdomen/pelvis without use of contrast material`, 
        `CT of the abdomen and pelvis with IV contrast with immediate images only`, 
        `CT of the abdomen and pelvis with IV contrast with immediate and delayed imaging (10 to 15 minutes)`, 
        ` IVP`, 
        ` Diuretic (Lasix) renography`,
        ],
        optionFeedback: [``,
          ``,
          ``,
          ``,
          ``],
        optionStyleType: `st-lower-alpha`,
        answer: [2],
        ansText: `Rationale: Because CT scanners can obtain early phase images before intravenous contrast dye is excreted in the urine, delayed images must be obtained (10 to 15 minutes after contrast material injection) to allow sufficient time for contrast to be excreted by the kidney and into the collecting system, renal pelvis, and down the ureter. `,
        state: `notAnswered`,
        userAnswered: []
              ,
        type: `MCSS`},
      {
        q: `Which of the following statements is TRUE about ureteral injuries during laparoscopy?`,
        q2: ``,
        q3: [],
        option: [`The total number of injuries has stayed steady over the years.`, 
        `Surgery for endometriosis greatly increases the risk.`, 
        `Bipolar cautery use during tubal ligation eliminates risk.`, 
        `Most ureteral injuries are recognized immediately. `, 
        `Indigo carmine dye injection eliminates the risk of injury. `,
        ],
        optionFeedback: [``,
          ``,
          ``,
          ``,
          ``],
        optionStyleType: `st-lower-alpha`,
        answer: [1],
        ansText: `Rationale: A large percentage of ureteral injuries after gynecologic laparoscopy occur during electrosurgical or laser-assisted lysis of endometriosis.`,
        state: `notAnswered`,
        userAnswered: []
      ,
	type: `MCSS`,
	type: `MCSS`        ,
        type: `MCSS`},
      {
        q: `<b>Imaging</b><br/><br/>A 22-year-old woman has a CT scan (<a href="a9d5a5235f5d40beb05dec8ba4d50682">Fig. 90.1</a>) after a motor vehicle accident. Her vital signs are stable, and there are no other significant injuries.<br/><br/>The next step is:`,
        q2: ``,
        q3: [],
        option: [`open surgical repair of the kidney.`, 
        `delayed imaging to evaluate the collecting system.`, 
        `left nephrectomy to avoid future complications.`, 
        ` renal artery embolization.`, 
        `intravenous urogram. `,
        ],
        optionFeedback: [``,
          ``,
          ``,
          ``,
          ``],
        optionStyleType: `st-lower-alpha`,
        answer: [1],
        ansText: `Rationale: When blunt renal trauma results in deep parenchymal lacerations, delayed imaging at the time of the CT is essential to evaluate the collecting system for injury. In a stable patient with this type of injury, neither surgical repair nor angiographic embolization is indicated. Most renal injuries heal well with conservative and expectant management, making options a and c incorrect.`,
        state: `notAnswered`,
        userAnswered: []
              ,
        type: `MCSS`},
      {
        q: `A 42-year-old man had a CT scan (<a href="491bb0cbcddf4841af0df4477e6daa0f">Fig. 90.2</a>) 36 hours after a motor vehicle accident. The most likely diagnosis is:`,
        q2: ``,
        q3: [],
        option: [`ureteral injury.`, 
        `segmental renal artery transection.`, 
        `main renal artery occlusion.`, 
        ` ureteropelvic junction disruption.`, 
        `traumatic renal vein occlusion. `,
        ],
        optionFeedback: [``,
          ``,
          ``,
          ``,
          ``],
        optionStyleType: `st-lower-alpha`,
        answer: [2],
        ansText: `Rationale: There is complete absence of enhancement of the entire right kidney, which is caused by intimal injury and then main renal artery occlusion. Segmental occlusion would cause abnormality only in a portion of the right renal nephrogram. Ureteral injury and UPJ disruption may cause delay in the nephrogram but not complete absence of enhancement.`,
        state: `notAnswered`,
        userAnswered: []
              ,
        type: `MCSS`},
      
    
     
]