var quiz = [
   
    {
        q: `The best predictor of post–percutaneous nephrolithotomy (PNL) urosepsis is:`,
        q2: ``,
        q3: [],
        option: [`preoperative bladder urine culture.`, 
        `intraoperative bladder urine culture.`, 
        `stone culture.`, 
        `preoperative blood culture.`, 
        `intraoperative blood culture.`],
        optionFeedback: [``,
        ``,
        ``,
        ``,
        
        ``],
        optionStyleType: `st-lower-alpha`,
        answer: [2],
        ansText:`Rationale: <!--c. Stone culture.--> The best predictor of post-PNL urosepsis is stone culture or renal pelvic urine culture results.`, 
        state: `notAnswered`,
        userAnswered: [],
	type: `MCSS`        ,
        type: `MCSS`},
    {
        q: `What is the risk of mortality from an untreated struvite staghorn stone?`,
        q2: ``,
        q3: [],
        option: [`Less than 10%`, 
        `10% to 30%`, 
        `30% to 50%`, 
        `50% to 70%`, 
        `Greater than 70%`],
        optionFeedback: [``,
        ``,
        ``,
        ``,
        
        ``],
        optionStyleType: `st-lower-alpha`,
        answer: [1],
        ansText:`Rationale: <!--b. 10% to 30%. -->The 10-year mortality rate of untreated staghorn stones was 28%, versus 7.2% in patients treated with surgery.`, 
        state: `notAnswered`,
        userAnswered: [],
	type: `MCSS`        ,
        type: `MCSS`},
    {
        q: `The increased risk of residual fragments after extracorporeal shockwave lithotripsy (SWL) of large-volume calculi is of particular importance for patients with stones composed of:`,
        q2: ``,
        q3: [],
        option: [`brushite.`, 
        `uric acid.`, 
        `struvite.`, 
        `calcium oxalate monohydrate.`, 
        `calcium oxalate dihydrate.`],
        optionFeedback: [``,
        ``,
        ``,
        ``,
        
        ``],
        optionStyleType: `st-lower-alpha`,
        answer: [2],
        ansText:`Rationale:<!--<b>c. Struvite.</b>--> Struvite stones must be removed completely to minimize the risk of continued urea-splitting bacteriuria.`, 
        state: `notAnswered`,
        userAnswered: [],
    
        type: `MCSS`},
    {
        q: `What is the single most important factor when choosing among SWL, ureteroscopic stone removal, and PNL for renal calculi?`,
        q2: ``,
        q3: [],
        option: [`Stone composition`, 
        `Stone location`, 
        `Anatomic abnormalities`, 
        `Stone burden`, 
        `Body habitus`],
        optionFeedback: [``,
        ``,
        ``,
        ``,
        
        ``],
        optionStyleType: `st-lower-alpha`,
        answer: [3],
        ansText:`Rationale:<!--<b>d. Stone burden</b>--> Stone burden (size and number) is perhaps the single most important factor in deciding the appropriate treatment modality for a patient with kidney calculi. `, 
        state: `notAnswered`,
        userAnswered: [],
	type: `MCSS`        ,
        type: `MCSS`},
    {
        q: `What is the preferred treatment for a known brushite stone former harboring a lower pole renal calculus 25 mm in diameter?`,
        q2: ``,
        q3: [],
        option: [`SWL`, 
        `SWL with ureteral stenting`, 
        `Flexible ureteroscopy with holmium laser lithotripsy`, 
        `PNL`, 
        `Laparoscopic pyelolithotomy`],
        optionFeedback: [``,
        ``,
        ``,
        ``,
        
        ``],
        optionStyleType: `st-lower-alpha`,
        answer: [3],
        ansText:`Rationale: <!--<b>d. PNL.</b>--> The Lower Pole Stone Study Group compared ureteroscopy and PNL for patients with 10- to 25-mm lower pole stones and found a significant difference in stone clearance, with only 40% of the ureteroscopic cohort stone free at 3 months versus 76% of the PNL cohort.`, 
        state: `notAnswered`,
        userAnswered: [],
    
        type: `MCSS`},
    {
        q: `What is the preferred initial treatment for staghorn calculi?`,
        q2: ``,
        q3: [],
        option: [`SWL with ureteral stenting`, 
        `Flexible ureteroscopy with holmium laser lithotripsy`, 
        `PNL`, 
        `Extended pyelolithotomy`, 
        `Anatrophic nephrolithotomy`],
        optionFeedback: [``,
        ``,
        ``,
        ``,
        
        ``],
        optionStyleType: `st-lower-alpha`,
        answer: [2],
        ansText:`Rationale:<!--<b>c. PNL</b>--> <b>The management of staghorn stones with a combined approach must be viewed as primarily percutaneous, with SWL being used only as adjunct to minimize the number of accesses required.</b> `, 
        state: `notAnswered`,
        userAnswered: [],
    
        type: `MCSS`},
    {
        q: `Which of the following is the most difficult stone composition to fragment with SWL?`,
        q2: ``,
        q3: [],
        option: [`Calcium oxalate dihydrate`, 
        `Calcium oxalate monohydrate`, 
        `Struvite`, 
        `Hydroxyapatite`, 
        `Uric acid`],
        optionFeedback: [``,
        ``,
        ``,
        ``,
        
        ``],
        optionStyleType: `st-lower-alpha`,
        answer: [1],
        ansText:`Rationale: <!--<b>b. Calcium oxalate monohydrate</b>--> <b>Cystine and brushite are the stones most resistant to SWL, followed by calcium oxalate monohydrate. Next, in descending order, are hydroxyapatite, struvite, calcium oxalate dihydrate, and uric acid stones.</b>`, 
        state: `notAnswered`,
        userAnswered: [],
    
        type: `MCSS`},
    {
        q: `What is the preferred treatment approach for a symptomatic 1.5-cm stone in a lower pole calyceal diverticulum?`,
        q2: ``,
        q3: [],
        option: [`SWL`, 
        `Flexible ureteroscopy`, 
        `PNL`, 
        `PNL with fulguration of the diverticulum`, 
        `Laparoscopic diverticulectomy`],
        optionFeedback: [``,
        ``,
        ``,
        ``,
        
        ``],
        optionStyleType: `st-lower-alpha`,
        answer: [3],
        ansText:`Rationale: <!--d. PNL with fulguration of the diverticulum.--> <b>The percutaneous approach for the management of patients with calyceal diverticular stones provides the patient with the best chance of becoming stone and symptom free.</b> Fulguration of the diverticulum will reduce the risk of recurrence of the diverticulum.`, 
        state: `notAnswered`,
        userAnswered: [],
    
        type: `MCSS`},
    {
        q: `What is the preferred initial treatment for a 10-mm stone in the renal pelvis of a horseshoe kidney with minimal hydronephrosis?`,
        q2: ``,
        q3: [],
        option: [`SWL`, 
        `Flexible ureteroscopy`, 
        `PNL`, 
        `Laparoscopic pyelolithotomy`, 
        `Symphysiotomy with pyelolithotomy`],
        optionFeedback: [``,
        ``,
        ``,
        ``,
        
        ``],
        optionStyleType: `st-lower-alpha`,
        answer: [0],
        ansText:`Rationale: <!--<b>a. SWL.</b>--> SWL can achieve satisfactory results in properly selected patients, such as those with small stones (&lt;1.5 cm) in the presence of normal urinary drainage. For larger stones, or when there is evidence of poor urinary drainage, PNL should be used as the primary approach.`, 
        state: `notAnswered`,
        userAnswered: [],
	type: `MCSS`        ,
        type: `MCSS`},
    {
        q: `What is the preferred treatment approach for a 10-mm renal calculus in a patient who weighs 375 lb?`,
        q2: ``,
        q3: [],
        option: [`SWL`, 
        `Flexible ureteroscopy`, 
        `PNL`, 
        `SWL using the “blast path” technique`, 
        `Open surgery`],
        optionFeedback: [``,
        ``,
        ``,
        ``,
        
        ``],
        optionStyleType: `st-lower-alpha`,
        answer: [1],
        ansText:`Rationale:<!--<b>b. Flexible ureteroscopy.</b>--> Retrograde ureteroscopic intrarenal surgery may be the preferred modality of treatment for morbidly obese patients when the stone burden is not excessively large. `, 
        state: `notAnswered`,
        userAnswered: [],
    
        type: `MCSS`},
    {
        q: `What is the preferred treatment option for a patient with a symptomatic 1.5-cm renal calculus and a coagulopathy?`,
        q2: ``,
        q3: [],
        option: [`SWL`, 
        `SWL after administration of fresh-frozen plasma`, 
        `Indwelling ureteral stent`, 
        `Flexible ureteroscopy`, 
        `PNL`],
        optionFeedback: [``,
        ``,
        ``,
        ``,
        
        ``],
        optionStyleType: `st-lower-alpha`,
        answer: [3],
        ansText:`Rationale:<!--d. Flexible ureteroscopy.--> <b>When anticoagulation cannot be temporarily discontinued, the use of ureteroscopy in combination with holmium laser lithotripsy is preferred.</b> One study reported that even when patients’ coagulopathies were not fully corrected, the stones could be successfully treated with no increase in hemorrhagic complications. `, 
        state: `notAnswered`,
        userAnswered: [],
    
        type: `MCSS`},
    {
        q: `Residual fragments after SWL have been associated with which of the following?`,
        q2: ``,
        q3: [],
        option: [`Hypertension`, 
        `An increased rate of recurrent stones`, 
        `A decreased rate of recurrent stones`, 
        `Perinephric hematomas`, 
        `Hematuria`],
        optionFeedback: [``,
        ``,
        ``,
        ``,
        
        ``],
        optionStyleType: `st-lower-alpha`,
        answer: [1],
        ansText:`Rationale: <!--<b>b. An increased rate of recurrent stones.</b>--> At follow-up (1.6 to 85.4 months), 43% of the patients with residual fragments had a significant symptomatic episode or required intervention.`, 
        state: `notAnswered`,
        userAnswered: [],
    
        type: `MCSS`},
    {
        q: `What is the most sensitive test for identifying residual fragments after PNL?`,
        q2: ``,
        q3: [],
        option: [`Nephrotomography`, 
        `Magnetic resonance imaging (MRI)`, 
        `Ultrasonography`, 
        `Noncontrast computed tomography (CT)`, 
        `Contrast-enhanced CT`],
        optionFeedback: [``,
        ``,
        ``,
        ``,
        
        ``],
        optionStyleType: `st-lower-alpha`,
        answer: [3],
        ansText:`Rationale:<!--<b>d. Noncontrast computed tomography (CT).</b>--> Although flexible nephroscopy is often considered the gold standard for assessing residual stones after PNL, the routine use of flexible nephroscopy has been challenged by studies showing the high sensitivity of noncontrast CT in detecting residual stones. Noncontrast CT had 100% sensitivity for detecting residual stones after PNL in 36 patients evaluated by both CT and flexible nephroscopy. `, 
        state: `notAnswered`,
        userAnswered: [],
    
        type: `MCSS`},
    {
        q: `Factors affecting the probability of spontaneous passage of ureteral calculi include all of the following EXCEPT:`,
        q2: ``,
        q3: [],
        option: [`stone size.`, 
        `stone location at presentation.`, 
        `stone composition.`, 
        `degree of hydronephrosis.`, 
        `duration of symptoms.`],
        optionFeedback: [``,
        ``,
        ``,
        ``,
        
        ``],
        optionStyleType: `st-lower-alpha`,
        answer: [2],
        ansText:`Rationale:<!--<b>c. Stone composition.</b>--> One study analyzed 75 patients with ureteral calculi and found that the interval to stone passage was highly variable and dependent on stone size, location, and side. Stones that were smaller, more distal, and on the right side were more likely to pass spontaneously. In another study, duration of symptoms before presentation was the most influential factor, followed by the degree of hydronephrosis. `, 
        state: `notAnswered`,
        userAnswered: [],
    
        type: `MCSS`},
    {
        q: `Irreversible loss of renal function can occur within what time period when a completely obstructing ureteral stone is present?`,
        q2: ``,
        q3: [],
        option: [`1 week`, 
        `2 to 4 weeks`, 
        `4 to 6 weeks`, 
        `More than 6 weeks`, 
        `3 months`],
        optionFeedback: [``,
        ``,
        ``,
        ``,
        
        ``],
        optionStyleType: `st-lower-alpha`,
        answer: [1],
        ansText:`Rationale:<!--<b>b. 2 to 4 weeks.</b>--> Even with complete ureteral obstruction, irreversible loss of renal function does not occur for more than 2 weeks but can progress to total renal unit loss at up to 6 weeks. `, 
        state: `notAnswered`,
        userAnswered: [],
    
        type: `MCSS`},
    {
        q: `A first-time stone former is diagnosed with a 4-mm proximal ureteral calculus. The best initial management is:`,
        q2: ``,
        q3: [],
        option: [`ureteroscopic laser lithotripsy.`, 
        `ureteral stent placement.`, 
        `SWL.`, 
        `expectant management.`, 
        `SWL with ureteral stent placement.`],
        optionFeedback: [``,
        ``,
        ``,
        ``,
        
        ``],
        optionStyleType: `st-lower-alpha`,
        answer: [3],
        ansText:`Rationale: <!--<b>d. Expectant management</b>--> <b>The majority of ureteral stones less than 5 mm will pass spontaneously and therefore can be treated with expectant management</b>.`, 
        state: `notAnswered`,
        userAnswered: [],
    
        type: `MCSS`},
    {
        q: `Large-volume matrix calculi, which form as a consequence of urinary tract infection, are:`,
        q2: ``,
        q3: [],
        option: [`effectively fragmented with SWL.`, 
        `best approached in a ureteroscopic fashion.`, 
        `generally sterile.`, 
        `radiopaque and well visualized on plain radiographic studies.`, 
        `most efficiently treated with PNL.`],
        optionFeedback: [``,
        ``,
        ``,
        ``,
        
        ``],
        optionStyleType: `st-lower-alpha`,
        answer: [4],
        ansText:`Rationale:<!--e. Most efficiently treated with PNL.--> <b>Matrix stones are most effectively treated with PNL.</b> SWL is usually ineffective because of the stone’s gelatinous nature, and ureteroscopy may be compromised by the large volume of stone material present. `, 
        state: `notAnswered`,
        userAnswered: [],
	type: `MCSS`        ,
        type: `MCSS`},
    {
        q: `Ureteral stent placement when SWL is performed for ureteral stones is appropriate for all of the following reasons EXCEPT:`,
        q2: ``,
        q3: [],
        option: [`solitary kidney.`, 
        `relief of severe symptoms.`, 
        `enhancement of stone fragmentation.`, 
        `relief of obstruction.`, 
        `aid in localization of difficult-to-visualize stones.`],
        optionFeedback: [``,
        ``,
        ``,
        ``,
        
        ``],
        optionStyleType: `st-lower-alpha`,
        answer: [2],
        ansText:`Rationale: <!--<b>c. Enhancement of stone fragmentation.</b>--> Although early reports supported the routine use of a ureteral stent to bypass ureteral stones before SWL, data analyzed by the American Urological Association Ureteral Calculi Guidelines Panel showed no improvement in fragmentation with stenting, and therefore routine stent placement before SWL was discouraged. However, ureteral stent placement is appropriate for other indications, such as management of pain, relief of obstruction, and stones that are difficult to visualize, and is mandatory in a patient who has a solitary obstructed kidney.`, 
        state: `notAnswered`,
        userAnswered: [],
    
        type: `MCSS`},
    {
        q: `The preferred single agent for medical expulsive therapy for distal ureteral calculi is:`,
        q2: ``,
        q3: [],
        option: [`nifedipine.`, 
        `tamsulosin.`, 
        `Solu-Medrol.`, 
        `ibuprofen.`, 
        `terazosin.`],
        optionFeedback: [``,
        ``,
        ``,
        ``,
        
        ``],
        optionStyleType: `st-lower-alpha`,
        answer: [1],
        ansText:`Rationale:<!--b. Tamsulosin.--> <b>Tamsulosin, a selective α-adrenergic blocker, is the preferred agent for medical expulsive therapy, owing to its reported efficacy and superior side effect profile.</b> `, 
        state: `notAnswered`,
        userAnswered: [],
    
        type: `MCSS`},
    {
        q: `The treatment modality associated with the greatest stone-free rates and the least morbidity for patients with distal ureteral stones of any size is:`,
        q2: ``,
        q3: [],
        option: [`PNL.`, 
        `SWL.`, 
        `ureteroscopy.`, 
        `open ureterolithotomy.`, 
        `laparoscopic ureterolithotomy.`],
        optionFeedback: [``,
        ``,
        ``,
        ``,
        
        ``],
        optionStyleType: `st-lower-alpha`,
        answer: [2],
        ansText:`Rationale: <!--<b>c. Ureteroscopy.</b>--> The stone-free rate for distal ureteral stones approached with ureteroscopy was 91% in the American Urological Association/European Association of Urology Ureteral Stones Guidelines document, an outcome superior to SWL.`, 
        state: `notAnswered`,
        userAnswered: [],
    
        type: `MCSS`},
]
