var quiz = [
   
    {
        q: `A 47-year-old woman is referred for the evaluation of renal cyst disease. What features would suggest a diagnosis of autosomal dominant polycystic kidney disease?`,
        q2: ``,
        q3: [],
        option: [`One simple (Bosniak I) renal cyst in each kidney`, 
        `One simple (Bosniak I) renal cyst in the right kidney and two hepatic cysts`, 
        `One complex (Bosniak III) renal cyst in the left kidney and one simple (Bosniak I) renal cyst in the right kidney`, 
        `Two simple (Bosniak I) renal cysts in each kidney`, 
        `Two simple (Bosniak I) renal cysts in the right kidney`],
        optionFeedback: [``,
        ``,
        ``,
        ``,
        
        ``],
        optionStyleType: `st-lower-alpha`,
        answer: [3],
        ansText:`Rationale:<!--<b>d. Two simple (Bosniak I) renal cysts in each kidney.</b>--> According to the diagnostic guidelines for autosomal dominant polycystic kidney disease, the finding of two renal cysts (unilateral or bilateral) in patients less than 30, two cysts in each kidney in patients between 30 and 59(d), and four cysts in each kidney after 60 is suggested of the disease. The other descriptors (a, b, c, e) are not sufficient for the diagnosis. `, 
        state: `notAnswered`,
        userAnswered: [],
	type: `MCSS`        ,
        type: `MCSS`},

    {
        q: `The key finding on CT imaging that differentiates Bosniak I-IIF from Bosniak III-IV renal cysts is:`,
        q2: ``,
        q3: [],
        option: [`enhancement on administration of intravenous contrast.`, 
        `high-density cystic fluid.`, 
        `intraseptal calcifications.`, 
        `septal nodularity.`, 
        `septal thickening.`],
        optionFeedback: [``,
        ``,
        ``,
        ``,
        
        ``],
        optionStyleType: `st-lower-alpha`,
        answer: [0],
        ansText:`Rationale:<!--<b>a. Enhancement on administration of intravenous contrast.</b>--> The Bosniak system for classifying renal cysts defines enhancement of the solid cyst components on the administration of intravenous contrast as a concerning finding toward the risk of malignancy and is the key finding that differentiates Bosniak I-IIF from Bosniak III/IV renal cysts (a). The remainder (b, c, d, e) can be seen in Bosniak II and IIF cysts. `, 
        state: `notAnswered`,
        userAnswered: [],
	type: `MCSS`        ,
        type: `MCSS`},

    {
        q: `A 58-year-old man undergoes a partial nephrectomy for a 4-cm renal mass. On pathologic evaluation, the mass is diffusely eosinophilic with invasion of the perirenal fat. Helpful in establishing a diagnosis of oncocytoma using immunohistochemical staining is:`,
        q2: ``,
        q3: [],
        option: [`Cytokeratin-7.`, 
        `Estrogen receptor.`, 
        `HMB-45.`, 
        `Melan-A.`, 
        `WT1.`],
        optionFeedback: [``,
        ``,
        ``,
        ``,
        
        ``],
        optionStyleType: `st-lower-alpha`,
        answer: [0],
        ansText:`Rationale:<!--<b>a. Cytokeratin-7.</b>--> For differentiation of oncocytoma from eosinophilic chromophobe renal cell carcinoma (the diagnostic dilemma in this case), the ISUP (International Society of Urologic Pathology) recommends the use of cytokeratin-7, which is rarely positive in oncocytoma and is diffusely positive in chromophobe renal cell carcinoma (a). Estrogen receptor positivity is seen in multiple other renal tumors (b), HMB-45 (c) and Melan-A (d) are positive in angiomyolipomas, and WT1 is positive in metanephric adenomas (e). `, 
        state: `notAnswered`,
        userAnswered: [],
    
        type: `MCSS`},

    {
        q: `A 25-year-old man presents with a renal mass identified on axial imaging obtained during the evaluation of a pneumothorax. On examination he has multiple raised lesions around his nasal folds. What chromosome is likely altered in this patient given the likely disease?`,
        q2: ``,
        q3: [],
        option: [`Chromosome 4`, 
        `Chromosome 7`, 
        `Chromosome 9`, 
        `Chromosome 16`, 
        `Chromosome 17`],
        optionFeedback: [``,
        ``,
        ``,
        ``,
        
        ``],
        optionStyleType: `st-lower-alpha`,
        answer: [4],
        ansText:`Rationale:<!--<b>e. Chromosome 17.</b>--> The likely disorder is Birt-Hogg-Dubé syndrome, which is associated with mutations in the folliculin gene on chromosome 17 (e). Chromosome 4 (a) is mutated in autosomal dominant polycystic kidney disease; chromosome 7 (b) mutations are associated with papillary adenomas; papillary renal cell carcinoma, and metanephric adenoma; chromosome 9 (c) is mutated in tuberous sclerosis; and chromosome 16 (d) in both autosomal dominant polycystic kidney disease. `, 
        state: `notAnswered`,
        userAnswered: [],
	type: `MCSS`        ,
        type: `MCSS`},

    {
        q: `A 30-year-old woman with neurocognitive delay, epilepsy, and multiple cutaneous lesions presents with her family for the evaluation of bilateral fat containing renal masses. As you discuss options for management, you review the role of everolimus in the management and stabilization of renal mass growth. This medication is targeting what abnormal genetic pathway?`,
        q2: ``,
        q3: [],
        option: [`<i>EHHADH</i> mutations resulting in decreased adenosine triphosphate (ATP) production`, 
        `<i>Hamartin</i> gene mutations that result in unchecked protein synthesis and cellular growth`, 
        `Nuclear transcription factor mutation resulting in constitutive activity`, 
        `<i>PKD1</i> gene mutations that impair intracellular calcium regulation`, 
        `<i>VHL</i> gene mutations that result in unregulated angiogenesis`],
        optionFeedback: [``,
        ``,
        ``,
        ``,
        
        ``],
        optionStyleType: `st-lower-alpha`,
        answer: [1],
        ansText:`Rationale:<!--<b>b. <i>Hamartin</i> gene mutations that result in unchecked protein synthesis and cellular growth.</b>--> Hamartin (b) is one of two genes mutated in tuberous sclerosis, the described disorder. In this disease, mutation results in activation of the mTOR pathway and unregulated growth. The other described mutations relate to Fanconi syndrome (a), a method for castration resistance in prostate cancer (c), polycystic kidney disease (d), and clear cell renal cell carcinoma (e). `, 
        state: `notAnswered`,
        userAnswered: [],
	type: `MCSS`        ,
        type: `MCSS`},

    {
        q: `A 44-year-old woman is referred for a suspected angiomyolipoma. All of the following radiographic findings are consistent with the diagnosis except:`,
        q2: ``,
        q3: [],
        option: [`hyperintensity on T1 MRI sequences.`, 
        `hyperintensity on T2 MRI sequences.`, 
        `hyperintense borders on in and opposed phase MRI sequences.`, 
        `intralesional density of –30 Hounsfield units (HU) on non-contrast CT.`, 
        `hypointensity of T1 fat-suppressed MRI sequences.`],
        optionFeedback: [``,
        ``,
        ``,
        ``,
        
        ``],
        optionStyleType: `st-lower-alpha`,
        answer: [2],
        ansText:`Rationale:<!--<b>c. Hyperintense borders on in and opposed phase MRI sequences. (c).</b>--> On these sequences, angiomyolipomas will appear to have a hypointense border (“India ink artifact”) due to the presence of intralesional fat. `, 
        state: `notAnswered`,
        userAnswered: [],
	type: `MCSS`        ,
        type: `MCSS`},

    {
        q: `The use of everolimus in the management of tuberous sclerosis-related angiomyolipoma is based on phase III data in which a 30% reduction in mass was observed in ____ patients.`,
        q2: ``,
        q3: [],
        option: [`20%`, 
        `40%`, 
        `60%`, 
        `80%`, 
        `100%`],
        optionFeedback: [``,
        ``,
        ``,
        ``,
        
        ``],
        optionStyleType: `st-lower-alpha`,
        answer: [3],
        ansText:`Rationale: <!--<b>d. 80%.</b>--> The phase III randomized controlled trial of everolimus in the management of TSC-related angiomyolipomas demonstrated a 42% response of 50% or greater reduction in size, 80% response of 30% or greater reduction in size (d), and a 100% rate of stabilization or partial response. Subsequent follow-up to 4 years revealed a 92% any response rate with only 14% experiencing progression.`, 
        state: `notAnswered`,
        userAnswered: [],
    
        type: `MCSS`},

    {
        q: `A 42-year-old woman presents with a hypoenhancing renal mass that is resected and determined to be a metanephric adenoma. A paraneoplastic syndrome identified in this disease is:`,
        q2: ``,
        q3: [],
        option: [`hyperaldosteronism.`, 
        `hyperparathyroidism.`, 
        `Cushing syndrome.`, 
        `polycythemia.`, 
        `syndrome of inappropriate antidiuretic hormone secretion (SIADH).`],
        optionFeedback: [``,
        ``,
        ``,
        ``,
        
        ``],
        optionStyleType: `st-lower-alpha`,
        answer: [3],
        ansText:`Rationale: <!--<b>d. Polycythemia.</b>--> Polycythemia (d) has been identified in metanephric adenoma due to tumor production of erythropoietin, IL-6, IL8, G-CSF, and GM-CSF. The remainder (a, b, c, e) of choices describe paraneoplastic syndromes not associated with metanephric adenoma.`, 
        state: `notAnswered`,
        userAnswered: [],
    
        type: `MCSS`},

    {
        q: `A 15-year-old boy is referred to your clinic for the evaluation of a cystic renal mass. On CT, the mass has evidence of multiple septations that enhance on contrast administration. Due to concern for Wilms tumor, a radical nephrectomy is performed. The final pathology is a cystic nephroma. A finding that will aid in differentiation of Wilms tumor from cystic nephroma is:`,
        q2: ``,
        q3: [],
        option: [`alpha-methylacyl-CoA racemase (AMACR) positivity.`, 
        `an absence of blastemal elements.`, 
        `cysts lined with hobnail epithelium in a background of spindle cell fascicles.`, 
        `no evidence of estrogen receptor positivity.`, 
        `staining for WT-1.`],
        optionFeedback: [``,
        ``,
        ``,
        ``,
        
        ``],
        optionStyleType: `st-lower-alpha`,
        answer: [1],
        ansText:`Rationale:<!--<b>b. An absence of blastemal elements.</b>--> (b) Blastemal and embryonal elements are common to Wilms tumor and are notably absent in cystic nephroma. While answer choice (c) describes findings common to cystic nephroma, this will not definitively rule out Wilms tumor. AMACR (a) and WT1 (e) staining are used in the diagnosis of metanephric adenomas. Cystic nephromas stain positive for estrogen receptor (d). `, 
        state: `notAnswered`,
        userAnswered: [],
    
        type: `MCSS`},

    {
        q: `A 58-year-old man presents with renal colic and hypertensive urgency. On evaluation he is found to have a cystic mass surrounding the renal capsule and compressing the kidney. This is consistent with a diagnosis of:`,
        q2: ``,
        q3: [],
        option: [`cystic nephroma.`, 
        `leiomyoma.`, 
        `lymphangioma.`, 
        `papillary adenoma.`, 
        `renal hemangioma.`],
        optionFeedback: [``,
        ``,
        ``,
        ``,
        
        ``],
        optionStyleType: `st-lower-alpha`,
        answer: [2],
        ansText:`Rationale:<!--<b>c. Lymphangioma.</b>--> Of the described choices, lymphangiomas (c) are known to present with cystic extrinsic compression of the kidney due to aberrant lymphatic development in the perirenal lymphatics. Leiomyomas (b), papillary adenomas (d), and renal hemangiomas (e) will not appear cystic and external to the kidney; while cystic nephroma (a) may appear cystic, they are most often within the renal parenchyma. `, 
        state: `notAnswered`,
        userAnswered: [],
    
        type: `MCSS`},

    {
        q: `A 35-year-old woman presents with hypokalemia and hypertension refractory to medical management. Evaluation reveals a small hypoechoic mass in the right kidney on ultrasound. The etiology of hypokalemia in this patient is related to:`,
        q2: ``,
        q3: [],
        option: [`Cushing syndrome.`, 
        `diuretic use.`, 
        `hyperaldosteronism.`, 
        `hyperparathyroidism.`, 
        `SIADH.`],
        optionFeedback: [``,
        ``,
        ``,
        ``,
        
        ``],
        optionStyleType: `st-lower-alpha`,
        answer: [4],
        ansText:`Rationale: <!--<b>e. SIADH.</b>--> This is a classic example of a juxtaglomerular tumor (JGCT). The source of hypertension in these patients is hyperproduction of renin, which results in a secondary cause of hyperaldosteronism (c). The other choices represent other paraneoplastic processes unrelated to JGCTs.`, 
        state: `notAnswered`,
        userAnswered: [],
    
        type: `MCSS`},

    {
        q: `A 35-year-old woman in her third trimester is brought to the emergency department unresponsive with hypotension, anemia, and is found to have a retroperitoneal hemorrhage. The most likely cause is:`,
        q2: ``,
        q3: [],
        option: [`angiomyolipoma.`, 
        `clear cell renal cell carcinoma.`, 
        `metanephric adenoma.`, 
        `oncocytoma.`, 
        `trauma.`],
        optionFeedback: [``,
        ``,
        ``,
        ``,
        
        ``],
        optionStyleType: `st-lower-alpha`,
        answer: [0],
        ansText:`Rationale:<!--<b>a. Angiomyolipoma.</b>--> The most common cause of Wunderlich syndrome is from an angiomyolipoma (a). An additional clue to this presentation is the patient’s pregnancy, where hormonal changes can result in growth of the lesion. `, 
        state: `notAnswered`,
        userAnswered: [],
    
        type: `MCSS`},

    {
        q: `The following are common to most benign renal mass presentations EXCEPT:`,
        q2: ``,
        q3: [],
        option: [`female gender.`, 
        `incidental diagnosis.`, 
        `older patient age.`, 
        `smoking history.`, 
        `stable size.`],
        optionFeedback: [``,
        ``,
        ``,
        ``,
        
        ``],
        optionStyleType: `st-lower-alpha`,
        answer: [3],
        ansText:`Rationale:<!--<b>d. Smoking history.</b>--> All of the answers suggest a benign renal mass presentation, except for smoking (d), which is a risk factor for a malignant renal mass. `, 
        state: `notAnswered`,
        userAnswered: [],
    
        type: `MCSS`},
]