var quiz = [
   
    {
        q: `The majority of ureteral tumors occur in the:`,
        q2: ``,
        q3: [],
        option: [`proximal ureter.`, 
        `midureter.`, 
        `distal ureter.`, 
        `proximal and midureter.`, 
        `distal and mid ureter.`],
        optionFeedback: [``,
        ``,
        ``,
        ``,
        
        ``],
        optionStyleType: `st-lower-alpha`,
        answer: [4],
        ansText:`Rationale:<!--<b>e. Distal and midureter.</b>--> Ureteral tumors occur more commonly in the lower than in the upper ureter. <b>Overall, approximately 70% of ureteral tumors occur in the distal ureter, 25% in the midureter, and 5% in the proximal ureter.</b> `, 
        state: `notAnswered`,
        userAnswered: [],
    
	type: `MCSS`        ,
        type: `MCSS`},
    {
        q: `The most important determinant of oncologic outcome in upper tract urothelial carcinoma is:`,
        q2: ``,
        q3: [],
        option: [`stage and grade.`, 
        `number of tumors.`, 
        `location.`, 
        `tumor size.`, 
        `tumor architecture.`],
        optionFeedback: [``,
        ``,
        ``,
        ``,
        
        ``],
        optionStyleType: `st-lower-alpha`,
        answer: [0],
        ansText:`Rationale: <!--<b>a. Stage and grade.</b>--> The most well-established current predictors of survival in patients with upper tract urothelial tumors are stage and grade. The most significant decrease in survival is seen in T3 tumors, and higher-grade tumors are more likely to invade the surrounding tissues, hence presenting with higher stage. Although there have been studies showing differences in prognosis based on the tumor number, location, size, and architecture, these criteria are evolving and warrant further investigation.`, 
        state: `notAnswered`,
        userAnswered: [],
    
	type: `MCSS`,
	type: `MCSS`        ,
        type: `MCSS`},
    {
        q: `At the time of nephroureterectomy, the ureteral stump can be safely left in place for patients with urothelial tumors of the renal pelvis.`,
        q2: ``,
        q3: [],
        option: [`true`, 
        `false`],
        optionFeedback: [``,
        ``,
        ``,
        ``,
        
        ``],
        optionStyleType: `st-lower-alpha`,
        answer: [1],
        ansText:`Rationale: <!--<b>b. False.</b>--> <b>Complete removal of the distal ureter and bladder cuff offers oncologic outcomes superior to those for incomplete resection.</b> The risk of tumor recurrence in a remaining ureteral stump is 30% to 75%. In addition, adequate cystoscopic surveillance of a residual distal ureter stump after nephroureterectomy is virtually impossible, contributing to high rates of local recurrence. Therefore the entire distal ureter, including the intramural portion and the ureteral orifice, must be removed.`, 
        state: `notAnswered`,
        userAnswered: [],
	type: `MCSS`        ,
        type: `MCSS`},
    {
        q: `Initial evaluation of positive cytology should include which of the following?`,
        q2: ``,
        q3: [],
        option: [`Cystoscopy`, 
        `Ureteroscopy`, 
        `CT urography`, 
        `a, b, and c`,
        `a and b`, 
        `a and c`],
        optionFeedback: [``,
        ``,
        ``,
        ``,
        
        ``],
        optionStyleType: `st-lower-alpha`,
        answer: [5],
        ansText:`Rationale: <!--<b>f. a and c.</b>--> Ureteroscopy should be reserved for situations in which the diagnosis remains in question after conventional radiographic studies, and for patients in whom the treatment plan may be modified on the basis of the ureteroscopic findings. Although the risks of tumor seeding, extravasation, and dissemination are low in experienced hands, these risks are real and should preclude ureteroscopy when it is unnecessary. Because upper urinary tract tumors are often associated with bladder cancers, cystoscopy is mandatory in the evaluation to exclude coexistent bladder lesions.`, 
        state: `notAnswered`,
        userAnswered: [],
	type: `MCSS`        ,
        type: `MCSS`},
    {
        q: `<b>Pathology</b><br/><br/>A 38-year-old woman has right flank pain and microscopic hematuria. Cytology is atypical. CT scan shows a mass in the distal right ureter with hydronephrosis. Cystoscopy is negative, and attempted ureteroscopy is unsuccessful. The distal ureter is excised, and the pathology is depicted in <a href="fc2d9b22024a42e79d6a319176e0dc22">Fig. 99.1</a> and is reported as endometriosis. The patient should be advised to:`,
        q2: ``,
        q3: [],
        option: [`have a diagnostic laparoscopy.`, 
        `receive ablative hormonal therapy.`, 
        `have periodic upper tract imaging.`, 
        `have cystoscopy and cytology twice yearly for the next 2 years.`, 
        `have a hysterectomy and bilateral salpingo-oophorectomy.`],
        optionFeedback: [``,
        ``,
        ``,
        ``,
        
        ``],
        optionStyleType: `st-lower-alpha`,
        answer: [2],
        ansText:`Rationale: <!--<b>c. Have periodic upper tract imaging.</b>--> With no symptoms, no further workup is indicated. The patient should be followed for possible development of a ureteral vesicle stricture at the site of the anastomosis.`, 
        state: `notAnswered`,
        userAnswered: [],
	type: `MCSS`        ,
        type: `MCSS`},
    {
        q: `A 60-year-old man has a right ureteral mass excised. The pathology is low-grade noninvasive transitional cell carcinoma (TCC) (<a href="ce3d59898a02407499973e3665c239ba">Fig. 99.2</a>). He has no prior history of upper tract disease or bladder cancer. Management should consist of:`,
        q2: ``,
        q3: [],
        option: [`interval cystoscopies and cytology.`, 
        `instillation of BCG into the right upper tract.`, 
        `systemic platinum chemotherapy.`, 
        `periodic ureteroscopies of the left system.`, 
        `no further follow-up.`],
        optionFeedback: [``,
        ``,
        ``,
        ``,
        
        ``],
        optionStyleType: `st-lower-alpha`,
        answer: [0],
        ansText:`Rationale: <!--<b>a. Interval cystoscopies and cytology.</b>--> Patients who have upper tract TCC have as high as a 30% incidence of bladder tumors and should be followed as for bladder cancer. Moreover, periodic upper tract imaging is necessary.`, 
        state: `notAnswered`,
        userAnswered: [],
    
        type: `MCSS`},
]