var quiz = [
   
    {
        q: `The ethnic/racial group with the highest prevalence of stone disease is:`,
        q2: ``,
        q3: [],
        option: [`African-American`, 
        `Hispanic`, 
        `White`, 
        `Asian`, 
        `American Indian`],
        optionFeedback: [``,
        ``,
        ``,
        ``,
        
        ``],
        optionStyleType: `st-lower-alpha`,
        answer: [2],
        ansText:`Rationale:<!--<b>c. White.</b>--> The highest prevalence of stone disease in both men and women occurs in whites. In men the lowest prevalence occurs in African-Americans, whereas Asian women have been found to have the lowest prevalence in one series. `, 
        state: `notAnswered`,
        userAnswered: [],
	type: `MCSS`        ,
        type: `MCSS`},
    {
        q: `The geographic area in the United States associated with the highest incidence of calcium oxalate stone disease is the:`,
        q2: ``,
        q3: [],
        option: [`northeast.`, 
        `southeast.`, 
        `southwest.`, 
        `west.`, 
        `northwest.`],
        optionFeedback: [``,
        ``,
        ``,
        ``,
        
        ``],
        optionStyleType: `st-lower-alpha`,
        answer: [1],
        ansText:`Rationale:<!--<b>b. Southeast.</b>--> According to hospital discharge rates among U.S. veterans, calcium oxalate stone disease is most prevalent in the southeast. `, 
        state: `notAnswered`,
        userAnswered: [],
	type: `MCSS`        ,
        type: `MCSS`},
    {
        q: `Which of the following conditions is associated with an increased risk of nephrolithiasis?`,
        q2: ``,
        q3: [],
        option: [`Underweight`, 
        `Metabolic syndrome`, 
        `Rheumatoid arthritis`, 
        `Hypothyroidism`, 
        `Atopy`],
        optionFeedback: [``,
        ``,
        ``,
        ``,
        
        ``],
        optionStyleType: `st-lower-alpha`,
        answer: [1],
        ansText:`Rationale: <!--<b>b. Metabolic syndrome.</b>--> Metabolic syndrome is characterized by obesity, hypertension, dyslipidemia, and insulin resistance, and is associated with an increased risk of kidney stone formation. Although impaired ammoniagenesis accounts for an increased risk of uric acid stones due to low urine pH, association with stone disease in general has been demonstrated. None of the other conditions has been associated with stone disease.`, 
        state: `notAnswered`,
        userAnswered: [],
    
        type: `MCSS`},
    {
        q: `Which of the following occurs when the concentration product of urine is in the metastable range?`,
        q2: ``,
        q3: [],
        option: [`Urine is supersaturated.`, 
        `Homogeneous nucleation occurs.`, 
        `Solubility product is reduced.`, 
        `Urinary inhibitors decrease the formation product.`, 
        `Nucleation never occurs.`],
        optionFeedback: [``,
        ``,
        ``,
        ``,
        
        ``],
        optionStyleType: `st-lower-alpha`,
        answer: [0],
        ansText:`<!--<b>a. Urine is supersaturated.</b>-->`, 
        state: `notAnswered`,
        userAnswered: [],
	type: `MCSS`        ,
        type: `MCSS`},
    {
        q: `The process by which nucleation occurs in pure solutions is:`,
        q2: ``,
        q3: [],
        option: [`homogeneous nucleation.`, 
        `heterogeneous nucleation.`, 
        `epitaxy.`, 
        `aggregation.`, 
        `agglomeration.`],
        optionFeedback: [``,
        ``,
        ``,
        ``,
        
        ``],
        optionStyleType: `st-lower-alpha`,
        answer: [0],
        ansText:`Rationale: <!--<b>a. Homogeneous nucleation.</b>--> The process by which nuclei form in pure solutions is called <b><i>homogeneous nucleation.</i></b>`, 
        state: `notAnswered`,
        userAnswered: [],
    
        type: `MCSS`},
    {
        q: `The proteinaceous portion of stones is composed of:`,
        q2: ``,
        q3: [],
        option: [`concentric lamination.`, 
        `protein-crystal complex.`, 
        `matrix.`, 
        `nephrocalcin.`, 
        `osteocalcin.`],
        optionFeedback: [``,
        ``,
        ``,
        ``,
        
        ``],
        optionStyleType: `st-lower-alpha`,
        answer: [2],
        ansText:`Rationale:<!--<b>c. Matrix.</b>--> Depending on their type, kidney stones contain between 2.5% and 65% of noncrystalline material or matrix. Extensive investigations have characterized matrix as a derivative of several of the mucoproteins of urine and serum. `, 
        state: `notAnswered`,
        userAnswered: [],
    
        type: `MCSS`},
    {
        q: `Stone-forming propensity is best described by:`,
        q2: ``,
        q3: [],
        option: [`formation product.`, 
        `ionic activity.`, 
        `saturation index.`, 
        `solubility product.`, 
        `relative saturation ratio.`],
        optionFeedback: [``,
        ``,
        ``,
        ``,
        
        ``],
        optionStyleType: `st-lower-alpha`,
        answer: [2],
        ansText:`Rationale: <!--<b>c. Saturation index.</b>--> The state of saturation of the urine with respect to particular stone-forming salts indicates the stone-forming propensity of the urine. The state of saturation is determined by pH and the ionic strength of the major ions in solution. Relative saturation ratio, determined by the EQUIL 2 computer program, has been the standard for determining stone-forming propensity. However, the newer <b><i>JESS</i></b> computer program takes into account several soluble complexes not recognized by the EQUIL 2 program and is likely a more accurate measure of stone-forming propensity, although it has not yet gained widespread use.`, 
        state: `notAnswered`,
        userAnswered: [],
    
        type: `MCSS`},
    {
        q: `The most common abnormal urinary finding in patients undergoing Roux-en-Y gastric bypass surgery is:`,
        q2: ``,
        q3: [],
        option: [`hypercalciuria.`, 
        `low urine pH.`, 
        `low urine volume.`, 
        `hypocitraturia.`, 
        `hyperoxaluria.`],
        optionFeedback: [``,
        ``,
        ``,
        ``,
        
        ``],
        optionStyleType: `st-lower-alpha`,
        answer: [4],
        ansText:`Rationale:<!--<b>e. Hyperoxaluria.</b>--> Hyperoxaluria has been described in both stone-forming and non-stone-forming patients who have undergone Roux-en-Y gastric bypass surgery, with urinary oxalate levels in some patients exceeding 100 mg/day. A mild decrease in urinary calcium compared with stone-forming control subjects has been described by some investigators but is a less consistent and severe finding. `, 
        state: `notAnswered`,
        userAnswered: [],
	type: `MCSS`        ,
        type: `MCSS`},
    {
        q: `The vitamin D metabolite that stimulates intestinal calcium absorption is:`,
        q2: ``,
        q3: [],
        option: [`7-dehydrocholesterol.`, 
        `cholecalciferol.`, 
        `25-dihydroxyvitamin D<sub>3</sub>.`,
        `1,25-dihydroxyvitamin D<sub>3</sub>.`,  
        `calcitonin.`],
        optionFeedback: [``,
        ``,
        ``,
        ``,
        
        ``],
        optionStyleType: `st-lower-alpha`,
        answer: [3],
        ansText:`<!--<b>d. 1,25-dihydroxyvitamin D<sub>3</sub>.</b>--> It is generally accepted that 1,25-dihydroxyvitamin D<sub>3</sub> is the vitamin D metabolite that is the most potent stimulator of intestinal calcium absorption. The other metabolites, except for calcitonin, are precursors of 1,25-dihydroxyvitamin D<sub>3</sub>. `, 
        state: `notAnswered`,
        userAnswered: [],
	type: `MCSS`        ,
        type: `MCSS`},
    {
        q: `Which of the following factors increases intestinal oxalate absorption?`,
        q2: ``,
        q3: [],
        option: [`High dietary calcium intake.`, 
        `Low dietary calcium intake.`, 
        `<i>Oxalobacter formigenes</i> colonization in the colon.`, 
        `<i>Helicobacter pylori</i> colonization in the stomach.`, 
        `Irritable bowel syndrome.`],
        optionFeedback: [``,
        ``,
        ``,
        ``,
        
        ``],
        optionStyleType: `st-lower-alpha`,
        answer: [1],
        ansText:`Rationale:<!--<b>b. Low dietary calcium intake.</b>--> Intestinal oxalate absorption is modulated by dietary oxalate and calcium intake and by the presence or absence of <b><i>O. formigenes.</i></b> In the setting of a high calcium intake, oxalate absorption decreases, and during calcium restriction, oxalate absorption increases because of reduced formation of a soluble calcium oxalate complex and increased availability of oxalate for absorption. <b><i>H. pylori,</i></b> which can colonize the stomach, has no effect on intestinal oxalate absorption. <b><i>O. formigenes</i></b>, an oxalate-degrading bacterium, uses oxalate as a substrate in the intestinal lumen, thereby reducing oxalate absorption. Irritable bowel syndrome, unless it is associated with chronic diarrhea, does not affect intestinal oxalate absorption. `, 
        state: `notAnswered`,
        userAnswered: [],
    
        type: `MCSS`},
    {
        q: `The primary determinant of urinary citrate excretion is:`,
        q2: ``,
        q3: [],
        option: [`acid–base status.`, 
        `urinary sodium excretion.`, 
        `citric acid intake.`, 
        `insulin sensitivity.`, 
        `urinary calcium excretion.`],
        optionFeedback: [``,
        ``,
        ``,
        ``,
        
        ``],
        optionStyleType: `st-lower-alpha`,
        answer: [0],
        ansText:`Rationale: <!--<b>a. Acid–base status</b>--> Citric acid intake has a limited effect on urinary citrate excretion because only a small portion of dietary citrate is excreted into the urine unmetabolized. The majority of absorbed citrate is metabolized to bicarbonate, which is neutralized by the free proton from citric acid, thereby providing no net alkali load that would increase urinary citrate excretion.`, 
        state: `notAnswered`,
        userAnswered: [],
    
        type: `MCSS`},
    {
        q: `The underlying abnormality of renal hypercalciuria is:`,
        q2: ``,
        q3: [],
        option: [`enhanced calcium filtration.`, 
        `enhanced calcium secretion.`, 
        `enhanced calcium reabsorption.`, 
        `primary renal wasting of calcium.`, 
        `primary renal storage of calcium.`],
        optionFeedback: [``,
        ``,
        ``,
        ``,
        
        ``],
        optionStyleType: `st-lower-alpha`,
        answer: [3],
        ansText:`Rationale:<!--<b>d. Primary renal wasting of calcium.</b>--> In this condition, the underlying abnormality is a primary renal leak of calcium due to impaired renal tubular calcium reabsorption. `, 
        state: `notAnswered`,
        userAnswered: [],
    
        type: `MCSS`},
    {
        q: `Enteric hyperoxaluria occurs as a result of:`,
        q2: ``,
        q3: [],
        option: [`excessive intake of oxalate.`, 
        `reduced excretion of oxalate.`, 
        `increased dietary fat.`, 
        `low calcium intake.`, 
        `fat malabsorption.`],
        optionFeedback: [``,
        ``,
        ``,
        ``,
        
        ``],
        optionStyleType: `st-lower-alpha`,
        answer: [4],
        ansText:`Rationale:<!--<b>e. Fat malabsorption.</b>--> Malabsorption from any cause, including small bowel resection, intrinsic disease, or jejunoileal bypass, increases luminal fatty acids and bile salts. In addition, poorly absorbed bile salts increase colonic permeability to oxalate, further increasing oxalate absorption. `, 
        state: `notAnswered`,
        userAnswered: [],
    
        type: `MCSS`},
    {
        q: `The most likely mechanism accounting for low urinary pH in uric acid stone formers with type 2 diabetes mellitus is:`,
        q2: ``,
        q3: [],
        option: [`defective ammoniagenesis.`, 
        `impaired urinary bicarbonate excretion.`, 
        `lactic acidosis.`, 
        `glucosuria.`, 
        `ketoacidosis.`],
        optionFeedback: [``,
        ``,
        ``,
        ``,
        
        ``],
        optionStyleType: `st-lower-alpha`,
        answer: [0],
        ansText:`Rationale:<!--<b>a. Defective ammoniagenesis.</b>--> Patients with type 2 diabetes mellitus typically exhibit characteristics of the metabolic syndrome, including insulin resistance. Although peripherally, insulin resistance leads to typical symptoms of diabetes, insulin resistance at the level of the kidney leads to impaired ammoniagenesis, by way of reduced production of ammonia from glutamine and reduced activity of the Na<sup>+</sup>/H<sup>+</sup> exchanger in the proximal tubule that is responsible for either the direct transport or trapping of ammonium in the urine. The result is reduced urinary ammonium and low urine pH. `, 
        state: `notAnswered`,
        userAnswered: [],
    
        type: `MCSS`},
    {
        q: `In idiopathic calcium oxalate stone formers, Randall plaques originate in the:`,
        q2: ``,
        q3: [],
        option: [`basement membrane of the thin loops of Henle.`, 
        `terminal collecting ducts.`, 
        `medullary interstitium.`, 
        `vasa recta.`, 
        `papillary tip.`],
        optionFeedback: [``,
        ``,
        ``,
        ``,
        
        ``],
        optionStyleType: `st-lower-alpha`,
        answer: [0],
        ansText:`Rationale:<!--<b>a. Basement membrane of the thin loops of Henle.</b>--> In idiopathic calcium oxalate stone formers, Randall plaques have been found to originate in the basement membrane of the thin loops of Henle. From there, they extend through the medullary interstitium to a subepithelial location, where they serve as an anchoring site for calcium oxalate stone formation. `, 
        state: `notAnswered`,
        userAnswered: [],
    
        type: `MCSS`},
    {
        q: `In calcium oxalate stone formers, Randall plaques are composed of:`,
        q2: ``,
        q3: [],
        option: [`calcium oxalate.`, 
        `brushite.`, 
        `calcium carbonate.`, 
        `calcium apatite.`, 
        `uric acid.`],
        optionFeedback: [``,
        ``,
        ``,
        ``,
        
        ``],
        optionStyleType: `st-lower-alpha`,
        answer: [4],
        ansText:`Rationale:<!--<b>d. Calcium apatite.</b>--> Randall plaques are invariably composed of calcium apatite, which serve as an anchoring site onto which calcium oxalate crystals can adhere and grow. `, 
        state: `notAnswered`,
        userAnswered: [],
    
        type: `MCSS`},
    {
        q: `Urinary saturation of calcium oxalate is most strongly dependent on:`,
        q2: ``,
        q3: [],
        option: [`urinary calcium concentration.`, 
        `urinary oxalate concentration.`, 
        `both urinary calcium and oxalate concentrations.`, 
        `urinary pH.`, 
        `urinary citrate concentration.`],
        optionFeedback: [``,
        ``,
        ``,
        ``,
        
        ``],
        optionStyleType: `st-lower-alpha`,
        answer: [2],
        ansText:`Rationale: <!--<b>c. Both urinary calcium and oxalate concentrations.</b>--> Urinary saturation of calcium oxalate is strongly, positively correlated with urinary calcium and oxalate concentrations. Both contribute equally to urinary saturation of calcium oxalate.`, 
        state: `notAnswered`,
        userAnswered: [],
    
        type: `MCSS`},
    {
        q: `<i>O. formigenes</i> reduces urinary oxalate by:`,
        q2: ``,
        q3: [],
        option: [`reducing intestinal calcium absorption, leading to decreased luminal free oxalate and reduced oxalate absorption.`, 
        `degrading urinary oxalate in infected urine.`, 
        `binding oxalate in the intestinal lumen and preventing its reabsorption.`, 
        `inhibiting the intestinal oxalate transporter.`, 
        `using oxalate as a substrate in the intestine, thereby reducing intestinal oxalate absorption.`],
        optionFeedback: [``,
        ``,
        ``,
        ``,
        
        ``],
        optionStyleType: `st-lower-alpha`,
        answer: [4],
        ansText:`Rationale: <!--<b>e. Using oxalate as a substrate in the intestine, thereby reducing intestinal oxalate absorption.</b>--> <b><i>O. formigenes</i></b> is an oxalate-degrading bacterium found in the intestinal lumen that uses oxalate as an energy source, thereby reducing luminal oxalate and intestinal oxalate absorption. <b><i>Oxalobacter</i></b> is not found in urine.`, 
        state: `notAnswered`,
        userAnswered: [],
    
        type: `MCSS`},
    {
        q: `Which of the following organisms is most likely to produce urease?`,
        q2: ``,
        q3: [],
        option: [`<i>Staphylococcus aureus</i>`, 
        `<i>Escherichia coli</i>`, 
        `<i>Streptococcus pneumoniae</i>`, 
        `<i>Serratia marcescens</i>`, 
        `<i>Chlamydia</i>`],
        optionFeedback: [``,
        ``,
        ``,
        ``,
        
        ``],
        optionStyleType: `st-lower-alpha`,
        answer: [0],
        ansText:`Rationale:<!--a. <b><i>Staphylococcus aureus.</i></b>--> Although <b><i>Proteus</i></b> species are most commonly associated with struvite stones, more than 90% of <b><i>S. aureus</i></b> organisms produce urease and are therefore associated with struvite stone formation. `, 
        state: `notAnswered`,
        userAnswered: [],
    
        type: `MCSS`},
    {
        q: `The mechanism responsible for type 1 (distal) renal tubular acidosis (RTA) is:`,
        q2: ``,
        q3: [],
        option: [`impaired bicarbonate reabsorption in the proximal tubule.`, 
        `defective H<sup>+</sup>-ATPase in the distal tubule that is unable to excrete excess acid.`, 
        `defective ammoniagenesis.`, 
        `impaired excretion of nontitratable acids.`, 
        `hypoaldosteronism.`],
        optionFeedback: [``,
        ``,
        ``,
        ``,
        
        ``],
        optionStyleType: `st-lower-alpha`,
        answer: [1],
        ansText:`Rationale:<!--<b>b. Defective H<sup>+</sup>-ATPase in the distal tubule that is unable to excrete excess acid.</b>--> A defective H<sup>+</sup>-ATPase in the distal tubule has been implicated in the inability to excrete excess acid in the presence of an oral acid load among patients with distal RTA. `, 
        state: `notAnswered`,
        userAnswered: [],
    
        type: `MCSS`},
    {
        q: `Patients with Lesch-Nyhan syndrome treated with high doses of allopurinol are at risk for formation of stones of which of the following compositions?`,
        q2: ``,
        q3: [],
        option: [`Hypoxanthine`, 
        `Uric acid`, 
        `Xanthine`, 
        `2,8-Dihydroxyadenine`, 
        `Calcium apatite`],
        optionFeedback: [``,
        ``,
        ``,
        ``,
        
        ``],
        optionStyleType: `st-lower-alpha`,
        answer: [2],
        ansText:`Rationale:<!--<b>c. Xanthine.</b>--> Patients with Lesch-Nyhan syndrome suffer from an inherited deficiency of the purine salvage enzyme hypoxanthine-guanine phosphoribosyltransferase, which leads to the accumulation of hypoxanthine, which is ultimately converted to uric acid. Allopurinol inhibits xanthine oxidase, which is responsible for converting hypoxanthine to xanthine and xanthine to uric acid. High doses of allopurinol in these patients lead to the accumulation of hypoxanthine and xanthine, but because xanthine is less soluble in urine than is hypoxanthine, xanthine stones form. `, 
        state: `notAnswered`,
        userAnswered: [],
    
        type: `MCSS`},
    {
        q: `The etiology of ammonium acid urate stone formation in patients abusing laxatives is:`,
        q2: ``,
        q3: [],
        option: [`recurrent infections with urease-producing bacteria.`, 
        `chronic dehydration and excessive uric acid excretion.`, 
        `increased ammoniagenesis.`, 
        `urinary phosphate deficiency and intracellular acidosis.`, 
        `chronic dehydration, intracellular acidosis, and low urinary sodium.`],
        optionFeedback: [``,
        ``,
        ``,
        ``,
        
        ``],
        optionStyleType: `st-lower-alpha`,
        answer: [4],
        ansText:`Rationale: <!--<b>e. Chronic dehydration, intracellular acidosis, and low urinary sodium.</b>--> Subjects who abuse laxatives are chronically dehydrated, resulting in intracellular acidosis. In addition, urinary sodium is low from sodium loss as a result of the laxatives. In this environment, urate preferentially complexes with the abundant ammonium rather than sodium and produces ammonium acid urate stones.`, 
        state: `notAnswered`,
        userAnswered: [],
    
        type: `MCSS`},
    {
        q: `The primary mechanism of action of citrate in preventing stone formation is:`,
        q2: ``,
        q3: [],
        option: [`reducing urinary calcium excretion.`, 
        `reducing urinary oxalate excretion.`, 
        `complexing calcium in urine.`, 
        `complexing oxalate in urine.`, 
        `complexing phosphate in urine.`],
        optionFeedback: [``,
        ``,
        ``,
        ``,
        
        ``],
        optionStyleType: `st-lower-alpha`,
        answer: [2],
        ansText:`Rationale: <!--<b>c. Complexing calcium in urine.</b>--> The primary mechanism of action of citrate is as a complexing agent for calcium, thereby reducing ionic calcium and urinary saturation of calcium oxalate.`, 
        state: `notAnswered`,
        userAnswered: [],
    
        type: `MCSS`},
    {
        q: `Type 1 (distal) RTA is characterized by which abnormality?`,
        q2: ``,
        q3: [],
        option: [`Hyperkalemia`, 
        `Hypochloremia`, 
        `Alkalosis`, 
        `Hypercitraturia`, 
        `Hypokalemia`],
        optionFeedback: [``,
        ``,
        ``,
        ``,
        
        ``],
        optionStyleType: `st-lower-alpha`,
        answer: [4],
        ansText:`<!--<b>e. Hypokalemia.</b>--> `, 
        state: `notAnswered`,
        userAnswered: [],
    
        type: `MCSS`},
    {
        q: `The primary defect in type 2 (proximal) RTA is failure of bicarbonate reabsorption in the:`,
        q2: ``,
        q3: [],
        option: [`glomerulus.`, 
        `proximal tubule.`, 
        `loop of Henle.`, 
        `distal tubule.`, 
        `collecting duct.`],
        optionFeedback: [``,
        ``,
        ``,
        ``,
        
        ``],
        optionStyleType: `st-lower-alpha`,
        answer: [1],
        ansText:`Rationale: <!--<b>b. Proximal tubule.</b>--> The primary defect in type 2 or proximal RTA is a failure of bicarbonate reabsorption in the proximal tubule, leading to excessive urinary bicarbonate excretion and metabolic acidosis.`, 
        state: `notAnswered`,
        userAnswered: [],
    
        type: `MCSS`},
    {
        q: `The most common abnormality identified in patients with uric acid stones is:`,
        q2: ``,
        q3: [],
        option: [`acidic urine.`, 
        `alkaline urine.`, 
        `low uric acid concentration.`, 
        `high uric acid concentration.`, 
        `distal renal tubular acidosis.`],
        optionFeedback: [``,
        ``,
        ``,
        ``,
        
        ``],
        optionStyleType: `st-lower-alpha`,
        answer: [0],
        ansText:`Rationale: <!--<b>a. Acidic urine.</b>--> Patients with uric acid stones often have prolonged periods of acidity in the urine.`, 
        state: `notAnswered`,
        userAnswered: [],
    
        type: `MCSS`},
    {
        q: `Carbonic anhydrase inhibitors are associated with formation of stones composed of:`,
        q2: ``,
        q3: [],
        option: [`calcium oxalate.`, 
        `calcium phosphate.`, 
        `struvite.`, 
        `cystine.`, 
        `uric acid.`],
        optionFeedback: [``,
        ``,
        ``,
        ``,
        
        ``],
        optionStyleType: `st-lower-alpha`,
        answer: [1],
        ansText:`Rationale: <!--<b>b. Calcium phosphate.</b>--> Carbonic anhydrase inhibitors such as acetazolamide and topiramate block reabsorption of bicarbonate in the renal proximal and distal tubules, thereby preventing urinary acidification and inducing a metabolic acidosis. Similar to RTA, carbonic anhydrase inhibition results in the formation of calcium phosphate stones because of the high urine pH, hypercalciuria, and hypocitraturia.`, 
        state: `notAnswered`,
        userAnswered: [],
    
        type: `MCSS`},
    {
        q: `Which of the following physiologic changes occurs in the kidney during pregnancy?`,
        q2: ``,
        q3: [],
        option: [`Decreased uric acid excretion`, 
        `Decreased citrate excretion`, 
        `Increased calcium excretion`, 
        `Decreased glomerular filtration rate (GFR)`, 
        `Increased magnesium excretion`],
        optionFeedback: [``,
        ``,
        ``,
        ``,
        
        ``],
        optionStyleType: `st-lower-alpha`,
        answer: [2],
        ansText:`Rationale:<!--<b>c. Increased calcium excretion.</b>--> Placental production of 1,25-dihydroxyvitamin D<sub>3</sub> increases intestinal calcium absorption, further increasing urinary calcium. `, 
        state: `notAnswered`,
        userAnswered: [],
    
        type: `MCSS`},
    {
        q: `Which of the following substances acts as a promoter of calcium oxalate stone formation?`,
        q2: ``,
        q3: [],
        option: [`Matrix-Gla protein`, 
        `Bikunin`, 
        `Citrate`, 
        `Pyrophosphate`, 
        `Uric acid`],
        optionFeedback: [``,
        ``,
        ``,
        ``,
        
        ``],
        optionStyleType: `st-lower-alpha`,
        answer: [4],
        ansText:`Rationale:<!--<b>e. Uric acid.</b>--> Uric acid is thought to promote calcium oxalate stone formation by removing urinary inhibitors, by “salting out” calcium oxalate in solution and by heterogeneous nucleation, or epitaxy. The other substances are all natural inhibitors of stone formation. `, 
        state: `notAnswered`,
        userAnswered: [],
    
        type: `MCSS`},
    {
        q: `Which of the following amino acids is subject to impaired renal reabsorption in cystinuria?`,
        q2: ``,
        q3: [],
        option: [`Arginine`, 
        `Glycine`, 
        `Alanine`, 
        `Leucine`, 
        `Methionine`],
        optionFeedback: [``,
        ``,
        ``,
        ``,
        
        ``],
        optionStyleType: `st-lower-alpha`,
        answer: [0],
        ansText:`Rationale:<!--<b>a. Arginine.</b>--> Renal reabsorption of the four dibasic amino acids—cystine, ornithine, lysine, and arginine—is affected by dysfunction of the heteromeric amino acid transporter located in the renal proximal tubule. Because of the poor solubility of cystine in urine, only cystine stones occur in this condition. `, 
        state: `notAnswered`,
        userAnswered: [],
    
        type: `MCSS`},
]