var quiz = [
  {
    q: `The uterine vessels are found ______________ to the ureter.`,
    q2: ``,
    q3: [],
    option: [
      `laterally`,
      `posteriorly`,
      `anteriorly`,
      `medially`,
      `running together in a common sheath`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [2],
    ansText: `Rationale: <!--<b>c. Anteriorly.</b>--> In women, the ureter first runs posterior to the ovary, then turns medially to run deep to the base of the broad ligament before entering a loose connective tissue tunnel through the substance of the cardinal ligament.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `All of the following are TRUE EXCEPT:`,
    q2: ``,
    q3: [],
    option: [
      `The angle between the inferior pubic rami is obtuse in women.`,
      `The female pelvis is larger and broader than the male pelvis.`,
      `The female inlet is heart shaped (as compared with the oval-shaped male inlet).`,
      `The female pelvis is shorter and wider, with a less pronounced sacral promontory.`,
      `Female pelvic inlet faces anteriorly, allowing pressure of the intra-abdominal and intrapelvic contents to be directed to the bony pelvis.`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [2],
    ansText: `Rationale: <!--<b>c. The female inlet is heart shaped (as compared with the oval-shaped male inlet).</b>--> The female inlet is oval in shape (as compared with the heart-shaped male inlet) and wider, which contributes to the weakness of the pelvic floor.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `In contrast to that of the male, the female bladder neck:`,
    q2: ``,
    q3: [],
    option: [
      `has extensive adrenergic innervation.`,
      `has a thickened middle smooth muscle layer.`,
      `is largely responsible for urinary continence.`,
      `is surrounded by type I (slow-twitch) fibers.`,
      `has longitudinal smooth muscle fibers that extend to the external meatus.`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [4],
    ansText: `Rationale: <!--<b>e. Has longitudinal smooth muscle fibers that extend to the external meatus.</b>--> At the female bladder neck, the inner longitudinal fibers converge radially to pass downward as the inner longitudinal layer of the urethra. The middle circular layer does not appear to be as robust as that of the male. The female bladder neck differs strikingly from the male in possessing little adrenergic innervation.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `Relative to the anterior portion of the uterosacral ligament, the ureter:`,
    q2: ``,
    q3: [],
    option: [
      `lies inferior.`,
      `lies posterior.`,
      `lies superior.`,
      `lies lateral.`,
      `runs along with it.`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [3],
    ansText: `Rationale: <!--<b>d. Lies lateral.</b>--> The uterosacral originates from the greater sciatic foramen and inserts into the lateral aspect of the fascia surrounding the cervix, isthmus of the uterus, and vaginal wall. The ureter lies lateral to the anterior portion of the uterosacral ligament (closest to the cervix).`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `To avoid denervation of the striated urethral sphincter, incisions through the vaginal wall to enter the retropubic space should be made:`,
    q2: ``,
    q3: [],
    option: [
      `perpendicular to the urethra.`,
      `over the urethra.`,
      `close to the lateral margins of the urethra.`,
      `cephalad to the bladder neck.`,
      `far lateral in the vaginal wall, parallel to the urethra.`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [4],
    ansText: `Rationale: <!--<b>e. Far lateral in the vaginal wall, parallel to the urethra.</b>--> Somatic and autonomic nerves to the urethra travel on the lateral walls of the vagina near the urethra. During transvaginal incontinence surgery, the anterior vaginal wall should be incised laterally to avoid these nerves and prevent type III urinary incontinence.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `The levator ani muscles make up the largest portion of the pelvic cavity floor. This consists of the:`,
    q2: ``,
    q3: [],
    option: [
      `iliopsoas, puborectalis, and obturator internus.`,
      `obturator externus, psoas major, and psoas minor.`,
      `coccygeus, pubococcygeus, and iliopsoas.`,
      `iliococcygeus, puborectalis, and pubococcygeus.`,
      `obturator internus, pubococcygeus, and psoas minor.`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [3],
    ansText: `Rationale: <!--<b>d. Iliococcygeus, puborectalis, and pubococcygeus.</b>--> This is innervated by the fourth sacral nerve. The name of each component is derived from their attachments.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `A Maritus (labial fat pad) rotational flap used in the repair of vesicovaginal fistula receives blood supply from the:`,
    q2: ``,
    q3: [],
    option: [
      `terminal branches of the internal pudendal artery and vein.`,
      `superficial inferior epigastric vessels.`,
      `inferior epigastric vessels.`,
      `accessory pudendal vessels.`,
      `external pudendal vessels.`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [4],
    ansText: `Rationale: <!--<b>e. External pudendal vessels.</b>--> The labial fat pads received blood supply from the external pudendal branches of the femoral vessels.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `Translabial ultrasound is valuable because it does not distort or compress the tissue. It is commonly used to visualize:`,
    q2: ``,
    q3: [],
    option: [
      `transvaginal mesh.`,
      `urethral bulking agents.`,
      `urethral implants.`,
      `bladder wall thickness.`,
      `all of the above.`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [4],
    ansText: ` `,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `The round ligament:`,
    q2: ``,
    q3: [],
    option: [
      `terminates in the uterus.`,
      `is the main source of blood supply to the ovaries.`,
      `terminates in the labia.`,
      `is the male homolog of the spermatic cord.`,
      `is NOT part of the broad ligament.`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [2],
    ansText: `Rationale: <!--<b>c. Terminates in the labia.</b>--> The round ligament exits at the internal inguinal ring and crosses over the external iliac artery, terminating in the mons pubis of the labia. The male homolog of the round ligament is the gubernaculum.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `All of the following are true regarding the perineal bodyEXCEPT:`,
    q2: ``,
    q3: [],
    option: [
      `Damage to the perineal body during labor can cause damage to fibers of the internal anal sphincter.`,
      `It is the convergence of the bulbospongiosus, external anal sphincter and superficial and deep transverse perineal muscles.`,
      `Perineal body attaches to the posterior border of the perineal membrane.`,
      `Perineal body is made up of muscle and collagenous and elastic fibers and lies at the central point of the perineum.`,
      `Episiotomy is angled laterally to avoid damage to fibers of the external anal sphincter.`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [0],
    ansText: ` `,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `The transversalis fascia is:`,
    q2: ``,
    q3: [],
    option: [
      `part of the inner stratum.`,
      `part of the outer stratum.`,
      `part of the intermediate stratum.`,
      `continuous with the endopelvic fascia.`,
      `b and d.`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [4],
    ansText: `Rationale: <!--<b>e. b and c.</b>--> The transversalis fascia is part of the outer stratum and is continuous with the endopelvic and lateral pelvic fascia. Both the transversalis and endopelvic fascia play important roles at the exit points of the pelvic organs. The endopelvic fascia extends from the uterine artery down to where the vagina and levator ani fuse.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `After a sacrospinous ligament fixation, the patient wakes up with pain in the posterior and lower leg. The nerve that was likely compromised is the:`,
    q2: ``,
    q3: [],
    option: [
      `femoral nerve.`,
      `pudendal nerve.`,
      `sacral plexus.`,
      `obturator nerve.`,
      `a and b.`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [2],
    ansText: `Rationale: <!--<b>c. Sacral plexus.</b>--> During an sacrospinous ligament fixation, the sacral plexus is in jeopardy of being injured because it lies immediately posterior to the sacrospinous ligament as it leaves through the greater sciatic foramen. The pudendal nerve may also be injured during this repair.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `The arcus tendineus fascia pelvis:`,
    q2: ``,
    q3: [],
    option: [
      `is present in females.`,
      `attaches from the ischial spine to the sacrum.`,
      `is also known as the tendinous arc.`,
      `is present only in males.`,
      `all of the above.`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [2],
    ansText: `Rationale: <!--<b>c. Is also known as the tendinous arc.</b>--> The arcus tendineus fascia pelvis, or tendinous arc, is a thickened band of the pelvic fascia that runs from the ischial spine to the pubic bone. It originates from the pubic bone laterally and is connected to the pubovesical ligament medially and the tendinous arch of the levator ani.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `Please identify the correct pair(s) of arterial supply and lymphatic drainage of the vagina.`,
    q2: ``,
    q3: [],
    option: [
      `Uterine arteries: superficial inguinal nodes`,
      `Internal pudendal artery: sacral common iliac and superficial inguinal nodes`,
      `Vaginal arteries: external iliac nodes`,
      `Uterine arteries: sacral common iliac nodes`,
      `Internal pudendal artery: external iliac nodes`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [1],
    ansText: `Rationale: <!--<b>b. Internal pudendal artery: sacral, common iliac, and superficial inguinal nodes.</b>--> The superior part: blood supply—uterine arteries/drainage—internal and external iliac nodes middle and inferior: blood supply—vaginal arteries/drainage—internal and external iliac nodes Inferior vagina: blood supply—internal pudendal artery/drainage—sacral, common iliac, and superficial inguinal nodes.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `Squamous metaplasia of the bladder:`,
    q2: ``,
    q3: [],
    option: [
      `is a premalignant lesion.`,
      `is a sign of an underlying serious infection.`,
      `should always be treated with surgical resection.`,
      `is a normal finding in premenopausal females.`,
      `is none of the above.`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [3],
    ansText: `Rationale: <!--<b>d. Is a normal finding in premenopausal females.</b>--> Premenopausal women can have normal signs of squamous metaplasia at the trigone and base of the bladder. This is a nonkeratinizing metaplasia or vaginal metaplasia that is hormonally responsive and is a normal variant.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `The levator ani attaches to all of the following EXCEPT:`,
    q2: ``,
    q3: [],
    option: [
      `perineal body.`,
      `pubis.`,
      `coccyx.`,
      `vagina.`,
      `arcus tendineus fascia pelvis.`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [4],
    ansText: `Rationale: <!--<b>e. Arcus tendineus fascia pelvis.</b>--> The tendinous arc of the levator ani serves as the origin of the muscles of the pelvis diaphragm: pubococcygeus and iliococcygeus. The muscle bordering this hiatus has been referred to as “pubovisceral” because it provides a sling for (pubourethralis, puborectalis), inserts directly into (pubovaginalis, puboanalis, levator prostate), or inserts into a structure intimately associated with the pelvic viscera. The coccygeus muscle extends from the sacrospinous ligament to the lateral border of the sacrum and coccyx to complete the pelvic diaphragm.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `The ureter can be injured during a hysterectomy:`,
    q2: ``,
    q3: [],
    option: [
      `at the time of the division of the ovarian artery.`,
      `at the time of the division of the uterine artery.`,
      `at the time of the division of the cardinal artery.`,
      `while dissecting out the cervix.`,
      `all of the above.`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [4],
    ansText: `Rationale: <!--<b>e. All of the above.</b>--> The ureter is vulnerable to injury because it comes in close proximity to many of the structures that are dissected and divided during a radical hysterectomy. It crosses the infundibulopelvic ligament under the ovarian artery and is just medial to the uterine artery. It also passes through the cardinal ligament and lies in close proximity to the cervix.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `During a sacrospinous ligament vault suspension, significant bleeding is encountered. The bleeding vessels most likely originate from the:`,
    q2: ``,
    q3: [],
    option: [
      `anterior division of the internal iliac artery.`,
      `posterior division of the internal iliac artery.`,
      `perineal artery.`,
      `mesenteric artery.`,
      `epigastric artery.`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [1],
    ansText: ` `,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `The peritoneum may be accessed transvaginally through the:`,
    q2: ``,
    q3: [],
    option: [
      `posterior fornix.`,
      `anterior fornix.`,
      `rectovaginal septum.`,
      `lateral fornices.`,
      `vesicovaginal space.`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [0],
    ansText: `Rationale: <!--<b>a. Posterior fornix.</b>--> Because the apex of the vagina is covered with the peritoneum of the rectouterine pouch, the peritoneal cavity may be accessed through the posterior fornix.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `The cavernous nerve, responsible for clitoral engorgement during sexual activity, is derived from:`,
    q2: ``,
    q3: [],
    option: [
      `the pudendal nerve.`,
      `the dorsal nerve of the clitoris.`,
      `the superior hypogastric plexus.`,
      `the inferior hypogastric plexus.`,
      `the obturator nerve`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [3],
    ansText: ` `,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
];
