var quiz = [
    

    {
        q: `The following statements are true regarding laparoscopic and robotic renal surgery in obese patients, EXCEPT:`,
        q2: ``,
        q3: [],
        option: [`Obesity is associated with distorted anatomy and limited range of instrument motion.`, 
        `Morbid obesity (body mass index [BMI] &gt;40) is a contraindication to laparoscopic or robotic surgery.`, 
        `Complication rates are higher among obese patients.`, 
        `Conversion to open surgery is more common in obese patients.`, 
        `Longer surgical instruments are sometimes required to complete the procedure.`],
        optionStyleType: `st-lower-alpha`,
        answer: [0],
        ansText:`Rationale: <!--b.--> <!--<b>Obesity is associated with distorted anatomy and limited range of instrument motion.</b>--> Although morbid obesity is associated with distorted anatomy, limited range of instrument motion, and higher complication and conversion rates, it is not a contraindication to laparoscopic or robotic renal surgery. In general, obese patients benefits from minimally invasive surgery given it provides less incisional pain and shorter convalescence.`, 
        state: `notAnswered`,
        userAnswered: []
    ,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`        ,
        type: `MCSS`},
    {
        q: `The following statements are true regarding laparoscopic and robotic surgical approaches to renal surgery, EXCEPT:`,
        q2: ``,
        q3: [],
        option: [`Transperitoneal is the most widely used approach.`, 
        `Retroperitoneal partial nephrectomy is best suited for anterior renal tumors.`, 
        `Disadvantages of retroperitoneal approach include the limited working space and decreased instrument triangulation.`, 
        `The advantages of robotic approach include greater degree of instrument motion, elimination of tremor, and the ability to scale motions.`, 
        `Advantages of transperitoneal approach include familiar anatomic landmarks and more flexibility of trocar placement.`],
        optionStyleType: `st-lower-alpha`,
        answer: [1],
        ansText:`Rationale: <!--<b>b. Retroperitoneal partial nephrectomy is best suited for anterior renal tumors.</b>--> Although anterior renal tumors can be resected with retroperitoneal partial nephrectomy, this technique is best suited for posterior tumors. A study comparing 100 transperitoneal and 63 retroperitoneal laparoscopic partial nephrectomies found that 77% of the posterior tumors were managed via retroperitoneal approach and 97% of the anterior tumors were managed with transperitoneal surgery.`, 
        state: `notAnswered`,
        userAnswered: []
    ,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`        ,
        type: `MCSS`},
    {
        q: `The following statements are true regarding laparoendoscopic single site (LESS) and natural orifice transluminal endoscopic surgery (NOTES) compared to conventional laparoscopic renal surgery, EXCEPT:`,
        q2: ``,
        q3: [],
        option: [`For both LESS and NOTES, conventional laparoscopic instrumentation cannot be used, and flexible or articulated instruments are required.`, 
        `LESS consolidates all laparoscopic ports in a single skin incision.`, 
        `LESS and NOTES are associated with improving cosmesis and reduced postoperative pain.`, 
        `LESS has limited triangulation due to the clustering of instruments entering the intracorporal working space.`, 
        `NOTES uses one or more patent natural orifices of the body for access.`],
        optionStyleType: `st-lower-alpha`,
        answer: [0],
        ansText:`Rationale: <!--<b>a. For both LESS and NOTES, conventional laparoscopic instrumentation cannot be used, and flexible or articulated instruments are required.</b>--> Although LESS has limited triangulation due to the clustering of instruments entering the intracorporeal working space, conventional laparoscopic instrumentation can be used. Flexible or articulated instruments are helpful but not required in cases of LESS or NOTES.`, 
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `The following are indications for renal cysts disease treatment, EXCEPT:`,
        q2: ``,
        q3: [],
        option: [`cyst-associated pain.`, 
        `ureteral obstruction.`, 
        `suspicion for malignancy.`, 
        `infection.`, 
        `autosomal dominant polycystic kidney disease.`],
        optionStyleType: `st-lower-alpha`,
        answer: [4],
        ansText:`Rationale: <!--<b>e. Autosomal dominant polycystic kidney disease.</b>--> Cyst-associated pain, urinary obstruction, suspicion for malignancy, and infection are traditional indications for operative management of renal cysts. Autosomal dominant polycystic kidney disease alone is not an indication for surgical intervention unless it is accompanied by complications, pain, suspicion for malignancy, etc.`, 
        state: `notAnswered`,
        userAnswered: []
    ,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`        ,
        type: `MCSS`},
    {
        q: `The following statements are true regarding laparoscopic and robotic renal surgery for renal cystic disease, EXCEPT:`,
        q2: ``,
        q3: [],
        option: [`Symptomatic benign cysts can be initially managed with percutaneous needle aspiration.`, 
        `Multiple or bilateral cysts should not be treated in the same operation.`, 
        `Laparoscopic management of symptomatic renal cysts is associated with greater than 90% symptom improvement.`, 
        `If a sclerosing agent is used, it should not be injected into the collecting system.`, 
        `Most renal cysts do not require surgical intervention.`],
        optionStyleType: `st-lower-alpha`,
        answer: [1],
        ansText:`Rationale: <!--<b>b. Multiple or bilateral cysts should not be treated in the same operation.</b>--> Although most renal cysts do not require surgical intervention, multiple or bilateral cysts can and frequently are treated in the same operation, with greater than 90% symptom improvement and radiologic resolution.`, 
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `The following statements are true regarding laparoscopic renal biopsy, EXCEPT:`,
        q2: ``,
        q3: [],
        option: [`It is indicated in cases of hematuria and proteinuria of glomerular origin and/or unexplained renal failure.`, 
        `The most common complication is bleeding.`, 
        `Ultrasound guidance can facilitate the localization of the kidney in cases of abundant retroperitoneal and perinephric adipose tissue.`, 
        `A 5-mm biopsy forceps or an 18-gauge Tru-Cut needle can be used for tissue sampling.`, 
        `It is contraindicated in cases of multiple renal cysts or solitary kidney.`],
        optionStyleType: `st-lower-alpha`,
        answer: [4],
        ansText:`Rationale: <!--<b>e. It is contraindicated in cases of multiple renal cysts or solitary kidney.</b>--> Although renal biopsy is typically done percutaneously under CT or ultrasound guidance, there are circumstances where a laparoscopic biopsy may be preferred, including failed previous attempts at percutaneous biopsy, renal anatomic abnormalities, bleeding diathesis, morbid obesity, multiple renal cysts, or a solitary kidney.`, 
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `The following statements are true regarding nephropexy and nephrolysis, EXCEPT:`,
        q2: ``,
        q3: [],
        option: [`Nephrolysis consists of the renal mobilization with skeletonization of the hilar vessels and upper ureter.`, 
        `Nephrolysis is an effective treatment for severe refractory chyluria.`, 
        `Nephropexy is indicated in cases of nephroptosis associated with pain or vascular or urinary obstruction.`, 
        `Nephropexy can be accomplished with either suture fixation or the use of foreign material, such as mesh or tissue adhesive.`, 
        `Laparoscopic nephropexy is associated with greater than 80% resolution of nephroptosis but almost no pain improvement.`],
        optionStyleType: `st-lower-alpha`,
        answer: [4],
        ansText:`Rationale: <!--<b>e. Laparoscopic nephropexy is associated with greater than 80% resolution of nephroptosis but almost no pain improvement.</b>--> Laparoscopic nephropexy is associated with a 90% to 100% pain improvement, 80% to 95% resolution of the 5-cm renal descent, and 90% improvement in renal function measured by nuclear medicine scan. Nephrolysis consists of the renal mobilization with skeletonization of the hilar vessels and upper ureter and is an effective treatment for severe refractory chyluria.`, 
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `The following statements are true regarding calyceal diverticulectomy, EXCEPT:`,
        q2: ``,
        q3: [],
        option: [`Most cases of calyceal diverticulectomy require hilar clamping.`, 
        `Indications for surgical intervention include chronic pain, recurrent urinary tract infection, gross hematuria, and decline in renal function.`, 
        `Calyceal diverticulectomy involves widening of the infundibular drainage to prevent urinary stasis or complete ablation of the diverticula cavity.`, 
        `Injection of dye via a preoperatively placed externalized ureteral catheter is helpful in localizing the diverticulum.`, 
        `Laparoscopic, robotic, or LESS transperitoneal or retroperitoneal approaches can be used.`],
        optionStyleType: `st-lower-alpha`,
        answer: [0],
        ansText:`Rationale: <!--<b>a. Most cases of calyceal diverticulectomy require hilar clamping.</b>--> Given most cases of calyceal diverticulectomy have low bleeding risk, hilar control is usually not required.`, 
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `The following are advantages of laparoscopic over open radical nephrectomy, EXCEPT:`,
        q2: ``,
        q3: [],
        option: [`improved cosmesis.`, 
        `shorter hospital stay.`, 
        `improved cancer-specific survival.`, 
        `less analgesic use.`, 
        `shorter convalescence time.`],
        optionStyleType: `st-lower-alpha`,
        answer: [2],
        ansText:`Rationale: <!--<b>c. Improved cancer-specific survival.</b>--> Advantages of laparoscopic radical nephrectomy include improved cosmesis, shorter hospital stay, less analgesic requirement, and shorter convalescence time. Oncologic outcomes including recurrence, progression to metastatic disease, and cancer-specific survival are comparable with open radical nephrectomy.`, 
        state: `notAnswered`,
        userAnswered: []
    ,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`        ,
        type: `MCSS`},
    {
        q: `Which of the following is an absolute contraindication to laparoscopic radical nephrectomy?`,
        q2: ``,
        q3: [],
        option: [`Tumor size greater than 14 cm`, 
        `Age older than 80 years`, 
        `Uncorrected coagulopathy`, 
        `Renal vein thrombus`, 
        `Multiple prior abdominal surgeries`],
        optionStyleType: `st-lower-alpha`,
        answer: [2],
        ansText:`Rationale: <!--<b>c. Uncorrected coagulopathy.</b>--> Uncorrected coagulopathy is an absolute contraindication to laparoscopic renal surgery, as are untreated infection and hypovolemic shock. Laparoscopic partial nephrectomy has been reported as a feasible and safe approach in the management of select large renal masses, elderly patients, renal vein thrombosis, and multiple prior abdominal surgeries.`, 
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `Regarding laparoscopic radical nephrectomy, the following statement is CORRECT:`,
        q2: ``,
        q3: [],
        option: [`En bloc hilar vessel stapling is unsafe and should not be attempted.`, 
        `The use of a retrieval bag is not needed in cases of tumor extraction after morcellation.`, 
        `Metastatic renal cell carcinoma is an absolute contraindication.`, 
        `Clips alone are contraindicated for the ligation of the renal artery.`, 
        `Adrenal gland should be bluntly hand-dissected away from the upper pole during hand-assisted nephrectomy.`],
        optionStyleType: `st-lower-alpha`,
        answer: [3],
        ansText:`Rationale: <!--<b>d. Clips alone are contraindicated for the ligation of the renal artery.</b>--> Although previously there have been concerns of arteriovenous fistula formation in cases of en bloc hilar vessel stapling, this approach has been shown to be a safe alternative. The use of a retrieval bag is mandatory in cases of tumor extraction after morcellation to prevent tumor spillage. Cytoreductive laparoscopic nephrectomy is safe and effective in patients with metastatic renal cell carcinoma. The hand should not be used to bluntly dissect the adrenal gland free from the upper pole because this will typically result in bleeding. Clips alone are contraindicated for the ligation of the renal artery due to reports of fatal cases of clip failure.`, 
        state: `notAnswered`,
        userAnswered: []
    ,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`        ,
        type: `MCSS`},
    {
        q: `Compared to traditional laparoscopic nephrectomy, hand-assisted nephrectomy is associated with higher:`,
        q2: ``,
        q3: [],
        option: [`local recurrence.`, 
        `wound-related complications.`, 
        `pain scores.`, 
        `conversion to open surgery.`, 
        `costs.`],
        optionStyleType: `st-lower-alpha`,
        answer: [1],
        ansText:`Rationale: <!--<b>b. Wound-related complications.</b>--> Hand-assisted laparoscopic nephrectomy offers recovery, morbidity and cost that are comparable with those of pure laparoscopy surgery. Recurrence-free, cancer-specific, and overall survivals are similar between surgical techniques. The rate of wound-related complications such as wound infection and incisional hernia are slightly higher in hand-assisted approach compared to pure laparoscopy.`, 
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `Regarding minimally invasive partial nephrectomy, the following statement is CORRECT:`,
        q2: ``,
        q3: [],
        option: [`Central and hilar tumors are a contraindication to laparoscopic partial nephrectomy.`, 
        `Compared to open partial nephrectomy, robot-assisted partial nephrectomy in solitary kidney is associated with higher conversion to radical nephrectomy.`, 
        `The placement of a drain is generally considered unnecessary when the incision in the pelvicalyceal system is repaired with running suture.`, 
        `Suture renorrhaphy is the most reliable technique to achieve hemostasis of the partial nephrectomy bed.`, 
        `Multiple ipsilateral renal tumors should not be removed in the same setting.`],
        optionStyleType: `st-lower-alpha`,
        answer: [3],
        ansText:`Rationale: <!--<b>d. Suture renorrhaphy is the most reliable technique to achieve hemostasis of the partial nephrectomy bed.</b>--> Minimally invasive partial nephrectomy for central and hilar tumors can be performed safely by an experienced surgeon with perioperative outcomes comparable with those of peripheral tumors. Minimally invasive partial nephrectomy for tumors in a solitary kidney is safe and offers comparable outcomes to open surgery. Repeat renal surgery can pose a technical challenge and is associated with higher blood loss and complication rates compared to first-time renal surgery. Although the laparoscopic resection of multiple tumors is associated with long operative time and hospitalization, in experience hands it is associated with comparable blood loss, complication rates, and renal functional outcomes as resection of a solitary tumor. The placement of a drain is usually recommended in most cases of pelvicalyceal system, even cases that are repaired with running sutures, to reduce the risk of perinephric urinoma. Although there are other means of achieving hemostasis of the partial nephrectomy bed such as the use of clips and tissue sealants, suture renorrhaphy is considered the most reliable technique to achieve hemostasis.`, 
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `Regarding warm renal ischemia and hilar control, the following statement is INCORRECT:`,
        q2: ``,
        q3: [],
        option: [`Hilar control can be accomplished by using bulldog clamps or a laparoscopic Satinsky clamp.`, 
        `Renal artery–only clamping is a safe alternative to artery and vein clamping.`, 
        `Parenchymal compression is best suited for peripheral tumors.`, 
        `Off-clamp partial nephrectomy is a suitable option for the resection of small, exophytic, and noninfiltrating tumors.`, 
        `Hilar unclamping before the completion of the renorrhaphy is contraindicated.`],
        optionStyleType: `st-lower-alpha`,
        answer: [4],
        ansText:`Rationale: <!--<b>e. Hilar unclamping before the completion of the renorrhaphy is contraindicated.</b>--> During radiofrequency ablation, thermal damage occurs through frictional heating due to ionic oscillation by a monopolar or bipolar high-frequency alternating current which can induce temperatures between 60°C and 100°C throughout the tumor. Temperatures greater than 105°C should be avoided to prevent tissue vaporization.`, 
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `Regarding laparoscopic thermal ablation, the following statement is INCORRECT:`,
        q2: ``,
        q3: [],
        option: [`Compared to partial nephrectomy, the advantages of thermal ablation include less blood loss, short operative time, and fewer complications.`, 
        `The advantages of the laparoscopic approach over percutaneous ablation include direct tumor visualization, mobilization of the kidney, and dissection and retraction of surrounding structures.`, 
        `Contact of the iceball with the renal collecting system, ureter, renal vasculature, or adjacent organs should be avoided.`, 
        `Intraoperative monitoring of radiofrequency ablation is based on direct temperature measurement or measurement of electrical impedance.`, 
        `Temperatures greater than 105°C throughout the tumor are recommended for an adequate thermal damage.`],
        optionStyleType: `st-lower-alpha`,
        answer: [4],
        ansText:`Rationale: <!--<b>e. Temperatures greater than 105° C throughout the tumor are recommended for an adequate thermal damage.</b>--> Hilar control can be accomplished by using bulldog clamps on the renal artery with or without venous clamping, or a laparoscopic Satinsky clamp for en bloc hilar clamping. Studies evaluating early unclamping (before the completion of the renorrhaphy) found this technique to be associated with shorter warm ischemia time and comparable estimated blood loss and complication rates.`, 
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `Regarding complications of minimally invasive renal surgery, the following statement is INCORRECT:`,
        q2: ``,
        q3: [],
        option: [`Advanced age is a major risk factor for complications.`, 
        `Partial nephrectomy is associated with higher complication rates compared to radical nephrectomy and simple nephrectomy.`, 
        `Large tumors, obesity, and prior abdominal surgery are associated with a higher complication rate.`, 
        `Chronic pyelonephritis, such as xanthogranulomatous pyelonephritis, is associated with greater rate of conversion to open surgery.`, 
        `The most common postoperative complications are bleeding, wound infection, pneumonia, and prolonged ileus.`],
        optionStyleType: `st-lower-alpha`,
        answer: [0],
        ansText:`Rationale: <!--<b>a. Advanced age is a major risk factor for complications.</b>--> Advanced age alone is not a major risk factor for complications. Obesity, comorbidities, prior abdominal surgery, and larger and more anatomically complex tumors have all been associated with higher complication rates.`, 
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `Regarding complications of minimally invasive renal surgery, the following statement is INCORRECT:`,
        q2: ``,
        q3: [],
        option: [`Most of the life-threatening intraoperative complications occur during the access phase and dissection of the renal hilum.`, 
        `Most cases of urinary leak require ureteral stenting or percutaneous nephrostomy placement.`, 
        `Mild to moderate venous bleeding can be controlled by applying direct pressure.`, 
        `Factors associated with urinary leak include large tumor size, hilar location, pelvicalyceal repair, and prolonged warm ischemia time.`, 
        `Stapler malfunction is associated with a 20% conversion rate to open surgery and 2% mortality rate.`],
        optionStyleType: `st-lower-alpha`,
        answer: [1],
        ansText:`Rationale: <!--<b>b. Most cases of urinary leak require ureteral stenting or percutaneous nephrostomy placement.</b>--> Factor associated with urinary leak include large tumor size, hilar location, pelvicalyceal repair, and prolonged operative and warm ischemia time. Most cases of urinary leak require no intervention other than percutaneous drainage. When conservative management fails or there is evidence of distal obstruction, additional intervention may be required, such as ureteral stenting and bladder decompression.`, 
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `Regarding complications of minimally invasive renal surgery, the following statement is INCORRECT:`,
        q2: ``,
        q3: [],
        option: [`Persistent and increased trocar site pain without significant erythema or purulent drainage is a common sign of visceral injury.`, 
        `Splenic injuries are most commonly caused by vigorous traction on splenic ligaments.`, 
        `Gallbladder injuries are best managed by primary surgical repair.`, 
        `Capsular pancreatic injuries can be managed by closing the defect with nonabsorbable suture and/or drain placement.`, 
        `Most liver injuries can be managed with topical hemostatic therapy and argon beam coagulation.`],
        optionStyleType: `st-lower-alpha`,
        answer: [2],
        ansText:`Rationale: <!--<b>c. Gallbladder injuries are best managed by primary surgical repair.</b>--> Gallbladder injuries are best managed by cholecystectomy.`, 
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `A 55-year-old woman presents to the emergency department on postoperative day 5 after laparoscopic left radical nephrectomy complaining of vomiting, fever, and diffuse abdominal pain. Computed tomography (CT) scan with oral contrast shows leakage of contrast from the ascending colon. The most likely cause of this injury is:`,
        q2: ``,
        q3: [],
        option: [`bowel ischemia.`, 
        `trocar placement.`, 
        `blunt dissection.`, 
        `electrocautery.`, 
        `abdominal wall closure.`],
        optionStyleType: `st-lower-alpha`,
        answer: [3],
        ansText:`Rationale: <!--<b>d. Electrocautery.</b>--> Although bowel injury can occur at any point during the procedure, the most common case of unrecognized injury is the use of thermal energy adjacent to the bowel, responsible for nearly 50% of the cases. Thermal injuries usually present later than nonthermal bowel injuries.`, 
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `A 71-year-old woman presents to emergency department with new-onset gross hematuria on postoperative day 6 after an uncomplicated laparoscopic right partial nephrectomy. Her blood pressure is 90/56 mm Hg and heart rate is 112 beats/min. Hematocrit is 21%. After fluid resuscitation, her vital signs normalized, but the hematuria worsens and requires continuous bladder irrigation. The best next step is:`,
        q2: ``,
        q3: [],
        option: [`cystoscopy and retrograde pyelogram.`, 
        `radical nephrectomy.`, 
        `renal angiography and embolization.`, 
        `admission to intensive care unit and blood transfusion.`, 
        `CT scan with intravenous contrast.`],
        optionStyleType: `st-lower-alpha`,
        answer: [2],
        ansText:`Rationale: <!--<b>c. Renal angiography and embolization.</b>--> Significant gross hematuria after partial nephrectomy suggests postoperative bleeding from an arteriovenous fistula or pseudoaneurysm. Although a CT scan with intravenous contrast may help to diagnose and localize a postoperative bleed, this will ultimately delay treatment. Immediate renal angiogram with selective arterial embolization allows for diagnosis, localization, and definitive treatment in the same setting.`, 
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`}
    



];
