var quiz = [
  {
    q: `A healthy 45-year-old man with no family history of cancer is found to have a 6-cm enhancing mass in the upper pole of his right kidney. A 2-cm solitary nodule is noted on preoperative chest radiography. Computed tomography (CT) confirms a solitary nodule in the lower lobe of the right lung. What is the most appropriate treatment course?`,
    q2: ``,
    q3: [],
    option: [
      `Systemic chemotherapy alone`,
      `Radical right nephrectomy and postoperative chemotherapy`,
      `Biopsy of pulmonary nodule`,
      `Radical nephrectomy and simultaneous pulmonary metastasectomy`,
      `Radical nephrectomy with staged resection of pulmonary nodule 6 weeks postoperatively`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [3],
    ansText: `Rationale: <!--<b>d. Radical nephrectomy and simultaneous pulmonary metastasectomy.</b>--> This patient would be best managed with a radical nephrectomy and simultaneous removal of the pulmonary nodule. Systemic therapy is not a primary treatment unless there is extensive metastatic disease at presentation. Given his age and lack of medical problems, there is no reason to delay the removal of his kidney and the pulmonary nodule. The tumor location and pulmonary nodule both can be accessed through one incision (i.e., thoracoabdominal).`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `What is the preferred technique for radical nephrectomy and removal of tumor thrombus above the level of the diaphragm in the absence of significant metastatic disease?`,
    q2: ``,
    q3: [],
    option: [
      `Flank incision with extensive liver mobilization and removal of tumor through an incision in the diaphragm`,
      `Flank incision with cardiopulmonary bypass and deep hypothermic circulatory arrest (CPB-DHCA)`,
      `Chevron incision with CPB-DHCA`,
      `Chevron incision with Pringle maneuver`,
      `Midline incision with CPB-DHCA`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [2],
    ansText: `Rationale: <!--<b>c. Chevron incision with CPB-DHCA.</b>--> CPB-DHCA has been established as the most prudent course for the removal of these tumor thrombi. The chevron incision provides the best exposure. Alternatives to CPB, including extensive liver mobilization and intrapericardial resection, carry an increased risk of bleeding.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `Deep hypothermic circulatory arrest (DHCA) can have irreversible neurologic effects after what period of time?`,
    q2: ``,
    q3: [],
    option: [
      `10 minutes`,
      `20 minutes`,
      `40 minutes`,
      `60 minutes`,
      `90 minutes`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [2],
    ansText: `Rationale: <!--<b>c. 40 minutes.</b>--> The duration of DHCA can vary depending on the degree of tumor thrombus. Vena cava resection and substitution can add additional time if there is significant tumor invasion into the wall of the vena cava. Studies have suggested that irreversible neurologic effects may be observed after 40 minutes of DHCA.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `In a 45-year-old man with a normal contralateral kidney and no family history of kidney cancer, in which of the following clinical scenarios would partial nephrectomy be indicated?`,
    q2: ``,
    q3: [],
    option: [
      `Two tumors less than 3 cm each in the upper and lower pole`,
      `Single 8-cm tumor in the upper pole`,
      `Single 2-cm tumor in a hilar location with small renal vein tumor thrombus`,
      `Single 4-cm tumor in any location`,
      `All of the above`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [3],
    ansText: `Rationale: <!--<b>d. Single 4-cm tumor in any location.</b>--> In patients with a normal contralateral kidney, the current literature supports elective partial nephrectomy for single T1 tumors.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `What is the strongest modifiable risk factor for renal insufficiency after partial nephrectomy?`,
    q2: ``,
    q3: [],
    option: [
      `Duration of renal ischemia`,
      `Surgical approach`,
      `Administration of nephrotoxins`,
      `Resection margin`,
      `Administration of heparin`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [0],
    ansText: `Rationale: <!--<b>a. Duration of renal ischemia.</b>--> Duration of renal ischemia is the strongest modifiable risk factor for renal insufficiency after partial nephrectomy.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `During a posterior right lumbotomy approach, what is the order of appearance of the renal artery, renal vein, and renal pelvis?`,
    q2: ``,
    q3: [],
    option: [
      `Artery, renal pelvis, vein`,
      `Artery, vein, renal pelvis`,
      `Renal pelvis, artery, vein`,
      `Vein, renal pelvis, artery`,
      `Renal pelvis, vein, artery`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [2],
    ansText: `Rationale: <!--<b>c. Renal pelvis, artery, vein.</b>--> The renal pelvis is the first structure one encounters with the posterior right lumbotomy incision, followed by the artery and vein. This approach can be used to repair ureteropelvic junction obstruction, especially in children or patients with multiple prior abdominal and/or flank surgeries.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `Coming soon`,
    q2: ``,
    q3: [],
    option: [`Coming soon`],
    optionStyleType: `Coming soon`,
    answer: [`Coming soon`],
    ansText: `Rationale: Coming soon`,
    state: `notAnswered`,
    userAnswered: [`Coming soon`],
  },
  {
    q: `Five days after left partial nephrectomy for a hilar tumor, there is persistent drainage from the Penrose drain site. Laboratory analysis of the drain fluid demonstrates elevated amylase levels. Imaging studies demonstrate small bowel dilation consistent with ileus and fluid around the tail of pancreas. What is the ideal management?`,
    q2: ``,
    q3: [],
    option: [
      `Antibiotics`,
      `Immediate surgical exploration`,
      `Percutaneous drain placement`,
      `Nasogastric tube placement, parenteral nutrition, and conservative management`,
      `Nasogastric tube placement, low-fat diet, and conservative management`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [3],
    ansText: `Rationale: <!--<b>d. Nasogastric tube placement, parenteral nutrition, and conservative management.</b>--> Conservative management of a pancreatic fistula should be the first approach in this patient. Initial nasogastric tube placement can help resolve the ileus. Parenteral nutrition will limit any pancreatic secretions from oral intake.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `Which segmental branch of the renal artery is most consistent and supplies 25% of the arterial supply to the renal unit?`,
    q2: ``,
    q3: [],
    option: [
      `Apical (superior) segmental artery`,
      `Anterior superior segmental artery`,
      `Posterior segmental artery`,
      `Anterior inferior segmental artery`,
      `The basilar (inferior) segmental artery`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [2],
    ansText: `Rationale: <!--<b>c. Posterior segmental artery.</b>--> The posterior division is the first and most consistent branch point of the renal artery and supplies approximately one-fourth of the blood supply.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `What maneuver refers to the reflection of the second and third portions of the duodenum in a medial direction to expose the right renal vessels and ventral inferior vena cava?`,
    q2: ``,
    q3: [],
    option: [
      `Cattell maneuver`,
      `Langenbeck maneuver`,
      `Sorcini maneuver`,
      `Kocher maneuver`,
      `Pringle maneuver`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [3],
    ansText: `Rationale: <!--<b>d. Kocher maneuver.</b>--> Mobilization of the second and third portions of the duodenum is referred to as a <b><i>Kocher maneuver.</i></b> The Pringle maneuver is the temporary occlusion of the porta hepatis. The Langenbeck maneuver is the division of the coronary and right triangular ligaments, providing medial rotation of the right lobe of the liver and exposure of the suprarenal inferior vena cava.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `What partial nephrectomy technique should be used as a last resort in a solitary kidney?`,
    q2: ``,
    q3: [],
    option: [
      `Enucleation`,
      `Wedge resection`,
      `Cryotherapy`,
      `Polar resection`,
      `Extracorporeal repair and autotransplantation`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [4],
    ansText: `Rationale: <!--<b>e. Extracorporeal repair and autotransplantation.</b>--> All patients with solitary kidneys are high-risk candidates for partial nephrectomy and may have transient renal impairment postoperatively. The degree and duration of renal impairment may be increased owing to risks associated with renal autotransplantation (hemorrhage, thrombosis, lymphocele, stenosis).`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `The subcostal nerve may be inadvertently transected during an anterior subcostal incision for a radical nephrectomy. Between what two layers does this nerve run?`,
    q2: ``,
    q3: [],
    option: [
      `Posterior peritoneum and transversalis fascia`,
      `Scarpa fascia and external oblique muscle`,
      `External oblique and internal oblique`,
      `Internal oblique and transversalis`,
      `Skin and Scarpa fascia`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [3],
    ansText: `Rationale: <!--<b>d. Internal oblique and transversalis.</b>--> The subcostal nerve runs between these two layers. Caution must be taken not to sever this nerve during flank incisions.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `What is the motor deficit resulting from transaction of the subcostal nerve?`,
    q2: ``,
    q3: [],
    option: [
      `Winged scapula`,
      `Hemidiaphragmatic paralysis`,
      `Paresis of the flank musculature and flank bulge`,
      `Inability to flex ipsilateral adductor muscle`,
      `Weakness of contralateral rectus abdominis muscle`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [2],
    ansText: `Rationale: <!--<b>c. Paresis of the flank musculature and flank bulge.</b>--> Damage to the subcostal nerve results in denervation and paresis of the flank musculature, leading to chronic postoperative pain or flank bulge.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `What percentage of patients have multiple renal arteries?`,
    q2: ``,
    q3: [],
    option: [
      `0% to 2%`,
      `2% to 10%`,
      `10% to 20%`,
      `20% to 30%`,
      `More than 30%`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [3],
    ansText: `Rationale: <!--<b>d. 20% to 30%.</b>--> <b>Multiple postmortem and radiographic studies estimate that 25% of the general population have supernumerary renal arteries.</b>`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `Which of the following is NOT an indication for simple nephrectomy?`,
    q2: ``,
    q3: [],
    option: [
      `Nonfunctional chronically infected kidney`,
      `Nonfunctional persistently hydronephrotic kidney causing pain`,
      `Renovascular hypertension refractory to medical and nephron-sparing surgical intervention`,
      `Polycystic kidney with minimal function and recurrent infections`,
      `Kidney with 8-cm enhancing upper pole hilar mass`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [4],
    ansText: `Rationale: <!--<b>e. Kidney with 8-cm enhancing upper pole hilar mass.</b>--> There should be little reservation about performing a radical nephrectomy for an enhancing mass, especially in the upper pole. Almost all nonmalignant disease affecting the kidney can be treated via a simple approach.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `Two days after cardiopulmonary bypass and circulatory arrest (20 minutes) for an extensive right-sided renal mass with thrombus extending into the atrium, using traditional median sternotomy, a relatively healthy 36-year-old patient is unable to be extubated and has no purposeful right-sided movement. Imaging reveals a large left-sided cerebrovascular infarct. What clinical scenario can explain this event?`,
    q2: ``,
    q3: [],
    option: [
      `Pulmonary air embolism`,
      `Cerebral ischemia from bypass and circulatory arrest`,
      `Tension pneumothorax`,
      `Right main stem bronchial intubation`,
      `Unrecognized paradoxical embolism`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [4],
    ansText: `Rationale: <!--<b>e. Unrecognized paradoxical embolism.</b>--> This rare but devastating clinical situation occurs in patients with a patent foramen ovale. An embolism may originate from tumor thrombus manipulation or from deep venous thromboembolism.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `Which form of therapy has been considered the gold standard for localized renal cell carcinoma?`,
    q2: ``,
    q3: [],
    option: [
      `Chemotherapy`,
      `Immunotherapy`,
      `Radiation`,
      `Hormonal therapy`,
      `Surgical resection`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [4],
    ansText: `Rationale: <!--<b>e. Surgical resection.</b>--> There have been numerous studies to suggest that surgical resection is the mainstay of therapy for kidney cancer.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `On postoperative day 2 after radical nephrectomy for a 14-cm complex left renal tumor using an anterior midline incision, there are overt signs of peritonitis. The patient is 72 years old with significant atherosclerotic disease. At exploration, the entire small bowel is necrotic and nonviable. What artery was inadvertently ligated?`,
    q2: ``,
    q3: [],
    option: [
      `Celiac`,
      `Left gastric`,
      `Inferior mesenteric`,
      `Superior mesenteric`,
      `Right gastroepiploic`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [3],
    ansText: `Rationale: <!--<b>d. Superior mesenteric.</b>--> Ligation of the superior mesenteric artery produces ischemia in the bowel distribution above. <b>The superior mesenteric artery can be mistaken for the left renal artery from the anterior approach. Visualizing the artery from a posterior position as it enters the hilum will help to minimize this complication.</b>`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `During resection of a large right renal mass, the main renal artery is identified, ligated, and divided, but the renal vein fails to decompress. What is the most likely explanation for this?`,
    q2: ``,
    q3: [],
    option: [
      `Renal vein tumor thrombus`,
      `Subclinical renal arteriovenous malformation`,
      `Bleeding disorder`,
      `Arterial collateral branch vessels`,
      `Extensive venous collateral obstruction`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [3],
    ansText: `Rationale: <!--<b>d. Arterial collateral branch vessels.</b>--> Failure of the renal vein to decompress after ligation of the main renal artery indicates additional arterial inflow, which may be secondary to a missed lower or upper pole artery or extensive collateral arteries.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `What is most appropriate setting for a thoracoabdominal incision?`,
    q2: ``,
    q3: [],
    option: [
      `Large right upper pole renal mass with tumor thrombus in the renal vein`,
      `5-cm right renal tumor in a hilar location`,
      `Large left lower pole tumor with extensive lymphadenopathy`,
      `Large right renal mass with tumor thrombus to the retrohepatic level`,
      `A 10-cm right lower pole tumor with arteriovenous malformation`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [0],
    ansText: `Rationale: <!--<b>a. Large right upper pole renal mass with tumor thrombus in the renal vein.</b>--> The thoracoabdominal incision is ideal for larger tumors involving the upper pole. The incision is also ideal for managing tumor thrombus extending into the renal vein. The inferior vena cava can be nicely exposed via this approach.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `What is the most common complication associated with performing CPB-DHCA for the removal of large renal cell tumor thrombus?`,
    q2: ``,
    q3: [],
    option: [
      `Pulmonary air emboli`,
      `Intestinal ischemia`,
      `Bleeding and coagulopathy`,
      `Lower extremity tumor emboli`,
      `Tumor emboli`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [2],
    ansText: `Rationale: <!--<b>c. Bleeding and coagulopathy.</b>--> Intraoperatively, the administration of heparin in addition to hypothermia leads to significant coagulopathy. The bleeding from heparin is typically limited to an “ooze” intraoperatively and should not consume time and energy during the operation. After tumor removal, the rewarming process helps to promote coagulation.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `Which of the following is NOT a proposed benefit of renal artery embolization (RAE)?`,
    q2: ``,
    q3: [],
    option: [
      `Shrinkage of an arterialized tumor thrombus to ease surgical removal`,
      `Reduced blood loss`,
      `Facilitation of dissection due to tissue plane edema`,
      `Ability to ligate the renal vein before the renal artery at time of nephrectomy`,
      `Modulation of the immune response`,
      `None of the above`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [5],
    ansText: `Rationale: <!--<b>f. None of the above.</b>--> <b>Proposed benefits of preoperative RAE include shrinkage of an arterialized tumor thrombus to ease surgical removal, reduced blood loss, facilitation of dissection due to tissue plane edema, ability to ligate the renal vein before the renal artery at time of nephrectomy, and modulation of the immune response.</b>`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `What is the most common complication after RAE?`,
    q2: ``,
    q3: [],
    option: [
      `Groin hematoma from puncture site`,
      `Paraplegia from spinal artery occlusion`,
      `Coil migration`,
      `Postinfarction syndrome (pain, nausea, and fever)`,
      `Adrenal insufficiency`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [3],
    ansText: `Rationale: <!--<b>d. Postinfarction syndrome (pain, nausea, and fever).</b>--> <b>The triad of fever, flank pain, and nausea occurs in up to 75% of patients after angioembolization.</b> Fevers can often exceed 39.4°C (103°F) and are best managed with antipyretics.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `What is the most common complication after partial nephrectomy for nonexophytic renal masses?`,
    q2: ``,
    q3: [],
    option: [
      `Hemorrhage`,
      `Renal failure`,
      `Rhabdomyolysis`,
      `Hydronephrosis`,
      `Urinary leak`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [4],
    ansText: `Rationale: <!--<b>e. Urinary leak.</b>--> Partial nephrectomy for nonexophytic masses has an increased risk of entering the collecting system. Even when the collecting system is closed under direct vision, there may still be extravasation of urine that collects in the perirenal space. The use of postoperative surgical drains is imperative in the management of these collections to reduce the risk of infections. In addition, the drain output volume can be observed to determine if collections are resolving. Renal failure is rare unless operating on a solitary kidney or on a patient with marginal renal function. Rhabdomyolysis can be encountered secondary to patient positioning and increased body mass index.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `Ten days after a left partial nephrectomy for a 4.5-cm hilar tumor, there is persistent fluid output from the surgical drain. No ureteral stent was placed at the time of surgery, and a small opening in the collecting system was oversewn. The creatinine concentration of the drain fluid is 34.5 mg/dL, consistent with urine. Despite conservative management, the volume fails to decline. A retrograde pyelogram demonstrates a moderate amount of contrast extravasation, confirming the urinary fistula. What is the most appropriate management at this time?`,
    q2: ``,
    q3: [],
    option: [
      `Immediate reexploration and repair`,
      `Percutaneous nephrostomy tube placement`,
      `Removal of surgical drain`,
      `Internalized ureteral stent placement`,
      `Internalized ureteral stent placement, continued surgical drain monitoring, and placement of Foley catheter`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [4],
    ansText: `Rationale: <!--<b>e. Internalized ureteral stent placement, continued surgical drain monitoring, and placement of Foley catheter.</b>--> <b>Placement of a ureteral stent can promote urine drainage into the bladder. Keeping a Foley catheter in place reduces urine reflux.</b>`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
];
