var quiz = [
    

    {
        q: `At birth the adrenal cortex:`,
        q2: ``,
        q3: [],
        option: [`is completely developed.`, 
        `weighs half as much as the adrenal cortex in adults.`, 
        `is composed of fetal and adult components.`, 
        `will continue to enlarge until 12 months of age.`, 
        `is composed of a single histologic zone.`],
        optionStyleType: `st-lower-alpha`,
        answer: [2],
        ansText:`Rationale: <!--<b>c. Is composed of fetal and adult components.</b>--> The adrenal gland weighs twice as much as the adult gland and begins to atrophy at birth. Development of the gland continues during the first 3 years of life, with the zona reticularis developing last.`, 
        state: `notAnswered`,
        userAnswered: []
    ,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`        ,
        type: `MCSS`},
    {
        q: `Adrenal rest tissue within the testis can mimic testicular cancer in patients with:`,
        q2: ``,
        q3: [],
        option: [`neuroblastoma.`, 
        `pheochromocytoma.`, 
        `primary aldosteronism.`, 
        `congenital adrenal hyperplasia.`, 
        `cryptorchidism.`],
        optionStyleType: `st-lower-alpha`,
        answer: [3],
        ansText:`Rationale: <!--<b>d. Congenital adrenal hyperplasia.</b>--> Testicular adrenal rests must be remembered when evaluating patients with congenital adrenal hyperplasia and testicular masses to avoid an unnecessary orchiectomy.`, 
        state: `notAnswered`,
        userAnswered: []
    ,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`        ,
        type: `MCSS`},
    {
        q: `In cases of renal agenesis, the ipsilateral adrenal gland is typically:`,
        q2: ``,
        q3: [],
        option: [`absent.`, 
        `in the normal location.`, 
        `located at the level of the eighth thoracic vertebral body.`, 
        `located at the level of the first lumbar vertebral body.`, 
        `at a location dependent on the cause of renal agenesis.`],
        optionStyleType: `st-lower-alpha`,
        answer: [1],
        ansText:`Rationale: <!--<b>b. In the normal location.</b>--> Reports of adrenal agenesis are extremely rare.`, 
        state: `notAnswered`,
        userAnswered: []
    ,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`        ,
        type: `MCSS`},
    {
        q: `The most abundant product of the adrenal cortex is:`,
        q2: ``,
        q3: [],
        option: [`mineralocorticoids.`, 
        `glucocorticoids.`, 
        `adrenal androgens.`, 
        `catecholamines.`, 
        `adrenocorticotropic hormone (ACTH).`],
        optionStyleType: `st-lower-alpha`,
        answer: [2],
        ansText:`Rationale: <!--<b>c. Adrenal androgens.</b>--> Although adrenal androgens are arguably the least physiologically significant compounds produced by the adrenals, the glands produce more than 20 mg of these compounds per day. Meanwhile, only 100 to 150 mcg/d of aldosterone and approximately 10 to 20 mg/d of cortisol are produced by the glands.`, 
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `Aldosterone synthase (CYP11B2) is unique to:`,
        q2: ``,
        q3: [],
        option: [`the zona glomerulosa.`, 
        `the zona fasciculata.`, 
        `the zona reticularis.`, 
        `the adrenal medulla.`, 
        `the distal renal tubule.`],
        optionStyleType: `st-lower-alpha`,
        answer: [0],
        ansText:`Rationale: <!--<b>a. The zona glomerulosa.</b>--> <b>The zona glomerulosa cells are the sole source of aldosterone in humans.</b>`, 
        state: `notAnswered`,
        userAnswered: []
    ,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`        ,
        type: `MCSS`},
    {
        q: `The only zone of the adrenal cortex that does not atrophy upon pituitary failure is:`,
        q2: ``,
        q3: [],
        option: [`the zona glomerulosa.`, 
        `the zona fasciculata.`, 
        `the zona reticularis.`, 
        `the adrenal medulla.`, 
        `none of the above.`],
        optionStyleType: `st-lower-alpha`,
        answer: [0],
        ansText:`Rationale: <!--<b>a. The zona glomerulosa.</b>--> <b>Production of aldosterone in the zona glomerulosa is primarily regulated by angiotensin II through the renin-angiotensin-aldosterone system and potassium levels.</b> Elevation of ACTH can also increase aldosterone secretion, but this is a much less potent stimulus. Therefore, in pituitary failure, when ACTH levels fall, the zona glomerulosa fails to atrophy.`, 
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `Presence of the phenylethanolamine-<i>N</i>-methyltransferase (PNMT) enzyme in the adrenal medulla is significant because:`,
        q2: ``,
        q3: [],
        option: [`the enzyme catalyzes degradation of catecholamines to metanephrines.`, 
        `the enzyme catalyzes conversion of catecholamines to vanillylmandelic acid (VMA).`, 
        `the enzyme converts tyrosine to dopamine.`, 
        `the enzyme catalyzes the conversion of norepinephrine to epinephrine.`, 
        `all of the above.`],
        optionStyleType: `st-lower-alpha`,
        answer: [3],
        ansText:`Rationale: <!--<b>d. The enzyme catalyzes the conversion of norepinephrine to epinephrine.</b>--> PNMT is virtually unique to the adrenal medulla (the brain and organ of Zuckerkandl also express the protein). <b>Therefore the presence of PNMT results in epinephrine being virtually a unique product of the adrenal gland.</b>`, 
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `Metanephrines:`,
        q2: ``,
        q3: [],
        option: [`refers to the term used for catecholamines and their byproducts.`, 
        `refers to the combined term for methylated metabolites of norepinephrine (normetanephrine) and epinephrine (metanephrine).`, 
        `refers to precursors to normetanephrines.`, 
        `are rarely helpful in establishing a diagnosis of pheochromocytoma.`, 
        `refers to the term used to describe epinephrine and norepinephrine in the context of pheochromocytoma symptomatology.`],
        optionStyleType: `st-lower-alpha`,
        answer: [1],
        ansText:`Rationale: <!--<b>b. Refers to the combined term for methylated metabolites of norepinephrine (normetanephrine) and epinephrine (metanephrine).</b>--> The enzyme catechol-<b><i>O</i></b>-methyltransferase catalyzes the methylation of norepinephrine to normetanephrine and epinephrine to metanephrine. The term <b><i>normetanephrines</i></b> is not used.`, 
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `The term <i>free metanephrines:</i>`,
        q2: ``,
        q3: [],
        option: [`is interchangeable with the term <i>total metanephrines.</i>`, 
        `is interchangeable with the term <i>fractionated metanephrines.</i>`, 
        `refers to normetanephrine and metanephrine that are not conjugated by a sulfate moiety.`, 
        `refers to normetanephrine and metanephrine that are not bound to albumin.`, 
        `refers to all of the above.`],
        optionStyleType: `st-lower-alpha`,
        answer: [2],
        ansText:`Rationale: <!--<b>c. Refers to normetanephrine and metanephrine that are not conjugated by a sulfate moiety.</b>--> Free metanephrines are unsulfonated normetanephrine and metanephrine, whereas total metanephrines refers to both conjugated and free compounds. The term <b><i>fractionated metanephrines</i></b> refers to laboratory reports that differentiate between metanephrine and normetanephrine concentrations (i.e., instead of only reporting metanephrine concentration, state the concentration of metanephrine and normetanephrine separately).`, 
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `The most common cause of Cushing syndrome (exclusive of exogenous steroid intake) is:`,
        q2: ``,
        q3: [],
        option: [`Cushing disease.`, 
        `a cortisol-producing adrenal adenoma.`, 
        `ectopic ACTH production by a lung malignancy.`, 
        `an adrenal carcinoma.`, 
        `a pheochromocytoma.`],
        optionStyleType: `st-lower-alpha`,
        answer: [0],
        ansText:`Rationale: <!--<b>a. Cushing disease.</b>--> <b>Cushing disease, which describes overproduction of ACTH by the pituitary, accounts for some 70% of endogenous Cushing syndrome.</b>`, 
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `What common urologic ailment can be found in up to 50% of patients with Cushing syndrome?`,
        q2: ``,
        q3: [],
        option: [`Testicular cancer`, 
        `Torsion of the appendix testis`, 
        `Urolithiasis`, 
        `Fournier gangrene`, 
        `Stress urinary incontinence`],
        optionStyleType: `st-lower-alpha`,
        answer: [2],
        ansText:`Rationale: <!--<b>c. Urolithiasis.</b>--> <b>Urolithiasis is seen in up to 50% of patients with Cushing syndrome; therefore stone formers with cushingoid features deserve a hypercortisolemia workup. The astute urologist should also remember that Cushing patients can also exhibit hypogonadal hypogonadism and should have a low threshold for a hypercortisolism workup in men with low testosterone and low gonadotropin levels.</b>`, 
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `How does one perform a low-dose dexamethasone suppression test (LDDST)?`,
        q2: ``,
        q3: [],
        option: [`Admit the patient and measure serum cortisol levels every 6 hours while the patient is on a dexamethasone drip`, 
        `Measure the patient’s saliva cortisol level at midnight`, 
        `Obtain a 24-hour urine cortisol measurement after the patient receives 1 mg of dexamethasone with the first void`, 
        `Have the patient take 10 mg of dexamethasone at 11 <small>pm</small> and measure urinary cortisol the next morning`, 
        `Have the patient take 1 mg of dexamethasone at 11 <small>pm</small> and measure serum cortisol the next morning`],
        optionStyleType: `st-lower-alpha`,
        answer: [4],
        ansText:`Rationale: <!--<b>e. Have the patient take 1 mg of dexamethasone at 11 <small>pm</small> and measure serum cortisol the next morning.</b>--> Despite its intimidating name and rather complex physiologic underpinnings, the test is remarkably simple to administer. Write the patient a prescription for 1 mg of dexamethasone and ask that it be taken by mouth at 11 <small>pm</small>. The next morning, determine the patient’s serum cortisol level. If the cortisol level is 5 mcg/dL or higher (i.e., not suppressed), then the patient likely has hypercortisolemia. Be aware that women on birth control will have false-positive results.`, 
        state: `notAnswered`,
        userAnswered: []
    ,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`        ,
        type: `MCSS`},
    {
        q: `The adrenal surgeon plays no role in the management of Cushing disease.`,
        q2: ``,
        q3: [],
        option: [`True`, 
        `False`],
        optionStyleType: `st-lower-alpha`,
        answer: [1],
        ansText:`Rationale: <!--<b>b. False.</b>--> ACTH-secreting pituitary adenomas are treated with transsphenoidal surgical resection. However, a cure is seen in only 60% to 80% of patients. Among those who are cured, there is approximately 25% relapse. <b>One option for patients who are refractory to neurosurgical treatment is a bilateral adrenalectomy.</b> However, this treatment should not be performed hastily. It is crucial that a thoughtful multidisciplinary decision be made. <b>Up to 30% of patients with Cushing disease who undergo bilateral adrenalectomy may develop Nelson syndrome—progressive growth of the pituitary adenoma causing increased intracranial pressure and compression of the ocular chiasm.</b>`, 
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `What percentage of patients presenting with primary aldosteronism are hypokalemic?`,
        q2: ``,
        q3: [],
        option: [`5% to 12%`, 
        `9% to 37%`, 
        `33% to 50%`, 
        `55% to 75%`, 
        `63% to 91%`],
        optionStyleType: `st-lower-alpha`,
        answer: [1],
        ansText:`Rationale: <!--<b>b. 9% to 37%</b>-->. <b>Although hypokalemia has been classically described as a common finding in primary aldosteronism, only 9% to 37% of newly diagnosed patients are hypokalemic.</b>`, 
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `Elevated aldosterone in patients with familial hyperaldosteronism type I is mediated by:`,
        q2: ``,
        q3: [],
        option: [`renin.`, 
        `sodium.`, 
        `angiotensin II.`, 
        `cortisol.`, 
        `ACTH.`],
        optionStyleType: `st-lower-alpha`,
        answer: [4],
        ansText:`Rationale: <!--<b>e. ACTH.</b>--> Because of the chimeric fusion of the promoter region of 11β-hydroxylase and the coding region of aldosterone synthase, aldosterone production is mediated by ACTH in familial hyperaldosteronism type I.`, 
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `What percentage of patients with a positive screening test will be diagnosed with primary aldosteronism after confirmatory testing?`,
        q2: ``,
        q3: [],
        option: [`2% to 10%`, 
        `20% to 40%`, 
        `30% to 50%`, 
        `50% to 70%`, 
        `75% to 90%`],
        optionStyleType: `st-lower-alpha`,
        answer: [3],
        ansText:`Rationale: <!--<b>d. 50% to 70%.</b>--> Fifty percent to 70% of patients with a positive screening test will be diagnosed with primary aldosteronism following confirmatory testing.`, 
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `What is the most common subtype of primary aldosteronism?`,
        q2: ``,
        q3: [],
        option: [`Idiopathic hyperplasia`, 
        `Aldosterone-producing adenoma`, 
        `Unilateral adrenal hyperplasia`, 
        `Familial hyperaldosteronism type I`, 
        `Adrenocortical carcinoma`],
        optionStyleType: `st-lower-alpha`,
        answer: [0],
        ansText:`Rationale: <!--<b>a. Idiopathic hyperplasia.</b>--> This subtype of primary aldosteronism accounts for approximately 60% of cases.`, 
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `The primary determinant of potentially surgically correctable primary aldosteronism is:`,
        q2: ``,
        q3: [],
        option: [`blood pressure.`, 
        `patient age.`, 
        `demonstration of lateralized aldosterone secretion.`, 
        `response to medical therapy.`, 
        `plasma aldosterone levels.`],
        optionStyleType: `st-lower-alpha`,
        answer: [2],
        ansText:`Rationale: <!--<b>c. Demonstration of lateralized aldosterone secretion.</b>--> Lateralization of aldosterone secretion is the primary determinant of successful surgical treatment of primary aldosteronism.`, 
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `Which class of antihypertensives is contraindicated during the evaluation of primary aldosteronism?`,
        q2: ``,
        q3: [],
        option: [`Calcium channel blockers`, 
        `Alpha blockers`, 
        `Beta blockers`, 
        `Aldosterone-receptor blockers`, 
        `Angiotensin-converting enzyme inhibitors`],
        optionStyleType: `st-lower-alpha`,
        answer: [3],
        ansText:`Rationale: <!--<b>d. Aldosterone-receptor blockers.</b>--> Aldosterone-receptor blockers (spironolactone and eplerenone) are contraindicated during the evaluation of primary aldosteronism. Patients requiring these agents for blood pressure control should be transitioned to other medications during testing for at least 6 weeks.`, 
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `What percentage of patients with incidental adrenal masses prove to have pheochromocytoma?`,
        q2: ``,
        q3: [],
        option: [`1%`, 
        `5%`, 
        `10%`, 
        `25%`, 
        `35%`],
        optionStyleType: `st-lower-alpha`,
        answer: [1],
        ansText:`Rationale: <!--<b>b. 5%.</b>--> Incidentally discovered lesions account for 10% to 25% of all pheochromocytomas.`, 
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `What subtype is assigned to patients with a von Hippel-Lindau <i>(VHL)</i> mutation and a history of pheochromocytoma but no other stigmata of the VHL syndrome?`,
        q2: ``,
        q3: [],
        option: [`Type 1`, 
        `Type 2A`, 
        `Type 2B`, 
        `Type 2C`, 
        `None of the above`],
        optionStyleType: `st-lower-alpha`,
        answer: [3],
        ansText:`Rationale: <!--<b>d. Type 2C.</b>--> Type 1 = VHL patient with no evidence or family history of pheochromocytoma. Type 2 patients are those with evidence or family history of pheochromocytoma. Type 2 is further subdivided. Type 2A = no evidence of renal malignancy and Type 2B = patients with concomitant RCC; type 2C = patients with pheochromocytoma and evidence of a <b><i>VHL</i></b> gene mutation but no other stigmata of VHL.`, 
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `What genetic abnormality is strongly linked with malignant pheochromocytoma?`,
        q2: ``,
        q3: [],
        option: [`<i>RET</i> mutation`, 
        `<i>VHL</i> mutation`, 
        `<i>SDHB</i> mutation`, 
        `<i>SDHD</i> mutation`, 
        `All of the above`],
        optionStyleType: `st-lower-alpha`,
        answer: [2],
        ansText:`Rationale: <!--<b>c. <i>SDHB</i> mutation.</b>--> Patients with multiple endocrine neoplasia (types 2A and 2B) possess a mutation in the <b><i>RET</i></b> proto-oncogene. Approximately half of these patients develop pheochromocytoma, but only about 3% of those with pheochromocytoma exhibit malignant potential. Ten percent to 20% of patients with VHL develop pheochromocytomas, but only 5% of those with pheochromocytoma have malignant disease. Pheochromocytoma among patients with neurofibromatosis type 1 is rare (1%), but malignant disease can be seen in more than 10%. Familial paraganglioma syndrome type 4 (<b><i>SDHB</i></b> mutation) carries the highest risk of malignancy (30% to 50%) among patients with the condition who develop pheochromocytoma (≈20%). Its pathologic cousin, familial paraganglioma syndrome type 1 (<b><i>SDHD</i></b> mutation), carries a negligible risk (&lt;3%) of malignancy among patients who develop pheochromocytomas (≈20%).`, 
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `What test is considered the cornerstone for modern pheochromocytoma biochemical testing?`,
        q2: ``,
        q3: [],
        option: [`Plasma catecholamines`, 
        `Plasma-free metanephrines or fractionated urinary metanephrines`, 
        `VMA testing`, 
        `Fasting morning urinary norepinephrine`, 
        `Adrenal vein sampling for catecholamines`],
        optionStyleType: `st-lower-alpha`,
        answer: [1],
        ansText:`Rationale: <!--<b>b. Plasma-free metanephrines or fractionated urinary metanephrines.</b>--> Methylated metabolites of catecholamines are known as <b><i>metanephrines.</i></b> Therefore normetanephrine (from norepinephrine) and metanephrine (from epinephrine) are collectively known as <b><i>metanephrines.</i></b> The vast majority of methylation occurs within the adrenal medulla or pheochromocytoma, when present. <b>Because this conversion of catecholamines to metanephrines is an uninterrupted process within pheochromocytomas, testing for these compounds is a much more sensitive means of tumor detection than the measurement of catecholamine levels, which may be paroxysmal.</b> Furthermore, measurement of levels of metanephrines is rather specific. Controversy exists regarding whether measurement of plasma-free metanephrines versus fractionated urinary metanephrine should be used as the initial test. The term “free” indicates that the metanephrines being measured are not conjugated by a sulfate moiety, whereas the term “fractionated” simply indicates that normetanephrine and metanephrine levels are reported as separate values.`, 
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `With regard to preoperative pheochromocytoma blockade, β-blockers should be started:`,
        q2: ``,
        q3: [],
        option: [`2 weeks prior to adrenalectomy.`, 
        `at least several days prior to α-blockers.`, 
        `to control tachycardia and arrhythmias that can result upon initiation of α blockade.`, 
        `in conjunction with metyrosine.`, 
        `never, because β-blockers can be lethal in patients with pheochromocytomas.`],
        optionStyleType: `st-lower-alpha`,
        answer: [2],
        ansText:`Rationale: <!--<b>c. To control tachycardia and arrhythmias that can result upon initiation of α blockade.</b>--> <b>Beta-blockade should never be started prior to appropriate α blockade.</b> In the absence of α blockade, β antagonists cause a potentiation of the action of epinephrine on the α<sub>1</sub> receptor, due to blockade of the arteriolar dilation at the β<sub>2</sub> receptor. Nevertheless, β blockade is at times necessary to control reflex tachycardia and arrhythmias that can result from α blockade.`, 
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `Patients with adrenal crisis can exhibit all of the following symptoms EXCEPT:`,
        q2: ``,
        q3: [],
        option: [`hypotension unresponsive to fluid resuscitation.`, 
        `abdominal pain.`, 
        `nausea.`, 
        `fever.`, 
        `priapism.`],
        optionStyleType: `st-lower-alpha`,
        answer: [4],
        ansText:`Rationale: <!--<b>e. Priapism.</b>--> Patients with adrenal crisis are easily misdiagnosed with an acute abdomen. Children can exhibit hypoglycemic seizures. Persistent painful erections are generally not associated with adrenal insufficiency.`, 
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `All of the following lesions can be extra-adrenal EXCEPT:`,
        q2: ``,
        q3: [],
        option: [`myelolipoma.`, 
        `ganglioneuroma.`, 
        `aldosteronoma.`, 
        `pheochromocytoma.`, 
        `oncocytoma.`],
        optionStyleType: `st-lower-alpha`,
        answer: [2],
        ansText:`Rationale: <!--<b>c. Aldosteronoma.</b>--> All listed lesions, other than an aldosterone-producing adenoma, can develop outside of the adrenal gland.`, 
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `A 25-year-old woman is diagnosed with a left adrenal mass, with abundant stippled calcifications, that exhibits imaging features inconsistent with adrenal adenoma. The patient complains of a severe bout of diarrhea that started approximately 8 months ago. Adrenalectomy reveals a ganglioneuroma. At her postoperative visit she is grateful, because her gastrointestinal (GI) complaints vanished following surgery. The substance responsible for diarrhea in this patient is most likely:`,
        q2: ``,
        q3: [],
        option: [`metanephrine.`, 
        `epinephrine.`, 
        `norepinephrine.`, 
        `VMA.`, 
        `vasoactive intestinal polypeptide (VIP).`],
        optionStyleType: `st-lower-alpha`,
        answer: [4],
        ansText:`Rationale: <!--<b>e. Vasoactive intestinal polypeptide (VIP).</b>--> <b>Ganglioneuromas are rare lesions that can arise in the adrenal glands and can secrete VIP, causing profound diarrhea in some patients.</b> Nevertheless, most ganglioneuromas are asymptomatic.`, 
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `What percentage of adrenal cysts is associated with malignancy in surgical series?`,
        q2: ``,
        q3: [],
        option: [`1%`, 
        `3%`, 
        `7%`, 
        `12%`, 
        `15%`],
        optionStyleType: `st-lower-alpha`,
        answer: [2],
        ansText:`Rationale: <!--<b>c. 7%.</b>--> In a meta-analysis accounting for 515 adrenal cysts, the incidence of associated adrenal malignancy was 7%.`, 
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `Adrenocortical carcinoma in children:`,
        q2: ``,
        q3: [],
        option: [`has a more favorable 5-year survival rate compared with adults.`, 
        `uses the same pathologic staging system as adults.`, 
        `is rarely associated with virilization.`, 
        `has equal female and male incidence in children older than 10 years.`, 
        `is frequently metastatic to the central nervous system.`],
        optionStyleType: `st-lower-alpha`,
        answer: [0],
        ansText:`Rationale: <!--<b>a. Has a more favorable 5-year survival rate compared with adults.</b>--> The 5-year survival rate in children with adrenal cortical carcinoma is 54% compared with only 20% to 47% in adults.`, 
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `The most common hormone secreted by adrenocortical carcinoma is:`,
        q2: ``,
        q3: [],
        option: [`aldosterone.`, 
        `testosterone.`, 
        `dehydroepiandrosterone (DHEA).`, 
        `cortisol.`, 
        `androstenedione.`],
        optionStyleType: `st-lower-alpha`,
        answer: [3],
        ansText:`Rationale: <!--<b>d. Cortisol.</b>--> Up to 74% of functional adrenocortical tumors produce excess cortisol.`, 
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `The Weiss criteria for identifying malignant adrenal tumors should be applied with caution in tumors with:`,
        q2: ``,
        q3: [],
        option: [`necrosis.`, 
        `high mitotic index.`, 
        `inferior vena cava (IVC) invasion.`, 
        `liver metastasis.`, 
        `oncocytic features.`],
        optionStyleType: `st-lower-alpha`,
        answer: [4],
        ansText:`Rationale: <!--<b>e. Oncocytic features.</b>--> The Weiss criteria should be applied with caution in pediatric cases and in those with oncocytic features.`, 
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `In patients presenting with metastatic adrenocortical carcinoma, the systemic agent of choice is:`,
        q2: ``,
        q3: [],
        option: [`valrubicin.`, 
        `mitotane alone or in combination with additional cytotoxic agents.`, 
        `gemcitabine and cisplatin.`, 
        `docetaxel (Taxotere).`, 
        `bleomycin, etoposide, and cisplatin.`],
        optionStyleType: `st-lower-alpha`,
        answer: [1],
        ansText:`Rationale: <!--<b>b. Mitotane alone or in combination with additional cytotoxic agents.</b>--> Mitotane has adrenolytic activity and is the first-line agent of choice in patients with metastatic adrenocortical carcinoma. The addition of streptozotocin or etoposide, doxorubicin, and cisplatin to mitotane has been shown to improve progression free survival compared to the use of mitotane alone.`, 
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `In the treatment of pathologically localized adrenocortical carcinoma:`,
        q2: ``,
        q3: [],
        option: [`adjuvant radiation therapy decreases systemic progression.`, 
        `complete surgical resection offers the best chance of cure.`, 
        `increased Ki-67 expression has been associated with improved survival.`, 
        `the tumor’s functional status is an independent predictor of survival.`, 
        `adjuvant therapy with mitotane has no proven benefit.`],
        optionStyleType: `st-lower-alpha`,
        answer: [1],
        ansText:`Rationale: <!--<b>b. Complete surgical resection offers the best chance of cure.</b>--> Adjuvant radiation therapy has demonstrated a decreased rate of local recurrence but has not been shown to improve overall survival. Adjuvant mitotane therapy has been shown to significantly improve recurrence-free and overall survival. A tumor’s functional status has not been consistently demonstrated to impact survival.`, 
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `A 50% false-positive rate can be seen during low-dose dexamethasone suppression testing in:`,
        q2: ``,
        q3: [],
        option: [`men with testicular cancer.`, 
        `women taking oral contraceptives.`, 
        `men with history of orchiopexy.`, 
        `patients with brain malignancy.`, 
        `patients with pheochromocytoma.`],
        optionStyleType: `st-lower-alpha`,
        answer: [1],
        ansText:`Rationale: <!--<b>b. Women taking oral contraceptives.</b>--> The urologist must be aware that the LDDST can yield as high as a 50% false-positive rate in women using oral contraceptives, because the contraceptives increase total (but not bioavailable) cortisol levels by raising the patient’s cortisol-binding globulin concentrations.`, 
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `The adrenal gland should be resected whenever one performs a radical nephrectomy.`,
        q2: ``,
        q3: [],
        option: [`True `, 
        `False`],
        optionStyleType: `st-lower-alpha`,
        answer: [1],
        ansText:`Rationale: <!--<b>b. False.</b>--> The classic description by Robson in the 1950s suggested that radical nephrectomy should include adrenalectomy. Today, however, adrenalectomy is believed to be necessary only for large (T2) upper pole tumors, in cases in which an abnormality in the gland can be seen on preoperative imaging and in cases in which a vein thrombus is present to the level of the adrenal gland.`, 
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `A 55-year-old woman presents for the evaluation of an adrenal mass. Past medical history is significant for severe hypertension requiring four oral medications for adequate blood pressure control. A noncontrast computed tomography (CT) scan of the abdomen reveals a 3-cm left adrenal mass, with an average attenuation of 7 Hounsfield units (HU). Appropriate initial screening should include:`,
        q2: ``,
        q3: [],
        option: [`free-fractionated plasma metanephrines, plasma aldosterone concentration, and plasma renin activity.`, 
        `LDDST and serum catecholamines.`, 
        `late-night salivary cortisol test, plasma aldosterone concentration, plasma renin activity, and plasma free metanephrines.`, 
        `plasma aldosterone concentration and plasma renin activity.`, 
        `24-hour urinary-fractionated metanephrines and serum cortisol concentration.`],
        optionStyleType: `st-lower-alpha`,
        answer: [2],
        ansText:`Rationale: <!--<b>c. Late-night salivary cortisol test, plasma aldosterone concentration, plasma renin activity, and plasma-free metanephrines.</b>--> <b>All patients presenting with an adrenal mass should be evaluated for cortisol and catecholamine hypersecretion.</b> Given the patient’s history of hypertension, evaluation of primary aldosteronism should also be undertaken. Choice c is the best answer.`, 
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `A 62-year-old man presents for postoperative surveillance of renal cell carcinoma. Three years prior, a right nephrectomy was performed for T2N0M0 grade III clear cell renal cell carcinoma. A current abdominal CT scan reveals a 3.5-cm right adrenal mass with an average attenuation of 32 HU prior to contrast administration. A CT washout study is performed, and absolute percent washout is calculated to be 52%. No other suspicious lesions are noted within the chest, abdomen, or pelvis. The next step in management should be:`,
        q2: ``,
        q3: [],
        option: [`observation.`, 
        `adrenalectomy.`, 
        `percutaneous biopsy.`, 
        `initiation of an oral tyrosine kinase inhibitor.`, 
        `assessment of the adrenal tumor’s functional status.`],
        optionStyleType: `st-lower-alpha`,
        answer: [4],
        ansText:`Rationale: <!--<b>e. Assessment of the adrenal tumor’s functional status.</b>--> Although there is a high probability that the adrenal lesion, in this case, represents a recurrence of the patient’s renal cell carcinoma, the functional status of the adrenal mass should be assessed. A pheochromocytoma may always be lurking.`, 
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `A 58-year-old woman has been diagnosed with primary aldosteronism based on appropriate screening and confirmatory testing. A CT scan of the abdomen reveals a 1.0-cm left adrenal mass. Adrenal vein sampling is performed with the results outlined below. Results of adrenal vein sampling:<br/><br/>
   Right cortisol gradient 2.7:1<br/>
   Left cortisol gradient 3.4:1<br/>
   Aldosterone ratio (left:right) 2.5:1<br/>
   The next step in management would be:`,
        q2: ``,
        q3: [],
        option: [`repeat adrenal vein sampling with ACTH stimulation.`, 
        `counseling for left adrenalectomy.`, 
        `counseling for right adrenalectomy.`, 
        `initiation of medical management based on diagnosis of bilateral adrenal hyperplasia.`, 
        `<sup>131</sup>I-iodomethyl-norcholesterol (NP-59) scintigraphy to confirm lateralization.`],
        optionStyleType: `st-lower-alpha`,
        answer: [1],
        ansText:`Rationale: <!--<b>b. Counseling for left adrenalectomy.</b>--> Both the right and left cortisol gradients suggest proper catheter placement for adrenal vein sampling. The aldosterone ratio of 2.5:1 demonstrates left lateralization of autonomous aldosterone secretion, and counseling for left adrenalectomy is appropriate.`, 
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `A 43-year-old woman undergoes an uneventful right laparoscopic adrenalectomy for a 4.5-cm pheochromocytoma. The pathology report states that the lesion is benign and that the margins are negative. On postoperative day 1, she is ready for discharge and wants to know if any additional follow-up is necessary. You inform her that the following is required:`,
        q2: ``,
        q3: [],
        option: [`Consideration of genetic screening`, 
        `Repeat metabolic testing in 2 weeks`, 
        `Cross-sectional imaging in 6 months`, 
        `Biochemical testing in 6 months and then lifelong biochemical testing`, 
        `All of the above`],
        optionStyleType: `st-lower-alpha`,
        answer: [4],
        ansText:`Rationale: <!--<b>e. All of the above.</b>--> The patient is less than 50 years old; therefore genetic screening is recommended. Up to 25% of patients who appear to have sporadic pheochromocytoma on presentation turn out to have germline mutations upon genetic testing. Repeat metabolic testing at 2 weeks after resection is prudent. Most experts recommend additional biochemical testing at 6 months, followed by annual lifelong screening. More than 15% of patients will demonstrate recurrence of pheochromocytoma in the first 10 years after a successful resection. Recurrent disease has been reported more than 15 years following adrenalectomy; therefore lifelong annual biochemical screening is advised. Although cross-sectional imaging is not absolutely required in the face of a negative biochemical workup, most surgeons obtain at least one study at some point during the postoperative follow-up.`, 
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `<b>Pathology</b><br/><br/>A 60-year-old woman is noted to have a 4-cm left adrenal mass on an abdominal CT scan. The endocrine workup is negative, and the mass is excised laparoscopically. The pathology, depicted in <a href="8e2fa7538e7d4beca51939c93bfd6639">Fig. 106.1</a>, is reported as a myolipoma. The next step in management is:`,
        q2: ``,
        q3: [],
        option: [`no additional therapy is indicated because this is a benign tumor.`, 
        `ask the pathologist to grade the tumor.`, 
        `the patient should receive mitotane.`, 
        `the patient should be followed carefully for development of hypertension.`, 
        `a metaiodobenzylguanidine (MIBG) scan should be obtained.`],
        optionStyleType: `st-lower-alpha`,
        answer: [0],
        ansText:`Rationale: <!--<b>a. No additional therapy is indicated because this is a benign tumor.</b>--> This is a benign myolipoma. Notice that it consists of fat mixed with hematopoietic elements.`, 
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `A 45-year-old man has an incidentally discovered 6-cm adrenal mass. Hormonal workup is negative. The mass is laparoscopically removed. The pathology is depicted in <a href="af86dc97af664631bf7f39c581557896">Fig. 106.2</a> and is read as adrenal corticocarcinoma. On separate stains the lesion stains positive for Ki-67. The next step in management is:`,
        q2: ``,
        q3: [],
        option: [`request a pathologic grade.`, 
        `stain for catecholamines.`, 
        `inquire as to whether any fat was observed in the specimen.`, 
        `short-term follow-up with imaging.`, 
        `adjuvant mitotane.`],
        optionStyleType: `st-lower-alpha`,
        answer: [3],
        ansText:`Rationale: <!--<b>d. Short-term follow-up with imaging.</b>--> The marked nuclear variability, increased mitotic figures, and positive staining for Ki-67 all strongly suggest adrenal corticocarcinoma. No further pathologic information is necessary. These patients have a high risk of developing metastatic disease, at which time mitotane would be considered.`, 
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `<b>Imaging</b><br/><br/>See <a href="43dbc7d11da145e48b3adcd0c8df9fc1">Fig. 106.3</a>. A 42-year-old man with lung cancer has this CT scan. The right adrenal nodule has attenuation measurements of 7 HU. The most likely diagnosis is:`,
        q2: ``,
        q3: [],
        option: [`adrenal adenoma.`, 
        `adrenal metastasis.`, 
        `indeterminate adrenal nodule.`, 
        `pheochromocytoma.`, 
        `adrenal myelolipoma.`],
        optionStyleType: `st-lower-alpha`,
        answer: [0],
        ansText:`Rationale: <!--<b>a. Adrenal adenoma.</b>--> Adrenal nodules that are less than 10 HU in density are almost always benign nodules, most often adrenal adenomas.`, 
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`}
    



];
