var quiz = [
  {
    q: `What is the approximate overall objective response rate to interleukin-2 (IL-2) monotherapy in patients with metastatic renal cell carcinoma (RCC)?`,
    q2: ``,
    q3: [],
    option: [`5%`, `10%`, `15%`, `25%`, `35%`],
    optionStyleType: `st-lower-alpha`,
    answer: [2],
    ansText: `Rationale: <!--<b>c. 15%</b>--> Although response rates of 30% or more were reported in early phase 2 studies with IL-2, the overall response rate with this agent was determined to be approximately 15% in larger studies and meta-analysis.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `Which of the following regarding IL-2 therapy for metastatic RCC is TRUE?`,
    q2: ``,
    q3: [],
    option: [
      `IL-2 has demonstrable efficacy in clear cell as well as papillary RCC.`,
      `Randomized studies have demonstrated a survival benefit associated with high-dose IL-2.`,
      `Low-dose subcutaneous and high-dose intravenous IL-2 have comparable efficacy.`,
      `Durable complete responses are seen in a small proportion of patients receiving high-dose IL-2.`,
      `Newer formulations have led to better tolerability of high-dose IL-2.`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [3],
    ansText: `Rationale: <!--<b>d. Durable complete responses are seen in a small proportion of patients receiving high-dose IL-2.</b>--> Complete responses are seen in 7% to 9% of metastatic clear cell RCC patients receiving high-dose IL-2, with the majority of these remaining disease-free for more than 15 years. <b>The efficacy of IL-2 has not been adequately evaluated in patients with non–clear cell histologies, and the use of this agent is largely restricted to clear cell RCC patients.</b> There are no randomized phase 3 studies demonstrating survival benefit with IL-2. While IL-2 use is limited in current clinical practice, it may be considered in well-selected patients because of its ability to provide durable responses in some patients.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `In the Memorial Sloan-Kettering Cancer Center (MSKCC) prognostic scheme for patients with metastatic RCC undergoing therapy with cytokine or chemotherapy, which of the following is NOT a predictor of poor outcome?`,
    q2: ``,
    q3: [],
    option: [
      `Karnofsky performance status greater than 80%`,
      `Elevated lactate dehydrogenase`,
      `Elevated calcium`,
      `Decreased hemoglobin`,
      `Interval from diagnosis to systemic therapy initiation of &lt;1 year`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [0],
    ansText: `Rationale: <!--<b>a. Karnofsky performance status greater than 80%.</b>--> A Karnofsky performance score below 80% was determined to be an adverse prognostic feature and is one of the factors used to predict outcome in the MSKCC prognostic system for patients with metastatic RCC. All other factors listed have been associated with poor outcome.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `A 50-year-old man with a 12-cm left renal renal mass, identified on a CT scan to evaluate abdominal pain, is referred for further management. He is otherwise healthy except for mild fatigue that has developed over the past 3 months; laboratory evaluation reveals a hemoglobin of 9.8 mg/dL and an elevated corrected calcium (10.8 mg/dL) but an otherwise normal chemistry panel and complete blood count. A CT scan of the chest reveals multiple pulmonary nodules consistent with metastatic disease. A biopsy of the renal mass reveals clear cell RCC, Fuhrman grade 3. Which of the following is true with regard to surgical management of this patient?`,
    q2: ``,
    q3: [],
    option: [
      `Cytoreductive nephrectomy should be performed since this patient appears to be otherwise healthy with a good performance status.`,
      `Systemic therapy should be offered to this patient since he is unlikely to benefit from cytoreductive nephrectomy.`,
      `Sytemic therapy should be commenced, with cytoreductive nephrectomy after six cycles of sunitinib.`,
      `The patient has high-risk disease and should commence therapy with everolimus.`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [1],
    ansText: `Rationale: <!--<b>b. Systemic therapy should be offered to this patient since he is unlikely to benefit from cytoreductive nephrectomy.</b>--> This patient has multiple poor prognostic indicators and is not likely to benefit from cytoreductive nephrectomy. While data from a randomized phase 3 study conducted in the era of cytokine therapy, as well as retrospective data in patients receiving therapy with VEGFR-targeted agents, suggest a benefit for cytoreductive nephrectomy in well-selected patients, a recent phase 3 study that randomized newly diagnosed intermediate and poor-risk patients with metastatic clear cell RCC to receive either cytoreductive nephrectomy followed by sunitinib or sunitinib alone (CARMENA) demonstrated no benefit for surgery preceding systemic therapy. There are insufficient data to support routine cytoreductive nephrectomy following suntinib; a study evaluating this approach (SURTIME) was closed early because of slow accrual. Everolimus is not appropriate in the front-line setting.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `Which of the following statements about cytokine therapy for metastatic renal cell carcinoma is TRUE?`,
    q2: ``,
    q3: [],
    option: [
      `Lymphokine-activated killer (LAK) cells augment the efficacy of both interferon-α (IFN-α) and IL-2.`,
      `Randomized trials have demonstrated a significant survival advantage for combined IL-2 and interferon versus either agent given as monotherapy.`,
      `The combination of IL-2 and interferon leads to higher overall response rates than either agent alone.`,
      `The complete response rate with interferon-α monotherapy is 10%.`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [2],
    ansText: `Rationale: <!--<b>c. The combination of IL-2 and interferon leads to higher overall response rates than either agent alone.</b>--> In a randomized phase 3 study, the combination of IL-2 and interferon was associated with a higher response rate than either agent given alone, although this did not translate to an improved long-term outcome (overall survival) in the combination arm. <b>The addition of LAK cells to cytokine therapy does not appear to improve outcome.</b>`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `Which of the following metastatic RCC tumors is most likely to benefit from cytokine therapy?`,
    q2: ``,
    q3: [],
    option: [
      `Papillary carcinoma`,
      `Clear cell carcinoma`,
      `Medullary carcinoma`,
      `Collecting duct carcinoma`,
      `Chromophobe carcinoma`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [1],
    ansText: `Rationale: <!--<b>b. Clear cell carcinoma.</b>--> Clear cell RCC is the histology most likely to respond to cytokine therapy. Although there are inadequate data to make definitive determinations about the activity of cytokines such as IL-2 or interferons in other histologic subtypes, these agents do not appear particularly effective in non–clear cell RCC variants.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `A 58-year-old woman had a nephrectomy 6 years previously for a grade 2 clear cell carcinoma. She was incidentally found to have three left-sided pulmonary nodules (two &lt;1.0 cm, other 2.5 cm). A physical examination is normal, as are all blood chemistries. Computed tomography (CT) of the brain, lungs, abdomen, and pelvis show three pulmonary nodules with no associated hilar or mediastinal adenopathy, and a bone scan is normal. Which of the following is the most appropriate next step in her management?`,
    q2: ``,
    q3: [],
    option: [
      `Therapy with high-dose IL-2`,
      `Biopsy of a pulmonary nodule`,
      `Mediastinoscopy followed by resection of the pulmonary nodules`,
      `Observation`,
      `IFN-α therapy`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [2],
    ansText: `Rationale: <!--<b>c. Mediastinoscopy followed by resection of the pulmonary nodules.</b>--> Patients with metachronous pulmonary nodules related to remote renal tumors may have prolonged survival following resection of the nodule(s) as demonstrated by several retrospective studies.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `The sirolimus analogs temsirolimus and everolimus act primarily on which of the following pathways?`,
    q2: ``,
    q3: [],
    option: [
      `Vascular endothelial growth factor (VEGF)`,
      `Platelet-derived growth factor (PDGF)`,
      `Raf-1`,
      `Mechanistic target of rapamycin (mTOR)`,
      `C-met`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [3],
    ansText: `Rationale: <!--<b>d. Mechanistic target of rapamycin (mTOR).</b>--> mTOR (mammalian target of rapamycin) is the primary target of sirolimus (rapamycin) and its analogs.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `The overall response rate in metastatic clear cell RCC patients receiving front-line therapy nivolumab in combination with ipilimumab is:`,
    q2: ``,
    q3: [],
    option: [
      `15% to 20%.`,
      `30% to 40%.`,
      `60% to 70%.`,
      `less than 10%.`,
      `greater than 70%.`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [1],
    ansText: `Rationale: <!--<b>b. 30% to 40%.</b>--> Objective overall response rates in metastatic clear cell RCC patients treated with nivolumab in combination with ipilimumab was 42% in a randomized phase 3 study comparing this combination with sunitinib.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `A newly diagnosed patient with metastatic clear cell RCC is referred for discussion of systemic therapy options. You determine that he has intermediate risk disease based on standard prognostic criteria and that systemic therapy should be commenced. Which of the following decisions would be supported by data from randomized phase 3 studies?`,
    q2: ``,
    q3: [],
    option: [
      `Sunitinb is the most appropriate choice for initial treatment of this patient`,
      `Initiate therapy with a combination of nivolumab and ipilimumab since it is associated with better response rates and overall survival compared with sunitinib`,
      `Initiate therapy with a combination of pazopanib and nivolumab`,
      `Initiate therapy with a combination of lenvatinib and everolimus`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [1],
    ansText: `Rationale: <!--<b>b. Initiate therapy with a combination of nivolumab and ipilimumab since it is associated with better response rates and overall survival compared with sunitinib.</b>--> Nivolumab, in combination with ipilimumab, was superior to sunitinib in patients with previously untreated metastatic clear cell RCC. Sunitinib is no longer considered the standard of care in these patients. Lenvatinib plus everolimus has not been evaluated in this setting, and the combination of pazopanib and a PD1 inhibitor is deemed to have an unacceptable side effect profile.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `Which of the following agents has been shown to prolong progression-free survival in patients with metastatic clear cell RCC who have progressed on first-line therapy with VEGFR antagonists?`,
    q2: ``,
    q3: [],
    option: [
      `Axitinib`,
      `Bevacizumab + IFN-α`,
      `High-dose IL-2`,
      `Bevacizumab`,
      `Low-dose subcutaneous IL-2`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [0],
    ansText: `Rationale: <!--<b>a. Axitinib.</b>--> In a randomized phase 3 trial, axitinib has been shown to prolong progression free survival compared with sorafenib in patients with metastatic clear cell RCC who have progressed on front-line therapy with either a VEGFR inhibitor or cytokine therapy.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `Randomized trials in patients with previously untreated metastatic clear cell RCC have demonstrated that:`,
    q2: ``,
    q3: [],
    option: [
      `the combination of pembrolizumab and axitinib is associated with better overall survival compared to sunitinib.`,
      `the combination of avelumab in combination with axitinib is associated with better progression free survival compared to sunitinib.`,
      `cabozantinib is associated with a better response rate and progression free survival compared to sunitinib.`,
      `all of the above.`,
      `none of the above.`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [3],
    ansText: `Rationale: <!--<b>d. All of the above.</b>--> In separate randomized phase 3 studies, axitinib, in combination with either pembrolizumab or avelumab, was shown to be superior to sunitinib in previously untreated patients with metastatic clear cell RCC. Cabozantinib was associated with a higher response rate and PFS compared with sunitinib in patients with intermediate or poor-risk prognostic features in a randomized phase 2 study.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `Which of the following agents has been shown in randomized phase 3 trials to prolong survival in “poor-risk” metastatic RCC patients?`,
    q2: ``,
    q3: [],
    option: [`IL-2`, `Sunitinib`, `Sorafenib`, `Temsirolimus`, `IFN-α`],
    optionStyleType: `st-lower-alpha`,
    answer: [3],
    ansText: `Rationale: <!--<b>d. Temsirolimus.</b>--> In a randomized phase 3 study, temsirolimus was associated with better overall survival than IFN-α (median 10.9 vs. 7.3 months) in metastatic RCC patients presenting with three or more predefined factors predictive of poor prognosis.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `Which of the following molecules is not known to be upregulated as a consequence of VHL inactivation in clear cell RCC?`,
    q2: ``,
    q3: [],
    option: [`VEGF`, `PDGF`, `TGF-α`, `Glut-1`, `Raf-1`],
    optionStyleType: `st-lower-alpha`,
    answer: [4],
    ansText: `Rationale: <!--<b>e. Raf-1.</b>--> Raf-1 is a mediator of growth factor signaling pathways but has not been shown to be upregulated in RCC as a consequence of VHL inactivation/HIF upregulation.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `In what proportion of sporadic clear cell tumors are mutations or promoter hypermethylation of the <i>VHL</i> gene seen?`,
    q2: ``,
    q3: [],
    option: [`70% to 90%`, `10% to 20%`, `100%`, `Less than 10%`],
    optionStyleType: `st-lower-alpha`,
    answer: [0],
    ansText: `Rationale: <!--<b>a. 70% to 90%.</b>--> <b>Based on numerous recent studies, it is estimated that VHL inactivation by mutation or promoter hypermethylation occurs in 70% to 90% of clear cell renal tumors.</b>`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `A 47-year-old man presents with multiple metastatic lesions to the lungs and liver 8 months following a radical nephrectomy for a 9-cm papillary type I renal tumor. Which of the following statements about his systemic treatment options is TRUE?`,
    q2: ``,
    q3: [],
    option: [
      `Sunitinib is associated with a 30% to 40% overall RECIST response rate in this subtype of RCC.`,
      `Sorafenib is associated with better long-term outcomes than sunitinib in papillary type I RCC.`,
      `mTOR inhibitors improve survival in patients with metastatic papillary RCC.`,
      `Enrollment in a phase 2 trial evaluating a novel inhibitor of MET activity is a reasonable consideration in this patient.`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [3],
    ansText: `Rationale: <!--<b>d. Enrollment in a phase 2 trial evaluating a novel inhibitor of MET activity is a reasonable consideration in this patient.</b>--> <b>There is no conclusive evidence suggesting that standard agents with activity in clear cell RCC (including VEGF pathway inhibitors and mTOR inhibitors) have a favorable impact on outcome in patients with metastatic papillary RCC, and patients with these tumors are appropriate candidates for rational targeted therapy approaches.</b> The presence of activating c-met mutations in some papillary tumors has kindled interest in the evaluation of <b><i>Met</i></b> pathway antagonists in this patient population.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
];
