var quiz = [
   
    {
        q: `Injury to the genitofemoral nerve will result in which neurologic manifestation?`,
        q2: ``,
        q3: [],
        option: [`Loss of antegrade ejaculation`, 
        `Weakness with hip flexion of the lower extremity`, 
        `Paresthesias of the anterior thigh and lateral scrotal skin`, 
        `Erectile dysfunction`, 
        `None of the above`],
        optionFeedback: [``,
        ``,
        ``,
        ``,
        
        ``],
        optionStyleType: `st-lower-alpha`,
        answer: [2],
        ansText:`Rationale:<!--<b>c. Paresthesias of the anterior thigh and lateral scrotal skin.</b>--> The genitofemoral nerve is a sensorimotor nerve and originates from the upper L1/2 segments of the lumbar plexus. It courses from the lumbar foramina and pierces the psoas major muscles anteriorly, traveling in a caudal direction toward the internal inguinal ring. It functions to provide sensation to the anterior thigh, lateral and anterior aspects of the scrotum in males, and mons pubis in female patients. The genital branch also has motor function, providing the innervation to the cremaster muscles in males. `, 
        state: `notAnswered`,
        userAnswered: [],
	type: `MCSS`        ,
        type: `MCSS`},
    {
        q: `Liposarcomas of the retroperitoneum demonstrate all of the following characteristics EXCEPT:`,
        q2: ``,
        q3: [],
        option: [`nonlipogenic components that are associated with more aggressive behavior`, 
        `overexpression of genes localized to chromosome 12q`, 
        `high frequency of local and regional recurrences`, 
        `excellent responsiveness to anthracycline-based chemotherapies for eradicating distant spread`, 
        `the need for both clinical and immunohistological characterizations to render an accurate diagnosis`],
        optionFeedback: [``,
        ``,
        ``,
        ``,
        
        ``],
        optionStyleType: `st-lower-alpha`,
        answer: [3],
        ansText:`Rationale:<!--<b>d. Excellent responsiveness to anthracycline-based chemotherapies for eradicating distant spread.</b>--> Liposarcomas represent soft tissue malignancies originating from adipocytes. Many tumors demonstrate aberrations of genes localized to chromosome 12q. The diagnosis of a liposarcoma can be difficult, and often requires clinical, radiographic, and histopathologic characterization to render it accurately. Surgical resection is the mainstay of treatment; however, local recurrences occur frequently in up to 40% of cases. Tumors with areas of de-differentiation are associated with more aggressive behavior, and metastatic disease responds poorly to systemic chemotherapy. `, 
        state: `notAnswered`,
        userAnswered: [],
	type: `MCSS`        ,
        type: `MCSS`},
    {
        q: `Which of the following statements is true regarding solitary fibrous tumors?`,
        q2: ``,
        q3: [],
        option: [`Can be associated with a paraneoplastic syndrome called Doege-Potter syndrome, which is characterized by hypoglycemia due to production of insulin-like growth factor`, 
        `Were previously referred to as hemangiopericytomas`, 
        `Are associated with uniform positivity for the <i>NAB2-STAT6</i> gene fusion product`, 
        `Demonstrate radiosensitivity`, 
        `All of the above`],
        optionFeedback: [``,
        ``,
        ``,
        ``,
        
        ``],
        optionStyleType: `st-lower-alpha`,
        answer: [4],
        ansText:`Rationale:<!--<b>e. All of the above.</b>--> All of the statements are true regarding solitary fibrous tumors. Previously referred to as hemangiopericytomas, they have been known to be associated with paraneoplastic syndromes due to endogenous insulinlike growth factor production. They are characteristically associated with the <b><i>NAB2-STAT6</i></b> gene product, which is diagnostic when present. Lastly, radiotherapy has been shown to improve surgical resection rates by decreasing positive margin rates. `, 
        state: `notAnswered`,
        userAnswered: [],
	type: `MCSS`        ,
        type: `MCSS`},
    {
        q: `Among the spectrum of tumors classified as ganglioneuroblastomas, which of the following is true?`,
        q2: ``,
        q3: [],
        option: [`Occur most commonly in elderly adults`, 
        `<i>N-myc</i> gene amplification is a negative prognostic marker`, 
        `Rarely, if ever, metastasize`, 
        `Survival rates exceed 90% at 5 years`, 
        `Unlike pheochromocytomas, metaiodobenzylguanidine (MIBG) scans have little value in staging disease`],
        optionFeedback: [``,
        ``,
        ``,
        ``,
        
        ``],
        optionStyleType: `st-lower-alpha`,
        answer: [1],
        ansText:`Rationale: <!--<b>b. <i>N-myc</i> gene amplification is a negative prognostic marker.</b>--> Ganglioneuroblastomas are lethal tumors. While occurring most commonly in the first decade of life, they are associated with high rates of metastases. <b><i>N-myc</i></b> gene amplification has been recognized as a negative prognostic marker for disease progression. The 5-year survival rates are poor. MIBG scans and MRI have proven useful for staging of disease at time of diagnosis.`, 
        state: `notAnswered`,
        userAnswered: [],
	type: `MCSS`        ,
        type: `MCSS`},
    {
        q: `In the setting of a retroperitoneal cancer of unknown primary origin, all of the following are correct EXCEPT:`,
        q2: ``,
        q3: [],
        option: [`PET-CT (positron emission tomography-computed tomography) offers little value in the initial workup of these patients`, 
        `Isochromosome i(12)p may identify patients with retroperitoneal primary germ cell tumors when assessing young, male patients`, 
        `Adenocarcinomas are the most common histologic subtype identified`, 
        `Represents up to 5% of new cancer cases worldwide`, 
        `Histology-specific chemotherapy is the mainstay of treatment`],
        optionFeedback: [``,
        ``,
        ``,
        ``,
        
        ``],
        optionStyleType: `st-lower-alpha`,
        answer: [0],
        ansText:`Rationale:<!--<b>a. PET-CT (positron emission tomography-computed tomography) offers little value in the initial workup of these patients.</b>--> Tumors of unknown primary origin represent a difficult challenge. Initial diagnostics of value include the use of PET-CT and histologic characterization via biopsy to provide as much information to classify these entities. In young patients, the presence of i(12)p is pathognomonic for germ cell tumors, which are treated with platinum-based chemotherapy. Overall, this entity represents 5% of all new cancer cases in the world, with adenocarcinomas comprising 50% of these tumors. `, 
        state: `notAnswered`,
        userAnswered: [],
	type: `MCSS`        ,
        type: `MCSS`},
    {
        q: `The incidence of perioperative acute respiratory distress syndrome (ARDS) in patients with prior receipt of bleomycin can be minimized by:`,
        q2: ``,
        q3: [],
        option: [`avoidance of the Trendelenburg position`, 
        `keeping the FiO<sub>2</sub> as low as possible`, 
        `short operating time`, 
        `minimization of intra- and perioperative fluid resuscitation`, 
        `both b and d`],
        optionFeedback: [``,
        ``,
        ``,
        ``,
        
        ``],
        optionStyleType: `st-lower-alpha`,
        answer: [4],
        ansText:`Rationale:<!--<b>e. Both b and d.</b>--> Bleomycin-induced pulmonary toxicity is a well-described side effect of the drug, seen most commonly with a greater number of cumulative doses. Minimizing risk factors associated with acute respiratory toxicity and failure remains critical to the management of postchemotherapy patients in the perioperative period. Specifically, minimizing the amount of FiO<sub>2</sub> received as well as reducing perioperative fluid resuscitation have both been associated with a lower risk of acute exacerbation and decompensation. `, 
        state: `notAnswered`,
        userAnswered: [],
        type: `MCSS`},
    {
        q: `Where is the cisterna chylae located?`,
        q2: ``,
        q3: [],
        option: [`Immediately posterolateral to the inferior vena cava (IVC) just superior to the right renal artery`, 
        `Immediately posterolateral to the aorta just superior to the left renal artery`, 
        `Immediately posterolateral to the aorta just inferior to the left renal artery`, 
        `Immediately posteromedial to the aorta just superior to the right renal artery.`, 
        `In the retrocrural region`],
        optionFeedback: [``,
        ``,
        ``,
        ``,
        
        ``],
        optionStyleType: `st-lower-alpha`,
        answer: [3],
        ansText:`Rationale:<!--<b>d. Immediately posteromedial to the aorta just superior to the right renal artery.</b>--> The cisterna chylae is most commonly identified in the posterior and medial position relative to the aorta cephalad in location to the right renal artery. `, 
        state: `notAnswered`,
        userAnswered: [],
    
        type: `MCSS`},
    {
        q: `When performing a full bilateral template retroperitoneal lymph node dissection (RPLND) for a mixed germ cell tumor in the retroperitoneum, the main packets are:`,
        q2: ``,
        q3: [],
        option: [`paracaval, suprahilar, interaortocaval, ipsilateral gonadal vein`, 
        `retrocrural, interaortocaval, para-aortic`, 
        `paracaval, interaortocaval, para-aortic, interiliac`, 
        `paracaval, interaortocaval, para-aortic, ipsilateral gonadal vessels`, 
        `retrocrural, paracaval, para-aortic, interiliac`],
        optionFeedback: [``,
        ``,
        ``,
        ``,
        
        ``],
        optionStyleType: `st-lower-alpha`,
        answer: [3],
        ansText:`Rationale: <!--<b>d. Paracaval, interaortocaval, para-aortic, ipsilateral gonadal vessels.</b>--> After a series of modifications made to the original template for RPLND, exclusion of the suprahilar and interiliac regions were incorporated to reduce surgical morbidity without any significant risk for relapse in select patients. As such, the current standard for a bilateral template would include the para-aortic, paracaval, and interaortocaval lymph node packets. Additionally, the ipsilateral gonadal vessels should be removed concomitantly.`, 
        state: `notAnswered`,
        userAnswered: [],
    
        type: `MCSS`},
    {
        q: `How many lumbar arteries need to be identified and divided to gain total vascular control of the abdominal aorta between the renal vessels and aortic bifurcation?`,
        q2: ``,
        q3: [],
        option: [`2`, 
        `3`, 
        `6`, 
        `8`, 
        `9`],
        optionFeedback: [``,
        ``,
        ``,
        ``,
        
        ``],
        optionStyleType: `st-lower-alpha`,
        answer: [2],
        ansText:`Rationale:<!--<b>c. 6.</b>--> Within the retroperitoneum, the infrahilar/infrarenal aorta has paired branches that extend posterolateral off of the aorta at regular intervals. Three such paired branches exist with few exceptions, for a total number of six lumbar artery branches that require prospective identification and division to achieve total vascular control of the aorta. `, 
        state: `notAnswered`,
        userAnswered: [],
    
        type: `MCSS`},
]