var quiz = [
  {
    q: `Nephron-sparing surgery (partial nephrectomy):`,
    q2: ``,
    q3: [],
    option: [
      `is the predominant treatment modality used in the United States for the management of small renal masses.`,
      `offers equivalent cancer-specific and overall survival compared with radical nephrectomy.`,
      `when performed laparoscopically, it is associated with fewer complications than radiofrequency ablation (RFA) or cryoablation.`,
      `offers metastatic recurrence-free survival and cancer-specific survival similar to that of radiofrequency ablation and cryoablation.`,
      `was not impacted by the advent of hand-assisted laparoscopic radical nephrectomy.`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [3],
    ansText: `Rationale: <!--<b>d. Offers metastatic recurrence-free survival and cancer-specific survival similar to that of radiofrequency ablation and cryoablation.</b>--> <b>Nephron-sparing surgery is considered the gold-standard treatment for small renal masses but is underused in the United States.</b> Partial nephrectomy offers equivalent oncologic outcomes when compared with radical nephrectomy and demonstrates superior renal functional preservation. Laparoscopic partial nephrectomy offers excellent cancer-specific end points but is technically challenging and is associated with significant complications. Cryoablation and radiofrequency ablation are associated with significantly fewer complications than laparoscopic partial nephrectomy. <b>There is no significant difference in metastatic recurrence-free survival between extirpative and ablative treatments. Cancer-specific survival (CSS) following RFA is comparable to laparoscopic partial nephrectomy. CSS is comparable between open partial nephrectomy and both RFA and cryoablation.</b> Preliminary studies suggest that the technical ease and minimal morbidity of hand-assisted laparoscopic nephrectomy may ultimately lead to fewer nephron-sparing procedures.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `With regard to deciding on a particular ablation modality, which of the following should be considered?`,
    q2: ``,
    q3: [],
    option: [
      `RFA is associated with less postoperative hemorrhage than cryoablation.`,
      `Both RFA and cryoablation are subject to “heat sink.`,
      `The American Urological Association (AUA) guidelines currently recommend consideration of ablation for primary treatment of T1a renal tumors, even for younger, healthier patients, with the understanding that recurrence rates may be higher and salvage procedure more difficult.`,
      `All of the above.`,
      `Both a and b are true.`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [4],
    ansText: ` `,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `The critical treatment temperature threshold during cryoablation at which irreparable cell damage is achieved is:`,
    q2: ``,
    q3: [],
    option: [`0°C.`, `−60°C.`, `−20°C.`, `−40°C.`, `−19.4°C.`],
    optionStyleType: `st-lower-alpha`,
    answer: [3],
    ansText: `Rationale: <!--<b>d. −40°C.</b>--> Experimental evidence suggests that irreversible cellular damage is achieved in normal renal parenchyma at −19.4°C. However, tumor cells require lower treatment temperatures to achieve uniform cellular necrosis. The recommended treatment temperature during renal cryosurgery is −40°C.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `Critical parameters for successful renal cryosurgery include:`,
    q2: ``,
    q3: [],
    option: [
      `a double freeze-thaw cycle.`,
      `achieving a critical target temperature.`,
      `treatment under real-time image guidance.`,
      `treatment to beyond 1 cm of the targeted lesion.`,
      `all of the above.`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [4],
    ansText: `Rationale: <!--<b>e. All of the above.</b>--> Animal studies have demonstrated that a single freeze-thaw cycle is inferior to a double freeze-thaw cycle with respect to adequacy of tissue ablation and local tumor control. As mentioned, complete cellular necrosis is consistently achieved at a targeted temperature of −40°C. Campbell and colleagues (1998)<a href="[remark:6844f0222cce4175a514cc9739b0f523]"><sup>a</sup></a> demonstrated that the aforementioned threshold temperature of −40°C was achieved 3.1 mm inside the edge of the evolving ice ball. <b>To guarantee that the tumor is completely ablated with a margin of normal tissue, the ice ball is generally carried 5 to 10 mm beyond the edge of the tumor when viewed under real-time imaging.</b>`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `Compared with renal cryoablation, the primary disadvantage of RFA is:`,
    q2: ``,
    q3: [],
    option: [
      `higher risk of hemorrhage following RFA.`,
      `inability to use RFA laparoscopically.`,
      `inability to monitor treatment under image guidance.`,
      `inferior cancer-specific survival.`,
      `none of the above.`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [2],
    ansText: `Rationale: <!--<b>c. Inability to monitor treatment under image guidance.</b>--> The primary disadvantage when employing RFA for the treatment of renal lesions is difficulty in monitoring treatment under real-time image guidance. The risk of hemorrhage is higher with cryoablation. RFA may be employed laparoscopically, percutaneously, or openly. <b>Cancer-specific survival is equivalent between RFA and cryoablation.</b>`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `Recent meta-analyses have demonstrated:`,
    q2: ``,
    q3: [],
    option: [
      `higher local recurrence rates with ablative technologies when compared with partial or radical nephrectomy.`,
      `no evidence for the superiority of one ablation technology versus the other with regard to oncologic outcomes or complications.`,
      `a lack of uniformity regarding evaluation, patient selection, treatment, and follow-up of patients undergoing renal tumor ablation.`,
      `fewer complications with renal tumor ablation compared with extirpative treatments.`,
      `all of the above.`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [4],
    ansText: `Rationale: <!--<b>e. All of the above.</b>--> Three recent meta-analyses evaluated outcomes following partial nephrectomy, radical nephrectomy, cryoablation, and RFA for the treatment of small renal masses. <b>Both RFA and cryoablation demonstrated higher local recurrence rates when compared with partial or radical nephrectomy.</b> However, the majority of published studies on cryoablation and RFA have enrolled small numbers of patients and used disparate operative and follow-up protocols. The pathology is either not obtained or is difficult to interpret, and the reliability of radiographic imaging remains unknown. <b>Although the aggregate duration of follow-up is too short to derive irrefutable conclusions, treatment outcomes with cryoablation and RFA appear comparable.</b> In general, complications occur with equal or less frequency with tumor ablation when compared with partial or radical nephrectomy.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `The most important technique to increase the size of RF lesions is:`,
    q2: ``,
    q3: [],
    option: [
      `using higher RF currents.`,
      `applying RF currents faster to achieve better heating.`,
      `clamping hilar vessels.`,
      `reducing impedance by improving current conductivity using “dry” RFA.`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [3],
    ansText: `Rationale: <!--<b>d. Reducing impedance by improving current conductivity.</b>--> The electrically conductive agent facilitates the delivery of energy from the electrode to surrounding tissue, rendering it a much larger, “virtual” electrode. Impedance remains lower, and larger volumes are ablated. One technique to accomplish this is to employ saline-cooled electrodes, which reduce charring at the tip of the electrode and thereby reduce impedance.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `Compared to radiofrequency ablation and cryoablation, newer technologies may have which of the following advantages?`,
    q2: ``,
    q3: [],
    option: [
      `High-intensity focused ultrasound (HIFU) requires no percutaneous needle placement, yet results in equivalent oncologic outcomes.`,
      `Irreversible electroporation (IRE) has a potential advantage for treating central tumors due to its nonthermal mechanism that preserves tissue scaffolding, large blood vessels, and urothelium.`,
      `Microwave ablation works through a similar mechanism to RFA and is therefore similarly limited by tissue charring and heat sink.`,
      `Stereotactic body radiation therapy (SBRT) is highly effective at treating renal cell carcinoma but is limited due to mobility of the kidney with respiration.`,
      `Routine use of selective embolization has consistently demonstrated improved outcomes for ablation of all renal mass, regardless of location.`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [1],
    ansText: `Rationale: <!--<b>b. Irreversible electroporation (IRE) has a potential advantage for treating central tumors due to its nonthermal mechanism that preserves tissue scaffolding, large blood vessels, and urothelium.</b>--> IRE is produced through a series of electrical pulses delivered by a single (bipolar) or multiple (monopolar) electrodes. With appropriate modulation it is able to ablate a substantial and reproducible amount of tissue by increasing cell membrane permeability that ultimately leads to cell death. Because it is nonthermal, studies have confirmed its ability to spare the urothelium and larger blood vessels.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `Following tumor ablation, the most reliable method of documenting treatment success is:`,
    q2: ``,
    q3: [],
    option: [
      `biopsy of the treatment area with hematoxylin and eosin (H&amp;E) staining.`,
      `biopsy of the treatment area with reduced nicotinamide adenine dinucleotide (NADH) diaphorase staining.`,
      `follow-up computed tomography (CT) or magnetic resonance imaging (MRI) with contrast that demonstrates complete loss of contrast enhancement and stable or decreased size of the treated area.`,
      `follow-up CT or MRI without contrast that demonstrates a decrease in size of the treated area.`,
      `all of the above.`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [2],
    ansText: `Rationale: <!--<b>c. Follow-up computed tomography (CT) or magnetic resonance imaging (MRI) with contrast that demonstrates complete loss of contrast enhancement and stable or decreased size of the treated area.</b>--> Complete loss of contrast enhancement on follow-up CT or MRI has been considered a sign of complete tissue destruction. <b>Following cryoablation, the treated area demonstrates a decrease in size of approximately 50% in the year following treatment. Following RFA, the treated area may not demonstrate a decrease in size. Any increase in size following treatment should be viewed as an ominous sign, and intervention should be directed accordingly.</b> Postablative biopsy, although helpful, yields ambiguous results following RFA. Its use and interpretation remain controversial.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
];
