var quiz = [
    

    {
        q: `Which of the following statements regarding the anatomy of the right adrenal gland is TRUE?`,
        q2: ``,
        q3: [],
        option: [`Its vein drains into the right renal vein.`, 
        `It is usually located on the upper pole and lateral border of the right kidney.`, 
        `The medulla is innervated by preganglionic sympathetic nerve fibers.`, 
        `It is usually located more caudal than the left adrenal gland and is closely related to the diaphragm.`, 
        `The right adrenal gland only receives arterial supply from the right renal artery.`],
        optionStyleType: `st-lower-alpha`,
        answer: [2],
        ansText:`Rationale: <!--<b>c. The medulla is innervated by preganglionic sympathetic nerve fibers.</b>--> <b>The right adrenal vein drains directly into the inferior vena cava and derives its arterial supply through the superior, middle, and inferior adrenal arteries from the inferior phrenic artery, the abdominal aorta, and the renal artery, respectively.</b> It is usually more cephalad than the left adrenal gland and is located at the upper pole and medial border of the right kidney. It is closely related to the diaphragm posteriorly, and thus extra care should be taken during surgical dissection, especially of large tumors.`, 
        state: `notAnswered`,
        userAnswered: []
    ,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`        ,
        type: `MCSS`},
    {
        q: `What is the risk of malignancy in an incidentaloma of more than 6 cm?`,
        q2: ``,
        q3: [],
        option: [`2%`, 
        `6%`, 
        `10%`, 
        `25%`, 
        `50%`],
        optionStyleType: `st-lower-alpha`,
        answer: [3],
        ansText:`Rationale: <!--<b>d. 25%.</b>--> <b>Of adrenal lesions larger than 6 cm, 25% are adrenal cortical carcinomas, and these larger lesions should be resected. Risk of malignancy in lesions smaller than 4 cm is 2%.</b> Approximately 6% of adrenal lesions between 4 and 6 cm are malignant, and surgical resection can be considered in appropriate individuals.`, 
        state: `notAnswered`,
        userAnswered: []
    ,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`        ,
        type: `MCSS`},
    {
        q: `Absolute contraindications to laparoscopic adrenalectomy include:`,
        q2: ``,
        q3: [],
        option: [`significant abdominal adhesions.`, 
        `adrenal mass greater than 12 cm in size.`, 
        `invasive adrenal cortical carcinoma with thrombus in the inferior vena cava.`, 
        `malignant pheochromocytoma.`, 
        `all of the above.`],
        optionStyleType: `st-lower-alpha`,
        answer: [2],
        ansText:`Rationale: <!--<b>c. Invasive adrenal cortical carcinoma with thrombus in the inferior vena cava.</b>--> Previous abdominal surgeries may result in dense intra-abdominal adhesions that may make surgery difficult. With improved laparoscopic techniques and equipment, large adrenal tumors are no longer considered absolute contraindication to the laparoscopic approach. Literature had described the feasibility of resecting large adrenal tumors laparoscopically. However, the risk of open conversion is greater in such large tumors. Invasion of adrenal cortical carcinoma into surrounding structures will make laparoscopic resection very difficult, and extension of tumor into the inferior vena cava should be considered an absolute contraindication to the laparoscopic approach.`, 
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `Which of the following statements regarding the perioperative management of pheochromocytoma is FALSE?`,
        q2: ``,
        q3: [],
        option: [`Preoperative sympatholytic therapy with α-adrenergic blockers should be started for at least 2 weeks before surgery.`, 
        `Phenoxybenzamine may lead to tachycardia, and β-adrenergic blockade should be started before phenoxybenzamine administration.`, 
        `Vasopressins and aggressive fluid infusion are often necessary after ligation of the adrenal vein or excision of a pheochromocytoma.`, 
        `The adrenal vein should be ligated early during surgical excision of a pheochromocytoma.`, 
        `Intravenous drugs with short half-lives are preferred versus longer-acting drugs for controlling blood pressure fluctuations during surgical excision of a pheochromocytoma.`],
        optionStyleType: `st-lower-alpha`,
        answer: [1],
        ansText:`Rationale: <!--<b>b. Phenoxybenzamine may lead to tachycardia, and β-adrenergic blockade should be started before phenoxybenzamine administration.</b>--> Preoperative sympatholytic therapy with α-adrenergic blockers for at least 2 weeks before surgery helps in both hemodynamic and glucose control and should be continued until the day of surgery. Phenoxybenzamine, being nonselective, may lead to tachycardia, and β-adrenergic blockade may be necessary. Because phenoxybenzamine is an irreversible noncompetitive α-adrenergic blocker, prolonged hypotension in the immediate postoperative period and central nervous system effects such as somnolence may be expected. <b>β-Adrenergic blockade, if needed, must be given with caution in patients with myocardial depression and started only after phenoxybenzamine therapy.</b> Aggressive fluid management with volume repletion is necessary after removal of pheochromocytoma or ligation of the adrenal vein, because hypotension can occur as a result of sudden loss of tonic vasoconstriction. The adrenal vein should be ligated early during the resection of pheochromocytoma to avoid the systemic release of catecholamines during manipulation of the adrenal gland. Lastly, drugs with rapid onset and short half-lives, such as nitroprusside, phentolamine, nitroglycerin, or nicardipine, are generally preferred in intraoperative hypertensive episodes, because hypotension can occur after ligation of the adrenal vein or excision of the pheochromocytoma.`, 
        state: `notAnswered`,
        userAnswered: []
    ,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`        ,
        type: `MCSS`},
    {
        q: `The lumbodorsal posterior approach to open adrenalectomy is not ideal in any of the following circumstances EXCEPT:`,
        q2: ``,
        q3: [],
        option: [`large adrenal tumors.`, 
        `bilateral adrenal hyperplasia.`, 
        `bilateral small adrenocortical carcinoma.`, 
        `patients with ventilatory difficulties.`, 
        `b and c.`],
        optionStyleType: `st-lower-alpha`,
        answer: [1],
        ansText:`Rationale: <!--<b>b. Bilateral adrenal hyperplasia.</b>--> Although the posterior approach is the most direct route to the adrenal glands and no major muscles are divided, surgical exposure is limited. In addition, access to the adrenal vein and great vessels is more difficult, which may be problematic in event of excessive intraoperative bleeding. Thus this approach is not ideal in large adrenal tumors or adrenocortical carcinoma. <b>The prone position will also make ventilating the patient difficult. However, this approach provides ready access to both adrenal glands through two separate incisions and is ideal for bilateral adrenal hyperplasia or small benign adrenal tumors.</b>`, 
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `In bilateral adrenalectomy, steroids replacement should be started:`,
        q2: ``,
        q3: [],
        option: [`on induction of general anesthesia.`, 
        `after ligation of the right adrenal vein.`, 
        `after excision of both adrenal glands.`, 
        `during closing of the abdominal incision.`, 
        `in the recovery room after surgery.`],
        optionStyleType: `st-lower-alpha`,
        answer: [2],
        ansText:`Rationale: <!--<b>c. After excision of both adrenal glands.</b>--> It is generally recommended that steroid replacement be started as soon as both adrenal glands are excised to minimize acute adrenal insufficiency. Patients can present with back/abdominal pain, nausea, vomiting, diarrhea, hypotension, fever, hypoglycemia, and hyperkalemia.`, 
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `A 57-year-old male with no significant medical problems presented with a right-sided abdominal mass. Computed tomographic (CT) imaging showed an 18-cm right adrenal tumor with invasion of the upper pole of the right kidney and tumor thrombus extending into the retrohepatic inferior vena cava. Which is the best surgical approach for this patient?`,
        q2: ``,
        q3: [],
        option: [`Open lumbodorsal posterior approach`, 
        `Open anterior transabdominal approach`, 
        `Open thoracoabdominal approach`, 
        `Laparoscopic transperitoneal approach`, 
        `Robot-assisted laparoscopic transperitoneal approach`],
        optionStyleType: `st-lower-alpha`,
        answer: [2],
        ansText:`Rationale: <!--<b>c. Open thoracoabdominal approach.</b>--> Surgical exposure is limited with the lumbodorsal posterior approach, and this approach should not be used for large tumors or adrenocortical carcinoma. Although the open anterior transabdominal approach using the subcostal or chevron incision gives a fairly good and adequate exposure for most cases, this approach might not be adequate in this case in view of the involvement of the retrohepatic inferior vena cava. The open thoracoabdominal approach is generally reserved for large and invasive tumors with extensive involvement of surrounding structures or vena cava that cannot be safely removed via the anterior transabdominal approach. The thoracoabdominal approach is particularly useful in right-sided tumors, because the liver and inferior vena cava can limit exposure, whereas on the left side, the spleen and pancreas can generally be elevated to provide adequate exposure. Minimally invasive approaches such as conventional laparoscopic or robot-assisted laparoscopic approach are usually contraindicated in such large tumors with extensive involvement of the great vessels.`, 
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `Which of the following is NOT a possible approach to the left adrenal gland in the anterior transabdominal approach?`,
        q2: ``,
        q3: [],
        option: [`Through the gastrocolic ligament`, 
        `Through the lienorenal ligament`, 
        `Through the transverse mesocolon`, 
        `Through the lesser omentum`, 
        `All the above are possible approaches`],
        optionStyleType: `st-lower-alpha`,
        answer: [4],
        ansText:`Rationale: <!--<b>e. All the above are possible approaches.</b>-->`, 
        state: `notAnswered`,
        userAnswered: []
    ,
	type: `MCSS`        ,
        type: `MCSS`},
    {
        q: `Which of the following statements on partial adrenalectomy is FALSE?`,
        q2: ``,
        q3: [],
        option: [`The adrenal gland is usually exposed but not mobilized.`, 
        `The arterial supply of the adrenal gland can be ligated without devascularizing the gland.`, 
        `It is generally safe to ligate the main adrenal vein if the adrenal gland is not mobilized.`, 
        `A repeat partial adrenalectomy is indicated in a small local recurrence of an adrenal mass previously treated with partial adrenalectomy.`, 
        `Partial adrenalectomy may be indicated in multiple endocrine neoplasia type IIA.`],
        optionStyleType: `st-lower-alpha`,
        answer: [3],
        ansText:`Rationale: <!--<b>d. A repeat partial adrenalectomy is indicated in a small local recurrence of an adrenal mass previously treated with partial adrenalectomy.</b>--> The arterial supply of the adrenal gland forms a plexus circumferentially around the gland and can usually be taken without fear of devascularizing the adrenal cortex, and the gland will remain viable as long it remains attached to the kidney or to an area of unmobilized connective tissue. <b>The venous system drains into a central adrenal vein, and the main adrenal vein can be taken as long as the remnant adrenal gland remains in situ without mobilization. However, it would be prudent to preserve the main adrenal vein as long as it is safe and adequate margins can be obtained.</b> A local recurrence after a previous partial adrenalectomy, regardless of size of recurrence, is an absolute contraindication to a repeat partial adrenalectomy. Multiple endocrine neoplasia type IIA is associated with adrenal tumors, and therefore partial adrenalectomy may be indicated in these patients.`, 
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `During a right adrenalectomy, severe bleeding is encountered. The possible causes include all of the following EXCEPT:`,
        q2: ``,
        q3: [],
        option: [`right adrenal vein avulsion at the origin on the inferior vena cava.`, 
        `avulsion of the right hepatic vein branch.`, 
        `disruption of the adrenal capsule.`, 
        `inadvertent ligation of the upper pole renal artery.`, 
        `all of the above.`],
        optionStyleType: `st-lower-alpha`,
        answer: [3],
        ansText:`Rationale: <!--<b>d. Inadvertent ligation of the upper pole renal artery.</b>--> All of the vascular injuries noted cause bleeding except ligation of an upper pole renal artery. Ligation of this artery would result in upper pole devascularization, not hemorrhage.`, 
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `Which of the following is not an advantage of retroperitoneal adrenalectomy when compared to transperitoneal approach?`,
        q2: ``,
        q3: [],
        option: [`Reducing the risk of injury to bowels and abdominal organs`, 
        `Larger working space and clearer anatomical landmarks`, 
        `Lower incidence of hemodynamic and respiratory morbidities`, 
        `Usually the approach of choice in patients with multiple previous abdominal surgeries`, 
        `All of the above are advantages of the retroperitoneal approach over the transperitoneal approach`],
        optionStyleType: `st-lower-alpha`,
        answer: [1],
        ansText:`Rationale: <!--<b>b. Larger working space and clearer anatomical landmarks.</b>--> The main advantage of the retroperitoneal approach is that entry into the peritoneum is avoided, and thus complications such as visceral and bowel injuries are minimized. In the absence of pneumoperitoneum, hemodynamic and respiratory morbidities are also reduced. In addition, dense intraperitoneal adhesions arising from previous surgery or inflammation are averted by operating in the retroperitoneum. The main disadvantage of the retroperitoneal approach is the limited working space that makes dissection of large tumors difficult. Finally, the lack of anatomic landmarks and the abundant retroperitoneal adipose tissues may pose a significant challenge to surgeons inexperienced with the retroperitoneum. The main advantage of the lateral approach over the posterior approach is the ease of conversion into the transperitoneal approach should difficulties be encountered. In contrast, the prone retroperitoneal approach allows for bilateral adrenalectomy without patient repositioning.`, 
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `With regard to intraoperative complications during adrenalectomy, which of the following is NOT the appropriate management?`,
        q2: ``,
        q3: [],
        option: [`In an event when splenectomy is performed for uncontrollable splenic hemorrhage, pneumococcus, <i>Haemophilus influenzae</i> type B (Hib), and meningococcus vaccinations should be given intraoperatively or immediately postoperatively.`, 
        `Postoperative drainage high in triglycerides and amylase is indicative of pancreas injury. Management consists of bowel rest with parenteral nutrition.`, 
        `Small diaphragmatic injuries if recognized intraoperatively should be repaired and a chest drain inserted.`, 
        `Inadvertent ligation of the superior mesenteric vein should be managed with revascularization and bowel resection.`, 
        `All of the above are appropriate management.`],
        optionStyleType: `st-lower-alpha`,
        answer: [0],
        ansText:`Rationale: <!--<b>a. In an event when splenectomy is performed for uncontrollable splenic hemorrhage, pneumococcus, <i>Haemophilus influenzae</i> type B (Hib), and meningococcus vaccinations should be given intraoperatively or immediately postoperatively.</b>--> Vaccinations should be given only after patients have recovered adequately from their surgeries (usually just before discharge from hospital) and not intraoperatively or immediately postoperatively. Diaphragmatic injuries, even if small, should be repaired due to the risk of abdominal content herniation and bowel strangulations. Ligation of the superior mesenteric vein is potentially fatal due to large segments of bowel congestion. Management must include revascularization and resection of unhealthy segment of bowels if necessary.`, 
        state: `notAnswered`,
        userAnswered: []
    ,
	type: `MCSS`        ,
        type: `MCSS`}
    



];
