var quiz = [
  {
    q: `<!--1. -->What is the general pattern of voiding dysfunction secondary to neurologic lesions above the level of the brainstem?`,
    q2: ``,
    q3: [],
    option: [
      `<!--a. -->Involuntary bladder contractions, smooth sphincter dyssynergia, striated sphincter synergy`,
      `<!--b. -->Involuntary bladder contractions, smooth sphincter synergy, striated sphincter synergy`,
      `<!--c. -->Involuntary bladder contractions, smooth sphincter synergy, striated sphincter dyssynergia`,
      ` <!--d. -->Detrusor hypocontractility, smooth sphincter synergy, striated sphincter synergy`,
      `<!--e. -->Detrusor areflexia, smooth sphincter synergy, striated sphincter synergy `,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [1],
    ansText: `Rationale: Neurologic lesions above the level of the brainstem that affect micturition generally result in involuntary bladder contractions with smooth and striated sphincter synergy. Sensation and voluntary striated sphincter function are generally preserved. Areflexia may occur either initially or as a permanent dysfunction.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `<!--2. -->What is the general pattern of voiding dysfunction that results from complete lesions of the spinal cord above the level of S2 after recovery from spinal shock?`,
    q2: ``,
    q3: [],
    option: [
      `<!--a. -->Involuntary bladder contractions, smooth sphincter dyssynergia, striated sphincter synergy`,
      `<!--b. -->Involuntary bladder contractions, smooth sphincter synergy, striated sphincter synergy`,
      `<!--c. -->Involuntary bladder contractions, smooth sphincter synergy, striated sphincter dyssynergia`,
      `<!--d. -->Detrusor hypocontractility, smooth sphincter synergy, striated sphincter synergy `,
      `<!--e. -->Detrusor areflexia, smooth sphincter synergy, striated sphincter synergy `,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [2],
    ansText: `Rationale: Patients with complete lesions of the spinal cord between spinal cord levels T6 and S2, after they recover from spinal shock, generally exhibit involuntary bladder contractions without sensation of the contraction, smooth sphincter synergy, but striated sphincter dyssynergia. Those with lesions above T6 may experience, in addition, smooth sphincter dyssynergia and autonomic hyperreflexia.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `<!--3. -->Which of the following is the most common long-term expression of lower urinary tract dysfunction after a cerebrovascular accident (CVA)?`,
    q2: ``,
    q3: [],
    option: [
      `<!--a. -->Detrusor areflexia`,
      `<!--b. -->Lack of sensation of filling`,
      `<!--c. -->Impaired bladder contractility`,
      `<!--d. -->Striated sphincter dyssynergia `,
      `<!--e. -->Detrusor overactivity `,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [4],
    ansText: `Rationale: The most common long-term expression of lower urinary tract dysfunction after a CVA is detrusor overactivity. Sensation is variable but is classically described as generally intact, and thus the patient has urgency and frequency with detrusor overactivity.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `<!--4. -->A 65-year-old man who has sustained a stroke but is otherwise in good health has symptoms of hesitancy, straining to void, urgency, and frequency. The optimal next step in management is:`,
    q2: ``,
    q3: [],
    option: [
      `<!--a. -->anticholinergic therapy.`,
      `<!--b. -->transurethral resection of the prostate (TURP).`,
      `<!--c. -->transurethral incision of the bladder neck and prostate.`,
      `<!--d. -->clean intermittent catheterization. `,
      `<!--e. -->full urodynamic evaluation. `,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [4],
    ansText: `Rationale: Poor flow rates and high residual urine volumes in a male with pre-CVA symptoms of prostatism generally indicate prostatic obstruction, but a full urodynamic evaluation is advisable before committing a patient to mechanical outlet reduction primarily to exclude detrusor hyperactivity with impaired contractility as a cause of symptoms.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `<!--5. -->The most common pattern of micturition in children and adults who have cerebral palsy (CP) and no other complicating neurologic condition is:`,
    q2: ``,
    q3: [],
    option: [
      `<!--a. -->abnormal filling/storage because of detrusor overactivity; normal emptying.`,
      `<!--b. -->normal filling/storage; normal emptying.`,
      `<!--c. -->normal filling/storage; abnormal emptying because of smooth sphincter dyssynergia.`,
      `<!--d. -->normal filling/storage; abnormal emptying because of striated sphincter dyssynergia. `,
      `<!--e. -->abnormal filling/storage because of detrusor overactivity; abnormal emptying because of striated sphincter dyssynergia. `,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [1],
    ansText: `Rationale: Most children and adults with only CP have urinary control and what seems to be normal filling/storage and normal emptying. The actual incidence of voiding dysfunction is somewhat vague because the few available series report findings predominantly in those who present with voiding symptoms. One study estimated that a third or more of children with CP are so affected. When an adult with CP presents with an acute or subacute change in voiding status, however, it is most likely unrelated to CP.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `<!--6. -->The most common urodynamic findings in individuals with CP who do exhibit lower urinary tract dysfunction are:`,
    q2: ``,
    q3: [],
    option: [
      `<!--a. -->detrusor areflexia, coordinated sphincters.`,
      `<!--b. -->detrusor overactivity, smooth sphincter dyssynergia, striated sphincter dyssynergia.`,
      `<!--c. -->detrusor overactivity, smooth sphincter synergy, striated sphincter dyssynergia.`,
      `<!--d. -->decreased detrusor compliance, coordinated sphincters. `,
      `<!--e. -->detrusor overactivity, coordinated sphincters. `,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [4],
    ansText: `Rationale: In those individuals with CP who exhibit significant dysfunction, the type of damage that one would suspect from the most common urodynamic abnormalities seems to be localized above the brainstem. This is commonly reflected by detrusor overactivity and coordinated sphincters. Spinal cord damage can occur, however, and probably accounts for those individuals with CP who seem to have evidence of striated sphincter dyssynergia.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `<!--7. -->The most common urodynamic abnormality found in patients with voiding dysfunction secondary to Parkinson disease (PD) is:`,
    q2: ``,
    q3: [],
    option: [
      `<!--a. -->impaired sensation during filling.`,
      `<!--b. -->striated sphincter dyssynergia.`,
      `<!--c. -->striated sphincter bradykinesia.`,
      `<!--d. -->detrusor overactivity. `,
      `<!--e. -->impaired detrusor contractility. `,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [3],
    ansText: `Rationale: The most common urodynamic finding is detrusor overactivity. The pathophysiology of detrusor overactivity most widely proposed is that the basal ganglia normally have an inhibitory effect on the micturition reflex, which is abolished by the cell loss in the substantia nigra.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `<!--8. -->Urodynamic findings that may distinguish multiple system atrophy (MSA) from PD include:`,
    q2: ``,
    q3: [],
    option: [
      `<!--a. -->sphincteric insufficiency`,
      `<!--b. -->detrusor overactivity`,
      `<!--c. -->detrusor areflexia`,
      `<!--d. -->lack of sensation during filling `,
      `<!--e. -->decreased bladder capacity `,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [0],
    ansText: `Rationale: Patients with MSA usually have sphincteric insufficiency, while patients with PD rarely have external sphincter acontractility. For this reason, a bladder outlet treatment is rarely indicated in MSA patients. Decreased compliance may also occur in MSA.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `<!--9. -->The most common urodynamic findings in individuals with multiple sclerosis (MS) who have lower urinary tract dysfunction are:`,
    q2: ``,
    q3: [],
    option: [
      `<!--a. -->detrusor overactivity, smooth sphincter dyssynergia`,
      `<!--b. -->detrusor overactivity, smooth sphincter synergia`,
      `<!--c. -->detrusor areflexia, impaired filling sensation`,
      `<!--d. -->detrusor areflexia, striated sphincter dyssynergia `,
      `<!--e. -->normal filling and storage `,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [1],
    ansText: `Rationale: In terms of urodynamic findings, detrusor overactivity is the most common abnormality detected and, in general, the smooth sphincter is synergic and sensation is intact. There can also be coexisting striated sphincter dyssynergia and/or impaired detrusor contractility.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `<!--10. -->The incidence of upper urinary tract deterioration is greatest in which of the following?`,
    q2: ``,
    q3: [],
    option: [`MS`, `MSA`, `PD`, `Spinal cord injury (SCI) `, `Diabetes `],
    optionStyleType: `st-lower-alpha`,
    answer: [3],
    ansText: `Rationale: Progressive neurologic diseases cause upper tract damage much less commonly than SCI, even when associated with severe disability and spasticity.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `<!--11. -->All of the following are risk factors for upper urinary tract deterioration in a patient with a suprasacral SCI except:`,
    q2: ``,
    q3: [],
    option: [
      `<!--a. -->high-pressure storage.`,
      `<!--b. -->high detrusor leak-point pressure.`,
      `<!--c. -->chronic bladder overdistention.`,
      `<!--d. -->high abdominal leak-point pressure. `,
      `<!--e. -->vesicoureteral reflux with infection. `,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [3],
    ansText: `Rationale: As with all patients with neurologic impairment, a careful initial evaluation and periodic follow-up evaluation must be performed to identify and correct the following risk factors and potential complications: bladder overdistention, high-pressure storage, high detrusor leak-point pressure, vesicoureteral reflux, stone formation (lower and upper tracts), and complicating infection, especially in association with reflux.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `<!--12. -->In spinal shock, findings generally include all of the following EXCEPT:`,
    q2: ``,
    q3: [],
    option: [
      `<!--a. -->acontractile bladder.`,
      `<!--b. -->areflexic bladder.`,
      `<!--c. -->open bladder neck.`,
      `<!--d. -->absent guarding reflex. `,
      `<!--e. -->maximal urethral closure pressure above normal. `,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [2],
    ansText: `Rationale: Spinal shock includes a suppression of autonomic activity and somatic activity, and the bladder is acontractile and areflexic. Radiologically, the bladder has a smooth contour with no evidence of trabeculation. The bladder neck is generally closed and competent unless there has been prior surgery or, in some cases, thoracolumbar and presumably sympathetic injury. The smooth sphincter mechanism seems to be functional. Some EMG activity may be recorded from the striated sphincter, and the maximum urethral closure pressure is lower than normal but still maintained at the level of the external sphincter zone; however, the normal guarding reflex is absent and there is no voluntary control.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `<!--13. -->The presence of true striated sphincter dyssynergia implies a neurologic lesion between the:`,
    q2: ``,
    q3: [],
    option: [
      `<!--a. -->pons and the sacral spinal cord.`,
      `<!--b. -->cerebral cortex and the pons.`,
      `<!--c. -->cervical and the sacral spinal cord.`,
      `<!--d. -->sacral spinal cord and the striated sphincter. `,
      `<!--e. -->cauda equina and the striated sphincter. `,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [0],
    ansText: `Rationale: A diagnosis of striated sphincter dyssynergia implies a neurologic lesion that interrupts the neural axis between the pontine-mesencephalic reticular formation and the sacral spinal cord.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `<!--14. -->Which of the following is least characteristic as a finding in autonomic hyperreflexia?`,
    q2: ``,
    q3: [],
    option: [
      `<!--a. -->Headache before bladder contraction`,
      `<!--b. -->Hypertension`,
      `<!--c. -->Flushing above the level of the lesion`,
      `<!--d. -->Tachycardia `,
      `<!--e. -->Sweating above the level of the lesion `,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [3],
    ansText: `Rationale: Symptomatically, autonomic hyperreflexia is a syndrome of exaggerated sympathetic activity in response to stimuli below the level of the lesion. The symptoms are pounding headache, hypertension, and flushing of the face and body above the level of the lesion with sweating. Bradycardia is a usual accompaniment, and an arrhythmia may be present.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `<!--15. -->A patient with a history of cervical SCI is undergoing urodynamic evaluation and currently has 350 cc infused volume. He begins to complain of headache and develops hypertension and bradycardia. What is the next step?`,
    q2: ``,
    q3: [],
    option: [
      `<!--a. -->Continue filling and reassure him`,
      `<!--b. -->Administer an antibiotic`,
      `<!--c. -->Give terazosin 5 mg immediately`,
      `<!--d. -->Empty his bladder `,
      `<!--e. -->Apply 2% nitroglycerin paste `,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [3],
    ansText: `Rationale: Immediate treatment of autonomic dysreflexia is to remove the cause, which in this case is bladder distension. The current recommendation for the acute pharmacologic treatment of autonomic dysreflexia is placement of 2% nitroglycerin paste above the level of the lesion for rapid blood pressure reduction secondary to vasodilation after removal of the stimulus.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `<!--16. -->The sacral spinal cord terminates in the cauda equina at approximately the spinal column level of:`,
    q2: ``,
    q3: [],
    option: [
      `<!--a. -->T10.`,
      `<!--b. -->L1.`,
      `<!--b. -->L2.`,
      ` <!--b. -->L3.`,
      ` <!--b. -->S1.`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [2],
    ansText: `Rationale: Spinal column (bone) segments are numbered by the vertebral level, and these have a different relationship to the spinal cord segmental level at different locations. The sacral spinal cord begins at approximately spinal column level T12-L1. The spinal cord terminates in the cauda equina at approximately the spinal column level of L2.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `<!--17. -->Patients who have voiding dysfunction secondary to lumbar disk disease most commonly present with which of the following symptoms and urodynamic findings?`,
    q2: ``,
    q3: [],
    option: [
      `<!--a. -->Retention; involuntary bladder contractions`,
      `<!--b. -->Incontinence; involuntary bladder contractions`,
      `<!--c. -->Retention; decreased bladder compliance`,
      `<!--d. -->Difficulty voiding; normal bladder compliance `,
      `<!--e. -->Incontinence; normal bladder compliance `,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [3],
    ansText: `Rationale: A study reported on findings in 114 patients with lumbar disk protrusion who were prospectively studied. The authors found detrusor areflexia in 31 (27.2%) and normal detrusor activity in the remaining 83. All 31 patients with detrusor areflexia reported difficulty voiding with straining. Patients with voiding dysfunction generally present with these symptoms or in urinary retention. The most consistent urodynamic finding is that of a normally compliant areflexic bladder associated with normal innervation or findings of incomplete denervation of the perineal floor musculature.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `<!--18. -->The clinical picture of cauda equina syndrome (CES) varies widely. Which of the following is typically not seen with CES?`,
    q2: ``,
    q3: [],
    option: [
      `<!--a. -->Urinary incontinence`,
      `<!--b. -->Loss of bowel control`,
      `<!--c. -->Perineal sensory loss`,
      `<!--d. -->Sexual dysfunction `,
      `<!--e. -->Limb spasticity `,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [4],
    ansText: `Rationale: CES is characterized by perineal sensory loss with loss of voluntary control of both anal and urethral sphincter and of sexual dysfunction. CES is a lower motor neuron disease, so would not expect limb spasticity which is a characteristic of upper motor neuron disease.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `<!--19. -->The combination that best describes the type of permanent voiding dysfunction that can occur after radical pelvic surgery is:`,
    q2: ``,
    q3: [],
    option: [
      `<!--a. -->stress incontinence; detrusor areflexia.`,
      `<!--b. -->urgency incontinence; detrusor overactivity.`,
      `<!--c. -->reflex incontinence; detrusor areflexia.`,
      `<!--d. -->urgency incontinence; detrusor overactivity. `,
      `<!--e. -->stress incontinence; detrusor overactivity. `,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [0],
    ansText: `Rationale: When permanent voiding dysfunction occurs after radical pelvic surgery, the pattern is generally one of a failure of voluntary bladder contraction, or impaired bladder contractility, with obstruction by what seems urodynamically to be residual fixed striated sphincter tone, which is not subject to voluntarily induced relaxation. Often, the smooth sphincter area is open and nonfunctional. Decreased compliance is common in these patients, and this, with the “obstruction” caused by fixed residual striated sphincter tone, results in both storage and emptying failure. These patients often experience leaking across the distal sphincter area and, in addition, are unable to empty the bladder because although intravesical pressure may be increased, there is nothing that approximates a true bladder contraction. The patient often presents with urinary incontinence that is characteristically most manifest with increases in intra-abdominal pressure. This is usually most obvious in females because the prostatic bulk in males often masks an equivalent deficit in urethral closure function. Alternatively, patients may present with variable degrees of urinary retention.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `<!--20. -->What is optimal management for a 65-year-old man who has had a first occurrence of urinary retention after radical pelvic surgery?`,
    q2: ``,
    q3: [],
    option: [
      `<!--a. -->Anticholinergic therapy`,
      `<!--b. -->Clean intermittent catheterization`,
      `<!--c. -->TURP`,
      `<!--d. -->External sphincterotomy `,
      `<!--e. -->Bethanechol chloride `,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [1],
    ansText: `Rationale: The temptation to perform a prostatectomy should be avoided unless a clear demonstration of outlet obstruction at this level is possible. Otherwise, prostatectomy simply decreases urethral sphincter function and thereby may result in the occurrence or worsening of sphincteric urinary incontinence. Most of these dysfunctions will be transient, and the temptation to “do something” other than perform clean intermittent catheterization initially after surgery in these patients, especially in those with little or no preexisting history of voiding dysfunction, cannot be too strongly discouraged.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `<!--21. -->The urodynamic parameter most likely to distinguish urinary retention due to prostatic obstruction from urinary retention due to “classic diabetic cystopathy” is:`,
    q2: ``,
    q3: [],
    option: [
      `uroflow.`,
      `<!--b. -->residual urine volume.`,
      `<!--c. -->bladder compliance.`,
      `<!--d. -->vesical pressure. `,
      `<!--e. -->detrusor pressure. `,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [4],
    ansText: `Rationale: Detrusor contractility is classically described as being decreased in the end-stage diabetic bladder. Current evidence points to both sensory and motor neuropathy as being involved in the pathogenesis, the motor aspect per se contributing to the impaired detrusor contractility. The typically described classic urodynamic findings include impaired bladder sensation, increased cystometric capacity, decreased bladder contractility, impaired uroflow, and, later, increased residual urine volume. The main differential diagnosis, at least in men, is generally bladder outlet obstruction because both conditions commonly produce a low flow rate. Pressure/flow urodynamic studies easily differentiate the two.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `<!--22. -->Detrusor-striated sphincter dyssynergia is least expected to occur with which of the following conditions?`,
    q2: ``,
    q3: [],
    option: [
      `MS`,
      `SCI`,
      `Stroke`,
      `Autonomic hyperreflexia `,
      `Transverse myelitis `,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [2],
    ansText: `Rationale: True detrusor sphincter dyssynergia should exist only in patients who have an abnormality in pathways between the sacral spinal cord and the brainstem pontine micturition center, generally due to neurologic injury or disease.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `<!--23. -->Treatment options for DSD can include all of the following except:`,
    q2: ``,
    q3: [],
    option: [
      `<!--a. -->intermittent catheterization`,
      `<!--b. -->injection of onabotulinum toxin into the sphincter`,
      `<!--c. -->sacral neuromodulation`,
      `sphincterotomy `,
      `<!--e. -->urinary diversion `,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [2],
    ansText: `Rationale: Therapy for DSD is designed to either eliminate or significantly minimize the abnormal sphincter activity or to bypass the sphincter itself.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `<!--24. -->Differentiation of bladder neck obstruction from dysfunctional voiding is most easily and accurately made by:`,
    q2: ``,
    q3: [],
    option: [
      `<!--a. -->filling cystometry.`,
      `<!--b. -->voiding cystometry.`,
      `<!--c. -->cystourethroscopy.`,
      ` <!--d. -->flowmetry and residual urine determination.`,
      `<!--e. -->video-urodynamics study. `,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [4],
    ansText: `Rationale: Objective evidence of outlet obstruction in these patients is easily obtainable by urodynamic study. Once obstruction is diagnosed, it can be localized at the level of the bladder neck by video-urodynamics study, cystourethrography during a bladder contraction, or micturitional urethral profilometry.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `<!--25. -->According to the AUA consensus statement on non-neurogenic urinary retention,`,
    q2: ``,
    q3: [],
    option: [
      `<!--a. -->non-neurogenic urinary retention is defined as a postvoid residual &gt; 300 mL on a single occasion.`,
      `low-risk and high-risk patients should be distinguished and patients with high-risk features should be treated.`,
      `<!--c. -->low-risk patients include those with hydronephrosis, recurrent UTIs, and chronic kidney disease.`,
      `<!--d. -->if long-term catheterization is needed, then an indwelling urethral catheter is preferred. `,
      `<!--e. -->patients with low-risk urinary retention do not need to be followed long term. `,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [1],
    ansText: `Rationale: Following a thorough history and physical examination, if a high-risk variable is present, such as hydronephrosis, hydroureter, chronic kidney disease, recurrent UTI, or urinary incontinence with skin sequalae, then treatment is recommended.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `<!--26. -->Which of the following is not a typical finding in a patient with Fowler syndrome?`,
    q2: ``,
    q3: [],
    option: [
      `<!--a. -->Female younger than 30 years`,
      `<!--b. -->Unable to void for a day or more with no urgency`,
      `<!--c. -->Bladder capacity of less than 1 L`,
      `<!--d. -->Increasing lower abdominal discomfort `,
      `<!--e. -->Electromyographic (EMG) abnormalities `,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [2],
    ansText: `Rationale: The criteria for Fowler syndrome include a bladder capacity of more than 1 L with no sensation of urgency.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `<!--27. -->Which of the following with the typical history is the most specific study to make the diagnosis of Fowler syndrome?`,
    q2: ``,
    q3: [],
    option: [
      `<!--a. -->Striated sphincter needle EMG recording`,
      `<!--b. -->Striated sphincter patch EMG recording`,
      `<!--c. -->Neurologic examination`,
      `<!--d. -->Spinal magnetic resonance imaging (MRI) examination `,
      `<!--e. -->Detrusor pressure/urinary flow recording `,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [0],
    ansText: `Rationale: <b><i>Fowler syndrome</i></b> refers particularly to a syndrome of urinary retention in young women in the absence of overt neurologic disease. The typical history is that of a woman younger than 30 years, who has found herself unable to void during the preceding day but with no sensation of urgency. MRI studies of the brain and the entire spinal cord are normal. On concentric needle electrode examination of the striated muscle of the urethral sphincter, however, Fowler and colleagues described a unique EMG abnormality. This abnormal activity, localized to the urethral sphincter, consists of a type of activity that would be expected to cause inappropriate contraction of the muscle. Sphincter activity consists of two components: complex repetitive discharges and decelerating bursts. This abnormal activity impairs sphincter relaxation.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `<!--28. -->Which of the following has proved to be successful in treating the urologic manifestations of Fowler syndrome?`,
    q2: ``,
    q3: [],
    option: [
      `<!--a. -->Estrogen therapy`,
      `<!--b. -->Progesterone therapy`,
      `<!--c. -->Baclofen therapy`,
      `<!--d. -->Botulinum toxin injection therapy `,
      `<!--e. -->Neuromodulation `,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [4],
    ansText: `Rationale: Fowler reports that efforts to treat this condition by hormonal manipulation, pharmacologic therapy, or injections of botulinum toxin have been unsuccessful. This condition is highly responsive to neuromodulation, even in women who have had retention for many months or years.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `<!--29. -->A 65-year-old female presents with a history of pelvic radiation for treatment of cervical cancer 30 years ago. What urodynamic findings would you expect?`,
    q2: ``,
    q3: [],
    option: [
      `<!--a. -->Reduced bladder capacity`,
      `<!--b. -->Increased postvoid residual`,
      `<!--c. -->Normal compliance`,
      `<!--d. -->Decreased flow rate `,
      `<!--e. -->Bladder outlet obstruction `,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [0],
    ansText: `Rationale: Radiation effects on the bladder evolve over time and may be progressive. Most commonly urodynamics will demonstrate reduced bladder capacity. Patients may also have reduced compliance and detrusor overactivity.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `<!--30. -->In the medical management of neurogenic detrusor overactivity (NDO), which of the following is least likely to worsen constipation?`,
    q2: ``,
    q3: [],
    option: [
      `Oxybutynin`,
      `Mirabegron`,
      `Tolterodine`,
      `Tamsulosin `,
      `Trospium `,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [1],
    ansText: `Rationale: Mirabegron is a β3 agonist that has shown efficacy in the treatment of NDO. Mirabegron avoids the anticholinergic effects of constipation and dry mouth, but can have cardiovascular side effects including mild elevations in blood pressure and small, dose-dependent increases in heart rate.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `<!--31. -->Increasing numbers of individuals with myelomeningocele are surviving into adulthood and older age. Critical for stability of function is recognition that the spinal cord may be tethered. Regarding the tethered spinal cord,`,
    q2: ``,
    q3: [],
    option: [
      `<!--a. -->the level of tethering as demonstrated by MRI is predictive of findings on urodynamics.`,
      `<!--b. -->urodynamics often shows improvement after detethering.`,
      `<!--c. -->tethered cord syndrome is not usually associated with bowel or leg dysfunction.`,
      `<!--d. -->there are no predictors for social continence after detethering. `,
      `<!--e. -->the symptomatic tethered cord, associated with worsening ambulation, can be managed non-operatively. `,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [1],
    ansText: `Rationale: Despite efforts at improved radiographic visualization of the spinal cord, imaging does not correlate with physical findings or connote overall responsiveness to surgical intervention because detethering remains a critical aspect of management and control of tethered cord. Cord tethering affects both bowel and leg function, as well as bladder function. Urodynamics is improved by detethering, and this parallels functional improvement in those individuals who have undergone the surgical procedure. The successful management of the tethered cord remains a critical aspect of long-term care in the myelomeningocele population.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `<!--32. -->Guillain-Barré syndrome is a demyelinating disorder. It is:`,
    q2: ``,
    q3: [],
    option: [
      `<!--a. -->not usually identified as a clinical entity having sporadic clinical manifestation.`,
      `<!--b. -->not caused by an acute inflammatory disorder.`,
      `<!--c. -->not usually associated with an antecedent acute infectious illness.`,
      `<!--d. -->associated with lower urinary tract function, usually in less than 5% of cases. `,
      `<!--e. -->associated with voiding dysfunction, which is usually reversible `,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [4],
    ansText: `Rationale: Guillain-Barré syndrome is an acute inflammatory disorder thought to be due to some inflammatory process because most patients do have evidence of acute inflammatory conditions before development of the syndrome. The syndrome is characterized by a distinct presenting scenario (ascending paralysis). Lower urinary tract dysfunction has been reported in as few as 25% to as many as 80% of cases and is usually reversible with resolution of the disorder.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `<!--33. -->In a patient with voiding dysfunction secondary to myelomeningocele who has slightly decreased compliance, detrusor areflexia, and low-pressure moderate to severe vesicoureteral reflux, which of the following urodynamic changes would be most likely after ureteral reimplantation alone?`,
    q2: ``,
    q3: [],
    option: [
      `<!--a. -->Compliance increased`,
      `<!--b. -->Voiding pressure decreased`,
      `<!--c. -->Valsalva leak-point pressure decreased`,
      `<!--d. -->Maximum urethral closure pressure decreased `,
      `<!--e. -->Maximum bladder capacity decreased `,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [4],
    ansText: `Rationale: One must remember the potential artifact that significant reflux can introduce into urodynamic studies. Measured bladder capacity may be more, and measured pressures at given inflow volumes may be less, than those after reflux correction. The apparent significance of detrusor overactivity may thus be underestimated.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `<!--34. -->Which of the following is true about patients with myelomeningocele?`,
    q2: ``,
    q3: [],
    option: [
      `<!--a. -->Myelomeningoceles most commonly occur at the cervical level.`,
      `<!--b. -->The level of the lesion correlates poorly with urodynamic findings.`,
      `<!--c. -->Neurologic examination of patients with myelomeningocele accurately predicts urodynamic findings.`,
      `<!--d. -->Patients rarely have lower urinary tract dysfunction. `,
      `<!--e. -->Life-long follow-up is not necessary. `,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [1],
    ansText: `Rationale: Myelomeningocele lesions most commonly occur in the lumbosacral region. The incidence of lower urinary tract dysfunction is estimated to be about 90%, and patients with lower urinary tract dysfunction require life-long follow-up with a urologist.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `<!--35. -->Findings consistent with herpes virus infection may include all of the following except:`,
    q2: ``,
    q3: [],
    option: [
      `<!--a. -->vesicles in the bladder on cystoscopy`,
      `<!--b. -->urinary retention`,
      `<!--c. -->detrusor overactivity`,
      `<!--d. -->rash on the palms and soles of feet `,
      `<!--e. -->fever, malaise `,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [3],
    ansText: `Rationale: Invasion of the sacral dorsal root ganglia and posterior nerve roots with herpes zoster virus may produce urinary retention, detrusor areflexia, or detrusor overactivity. A rash on the palms and soles is associated with syphilis.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
];
