var quiz = [
  {
    q: `<!--1. -->Which definition or definitions appear in the current International Continence Society (ICS) terminology (2002)?`,
    q2: ``,
    q3: [],
    option: [
      `<!--a. -->Detrusor hyperreflexia`,
      `<!--b. -->Overactive bladder`,
      `<!--c. -->Idiopathic detrusor overactivity`,
      `<!--d. -->Detrusor instability `,
      ` <!--e. -->b and c`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [4],
    ansText: `Rationale: Detrusor hyperreflexia has been replaced by neurogenic detrusor overactivity. The concept of tone is poorly understood; hence, the term <b><i>detrusor instability</i></b> is not recommended.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `<!--2. -->Which symptoms are included in overactive bladder syndrome (OAB)?`,
    q2: ``,
    q3: [],
    option: [
      `Dysuria`,
      `Straining`,
      `Urgency incontinence`,
      `Bladder pain `,
      `Stress incontinence `,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [2],
    ansText: `Rationale: Urgency incontinence is experienced by a large proportion of patients with OAB.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `<!--3. -->In the community, what percentage of adults have overactive bladder symptoms?`,
    q2: ``,
    q3: [],
    option: [
      `<!--a. -->Less than 5%`,
      `<!--b. -->5% to 10%`,
      `<!--c. -->10% to 20%`,
      `<!--d. -->20% to 50% `,
      `<!--e. -->More than 50% `,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [2],
    ansText: `Rationale: <b>Two large prevalence surveys in North America and Europe have shown the prevalence at 16%, whereas the EPIC study put the figure at nearly 12%.</b> Prevalence of at least one lower urinary tract symptom is greater than 50% according to the EPIC study.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `<!--4. -->Mixed incontinence includes:`,
    q2: ``,
    q3: [],
    option: [
      `<!--a. -->stress urinary incontinence.`,
      `<!--b. -->continuous incontinence.`,
      `<!--c. -->postmicturition leakage.`,
      `<!--d. -->incontinence during sexual intercourse. `,
      `<!--e. -->giggle incontinence. `,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [0],
    ansText: `Rationale: This is one of the two constituents of mixed incontinence, along with urgency urinary incontinence.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `<!--5. -->Which features are characteristics of urgency?`,
    q2: ``,
    q3: [],
    option: [
      `<!--a. -->A normal sensation.`,
      `<!--b. -->It builds up slowly.`,
      `<!--c. -->It is usually felt suprapubically.`,
      ` <!--d. -->It develops quickly and may lead to incontinence.`,
      `<!--e. -->a and b. `,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [3],
    ansText: `Rationale: Urgency is thought to be a symptom of rapid onset. Urgency leads to urgency incontinence in the susceptible patient, but not invariably.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `<!--6. -->Which statements are TRUE for detrusor overactivity (DO)?`,
    q2: ``,
    q3: [],
    option: [
      `<!--a. -->It is characterized by phasic involuntary detrusor contractions during bladder filling.`,
      `<!--b. -->It is always accompanied by a feeling of urgency.`,
      `<!--c. -->It is a urodynamic diagnosis.`,
      `<!--d. -->It is a feature of the voiding phase of micturition. `,
      `<!--e. -->a and c. `,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [4],
    ansText: `Rationale: Involuntary contractions seen on urodynamic assessment are characteristic of detrusor overactivity.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `<!--7. -->Detrusor overactivity can be diagnosed:`,
    q2: ``,
    q3: [],
    option: [
      `<!--a. -->only if involuntary filling phase contractions are greater than 15 cm H<sub>2</sub>O in amplitude.`,
      `<!--b. -->if an involuntary contraction is seen during bladder filling, irrespective of size.`,
      `<!--c. -->if there is urgency incontinence but no contraction.`,
      `<!--d. -->if leakage occurs during exercise. `,
      ` <!--e. -->before urodynamics if the patient has overactive bladder syndrome.`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [3],
    ansText: ``,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `<!--8. -->Which statement is FALSE with respect to the hypotheses of detrusor pathophysiology?`,
    q2: ``,
    q3: [],
    option: [
      `<!--a. -->Afferent sensitization signifies an increased afferent firing rate in response to a standardized stimulus.`,
      `<!--b. -->The myogenic and integrative hypotheses require abnormal propagation of excitation in the bladder wall.`,
      `<!--c. -->Synaptic reorganization in the spinal cord may contribute to neurogenic detrusor overactivity.`,
      `<!--d. -->Detrusor overactivity requires volitional control. `,
      `<!--e. -->Synergic coordination of bladder and outlet are determined at the brainstem/midbrain level. `,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [3],
    ansText: `Rationale: Patients are unable to inhibit overactive contractions voluntarily.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `<!--9. -->Which of the following statements is correct regarding symptom assessment tools?`,
    q2: ``,
    q3: [],
    option: [
      `<!--a. -->OAB can be diagnosed from the frequency volume chart.`,
      `<!--b. -->A validated questionnaire is mandatory for diagnosis of OAB.`,
      `<!--c. -->Modular components of the International Consultation on Incontinence Questionnaire system (ICIQ) have undergone formal validation.`,
      `<!--d. -->A high urgency score is diagnostic of detrusor overactivity. `,
      `<!--e. -->a and b. `,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [2],
    ansText: `Rationale: The ICIQ generates new tools and adopts established tools for a system that allows selection of appropriate symptom assessment for specific clinical contexts.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
];
