var quiz = [
   
   
    {
        q: `<!--1. -->Indications for urodynamic studies:`,
        q2: ``,
        q3: [],
        option: [`<!--a. -->are supported by high-quality, level 1 evidence for most conditions.`, 
        `<!--b. -->are better defined for men than for women.`, 
        `<!--c. -->are best defined by the clinician who has clear-cut reasons for performing the study and will use the information obtained to guide treatment.`, 
        ` <!--d. -->are of little value in assessing a patient with neurogenic lower urinary tract dysfunction.`, 
        `<!--e. -->are only useful in women when incontinence is seen clinically. `,
        ],
        optionStyleType: `st-lower-alpha`,
        answer: [2],
        ansText: `Rationale: Urodynamics studies have been used for decades, yet clear-cut, level-1 evidenced-based “indications” for its use are surprisingly lacking. There are a number of reasons for this. It is difficult to conduct proper randomized controlled trials on urodynamics for conditions in which lesser levels of evidence and expert opinion strongly suggest clinical utility and in which “empiric treatment” is potentially harmful or even life-threatening (e.g., neurogenic voiding dysfunction). In addition, symptoms can be caused by a number of different conditions, and it is difficult to study pure or homogeneous patient populations. Given the current state of evidence for urodynamic studies, what is most important is that the clinician has clear-cut reasons for performing the study and that the information obtained will be used to guide treatment of the patient. Despite having established nomograms for bladder outlet obstruction in men, the indications for urodynamics in men are no more clear-cut than they are in women. Urodynamics probably have the most important role in the diagnosis and management of patients with neuropathic voiding dysfunction. In straightforward cases of pure SUI where incontinence is seen clinically, urodynamics may not be needed.`,
        state: `notAnswered`,
        userAnswered: []
      ,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`        ,
        type: `MCSS`},
      {
        q: `<!--2. -->The American Urological Association/Society for Urodynamics and Female Urology Urodynamics (AUA/SUFU) guidelines and recommendations:`,
        q2: ``,
        q3: [],
        option: [`<!--a. -->are all supported by level 1 or 2 evidence.`, 
        `<!--b. -->do not apply to patients with neurogenic lower urinary tract dysfunction.`, 
        `<!--c. -->are intended to assist the clinician in the appropriate selection of urodynamic tests, following evaluation and symptom characterization.`, 
        ` <!--d. -->include recommendations on standardization of urodynamic equipment.`, 
        ` <!--e. -->do not consider expert opinion.`,
        ],
        optionStyleType: `st-lower-alpha`,
        answer: [2],
        ansText: `Rationale: The intent of the guideline was to assist clinicians in the appropriate selection of tests rather than to provide absolute indications for urodynamics. The review of literature produced few articles offering a high level of evidence, and most of the recommendations are based on lower levels of evidence, expert opinion, and clinical principles.`,
        state: `notAnswered`,
        userAnswered: []
              ,
        type: `MCSS`},
      {
        q: `<!--3. -->Which of the following tests assesses bladder compliance?`,
        q2: ``,
        q3: [],
        option: [`<!--a. -->Cystometrogram (CMG)`, 
        `<!--b. -->Micturitional urethral pressure profile`, 
        `<!--c. -->Postvoid residual volume`, 
        `<!--d. -->Voiding pressure flow study `, 
        `<!--e. -->Electromyogram `,
        ],
        optionStyleType: `st-lower-alpha`,
        answer: [0],
        ansText: `Rationale: Compliance is the change in bladder volume/change in bladder pressure. Bladder pressure during filling is assessed by CMG.`,
        state: `notAnswered`,
        userAnswered: []
      ,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`        ,
        type: `MCSS`},
      {
        q: `<!--4. -->Detrusor pressure:`,
        q2: ``,
        q3: [],
        option: [`<!--a. -->can be measured directly via a transurethral catheter.`, 
        `<!--b. -->should remain low (near zero) during bladder filling.`, 
        `<!--c. -->rises abruptly and does not return to baseline with detrusor overactivity.`, 
        `<!--d. -->rises before the external sphincter relaxes in normal voluntary micturition. `, 
        `<!--e. -->is obtained by adding the abdominal pressure to the vesicle pressure. `,
        ],
        optionStyleType: `st-lower-alpha`,
        answer: [1],
        ansText: `Rationale: Detrusor pressure normally remains low during filling, as the bladder is highly compliant. It cannot be measured directly with a transurethral catheter, but must be obtained via subtraction of abdominal pressure from vesicle pressure. With detrusor overactivity, pressure usually returns to baseline after the involuntary contraction abates.`,
        state: `notAnswered`,
        userAnswered: []
      ,
	type: `MCSS`,
	type: `MCSS`        ,
        type: `MCSS`},
      {
        q: `<!--5. -->Detrusor overactivity (DO):`,
        q2: ``,
        q3: [],
        option: [`<!--a. -->is synonymous with overactive bladder.`, 
        `<!--b. -->is necessary to make a diagnosis of urodynamic bladder outlet obstruction.`, 
        `<!--c. -->can be seen on urodynamics of asymptomatic men and women.`, 
        ` <!--d. -->is commonly associated with renal deterioration.`, 
        `<!--e. -->is a diagnosis made based on history alone. `,
        ],
        optionStyleType: `st-lower-alpha`,
        answer: [2],
        ansText: `Rationale: DO is defined as involuntary bladder contractions on CMG. Overactive bladder is a symptom complex with the hallmark symptom of urinary urgency and is not diagnosed on urodynamics. DO has been reported to occur in studies on asymptomatic men and women. Impaired compliance, not DO, is associated with renal deterioration. DO is an observation made during urodynamics.`,
        state: `notAnswered`,
        userAnswered: []
              ,
        type: `MCSS`},
      {
        q: `<!--6. -->The hallmark of bladder outlet obstruction is:`,
        q2: ``,
        q3: [],
        option: [`<!--a. -->incomplete bladder emptying.`, 
        `<!--b. -->low pressure–low flow voiding dynamics.`, 
        `<!--c. -->high pressure–low flow voiding dynamics.`, 
        `<!--d. -->impaired detrusor contractility. `, 
        `<!--e. -->elevated postvoid residual. `,
        ],
        optionStyleType: `st-lower-alpha`,
        answer: [2],
        ansText: `Rationale: Obstruction is defined by high pressure low flow voiding. It may or may not be accompanied by incomplete bladder emptying. Impaired detrusor contractility may sometimes, but not always, be a long-term consequence of obstruction.`,
        state: `notAnswered`,
        userAnswered: []
              ,
        type: `MCSS`},
      {
        q: `<!--7. -->The external urethral sphincter should normally:`,
        q2: ``,
        q3: [],
        option: [`<!--a. -->relax with an involuntary bladder contraction in a neurologically normal person.`, 
        `<!--b. -->relax prior to a voluntary detrusor contraction in a neurologically normal person.`, 
        `<!--c. -->progressively relax while the bladder fills.`, 
        ` <!--d. -->always contract when the detrusor contracts.`, 
        ` <!--e. -->contract during urination in a neurologically normal person.`,
        ],
        optionStyleType: `st-lower-alpha`,
        answer: [1],
        ansText: `Rationale: In a neurologically normal person, the external sphincter progressively contracts with bladder filling and will also contract during an involuntary bladder contraction (guarding reflex). External sphincter relaxation is the first step in the micturition cycle and precedes the detrusor contraction. In detrusor external sphincter dyssynergia, an abnormal neurologic condition, the external sphincter contracts when the detrusor does. Intermittent or fluctuating flow rate of urine due to intermittent contractions of the external sphincter in a neurologically normal person is considered dysfunctional voiding.`,
        state: `notAnswered`,
        userAnswered: []
              ,
        type: `MCSS`},
      {
        q: `<!--8. -->Video-urodynamics (VUDS):`,
        q2: ``,
        q3: [],
        option: [`<!--a. -->is the most precise measure of lower urinary tract function and should be used in all cases in which urodynamics are to be performed.`, 
        `<!--b. -->is required to assess obstruction in a man.`, 
        `<!--c. -->is the procedure of choice for documenting bladder neck dysfunction in men and women.`, 
        `<!--d. -->is impractical to perform in spinal cord–injured patients. `, 
        `<!--e. -->is needed to confirm detrusor overactivity. `,
        ],
        optionStyleType: `st-lower-alpha`,
        answer: [2],
        ansText: `Rationale: Although VUDS provides the most precise evaluation of voiding function and dysfunction and is particularly useful when anatomic structure and function are important, it is not practical or necessary for all centers to have VUDS capabilities. VUDS is useful for a number of conditions when an accurate diagnosis cannot otherwise be obtained (e.g., by conventional urodynamics), including complicated voiding dysfunction or known or suspected neuropathic voiding dysfunction (adults and children), unexplained urinary retention in women, prior radical pelvic surgery, urinary diversion, preceding or following renal transplant, or prior pelvic radiation. VUDS is the procedure of choice for documenting bladder neck dysfunction in men and women. VUDS is not specifically needed to diagnose DO.`,
        state: `notAnswered`,
        userAnswered: []
              ,
        type: `MCSS`},
      {
        q: `<!--9. -->Urethral function tests such as abdominal leak point pressure (ALPP) and maximum urethral closure pressure (MUCP):`,
        q2: ``,
        q3: [],
        option: [`<!--a. -->can precisely define intrinsic sphincter deficiency (ISD).`, 
        `<!--b. -->should be done routinely before all surgery for stress incontinence.`, 
        `<!--c. -->are the most important part of the urodynamic assessment of women with stress urinary incontinence (SUI).`, 
        `<!--d. -->should not be used as a single factor to grade the severity of incontinence. `, 
        `<!--e. -->can only be performed during ambulatory urodynamics. `,
        ],
        optionStyleType: `st-lower-alpha`,
        answer: [3],
        ansText: `Rationale: Urethral function tests such as ALPP and MUCP have not been shown to be consistently useful in defining ISD or outcomes of treatments for SUI. They may be useful for some clinicians, but are by no means mandatory. According to the International Continence Society, “Urethral function measurements of leak point pressures and urethral closure pressures are not used as a single factor to grade the severity of incontinence.” Urodynamics are not necessary before surgical treatment of SUI for all women, but if it is done, the AUA/SUFU Guideline states that ALPP or MUCP should be preformed. ALPP can be reported as part of ambulatory urodynamics; however, it is not a measure that is unique to this method.`,
        state: `notAnswered`,
        userAnswered: []
      ,
	type: `MCSS`        ,
        type: `MCSS`},
      {
        q: `<!--10. -->Which of the following conditions/factors may result in inaccurate measurement of bladder compliance?`,
        q2: ``,
        q3: [],
        option: [`<!--a. -->Prior radiation to the pelvis`, 
        `<!--b. -->Use of fluid-filled urodynamic catheters`, 
        `<!--c. -->Presence of vesicoureteral reflux`, 
        `<!--d. -->Bladder outlet obstruction `, 
        `<!--e. -->History of genitourinary (GU) tuberculosis (TB) `,
        ],
        optionStyleType: `st-lower-alpha`,
        answer: [2],
        ansText: `Rationale: Bladder outlet obstruction and radiation can cause a decrease in compliance, but should not affect its accurate measurement. GU TB also can cause significant bladder fibrosis and impaired compliance. Reflux can make compliance look worse than it actually is secondary to the “pop-off” it creates. Fluoroscopy or VUDS is necessary in some cases (e.g., neurogenic bladder) to assess for reflux during filling. In addition, filling rate and involuntary detrusor contractions can also make compliance look worse than it actually is. There are no data to support the proposition that fluid-filled catheters or air charge catheters will result in inaccurate measures of compliance, which is a measure of change volume over pressure.`,
        state: `notAnswered`,
        userAnswered: []
              ,
        type: `MCSS`},
      {
        q: `<!--11. -->According to the Functional Classification System, the symptom of stress incontinence can be classified as:`,
        q2: ``,
        q3: [],
        option: [`<!--a. -->failure to store secondary to an overactive bladder outlet.`, 
        `<!--b. -->failure to store secondary to an overactive bladder.`, 
        `<!--c. -->failure to store secondary to an underactive bladder outlet.`, 
        `<!--d. -->failure to empty secondary to an underactive bladder outlet. `, 
        `<!--e. -->failure to empty secondary to an overactive bladder outlet. `,
        ],
        optionStyleType: `st-lower-alpha`,
        answer: [2],
        ansText: `Rationale: Stress incontinence is a symptom caused by failure to store urine during increases in abdominal pressure. It can be caused by a loss of outlet resistance or an underactive bladder outlet.`,
        state: `notAnswered`,
        userAnswered: []
              ,
        type: `MCSS`},
      {
        q: `<!--12. -->During multichannel urodynamics, what is the best measure that allows the clinician to look for abdominal straining occurring during micturition?`,
        q2: ``,
        q3: [],
        option: [`<!--a. -->Rectal or vaginal catheter pressure`, 
        `<!--b. -->Bladder catheter pressure`, 
        `<!--c. -->Uroflow pattern`, 
        `<!--d. -->Electromyogram activity and uroflow velocity `, 
        `<!--e. -->Postvoid residual `,
        ],
        optionStyleType: `st-lower-alpha`,
        answer: [0],
        ansText: `Rationale: Rectal and or vaginal pressure are used to measure abdominal pressure throughout urodynamics. Patients who are straining to void will exhibit increases in abdominal pressure measurements. Flow patterns can be suggestive of abdominal straining, but are not as accurate as measuring abdominal pressure. Postvoid residual may allow clinicians to understand how well the patient is emptying his or her bladder but does not give information about how voiding is accomplished. Similarly, EMG may be increased from abdominal straining, but there are many other causes of increased EMG activity during voiding. Bladder catheter pressure will increase with abdominal straining. The difference between the bladder catheter and the rectal or vaginal catheter allows for calculation of the detrusor pressure.`,
        state: `notAnswered`,
        userAnswered: []
              ,
        type: `MCSS`},
      {
        q: `<!--13. -->For women with stress incontinence, urodynamics have the most useful role in which of the following scenarios?`,
        q2: ``,
        q3: [],
        option: [`<!--a. -->In women who are considering surgical correction who also have urgency incontinence symptoms or difficulty emptying the bladder`, 
        `<!--b. -->In predicting outcomes of surgery for women with pure stress incontinence`, 
        `<!--c. -->In predicting the likelihood of voiding dysfunction in women with pure stress incontinence`, 
        `<!--d. -->In predicting outcomes of conservative, nonsurgical treatments for women with mixed incontinence `, 
        `Prior to starting conservative, nonsurgical treatments for women with pure incontinence `,
        ],
        optionStyleType: `st-lower-alpha`,
        answer: [0],
        ansText: `Rationale: UDS in women with pure stress or stress-predominant mixed incontinence and normal emptying has not been shown in randomized controlled trials to be more beneficial than office evaluation alone and has not been shown to predict outcomes of surgery in the same population. Women with significant mixed incontinence and emptying problems have not been studied in randomized controlled trials, and it is felt that UDS is beneficial in these women.`,
        state: `notAnswered`,
        userAnswered: []
              ,
        type: `MCSS`}
      
]