var quiz = [
   
   
    {
        q: `<!--1. -->An example of a lower urinary tract (LUT) symptom is:`,
        q2: ``,
        q3: [],
        option: [`<!--a. -->urine loss while playing tennis.`, 
        `<!--b. -->urodynamic stress incontinence with Valsalva leak point pressure (VLPP) of 60 cm H<sub>2</sub>O.`, 
        `<!--c. -->a symptom score of 19 on the AUA Symptom Index.`, 
        `<!--d. -->the finding of urinary incontinence on a supine stress test. `, 
        `<!--e. -->the presence of stage 2 anterior pelvic organ prolapse on a cystogram. `,
        ],
        optionStyleType: `st-lower-alpha`,
        answer: [3],
        ansText: `Rationale: A LUT symptom is one that is recognizable by the patient. A sign is one that is observable by a clinician (i.e., urine loss during a supine stress test). A VLPP result is a urodynamic observation, whereas a cystogram report of a cystocele is a radiologic observation.`,
        state: `notAnswered`,
        userAnswered: []
      ,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`        ,
        type: `MCSS`},
      {
        q: `<!--2. -->Which of the following is consistent with the diagnosis of urgency urinary incontinence?`,
        q2: ``,
        q3: [],
        option: [`<!--a. -->Leakage of urine with coughing and a VLPP of 60 cm H<sub>2</sub>O`, 
        `<!--b. -->Leakage of urine with detrusor overactivity`, 
        `<!--c. -->Leakage of urine while coughing and detrusor leak point pressure of 50 cm H<sub>2</sub>O`, 
        `<!--d. -->Leakage of urine while coughing and leakage of urine with urgency `, 
        `<!--e. -->Leakage of urine and feces while straining `,
        ],
        optionStyleType: `st-lower-alpha`,
        answer: [1],
        ansText: `Rationale: Urgency urinary incontinence may be associated with detrusor overactivity (DO), though DO need not be present for the diagnosis, merely sense of urgency with loss of urine. Mixed incontinence is the symptomatic complaint of both stress urinary incontinence and urgency incontinence.`,
        state: `notAnswered`,
        userAnswered: []
      ,
	type: `MCSS`,
	type: `MCSS`        ,
        type: `MCSS`},
      {
        q: `<!--3. -->The most common form of urinary incontinence (UI) in a woman aged 40 years is:`,
        q2: ``,
        q3: [],
        option: [`<!--a. -->stress incontinence.`, 
        `<!--b. -->urgency incontinence.`, 
        `<!--c. -->mixed incontinence.`, 
        `<!--d. -->detrusor overactivity incontinence. `, 
        `<!--e. -->continuous incontinence. `,
        ],
        optionStyleType: `st-lower-alpha`,
        answer: [0],
        ansText: `Rationale: Stress urinary incontinence (SUI) is the most common form of UI in young women. In contrast, urge UI and mixed UI appear to become more prevalent forms of UI with aging. Continuous incontinence is uncommon—often associated with iatrogenic injuries to the lower urinary tract resulting in fistulae.`,
        state: `notAnswered`,
        userAnswered: []
      ,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`        ,
        type: `MCSS`},
      {
        q: `<!--4. -->What factor has been associated with LUTS but not urinary incontinence in women?`,
        q2: ``,
        q3: [],
        option: [`<!--a. -->Advancing age.`, 
        `<!--b. -->Caucasian race.`, 
        `<!--c. -->Number of prior vaginal delivereries.`, 
        ` <!--d. -->Caffeine intake.`, 
        ` <!--e. -->Large birth weight.`,
        ],
        optionStyleType: `st-lower-alpha`,
        answer: [3],
        ansText: `Rationale: Caffeine consumption has been associated with urinary urgency, but most studies have not necessarily noted an association with urinary incontinence. All other factors mentioned have been associated with a form of UI.`,
        state: `notAnswered`,
        userAnswered: []
              ,
        type: `MCSS`},
      {
        q: `<!--5. -->Later in life, when compared with a woman who had her first child at the age of 36, a woman delivering her first child at 23 years of age would be:`,
        q2: ``,
        q3: [],
        option: [`<!--a. -->more likely to experience SUI.`, 
        `<!--b. -->equally likely to experience SUI.`, 
        `<!--c. -->more likely to experience UUI.`, 
        `<!--d. -->equally likely to experience UUI. `, 
        `<!--e. -->less likely to experience MUI. `,
        ],
        optionStyleType: `st-lower-alpha`,
        answer: [0],
        ansText: `Rationale: Younger age at time of first pregnancy has been associated with a greater likelihood of developing SUI later in life.`,
        state: `notAnswered`,
        userAnswered: []
              ,
        type: `MCSS`},
      {
        q: `<!--6. -->The symptom most closely associated with the presence of advanced pelvic organ prolapse is the sensation of:`,
        q2: ``,
        q3: [],
        option: [`<!--a. -->pelvic pressure.`, 
        `<!--b. -->pelvic pain.`, 
        `<!--c. -->constipation.`, 
        `<!--d. -->voiding difficulty. `, 
        `<!--e. -->vaginal bulge. `,
        ],
        optionStyleType: `st-lower-alpha`,
        answer: [4],
        ansText: `Rationale: Although all of the symptoms described can be associated with POP, only the specific complaint of a vaginal bulge has been consistently demonstrated to be associated with the presence of POP. All others can be associated with other conditions distinct from the presence of POP. For example, pelvic pressure can be related to pelvic floor dysfunction or a variety of other conditions, and pelvic pain can be associated with various forms of pelvic pathology including adnexal pathology.`,
        state: `notAnswered`,
        userAnswered: []
      ,
	type: `MCSS`        ,
        type: `MCSS`},
      {
        q: `<!--7. -->Which of the following Pelvic Organ Prolapse Quantification System (POP-Q) scores is implausible?`,
        q2: ``,
        q3: [],
        option: [`<!--a. -->Aa of −2`, 
        `<!--b. -->Ap of +4`, 
        `<!--c. -->Ba of +5`, 
        `<!--d. -->Bp of 0 `, 
        `<!--e. -->C of −8 `,
        ],
        optionStyleType: `st-lower-alpha`,
        answer: [1],
        ansText: `Rationale: POP-Q points are measured by their distance from the hymenal ring (in centimeters). By definition, Aa and Ap are the points 3 cm from the hymen on the anterior and posterior vaginal walls, respectively. It would be impossible for this point to be greater than 3 cm proximal (or distal) to the hymen. In advanced prolapse, this point could be up to 3 cm distal to the hymen. C point represents the distance from the hymen to the cervix or vaginal cuff (post hysterectomy). Ba and Bp point represent the leading edge of the most advanced aspect of the prolapse on the anterior and posterior vaginal walls, respectively. As such, they can be well beyond + 3 in advanced prolapse.`,
        state: `notAnswered`,
        userAnswered: []
              ,
        type: `MCSS`},
      {
        q: `<!--8. -->A woman with POP-Q scores of Aa −2, Ba 0, C −5, Ap +1, Bp +1 would be considered to have what stage prolapse?`,
        q2: ``,
        q3: [],
        option: [`<!--a. -->Stage 0`, 
        `<!--a. -->Stage 1`, 
        `<!--a. -->Stage 2`, 
        `<!--a. -->Stage 3 `, 
        `<!--a. -->Stage 4 `,
        ],
        optionStyleType: `st-lower-alpha`,
        answer: [2],
        ansText: `Rationale: Staging in POP-Q is based on the leading edge of prolapse. This equates to the highest (positive) number associated with the points listed (Aa, Ba, Ap, Bp, C). The leading edge of the most advanced POP is greater than 1 cm proximal to the hymen in patients with stage 1 prolapse. Stage 2 patients will have their leading edge between 1 cm proximal to and distal to the hymen. Stage 3 indicates a leading edge greater than 1 cm beyond the hymen but not completely everted (stage 4).`,
        state: `notAnswered`,
        userAnswered: []
      ,
	type: `MCSS`        ,
        type: `MCSS`},
      {
        q: `<!--9. -->A patient with a POP-Q score of Aa −2, Ba −2, Ap +2, Bp +2, and C 0 should be counseled to undergo:`,
        q2: ``,
        q3: [],
        option: [`<!--a. -->anterior colporrhaphy.`, 
        `<!--b. -->posterior colporrhaphy.`, 
        `<!--c. -->anterior and posterior colporrhaphy.`, 
        `<!--d. -->posterior colporrhaphy and sacrospinous fixation. `, 
        `<!--e. -->sacrospinous fixation. `,
        ],
        optionStyleType: `st-lower-alpha`,
        answer: [3],
        ansText: `Rationale: This patient has both posterior compartment prolapse (based on Ap and Bp points beyond the hymen) and apical prolapse (C point at the hymen) based on the POP-Q score. Therefore the patient should be counseled to have both posterior repair of some type (posterior colporrhaphy in this example) and apical repair (sacrospinous fixation in this example).`,
        state: `notAnswered`,
        userAnswered: []
              ,
        type: `MCSS`},
      {
        q: `<!--10. -->During bladder contraction, which is most active?`,
        q2: ``,
        q3: [],
        option: [`<!--a. -->Pelvic nerve`, 
        `<!--b. -->Hypogastric nerve`, 
        `<!--c. -->Pudendal nerve`, 
        `<!--d. -->A-delta nerves `, 
        `<!--e. -->Onuf nucleus `,
        ],
        optionStyleType: `st-lower-alpha`,
        answer: [0],
        ansText: `Rationale: During bladder contraction, parasympathetic transmission (via the pelvic nerve) is active and sympathetic transmission (via the hypogastric nerve) is suppressed. Pudendal innervation to the external sphincter is suppressed. Pudendal innervation is derived from Onuf nucleus in the sacral cord. A-delta nerves (afferent) are active during storage and are involved in the spinal reflex mechanism that promotes closure of the bladder neck.`,
        state: `notAnswered`,
        userAnswered: []
              ,
        type: `MCSS`}
      
]