var quiz = [
  {
    q: `<!--1. -->Nocturnal polyuria is defined as:`,
    q2: ``,
    q3: [],
    option: [
      `<!--a. -->nocturnal polyuria index (NPi) greater than 0.33.`,
      `<!--b. -->nocturnal urine volume (NUV) greater than 6.4 mL/kg.`,
      `<!--c. -->NUV greater than 54 mL/h.`,
      `<!--d. -->a and b. `,
      `<!--e. -->a, b, and c. `,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [4],
    ansText: `Rationale: Nocturnal polyuria is defined as NPi greater than 0.20 in young adults and greater than 0.33 in adults older than 65 years when 24-hour urine production is within normal limits. Other definitions include NUV greater than 0.9 mL/min (54 mL/h) and NUV greater than 1.5 mL/min (90 mL/h). A universally accepted definition of nocturnal polyuria has yet to be identified.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `<!--2. -->All of the following statements are true about nocturia EXCEPT:`,
    q2: ``,
    q3: [],
    option: [
      `<!--a. -->nocturia is voiding that is preceded and followed by sleep.`,
      `<!--b. -->the prevalence of nocturia increases with age.`,
      `<!--c. -->nocturia impairs sleep efficiency, sleep latency, and slow-wave sleep and is associated with increased mortality.`,
      `<!--d. -->one or more voids per night appear to be clinically significant. `,
      `<!--e. -->nocturia is associated with falls. `,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [3],
    ansText: `Rationale: Several studies have shown that two or more voids per night generate bother and impair quality of life.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `<!--3. -->When instructing a patient how to complete a frequency-volume chart, it is essential to:`,
    q2: ``,
    q3: [],
    option: [
      `<!--a. -->tell the patient to record what time he or she goes to sleep.`,
      `<!--b. -->tell the patient to record what time he or she awakens.`,
      `<!--c. -->tell the patient to record how much he or she drinks during the day.`,
      `<!--d. -->a and b. `,
      ` <!--e. -->a, b, and c.`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [3],
    ansText: `Rationale: Although having the patient record how much he drinks during the day may be helpful, it is essential that the patient record the time he goes to sleep and the time he awakens to know the number of nocturnal voids and NUV.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `<!--4. -->Factors that inhibit antidiuretic hormone (ADH) secretion include all of the following EXCEPT:`,
    q2: ``,
    q3: [],
    option: [
      `<!--a. -->hyperkalemia.`,
      `<!--b. -->atrial natriuretic peptide (ANP).`,
      `hypercalcemia.`,
      `prostaglandin E2 (PGE2). `,
      `lithium. `,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [0],
    ansText: `Rationale: <b>Factors that inhibit antidiuretic hormone (ADH) and cause diuresis (inhibit water reabsorption) include PGE2, ANP, hypercalcemia, hypokalemia, lithium, and tetracyclines.</b> Reversal of water diuresis, accordingly, may occur through stimulation of V2 receptors, either by endogenous arginine vasopressin or a congener thereof, such as desmopressin.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `<!--5. -->A 75-year-old obese man (100 kg) with a short neck reports frequent urination during the nighttime and completes a voiding diary. His 24-hour voided volume is 2000 mL, and his NUV is 1000 mL. Based on these diary findings, this man has:`,
    q2: ``,
    q3: [],
    option: [
      `<!--a. -->global polyuria.`,
      `<!--b. -->nocturnal polyuria.`,
      `<!--c. -->diminished nocturnal bladder capacity.`,
      `<!--d. -->diminished global bladder capacity. `,
      ` <!--e. -->none of the above.`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [1],
    ansText: `Rationale: <b>This patient suffers from nocturnal polyuria as defined by his NPi. His NPi can be calculated by dividing his NUV by his 24-hour voided volume:</b><br/><br/>NPi = NUV/24 − hour voided volume = 1000 mL/2000 mL = 0.5 <br/><br/><b>He has nocturnal polyuria because his NPi is greater than 0.33. Global polyuria is defined as 24-hour urine volume greater than 40 mL/kg.</b> Diminished nocturnal bladder capacity and global bladder capacity cannot be determined by the information provided in this scenario.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `<!--6. -->According to a recent study, which of the following showed the greatest decline in nocturia severity and greatest improvement of health-related quality of life (HRQL) in men with benign prostatic hyperplasia (BPH) and nocturia?`,
    q2: ``,
    q3: [],
    option: [
      `<!--a. -->Watchful waiting.`,
      `<!--b. -->α-Blockers.`,
      `<!--c. -->Transurethral resection of the prostate (TURP).`,
      `<!--d. -->Transurethral microwave treatment (TUMT). `,
      `<!--e. -->There was no difference among these treatments. `,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [2],
    ansText: `Rationale: After 6 to 12 months, watchful waiting, α-blockers, TURP, and TUMT yielded reduction in nocturia episodes by 7%, 17%, 75%, and 32%, respectively. Improvements in HRQL were most strongly associated with treatment-associated declines in nocturia severity.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `<!--7. -->When bound to V2 receptors in the renal collecting tubules, desmopressin:`,
    q2: ``,
    q3: [],
    option: [
      `<!--a. -->increases water permeability.`,
      `<!--b. -->enhances water reabsorption.`,
      `<!--c. -->dilutes extracellular fluid.`,
      `<!--d. -->concentrates urine. `,
      `<!--e. -->all of the above. `,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [4],
    ansText: `Rationale: When bound to V2 receptors in the renal collecting tubules, desmopressin increases water permeability, enhances water reabsorption, dilutes extracellular fluid, and concentrates urine.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `<!--8. -->Current thinking is that desmopressin is most appropriate to treat:`,
    q2: ``,
    q3: [],
    option: [
      `<!--a. -->nocturnal polyuria.`,
      `<!--b. -->global polyuria.`,
      `<!--c. -->decreased global bladder capacity.`,
      ` <!--d. -->decreased nocturnal bladder capacity.`,
      ` <!--e. -->all of the above.`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [0],
    ansText: `Rationale: Current thinking is that desmopressin would be the most appropriate therapy for patients with nocturia related to nocturnal polyuria.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `<!--9. -->Which of the following have caused statistically but minimally clinically significant reductions in nocturia episodes?`,
    q2: ``,
    q3: [],
    option: [
      `Blockers`,
      `5α-Reductase inhibitors`,
      `Antimuscarinics`,
      `α-Blockers and antimuscarinics `,
      `All of the above `,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [4],
    ansText: `Rationale: α-blockers, 5α-reductase inhibitors, antimuscarinics, and antimuscarinics + α-blockers have been found to produce a statistically significant reduction in nocturia episodes, yielding minimal clinical significance.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `<!--10. -->Regarding the frequency volume chart (voiding diary), which of the following statements is FALSE?`,
    q2: ``,
    q3: [],
    option: [
      `<!--a. -->NUV is defined as the total volume of all voids preceded and followed by sleep.`,
      `<!--b. -->The first morning void counts toward total number of nightly voiding episodes in computing the nocturnal urine volume.`,
      `<!--c. -->Nighttime may be during daylight hours.`,
      ` <!--d. -->Maximum voided volume is the single greatest urine volume measured during a 24-hour period.`,
      ` <!--e. -->Nocturia or enuresis occurs when the nocturia index (Ni) is greater than 1.`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [0],
    ansText: `Rationale: This is incorrect. NUV is the total volume of urine passed during the night and the first morning void.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `<!--11. -->When prescribing desmopressin to an elderly patient (&gt;65 years), it is advisable to:`,
    q2: ``,
    q3: [],
    option: [
      `<!--a. -->check a baseline serum sodium level`,
      `<!--b. -->check a serum sodium level within 7 days and then 28 days after initial or incremental dosing`,
      `<!--c. -->check a serum sodium level every 6 months or as often as indicated`,
      `<!--d. -->avoid prescribing in those with baseline serum sodium below 130 mmol/L`,
      `<!--e. -->all of the above `,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [4],
    ansText: `Rationale: When prescribing desmopressin to a patient older than 65 years of age, it is advisable to closely monitor serum sodium AND to avoid prescribing it to elderly patients with baseline hyponatremia.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
];
