var quiz = [
   
   
    {
        q: `<!--1. -->Which of the following is the definition of stress urinary incontinence (UI)?`,
        q2: ``,
        q3: [],
        option: [`<!--a. -->Leakage of urine with urgency`, 
        `<!--b. -->Leakage of urine with an increase in intra-abdominal pressure`, 
        `<!--c. -->Leakage of urine while asleep`, 
        `<!--d. -->Leakage of urine with urgency and effort `, 
        `<!--e. -->Leakage of urine without being aware of it `,
        ],
        optionStyleType: `st-lower-alpha`,
        answer: [1],
        ansText: `Rationale: Leakage of urine with urgency is known as UUI. Leakage of urine while asleep is nocturnal enuresis. Leakage of urine on urgency and effort is mixed UI, and leakage of urine without being aware of it is insensible UI.`,
        state: `notAnswered`,
        userAnswered: []
      ,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`        ,
        type: `MCSS`},
      {
        q: `<!--2. -->Which of the following symptoms is not considered a bladder storage symptom?`,
        q2: ``,
        q3: [],
        option: [`<!--a. -->Frequency`, 
        `Urgency`, 
        `Hesitancy`, 
        `Nocturia `, 
        ` UI`,
        ],
        optionStyleType: `st-lower-alpha`,
        answer: [2],
        ansText: `Rationale: Frequency, urgency, nocturia, and urinary incontinence are all bladder storage symptoms, while hesitancy is a voiding symptom.`,
        state: `notAnswered`,
        userAnswered: []
      ,
	type: `MCSS`,
	type: `MCSS`        ,
        type: `MCSS`},
      {
        q: `<!--3. -->Which of the following is not a potential risk factor for UI in men?`,
        q2: ``,
        q3: [],
        option: [`Age`, 
        `Race`, 
        `Urological infection`, 
        ` Cognitive impairment`, 
        `Prostatectomy `,
        ],
        optionStyleType: `st-lower-alpha`,
        answer: [1],
        ansText: `Rationale: Potential risk factors for UI in men include increased age, urological infection, neurological and cognitive impairment, prostatectomy, and drugs. Ethnicity and race were not shown to have any statistical significance as a potential risk factor for UI in men.`,
        state: `notAnswered`,
        userAnswered: []
              ,
        type: `MCSS`},
      {
        q: `<!--4. -->Initial assessment of men with UI includes all of the following except:`,
        q2: ``,
        q3: [],
        option: [`<!--a. -->flow test.`, 
        `<!--b. -->invasive urodynamics.`, 
        `<!--c. -->frequency/volume chart.`, 
        ` urinalysis.`, 
        `<!--e. -->quality-of-life questionnaire. `,
        ],
        optionStyleType: `st-lower-alpha`,
        answer: [1],
        ansText: `Rationale: Men with UI should be assessed with noninvasive baseline investigations including a flow test, frequency/volume chart or bladder diary, urinalysis to exclude infection and blood in the urine, and a quality-of-life questionnaire to assess the impact of the incontinence on quality of life. Invasive urodynamics, including filling cystometry and pressure flow studies, is reserved for use following failure of conservative and medical therapies and when it will alter the management of the patient.`,
        state: `notAnswered`,
        userAnswered: []
              ,
        type: `MCSS`},
      {
        q: `<!--5. -->Which of the following is not a treatment for urgency urinary incontinence (UUI)?`,
        q2: ``,
        q3: [],
        option: [`<!--a. -->Bladder training`, 
        `<!--b. -->Pelvic floor muscle training`, 
        `<!--c. -->Antimuscarinics`, 
        ` Duloxetine`, 
        `Botox `,
        ],
        optionStyleType: `st-lower-alpha`,
        answer: [3],
        ansText: `Rationale: Bladder training, pelvic floor muscle training, and antimuscarinics are first-line treatments of patients with UUI. If these fail, then patients can be treated with cystoscopic intradetrusor botulinum toxin-A injections. Duloxetine is a serotonin, norepinephrine reuptake inhibitor that has been licensed for the treatment of SUI in women but not for the treatment of UUI.`,
        state: `notAnswered`,
        userAnswered: []
      ,
	type: `MCSS`,
	type: `MCSS`        ,
        type: `MCSS`},
      {
        q: `<!--6. -->Which of the following is not a treatment for stress urinary incontinence (SUI) in men?`,
        q2: ``,
        q3: [],
        option: [`<!--a. -->Pelvic floor muscle training`, 
        `<!--b. -->Penile clamp`, 
        `Antimuscarinics`, 
        `<!--d. -->Male sling `, 
        `<!--e. -->Artificial urinary sphincter `,
        ],
        optionStyleType: `st-lower-alpha`,
        answer: [2],
        ansText: `Rationale: Antimuscarinics are licensed for the treatment of overactive bladder syndrome and not SUI.`,
        state: `notAnswered`,
        userAnswered: []
              ,
        type: `MCSS`},
      {
        q: `<!--7. -->Which of the following is not measured by the International Prostate Symptom Score (IPSS)/AUA-SI?`,
        q2: ``,
        q3: [],
        option: [`Urgency`, 
        `Frequency`, 
        `Nocturia`, 
        `Incontinence `, 
        `Straining `,
        ],
        optionStyleType: `st-lower-alpha`,
        answer: [3],
        ansText: `Rationale: The IPSS or AUA-SI assesses three storage symptoms (urgency, frequency, nocturia), three voiding symptoms (intermittency, weak stream, straining), and one post-micturition symptom (incomplete emptying). It does not assess for UI (see <a href="df347f2013444c1bb0ac7913eaf28f43">Fig. 113.1A</a><a href="3217d2908d9d498384aef4cd5dd440a8">B</a>).`,
        state: `notAnswered`,
        userAnswered: []
              ,
        type: `MCSS`}
]