var quiz = [
    

    {
        q: `What is a mesh erosion?`,
        q2: ``,
        q3: [],
        option: [`When mesh gradually becomes apparent in the vagina`, 
        `It is an incorrect term that should not be used`, 
        `When mesh gradually becomes exposed in the urethra or bladder`, 
        `Any palpable or visible mesh in any organ`, 
        `A result of trocar injury to the bladder or urethra`],
        optionStyleType: `st-lower-alpha`,
        answer: [1],
        ansText:`Rationale: <!--<b>b. It is an incorrect term that should not be used.</b>--> <b><i>Erosion</i></b> is a generic term that implies that tissue has been worn away by friction or pressure. Therefore, the term should not be used.`, 
        state: `notAnswered`,
        userAnswered: []
    ,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`        ,
        type: `MCSS`},
    {
        q: `Why are large pores essential for mesh to prevent complications?`,
        q2: ``,
        q3: [],
        option: [`These make the mesh a lighter weight.`, 
        `They make the mesh stretch.`, 
        `They make the mesh cheaper to produce.`, 
        `They allow macrophages and other cells to penetrate the mesh.`, 
        `They make the mesh less visible.`],
        optionStyleType: `st-lower-alpha`,
        answer: [3],
        ansText:`Rationale: <!--<b>d. They allow macrophages and other cells to penetrate the mesh.</b>--> Pore size is critical to wound healing and mesh integration by the body. Smaller pore size in woven grafts allows bacteria (1 μm) to enter but restricts entry of host macrophages and lymphocytes (50 μm), impeding immune response. When pores are large such as with polypropylene type I mesh (∼1500 μm), fibrocollagenous tissue ingrowth can occur, which allows the mesh to integrate into the local tissue providing strength and support.`, 
        state: `notAnswered`,
        userAnswered: []
    ,
	type: `MCSS`,
	type: `MCSS`        ,
        type: `MCSS`},
    {
        q: `Mesh is known to increase the long-term risk of`,
        q2: ``,
        q3: [],
        option: [`pelvic cancers`, 
        `systemic (nonpelvic) cancers`, 
        `autoimmune diseases`, 
        `chronic fatigue syndrome`, 
        `none of the above`],
        optionStyleType: `st-lower-alpha`,
        answer: [4],
        ansText:`Rationale: <!--<b>e. None of the above.</b>--> With long-term use of mesh in the vagina, there has been the opportunity to follow women over many years for complications. Mesh has been hypothesized to increase cancer risk due to chronic foreign body response. This theory has been disproved with population-based studies that showed no increase in pelvic or any other cancer diagnoses in women followed for 6 years after implant. Similarly, mesh implantation has not been associated with the development of autoimmune diseases over long-term follow-up.`, 
        state: `notAnswered`,
        userAnswered: []
    ,
	type: `MCSS`,
	type: `MCSS`        ,
        type: `MCSS`},
    {
        q: `Which of the following is a contraindication for mesh sling placement?`,
        q2: ``,
        q3: [],
        option: [`Prior failed mesh sling`, 
        `Vaginal atrophy`, 
        `Urethral injury during procedure`, 
        `History of recurrent urinary tract infections (UTIs)`, 
        `Fibromyalgia`],
        optionStyleType: `st-lower-alpha`,
        answer: [2],
        ansText:`Rationale: <!--<b>c. Urethral injury during procedure.</b>--> Mesh perforation or later extrusion at the bladder neck or into urethra is a rare complication. It occurs due to an injury to the urethra or bladder neck during either the vaginal dissection or trocar passage. If an intraoperative urethral injury is noted during dissection for placement of the sling, the surgeon must abandon mesh placement. One should repair the urethral injury with absorbable suture and allow healing before undertaking any mesh procedure, given the extraordinary high risk of urethral extrusion of the mesh.`, 
        state: `notAnswered`,
        userAnswered: []
    ,
	type: `MCSS`,
	type: `MCSS`        ,
        type: `MCSS`},
    {
        q: `In which of the following procedures can bladder perforations occur?`,
        q2: ``,
        q3: [],
        option: [`Retropubic sling`, 
        `Transobturator sling`, 
        `Mini/single incision sling`, 
        `Anterior prolapse mesh`, 
        `All of the above`],
        optionStyleType: `st-lower-alpha`,
        answer: [4],
        ansText:`Rationale: <!--<b>e. All of the above.</b>--> Bladder injury is far more common with retropubic than transobturator trocars (4.8% vs. 0.6%) and is typically diagnosed on cystoscopy with a 70-degree lens during the sling placement. The trocar is seen as at the dome/lateral wall of the bladder. Mesh perforation into the bladder (0.7% to 3.5%) in the case of anterior compartment pelvic organ prolapse repair and into the rectum (0.15%) from posterior repair can present with pain, fistula formation, or, in the case of bladder perforation, recurrent hematuria, UTIs, or voiding-related pain.`, 
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `In a woman with retention immediately after a mesh sling placement, which of the following treatments is contraindicated?`,
        q2: ``,
        q3: [],
        option: [`Self-catheterization for 2 weeks`, 
        `Urethral dilation after 1 week`, 
        `Indwelling catheter for 3 days`, 
        `Sling loosening/division in 1 week`],
        optionStyleType: `st-lower-alpha`,
        answer: [1],
        ansText:`Rationale: <!--<b>b. Urethral dilation after 1 week.</b>--> Urethral dilation is ineffective in the setting of bladder outlet obstruction (BOO) from an obstructing sling and puts the patient at risk for urethral extrusion of the mesh with the dilation traumatizing the tissue over the inflexible mesh.`, 
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `What is a desirable property for type I mesh?`,
        q2: ``,
        q3: [],
        option: [`Low melting point`, 
        `Knitted`, 
        `Smaller pore size`, 
        `Clear colored material`, 
        `Made of polytetrafluoroethylene`],
        optionStyleType: `st-lower-alpha`,
        answer: [1],
        ansText:`Rationale: <!--<b>b. Knitted.</b>--> Type I mesh is macroporous with pore size greater than 75 μm. Examples of type I mesh are polypropylene and Marlex. Marlex is a woven monofilament polypropylene. It is one of the stiffest mesh materials, with a propensity to wrinkle and a high extrusion rate. In contrast, Polypropylene is a monofilament knitted graft that is softer and more compliant than woven configurations and has larger interstices due to the loose knit (1500 vs. 600 μm) increasing elasticity. In addition, its melting point of 160°C allows it to be autoclaved. It is currently the only recommended implantable vaginal mesh for slings and pelvic organ prolapse.`, 
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `Which of the following statements about mesh is true?`,
        q2: ``,
        q3: [],
        option: [`New mesh exposures/extrusions cannot occur more than two years after the original surgery`, 
        `Conservative treatment of mesh exposures with estrogen is never effective`, 
        `If your technique is meticulous, you can remove the entire mesh`, 
        `Cystoscopy always needs to be performed after any mesh sling placement`, 
        `Dyspareunia without mesh exposure should only be treated conservatively`],
        optionStyleType: `st-lower-alpha`,
        answer: [3],
        ansText:`Rationale: <!--<b>d. Cystoscopy always needs to be performed after any mesh sling placement.</b>--> Bladder injury is far more common with retropubic than transobturator trocars (4.8% vs. 0.6%) and is typically diagnosed on cystoscopy with a 70-degree lens during the sling placement. The trocar is seen as at the dome/lateral wall of the bladder. Complete filling of the bladder is required to evaluated for injuries as an underfilled may obscure a small perforation.`, 
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `What symptom is the most likely to resolve after mesh sling revision?`,
        q2: ``,
        q3: [],
        option: [`Urinary retention`, 
        `Mesh exposure`, 
        `Stress incontinence`, 
        `Urgency incontinence`, 
        `Dyspareunia`],
        optionStyleType: `st-lower-alpha`,
        answer: [1],
        ansText:`Rationale: <!--<b>b. Mesh exposure.</b>--> Mesh re-exposure if these principles are followed is near 0%.`, 
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `Abdominal sacrocolpopexy (ASC) mesh presenting with mesh-related abdominal abscess should be treated with:`,
        q2: ``,
        q3: [],
        option: [`long-term antibiotics and percutaneous drainage`, 
        `complete abdominal and vaginal mesh removal`, 
        `abdominal mesh removal leaving vaginal mesh in place to avoid vaginal tissue loss`, 
        `vaginal mesh removal and vaginal drainage of the abscess`, 
        `abdominal exploration and washout`],
        optionStyleType: `st-lower-alpha`,
        answer: [1],
        ansText:`Rationale: <!--<b>b. Complete abdominal and vaginal mesh removal.</b>--> Abdominal mesh removal is sometimes indicated after failed vaginal approach or for patients with intractable mesh-related pain, abscess/infected upper portion of the mesh, or discitis. In the case of infection, the entire mesh should always be removed since residual infected mesh after a failed partial excision causes significant morbidity, including chronic infection, sinus tracts, abscess, and fistula formation. These will require a repeat excision typically via laparotomy, and this is usually a very difficult and morbid procedure.`, 
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `Which of the following statements about male mesh slings are true?`,
        q2: ``,
        q3: [],
        option: [`The mesh perforation rate of the urethra is underreported.`, 
        `Retention after catheter removal should quickly be treated by sling incision to prevent bladder remodeling.`, 
        `If a man requires an artificial sphincter after failed mesh sling, the sling can simply be divided and left in place during artificial urinary sphincter (AUS) placement.`, 
        `Mesh urethral perforation is often asymptomatic.`],
        optionStyleType: `st-lower-alpha`,
        answer: [2],
        ansText:`Rationale: <!--<b>c. If a man requires an artificial sphincter after failed mesh sling, the sling can simply be divided and left in place during artificial urinary sphincter (AUS) placement.</b>--> Sling division without actual removal is sometimes needed when placing an artificial sphincter and can be performed simultaneously without difficulty.`, 
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`}

    



];
