var quiz = [
    

    {
        q: `Urodynamic stress urinary incontinence (SUI) refers to:`,
        q2: ``,
        q3: [],
        option: [`incontinence that is demonstrated during a cough on clinical examination.`, 
        `incontinence occurring in the absence of urgency.`, 
        `incontinence occurring in combination with detrusor overactivity (DO).`, 
        `incontinence occurring on coughing in association with urgency and demonstrable DO.`, 
        `incontinence occurring on coughing in the absence of urgency and of urgency incontinence and with no demonstrable DO.`],
        optionStyleType: `st-lower-alpha`,
        answer: [4],
        ansText:`Rationale: <!--<b>e. Incontinence occurring on coughing in the absence of urgency and of urgency incontinence and with no demonstrable DO</b>--> SUI is the symptom of involuntary loss of urine during situations of increased intra-abdominal pressure such as coughing or sneezing. <b>The International Continence Society defines <i>urodynamic stress incontinence</i> as the involuntary loss of urine during increased intra-abdominal pressure during filling cystometry, in the absence of detrusor (bladder wall muscle) contraction</b> (Abrams et al., 2002).<sup>a</sup> Thus urodynamic evaluation is a prerequisite for the diagnosis of urodynamic SUI. It is not clear, however, especially from the clinical management standpoint, whether a urodynamic diagnosis is imperative for successful treatment of SUI.
    
    <br /><br /><b>a</b> Sources referenced can be found in <i>Campbell-Walsh-Wein Urology, 12th Edition</i>, on the Expert Consult website.
`, 
        state: `notAnswered`,
        userAnswered: []
    ,
	type: `MCSS`,
	type: `MCSS`        ,
        type: `MCSS`},
    {
        q: `Anti-incontinence surgery via the retropubic route:`,
        q2: ``,
        q3: [],
        option: [`is an effective approach for primary intrinsic sphincter deficiency (ISD).`, 
        `works by restoring the same mechanism of continence that was present before the onset of incontinence.`, 
        `aims to improve the support to the urethrovesical junction and correct deficient urethral closure.`, 
        `is the most effective form of anti-incontinence surgery.`, 
        `is carried out laparoscopically as effectively as via an open approach.`],
        optionStyleType: `st-lower-alpha`,
        answer: [2],
        ansText:`Rationale: <!--<b>c. Aims to improve the support to the urethrovesical junction and correct deficient urethral closure.</b>--> Surgical procedures to treat SUI generally aim to improve the support to the urethrovesical junction and correct deficient urethral closure. There is disagreement, however, regarding the precise mechanism by which continence is achieved in the “normal asymptomatic female” and therefore, not surprisingly, how restoration of “normality” is reestablished via surgical manipulation. Anti-incontinence surgery is generally used to address the failure of normal anatomic support of the bladder neck and proximal urethra and ISD. <b>Anti-incontinence surgery does not necessarily work by restoring the same mechanism of continence that was present before the onset of incontinence.</b> Rather, it works by a compensatory approach, creating a new mechanism of continence (Jarvis, 1994). The surgeon’s preference, coexisting problems, and the anatomic features of the patient and her general health condition often influence the choice of procedure.<br/><br/>Current evidence would suggest that in adequately experienced hands, there is no difference in overall safety and efficacy between laparoscopic and open colposuspension. Clearly, another concern is how generalizable the data are on laparoscopic colposuspension because the majority of reported studies are from expert laparoscopists or surgeons working in specialized units. The evidence base on both laparoscopic and open colposuspension is limited by relatively short-term follow-up (robust data are needed out to 5 years) and the tendency toward small numbers, and poor methodology limits the interpretation of most studies with the exception of those reported by Carey and coworkers (2006) and Kitchener and colleagues (2006).`, 
        state: `notAnswered`,
        userAnswered: []
    ,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`        ,
        type: `MCSS`},
    {
        q: `The most important determinant affecting the outcome of retropubic surgery is:`,
        q2: ``,
        q3: [],
        option: [`increasing age.`, 
        `postoperative activity.`, 
        `coexisting medical morbidity.`, 
        `previous surgery.`, 
        `obesity.`],
        optionStyleType: `st-lower-alpha`,
        answer: [3],
        ansText:`Rationale: <!--<b>d. Previous surgery.</b>--> Surgery for recurrent SUI has a lower success rate. One study has reported that <b>Burch colposuspension has an 81% success rate after one previous surgical procedure has failed, but this drops to 25% after two previous repairs and 0% after three previous operations</b> (Petrou and Frank, 2001). Other series report excellent results for colposuspension performed after prior failed surgery. Maher and associates (1999) and Cardozo and colleagues (1999) have both shown good objective (72% and 79%) and subjective (89% and 80%) success rates with repeat colposuspension at a mean follow-up of 9 months. Nitahara and coworkers (1999) reported a 69% subjective success at a mean follow-up of 6.9 years.<br/><br/>The evidence on the duration of symptoms as a predictor of outcome is conflicting. <b>Age may not be a contraindication to colposuspension (with equivalent success rates in the elderly at long-term follow-up), although others reported less success with increasing age</b>. The influence of levels of postoperative activity has been inadequately studied, so no recommendations can be made. There is limited evidence that medical comorbidity may affect surgical outcomes, depending on the outcomes selected. Obesity as a confounding variable is the subject of conflicting evidence in the literature and has not been studied in a prospective fashion. <b>Approximately one-fourth of women undergoing urodynamic study have mixed urodynamic SUI and DO.</b> It is likely that the presence of concomitant DO lessens the success rate of surgery. There is no consensus in the literature as to whether the presence of ISD as assessed by urethral pressure profilometry has any influence in outcome of colposuspension.`, 
        state: `notAnswered`,
        userAnswered: []
    ,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`        ,
        type: `MCSS`},
    {
        q: `ISD is:`,
        q2: ``,
        q3: [],
        option: [`present only in 30% of patients presenting with SUI.`, 
        `most likely present in the majority of women presenting with SUI.`, 
        `accurately identified on the basis of Valsalva leak point pressure.`, 
        `an absolute contraindication to a retropubic suspension procedure.`, 
        `clearly defined in the current literature.`],
        optionStyleType: `st-lower-alpha`,
        answer: [1],
        ansText:`Rationale: <!--<b>b. Most likely present in the majority of women presenting with SUI.</b>--> Hypermobility of the bladder neck and proximal urethra results from a weakening or loss of the supporting elements (ligaments, fasciae, and muscles), which in turn may result from aging, hormonal changes, childbirth, and prior surgery. <b>It seems likely that the majority of women with SUI will also have an element of intrinsic sphincteric weakness with a variable degree of loss of the normal anatomic support of the bladder neck and proximal urethra, resulting in hypermobility.</b><br/><br/>A standardized test is not, however, available to differentiate the relative contributions of ISD and hypermobility, and therefore few studies have been able to accurately differentiate their individual contributions to the incontinence. Retropubic procedures act to restore the bladder neck and proximal urethra to a fixed, retropubic position and are used when hypermobility is thought to be an important factor in the development of that woman’s SUI. This may facilitate the function of a marginally compromised intrinsic urethral sphincter mechanism, but if significant ISD is present, SUI will persist despite efficient surgical repositioning of the bladder neck and proximal urethra.`, 
        state: `notAnswered`,
        userAnswered: []
    ,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`        ,
        type: `MCSS`},
    {
        q: `Retropubic colposuspension procedures may act via which of the following mechanisms?`,
        q2: ``,
        q3: [],
        option: [`Re-creating the normal continence mechanism`, 
        `Elevating the anterior vaginal wall and paravesical tissues toward the iliopectineal line`, 
        `Anchoring the obturator internus fascia to the iliopectineal line`, 
        `Suspending the bladder onto the periosteum of the symphysis pubis`, 
        `Strengthening the pubourethral ligaments`],
        optionStyleType: `st-lower-alpha`,
        answer: [1],
        ansText:`Rationale: <!--<b>b. Elevating the anterior vaginal wall and paravesical tissues toward the iliopectineal line.</b>--> Retropubic colposuspension urethral repositioning can be achieved by three distinctly different procedure principles. These are all based on a similar underlying principle but in a spectrum in relation to the degree of the support/elevations they achieve, and their outcomes differ somewhat in the longer term. <b>The Burch colposuspension is the elevation of the anterior vaginal wall and paravesical tissues toward the iliopectineal line of the pelvic side wall using two to four sutures on either side</b> (Burch, 1961). The vagino-obturator shelf repair aims to anchor the vagina to the obturator internus fascia and is a modification of a combination of the Burch colposuspension and paravaginal defect repair with placement of the sutures laterally anchored to the obturator internus fascia rather than hitching the vagina up to the iliopectineal line (Turner Warwick, 1986). The paravaginal defect repair aims to close a presumed fascial weakness laterally at the site of attachment of the pelvic fascia to obturator internus fascia (Richardson et al., 1976). The MMK procedure is the suspension of the vesicourethral junction (bladder neck) onto the periosteum of the symphysis pubis (Marshall et al., 1949). It aims to close the fascial defect rather than elevate the tissues in the paravesical area.`, 
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `In assessing the outcome of retropubic suspension surgery, which of the following is most important?`,
        q2: ``,
        q3: [],
        option: [`Using objective urodynamic-based outcome criteria`, 
        `Improving symptoms from the patient’s perspective`, 
        `Achieving complete continence`, 
        `Identifying the degree of improvement in the urethral closure pressure`, 
        `Having follow-up data of at least 6 months’ duration`],
        optionStyleType: `st-lower-alpha`,
        answer: [1],
        ansText:`Rationale: <!--<b>b. Improving symptoms from the patient’s perspective.</b>--> One or more high-quality validated symptom and quality-of-life instruments should be chosen at the outset of a clinical trial representing the patient’s viewpoint, accurately defining baseline symptoms, as well as any other areas in which treatment may be beneficial, and assessing the objective severity and subjective impact of bother. Although many, including the author, believe that urodynamic studies are helpful in defining the underlying pathophysiology in cases with incontinence, these tests have not been proven to have adequate sensitivity, specificity, or predictive value (Chapple et al., 2005). The International Consensus Meeting on Incontinence concluded that although urodynamic studies such as frequency-volume charts and pad tests were useful, there was inadequate evidence to justify pressure-flow studies for routine testing as either entry criteria or outcome measures in clinical trials, and they recommended that most large-scale clinical trials should enroll patients by carefully defined symptom-driven criteria when the treatment will be given on an empirical basis (Abrams et al., 2005).`, 
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `Which of the following is not an indication for retropubic repair of SUI?`,
        q2: ``,
        q3: [],
        option: [`A patient who needs a concomitant hysterectomy that cannot be performed vaginally`, 
        `A patient with urethral descent with straining and SUI`, 
        `A patient with limited vaginal access`, 
        `A patient who frequently generates high intra-abdominal pressure due to a chronic cough`, 
        `A patient with inadequate vaginal length or mobility of the vaginal tissues`],
        optionStyleType: `st-lower-alpha`,
        answer: [4],
        ansText:`Rationale: <!--<b>e. A patient with inadequate vaginal length or mobility of the vaginal tissues.</b>--> Although it has been suggested that a retropubic colposuspension should be considered in patients who frequently generate high intra-abdominal pressure (e.g., those with chronic cough from obstructive pulmonary disease and women in strenuous occupations), it has also been argued that these patients may be better served by a pubovaginal sling as well. <b>There may be specific indications for a retropubic approach for the correction of anatomic SUI, namely:</b><br/><br/>• <b>A patient undergoing a laparotomy for concomitant abdominal surgery that cannot be performed vaginally.</b><br/>• <b>In cases with limited vaginal access.</b><br/><br/><b>Conversely, contraindications include:</b><br/><br/>• <b>If there is a history of prior failed incontinence procedures, the existence of significant sphincteric deficiency must be suspected, even if hypermobility exists, and consideration given to performing a pubovaginal sling.</b><br/>• <b>In cases with a pan-pelvic floor weakness, a colposuspension should not be used in isolation but should be used as part of a comprehensive approach to the pelvic floor and be combined as appropriate with other alternative pelvic floor repair procedures.</b> Although lateral defect cystocele and enterocele lend themselves to retropubic repair, central defect cystocele, rectocele, and introital deficiency do not.<br/>• <b>In cases in which there is an inadequate vaginal length or mobility of the vaginal tissues, such as after previous vaginal surgery or irradiation or after a previous vaginal incontinence procedure, a colposuspension should not be used.</b><br/>• <b>A retropubic colposuspension does not always adequately correct the associated vaginal prolapse that frequently coexists with bladder neck hypermobility.</b>`, 
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `Which of the following statements is TRUE regarding retropubic procedures for incontinence?`,
        q2: ``,
        q3: [],
        option: [`It is important to avoid dissecting the old retropubic adhesions from prior incontinence procedures because these may contribute to continence.`, 
        `Nonabsorbable sutures are better than absorbable sutures for retropubic suspension procedures.`, 
        `It may be necessary to open the bladder to facilitate identification of the bladder margins and bladder neck.`, 
        `A urethral Foley catheter is preferred for bladder drainage because it is more comfortable and associated with fewer urinary tract infections and earlier resumption of voiding.`, 
        `The retropubic space must be drained after the procedure to prevent bleeding.`],
        optionStyleType: `st-lower-alpha`,
        answer: [2],
        ansText:`Rationale: <!--<b>c. It may be necessary to open the bladder to facilitate identification of the bladder margins and bladder neck.</b>--> In open retropubic suspension procedures, good access to the retropubic space is crucial. This is best performed with the patient in the supine position with the legs abducted, in either a low or a modified dorsal lithotomy position using stirrups, allowing access to the vagina during the procedure and a perineoabdominal progression. A urethral Foley catheter is inserted; the catheter balloon is used for subsequent identification of the urethra and bladder neck and is invaluable in allowing palpation of the edges of the bladder by appropriate manipulation. A Pfannenstiel or lower midline abdominal incision is made, separating the rectus muscles in the midline and sweeping the anterior peritoneal reflection off the bladder. It is essential to optimize the access to the retropubic space, and if a Pfannenstiel skin incision is made, it is advisable to utilize the suprapubic V modification described by Turner-Warwick and colleagues (1974). Likewise, whatever incision is made, extra valuable access to the retropubic space is obtained by extending the division of the rectus muscles right down to the pubic bone and elevating the aponeurotic insertion of the rectus muscle right off the upper border of the pubic bone.<br/><br/>The retropubic space is then developed by teasing away the retropubic fat and underlying retropubic veins from the back of the pubic bone. The bladder neck, anterior vaginal wall, and urethra are then easy to identify—often facilitated by the presence of the Foley catheter balloon. In patients who have had previous retropubic surgery, the dissection is performed sharply, and it is important to take down all old retropubic adhesions, particularly in the presence of a prior failed repair. <b>If difficulty is encountered in the identification of the bladder neck, the bladder may be partially filled or even opened to identify its limits; an examining finger in the vagina is invaluable in aiding the dissection</b> (Symmonds, 1972; Gleason et al., 1976).<br/><br/>It is important to identify the lateral limits of the bladder as it reflects off the vaginal wall, because only in this manner can one avoid inadvertent suturing of the bladder itself. Dissection over the bladder neck and urethra in the midline is to be avoided so as to not damage the intrinsic musculature. The lateral bladder wall may be “rolled off” medially and cephalad from the vaginal wall using a mounted swab and by using countertraction with a finger in the vagina. In the author’s experience, it is necessary to incise the endopelvic fascia. Occasional venous bleeding from the large vaginal veins is controlled by suture ligature, although it often resolves with tying of elevating sutures. To aid in the identification of the lateral margin of the bladder, it is helpful to displace the balloon of the Foley catheter into the lateral recess, where it can be easily palpated through the bladder wall.<br/><br/>Absorbable sutures were used in the original descriptions of the MMK procedure (chromic catgut), Burch colposuspension (chromic catgut), and vagino-obturator shelf procedure (polyglycolic acid or polydioxanone), whereas the original paravaginal repair used nonabsorbable sutures (silicon-coated Dacron). Fibrosis during subsequent healing is likely to be the most important factor in providing continued fixation of the perivaginal fascia to the suspension sites (Tanagho, 1996); nevertheless, some surgeons believe that a nonabsorbable suture material is better because of the risk of suture dissolution before the development of adequate fibrosis (Penson and Raz, 1996). <b>Clearly the choice of suspension suture material is personal, but it must be remembered that nonabsorbent sutures eroding into the lumen of the bladder are a not uncommon complication and a not-uncommon source of medical litigation</b> (Woo et al., 1995).<br/><br/>Some degree of immediate postoperative voiding difficulty can be expected after retropubic suspensions (Lose et al., 1987; Colombo et al., 1996). Immediately postoperatively, bladder drainage may take the form of a urethral or a suprapubic catheter, generally based on surgeon preference. A voiding trial is usually performed around the fifth day postoperatively. However, there is some evidence that a suprapubic catheter may be advantageous with respect to a lower incidence of asymptomatic and febrile urinary tract infection and earlier resumption of normal bladder function (Andersen et al., 1985; Bergman et al., 1987). In addition, the use of a suprapubic tube is generally more comfortable, allows the patient to participate in catheter management, and avoids the need for clean intermittent catheterization. Catheterization can be discontinued when efficient voiding has resumed, which is usually indicated by a postvoid residual volume either less than 100 mL or less than 30% of the functional bladder volume.<br/><br/>A tube drain may be placed in the retropubic space when there is concern about ongoing bleeding from perivaginal veins that may prove difficult to control with suture and electrocautery. Often, tying the suspension sutures is sufficient to stop this bleeding, but when it persists, drainage of the retropubic space is indicated. The drain is generally removed on the first to third day, when minimal output is noted.`, 
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `Which of the following statements is TRUE regarding the Marshall-Marchetti-Krantz (MMK) procedure?`,
        q2: ``,
        q3: [],
        option: [`It is important to elevate the midurethra and external sphincter in particular.`, 
        `It carries little risk of causing urethral obstruction.`, 
        `It is associated with osteitis pubis.`, 
        `A better than 90% cure rate can be expected in the long term.`, 
        `The sutures should incorporate a full thickness of the vaginal wall and lateral urethral wall.`],
        optionStyleType: `st-lower-alpha`,
        answer: [2],
        ansText:`Rationale: <!--<b>c. It is associated with osteitis pubis.</b>--> <b>Complications occur in up to 21% of cases (Mainprize, 1988), and the placement of sutures through the pubic symphysis incurs the risk of osteitis pubis, a potentially devastating complication of the MMK procedure that has been reported in 0.9% to 3.2% of patients</b> (Lee et al., 1979; Mainprize, 1988; Zorzos and Paterson, 1996). Patients usually present 1 to 8 weeks postoperatively with acute pubic pain radiating to the inner thighs and aggravated by moving. Physical examination reveals tenderness over the pubic symphysis, and radiography demonstrates haziness to the borders of the pubic symphysis and possibly lytic changes. Treatment is with bed rest, analgesics, and possibly corticosteroids (Lee et al., 1979).`, 
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `Which of the following is TRUE of the Burch colposuspension?`,
        q2: ``,
        q3: [],
        option: [`It is appropriate only for patients with adequate vaginal mobility and capacity.`, 
        `The repair is performed between the vagina and the arcus tendineus fasciae pelvis bilaterally.`, 
        `It is less effective than a tension-free vaginal tape procedure.`, 
        `It is less effective than a paravaginal repair.`, 
        `It is more effectively performed via a vaginal approach.`],
        optionStyleType: `st-lower-alpha`,
        answer: [0],
        ansText:`Rationale: <!--<b>a. It is appropriate only for patients with adequate vaginal mobility and capacity.</b>--> <b>The Burch retropubic colposuspension, which has undergone few modifications since its original description, is appropriate only if the patient has adequate vaginal mobility and capacity to allow the lateral vaginal fornices to be elevated toward and approximated to the Cooper ligament on either side.</b>`, 
        state: `notAnswered`,
        userAnswered: []
    ,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`        ,
        type: `MCSS`},
    {
        q: `Laparoscopic retropubic colposuspension is advantageous versus open colposuspension because:`,
        q2: ``,
        q3: [],
        option: [`it is technically simple to perform.`, 
        `it provides access for repair of an associated central defect cystocele.`, 
        `it is more effective than an open colposuspension.`, 
        `it is associated with shorter hospitalization and recovery times.`, 
        `it is associated with shorter operating times.`],
        optionStyleType: `st-lower-alpha`,
        answer: [3],
        ansText:`Rationale: <!--<b>d. It is associated with shorter hospitalization and recovery times.</b>--> Proposed advantages to the laparoscopic approach include improved intraoperative visualization, less postoperative pain, shorter hospitalization, and quicker recovery times (Liu, 1993). Disadvantages include greater technical difficulty with resultant longer operating times and higher operating costs (Paraiso et al., 1999).<br/><br/>The last major publication in this field was a meta-analysis of all of the comparative studies published between 1995 and 2006 of laparoscopic versus open colposuspension (Tan et al., 2007). End points evaluated were operative outcomes and subjective/objective cure. A random-effect model was used and sensitivity analysis performed to account for bias in patient selection. Sixteen studies matched the selection criteria, reporting on 1807 patients, of whom 861 (47.6%) underwent laparoscopic and 946 (52.4%) underwent open colposuspension. Length of hospital stay and return to normal life were significantly reduced after laparoscopic surgery. These findings remained consistent on sensitivity analysis. Bladder injuries occurred more often in the laparoscopic group, but only with marginal statistical significance. Comparable bladder injury rates were found when studies were matched for quality, year, and randomized trials. Cure rates were similar between the two procedures at 2-year follow-up.`, 
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `Common complications specific to retropubic suspension procedures include:`,
        q2: ``,
        q3: [],
        option: [`bladder denervation.`, 
        `detrusor sphincter dyssynergia.`, 
        `postoperative voiding difficulty.`, 
        `detrusor underactivity.`, 
        `genitourinary tract fistulae.`],
        optionStyleType: `st-lower-alpha`,
        answer: [2],
        ansText:`Rationale: <!--<b>c. Postoperative voiding difficulty.</b>--> As with any major abdominal or pelvic surgical procedure, intraoperative and perioperative complications that may occur after a retropubic suspension include bleeding, injury to genitourinary organs (bladder, urethra, ureter), pulmonary atelectasis and infection, wound infection or dehiscence, abscess formation, and venous thrombosis/embolism. <b>Other common complications more specific to retropubic suspension procedures include postoperative voiding difficulty, DO, and vaginal prolapse.</b><br/><br/>Nevertheless, the reported incidence of these problems is relatively low. In their meta-analysis, Leach and associates (1997) noted a 3% to 8% transfusion rate for retropubic suspensions and no significant difference in the overall medical and surgical complication rates among retropubic suspensions, needle suspensions, anterior colporrhaphy, and pubovaginal slings.<br/><br/>Ureteral obstruction has been reported rarely after Burch colposuspension, and it usually results from ureteral kinking after elevation of the vagina and bladder base, although direct suture ligation of the ureter can occur (Applegate et al., 1987). If identified intraoperatively, it is best remedied by removal of the offending ligature and temporary placement of a ureteral stent. The so-called <b><i>post-colposuspension syndrome</i></b>, which has been described as pain in one or both groins at the site of suspension, has been noted in as many as 12% of patients after a Burch colposuspension (Galloway et al., 1987). More recently, Demirci and associates (2001) reported the occurrence of groin or suprapubic pain in 15 of 220 women (6.8%) after Burch colposuspension with a follow-up of 4.5 years.`, 
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `Postoperative voiding difficulty after a retropubic suspension procedure:`,
        q2: ``,
        q3: [],
        option: [`is more likely if there is preexisting detrusor dysfunction.`, 
        `may be due to detrusor sphincter dyssynergia.`, 
        `is most likely to occur with undercorrection of the urethral axis.`, 
        `should be managed by ureterolysis within 1 month.`, 
        `occurs in less than 1% of patients.`],
        optionStyleType: `st-lower-alpha`,
        answer: [0],
        ansText:`Rationale: <!--<b>a. Is more likely if there is preexisting detrusor dysfunction.</b>--> Postoperative voiding difficulty after any type of retropubic suspension is not uncommon, and undoubtedly its occurrence is more likely if there is preexisting detrusor dysfunction or denervation resulting from extensive perivesical dissection. In most cases, however, it is the result of overcorrection of the urethral axis, owing to sutures being inappropriately placed or excessively tightened. If they are placed too medially, sutures may also transfix the urethra or distort it.<br/><br/>Preoperatively, at-risk patients may be identified by their history of prior voiding dysfunction or episodes of urinary retention. Preoperatively, these women should be counseled carefully about the potential for postoperative voiding difficulty and the possible need for self-catheterization. Their incontinence should be of sufficient magnitude that its correction offsets the risk of the need for self-catheterization.<br/><br/>Women with post-cystourethropexy voiding problems who have obstruction often do not exhibit the classic urodynamic features of obstruction. However, the history of postoperative voiding symptoms and associated new-onset bladder irritative symptoms and a finding of a retropubically angulated and fixed urethra generally indicate that obstruction does exist (Carr and Webster, 1997). In such cases, revision of the retropubic suspension by releasing the urethra into a more anatomic position resolves voiding symptoms in as many as 90% of cases (Webster and Kreder, 1990; Nitti and Raz, 1994; Carr and Webster, 1997).<br/><br/><b>The meta-analysis by Leach and coworkers (1997) noted that the risk of temporary urinary retention lasting more than 4 weeks postoperatively was 5% for all retropubic suspensions, the risk for permanent retention was estimated to be less than 5%, and these risks were not significantly different from those for needle suspensions or pubovaginal slings.</b>`, 
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `Which of the following statements is TRUE regarding DO and retropubic suspension procedures?`,
        q2: ``,
        q3: [],
        option: [`Preoperative DO is a contraindication to a retropubic suspension because it increases the risk of postoperative DO.`, 
        `New-onset DO after a suspension procedure performed for SUI invariably resolves within 3 months.`, 
        `DO occurs de novo, on average in fewer than 2% of the patients reported in the literature.`, 
        `A history of voiding symptoms and new-onset storage symptoms as well as a retropubically angulated urethra usually suggests obstruction.`, 
        `DO is not causally related.`],
        optionStyleType: `st-lower-alpha`,
        answer: [3],
        ansText:`Rationale: <!--<b>d. A history of voiding symptoms and new-onset irritative symptoms as well as a retropubically angulated urethra usually suggests obstruction.</b>--> <b>Bladder hyperactivity commonly accompanies anatomic SUI, and its incidence preoperatively has been reported to be as high as 30% in patients undergoing either first correction or repeated operations</b> (McGuire, 1981). Provided that it is considered as a diagnosis, urodynamic study is performed to show whether DO is present, an attempt at treatment of the related overactive bladder symptoms has been made (with or without success), and the patient has been advised that the presence of DO will increase the risk of continuing storage symptoms postoperatively, then preoperative bladder overactivity does not contraindicate a retropubic suspension procedure, provided that anatomic SUI has also been demonstrated. <b>In the majority of cases the bladder overactivity symptoms resolve after surgical repair</b> (McGuire, 1988). Leach and coworkers’ meta-analysis (1997) found the risk of urgency after a retropubic suspension was 66% if urgency and DO were present preoperatively, 36% if there was urgency but no documented overactivity preoperatively, and only 11% if there was neither urgency nor overactivity preoperatively. There was no significant difference in the incidence of postoperative urgency among retropubic suspensions, needle suspensions, and pubovaginal slings. Postoperative urgency was noted in only 0.9% of MMK procedures in Mainprize and Drutz’s meta-analysis of 15 series (1988), although Parnell and associates (1982) reported that 28.5% of their patients developed postoperative storage symptoms. Jarvis’s meta-analysis (1994) of Burch colposuspensions found the incidence of de novo bladder overactivity to be 3.4% to 18%. More recently Smith and associates quote a figure for postoperative DO of 6.6% for colposuspension (range 1.0% to 16.6%), whereas the incidence of postoperative urgency or urgency incontinence after the paravaginal/vagino-obturator shelf repair has been reported to be 0% to 6% (Shull and Baden, 1989; German et al., 1994; Colombo et al., 1996).<br/><br/>For those patients in whom postoperative storage symptoms persist, proven to be associated with DO and intractable to management with anticholinergic therapy and behavioral modification, surgical techniques including intravesical botulinum toxin therapy, neuromodulation, augmentation cystoplasty, or detrusor myectomy may be indicated.<br/><br/>Bladder storage symptoms arising de novo after retropubic suspension may be associated with bladder outlet obstruction. This premise is supported by the frequent coexistence of these symptoms with impaired voiding after suspension procedures and confirmed by the finding that ureterolysis, by freeing the urethra from an obstructed position, often resolves both storage and voiding symptoms (Raz, 1981; Webster and Kreder, 1990).`, 
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `Prolapse as a reported complication of retropubic repairs:`,
        q2: ``,
        q3: [],
        option: [`is rarely associated with a central defect cystocele.`, 
        `results in genitourinary prolapse as a sequel to Burch colposuspension to occur in less than 10% of women.`, 
        `may aggravate posterior vaginal wall weakness, predisposing to enterocele.`, 
        `will be prevented by a synchronous hysterectomy.`, 
        `occurs only rarely after a paravaginal repair.`],
        optionStyleType: `st-lower-alpha`,
        answer: [2],
        ansText:`Rationale: <!--<b>c. May aggravate posterior vaginal wall weakness, predisposing to enterocele.</b>--> Retropubic suspensions alter vaginal and bladder base anatomy, and, thus, postoperative vaginal prolapse is a potential complication. <b>Genitourinary prolapse has been reported as a sequel to Burch colposuspension in 22.1% of women (range 9.5% to 38.2%) by Smith and colleagues (2005) in their review of the literature. The Burch colposuspension, because of lateral vaginal elevation, may aggravate posterior vaginal wall weakness, predisposing to enterocele.</b> The incidence varies between 3% and 17% (Burch, 1961, 1968; Galloway et al., 1987; Wiskind et al., 1992), and because of this, prophylactic obliteration of the cul-de-sac of Douglas is sometimes considered when performing retropubic suspensions (Shull and Baden, 1989; Turner-Warwick and Kirby, 1993). <b>However, simultaneous hysterectomy is not recommended prophylactically because it does not enhance the outcome of a retropubic suspension and should be performed only if there is concomitant uterine pathology</b> (Milani et al., 1985; Langer et al., 1988). Although the Burch colposuspension and paravaginal/vagino-obturator shelf repair both correct lateral defect cystourethroceles, recurrent cystourethroceles were noted in 11% and 39% of Burch colposuspensions and paravaginal repairs, respectively (Colombo et al., 1996). In Mainprize and Drutz’s review (1988), postoperative cystocele was noted in only 0.4% of patients after an MMK procedure.<br/><br/>Wiskind and coworkers (1992) noted that 27% of patients who had undergone a Burch colposuspension developed prolapse requiring surgery: rectocele in 22%, enterocele in 11%, uterine prolapse in 13%, and cystocele in 2%. More recently, it has been suggested that most women are asymptomatic and fewer than 5% have been reported to request further surgery (Smith et al., 2005). Ward and associates (2004) reported 4.8% of women needing a posterior repair whereas Kwon and coworkers (2003) reported 4.7% requiring subsequent pelvic reconstruction.<br/><br/>Because retropubic suspensions are unable to correct central defect cystoceles, patients must be carefully examined preoperatively to exclude their presence.`, 
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `From comparative studies in the literature, which is correct about open retropubic colposuspension?`,
        q2: ``,
        q3: [],
        option: [`It is not as effective as a pubovaginal sling.`, 
        `It is not effective in patients with a low leak point pressure.`, 
        `It is no more effective than an anterior colporrhaphy.`, 
        `It is less effective than a tension-free vaginal tape procedure.`, 
        `It is no more effective than a paravaginal repair.`],
        optionStyleType: `st-lower-alpha`,
        answer: [0],
        ansText:`Rationale: <!--<b>a. It is not as effective as a pubovaginal sling.</b>--> A total of 655 women were randomly assigned to study groups: 326 to undergo the sling procedure and 329 to undergo the Burch colposuspension; 520 women (79%) completed the outcome assessment (Aldo et al., 2007). At 24 months, success rates were higher for women who underwent the sling procedure than for those who underwent the Burch colposuspension for both the overall category of success (47% vs. 38%, <b><i>P</i></b> = .01) and the category specific to SUI (66% vs. 49%, <b><i>P</i></b> &lt; .001). There was no significant difference between the sling and Burch colposuspension groups in the percentage of patients who had serious adverse events (13% and 10%, respectively; <b><i>P</i></b> = .20). However, more women who underwent the sling procedure had adverse events than in the Burch colposuspension group, with 415 events among 206 women in the sling group as compared with 305 events among 156 women in the Burch colposuspension group. This difference was due primarily to urinary tract infections: 157 women in the sling group (48%) had 305 events and 105 women in the Burch colposuspension group (32%) had 203 events. When urinary tract infections were excluded, although the rates of adverse events were similar in the two groups, there was more difficulty voiding. The distribution of time to return to normal voiding differed significantly between the two groups: Voiding dysfunction was more common in the sling group than in the Burch colposuspension group (14% vs. 2%, <b><i>P</i></b> &lt; .001). Consequently, surgical procedures to reduce voiding symptoms or improve urinary retention were performed exclusively in the sling group, in which 19 patients underwent 20 such procedures (63% vs. 47%, <b><i>P</i></b> &lt; .001). Treatment satisfaction rates for the 480 subjects who answered the satisfaction question at 24 months were significantly higher in the sling group than in the Burch colposuspension group (86% vs. 78%, <b><i>P</i></b> = .02). A further analysis of this study focused on sexual activity as assessed by the Pelvic Organ Prolapse/Urinary Incontinence Sexual Questionnaire (PISQ-12) among those sexually active at baseline and 2 years after surgery (Brubaker et al., 2009). This report demonstrated that sexual function improves after successful surgery and does not differ between Burch colposuspension and sling procedures.<br/><br/>It can therefore be reliably concluded that in specialist centers working in a standardized fashion, the autologous fascial sling results in a higher rate of successful treatment of SUI but also greater morbidity than the Burch colposuspension.<br/><br/>Comparisons between the MMK and the Burch colposuspension procedures have generally yielded similar results. Three articles that reviewed the literature on incontinence procedures all found retropubic suspensions to be more effective than either needle suspensions or anterior colporrhaphies (Jarvis, 1994; Black and Downs, 1996; Leach et al., 1997). Most studies in the literature have not demonstrated a significant difference in cure rates between retropubic suspensions (generally a Burch colposuspension) and pubovaginal slings (Jarvis, 1994; Black and Downs, 1996; Leach et al., 1997). The literature on the paravaginal repair is sparse. The only randomized study that compared the Burch colposuspension with a paravaginal repair found significantly greater subjective and objective cure with the Burch colposuspension (Colombo et al., 1996). At this point, the tension-free vaginal tape procedure appears to be at least equivalent to the Burch colposuspension.`, 
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`}

    



];
