var quiz = [
  {
    q: `Which of the following statements regarding anterior colporrhaphy is FALSE?`,
    q2: ``,
    q3: [],
    option: [
      `Anterior colporrhaphy is not used to treat stress incontinence.`,
      `Recent series report a 40% recurrence rate for standard anterior colporrhaphy.`,
      `The most likely contributing factor for failure of anterior compartment repairs is the concomitant presence of other compartmental defects.`,
      `Cystoscopy with indigo carmine is not routinely necessary.`,
      `Ensuring that the bladder is drained before perforating the endopelvic fascia may decrease bladder injuries.`,
    ],
    optionStyleType: `st-upper-alpha`,
    answer: [3],
    ansText: `Rationale: <!--<b>d. Cystoscopy with indigo carmine is not routinely necessary.</b>--> Cystoscopy after the administration of indigo carmine or methylene blue is recommended as a routine practice after anterior colporrhaphy. If blue-tinged urine is not seen effluxing from each ureteral orifice, catheterization may be considered before taking down the plication sutures. Appropriate steps must be performed to ensure ureteral patency, including takedown of the sutures.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `A 50-year-old woman presents with symptoms of voiding difficulty and vaginal bulging. She has had a prior hysterectomy. In the supine position she demonstrates stage 3 prolapse with the Ba point at +4. Her C point is −4 with a TVL of 9 cm, and her Bp is −3. With prolapse reduction there is no stress incontinence. Which of the following repairs would be most appropriate?`,
    q2: ``,
    q3: [],
    option: [
      `Vault suspension alone`,
      `Vault suspension with anterior repair`,
      `Vault suspension with anterior repair and anti-incontinence procedure`,
      `Vault suspension with anterior repair, anti-incontinence procedure, and posterior repair`,
      `Anterior repair alone`,
      `Anterior and posterior repair`,
    ],
    optionStyleType: `st-upper-alpha`,
    answer: [1],
    ansText: `Rationale: <!--<b>b. Vault suspension and anterior repair.</b>--> The patient has stage 3 anterior vaginal wall prolapse at the apical descent. These defects are best addressed by restoring the apical and anterior support. Failure rates for an anterior repair alone are unacceptably high. As no stress urinalysis incontinence was demonstrated, there is no absolute indication for an anti-incontinence procedure. The support of the posterior compartment is intact and posterior repair is not indicated.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `Which surgical technique of rectocele repair is most associated with postoperative dyspareunia?`,
    q2: ``,
    q3: [],
    option: [
      `Levator plication`,
      `Site-specific repair`,
      `Site-specific repair with biologic interposition graft`,
      `Transanal repair of rectocele`,
      `Perineorrhaphy`,
    ],
    optionStyleType: `st-upper-alpha`,
    answer: [0],
    ansText: `Rationale: <!--<b>a. Levator plication.</b>--> Levator plication was associated with high rates of de novo postoperative dyspareunia. As such, it has largely been abandoned.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `Which symptom changes the least following site-specific posterior colporrhaphy?`,
    q2: ``,
    q3: [],
    option: [
      `Dyspareunia`,
      `Constipation`,
      `Vaginal mass`,
      `Splinting`,
      `Vaginal pressure or pain`,
    ],
    optionStyleType: `st-upper-alpha`,
    answer: [1],
    ansText: `Rationale: <!--<b>b. Constipation.</b>--> Constipation may be associated with dysmotility disorders of the rectum that do not improve with an anatomic repair. The symptoms most likely to improve are dyspareunia, the need for vaginal splinting, vaginal mass, and pressure.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `When planning a multi-compartment repair with an outlet procedure, which of the following is the preferred sequence of compartmental approaches?`,
    q2: ``,
    q3: [],
    option: [
      `Apical, anterior, posterior, sling`,
      `Sling, apical, anterior, posterior`,
      `Apical, anterior, sling, posterior`,
      `Posterior, anterior, apical, sling`,
      `Anterior, posterior, sling, apical`,
    ],
    optionStyleType: `st-upper-alpha`,
    answer: [2],
    ansText: `Rationale: <!--<b>c. Apical, anterior, sling, posterior.</b>--> The apical compartment should always be addressed first. The anterior compartment should preferentially be repaired before the posterior compartment when an anti-incontinence procedure is being performed, should an inadvertent rectal injury occur. Once the sling incision is closed, a rectal injury can be repaired and the mesh is uninvolved.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `When performing a posterior repair, the literature currently supports which of the following methods to maximize success rates and decrease complications, namely dyspareunia?`,
    q2: ``,
    q3: [],
    option: [
      `Traditional posterior colporrhaphy`,
      `Mesh augmented posterior colporrhaphy`,
      `Traditional posterior colporrhaphy with levator plication`,
      `Porcine graft augmented posterior colporrhaphy`,
      `Cadaveric graft augmented posterior colporrhaphy`,
    ],
    optionStyleType: `st-upper-alpha`,
    answer: [0],
    ansText: `Rationale: <!--<b>a. Traditional posterior colporrhaphy.</b>--> Both mesh-augmented repairs and levator plication report a higher incidence of complications, namely dyspareunia. As far as success is concerned, neither porcine nor biologic interposition grafts create a superior outcome when compared to traditional colporrhaphy.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `Which of the following procedures have proven to be ineffective in the treatment of stress urinary incontinence?`,
    q2: ``,
    q3: [],
    option: [
      `Synthetic midurethral sling`,
      `Anterior colporrhaphy`,
      `Burch colposuspension`,
      `Autologous pubovaginal sling`,
      `Vaginal paravaginal repair`,
      `b and e`,
      `All of the above`,
    ],
    optionStyleType: `st-upper-alpha`,
    answer: [5],
    ansText: `Rationale: <!--<b>f. b and e.</b>--> Neither anterior colporrhaphy nor vaginal paravaginal repair have proven efficacy for the treatment of stress urinary incontinence. The other options are all viable treatment options.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `Which of the following statements regarding anterior compartment prolapse and/or repair is false?`,
    q2: ``,
    q3: [],
    option: [
      `An anterior compartment defect may be central, lateral, or combined.`,
      `A central defect results from midline separation or attenuation of the pubocervical (perivesical) fascia.`,
      `A lateral defect results when the pubocervical fascia detaches from the arcus tendineus fascia pelvis (ATFP).`,
      `Most anterior compartment defects have concomitant lateral and/or apical defects.`,
      `Isolated anterior colporrhaphy is not recommended when additional defects are present.`,
      `Anterior compartment prolapse repair also suspends the vaginal apex.`,
    ],
    optionStyleType: `st-upper-alpha`,
    answer: [5],
    ansText: `Rationale: <!--<b>f. Anterior compartment prolapse repair also suspends the vaginal apex.</b>--> An anterior colporrhaphy restores the level 2 support, but has no effect on the apex, which is level 1 support. The other statements are true.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `Which of the following defects requires surgical correction?`,
    q2: ``,
    q3: [],
    option: [
      `Ba −1 in an asymptomatic 48-year-old`,
      `Bp −3 with complaints of constipation`,
      `C −9, TVL 10, Ba −3`,
      `Ba 0 with complaint of a vaginal bulge`,
      `C −8, TVL 10, Ba −2`,
    ],
    optionStyleType: `st-upper-alpha`,
    answer: [3],
    ansText: `Rationale: <!--<b>d. Ba 0 with complaint of a vaginal bulge.</b>--> Only symptomatic prolapse requires repair. Repair of prolapse will have little effect on constipation, as this is usually a motility issue. Choices c and e demonstrate normal vaginal exams.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `A 31-year-old woman with a history of four prior vaginal deliveries presents to your office with symptoms of a vaginal bulge. On pelvic exam, you note the cervix is protruding 4 cm beyond the introitus, the anterior vaginal wall bulges just beyond the hymenal ring, and the posterior wall seems to be well supported. Total vaginal length is about 9 cm. The patient is not interested in using a pessary. She desires future fertility. She wants you to do the operation that will reduce her chance of requiring another surgery for prolapse in the future.<br/><br/>The next best step in management is:`,
    q2: ``,
    q3: [],
    option: [
      `Vaginal hysterectomy and uterosacral ligament suspension`,
      `Vaginal hysterectomy and sacrospinous ligament suspension`,
      `Transvaginal suture hysteropexy`,
      `Abdominal sacrohysteropexy with mesh`,
      `Abdominal hysterectomy and sacrocolpopexy`,
    ],
    optionStyleType: `st-upper-alpha`,
    answer: [3],
    ansText: `Rationale: <!--<b>d. Abdominal sacrohysteropexy with mesh.</b>--> Since she desires future fertility, we recommended that a hysterectomy not be performed for the management of her prolapse. This eliminates answers a, b, and e. Of the remaining two choices, the one that has the best potential of long-term success is the sacrohysteropexy. During this operation, a rectangular piece of mesh is sewn to the posterior vaginal wall (all the way down to the perineum), the cervix, and the lower uterine segment. An inverted U-shaped mesh is then sewn to the anterior vaginal wall all the way down to the pubic bone and lower portion of the anterior rectus abdominis fascia. Due to the fact that mesh is fixated to the lower uterine segment, a C-section should be recommended as the mode of delivery.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `A 48-year-old active woman with incomplete uterovaginal prolapse with cervical elongation desires a transvaginal uterine-sparing procedure. POQ point C is +2 and Point D is −7. Select the most appropriate type of uterine-preserving POP reparative surgery for her condition.`,
    q2: ``,
    q3: [],
    option: [
      `Le Forte colpocleisis`,
      `Sacrohysteropexy`,
      `Manchester procedure`,
      `Sacrospinous cervicopexy`,
      `Uterosacral hysteropexy`,
    ],
    optionStyleType: `st-upper-alpha`,
    answer: [2],
    ansText: `Rationale: <!--<b>c. Manchester procedure.</b>--> The Manchester-Fothergill operation is the most appropriate transvaginal surgery for treatment of hypertrophic cervical elongation co-existing with a well-supported uterine corpus in a woman desiring uterine preservation.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `An 89-year-old woman who has failed numerous pessaries has symptomatic complete uterovaginal prolapse. She is frail, lives in a nursing home, and has medical comorbidities making her high risk for general anesthesia. Select the most appropriate surgical procedure.`,
    q2: ``,
    q3: [],
    option: [
      `Uterosacral hysteropexy`,
      `Sacrospinous cervicopexy`,
      `Sacrohysteropexy`,
      `Le Forte colpocleisis`,
      `Manchester-Fothergill operation`,
    ],
    optionStyleType: `st-upper-alpha`,
    answer: [3],
    ansText: `Rationale: <!--<b>d. Le Forte colpocleisis.</b>--> The Leforte procedure is a partial colpocleisis in which matching rectangular sections of vaginal epithelium are excised from both the anterior and posterior vaginal walls and then fused together by sutures. The procedure can be performed under local anesthesia in patients with significant comorbidities.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `A 54-year-old woman who has a history of multiple laparotomies for treatment of endometriosis and a history of small bowel obstruction requiring resection and anastomosis presents with symptomatic incomplete uterovaginal prolapse. POPQ C is at 1, Point D is −4. During her small bowel surgery, the surgeon noted significant pelvic adhesions involving the uterus, tubes, and ovaries, which were not addressed during that surgery. Select the most appropriate surgical procedure.`,
    q2: ``,
    q3: [],
    option: [
      `Uterosacral hysteropexy`,
      `Sacrospinous cervicopexy`,
      `Sacrohysteropexy`,
      `Le Forte Colpocleisis`,
      `Manchester-Fothergill operation`,
    ],
    optionStyleType: `st-upper-alpha`,
    answer: [1],
    ansText: `Rationale: <!--<b>b. Sacrospinous cervicopexy.</b>--> Sacrospinous hysteropexy is a uterine-sparing procedure for cervical prolapse useful when an abdominal or laparoscopic/robotic procedure may be very difficult, due to presence of intraperitoneal adhesions or previous mesh-augmented ventral hernia repair.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `A 41-year-old woman with symptomatic uterovaginal prolapse with POPQ point C +2, D −6 presents to your office desiring a uterine-sparing procedure. She smokes a half a pack of cigarettes per day and will not quit. She also has a history of two procedures to treat recurrent mid-urethral polypropylene sling exposure. She also has a 5-cm ovarian cyst that appears benign but has been present for 8 months; she desires its removal. She is sexually active and is concerned about pain with intercourse after the procedure. Select the most appropriate surgical procedure.`,
    q2: ``,
    q3: [],
    option: [
      `Uterosacral hysteropexy`,
      `Sacrospinous cervicopexy`,
      `Sacrohysteropexy`,
      `Le Forte colpocleisis`,
      `Manchester-Fothergill operation`,
    ],
    optionStyleType: `st-upper-alpha`,
    answer: [0],
    ansText: `Rationale: <!--<b>a. Uterosacral hysteropexy.</b>--> Uterosacral hysteropexy has been reported using both transvaginal and laparoscopic techniques in which the posterior cul de sac may be closed, the uterosacral ligaments are plicated in the midline, and if severed, then reattached to the cervix. This technique avoids the use of synthetic surgical mesh, for which this patient in the scenario has both known risk factors and complications from previous personal experience. This technique also reduces the risk of dyspareunia that can be associated with deviation of the vaginal axis related to unilateral sacrospinous fixation. The patient also has abdominal pathology and requests it be addressed at this surgery. An abdominal approach to her suspension procedure allows for evaluation and management of abdominal pathology.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `A 28-year-old woman who has Ehlers-Danlos syndrome presents with symptomatic uterovaginal prolapse. Her relevant POPQ is as follows: C +1, TVL 8, D −4. She desires future fertility. She has a history of asthma and problems with chronic constipation. Select the most appropriate procedure for this patient.`,
    q2: ``,
    q3: [],
    option: [
      `Uterosacral hysteropexy`,
      `Sacrospinous cervicopexy`,
      `Sacrohysteropexy`,
      `Le Forte colpocleisis`,
      `Manchester-Fothergill operation`,
    ],
    optionStyleType: `st-upper-alpha`,
    answer: [2],
    ansText: `Rationale: <!--<b>c. Sacrohysteropexy.</b>--> Sacrohysteropexy using a synthetic mesh bridge to suspend the posterior lower uterine segment/proximal cervix from the anterior sacrum (at S1-2) has been reported to be successful in a small series of women with collagen connective tissue disorders and in young women born with bladder exstrophy.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `A 60-year-old patient undergoes a transvaginal hysterectomy (TVH), bilateral salpingo-oophorectomy (BSO), uterosacral ligament suspension, enterocele repair, anterior and posterior repair, and transvaginal tape (TVT) sling procedure for symptomatic uterovaginal prolapse (POPQ point C +3, D-5) and stress urinary incontinence. She presents 6 months postoperative and tells you she is having pain with intercourse. Select the procedure that is the probable cause of her dyspareunia.`,
    q2: ``,
    q3: [],
    option: [
      `Vaginal vault suspension`,
      `Enterocele repair`,
      `TVT sling`,
      `Anterior colporrhaphy`,
      `Posterior colporrhaphy`,
    ],
    optionStyleType: `st-upper-alpha`,
    answer: [4],
    ansText: `Rationale: <!--<b>e. Posterior colporrhaphy.</b>--> Posterior colporrhaphy is associated with the highest rate of dyspareunia—on average around 18% (0%–46%). In general, there is a high prevalence of dyspareunia in women with prolapse, but sexual function does improve with prolapse repair. Improvement in sexual function occurs more often in women who did not have a posterior repair. The uterosacral ligament suspension, anterior repair and enterocele repair are much less likely to cause dyspareunia. However, about 1% to 2% of patients who have undergone high uterosacral ligament suspension can develop sacral nerve entrapment (thigh, buttocks, and low back pain), which can affect sexual function (answer a, b, and d are incorrect). The TVT sling does not affect overall sexual function and satisfaction, but the partners of patients with mesh exposure (&lt;3%) may complain of pain with intercourse (answer C is incorrect). The possible reasons for dyspareunia after posterior repair are the following:<br/><br/>• Inadequate lateral dissection of the rectovaginal septum before plicating<br/>• Aggressive plication of lateral tissue, including levator muscles<br/>• Aggressive trimming of vaginal skin prior to closure<br/>• Poor surgical technique, making introitus too narrow<br/>• Development of vaginal scar tissue, infection, or hematoma<br/>• Vaginal atrophy`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `A 46-year-old woman with vaginal vault prolapse undergoes a laparoscopic sacrocolpopexy for symptomatic vaginal vault prolapse. Her BMI is 19 and she has a history of lupus. The patient is positioned by a new nurse circulator. The surgery lasts 5 hours. When seeing her on POD#1, she is unable to flex her knee, has foot drop, and decreased sensation in the calf. Select the likely nerve affected.`,
    q2: ``,
    q3: [],
    option: [
      `Femoral`,
      `Genitofemoral`,
      `Sciatic`,
      `Brachial plexus`,
      `Obturator`,
      `Common peroneal`,
      `Ilioinguinal`,
      `Iliohypogastric`,
    ],
    optionStyleType: `st-upper-alpha`,
    answer: [2],
    ansText: `Rationale: <!--<b>c. Sciatic.</b>--> Prolonged hyperflexion and external rotation of the hips with knees extended can lead to sciatic nerve injury. This presents with foot drop, inability to flex the knee, and loss in sensation of the calf and lateral foot. One must be careful to properly position the patient; we recommend proper positioning be confirmed by the surgeon. Prolonged hip flexion, abduction, and external rotation may also lead to femoral nerve injury. This presents with weakness of the quadriceps muscle, which makes it difficult to extend the knee (i.e., knee gives out when trying to stand). There is also decrease in sensation of the anterior thigh and medial lower leg. The three big risk factors for neurologic injury because of patient positioning are thinness (BMI &lt;20 kg/m<sup>2</sup>), diabetes mellitus, and time (each additional hour in lithotomy position increases risk).`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `A 57-year-old woman with symptomatic uterovaginal prolapse presents desiring surgical correction of her prolapse. She has no significant comorbidities other than well-controlled hypertension. She is sexually active. She has been menopausal for the last 6 years and reports no postmenopausal bleeding. Her last pap smear was negative for malignancy; she has never had an abnormal pap smear. On manual exam her uterus is small and mobile. Her POPQ is as follows: Aa +3, Ba+5, C +7, Gh 5, Pb 1, TVL 10, Ap −1, Bp −1, D+4. Select the best procedure to address her prolapse.`,
    q2: ``,
    q3: [],
    option: [
      `Anterior and posterior colporrhaphy`,
      `Vaginal hysterectomy with an anterior and posterior colporrhaphy`,
      `Abdominal supracervical hysterectomy with sacrocervicopexy ± anterior and posterior colporrhaphy`,
      `Abdominal hysterectomy`,
      `Lefort colpocleisis`,
    ],
    optionStyleType: `st-upper-alpha`,
    answer: [2],
    ansText: `Rationale: <!--<b>c. Abdominal supracervical hysterectomy with sacrocervicopexy ± anterior and posterior colporrhaphy.</b>--> The patient is sexually active, has no history of post-menopausal bleeding, and has a negative pap smear with no history of abnormal pap smears. A supracervical hysterectomy reduces the risk of graft extrusion at the time of the sacrocervicopexy. The procedure can be done open, laparoscopicly, or robotically; a, b, and d are incorrect because none of them address the apex. Answer e is incorrect because it is an obliterative procedure and she is currently sexually active.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `Which of the procedures listed below to address pelvic organ prolapse has been reported to have the highest risk of ureteral injury?`,
    q2: ``,
    q3: [],
    option: [
      `Sacrospinous ligament suspension`,
      `Uterosacral ligament suspension`,
      `Anterior colporrhaphy`,
      `Transvaginal hysterectomy`,
      `Posterior colporrhaphy`,
    ],
    optionStyleType: `st-upper-alpha`,
    answer: [1],
    ansText: `Rationale: <!--<b>b. Uterosacral ligament suspension.</b>--> In reported studies uterosacral ligament suspension has a ureteral injury risk of 0% to 11% in prolapse surgery. In a systematic review, the rate of ureteral injury following transvaginal hysterectomy was 0.2 per 1000 surgeries. Ureteral injury can occur with anterior colporrhaphy but is uncommon.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `A 51-year-old woman presents 2 months after a laparoscopic sacrocolpopexy with persistent low back pain. She states the pain has been present for the last 3 weeks and it does not feel like it is getting better. She describes the pain as constant and achy. Over-the-counter ibuprofen helps, but the pain never goes away. She admits to intermittent fever and chills but denies abdominal pain, nausea, or vomiting. She admits to having regular bowel movements and denies dysuria. Select the most likely diagnosis.`,
    q2: ``,
    q3: [],
    option: [
      `Herniated disc`,
      `Bowel obstruction`,
      `Osteomyelitis`,
      `Spinal stenosis`,
    ],
    optionStyleType: `st-upper-alpha`,
    answer: [2],
    ansText: `Rationale: <!--<b>c. Osteomyelitis.</b>--> Sacral osteomyelitis is a well-known but fortunately rare complication of sacrocolpopexy, and common presenting symptoms include back pain, fevers, lethargy, and vaginal discharge. Sacral infections after sacrocolpopexies are likely to have a multifactorial origin. One hypothesis is that ischemia from devascularization during surgical dissection provides a microenvironment conducive to infection. It is conceivable that a suture placed too deeply into the vaginal canal or the sacral promontory provides a mechanism by which bacteria can be introduced into the abdominal cavity or into the periosteum of the sacral promontory. Similarly, placement of the sutures into the disc itself can lead to discitis. Sacrocolpopexy presacral sutures are often placed without knowledge of the location of the intervertebral discs. Herniated disc and spinal stenosis are clinical etiologies of back pain, but have not been reported as complications of mesh sacrocolpopexy. Though bowel obstruction can occur after sacrocolpopexy, it would be unusual to present with back pain. This condition more commonly presents with nausea/vomiting.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `You are instructing your first-year fellow through a sacrospinous ligament suspension and tell your fellow that, to avoid complications related to suture placement, the suture should be placed:`,
    q2: ``,
    q3: [],
    option: [
      `1 cm lateral and slightly superior to the ischial spine`,
      `3 cm medial to the ischial spine, slightly below the superior edge of the ligament`,
      `3 cm medial to the ischial spine, superiorly and slightly behind the ligament`,
      `1 cm medial to the sacrum, slightly below the superior edge of the ligament`,
    ],
    optionStyleType: `st-upper-alpha`,
    answer: [0],
    ansText: `Rationale: <!--<b>a. 1 cm lateral and slightly superior to the ischial spine.</b>--> In the area, there is decreased chance of injuring the pudendal nerves or vessels. The pudendal nerves and vessels lie directly posterior to the ischial spine. The suture should not be placed as close as these to the ischial spine. Superiorly and just behind the ligament lies the inferior gluteal vessels and hypogastric venous plexus.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `An 80-year-old woman has recurrent vaginal vault prolapse. She had a sacrospinous ligament fixation 20 years prior. She has not been sexually active for the last 15 years. She has failed numerous pessary trials. She is interested in a surgical procedure with the lowest likelihood for repeat surgery. Select the best procedure.`,
    q2: ``,
    q3: [],
    option: [
      `Mesh sacrocolpopexy`,
      `Vaginal mesh for prolapse`,
      `Sacrospinous ligament fixation`,
      `Colpocleisis`,
    ],
    optionStyleType: `st-upper-alpha`,
    answer: [3],
    ansText: `Rationale: <!--<b>d. Colpocleisis.</b>--> Obliterative procedures have the lowest rates of prolapse recurrence and low rates of reoperation. When compared to native tissue repairs, the use of mesh in pelvic organ prolapse surgery is associated with increased rates of reoperations.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
];
