var quiz = [
    

    {
        q: `A person with cognitive impairment may not be a candidate for which behavioral interventions:`,
        q2: ``,
        q3: [],
        option: [`prompted voiding`, 
        `timed voiding`, 
        `bladder training`, 
        `habit training`],
        optionStyleType: `st-lower-alpha`,
        answer: [2],
        ansText:`Rationale: <!--<b>c. Bladder training.</b>--> Bladder training is an example of “patient-dependent” interventions: it relies on active patient participation. There must be adequate function, learning capability, and motivation of the individual. Bladder training involves patient education regarding lower urinary tract function, setting incremental voiding schedules, and teaching urge control techniques to help patients postpone voiding and adhere to the schedule.`, 
        state: `notAnswered`,
        userAnswered: []
    ,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`        ,
        type: `MCSS`},
    {
        q: `A bladder diary is integral to behavioral therapy because it can:`,
        q2: ``,
        q3: [],
        option: [`help determine functional bladder capacity`, 
        `provide information about symptom improvement`, 
        `determine adherence to pelvic floor muscle training`, 
        `improve understanding of patient’s voiding pattern`, 
        `all of the above`,
        `b and d`],
        optionStyleType: `st-lower-alpha`,
        answer: [5],
        ansText:`Rationale: <!--<b>f. b and d.</b>--> A bladder diary provides information on the type and amount of fluid intake, type and frequency of symptoms, such as incontinence episodes, frequency of urination, the urgency associated with each, and the circumstances or reasons for incontinence episodes, which helps the provider plan appropriate components of behavioral intervention. A bladder diary is also the best noninvasive tool available to objectively monitor the patient’s voiding habits and the effect of treatment on symptoms guiding the use of various treatment components.`, 
        state: `notAnswered`,
        userAnswered: []
    ,
	type: `MCSS`        ,
        type: `MCSS`},
    {
        q: `Which of the following are true about pelvic floor muscle training?`,
        q2: ``,
        q3: [],
        option: [`Pelvic floor muscle training is effective for treating stress, urge, or mixed incontinence in men and women of any age.`, 
        `Pelvic floor muscle training is appropriate for stress or mixed incontinence, but not for urgency incontinence.`, 
        `Pelvic floor muscle training works for women, but not for men.`, 
        `Pelvic floor muscle training is not effective for older people.`, 
        `Pelvic floor muscle training is useful for mild-moderate incontinence, but not severe incontinence.`],
        optionStyleType: `st-lower-alpha`,
        answer: [0],
        ansText:`Rationale: <!--<b>a. Pelvic floor muscle training is effective for treating stress, urge, or mixed incontinence in men and women of any age.</b>--> Behavioral interventions are well established for treating stress and urgency UI and OAB. Because behavioral treatments are effective and essentially risk free, they are the mainstay of conservative treatment and are recommended for both men and women of all ages as first-line therapy by several guidelines and consensus panels.`, 
        state: `notAnswered`,
        userAnswered: []
    ,
	type: `MCSS`,
	type: `MCSS`        ,
        type: `MCSS`},
    {
        q: `When teaching the urge suppression technique, patients are encouraged to:`,
        q2: ``,
        q3: [],
        option: [`Stay near a bathroom as much as possible, so they won’t have far to go when they feel an urge to void.`, 
        `Stay away from the bathroom until they feel an urge to void. Then get to the bathroom as soon as possible.`, 
        `Stay away from the bathroom until urgency or the urge to void occurs. Then they should sit down, practice urge suppression techniques, and once the urge has passed, slowly walk to the bathroom to void.`, 
        `Wait as long as possible to go to the bathroom to increase bladder capacity.`],
        optionStyleType: `st-lower-alpha`,
        answer: [2],
        ansText:`Rationale: <!--<b>c. Stay away from the bathroom until urgency or the urge to void occurs. Then they should sit down, practice urge suppression techniques, and once the urge has passed, slowly walk to the bathroom to void.</b>--> Patients are taught not to feel compelled to rush to the nearest bathroom when they feel the urge to void, believing that they are about to lose control. With behavioral training, they learn how this natural “gotta go” response is actually counter-productive, because it increases physical pressure on the bladder, increases the feeling of fullness, exacerbates urgency, and triggers detrusor contraction. Further, as the patient approaches the toilet, visual cues can trigger urgency and incontinence. To avoid this conditioned response, patients are taught not to rush to the bathroom when they feel the urge to void. Instead, they are advised to stay away from the bathroom, so as to avoid exposure to cues that trigger urgency. They are taught strategies to suppress urgency prior to walking to the toilet.`, 
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `When patients are trying to calm down urgency and prevent leakage, which of the following works BEST?`,
        q2: ``,
        q3: [],
        option: [`Crossing the legs`, 
        `Squeezing the pelvic floor muscles while rushing to the bathroom`, 
        `Squeezing the pelvic floor muscles while sitting still until the urgency goes away, then walking to the bathroom`, 
        `Relaxing the pelvic floor muscles to help relax the bladder`],
        optionStyleType: `st-lower-alpha`,
        answer: [2],
        ansText:`Rationale: <!--<b>c. Squeezing the pelvic floor muscles while sitting still until the urgency goes away, then walking to the bathroom.</b>--> Patients are taught not to rush to the bathroom when they feel the urge to void. Instead, they are advised to stay away from the bathroom, so as to avoid exposure to cues that trigger urgency. They are encouraged to pause, sit down if possible, relax the entire body, and contract PFM repeatedly, without relaxing in between contractions, to diminish urgency, inhibit detrusor contraction, and prevent urine loss. They focus on inhibiting the urge sensation, giving it time to pass. Once the sensation subsides, they walk at a normal pace to the toilet.`, 
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `When using fluid management as a treatment for urgency incontinence, patients are told to:`,
        q2: ``,
        q3: [],
        option: [`consume a normal amount of fluid to avoid dehydration as well as sudden urgency.`, 
        `increase fluid intake to ensure adequate hydration and train the bladder.`, 
        `decrease fluid intake to minimize bladder filling.`, 
        `increase fluid intake to prevent the loss of functional bladder capacity.`],
        optionStyleType: `st-lower-alpha`,
        answer: [0],
        ansText:`Rationale: <!--<b>a. Consume a normal amount of fluid to avoid dehydration as well as sudden urgency.</b>--> Fluid intake modifications depend on the patients’ pattern of intake, which can be assessed by having them complete a 24- to 48-hour diary of intake and output, including voided volumes when possible. Reviewing such a diary can reveal excessive fluid intake, inadequate fluid intake, and diurnal patterns of intake that may be contributing to LUTS. Although it may seem counterintuitive, it is usually good advice to encourage patients to consume at least six 8-ounce glasses of fluid each day to maintain adequate hydration. Fluid intake should be regulated to 6- to 8-ounce glasses or 30 mL/kg body weight per day with a 1500 mL/day minimum at designated times unless contraindicated by a medical condition. The Institute of Medicine issued a report in 2004 with guidelines for total water intake for healthy people.`, 
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `When attempting to identify dietary bladder irritants, the patient should:`,
        q2: ``,
        q3: [],
        option: [`avoid spicy foods, tomatoes, and citric fruits`, 
        `eliminate caffeine`, 
        `keep a diary to see which foods or beverages increase urgency`, 
        `all of the above`],
        optionStyleType: `st-lower-alpha`,
        answer: [2],
        ansText:`Rationale: <!--<b>c. Keep a diary to see which foods or beverages increase urgency.</b>--> A diary of food and beverage intake is useful for identifying which substances are in fact irritants for individual patients; and a trial period of eliminating these substances one at a time can be used to confirm the relationship.`, 
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `When conducting pelvic floor muscle training, clinicians should:`,
        q2: ``,
        q3: [],
        option: [`ensure that patients are contracting the pelvic floor muscles selectively`, 
        `prescribe a specific set of exercises for the patients to do each day`, 
        `teach patients to contract pelvic floor muscles whenever they engage in activities that precipitate leakage`, 
        `all of the above`],
        optionStyleType: `st-lower-alpha`,
        answer: [3],
        ansText:`Rationale: <!--<b>d. All of the above.</b>--> It is important to verify that patients have identified and can contract the pelvic floor muscles (PFMs) properly before initiating an exercise regimen. Specific exercise regimens vary considerably in frequency and intensity, and the ideal exercise regimen has not yet been determined. However, good results have been achieved in several trials using 45 to 60 paired contractions and relaxations per day. We use an “exercise prescription” to prescribe the daily exercise program. It is important to teach patients how to prevent urine loss in daily life by occluding the urethra using active contraction of PFMs. Although exercise alone can improve urethral pressure and structural support and reduce incontinence, this motor skill enables patients to consciously occlude the urethra at specific times when urine loss is imminent. A careful history or examination of a bladder diary can alert the provider and patient of the circumstances during which each individual patient commonly experiences urine loss. Patients then learn to anticipate these activities and prevent leakage by contracting the PFM to occlude the urethra prior to and during coughing, sneezing, lifting, or any other physical activities that have precipitated urine leakage.`, 
        state: `notAnswered`,
        userAnswered: []
    ,
	type: `MCSS`        ,
        type: `MCSS`},
    {
        q: `Which of the following is true of caffeine reduction as a lifestyle modification for the treatment of incontinence?`,
        q2: ``,
        q3: [],
        option: [`Patients should be told to eliminate caffeine gradually`, 
        `Patients should be encouraged to try eliminating caffeine for a few days to see how it affects their bladder`, 
        `Patients should be encouraged to reduce caffeine gradually`, 
        `Patients should be advised to eliminate coffee only, as it is the main source of caffeine`],
        optionStyleType: `st-lower-alpha`,
        answer: [1],
        ansText:`Rationale: <!--<b>b. Patients should be encouraged to try eliminating caffeine for a few days to see how it affects their bladder.</b>--> Many patients are reluctant initially to forgo their caffeinated beverages, but they may be convinced to try it for a short period of time, such as 3 to 5 days, to determine if they are sensitive to its effects. If they experience relief from their symptoms, they are often more willing to reduce or eliminate caffeine from their diet.`, 
        state: `notAnswered`,
        userAnswered: []
    ,
	type: `MCSS`        ,
        type: `MCSS`}
    



];
