var quiz = [
    

    {
        q: `The most common cause of vesicovaginal fistulae in the nonindustrialized, developing world is:`,
        q2: ``,
        q3: [],
        option: [`cesarean section.`, 
        `surgical trauma during abdominal hysterectomy.`, 
        `surgical trauma during vaginal hysterectomy.`, 
        `obstructed labor.`, 
        `none of the above.`],
        optionStyleType: `st-lower-alpha`,
        answer: [3],
        ansText:`Rationale: <!--<b>d. Obstructed labor.</b>--> In the industrialized world, the most common cause of VVF is surgical trauma during gynecologic surgery, specifically hysterectomy. In the developing world, untreated obstructed labor results in ischemic necrosis of the anterior vaginal wall and underlying lower urinary tract and is the most common fistula in these geographic areas.`, 
        state: `notAnswered`,
        userAnswered: []
    ,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`        ,
        type: `MCSS`},
    {
        q: `The most common type of acquired urinary fistulae is:`,
        q2: ``,
        q3: [],
        option: [`vesicovaginal fistula.`, 
        `ureterovaginal fistula.`, 
        `colovesical fistula.`, 
        `rectourethral fistula.`, 
        `vesicouterine fistula.`],
        optionStyleType: `st-lower-alpha`,
        answer: [0],
        ansText:`Rationale: <!--<b>a. Vesicovaginal fistula.</b>--> The vast majority of urinary fistulae involve the bladder and vagina in both the industrialized and nonindustrialized world. The other types of fistulae listed are much less common.`, 
        state: `notAnswered`,
        userAnswered: []
    ,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`        ,
        type: `MCSS`},
    {
        q: `Vesicovaginal fistulae (VVF) may occur as a result of:`,
        q2: ``,
        q3: [],
        option: [`locally advanced vaginal cancer.`, 
        `incidentally noted and repaired iatrogenic cystotomy during hysterectomy.`, 
        `radiotherapy for cervical cancer.`, 
        `cystocele repair with bladder neck suspension.`, 
        `all of the above.`],
        optionStyleType: `st-lower-alpha`,
        answer: [0],
        ansText:`Rationale: <!--<b>e. All of the above.</b>--> Causes of VVF in the industrialized world include surgical trauma during hysterectomy, locally advanced gynecologic malignancy, anterior vaginal wall prolapse, anti-incontinence surgery, and pelvic radiotherapy. Intraoperative recognition and repair of bladder injury during hysterectomy should reduce the probability of VVF formation, but it does not eliminate the possibility.`, 
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `Intraoperative consultation is requested by a gynecologist for a possible urinary tract injury during a difficult abdominal hysterectomy. There is clear fluid noted in the pelvis. The gynecologist is particularly worried about postoperative VVF formation. All of the following statements are correct regarding counseling this gynecologist EXCEPT:`,
        q2: ``,
        q3: [],
        option: [`The incidence of iatrogenic bladder injury during hysterectomy is approximately 0.5% to 1.0%.`, 
        `Approximately 0.1% to 0.2% of individuals undergoing hysterectomy develop a VVF.`, 
        `The risk of ureterovaginal fistula is greater than the risk of VVF in this setting.`, 
        `The absence of blue-stained fluid in the operative field following the administration of intravenous indigo carmine does not eliminate a possibility of a urinary tract injury.`, 
        `All of the above are true.`],
        optionStyleType: `st-lower-alpha`,
        answer: [2],
        ansText:`Rationale: <!--<b>c. The risk of ureterovaginal fistula is greater than the risk of VVF in this setting.</b>--> The most common injury to the urinary tract during hysterectomy is a bladder laceration. Although ureteral injuries are not uncommon, they occur far less frequently than bladder injuries. Furthermore, ureterovaginal fistulae are much less common than VVF. The absence of blue-colored fluid in the pelvis does not exclude injury to the urinary tract. For example, a small bladder laceration may not be evident, especially if the bladder is decompressed with a Foley catheter.`, 
        state: `notAnswered`,
        userAnswered: []
    ,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`        ,
        type: `MCSS`},
    {
        q: `VVF due to obstructed labor are:`,
        q2: ``,
        q3: [],
        option: [`the most common etiology of VVF in sub-Saharan Africa.`, 
        `usually located at the vaginal apex.`, 
        `never associated with simultaneous rectovaginal fistula.`, 
        `typically found in multiparous women.`, 
        `usually smaller and simpler to repair than those associated with gynecologic surgery.`],
        optionStyleType: `st-lower-alpha`,
        answer: [0],
        ansText:`Rationale: <!--<b>a. The most common etiology of VVF in sub-Saharan Africa.</b>--> VVF in the developing world occur primarily due to obstructed labor. Typically, these occur in individuals who are young primigravidas with a narrow bony pelvis. These fistulae are usually large; located distally in the vagina, sometimes encompassing large segments of the trigone, posterior bladder wall, and bladder neck; and are often part of a larger complex of presenting signs and symptoms termed the “obstructed labor injury complex,” which includes rectovaginal fistulae. Because of their size and extensive ischemia of the surrounding tissues, these fistulae are often difficult to repair.`, 
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `A 47-year-old woman presents with the new onset of constant urinary leakage 5 years after completing radiation therapy for locally advanced cervical carcinoma. All of the following may be considered part of the diagnostic evaluation EXCEPT:`,
        q2: ``,
        q3: [],
        option: [`cystoscopy and possible biopsy.`, 
        `voiding cystourethrography (VCUG).`, 
        `computed tomographic (CT) scan of the abdomen and pelvis.`, 
        `urodynamics.`, 
        `ureteroscopy.`],
        optionStyleType: `st-lower-alpha`,
        answer: [0],
        ansText:`Rationale: <!--<b>e. Ureteroscopy.</b>--> This individual does not have diagnosis of VVF, and therefore multiple considerations are present. Nevertheless, VVF is a strong possibility given the history of radiation therapy and pelvic malignancy. A VCUG can establish the presence of a fistula. Cystoscopy and biopsy of a fistula, if present, are mandatory to rule out recurrent malignancy. A CT scan of the abdomen and pelvis can evaluate for recurrent malignancy. Urodynamics may be helpful in evaluating for other types of incontinence, as well as assessing for bladder compliance and capacity in this individual, with a risk for impaired compliance due to radiation therapy. There is no indication for ureteroscopy in this individual.`, 
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `A 52-year-old woman with a history of an abdominal hysterectomy 2 months previously presents for the evaluation of a constant clear vaginal discharge since the surgery. Following oral intake of Pyridium, her pads continue to have a clear watery discharge. The most likely diagnosis is:`,
        q2: ``,
        q3: [],
        option: [`vesicovaginal fistula.`, 
        `ureterovaginal fistula.`, 
        `peritoneovaginal fistula.`, 
        `vesicouterine fistula.`, 
        `urethrovaginal fistula.`],
        optionStyleType: `st-lower-alpha`,
        answer: [2],
        ansText:`Rationale: <!--<b>c. Peritoneovaginal fistula.</b>--> Clear fluid draining from the vagina following surgery should be properly characterized. A urinary fistula is a possible source; however, urinary incontinence (stress, urge, overflow, etc.) are strong considerations as well. A peritoneovaginal fistula is a rare complication of hysterectomy in which peritoneal fluid leaks through the vaginal cuff. The fluid may be collected and analyzed for creatinine level. A creatinine level similar to that found in serum excludes urinary fistula as the source of the fluid. In addition, if a Pyridium pad test is negative (pads are wet but are not stained orange), then this is highly suggestive of a peritoneal vaginal cuff fistula.`, 
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `In the industrialized world, postsurgical VVF are associated with ureteral injury in approximately:`,
        q2: ``,
        q3: [],
        option: [`0.01% of cases.`, 
        `0.1% of cases.`, 
        `10% of cases.`, 
        `25% of cases.`, 
        `50% of cases.`],
        optionStyleType: `st-lower-alpha`,
        answer: [2],
        ansText:`Rationale: <!--<b>c. 10% of cases.</b>--> Approximately 10% to 12% of individuals with VVF are found to have an associated ureteral injury.`, 
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `A 68-year-old woman presents with a 1-week history of vaginal leakage 6 months after completion of radiation therapy for locally advanced cervical cancer. VCUG reveals a VVF. On physical examination, the fistula is irregular and indurated, and approximately 3 mm in size. Cystoscopy reveals bullous edema surrounding the fistula, and biopsy of the fistula tract reveals only fibrosis without evidence of malignancy. There is no suggestion of recurrent malignancy on CT scan. She should be counseled that:`,
        q2: ``,
        q3: [],
        option: [`the optimal timing for repair of this fistula may be in 5 to 6 months.`, 
        `the best chance to repair this fistula is with immediate surgical intervention.`, 
        `a vaginal approach is not indicated.`, 
        `the use of an adjuvant flap will not be necessary.`, 
        `the success rate for the repair of this fistula is similar to that of a nonradiated VVF.`],
        optionStyleType: `st-lower-alpha`,
        answer: [0],
        ansText:`Rationale: <!--<b>a. The optimal timing for repair of this fistula may be in 5 to 6 months.</b>--> This patient has a VVF due to radiation therapy. It is recent in onset, suggesting that the fistula is immature and has a possibility of enlarging because the radiation injury has not yet completely demarcated. The optimal timing for repair of this fistula may be in 5 to 6 months. A reevaluation at that time will be needed to assess whether the VVF is now mature and amenable to repair. Radiation-induced fistulae can be repaired vaginally, and adjuvant flaps are used to bolster the repair. The success rates for radiation-induced VVF are less than those associated with non-radiation-induced VVF, whether they are approached vaginally or abdominally.`, 
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `The abdominal approach to VVF repair:`,
        q2: ``,
        q3: [],
        option: [`is the preferred approach in all patients with VVF.`, 
        `has a higher success rate than the vaginal approach.`, 
        `is suitable for the use of an omental interpositional flap.`, 
        `is associated with less morbidity and a shorter hospital stay than the vaginal approach.`, 
        `is more often associated with postoperative vaginal shortening and dyspareunia than the vaginal approach.`],
        optionStyleType: `st-lower-alpha`,
        answer: [2],
        ansText:`Rationale: <!--<b>c. Is suitable for the use of an omental interpositional flap.</b>--> The choice of approach for VVF repair is generally individualized based on the patient’s anatomy, clinical circumstances, and the experience of the operating surgeon. In experienced hands, success rates are similar between the two approaches. Advantages of the vaginal approach include a shorter hospital stay and less postoperative morbidity compared with the abdominal approach; however, vaginal shortening may be an issue with some types of vaginal VVF repairs, including the Latzko operation.`, 
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `The vaginal approach to an uncomplicated VVF repair:`,
        q2: ``,
        q3: [],
        option: [`Should always be bolstered by a gracilis flap.`, 
        `may be accomplished with a multilayer closure.`, 
        `Requires the use of non-absorbable sutures.`, 
        `is not indicated for obstetric fistula.`, 
        `is not indicated if the fistula tract is within 2cm of the ureter.`],
        optionStyleType: `st-lower-alpha`,
        answer: [1],
        ansText:`Rationale: <!--<b>b. May be accomplished with a three- or four-layer closure.</b>--> The vaginal approach to VVF repair uses a three- or four-layer closure. Absorbable suture is preferred to avoid complications related to foreign bodies in the urinary tract, including stone formation and infection. Gracilis flaps are rarely necessary as peritoneal flaps or Martius labial fat flaps are much more convenient and local. The vaginal approach is not contraindicated in obstetric fistula, or if the ureter is near the fistula tract.`, 
        state: `notAnswered`,
        userAnswered: []
    ,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`        ,
        type: `MCSS`},
    {
        q: `Principles of urinary fistula repair include all of the following EXCEPT:`,
        q2: ``,
        q3: [],
        option: [`excision of the fistula tract.`, 
        `tension-free closure.`, 
        `use of well-vascularized tissue flaps.`, 
        `watertight closure.`, 
        `adequate postoperative urinary drainage.`],
        optionStyleType: `st-lower-alpha`,
        answer: [0],
        ansText:`Rationale: <!--<b>a. Excision of the fistula tract.</b>--> Although some authors have suggested that excision of the epithelialized portion of the fistula tract is beneficial, it is not required in all cases.`, 
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `Level I evidence (one or more randomized control trials) exists to support which of the following statements?`,
        q2: ``,
        q3: [],
        option: [`Preoperative administration of topical estrogens improves tissue quality prior to the repair of VVF.`, 
        `Preoperative administration of topical estrogens improves the success rate of transvaginal VVF repair.`, 
        `Preoperative administration of broad-spectrum intravenous antibiotics improves the success rate of all types of VVF repair.`, 
        `Suprapubic bladder drainage is superior to urethral (Foley) catheter drainage in preventing surgical failure following VVF repair.`, 
        `None of the above.`],
        optionStyleType: `st-lower-alpha`,
        answer: [4],
        ansText:`Rationale: <!--<b>e. None of the above.</b>--> There is no evidence-based medicine to support any of these statements. Although both topical estrogens and intravenous antibiotics are commonly used, this is on the basis of expert opinion. There is no preferred method for postoperative bladder drainage following VVF repair, although unobstructed drainage is critical in preventing disruption of the suture line.`, 
        state: `notAnswered`,
        userAnswered: []
    ,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`        ,
        type: `MCSS`},
    {
        q: `Vaginal repair of VVF is contraindicated in:`,
        q2: ``,
        q3: [],
        option: [`multiparous women.`, 
        `large fistulae.`, 
        `radiation-induced fistulae.`, 
        `fistulae located at the vaginal cuff.`, 
        `none of the above.`],
        optionStyleType: `st-lower-alpha`,
        answer: [4],
        ansText:`Rationale: <!--<b>e. None of the above.</b>--> The transvaginal approach to VVF repair can be used in most patients with uncomplicated VVF. There are few absolute contraindications to the vaginal approach. Nulliparous individuals with VVF located at the vaginal cuff in a high narrow vagina can be challenging to repair vaginally due to anatomic considerations, but this approach is not contraindicated.`, 
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `Potential complications of repair for a VVF following abdominal hysterectomy include all of the following EXCEPT:`,
        q2: ``,
        q3: [],
        option: [`stress urinary incontinence.`, 
        `dyspareunia.`, 
        `recurrence of the fistula.`, 
        `urinary urgency and frequency.`, 
        `ureteral injury.`],
        optionStyleType: `st-lower-alpha`,
        answer: [0],
        ansText:`Rationale: <!--<b>a. Stress urinary incontinence.</b>--> Stress urinary incontinence may coexist with VVF; however, it is usually not related to the repair. One exception is the fistula located at the bladder neck or with involvement of the proximal urethra such as obstetric fistulae. These individuals may have new onset stress incontinence following repair due to destruction of the sphincter from the original injury.`, 
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `Advantages of the transabdominal approach to VVF repair as compared with the transvaginal repair include all of the following Except:`,
        q2: ``,
        q3: [],
        option: [`ease of mobilization of the omentum as an interpositional flap.`, 
        `decreased rate of intraoperative ureteral injury.`, 
        `preservation of vaginal depth.`, 
        `easier access to the apical VVF in individuals with high narrow vaginal canals.`, 
        `ability to perform an augmentation cystoplasty through the same incision.`],
        optionStyleType: `st-lower-alpha`,
        answer: [1],
        ansText:`Rationale: <!--<b>b. Decreased rate of intraoperative ureteral injury.</b>--> The transabdominal approach to VVF repair has several distinct advantages compared with the transvaginal approach. However, there are no studies to suggest that ureteral injury is less common using a transabdominal approach than a transvaginal approach.`, 
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `Seventeen days following a transvaginal VVF repair, a cystogram is performed. The bladder is filled to 100 mL with contrast medium and several images are taken. There is no evidence of a fistula on the filling images; however, the patient was unable to void during the study. A postvoid film was not obtained. This study:`,
        q2: ``,
        q3: [],
        option: [`demonstrates successful repair of the VVF, and the catheter should be removed.`, 
        `is nondiagnostic, because it was done too soon following repair.`, 
        `is nondiagnostic, because there are no voiding images or postvoid images.`, 
        `is nondiagnostic, because the bladder was not filled to an adequate volume.`, 
        `should be terminated and cystoscopy performed to examine for a persistent fistula.`],
        optionStyleType: `st-lower-alpha`,
        answer: [2],
        ansText:`Rationale: <!--<b>c. Is nondiagnostic, because there are no voiding images or postvoid images.</b>--> A postoperative cystogram should include voiding or postvoiding images to ensure that the VVF has been adequately repaired. Voiding may marginally increase the intravesical pressure, thereby providing opacification of some VVF that otherwise would be missed on simple filling cystograms. There is no standard filling volume for cystography. In general, 2 to 3 weeks from surgery is an adequate time period for postoperative imaging. There is no indication for cystoscopy in this patient.`, 
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `Before surgical mobilization, the blood supply to a potential Martius flap (fibrofatty labial flap) is through the:`,
        q2: ``,
        q3: [],
        option: [`inferior hemorrhoidal artery.`, 
        `external pudendal artery.`, 
        `uterine artery.`, 
        `inferior epigastric artery.`, 
        `gonadal artery.`],
        optionStyleType: `st-lower-alpha`,
        answer: [1],
        ansText:`Rationale: <!--<b>b. External pudendal artery.</b>--> The blood supply to the Martius flap is provided from three sources: the internal and external pudendal arteries as well as the obturator artery. In general, the small branches from the obturator artery, supplying the flap from a lateral direction, are sacrificed during mobilization. Furthermore, either the anterior (external pudendal) or posterior (internal pudendal) blood supply is divided in order to tunnel and then position the flap over the fistula.`, 
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `An interpositional flap of the greater omentum during VVF repair:`,
        q2: ``,
        q3: [],
        option: [`may be able to reach the deep pelvis without any mobilization in some patients.`, 
        `is most commonly based on the superior mesenteric artery.`, 
        `is contraindicated in the setting of inflammation or infection.`, 
        `should not be divided or incised vertically in the midline because this may compromise the blood supply.`, 
        `is most commonly used during a transvaginal approach.`],
        optionStyleType: `st-lower-alpha`,
        answer: [0],
        ansText:`Rationale: <!--<b>a. May be able to reach the deep pelvis without any mobilization in some patients.</b>--> The greater omentum has several favorable properties that support its use during transabdominal VVF repair. It is based on the right and left gastroepiploic arteries. Because of its rich blood supply and lymphatic properties, it can be a useful adjunctive measure in the setting of infection or inflammation. The blood supply enters the omentum perpendicular to its origin off the greater curvature of the stomach, enabling vertical incisions and mobilization into the deep pelvis. Wide mobilization may be necessary to permit the omentum to reach the deep pelvis in some cases; however, in many individuals the flap will reach into the deep pelvis without mobilization and without tension.`, 
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `A 39-year-old woman presents with constant vaginal leakage for 1 month following an abdominal hysterectomy. She describes symptoms of stress incontinence before the hysterectomy. She has no urgency and is voiding normally. Physical examination demonstrates no obvious fistula tract at the vaginal cuff. Oral phenazopyridine is given, and the bladder is filled with 100 mL of saline mixed with indigo carmine. A gauze pad is packed from the apex of the vagina proximally to the introitus distally, and the patient is told to ambulate for 90 minutes. Upon the patient’s return, the pad is removed and examined. The most proximal portion of the pad is stained yellow-orange, and the most distal portion is blue. This is most consistent with:`,
        q2: ``,
        q3: [],
        option: [`ureterovaginal fistula.`, 
        `vesicovaginal fistula.`, 
        `urethrovaginal fistula.`, 
        `a and b.`, 
        `a and c.`],
        optionStyleType: `st-lower-alpha`,
        answer: [0],
        ansText:`Rationale: <!--<b>a. Ureterovaginal fistula.</b>--> This patient has at least a ureterovaginal fistula, based on the yellow-orange staining at the proximal portion of the gauze pad. This would be consistent with the normal voiding pattern. The distal blue staining would be consistent with stress incontinence as noted by the patient preoperatively. Hysterectomy is not associated with formation of urethrovaginal fistula. Vesicovaginal fistula is less likely because the staining would tend to be green (a combination of blue and yellow) and located in the midportion of the pad. A VCUG would be most helpful in definitively ruling out a vesicovaginal fistula.`, 
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `Ureterovaginal fistulae are:`,
        q2: ``,
        q3: [],
        option: [`not associated with transvaginal hysterectomy.`, 
        `usually associated with normal voiding patterns.`, 
        `best diagnosed on VCUG.`, 
        `found more commonly following hysterectomy for malignancy than for benign indications.`, 
        `usually located in the middle one-third of the ureter.`],
        optionStyleType: `st-lower-alpha`,
        answer: [1],
        ansText:`Rationale: <!--<b>b. Usually associated with normal voiding patterns.</b>--> Ureterovaginal fistulae involve the distal one-third of the ureter. They most commonly occur in the setting of hysterectomy: laparoscopic, abdominal, and vaginal hysterectomy may all result in ureterovaginal fistulae. Most ureterovaginal fistulae occur following hysterectomy for benign indications. Patients often do not complain of voiding dysfunction because the contralateral upper urinary tract provides filling of the bladder. VCUG is used primarily to exclude a concomitant VVF.`, 
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `Two weeks following an emergent cesarean section for fetal distress during labor, a 28-year-old woman reports constant leakage per vagina. Analysis of the collected fluid reveals it to have a high creatinine level consistent with urine. Physical examination, including pelvic examination, reveals absolutely no abnormalities or surgical trauma to suggest a urinary fistula. There is no stress incontinence elicited on physical examination. Renal ultrasonography demonstrates no hydronephrosis, and the bladder is empty. The most likely diagnosis is:`,
        q2: ``,
        q3: [],
        option: [`occult vesicovaginal fistula.`, 
        `occult ureterovaginal fistula.`, 
        `urethrovaginal fistula.`, 
        `vesicouterine fistula.`, 
        `peritoneovaginal fistula.`],
        optionStyleType: `st-lower-alpha`,
        answer: [3],
        ansText:`Rationale: <!--<b>d. Vesicouterine fistula.</b>--> The most common cause of vesicouterine fistula is low-segment cesarean section. The normal physical examination suggests a lack of surgical trauma to the vagina, which most likely excludes a vaginal fistula. In the postpartum period, urine from a vesicouterine fistula will leak out of the incompetent cervical os, resulting in constant urinary leakage. A VCUG will confirm the diagnosis.`, 
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `Vesicouterine fistulae occur most commonly due to:`,
        q2: ``,
        q3: [],
        option: [`low-segment cesarean section.`, 
        `vaginal delivery.`, 
        `malignancy.`, 
        `conization of the cervix.`, 
        `myomectomy.`],
        optionStyleType: `st-lower-alpha`,
        answer: [0],
        ansText:`Rationale: <!--<b>a. Low-segment cesarean section.</b>--> The vast majority of vesicouterine fistulae occur following low-segment cesarean section. Rarely, these may occur due to uterine rupture at the time of vaginal delivery.`, 
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `Potential options for therapy of vesicouterine fistula in a patient desiring long-term preservation of fertility include:`,
        q2: ``,
        q3: [],
        option: [`observation.`, 
        `cystoscopy and fulguration of the fistula tract.`, 
        `hormonal therapy.`, 
        `surgical exploration and repair of the fistula with interpositional omental flap.`, 
        `all of the above.`],
        optionStyleType: `st-lower-alpha`,
        answer: [4],
        ansText:`Rationale: All of the listed options may preserve long-term fertility in patients with vesicouterine fistula. In those not desiring preservation of fertility, hysterectomy is indicated.`, 
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `Two months following resection of a large urethral diverticulum extending proximally beyond the bladder neck, a patient complains of urinary leakage. All of the following may be the source of this patient’s symptoms EXCEPT:`,
        q2: ``,
        q3: [],
        option: [`a urethrovaginal fistula.`, 
        `a vesicovaginal fistula.`, 
        `stress urinary incontinence.`, 
        `a recurrent urethral diverticulum.`, 
        `a vesicouterine fistula.`],
        optionStyleType: `st-lower-alpha`,
        answer: [4],
        ansText:`Rationale: <!--<b>e. A vesicouterine fistula.</b>--> It is very unlikely that a vesicouterine fistula can result from such a clinical circumstance. Stress incontinence, VVF, urethrovaginal fistula, and a recurrent diverticulum may all result in the described symptoms.`, 
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `Urethrovaginal fistulae in the distal one-third of the urethra:`,
        q2: ``,
        q3: [],
        option: [`are often asymptomatic.`, 
        `are associated with significant bladder overactivity.`, 
        `cannot be repaired using a vaginal flap technique.`, 
        `can result in severe stress incontinence.`, 
        `are usually the result of malignant infiltration.`],
        optionStyleType: `st-lower-alpha`,
        answer: [0],
        ansText:`Rationale: <!--<b>a. Are often asymptomatic.</b>--> Distal urethrovaginal fistulae are often asymptomatic, because they originate beyond the sphincter. Vaginal voiding and pseudoincontinence may be present in some patients. A vaginal flap technique is an effective method of repair.`, 
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `The most common cause of a colovesical fistula is:`,
        q2: ``,
        q3: [],
        option: [`colon cancer.`, 
        `bladder cancer.`, 
        `prostate cancer.`, 
        `Crohn disease.`, 
        `diverticulitis.`],
        optionStyleType: `st-lower-alpha`,
        answer: [4],
        ansText:`Rationale: <!--<b>e. Diverticulitis.</b>--> Diverticulitis is the most common cause of colovesical fistula in most series. Colon cancer is the second most common cause, followed by Crohn disease.`, 
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `CT scan findings suggestive of a colovesical fistula include:`,
        q2: ``,
        q3: [],
        option: [`intravesical mass, air in the bladder, and bladder wall thickening.`, 
        `air in the bladder, bowel wall thickening adjacent to the bladder, and clear fluid in a bowel segment adjacent to the bladder.`, 
        `air in the bladder, bladder wall thickening adjacent to a loop of thickened bowel wall, and the presence of colonic diverticula.`, 
        `air in the colon, colonic mass adjacent to the bladder, and debris within the bladder.`, 
        `air in the colon, bladder wall thickening, and an intravesical mass.`],
        optionStyleType: `st-lower-alpha`,
        answer: [2],
        ansText:`Rationale: <!--<b>c. Air in the bladder, bladder wall thickening adjacent to a loop of thickened bowel wall, and the presence of colonic diverticula.</b>--> The classic triad found on CT scan, which is suggestive of a colovesical fistula, includes air in the bladder, bladder wall thickening adjacent to a loop of thickened bowel, and the presence of colonic diverticula.`, 
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `In the evaluation of a possible colovesical fistula, cystoscopy:`,
        q2: ``,
        q3: [],
        option: [`has high diagnostic accuracy in revealing the cause of the fistula.`, 
        `has a high yield in identifying potential fistulae.`, 
        `should not be performed due to the risk of sepsis.`, 
        `is usually normal.`, 
        `most commonly reveals a large connection to the bowel.`],
        optionStyleType: `st-lower-alpha`,
        answer: [1],
        ansText:`Rationale: <!--<b>b. Has a high yield in identifying potential fistulae.</b>--> The finding of bullous edema during cystoscopy is nonspecific; however, in the appropriate clinical setting, this can be very suggestive of a colovesical fistula. Eighty percent to 100% of cases of colovesical fistulae have an abnormality noted on cystoscopy. Cystoscopy and biopsy are useful to rule out a malignant fistula when this is a consideration.`, 
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `A 62-year-old man presents with pneumaturia and recurrent urinary tract infections. A cystoscopy is performed, revealing a bullous lesion on the posterior bladder wall. Two hours later, a CT scan is performed, revealing air in the bladder. In this patient, air in the bladder:`,
        q2: ``,
        q3: [],
        option: [`suggests colovesical fistula.`, 
        `may be due to a bacterial infection.`, 
        `may be due to instrumentation.`, 
        `is a nonspecific finding.`, 
        `all of the above.`],
        optionStyleType: `st-lower-alpha`,
        answer: [4],
        ansText:`Rationale: <!--<b>e. All of the above.</b>--> Air can be introduced into the bladder from instrumentation (i.e., cystoscopy or catheterization) or may be present due to infection with a gas-forming organism. Less commonly, air in the bladder results from a colovesical fistula.`, 
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `The most common cause of a ureterocolic fistula is:`,
        q2: ``,
        q3: [],
        option: [`locally extensive colon cancer.`, 
        `appendicitis with an associated abscess.`, 
        `diverticulitis.`, 
        `Crohn disease.`, 
        `tuberculosis.`],
        optionStyleType: `st-lower-alpha`,
        answer: [3],
        ansText:`Rationale: <!--<b>d. Crohn disease.</b>--> Most ureterocolic fistulae occur on the right side and occur in patients with Crohn disease. Left-sided fistulae in Crohn disease are much less common.`, 
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `The incidence of rectal injury during radical retropubic prostatectomy is:`,
        q2: ``,
        q3: [],
        option: [`0.1%.`, 
        `1.0%.`, 
        `5.0%.`, 
        `10%.`, 
        `20-fold higher in patients undergoing laparoscopic radical prostatectomy.`],
        optionStyleType: `st-lower-alpha`,
        answer: [1],
        ansText:`Rationale: <!--<b>b. 1.0%.</b>--> Most large series report a 1.0% to 1.5% incidence of rectal injury during radical retropubic prostatectomy. When recognized and repaired intraoperatively, very few of these injuries result in a rectourethral fistula. The incidence of rectal injury during laparoscopic radical prostatectomy, when performed by experienced surgeons, is similar to that reported in most open series.`, 
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `Rectourethral fistula (RUF) formation following brachytherapy for prostate cancer:`,
        q2: ``,
        q3: [],
        option: [`may require complex reconstructive surgery or urinary diversion for repair.`, 
        `is located at the level of the prostate.`, 
        `is associated with fecaluria.`, 
        `may be associated with recurrent malignancy.`, 
        `may relate to all of the above.`],
        optionStyleType: `st-lower-alpha`,
        answer: [4],
        ansText:`Rationale: <!--<b>e. May relate to all of the above.</b>--> RUF commonly present with fecaluria, regardless of the etiology. RUF in the setting of prostatic malignancy should be biopsied to evaluate for the possibility of recurrent disease.`, 
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `A 61-year-old otherwise healthy man returns to the office with symptoms of mild stress urinary incontinence and fecaluria 3 weeks following radical retropubic prostatectomy. A VCUG is performed and reveals a 1-mm fistula at the vesicourethral junction. The prostate-specific antigen (PSA) is undetectable, and the final pathology reveals organ-confined disease. This patient should be counseled that:`,
        q2: ``,
        q3: [],
        option: [`a York-Mason transsphincteric approach to this fistula is associated with a high risk of anal incontinence.`, 
        `a trial of indwelling catheterization may result in resolution of the fistula.`, 
        `immediate colostomy is indicated.`, 
        `the stress incontinence will become more severe following repair of the fistula.`, 
        `urinary and fecal diversion will be necessary to repair this fistula.`],
        optionStyleType: `st-lower-alpha`,
        answer: [1],
        ansText:`Rationale: <!--<b>b. A trial of indwelling catheterization may result in resolution of the fistula.</b>--> This is a small fistula, and as such, a trial of conservative therapy is warranted. Because this fistula is not associated with signs of local infection or sepsis, immediate colostomy is not indicated. A York-Mason operation is not associated with a high rate of anal incontinence. Furthermore, a single-stage approach may be attempted (without fecal diversion) in this uncomplicated fistula, if conservative measures fail. Finally, urinary incontinence may not worsen following surgical repair of the fistula.`, 
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `Pyelovascular fistulae:`,
        q2: ``,
        q3: [],
        option: [`are usually related to percutaneous procedures in the upper urinary tract.`, 
        `are most often due to renal malignancy.`, 
        `should be treated by removal of the nephrostomy tube.`, 
        `usually occur following radiation therapy.`, 
        `are usually fatal.`],
        optionStyleType: `st-lower-alpha`,
        answer: [0],
        ansText:`Rationale: <!--<b>a. Are usually related to percutaneous procedures in the upper urinary tract.</b>--> Pyelovascular fistulae are most often related to interventional procedures in the upper urinary tract, especially percutaneous procedures. Renal neoplasms and radiation therapy are not usually causative of these fistulae. Initial treatment consists of tamponade of the bleeding vessel. If this is unsuccessful, angiographic embolization may be necessary.`, 
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `A 74-year-old woman with a history of colon cancer and external beam radiotherapy develops ureteral obstruction, and a stent is placed. Three months later, she presents with severe anemia and ongoing bright red gross hematuria for several hours. On examination she is pale and tachycardic, with a thready pulse and a systolic blood pressure of 60. As resuscitation is initiated with fluids and blood transfusion, the next step in management is:`,
        q2: ``,
        q3: [],
        option: [`a CT scan of the abdomen and pelvis.`, 
        `cystoscopy, removal of the stent, and retrograde pyelography.`, 
        `immediate laparotomy and possible nephrectomy.`, 
        `angiography.`, 
        `a tagged red blood cell scan to lateralize the bleeding.`],
        optionStyleType: `st-lower-alpha`,
        answer: [3],
        ansText:`Rationale: <!--<b>d. Angiography.</b>--> This individual is at high risk for a ureteroarterial fistula at the level of the stent. A CT scan and retrograde pyelography will both most likely be nondiagnostic. Removal of the stent could result in an increase in bleeding and be rapidly fatal. Angiography in the setting of active bleeding will provide both the diagnosis of a ureteroarterial fistula, if present, and a possible therapeutic intervention in the form of embolization or stent graft placement. Nephrectomy will not stop the acute hemorrhage. A red blood cell scan will be too time consuming, and although it may lateralize the side of the bleeding, it will delay a potentially lifesaving intervention.`, 
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `<b>Imaging</b><br/><br/>See <a class="lightboxcallout" img-ref="image_fig_129_1" href="f375d475c82f408d897f097fa760e582">Fig. 129.1</a>. A 36-year-old woman presents with increased vaginal discharge 3 weeks after an abdominal hysterectomy. On the axial CT images in the delayed excretory phase, the most likely diagnosis is:`,
        q2: ``,
        q3: [],
        option: [`vesicovaginal fistula.`, 
        `ureterovaginal fistula.`, 
        `colovesical fistula.`, 
        `ureteral duplication.`, 
        `vesicocutaneous fistula.`],
        optionStyleType: `st-lower-alpha`,
        answer: [1],
        ansText:`Rationale: <!--<b>b. Ureterovaginal fistula.</b>--> There is extraluminal contrast around the left distal pelvic ureter with contrast opacification of the vagina on the lower image. The bladder is normal in appearance with no contrast extravasation, making options a, c, and e incorrect. Ureteral duplication does not have this appearance.`, 
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`}

    



];
