var quiz = [
    

    {
        q: `With aging:`,
        q2: ``,
        q3: [],
        option: [`renal function increases.`, 
        `bladder capacity declines.`, 
        `hepatic function remains relatively stable.`, 
        `pulmonary function declines.`, 
        `immunologic function remains stable.`],
        optionStyleType: `st-lower-alpha`,
        answer: [3],
        ansText:`Rationale: <!--<b>d. Pulmonary function declines.</b>--> Pulmonary surface area for oxygen diffusion decreases, which leads to alterations in the ventilation perfusion ratio. <b>With aging, renal function and renal mass decline, bladder capacity remains relatively stable but elasticity and contractility decline, and hepatic and immunologic function decline.</b>`, 
        state: `notAnswered`,
        userAnswered: []
    ,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`        ,
        type: `MCSS`},
    {
        q: `Urinary tract infections (UTIs) in elderly women may best be decreased by:`,
        q2: ``,
        q3: [],
        option: [`nitrofurantoin prophylaxis.`, 
        `systemic estrogen administration.`, 
        `cranberry juice.`, 
        `vaginal estrogen application.`, 
        `α-blocker therapy.`],
        optionStyleType: `st-lower-alpha`,
        answer: [3],
        ansText:`Rationale: <!--<b>d. Vaginal estrogen application.</b>--> It has been proposed that vaginal estrogens promote the growth of lactobacillus and thereby lower vaginal pH, which helps reduce pathogen colonization. Systemic estrogens are generally not prescribed in the elderly and may in fact cause incontinence in this population. Nitrofurantoin should not be given during the long term in the elderly because it may reduce renal function and lead to pulmonary fibrosis. Cranberry juice has its advocates but has not been shown to be effective in randomized trials, and α-blocker therapy in the female would not be expected to have much of an effect on residual urine as the female has few alpha receptors at the bladder neck.`, 
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `In demented elderly patients, incontinence:`,
        q2: ``,
        q3: [],
        option: [`is inevitable.`, 
        `is virtually always due to detrusor hyperreflexia.`, 
        `is unlikely to respond to therapy.`, 
        `is multifactorial and often reversible.`, 
        `treatment should focus primarily on preventing skin breakdown.`],
        optionStyleType: `st-lower-alpha`,
        answer: [3],
        ansText:`Rationale: <!--<b>d. Is multifactorial and often reversible.</b>--> Incontinence is never normal, even with dementia. <b>Detrusor overactivity (DO) is the most common type of lower urinary tract dysfunction among demented incontinent nursing home residents, but it is also the most common dysfunction among their dry peers.</b> Moreover, incontinence in 40% of these individuals is not associated with DO but with obstruction (in men), stress incontinence (in women), or a combination of an outlet and a detrusor problem, and the cause does not correlate with either the presence or severity of dementia. Thus it is no longer tenable to attribute incontinence a priori to DO. <b>Because incontinence in the elderly is usually multifactorial, involving urinary tract as well as nonurinary tract contributions, it is often treatable.</b> Even among nursing home patients, studies have documented more than a 50% reduction in incontinent episodes overall and full daytime continence in nearly 40% of residents. Particularly among demented individuals, nonurinary factors are prevalent and commonly include medication use, depression, fecal impaction, UTI, atrophic vaginitis, and disorders of fluid excretion. It is important to prevent skin breakdown, but this should not be the primary approach to the incontinent nursing home resident.`, 
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `Urinary incontinence (UI) in older people is usually:`,
        q2: ``,
        q3: [],
        option: [`brought to a physician’s attention by the patient.`, 
        `detected by the patient’s primary physician.`, 
        `obvious to the urologist.`, 
        `detected by the physician but ignored.`, 
        `unknown to the patient’s physician.`],
        optionStyleType: `st-lower-alpha`,
        answer: [4],
        ansText:`Rationale: <!--<b>e. Unknown to the patient’s physician.</b>--> Despite the fact that incontinence is so common and amenable to therapy, most patients do not mention it to a physician. Reasons include embarrassment, misperception that it is a normal part of aging, belief that it is untreatable, fear of complications associated with its evaluation and treatment, or misconception that only major surgery can cure it. Moreover, when patients do mention it, most physicians either dismiss it as a normal part of aging or merely check a urinalysis. With newer undergarments and pads that better absorb and deodorize, the doctor may be unaware of the problem unless he/she asks about it.`, 
        state: `notAnswered`,
        userAnswered: []
    ,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`        ,
        type: `MCSS`},
    {
        q: `In older patients, involuntary bladder contractions:`,
        q2: ``,
        q3: [],
        option: [`are rarely seen in asymptomatic patients.`, 
        `are primarily due to central nervous system (CNS) pathology.`, 
        `are almost always the cause of the patient’s incontinence.`, 
        `are inevitable in demented patients.`, 
        `may not be the cause of the incontinence.`],
        optionStyleType: `st-lower-alpha`,
        answer: [4],
        ansText:`Rationale: <!--<b>e. May not be the cause of the incontinence.</b>--> <b>It is important to realize that involuntary bladder contractions are found commonly in even continent, neurologically intact elderly; the prevalence ranges in various studies between 50% and 55%.</b> This fact underscores the concept that such contractions are a risk factor for UI but not necessarily sufficient. Moreover, even when such contractions are the major contributor to UI, they may be due to a urethral abnormality. More than half of obstructed individuals and approximately 25% of those with stress incontinence have associated DO that usually remits with correction of the urethral abnormality alone. The proportion of elderly individuals in whom DO remits is likely lower, but clearly it is insufficient merely to identify involuntary contractions on cystometry and attribute the incontinence to them. To be considered the cause of the UI, such contractions must reproduce the patient’s type of leakage, and urethral abnormalities must be excluded. This is particularly important because a bladder relaxant medication prescribed for DO that is actually due to obstruction may precipitate acute retention.`, 
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `After the history and physical examination, evaluation of the incontinent older patient should include:`,
        q2: ``,
        q3: [],
        option: [`cystoscopy.`, 
        `videourodynamics.`, 
        `postvoid residual assessment.`, 
        `urinary cytology.`, 
        `assessment of prostate size in a male.`],
        optionStyleType: `st-lower-alpha`,
        answer: [2],
        ansText:`Rationale: <!--<b>c. Postvoid residual assessment.</b>--> Determining the PVR is essential in all incontinent older individuals, not only because retention can mimic other causes of UI, but also because knowledge of the PVR will affect therapy. For instance, an older woman with DO and PVR of 250 mL would be approached differently from a woman with DO and PVR of 5 mL. The rest of the diagnostic evaluation depends on the need for diagnostic certainty. However, if surgical correction is contemplated, or if the risk of empiric therapy exceeds the benefit, further testing is warranted. Cytology is indicated when bladder carcinoma is suspected and would be treated if found (i.e., not in a bedfast, demented patient). Cystoscopy has many indications, but it is not routinely required for evaluation of incontinence, nor is it alone sufficient to detect or exclude prostatic obstruction. Palpated prostate size correlates poorly with the presence of obstruction.`, 
        state: `notAnswered`,
        userAnswered: []
    ,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`        ,
        type: `MCSS`},
    {
        q: `Which of the following occurs as part of normal aging?`,
        q2: ``,
        q3: [],
        option: [`Urinary incontinence`, 
        `A small increase in serum creatinine concentration`, 
        `Uninhibited detrusor contractions`, 
        `Increase in bladder capacity`, 
        `Urinary flow rate is unchanged`],
        optionStyleType: `st-lower-alpha`,
        answer: [2],
        ansText:`Rationale: <!--<b>c. Uninhibited detrusor contractions.</b>--> Incontinence is never part of normal aging. Even at age 90 years, at least half of people are continent. Although renal function declines in most older adults, there is no change in serum creatinine because of a concomitant and balanced decrease in muscle mass. Involuntary detrusor contractions are common in continent and even asymptomatic elderly, but are rarely seen during routine cystometry in younger people. Bladder capacity may decrease in the elderly, but there is no evidence for an increase. <b>Flow rate declines, not only because obstruction becomes more likely in aging men, but also because detrusor contractility appears to decrease in both sexes.</b>`, 
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `The cornerstone of treatment for persistent urgency incontinence is:`,
        q2: ``,
        q3: [],
        option: [`behavioral therapy.`, 
        `flavoxate.`, 
        `oxybutynin.`, 
        `tolterodine.`, 
        `solifenacin.`],
        optionStyleType: `st-lower-alpha`,
        answer: [0],
        ansText:`Rationale: <!--<b>a. Behavioral therapy.</b>--> Behavioral therapy is the cornerstone of treatment for detrusor overactivity, although the type of therapy must be tailored to the individual. Bladder retraining attempts to restore a normal voiding pattern by progressively lengthening the voiding interval. Scheduled toileting aims to reduce incontinence by frequent voiding, which reduces total bladder volume and the chance of triggering involuntary bladder contractions. Prompted voiding works by regularly and frequently reminding cognitively impaired residents of the need to void. The role of medications is to supplement behavioral therapy, but only if needed. By reducing bladder irritability, such agents allow the bladder to hold more urine before the spasm occurs. However, even when continence is restored by these drugs, detrusor overactivity is still generally demonstrable. Furthermore, if the drug increases residual urine more than total bladder capacity, it may paradoxically decrease functional capacity, allowing the persistent involuntary contraction to occur at more frequent intervals. Thus before deciding that drug therapy has failed, PVR should be remeasured. Except for flavoxate, each of the agents listed has been proved effective in randomized controlled trials that included a substantial number of elderly patients.`, 
        state: `notAnswered`,
        userAnswered: []
    ,
	type: `MCSS`,
	type: `MCSS`        ,
        type: `MCSS`},
    {
        q: `Acute urinary retention in an older man:`,
        q2: ``,
        q3: [],
        option: [`indicates the need for surgical decompression.`, 
        `is treated effectively with α-adrenergic blockers.`, 
        `can be seen with detrusor hyperactivity with impaired contractility (DHIC).`, 
        `is treated effectively with bethanechol.`, 
        `requires treatment of the underlying urinary tract abnormality.`],
        optionStyleType: `st-lower-alpha`,
        answer: [2],
        ansText:`Rationale: <!--<b>c. Can be seen with detrusor hyperactivity with impaired contractility (DHIC).</b>--> The differential diagnosis for urinary retention extends beyond urethral obstruction, particularly in the elderly. <b>Patients with underactive detrusor or DHIC also may develop urinary retention. In addition, fecal impaction, pain (e.g., following hip replacement), and medications with urinary tract side effects (e.g., anticholinergics, sedating antihistamines, decongestants, and opiates) may induce acute urinary retention, particularly in patients with underlying bladder weakness or obstruction.</b> Thus the bladder should be decompressed for at least a week while reversible causes are addressed; the larger the PVR, the longer should be the decompression. Decompression allows some restoration of detrusor strength, which also facilitates urodynamic testing should it be necessary. α-Adrenergic blockers are effective for men with symptoms of prostatism, but clinical trials excluded patients with significant urinary retention. Bethanechol, although originally designed to improve bladder emptying in unobstructed patients, has not proved effective for this purpose (and likely not for nonobstructed patients either). Decompression in some elderly patients can reduce but not eliminate residual urine; provided it does not cause symptoms or renal compromise, subclinical retention need not necessarily be treated in all elderly patients, even if obstruction is present.`, 
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `Incontinence management products (e.g., garments/pads):`,
        q2: ``,
        q3: [],
        option: [`are reimbursed by insurance companies.`, 
        `should include menstrual pads.`, 
        `generally cost less than a dollar per day.`, 
        `should be chosen according to the type of incontinence rather than its severity.`, 
        `should be tailored to the individual.`],
        optionStyleType: `st-lower-alpha`,
        answer: [4],
        ansText:`Rationale: <!--<b>e. Should be tailored to the individual.</b>--> The cost of pads is rarely covered by insurance and can easily exceed $1/day. Menstrual pads, although often used for incontinence, are usually inappropriate. They are designed to absorb small amounts of slowly leaking viscid fluid rather than rapid gushes of urine. From among the numerous types of pads and garments, selection should be tailored to the individual’s needs and comorbidity; the type of incontinence matters less than severity.`, 
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `The voiding diary completed by an 83-year-old woman bothered by daytime incontinence discloses 800-mL output between 8:00 am and 11:00 pm, and 1500 mL from 11:00 pm to 8:00 am. The next step should be:`,
        q2: ``,
        q3: [],
        option: [`to have her repeat it with a record of fluid intake.`, 
        `to take furosemide at 7:00 pm each evening to reduce nocturnal excretion.`, 
        `to use pressure-gradient stockings to minimize peripheral edema.`, 
        `to advise her to curtail fluid intake after dinner.`, 
        `none of the above.`],
        optionStyleType: `st-lower-alpha`,
        answer: [4],
        ansText:`Rationale: <!--<b>e. None of the above.</b>--> The patient’s altered pattern of fluid excretion may occur for a variety of reasons. The most common is accumulation of peripheral edema due to venous insufficiency, peripheral vascular disease, low albumin states (malnutrition, hepatic disease), congestive heart failure, or medications (e.g., nonsteroidal antiinflammatory drugs [NSAIDs], dihydropyridine calcium channel blockers [e.g., nifedipine], or thiazolidinediones [e.g., rosiglitazone]). Each can be readily addressed. Before doing so, however, it is important to realize that the multiple pathologic conditions so often found in the elderly may be causal, contributory, a consequence, or unrelated to the condition for which the patient seeks help. In this individual, daytime leakage is the problem. Addressing the excess nocturnal excretion will not improve the daytime problem and, if it shifts the excess nocturnal excretion to the daytime (e.g., by use of pressure-gradient stockings), therapy may exacerbate the daytime leakage. If the nocturnal polyuria can be eliminated entirely (e.g., by substituting a drug that does not cause fluid retention), this should be done. If, however, therapy will only shift excretion to the daytime, one may elect not to treat if it is not dangerous (e.g., venous insufficiency). Evening furosemide risks inducing hypovolemia and increasing her risk of falls and fracture. Daytime predominance of incontinence suggests that she has stress incontinence, or DO associated with bladder neck incompetence that is exacerbated when she is upright. Once the cause is sorted out, the appropriate intervention can be prescribed, but in this individual, it should not include alteration of fluid intake: Her daytime output is too small to contribute to her daytime UI and, unless she is ingesting 2 L after dinner, her intake is also likely unrelated to her nocturnal polyuria. Moreover, the older kidney generally takes twice as long to respond to fluid restriction as the younger one, so restricting fluid after dinner is apt to do little. This case highlights the need to tailor the evaluation and treatment to the patient rather than to a given abnormality.`, 
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `Anticholinergic bladder relaxants may, ironically, actually exacerbate incontinence through all of the following mechanisms EXCEPT:`,
        q2: ``,
        q3: [],
        option: [`causing/exacerbating confusion.`, 
        `causing/exacerbating impaired mobility.`, 
        `causing/exacerbating a dry mouth.`, 
        `causing/exacerbating subacute urinary retention.`, 
        `precipitating acute urinary retention.`],
        optionStyleType: `st-lower-alpha`,
        answer: [1],
        ansText:`Rationale: <!--<b>b. Causing/exacerbating impaired mobility.</b>--> All of the currently available bladder relaxant medications have anticholinergic properties and thus can cause anticholinergic side effects. Dry mouth (xerostomia) results from the anticholinergic effect on the salivary and parotid glands. Even the M<sub>3</sub>-specific agents have this effect, because M<sub>3</sub> receptors are the predominant receptor in these glands as well as in the bladder. Because bladder relaxants generally do not abolish the involuntary detrusor contractions, the xerostomia-mediated increased fluid intake results in the bladder filling more frequently to the volume at which detrusor contractions may be triggered. Bladder relaxants often impair detrusor contractility and can lead to subacute retention. If the increase in PVR is more than the increase in total bladder capacity, the effective bladder capacity will decrease. In turn, this could allow involuntary contractions to occur at a lower effective volume; an increase in incontinence frequency can ensue.`, 
        state: `notAnswered`,
        userAnswered: []
    ,
	type: `MCSS`        ,
        type: `MCSS`},
    {
        q: `A 78-year-old woman with dementia has responded modestly to donepezil (Aricept, a cholinesterase inhibitor) for the past year. The recent onset of urgency incontinence led her primary physician to prescribe tolterodine last month while awaiting your assessment. Her incontinence has responded well. The next appropriate step is to:`,
        q2: ``,
        q3: [],
        option: [`discontinue tolterodine due to its interaction with donepezil.`, 
        `discontinue donepezil because her cognitive function is stable.`, 
        `discontinue both drugs because she is stable and the urgency incontinence may reflect an adverse effect of the donepezil.`, 
        `continue both drugs and monitor her for deterioration in cognitive function.`, 
        `taper the tolterodine.`],
        optionStyleType: `st-lower-alpha`,
        answer: [3],
        ansText:`Rationale: <!--<b>d. Continue both drugs and monitor her for deterioration in cognitive function.</b>--> Because cholinesterase inhibitors block the metabolism of acetylcholine, there is concern that they will provoke urgency incontinence, especially in older adults who already may have underlying age-related involuntary detrusor contractions that have not yet caused incontinence. However, despite prescription of these agents to millions of demented patients, there is little evidence that they cause incontinence. Moreover, because the benefits of these drugs for dementia are modest at best and are not seen in the majority of patients who use them, patients and families may decide that the benefit of the bladder relaxant outweighs the risk. Particularly in this patient, who has already benefited from tolterodine without notable cognitive deterioration, it is worth continuing therapy and monitoring her cognitive status.`, 
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `A 68-year-old obese woman with significant daily stress incontinence comes for a follow-up. Her bladder diary shows maximal voided volume of 125 mL during the daytime. Each of these measures is appropriate EXCEPT:`,
        q2: ``,
        q3: [],
        option: [`adjustment of fluid excretion and voiding intervals.`, 
        `advising weight reduction.`, 
        `teaching her postural maneuvers.`, 
        `consideration of surgical correction.`, 
        `pelvic floor muscle exercises.`],
        optionStyleType: `st-lower-alpha`,
        answer: [0],
        ansText:`Rationale: <!--<b>a. Adjustment of fluid excretion and voiding intervals.</b>--> Recent evidence suggests that weight loss will improve stress incontinence in obese women, and data support the use of postural maneuvers, pelvic floor muscle exercises, and surgical correction as well. Adjusting fluid excretion and voiding intervals can also be useful, especially for women with volume-dependent stress leakage. It can work particularly well for women with a threshold of at least 150 mL and best in those with a threshold greater than 250 mL. However, when the threshold is this low, the extent of fluid restriction required is usually not feasible and might even lead to dangerous dehydration.`, 
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `A 72-year-old man has urinary urgency and postvoid residual (PVR) of 40 mL. He also has hypertension and aortic stenosis that has caused minimal symptoms. His friend suggested that he ask for terazosin because it helped him with similar symptoms. The most appropriate response is:`,
        q2: ``,
        q3: [],
        option: [`to prescribe terazosin and see him again in 4 weeks.`, 
        `to prescribe alfuzosin instead, because it has a better side-effect profile.`, 
        `to obtain medical consultation before prescribing the drug.`, 
        `to perform urodynamic testing before deciding.`, 
        `to prescribe an anticholinergic agent.`],
        optionStyleType: `st-lower-alpha`,
        answer: [2],
        ansText:`Rationale: <!--<b>c. To obtain medical consultation before prescribing the drug.</b>--> Men with these lower urinary tract symptoms and a low PVR generally respond well to an α-adrenergic receptor blocker. However, many of these agents can reduce cardiac preload and thus impede adequate left ventricular filling and cardiac output, especially in individuals whose ventricular filling is already more difficult in the setting of left ventricular hypertrophy. The risk is exacerbated by the normal age-related decline that occurs in baroreflex sensitivity and further compounded in patients who take a β blocker and/or have aortic stenosis. Thus although the overall risks of orthostasis, falls, and fracture appear to be lower with the newer α-adrenergic agents, it would be prudent to obtain medical consultation before prescribing an α-blocker in this clinical setting. Anticholinergic therapy can be used in men with urgency and a low PVR, but because of the risk of inducing a tachycardia in a man with aortic stenosis and thereby also reducing left ventricular filling—combined with the potential risk of inducing urinary retention—prescription of an anticholinergic should not be the next step.`, 
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`}

    



];
