var quiz = [
  {
    q: `<!--1. -->Postoperative intravesical chemotherapy (administered in the recovery room) is most appropriate for which of the following patients?`,
    q2: ``,
    q3: [],
    option: [
      `<!--a. -->Initial presentation of a solitary 3.0-cm, low-grade–appearing tumor on the posterior bladder wall`,
      `<!--b. -->Multifocal high-grade Ta lesions with associated urothelial carcinoma in situ (CIS)`,
      `<!--c. -->6.5-cm high-grade, broad-based tumor on lateral wall with deep resection`,
      `<!--d. -->a and b`,
      `<!--e. -->a, b, and c`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [0],
    ansText: `Rationale: <b>Postoperative intravesical chemotherapy should be considered for most cases of new, apparently low-grade non–muscle-invasive bladder cancer because it has been shown to reduce recurrence rates and to improve outcomes for this disease.</b> One major exception is the patient in whom an extensive resection has been performed or whenever there is a possible perforation. In these patients intravesical chemotherapy should be withheld owing to concern about local extravasation and absorption. The benefit of postoperative intravesical chemotherapy is reduced in patients with recurrent or multiple tumors, and there is no clear benefit in patients with high-grade disease.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `<!--2. -->Which of the following agents is contraindicated for immediate postoperative intravesical chemotherapy (administered at time of transurethral resection of bladder tumor [TURBT])?`,
    q2: ``,
    q3: [],
    option: [
      `<!--a. -->Thiotepa`,
      `<!--b. -->Bacille Calmette-Guérin (BCG)`,
      `<!--c. -->Mitomycin C (MMC)`,
      `<!--d. -->Epirubicin`,
      `<!--e. -->b and c`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [1],
    ansText: `Rationale: <b>BCG should never be given in association with known trauma to the urinary tract, such as after transurethral resection of a bladder tumor (TURBT), owing to concern over systemic absorption and sepsis.</b> All of the other agents have shown efficacy in this setting with a favorable morbidity profile.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `<!--3. -->Potential advantage(s) of tumor markers such as, BTA, stat NMP-22, and UroVysion (FISH) when compared with urinary cytology for monitoring patients with bladder cancer is (are) improved:`,
    q2: ``,
    q3: [],
    option: [
      `sensitivity.`,
      `specificity.`,
      `<!--c. -->positive predictive value.`,
      `<!--d. -->a and c.`,
      `<!--e. -->a, b, and c.`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [0],
    ansText: `Rationale: <b>Tumor markers such as BTA stat, NMP-22, and UroVysion (FISH) provide increased sensitivity, particularly for low-grade tumors. High specificity is the strength of urinary cytology.</b> This approaches 90% to 100% in many series and has not been improved on with these other markers. Positive predictive value is highest for urinary cytology because the number of false positives is low.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `<!--4. -->Progression rates for low-grade Ta tumors range from:`,
    q2: ``,
    q3: [],
    option: [
      `<!--a. -->3% to 10%.`,
      `<!--b. -->12% to 17%.`,
      `<!--c. -->17% to 25%.`,
      `<!--d. -->25% to 35%.`,
      `<!--e. -->Over 35% and higher`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [0],
    ansText: `Rationale: <b>Recurrence is common (50%–70%) for patients with low-grade pTa tumors, but progression to higher tumor stage is uncommon, occurring in about 5% to 10% of patients.</b>`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `<!--5. -->General anesthesia can be advantageous compared with spinal anesthesia when a bladder tumor is being resected in which setting?`,
    q2: ``,
    q3: [],
    option: [
      `<!--a. -->Large mobile papillary tumor`,
      `<!--b. -->Tumor in a posterior wall diverticulum`,
      `<!--c. -->Lateral location at approximately 4 or 8 o’clock`,
      `<!--d. -->Extensive CIS`,
      `<!--e. -->Tumor at dome and along anterior bladder wall`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [2],
    ansText: `Rationale: <b>Resection along the lateral bladder wall posterolaterally places one in proximity to the obturator nerve, which can lead to an obturator reflex and increased risk of bladder wall perforation.</b> In this situation, general anesthesia with complete paralysis is sometimes beneficial to allow the procedure to be performed in a safe and simple manner.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `<!--6. -->A healthy 55-year-old man undergoes resection of a 2.0-cm bladder tumor in a posterior wall bladder diverticulum. Pathology demonstrates a pT1G3 bladder tumor with associated areas of CIS. Muscularis mucosa is involved, but there is no definite muscularis propria in the specimen. Optimal management includes`,
    q2: ``,
    q3: [],
    option: [
      `<!--a. -->repeat resection to stage the cancer.`,
      `<!--b. -->intravesical BCG therapy.`,
      `<!--c. -->partial cystectomy with excision of the diverticulum.`,
      `<!--d. -->radical cystectomy and urinary diversion.`,
      `<!--e. -->chemotherapy and radiation therapy.`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [3],
    ansText: `Rationale: This patient should be strongly considered for radical cystectomy. Partial cystectomy is not a good option because of the presence of CIS, which indicates a high risk of field-effect disease and subsequent recurrence. Deeper biopsies will risk perforation and would be unlikely to influence management. <b>Understaging is common with tumors in diverticula, and high-grade invasive tumors like this are best managed with radical cystectomy to ensure local disease control and optimize outcomes on a long-term basis.</b>`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `<!--7. -->The most important principle to follow when tumor is resected near or overlying a ureteral orifice is which?`,
    q2: ``,
    q3: [],
    option: [
      `<!--a. -->A ureteral stent must be placed at time of resection.`,
      `<!--b. -->In most cases resection is to be avoided.`,
      `<!--c. -->Coagulating current should not be used in this area.`,
      `<!--d. -->Resection and fulguration may be done at will—a stent or nephrostomy tube can be placed later.`,
      `<!--e. -->If hydronephrosis is found, an ultrasound should be obtained preoperatively and a nephrostomy tube placed.`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [2],
    ansText: `Rationale: A stent should be avoided if possible to prevent theoretical risk of reflux of tumor cells into the upper tracts. In most cases this area can be resected, and most ureters will remain unobstructed as long as the orifice is identified and coagulating current is not used in this area. Preoperative placement of a nephrostomy tube is often unnecessary as long as renal function is stable. Many patients with hydronephrosis will have invasive disease and will be undergoing urinary diversion in the near future, and this will relieve the obstruction. Hence, temporary nephrostomy tube placement is usually not required.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `<!--8. -->A restaging TURBT is indicated in which of the following situations?`,
    q2: ``,
    q3: [],
    option: [
      `<!--a. -->pT1 high-grade tumor with no muscularis propria identified`,
      `<!--b. -->pTa low-grade tumor that is multifocal (<i>n</i> = 5), for which resection appeared to be complete but postoperative intravesical therapy was <i>not</i> administered`,
      `<!--c. -->pT1 high-grade tumor with muscularis propria identified and negative`,
      `<!--d. -->a and c`,
      `<!--e. -->a, b, and c`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [3],
    ansText: `Rationale: Patients with pT1 tumor for whom the muscularis propria was not identified are understaged about 50% of the time and a repeat resection is clearly indicated. <b>Repeat resection of patients with pT1G3 tumor with muscularis propria present and negative are found to have residual or invasive disease 30% of the time.</b> A repeat TURBT is thus indicated in both of these patient populations to accurately stage the tumor and to optimize patient management.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `<!--9. -->Intravesical mitomycin C chemotherapy for high-risk superficial bladder cancer:`,
    q2: ``,
    q3: [],
    option: [
      `<!--a. -->reduces the risk of progression.`,
      `<!--b. -->reduces the risk of recurrence.`,
      `<!--c. -->is preferred over BCG, particularly for CIS.`,
      `<!--d. -->is virtually free of side effects.`,
      `<!--e. -->is less expensive than BCG.`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [1],
    ansText: `Rationale: <b>Mitomycin C (MMC) can reduce the risk of recurrence, but there is no convincing evidence that it can reduce progression rates, which is true for all forms of intravesical chemotherapy. Most comparative studies and meta-analyses suggest an advantage to BCG, particularly for CIS.</b> MMC can lead to local bladder irritation and a number of other side effects and is thus far from risk free.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `<!--10. -->Relative contraindications to intravesical BCG therapy include which of the following?`,
    q2: ``,
    q3: [],
    option: [
      `cirrhosis`,
      `history of tuberculosis (TB)`,
      `total incontinence`,
      `immunosuppression`,
      `all of the above`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [4],
    ansText: `Rationale: <b>BGC is contraindicated in patients with liver disease (isoniazid cannot be given if they develop BCG sepsis), have a personal history of TB, have total incontinence (they cannot retain the BCG, so efficacy would be poor). Immunosuppression represents a relative contraindication as the mechanism of action is to stimulate an immune response. Although small series have demonstrated this to be safe, it may be less effective than in immunocompetent patients. Other contraindications include disrupted urothelium, gross hematuria, or active or persistent symptomatic urinary tract infection (UTI).</b>`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `<!--11. -->The combination of reduced-dose BCG and interferon alpha for intravesical therapy is:`,
    q2: ``,
    q3: [],
    option: [
      `<!--a. -->more effective than BCG alone.`,
      `<!--b. -->more toxic than BCG alone.`,
      `<!--c. -->preferred first-line therapy for patients with multifocal CIS.`,
      `<!--d. -->less effective than BCG alone.`,
      `<!--e. -->a reasonable option for BCG failures after one course of therapy.`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [3],
    ansText: `Rationale: BCG plus interferon alpha has shown activity in BCG failures; this is a viable option for this challenging patient population. However, it is more expensive, and a randomized trial demonstrated that it is less effective than BCG alone in BCG-naive patients. BCG remains the treatment of choice for CIS. BCG plus interferon alpha is well tolerated with a side-effect profile that is better on average than BCG alone, because most of the side effects are related to the BCG and its dose is reduced in this regimen.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `<!--12. -->Common side effects of thiotepa include:`,
    q2: ``,
    q3: [],
    option: [
      `<!--a. -->irritative voiding symptoms and fever.`,
      `<!--b. -->hematuria and irritative voiding symptoms.`,
      `<!--c. -->bladder contraction and myelosuppression.`,
      `<!--d. -->irritative voiding symptoms and myelosuppression.`,
      `<!--e. -->flu-like symptoms and fever.`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [3],
    ansText: `Rationale: <b>Irritative voiding symptoms are reported by 12% to 69% of patients receiving intravesical thiotepa. The low molecular weight of this agent (189 kD) predisposes to systemic absorption and myelosuppression.</b> These are the two most common side effects of this agent.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `<!--13. -->Long-term (15 years) outcomes after intravesical BCG therapy for patients with high-risk non–muscle-invasive bladder cancer include which of the following?`,
    q2: ``,
    q3: [],
    option: [
      `<!--a. -->approximately 50% progression rate`,
      `<!--b. -->approximately 25% alive and with bladder intact`,
      `<!--c. -->a high incidence of recurrence in extravesical sites (prostatic urothelium and upper tracts)`,
      `<!--d. -->approximately 33% cancer-related mortality rates`,
      `<!--e. -->all of the above`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [4],
    ansText: `Rationale: <b>Data about long-term outcomes for patients with high-risk superficial bladder cancer treated with intravesical BCG therapy are derived primarily from the experience at Memorial Sloan Kettering (Cookson et al., 1997).</b><a href="[remark:99bfbca1bf314340b42f6f82eeb1a9a0]"><sup>a</sup></a> <b>In this series, 50% of patient progressed and one-third died of cancer progression. Approximately one-third developed disease in the prostatic fossa or upper tracts and only 27% survived with an intact bladder.</b> Such data should be considered when patients are being counseled about treatment options for high-risk disease.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `<!--14. -->Understaging for patients with pT1 high-grade bladder cancer is approximately:`,
    q2: ``,
    q3: [],
    option: [
      `<!--a. -->5% to 10%.`,
      `<!--b. -->10% to 20%.`,
      `<!--c. -->20% to 30%.`,
      `<!--d. -->30% to 50%.`,
      `<!--e. -->50% to 70%.`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [3],
    ansText: `Rationale: The risk of understaging a pT1 high-grade bladder tumor is approximately 30%, but it is even higher if there is no muscularis propria in the specimen. Overall, the risk is about 30% to 50% in this high-risk patient population.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `<!--15. -->A patient is diagnosed with a 1.0-cm pTa low-grade bladder cancer. What about imaging of the upper tracts?`,
    q2: ``,
    q3: [],
    option: [
      `<!--a. -->Not indicated`,
      `<!--b. -->Indicated only at diagnosis`,
      `<!--c. -->At diagnosis and 5 years later`,
      `<!--d. -->At diagnosis and every other year thereafter`,
      `<!--e. -->At diagnosis and every year thereafter:`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [0],
    ansText: `Rationale: The incidence of upper tract tumor associated with pTaG1 bladder cancer is extremely low (0.3%–2.3%), and current consensus is that upper tract imaging is not indicated in this patient population (Oosterlinck et al., 2005). If hematuria is present, however, upper tract imaging is indicated for its evaluation regardless of the finding of bladder tumor.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `<!--16. -->For patients with a stage pTa low-grade bladder tumor and a negative cytology, random bladder biopsies:`,
    q2: ``,
    q3: [],
    option: [
      `<!--a. -->are more likely to be positive in the prostatic fossa than the bladder.`,
      `<!--b. -->must be done in a systematic manner.`,
      `<!--c. -->should include sampling of the muscularis mucosa and preferably also the muscularis propria.`,
      `<!--d. -->are indicated at initial diagnosis and need not be repeated if negative.`,
      `<!--e. -->are not indicated in most cases.`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [4],
    ansText: `Rationale: The yield of random bladder biopsy in patients with low-grade low-stage bladder tumors and a negative cytology is very low and is not indicated unless high-risk features are present.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `<!--17. -->The risk of progression to muscle-invasive disease for patients with untreated CIS of the bladder is approximately:`,
    q2: ``,
    q3: [],
    option: [
      `<!--a. -->5% to 15%.`,
      `<!--b. -->15% to 25%.`,
      `<!--c. -->25% to 35%.`,
      `<!--d. -->35% to 45%.`,
      `<!--e. -->higher than 45%.`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [4],
    ansText: `Rationale: <b>Untreated CIS is very high risk (&gt;50%) for progressing to muscle-invasive disease. Even patients with a complete response to intravesical BCG will experience progression in 30% to 40% of cases on longitudinal follow-up</b> (Sylvester et al., 2005).`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `<!--18. -->The most important factor determining the long-term impact of BCG on progression is:`,
    q2: ``,
    q3: [],
    option: [
      `<!--a. -->using a full dose with each instillation.`,
      `<!--b. -->adding interferon.`,
      `<!--c. -->maintenance therapy.`,
      `<!--d. -->rolling the patient side to side to ensure that BCG covers the entire urothelium.`,
      `<!--e. -->washing the toilet with bleach after voiding each dose.`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [2],
    ansText: `Rationale: Maintenance therapy is the only proven scenario demonstrating reduction of tumor progression. Dose reduction studies appear to support similar benefit for lower doses, which are usually better tolerated if side effects are identified with full dosing. Interferon is incrementally beneficial in certain circumstances. Options d and e are both without scientific basis but are commonly recommended.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `<!--19. -->According to the American Urological Association (AUA) risk stratification tables from the 2016 AUA/Society of Urologic Oncology (SUO) guideline of non–muscle-invasive bladder cancer (NMIBC), which of the following tumor characteristics would classify as an intermediate risk tumor?`,
    q2: ``,
    q3: [],
    option: [
      `<!--a. -->HG T1`,
      `<!--b. -->Any CIS`,
      `<!--c. -->Solitary LG Ta &gt;3 cm`,
      `<!--d. -->PUNLMP`,
      `<!--e. -->Any variant histology`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [2],
    ansText: `Rationale: According the 2016 AUA/SUO guidelines, cases of NMIBC. can be classified as low-, intermediate-, or high-risk tumors (Table 136.2). LG Ta with recurrence within 1 year, solitary LG Ta tumors larger than 3 cm, multifocal LG Ta tumors, HG Ta tumors smaller than 3 cm, and LG T1 tumors are all considered to be of intermediate risk.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `<!--20. -->Which of the following represents an appropriate surveillance algorithm for high-risk NMIBC according to the 2016 AUA/SUO guideline?`,
    q2: ``,
    q3: [],
    option: [
      `<!--a. -->Cystoscopy every 3 to 4 months for 2 years, every 6 months for the subsequent 2 years, and annually for life`,
      `<!--b. -->Cystoscopy every 3 to 6 months for 2 years, then stop`,
      `<!--c. -->Imaging unnecessary unless hematuria is present`,
      `<!--d. -->Upper tract imaging annually for at least 2 years`,
      `<!--e. -->Cystoscopy at 3 months and then again 9 months later`,
      `<!--f. -->a and d.`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [5],
    ansText: `Rationale: Appropriate surveillance for high-risk tumors includes cystoscopy every 3 to 4 months for 2 years, semiannually for 2 years, and annually for life with cytology on the same schedule. The clock should be restarted with each recurrence. Upper tract imaging should be done annually for 2 years and considered on a less frequent basis after that.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
    type: `MCSS`,
  },
  {
    q: `<!--21. -->A 76-year-old male with a history of urothelial CIS begins induction BCG. Following his second instillation, he notes severe urinary urgency and dysuria as well as a fever to 102<sup>°</sup>F that is present 2 days after instillation. Appropriate management of this BCG toxicity includes which of the following?`,
    q2: ``,
    q3: [],
    option: [
      `<!--a. -->Continue BCG instillations unchanged at next instillation`,
      `<!--b. -->Start isoniazid and rifampin`,
      `<!--c. -->Start ciprofloxacin`,
      `<!--d. -->Consider infectious disease consult`,
      `<!--e. -->b and d`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [4],
    ansText: `Rationale: The clinical scenario described represents a grade 3 complication given the persistent high-grade fever. This patient should be started on treatment with isoniazid and rifampin for 3 to 6 months (choice b) along with vitamin B6 or pyridoxine. Furthermore, consultation with an infectious disease specialist (choice d) should be considered in this setting, particularly if symptoms are severe. This patient should also be provided with symptomatic management with anticholinergics and/or nonsteroidal anti-inflammatory drugs (NSAIDs), etc. The dose of BCG should be reduced to a half or one-third dose or stopped completely if there is any evidence of solid organ involvement.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `<!--22. -->Which of the following genetic mutations is commonly linked to low-grade NMIBC?`,
    q2: ``,
    q3: [],
    option: [
      `<!--a. -->Rb`,
      `<!--b. -->Fibroblast growth factor receptor 3 (FGFR3)`,
      `<!--c. -->p53`,
      `RAS`,
      `PTEN`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [1],
    ansText: `Rationale: Fibroblast growth factor receptor 3 is a commonly mutated cellular proliferation gene that is mutated in low-grade NMIBC. RB and p53, along with a number of mutations on chromosome 9, are commonly associated with high-grade tumors.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `<!--23. -->In the setting of initial BCG failure, a second course of BCG provides a response rate of approximately:`,
    q2: ``,
    q3: [],
    option: [
      `<!--a. -->5% to 10%`,
      `<!--b. -->10% to 20%`,
      `<!--c. -->30% to 50%`,
      `<!--d. -->60% to 80%`,
      `<!--e. -->&gt;90%`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [2],
    ansText: `Rationale: For patients who fail initial BCG, a second course provides a 30% to 50% chance of response.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
];
