var quiz = [
   
   
    {
        q: `<!--1. -->What is the most common urologic complication after phallic reconstruction?`,
        q2: ``,
        q3: [],
        option: [`<!--a. -->Urethral fistula`, 
        `<!--b. -->Urethral stricture`, 
        `<!--c. -->Stress incontinence`, 
        `<!--d. -->Urge incontinence`, 
        `<!--e. -->Urinary tract infection`,
        ],
        optionStyleType: `st-lower-alpha`,
        answer: [0],
        ansText: `Rationale: Urethral fistula is the most common urologic complication after phallic reconstruction.`,
        state: `notAnswered`,
        userAnswered: []
      ,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`        ,
        type: `MCSS`},
      {
        q: `<!--2. -->What is the most frequent site of urethral stricture in transmen?`,
        q2: ``,
        q3: [],
        option: [`<!--a. -->The anastomotic region between the fixed and phallic parts of the urethra`, 
        `<!--b. -->The fixed part of urethra`, 
        `<!--c. -->The phallic part of urethra`, 
        `<!--d. -->The bladder neck`, 
        `<!--e. -->The neomeatus`,
        ],
        optionStyleType: `st-lower-alpha`,
        answer: [0],
        ansText: `Rationale: Multiple retrospective studies in large cohorts of patients show that the anastomotic region between the fixed and phallic parts of the urethra is the most frequent site of urethral stricture in transmen.`,
        state: `notAnswered`,
        userAnswered: []
              ,
        type: `MCSS`},
      {
        q: `<!--3. -->Rectal injury as a consequence of vaginectomy occurs in approximately what percent of procedures?`,
        q2: ``,
        q3: [],
        option: [`<!--a. -->0.09%`, 
        `<!--b. -->0.9%`, 
        `<!--c. -->9%`, 
        `<!--c. -->19%`, 
        `<!--e. -->25%`,
        ],
        optionStyleType: `st-lower-alpha`,
        answer: [1],
        ansText: `Rationale: Multiple retrospective studies in large cohorts of patients show that rectal injury as a consequence of vaginectomy occurs in approximately 0.9% of patients.`,
        state: `notAnswered`,
        userAnswered: []
      ,
	type: `MCSS`,
	type: `MCSS`        ,
        type: `MCSS`},
      {
        q: `<!--4. -->The scrotum in transmen is made of the:`,
        q2: ``,
        q3: [],
        option: [`<!--a. -->labia majora`, 
        `<!--b. -->labia minora`, 
        `<!--c. -->anterior vaginal wall`, 
        `<!--d. -->perineal skin`, 
        `<!--e. -->labia majora and minora`,
        ],
        optionStyleType: `st-lower-alpha`,
        answer: [0],
        ansText: `Rationale: The labia majora are the embryologic counterpart of the scrotum, so using them for scrotal reconstruction is logical and gives the best aesthetic outcomes.`,
        state: `notAnswered`,
        userAnswered: []
              ,
        type: `MCSS`},
      {
        q: `<!--5. -->Urologic preoperative assessment in transmen should absolutely include:`,
        q2: ``,
        q3: [],
        option: [`uroflowmetry.`, 
        `<!--b. -->ultrasound of the urinary tract.`, 
        `<!--c. -->the patient’s urologic history.`, 
        `<!--d. -->a, b, c.`, 
        `<!--e. -->no assessment needed.`,
        ],
        optionStyleType: `st-lower-alpha`,
        answer: [3],
        ansText: `Rationale: In order to exclude any major urologic problem that could interfere with the reconstructive surgery, all three assessments are necessary.`,
        state: `notAnswered`,
        userAnswered: []
      ,
	type: `MCSS`        ,
        type: `MCSS`},
      {
        q: `<!--6. -->Transmen are usually difficult to catheterize transurethrally after surgery because of:`,
        q2: ``,
        q3: [],
        option: [`<!--a. -->the sharp curve between the female native urethra and the pars fixa of the neourethra.`, 
        `<!--b. -->the presence of a vaginal recessus close to the native female urethra.`, 
        `<!--c. -->hairy skin in the phallic urethra.`, 
        `<!--d. -->the presence of the clitoris dorsally in the perineal urethra.`, 
        `<!--e. -->the difference in elasticity between the phallic and the perineal urethra.`,
        ],
        optionStyleType: `st-lower-alpha`,
        answer: [0],
        ansText: `Rationale: Transmen are usually difficult to catheterize transurethrally after surgery because of the sharp curve between the female native urethra and the pars fixa of the neourethra.`,
        state: `notAnswered`,
        userAnswered: []
              ,
        type: `MCSS`},
      {
        q: `<!--7. -->Overall, the complication rate in gender-confirming surgery for transmen is:`,
        q2: ``,
        q3: [],
        option: [`<!--a. -->0.4%.`, 
        `<!--b. -->4%.`, 
        `<!--c. -->40%.`, 
        `<!--d. -->80%.`, 
        `<!--e. -->25%.`,
        ],
        optionStyleType: `st-lower-alpha`,
        answer: [2],
        ansText: `Rationale: Based on studies published in the field, the main complication rate including all parts of the surgery is 40%.`,
        state: `notAnswered`,
        userAnswered: []
      ,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`        ,
        type: `MCSS`},
      {
        q: `<!--8. -->An erectile and testicular prosthesis is implanted:`,
        q2: ``,
        q3: [],
        option: [`<!--a. -->at the time of phalloplasty.`, 
        `<!--b. -->1 year after phalloplasty.`, 
        `<!--c. -->3 months after phalloplasty.`, 
        `<!--d. -->2 years after phalloplasty.`, 
        `<!--e. -->first a testicular and 3 months later an erectile prosthesis.`,
        ],
        optionStyleType: `st-lower-alpha`,
        answer: [1],
        ansText: `Rationale: The implantation is done when sensitivity is observed in the phallus. As the sensitivity is based on a nerve anastomosis, it takes about a year before this anastomosis becomes functional.`,
        state: `notAnswered`,
        userAnswered: []
              ,
        type: `MCSS`},
      {
        q: `<!--9. -->When gender identity and sex do not match in a person, it is called:`,
        q2: ``,
        q3: [],
        option: [`<!--a. -->transsexualism.`, 
        `<!--b. -->sex reversal.`, 
        `<!--c. -->gender dysphoria.`, 
        `<!--d. -->gender nonconformity.`, 
        `<!--e. -->homosexuality.`,
        ],
        optionStyleType: `st-lower-alpha`,
        answer: [2],
        ansText: `Rationale: This term is based on the International Classification of Disease and DSM classifications and definitions.`,
        state: `notAnswered`,
        userAnswered: []
              ,
        type: `MCSS`},
      {
        q: `<!--10. -->In transwomen, ultrasound examination of the prostate is best done:`,
        q2: ``,
        q3: [],
        option: [`transrectally.`, 
        `transabominally.`, 
        `transvaginally.`, 
        `perineally.`, 
        `<!--e. -->by CT scan only.`,
        ],
        optionStyleType: `st-lower-alpha`,
        answer: [2],
        ansText: `Rationale: The neovagina is reconstructed between the rectum and the prostate; thus this new structure allows easy access of the ultrasound probe to examine the prostate.`,
        state: `notAnswered`,
        userAnswered: []
              ,
        type: `MCSS`},
      {
        q: `<!--11. -->Which statement is correct about gender identity disorder?`,
        q2: ``,
        q3: [],
        option: [`<!--a. -->It can be diagnosed at pediatric age.`, 
        `<!--b. -->Is more frequent in biological females than males.`, 
        `<!--c. -->Is based on hormonal imbalance.`, 
        `<!--d. -->Always calls for psychotherapy before any hormonal or surgical treatment.`, 
        `<!--e. -->Is not mentioned in the fifth edition of the <i>Diagnostic and Statistical Manual of Mental Disorders</i> (DSM-5).`,
        ],
        optionStyleType: `st-lower-alpha`,
        answer: [0],
        ansText: `Rationale: Gender identity disorder (GID), which is mentioned in DSM-5, can be diagnosed in childhood. GID is more frequent in males and is not based on hormonal imbalance. Psychotherapy as treatment has bad results and is no longer recommended in the standards of care.`,
        state: `notAnswered`,
        userAnswered: []
              ,
        type: `MCSS`},
      
];
      
     