var quiz = [
  {
    q: `<!--1. -->Male stress urinary incontinence (SUI) may result from all of the following except:`,
    q2: ``,
    q3: [],
    option: [
      `<!--a. -->radical prostatectomy`,
      `<!--b. -->pelvic fracture urethral injury`,
      `<!--c. -->spinal cord injury`,
      `<!--d. -->bladder extrophy`,
      `<!--e. -->multiple system atrophy`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [2],
    ansText: `Rationale: SUI develops only in men with concomitant internal and external sphincter impairment. Internal sphincter incompetence results from pelvic surgery, such as radical prostatectomy, bladder neck injury, specific sympathetic neuropathic dysfunction, or embryological disruption. Incompetence of the external sphincter occurs most frequently after radical prostatectomy, but also can result from pelvic fracture urethral injuries, traumatic and acquired myelopathy, and congenital disorders such as spinal dysraphism, sacral agenesis, and the exstrophy/epispadias complex. Spinal cord injury leads to external or internal sphincter dyssynergia, which cause failure to empty, not failure to store.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `<!--2. -->The Advance male sling is hypothesized to provide continence by:`,
    q2: ``,
    q3: [],
    option: [
      `<!--a. -->mucosal coaptation.`,
      `<!--b. -->elevation of the bulbar urethra.`,
      `<!--c. -->compression of the membranous urethra.`,
      `<!--d. -->circumferential occlusion of the bulbar urethra.`,
      `<!--e. -->repositioning and lengthening of the membranous urethra.`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [4],
    ansText: `Rationale: <b>Transobturator slings are hypothesized to enhance external sphincter function by repositioning and lengthening the membranous urethra without significant compression.</b> Urodynamic studies show an increase in abdominal leak point pressure without other urodynamic evidence of obstruction. Evidence for this comes from fluoroscopic studies and magnetic resonance imaging. The latter studies demonstrate an increase in membranous urethral length and elevation of the bladder neck, posterior bladder wall, and rhabdosphincter.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `<!--3. -->Nerve-sparing radical prostatectomy has been associated with which of the following:`,
    q2: ``,
    q3: [],
    option: [
      `<!--a. -->Earlier return to urinary continence and improved final urinary continence`,
      `<!--b. -->Delayed return to urinary continence`,
      `<!--c. -->Earlier return of urinary continence`,
      `<!--d. -->Improved final continence`,
      `<!--e. -->No difference in time to return of continence`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [2],
    ansText: `Rationale: In systematic review and meta-analysis, nerve-sparing techniques have been associated with <b>more rapid return of continence, although not final continence status, after RP</b>.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `<!--4. -->The initial evaluation of a man with SUI should include all of the following except:`,
    q2: ``,
    q3: [],
    option: [
      `<!--a. -->Detailed history and physical exam`,
      `<!--b. -->Voiding diary and pad test`,
      `<!--c. -->Post void residual (PVR)`,
      `<!--d. -->Urinalysis`,
      `<!--e. -->Pressure flow urodynamics`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [4],
    ansText: `Rationale: The initial evaluation of a man with UI requires a detailed history, physical examination, postvoid residual measurement, and urinalysis. <b>Pressure flow urodynamics</b> can be used to evaluate potential bladder neck stenosis, residual sphincteric function, and bladder storage function as indicated, but <b>is not part of the initial evaluation of stress incontinence.</b>`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `<!--5. -->A 65-year-old man status post robotic assisted radical prostatectomy had a direct vision internal urethrotomy for a vesicourethral anastomotic stenosis 6 months ago. He has SUI, wears 6 pads per day, and does not leak at night. Office examination reveals a normal urinalysis, PVR of 175 mL, and positive leak test on Valsalva. What is the next best step?`,
    q2: ``,
    q3: [],
    option: [
      `Cystoscopy`,
      `<!--b. -->Retrograde urethrogram`,
      `<!--c. -->Pressure flow urodynamics`,
      `<!--d. -->Advance sling`,
      `<!--e. -->Artificial urinary sphincter (AUS)`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [0],
    ansText: `Rationale: Because unrecognized urethral or bladder neck pathology can significantly complicate all surgical approaches, endoscopic evaluation should be considered prior to surgical correction of UI post RP or TURP if there is any suspicion of bladder neck stenosis. <b>Cystoscopy is the best way to evaluate his elevated PVR and determine if he has a recurrent vesicourethral anastomotic stenosis.</b> Urethrography is less useful in delineating posterior urethral strictures. Urodynamics are not indicated unless poor bladder emptying cannot be otherwise explained.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `<!--6. -->Recurrent moderate SUI 4 years following AUS placement is most likely due to:`,
    q2: ``,
    q3: [],
    option: [
      `<!--a. -->detrusor overactivity.`,
      `<!--b. -->bladder neck stenosis.`,
      `<!--c. -->subcuff atrophy.`,
      `<!--d. -->pressure regulating balloon (PRB) herniation.`,
      `<!--e. -->cuff erosion.`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [2],
    ansText: `Rationale: While detrusor overactivity, PRB herniation and cuff erosion may all result in recurrent UI, <b>subcuff atrophy is the most common cause of recurrent SUI 4 years after AUS placement.</b> Mechanical failure, another cause of recurrent incontinence, is not listed as an option but over time becomes more common.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `<!--7. -->A 71-year-old male underwent successful implantation of an Advance sling for stress incontinence. Preoperatively he wore two pads per day, and 1 week postoperatively he is perfectly continent. Two weeks postoperatively he went on a hike with his family and immediately noticed that he was requiring two pads per day again. He is now 3 weeks postop. What is the best option to treat his recurrent incontinence?`,
    q2: ``,
    q3: [],
    option: [
      `<!--a. -->Immediate re-exploration, removal of the sling, and replacement with another Advance sling`,
      `<!--b. -->Placement of a second Advance sling in 3 months`,
      `<!--c. -->AUS in 3 months`,
      `<!--d. -->Urethral bulking agent`,
      `<!--e. -->Removal of the sling in 3 months and placement of a Virtue sling`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [0],
    ansText: `Rationale: <b>Evaluation of the patient who had prior urethral sling is similar to the evaluation after AUS placement</b> with several caveats. Identifying the type of sling placed (Advance vs. Virtue vs. bone anchored) and the timing of the incontinence are important. In the case of the Advance sling, it is important to determine whether the patient may have loosened the sling in the first 6 weeks postoperatively, whether the incontinence is persistent (ongoing SUI) or the result of detrusor overactivity. If patients give a history of improved UI and a loosening of the sling in the first 6 weeks postoperatively, re-exploration is appropriate. The perineum is opened, the arms of the sling lateral to the bulbar urethra are identified and each arm is cut. The remaining central portion of the sling should be removed from the surface of the corpus spongiosum of the bulbar urethra. Another sling can then be placed in the same manner, as described later.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `<!--8. -->A 57-year-old man presents with SUI 12 months after robot-assisted radical prostatectomy and adjuvant external beam radiation therapy. His PSA is &lt;0.01. His 24 hour pad weight is 600 g, and he has incontinence while sleeping. What is his best option for maximal urinary control?`,
    q2: ``,
    q3: [],
    option: [
      `<!--a. -->Advance male sling`,
      `<!--b. -->Virtue male sling`,
      `<!--c. -->Urethral bulking agent`,
      `<!--d. -->AUS`,
      `<!--e. -->Sacral neuromodulation`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [3],
    ansText: `Rationale: Because of limited efficacy, submucosal bulking agents are not part of the treatment algorithm for post-RP UI. Thus the <b>AUS and slings should be considered as first-line surgical therapy for sphincteric incontinence in most men, although a trial of a bulking agent may be appropriate in cases of neurogenic male stress UI. The AUS remains the established device for treatment of moderate to severe UI, supported by numerous publications documenting its benefits.</b> Thus, the transobturator slings should be primarily used in cases with mild to moderate incontinence, which can be defined as a 24-hour pad weight of less than 150 grams for mild UI and less than 400 grams for moderate UI. A sling procedure should be offered with caution to those with prior radiation therapy or urethral erosion, because the degree of urine loss that exists in this group usually exceeds the limits of the procedure. One reason for the lower efficacy in these patients may be the lack of appropriate tissue elasticity for deformation/elongation/compression of the external urinary sphincter apparatus.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `<!--9. -->A 74-year-old man has SUI after radical prostatectomy with a 24-hour pad weight of 600 g. He would like treatment of his SUI and is considered an acceptable surgical candidate. He has poor manual dexterity. Which treatment is his best option for urinary control?`,
    q2: ``,
    q3: [],
    option: [
      `<!--a. -->Advance sling`,
      `<!--b. -->Virtue sling`,
      `<!--c. -->Urethral bulking agent`,
      `<!--d. -->AUS`,
      `<!--e. -->External collecting device`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [0],
    ansText: `Rationale: Because of limited efficacy, submucosal bulking agents are not part of the treatment algorithm for post-RP UI. Although the patient has severe UI, an <b>AUS is not advised due to his poor manual dexterity, and a perineal sling is the preferred treatment option.</b> The authors recommend the Advance sling based on broader experience with this device in the urological community, more substantial corroborating literature, and personal experience with the device compared to the Virtue sling.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `<!--10. -->A 72-year-old man with incontinence after radical prostatectomy and adjuvant radiation therapy had an AUS implanted 5 years ago and has recurrent incontinence due to subcuff atrophy. He is impotent and not interested in sexual activity. Intraoperatively, the urethra measures &lt;3.5 cm under the previous cuff and the bulbar urethra distal to this appears atrophic as well and likely measures &lt;4.0 cm. What is the next best step?`,
    q2: ``,
    q3: [],
    option: [
      `<!--a. -->Place a second cuff in tandem distal to the existing cuff.`,
      `<!--b. -->Place a transcorporal cuff distal to the existing cuff site.`,
      `<!--c. -->Place a transcorporal cuff at the existing cuff site.`,
      `<!--d. -->Place a 3.5-cm cuff distal to the existing cuff site.`,
      `<!--e. -->Place a 3.5-cm cuff at the existing cuff site.`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [1],
    ansText: `Rationale: Indiscriminate use of the tandem cuff approach as first-line surgical treatment should be tempered by higher rates of erosion associated with the distal cuff in several series. <b>Use of the 3.5-cm size has resulted in an increased risk of erosion in patients with a prior history of radiation therapy.</b> Patients with radiation therapy or other adverse risk factors and significant urethral atrophy should be considered for transcorporal placement rather than a 3.5-cm cuff. Placing a transcorporal cuff should be performed at a different location along the bulbar urethra.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `<!--11. -->A 63-year-old man underwent uncomplicated 4.0-cm cuff bulbar AUS placement and has failed a series of voiding trials over the first week postoperatively. What is the best option to manage his bladder?`,
    q2: ``,
    q3: [],
    option: [
      `<!--a. -->Suprapubic cystostomy drainage`,
      `<!--b. -->12 French catheter for an additional week followed by another voiding trial`,
      `<!--c. -->Clean intermittent catheterization (CIC) until able to spontaneously void`,
      `<!--d. -->Re-exploration and upsize of AUS cuff`,
      `<!--e. -->Re-exploration and removal of AUS`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [0],
    ansText: `Rationale: <b>If the patient fails a voiding trial at 48 hours, suprapubic cystostomy drainage is recommended to reduce the risk of urethral erosion. Ultrasound or fluoroscopic guidance is recommended to prevent puncture or potential contamination of the PRB.</b> Retention persisting beyond several weeks implies undersizing of the cuff; in such cases reoperation and cuff replacement may be required. <b>Prolonged urethral catheterization or CIC after AUS will result in an increased risk of cuff urethral erosion, even if the device is deactivated.</b>`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `<!--12. -->Artificial urinary sphincter infections are most commonly due to which organisms?`,
    q2: ``,
    q3: [],
    option: [
      `<!--a. --><i>Escherichia coli</i>`,
      `Proteus`,
      `<!--c. --><i>Streptococcus</i>`,
      `<!--d. --><i>Staphylococcus</i>`,
      `Yeast`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [3],
    ansText: `Rationale: Skin pathogens are the most commonly cultured organism, usually <b><i>Staphylococcus epidermidis</i></b> and <b><i>Staphylococcus aureus</i></b>.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `<!--13. -->All of the following are established risk factor for AUS erosion except:`,
    q2: ``,
    q3: [],
    option: [
      `<!--a. -->Prior radiation`,
      `<!--b. -->Urethral catheterization`,
      `<!--c. -->Prior AUS revision`,
      `<!--d. -->Prior urethroplasty`,
      `<!--e. -->Prior Advance sling`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [4],
    ansText: `Rationale: Prior radiation, urethral catheterization, prior AUS revision, and urethroplasty are all risk factors for AUS urethral erosion. <b>Prior Advance sling has not resulted in an increased risk of AUS erosion.</b>`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `<!--14. -->Management of AUS cuff atrophy can be performed in which way?`,
    q2: ``,
    q3: [],
    option: [
      `<!--a. -->Cuff downsizing at existing cuff location`,
      `<!--b. -->Repositioning a cuff at a different location`,
      `<!--c. -->Tandem cuff placement`,
      `<!--d. -->Transcorporal cuff placement`,
      `<!--e. -->All of the above`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [4],
    ansText: `Rationale: <b>Managing AUS cuff atrophy can be performed in a number of ways and may require any one of the following maneuvers—cuff downsizing at existing cuff location, repositioning a cuff at a different location, tandem cuff placement, or transcorporal cuff placement—depending</b> on intraoperative findings.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `<!--15. -->A 67-year-old man status who underwent implantation of a 3.5-cm cuff bulbar AUS for post–radical prostatectomy SUI develops a symptomatic vesicourethral anastomotic stenosis. How is this best managed?`,
    q2: ``,
    q3: [],
    option: [
      `<!--a. -->Urethral dilation with sounds`,
      `<!--b. -->Antegrade incision through a SP cystostomy tract`,
      `<!--c. -->Transurethral incision through a 21 Fr rigid cystoscope`,
      `<!--d. -->Surgically uncouple the cuff followed by endoscopic treatment`,
      `<!--e. -->Robotic or transperineal bladder neck reconstruction`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [3],
    ansText: `Rationale: First-line management of vesicourethral anastomotic strictures usually involves an endoscopic approach with DVIU or dilation. <b>In the event significant endoscopic manipulation is required proximal to the cuff site, our practice is to surgically uncouple the cuff</b> for the duration of the endoscopic procedure to avoid the risk of urethral erosion or damaging the AUS cuff, which may result from either a balloon dilation or transurethral incision through a 21-Fr rigid cystoscope.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
];
