var quiz = [
   
   
    {
        q: `<!--1. -->The average age of patients with bladder cancer in the United States is:`,
        q2: ``,
        q3: [],
        option: [`<!--a. -->65.`, 
        `69.`, 
        `73.`, 
        `76.`, 
        `78.`,
        ],
        optionStyleType: `st-lower-alpha`,
        answer: [2],
        ansText: `Rationale: In the United States, the mean age of diagnosis is 73.<a href="[remark:cc89bc3a2e3a4c5b9f5cb66f8c653645]"><sup>a</sup></a>`,
        state: `notAnswered`,
        userAnswered: []
      ,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`        ,
        type: `MCSS`},
      {
        q: `<!--2. -->Inverted papillomas are:`,
        q2: ``,
        q3: [],
        option: [`<!--a. -->a benign tumor of the bladder.`, 
        `<!--b. -->a precursor to low-grade papillary cancer.`, 
        `<!--c. -->chemotherapy resistant.`, 
        `<!--d. -->an invasive tumor.`, 
        `<!--e. -->best treated with antibiotics.`,
        ],
        optionStyleType: `st-lower-alpha`,
        answer: [0],
        ansText: `Rationale: When diagnosed according to strictly defined criteria (e.g., lack of cytologic atypia), inverted papillomas behave in a benign fashion with only a 1% incidence of tumor recurrence (Sung et al., 2006; Kilciler et al., 2008). Occasionally, inverted papillomas are present with coexistent urothelial cancer elsewhere in the urinary system, occurring more commonly in the upper tract than the bladder (Asano et al., 2003). The use of fluorescence in situ hybridization to evaluate chromosomal changes can distinguish between an inverted papilloma and a urothelial cancer with an inverted growth pattern (Jones et al., 2007).`,
        state: `notAnswered`,
        userAnswered: []
      ,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`        ,
        type: `MCSS`},
      {
        q: `<!--3. -->The incidence rate of urothelial cancer:`,
        q2: ``,
        q3: [],
        option: [`<!--a. -->has been decreasing recently because of less smoking.`, 
        `<!--b. -->is higher in women than in men.`, 
        `<!--c. -->is highest in developed countries.`, 
        `<!--d. -->peaks in the fifth decade of life.`, 
        `<!--e. -->is higher in Asia than Europe.`,
        ],
        optionStyleType: `st-lower-alpha`,
        answer: [2],
        ansText: `Rationale: Sixty-three percent of all bladder cancer cases occur in developed countries, with 55% occurring in North America and Europe. There is a geographic difference in bladder cancer incidence rates across the world, with the highest rates in Southern and Eastern Europe, parts of Africa, Middle East, and North America, and the lowest in Asia and underdeveloped areas in Africa (Ferlay et al., 2007). <b>The incidence of urothelial cancer peaks in the seventh decade of life.</b>`,
        state: `notAnswered`,
        userAnswered: []
              ,
        type: `MCSS`},
      {
        q: `<!--4. -->The mortality rate of urothelial cancer:`,
        q2: ``,
        q3: [],
        option: [`<!--a. -->is primarily related to lack of health care access.`, 
        `<!--b. -->has been decreasing since 1990.`, 
        `<!--c. -->is highest in underdeveloped countries.`, 
        `<!--d. -->is proportionally higher in women than in men.`, 
        `<!--e. -->is proportionally higher in white men than in African American men.`,
        ],
        optionStyleType: `st-lower-alpha`,
        answer: [1],
        ansText: `Rationale: The mortality rate of urothelial cancer has decreased by 5% since 1990, primarily because of smoking cessation, changes in environmental carcinogens, and healthier lifestyles (Jemal et al., 2008).`,
        state: `notAnswered`,
        userAnswered: []
      ,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`        ,
        type: `MCSS`},
      {
        q: `<!--5. -->What is the risk of a white male developing urothelial cancer in his lifetime?`,
        q2: ``,
        q3: [],
        option: [`<!--a. -->Less than 5%`, 
        `<!--b. -->20%`, 
        `<!--c. -->40%`, 
        `<!--d. -->60%`, 
        `<!--e. -->80%`,
        ],
        optionStyleType: `st-lower-alpha`,
        answer: [0],
        ansText: `Rationale: A white male has a 3.7% chance of developing urothelial cancer in his lifetime, which is roughly 3 times the probability in white females or African American males and more than 4.5 times the probability of an African American female (Hayat et al., 2007; Jemal et al, 2008).`,
        state: `notAnswered`,
        userAnswered: []
              ,
        type: `MCSS`},
      {
        q: `<!--6. -->The most common histologic bladder cancer cell type is:`,
        q2: ``,
        q3: [],
        option: [`squamous.`, 
        `adeno.`, 
        `urothelial.`, 
        `small cell.`, 
        `leiomyosarcoma.`,
        ],
        optionStyleType: `st-lower-alpha`,
        answer: [2],
        ansText: `Rationale: <b>Histologically, 90% of bladder cancers are of urothelial origin, 5% squamous cell, and less than 2% adenocarcinoma or other variants</b> (Lopez-Beltran, 2008). Urothelial carcinoma is the most common malignancy of the urinary tract and is the second most common cause of death among genitourinary tumors.`,
        state: `notAnswered`,
        userAnswered: []
              ,
        type: `MCSS`},
      {
        q: `<!--7. -->The mortality rate from bladder cancer is highest in:`,
        q2: ``,
        q3: [],
        option: [`<!--a. -->the United States.`, 
        `<!--b. -->England.`, 
        `<!--c. -->South America.`, 
        `<!--d. -->China.`, 
        `<!--e. -->Egypt.`,
        ],
        optionStyleType: `st-lower-alpha`,
        answer: [4],
        ansText: `Rationale: The mortality rate from bladder cancer in Egypt is three times higher than in Europe and eight times higher than in North America because squamous cell carcinoma is highly prevalent in Egypt (Parekh et al., 2002).`,
        state: `notAnswered`,
        userAnswered: []
      ,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`        ,
        type: `MCSS`},
      {
        q: `<!--8. -->Recent evidence suggests that physician practice may be related to bladder cancer deaths in the elderly. What percentage of deaths could be avoided?`,
        q2: ``,
        q3: [],
        option: [`<!--a. -->Less than 5%`, 
        `<!--b. -->30%`, 
        `<!--c. -->50%`, 
        `<!--c. -->70%`, 
        `<!--c. -->90%`,
        ],
        optionStyleType: `st-lower-alpha`,
        answer: [1],
        ansText: `Rationale: Mortality from bladder cancer is highest in elderly persons, particularly those past the age of 80, accounting for the third most common cause of cancer deaths in men over the age of 80 (Jemal et al., 2008). Whether this increase in mortality rate is related to tumor biology or changes in physician practice with the elderly is unclear. Recent evidence suggests that physician practice may be related to bladder cancer deaths in the elderly (Morris et al., 2009). These authors estimated that 31% of all bladder cancer deaths were avoidable, more commonly in noninvasive than invasive disease.`,
        state: `notAnswered`,
        userAnswered: []
              ,
        type: `MCSS`},
      {
        q: `<!--9. -->Which gene is most commonly mutated in high-grade muscle invasive urothelial cancer?`,
        q2: ``,
        q3: [],
        option: [`<!--a. --><i>Cyclin A</i>`, 
        `<!--b. --><i>TP53</i>`, 
        `<!--c. --><i>FGFR-3</i>`, 
        `<!--d. --><i>HRAS</i>`, 
        `<!--e. --><i>PTEN</i>`,
        ],
        optionStyleType: `st-lower-alpha`,
        answer: [1],
        ansText: `Rationale: <b>High-malignant potential, non–muscle-invasive bladder cancer is more likely associated with deletions of tumor suppressor genes such as <i>TP53</i> and <i>RB</i></b> (Chatterjee et al., 2004a; George et al, 2007; Sanchez-Carbayo et al, 2007).`,
        state: `notAnswered`,
        userAnswered: []
              ,
        type: `MCSS`},
      {
        q: `<!--10. -->Which gene is most commonly mutated in carcinoma in situ (CIS)?`,
        q2: ``,
        q3: [],
        option: [`<!--a. --><i>PI3K</i>`, 
        `<!--b. --><i>RB</i>`, 
        `<!--c. --><i>FGFR-3</i>`, 
        `<!--d. --><i>HRAS</i>`, 
        `<!--e. --><i>CD-44</i>`,
        ],
        optionStyleType: `st-lower-alpha`,
        answer: [1],
        ansText: `Rationale: <b>All CIS is high grade by definition. The genetic abnormalities associated with CIS include alterations to the <i>RB</i>, <i>TP53,</i> and <i>PTEN</i> genes</b> (Cordon-Cardo et al., 2000; Lopez-Beltran et al, 2002; Cordon-Cardo, 2008).`,
        state: `notAnswered`,
        userAnswered: []
              ,
        type: `MCSS`},
      {
        q: `<!--11. -->Which gene is most commonly mutated low-grade papillary urothelial carcinoma (LgTa)?`,
        q2: ``,
        q3: [],
        option: [`<!--a. --><i>PTEN</i>`, 
        `<!--b. --><i>RB</i>`, 
        `<!--c. --><i>FGFR-3</i>`, 
        `<!--d. --><i>HRAS</i>`, 
        `<!--e. --><i>CD-44</i>`,
        ],
        optionStyleType: `st-lower-alpha`,
        answer: [2],
        ansText: `Rationale: Low-grade urothelial carcinoma is typically papillary in nature with a fibrovascular stalk and frequent papillary branching with increased cellular size, some nuclear atypia, and occasional mitotic figures. These tumors almost universally display alterations of genes in chromosome 9 and frequent mutations in FGFR3, PI3K or, alternatively, Ras genes.`,
        state: `notAnswered`,
        userAnswered: []
              ,
        type: `MCSS`},
      {
        q: `<!--12. -->The chemotherapy proven to cause urothelial cancer is:`,
        q2: ``,
        q3: [],
        option: [`doxorubicin.`, 
        `bleomycin.`, 
        `ifosfamide.`, 
        `etoposide.`, 
        `cyclophosphamide.`,
        ],
        optionStyleType: `st-lower-alpha`,
        answer: [4],
        ansText: `Rationale: <b>The only chemotherapeutic agent that has been proven to cause bladder cancer is cyclophosphamide</b> (Travis et al., 1995; Nilsson and Ullen, 2008). The risk of bladder cancer formation is linearly related to the duration and intensity of cyclophosphamide treatment, supporting a causative role. Phosphoramide mustard is the primary mutagenic metabolite that causes bladder cancer in patients exposed to cyclophosphamide.`,
        state: `notAnswered`,
        userAnswered: []
              ,
        type: `MCSS`},
      {
        q: `<!--13. -->The increased risk of developing bladder cancer for a man who has a sister with bladder cancer is:`,
        q2: ``,
        q3: [],
        option: [`twofold.`, 
        `<!--b. -->10-fold.`, 
        `<!--c. -->20-fold.`, 
        `<!--d. -->40-fold.`, 
        `<!--e. -->60-fold.`,
        ],
        optionStyleType: `st-lower-alpha`,
        answer: [0],
        ansText: `Rationale: <b>First-degree relatives of patients with bladder cancer have a twofold increased risk of developing urothelial cancer themselves, but high-risk urothelial cancer families are relatively rare</b> (Aben et al., 2002; Murta-Nascimento et al., 2007; Kiemeney, 2008).`,
        state: `notAnswered`,
        userAnswered: []
              ,
        type: `MCSS`},
      {
        q: `<!--14. -->The risk of a family member developing bladder cancer if a first-degree relative has the disease is:`,
        q2: ``,
        q3: [],
        option: [`<!--a. -->related to secondhand smoke.`, 
        `<!--b. -->higher in men.`, 
        `<!--c. -->higher in smokers.`, 
        `<!--d. -->related to inheritance of low-penetrance genes.`, 
        `<!--e. -->most common in high-grade cancer.`,
        ],
        optionStyleType: `st-lower-alpha`,
        answer: [3],
        ansText: `Rationale: The hereditary risk seems to be higher for women and nonsmokers, but it is not related to secondhand exposure to smoking in families. Most likely, there are a variety of low-penetrance genes that can be inherited to make a person more susceptible to carcinogenic exposure, thus increasing the risk of bladder cancer formation.`,
        state: `notAnswered`,
        userAnswered: []
      ,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`        ,
        type: `MCSS`},
      {
        q: `<!--15. -->The percent of patients presenting with non–muscle-invasive disease is:`,
        q2: ``,
        q3: [],
        option: [`<!--a. -->less than 5%.`, 
        `<!--b. -->20%.`, 
        `<!--c. -->40%.`, 
        `<!--d. -->60%.`, 
        `<!--d. -->80%.`,
        ],
        optionStyleType: `st-lower-alpha`,
        answer: [4],
        ansText: `Rationale: <b>At initial presentation, 80% of urothelial tumors are non–muscle-invasive.</b> There are multiple growth patterns of urothelial cancer, including flat carcinoma in situ (CIS), papillary tumors that can be low or high grade, and sessile tumors with a solid growth pattern. Non–muscle-invasive cancers can be very large because of lack of the genetic alterations required for invasion.`,
        state: `notAnswered`,
        userAnswered: []
              ,
        type: `MCSS`},
      {
        q: `<!--16. -->A 30-year-old man has gross hematuria, and cystoscopy reveals a papillary tumor. Transurethral resection of the tumor reveals a noninvasive 2-cm papillary low-malignant-potential urothelial tumor. Muscle is present in the resected specimen. All of the tumor is resected. The best treatment is:`,
        q2: ``,
        q3: [],
        option: [`<!--a. -->intravesical bacille Calmette-Guérin (BCG).`, 
        `<!--b. -->repeat cystoscopy with random bladder biopsies.`, 
        `<!--c. -->radical cystectomy because of the patient’s young age.`, 
        `<!--d. -->immediate mitomycin C intravesical therapy.`, 
        `observation.`,
        ],
        optionStyleType: `st-lower-alpha`,
        answer: [3],
        ansText: `Rationale: <b>PUNLMP is a papillary growth with minimal cytological atypia that is more than seven cells thick and is generally solitary and located on the trigone</b> (Holmang et al., 2001; Sauter et al., 2004). PUNLMP is composed of thin papillary stalks where the polarity of the cells is maintained and the nuclei are minimally enlarged. PUNLMP has a low proliferation rate and is not associated with invasion or metastases. Tumor recurrence is common, and thus perioperative treatment with mitomycin C is warranted.`,
        state: `notAnswered`,
        userAnswered: []
              ,
        type: `MCSS`},
      {
        q: `<!--17. -->The external agent most implicated in causing urothelial cancer is:`,
        q2: ``,
        q3: [],
        option: [`<!--a. -->β-naphthylamine.`, 
        `<!--b. -->4-aminobiphenyl.`, 
        `<!--c. -->perchloroethylene.`, 
        `<!--d. -->trichloroethylene.`, 
        `<!--e. -->4,4′-methylene bis(2-methylaniline).`,
        ],
        optionStyleType: `st-lower-alpha`,
        answer: [0],
        ansText: `Rationale: One of the first and most common chemical agents implicated in the formation of bladder cancer in dye and rubber workers is β-naphthylamine (Case and Hosker, 1954). Activation of aromatic amines allows DNA binding by enzymes that are selectively expressed in the population, making some subjects more susceptible to cancer formation, as described earlier related to the <b><i>NAT-2</i></b> and the <b><i>GSTM1</i></b> polymorphisms.`,
        state: `notAnswered`,
        userAnswered: []
              ,
        type: `MCSS`},
      {
        q: `<!--18. -->If a woman stops smoking for 10 years after 30 pack-years of smoking, her risk of developing bladder cancer:`,
        q2: ``,
        q3: [],
        option: [`<!--a. -->is the same as if she still smoked.`, 
        `<!--b. -->is the same as if she never smoked.`, 
        `<!--c. -->is unrelated to the intensity of smoking.`, 
        `<!--d. -->is very low because of her gender.`, 
        `<!--e. -->gradually decreases with time.`,
        ],
        optionStyleType: `st-lower-alpha`,
        answer: [4],
        ansText: `Rationale: <b>Smoking cessation does make a difference in urothelial cancer formation.</b> Smokers who have stopped for 1 to 3 years have a 2.6 relative risk, and those who have stopped for more than 15 years have a 1.1 relative risk of bladder cancer formation (Wynder and Goldsmith, 1977; Smoke IAfRoCT, 2004).`,
        state: `notAnswered`,
        userAnswered: []
              ,
        type: `MCSS`},
      {
        q: `<!--19. -->A man exposed to high doses of radiation (more than 500 mSv):`,
        q2: ``,
        q3: [],
        option: [`<!--a. -->has the same risk of urothelial cancer formation as a nuclear plant worker.`, 
        `<!--b. -->will likely develop urothelial cancer within 5 years.`, 
        `<!--c. -->is more likely to develop urothelial cancer if he is younger than 20 years.`, 
        `<!--d. -->is two times more likely to develop urothelial cancer.`, 
        `<!--e. -->should be quarantined for 3 months.`,
        ],
        optionStyleType: `st-lower-alpha`,
        answer: [3],
        ansText: `Rationale: There is a significant increased risk of dying from any cancer if a person is exposed to greater than 50 mSv. The relative risk of urothelial cancer formation is 1.63 in men and 1.74 in women. <b>Interestingly, urothelial cancer formation after radiation is not age related, but the latency period is 15 to 30 years.</b> However, there is no association with low-dose or industrial exposure of radiation therapy and bladder cancer formation. Importantly, urologic technicians and nuclear radiation workers do not have an increased risk of urothelial cancer formation.`,
        state: `notAnswered`,
        userAnswered: []
              ,
        type: `MCSS`},
      {
        q: `<!--20. -->One of the main changes between the AJCC 7th edition and AJCC 8th edition for bladder cancer is:`,
        q2: ``,
        q3: [],
        option: [`<!--a. -->there should be two grades of non-muscle-invasive bladder cancer.`, 
        `<!--b. -->multiple positive pelvic lymph nodes is considered stage 3 disease.`, 
        `<!--c. -->perivesical fat involvement by tumors is stage T3.`, 
        `<!--d. -->CIS can be low or high grade.`, 
        `<!--e. -->Ta grade 1 tumors should be considered cancerous.`,
        ],
        optionStyleType: `st-lower-alpha`,
        answer: [1],
        ansText: `Rationale: Broadly speaking, non–muscle-invasive bladder cancer is composed of stage 0 (noninvasive) and stage 1 (invasion into subepithelial connective tissue), muscle-invasive organ-confined bladder cancer is of stage 2, muscle-invasive locally advanced bladder cancer is stage 3, and metastatic disease is stage 4. Whereas prior AJCC editions viewed positive lymph nodes as stage 4 regardless of the quantity or location, the 2017 AJCC staging update now views nodal disease in the absence of systemic metastases as stage 3.`,
        state: `notAnswered`,
        userAnswered: []
              ,
        type: `MCSS`},
      {
        q: `<!--21. -->Genetic abnormalities associated with low-malignant potential Ta tumors include:`,
        q2: ``,
        q3: [],
        option: [`<!--a. -->fibroblast growth factor receptor-3 (<i>FGFR-3</i>).`, 
        `<!--b. -->TP53.`, 
        `<!--c. -->retinoblastoma (RB) gene.`, 
        `<!--d. -->PTEN.`, 
        `<!--e. -->loss of chromosome 17.`,
        ],
        optionStyleType: `st-lower-alpha`,
        answer: [0],
        ansText: `Rationale: Genetic abnormalities associated with low-grade cancer include deletion of 9q and alterations of <b><i>FGFR-3</i></b>, <b><i>HRAS</i></b>, and <b><i>PI3K</i></b> (Holmang et al, 2001; Cordon-Cardo, 2008). Low-grade carcinomas are immunoreactive for cytokeratin-20 and CD-44. The <b><i>TP53,</i></b> retinoblastoma <b><i>(RB),</i></b> and <b><i>PTEN</i></b> genes and loss of chromosome 17 are all associated with high-grade cancer.`,
        state: `notAnswered`,
        userAnswered: []
              ,
        type: `MCSS`},
      {
        q: `<!--22. -->A 40-year-old man has a T1 high-grade urothelial cancer on initial presentation. Muscle was present in the biopsy specimen. The next treatment is:`,
        q2: ``,
        q3: [],
        option: [`BCG.`, 
        `<!--b. -->repeat transurethral resection of a bladder tumor (TURBT).`, 
        `<!--c. -->radical cystectomy.`, 
        `<!--d. -->immediate mitomycin C instillation.`, 
        `<!--e. -->neoadjuvant chemotherapy followed by radical cystectomy.`,
        ],
        optionStyleType: `st-lower-alpha`,
        answer: [1],
        ansText: `Rationale: <b>Because of this understaging, the American Urological Association (AUA) guidelines call for a repeat transurethral resection in patients with T1 tumors to assess for muscle-invasive disease even if muscle was present in the specimen</b> (Hall et al, 2007).`,
        state: `notAnswered`,
        userAnswered: []
              ,
        type: `MCSS`},
      {
        q: `<!--23. -->A 73-year-old man with a history of Ta bladder cancer is found to have a 0.5-cm papillary lesion in the prostatic urethra and undergoes extensive transurethral resection of the prostate, revealing high-grade noninvasive disease of the prostatic urethra without ductal or stromal involvement. The next best step is:`,
        q2: ``,
        q3: [],
        option: [`<!--a. -->perioperative mitomycin C.`, 
        `<!--b. -->surveillance cystoscopy every 3 months.`, 
        `<!--c. -->mitomycin C therapy.`, 
        `<!--d. -->induction of and maintenance with BCG therapy.`, 
        `<!--e. -->radical cystectomy.`,
        ],
        optionStyleType: `st-lower-alpha`,
        answer: [3],
        ansText: `Rationale: For patients with noninvasive prostatic urethral cancer, transurethral resection of the prostate with BCG therapy is appropriate (Palou et al, 2007). For patients with prostatic ductal disease, a complete TURP is warranted, plus BCG therapy. Although a radical cystectomy could be performed, a more conservative organ-sparing treatment is recommended.`,
        state: `notAnswered`,
        userAnswered: []
              ,
        type: `MCSS`},
      {
        q: `<!--24. -->A 62-year-old man undergoes a transurethral biopsy of a bladder tumor at the dome. Final pathology reveals muscle-invasive urothelial and small cell carcinoma. Metastatic workup is negative. The next step is:`,
        q2: ``,
        q3: [],
        option: [`<!--a. -->intravesical gemcitabine therapy.`, 
        `<!--b. -->partial cystectomy.`, 
        `<!--c. -->radical cystoprostatectomy.`, 
        `<!--d. -->external beam radiotherapy.`, 
        `<!--e. -->chemoradiation therapy.`,
        ],
        optionStyleType: `st-lower-alpha`,
        answer: [4],
        ansText: `Rationale: Small cell carcinoma of the bladder should be considered and treated as metastatic disease, even if there is no radiologic evidence of disease outside the bladder. Small cell carcinoma of the bladder accounts for much less than 1% of all primary bladder tumors. <b>In general, small cell carcinoma of the bladder is very chemosensitive, and the primary mode of therapy is chemoradiation therapy or chemotherapy followed by cystectomy.</b>`,
        state: `notAnswered`,
        userAnswered: []
              ,
        type: `MCSS`},
      {
        q: `<!--25. -->When cisplatin-based chemotherapy is used, which of the following genetic mutations is associated with the worst prognosis?`,
        q2: ``,
        q3: [],
        option: [`<!--a. --><i>FGFR-3</i> mutations`, 
        `<!--b. --><i>PTEN</i>`, 
        `<!--c. --><i>TP53</i>`, 
        `<!--d. --><i>RB</i>`, 
        `<!--e. --><i>PTEN, TP53,</i> and <i>RB</i>`,
        ],
        optionStyleType: `st-lower-alpha`,
        answer: [4],
        ansText: `Rationale: Overall genetic instability is the hallmark of invasive urothelial cancer, but, specifically, alterations of <b><i>TP53, RB,</i></b> and <b><i>PTEN</i> carry a very poor prognosis</b> (Chatterjee et al, 2004a). <b><i>FGFR-3</i></b> mutations are associated with noninvasive bladder cancer.`,
        state: `notAnswered`,
        userAnswered: []
              ,
        type: `MCSS`},
      {
        q: `<!--26. -->When cisplatin-based neoadjuvant chemotherapy is used, which of the following genetic mutations is associated with an improved response?`,
        q2: ``,
        q3: [],
        option: [`<!--a. --><i>FGFR-3</i> mutations`, 
        `<!--b. --><i>ERCC2</i>`, 
        `<!--c. --><i>TP53</i>`, 
        `<!--d. --><i>RB</i>`, 
        `<!--e. --><i>ERCC2, FANCC,</i> and <i>ATM</i>`,
        ],
        optionStyleType: `st-lower-alpha`,
        answer: [4],
        ansText: `Rationale: The recent application of genomics to large cohorts of MIBCs has produced major breakthroughs in disease heterogeneity with obvious implications for clinical management. Whole transcriptome studies identified basal and luminal molecular subtypes (Choi et al., 2014; TCGAR, 2014; Damrauer et al., 2014), and patients with basal tumors appeared to derive the most benefit from neoadjuvant chemotherapy (NAC) (Seiler et al 2017; McConkey et al., 2018). In parallel, two other groups demonstrated that inactivating mutations in DNA damage repair genes (including ERCC2, FANCC, ATM) were associated with response to NAC (Van Allen et al., 2014; Serebriiskii et al., 2015). These findings are now being prospectively examined within the context of the Southwest Oncology Group’s (SWOG’s) completed S1314 trial. In addition, two groups have designed prospective clinical trials to test whether DDR mutations can be used to guide bladder preservation in patients treated with NAC, and several groups are considering clinical trials to select MIBC patients for NAC based on basal molecular subtype membership.`,
        state: `notAnswered`,
        userAnswered: []
              ,
        type: `MCSS`},
      {
        q: `<!--27. -->Tumor suppressor genes are activated by:`,
        q2: ``,
        q3: [],
        option: [`<!--a. -->gene amplification.`, 
        `<!--b. -->translocation.`, 
        `<!--c. -->point mutations.`, 
        `<!--d. -->DNA methylation.`, 
        `<!--e. -->microsatellite instability.`,
        ],
        optionStyleType: `st-lower-alpha`,
        answer: [2],
        ansText: `Rationale: Tumor suppressor genes are mainly activated by allelic deletion of one allele followed by point mutations of the remaining allele. Tumor suppressor genes are recessive or have a negative effect, resulting in unregulated cellular growth. Proto-oncogenes are generally activated by point mutations in the genetic code, gene amplification, and gene translocation. The activated proto-oncogenes become oncogenes that can cause cancer, and this is considered a positive or dominant growth effect (Lengauer et al, 1998; Wolff et al, 2005; Cordon-Cardo, 2008).`,
        state: `notAnswered`,
        userAnswered: []
              ,
        type: `MCSS`},
      {
        q: `<!--28. -->The risk of urologic malignancy in a man with recurrent gross hematuria, but who had a previous negative evaluation, is:`,
        q2: ``,
        q3: [],
        option: [`<!--a. -->less than 5%.`, 
        `<!--b. -->20%.`, 
        `<!--c. -->40%.`, 
        `<!--d. -->60%.`, 
        `<!--e. -->80%.`,
        ],
        optionStyleType: `st-lower-alpha`,
        answer: [0],
        ansText: `Rationale: <b>Gross, painless hematuria is the primary symptom in 85% of patients with a newly diagnosed bladder tumor</b> (Khadra et al, 2000; Alishahi et al, 2002; Edwards et al, 2006). The gross hematuria is usually intermittent and can be related to Valsalva maneuvers; therefore any episode of gross hematuria should be evaluated even if subsequent urinalysis is negative. Fifty percent of patients with gross hematuria will have a demonstrable cause, 20% will have a urological malignancy, and 12% will have a bladder tumor (Khadra et al, 2000). <b>The risk of malignancy in patients with recurrent gross or microscopic hematuria that had a full, negative evaluation is near zero within the first 6 years</b> (Khadra et al, 2000).`,
        state: `notAnswered`,
        userAnswered: []
              ,
        type: `MCSS`},
      {
        q: `<!--29. -->Which of the following is not a high-risk factor in urothelial cancer formation in patients with microscopic hematuria?`,
        q2: ``,
        q3: [],
        option: [`<!--a. -->Age younger than 40 years`, 
        `<!--b. -->Smoking`, 
        `<!--c. -->History of pelvic radiation`, 
        `<!--d. -->Urinary tract infections`, 
        `<!--e. -->Previous urologic surgery`,
        ],
        optionStyleType: `st-lower-alpha`,
        answer: [0],
        ansText: `Rationale: The guidelines recommend consideration for reevaluation of low-risk individuals with microscopic hematuria, but repeat evaluation every 6 months with a urinalysis, cytology, and blood pressure (to detect renal disease) is recommended for high-risk patients. Age younger than 40 years is the only factor that is not associated with an increased risk of malignancy.`,
        state: `notAnswered`,
        userAnswered: []
              ,
        type: `MCSS`},
      {
        q: `<!--30. -->Commercially available fluorescence in situ hybridization kits test for abnormalities in which of the following chromosomes?`,
        q2: ``,
        q3: [],
        option: [`<!--a. -->3, 7, 9, 17`, 
        `<!--b. -->2, 5, 8`, 
        `<!--c. -->4, 6, 9`, 
        `<!--d. -->1, 10, 12`, 
        `<!--e. -->13, 14, 16`,
        ],
        optionStyleType: `st-lower-alpha`,
        answer: [0],
        ansText: `Rationale: Fluorescence in situ hybridization (FISH) identifies fluorescently labeled DNA probes that bind to intranuclear chromosomes. <b>The current commercially available probes evaluate aneuploidy for chromosomes 3, 7, 17, and homozygous loss of 9p 21</b> (Zwarthoff, 2008). The median sensitivity and specificity of FISH analysis is 79% and 70%, respectively (van Rhijn et al, 2005).`,
        state: `notAnswered`,
        userAnswered: []
              ,
        type: `MCSS`},
      {
        q: `<!--31. -->Microsatellite analysis:`,
        q2: ``,
        q3: [],
        option: [`<!--a. -->detects telomeric repeats.`, 
        `<!--b. -->amplifies DNA repeats in the genome.`, 
        `<!--c. -->evaluates abnormalities on chromosome 9.`, 
        `<!--d. -->detects DNA methylation.`, 
        `<!--e. -->identifies hereditary urothelial cancer.`,
        ],
        optionStyleType: `st-lower-alpha`,
        answer: [1],
        ansText: `Rationale: There are multiple markers available to identify short DNA repeats present throughout the chromosomes that are lost in some tumor cells. Microsatellite analysis amplifies these repeats in the genome that are highly polymorphic, and PCR amplification can detect tumor-associated loss of heterozygosity by comparing the peak ratio of the two alleles in tumor DNA in a urine sample with that ratio in a blood sample from the same individual (Steiner et al, 1997; Wang et al, 1997). The sensitivity and specificity of microsatellite analysis for the detection of urothelial carcinoma range from 72% to 97% and 80% to 100%, respectively (Steiner et al, 1997; Wang et al, 1997). Microsatellite analysis evaluates abnormalities on all chromosomes.`,
        state: `notAnswered`,
        userAnswered: []
              ,
        type: `MCSS`},
      {
        q: `<!--32. -->Smoking is responsible for what percent of bladder cancer in males?`,
        q2: ``,
        q3: [],
        option: [`<!--a. -->5%`, 
        `<!--a. -->20%`, 
        `<!--a. -->40%`, 
        `<!--a. -->60%`, 
        `<!--a. -->80%`,
        ],
        optionStyleType: `st-lower-alpha`,
        answer: [2],
        ansText: `Rationale: Smoking is responsible for 30% to 50% of all bladder cancers in males, and smokers have a twofold to sixfold greater risk for bladder cancer (Brennan et al, 2000; Boffetta, 2008). Smoking cessation will decrease the risk of eventual urothelial cancer formation in a linear fashion. After 15 years of not smoking, the risk of cancer formation is the same as for a person who never smoked (Smoke IAfRoCT, 2004). The strong influence of smoking in bladder cancer formation prevents accurate determination of other, less significant dietary, micronutrient, or lifestyle changes that may alter bladder cancer formation.`,
        state: `notAnswered`,
        userAnswered: []
              ,
        type: `MCSS`},
      {
        q: `<!--33. -->Which of the following is not sensitive to cisplatin chemotherapy?`,
        q2: ``,
        q3: [],
        option: [`<!--a. -->High-grade urothelial cancer`, 
        `<!--b. -->Micropapillary cancer`, 
        `<!--c. -->Squamous cell cancer`, 
        `<!--d. -->Adenocarcinoma`, 
        `<!--e. -->Small cell cancer`,
        ],
        optionStyleType: `st-lower-alpha`,
        answer: [1],
        ansText: `Rationale: The most effective treatment for all stages of micropapillary urothelial carcinoma is surgical resection. Treatment with transurethral resection and BCG therapy is ineffective unless the tumor is completely resected (Kamat et al, 2007). <b>Neoadjuvant chemotherapy does not appear effective in micropapillary urothelial carcinoma, similar to ovarian cancer</b> (Bristow et al, 2002; Kamat et al, 2007). Neoadjuvant chemotherapy may actually worsen survival by delaying therapy when compared with immediate cystectomy. Cisplatin is effective against urothelial cancer and the associated variants of squamous cell, adenocarcinoma, and small cell cancer.`,
        state: `notAnswered`,
        userAnswered: []
              ,
        type: `MCSS`},
      {
        q: `<!--34. -->Nested variant of urothelial cancer can be confused with:`,
        q2: ``,
        q3: [],
        option: [`<!--a. -->cystitis cystica.`, 
        `<!--b. -->micropapillary cancer.`, 
        `<!--c. -->squamous cell cancer.`, 
        `<!--d. -->small cell cancer.`, 
        `<!--e. -->high-grade urothelial cancer.`,
        ],
        optionStyleType: `st-lower-alpha`,
        answer: [0],
        ansText: `Rationale: The nested variant of urothelial cancer is a rare but aggressive cancer that has a male-to-female ratio of 6:1 and can be confused with benign lesions, such as Von Brunn nests that are in the lamina propria, cystitis cystica, and inverted papillomas (Holmang and Johansson, 2001). There is little nuclear atypia in nested variant urothelial carcinoma, but the tumor cells will often contain areas with large nuclei and mitotic figures. <b>The mortality rate from nested variant urothelial carcinoma, despite aggressive therapy, is significant, with 70% dying of their disease within 3 years</b> (Paik and Park, 1996).`,
        state: `notAnswered`,
        userAnswered: []
              ,
        type: `MCSS`},
      {
        q: `<!--35. -->The most common sarcoma involving the bladder is:`,
        q2: ``,
        q3: [],
        option: [`<!--a. -->angiosarcoma.`, 
        `<!--b. -->chondrosarcoma.`, 
        `<!--c. -->leiomyosarcoma.`, 
        `<!--d. -->rhabdomyosarcoma.`, 
        `<!--e. -->osteosarcoma.`,
        ],
        optionStyleType: `st-lower-alpha`,
        answer: [2],
        ansText: `Rationale: <b>Leiomyosarcoma is the most common histologic subtype, followed by rhabdomyosarcoma and then, rarely, angiosarcomas, osteosarcomas, and carcinosarcomas.</b> The male-to-female ratio is 2:1, and the average age at presentation is in the sixth decade of life. There are no clear agents that cause bladder sarcomas, although there is an association with pelvic radiation and systemic chemotherapy for other malignancies (Spiess et al, 2007). Importantly, bladder sarcomas are not smoking related.`,
        state: `notAnswered`,
        userAnswered: []
              ,
        type: `MCSS`},
      {
        q: `<!--36. -->Signet ring cell cancers:`,
        q2: ``,
        q3: [],
        option: [`<!--a. -->have a good prognosis.`, 
        `<!--b. -->are sensitive to doxorubicin chemotherapy.`, 
        `<!--c. -->usually present in advanced stage.`, 
        `<!--d. -->are responsive to radiation therapy.`, 
        `<!--e. -->are low-grade at initial presentation.`,
        ],
        optionStyleType: `st-lower-alpha`,
        answer: [2],
        ansText: `Rationale: Primary signet ring cell carcinoma of the bladder is extremely rare, making up less than 1% of all epithelial bladder neoplasms (Morelli et al, 2006). <b>Signet ring cell carcinoma can be of urachal origin and directly extend into the bladder. These tumors generally present as high-grade, high-stage tumors and have a uniformly poor prognosis.</b> The primary treatment is radical cystectomy; however, in the majority of cases there are regional or distant metastases at the time of presentation, and the mean survival time is less than 20 months (Torenbeek et al, 1996). There are reports of elevated carcinoembryonic antigen (CEA) in patients with signet ring cell carcinoma. The prognostic significance of this elevated serum marker is unclear (Morelli et al, 2006). Understaging is very common in signet ring cell carcinoma, with peritoneal studding common at the time of surgical exploration.`,
        state: `notAnswered`,
        userAnswered: []
              ,
        type: `MCSS`},
      {
        q: `<!--37. -->The risk of bladder cancer formation in a spinal cord–injured patient is:`,
        q2: ``,
        q3: [],
        option: [`<!--a. -->less than 5%.`, 
        `<!--b. -->20%.`, 
        `<!--b. -->40%.`, 
        `<!--b. -->60%.`, 
        `<!--b. -->80%.`,
        ],
        optionStyleType: `st-lower-alpha`,
        answer: [0],
        ansText: `Rationale: Spinal cord–injured patients are at risk for developing squamous cell carcinoma, most likely due to chronic catheter irritation and infection. Older studies have suggested a 2.5% to 10% incidence of squamous cell carcinoma in the spinal cord–injured population, with a mean delay of 17 years after the spinal cord injury (Kaufman et al., 1977). More recent analysis of the association of spinal cord injury and bladder cancer formation has shown a remarkably lower risk of bladder cancer formation of 0.38%, most likely because of better catheter care (Bickel et al., 1991). This supports the concept that chronic infection and foreign bodies can lead to bladder cancer formation.`,
        state: `notAnswered`,
        userAnswered: []
              ,
        type: `MCSS`},
      {
        q: `<!--38. -->For patients undergoing radical cystectomy for urothelial cancer, the risk of identifying prostatic urethral disease is:`,
        q2: ``,
        q3: [],
        option: [`<!--a. -->less than 5%.`, 
        `<!--b. -->20%.`, 
        `<!--c. -->40%.`, 
        `<!--c. -->60%.`, 
        `<!--c. -->80%.`,
        ],
        optionStyleType: `st-lower-alpha`,
        answer: [2],
        ansText: `Rationale: Prostatic urethral cancer is associated with urothelial cancer of the bladder in 90% of cases, primarily CIS, and most will have multifocal bladder tumors. However, the incidence of prostatic urethral disease in patients with primary urothelial cancer is only 3% (Rikken et al., 1987; Millan-Rodriguez et al., 2000). <b>Secondary prostatic urethral involvement in patients with a history of urothelial cancer is approximately 15% at 5 years and 30% at 15 years, almost uniformly associated with extensive intravesical therapy</b> (Herr and Donat, 1999). For patients undergoing radical cystectomy for urothelial cancer, the risk of identifying prostatic urethral disease is 40%.`,
        state: `notAnswered`,
        userAnswered: []
              ,
        type: `MCSS`},
      {
        q: `<!--39. -->Which of the following is NOT a risk factor for prostatic urethral cancer?`,
        q2: ``,
        q3: [],
        option: [`<!--a. -->Previous intravesical therapy`, 
        `<!--b. -->CIS of the trigone`, 
        `<!--c. -->CIS of the distal ureters`, 
        `<!--d. -->Low-grade urothelial cancer`, 
        `<!--e. -->Recurrent bladder tumors`,
        ],
        optionStyleType: `st-lower-alpha`,
        answer: [3],
        ansText: `Rationale: <b>Risk factors for prostatic urethral involvement are CIS of the trigone, bladder neck, distal ureters, recurrent bladder tumors, and a history of intravesical chemotherapy</b> (Wood et al., 1989b). Low-grade tumors rarely involve the prostatic urethra.`,
        state: `notAnswered`,
        userAnswered: []
              ,
        type: `MCSS`},
      {
        q: `<!--1. --><b>Pathology</b><br/><br/>A 70-year-old man has microscopic hematuria. Cytology and computed tomography (CT) scan are negative. Cystoscopy reveals a raised 3-mm lesion on the trigone. The lesion is biopsied and is depicted in <a href="83dc673001d14b4493acf37fbd172db4">Fig. 135.1A</a> and <a href="83dc673001d14b4493acf37fbd172db4">B</a>, and is reported as adenocarcinoma. The next step in management is:`,
        q2: ``,
        q3: [],
        option: [`<!--a. -->review the pathology slides with the pathologist.`, 
        `<!--b. -->cystectomy.`, 
        `<!--c. -->intravesical chemotherapy.`, 
        `<!--d. -->bone scan.`, 
        `<!--e. -->ask for special stains from pathology.`,
        ],
        optionStyleType: `st-lower-alpha`,
        answer: [0],
        ansText: `Rationale: This is a classic inverted papilloma, and the inexperienced pathologist might mistake it for an adenocarcinoma. The location of the lesion would be unusual for adenocarcinoma, particularly in a patient with no risk factors, and should alert the clinician to review the slides with the pathologist.`,
        state: `notAnswered`,
        userAnswered: []
              ,
        type: `MCSS`},
      {
        q: `<!--2. -->A 65-year-old man has gross hematuria. He has a history of tuberculosis. Cytology is suspicious, CT scan is normal, and cystoscopy reveals a papillary lesion cephalad to the trigone. The lesion is visually completely resected (<a href="f219db573b1a42a5923efe768193f121">Fig. 135.2</a>) and is reported as high-grade invasive urothelial carcinoma. The next step in management is:`,
        q2: ``,
        q3: [],
        option: [`<!--a. -->intravesical BCG.`, 
        `<!--b. -->immediate intravesical mitomycin C.`, 
        `<!--c. -->repeat transurethral resection of bladder at the previous biopsied site.`, 
        `<!--d. -->a cystectomy.`, 
        `<!--e. -->ask the pathologist if there is muscularis propria in the specimen.`,
        ],
        optionStyleType: `st-lower-alpha`,
        answer: [4],
        ansText: `Rationale: There are clear bundles of muscularis propria in the micrograph making the tumor at least a T2.`,
        state: `notAnswered`,
        userAnswered: []
              ,
        type: `MCSS`},
      {
        q: `<!--1. --><b>Imaging</b><br/><br/>See <a href="ec874f98aa6a4190bc641e6be77f3e27">Fig. 135.3</a>. The depicted findings have an association with:`,
        q2: ``,
        q3: [],
        option: [`<!--a. -->bladder carcinoma.`, 
        `<!--b. -->previous trauma.`, 
        `<!--c. -->recurrent urinary tract infections.`, 
        `<!--d. -->urolithiasis.`, 
        `<!--e. -->ureteral spasm.`,
        ],
        optionStyleType: `st-lower-alpha`,
        answer: [0],
        ansText: `Rationale: Pseudodiverticulosis of the ureter is associated with bladder carcinoma in 30% of cases. This association has led many to recommend that patients with this diagnosis undergo surveillance of their bladder for the development of urothelial neoplasms. The etiology is unknown.`,
        state: `notAnswered`,
        userAnswered: []
              ,
        type: `MCSS`},
      {
        q: `<!--2. --><a href="54c31ddc65244664a6bcfe5ffb80b498">Fig. 135.4A</a> is a delayed contrast-enhanced image through the pelvic ureters, and <a href="54c31ddc65244664a6bcfe5ffb80b498">Fig. 135.4B</a> is an early contrast-enhanced image through the bladder. The next step in management is:`,
        q2: ``,
        q3: [],
        option: [`<!--a. -->shockwave lithotripsy.`, 
        `<!--b. -->percutaneous nephrostolithotomy.`, 
        `<!--c. -->cystoscopy.`, 
        `<!--d. -->cystoscopy with ureteroscopy.`, 
        `<!--e. -->follow-up with imaging in 6 months.`,
        ],
        optionStyleType: `st-lower-alpha`,
        answer: [3],
        ansText: `Rationale: There are multiple enhancing masses in the fluid-filled urinary bladder on the early image. On the delayed image, the ureters are opacified with contrast, and there is a filling defect seen in the mildly dilated right ureter, suspicious for a synchronous ureteral lesion.`,
        state: `notAnswered`,
        userAnswered: []
              ,
        type: `MCSS`},
      
     
];
      
     