var quiz = [
    

    {
        q: `Congenital bladder diverticula are:`,
        q2: ``,
        q3: [],
        option: [`usually multiple.`, 
        `strongly associated with bladder outlet obstruction.`, 
        `often found in smooth-walled bladders.`, 
        `located at the dome.`, 
        `usually less than 1 cm in size.`],
        optionStyleType: `st-lower-alpha`,
        answer: [2],
        ansText:`Rationale: <!--<b>c. Often found in smooth-walled bladders.</b>--> Unlike acquired bladder diverticula, congenital lesions are found in smooth-walled bladders, often adjacent to the ureteric orifice. <b>Congenital bladder diverticula are usually solitary, often large, and not associated with bladder outlet obstruction.</b> Congenital diverticula at the dome may be related to prune-belly syndrome, posterior urethral valves, or urachal anomalies.`, 
        state: `notAnswered`,
        userAnswered: []
    ,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`        ,
        type: `MCSS`},
    {
        q: `Acquired bladder diverticula are most commonly located:`,
        q2: ``,
        q3: [],
        option: [`near the urethrovesical junction.`, 
        `adjacent to the ureter.`, 
        `at the dome.`, 
        `at the 10 and 2 o’clock positions.`, 
        `posteriorly.`],
        optionStyleType: `st-lower-alpha`,
        answer: [1],
        ansText:`Rationale: <!--<b>b. Adjacent to the ureter.</b>--> Similar to congenital bladder diverticula, acquired bladder diverticula are often located near the ureteric orifice. This area of the bladder is thought to be a location of relative anatomic weakness of the bladder wall, predisposing to the formation of bladder diverticula.`, 
        state: `notAnswered`,
        userAnswered: []
    ,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`        ,
        type: `MCSS`},
    {
        q: `Videourodynamic evaluation in an adult female with a bladder diverticulum will likely reveal:`,
        q2: ``,
        q3: [],
        option: [`impaired compliance.`, 
        `bladder outlet obstruction.`, 
        `intrinsic sphincter deficiency (ISD).`, 
        `low-pressure, low-flow voiding.`, 
        `no abnormality.`],
        optionStyleType: `st-lower-alpha`,
        answer: [1],
        ansText:`Rationale: <!--<b>b. Bladder outlet obstruction.</b>--> <b>Bladder diverticula in adults are most commonly associated with some type of bladder outlet obstruction.</b> In an adult female this may be due to prior anti-incontinence surgery (iatrogenic), dysfunctional voiding, neurogenic causes (e.g., detrusor external sphincter dyssynergia), or a variety of other conditions such as obstructing vaginal or urethral masses (e.g., malignancy).`, 
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `Pathologic examination of a surgical bladder diverticulectomy specimen will likely reveal:`,
        q2: ``,
        q3: [],
        option: [`absence of epithelium.`, 
        `premalignant or malignant changes.`, 
        `nephrogenic metaplasia.`, 
        `a poorly developed muscularis propria layer.`, 
        `trabeculation of the smooth muscle layer.`],
        optionStyleType: `st-lower-alpha`,
        answer: [3],
        ansText:`Rationale: <!--<b>d. A poorly developed muscularis propria layer.</b>--> Although varying amounts of detrusor muscle fibers may be found on pathologic examination of surgical excised bladder diverticula, the muscularis propria layer is usually incomplete and the fibers are disorganized. Such a lack of a well-developed muscularis propria layer is a hallmark of a bladder diverticulum. Absence of an epithelial layer, nephrogenic metaplasia, and malignant changes are uncommonly reported in the histologic evaluation of bladder diverticula. Typically there is no trabeculation within the wall of a bladder diverticulum.`, 
        state: `notAnswered`,
        userAnswered: []
    ,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`        ,
        type: `MCSS`},
    {
        q: `The most common malignant tumor associated with bladder diverticula is:`,
        q2: ``,
        q3: [],
        option: [`urothelial.`, 
        `squamous cell.`, 
        `adenocarcinoma.`, 
        `sarcomatous.`, 
        `undifferentiated.`],
        optionStyleType: `st-lower-alpha`,
        answer: [0],
        ansText:`Rationale: <!--<b>a. Urothelial.</b>--> The most common malignant tumors seen within bladder diverticula are urothelial. The other types of tumors can be seen but are much less common.`, 
        state: `notAnswered`,
        userAnswered: []
    ,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`        ,
        type: `MCSS`},
    {
        q: `A 68-year-old man presents with hematuria. Cystoscopy reveals a 15-cm bladder diverticulum with a 3-mm papillary lesion at the base of the diverticulum. The next step is:`,
        q2: ``,
        q3: [],
        option: [`biopsy of the papillary lesion.`, 
        `transurethral resection of the papillary lesion with deep muscle resection.`, 
        `urodynamics and transurethral prostatectomy (TURP) if bladder outlet obstruction is noted.`, 
        `bladder diverticulectomy.`, 
        `radical cystectomy and urinary diversion.`],
        optionStyleType: `st-lower-alpha`,
        answer: [0],
        ansText:`Rationale: <!--<b>a. Biopsy of the papillary lesion.</b>--> A papillary lesion in a bladder diverticulum, similar to the rest of the urinary tract, may indicate a malignancy, but it may also represent a benign lesion. Biopsy is warranted. Care should be taken to avoid perforation of the diverticular wall during the biopsy as the wall lacks a muscularis propria layer. A 3-mm lesion can easily be biopsied without the use of a resectoscope. In the event that the biopsy demonstrates malignancy, perforation of the bladder wall risks malignant dissemination.`, 
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `Acquired bladder diverticula are commonly found in association with:`,
        q2: ``,
        q3: [],
        option: [`prostatic obstruction.`, 
        `calyceal diverticula.`, 
        `nephrogenic adenoma.`, 
        `infection of perivesical glands.`, 
        `erectile dysfunction (ED).`],
        optionStyleType: `st-lower-alpha`,
        answer: [0],
        ansText:`Rationale: <!--<b>a. Prostatic obstruction.</b>--> Acquired bladder diverticula are most commonly associated with bladder outlet obstruction (approximately 70%). They are also more common in males than in females. The most common cause of bladder outlet obstruction in males is prostatic obstruction. There is no known association of bladder diverticula with calyceal diverticula, ED, nephrogenic adenoma, or perivesical gland infection.`, 
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `A 65-year-old man with bladder outlet obstruction and a 5-cm bladder diverticulum undergoes uneventful TURP. Postoperatively, the patient’s symptoms are resolved, and a voiding cystourethrogram (VCUG) demonstrates satisfactory emptying of the bladder and the bladder diverticulum. The next step is:`,
        q2: ``,
        q3: [],
        option: [`annual surveillance with cystoscopy and urine cytology.`, 
        `discharge from urologic care.`, 
        `transvesical bladder diverticulectomy.`, 
        `repeat urodynamics.`, 
        `computed tomographic (CT) cystogram.`],
        optionStyleType: `st-lower-alpha`,
        answer: [0],
        ansText:`Rationale: <!--<b>a. Annual surveillance with cystoscopy and urine cytology.</b>--> Although the bladder diverticulum drains well and the patient is asymptomatic, long-term follow-up of bladder diverticula is warranted. <b>The natural history of such lesions is unknown, and although the etiology of malignant transformation is thought to involve urinary stasis, this is unproved. Furthermore, it is possible that premalignant changes may have occurred during the time that the diverticulum was not draining well.</b>`, 
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `Ten years following TURP, a 71-year-old man with congestive heart failure (CHF) and atrial fibrillation who is on warfarin sodium (Coumadin) has recurrent urinary tract infections (UTIs) and an American Urological Association (AUA) symptom score of 25. A videourodynamic study shows a 14-cm poorly emptying bladder diverticulum. The peak subtracted detrusor pressure (Pdet) during micturition is 15 cm H<sub>2</sub>O with a Qmax of 3 mL/s. Renal ultrasonography is normal. The next step is:`,
        q2: ``,
        q3: [],
        option: [`repeat TURP.`, 
        `clean intermittent self-catheterization (CIC).`, 
        `observation.`, 
        `bethanechol.`, 
        `CT urography.`],
        optionStyleType: `st-lower-alpha`,
        answer: [1],
        ansText:`Rationale: <!--<b>b. Clean intermittent self-catheterization (CIC).</b>--> This patient is at high risk for major abdominal surgery. Removal of his diverticulum is likely to be a large surgical undertaking with substantial risk and would be ill advised unless other conservative measures failed. Endoscopic treatment with TURP is also a risk because of anticoagulation. His detrusor pressure is low, suggesting that even an adequate outlet procedure (in this patient without definite evidence of obstruction) will not provide satisfactory emptying of the diverticulum. He has normal upper tracts but recurrent UTIs, thus observation would not be optimal. It is likely that his UTIs are due to urinary stasis in the diverticulum. CIC should adequately empty the diverticulum and reduce the risk of ongoing UTIs.`, 
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `Endoscopic examination of the lower urinary tract in the setting of bladder diverticula:`,
        q2: ``,
        q3: [],
        option: [`is best performed with a rigid cystoscope.`, 
        `is associated with a high risk of perforation.`, 
        `should include examination of the entire interior of the diverticulum.`, 
        `is not indicated if an elective submucosal bladder diverticulectomy is planned.`, 
        `should always be performed with concomitant bilateral retrograde pyelography (RPG).`],
        optionStyleType: `st-lower-alpha`,
        answer: [2],
        ansText:`Rationale: <!--<b>c. Should include examination of the entire interior of the diverticulum.</b>--> Periodic endoscopic examination of bladder diverticula is warranted because of the risk of malignant transformation and early transmural involvement. The entire lining of the diverticulum should be examined. Rigid and flexible cystoscopes can be used. The upper urinary tract should be imaged. However, RPGs are not necessary unless otherwise indicated for another reason (e.g., a filling defect on urography).`, 
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `Bladder diverticula:`,
        q2: ``,
        q3: [],
        option: [`often do not produce specific symptoms.`, 
        `can be associated with UTIs.`, 
        `are commonly diagnosed incidentally during the evaluation of other symptoms or conditions.`, 
        `may be associated with persistent pyuria.`, 
        `all of the above.`],
        optionStyleType: `st-lower-alpha`,
        answer: [4],
        ansText:`Rationale: <!--<b>e. All of the above.</b>--> Bladder diverticula are most commonly recognized incidentally on evaluation for other signs and symptoms. There are no symptoms that are specific to bladder diverticula. Bladder diverticula are associated with UTIs and pyuria in some individuals.`, 
        state: `notAnswered`,
        userAnswered: []
    ,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`        ,
        type: `MCSS`},
    {
        q: `Bladder diverticula associated with bladder outlet obstruction:`,
        q2: ``,
        q3: [],
        option: [`are usually found in the absence of cellules and saccules.`, 
        `are associated with the universal finding of ipsilateral vesicoureteral reflux.`, 
        `cannot be imaged by CT.`, 
        `are associated with medial deviation of the pelvic ureter.`, 
        `are less likely to be associated with malignancy compared with congenital bladder diverticula.`],
        optionStyleType: `st-lower-alpha`,
        answer: [3],
        ansText:`Rationale: <!--<b>d. Are associated with medial deviation of the pelvic ureter.</b>--> Bladder diverticula found in association with lower urinary tract obstruction are commonly seen with saccules and cellules. <b>Reflux is not a common finding with acquired bladder diverticula but may be present in some individuals, especially those with “Hutch” diverticula.</b> Congenital bladder diverticula are not associated with malignancy. Medial deviation of the ureter can be seen on intravenous urography and CT, with some large bladder diverticula due to the location of the diverticula relative to the ureter.`, 
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `Increased size of urethral diverticula (UDs) at presentation correlates with:`,
        q2: ``,
        q3: [],
        option: [`increased symptoms.`, 
        `risk of UTI.`, 
        `risk of recurrence postoperatively.`, 
        `risk of malignancy.`, 
        `risk of incontinence.`],
        optionStyleType: `st-lower-alpha`,
        answer: [2],
        ansText:`Rationale: <!--<b>c. Risk of recurrence postoperatively.</b>--> Although some UDs can be quite large, symptoms, malignancy risk, incontinence, and risk of UTI are not known to correlate with size. Large diverticula, including those extending in a “saddle bag” configuration, are more likely to recur.`, 
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `Common symptoms associated with UDs include all of the following EXCEPT:`,
        q2: ``,
        q3: [],
        option: [`vaginal pruritus.`, 
        `dysuria.`, 
        `dyspareunia.`, 
        `postvoid dribbling.`, 
        `urinary urgency and frequency.`],
        optionStyleType: `st-lower-alpha`,
        answer: [0],
        ansText:`Rationale: <!--<b>a. Vaginal pruritus.</b>--> Vaginal pruritus is not a symptom of UDs. Inflammatory and infectious conditions as well as lichen sclerosis (vulvar dystrophy) may cause vaginal pruritus. The other symptoms listed are often, although not invariably, individually or collectively associated with UDs. The classic triad of symptoms of UDs includes the “3 D’s”—dysuria, postvoid dribbling, and dyspareunia—although these are seen only rarely in the same patient.`, 
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `In a 35-year-old woman a 1.5-cm firm anterior vaginal wall mass is noted approximately 2 cm proximal to the urethral meatus at the level of the mid-urethra without distorting the urethral meatus. It is nontender. Urine analysis is unremarkable. This mass may represent any of the following EXCEPT:`,
        q2: ``,
        q3: [],
        option: [`vaginal wall cyst.`, 
        `Skene gland abscess.`, 
        `UD.`, 
        `vaginal leiomyoma.`, 
        `Gartner duct cyst.`],
        optionStyleType: `st-lower-alpha`,
        answer: [1],
        ansText:`Rationale: <!--<b>b. Skene gland abscess.</b>--> <b>Skene gland abscess is usually associated with distortion of the urethral meatus due to its distal location.</b> These lesions are also often symptomatic, with associated dyspareunia and tenderness on physical examination. <b>Vaginal wall cysts, vaginal leiomyomas, and Gartner duct cysts are firm anterior vaginal wall masses and are often nontender.</b> UDs in some cases may be asymptomatic and found incidentally in the evaluation of other conditions, but they do not result in distortion of the urethral meatus.`, 
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `The ostium of a UD is:`,
        q2: ``,
        q3: [],
        option: [`most commonly found in the proximal third of the urethra.`, 
        `most commonly found at the 10 and 2 o’clock position in the urethral lumen.`, 
        `usually seen on transvaginal ultrasound imaging.`, 
        `unable to be visualized with rigid cystoscopy.`, 
        `usually located in the ventrolateral urethra.`],
        optionStyleType: `st-lower-alpha`,
        answer: [4],
        ansText:`Rationale: <!--<b>e. Usually located in the ventrolateral urethra.</b>--> <b>The ostium (opening) of a UD is most commonly found in the middle or distal third of the urethra, at the 4 and 8 o’clock positions.</b> They are usually too small to be visualized by ultrasound but can often be seen with both rigid and flexible cystoscopy as small openings in the urethral lumen ventrolaterally.`, 
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `Two weeks after removal of a 5-cm proximal UD extending beneath the trigone of the bladder, a 48-year-old woman returns to the office with complaints of urine staining her undergarments. Possible etiologies include:`,
        q2: ``,
        q3: [],
        option: [`urethrovaginal fistula.`, 
        `ureterovaginal fistula.`, 
        `vesicovaginal fistula.`, 
        `stress urinary incontinence (SUI).`, 
        `all of the above.`],
        optionStyleType: `st-lower-alpha`,
        answer: [4],
        ansText:`Rationale: <!--<b>e. All of the above.</b>--> Complications of urethral diverticulectomy include urinary fistulas as well as stress incontinence. Large diverticula may extend beneath the trigone of the bladder, and excision of such lesions risks injury to the urethra, bladder, and ureters. De novo SUI may occur following urethral diverticulectomy, which may be due to distortion or injury to the sphincter mechanism.`, 
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `During excision of the epithelial lining (sac) of a UD, a portion of the indwelling urethral catheter is seen at the base of the dissection. The next step is to:`,
        q2: ``,
        q3: [],
        option: [`close the urethra and abort the procedure.`, 
        `perform buccal mucosal urethroplasty and abort the procedure.`, 
        `complete the urethral diverticulectomy.`, 
        `construct a vaginal inversion flap and close the urethra.`, 
        `close the urethra primarily, place a suprapubic tube, and harvest a Martius flap.`],
        optionStyleType: `st-lower-alpha`,
        answer: [2],
        ansText:`Rationale: <!--<b>c. Complete the urethral diverticulectomy.</b>--> Successful excision of a UD involves removal of the ostium that connects with the urethral lumen. This often results in direct visualization of the urethral catheter within the urethral lumen during surgery. The urethral defect is closed primarily with absorbable suture in a watertight fashion following completion of the removal of the sac. Additional procedures such as buccal mucosal urethroplasty, Martius flap, or vaginal flaps are not necessary to close the urethra.`, 
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `A VCUG is performed for evaluation of a possible UD. The filling images are nondiagnostic. The radiologist calls you because the patient is unable to void under fluoroscopy in the radiology suite. The patient is taken off the imaging table and is able to void in the adjacent bathroom. The next step is to:`,
        q2: ``,
        q3: [],
        option: [`obtain a CT cystogram.`, 
        `do a transvaginal ultrasound.`, 
        `obtain postvoid images.`, 
        `implement endoluminal magnetic resonance imaging (MRI).`, 
        `positive pressure urethrography (PPU).`],
        optionStyleType: `st-lower-alpha`,
        answer: [2],
        ansText:`Rationale: <!--<b>c. Obtain postvoid images.</b>--> In the absence of voiding images, many UDs will not be visualized during fluoroscopy as there is no contrast in the urethra. This is a nondiagnostic but incomplete study. Postvoid images will often reveal retained contrast in the diverticulum. CT, ultrasound, MRI, and PPU are all potentially useful studies in the evaluation of diverticula, but every effort should be made to maximize the diagnostic potential of each radiographic imaging technique, and a postvoid image in this clinical scenario may provide useful diagnostic information.`, 
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `The most common malignancy found in UDs is:`,
        q2: ``,
        q3: [],
        option: [`squamous.`, 
        `urothelial.`, 
        `adenocarcinoma.`, 
        `undifferentiated.`, 
        `sarcomatous.`],
        optionStyleType: `st-lower-alpha`,
        answer: [2],
        ansText:`Rationale: <!--<b>c. Adenocarcinoma.</b>--> The most common malignant tumor type found in UDs is adenocarcinoma. Although the other malignant tumors listed may be found, adenocarcinoma is the most common.`, 
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `Principles of surgical urethral diverticulectomy include all of the following EXCEPT:`,
        q2: ``,
        q3: [],
        option: [`preservation or creation of urinary continence.`, 
        `excision of all identifiable periurethral fascia.`, 
        `identification of the ostium of the UD.`, 
        `closure of periurethral fascia following removal of the UD.`, 
        `watertight closure of the urethra.`],
        optionStyleType: `st-lower-alpha`,
        answer: [1],
        ansText:`Rationale: <!--<b>b. Excision of all identifiable periurethral fascia.</b>--> <b>Preservation of periurethral fascia is an important step in urethral diverticulectomy. This tissue is very important in reconstruction of the urethra to prevent fistula formation and close dead space.</b> This tissue should not be excised.`, 
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `The initial event implicated in the formation of most UDs is:`,
        q2: ``,
        q3: [],
        option: [`congenital lack of fusion of the urethral crest.`, 
        `infection of vaginal cysts.`, 
        `a traumatic vaginal delivery.`, 
        `infection of the periurethral glands.`, 
        `dysfunctional voiding.`],
        optionStyleType: `st-lower-alpha`,
        answer: [3],
        ansText:`Rationale: <!--<b>d. Infection of the periurethral glands.</b>--> Infection of the periurethral glands is felt to be the initial step in the formation of UDs. Such infection may lead to periurethral abscess formation and development of a cavity or space within the periurethral fascia that then becomes the anatomic location of a UD.`, 
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `In a patient with bothersome SUI and UD, anti-incontinence surgery is being considered. Of the choices listed below, the best concomitant surgical procedure to treat the SUI is to provide a:`,
        q2: ``,
        q3: [],
        option: [`transobturator midurethral sling.`, 
        `retropubic midurethral sling.`, 
        `single-incision synthetic sling.`, 
        `autologous pubovaginal fascial sling.`, 
        `polypropylene bladder neck sling.`],
        optionStyleType: `st-lower-alpha`,
        answer: [3],
        ansText:`Rationale: <!--<b>d. Autologous pubovaginal fascial sling.</b>--> SUI may accompany UDs. In symptomatic patients, concomitant repair can be considered. UDs connect to the urethral lumen, and therefore the surgical excision of these lesions requires suture repair and closure of the ostium of the UD where it connects to the urethra. <b>In such settings, the use of synthetic material for a sling is not advisable because of the risk of subsequent erosion of the synthetic material into the urethra.</b> Autologous fascia is an excellent choice for a concomitant sling at the time of urethral diverticulectomy.`, 
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `The ostia of UD are most commonly found at:`,
        q2: ``,
        q3: [],
        option: [`12 o’clock.`, 
        `6 o’clock.`, 
        `4 and 8 o’clock.`, 
        `10 and 12 o’clock.`, 
        `none of the above.`],
        optionStyleType: `st-lower-alpha`,
        answer: [2],
        ansText:`Rationale: <!--<b>c. 4 and 8 o’clock.</b>--> <b>UDs are thought to originate from infection of the periurethral glands. Such glands are located along the urethra and arborize laterally. They generally drain medially into the urethral lumen ventrolaterally at approximately the 4 and 8 o’clock positions of the middle and distal third of the urethra.</b>`, 
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `<b>Imaging</b><br/><br/>A 47-year-old woman presents with dribbling and recurrent UTIs; see <a class="lightboxcallout" img-ref="image_fig_130_1" href="caead372ceac4a278afe00eb1b2786cf">Fig. 130.1</a>.<br/><br/>The most likely diagnosis on this axial and coronal T2-weighted MRI done with an endovaginal coil is:`,
        q2: ``,
        q3: [],
        option: [`bladder prolapse.`, 
        `urethral diverticulum.`, 
        `bladder diverticulum.`, 
        `ureteral duplication.`, 
        `ectopic ureter.`],
        optionStyleType: `st-lower-alpha`,
        answer: [1],
        ansText:`Rationale: <!--<b>b. Urethral diverticulum.</b>--> These images demonstrate a fluid collection surrounding the urethra, compatible with a saddlebag UD. The coronal image clearly shows that the collection is separate from the bladder. (Options a and c are incorrect. An ectopic ureter would not have a saddlebag configuration.)`, 
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`}

    



];
