var quiz = [
   
   
    {
        q: `<!--1. -->Which of the following is an absolute indication for open repair of blunt bladder rupture injury?`,
        q2: ``,
        q3: [],
        option: [`<!--a. -->Significant extraperitoneal bladder rupture with extravasation of contrast agent into the scrotum`, 
        `<!--b. -->Significant extraperitoneal bladder rupture with gross hematuria`, 
        `<!--c. -->Significant extraperitoneal bladder rupture that has not healed after 3 weeks of Foley catheter drainage`, 
        `<!--d. -->Intraperitoneal bladder rupture`, 
        `<!--e. -->Significant extraperitoneal bladder rupture associated with pelvic fracture requiring treatment by external fixation`,
        ],
        optionStyleType: `st-lower-alpha`,
        answer: [3],
        ansText: `Rationale: When intraperitoneal bladder laceration occurs after blunt trauma, a large laceration of the bladder dome is usually produced that predisposes to urinary ascites and/or peritonitis if it is not repaired promptly.`,
        state: `notAnswered`,
        userAnswered: []
      ,
	type: `MCSS`,
	type: `MCSS`        ,
        type: `MCSS`},
      {
        q: `<!--2. -->Which of the following statements is TRUE regarding cystography for diagnosis of bladder injury?`,
        q2: ``,
        q3: [],
        option: [`<!--a. -->If the patient is already undergoing computed tomography (CT) for evaluation of associated injuries, CT cystography should be performed via antegrade filling of the bladder after intravenous administration of radiographic contrast material and clamping the Foley catheter.`, 
        `<!--b. -->If plain film cystograms are obtained, the study is considered negative and complete if there is no extravasation of contrast agent seen on the filling film.`, 
        `<!--c. -->CT cystography is best performed with undiluted contrast medium.`, 
        `<!--d. -->An absolute indication for immediate cystography is the presence of pelvic fracture and microhematuria.`, 
        `<!--e. -->None of the above.`,
        ],
        optionStyleType: `st-lower-alpha`,
        answer: [4],
        ansText: `Rationale: The CT cystogram must be performed via retrograde distention of the bladder with a diluted contrast medium. Most bladder lacerations are associated with gross hematuria, not microhematuria. A drainage film is required to complete a plain film cystogram.`,
        state: `notAnswered`,
        userAnswered: []
      ,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`        ,
        type: `MCSS`},
      {
        q: `<!--3. -->Which of the following statements is TRUE about blunt bladder rupture injuries?`,
        q2: ``,
        q3: [],
        option: [`<!--a. -->They are present in 90% of patients presenting with pelvic fractures.`, 
        `<!--b. -->They coexist with urethral disruption in 50% of cases.`, 
        `<!--c. -->Extraperitoneal ruptures are always amenable to nonoperative treatment.`, 
        `<!--d. -->High mortality rate is primarily related to nonurologic comorbidities.`, 
        `<!--e. -->They are associated with microhematuria or no hematuria in 40% of cases.`,
        ],
        optionStyleType: `st-lower-alpha`,
        answer: [3],
        ansText: `Rationale: Bladder lacerations occur in approximately 10% of pelvic fractures and often occur in the context of multisystemic trauma.`,
        state: `notAnswered`,
        userAnswered: []
              ,
        type: `MCSS`},
      {
        q: `<!--4. -->The risk of complications from nonoperative treatment of extraperitoneal bladder rupture is increased by:`,
        q2: ``,
        q3: [],
        option: [`<!--a. -->associated orthopedic injury.`, 
        `<!--b. -->associated vaginal injury.`, 
        `<!--c. -->associated urethral injury.`, 
        `<!--d. -->associated rectal injury.`, 
        `<!--e. -->all of the above.`,
        ],
        optionStyleType: `st-lower-alpha`,
        answer: [4],
        ansText: `Rationale: All of the listed concomitant injuries increase the risk of complications such as abscess, fistula, or incontinence.`,
        state: `notAnswered`,
        userAnswered: []
              ,
        type: `MCSS`},
      {
        q: `<!--5. -->Three months after a urethral distraction injury, a patient is found to have a 2-cm obliterative posterior urethral defect. Which of the following is TRUE about the repair?`,
        q2: ``,
        q3: [],
        option: [`<!--a. -->One-stage, open, perineal anastomotic urethroplasty is preferred.`, 
        `<!--b. -->Orthopedic hardware in the pubic symphysis area is a contraindication to open posterior urethroplasty.`, 
        `<!--c. -->Buccal mucosa graft urethroplasty is recommended.`, 
        `<!--d. -->Urethral stent placement is recommended.`, 
        `<!--e. -->The patient is at high risk for incontinence after posterior urethral reconstruction surgery.`,
        ],
        optionStyleType: `st-lower-alpha`,
        answer: [0],
        ansText: `Rationale: Posterior urethral reconstruction including excision of the fibrotic segment with distal urethral mobilization and primary anastomosis is associated with the best long-term outcomes after urethral disruption. Incontinence occurs in less than 5% of patients.`,
        state: `notAnswered`,
        userAnswered: []
      ,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`        ,
        type: `MCSS`},
      {
        q: `<!--6. -->In a patient with a pelvic fracture from blunt trauma in whom no urine is returned after catheter placement, what is the best initial method to evaluate urethral injury?`,
        q2: ``,
        q3: [],
        option: [`<!--a. -->Retrograde urethrography`, 
        `<!--b. -->CT of abdomen and pelvis`, 
        `<!--c. -->Filiforms and followers`, 
        `<!--d. -->Bladder ultrasonography`, 
        `<!--e. -->None of the above`,
        ],
        optionStyleType: `st-lower-alpha`,
        answer: [0],
        ansText: `Rationale: Retrograde urethrography is the most reliable imaging study for urethral evaluation.`,
        state: `notAnswered`,
        userAnswered: []
              ,
        type: `MCSS`},
      {
        q: `<!--7. -->During exploration after a scrotal gunshot wound, 20% of the left testicular capsule is found to be disrupted. What should be done?`,
        q2: ``,
        q3: [],
        option: [`<!--a. -->Left orchiectomy`, 
        `<!--b. -->Application of wet dressings and delayed testicular surgery`, 
        `<!--c. -->Left testicular reconstruction with synthetic graft`, 
        `<!--d. -->Closure of the scrotal laceration followed by ultrasonography`, 
        `<!--e. -->Immediate primary repair of the left testis`,
        ],
        optionStyleType: `st-lower-alpha`,
        answer: [4],
        ansText: `Rationale: Immediate primary repair should be attempted in the setting of subtotal injury to an otherwise viable testis. Even extensive testicular injuries often can be safely salvaged, and tunica vaginalis grafts provide better outcomes than do synthetic grafts for complex repair.`,
        state: `notAnswered`,
        userAnswered: []
              ,
        type: `MCSS`},
      {
        q: `<!--8. -->A 23-year-old man is found to have an 80% transection of the proximal bulbar urethra after a gunshot wound with a 22-caliber pistol. A 1-cm urethral defect is visualized during cystoscopy. What is the most appropriate therapy?`,
        q2: ``,
        q3: [],
        option: [`<!--a. -->Buccal mucosa graft urethroplasty`, 
        `<!--b. -->Spatulated, stented, tension-free, watertight repair of the urethra with absorbable sutures`, 
        `<!--c. -->Suprapubic tube placement`, 
        `<!--d. -->Urethral catheterization alone`, 
        `<!--e. -->Perineal urethrostomy`,
        ],
        optionStyleType: `st-lower-alpha`,
        answer: [1],
        ansText: `Rationale: Immediate urethral repair with fine absorbable suture over a Foley catheter is associated with superior outcomes after penetrating injury. A proximal bulbar urethral pathologic process in a young man is uniquely amenable to primary anastomotic repair.`,
        state: `notAnswered`,
        userAnswered: []
      ,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`        ,
        type: `MCSS`},
      {
        q: `<!--9. -->Which of the following statements regarding penile fracture is FALSE?`,
        q2: ``,
        q3: [],
        option: [`<!--a. -->Most injuries occur ventrolaterally.`, 
        `<!--b. -->Rupture of a superficial vein can sometimes mimic the presentation of a corporal tear.`, 
        `<!--c. -->Retrograde urethrography should be uniformly performed to assess for urethral injury.`, 
        `<!--d. -->Patients with penile fracture who are treated nonoperatively are more likely to have longer hospital stays, a higher risk of infection, and penile curvature than those whose fracture is repaired surgically.`, 
        `<!--e. -->Physical examination is usually sufficient in making the diagnosis or for deciding on surgical exploration.`,
        ],
        optionStyleType: `st-lower-alpha`,
        answer: [2],
        ansText: `Rationale: Flexible cystoscopy performed at the time of surgical exploration is the simplest and most sensitive means to assess for urethral injury. Urethrography is of low yield in men with no hematuria, no blood at the meatus, and no voiding symptoms; intraoperative flexible cystoscopy is an appropriate alternative method of urethral evaluation.`,
        state: `notAnswered`,
        userAnswered: []
      ,
	type: `MCSS`,
	type: `MCSS`        ,
        type: `MCSS`},
      {
        q: `<!--10. -->The blood in a hematocele is contained in which of the following?`,
        q2: ``,
        q3: [],
        option: [`<!--a. -->Tunica albuginea`, 
        `<!--b. -->Tunica vaginalis`, 
        `<!--c. -->Dartos muscle`, 
        `<!--d. -->Camper fascia`, 
        `<!--e. -->Spermatic cord`,
        ],
        optionStyleType: `st-lower-alpha`,
        answer: [1],
        ansText: `Rationale: Blood fills the space between the visceral and parietal layers of the tunica vaginalis.`,
        state: `notAnswered`,
        userAnswered: []
              ,
        type: `MCSS`},
      {
        q: `<!--11. -->Blunt scrotal trauma that results in testis rupture:`,
        q2: ``,
        q3: [],
        option: [`<!--a. -->is usually a bilateral process.`, 
        `<!--b. -->is often diagnosed by the presence of intratesticular hypoechoic areas on ultrasonography.`, 
        `<!--c. -->has a degree of hematoma that correlates with the extent of injury.`, 
        `<!--d. -->requires conservative management that results in acceptable viability and function.`, 
        `<!--e. -->is definitively diagnosed during physical examination alone in most cases.`,
        ],
        optionStyleType: `st-lower-alpha`,
        answer: [1],
        ansText: `Rationale: Testicular rupture is often difficult to detect clinically. Ultrasound evaluation usually shows intratesticular heterogeneity as a sentinel finding; detection of a defect of the tunica albuginea is less common.`,
        state: `notAnswered`,
        userAnswered: []
              ,
        type: `MCSS`},
      {
        q: `<!--12. -->Which of the following statements is TRUE regarding penile amputation injury?`,
        q2: ``,
        q3: [],
        option: [`<!--a. -->Microscopic reanastomosis of the corporal arteries is recommended.`, 
        `<!--b. -->The severed phallus should be placed directly on ice during transport.`, 
        `<!--c. -->Microscopic dorsal vascular and neural reanastomosis is the best method of repair.`, 
        `<!--d. -->Primary macroscopic reanastomosis invariably results in erectile dysfunction.`, 
        `<!--e. -->Skin loss is rarely a problem after macroscopic repair.`,
        ],
        optionStyleType: `st-lower-alpha`,
        answer: [2],
        ansText: `Rationale: Microvascular reanastomosis of the dorsal neurovascular structures is suggested as the preferred treatment modality whenever possible. Reanastomosis of the corporal arteries is not recommended.`,
        state: `notAnswered`,
        userAnswered: []
              ,
        type: `MCSS`},
      {
        q: `<!--13. -->What is the best option for coverage of acute penile skin loss?`,
        q2: ``,
        q3: [],
        option: [`<!--a. -->Foreskin flap for small distal lesions`, 
        `<!--b. -->Meshed skin graft in a young child`, 
        `<!--c. -->Wet-to-dry dressings`, 
        `<!--d. -->Thigh flaps`, 
        `<!--e. -->Burying the penile shaft in a scrotal skin tunnel`,
        ],
        optionStyleType: `st-lower-alpha`,
        answer: [0],
        ansText: `Rationale: Redundant foreskin provides excellent closure when ample viable tissue exists.`,
        state: `notAnswered`,
        userAnswered: []
              ,
        type: `MCSS`},
      {
        q: `<!--14. -->Which is FALSE about penile fracture?`,
        q2: ``,
        q3: [],
        option: [`<!--a. -->Penile fracture must be repaired immediately for the best outcomes.`, 
        `<!--b. -->Ultrasonography can identify location of the corporal tear.`, 
        `<!--c. -->Magnetic resonance imaging (MRI) can demonstrate disruption of the tunica albuginea.`, 
        `<!--d. -->Rupture of the dorsal penile artery can have the same presentation as penile fracture.`, 
        `<!--e. -->Bilateral corporal injury is more commonly associated with urethral injury.`,
        ],
        optionStyleType: `st-lower-alpha`,
        answer: [0],
        ansText: `Rationale: <b>Penile fracture must be repaired immediately or there is a decrement in erectile function.</b> Recent data have shown that a delay in surgery of as long as 7 days has no effect on the outcomes of penile fracture.`,
        state: `notAnswered`,
        userAnswered: []
              ,
        type: `MCSS`},
      {
        q: `<!--15. -->Advantages of open suprapubic tube placement after posterior urethral disruption injuries include:`,
        q2: ``,
        q3: [],
        option: [`<!--a. -->inspection of bladder.`, 
        `<!--b. -->an opportunity for controlled antegrade urethral realignment.`, 
        `<!--c. -->allowance for large-bore catheter insertion.`, 
        `<!--d. -->not jeopardizing continence or potency rates.`, 
        `<!--e. -->all of the above.`,
        ],
        optionStyleType: `st-lower-alpha`,
        answer: [4],
        ansText: `Rationale: Antegrade urethral realignment may simplify treatment of the defect, and a large-bore suprapubic catheter placed near the midline will promote subsequent identification of the prostatic apex during delayed reconstruction while preventing tube encrustation or obstruction.`,
        state: `notAnswered`,
        userAnswered: []
              ,
        type: `MCSS`},
      
     
];
      
     