var quiz = [
  {
    q: `<!--1. -->All of the following are critical to consider in the surgical management of a bladder diverticulum EXCEPT one. Which?`,
    q2: ``,
    q3: [],
    option: [
      `<!--a. -->If outlet obstruction is present, it should be managed prior to or at the time of bladder diverticulectomy.`,
      `<!--b. -->The need for ureteral reimplantation is a contraindication to surgical resection of a bladder diverticulum.`,
      `<!--c. -->Cystoscopic examination of the diverticulum should be attempted in order to characterize the anatomy of the diverticulum as well as to evaluate for the presence for a bladder tumor within the diverticulum.`,
      `<!--d. -->A preoperative stent may be placed if there is concern for ureteral injury during bladder diverticulectomy.`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [1],
    ansText: `Rationale: The need for ureteral reimplantation is not a contraindication to performing bladder diverticulectomy. Rather, careful preoperative planning is necessary to discern the proximity of the ureter to the diverticulum and to gauge whether surgical maneuvers, such as retrograde ureteral stent placement, are necessary to prevent inadvertent ureteral injury. Alternatively, planned ureteral reimplantation may be performed at the time of bladder diverticulectomy. The surgeon should be cognizant of the ureteral anatomy relative to the diverticulum to avoid intraoperative injury. At the conclusion of the case, the ureter should be inspected to ensure its integrity; reimplantation should be performed if there is any concern for ureteral compromise.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `<!--2. -->In patients with ureteral stricture disease, which of the following should ideally be a part of the preoperative evaluation?`,
    q2: ``,
    q3: [],
    option: [
      `<!--a. -->Retrograde pyelography`,
      `<!--b. -->Both retrograde and antegrade evaluation`,
      `<!--c. -->Computed tomography (CT) urography`,
      `<!--d. -->None of the above; direct intraoperative visualization of stricture length will suffice.`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [1],
    ansText: `Rationale: Both antegrade and retrograde evaluation of stricture disease is necessary to accurately assess the length and location of disease as well as whether multiple strictures are present, as these factors heavily influence operative planning. In cases of distal ureteral strictures, retrograde contrast administration alone may fail to opacify more proximal aspects of the ureter, precluding an understanding of the length of stricture disease. Similarly, high-grade proximal strictures may prevent adequate ureteral opacification past the stricture segment with antegrade studies (e.g., contrast administration through a nephrostomy tube or delayed-phase imaging on a CT urogram), hindering adequate characterization of the extent of stricture disease. Obstructive uropathy in the setting of a ureteral stricture may also impair the uptake of intravenous contrast by the kidney during a CT urogram study, rendering this study futile for the anatomic characterization of stricture disease when it is performed in isolation.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `<!--3. -->Which of the following maneuvers can be used to reduce tension on the ureterovesical anastomosis?`,
    q2: ``,
    q3: [],
    option: [
      `<!--a. -->Ligation of the contralateral bladder pedicles to facilitate cephalad displacement of the bladder`,
      `<!--b. -->Disengagement of the peritoneal reflection off the bladder dome to enhance bladder mobility`,
      `<!--c. -->A psoas hitch procedure`,
      `<!--d. -->Renal mobilization and downward nephropexy`,
      `<!--e. -->All of the above`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [4],
    ansText: `Rationale: It is critical to avoid tension at the ureterovesical junction during reimplantation as ischemic injury related to undue traction may result in the formation of scar and subsequent stricture. All the aforementioned techniques can be employed to reduce tension, although they vary in their degree of surgical complexity. In general, a psoas hitch procedure represents the least complex of the options mentioned and is generally all that is needed for ureteral strictures involving the distal third of the ureter. If further length is needed, a Boari flap may be performed prior to more aggressive surgical maneuvers such as ligation of bladder pedicles, disengagement of the peritoneal reflection, and renal mobilization.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `<!--4. -->All of the following are essential surgical aspects of the Boari flap or bladder advancement flap EXCEPT one. Which?`,
    q2: ``,
    q3: [],
    option: [
      `<!--a. -->An adequate-sized bladder must be present (200- to 300-mL capacity).`,
      `<!--b. -->The contralateral vesical pedicle may be transected if necessary.`,
      `<!--c. -->The bladder flap should be slightly shorter than anticipated because bladder tissue can easily be stretched.`,
      `<!--d. -->A tension-free anastomosis is important.`,
      `<!--e. -->Typically, a refluxing ureteral anastomosis is created.`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [2],
    ansText: `Rationale: The bladder flap should be slightly shorter than anticipated because bladder tissue can easily be stretched. A tension-free anastomosis of the anterolateral bladder flap based on the ipsilateral vesical pedicle is critical. The bladder flap should be somewhat longer and wider than anticipated because the nondistended bladder shrinks in size, thus placing tension on the anastomosis. Ideally, a flap length-to-breadth ratio of 3:1 ensures good vascularity of its apex.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `<!--5. -->What nerves may be injured during a psoas hitch procedure?`,
    q2: ``,
    q3: [],
    option: [
      `<!--a. -->Obturator nerve`,
      `<!--b. -->Genitofemoral nerve`,
      `<!--c. -->Ilioinguinal nerve`,
      `<!--d. -->Sciatic nerve`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [1],
    ansText: `Rationale: During a psoas hitch procedure, sutures should be placed superficially through the tendon of the psoas minor parallel to the direction of the muscle fibers. This helps to minimize the risk for disrupting the genitofemoral nerve, situated superficially on the psoas muscle, or the femoral nerve, located deeper in the belly of the muscle.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `<!--6. -->Which of the following statements is NOT correct regarding enterocystoplasty?`,
    q2: ``,
    q3: [],
    option: [
      `<!--a. -->Subtotal cystectomy is not always mandatory.`,
      `<!--b. -->The mesenteric pedicle of the selected bowel segment is wide and broad-based.`,
      `<!--c. -->The mesenteric window is closed.`,
      `<!--d. -->Reestablishment of bowel continuity is a critical step of the operation and may be performed extracorporeally, if necessary, for added security.`,
      `<!--e. -->Bowel-to-bladder anastomosis is optimally performed with interrupted serosa-to-serosa sutures.`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [4],
    ansText: `Rationale: The technical principles of enterocystoplasty are identical between open surgical and laparoscopic techniques. Generous mobilization of the bladder allows creation of an adequate anteroposterior cystotomy. Subtotal cystectomy is necessary only in patients with severely symptomatic interstitial cystitis. An optimal segment of bowel based on a broad, well-vascularized mesenteric pedicle is selected that will reach the pelvis without tension. The bowel segment is isolated and bowel continuity reestablished, either by intracorporeal or extracorporeal techniques, and the mesenteric window is closed. The isolated bowel segment is detubularized and a bowel plate is created appropriately. A tension-free, watertight, full-thickness circumferential running anastomosis of the bowel segment to the bladder is created. Adequate urinary drainage is established.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `<!--7. -->Contraindications for enterocystoplasty include all of the following EXCEPT:`,
    q2: ``,
    q3: [],
    option: [
      `diverticulosis.`,
      `<!--b. -->inflammatory bowel disease.`,
      `<!--c. -->renal failure.`,
      `<!--d. -->noncompliance.`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [0],
    ansText: `Rationale: The presence of bowel pathology such as diverticulitis or ulcerative colitis requires the use of alternative, nondiseased bowel segments. Enterocystoplasty should not be performed in the presence of advanced renal or liver failure, inflammatory bowel disease, or short gut syndrome or in a patient who is unable to perform or noncompliant in performing intermittent catheterization reliably. Diverticulosis is not a contraindication for performing enterocystoplasty.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `<!--8. -->Which is the following is a contraindication to partial cystectomy for a bladder leiomyoma?`,
    q2: ``,
    q3: [],
    option: [
      `<!--a. -->Need for ureteral reimplantation`,
      `<!--b. -->Transmural involvement by the neoplastic process`,
      `<!--c. -->Significant irritative voiding symptoms at baseline`,
      `<!--d. -->Reduced preoperative bladder capacity`,
      `<!--e. -->c and d`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [4],
    ansText: `Rationale: Bladder leiomyomas are benign tumors of the bladder that most commonly manifest with an endovesical, intramural, or extravesical pattern of growth; therefore they may not be discerned on cystoscopic exam or may appear only as a submucosal growth. Owing to the benign nature of bladder leiomyomas, partial cystectomy represents a reasonable treatment approach, particularly for lesions that are large in size and require wide local excision. Patient selection is critical when partial cystectomy is being considered irrespective of the pathology for which it is being performed. This includes performing the procedure only in patients with adequate preoperative bladder capacity, as further postoperative reduction in capacity can result in significant voiding complaints. Additionally, the presence of baseline irritative voiding complaints is a relative contraindication, as the process of bladder tissue resection and postoperative reduction in bladder capacity may exacerbate these symptoms. Ureteral reimplantation is not an absolute contraindication for partial cystectomy, particularly for benign disease, and can be performed concomitantly if necessary.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `<!--9. -->Which of the following with regard to ureteral reimplantation is true?`,
    q2: ``,
    q3: [],
    option: [
      `<!--a. -->A nonrefluxing anastomosis is superior to a refluxing anastomosis due to a reduced risk for infection.`,
      `<!--b. -->The ureter should be skeletonized as much as possible to facilitate maximal ureteral mobility and increase the chance for a tension-free anastomosis.`,
      `<!--c. -->For a nonrefluxing anastomosis, the length of the submucosal tunnel should be approximately three to five times the diameter of the ureter to be reimplanted.`,
      `<!--d. -->For ureteral defects greater than 4 cm, a primary ureteroneocystotomy is generally feasible without the need for a psoas hitch or Boari flap.`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [2],
    ansText: `Rationale: When a nonrefluxing anastomosis is being performed, a submucosal tunnel is created to support compression of the reimplanted ureter during bladder contraction. The length of this tunnel should be roughly three to five times the diameter of the ureter to be reimplanted. Nonrefluxing anastomoses can be created via an extravesical or transvesical approach. Based on the currently available literature, the use of a refluxing anastomosis does not appear to place individuals at increased risk for accelerated renal functional decline or for stenosis as compared with nonrefluxing anastomoses. Similarly, long-term studies in adults undergoing a refluxing anastomosis do not seem to indicate increased risk for infection. For ureteral defects greater than 4 cm, primary ureteroneocystotomy would likely result in undue traction at the ureterovesical anastomosis and cause stricture secondary to ischemic injury. Therefore additional measures such as psoas hitch and/or Boari flap are often implemented. In addition to creating a tension-free anastomosis during ureteral reimplantation, the ureter should be manipulated delicately so as to minimize devascularization injury. Furthermore, a conscious effort should be made during extravesical mobilization of the ureter to preserve the periureteral fibroadipose tissue and avoid excessive skeletonization, which may also compromise the blood supply.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `<!--10. -->When urachal surgery is performed for a benign indication, which of the following is true?`,
    q2: ``,
    q3: [],
    option: [
      `<!--a. -->Wide margins of resection along the peritoneal wing are necessary.`,
      `<!--b. -->A wide-margin bladder cuff is preferred.`,
      `<!--c. -->Excision of the umbilicus should be performed.`,
      `<!--d. -->Narrow peritoneal wings around the urachus and a narrow-margin bladder cuff will suffice.`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [3],
    ansText: `Rationale: Surgery is indicated for symptomatic or infected urachal anomalies that do not respond to conservative approaches to treatment, such as incision and drainage and/or antibiotic therapy. When surgery is performed, the entire urachus should be excised, including a small area on the dome of the bladder. The practice of incorporating a bladder cuff into the surgical specimen is thought to ensure that no residual tissue will be left in the vicinity of the bladder apex, as this may risk recurrence of symptoms or malignant transformation. In general, a narrow peritoneal wing around the urachus will suffice, as will a narrow bladder cuff because of the noninfiltrative nature of benign urachal lesions. Excision of the umbilicus is not necessary for a benign indication, especially when the lesion is not in the vicinity of the umbilicus.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
];
