var quiz = [
   
   
    {
        q: `<!--1. -->Important components in the clinical staging of patients with muscle-invasive bladder cancer include which of the following?`,
        q2: ``,
        q3: [],
        option: [`<!--a. -->Transurethral resection with adequate detrusor muscle in the specimen`, 
        `<!--b. -->Bimanual examination under anesthesia`, 
        `<!--c. -->Cross-sectional imaging of the abdomen and pelvis`, 
        `<!--d. -->Laboratory studies including liver function tests`, 
        `<!--e. -->All of the above`,
        ],
        optionStyleType: `st-lower-alpha`,
        answer: [4],
        ansText: `Rationale: Important components of staging patients with muscle-invasive bladder cancer include adequate transurethral resection, bimanual examination under anesthesia to assess local extent of disease, cross-sectional imaging, and serum laboratory values.`,
        state: `notAnswered`,
        userAnswered: []
      ,
	type: `MCSS`,
	type: `MCSS`        ,
        type: `MCSS`},
      {
        q: `<!--2. -->The most important pathologic predictor of outcome following radical cystectomy for muscle-invasive bladder cancer is`,
        q2: ``,
        q3: [],
        option: [`<!--a. -->pT2a versus pT2b substaging.`, 
        `<!--b. -->soft tissue margin status.`, 
        `<!--c. -->nodal metastasis.`, 
        `<!--d. -->ureteral margin status.`, 
        `<!--e. -->prostatic urethral involvement.`,
        ],
        optionStyleType: `st-lower-alpha`,
        answer: [2],
        ansText: `Rationale: <b>Approximately 25% of patients with clinical T2 disease will have lymph node metastasis at the time of radical cystectomy.</b> Lymph node status following surgery is a powerful predictor of long-term recurrence-free and overall survival. <b>Of patients with lymph node involvement, 70% to 80% will ultimately experience a recurrence following radical cystectomy.</b>`,
        state: `notAnswered`,
        userAnswered: []
      ,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`        ,
        type: `MCSS`},
      {
        q: `<!--3. -->All of the following have been reported to provide prognostic information with regard to pelvic lymphadenectomy EXCEPT`,
        q2: ``,
        q3: [],
        option: [`<!--a. -->absolute number of lymph nodes removed.`, 
        `<!--b. -->laterality of a single positive lymph node.`, 
        `<!--c. -->lymph node density.`, 
        `<!--d. -->extranodal extension.`, 
        `<!--e. -->anatomic extent of the lymph node dissection.`,
        ],
        optionStyleType: `st-lower-alpha`,
        answer: [1],
        ansText: `Rationale: Although some surgical series have demonstrated improved survival in patients with one positive lymph node compared with those with multiple positive nodes, the laterality of a single positive lymph node has no prognostic significance.`,
        state: `notAnswered`,
        userAnswered: []
      ,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`        ,
        type: `MCSS`},
      {
        q: `<!--4. -->A 52-year-old male with cT2N0Mx urothelial carcinoma is undergoing a radical cystoprostatectomy and planned orthotopic urinary diversion. What intraoperative finding would be an absolute contraindication to orthotopic diversion?`,
        q2: ``,
        q3: [],
        option: [`<!--a. -->Positive ureteral frozen section for carcinoma in situ (CIS)`, 
        `<!--b. -->Positive apical urethral frozen section for urothelial carcinoma`, 
        `<!--c. -->Suspicious lymphadenopathy`, 
        `<!--d. -->Greater than 1.5-L blood loss during the cystectomy`, 
        `<!--e. -->None of the above`,
        ],
        optionStyleType: `st-lower-alpha`,
        answer: [1],
        ansText: `Rationale: The only contraindication to performing an orthotopic neobladder is a positive apical urethral margin and inability to achieve a negative margin of the retained urethra.`,
        state: `notAnswered`,
        userAnswered: []
              ,
        type: `MCSS`},
      {
        q: `<!--5. -->All of the following are true statements regarding neoadjuvant chemotherapy for muscle-invasive bladder cancer EXCEPT which?`,
        q2: ``,
        q3: [],
        option: [`<!--a. -->Meta-analysis of available randomized trial data has reported an absolute 5% survival advantage for patients who receive neoadjuvant chemotherapy.`, 
        `<!--b. -->Neoadjuvant chemotherapy is likely underutilized in the US-based studies that use administrative data sets.`, 
        `<!--c. -->Patients who are pT0 on final pathology following neoadjuvant chemotherapy have excellent oncologic outcomes.`, 
        `<!--d. -->In patients in whom a cisplatin-based regimen is contraindicated, carboplatin-based chemotherapy provides similar oncologic efficacy.`, 
        `<!--e. -->All of the above.`,
        ],
        optionStyleType: `st-lower-alpha`,
        answer: [3],
        ansText: `Rationale: <b>Although carboplatin is a reasonable choice for patients in whom cisplatin is contraindicated, it should not be considered a first-line therapy.</b> Patients who cannot undergo neoadjuvant cisplatin-based chemotherapy should be considered for immediate cystectomy.`,
        state: `notAnswered`,
        userAnswered: []
      ,
	type: `MCSS`        ,
        type: `MCSS`},
      {
        q: `<!--6. -->A 65-year-old woman with normal renal function undergoes up-front radical cystectomy, extended pelvic lymphadenectomy, and ileal conduit urinary diversion for bacille Calmette-Guérin–refractory bladder carcinoma in situ (CIS). Final pathology is notable for T2N1M0 disease. The next step in management should be`,
        q2: ``,
        q3: [],
        option: [`<!--a. -->enrollment in a clinical vaccine trial.`, 
        `<!--b. -->adjuvant cisplatin-based chemotherapy.`, 
        `<!--c. -->adjuvant pelvic external beam radiation therapy.`, 
        `<!--d. -->combination chemotherapy/external beam radiation therapy.`, 
        `<!--e. -->adjuvant carboplatin-based chemotherapy.`,
        ],
        optionStyleType: `st-lower-alpha`,
        answer: [1],
        ansText: `Rationale: Adjuvant cisplatin-based combination chemotherapy should be considered. Randomized trials have thus far not been definitive in overall survival results on this subject. A meta-analysis suggests a 9% absolute benefit in overall survival, but the trials often closed early or because of poor accrual, a small number of patients, and inability to represent all of the patients in adjuvant chemotherapy trials.`,
        state: `notAnswered`,
        userAnswered: []
              ,
        type: `MCSS`},
      {
        q: `<!--7. -->All of the following are contraindications to trimodal bladder preservation EXCEPT`,
        q2: ``,
        q3: [],
        option: [`<!--a. -->a solitary, completely resected tumor.`, 
        `<!--b. -->hydronephrosis.`, 
        `<!--c. -->diffuse bladder CIS.`, 
        `<!--d. -->T3 disease on cross-sectional imaging.`, 
        `<!--e. -->multifocal tumors.`,
        ],
        optionStyleType: `st-lower-alpha`,
        answer: [0],
        ansText: `Rationale: <b>Patients with solitary completely resected tumors are ideal candidates for bladder preservation.</b>`,
        state: `notAnswered`,
        userAnswered: []
      ,
	type: `MCSS`        ,
        type: `MCSS`},
      {
        q: `<!--8. -->Predictors of a poor response to chemotherapy in patients with locally advanced or metastatic bladder cancer include`,
        q2: ``,
        q3: [],
        option: [`<!--a. -->Karnofsky performance status below 80%.`, 
        `<!--b. -->visceral metastasis.`, 
        `<!--c. -->both a and b.`, 
        `<!--d. -->neither a nor b.`, 
        ],
        optionStyleType: `st-lower-alpha`,
        answer: [2],
        ansText: `Rationale: <b>The Memorial Sloan Kettering Cancer Center group published their data on 203 patients with unresectable or metastatic bladder cancer treated with MVAC (). They found a Karnofsky performance status below 80% and visceral (lung, liver, bone) metastasis to be independent predictors of poor outcome.</b> Median survival times for patients who had zero, one, or two risk factors were 33, 13.4, and 9.3 months, respectively.`,
        state: `notAnswered`,
        userAnswered: []
              ,
        type: `MCSS`},
      {
        q: `<!--9. -->Gemcitabine/cisplatin systemic therapy is often used in preference to MVAC (methotrexate, vinblastine, doxorubicin, and cisplatin) for patients with locally advanced and metastatic bladder cancer because of`,
        q2: ``,
        q3: [],
        option: [`<!--a. -->studies demonstrating improved progression-free survival.`, 
        `<!--b. -->studies demonstrating improved overall survival.`, 
        `<!--c. -->a better toxicity profile.`, 
        `<!--d. -->oral administration compared with intravenous administration.`, 
        `<!--e. -->cost.`,
        ],
        optionStyleType: `st-lower-alpha`,
        answer: [2],
        ansText: `Rationale: The toxicity of MVAC led to trials of alternative, less toxic chemotherapy regimens. <b>Most notably, a phase III randomized trial comparing gemcitabine/cisplatin with MVAC was conducted in 405 patients</b> (von der Maase et al., 2000, 2005).<a href="[remark:cc00c08658c940aab99a394c37c133d0]"><sup>a</sup></a> There was no difference in response rates (49% vs 46%), time to progression (7.4 vs 7.4 months), and overall survival rates (13.8 vs 14.8 months) between the two study arms. <b>The updated study analysis confirmed equivalence of the two regimens (hazard ratio, 1.09, 95% confidence interval, 0.88 to 1.34, <i>P</i> = .66). The gemcitabine/cisplatin regimen was better tolerated, with only 37% of patients in that arm requiring dose modifications compared with 63% in the MVAC arm.</b> Patients in the gemcitabine/cisplatin arm also experienced less grade 3/4 neutropenia, neutropenic fever, neutropenic sepsis, and mucositis. The toxicity-related death rate was also lower in the gemcitabine/cisplatin group (1% vs 3%). Because of its equivalent efficacy and better tolerability, gemcitabine/cisplatin is the most widely used chemotherapeutic regimen for muscle-invasive and metastatic bladder cancer.`,
        state: `notAnswered`,
        userAnswered: []
              ,
        type: `MCSS`},
      {
        q: `<!--10. -->An orthotopic neobladder in a woman undergoing anterior pelvic exenteration for muscle-invasive bladder cancer is contraindicated in the setting of`,
        q2: ``,
        q3: [],
        option: [`<!--a. -->age older than 75 years.`, 
        `<!--b. -->nodal metastasis.`, 
        `<!--c. -->recurrent urinary tract infection.`, 
        `<!--d. -->a serum creatinine of 1.5.`, 
        `<!--e. -->tumor invading the anterior vaginal wall.`,
        ],
        optionStyleType: `st-lower-alpha`,
        answer: [4],
        ansText: `Rationale: The distal two-thirds of the female urethra may serve as an adequate sphincter mechanism provided that the risk of cancer in the retained urethra is low. Anterior vaginal wall involvement—by a posterior-based bladder tumor or bladder neck or urethral involvement—is a contraindication to urethral sparing and orthotopic bladder replacement because one cannot get an adequate distal vaginal margin and urethral margin (Stein et al., 1998). Age is not a contraindication as long as there is good pelvic support minimizing the risk of stress incontinence and the patient is capable of intermittent catheterization should the need arise. Nodal metastasis is associated with a 15% local recurrence rate with only a modest risk of invasion of the neobladder, and a thorough node dissection minimizes this risk (Lerner, 2009). Bilateral hydronephrosis, although indicating a deeply invasive cancer, is not a de facto contraindication (Stimson et al., 2010).`,
        state: `notAnswered`,
        userAnswered: []
              ,
        type: `MCSS`},
      
];
      
     