var quiz = [
  {
    q: `In the conduct of performing a transurethral resection of the prostate (TURP) on a 65-g prostate using a continuous flow instrument, the urologist notes a disturbing amount of dark blood from the rectoscope efflux. In carefully and repeatedly observing the prostate fossa he notes no obvious bleeding sites. The likely etiology of such blood is:`,
    q2: ``,
    q3: [],
    option: [
      `venous bleeding from prostatic fossa.`,
      `unstable blood pressure resulting in intermittent arterial bleeding.`,
      `inadvertent use of chromogen dyes (methylene blue or indocarmine) by anesthesia.`,
      `perforation of the bladder. `,
      `previous unrecognized coagulopathy. `,
    ],
    optionFeedback: [``, ``, ``, ``, ``],
    optionStyleType: `st-lower-alpha`,
    answer: [0],
    ansText: `Rationale: enous bleeding can be more vexing and generally appears darker in color than arterial bleeding. Venous bleeding will often disappear with a full bladder as it applies pressure to the prostatic fossa. Identifying venous sinuses may be difficult due to the lack of persistent bleeding with rapid irrigation influx and controlling of the bleeding with fulguration may be even more challenging. Once again, the cutting loop may be used to temporarily tamponade any bleeding with precise fulguration. If the venous bleeding is unable to be completely controlled (as is frequently the case) a catheter may be inserted, the balloon overinflated and pulled to traction for tamponade of venous bleeding.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `A patient is 6 weeks post-TURP for long-standing obstruction and detrusor overactivity; voices marked concern over his persistent symptoms, wondering if there was an incomplete resection. A urine culture is negative. The next best sequence of care is:`,
    q2: ``,
    q3: [],
    option: [
      `measure post void residual, provide reassurance, and monitor symptom improvement.`,
      `measure post void residual volume and schedule formal urodynamics.`,
      `restart a course of 5-alpha reductase inhibitors (5ARIs) and antibiotics.`,
      `perform immediate cystoscopy looking for residual tissue. `,
      ` prescribe 90-day supply of phenazopyridine HCl`,
    ],
    optionFeedback: [``, ``, ``, ``, ``],
    optionStyleType: `st-lower-alpha`,
    answer: [1],
    ansText: `Rationale: Patients with long-standing obstruction (particularly those with urgency and frequency preoperatively) will often experience a continuation or exacerbation of these symptoms in the postoperative period. If proper bladder emptying can be verified, an anticholinergic or beta-3 agonist medication during this time may help the patient feel more comfortable. It is our practice to warn those men with preoperatively documented detrusor overactivity that patience will be required in the months following surgery to see if this will resolve. Such caution goes a long way in assuring patients to adopt a strong coping mechanism rather than a polypharmacy approach.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `In the course of performing a monopolar TURP under spinal block, the nurse anesthetist reports the patient is suddenly markedly confused, brachycardic, and hypertensive. An emergent serum sodium level is 110 mEq/L. The following are the next best steps:`,
    q2: ``,
    q3: [],
    option: [
      `Switch to bipolar TURP equipment and finish the case.`,
      `Drop the height of the irrigating fluid to &lt;60 cm above the patient, control bleeding, terminate the case, administer furosemide, and begin a calculated dose of hypertonic saline.`,
      `Convert to an open simple prostatectomy`,
      `Measure serum levels of illicit drugs and ammonia. `,
      `Swap irrigating fluid form glycine to sorbitol. `,
    ],
    optionFeedback: [``, ``, ``, ``, ``],
    optionStyleType: `st-lower-alpha`,
    answer: [1],
    ansText: `Rationale: Patient is likely experiencing TUR syndrome; thus rapid termination is needed. The height of the irrigating fluid above the patient should be carefully chosen. Investigators have demonstrated that the ideal height of the fluid was 60 cm above the patient. This appears to be the minimal height to maintain good vision but also not lead to excessive systemic fluid absorption. Increasing the height 10 cm above this leads to increased pressure in the prostatic fossa and a greater than twofold increase in systemic fluid absorption. Diagnosis of this condition is made by assessment of neurologic status and comparison to laboratory values. Serum sodium should be obtained in long, large resections postoperatively (or intraoperatively if concern exists). A serum sodium of less than 120 mEq/L indicates a significant dilution and may lead to coma or seizures. Transient visual disturbances or blindness indicate central nervous system (CNS) toxicity and are obviously very distressing to all the parties involved. If profound central nervous symptoms are noted, judicious administration of hypertonic saline should be instituted and formulas exist to help guide this resuscitation as overly rapid correction of hyponatremia may lead to a demyelinating lesion of the brain (central pontine myelinolysis).`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `Risk factors for development of the TUR syndrome include:`,
    q2: ``,
    q3: [],
    option: [
      `prostate volume less than 45 g.`,
      `failure to use isotonic, iso-osmolar irrigating solution and the bipolar electroresection system.`,
      `underlying hepatic dysfunction.`,
      `irrigating fluid above the patient should be ideal be &gt;60 cm. `,
      ` preoperative use of opioids.`,
    ],
    optionFeedback: [``, ``, ``, ``, ``],
    optionStyleType: `st-lower-alpha`,
    answer: [1],
    ansText: `Rationale: The absorption of the hypo-osmolar irrigating fluid leads to an acute dilutional hyponatremia with resulting neurologic changes (confusion, nausea, vomiting, visual changes, hypertension, tachypnea, and bradycardia). Now with the use of isotonic, iso-osmolar irrigating solution and the bipolar electroresection system this risk has theoretically been eliminated. While most authors agree that TUR syndrome is caused by dilutional hyponatremia, there have been alternate etiologies proposed. Excessive glycine absorption can lead to liberation of ammonia from metabolic pathways leading to immediate or delayed encephalopathic symptoms. Several steps can be taken to prevent this complication. Use of a bipolar resection method should certainly be considered. The height of the irrigating fluid above the patient should be carefully chosen. Use the minimal height to maintain good vision but also not lead to excessive systemic fluid absorption.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `Transurethral resection (TUR) syndrome is caused by:`,
    q2: ``,
    q3: [],
    option: [
      `absorption of fluid during procedures such as holmium laser enucleation of the prostate (HoLEP) and bipolar TURP.`,
      `absorption of non–sodium-containing irrigating fluid, leading to an acute dilutional hyponatremia.`,
      `irrigating fluid placed at a less than ideal height above the patient.`,
      ` a serum sodium of greater than 130 mEq/L.`,
      `intraoperative ureteral injury. `,
    ],
    optionFeedback: [``, ``, ``, ``, ``],
    optionStyleType: `st-lower-alpha`,
    answer: [1],
    ansText: `Rationale: Absorption of non–sodium-containing irrigating fluid into the prostatic venous system that is exposed during resection is the etiology of the disease. This risk appears to be unique to monopolar TURP; other BPH techniques (such as bipolar TURP, HoLEP, and laser vaporization) use isotonic/iso-osmolar irrigating fluid such as normal saline. <b>The ideal height of irrigating fluid was determined to be 60 cm above the patient, as this balanced the benefits of visualization with systemic absorption.</b> Heights above this level will lead to an increased systemic absorption. In general, symptoms of TUR syndrome begin with a serum sodium of less than 120 mEq/L. Ureteral injury is not associated with TUR syndrome.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `TURP should begin with resection of the:`,
    q2: ``,
    q3: [],
    option: [
      `apical portion of the prostate.`,
      `prostate floor`,
      `bladder neck.`,
      ` median lobe, if present.`,
      `anterior portion of the prostate. `,
    ],
    optionFeedback: [``, ``, ``, ``, ``],
    optionStyleType: `st-lower-alpha`,
    answer: [3],
    ansText: `Rationale: Although many different plans for resection exist, resection of the median lobe (when present) is generally accepted as the first step. `,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `Which of the following is TRUE of bipolar compared with monopolar TURP?`,
    q2: ``,
    q3: [],
    option: [
      `In a meta-analysis of patients undergoing bipolar TURP, authors concluded that by treating 50 patients with bipolar TURP, one case of TUR syndrome could be prevented.`,
      `A relative risk of 0.53 for blood transfusion with bipolar resection was found in meta-analysis.`,
      `Improved visualization during bipolar TURP may also lead to a decrease in capsular perforations and operating time.`,
      ` Late complications such as bladder neck contracture and need for retreatment of benign prostatic hyperplasia (BPH) do not appear to be much different from those found with conventional TURP.`,
      `All of the above `,
    ],
    optionFeedback: [``, ``, ``, ``, ``],
    optionStyleType: `st-lower-alpha`,
    answer: [4],
    ansText: `Rationale: All of the findings in a through d have been demonstrated in studies. The use of a sodium-containing iso-osmolar irrigating fluid has essentially eliminated the risk of TUR syndrome in bipolar TURP. <b>The “cut and seal” action of the technology improves intraoperative hemostasis with better visualization, leading to less blood transfusion and quicker operating times.</b> Differences in many late complications such as bladder neck contracture and need for retreatment have not been demonstrated in comparison to monopolar technology.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `Sham studies on urologic procedures for lower urinary tract symptoms (LUTS) due to BPH:`,
    q2: ``,
    q3: [],
    option: [
      `frequently show statistically significant decreases in AUASS (American Urological Association Symptom Score).`,
      `are poorly tolerated by the patient.`,
      `have significant side effects and should not be performed as part of research.`,
      `have never shown a statistically significant improvement in objective measures such as peak urinary flow. `,
      ` have never been performed`,
    ],
    optionFeedback: [``, ``, ``, ``, ``],
    optionStyleType: `st-lower-alpha`,
    answer: [0],
    ansText: `Rationale: Multiple sham studies have been performed as part of clinical trials on transurethral microwave thermotherapy and prostate lift. Significant improvements in both AUASS and peak flow have been shown. Side effects of treatment are infrequent, and the sham procedures are well tolerated.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `Which of the following is TRUE regarding transurethral incision of the prostate (TUIP)?`,
    q2: ``,
    q3: [],
    option: [
      `It commonly results in TUR syndrome.`,
      `It is generally only used in prostates larger than 60 mL.`,
      `It causes retrograde ejaculation in 80% of cases.`,
      ` It results in removal of a large volume of prostate adenoma.`,
      `It may have a lower rate of ejaculatory dysfunction in patients when done unilaterally. `,
    ],
    optionFeedback: [``, ``, ``, ``, ``],
    optionStyleType: `st-lower-alpha`,
    answer: [4],
    ansText: `Rationale: relatively short and does not cause TUR syndrome. The procedure is only appropriate for small prostate glands (generally less than 30 mL), and no prostate adenoma is removed. Retrograde ejaculation occurs in up to 37% of patients. Although this is controversial, most authors believe that the risk of retrograde ejaculation is lower if done unilaterally as opposed to bilaterally.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `With regard to laser safety, which of the following statements is correct?`,
    q2: ``,
    q3: [],
    option: [
      `Eye protection is required for the surgeon only.`,
      `All windows or wall openings from the operating room (OR) must be covered.`,
      `Signs denoting that a laser is in use need only be displayed on the most commonly used door for that OR.`,
      `Eye protection is required only when a video camera is not used during the case. `,
      `All laser energy is readily absorbed by air/irrigating fluid, making it safe to use in the OR. `,
    ],
    optionFeedback: [``, ``, ``, ``, ``],
    optionStyleType: `st-lower-alpha`,
    answer: [1],
    ansText: `Rationale: Eye protection is required for all classes of lasers used in urology currently. Eye protection should be utilized by the patient and all personnel in the room even if a video camera is used during the case. Signs should be placed on all entries to the OR. Any and all openings to the OR from which laser energy could escape should be covered to preclude injury to persons outside of the OR. Although holmium laser energy is absorbed in irrigating fluid, potassium-titanyl-phosphate/lithium-triborate (KTP/LBO) laser energy is not readily absorbed in either fluid. Both of these lasers can damage the eye when outside the body as neither are readily absorbed/dispersed in air.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `Patients on anticoagulation who undergo photoselective vaporization of the prostate (PVP) have an increased risk of:`,
    q2: ``,
    q3: [],
    option: [
      `erectile dysfunction.`,
      `blood transfusion.`,
      `TUR syndrome.`,
      `ejaculatory dysfunction. `,
      ` time in the hospital after procedure.`,
    ],
    optionFeedback: [``, ``, ``, ``, ``],
    optionStyleType: `st-lower-alpha`,
    answer: [4],
    ansText: `Rationale: Patients who undergo PVP while on anticoagulation appear to be more likely to require longer times in the hospital. They also appear to require more continuous bladder irrigation and a longer time with a urethral catheter. Blood transfusions do not appear to be more frequent. TUR syndrome does not occur with PVP, as normal saline is used. Erectile dysfunction and ejaculatory dysfunction in patients on anticoagulation during PVP are not well studied.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `When using the prostate lift for treatment of LUTS due to BPH, implants are placed where in the prostate anatomically?`,
    q2: ``,
    q3: [],
    option: [
      `Anterolaterally`,
      `Posterolaterally`,
      `Anteriorly`,
      `Posteriorly `,
      `In the peripheral zone `,
    ],
    optionFeedback: [``, ``, ``, ``, ``],
    optionStyleType: `st-lower-alpha`,
    answer: [4],
    ansText: `Rationale: The implants in the prostate lift system are placed anterolaterally to avoid the neurovascular bundles (posterolateral) and the prostate veins (anterior). The implants work by primarily compressing the transition zone of the prostate and leading to an increased opening of the urethral lumen.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
];
