var quiz = [
  {
    q: `<!--1. -->A 45-year-old man had an ileal conduit diversion as a child for bladder exstrophy. He requests a continent diversion. Serum creatinine is 2 mg/dL. Loopogram shows bilaterally thin ureters with small kidneys. Which is the best procedure?`,
    q2: ``,
    q3: [],
    option: [
      `Ureterosigmoidostomy`,
      `<!--b. -->T pouch using the ileal conduit`,
      `<!--c. -->Abandon continent diversion`,
      `<!--d. -->Penn pouch using the ileal conduit`,
      `<!--e. -->Indiana pouch`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [2],
    ansText: `Rationale: A creatinine level greater than 1.8 mg/dL indicates a level of renal function insufficient for continent diversion.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `<!--2. -->A 45-year-old man underwent ileal conduit urinary diversion as a child for bladder exstrophy. He presents requesting continent diversion. Serum creatinine is 2 mg/dL. Loopogram shows bilateral hydronephrosis and a pipestem conduit. What is the best course of action?`,
    q2: ``,
    q3: [],
    option: [
      `<!--a. -->Mainz II to avoid problems with dilated ureters`,
      `<!--b. -->T pouch abandoning the disease conduit`,
      `<!--c. -->No continent diversion`,
      `<!--d. -->Drain the upper tracts and reassess renal function`,
      `<!--e. -->Proceed to neobladder construction`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [3],
    ansText: `Rationale: The best course of action is to place ureteral cutaneous stents bilaterally (bypassing the pipestem segment) and reassess urinary function. In evaluating the hydronephrotic patient with impaired renal function for continent diversion, upper tract drainage is advised. If necessary, bilateral nephrostomy tubes can be used.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `<!--3. -->A patient undergoing a cystectomy and planned continent cutaneous diversion has positive ureteral margin biopsies up to 2 cm above each iliac artery, at which point negative biopsies are obtained. What is the best course of action?`,
    q2: ``,
    q3: [],
    option: [
      `<!--a. -->Use the terminal ileum for ureteral implantation and a Mitrofanoff continence mechanism`,
      `<!--b. -->No continent diversion`,
      `<!--c. -->Mobilize the kidneys and stretch the ureters to the reservoir`,
      `<!--d. -->Use a T pouch with a long chimney`,
      `<!--e. -->Cutaneous ureterostomies`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [0],
    ansText: `Rationale: The best course of action is to perform a right colon reservoir with anastomosis of the ureters to the terminal ileum. The appendix or other pseudo-appendiceal (Mitrofanoff) mechanisms can be used for continence. The terminal ileum can accommodate short ureters.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `<!--4. -->Preservation of the ileocecal valve can be maintained with which catheterizable pouch?`,
    q2: ``,
    q3: [],
    option: [
      `<!--a. -->T pouch or Kock pouch`,
      `<!--b. -->Le Bag`,
      `<!--c. -->Indiana pouch`,
      `<!--d. -->Mainz I or II`,
      `<!--e. -->Penn pouch`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [0],
    ansText: `Rationale: Preservation of the ileocecal valve can be maintained with the T or Kock pouch. All other pouches use the right colon, so that the ileocecal valve is sacrificed.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `<!--5. -->In which procedure to repair a nipple valve would resection of additional bowel be routinely required?`,
    q2: ``,
    q3: [],
    option: [
      `<!--a. -->Stones on exposed staples`,
      `<!--b. -->Nipple valve slippage`,
      `<!--c. -->Nipple valve atrophy`,
      `<!--d. -->Pinhole leak`,
      `<!--e. -->Anastomotic leak`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [2],
    ansText: `Rationale: Nipple valve atrophy requires that a new nipple valve be made of additional bowel.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `<!--6. -->A 10-year-old child has an ileal conduit for myelomeningocele. The conduit was replaced on two occasions for pipestem conduit development. The conduit is again affected by the same process. The patient’s family wants a continent diversion. Which is the best procedure?`,
    q2: ``,
    q3: [],
    option: [
      `Ureterosigmoidostomy`,
      `<!--b. -->Revise the conduit`,
      `<!--c. -->T pouch using the ileal conduit`,
      `<!--d. -->Penn pouch using the ileal conduit`,
      `<!--e. -->Indiana pouch using the ileal conduit`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [1],
    ansText: `Rationale: <b>With significant small bowel compromise, as well as loss of the ileocecal valve in a neurogenic bladder patient, severe diarrhea may ensue.</b>`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `<!--7. -->A patient with chronic active hepatitis and invasive bladder cancer associated with intravesical carcinoma in situ is scheduled for a cystoprostatectomy. The serum creatinine concentration is 1 mg/dL. Prostatic urethral biopsy shows mild atypia. What is the best diversion?`,
    q2: ``,
    q3: [],
    option: [
      `<!--a. -->T pouch`,
      `<!--b. -->Ileal conduit`,
      `<!--c. -->Right colon reservoir`,
      `<!--d. -->Mainz II`,
      `<!--e. -->Cutaneous ureterostomies`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [1],
    ansText: `Rationale: The best approach is cystoprostatectomy and a conduit. Normal hepatic function is mandated in any patient undergoing continent diversion.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `<!--8. -->The highest reoperation rate in catheterizable pouches occurs with what type of sphincter?`,
    q2: ``,
    q3: [],
    option: [
      `<!--a. -->In situ appendix`,
      `<!--b. -->Imbricated terminal ileum`,
      `<!--c. -->Plicated terminal ileum`,
      `<!--d. -->Nipple valves`,
      `<!--e. -->Transposed appendix`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [3],
    ansText: `Rationale: The highest reoperation rate is associated with nipple valve sphincter failure.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `<!--9. -->Which of the Mitrofanoff sphincter deficiencies can be corrected surgically?`,
    q2: ``,
    q3: [],
    option: [
      `<!--a. -->Length of the appendix`,
      `<!--b. -->Absence of the appendix`,
      `<!--c. -->Stenosis of the appendix`,
      `<!--d. -->All of the above`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [3],
    ansText: `Rationale: The caliber of Mitrofanoff mechanisms, the length of the appendix, stenosis, and even absence of the appendix can be resolved by surgical variations.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `<!--10. -->Hematuria and skin breakdown may occur with what type of pouch?`,
    q2: ``,
    q3: [],
    option: [`T`, `Gastric`, `Mainz`, `Right colon`, `All of the above`],
    optionStyleType: `st-lower-alpha`,
    answer: [1],
    ansText: `Rationale: Hematuria and cutaneous skin erosion may occur with a gastric pouch. With gastric reservoirs or composite reservoirs, the low pH of the urine may lead to hematuria and cutaneous breakdown.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `<!--11. -->Preoperative colonoscopy is indicated in candidates for which reservoir procedures?`,
    q2: ``,
    q3: [],
    option: [`Ileal`, `Jejunal`, `Rectal`, `Gastric`, `All of the above`],
    optionStyleType: `st-lower-alpha`,
    answer: [2],
    ansText: `Rationale: Preoperative colonoscopy is relatively indicated in candidates for any pouch. <b>Any pouch using colon mandates preoperative colonic evaluation.</b>`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `<!--12. -->What condition is more common in absorbable stapled ileal pouches?`,
    q2: ``,
    q3: [],
    option: [
      `<!--a. -->Urine leaks`,
      `<!--b. -->Valve failure`,
      `<!--c. -->Hydronephrosis`,
      `<!--d. -->Ischemic pouch contraction`,
      `<!--e. -->Ureteral stricture`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [3],
    ansText: `Rationale: <b>Because of the overlap of staple lines in absorbable stapled ileal pouches, ischemic pouch contraction may occur.</b>`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `<!--13. -->Anastomotic transitional cell carcinoma develops in a patient who has undergone cystectomy and continent cutaneous urinary diversion. What is the best treatment?`,
    q2: ``,
    q3: [],
    option: [
      `<!--a. -->Distal ureterectomy and reimplantation`,
      `<!--b. -->Conversion to ileal conduit`,
      `<!--c. -->Ileal ureter interposition`,
      `<!--d. -->Nephroureterectomy`,
      `<!--e. -->Cutaneous ureterostomies`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [0],
    ansText: `Rationale: An additional segment of ileum can serve as a proximal limb to the reservoir. If nephrectomy is necessary, careful attention must be paid to the residual renal function.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `<!--14. -->Drainage of mucus is most difficult with which sphincteric mechanism?`,
    q2: ``,
    q3: [],
    option: [
      `<!--a. -->Kock valve`,
      `<!--b. -->In situ appendix`,
      `<!--c. -->Imbricated ileum`,
      `<!--d. -->Plicated ileum`,
      `<!--e. -->Transposed appendix`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [1],
    ansText: `Rationale: <b>The small-diameter catheter used in draining appendiceal sphincter pouches allows for less effective mucus drainage.</b>`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `<!--15. -->Which continent cutaneous diversion allows for a refluxing ureteroenteric anastomosis?`,
    q2: ``,
    q3: [],
    option: [
      `<!--a. -->Mitrofanoff with implantation of the ureters into terminal ileum`,
      `<!--b. -->Mitrofanoff with implantation of the ureters into the colon`,
      `<!--c. -->T pouch`,
      `<!--d. -->Kock pouch`,
      `<!--e. -->Indiana pouch`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [0],
    ansText: `Rationale: The implantation of the ureters into the terminal ileum may allow for reflux. The ileocecal valve and the isoperistaltic ileal segment may either prevent or diminish reflux.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `<!--16. -->Three years after radical cystectomy and construction of a Kock pouch, a patient presents with right lower quadrant discomfort and associated spurts of urinary leakage. The test most likely to diagnose the condition is:`,
    q2: ``,
    q3: [],
    option: [
      `<!--a. -->computed tomography (CT).`,
      `<!--b. -->intravenous pyelogram (IVP).`,
      `<!--c. -->urine culture and sensitivity.`,
      `<!--d. -->cystogram of pouch.`,
      `<!--e. -->urodynamics.`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [2],
    ansText: `Rationale: The most important diagnostic test is urine culture. The symptoms described are those of pouchitis. This is treated by appropriate antibiotic therapy.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `<!--17. -->Three years after cystectomy and Kock pouch for bladder cancer, a patient presents with recurrent episodes of bilateral pyelonephritis. The test most likely to provide the correct diagnosis is:`,
    q2: ``,
    q3: [],
    option: [
      `CT.`,
      `IVP.`,
      `urine culture and sensitivity.`,
      `cystogram of the pouch.`,
      `magnetic resonance imaging (MRI).`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [3],
    ansText: `Rationale: The proximal nipple valve may have failed, leading to reflux and pyelonephritis. This is tested by the pouch-o-gram.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `<!--18. -->What is the most important feature in preventing nipple valve slippage?`,
    q2: ``,
    q3: [],
    option: [
      `<!--a. -->Absorbable staples`,
      `<!--b. -->Length of the intussusception`,
      `<!--c. -->Resecting adequate mesentery`,
      `<!--d. -->Attaching the nipple valve to the side wall of the reservoir`,
      `<!--e. -->Length of staple line`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [3],
    ansText: `Rationale: This results in a relative lengthening of the valve rather than a foreshortening of the valve with pouch filling.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `<!--19. -->In a patient with pipestem conduit and bilateral hydronephrosis requesting conversion to continent urinary diversion, nephrostomy drainage results in clearance values of 40 mL/min on the right and 10 mL/min on the left. Serum creatinine is 1.8 mg/dL. The next step in management is:`,
    q2: ``,
    q3: [],
    option: [
      `<!--a. -->Mainz II to avoid problems with the dilated ureters.`,
      `<!--b. -->T pouch abandoning the disease conduit.`,
      `<!--c. -->no continent diversion.`,
      `<!--d. -->ureterosigmoidostomy.`,
      `neobladder.`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [2],
    ansText: `Rationale: <b>In this case, although the serum creatinine level returns to 1.8 mg/dL, the clearance value measured is less than the 60 mL/min required for continent diversion. Continent diversion should be abandoned, and simple replacement of the conduit considered.</b>`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `<!--20. -->A patient with squamous cell cancer of the bladder desires cystectomy and continent diversion. He has lost 20 pounds in the month before surgery. The next step in management is:`,
    q2: ``,
    q3: [],
    option: [
      `<!--a. -->increased oral intake.`,
      `<!--b. -->conduct preoperative hyperalimentation.`,
      `<!--c. -->conduct postoperative hyperalimentation.`,
      `<!--d. -->proceed directly with surgery.`,
      `<!--e. -->count calories.`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [1],
    ansText: `Rationale: The 20-pound weight loss indicates a potential for nutritional depletion or metastatic disease. A careful search for metastatic disease should be undertaken. For the patient with nutritional depletion, preoperative hyperalimentation is suggested to be of value.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `<!--21. -->Preoperative evaluation with an oatmeal enema is required in which procedure?`,
    q2: ``,
    q3: [],
    option: [
      `<!--a. -->Right colon reservoir`,
      `<!--b. -->Mainz I pouch`,
      `<!--c. -->Mainz II procedure`,
      `<!--d. -->Le Bag pouch`,
      `<!--e. -->Indiana pouch`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [2],
    ansText: `Rationale: <b>Any procedure that relies on the intact anal sphincter for continence (i.e., the Mainz II pouch) requires an assessment of the sphincter before carrying out the operation. This can be assessed by an oatmeal enema, which mimics the constitution of a combination of the urinary and fecal streams.</b>`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `<!--22. -->Follow-up urinary cytology and colonoscopy should be used in which type of continent diversion?`,
    q2: ``,
    q3: [],
    option: [
      `<!--a. -->Ureterosigmoidostomy`,
      `<!--b. -->Mainz II procedure`,
      `<!--c. -->Right colon reservoir`,
      `<!--d. -->All of the above`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [3],
    ansText: `Rationale: <b>Follow-up urinary cytology and colonoscopy is mandatory with any procedure that combines urinary and fecal streams. Because of an increased risk of malignancy even in the absence of admixture of urine and stool, all large intestinal pouches should be subjected to annual investigation by pouchoscopy and cytology.</b>`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `<!--23. -->Nocturnal emptying of the patient’s reservoir is required in which type of diversion?`,
    q2: ``,
    q3: [],
    option: [
      `Ureterosigmoidostomy`,
      `T pouch`,
      `Right colon reservoir`,
      `Penn pouch`,
      `Ileal conduit`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [0],
    ansText: `Rationale: <b>Nocturnal reservoir emptying may be required with any of the continent cutaneous reservoirs to prevent overdistention and possible rupture but is mandatory with ureterosigmoidostomy owing to the additional risk of fecal incontinence and metabolic acidosis.</b>`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `<!--24. -->The appendix is sacrificed in patients undergoing which pouch construction?`,
    q2: ``,
    q3: [],
    option: [
      `<!--a. -->Indiana`,
      `<!--b. -->Le Bag`,
      `<!--c. -->Mainz I`,
      `<!--d. -->All of the above`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [3],
    ansText: `Rationale: The appendix is sacrificed in patients undergoing Indiana, Le Bag, and Mainz I pouch reconstruction because it can serve as a nidus for infection and abscess formation.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `<!--25. -->Pouch stone development occurs most commonly with which pouch?`,
    q2: ``,
    q3: [],
    option: [
      `<!--a. -->T pouch`,
      `<!--b. -->Kock pouch`,
      `<!--c. -->Penn pouch`,
      `<!--d. -->Gastric-ileal composite pouch`,
      `<!--e. -->Le Bag`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [0],
    ansText: `Rationale: Pouch stone development occurs most commonly with the Kock pouch. Despite the exclusion of distal staples, the stapling techniques used to secure nipple valves will lead to a higher potential for stone development than in pouches not requiring nipple valves.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `<!--26. -->What is the typical catheter used for appendiceal sphincters?`,
    q2: ``,
    q3: [],
    option: [
      `<!--a. -->22-French (Fr) straight-tipped`,
      `<!--b. -->22-Fr coudé-tipped`,
      `<!--c. -->14-Fr straight-tipped`,
      `<!--d. -->14-Fr coudé-tipped`,
      `<!--e. -->20-Fr coudé-tipped`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [3],
    ansText: `Rationale: Larger catheters will not fit into the appendix. A straight catheter is more difficult to pass.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `<!--27. -->Urinary retention resulting from continent diversion occurs most commonly with what type of sphincter?`,
    q2: ``,
    q3: [],
    option: [
      `<!--a. -->Appendiceal stoma`,
      `<!--b. -->Benchekroun hydraulic valve`,
      `<!--c. -->Nipple valve sphincter`,
      `<!--d. -->Imbricated Indiana mechanism`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [2],
    ansText: `Rationale: <b>Urinary retention occurs most commonly with nipple valve sphincters.</b> If the chimney of the nipple valve is not near the surface of the abdomen, the catheter can be misdirected into folds of bowel rather than through the nipple valve.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `<!--28. -->Immediate postoperative initial pouch capacity is least in which pouch?`,
    q2: ``,
    q3: [],
    option: [
      `<!--a. -->T or Kock ileal`,
      `<!--b. -->Right colon`,
      `<!--c. -->Gastric`,
      `<!--d. -->Mainz I`,
      `<!--e. -->Transverse colon`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [0],
    ansText: `Rationale: Immediate postoperative initial pouch capacity is least in ileal reservoirs (i.e., the T or Kock pouch). <b>Small bowel pouches have initial capacities that are much lower than right colon pouches.</b>`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `<!--29. -->Elevated pouch pressures would potentially facilitate the continence mechanism seen with which valve or sphincter?`,
    q2: ``,
    q3: [],
    option: [
      `<!--a. -->Benchekroun ileal valve`,
      `<!--b. -->Kock valve`,
      `<!--c. -->Appendiceal tunnel`,
      `<!--d. -->Imbricated Indiana mechanism`,
      `<!--e. -->All of the above`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [0],
    ansText: `Rationale: Because the Benchekroun ileal valve is hydraulic, higher pouch pressures would facilitate continence, whereas lower pouch pressures might lead to incontinence.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `<!--30. -->The long-term failure rate of continence mechanisms is greatest with which mechanism?`,
    q2: ``,
    q3: [],
    option: [
      `<!--a. -->T pouch valve`,
      `<!--b. -->Appendiceal tunnel`,
      `<!--c. -->Benchekroun hydraulic valve`,
      `<!--d. -->Imbricated terminal ileum`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [2],
    ansText: `Rationale: The long-term outcome of Benchekroun hydraulic ileal valve mechanisms is possibly the worst of all reported sphincteric mechanisms.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `<!--31. -->Absorbable staples in continent urinary diversion are best suited to what type of reservoir pouch?`,
    q2: ``,
    q3: [],
    option: [
      `Ileal`,
      `<!--b. -->Right colon reservoir`,
      `<!--c. -->Gastric-ileal composite`,
      `<!--d. -->Gastric`,
      `<!--e. -->None of the above`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [1],
    ansText: `Rationale: <b>The use of absorbable staples is best suited to large bowel pouches. With large bowel pouches there is no problem with staple lines causing subsequent bowel ischemia.</b>`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `<!--32. -->When creating a large intestinal reservoir from absorbable staples, why is bowel eversion necessary?`,
    q2: ``,
    q3: [],
    option: [
      `<!--a. -->Because staples should not be used in reservoir construction`,
      `<!--b. -->To inspect the inside of the reservoir`,
      `<!--c. -->To avoid injury to the mesenteric blood supply`,
      `<!--d. -->To allow application of the second row of staples`,
      `<!--e. -->None of the above`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [3],
    ansText: `Rationale: In an absorbable-stapled right colon pouch, bowel eversion is required to allow for the application of the second row of staples. <b>Staple lines must not cross because this will prevent the bulky, absorbable staples from seating properly.</b> The bowel is everted, a cut is made beyond the end of the staple line, and the next line of staples is applied.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `<!--33. -->Which of the following conditions make patients unsuitable candidates for continent urinary diversion?`,
    q2: ``,
    q3: [],
    option: [
      `<!--a. -->Multiple sclerosis`,
      `<!--b. -->Quadriplegia`,
      `<!--c. -->Mental impairment`,
      `<!--d. -->Severe physical impairment`,
      `<!--e. -->All of the above`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [4],
    ansText: `Rationale: <b>Patients with multiple sclerosis, quadriplegia, frailty, or mental impairment will at some point in their lives require the care of family members or visiting nurses, so they are poor candidates for any form of continent diversion.</b>`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `<!--34. -->Which of the following sutures should NOT be used in the construction of a reservoir?`,
    q2: ``,
    q3: [],
    option: [
      `<!--a. -->Chromic catgut`,
      `<!--b. -->Plain catgut`,
      `Silk`,
      `Polyglycolic acid (Dexon)`,
      `Polyglactin (Vicryl)`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [2],
    ansText: `Rationale: All sutures used in the urinary tract should be absorbable.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `<!--35. -->Which of the following diversions place the patient at risk for the development of a late malignancy?`,
    q2: ``,
    q3: [],
    option: [
      `<!--a. -->Ureterosigmoidostomy`,
      `<!--b. -->T pouch`,
      `<!--c. -->Mainz II`,
      `<!--d. -->Indiana pouch`,
      `<!--e. -->All of the above`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [4],
    ansText: `Rationale: Late malignancy has been reported in all bowel segments exposed to the urinary stream, whether or not there is a commingling with feces.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `<!--36. -->Which of the following diversions places the patient at greatest risk for the development of a late malignancy?`,
    q2: ``,
    q3: [],
    option: [
      `<!--a. -->Ureterosigmoidostomy`,
      `<!--b. -->T pouch`,
      `<!--c. -->Mainz II`,
      `<!--d. -->Indiana reservoir`,
      `<!--e. -->Le Bag`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [0],
    ansText: `Rationale: <b>Although late malignancy has been reported in all bowel segments exposed to the urinary stream, whether or not there is a commingling with feces, the mixture of urothelium, urine, and feces poses the greatest risk.</b>`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `<!--37. -->Continent urinary diversion has which of the following effects?`,
    q2: ``,
    q3: [],
    option: [
      `<!--a. -->Results in a psychotic depression`,
      `<!--b. -->Results in an improved psychosocial adjustment`,
      `<!--c. -->Results in violent behavior`,
      `<!--d. -->Bipolar behavior`,
      `<!--e. -->None of the above`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [1],
    ansText: `Rationale: Many studies from throughout the world have suggested an improved psychosocial adjustment of the patient undergoing continent urinary and fecal diversion compared with those patients with diversions requiring collecting appliances.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `<!--38. -->According to most randomized studies, which type of urinary diversion is associated with the highest reported quality of life?`,
    q2: ``,
    q3: [],
    option: [
      `<!--a. -->Ureterosigmoidostomy`,
      `<!--b. -->Continent ileal reservoir (Kock pouch)`,
      `<!--c. -->Ileal conduit`,
      `<!--d. -->Orthotopic neobladder`,
      `<!--e. -->None—no conclusive studies have established higher satisfaction or quality of life with any one specific continent diversion`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [4],
    ansText: `Rationale: <b>There are insufficient quality-of-life data from randomized studies comparing continent and incontinent urinary diversions to establish the superiority of any one technique.</b>`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `<!--39. -->Which of the following is NOT true of continent urinary diversion?`,
    q2: ``,
    q3: [],
    option: [
      `<!--a. -->It is the gold standard of urinary diversion.`,
      `<!--b. -->It is a safe and reliable urinary diversion.`,
      `<!--c. -->It is associated with an increased complication rate.`,
      `<!--d. -->It is appropriate for selected individuals.`,
      `<!--e. -->It requires stricter selection criteria than incontinent diversion.`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [0],
    ansText: `Rationale: Ileal conduit should be considered the “gold standard” of urinary diversion.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `<!--40. -->Which of the following circumstances would contraindicate a rectal bladder?`,
    q2: ``,
    q3: [],
    option: [
      `<!--a. -->Prior pelvic irradiation`,
      `<!--b. -->Unilateral ureteral dilation`,
      `<!--c. -->Bilateral ureteral dilation`,
      `<!--d. -->Lax anal sphincter tone`,
      `<!--e. -->All of the above`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [4],
    ansText: `Rationale: Dilated ureters, pelvic irradiation, and lax anal sphincteric tone are all contraindications to the procedure.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `<!--41. -->During the construction of a continent cutaneous urinary diversion, the surgeon should:`,
    q2: ``,
    q3: [],
    option: [
      `not be concerned about the continence mechanism because the mechanism will mold to the catheter.`,
      `not test the continence mechanism for ease of catheterization.`,
      `not be concerned about pouch integrity because the pouch will seal itself.`,
      `do none of the above.`,
      `do all of the above.`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [3],
    ansText: `Rationale: <b>The continence mechanism must be catheterized intraoperatively to ensure ease of catheter passage.</b> This is an extremely important and crucial maneuver because the inability to catheterize is a serious complication that will often result in the need for reoperation.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `<!--42. -->If the urine in a continent cutaneous reservoir is found to be infected, what should be done?`,
    q2: ``,
    q3: [],
    option: [
      `<!--a. -->Nothing needs to be done in the absence of symptoms.`,
      `<!--b. -->The urine should always be sterilized with appropriate antibiotics.`,
      `<!--c. -->The infection should be eradicated, and prophylactic antibiotics prescribed.`,
      `<!--d. -->Administer an intravenous pyelogram to check for upper tract damage.`,
      `<!--e. -->Perform a pouch-o-gram.`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [0],
    ansText: `Rationale: Most authors would suggest that bacteriuria in the absence of symptomatology does not warrant antibiotic treatment.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `<!--43. -->The most appropriate and conservative care for pouch rupture is:`,
    q2: ``,
    q3: [],
    option: [
      `<!--a. -->broad-spectrum antibiotic therapy.`,
      `<!--b. -->careful radiologic imaging and antibiotic therapy.`,
      `<!--c. -->surgical exploration for repair of the rupture and broad-spectrum antibiotic therapy.`,
      `<!--d. -->pouch drainage and broad-spectrum antibiotic therapy.`,
      `<!--e. -->bilateral percutaneous nephrostomies.`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [2],
    ansText: `Rationale: <b>In general, these patients require immediate pouch decompression, radiologic pouch studies, and surgical exploration with pouch repair.</b> If the amount of urinary extravasation is small and the patient does not have a surgical abdomen, catheter drainage and antibiotic administration may suffice in treating intraperitoneal rupture of a pouch. Patients managed with this conservative approach require careful monitoring.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `<!--44. -->The first pouch to use the Mitrofanoff principle was the:`,
    q2: ``,
    q3: [],
    option: [
      `<!--a. -->Mainz I.`,
      `<!--b. -->Penn.`,
      `<!--c. -->Kock.`,
      `<!--d. -->Indiana.`,
      `<!--e. -->Le Bag.`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [1],
    ansText: `Rationale: The Penn pouch was the first continent diversion to use the Mitrofanoff principle, wherein the appendix served as the continence mechanism.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `<!--45. -->Which of the following represents the advantage of the gastric pouch?`,
    q2: ``,
    q3: [],
    option: [
      `<!--a. -->Electrolyte reabsorption is reduced.`,
      `<!--b. -->Absorptive malabsorption is avoided.`,
      `<!--c. -->Acid urine may reduce the risk of infection.`,
      `<!--d. -->All of the above`,
      `<!--e. -->None of the above`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [3],
    ansText: `Rationale: Electrolyte reabsorption is greatly diminished, shortening of the absorptive bowel does not occur, and the acid urine may decrease the likelihood of reservoir colonization.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `<!--46. -->When converting from an ileal conduit to a continent diversion, the conduit should be:`,
    q2: ``,
    q3: [],
    option: [
      `<!--a. -->discarded because it is older and subject to higher complications.`,
      `<!--b. -->preserved for the ureteroileal anastomosis.`,
      `<!--c. -->incorporated into the continent diversion when possible.`,
      `<!--d. -->discarded because it is a potential nidus of infection.`,
      `<!--e. -->None of the above`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [2],
    ansText: `Rationale: The authors prefer to use the conduit in some form whenever possible. The use of an existing bowel segment has the potential to diminish metabolic sequelae and may result in a lower complication rate.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `<!--47. -->Which of the following is TRUE of absorbable staples?`,
    q2: ``,
    q3: [],
    option: [
      `<!--a. -->Their use has been shown to shorten operative time.`,
      `<!--b. -->They are safe and reliable.`,
      `<!--c. -->Unlike nonabsorbable staples, they must not be overlapped.`,
      `<!--d. -->All of the above.`,
      `<!--e. -->None of the above.`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [3],
    ansText: `Rationale: The use of absorbable staples has substantially reduced the time required to fashion bowel reservoirs and has demonstrated short-term and long-term reliability with respect to reservoir integrity and volume. They must not be overlapped because overlapping will prevent the proper close of the staple.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
];
