var quiz = [
   
   
    {
        q: `Regarding perioperative thrombo-prophylaxis treatment after robot-assisted radical cystectomy (RARC), which of the following is true?`,
        q2: ``,
        q3: [],
        option: [`Pneumatic compressions and leg stockings only are adequate.`, 
        `Low molecular weight heparin can be used as a single dose before the operation`, 
        `Low molecular weight heparin should be continued up to 4 weeks after surgery.`, 
        ` Both mechanical and pharmacological prophylaxes are adequate for 48 hours perioperative.`, 
        ` No prophylaxis.`,
        ],
        optionFeedback: [``,
          ``,
          ``,
          ``,
          ``],
        optionStyleType: `st-lower-alpha`,
        answer: [2],
        ansText: `Rationale: Based on 939 patients who underwent robot-assisted radical cystectomy, the incidence of hematologic and vascular complications was 10%. A survey of urologists who were aware of the American Urological Association (AUA) Best Practice Statement guidelines revealed that 51% were likely to use thromboprophylaxis (odds ratio, 1.4, confidence interval, 1.2 to 1.6). Eighteen percent of urologic oncologists and/or laparoscopic/robotic specialists and 34% of nonurologic oncologists and/or laparoscopic/robotic specialists avoided routine thromboprophylaxis in patients undergoing radical cystectomy. The former were more likely to use thromboprophylaxis (<b><i>P</i></b> &lt; .0001) than other respondents. Urologists graduating after the year 2000 used thromboprophylaxis in high-risk patients undergoing radical cystectomy more often than did earlier graduates (79.2% vs. 63.4%, <b><i>P</i></b> &lt; .0001). <b>Based on the American College of Surgeons NSQIP (National Surgical Quality Improvement Program) database from 1307 patients who underwent radical cystectomy, the mean time to venous thromboembolism diagnosis was 15.2 days postoperatively; 55% of all venous thromboembolism events were diagnosed after patient discharge home.</b> It is recommended to consider extended duration pharmacologic prophylaxis (4 weeks) in this high-risk surgical population.`,
        state: `notAnswered`,
        userAnswered: []
      ,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`        ,
        type: `MCSS`},
  
      {
        q: `Criteria for patient selection for intracorporeal urinary diversion during RARC include all of the following except:`,
        q2: ``,
        q3: [],
        option: [`high body mass index.`, 
        `locally advanced disease.`, 
        `older age.`, 
        `prior abdominal surgery. `, 
        `none of the above. `,
        ],
        optionFeedback: [``,
          ``,
          ``,
          ``,
          ``],
        optionStyleType: `st-lower-alpha`,
        answer: [4],
        ansText: `Rationale: The selection criteria (including high body mass index, locally advanced disease, older age, prior abdominal surgery) have significantly broadened as learning curve has flattened. Reduction in cardiac and pulmonary compliance due to the inability to tolerate steep Trendelenburg position especially with prolonged operative duration during intracorporeal urinary diversion (ICUD) has also been addressed. Newer technology available is the Xi model of the da-Vinci Surgical System and use of the AirSeal has allowed surgeons to operate in less steep Trendelenburg position. Absolute and relative contraindications for neobladder are similar to open surgery.`,
        state: `notAnswered`,
        userAnswered: []
      ,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`        ,
        type: `MCSS`},
  
      {
        q: `Enhanced recovery after surgery (ERAS) includes which of the following?`,
        q2: ``,
        q3: [],
        option: [`Allow clear liquids up to 2 hours prior to the surgery`, 
        `Allow solid food up to 6 hours prior to the surgery.`, 
        `Maintain positive balance during the procedure.`, 
        ` Mechanical bowel preparations and oral antibiotics should be omitted.`, 
        `All of the above. `,
        ],
        optionFeedback: [``,
          ``,
          ``,
          ``,
          ``],
        optionStyleType: `st-lower-alpha`,
        answer: [4],
        ansText: `Rationale: ERAS has evolved with more than 20 key components and has been tailored by several cystectomy experts. Recent modifications include early use of alvimopan, intraoperative goal-oriented fluid optimization, immediate initiation of oral diet, and reduced narcotic use. Xu and colleagues (2015) compared traditional pathway to an enhanced recovery protocol and reported decreased opioid usage per day, incidence of ileus, and hospital stay. <b>Opioid use for breakthrough pain underwent a radical change from opioid patient controlled analgesia (PCA) and epidurals to high-dose acetaminophen and/or ketorolac. Patients who underwent RARC with ICUD and participated in the ERAS pathway had shorter length of stay and were more likely to receive a neobladder.</b> The ERAS group was associated with significantly lower overall, gastrointestinal-related complications and readmission rates at 90 days. Participating in the ERAS pathway and younger age were independently associated with a hospital stay of less than 10 day. Pooled meta-analysis of 13 studies with 1493 patients showed that implementation of ERAS protocols after surgery reduced complications, length of stay without impacting overall readmission rates.`,
        state: `notAnswered`,
        userAnswered: []
              ,
        type: `MCSS`},
  
      {
        q: `During RARC and intracorporeal urinary diversion,`,
        q2: ``,
        q3: [],
        option: [`usage of 30° up lens is advantageous for deep female pelvis.`, 
        `a 0-degree lens can be used for the entire procedure.`, 
        `the camera port is inserted below the umbilicus.`, 
        `the camera can be easily switched to another robotic port. `, 
        `a five-port configuration is used. `,
        ],
        optionFeedback: [``,
          ``,
          ``,
          ``,
          ``],
        optionStyleType: `st-lower-alpha`,
        answer: [1],
        ansText: `Rationale: The majority of robot-assisted radical prostatectomy procedures use different lenses for the procedure. During robot-assisted radical cystectomy, surgeons prefer a 0-degree lens. Special situations of a narrow, deep pelvis in association with obesity can require a 30-degree down lens for better visualization, especially for the proximal portion of the extended lymph node dissection.`,
        state: `notAnswered`,
        userAnswered: []
      ,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`        ,
        type: `MCSS`},
  
      {
        q: `During intracorporeal urinary diversion, the benefit of marionette stitch is to:`,
        q2: ``,
        q3: [],
        option: [`identify the distal and proximal ends of the conduit.`, 
        `help in retaining orientation of the bowel.`, 
        `allow free movement of the bowel segment for creation of the conduit.`, 
        `prevent leakage of bowel contents during the creation of the conduit. `, 
        `allow free movement of the bowel segment and prevent inadvertent movements of the robotic instruments. `,
        ],
        optionFeedback: [``,
          ``,
          ``,
          ``,
          ``],
        optionStyleType: `st-lower-alpha`,
        answer: [2],
        ansText: `Rationale: Because of the multiple detailed steps required during intracorporeal urinary diversion in a narrow operative space, the marionette stitch helps in controlling the area of focus by acting as a retraction and exposing the correct surgical space to perform the right and left uretero-ileal anastomosis.`,
        state: `notAnswered`,
        userAnswered: []
              ,
        type: `MCSS`},
  
      {
        q: `To avoid the risk of uretero-ileal strictures, which of the following is correct?`,
        q2: ``,
        q3: [],
        option: [`Button-hole enterotomy is done using cold scissors.`, 
        `Spatulation is omitted.`, 
        `Slit-like enterotomy.`, 
        `Using electrocautery in creating the enterotomy. `, 
        ` None of the above`,
        ],
        optionFeedback: [``,
          ``,
          ``,
          ``,
          ``],
        optionStyleType: `st-lower-alpha`,
        answer: [1],
        ansText: `Rationale: To avoid risk of strictures, it is advisable to <b>avoid the use of electrocautery; instead, it is better to use a cold scissors to create a wide button-hole enterotomy by removing the serosa in the proximal end of the ileum.</b> We also have started to preserve a flap of peritoneum while dissecting the right ureter (periureteral space) at the time of RARC and extended lymph node dissection. This peritoneal flap helps in covering the proximal uretero-ileal anastomosis and retroperitonealize it, to avoid an inflammatory response at the site of the anastomosis. `,
        state: `notAnswered`,
        userAnswered: []
              ,
        type: `MCSS`},
  
      {
        q: `During creation of the neobladder, mobilization of the bowel to reach the urethra can be achieved by all of the following except:`,
        q2: ``,
        q3: [],
        option: [`reducing Trendelenburg position.`, 
        `using Penrose drain for gentle traction and stretching.`, 
        `mobilization of the urethra cephalad.`, 
        ` incising the peritoneum over the mesentery.`, 
        `dissection of the ileum around the ileocecal junction. `,
        ],
        optionFeedback: [``,
          ``,
          ``,
          ``,
          ``],
        optionStyleType: `st-lower-alpha`,
        answer: [2],
        ansText: `Rationale: Traditionally, a steep Trendelenburg position has been used to avoid bowel in the operative field and also to gain direct access to the deeper pelvis. Unfortunately this works against intracorporeal neobladder because urethral-neobladder anastomosis is difficult if the bowel tries to retract back into the abdominal cavity and is in tension. Several options used to reduce tension and ease anastomosis include reducing Trendelenburg, performing the urethra-neobladder anastomosis at the beginning of the procedure, incising the peritoneum over the mesentery, dissection of the ileum around the ileocecal junction, and, finally, using temporary traction for stretching and holding the bowel in place for anastomosis`,
        state: `notAnswered`,
        userAnswered: []
              ,
        type: `MCSS`},
  
      {
        q: `All of these factors that may affect operative time during RARC except:`,
        q2: ``,
        q3: [],
        option: [`female gender.`, 
        `higher body mass index.`, 
        `prior abdominal surgery.`, 
        `approach to urinary diversion (intracorporeal versus extracorporeal). `, 
        ` urinary diversion type (ileal conduit vs neobladder).`,
        ],
        optionFeedback: [``,
          ``,
          ``,
          ``,
          ``],
        optionStyleType: `st-lower-alpha`,
        answer: [3],
        ansText: `Rationale: No significant difference between intracorporeal and extracorporeal approaches to urinary diversion was found based on the recent International Robotic Cystectomy Consortium (IRCC) study of 2134 patients. One possible explanation is that the additional time for undocking, patient positioning and then redocking for extracorporeal diversion may have reduced the difference between both approaches. High-volume institutions had shorter operative times for radical cystectomy. This may be attributed to the experience of the surgeon and the teams at those institutions. `,
        state: `notAnswered`,
        userAnswered: []
      ,
	type: `MCSS`        ,
        type: `MCSS`},
  
      {
        q: `Regarding the approach for nerve sparing cystectomy in men, which of the following is incorrect?`,
        q2: ``,
        q3: [],
        option: [`Preservation of the proximal neurovascular complex.`, 
        `Athermal approach of the seminal vesicles.`, 
        `Control of the proximal prostatic pedicles near the prostate.`, 
        ` Lateral nerve preservation is done after dissection of the prostatic apex.`, 
        `Computer-assisted reconstruction does not help. `,
        ],
        optionFeedback: [``,
          ``,
          ``,
          ``,
          ``],
        optionStyleType: `st-lower-alpha`,
        answer: [4],
        ansText: `Rationale: Computer-assisted dissection that involved 3D reconstruction of the inferior hypogastric plexus has demonstrated the precise location and distribution of pelvic nerves helping in both continence and erectile function. Approximately one-third of cross-sectional external urethral sphincter area has shown to be laterally overlapped by the dorsal venous complex at the prostatic apex. Doppler studies have <b>shown dorso-cavernous anastomoses play an important role in the cavernous arterial hemodynamics.</b> Vascular anastomoses have also been found between different arterial supplies (dorsal, the cavernous and the bulbourethral) of the penis. These arteries, except for bulbo-urethral arteries, have been shown to have function of contractibility based on their muscular walls and accompanying nerves. At the site of the external urethral sphincter, cavernosa nerves converge close to the urethra before they penetrate the muscular pelvic floor.`,
        state: `notAnswered`,
        userAnswered: []
              ,
        type: `MCSS`},
  
      {
        q: `It is critical to avoid injury to the neural pathway for continence and sexual function in the following area:`,
        q2: ``,
        q3: [],
        option: [`common iliac bifurcation.`, 
        `tip of seminal vesicles.`, 
        `lateral prostatic fascia.`, 
        ` dorsal venous complex and ureters.`, 
        ` all of the above.`,
        ],
        optionFeedback: [``,
          ``,
          ``,
          ``,
          ``],
        optionStyleType: `st-lower-alpha`,
        answer: [4],
        ansText: `Rationale: Nerve-sparing approach should only be utilized in patients who have anatomically safe location of tumor, lower tumor burden, and adequate baseline sexual function making such patients more amenable to nerve-sparing not only for sexual preservation but also for continence after creation of a neobladder. The <b>nerves are at risk at their origin in the medial aspect of the common iliac vessels and the presacral area.</b> It is critical to keep in mind the course of the pelvic plexus while performing an extended lymph node dissection as it can risk both sexual function and continence. <b>The approach to nerve-sparing has to also start early on from the high ligation of the bladder vascular pedicle</b> (ensuring preservation of the proximal neurovascular complex) to the incision of the peritoneum in the pouch of Douglas overlying the recto-vesical space. Once the ampullae of the vasa are identified and safely dissected an athermal approach of the seminal vesicles, while sparing the Denonvilliers fascia (where the pelvic plexus is mostly concentrated), should be attempted. It is safe to avoid manipulation and sometimes spare the middle to lower part of the seminal vesicles. The complete lateral nerve preservation (i.e., veil of Aphrodite) and its distal extent are difficult to complete without dissecting the apex of the prostate after dropping of the bladder.`,
        state: `notAnswered`,
        userAnswered: []
              ,
        type: `MCSS`},
  
      {
        q: `The ileal surgical maneuvers for continence after creation of neobladder are:`,
        q2: ``,
        q3: [],
        option: [`adequate de-tubularization and double-folding.`, 
        `capacity (length of bowel used).`, 
        `preservation of urethral length.`, 
        `sphincter complex. `, 
        ` all of the above`,
        ],
        optionFeedback: [``,
          ``,
          ``,
          ``,
          ``],
        optionStyleType: `st-lower-alpha`,
        answer: [4],
        ansText: `Rationale: Several other key steps include mobilizing the sigmoid colon out of the true pelvis, and occasionally a stay suture is used to keep it temporarily fixed laterally until the neobladder is created. It is also critical to reduce the steep Trendelenburg position after undocking the robot. The new advances with the da-Vinci Xi Surgical System with an integrated operating room table will make this easier without undocking the surgical robot. Application of perineal pressure at the time of anastomosis with insertion of Foley catheter to guide the needle towards the urethral opening has already been used consistently during robot-assisted radical prostatectomy. The utilization of barbed suture, especially the V-Loc, has helped reduce time and complexity of neobladder creation as well as the urethral anastomosis. Detubularization of the ileal segment, opening and stretching of the bowel helps in adding length to the ileum. The peritoneal covering of the ileum can be also incised and the mesenteric fat is released to help add length. This should be performed with care as it exposes the mesenteric vessels and can lead to annoying bleeding which can jeopardize the vascular supply to the neobladder. The Karolinska group has used Penrose drains in their early experience for gentle stretching and traction of bowel for ease of anastomosis.`,
        state: `notAnswered`,
        userAnswered: []
              ,
        type: `MCSS`},
  
      {
        q: `The most common cause of complications after RARC and intra-corporeal urinary diversion is:`,
        q2: ``,
        q3: [],
        option: [`bleeding`, 
        `sepsis`, 
        `necrosis of the bowel segment.`, 
        `enteroenteric anastomotic leak. `, 
        `port site and parastomal hernia. `,
        ],
        optionFeedback: [``,
          ``,
          ``,
          ``,
          ``],
        optionStyleType: `st-lower-alpha`,
        answer: [1],
        ansText: `Rationale: A study evaluated 935 patients in the IRCC database who had robot-assisted radical cystectomy and pelvic lymph node dissection with both intracorporeal (ileal conduit: 106; neobladder: 61), and extracorporeal urinary diversion (ileal conduit: 570; neobladder: 198). The 90-day complication rate was not significantly different between the two groups, but there was a trend favoring the intracorporeal group (41% vs. 49%, <b><i>P</i></b> = .05). <b>Gastrointestinal complications and sepsis constituted the majority of the complications in all robot-assisted radical cystectomy series comparing intracorporeal and extracorporeal urinary diversion.</b> Although both complications were significantly lower in the intracorporeal group, sepsis was the most common complication in that group.`,
        state: `notAnswered`,
        userAnswered: []
              ,
        type: `MCSS`},
      
    
     
]