var quiz = [
  {
    q: `Which of the following is NOT considered a sex accessory tissue?`,
    q2: ``,
    q3: [],
    option: [
      `Prostate gland`,
      `Seminal vesicles`,
      `Tunica albuginea`,
      `Ampullae `,
      ` Bulbourethral gland`,
    ],
    optionFeedback: [``, ``, ``, ``, ``],
    optionStyleType: `st-lower-alpha`,
    answer: [2],
    ansText: `Rationale: Sex accessory tissues include the prostate gland, seminal vesicles, ampullae, and bulbourethral glands. They are believed to play a major, but unknown, role in the reproductive process.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
    type: `MCSS`,
    type: `MCSS`,
    type: `MCSS`,
    type: `MCSS`,
  },

  {
    q: `Which fetal hormone stimulates the development of the wolffian ducts?`,
    q2: ``,
    q3: [],
    option: [
      `Estradiol`,
      `Dihydrotestosterone (DHT)`,
      `Estrone`,
      ` Testosterone`,
      ` Inhibin`,
    ],
    optionFeedback: [``, ``, ``, ``, ``],
    optionStyleType: `st-lower-alpha`,
    answer: [3],
    ansText: `Rationale: The wolffian ducts develop into the seminal vesicles, epididymis, vas deferens, ampulla, and ejaculatory duct; the developmental growth of this group of glands is stimulated by fetal testosterone and not DHT.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
    type: `MCSS`,
  },
  {
    q: `Which one of the following statements about fetal development of the lower urogenital tract is FALSE?`,
    q2: ``,
    q3: [],
    option: [
      `The urogenital sinus derives from the cloaca.`,
      `The cloaca gets its name (L. “sewer”) because it receives input from the gastrointestinal and urinary tracts.`,
      `The seminal vesicles derive from the posterior portion of the wolffian ducts, whereas the prostate derives from the anterior portion.`,
      `Sox9 is an early molecular marker of prostate development. `,
      ` The urogenital sinus is a primordial structure that contributes to bladder <i>and</i> prostate development.`,
    ],
    optionFeedback: [``, ``, ``, ``, ``],
    optionStyleType: `st-lower-alpha`,
    answer: [2],
    ansText: `Rationale: The prostate develops from the urogenital sinus, not the wolffian duct.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `Which fetal hormone is most important in stimulating the growth of the prostate during development?`,
    q2: ``,
    q3: [],
    option: [`Estradiol`, `DHT`, `Estrone`, ` Testosterone`, ` Inhibin`],
    optionFeedback: [``, ``, ``, ``, ``],
    optionStyleType: `st-lower-alpha`,
    answer: [1],
    ansText: `Rationale: The prostate first appears and starts its development from the urogenital sinus during the third month of fetal growth, and development is directed primarily by DHT, not testosterone.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
    type: `MCSS`,
    type: `MCSS`,
    type: `MCSS`,
    type: `MCSS`,
    type: `MCSS`,
  },
  {
    q: `Which one of the following statements is TRUE regarding the role of androgens in prostate development?`,
    q2: ``,
    q3: [],
    option: [
      `Males will develop prostates in the presence of sufficiently high levels of androgens, but females will not.`,
      `Females will develop prostates in the presence of sufficiently high levels of androgens, but males will not.`,
      `Both males and females will develop prostates in the presence of sufficiently high levels of androgens.`,
      ` Prostate tissue rudiments with a normal androgen receptor in the epithelium but mutant androgen receptor in the mesenchyme will develop into normal prostates in the presence of sufficiently high levels of androgen.`,
      ` Prostate tissue rudiments with androgen receptor overexpression in the epithelium but mutant androgen receptor in the mesenchyme will develop into normal prostates in the absence of androgen`,
    ],
    optionFeedback: [``, ``, ``, ``, ``],
    optionStyleType: `st-lower-alpha`,
    answer: [2],
    ansText: `Rationale: If androgen (testosterone or DHT) levels are sufficiently high at the right time in fetal development, prostate development will proceed in the urogenital sinus regardless of whether the embryo is male or female. For prostate development to proceed, androgen receptor is required to be functional in the mesenchyme.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `Which α<sub>1</sub>-adrenergic receptor subtype is linked to smooth muscle contraction in the prostate?`,
    q2: ``,
    q3: [],
    option: [
      `α<sub>D</sub>`,
      `α<sub>1A</sub>`,
      `α<sub>1B</sub>`,
      `α<sub>2</sub> `,
      `α<sub>2B</sub> `,
    ],
    optionFeedback: [``, ``, ``, ``, ``],
    optionStyleType: `st-lower-alpha`,
    answer: [1],
    ansText: `Rationale: Research work has demonstrated three subtypes of the α<sub>1</sub>-adrenergic receptor (α<sub>1A</sub>, α<sub>1B</sub>, and α<sub>1D</sub>), of which the α<sub>1A</sub> receptor appears to be linked to contraction.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `Which of the following is TRUE regarding testosterone?`,
    q2: ``,
    q3: [],
    option: [
      `Testosterone is synthesized by the Sertoli cells of the testes.`,
      `Testosterone is synthesized by the Leydig cells of the testes.`,
      `Testosterone is a direct precursor of pregnenolone`,
      `5α-Reductase is an enzyme that converts DHT into testosterone. `,
      `Aromatase converts estrogens into testosterone. `,
    ],
    optionFeedback: [``, ``, ``, ``, ``],
    optionStyleType: `st-lower-alpha`,
    answer: [1],
    ansText: `Rationale: Foremost among the hormones and growth factors that stimulate the prostate is the prohormone testosterone, which must be converted within the prostate into the active androgen DHT. <b>Testosterone is synthesized in the Leydig cells of the testes from pregnenolone by a series of reversible reactions; however, once testosterone is reduced by 5α-reductase into DHT or to estrogens by aromatase, the process is irreversible.</b> In other words, whereas testosterone can be converted into DHT and into estrogens, estrogens and DHT cannot be converted into testosterone.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `Dehydroepiandrosterone (DHEA) has been suggested as a major source of testosterone within the plasma. What percentage of total testosterone has been determined to be derived from DHEA?`,
    q2: ``,
    q3: [],
    option: [`1%`, `2%`, `5%`, `15% `, `20% `],
    optionFeedback: [``, ``, ``, ``, ``],
    optionStyleType: `st-lower-alpha`,
    answer: [0],
    ansText: `Rationale: Less than 1% of the total testosterone in the plasma is derived from DHEA.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
    type: `MCSS`,
    type: `MCSS`,
    type: `MCSS`,
  },
  {
    q: `To what is the majority of testosterone in the plasma bound?`,
    q2: ``,
    q3: [],
    option: [
      `Insulin`,
      `Cholesterol`,
      `Prostaglandins`,
      ` TP53`,
      `Sex hormone-binding globulin (SHBG) `,
    ],
    optionFeedback: [``, ``, ``, ``, ``],
    optionStyleType: `st-lower-alpha`,
    answer: [4],
    ansText: `Rationale: The majority of testosterone bound to plasma protein is associated with SHBG.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
    type: `MCSS`,
    type: `MCSS`,
  },
  {
    q: `Which 5α-reductase isoform predominates in the prostate gland?`,
    q2: ``,
    q3: [],
    option: [`Type 1`, `Type 2`, `Type 3`, `Type 4 `, `Type 5 `],
    optionFeedback: [``, ``, ``, ``, ``],
    optionStyleType: `st-lower-alpha`,
    answer: [1],
    ansText: `Rationale: The type 2 isoform is mutated in 5α-reductase deficiency and is the dominant isoform present in the prostate gland.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `What is the source of fructose in seminal plasma?`,
    q2: ``,
    q3: [],
    option: [
      `Prostate gland`,
      `Bulbourethral gland`,
      `Vas deferens`,
      ` Seminal vesicles`,
      `Basal cells `,
    ],
    optionFeedback: [``, ``, ``, ``, ``],
    optionStyleType: `st-lower-alpha`,
    answer: [2],
    ansText: `Rationale: The source of fructose in human seminal plasma is the seminal vesicles. Patients with congenital absence of the seminal vesicles also have an associated absence of fructose in their ejaculates. `,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `Compartmentalization of the androgen receptor from the cytosol to the nucleus is dependent on:`,
    q2: ``,
    q3: [],
    option: [
      `dimerization`,
      `adenosine triphosphate (ATP).`,
      `RAN-mediated transport.`,
      ` nuclear localization and nuclear export signals.`,
      ` all of the above.`,
    ],
    optionFeedback: [``, ``, ``, ``, ``],
    optionStyleType: `st-lower-alpha`,
    answer: [4],
    ansText: `Rationale: After binding ligand, the androgen receptor dissociates from chaperonins, dimerizes, and then is transported to the nucleus via a nuclear localization motif, which activates Ran-dependent active transport, a process that is ATP dependent.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `Which feature of the androgen receptor polymorphisms is thought to impact on the overall activity of androgen target gene induction?`,
    q2: ``,
    q3: [],
    option: [
      `Zinc finger motifs`,
      `Poly CAG repeats`,
      `Nuclear export signals`,
      `Ligand binding domain `,
    ],
    optionFeedback: [``, ``, ``, ``, ``],
    optionStyleType: `st-lower-alpha`,
    answer: [1],
    ansText: `Rationale: The shorter the length, the more actively the androgen receptor is thought to function.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },

  {
    q: `Which of the following is TRUE with regard to the effects of estrogens in prostate development?`,
    q2: ``,
    q3: [],
    option: [
      `Estrogens are not required for the development of a prostate because ER-α and ER-β knockout mice have phenotypically normal prostates.`,
      `ER-α regulates ductal formation.`,
      `ER-β is required for prostates to allow sperm to mature to an active form.`,
      `b and c `,
    ],
    optionFeedback: [``, ``, ``, ``, ``],
    optionStyleType: `st-lower-alpha`,
    answer: [0],
    ansText: ``,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `When the androgen receptor binds to an androgen response element, which of the following is (are) true?`,
    q2: ``,
    q3: [],
    option: [
      `The dimerization of the receptor is always head to head, regardless of whether the sequence is a direct repeat or an inverted repeat.`,
      `The dimerization occurs head to head for an inverted repeat and head to tail for a direct repeat.`,
      `The dimerization of the androgen receptor occurs on the DNA template in a process that requires ATP and heat shock proteins.`,
      ` The androgen receptor can bind to a target androgen response element in either a head-to-head or a head-to-tail orientation, depending on the orientation of the structural gene.`,
    ],
    optionFeedback: [``, ``, ``, ``, ``],
    optionStyleType: `st-lower-alpha`,
    answer: [0],
    ansText: `Rationale: Although most models predicted that inverted repeat and direct repeat androgen response elements would have dimers that bind with opposite polarity, this prediction was not observed in x-ray crystallography studies.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
];
