var quiz = [
  {
    q: `Since 2008, the incidence of prostate cancer in the United States:`,
    q2: ``,
    q3: [],
    option: [
      `is decreasing.`,
      `is stable.`,
      `is increasing.`,
      `increased initially, then decreased. `,
      `is fluctuating. `,
    ],
    optionFeedback: [``, ``, ``, ``, ``],
    optionStyleType: `st-lower-alpha`,
    answer: [0],
    ansText: `Rationale: According to Surveillance, Epidemiology, and End Results (SEER) estimates, the incidence of prostate cancer peaked in 1992, approximately 5 years after introduction of PSA as a screening test, fell precipitously until 1995, increased slowly at a slope similar to that observed prior to the PSA era until 2001, has fluctuated year-to-year since 2001, and has been consistently decreasing since 2008.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `In the United States, the highest prostate cancer incidence rates are seen in:`,
    q2: ``,
    q3: [],
    option: [
      `Caucasians`,
      `African Americans.`,
      `Hispanic/Latinos.`,
      `Asian Americans `,
      `American Indians. `,
    ],
    optionFeedback: [``, ``, ``, ``, ``],
    optionStyleType: `st-lower-alpha`,
    answer: [1],
    ansText: `Rationale: African American men have one of the highest reported incidences of prostate cancer in the world, with an incidence of 186.8 per 100,000 person-years and a relative incidence of 1.75 compared to white men in the United States (American Cancer Society). Although African Americans have experienced a greater decline in mortality than white men since the early 1990s, their death rates remain 2.2 times higher than whites. Many biological, environmental, and social hypotheses have been advanced to explain these differences, ranging from postulated differences in genetic predisposition; differences in mechanisms of tumor initiation, promotion and/or progression; higher fat diets, higher serum testosterone levels, or higher body mass index; structural, financial, educational, and cultural barriers to screening, early detection and aggressive therapy; and physician bias. There are currently no data that clearly indicate any of these hypotheses are the determinants of the observed differences in incidence or mortality, and it seems likely that the source of the disparity is multifactorial, although emerging data indicate a clear biologic underpinning.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `Worldwide, prostate cancer:`,
    q2: ``,
    q3: [],
    option: [
      `is the leading cancer diagnosis in men.`,
      `is the leading cause of cancer-related mortality.`,
      `incidence is highest in countries with the highest rates of screening`,
      ` is entirely genetic in origin.`,
      `has the lowest age-adjusted mortality rates per 100,000 men in North America. `,
    ],
    optionFeedback: [``, ``, ``, ``, ``],
    optionStyleType: `st-lower-alpha`,
    answer: [2],
    ansText: `Rationale: The age-standardized incidence rates per 100 000 men are highest in the highest income regions of the world where PSA screening is more commonly practiced.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `With respect to two large randomized trials assessing the effect of prostate specific antigen (PSA) screening on prostate cancer mortality:`,
    q2: ``,
    q3: [],
    option: [
      `overall incidence rates were higher in European Randomized Study of Screening for Prostate Cancer (ERSPC,) but overall mortality rates were higher in Prostate, Lung, Colorectal and Ovarian PLCO`,
      `the ERSPC showed no significant difference in survival between screened and unscreened men.`,
      `the PLCO cancer screening trial demonstrated a 20% risk reduction in prostate cancer mortality in screened men compared to unscreened men.`,
      `contamination of the control arm with PSA screening is a limitation of the PLCO cancer screening trial. `,
      ` both studies clearly show no benefit to PSA screening for prostate cancer.`,
    ],
    optionFeedback: [``, ``, ``, ``, ``],
    optionStyleType: `st-lower-alpha`,
    answer: [3],
    ansText: `Rationale: The trial has been criticized for high rates of pre-screening (44% reported undergoing PSA testing prior to enrollment), poor compliance with prostate biopsy, and 52% contamination by ad hoc screening in the control arm. A follow-up study in which PLCO participants were questioned about PSA testing reported a 15% non-PSA testing rate in the control arm of PLCO, which is identical to the non-compliance with screening in the screening arm. Another study showed that when analyzed by actual screening status, rather than an intent to screen analysis, results of the PLCO were similar to that of the ERSPC with respect to the benefit of PSA screening in reducing prostate cancer mortality.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `Compared with a man with no family history of prostate cancer, the risk of developing prostate cancer in a man with one affected first-degree relative is:`,
    q2: ``,
    q3: [],
    option: [
      `unchanged`,
      `1.5 times higher.`,
      `2 to 3 times higher.`,
      `5 times higher. `,
      ` 100%`,
    ],
    optionFeedback: [``, ``, ``, ``, ``],
    optionStyleType: `st-lower-alpha`,
    answer: [3],
    ansText: `Rationale: In someone with a positive family history of prostate cancer, the relative risk increases according to the number of affected family members, their degree of relatedness, and the age at which they were affected. There have been more than 100 single nucleotide polymorphism (SNPs) identified in germline genome-wide association study (GWAS) studies that influence the risk of prostate cancer, and multi-SNP panels can identify individuals at very low and very high risk, although none have shown to be correlated with disease aggressiveness.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `High body mass index is associated with:`,
    q2: ``,
    q3: [],
    option: [
      `protection against oxidative stress.`,
      `higher circulating androgens.`,
      `lower serum PSA levels.`,
      `better cancer-specific survival after radical prostatectomy. `,
      ` lower free IGF-1.`,
    ],
    optionFeedback: [``, ``, ``, ``, ``],
    optionStyleType: `st-lower-alpha`,
    answer: [2],
    ansText: `Rationale: Higher body mass index has been associated with increased biologic measures of oxidative stress, lower circulating androgen levels, lower serum PSA (perhaps as a consequence of lower circulating androgens), higher serum-free IGF-1 levels, and worse cancer specific survival after radical prostatectomy. Obese men have lower PSA levels and larger prostates, which together may lead to fewer biopsies and more sampling error, potentially contributing to an increased risk of high-grade disease.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `Which of the following statements regarding gene fusions in prostate cancer are correct?`,
    q2: ``,
    q3: [],
    option: [
      `The most frequent fusions are between the TMPRSS2 serine protease to members of the E26 transformation-specific (ETS) family of oncogenic transcription factors.`,
      `The TMPRSS2-ERG fusion gene is present in prostate stem cells.`,
      `TMPRSS2 expression is induced by androgens.`,
      ` TRMPSS2-related gene fusions are highly specific to prostate cancer.`,
      ` All of the above`,
    ],
    optionFeedback: [``, ``, ``, ``, ``],
    optionStyleType: `st-lower-alpha`,
    answer: [4],
    ansText: `Rationale: Gene fusions, once thought to be the exclusive domain of hematologic malignancies, are common in prostate cancer and are fundamental drivers of prostate cancer growth and progression. The most commonly observed fusion results from the fusion of the 5’ untranslated end of TMPRSS2 serine protease to members of the ETS family of oncogenic transcription factors, bringing the latter growth-promoting genes under androgen control. The most common fusion identified in localized prostate cancer involves TMPRSS2 fused to ERG (ETS-related gene, 21q22.3) in approximately 50% of patients. The TMPRSS2 gene is prostate specific, and is expressed in both benign and malignant prostatic epithelium. TRMPSS-related gene fusions are highly specific for the presence of prostate cancer.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `Which of the following statements about androgens and the prostate are correct?`,
    q2: ``,
    q3: [],
    option: [
      `Testosterone is the primary androgen affecting prostate cell growth.`,
      `Higher circulating serum levels of androgens increase the risk of developing prostate cancer.`,
      `Men with hypogonadism never develop prostate cancer.`,
      `Exposure to androgens before or at puberty are necessary for the development of prostate cancer. `,
      `Type I 5 alpha reductase is the enzyme primarily responsible for converting T to DHT in the prostate. `,
    ],
    optionFeedback: [``, ``, ``, ``, ``],
    optionStyleType: `st-lower-alpha`,
    answer: [3],
    ansText: `Rationale: All of the other statements are false. DHT, derived from T by Type II 5 alpha reductase (not type I which is predominantly located in skin and liver), is the primary androgen that spurs prostate growth. Intraprostatic levels of androgens are tightly regulated by local mechanisms and are not affected by the level of circulating androgens. Hypogonadal men can develop prostate cancer, likely by pathways independent of androgens.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `Prostate tumors defined by mutations in the <i>SPOP</i> gene and overexpression of <i>SPINK1</i>:`,
    q2: ``,
    q3: [],
    option: [
      `May also contain ETS family gene fusions`,
      `Are frequently hypermethylated`,
      `Are more common in African American men`,
      `Are associated with lower Gleason scores `,
      ` Account for 25% of all prostate cancer.`,
    ],
    optionFeedback: [``, ``, ``, ``, ``],
    optionStyleType: `st-lower-alpha`,
    answer: [2],
    ansText: `Rationale: Tumors with SPOP mutations account for about 10% of primary prostate cancers and have average levels of methylation. A subclass of SPOP-mutated tumors that overexpress the <b><i>SPINK1</i></b> gene occur more commonly in African Americans and are associated with higher Gleason scores, and may in part underlie the increased incidence and mortality of prostate cancer in this group.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `Epigenetic mechanisms active in prostate cancer include:`,
    q2: ``,
    q3: [],
    option: [
      `chromatin remodeling`,
      `promoter hypo- and hypermethylation`,
      `microRNAs that lead to gene silencing`,
      `long noncoding RNAs `,
      `all of the above. `,
    ],
    optionFeedback: [``, ``, ``, ``, ``],
    optionStyleType: `st-lower-alpha`,
    answer: [4],
    ansText: `Rationale: Epigenetic events affect gene expression without altering the actual sequence of DNA, and in prostate cancer all of the listed mechanisms are important.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `Findings of the Selenium and Vitamin E Cancer Prevention Trial (SELECT) include:`,
    q2: ``,
    q3: [],
    option: [
      `A significant reduction in the incidence of prostate cancer in the combination arm`,
      `A significant effect of selenium and vitamin E on reducing the risk of cardiovascular disease and non-prostate malignancies.`,
      `A significant increased incidence of diabetes mellitus in the selenium arm.`,
      ` A reduction in prostate cancer–specific mortality`,
      `An increased risk of prostate cancer in those taking vitamin E alone `,
    ],
    optionFeedback: [``, ``, ``, ``, ``],
    optionStyleType: `st-lower-alpha`,
    answer: [4],
    ansText: `Rationale: SELECT demonstrated no beneficial effect of vitamin E or selenium on the risk of prostate cancer (alone or in combination). Hazard ratios for prostate cancer were 1.13 (99% CI: 0.95 to 1.13) for vitamin E, 1.04 (99% CI: 0.87 to 1.24) for selenium, and 1.05 (99% CI: 0.88 to 1.25) for selenium and vitamin E. A follow-up study that included an additional 54,464 person-years showed that dietary supplementation with vitamin E significantly increased the risk of prostate cancer among healthy men (HR 1.17; 95% CI: 1.004 to 1.36; <b><i>P</i></b> = 0.008).`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `In two large randomized controlled intervention trials (Prostate Cancer Prevention Trial [PCPT] and Reduction by Dutasteride of Prostate Cancer Events [REDUCE]), the use of 5ARIs in healthy men resulted in:`,
    q2: ``,
    q3: [],
    option: [
      `significant toxicity leading to high dropout rates`,
      `no improvement in symptoms related to benign prostatic hypertrophy (BPH)`,
      `an excess of high-grade cancers, leading to higher rates of prostate cancer–specific and all-cause mortality`,
      `higher rates of biopsy than those taking placebo `,
      ` a 25% reduction in the risk of being diagnosed with prostate cancer.`,
    ],
    optionFeedback: [``, ``, ``, ``, ``],
    optionStyleType: `st-lower-alpha`,
    answer: [4],
    ansText: `Rationale: Both these trials showed a significant reduction in the risk of being diagnosed with prostate cancer with drugs (finasteride and dutasteride) that were well tolerated and reduced both short- and long-term symptoms of BPH. Although there seemed to be an excess of high-grade cancers diagnosed in men who took these drugs, this had no effect on the risk of dying or dying specifically from prostate cancer. `,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
];
