var quiz = [
  {
    q: `Which statement is correct regarding the role of androgenic hormones in the etiology of benign prostatic hyperplasia (BPH)?`,
    q2: ``,
    q3: [],
    option: [
      `Testosterone and dihydrotestosterone (DHT) are the sole causes of the hyperplasia taking place in the prostate after the age of 40 years.`,
      `The total amount of androgen receptors in the prostate decreases with aging, leading to a lesser response to androgenic stimuli.`,
      `DHT is considered the more potent of the androgenic steroid hormones by a factor of approximately 10:1.`,
      `Of the two 5α-reductase isoforms, type 1 is most commonly found in the prostate. `,
      `Only testosterone produced in the testis and not in the adrenal gland enters into the prostate gland. `,
    ],
    optionFeedback: [``, ``, ``, ``, ``],
    optionStyleType: `st-lower-alpha`,
    answer: [2],
    ansText: `Rationale: The androgenic steroid hormones testosterone and DHT have a permissive role in the development of BPH but are not the sole cause. The androgen receptor remains at high levels in the prostate in aging men and specifically in BPH tissues, maintaining responsiveness to androgenic stimuli. The most common of the two 5α-reductase isoforms in the benignly enlarged prostate gland is type 2.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `Regarding genetic and familial factors in the etiology of BPH, which statement is TRUE?`,
    q2: ``,
    q3: [],
    option: [
      `There is no evidence that BPH is a familial disease.`,
      `Any man who has undergone transurethral resection of the prostate (TURP) should alert his sons that their chances of requiring TURP is three times greater than age-matched controls.`,
      `Cases of familial BPH tend to occur in men with smaller prostates than the sporadic cases of BPH.`,
      ` Approximately 50% of cases of BPH in men who undergo surgery when younger than the age of 60 years are estimated to be inheritable.`,
      ` The most likely inheritance pattern is autosomal recessive.`,
    ],
    optionFeedback: [``, ``, ``, ``, ``],
    optionStyleType: `st-lower-alpha`,
    answer: [3],
    ansText: `Rationale: There is significant evidence to suggest that some cases of BPH are familial, with autosomal dominant being the most likely inheritance pattern. An increased risk for BPH surgery exists mostly for men who come to BPH surgery when younger than the age of 60 years, and men with familial cases of BPH have larger glands than men with sporadic cases.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `The prevalence of a disease is defined as the number of:`,
    q2: ``,
    q3: [],
    option: [
      `diseased people per 100,000 population per year.`,
      `existing cases per 100,000 population at a distinct target date.`,
      `deaths per 100,000 population per year.`,
      ` deaths per number of diseased.`,
      `cumulative cases of a disease over a specified time period. `,
    ],
    optionFeedback: [``, ``, ``, ``, ``],
    optionStyleType: `st-lower-alpha`,
    answer: [1],
    ansText: `Rationale: When studying diseases by descriptive or analytical epidemiologic methods, it is important to have a good understanding of the definitions that apply. Most epidemiologic terms are expressed as rates, which are the number of cases for persons expressed over the population. The definitions that are of relevance are incidence rates, which are equal to the number of people/100,000 population/year getting a certain disease; prevalence, which is the number of existing cases of the disease of interest/100,000 at a distinct target date; mortality rate, which is the number of deaths/100,000 population/year; and fatality, which equals the number of deaths due to the disease/number of diseased people.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `Concerning the autopsy prevalence of BPH or stromoglandular hyperplasia of the prostate, which statement is correct?`,
    q2: ``,
    q3: [],
    option: [
      `No adequate studies have been done to date.`,
      `It is commonly found in men of all ages.`,
      `It is very uncommon in men younger than 30 years.`,
      ` It is found in 100% of men beginning at the age of 40 years.`,
      ` International comparisons are impossible because of a lack of its definition.`,
    ],
    optionFeedback: [``, ``, ``, ``, ``],
    optionStyleType: `st-lower-alpha`,
    answer: [2],
    ansText: `Rationale: The autopsy prevalence of BPH has been studied as early as 1984 by Berry and colleagues.<a href="[remark:b569eaa0fd404ed9a8213e525f8919d1]"><sup>a</sup></a> Since then, many studies have been done on virtually all continents in many ethnic groups. It is astonishing that these studies find a very significant agreement in terms of the actual prevalence of histologic BPH or stromoglandular hyperplasia around the world. Stromoglandular hyperplasia or BPH is very uncommon in men younger than the age of 30 years, but then increases steadily in an almost linear manner. In fact, approximately 90% of men in their 80s have evidence of stromoglandular hyperplasia.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `Which of the following statements regarding the International Prostate Symptom Score (IPSS) is TRUE?`,
    q2: ``,
    q3: [],
    option: [
      `Moderate symptom severity is defined as a score from 12 to 22 points.`,
      `The IPSS score addresses voiding and storage symptoms as well as questions regarding incontinence.`,
      `Quantitative symptom scores in BPH are not as important as are objective measures such as a flow rate recording.`,
      ` The IPSS score has been translated and validated in many languages.`,
      `Physicians and nurses may fill out the IPSS score for their patients after consultation. `,
    ],
    optionFeedback: [``, ``, ``, ``, ``],
    optionStyleType: `st-lower-alpha`,
    answer: [3],
    ansText: `Rationale: The IPSS symptom score is a seven-question, self-administered questionnaire that yields a total score ranging from 0 to 35 points. Men who score 0 to 7 points are classified as mildly symptomatic, those scoring from 8 to 19 points as moderately symptomatic, and those scoring from 20 to 35 points as severely symptomatic. The IPSS score addresses both voiding and storage, but not incontinence symptomatology. It is widely accepted that quantitative symptom scores are more important than, for example, urinary flow rate recordings. The IPSS score, the most widely utilized instrument, has been translated and culturally validated in many languages. Providers should abstain from filling in the questionnaire for their patients as it is validated as a self-reported symptom severity instrument.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `Which statement is TRUE regarding prostate volume?`,
    q2: ``,
    q3: [],
    option: [
      `International studies show significant similarity in prostate volume in white, age-stratified men.`,
      `Prostate volume assessment by digital rectal examination (DRE) is reproducible across examiners.`,
      `Although there is a steady increase in total prostate volume with age, the transition zone volume increases only marginally.`,
      ` Magnetic resonance imaging (MRI) measurements are, in general, smaller compared with transrectal ultrasound measurements.`,
      `DRE estimation of prostate volume is fairly accurate when done by an experienced urologist. `,
    ],
    optionFeedback: [``, ``, ``, ``, ``],
    optionStyleType: `st-lower-alpha`,
    answer: [0],
    ansText: `Rationale: Prostate volume can relatively easily be assessed by transrectal ultrasonography (TRUS). TRUS has been found to be a reliable measure that is reproducible across examiners, in contrast to DRE, which is only poorly reproducible. MRI is very expensive and it yields in general a larger volume compared with TRUS measurements. Of note is the fact that international studies show significant similarity in regard to total and transitional zone prostate volume in white, age-stratified men.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `Concerning liver disease and BPH, which of the following statements is TRUE?`,
    q2: ``,
    q3: [],
    option: [
      `Ethanol consumption increases circulating levels of estrogens.`,
      `The risk of having surgery for BPH is increased in heavy drinkers.`,
      `The intake of ethanol can decrease serum testosterone levels by a variety of mechanisms.`,
      `Most autopsy studies find a higher prevalence of BPH in men with liver cirrhosis. `,
      `In men with liver disease, histologic specimens of the prostate show a similar influence of estrogen such as seen in hormonally treated prostate cancer. `,
    ],
    optionFeedback: [``, ``, ``, ``, ``],
    optionStyleType: `st-lower-alpha`,
    answer: [2],
    ansText: `Rationale: It is known that alcohol intake may decrease plasma testosterone levels by reducing production of and increasing clearance of testosterone. However, despite this hypothetical reason for a lower incidence, an inverse relationship has been described. The age-adjusted multivariate relative risks for undergoing surgery for BPH in men drinking more than three or four glasses of alcohol per day is lower than in age-matched controls. Of course, this could be due to a bias against surgery in patients who are heavy drinkers and therefore in poor health. It is interesting to note, however, that in the majority of studies, namely, four of five, a lower prevalence of BPH is found in men with cirrhosis compared with those without cirrhosis.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `How do medications influence symptoms and flow rate?`,
    q2: ``,
    q3: [],
    option: [
      `There is no documented influence of any medication on symptoms or flow rate.`,
      `Antihistamines and bronchodilators significantly decrease urinary flow rates.`,
      `Calcium channel blockers and β-adrenergic blockers reduce urinary flow rates significantly.`,
      ` Antidepressants, antihistamines, and bronchodilators increase the symptom score by several points.`,
      ` Anticholinergic agents decrease the peak urinary flow rate markedly.`,
    ],
    optionFeedback: [``, ``, ``, ``, ``],
    optionStyleType: `st-lower-alpha`,
    answer: [3],
    ansText: `Rationale: There is only one study that systematically assessed the effect of medications on urinary symptoms and flow rate. Cold medications containing α-sympathomimetics tend to exacerbate lower urinary tract symptoms by the expected effect on the smooth muscle of the bladder outlet. Data from the Olmsted County Study of Urinary Symptoms and Health Status Among Men show that daily use of antidepressants, antihistamines, or bronchodilators is associated with a 2- to 3-point increase in the symptom score. However, only the daily use of antidepressants is associated with a decrease in the age-adjusted urinary flow rate.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `Concerning correlations between baseline parameters, which statement is TRUE?`,
    q2: ``,
    q3: [],
    option: [
      `A clinically useful correlation exists between prostate volume and serum prostate-specific antigen (PSA) level.`,
      `Many studies have shown a significant correlation between the transition zone volume and symptom severity.`,
      `Correlation of symptoms, bother, interference, and quality of life are poor.`,
      ` Urinary flow rate and prostate volume correlate highly with serum PSA level.`,
      `Serum PSA level shows a strong correlation with symptom frequency and bother. `,
    ],
    optionFeedback: [``, ``, ``, ``, ``],
    optionStyleType: `st-lower-alpha`,
    answer: [0],
    ansText: `Rationale: In general there is an absence of useful baseline correlations between subjective and objective parameters such as symptoms, frequency, quality of life, and urinary flow rate measures of obstruction and prostate volume. However, symptom, bother, and interference with quality of life show excellent correlation with each other, and a clinically useful correlation exists between total and transition zone prostate volume and serum PSA in men with BPH.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `Which statement is correct regarding the study of the natural history of BPH?`,
    q2: ``,
    q3: [],
    option: [
      `Placebo groups from treatment trials are useful because they do not have treatment biases.`,
      `A longitudinal population-based study has the fewest biases and is the most useful type of study.`,
      `Control groups from intervention or medical therapy trials reflect the natural history of the disease in unselected community-dwelling men.`,
      `Placebo groups have fewer selection biases compared with population-based studies. `,
      `No such studies have been conducted. `,
    ],
    optionFeedback: [``, ``, ``, ``, ``],
    optionStyleType: `st-lower-alpha`,
    answer: [1],
    ansText: `Rationale: There are several ways to study the natural history of BPH. One can look at watchful waiting cohorts or placebo-controlled groups of medication trials, or study population-based groups of men longitudinally over time. The latter is clearly the best way of studying the natural history of the disease because it incurs the fewest biases. However, it is also the most tedious and most expensive method. Placebo groups in medication trials clearly suffer from enrollment biases but do provide useful information.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `Regarding the magnitude of the placebo response and its perception, which of the following statements is TRUE?`,
    q2: ``,
    q3: [],
    option: [
      `Placebo response is not dependent on the baseline severity score.`,
      `Most patients report subjective improvement when the drop from baseline is 30%.`,
      `The higher the baseline score, the more of a drop is required for patients to subjectively feel improved.`,
      ` Perception of improvement is independent of baseline score.`,
      `There are convincing data to demonstrate that the final score after treatment is more important than the baseline score or the drop from baseline. `,
    ],
    optionFeedback: [``, ``, ``, ``, ``],
    optionStyleType: `st-lower-alpha`,
    answer: [2],
    ansText: `Rationale: The placebo response is partially a regression to the mean and partially an effect induced by the interaction between patient and doctor. The response is clearly dependent on the baseline severity score, with patients’ higher scores having a larger decrease from baseline. The perception of subjective improvement has been shown to be dependent on the drop from baseline as well as on the baseline itself. For example, the higher the baseline score, the more of a drop from baseline is required for patients to have a subjective perception of improvement. Overall, a 3-point decrease is associated with a subjective perception of improvement.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `Descriptive studies of the incidence rates of acute urinary retention (AUR) have demonstrated that:`,
    q2: ``,
    q3: [],
    option: [
      `depending on the population studied, incidence rates less than 5 to more than 130 cases/1000 man-years have been reported.`,
      `the incidence rates reported do not differ significantly between various studies and populations.`,
      `AUR has been poorly defined, and therefore no incidence rate can be calculated.`,
      ` incidence rates of approximately 10/1000 man-years have been reported in all watchful waiting studies.`,
      ` incidence rates of AUR have not been reported in the urologic literature, only prevalence rates.`,
    ],
    optionFeedback: [``, ``, ``, ``, ``],
    optionStyleType: `st-lower-alpha`,
    answer: [0],
    ansText: `Rationale: AUR has been studied during the past few years in population-based studies as well as in placebo-control groups from long-term treatment trials. The incidence rates differ significantly between different studies because of the inclusion and exclusion criteria and selection biases. Fortunately, AUR is a very clearly defined outcome and, thus, incidence rates can easily be calculated and compared.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `What is the most significant finding regarding analytical epidemiology of AUR?`,
    q2: ``,
    q3: [],
    option: [
      `Serum PSA level is a more powerful predictor of AUR than is age.`,
      `Serum PSA level and prostate volume have limited ability to predict episodes of AUR.`,
      `Urinary flow rates in placebo control groups are strong predictors of AUR episodes.`,
      ` Age has been found to be the most significant risk factor for AUR in population-based studies.`,
      `There is virtually no relationship between symptom frequency and bother and AUR episodes. `,
    ],
    optionFeedback: [``, ``, ``, ``, ``],
    optionStyleType: `st-lower-alpha`,
    answer: [3],
    ansText: `Rationale: In population-based studies such as the Olmsted County Study of Urinary Symptoms and Health Status Among Men, age is the most significant predictor of AUR. Data from placebo groups of long-term medical treatment trials demonstrate that serum PSA is the most powerful predictor of AUR together with prostate volume. Although this appears on the surface to be a contradiction, it can be relatively easily explained by the fact that in BPH treatment trials, elderly men with already an existing diagnosis of BPH are enrolled. Thus, age plays a lesser factor in terms of predicting AUR. In population-based studies in which men stratified by age are followed during long periods of time, age plays a more significant factor compared with PSA.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `Which statement regarding surgery for BPH is TRUE?`,
    q2: ``,
    q3: [],
    option: [
      `The incidence rates of surgery are similar across wide geographic regions and ethnic backgrounds.`,
      `AUR is a harder and more objective end point compared to surgery.`,
      `Surgery is a less common end point compared with AUR.`,
      ` Most patients with BPH eventually require surgery for their condition.`,
      ` Surgery rates for BPH have remained stable since approximately 1990.`,
    ],
    optionFeedback: [``, ``, ``, ``, ``],
    optionStyleType: `st-lower-alpha`,
    answer: [1],
    ansText: `Rationale: Incidence rates of surgery vary significantly across geographic regions and patients with different ethnic backgrounds. Depending on the interaction between patient and physician, the physician can convince the patient to undergo surgery or, based on the patient’s comorbidities, talk him out of surgery. The same cannot be said for urinary retention. It is clear that a vast majority of patients do not require surgery in the course of their disease but, rather, can be treated effectively with reassurance alone or medication.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
];
