var quiz = [
  {
    q: `When managed with radiation alone, patients with high-risk prostate cancer have a 5-year prostate-specific antigen (PSA) failure-free survival rate of approximately:`,
    q2: ``,
    q3: [],
    option: [
      `<!--a. -->75%.`,
      `<!--b. -->60%.`,
      `<!--c. -->33%.`,
      `<!--d. -->10%.`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [2],
    ansText: `Rationale: (see D’Amico AV, Whittington R, Malkowicz S, et al: Biochemical outcome after radical prostatectomy, external beam radiation therapy, or interstitial radiation therapy for clinically localized prostate cancer. <b><i>JAMA</i></b> 280:969–974, 1998.) `,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
    type: `MCSS`,
  },
  {
    q: `Which of the following represents unfavorable intermediate-risk disease?`,
    q2: ``,
    q3: [],
    option: [
      `<!--a. -->Gleason 3 + 4, PSA 9.5, cT2a`,
      `<!--b. -->Gleason 4 + 3, PSA 9.5, cT3a`,
      `<!--c. -->Gleason 4 + 4, PSA 9.5, cT1c`,
      `<!--d. -->Gleason 4 + 3, PSA 12.8, cT2a`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [3],
    ansText: `Rationale: (see Zumsteg ZS, Spratt DE, Pei I, et al: A new risk classification system for therapeutic decision making with intermediate-risk prostate cancer patients undergoing dose-escalated external-beam radiation therapy. <b><i>Eur Urol</i></b> S0302-2838[13]00257-1, 2013.)`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
    type: `MCSS`,
    type: `MCSS`,
    type: `MCSS`,
    type: `MCSS`,
  },
  {
    q: `A 58-year-old man presents with a T2b, Gleason 7 (4 + 3: 80% pattern 4, 2/6 sextants positive, 4/10 cores), PSA 7.8 ng/mL. He is treated with 6 months combined androgen deprivation therapy (ADT) + 78 Gy intensity-modulated radiation therapy (IMRT). Testosterone recovers 6 months following completion of IMRT. At 12 months, PSA is 0.8 ng/mL; at 18 months, 2.6 ng/mL; at 24 months, 3.2 ng/mL; and now at 30 months, following IMRT, PSA is 5.4 ng/mL. The best next step in management is:`,
    q2: ``,
    q3: [],
    option: [
      `<!--a. -->because the most likely explanation for the rising PSA is testosterone recovery, reassure the patient and continue to follow up.`,
      `<!--b. -->arrange biopsy for presumed local failure.`,
      `<!--c. -->because patient clearly has failed radiotherapy, advise radical local salvage.`,
      `<!--d. -->because patient’s PSA doubling time and time to biochemical failure make him an unlikely candidate for local salvage because they are indicative of systemic failure, arrange systemic staging with or without multiparametric magnetic resonance imaging (MRI) of the prostate.`,
      "<!--e. -->The PSA kinetics are compatible with a benign increase or “bounce.” Reassure the patient and continue to monitor.",
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [3],
    ansText: `Rationale: This PSA increase is much too high to be due to testosterone recovery. Because this patient was treated with IMRT and not brachytherapy, this is not a benign increase. A 58-year-old man should not be denied potentially curative salvage, but his PSA kinetics are strongly suggestive of distant failure. Although ADT may well be the correct maneuver, systemic staging should be undertaken first. <b>A posttreatment biopsy of the prostate should be interpretable 30 months after completion of treatment, but even if residual disease is demonstrated, this patient is at very high risk of also harboring systemic disease because of his PSA kinetics and should fully understand this before consenting to further local treatment.</b>`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `A 53-year-old man presents with T2a, Gleason 7 (3 + 4: 20% pattern 4, 1/6 sextants positive, 2/10 cores), PSA 5.9 ng/mL. He is treated with iodine-125 (<sup>125</sup>I) permanent seed prostate brachytherapy. At 12 months, PSA has fallen to 1.2 ng/mL. At 15 months, PSA is 1.8 ng/mL; at 18 months, it is 3.2 ng/mL. He is sexually active and asymptomatic. Which is the best next step?`,
    q2: ``,
    q3: [],
    option: [
      `<!--a. -->Brachytherapy has failed. Start ADT.`,
      `<!--b. -->Brachytherapy has failed. Arrange radical local salvage.`,
      `<!--c. -->Brachytherapy has failed. Arrange biopsy before radical local salvage.`,
      `<!--d. -->Recognizing that this is classic timing for a benign PSA bounce, contact his radiation oncologist, review the dosimetry of the implant, and continue to monitor the PSA every 3 months, planning for eventual biopsy if the PSA has not started to decline again by 30 months.`,
      `<!--e. -->Given his time to nadir of 12 months and PSA doubling time of 4 months, explain to the patient that this is almost certainly distant failure and discuss timing of ADT.`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [3],
    ansText: `Rationale: <b>This is classic timing for a benign PSA bounce after brachytherapy monotherapy</b>. Bounces are seen in 65% of men younger than 55 years, especially those who are sexually active, and can be quite dramatic, with kinetics characteristic of distant failure because of the early onset and rapid doubling. <b>Reassurance, close monitoring, biopsy if the bounce has not resolved by 30 months, and systemic staging if the PSA approaches 10 ng/mL are appropriate.</b>`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `In two large trials that randomized patients with high-risk and locally advanced prostate cancer to ADT with versus without radiation therapy, the addition of radiation improved what outcome by an absolute of 8% to 10%?`,
    q2: ``,
    q3: [],
    option: [
      `<!--a. -->Biochemical recurrence-free survival`,
      `<!--b. -->Clinical recurrence-free survival`,
      `<!--c. -->Metastasis-free survival`,
      `<!--d. -->Disease-specific survival`,
      `<!--e. -->Overall survival`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [4],
    ansText: `Rationale: In the NCIC/MRC trial of 1205 patients, the addition of radiation therapy significantly improved overall survival: 7-year survival 66% for ADT versus 74% ADT/RT (<b><i>P</i></b> = .033). In a Scandinavian trial (SPCG-7/SFUO-3) of 875 patients, radiation therapy decreased overall mortality: 10-year mortality was 39.4% for ADT versus 29.6% for ADT/RT (<b><i>P</i></b> &lt; .05).`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
    type: `MCSS`,
    type: `MCSS`,
  },
  {
    q: `Modern radiation therapy for prostate cancer differs from the technology used in the 1980s to 1990s in what ways? Modern radiation uses:`,
    q2: ``,
    q3: [],
    option: [
      `<!--a. -->computed tomography (CT)-based treatment planning.`,
      `<!--b. -->intensity-modulated radiation delivery.`,
      `<!--c. -->image guidance.`,
      `<!--d. -->dose-escalated radiation.`,
      `<!--e. -->all of the above.`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [4],
    ansText: `Rationale: CT-based treatment planning was developed in the 1990s, IMRT in the early 2000s, and image guidance more recently. Four randomized trials consistently demonstrated improved cancer control with “dose-escalated” radiation, which has changed the standard of care in prostate cancer radiation.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `A randomized trial comparing 76 Gy in 38 fractions to 70.2 Gy in 26 fractions found:`,
    q2: ``,
    q3: [],
    option: [
      `<!--a. -->the shorter regimen improved 5-year biochemical failure and had comparable rectal and urinary toxicity.`,
      `<!--b. -->the shorter regimen improved 5-year biochemical failure and had higher late urinary toxicity.`,
      `<!--c. -->the shorter regimen improved 5-year biochemical failure and had higher late rectal toxicity.`,
      `<!--d. -->the shorter regimen did not improve 5-year biochemical failure and had higher late urinary toxicity in men with poor baseline urinary function.`,
      `<!--e. -->the shorter regimen did not improve 5-year biochemical failure and had higher late rectal toxicity.`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [3],
    ansText: `Rationale: (See Pollack A, Walker G, Buyyounouski MK, et al: Five year results of a randomized external beam radiotherapy hypofractionation trial for prostate cancer. <b><i>Int J Radiat Oncol Biol Phys</i></b> 81[2]:S1, 2011.)`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `In 2013, radium-223 was approved by the U.S. Food and Drug Administration (FDA) for use in the treatment of men with ________ because of a prolongation in ________.`,
    q2: ``,
    q3: [],
    option: [
      `<!--a. -->castrate-resistant metastatic prostate cancer, overall survival`,
      `<!--b. -->castrate-resistant metastatic prostate cancer, disease-free survival`,
      `<!--c. -->castrate-resistant nonmetastatic prostate cancer, overall survival`,
      `<!--d. -->castrate-resistant metastatic prostate cancer, PSA failure–free survival`,
      `<!--e. -->castrate-resistant nonmetastatic prostate cancer, PSA failure–free survival`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [0],
    ansText: `Rationale: (See Parker C, Nilsson S, Heinrich D, et al: ALSYMPCA Investigators. Alpha emitter radium-223 and survival in metastatic prostate cancer. <b><i>N Engl J Med.</i></b> 369[3]:213–223, 2013.)`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
    type: `MCSS`,
  },
  {
    q: `<b>Imaging</b><br/><br/>A voiding cystourethrogram on a 72-year-old man who presents with urinary tract infections 2 years after combination external beam radiation therapy and brachytherapy for prostate cancer is depicted in <a class="lightboxcallout" img-ref="image_fig_157_1" href="5ac004e9b57e4d548b4b1c5a8d6d87ae">Fig. 157.1</a>. The most likely diagnosis is:`,
    q2: ``,
    q3: [],
    option: [
      `<!--a. -->brachytherapy seed migration.`,
      `<!--b. -->urethra rectal fistula.`,
      `<!--c. -->vesico sigmoid fistula.`,
      `<!--d. -->urethra cutaneous fistula.`,
      `<!--e. -->vesico rectal fistula.`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [1],
    ansText: `Rationale: There is partial opacification of the irregular prostatic urethra with immediate filling of the rectum. The bladder is normal in appearance, making option e incorrect. The contrast is in the rectum, making a urethra cutaneous fistula and vesico sigmoid fistula incorrect. The seeds are located in the area one would expect following brachytherapy.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
    type: `MCSS`,
  },
];
