var quiz = [
  {
    q: `What is the arterial blood supply to the prostate? `,
    q2: ``,
    q3: [],
    option: [
      ` The pudendal artery.`,
      ` The superior vesical artery.`,
      ` The inferior vesical artery.`,
      `The external iliac artery. `,
      `The obturator artery. `,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [2],
    ansText: `Rationale: The prostate receives arterial blood supply from the inferior vesical artery. `,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `What vessels are located in the neurovascular bundle? `,
    q2: ``,
    q3: [],
    option: [
      ` Capsular arteries and veins.`,
      `Pudendal artery and vein. `,
      ` Hemorrhoidal artery and vein.`,
      `Santorini plexus. `,
      ` Accessory pudendal artery.`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [0],
    ansText: `Rationale: <b>The capsular branches run along the pelvic sidewall in the lateral pelvic fascia posterolateral to the prostate, providing branches that course ventrally and dorsally to supply the outer portion of the prostate.</b> Histologically, the capsular arteries and veins are surrounded by an extensive network of nerves. These capsular vessels provide the macroscopic landmark that aids in the identification of the microscopic branches of the pelvic plexus that innervate the corpora cavernosa. `,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: ` A radical prostatectomy may compromise the arterial blood supply to the penis by injuring the aberrant blood supply from which artery?`,
    q2: ``,
    q3: [],
    option: [
      ` The obturator artery.`,
      ` The inferior vesical artery.`,
      ` The superior vesical artery.`,
      ` The penile artery.`,
      ` All of the above.`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [4],
    ansText: `Rationale: The major arterial supply to the corpora cavernosa is derived from the internal pudendal artery. <b>However, pudendal arteries can arise from the obturator, inferior vesical, and superior vesical arteries. Because these aberrant branches travel along the lower part of the bladder and anterolateral surface of the prostate, they are divided during radical prostatectomy. This may compromise arterial supply to the penis, especially in older patients with borderline penile blood flow.</b> `,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `The main parasympathetic efferent innervation to the pelvic plexus arises from: `,
    q2: ``,
    q3: [],
    option: [` S1.`, ` S2 to S4.`, ` T11 to L2.`, ` L3 to S1.`, ` T5 to T8.`],
    optionStyleType: `st-lower-alpha`,
    answer: [1],
    ansText: `Rationale: The autonomic innervation of the pelvic organs and external genitalia arises from the pelvic plexus, which is formed by parasympathetic visceral efferent preganglionic fibers that arise from the sacral center (S2 to S4).`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: ` What is the relationship of the neurovascular bundle to the prostatic fascia?`,
    q2: ``,
    q3: [],
    option: [
      `Inside Denonvilliers fascia. `,
      ` Outside the lateral pelvic fascia.`,
      ` Inside the prostatic fascia.`,
      ` Between the layers of the prostatic fascia and the levator fascia.`,
      `Both inside and outside the prostatic fascia. `,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [3],
    ansText: `Rationale: The neurovascular bundles are located in the lateral pelvic fascia between the prostatic and levator fasciae. `,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: ` Which anatomic structure is responsible for the maintenance of passive urinary control after radical prostatectomy?`,
    q2: ``,
    q3: [],
    option: [
      `Bladder neck. `,
      ` Levator ani musculature.`,
      `Preprostatic sphincter. `,
      `Striated urethral sphincter. `,
      `Bulbar urethra. `,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [3],
    ansText: `Rationale: The striated sphincter contains fatigue-resistant, slow-twitch fibers that are responsible for passive urinary control. `,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: ` What is the major nerve supply to the striated sphincter and levator ani?`,
    q2: ``,
    q3: [],
    option: [
      `The neurovascular bundle. `,
      `The sympathetic fibers from T11 to L2. `,
      `The pudendal nerve. `,
      ` The obturator nerve.`,
      ` The accessory pudendal nerve.`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [2],
    ansText: `Rationale: The pudendal nerve provides the major nerve supply to the striated sphincter and levator ani. `,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `What is the posterior extent of the pelvic lymph node dissection? `,
    q2: ``,
    q3: [],
    option: [
      `The hypogastric vein. `,
      `The obturator nerve. `,
      ` The obturator vessels.`,
      ` The sacral foramen.`,
      ` The pelvic sidewall musculature.`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [0],
    ansText: `Rationale: The obturator artery and vein are skeletonized but are usually left undisturbed and are not ligated unless excessive bleeding occurs. The dissection then continues down to the pelvic floor, exposing the hypogastric veins. `,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `In opening the endopelvic fascia, there are often small branches traveling from the prostate to the pelvic sidewall. These branches are tributaries from the: `,
    q2: ``,
    q3: [],
    option: [
      `Obturator artery. `,
      ` External iliac artery.`,
      ` Inferior vesical artery.`,
      ` Pudendal artery and veins.`,
      `Neurovascular bundle. `,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [3],
    ansText: `Rationale: The incision in the endopelvic fascia is carefully extended in an anteromedial direction toward the puboprostatic ligaments. At this point, one often encounters small arterial and venous branches from the pudendal vessels, which perforate the pelvic musculature to supply the prostate. These vessels should be ligated with clips to avoid coagulation injury to the pudendal artery and nerve, which are located just deep to this muscle as they travel along the pubic ramus. `,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: ` How extensively should the puboprostatic ligaments be divided?`,
    q2: ``,
    q3: [],
    option: [
      ` Superficially, with just enough incised to expose the junction between the anterior apex of the prostate and the dorsal vein complex.`,
      ` Extensively, down to the pelvic floor, including the pubourethral component.`,
      `Not at all; the puboprostatic ligaments should be left intact. `,
      ` Widely enough to permit a right angle to be placed around the dorsal vein complex.`,
      `Not at all; the puboprostatic ligaments do not need to be divided to perform a radical prostatectomy. `,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [0],
    ansText: `Rationale: The dissection should continue down far enough to expose the juncture between the apex of the prostate and the anterior surface of the dorsal vein complex at the point where it will be divided. The pubourethral component of the complex must remain intact to preserve the anterior fixation of the striated urethral sphincter to the pubis.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: ` When the dorsal vein complex is divided anteriorly, what is the most common major structure that can be damaged, and what is the most common adverse outcome?`,
    q2: ``,
    q3: [],
    option: [
      ` Aberrant pudendal arteries; impotence.`,
      ` Neurovascular bundle; impotence.`,
      `Striated urethral sphincter; incontinence. `,
      ` Levator ani musculature; incontinence.`,
      ` Both a and b.`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [2],
    ansText: `Rationale: The goal is to divide the complex with minimal blood loss while avoiding damage to the striated sphincter.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `What is the most common site for a positive surgical margin and when does this occur? `,
    q2: ``,
    q3: [],
    option: [
      `Posterolateral; during release of the neurovascular bundle. `,
      ` Posterior; when the prostate is dissected from the rectum.`,
      `Apex; during division of the striated urethral sphincter-dorsal vein complex. `,
      ` Bladder neck; during separation of the prostate from the bladder.`,
      ` Seminal vesicles.`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [2],
    ansText: `Rationale: The exact plane on the anterior surface of the prostate can be visualized, avoiding inadvertent entry into the anterior prostate and ensuring minimal excision of the striated sphincter musculature. This is the most common site for positive surgical margins because it can be difficult to identify the anterior apical surface of the prostate. `,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: ` How should the back-bleeders from the dorsal vein complex on the anterior surface of the prostate be oversewn and why?`,
    q2: ``,
    q3: [],
    option: [
      `The edges should be pulled together in the midline to avoid bleeding. `,
      ` Bunching sutures should be used to avoid excising too much striated sphincter.`,
      `The edges should be oversewn in the shape of a V to avoid advancing the neurovascular bundles too far anteriorly on the prostate. `,
      ` They should be oversewn horizontally to avoid a positive surgical margin.`,
      ` Oversewing the proximal dorsal vein complex is not required.`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [2],
    ansText: `Rationale: To avoid back-bleeding from the anterior surface of the prostate, the edges of the proximal dorsal vein complex on the anterior surface of the prostate are sewn in the shape of a V with a running 2-0 absorbable suture. If one tries to pull these edges together in the midline, the neurovascular bundles can be advanced too far anteriorly on the prostate. `,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: ` After the dorsal vein complex has been ligated and the urethra has been divided, what posterior structure, other than the neurovascular bundles, attaches the prostate to the pelvic floor?`,
    q2: ``,
    q3: [],
    option: [
      `Rectourethralis. `,
      ` Denonvilliers fascia.`,
      ` Rectal fascia.`,
      ` Posterior portion of the striated sphincter complex.`,
      ` Neurovascular bundles.`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [3],
    ansText: `Rationale: The posterior band of urethra is now divided to expose the posterior portion of the striated urethral sphincter complex. The posterior sphincter complex is composed of skeletal muscle and fibrous tissue. `,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `What are the advantages of releasing the levator fascia higher at the apex (more than one answer may be correct)? `,
    q2: ``,
    q3: [],
    option: [
      `More soft tissue on the prostate. `,
      `Less traction on the neurovascular bundles as they are released. `,
      ` Preservation of anterior nerve fibers.`,
      ` Less blood loss.`,
      `Better visualization of the location of the cancer. `,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [1, 2],
    ansText: ``,
    state: `notAnswered`,
    userAnswered: [],
  },
  {
    q: `Once the apex of the prostate has been released, what is the best way to retract the prostate for exposure of the neurovascular bundle? `,
    q2: ``,
    q3: [],
    option: [
      ` Traction on the catheter, producing upward rotation of the apex of the prostate.`,
      ` Use of a sponge stick to roll the prostate on its side.`,
      `Downward displacement of the prostate with a sponge stick. `,
      `Use of finger dissection to release the prostate posteriorly. `,
      `Dissection with the sucker. `,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [1],
    ansText: `Rationale: When the surgeon releases the neurovascular bundle, there should be no upward traction on the prostate. Rather, the prostate should be rolled from side to side.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `To avoid a positive surgical margin, what is the best way to release the neurovascular bundle? `,
    q2: ``,
    q3: [],
    option: [
      `Right-angle dissection beginning on the posterior surface of the prostate and dissecting anterolaterally. `,
      ` With sharp dissection, laterally dissecting toward the rectum.`,
      `With finger dissection to fracture the neurovascular bundle from the prostate. `,
      ` With electrocautery to separate the neurovascular bundle from the prostate.`,
      `Elevation of the prostate with traction on the Foley catheter. `,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [0],
    ansText: `Rationale: After the plane between the rectum and prostate in the midline has been developed, it is possible to release the neurovascular bundle from the prostate, beginning at the apex and moving toward the base, by using the sponge stick to roll the prostate over on its side. Beginning on the rectal surface, the bundle is released from the prostate by spreading a right angle gently. With use of this plane, Denonvilliers fascia and the prostatic fascia remain on the prostate; only the residual fragments of the levator fascia are released from the prostate laterally.  `,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: ` What is the latest point at which a decision can be made regarding preservation or excision of the neurovascular bundle?`,
    q2: ``,
    q3: [],
    option: [
      ` When perineural invasion is identified on the needle biopsy specimen.`,
      ` When the neurovascular bundle is being released from the prostate and fixation is identified.`,
      ` When the prostate has been removed and tissue covering the posterolateral surface of the prostate is thought to be inadequate.`,
      ` When the patient is found to have a positive biopsy result at the apex.`,
      ` When the Partin tables indicate a greater than 50% chance of extraprostatic extension.`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [2],
    ansText: `Rationale: <b>Clues that indicate that wide excision of the neurovascular bundle is necessary include inadequate tissue covering the posterolateral surface of the prostate once the prostate has been removed, leading to secondary wide excision of the neurovascular bundle.</b> This last point is important to understand. The surgeon does not have to make the decision about whether to excise or preserve the neurovascular bundle until the prostate is removed, and, if there is not enough soft tissue covering the prostate, one can excise the neurovascular bundle then. `,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: ` Before the lateral pedicles are divided, what is the last major branch of the neurovascular bundle that must be identified and released?`,
    q2: ``,
    q3: [],
    option: [
      `Apical branch. `,
      ` Posterior branch.`,
      `Capsular branch. `,
      ` Bladder neck branch.`,
      ` Seminal branch.`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [2],
    ansText: `Rationale: The surgeon should look for a prominent arterial branch traveling from the neurovascular bundle over the seminal vesicles to supply the base of the prostate. This posterior vessel should be ligated on each side and divided. By this method, the neurovascular bundles are no longer tethered to the prostate and fall posteriorly. `,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `When the vesicourethral anastomosis sutures are being tied, if tension is found, what is the best way to release it? `,
    q2: ``,
    q3: [],
    option: [
      `Creating an anterior bladder neck flap. `,
      ` Placing the Foley catheter on traction postoperatively.`,
      ` Releasing attachments of the bladder to the peritoneum.`,
      ` Using vest sutures.`,
      ` Releasing the urethra from the pelvic floor.`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [2],
    ansText: `Rationale: The anterior suture is tied initially. There should be no tension. If there is, the bladder should be released from the peritoneum.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: ` If there is excessive bleeding from the dorsal vein complex while it is being divided, what should be done?`,
    q2: ``,
    q3: [],
    option: [
      ` Abandon the operation and close the incision.`,
      ` Ligate the hypogastric arteries.`,
      ` Inflate a Foley balloon and place traction on it.`,
      `Divide the dorsal vein complex completely over the urethra and oversew the end. `,
      ` Deflate the Foley catheter.`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [3],
    ansText: `Rationale: <b>If there is troublesome bleeding from the dorsal vein complex at any point, the surgeon should completely divide the dorsal vein complex over the urethra and oversew the end.</b> This is the single best means to control bleeding from the dorsal vein complex. Any maneuver short of this will only worsen the bleeding. To gain exposure for the prostatectomy, one must put traction on the prostate. If the dorsal vein is not completely divided, traction opens the partially transected veins and usually worsens the bleeding.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: ` If a rectal injury occurs during the operation, the most appropriate next step is:`,
    q2: ``,
    q3: [],
    option: [
      `To create a loop colostomy. `,
      `To create an end colostomy. `,
      ` To create a Hartman pouch.`,
      ` To ensure interposition of the omentum following repair of the injury.`,
      `To repair the rectal injury in two layers. `,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [3],
    ansText: `Rationale: It is wise to interpose omentum between the rectal closure and the vesicourethral anastomosis to reduce the possibility of a rectourethral fistula.  `,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: ` In postoperative patients who require transfusions of blood for hypotension, the best approach is to:`,
    q2: ``,
    q3: [],
    option: [
      `Avoid re-exploration because it might damage the anastomosis. `,
      `Perform re-exploration. `,
      `Place the Foley catheter on traction. `,
      ` Administer fresh frozen plasma.`,
      ` Serially monitor the patient in an intensive care unit setting.`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [1],
    ansText: `Rationale: <b>Our findings suggest that patients requiring acute transfusions for hypotension after radical prostatectomy should undergo exploration to evacuate the pelvic hematoma in an effort to decrease the likelihood of bladder neck contracture and incontinence.</b> `,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: ` What is the best way to ensure good coaptation of the anastomotic mucosal surfaces to avoid a bladder neck contracture?`,
    q2: ``,
    q3: [],
    option: [
      `Hold the catheter on traction while tying the sutures. `,
      ` Use a sponge stick in the perineum.`,
      `Use a Babcock clamp to hold the bladder down. `,
      ` Use vest sutures.`,
      ` Evert the bladder mucosa.`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [2],
    ansText: `Rationale: We have found that the use of a Babcock clamp to approximate the bladder neck and urethra while the anastomotic sutures are tied has virtually eliminated bladder neck contractures in our practice.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: ` What is the most common cause of incontinence after radical prostatectomy?`,
    q2: ``,
    q3: [],
    option: [
      `Intrinsic sphincter deficiency. `,
      ` Detrusor instability.`,
      `Failure to reconstruct the bladder neck. `,
      ` Injury to the neurovascular bundles.`,
      `Bladder neck contracture. `,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [0],
    ansText: `Rationale: After radical prostatectomy, incontinence is usually secondary to intrinsic sphincter deficiency. `,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `Preservation of the seminal vesicles during radical prostatectomy has demonstrated: `,
    q2: ``,
    q3: [],
    option: [
      `Improved erectile function in most men. `,
      ` No increase in biochemical recurrence.`,
      ` Improved early and late urinary control.`,
      `Increased rate of pelvic abscess. `,
      `None of the above. `,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [4],
    ansText: `Rationale: Sparing of the seminal vesicles has not improved incontinence, potency, or margin status, and there have been no reported cases of pelvic abscess. `,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: ` Preservation of the bladder neck during radical prostatectomy has demonstrated:`,
    q2: ``,
    q3: [],
    option: [
      `Improved erectile function. `,
      ` Improved long-term urinary control.`,
      `Decreased surgical margins. `,
      ` Improved anastomotic stricture rate.`,
      ` None of the above.`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [4],
    ansText: `Rationale: 
        <!--<b>e. None of the above.</b>--> <b>Sparing of the bladder neck has not improved incontinence, potency, margin status, or stricture rates.</b> `,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: ` What percentage of men who had bilateral sural nerve grafting demonstrated full erections capable of penetration?`,
    q2: ``,
    q3: [],
    option: [` 9%`, ` 13%`, ` 26%`, `38% `, `57% `],
    optionStyleType: `st-lower-alpha`,
    answer: [2],
    ansText: `Rationale: The percentage of men who had bilateral sural nerve grafting and demonstrated full erections (capable of penetration) was 26%. `,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: ` Sural nerve grafts are placed:`,
    q2: ``,
    q3: [],
    option: [
      ` End to end on the ipsilateral side from the tumor.`,
      ` Above the bladder neck and below the pubic arch.`,
      `In reverse to the natural position (proximal to distal and distal to proximal). `,
      ` In a circle to enhance nerve growth factor release.`,
      ` Next to the prostatectomy specimen in the pelvis until it is time for anastomosis.`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [2],
    ansText: `Rationale: Sural nerve grafts are placed in reverse to the natural position (proximal to distal and distal to proximal). `,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: ` Which complication has changed dramatically with experience with salvage prostatectomy?`,
    q2: ``,
    q3: [],
    option: [
      `Overall urinary incontinence. `,
      `Potency. `,
      ` Blood loss.`,
      ` Rectal injury.`,
      ` Stricture rate.`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [3],
    ansText: `Rationale: Only rectal injury rates have dramatically changed. `,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `Concerning postoperative neurapraxia, which of the following statements is TRUE? `,
    q2: ``,
    q3: [],
    option: [
      `The literature supports that it is almost always transient. `,
      ` It usually results in a motor deficit that is transient.`,
      `Most studies show that a self-limited neurapraxia occurs in approximately 25% of patients. `,
      `The same rates of neurapraxia tend to occur in retropubic prostatectomy as well. `,
      `This is a major source of morbidity and the reason many surgeons do not use this approach. `,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [0],
    ansText: `Rationale: Sensory neurapraxia of the lower extremity is reported to occur in approximately 2% of radical perineal prostatectomy cases. However, one study did report an incidence of 25%. This is reported significantly more often than with retropubic prostatectomy. True motor deficits are rare. Because of the transient nature, this is not a major source of morbidity.  `,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `Which of the following statements concerning rectal injury associated with perineal prostatectomy is FALSE? `,
    q2: ``,
    q3: [],
    option: [
      ` If unrecognized, it may result in the occurrence of a rectocutaneous or urethrocutaneous fistula.`,
      `Despite the close proximity of the rectum in the initial dissection, the incidence is fairly low. `,
      ` It can be avoided when an assistant places gentle downward pressure on the Lowsley tractor while the rectourethralis muscle is divided.`,
      `If repaired with a two-layer closure, most clinical sequelae are avoided. `,
      ` After repair with a two-layer closure, the operation can continue without a problem.`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [2],
    ansText: `Rationale: Traction on the Lowsley tractor during division of the rectourethralis muscle tents the rectum upward and increases the likelihood of injury. Traction should not be placed until after the rectourethralis muscle is divided. When unrecognized, a fistula may ensue. Although one report showed an incidence of rectal injury in 11% of cases, most series recognize an incidence of 1% to 5%. When the injury is recognized and repaired at the time of occurrence, the operation can continue without a problem.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: ` After repair with a two-layer closure, the operation can continue without a problem.`,
    q2: ``,
    q3: [],
    option: [
      ` The diet is rapidly advanced to a regular diet.`,
      `Most patients are discharged from the hospital by postoperative day 2. `,
      ` A rectal suppository is administered on a scheduled basis while in the hospital to minimize Foley catheter discomfort except in cases of intraoperative rectal injury.`,
      `a and b only. `,
      ` All of the above.`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [3],
    ansText: `Rationale: Postoperatively, the diet is advanced rapidly as tolerated, patients ambulate early, and the overwhelming majority of patients are discharged by the second postoperative day. However, rectal stimulation or manipulation is prohibited in the postoperative period.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `Which of the following statements concerning the technique of urethral anastomosis is TRUE? `,
    q2: ``,
    q3: [],
    option: [
      `The presence of the Lowsley retractor assists in identifying the membranous urethral stump for the initial placement of interrupted sutures. `,
      ` A running suture technique is advocated for a watertight anastomosis.`,
      ` The visualization of the anastomosis is difficult, one of the few disadvantages of the radical perineal prostatectomy.`,
      ` The sutures are interrupted in a tennis-racquet fashion.`,
      ` The indwelling Foley catheter is not passed until after the anterior vesicourethral anastomotic sutures are placed and tied down.`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [4],
    ansText: `Rationale: During placement of the anterior vesicourethral anastomotic sutures, a red rubber catheter is placed transurethrally and used to identify the membranous urethral stump and provide traction on the urethra to assist in placement of the sutures. The red rubber catheter is then removed, and the indwelling Foley catheter is then placed retrograde into the bladder. Simple interrupted sutures are placed for the anastomosis. A tennis-racquet technique is used for bladder neck reconstruction if necessary.  `,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
];
