var quiz = [
  {
    q: `Which of the following is true about low-risk prostate cancer? `,
    q2: ``,
    q3: [],
    option: [
      `The major concern is biological grade progression over time (from GG 1 to GG 2-5). `,
      `About 25% of patients harbor occult higher-grade cancer at diagnosis. `,
      `30% of middle-aged Caucasian men harbor some prostate cancer. `,
      `Most low-risk prostate cancers harbor significant genetic mutations. `,
      ` GG 1 cancer metastasizes in 3% to 5% of cases.`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [1],
    ansText: `Rationale: Grade progression over time occurs in 1% to 2% per year; this is much less of a concern than coexistent high-grade cancer. Fifty to sixty percent of middle-aged men have microfocal prostate cancer. Most low-risk cancers have a very low mutational burden. GG1 cancer is a non-metastasizing lesion; low-grade cancers in men with metastasis invariably have an underlying higher-grade cancer.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `In men with low-risk prostate cancer on active surveillance: `,
    q2: ``,
    q3: [],
    option: [
      `With long-term follow-up, local progression of disease resulting in outflow obstruction, retention, and hydronephrosis is common. `,
      ` Delayed treatment is less likely to be effective.`,
      `Approximately 40% will have a signal for treatment by 10 years. `,
      ` The likelihood of metastasis of low-grade prostate cancer is 0.5% to 5% at 15 years.`,
      ` A PSA above 10 is a significant risk factor for metastatic disease.`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [2],
    ansText: `Rationale: Local progression of cancer is rare. Delayed treatment in this cohort does not reduce effectiveness of therapy. In published series, 20% to 30% are treated by 5 years and 30% to 40% by 10 years. Metastasis occurs from higher-grade cancer (which may be occult). PSA is not a strong predictor for metastasis.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: ` Clinical parameters which predict for the likelihood of upgrading include:`,
    q2: ``,
    q3: [],
    option: [
      ` Extent of core involvement.`,
      ` Bilaterality.`,
      ` PSA density.`,
      ` Proportion of cores involved.`,
      ` All of the above.`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [4],
    ansText: `Rationale: These are all clinical parameters that predict for the likelihood of upgrading.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: ` Which of the following parameters should preclude active surveillance?`,
    q2: ``,
    q3: [],
    option: [
      ` Extensive GG1 disease.`,
      `High PSA density. `,
      `Baseline PSA &gt;10. `,
      ` Presence of any Gleason pattern 4.`,
      `None of the above. `,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [4],
    ansText: `Rationale: None of these parameters should exclude a patient from surveillance. Small amounts of pattern 4 may represent artefactual upgrading and is not an exclusion. `,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: ` The switch from active surveillance to watchful waiting should be based on:`,
    q2: ``,
    q3: [],
    option: [
      `More than 10 years stable on surveillance. `,
      `More than 2 successive negative biopsies and negative MRI. `,
      `An estimated life expectancy of &lt;5 to 7 years. `,
      `Presence of cardiovascular co-morbidity. `,
      ` Patient refuses further biopsies.`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [2],
    ansText: `Rationale: A patient refusing biopsy may still be followed actively with, for example, MRI.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: ` For patients on surveillance, the trigger for intervention should be:`,
    q2: ``,
    q3: [],
    option: [
      `Short PSA doubling time (&lt;3 years) or PSA velocity &gt;2.0/year. `,
      `Progression in lesion size or conspicuity on MRI. `,
      `Grade group progression. `,
      `Volume progression of GG 1. `,
      ` Tissue-based biomarker showing &gt;15% risk of high-grade cancer.`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [2],
    ansText: `Rationale: None of the other criteria have been demonstrated to predict for an adverse outcome with reliable accuracy.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: ` Most national guidelines (Cancer Care Ontario, AUA, ASCO) state which of the following regarding active surveillance?`,
    q2: ``,
    q3: [],
    option: [
      ` For low-risk disease, it is one of several recommended options.`,
      ` Patients should be followed with serial PSA, DRE, and biopsy.`,
      ` MRI is a useful diagnostic test in these patients and should be incorporated into routine clinical practice.`,
      ` Tissue-based biomarkers have a clear role in the low-risk patient in identifying those at risk.`,
      `Patients with intermediate risk disease should not be offered surveillance. `,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [1],
    ansText: `Rationale: It is THE recommended option for low-risk disease; MRI and biomarkers are not recommended routinely; and AS can be offered to selected intermediate-risk patients. `,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
];
