var quiz = [
    {
        q: ` Decisions regarding the benefit of prostate cancer treatment should be primarily rooted in:`,
        q2: ``,
        q3: [],
        option: [`life expectancy calculation of greater than 10 years. `, 
        ` the expertise of the managing physician.`, 
        `assessment of the risk of prostate cancer mortality relative to other competing risks for death over time. `, 
        `the prostate-specific antigen (PSA) level at time of diagnosis. `,
        `selection of candidates with low risk for metastatic progression. `,
],
        optionStyleType: `st-lower-alpha`,
        answer: [2],
        ansText: `Rationale: Evaluation of the relative benefit of prostate cancer treatment in the individual patient should be based upon a determination of the relative probability of prostate cancer metastatic progression and cancer-specific mortality, as compared to the risk of death from other causes, within the expected natural longevity of the patient. A number of tools are available for assessing the risk of prostate cancer progression including nomograms, predictive models, and long-term observational cohorts. Most of these are based upon biopsy characteristics (including Gleason score and disease volume), serum PSA, imaging characteristics, genomic markers, and metastatic staging, in combination, rather than individually. The optimal candidate likely to benefit from treatment is the individual who has a reasonable likelihood of metastatic progression within his lifetime, if not treated. A number of tools exist for predicting life expectancy on the basis of age, adjusted for baseline comorbidities. While a life expectancy of 10 years is often used as a benchmark for benefit from therapy, life expectancy should be considered within the context of disease aggressiveness and the likelihood of disease progression within 5, 10, 15 years and beyond.`,
        state: `notAnswered`,
        userAnswered: []
    ,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`        ,
        type: `MCSS`},
    {
        q: ` Appropriate candidate selection for prostate cancer treatment may be improved through:`,
        q2: ``,
        q3: [],
        option: [`use of validated comorbidity indices and life tables. `, 
        ` exclusion of men who are obese.`, 
        ` exclusion of men over the age of 70.`, 
        ` inclusion of men with high-risk disease features.`, 
        ` psychosocial assessments with validated instruments.`],
        optionStyleType: `st-lower-alpha`,
        answer: [0],
        ansText: `Rationale: The perception of longevity in clinical practice is often based solely upon age rather than comorbidity. Daskivich et al. have previously demonstrated that among men with low-risk prostate cancer diagnosed in the VAMC, treatment rates were higher for men with CCI ≥ 3 than those with age greater than 75 (54% vs. 16%), despite a much higher likelihood of other cause mortality within 10 years (70% vs. 24%). Additionally, among men in the SEER-Medicare database, aggressive treatment for men with less than 10 years life expectancy, based upon CCI, was dependent upon age, with 68% to 69% of men aged less than 75 receiving aggressive therapy compared to only 57% and 24% of those aged 75 to 79, or greater than or equal to 80. Similarly, Bratt et al. demonstrated that among men with high-risk prostate cancer in the National Prostate Cancer Register of Sweden, 50% of men aged less than 70 received radical treatment, as compared to only 10% of men aged 70 to 80, despite a 52% likelihood of 10-year longevity. Improvements in appropriate candidate selection for treatment, and secondarily survival benefit, can be achieved through age-adjusted assessment of longevity on the basis of validated comorbidity indices and life tables. `,
        state: `notAnswered`,
        userAnswered: []
    ,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`        ,
        type: `MCSS`},
    {
        q: `The instrument that considers comorbidities with prostate cancer patients in making predictions of 10-year longevity is the: `,
        q2: ``,
        q3: [],
        option: [`Kattan nomogram. `, 
        `PCPT calculator. `, 
        ` WHO Life Tables.`, 
        ` CAPRA score.`, 
        ` prostate cancer-specific Charlson Comorbidity Index (CCI).`],
        optionStyleType: `st-lower-alpha`,
        answer: [4],
        ansText: `Rationale: The most widely utilized scale of comorbidity is the CCI. The CCI was designed to weigh comorbidities in prediction of one-year mortality among inpatients, but ultimately has been shown to be a significant prognostic indicator in the treatment of many types of cancer. In 2011, Daskivich et al. created a prostate cancer-specific CCI (PCCI) weighting comorbidities to predict 10-year risk of mortality among prostate cancer patients. When adjusting for age, and applying the PCCI to men with prostate cancer in the Veteran’s Administration health care system (VAMC), segregated PCCI score at 0, 1–2, 3–4, 5–6, 7–9, and 10, the 10-year cumulative incidence of other cause mortality was 10%, 19%, 35%, 60%, 79%, and 99%, respectively.`,
        state: `notAnswered`,
        userAnswered: []
    ,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`        ,
        type: `MCSS`},
    {
        q: `Men with a high risk of metastatic progression or mortality within 10 years of diagnosis: `,
        q2: ``,
        q3: [],
        option: [`are not likely to be helped by active treatment. `, 
        ` are unlikely to develop symptoms of prostate cancer progression.`, 
        `may benefit from curative-intent treatment, regardless of age. `, 
        ` are most often more likely to die of competing risks.`, 
        ` should empirically be offered androgen deprivation.`],
        optionStyleType: `st-lower-alpha`,
        answer: [2],
        ansText: `Rationale: Longevity assessment must be contemplated within the context of cancer aggressiveness. Men with aggressive malignancies may benefit from diagnosis and treatment regardless of a shortened longevity, particularly if presenting at an advanced stage. In men with high-risk, poorly differentiated prostate cancer, within the SEER-Medicare dataset, when comparing cancer-specific survival, aggressive treatment resulted in mortality improvements of 11.3%, 7.9%, 8.6%, and 2.8% at 10-year follow-up for men with Charlson scores of 0, 1, 2, and 3+, respectively, and numbers needed to treat to prevent 1 cancer death at 10 years were 9, 13, 12, and 36 men. Lead time from diagnosis to symptoms and eventual cancer-related mortality is heavily influenced by Gleason score and tumor stage, and this suggests that the relevance of expected longevity in treatment decision-making must be framed within a temporal estimate of cancer progression and mortality risk. Men with a high risk of metastatic progression or mortality within 10 years of diagnosis should be considered for aggressive therapy despite the presence of one or more competing risks for mortality within the same time period. `,
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `Which of the following increases the risk of early urinary toxicity after external beam radiation therapy to the prostate? `,
        q2: ``,
        q3: [],
        option: [`Previous urinary tract infection `, 
        `Nocturia `, 
        ` History of hematospermia`, 
        ` Previous transurethral resection of prostate (TURP)`, 
        `Prior urethroplasty `],
        optionStyleType: `st-lower-alpha`,
        answer: [3],
        ansText: `Rationale: For men who have had a previous aggressive TURP for outlet obstruction, the risk of <b><i>urinary toxicity</i></b> may be higher in those that undergo radiotherapy, but the rates of long-term severe urinary symptoms may be lower. Delay of radiation for 6 to 8 weeks after TURP may reduce the risk of incontinence and bladder neck contracture. `,
        state: `notAnswered`,
        userAnswered: []
    ,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`,
	type: `MCSS`        ,
        type: `MCSS`},
    {
        q: `Decision regret in prostate cancer therapy selection is reduced by: `,
        q2: ``,
        q3: [],
        option: [`robotic surgery. `, 
        ` less aggressive therapy.`, 
        ` second-opinion consultation.`, 
        ` shared decision-making.`, 
        ` physician bias.`],
        optionStyleType: `st-lower-alpha`,
        answer: [3],
        ansText: `Rationale: Shared decision-making involves a collaborative process in which patients and clinicians make decisions together. Given the controversy surrounding the relative benefit of prostate cancer screening and treatment, shared decision-making, both with regard to PSA testing and prostate cancer treatment, has been strongly advocated by a number of governing bodies. This shared decision-making model has been adopted into guidelines on localized prostate cancer management supported by the AUA, ASTRO, and the SUO. More recently, consensus has been achieved regarding strategies for implementation of shared decision-making in clinical practice. In a recent multicenter, prospective, observational study of 454 men undergoing prostate cancer counseling and treatment, regardless of whether men expressed an initial desire to be actively or passively involved in decision-making or not, after treatment, men who perceived their involvement in decision-making as active were more well-informed with regard to the disease and expressed less decisional regret in follow-up after treatment. The available evidence suggests that interventions aimed at informing patients regarding the comparative effectiveness of prostate cancer management alternatives should include the influence of physician recommendations and family members’ desires on patient decision-making. The urologist’s recommendation for treatment, however, continues to have the most influence on the decision-making.  `,
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `The 2005 ISUP modifications in prostate cancer grading resulted in: `,
        q2: ``,
        q3: [],
        option: [`characterization of cribriform pattern as Gleason grade 4. `, 
        ` downward migration in Gleason score.`, 
        `characterization of intraductal variant as Gleason grade 3. `, 
        `limits on number of cancers deemed Gleason grade 5. `, 
        ` creation of Gleason grade groups.`],
        optionStyleType: `st-lower-alpha`,
        answer: [0],
        ansText: `Rationale: In 2005, the International Society of Urologic Pathology (ISUP) recommended against the use of patterns 1 and 2, leaving a shortened scoring scale of 6 to 10. Additionally, the consensus recommended that a number of variant patterns previously graded as 3, and all cribriform patterns, should be considered pattern 4. In doing so, there has been an observation of Gleason scoring migration, with a greater number of cancers designated as Gleason score 3+4 or 4+3, as compared to historical cohorts. This migration has led to a reassessment of the accuracy of Gleason scoring in contemporary practice, with most such evaluations demonstrating improved prognostic accuracy. While the grading system appears to be more prognostically accurate, it has created difficulty in comparing historical outcomes of treatment to contemporary cohorts, given the difference in what is meant by Gleason 3+3 and 3+4/4+3. `,
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: ` In its initial description, the UCSF-CAPRA score was able to widely discriminate:`,
        q2: ``,
        q3: [],
        option: [`risk of extraprostatic extension. `, 
        `likelihood of Gleason upgrade. `, 
        ` risk of mortality from competing causes.`, 
        `recurrence-free survival. `, 
        `response to adjuvant therapy. `],
        optionStyleType: `st-lower-alpha`,
        answer: [3],
        ansText: `Rationale: The UCSF-Cancer of the Prostate Risk Assessment (CAPRA) score was developed for predicting clinical outcomes using age, PSA level, clinical stage, biopsy Gleason score, and percentage of positive biopsy cores. In its initial description, the UCSF-CAPRA score was able to widely segregate risk from a 5-year recurrence free survival of 85% among low-risk to 8% among high-risk patients. This stratification scheme has subsequently been shown to additionally predict prostate-cancer-specific mortality independently of the treatment given.  `,
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: ` The Scandinavian Prostate Cancer Group Study Number 4, comparing radical prostatectomy and watchful waiting, demonstrated improved survival among men undergoing radical prostatectomy. The study was limited by:`,
        q2: ``,
        q3: [],
        option: [` predominant inclusion of indolent, low-risk disease.`, 
        ` high rates of death from competing causes.`, 
        ` increased age at time of accrual.`, 
        ` excessive complications from surgery.`, 
        ` primary enrollment in the pre-PSA era.`],
        optionStyleType: `st-lower-alpha`,
        answer: [4],
        ansText: `Rationale: SPCG-4 was the first to publish a randomized intention-to-treat analysis comparing watchful waiting and radical prostatectomy using informative clinical endpoints such as overall and cancer-specific survival. Furthermore, the SPCG-4 offered the long-term follow-up necessary to characterize between-group differences in survival and employed rigorous study design methods such as blinded histopathologic review. However, because this trial enrolled men predominantly during the pre-PSA era, nearly 90% of the 695 participants harbored palpable disease. Although a number of important observations regarding the comparative effectiveness of radical prostatectomy in the treatment of localized prostate can be made from the SPCG-4 data, this trial does not reflect current prostate cancer screening, detection, and treatment paradigms. `,
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: ` The PIVOT trial, comparing radical prostatectomy and watchful waiting, demonstrated no difference in survival among men undergoing radical prostatectomy or watchful waiting. The study was limited by:`,
        q2: ``,
        q3: [],
        option: [`predominant inclusion of indolent, low-risk disease. `, 
        `high rates of death from competing causes. `, 
        ` increased age at time of accrual.`, 
        `excessive complications from surgery. `, 
        ` primary enrollment in the pre-PSA era.`],
        optionStyleType: `st-lower-alpha`,
        answer: [1],
        ansText: `Rationale: The follow-up of the original PIVOT analysis was published in 2017, after 19.5 years of follow-up, demonstrating an absolute risk reduction (ARR) of 5.5% (95% confidence interval [CI]; −1.5% to 12.4%, <b><i>P</i></b> = .06) for all-cause mortality (61.3% vs. 66.8%) through prostatectomy. An ARR of 4.0% (95% CI; −0.2 to 8.3%, <b><i>P</i></b> = .06) was found for prostate cancer-specific mortality (7.4% vs. 11.4%). On subgroup analysis, surgery reduced all-cause mortality among men with intermediate-risk disease (ARR = 14.5%, 95% CI 2.8% to 25.6%). By contrast, no benefit was seen in the low- or high-risk groups. While surgery reduced the need for treatment of progressive disease, there were increased incidences of therapy-related long-term complications such as urinary incontinence and erectile and sexual dysfunction. One of the major concerns regarding the PIVOT study design was that the inclusion criterion for the study was life expectancy of greater than 10 year. However, according to the analysis of all-cause mortality after 10-year follow-up, nearly 40% of the study population had died, with only approximately 5% from prostate cancer. After 15 years, up to 60% had died, with ∼10% from prostate cancer. These considerations suggest poor risk assessment at baseline inclusion and lessen the impact of the study. Since the design of the study, it is now well understood that patients with low-risk prostate cancer and comorbidities do not benefit within 10 years from radical interventions. `,
        state: `notAnswered`,
        userAnswered: []
    ,
	type: `MCSS`,
	type: `MCSS`        ,
        type: `MCSS`},
    {
        q: ` The Prostate Testing for Cancer and Treatment (ProtecT) trial, a randomized trial of prostatectomy, external-beam radiation with androgen deprivation, or prostate-specific antigen–based active monitoring, demonstrated no difference in mortality between the three study groups at 10 years of follow-up. The study was limited by:`,
        q2: ``,
        q3: [],
        option: [`predominant inclusion of indolent, low-risk disease. `, 
        ` high rates of death from competing causes.`, 
        ` increased age at time of accrual.`, 
        ` excessive complications from surgery.`, 
        ` primary enrollment in the pre-PSA era.`],
        optionStyleType: `st-lower-alpha`,
        answer: [0],
        ansText: `Rationale: In the ProtecT trial, a total of 82,429 men 50 to 69 years of age received a PSA test; 2664 received a diagnosis of localized prostate cancer, and 1643 agreed to undergo randomization to active monitoring (545 men), surgery (553 men), or radiotherapy (plus 3 to 6 months androgen deprivation therapy, 545 men). The primary outcome was prostate-cancer mortality at a median of 10 years of follow-up. In total, 62% of eligible men accepted randomization, comprising a cohort with mostly low- to intermediate-risk tumors. The primary outcome of prostate cancer mortality was not different between the three arms at a median follow-up of 10 years. However, the incidence of metastases was higher in the active monitoring group. The majority of included patients had a low PSA and Gleason 6 tumors (grade group 1). As the chance of low-risk patients dying from prostate cancer within 10 years is very low, longer follow-up may be needed to draw firm conclusions. The mortality in the study was approximately 1% which is low in comparison to the predicted mortality of 15% at the time the study was designed, thereby reducing the power of the study to assess its intended purpose. `,
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: ` Whole-gland prostate ablation with high-intensity focused ultrasound is characterized by:`,
        q2: ``,
        q3: [],
        option: [`predominant inclusion of indolent, low-risk disease. `, 
        ` high rates of death from competing causes.`, 
        `increased age at time of accrual. `, 
        ` excessive complications from surgery.`, 
        ` primary enrollment in the pre-PSA era.`],
        optionStyleType: `st-lower-alpha`,
        answer: [0],
        ansText: ``,
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: ` Whole-gland prostate ablation with high-intensity focused ultrasound is characterized by:`,
        q2: ``,
        q3: [],
        option: [`demonstration of durable disease control at 15 to 20 years of follow-up. `, 
        ` rates of erectile dysfunction comparable to radical prostatectomy.`, 
        ` substantial requirement for re-treatment within 5 years.`, 
        ` higher rates of erectile dysfunction than cryoablation.`, 
        `urinary toxicity comparable to radiation therapy. `],
        optionStyleType: `st-lower-alpha`,
        answer: [2],
        ansText: `Rationale: The primary attraction of whole-gland ablation is the potential to preserve sexual and urinary function more frequently than radical prostatectomy or radiation therapy. While whole-gland cryoablation almost always results in erectile dysfunction, preservation of function with whole-gland high-intensity focused ultrasound (HIFU) is more common, but may vary with the aggressiveness and oncologic efficacy of the procedure. Additionally, the need for re-treatment is 29% to 38% with an increased rate of erectile dysfunction and stricture following a second treatment. As such, men considering whole-gland ablation by HIFU should be counseled with regard to the paucity of long-term outcomes and the potential need for re-treatment. `,
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: ` In risk assessment, the prostate MRI parameter most predictive of disease outcomes is:`,
        q2: ``,
        q3: [],
        option: [`T2-weighted signal attenuation. `, 
        `diffusion weighted image. `, 
        ` contrast wash-in.`, 
        `apparent diffusion coefficient (ADC). `, 
        ` hemorrhage on T1-weighted image.`],
        optionStyleType: `st-lower-alpha`,
        answer: [4],
        ansText: `Rationale: The apparent diffusion coefficient, measured on diffusion-weighted imaging, has been shown to correlate with clinical outcomes and thus can be used as a risk stratification tool. Recent data have explored the value of MRI in monitoring tumors in patients on an active surveillance protocol. In patients with low-risk, localized disease, tumor ADC on diffusion-weighted imaging (DWI) may be a useful marker of prostate cancer progression and may help to identify patients who stand to benefit from radical treatment. As a preoperative imaging tool, tumor ADC and PI-RADS may also be useful to predict biochemical recurrence after radical prostatectomy and radiation therapy. MRI data improves the prediction of biochemical failure within nomograms after external-beam radiation therapy. Pretreatment MRI findings have also been found to predict for biochemical recurrence in intermediate- and high-risk prostate cancer patients treated with combination brachytherapy and external-beam radiotherapy. `,
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `Initial risk stratification and staging workup for a man with newly diagnosed clinically localized intermediate risk prostate cancer (T2b, GG 2, PSA 8) includes: `,
        q2: ``,
        q3: [],
        option: [`imaging is not indicated in this patient. `, 
        ` cross-sectional abdominopelvic imaging.`, 
        ` bone scan and cross-sectional abdominopelvic imaging.`, 
        ` bone scan and cross-sectional abdominopelvic imaging only if a nomogram predicts greater than 10% probability of pelvic lymph node involvement.`, 
        ` bone scan, cross-sectional abdominopelvic imaging, and fluciclovine PET.`],
        optionStyleType: `st-lower-alpha`,
        answer: [3],
        ansText: `Rationale: bone scan and cross-sectional abdominopelvic imaging only if a nomogram predicts greater than 10% probability of pelvic lymph node involvement. Guidelines for initial diagnostic imaging in the newly diagnosed prostate cancer patient vary considerably. While most definitions support radionuclide bone scan for the initial staging of high-risk prostate cancer, not all specifically address imaging for soft tissue metastases. Those that do commonly endorse pelvic CT or MRI. Current NCCN guidelines recommend the use of technetium 99m bone scan and cross-sectional imaging (CT or MRI) among high-risk and unfavorable intermediate-risk men deemed to be at high risk for occult metastasis on the basis of clinical parameters or nomograms. In cases of equivocal bone scans, PET/CT or MRI have been endorsed by several professional organizations. `,
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    {
        q: `Prediction of seminal vesical invasion by prostate MRI is characterized by a high: `,
        q2: ``,
        q3: [],
        option: [`false-positive rate. `, 
        ` positive predictive value.`, 
        ` sensitivity.`, 
        ` negative predictive value.`, 
        `diagnostic accuracy. `],
        optionStyleType: `st-lower-alpha`,
        answer: [1],
        ansText: `Rationale: For identifying extraprostatic extension (EPE) or seminal vesical invasion (SVI), MRI is the only examination with sufficient accuracy to be used in clinical practice given its combination of both high spatial and contrast resolution. Historically, assessment for EPE on MRI was based on T2-weighted imaging (T2WI) which provides the best spatial resolution of the MR sequences typically employed. The identification of EPE on T2WI alone is dependent on the amount of EPE present. Gross extension or disruption of the capsule is highly predictive of EPE, but more subtle findings such as irregularity or bulging of the “capsule” have a lower predictive value. As such, when deemed positive for seminal vesical invasion, MRI is generally correct resulting in low rates of false-positive and high positive predictive value. In general, MRI is poor for the detection of focal ECE, as demonstrated by the majority of patients with ECE, resulting in poor sensitivity and low negative predictive value. More subtle findings, such as linear length of capsular contact at the region of suspicion, may improve the pre-treatment prediction of the likelihood of ECE. Accuracy for more subtle EPE is improved when T2WI is combined with diffusion-weighted imaging (DWI) or dynamic contrast enhanced (DCE) imaging primarily because these additional sequences improve dominant tumor localization, which in turn helps predict presence of EPE, however, uncertainty remains because these ancillary sequences have lower spatial resolution than T2WI.`,
        state: `notAnswered`,
        userAnswered: []
            ,
        type: `MCSS`},
    





];
