var quiz = [
  {
    q: `With laparoscopic/robotic prostatectomy, a continuous suture for the vesicourethral anastomosis: `,
    q2: ``,
    q3: [],
    option: [
      `avoids incontinence.`,
      ` has a high rate of bladder neck contracture.`,
      ` can be performed with the need for only a single knot.`,
      ` requires an indwelling catheter for at least 2 weeks.`,
      `eliminates the need for a pelvic drain. `,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [2],
    ansText: `Rationale: The vesicourethral anastomosis may be accomplished using either an interrupted closure or a running continuous suture with a single knot. `,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
    type: `MCSS`,
    type: `MCSS`,
    type: `MCSS`,
    type: `MCSS`,
    type: `MCSS`,
    type: `MCSS`,
  },
  {
    q: `With laparoscopic/robotic radical prostatectomy, positive margin rates are not influenced by: `,
    q2: ``,
    q3: [],
    option: [
      `surgical technique. `,
      ` patient selection.`,
      `the method of pathologic analysis. `,
      ` transperitoneal versus extraperitoneal exposure.`,
      ` tumor grade and stage.`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [3],
    ansText: `Rationale: Comparison of margin status between high-volume centers with the operations performed by experienced surgeons has shown no definitive advantage for one surgical approach over the other in achieving negative surgical margins.  `,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
    type: `MCSS`,
    type: `MCSS`,
    type: `MCSS`,
    type: `MCSS`,
    type: `MCSS`,
  },
  {
    q: ` Compared with open surgical approaches, laparoscopic/robotic prostatectomy has been consistently shown to decrease:`,
    q2: ``,
    q3: [],
    option: [
      `postoperative pain. `,
      `urinary incontinence. `,
      ` bleeding.`,
      ` erectile dysfunction.`,
      ` positive margins.`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [2],
    ansText: `Rationale: Because most of the blood loss that occurs during radical prostatectomy is from venous sinuses, the tamponade effect from the pneumoperitoneum helps diminish ongoing blood loss during laparoscopic robotic prostatectomy (LRP)/RALP. Blood loss of less than a few hundred milliliters is routinely reported. `,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `Positive surgical margins with laparoscopic/robotic prostatectomy: `,
    q2: ``,
    q3: [],
    option: [
      `decrease as technical experience is gained. `,
      ` are rare at the prostatic apex.`,
      ` occur only when extracapsular disease is present.`,
      `are seen most commonly at the prostate base. `,
      `can be avoided by using a robotic-assisted approach. `,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [0],
    ansText: `Rationale: In most series of LRP and RALP, positive margin percentages decrease as greater familiarity with the procedure is obtained.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
    type: `MCSS`,
    type: `MCSS`,
  },
  {
    q: `An advantage of extraperitoneal versus transperitoneal approach to laparoscopic/robotic prostatectomy is: `,
    q2: ``,
    q3: [],
    option: [
      `faster operating room time. `,
      ` shorter hospitalization.`,
      ` increased working space.`,
      `avoidance of bowel manipulation. `,
      ` fewer positive margins.`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [3],
    ansText: `Rationale: As the extraperitoneal technique avoids violation of the peritoneal envelope, bowel manipulation is avoided. It is for this reason that patients with extensive prior abdominal surgery can undergo successful laparoscopic and robotic prostatectomy by the extraperitoneal route.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `Minimally invasive pelvic lymph node dissection: `,
    q2: ``,
    q3: [],
    option: [
      `is difficult to perform along with robotic radical prostatectomy. `,
      ` should always be performed transperitoneally.`,
      ` has an increased risk of thromboembolic complication compared with open approaches.`,
      ` should only be performed for tumors lower than or equal to Gleason grade 7.`,
      `can allow lymph node removal comparable with open surgery. `,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [4],
    ansText: `Rationale: Pelvic lymphadenectomy can be performed by open or laparoscopic techniques with no significant difference in nodal yield.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
    type: `MCSS`,
    type: `MCSS`,
  },
  {
    q: `Pelvic lymphadenectomy can be performed by open or laparoscopic techniques with no significant difference in nodal yield. `,
    q2: ``,
    q3: [],
    option: [
      `is best avoided by antegrade release of the rectum from the posterior prostate. `,
      `is usually from trocar placement. `,
      ` can be avoided by bluntly dividing Denonvilliers fascia.`,
      `should be treated with an immediate diverting colostomy. `,
      `is often unrecognized and heals spontaneously. `,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [0],
    ansText: `Rationale: Thorough dissection of the rectum off of the posterior prostate is critical to minimize the risk of rectal injury during subsequent steps such as division of the urethra and dissection of the prostatic apex. With LRP and RALP, sharp and complete incision of the posterior layer of Denonvilliers fascia is necessary after seminal vesicle dissection to allow adequate mobilization of the rectum.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `Bleeding during laparoscopic/robotic radical prostatectomy is usually minimal because: `,
    q2: ``,
    q3: [],
    option: [
      `Bleeding during laparoscopic/robotic radical prostatectomy is usually minimal because: `,
      ` the dorsal vein complex does not have to be divided.`,
      `the pneumoperitoneum tamponades venous bleeding. `,
      `suturing is easier than with open surgery. `,
      ` the Trendelenburg position decreases venous pressure.`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [2],
    ansText: `Rationale: Because most of the blood loss that occurs during radical prostatectomy is from venous sinuses, the tamponade effect from the pneumoperitoneum helps diminish ongoing blood loss during LRP/RALP. Blood loss of less than a few hundred milliliters is routinely reported.  `,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `Robotic assistance with laparoscopy is most useful in: `,
    q2: ``,
    q3: [],
    option: [
      `trocar insertion and removal. `,
      `maintaining a steady insufflation pressure. `,
      ` decreasing operating room costs.`,
      `facilitating suturing. `,
      ` eliminating the need for a tableside assistant.`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [3],
    ansText: `Rationale: Most surgeons, however, believe that the robotic technology significantly facilitates suturing (especially for the vesicourethral anastomosis) and other aspects of the surgical dissection.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `The neurovascular bundle lies within which two periprostatic fascial planes? `,
    q2: ``,
    q3: [],
    option: [
      ` Prostate capsule and prostatic fascia.`,
      `Prostate capsule and levator fascia. `,
      `Prostatic fascia and levator fascia. `,
      ` Denonvilliers fascia and prostate capsule.`,
      `Denonvilliers fascia and endopelvic fascia. `,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [2],
    ansText: `Rationale: The neurovascular bundle travels between two distinct fascial planes that surround the prostate, namely, the prostatic fascia and levator fascia. `,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: ` Antegrade laparoscopic dissection of the prostate results in less blood loss as compared with the retrograde approach due in part to:`,
    q2: ``,
    q3: [],
    option: [
      `early division of the dorsal venous complex and prostatic pedicles. `,
      `early division of the prostatic pedicles and late division of the dorsal venous complex. `,
      `less tissue manipulation. `,
      ` better visualization.`,
      `late division of the dorsal venous complex and prostatic pedicles. `,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [1],
    ansText: `Rationale: Because the dorsal venous complex is divided early in the operation and the prostatic pedicles late, there is potentially a greater risk of ongoing bleeding with the retrograde technique. In contrast, during the antegrade neurovascular bundle dissection, the arterial blood supply to the prostate (via the prostatic pedicles) is divided early and the dorsal venous complex is divided near the end of the operation, thus reducing blood loss during the operation. `,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
    type: `MCSS`,
  },

  {
    q: `The higher cost of laparoscopic/robotic-assisted as compared with open radical prostatectomy is mostly a consequence of: `,
    q2: ``,
    q3: [],
    option: [
      `higher blood loss and transfusion rates. `,
      ` a higher complication rate.`,
      ` a longer operative time and disposable equipment.`,
      `longer hospital stays. `,
      ` higher surgical and anesthesia charges.`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [2],
    ansText: `Rationale: In the study by Link and colleagues (2004), the factors that most influenced overall cost in order of importance included operative time, length of hospital stay, and consumable items (e.g., disposable laparoscopic equipment and trocars). `,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },

  {
    q: ` As a consequence of the CO<sub>2</sub> pneumoperitoneum used during minimally invasive prostatectomy, the anesthesia team must be most aware of the potential for:`,
    q2: ``,
    q3: [],
    option: [
      `bleeding and hypotension. `,
      `hypoxia and acidosis. `,
      `tachycardia and hypertension. `,
      `bradycardia and hypotension. `,
      `hypercarbia and oliguria. `,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [4],
    ansText: `Rationale: The anesthesiologist must be aware of the potential consequences of CO<sub>2</sub> insufflation and pneumoperitoneum including oliguria and hypercarbia. `,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },

  {
    q: ` Positive margins at the prostatic apex:`,
    q2: ``,
    q3: [],
    option: [
      `are more common with the robotic-assisted technique as compared with open surgery. `,
      ` can occur due to protrusion of the posterior prostatic apex beneath the urethra.`,
      ` can occur more commonly with retrograde versus antegrade dissection of the prostate.`,
      `are less common in laparoscopic versus open surgery. `,
      ` are less common than at the prostatic base.`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [2],
    ansText: `Rationale: Before division of the posterior urethra, great care must be taken to inspect the contour of the posterior prostatic apex. In some patients, the posterior prostatic apex can protrude beneath the urethra, resulting in an iatrogenic positive margin if not identified.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `Men who are not candidates for laparoscopic/robotic-assisted laparoscopic radical prostatectomy include those with: `,
    q2: ``,
    q3: [],
    option: [
      ` palpable tumors.`,
      ` palpable tumors.`,
      ` morbid obesity.`,
      ` uncorrectable bleeding diatheses.`,
      ` prior neoadjuvant hormonal therapy.`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [3],
    ansText: `Rationale: Contraindications to minimally invasive laparoscopic prostatectomy include uncorrectable bleeding diatheses or the inability to undergo general anesthesia due to severe cardiopulmonary compromise.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: ` The following are true about robotic salvage prostatectomy except:`,
    q2: ``,
    q3: [],
    option: [
      `Higher risk of rectal injury than standard robotic-assisted laparoscopic prostatectomy (RALP). `,
      `Higher risk of urinary incontinence than standard RALP. `,
      `Need to rule out metastatic disease prior to performing. `,
      `Should be attempted early in one’s experience. `,
      ` The Foley catheter should be left in place longer than with a standard RALP.`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [3],
    ansText: `Rationale: These cases are perhaps best performed in high-volume centers by experienced robotic surgeons, as they can be very challenging with a higher risk of intraoperative and postoperative complications.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
];
