var quiz = [
  {
    q: ` Most immunodetectable prostate-specific antigen (PSA) in serum is bound to which of the following?`,
    q2: ``,
    q3: [],
    option: [
      `Albumin. `,
      `α<sub>1</sub>-Antichymotrypsin (ACT)..`,
      `α<sub>2</sub>-Macroglobulin (MG). `,
      ` Human kallikrein.`,
      ` Globulin`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [1],
    ansText: `Rationale: Most detectable PSA in sera (65% to 90%) is bound to ACT.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
    type: `MCSS`,
  },
  {
    q: ` Serum PSA levels vary with which factor?`,
    q2: ``,
    q3: [],
    option: [
      `Age. `,
      ` Race.`,
      ` Prostate volume.`,
      `ACT concentration. `,
      ` Age, race, and prostate volume.`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [4],
    ansText: `Rationale: In the absence of prostate cancer, serum PSA levels vary with age, race, and prostate volume.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
    type: `MCSS`,
    type: `MCSS`,
    type: `MCSS`,
    type: `MCSS`,
    type: `MCSS`,
    type: `MCSS`,
    type: `MCSS`,
  },
  {
    q: ` Serum PSA elevations may occur with prostate:`,
    q2: ``,
    q3: [],
    option: [
      ` manipulation.`,
      ` cancer.`,
      `enlargement. `,
      `inflammation. `,
      ` all of the above.`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [4],
    ansText: `Rationale: Serum PSA elevations may occur as a result of disruption of the normal prostatic architecture that allows PSA to diffuse into the prostatic tissue and gain access to the circulation. This can occur in the setting of prostate disease (benign prostatic hyperplasia [BPH], prostatitis, and prostate cancer) and with prostate manipulation (prostate massage, prostate biopsy). The presence of prostate disease (prostate cancer, BPH, and prostatitis) is the most important factor affecting serum levels of PSA. PSA elevations may indicate the presence of prostate disease, but not all men with prostate disease have elevated PSA levels. Furthermore, PSA elevations are not specific for cancer.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `Which of the following should be recommended for an elevated PSA? `,
    q2: ``,
    q3: [],
    option: [
      ` Repeat the measurement after cystoscopy.`,
      `Give a 2-week course of fluoroquinolones, then repeat PSA. `,
      ` Give a 4-week course of doxycycline, then repeat PSA.`,
      ` Repeat the PSA measurement after a period of observation.`,
      `All of the above. `,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [3],
    ansText: `Rationale: The American Urological Association does not recommend giving empiric antibiotics for an elevated PSA. Manipulation of the urinary tract such as cystoscopy can lead to PSA elevations. Repeating an abnormal test after a period of observation is a good practice. `,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
    type: `MCSS`,
    type: `MCSS`,
    type: `MCSS`,
  },
  {
    q: `Which of the following represent ways to adjust the PSA measurement? `,
    q2: ``,
    q3: [],
    option: [
      ` PSA density.`,
      ` PSA velocity.`,
      `PSA transition zone density. `,
      ` Percent free PSA.`,
      `All the above. `,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [4],
    ansText: `Rationale: Many different variations on the PSA test have been proposed to improve specificity. These include dividing by total prostate volume (PSA density) or volume of the transition zone (PSA transition zone density), examining changes over time (PSA velocity), and determining the proportion circulating in the free form (percent free PSA). `,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: ` A 60-year-old man taking finasteride (Proscar) for 2 years with a PSA value of 4 ng/mL would most likely, if he were not taking finasteride, have which PSA value?`,
    q2: ``,
    q3: [],
    option: [` 2 ng/mL`, `6 ng/mL `, ` 8 ng/mL`, ` 12 ng/mL`, `4 ng/mL `],
    optionStyleType: `st-lower-alpha`,
    answer: [2],
    ansText: `Rationale: Finasteride (a 5α-reductase inhibitor for treatment of BPH) at 5 mg has been shown to lower PSA levels by approximately 50% after 12 months of treatment. Thus, one can multiply the PSA level by 2 to obtain the “true” PSA level of a patient who has been taking finasteride for 12 months or more. After 2 and 7 years of finasteride therapy, the PSA level should be multiplied by a factor of 2.3 and 2.5, respectively. Men who are to be treated with finasteride should have a baseline PSA measurement before initiation of treatment and should be followed with serial PSA measurements. If there is a rise in the PSA value when the patient is taking finasteride, these men should be suspected of having an occult prostate cancer. `,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
    type: `MCSS`,
    type: `MCSS`,
  },
  {
    q: ` Which of the following tests has the highest positive predictive value for prostate cancer?`,
    q2: ``,
    q3: [],
    option: [
      ` PSA is the single test with the highest positive predictive value for cancer. `,
      ` Digital rectal exam (DRE).`,
      ` Transrectal ultrasonography (TRUS).`,
      ` Combination of DRE and TRUS.`,
      `Human glandular kallikrein (hK2). `,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [0],
    ansText: `Rationale: PSA is the single test with the highest positive predictive value for cancer.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
    type: `MCSS`,
    type: `MCSS`,
  },
  {
    q: ` Which of the following statements about prostate cancer staging is FALSE?`,
    q2: ``,
    q3: [],
    option: [
      `A goal of staging is to predict prognosis. `,
      ` Staging facilitates the selection of rational therapy based on predicted extent of disease.`,
      `Imaging can accurately identify all cases of pelvic lymph node metastases. `,
      ` PSA and DRE are components of the staging evaluation.`,
      `Pelvic lymphadenectomy is the gold standard for the detection of pelvic lymph node metastases. `,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [2],
    ansText: `Rationale: The goals in staging of prostate cancer are twofold: (1) to predict prognosis and (2) to rationally select therapy based on predicted extent of disease. `,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: ` The currently available modalities for assessing disease extent in men with prostate cancer include:`,
    q2: ``,
    q3: [],
    option: [
      `DRE. `,
      `serum PSA. `,
      `histologic grade. `,
      `bone scan. `,
      ` all of the above.`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [4],
    ansText: `Rationale: The currently available modalities for assessing disease extent in men with prostate cancer include DRE, serum tumor markers, histologic grade, radiographic imaging, and pelvic lymphadenectomy. `,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `Pathologic staging is superior to clinical staging because all the following factors are confirmed in the final pathologic examination EXCEPT: `,
    q2: ``,
    q3: [],
    option: [
      `PSA. `,
      `surgical margin status. `,
      ` seminal vesicle involvement.`,
      `tumor volume. `,
      ` capsular penetration.`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [0],
    ansText: `Rationale: Pathologic staging is more useful than clinical staging in the prediction of prognosis because tumor volume, surgical margin status, extent of extracapsular spread, and involvement of seminal vesicles and pelvic lymph nodes can be determined. `,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: ` What pathologic finding or findings at radical prostatectomy are highly predictive of the presence of occult metastatic disease?`,
    q2: ``,
    q3: [],
    option: [
      `Positive surgical margins. `,
      ` Seminal vesicle involvement.`,
      `Lymph node involvement. `,
      ` Both b and c.`,
      ` Both a and b.`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [3],
    ansText: `Rationale: The finding of seminal vesicle invasion or lymph node metastases on pathologic evaluation after radical prostatectomy is associated with a high risk of distant disease.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `In 2017, which group recommends shared decision making about PSA screening? `,
    q2: ``,
    q3: [],
    option: [
      ` United States Preventive Services Task Force.`,
      `American Urological Association. `,
      `American Cancer Society. `,
      ` European Association of Urology.`,
      ` All of the above.`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [4],
    ansText: `Rationale: All of these groups recommend shared decision making or a discussion of risks and benefits between the patient and provider about PSA screening.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: ` As general guidelines regarding PSA levels and pathologic stage, which of the following statements is TRUE?`,
    q2: ``,
    q3: [],
    option: [
      `Twenty-five percent of men with a PSA value less than 4 ng/mL have organ-confined disease. `,
      ` One hundred percent of men with a PSA value greater than 50 ng/mL have pelvic lymph node involvement.`,
      `Ten percent of men with a PSA value greater than 10 ng/mL have extraprostatic extension. `,
      ` Serum PSA has no predictive value for staging.`,
      `Seventy percent or more of men with a PSA value between 4 and 10 ng/mL have organ-confined disease. `,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [4],
    ansText: `Rationale: As a general guideline, the majority of men (80%) who have prostate cancer with PSA values less than 4 ng/mL have pathologically organ-confined disease, two-thirds of men with PSA levels between 4 and 10 ng/mL have organ-confined cancer, and more than 50% of men with PSA levels more than 10 ng/mL have disease beyond the prostate. Pelvic lymph node involvement is found in nearly 20% of men with PSA levels greater than 20 ng/mL and in most men (75%) with serum PSA levels greater than 50 ng/mL. `,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `With respect to the grade groups, all of the following statements are TRUE EXCEPT: `,
    q2: ``,
    q3: [],
    option: [
      ` Grade groups range from 1 to 5.`,
      ` Gleason 3 + 3 disease is considered grade group 1.`,
      ` Gleason 4 + 5 = 9 disease is considered grade group 5.`,
      ` Gleason 4 + 4 disease is considered grade group 3.`,
      `Gleason 4 + 3 disease is considered grade group 3. `,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [3],
    ansText: `Rationale: The new grade groups of 1 to 5 represent Gleason scores of ≤6, 3 + 4, 4 + 3, 8 and 9 to 10). Thus, Gleason 4 + 3 is considered grade group 3 and Gleason 4 + 4 is considered grade group 4.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `Which of the following variables are used to predict pathologic stage in the Partin tables? `,
    q2: ``,
    q3: [],
    option: [
      `PSA. `,
      ` Number of positive biopsy cores.`,
      `Gleason score. `,
      ` Clinical stage.`,
      `a, c, and d are all correct. `,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [4],
    ansText: `Rationale: The “Partin tables” are probability tables for the determination of pathologic stage that are based on three parameters: preoperative clinical stage, serum PSA level, and Gleason sum. In the Partin tables, numbers within the nomogram represent the percent probability of having a given final pathologic stage based on logistic regression analyses for all three variables combined; dashes represent data categories in which insufficient data existed to calculate a probability. This information is useful in counseling men with newly diagnosed prostate cancer with respect to treatment alternatives and probability of complete eradication of tumor. `,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `A 55-year-old man with a family history of prostate cancer had a 12-core prostate biopsy 1 year ago for a PSA of 2.6 ng/mL. Currently his PSA is 2.7 ng/mL and his DRE reveals a smooth soft minimally enlarged prostate with no nodules or firm areas. Prostate magnetic resonance imaging (MRI) is obtained and is depicted in <a class="lightboxcallout" img-ref="image_fig_152_1" href="28444d23c68f49eaaa4831e4c56b979e">Fig. 152.1A</a>: T2-weighted axial image of the prostate; <a class="lightboxcallout" img-ref="image_fig_152_1" href="28444d23c68f49eaaa4831e4c56b979e">Fig. 152.1B</a>: diffusion-weighted image of panel A; and <a class="lightboxcallout" img-ref="image_fig_152_1" href="28444d23c68f49eaaa4831e4c56b979e">Fig. 152.1C</a>: dynamic contrast enhancement image of 1A. The patient should be:`,
    q2: ``,
    q3: [],
    option: [
      ` reassured and scheduled for yearly PSA and rectal examination.`,
      `sent back to his primary care physician for follow-up. `,
      ` scheduled for a directed prostate biopsy.`,
      ` scheduled for a saturation biopsy.`,
      `followed with a PSA every 4 months and an MRI in a year. `,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [2],
    ansText: `Rationale: The T2-weighted image (<a href="28444d23c68f49eaaa4831e4c56b979e">Fig. 152.1A</a>) shows a well-demarcated low-signal-intensity area in the left peripheral zone with likely extracapsular extension. The diffusion-weighted image (B) shows restricted diffusion (dark area) in the same location as the abnormality seen in A and the dynamic contrast enhanced image (C) shows rapid uptake and loss of contrast (red area) in the same location of the abnormal left peripheral zone seen in A. These findings are highly suggestive of prostate cancer. The patient should have a directed biopsy to this area.  `,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
];
