var quiz = [
  {
    q: `The effectiveness of estrogen as a hormone therapy for prostate cancer is primarily based on:`,
    q2: ``,
    q3: [],
    option: [
      `<!--a. -->direct cytotoxic effects of estrogen on prostate cancer cells.`,
      `<!--b. -->competitive binding of estrogen to the androgen receptor.`,
      `<!--c. -->inhibition of the conversion of cholesterol to pregnenolone.`,
      `<!--d. -->desensitizing luteinizing hormone–releasing hormone (LHRH) receptors in the anterior pituitary.`,
      `<!--e. -->negative feedback on luteinizing hormone (LH) secretion by the pituitary.`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [4],
    ansText: `Rationale: After the success of surgical castration in treating prostate cancer, the first central inhibition of the hypothalamic-pituitary-gonadal axis exploited the potent negative feedback of estrogen on LH secretion. <b>Estradiol is a 1000-fold more potent at suppressing LH and follicle-stimulating hormone (FSH) secretion by the pituitary compared with testosterone.</b> Although estrogen has some direct cytotoxic effects on prostate cancer cells, this is not its primary mode of action. <b>All antiandrogens competitively bind to the androgen receptor. Aminoglutethimide inhibits the conversion of cholesterol to pregnenolone, an early step in steroidogenesis. The LHRH agonists desensitize LHRH receptors in the anterior pituitary.</b>`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
    type: `MCSS`,
    type: `MCSS`,
    type: `MCSS`,
  },
  {
    q: `The expected response of a man to the administration of the nonsteroidal antiandrogens is:`,
    q2: ``,
    q3: [],
    option: [
      `<!--a. -->LH increases, testosterone decreases, estrogen decreases.`,
      `<!--b. -->LH increases, testosterone increases, estrogen decreases.`,
      `<!--c. -->LH increases, testosterone increases, estrogen increases.`,
      `<!--d. -->LH decreases, testosterone decreases, estrogen increases.`,
      `<!--e. -->LH decreases, testosterone increases, estrogen increases.`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [2],
    ansText: `Rationale: <b>Unlike the steroidal antiandrogens, such as cyproterone acetate, which have central progestational inhibitory effects, the nonsteroidal antiandrogens simply block androgen receptors, including those in the hypothalamic-pituitary axis.</b> Because those central androgen receptors no longer sense the normal negative feedback exerted by testosterone, both LH levels and—as the normal testicular response to increased LH—testosterone levels increase. <b>Peripheral conversion of this excessive testosterone also increases estrogen levels, leading to the gynecomastia and mastodynia associated with the nonsteroidal antiandrogens.</b>`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
    type: `MCSS`,
    type: `MCSS`,
    type: `MCSS`,
  },
  {
    q: `All of the following therapeutic approaches for androgen axis blockade are in current clinical use, EXCEPT:`,
    q2: ``,
    q3: [],
    option: [
      `<!--a. -->inhibition of androgen synthesis.`,
      `<!--b. -->blocking androgen action by binding to the androgen receptor in a competitive fashion.`,
      `<!--c. -->ablating the source of androgens.`,
      `<!--d. -->direct inhibition of androgen receptor–mediated pathways.`,
      `<!--e. -->inhibition of LHRH and LH release.`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [3],
    ansText: `Rationale: There are four therapeutic approaches for androgen axis blockade in current clinical use. All current forms of ADT function by reducing the ability of androgen to activate the androgen receptor, whether through lowering levels of androgen or by blocking androgen–androgen receptor binding. <b>Therefore, the androgen receptor is not directly affected by ADT, leading many to hypothesize that hormone-refractory prostate cancer is a reactivation of androgen receptor–mediated pathways.</b>`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
    type: `MCSS`,
    type: `MCSS`,
    type: `MCSS`,
    type: `MCSS`,
    type: `MCSS`,
    type: `MCSS`,
  },
  {
    q: `Nonsteroidal antiandrogens:`,
    q2: ``,
    q3: [],
    option: [
      `<!--a. -->do not act as agonists for prostate cancer cells when used in combination with LHRH agonists.`,
      `<!--b. -->allow long-term maintenance of erectile function and sexual activity at rates similar to men undergoing surgical castration.`,
      `<!--c. -->commonly induce gastrointestinal toxicity, manifest as constipation leading, on occasion, to fecal impaction.`,
      `<!--d. -->have pancreatic toxicity, ranging from reversible mild to fulminant, life-threatening suppurative pancreatitis, and require periodic monitoring of serum amylase and lipase.`,
      `<!--e. -->cause fluid retention and thromboembolism in the majority of patients.`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [1],
    ansText: `Rationale: By blocking testosterone feedback centrally, the nonsteroidal antiandrogens cause LH and testosterone levels to increase, allowing antiandrogen activity without inducing hypogonadism and potency can be preserved. In clinical trials specifically examining erectile function and sexual activity in men on antiandrogen monotherapy, however, long-term preservation of those domains was 20% and not significantly different from that in men undergoing surgical castration. <b>All antiandrogens can act agonistically on prostate cancer cells and, when used in combination with LHRH agonists, withdrawal of the antiandrogen can lead to declines in PSA and even objective responses.</b> The common gastrointestinal toxicity is diarrhea, most often seen with flutamide. Liver toxicity, ranging from reversible hepatitis to fulminant hepatic failure, is associated with all nonsteroidal antiandrogens and requires periodic monitoring of liver function tests. The steroidal antiandrogen cyproterone acetate is associated with fluid retention and thromboembolism.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
    type: `MCSS`,
    type: `MCSS`,
  },
  {
    q: `Which of the following nonsteroidal antiandrogens is associated with interstitial pneumonitis and a delayed adaptation to darkness after exposure to bright illumination?`,
    q2: ``,
    q3: [],
    option: [
      `<!--a. -->Bicalutamide`,
      `<!--b. -->Flutamide`,
      `<!--c. -->Hydroxyflutamide`,
      `<!--d. -->Nilutamide`,
      `<!--e. -->Cyproterone acetate`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [3],
    ansText: `Rationale: About one quarter of men on nilutamide therapy will note a delayed adaptation to darkness after exposure to bright illumination, and in approximately 1% of patients, nilutamide is also associated with interstitial pneumonitis, which can progress to pulmonary fibrosis. Hydroxyflutamide is the active metabolite of flutamide. Cyproterone acetate is a steroidal antiandrogen.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `Which of the following statements is TRUE concerning LHRH agonists?`,
    q2: ``,
    q3: [],
    option: [
      `<!--a. -->Based on a review of 24 trials, involving more than 6600 patients, survival after therapy with an LHRH agonist was significantly better than after surgical castration.`,
      `<!--b. -->Although depot preparations and osmotic pump devices allow dosing to extend from 28 days to 1 year, the most effective dosing regimen is daily.`,
      `<!--c. -->Potential side effects of LHRH agonist therapy include an initial rise in serum testosterone, hot flushes, osteoporosis, and decreased insulin sensitivity.`,
      `<!--d. -->Widespread use of orally effective LHRH agonists has been limited by severe allergic reactions in some patients, even after previously uneventful treatment.`,
      `<!--e. -->The use of LHRH agonists is limited to combined androgen blockade.`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [3],
    ansText: `Rationale: <b>The LHRH agonists exploit the desensitization of LHRH receptors in the anterior pituitary following chronic exposure to LHRH, thereby shutting down the production of LH and, ultimately, testosterone.</b> Analogues of native LHRH increase their potency and half-lives. <b>The initial flare in LH and testosterone may last 10 to 20 days, and co-administration of an antiandrogen is required for only 21 to 28 days.</b> Survival after therapy with an LHRH agonist was equivalent to that for orchiectomy. The clinical utility of the first LHRH agonists was hampered by their short half-lives, requiring daily dosing. The LHRH antagonist abarelix has been associated with severe allergic reactions: All LHRH agonists are administered either IM or subcutaneously. LHRH can be used without combination with an antiandrogen.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `Each of the following has been associated with a favorable initial response to androgen deprivation therapy (ADT), EXCEPT:`,
    q2: ``,
    q3: [],
    option: [
      `<!--a. -->the magnitude of the PSA decline.`,
      `<!--b. -->the rapidity of the PSA decline.`,
      `<!--c. -->the PSA doubling time before initiating ADT.`,
      `<!--d. -->the Gleason score of the primary tumor.`,
      `<!--e. -->the maintenance of a detectable PSA.`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [4],
    ansText: `Rationale: The odds ratio of progressing to androgen-refractory progression at 24 months after starting ADT was 15-fold higher in those who did not achieve an undetectable PSA. <b>The magnitude and rapidity of PSA decline, the pre-ADT PSA doubling time, and pretreatment testosterone levels are all associated with the ability to predict the response to ADT.</b> For each unit increase in Gleason score, the cumulative hazard of castration-resistant progression was nearly 70%.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `Which of the following statements about the complications of ADT is TRUE?`,
    q2: ``,
    q3: [],
    option: [
      `<!--a. -->Most men undergoing ADT have normal bone mineral density before initiating therapy, and it usually takes at least a decade of treatment before the average man will develop osteopenia.`,
      `<!--b. -->Hot flashes occur in about one quarter of men on ADT but should always be treated because of the associated rare but life-threatening cardiovascular side effects.`,
      `<!--c. -->Erectile dysfunction after surgical castration or use of an LHRH is common but not inevitable: Although 1 in 5 men maintains some sexual activity, only 1 in 20 maintains high levels of sexual interest (libido).`,
      `<!--d. -->Because most men on ADT maintain lean muscle mass, the increase in weight is due to increases in adipose tissue.`,
      `<!--e. -->Gynecomastia and mastodynia are common with estrogenic compounds and antiandrogens but are effectively treated by external beam radiation after they occur.`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [2],
    ansText: `Rationale: The loss of sexual functioning is not inevitable with surgical or chemical castration, with up to 20% of men able to maintain some sexual activity. <b>Libido is more severely compromised, with approximately 5% maintaining a high level of sexual interest. More than half of men undergoing ADT meet the bone mineral density criteria for osteopenia or osteoporosis; it is estimated osteopenia will develop in the average man within 4 years of initiating ADT.</b> Hot flashes are among the most common side effects of ADT, affecting between 50% and 80% of patients. Hot flashes should be treated only in those who find them bothersome. <b>Loss of muscle mass and increase in percent fat body mass are common in men undergoing ADT. Prophylactic radiation therapy (10 Gy) has been used to prevent or reduce gynecomastia and mastodynia, but it has no benefit once these side effects have already occurred.</b>`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `Which of the following statements about the combination of 3 months of neoadjuvant ADT before radical prostatectomy is TRUE?`,
    q2: ``,
    q3: [],
    option: [
      `<!--a. -->Positive surgical margin rates are significantly reduced with ADT-treated patients.`,
      `<!--b. -->There is a significant reduction in biochemical (PSA) progression with ADT-treated patients.`,
      `<!--c. -->The benefit of neoadjuvant ADT appears to be in men with locally advanced disease and/or those with high-grade disease.`,
      `<!--d. -->Antiandrogen monotherapy has not shown a significant reduction of biochemical failure, but LHRH agonists have demonstrated this reduction.`,
      `<!--e. -->Although the results of prospective randomized studies of this combination are mixed, the overall body of evidence supports the use of ADT in this setting.`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [0],
    ansText: `Rationale: In both nonrandomized and randomized clinical trials, the pathologic positive surgical margin rate is significantly reduced. In one study, the positive surgical margin rate fell from nearly 50% in hormonally intact patients to 15% in ADT-treated patients. <b>Despite this improvement, there has not been a corresponding significant reduction in biochemical (PSA) progression in ADT-treatment patients, a finding in four separate prospective randomized studies. The benefit of ADT in men with locally advanced disease and/or high-grade disease has been in combination with external beam radiation therapy.</b> There is no evidence that any form of 3-month neoadjuvant ADT before radical prostatectomy reduces biochemical failure rates.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
    type: `MCSS`,
  },
  {
    q: `Combined androgen blockade:`,
    q2: ``,
    q3: [],
    option: [
      `<!--a. -->is designed to address the low levels of testicular androgens remaining after the use of LHRH agonists or antagonists.`,
      `<!--b. -->typically uses an antiandrogen at the time of PSA rise after treatment with an LHRH agonist.
         `,
      `<!--c. -->has not shown a survival advantage compared with an LHRH agonist alone.`,
      `<!--d. -->significantly benefits men with minimally metastatic disease when used in combination with surgical castration.`,
      `<!--e. -->using cyproterone acetate has a slightly worse outcome.`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [4],
    ansText: `Rationale: In studies of combined androgen blockade using the steroidal antiandrogen cyproterone acetate compared to LHRH agonists alone, the outcomes were slightly worse with the combination, suggesting increased non–prostate cancer deaths with this agent. Combined androgen blockade is designed to block the possible contribution of adrenal androgens to prostate cancer progression. Combined androgen blockade uses an antiandrogen along with an LHRH agonist: Addition of an antiandrogen at the time of PSA rise (evidence of hormone-refractory disease) is considered secondary hormonal manipulation. Several clinical trials have shown a slight but significant survival advantage for combined androgen blockade. <b>A landmark randomized clinical trial comparing surgical castration alone with surgical castration combined with flutamide did not show a significant benefit in men with minimal metastatic disease.</b>`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `Compared with deferred ADT, early ADT instituted before the development of objective metastatic disease:`,
    q2: ``,
    q3: [],
    option: [
      `<!--a. -->provides an overall survival advantage in all clinical disease states.`,
      `<!--b. -->has an equivalent quality of life.`,
      `<!--c. -->does not increase overall death rates.`,
      `<!--d. -->does not prevent the emergence of castration-resistant prostate cancer.`,
      `<!--e. -->should be offered to men with PSA recurrence after radical prostatectomy because of the rapid disease progression in this clinical setting.`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [3],
    ansText: `Rationale: The timing of the initiation of ADT has not prevented the development of castration-resistant prostate cancer. <b>Although early ADT may provide an overall survival advantage in certain clinical disease states, in most studies there is no significant overall survival advantage. Indeed, in localized, low-risk prostate cancer, early ADT is associated with an increase in overall death rates.</b> The natural history of disease progression after biochemical failure following radical prostatectomy is protracted: Median time to bone metastases is 10 years.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `In men with lymph-node metastatic prostate cancer discovered at the time of radical prostatectomy:`,
    q2: ``,
    q3: [],
    option: [
      `<!--a. -->significant overall survival benefits of immediate ADT are limited to those with extrapelvic positive nodes.`,
      `<!--b. -->a significant overall survival benefit of immediate ADT has been demonstrated in men who have also undergone subsequent radical prostatectomy.`,
      `<!--c. -->a significant overall survival benefit of immediate ADT has been demonstrated in men who have not undergone subsequent radical prostatectomy.`,
      `<!--d. -->b and c are correct.`,
      `<!--e. -->a, b, and c are correct.`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [1],
    ansText: `Rationale: A randomized prospective study of men with positive regional pelvic lymph nodes discovered at the time of radical prostatectomy showed an overall survival advantage to immediate ADT. In that study, all men also underwent the radical prostatectomy. A similar study, performed by the European Organisation for Research and Treatment of Cancer (EORTC) in men who did not undergo radical prostatectomy if positive nodes were discovered did not show a significant survival advantage to immediate ADT.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `From a strictly financial point of view, which of the following forms of ADT is the least expensive?`,
    q2: ``,
    q3: [],
    option: [
      `<!--a. -->Scrotal orchiectomy`,
      `<!--b. -->LHRH agonist`,
      `<!--c. -->Diethylstilbestrol (DES)`,
      `<!--d. -->Antiandrogen monotherapy`,
      `<!--e. -->LHRH antagonist`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [2],
    ansText: `Rationale: At a dose of 1 to 3 mg/day with no prophylactic breast irradiation, DES is the cheapest form of ADT. LHRH agonists would be cheaper than scrotal orchiectomy only if the patient lived a few months after the administration of ADT. Combined androgen blockade is the most expensive form of ADT.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `In a trial studying continuous ADT to intermittent ADT for men with rising PSA after radiation therapy:`,
    q2: ``,
    q3: [],
    option: [
      `<!--a. -->prostate cancer–specific death was more common in the continuous ADT arm.`,
      `<!--b. -->death unrelated to prostate cancer was more common in the intermittent ADT arm.`,
      `<!--c. -->attrition from the intermittent arm was rare throughout the cycles.`,
      `<!--d. -->duration of intermittent ADT progressively shortened over time.`,
      `<!--e. -->quality of life was not improved in the intermittent arm.`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [3],
    ansText: `Rationale: The duration of intermittent ADT progressively shortened over time: the median interval of the “off cycle” was 20.1 months for the first interval, 13.2 months for the second cycle, 9.1 months for the third, and 4 to 5 months thereafter. Disease-specific death (prostate cancer and related treatments) was more common in the intermittent-therapy arm compared to the continuous-therapy, 120 versus 94, respectively; conversely, deaths unrelated to prostate cancer were more common in the continuous-therapy arm compared with the intermittent-therapy arm, 162 versus 148, respectively. Attrition from intermittent androgen deprivation progressively increased over time as patients either developed castration-resistant prostate cancer or died of another cause. Attrition occurred in only 5% of men in the first interval, whereas 68% had stopped intermittent therapy by the third interval. A secondary end point, improved quality of life in the intermittent-therapy arm, was associated with significantly better scores for hot flashes, desire for sexual activity, and urinary symptoms.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
  {
    q: `There is general consensus that ADT should always be initiated in a hormonally intact patient in which of the following clinical settings?`,
    q2: ``,
    q3: [],
    option: [
      `<!--a. -->Before radical prostatectomy with a clinical T2 tumor.`,
      `<!--b. -->In all clinical stages of men undergoing external beam radiation therapy.`,
      `<!--c. -->In those with clinically localized prostate cancer who do not want local treatment.`,
      `<!--d. -->In those with symptomatic metastatic disease.`,
      `<!--e. -->In those with high-grade prostatic intraepithelial neoplasia (PIN) on needle biopsy who refuse a subsequent biopsy.`,
    ],
    optionStyleType: `st-lower-alpha`,
    answer: [3],
    ansText: `Rationale: In hormonally intact men with symptomatic metastatic prostate cancer, ADT is always indicated. There is no significant biochemical (PSA) disease-free advantage in men treated with neoadjuvant ADT. <b>The benefits of ADT in combination with external beam radiation therapy are in men with locally advanced and/or high-grade disease.</b> The use of ADT in men with low-risk, localized prostate cancer is associated with a significantly lower overall survival. There is no indication for ADT in the management of PIN.`,
    state: `notAnswered`,
    userAnswered: [],
    type: `MCSS`,
  },
];
